<s>
<W id="1" msd="SP" tag="IN" in="" out="">At</W>
<W id="2" msd="PD" tag="DT" in="" out="">the</W>
<W id="3" msd="ANP" tag="JJ" in="" out="">same</W>
<W id="4" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="5" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="6" msd="SP" tag="IN" in="" out="">in</W>
<W id="7" msd="PD" tag="DT" in="" out="">the</W>
<W id="8" msd="NC=S" tag="NN" in="" out="">space</W>
<W id="9" msd="SP" tag="IN" in="" out="">of</W>
<W id="10" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="11" msd="SP" tag="IN" in="" out="">between</W>
<W id="12" msd="AC" tag="CD" in="" out="">11</W>
<W id="13" msd="XP" tag="&3a;" in="" out="">:</W>
<W id="14" msd="AC" tag="CD" in="" out="">50</W>
<W id="15" msd="CC" tag="CC" in="" out="">and</W>
<W id="16" msd="AC" tag="CD" in="" out="">12</W>
<W id="17" msd="XP" tag="&3a;" in="" out="">:</W>
<W id="18" msd="AC" tag="CD" in="" out="">50</W>
<W id="19" msd="SP" tag="IN" in="" out="">on</W>
<W id="20" msd="NP=S" tag="NNP" in="" out="">December</W>
<W id="21" msd="AC" tag="CD" in="" out="">12,</W>
<W id="22" msd="AC" tag="CD" in="" out="">1981</W>
<W id="23" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="24" msd="NP=S" tag="NNP" in="" out="">Ove</W>
<W id="25" msd="NP=S" tag="NNP" in="" out="">Hansen</W>
<W id="26" msd="XP" tag="," in="" out="">,</W>
<W id="27" msd="VAG" tag="VBG" in="" out="">according</W>
<W id="28" msd="U=" tag="TO" in="" out="">to</W>
<W id="29" msd="PD" tag="DT" in="" out="">the</W>
<W id="30" msd="NC=S" tag="NN" in="" out="">police</W>
<W id="31" msd="XP" tag="," in="" out="">,</W>
<W id="32" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="33" msd="VAP" tag="VBN" in="" out="">supposed</W>
<W id="34" msd="U=" tag="TO" in="" out="">to</W>
<W id="35" msd="VAF" tag="VB" in="" out="">have</W>
<W id="36" msd="VAP" tag="VBN" in="" out="">killed</W>
<W id="37" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="38" msd="NC=S" tag="NN" in="" out="">wife</W>
<W id="39" msd="CC" tag="CC" in="" out="">and</W>
<W id="40" msd="VAP" tag="VBN" in="" out="">done</W>
<W id="41" msd="ANP" tag="RB" in="" out="">away</W>
<W id="42" msd="SP" tag="IN" in="" out="">with</W>
<W id="43" msd="PD" tag="DT" in="" out="">the</W>
<W id="44" msd="NC=S" tag="NN" in="" out="">body</W>
<W id="45" msd="SP" tag="IN" in="" out="">by</W>
<W id="46" msd="VAG" tag="VBG" in="" out="">throwing</W>
<W id="47" msd="PP" tag="PRP" in="" out="">it</W>
<W id="48" msd="SP" tag="IN" in="" out="">in</W>
<W id="49" msd="PD" tag="DT" in="" out="">the</W>
<W id="50" msd="NC=S" tag="NN" in="" out="">harbour</W>
<W id="51" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="54" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="55" msd="ANP" tag="RB" in="" out="">Nevertheless</W>
<W id="56" msd="XP" tag="," in="" out="">,</W>
<W id="57" msd="PD" tag="DT" in="" out="">the</W>
<W id="58" msd="NC=S" tag="NN" in="" out="">information</W>
<W id="59" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="60" msd="ANP" tag="RB" in="" out="">never</W>
<W id="61" msd="VAP" tag="VBN" in="" out="">written</W>
<W id="62" msd="ANP" tag="RB" in="" out="">down</W>
<W id="63" msd="XP" tag="," in="" out="">,</W>
<W id="64" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="65" msd="VADA" tag="VBD" in="" out="">maintained</W>
<W id="66" msd="PD" tag="DT" in="" out="">the</W>
<W id="67" msd="NP=S" tag="NNP" in="" out="">DR-Documentary</W>
<W id="68" msd="NC=S" tag="NN" in="" out="">group</W>
<W id="69" msd="SP" tag="IN" in="" out="">in</W>
<W id="70" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="71" msd="ANP" tag="JJ" in="" out="">devastating</W>
<W id="72" msd="NC=S" tag="NN" in="" out="">critique</W>
<W id="73" msd="SP" tag="IN" in="" out="">of</W>
<W id="74" msd="PD" tag="DT" in="" out="">the</W>
<W id="75" msd="NP=S" tag="NNP" in="" out="">Frederikshavn</W>
<W id="76" msd="NC=P" tag="NNS" in="" out="">police's</W>
<W id="77" msd="NC=S" tag="NN" in="" out="">investigation</W>
<W id="78" msd="SP" tag="IN" in="" out="">of</W>
<W id="79" msd="PD" tag="DT" in="" out="">the</W>
<W id="80" msd="NP=S" tag="NNP" in="" out="">Pedal-Ove</W>
<W id="81" msd="NC=S" tag="NN" in="" out="">case</W>
</s>
<s>
<W id="84" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="85" msd="PD" tag="DT" in="" out="">The</W>
<W id="86" msd="NC=S" tag="NN" in="" out="">report</W>
<W id="87" msd="SP" tag="IN" in="" out="">with</W>
<W id="88" msd="NC=S" tag="NN" in="" out="">number</W>
<W id="89" msd="NC=S" tag="NN" in="" out="">0-22</W>
<W id="90" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="91" msd="ANP" tag="RB" in="" out="">never</W>
<W id="92" msd="VAP" tag="VBN" in="" out="">presented</W>
<W id="93" msd="SP" tag="IN" in="" out="">by</W>
<W id="94" msd="NP=S" tag="NNP" in="" out="">Jane</W>
<W id="95" msd="NP=S" tag="NNP" in="" out="">Nielsen.</W>
<W id="96" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="99" msd="NP=S" tag="NNP" in="" out="">TV's</W>
<W id="100" msd="NP=S" tag="NNP" in="" out="">Sten</W>
<W id="101" msd="NP=S" tag="NNP" in="" out="">Baadsgaard</W>
<W id="102" msd="VADA" tag="VBD" in="" out="">showed</W>
<W id="103" msd="PP" tag="PRP" in="" out="">it</W>
<W id="104" msd="U=" tag="TO" in="" out="">to</W>
<W id="105" msd="PP" tag="PRP" in="" out="">her</W>
<W id="106" msd="CS" tag="IN" in="" out="">before</W>
<W id="107" msd="PD" tag="DT" in="" out="">the</W>
<W id="108" msd="NC=S" tag="NN" in="" out="">interview</W>
<W id="109" msd="XP" tag="," in="" out="">,</W>
<W id="110" msd="CC" tag="CC" in="" out="">but</W>
<W id="111" msd="XP" tag="," in="" out="">,</W>
<W id="112" msd="ANP" tag="JJ" in="" out="">pursuant</W>
<W id="113" msd="U=" tag="TO" in="" out="">to</W>
<W id="114" msd="NC=S" tag="NN" in="" out="">agreement</W>
<W id="115" msd="XP" tag="," in="" out="">,</W>
<W id="116" msd="PP" tag="PRP" in="" out="">she</W>
<W id="117" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="118" msd="U=" tag="TO" in="" out="">to</W>
<W id="119" msd="VAF" tag="VB" in="" out="">act</W>
<W id="120" msd="SP" tag="IN" in="" out="">on</W>
<W id="121" msd="NC=S" tag="NN" in="" out="">screen</W>
<W id="122" msd="CS" tag="IN" in="" out="">as</W>
<W id="123" msd="CS" tag="IN" in="" out="">if</W>
<W id="124" msd="PP" tag="PRP" in="" out="">she</W>
<W id="125" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="126" msd="ANP" tag="RB" in="" out="">not</W>
<W id="127" msd="VAP" tag="VBN" in="" out="">seen</W>
<W id="128" msd="PP" tag="PRP" in="" out="">it</W>
<W id="129" msd="CS" tag="IN" in="" out="">before</W>
<W id="130" msd="CC" tag="CC" in="" out="">and</W>
<W id="131" msd="VAF" tag="VB" in="" out="">ask</W>
<W id="132" msd="XP" tag="&3a;" in="" out="">:</W>
</s>
<s>
<W id="135" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="136" msd="PT" tag="WRB" in="" out="">Where</W>
<W id="137" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="138" msd="PD" tag="DT" in="" out="">the</W>
<W id="139" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="140" msd="NC=S" tag="NN" in="" out="">part</W>
<W id="141" msd="XP" tag="." in="" out="">?</W>
<W id="142" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="145" msd="VAP" tag="VBN" in="" out="">Implied</W>
<W id="146" msd="SP" tag="IN" in="" out="">that</W>
<W id="147" msd="PI" tag="DT" in="" out="">a</W>
<W id="148" msd="NC=S" tag="NN" in="" out="">page</W>
<W id="149" msd="VA" tag="MD" in="" out="">must</W>
<W id="150" msd="VAF" tag="VB" in="" out="">be</W>
<W id="151" msd="VAG" tag="VBG" in="" out="">missing</W>
<W id="152" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="153" msd="PD" tag="DT" in="" out="">the</W>
<W id="154" msd="AC" tag="CD" in="" out="">one</W>
<W id="155" msd="SP" tag="IN" in="" out="">with</W>
<W id="156" msd="PO" tag="PRP$" in="" out="">her</W>
<W id="157" msd="NC=S" tag="NN" in="" out="">explanation</W>
<W id="158" msd="SP" tag="IN" in="" out="">about</W>
<W id="159" msd="NP=S" tag="NNP" in="" out="">Ove</W>
<W id="160" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="163" msd="VAP" tag="VBN" in="" out="">Interrogated</W>
<W id="164" msd="SP" tag="IN" in="" out="">under</W>
<W id="165" msd="NC=S" tag="NN" in="" out="">oath</W>
<W id="166" msd="XP" tag="," in="" out="">,</W>
<W id="167" msd="NP=S" tag="NNP" in="" out="">Detective</W>
<W id="168" msd="NP=S" tag="NNP" in="" out="">Inspector</W>
<W id="169" msd="NP=S" tag="NNP" in="" out="">Villy</W>
<W id="170" msd="NP=S" tag="NNP" in="" out="">Nielsen</W>
<W id="171" msd="XP" tag="," in="" out="">,</W>
<W id="172" msd="NP=S" tag="NNP" in="" out="">Frederikshavn</W>
<W id="173" msd="NC=S" tag="NN" in="" out="">police</W>
<W id="174" msd="XP" tag="," in="" out="">,</W>
<W id="175" msd="PT" tag="WP" in="" out="">who</W>
<W id="176" msd="SP" tag="IN" in="" out="">along</W>
<W id="177" msd="SP" tag="IN" in="" out="">with</W>
<W id="178" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="179" msd="NC=S" tag="NN" in="" out="">colleague</W>
<W id="180" msd="NP=S" tag="NNP" in="" out="">Frank</W>
<W id="181" msd="NP=S" tag="NNP" in="" out="">B.</W>
<W id="182" msd="NP=S" tag="NNP" in="" out="">Madsen</W>
<W id="183" msd="VADA" tag="VBD" in="" out="">undertook</W>
<W id="184" msd="PD" tag="DT" in="" out="">the</W>
<W id="185" msd="NC=S" tag="NN" in="" out="">interrogation</W>
<W id="186" msd="SP" tag="IN" in="" out="">on</W>
<W id="187" msd="NP=S" tag="NNP" in="" out="">December</W>
<W id="188" msd="AC" tag="CD" in="" out="">30,</W>
<W id="189" msd="AC" tag="CD" in="" out="">1981,</W>
<W id="190" msd="SP" tag="IN" in="" out="">of</W>
<W id="191" msd="NP=S" tag="NNP" in="" out="">Jane</W>
<W id="192" msd="NP=S" tag="NNP" in="" out="">Nielsen</W>
<W id="193" msd="SP" tag="IN" in="" out="">at</W>
<W id="194" msd="PO" tag="PRP$" in="" out="">her</W>
<W id="195" msd="NC=S" tag="NN" in="" out="">residence</W>
<W id="196" msd="SP" tag="IN" in="" out="">in</W>
<W id="197" msd="PD" tag="DT" in="" out="">the</W>
<W id="198" msd="NC=S" tag="NN" in="" out="">presence</W>
<W id="199" msd="SP" tag="IN" in="" out="">of</W>
<W id="200" msd="PO" tag="PRP$" in="" out="">her</W>
<W id="201" msd="NC=S" tag="NN" in="" out="">husband</W>
<W id="202" msd="XP" tag="," in="" out="">,</W>
<W id="203" msd="ANP" tag="RB" in="" out="">however</W>
<W id="204" msd="XP" tag="," in="" out="">,</W>
<W id="205" msd="VADA" tag="VBD" in="" out="">denied</W>
<W id="206" msd="SP" tag="IN" in="" out="">that</W>
<W id="207" msd="PP" tag="PRP" in="" out="">she</W>
<W id="208" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="209" msd="VAP" tag="VBN" in="" out="">mentioned</W>
<W id="210" msd="NC=S" tag="NN" in="" out="">anything</W>
<W id="211" msd="SP" tag="IN" in="" out="">about</W>
<W id="212" msd="VAG" tag="VBG" in="" out="">seeing</W>
<W id="213" msd="NP=S" tag="NNP" in="" out="">Ove</W>
<W id="214" msd="SP" tag="IN" in="" out="">on</W>
<W id="215" msd="PD" tag="DT" in="" out="">the</W>
<W id="216" msd="NC=S" tag="NN" in="" out="">day</W>
<W id="217" msd="SP" tag="IN" in="" out="">of</W>
<W id="218" msd="PD" tag="DT" in="" out="">the</W>
<W id="219" msd="NC=S" tag="NN" in="" out="">killing</W>
<W id="220" msd="XP" tag="." in="" out="">.</W>
</s>
