<s>
<W msd="&quot;" in="3:pnct" out="">"</W>
<W msd="PRP$" in="2:subj|3:[subj]" out="1:possd">My</W>
<W msd="NN" in="-1:possd" out="">father</W>
<W msd="VBZ" in="9:qobj" out="-3:pnct|-2:subj|1:vobj|7:pnct|8:pnct">has</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:dobj|3:lobj">stuck</W>
<W msd="PRP$" in="-1:dobj" out="1:possd">his</W>
<W msd="NN" in="-1:possd" out="">peepee</W>
<W msd="RP" in="-3:lobj" out="1:pobj">up</W>
<W msd="IN" in="-1:pobj" out="1:nobj">into</W>
<W msd="PRP" in="-1:nobj" out="">me</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="&quot;" in="-8:pnct" out="">"</W>
<W msd="VBD" in="" out="-9:qobj|1:subj|4:mod|8:pnct|9:coord|20:pnct">reported</W>
<W msd="DT" in="-1:subj" out="1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">retarded</W>
<W msd="NN" in="-2:nobj" out="">girl</W>
<W msd="IN" in="-4:mod" out="1:nobj">via</W>
<W msd="DT" in="-1:nobj" out="2:nobj">a</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NN" in="-2:nobj" out="-1:mod">board</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="CC" in="-9:coord" out="2:conj">and</W>
<W msd="PRP" in="1:subj" out="">it</W>
<W msd="VBD" in="-2:conj" out="-1:subj|1:pobj">resulted</W>
<W msd="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="2:nobj">a</W>
<W msd="NN" in="1:mod" out="">police</W>
<W msd="NN" in="-2:nobj" out="-1:mod|1:pobj">report</W>
<W msd="IN" in="-1:pobj" out="1:nobj">against</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">innocent</W>
<W msd="NNS" in="-2:nobj" out="">parents</W>
<W msd="." in="-20:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="2:subj|3:[subj]|5:[subj]|7:[subj]" out="1:nobj">The</W>
<W msd="NNS" in="-1:nobj" out="">parents</W>
<W msd="VBD" in="" out="-2:subj|1:vobj|2:coord|10:pnct">were</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]">convicted</W>
<W msd="CC" in="-2:coord" out="1:conj">but</W>
<W msd="VBD" in="-1:conj" out="-5:[subj]|1:nobj">had</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-7:[subj]|1:pobj">go</W>
<W msd="IN" in="-1:pobj" out="1:nobj">through</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">a</W>
<W msd="VBG" in="-1:mod" out="">gruelling</W>
<W msd="NN" in="-2:nobj" out="">case</W>
<W msd="." in="-10:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="7:subj|8:[subj]|10:[subj]" out="1:nobj|2:pnct|3:ref|4:rel">The</W>
<W msd="NN" in="-1:nobj" out="">report</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="WDT" in="-3:ref|1:subj|2:[subj]" out="">which</W>
<W msd="VBZ" in="-4:rel" out="-1:subj|1:vobj|2:pnct#">has</W>
<W msd="NN" in="-1:vobj" out="-2:[subj]|1:dobj">cost</W>
<W msd="CD" in="-1:dobj|-2:pnct#" out="">800,000,</W>
<W msd="VBD" in="" out="-7:subj|1:vobj|9:mod|39:pnct">was</W>
<W msd="VBN" in="-1:vobj" out="-8:[subj]|1:coord|3:pobj">ordered</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="VBN" in="-1:conj" out="-10:[subj]|1:[pobj]">paid</W>
<W msd="IN" in="-3:pobj|-1:[pobj]" out="1:nobj">by</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="2:nobj">Copenhagen</W>
<W msd="NNP" in="1:mod" out="">County</W>
<W msd="NNP" in="-2:nobj" out="-1:mod">Council</W>
<W msd="IN" in="-9:mod" out="1:nobj">after</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">an</W>
<W msd="JJ" in="-1:mod" out="">intense</W>
<W msd="NN" in="-2:nobj" out="1:pobj">debate</W>
<W msd="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="1:nobj|3:ref|7:rel">the</W>
<W msd="NN" in="-1:nobj" out="">extent</W>
<W msd="TO" in="5:mod" out="1:nobj">to</W>
<W msd="WDT" in="-3:ref|-1:nobj" out="">which</W>
<W msd="DT" in="3:subj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NN" in="-2:nobj" out="-1:mod">board</W>
<W msd="VBD" in="-7:rel" out="-3:subj|-5:mod|1:pred">was</W>
<W msd="DT" in="-1:pred" out="1:nobj|2:coord">a</W>
<W msd="JJ" in="-1:nobj" out="">con</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="DT" in="-1:conj" out="1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">valuable</W>
<W msd="NNS" in="-2:nobj" out="1:pobj">means</W>
<W msd="TO" in="-1:pobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pobj">communicate</W>
<W msd="IN" in="-1:pobj" out="7:nobj">with</W>
<W msd="JJ" in="6:mod" out="">so-called</W>
<W msd="&quot;" in="5:pnct" out="">"</W>
<W msd="RB" in="1:mod" out="">severely</W>
<W msd="RB" in="3:mod" out="-1:mod|1:coord">physically</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="RB" in="-1:conj" out="">psychically</W>
<W msd="JJ" in="-7:nobj" out="-6:mod|-5:pnct|-3:mod|1:pnct">handicapped</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="." in="-39:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="" out="1:nobj">WITH</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">A</W>
<W msd="VBD" in="-1:mod" out="">GUIDED</W>
<W msd="NNP" in="-2:nobj" out="">HAND</W>
</s>
<s>
<W msd="DT" in="5:subj|22:[subj]" out="1:nobj">The</W>
<W msd="NN" in="-1:nobj" out="1:pobj">use</W>
<W msd="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">boards</W>
<W msd="VBD" in="" out="-5:subj|1:lobj|15:coord|21:pnct">began</W>
<W msd="IN" in="-1:lobj" out="1:nobj">at</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NNP" in="-1:nobj" out="">M-house</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NNP" in="-1:nobj" out="1:nobj|7:pnct|8:appa">Copenhagen</W>
<W msd="NNP" in="-1:nobj" out="2:possd">County's</W>
<W msd="NN" in="1:mod" out="">hospital</W>
<W msd="NN" in="-2:possd" out="-1:mod|1:pobj">department</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">multiple-handicapped</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="NNP" in="-8:appa" out="1:pnct">Vangedehuse</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="CC" in="-15:coord" out="2:conj">and</W>
<W msd="RB" in="1:mod" out="">gradually</W>
<W msd="VBP" in="-2:conj" out="-22:[subj]|-1:mod|1:pobj">spread</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NNS" in="-1:nobj" out="">institutions</W>
<W msd="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NNP" in="-1:nobj" out="">County</W>
<W msd="NNS" in="" out="-2:subj|1:dobj|14:pnct">estimates</W>
<W msd="IN" in="-1:dobj" out="6:vobj">that</W>
<W msd="RP" in="2:mod" out="1:mod">up</W>
<W msd="IN" in="-1:mod" out="1:[nobj]">towards</W>
<W msd="CD" in="-1:[nobj]|3:subj|4:[subj]|6:[subj]" out="-2:mod|1:mod|2:nobj">100</W>
<W msd="JJ" in="-1:mod" out="">handicapped</W>
<W msd="NNS" in="-2:nobj" out="">people</W>
<W msd="VBP" in="-6:vobj" out="-3:subj|1:vobj|2:coord">have</W>
<W msd="VBN" in="-1:vobj" out="-4:[subj]|3:dobj">used</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="VB" in="-1:conj" out="-6:[subj]|1:[dobj]">use</W>
<W msd="DT" in="-3:dobj|-1:[dobj]" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">boards</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="8:subj" out="1:mod|2:pnct|3:ref|4:rel|15:mod">The</W>
<W msd="JJ" in="-1:mod" out="">handicapped</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="WP" in="-3:ref|1:subj|3:[subj]" out="">who</W>
<W msd="VBP" in="-4:rel" out="-1:subj|1:mod|2:vobj|3:pnct">do</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VB" in="-2:vobj" out="-3:[subj]">speak</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="VB" in="" out="-8:subj|1:mod|22:pnct">sit</W>
<W msd="RB" in="-1:mod" out="1:pobj">together</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="CD" in="-1:nobj" out="1:coord|3:nobj">two</W>
<W msd="CC" in="-1:coord" out="1:conj">or</W>
<W msd="JJR" in="-1:conj" out="1:[nobj]">more</W>
<W msd="NNS" in="-3:nobj|-1:[nobj]" out="">tutors</W>
<W msd="VBG" in="-15:mod" out="1:dobj">facing</W>
<W msd="DT" in="-1:dobj" out="2:nobj|3:pnct|4:ref|5:rel">the</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NN" in="-2:nobj" out="-1:mod">board</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="WDT" in="-4:ref|1:subj" out="">which</W>
<W msd="VBZ" in="-5:rel" out="-1:subj|1:pobj">consists</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:coord">the</W>
<W msd="NN" in="-1:nobj" out="">alphabet</W>
<W msd="CC" in="-2:coord" out="1:conj">and</W>
<W msd="DT" in="-1:conj" out="1:nobj">a</W>
<W msd="JJ" in="-1:nobj" out="1:nobj">few</W>
<W msd="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NNS" in="-1:nobj" out="">symbols</W>
<W msd="." in="-22:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="8:mod" out="1:nobj|5:pnct">In</W>
<W msd="NN" in="-1:nobj" out="1:nobj">order</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj">provide</W>
<W msd="NN" in="-1:dobj" out="">support</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="DT" in="2:subj" out="1:nobj">a</W>
<W msd="VB" in="-1:nobj" out="">tutor</W>
<W msd="VBZ" in="" out="-2:subj|-8:mod|1:dobj|4:mod|8:pnct|9:mod|19:pnct">guides</W>
<W msd="DT" in="-1:dobj" out="1:mod|2:possd">the</W>
<W msd="NNS" in="-1:mod" out="">handicapped's</W>
<W msd="VBP" in="-2:possd" out="">hand</W>
<W msd="IN" in="-4:mod" out="1:nobj">over</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">message</W>
<W msd="NN" in="-2:nobj" out="-1:mod">board</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="IN" in="-9:mod" out="3:vobj">until</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">client</W>
<W msd="NNS" in="-3:vobj" out="-2:subj|1:pobj">points</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">a</W>
<W msd="NN" in="-1:nobj" out="">symbol</W>
<W msd="IN" in="-2:mod" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">board</W>
<W msd="." in="-19:pnct" out="">.</W>
</s>
