<s>
<W msd="DT" in="10:subj" out="1:nobj">The</W>
<W msd="NN" in="-1:nobj" out="1:pobj">proposal</W>
<W msd="IN" in="-1:pobj" out="3:nobj">for</W>
<W msd="JJ" in="2:mod" out="">joint</W>
<W msd="NN" in="1:mod" out="">group</W>
<W msd="NNS" in="-3:nobj" out="-1:mod|-2:mod|1:pobj">meetings</W>
<W msd="IN" in="-1:pobj" out="1:nobj">between</W>
<W msd="NNP" in="-1:nobj" out="1:coord">V</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NNP" in="-1:conj" out="">K</W>
<W msd="VBZ" in="" out="-10:subj|1:mod|3:pred|4:pnct">is</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="RB" in="1:mod" out="">entirely</W>
<W msd="JJ" in="-3:pred" out="-1:mod">new</W>
<W msd="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="8:mod" out="1:nobj|2:pnct">In</W>
<W msd="NN" in="-1:nobj" out="">fact</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="DT" in="5:subj|6:[subj]" out="1:mod|2:mod|4:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">historic</W>
<W msd="JJ" in="-2:mod" out="">joint</W>
<W msd="NN" in="1:mod" out="">group</W>
<W msd="NN" in="-4:nobj" out="-1:mod">meeting</W>
<W msd="VBD" in="" out="-8:mod|-5:subj|1:vobj|11:coord|49:pnct">was</W>
<W msd="VBN" in="-1:vobj" out="-6:[subj]|1:mod|8:mod">held</W>
<W msd="IN" in="-1:mod" out="1:nobj">before</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">launching</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NNP" in="1:mod" out="">KV</W>
<W msd="NN" in="-2:nobj" out="-1:mod">plan</W>
<W msd="IN" in="-8:mod" out="1:nobj">in</W>
<W msd="CD" in="-1:nobj" out="">1964,</W>
<W msd="CC" in="-11:coord" out="1:pnct|5:conj">and</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="3:mod" out="1:nobj|1:pnct#">in</W>
<W msd="CD" in="-1:nobj|-1:pnct#" out="">1965,</W>
<W msd="PRP" in="1:subj" out="24:nobj">it</W>
<W msd="VBP" in="-5:conj" out="-3:mod|-1:subj|1:iobj|16:dobj">cost</W>
<W msd="DT" in="-1:iobj" out="1:nobj|6:mod|9:pnct|14:appa">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">leader</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">Liberal</W>
<W msd="NNP" in="-2:nobj" out="">Party</W>
<W msd="IN" in="-6:mod" out="1:nobj">at</W>
<W msd="DT" in="-1:nobj" out="1:nobj">that</W>
<W msd="NN" in="-1:nobj" out="">time</W>
<W msd="," in="-9:pnct" out="">,</W>
<W msd="JJ" in="2:mod" out="">former</W>
<W msd="NNP" in="1:mod" out="">Prime</W>
<W msd="NNP" in="2:title" out="-1:mod|-2:mod">Minister</W>
<W msd="NNP" in="1:namef" out="">Erik</W>
<W msd="NNP" in="-14:appa" out="-2:title|-1:namef">Erikson</W>
<W msd="PRP$" in="-16:dobj" out="1:possd">his</W>
<W msd="NN" in="-1:possd" out="1:pobj">role</W>
<W msd="IN" in="-1:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod|3:possd">the</W>
<W msd="NNS" in="-1:nobj" out="">party's</W>
<W msd="VBG" in="-2:mod" out="">leading</W>
<W msd="NN" in="-3:possd" out="">figure</W>
<W msd="IN" in="-24:nobj" out="3:vobj">that</W>
<W msd="PRP" in="2:subj" out="">he</W>
<W msd="RB" in="1:mod" out="">directly</W>
<W msd="VBD" in="-3:vobj" out="-2:subj|-1:mod|1:dobj">supported</W>
<W msd="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj">merger</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NNS" in="-1:nobj" out="">parties</W>
<W msd="." in="-49:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NN" in="-1:nobj" out="">time</W>
<W msd="VBD" in="" out="-2:subj|1:mod|2:pred|3:mod|9:pnct|13:xpl">was</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="JJ" in="-2:pred" out="2:pobj">ripe</W>
<W msd="RB" in="-3:mod" out="">then</W>
<W msd="IN" in="-2:pobj" out="2:nobj">for</W>
<W msd="JJ" in="1:mod" out="">such</W>
<W msd="DT" in="-2:nobj" out="-1:mod|1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">decisive</W>
<W msd="NN" in="-2:nobj" out="">step</W>
<W msd=":" in="-9:pnct" out="">:</W>
</s>
<s>
<W msd="&quot;" in="1:pnct" out="">"</W>
<W msd="CC" in="-13:xpl" out="-1:pnct|1:vobj|9:pnct">Nor</W>
<W msd="VBZ" in="-1:vobj" out="1:subj|2:pnct|3:mod|7:mod">is</W>
<W msd="PRP" in="-1:subj" out="">it</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="IN" in="-3:mod" out="1:nobj|3:pnct">for</W>
<W msd="DT" in="-1:nobj" out="1:nobj">that</W>
<W msd="NN" in="-1:nobj" out="">matter</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="RB" in="-7:mod" out="">now</W>
<W msd="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|8:[subj]" out="">We</W>
<W msd="MD" in="" out="-1:subj|1:mod|2:pnct|3:mod|7:vobj|28:pnct">must</W>
<W msd="RB" in="-1:mod" out="">first</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="IN" in="-3:mod" out="1:nobj|3:pnct">at</W>
<W msd="DT" in="-1:nobj" out="1:nobj">any</W>
<W msd="NN" in="-1:nobj" out="">rate</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="VB" in="-7:vobj" out="-8:[subj]|1:lobj">go</W>
<W msd="IN" in="-1:lobj" out="1:nobj">through</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:pnct|3:mod|4:nobj|6:ref|12:rel">a</W>
<W msd="JJ" in="-1:mod" out="">long</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="JJ" in="-3:mod" out="">long</W>
<W msd="NN" in="-4:nobj" out="">period</W>
<W msd="IN" in="7:mod" out="1:nobj">during</W>
<W msd="WDT" in="-1:nobj|-6:ref" out="">which</W>
<W msd="NNS" in="5:subj|6:[subj]|7:[subj]" out="1:mod">people</W>
<W msd="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NNS" in="-1:nobj" out="">parties</W>
<W msd="MD" in="-12:rel" out="-7:mod|-5:subj|1:vobj">can</W>
<W msd="VB" in="-1:vobj" out="-6:[subj]|1:vobj">become</W>
<W msd="VBN" in="-1:vobj" out="-7:[subj]|1:pobj">acquainted</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:possd">each</W>
<W msd="NNS" in="-1:nobj" out="">other's</W>
<W msd="NN" in="-2:possd" out="">chemistry</W>
<W msd="." in="-28:pnct" out="">.</W>
</s>
<s>
<W msd="RB" in="9:mod" out="1:pnct">Here</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="JJ" in="6:mod" out="">regular</W>
<W msd="JJ" in="5:mod" out="">joint</W>
<W msd="NN" in="4:mod" out="1:coord">group</W>
<W msd="CC" in="-1:coord" out="2:conj">and</W>
<W msd="JJ" in="1:mod" out="">executive</W>
<W msd="NN" in="-2:conj" out="-1:mod">committee</W>
<W msd="NNS" in="1:subj|2:[subj]" out="-4:mod|-6:mod|-5:mod">meetings</W>
<W msd="MD" in="" out="-9:mod|-1:subj|1:vobj|7:pnct">could</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W msd="DT" in="-1:pred" out="1:nobj|2:mod">a</W>
<W msd="NN" in="-1:nobj" out="">step</W>
<W msd="IN" in="-2:mod" out="1:nobj">along</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">way</W>
<W msd="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="1:subj|2:[subj]" out="">This</W>
<W msd="MD" in="" out="-1:subj|1:vobj|8:pnct">would</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:dobj">prevent</W>
<W msd="JJ" in="-1:dobj" out="1:nobj">many</W>
<W msd="NNS" in="-1:nobj" out="1:pobj">misunderstandings</W>
<W msd="IN" in="-1:pobj" out="1:nobj">between</W>
<W msd="PRP$" in="-1:nobj" out="1:possd">our</W>
<W msd="CD" in="-1:possd" out="1:nobj">two</W>
<W msd="NNS" in="-1:nobj" out="">parties</W>
<W msd="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|2:[subj]" out="">We</W>
<W msd="MD" in="" out="-1:subj|1:vobj|12:pnct">must</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:pobj">think</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NN" in="-1:nobj" out="">co-operation</W>
<W msd="IN" in="-2:mod" out="1:nobj">among</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="VBG" in="-1:mod" out="">coming</W>
<W msd="NN" in="-2:nobj" out="1:pobj">generation</W>
<W msd="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="JJ" in="1:mod" out="">non-socialist</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">politicians</W>
<W msd="." in="-12:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|2:[subj]" out="">It</W>
<W msd="MD" in="22:qobj" out="-1:subj|1:vobj|11:pnct|12:mod|20:pnct|21:pnct">would</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W msd="DT" in="-1:pred" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj|5:nobj">shame</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">whole</W>
<W msd="NN" in="-2:nobj" out="">thing</W>
<W msd="TO" in="-5:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:part">fall</W>
<W msd="IN" in="-1:part" out="">through</W>
<W msd="," in="-11:pnct" out="">,</W>
<W msd="IN" in="-12:mod" out="3:vobj">because</W>
<W msd="DT" in="2:subj|3:[subj]" out="1:nobj">some</W>
<W msd="NNS" in="-1:nobj" out="">individuals</W>
<W msd="VBP" in="-3:vobj" out="-2:subj|1:vobj">have</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:dobj|3:vobj">kept</W>
<W msd="DT" in="-1:dobj|2:[subj]" out="1:nobj">the</W>
<W msd="JJ" in="-1:nobj" out="">co-operation</W>
<W msd="NN" in="-3:vobj" out="-2:[subj]">going</W>
<W msd="," in="-20:pnct" out="">,</W>
<W msd="&quot;" in="-21:pnct" out="">"</W>
<W msd="VBZ" in="" out="-22:qobj|1:subj|5:pnct">says</W>
<W msd="DT" in="-1:subj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="1:pobj">Minister</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NNP" in="-1:nobj" out="">Fisheries</W>
<W msd="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="10:mod" out="1:nobj|8:pnct">After</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">a</W>
<W msd="NN" in="-1:nobj" out="">weekend</W>
<W msd="IN" in="-2:mod" out="1:nobj">with</W>
<W msd="PRP$" in="-1:nobj" out="1:possd">his</W>
<W msd="NN" in="-1:possd" out="1:mod">family</W>
<W msd="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="NNP" in="-1:nobj" out="">Fanø</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="PRP" in="1:subj" out="">he</W>
<W msd="VBD" in="" out="-10:mod|-1:subj|1:pred|3:mod|12:pnct">was</W>
<W msd="IN" in="-1:pred" out="1:nobj|4:mod">in</W>
<W msd="NNP" in="-1:nobj" out="">Brussels</W>
<W msd="IN" in="-3:mod" out="1:nobj">on</W>
<W msd="NNP" in="-1:nobj" out="">Monday</W>
<W msd="IN" in="-4:mod" out="1:nobj">at</W>
<W msd="DT" in="-1:nobj" out="5:nobj">the</W>
<W msd="NNP" in="1:mod" out="">EC</W>
<W msd="NNP" in="3:mod" out="-1:mod|1:pobj">Minister</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNP" in="-1:nobj" out="">Fisheries</W>
<W msd="NN" in="-5:nobj" out="-3:mod">meeting</W>
<W msd="." in="-12:pnct" out="">.</W>
</s>
