<s>
<W msd="XP" tag="&amp;quot;" in="10:pnct" out="">"</W>
<W msd="CS" tag="IN" in="9:xtop" out="5:vobj|7:ref">Since</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W msd="SP" tag="IN" in="" out="">for</W>
<W msd="NP=S" tag="NNP" in="" out="">Housing</W>
<W msd="NC=S" tag="NN" in="-5:vobj" out="1:pnct">won't</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-7:ref|2:mod" out="">then</W>
<W msd="PP" tag="PRP" in="1:subj|4:[subj]" out="">I</W>
<W msd="VA" tag="MD" in="" out="-10:pnct|-9:xtop|-2:mod|-1:subj">will</W>
<W msd="VAF" tag="VB" in="" out="">have</W>
<W msd="U=" tag="TO" in="" out="1:vobj|3:pnct|4:pnct">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-4:[subj]|1:dobj">do</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="">it</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-4:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="" out="2:subj|3:pnct|33:pnct">says</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Kristen</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef">Jacobsen</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="VAG" tag="VBG" in="" out="">referring</W>
<W msd="U=" tag="TO" in="" out="3:nobj">to</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">fact</W>
<W msd="SP" tag="IN" in="-3:nobj" out="10:vobj">that</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Housing</W>
<W msd="NP=S" tag="NNP" in="" out="-1:mod">Minister</W>
<W msd="NP=S" tag="NNP" in="2:namef" out="1:namef">Svend</W>
<W msd="NP=S" tag="NNP" in="-1:namef" out="">Erik</W>
<W msd="NP=S" tag="NNP" in="4:subj|5:[subj]" out="-2:namef|2:mod">Hovmand</W>
<W msd="XP" tag="(" in="1:pnct" out="">(</W>
<W msd="NP=S" tag="NNP" in="-2:mod" out="-1:pnct|1:pnct">V</W>
<W msd="XP" tag=")" in="-1:pnct" out="">)</W>
<W msd="VADR" tag="VBZ" in="-10:vobj" out="-4:subj|1:vobj">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]|1:dobj">refused</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|2:pnct|3:prec">do</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">anything</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-3:prec" out="5:vobj">before</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">attorney</W>
<W msd="NC=P" tag="NNS" in="" out="">general's</W>
<W msd="NC=S" tag="NN" in="" out="">office</W>
<W msd="VADR" tag="VBZ" in="-5:vobj" out="1:vobj">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="1:dobj">assessed</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">case</W>
<W msd="XP" tag="." in="-33:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="3:mod" out="1:pnct">Thus</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]" out="">she</W>
<W msd="VADR" tag="VBZ" in="" out="-3:mod|-1:subj|1:mod|2:vobj|13:pnct|14:mod">is</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">literally</W>
<W msd="VAG" tag="VBG" in="-2:vobj" out="-3:[subj]|2:dobj|8:pobj">taking</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-2:dobj" out="-1:mod|1:attr|2:possd|3:pnct|5:appa">Housing's</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">former</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="">chairman</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Torben</W>
<W msd="NP=S" tag="NNP" in="-5:appa" out="-1:namef">Lund</W>
<W msd="SP" tag="IN" in="-8:pobj" out="">at</W>
<W msd="PO" tag="PRP$" in="" out="">his</W>
<W msd="NC=S" tag="NN" in="" out="">word</W>
<W msd="XP" tag="," in="-13:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-14:mod" out="9:vobj">since</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">vice</W>
<W msd="NC=S" tag="NN" in="" out="1:mod">chairman</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W msd="NP=S" tag="NNP" in="" out="">Social</W>
<W msd="ANP" tag="JJ" in="" out="">Democratic</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">group</W>
<W msd="VADA" tag="VBD" in="-9:vobj" out="3:pobj|7:dobj">said</W>
<W msd="ANP" tag="JJ" in="" out="">last</W>
<W msd="NC=S" tag="NN" in="" out="">night</W>
<W msd="U=" tag="TO" in="-3:pobj" out="">to</W>
<W msd="NC=S" tag="NN" in="" out="">TV</W>
<W msd="AC" tag="CD" in="" out="">2</W>
<W msd="NP=S" tag="NNP" in="" out="">News</W>
<W msd="SP" tag="IN" in="-7:dobj" out="3:vobj">that</W>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj" out="6:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-3:vobj" out="-2:pnct|-1:subj|1:preds|15:pnct#|16:pnct">is</W>
<W msd="RG" tag="RP" in="-1:preds" out="1:pobj">up</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">judge</W>
<W msd="U=" tag="TO" in="-6:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">decide</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">whether</W>
<W msd="NC=P" tag="NNS" in="1:subj|2:[subj]|3:[subj]" out="">illegalities</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:vobj|2:mod">been</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]">committed</W>
<W msd="SP" tag="IN" in="-2:mod" out="2:nobj">in</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod|1:possd">Housing's</W>
<W msd="ANP" tag="JJ" in="-1:possd|-15:pnct#" out="">administration.</W>
<W msd="XP" tag="&amp;quot;" in="-16:pnct" out="">"</W>
</s>
<s>
<W msd="SP" tag="IN" in="6:mod" out="">In</W>
<W msd="PO" tag="PRP$" in="" out="">her</W>
<W msd="NC=S" tag="NN" in="" out="1:pnct">report</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Kirsten</W>
<W msd="NP=S" tag="NNP" in="1:subj|2:[subj]" out="-1:namef">Jacobsen</W>
<W msd="VA" tag="MD" in="" out="-1:subj|-6:mod|1:vobj|36:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]">ask</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">commissioner</W>
<W msd="SP" tag="IN" in="" out="">of</W>
<W msd="NC=S" tag="NN" in="" out="">police</W>
<W msd="U=" tag="TO" in="" out="">to</W>
<W msd="VAF" tag="VB" in="" out="1:dobj">investigate</W>
<W msd="SP" tag="IN" in="-1:dobj" out="7:vobj">whether</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NP=S" tag="NNP" in="" out="">National</W>
<W msd="NP=S" tag="NNP" in="" out="">Association</W>
<W msd="SP" tag="IN" in="" out="2:appr">of</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-2:appr" out="-1:mod">Housing</W>
<W msd="VADR" tag="VBZ" in="-7:vobj" out="1:vobj">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="9:mod">committed</W>
<W msd="ANP" tag="JJ" in="" out="">fraudulent</W>
<W msd="NC=S" tag="NN" in="" out="">abuse</W>
<W msd="SP" tag="IN" in="" out="">of</W>
<W msd="NC=S" tag="NN" in="" out="1:pnct|2:conj|4:conj">authority</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="">embezzlement</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-4:conj" out="-1:coord">fraud</W>
<W msd="SP" tag="IN" in="-9:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">connection</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">state's</W>
<W msd="ANP" tag="JJ" in="" out="">million-crown</W>
<W msd="NC=S" tag="NN" in="" out="1:pobj">subsidy</W>
<W msd="U=" tag="TO" in="-1:pobj" out="2:nobj">to</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod|1:possd">Housing's</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">activities</W>
<W msd="XP" tag="." in="-36:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:mod" out="">NEW</W>
<W msd="NP=S" tag="NNP" in="" out="-1:mod">REVELATIONS</W>
</s>
<s>
<W msd="CS" tag="IN" in="20:mod" out="">Since</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:mod">Housing</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj">went</W>
<W msd="SP" tag="IN" in="" out="1:aobj|4:mod|5:mod|12:pnct">into</W>
<W msd="NC=S" tag="NN" in="-1:aobj" out="">bankruptcy</W>
<W msd="AC" tag="CD" in="2:nobj" out="1:nobj">three</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">weeks</W>
<W msd="ANP" tag="RB" in="-4:mod" out="-2:nobj">ago</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj">with</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">deficit</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">of</W>
<W msd="NP=S" tag="NNP" in="2:nobj" out="">DKK</W>
<W msd="AC" tag="CD" in="1:numm" out="">44.1</W>
<W msd="AC" tag="CD" in="-3:nobj" out="-1:numm|-2:nobj">million</W>
<W msd="XP" tag="," in="-12:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="3:eval" out="">hardly</W>
<W msd="PI" tag="DT" in="3:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">day</W>
<W msd="VADR" tag="VBZ" in="" out="-20:mod|1:expl|1:vobj|18:pnct|-3:eval">has</W>
<W msd="VAP" tag="VBN" in="-1:expl|-1:vobj" out="-3:dobj|1:accom">passed</W>
<W msd="SP" tag="IN" in="-1:accom" out="">without</W>
<W msd="ANP" tag="JJ" in="2:attr" out="">new</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">incriminating</W>
<W msd="NC=P" tag="NNS" in="1:subj|1:[subj]" out="-2:attr|-1:attr|3:pobj">revelations</W>
<W msd="VAG" tag="VBG" in="" out="-1:subj|-1:[subj]">turning</W>
<W msd="RG" tag="RP" in="" out="">up</W>
<W msd="SP" tag="IN" in="-3:pobj" out="4:nobj">about</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="3:nobj">way</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-4:nobj|1:[nobj]" out="-1:mod">Housing</W>
<W msd="VADA" tag="VBD" in="-3:nobj" out="-1:[nobj]">ran</W>
<W msd="PO" tag="PRP$" in="" out="1:attr">its</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">non-profit</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">leasehold</W>
<W msd="NC=S" tag="NN" in="" out="-1:mod">business</W>
<W msd="XP" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="PI" tag="DT" in="12:subj|13:[subj]" out="1:attr|2:nobj">A</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">large</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">part</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Youth</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod|1:possd">Housing's</W>
<W msd="AC" tag="CD" in="-1:possd" out="2:nobj|4:conj">1,600</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">youth</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">residences</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="AC" tag="CD" in="-4:conj" out="-1:coord|1:nobj">2,200</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">lodgings</W>
<W msd="VADR" tag="VBP" in="" out="-12:subj|1:vobj|6:pnct">are</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-13:[subj]|1:pobj">threatened</W>
<W msd="SP" tag="IN" in="-1:pobj" out="">with</W>
<W msd="PI" tag="DT" in="" out="">a</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">foreclosure</W>
<W msd="NC=S" tag="NN" in="" out="-1:mod">sale</W>
<W msd="XP" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W msd="AC" tag="CD" in="6:subj" out="1:mod|2:mod">150</W>
<W msd="NC=P" tag="NNS" in="-1:mod" out="">employees</W>
<W msd="SP" tag="IN" in="-2:mod" out="">at</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="ANP" tag="JJ" in="" out="">main</W>
<W msd="NC=S" tag="NN" in="" out="">office</W>
<W msd="NC=S" tag="NN" in="" out="-6:subj|1:dobj|4:pnct|5:coord|26:pnct">risk</W>
<W msd="PI" tag="DT" in="-1:dobj" out="">a</W>
<W msd="ANP" tag="JJ" in="" out="">pink</W>
<W msd="NC=S" tag="NN" in="" out="">slip</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="CC" tag="CC" in="-5:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="17:subj|18:[subj]" out="1:nobj|2:pnct|3:conj|5:pnct|10:pnct|11:conj|14:conj">many</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">renters</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-3:conj" out="1:nobj">several</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">municipalities</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">trade</W>
<W msd="NC=S" tag="NN" in="" out="">union</W>
<W msd="NC=S" tag="NN" in="" out="">movement</W>
<W msd="XP" tag="," in="-10:pnct" out="">,</W>
<W msd="PI" tag="DT" in="-11:conj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">bank</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="PD" tag="DT" in="-14:conj" out="-1:coord|1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">state</W>
<W msd="PD" tag="DT" in="1:mod" out="">all</W>
<W msd="VADR" tag="VBP" in="" out="-17:subj|-1:mod">are</W>
<W msd="VAP" tag="VBN" in="" out="-18:[subj]|1:dobj">owed</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">money</W>
<W msd="XP" tag="." in="-26:pnct" out="">.</W>
</s>
