<s>
<W msd="CC" tag="CC" in="" out="2:conj|33:pnct">But</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Lars</W>
<W msd="VADA" tag="VBD" in="-2:conj" out="-1:subj|2:preds|12:time">was</W>
<W msd="CS" tag="IN" in="1:mod" out="4:pobj">as</W>
<W msd="ANP" tag="RB" in="-2:preds" out="-1:mod|1:pobj">close</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="VAF" tag="VB" in="-1:nobj" out="">triumph</W>
<W msd="CS" tag="IN" in="-4:pobj" out="2:vobj">as</W>
<W msd="PP" tag="PRP" in="1:subj" out="3:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-2:vobj" out="-1:subj|1:preds|4:pnct">is</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="">possible</W>
<W msd="U=" tag="TO" in="-3:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="">get</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-12:time" out="8:vobj">when</W>
<W msd="SP" tag="IN" in="7:mod" out="4:mod">in</W>
<W msd="PD" tag="DT" in="" out="1:attr">the</W>
<W msd="AC" tag="CD" in="-1:attr" out="">2nd</W>
<W msd="VAP" tag="VBN" in="" out="">set</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">at</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="">20-20</W>
<W msd="PP" tag="PRP" in="1:subj|9:[subj]" out="">he</W>
<W msd="VADR" tag="VBP" in="-8:vobj" out="-1:subj|-7:mod|1:dobj|2:pobj|6:pnct|8:conj">bet</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">everything</W>
<W msd="SP" tag="IN" in="-2:pobj" out="">on</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">match</W>
<W msd="NC=S" tag="NN" in="" out="-1:mod">ball</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="CC" tag="CC" in="1:coord" out="">but</W>
<W msd="VADA" tag="VBD" in="-8:conj" out="-9:[subj]|-1:coord|1:nobj">hit</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">net</W>
<W msd="XP" tag="." in="-33:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="3:conj|8:pnct">And</W>
<W msd="ANP" tag="RB" in="2:mod" out="">then</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VADA" tag="VBD" in="-3:conj" out="-2:mod|-1:subj|1:preds|2:mod">was</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="">22-20</W>
<W msd="U=" tag="TO" in="-2:mod" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Pole</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="NC=S" tag="NN" in="" out="1:mod">SOMETHING</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">UP</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">THE</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">SLEEVE</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]|5:[subj]" out="">I</W>
<W msd="VADR" tag="VBP" in="" out="-2:pnct|-1:subj|1:neg">am</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAG" tag="VBG" in="" out="-3:[subj]">going</W>
<W msd="U=" tag="TO" in="" out="">to</W>
<W msd="VAF" tag="VB" in="" out="-5:[subj]|1:dobj|5:pnct|6:pnct|17:conj">forget</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">that</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">ball</W>
<W msd="ANP" tag="RB" in="" out="">very</W>
<W msd="ANP" tag="RB" in="" out="">soon</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-6:pnct" out="">"</W>
<W msd="VADA" tag="VBD" in="" out="1:subj|2:mod|5:pnct|36:pnct">maintained</W>
<W msd="NP=S" tag="NNP" in="-1:subj" out="">Hauth</W>
<W msd="CS" tag="IN" in="-2:mod" out="">after</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="VAF" tag="VB" in="" out="">meet</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="CC" tag="CC" in="3:coord" out="-1:pnct|30:pnct">but</W>
<W msd="ANP" tag="RB" in="2:mod" out="">otherwise</W>
<W msd="PP" tag="PRP" in="1:subj" out="">I</W>
<W msd="VADR" tag="VBP" in="-17:conj" out="-2:mod|-1:subj|-3:coord|2:preds">am</W>
<W msd="ANP" tag="RB" in="1:mod" out="">quite</W>
<W msd="VAP" tag="VBN" in="-2:preds" out="-1:mod|1:nobj">satisfied</W>
<W msd="SP" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|9:[subj]|15:[subj]" out="">I</W>
<W msd="VADA" tag="VBD" in="-2:vobj" out="-1:subj|2:preds|3:mod|8:conj">was</W>
<W msd="ANP" tag="RB" in="1:mod" out="">so</W>
<W msd="VAF" tag="VB" in="-2:preds" out="-1:mod">close</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">against</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Grubba</W>
<W msd="CC" tag="CC" in="3:coord" out="">and</W>
<W msd="ANP" tag="RB" in="2:succ" out="">afterwards</W>
<W msd="ANP" tag="RB" in="1:add" out="">also</W>
<W msd="VADA" tag="VBD" in="-8:conj" out="-9:[subj]|-3:coord|-1:add|3:pobj|6:conj|-2:succ">took</W>
<W msd="PI" tag="DT" in="" out="">a</W>
<W msd="NC=S" tag="NN" in="" out="">set</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Appelgren</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VADA" tag="VBD" in="-6:conj" out="-15:[subj]|-1:coord|1:dobj">showed</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="1:pobj">something</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj|3:[dobj]" out="1:attr">the</W>
<W msd="ANS" tag="JJS" in="-1:attr" out="">best</W>
<W msd="PP" tag="PRP" in="1:subj" out="">I</W>
<W msd="VA" tag="MD" in="" out="-3:[dobj]|-1:subj">can</W>
<W msd="VAF" tag="VB" in="-36:pnct" out="">do.</W>
<W msd="XP" tag="&amp;quot;" in="-30:pnct" out="">"</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj" out="">They</W>
<W msd="VADR" tag="VBP" in="32:qobj" out="-2:pnct|-1:subj|1:dobj|12:pnct|15:conj|31:pnct">have</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="1:mod|5:conj">something</W>
<W msd="RG" tag="RP" in="-1:mod" out="">up</W>
<W msd="PO" tag="PRP$" in="" out="">their</W>
<W msd="NC=P" tag="NNS" in="" out="">sleeves</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="ANC" tag="JJR" in="-5:conj" out="-1:coord|2:nobj|3:pobj">more</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">power</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">reserves</W>
<W msd="SP" tag="IN" in="-3:pobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj" out="">we</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj">have</W>
<W msd="XP" tag="," in="-12:pnct" out="">,</W>
<W msd="CC" tag="CC" in="2:coord" out="">but</W>
<W msd="PP" tag="PRP" in="1:subj" out="">I</W>
<W msd="VADR" tag="VBP" in="-15:conj" out="-1:subj|-2:coord|1:preds">am</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="1:nobj">happy</W>
<W msd="SP" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj|11:pnct#">could</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|3:pobj">take</W>
<W msd="PI" tag="DT" in="" out="">a</W>
<W msd="NC=S" tag="NN" in="" out="">set</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">world's</W>
<W msd="PD" tag="DT" in="" out="">no</W>
<W msd="XP" tag="." in="" out="3:nobj">.</W>
</s>
<s>
<W msd="AC" tag="CD" in="-3:nobj|-11:pnct#" out="">1,</W>
<W msd="XP" tag="&amp;quot;" in="-31:pnct" out="">"</W>
<W msd="VADA" tag="VBD" in="" out="-32:qobj|2:subj|3:mod|6:pnct">added</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Allan</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef">Bentsen</W>
<W msd="U=" tag="TO" in="-3:mod" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">conversation</W>
<W msd="XP" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W msd="NP=P" tag="NNPS" in="-1:nobj" out="">Swedes</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|7:pnct|19:conj|45:pnct">had</W>
<W msd="VAP" tag="VBN" in="" out="-3:[subj]">counted</W>
<W msd="SP" tag="IN" in="" out="1:nobj">on</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:dobj">getting</W>
<W msd="PI" tag="DT" in="-1:dobj" out="">a</W>
<W msd="NC=S" tag="NN" in="" out="">finale</W>
<W msd="NC=S" tag="NN" in="" out="">sweep</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="CC" tag="CC" in="11:coord" out="">but</W>
<W msd="PD" tag="DT" in="" out="3:pobj">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Pondus</W>
<W msd="NC=S" tag="NN" in="2:possd" out="-1:mod">winner</W>
<W msd="SP" tag="IN" in="-3:pobj" out="">for</W>
<W msd="PD" tag="DT" in="6:subj" out="-2:possd|2:nobj|5:appr">the</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">last</W>
<W msd="AC" tag="CD" in="-2:nobj" out="-1:attr">two</W>
<W msd="NC=P" tag="NNS" in="" out="">years</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Jean-Michel</W>
<W msd="NP=S" tag="NNP" in="-5:appr" out="-1:namef">Saive</W>
<W msd="VAF" tag="VB" in="-19:conj" out="-6:subj|-11:coord|1:dobj|5:pnct|6:time">put</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">stopper</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="SP" tag="IN" in="-1:nobj" out="">that</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-6:time" out="5:vobj">when</W>
<W msd="SP" tag="IN" in="4:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">semi-finals</W>
<W msd="PP" tag="PRP" in="1:subj|10:[subj]" out="">he</W>
<W msd="VADA" tag="VBD" in="-5:vobj" out="-1:subj|-4:mod|1:dobj|9:conj">continued</W>
<W msd="PO" tag="PRP$" in="-1:dobj" out="1:attr|2:possd|3:mod">his</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">magnificent</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="">play</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">introductory</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">rounds</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VADA" tag="VBD" in="-9:conj" out="-10:[subj]|-1:coord|1:pobj|3:pobj">won</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">over</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Appelgren</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">with</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:conj">21-15,</W>
<W msd="NC=S" tag="NN" in="-1:conj" out="">21-10</W>
<W msd="XP" tag="." in="-45:pnct" out="">.</W>
</s>
