<s>
<W msd="XP" tag="(" in="2:pnct" out="">(</W>
<W msd="AC" tag="CD" in="1:mod" out="">2nd</W>
<W msd="NC=S" tag="NN" in="" out="-2:pnct|-1:mod|1:pnct">edition</W>
<W msd="XP" tag=")" in="-1:pnct" out="">)</W>
<W msd="PD" tag="DT" in="5:subj|7:[subj]" out="3:nobj">The</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">real</W>
<W msd="NC=S" tag="NN" in="1:mod" out="-1:mod">estate</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod|1:appr">company</W>
<W msd="NP=S" tag="NNP" in="-1:appr" out="">Norden</W>
<W msd="VADR" tag="VBZ" in="" out="-5:subj|1:dobj|27:pnct">wants</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-7:[subj]|2:pred">grow</W>
<W msd="ANP" tag="RB" in="1:mod" out="">even</W>
<W msd="ANC" tag="JJR" in="-2:pred" out="-1:mod|1:pobj">bigger</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:vobj">than</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj|2:mod">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="">be</W>
<W msd="CS" tag="IN" in="-2:mod" out="1:nobj">after</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">merger</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:pobj|6:pnct|9:appa">one</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:possd">group's</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">companies</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="2:mod" out="">Public</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Limited</W>
<W msd="NC=S" tag="NN" in="-9:appa" out="-1:mod|-2:mod|1:mod">Company</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">of</W>
<W msd="AC" tag="CD" in="1:mod" out="">15</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod|1:nobj">April</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1980</W>
<W msd="XP" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="4:subj|6:[subj]" out="1:mod|2:mod|3:nobj">The</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">first</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="">interested</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="">companies</W>
<W msd="VADR" tag="VBP" in="" out="-4:subj|1:mod|2:vobj|3:pnct|4:mod|21:pnct">have</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">already</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-6:[subj]">appeared</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-4:mod" out="4:vobj">after</W>
<W msd="NP=S" tag="NNP" in="3:subj" out="">Norden</W>
<W msd="NC=S" tag="NN" in="2:mod" out="">yesterday</W>
<W msd="ANP" tag="RB" in="1:mod" out="">officially</W>
<W msd="VADA" tag="VBD" in="-4:vobj" out="-3:subj|-2:mod|-1:mod|1:dobj">announced</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="NC=P" tag="NNS" in="1:subj|2:[subj]" out="">negotiations</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|7:pobj">put</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">consolidation</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">company</W>
<W msd="SP" tag="IN" in="-7:pobj" out="1:nobj">into</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">place</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="XP" tag="&quot;" in="4:pnct" out="">"</W>
<W msd="NP=S" tag="NNP" in="3:subj|4:[subj]" out="1:coord">Hafnia</W>
<W msd="CC" tag="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NP=S" tag="NNP" in="-1:conj" out="">Norden</W>
<W msd="VADR" tag="VBP" in="9:qobj" out="-4:pnct|-3:subj|1:vobj|7:pnct|8:pnct">are</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-4:[subj]|1:dobj|3:pred">leaving</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">door</W>
<W msd="ANP" tag="JJ" in="-3:pred" out="1:mod">open</W>
<W msd="U=" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">others</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="XP" tag="&quot;" in="-8:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="" out="-9:qobj|2:subj|15:pnct">says</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Preben</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef|1:pnct|2:ref|3:rel">Nygaard</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W msd="VADR" tag="VBZ" in="-3:rel" out="-1:subj|1:pred">is</W>
<W msd="NC=S" tag="NN" in="-1:pred" out="1:pobj">director</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="2:possd|4:appr">Norden's</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">parent</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-1:mod">company</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Commercial</W>
<W msd="NP=S" tag="NNP" in="-4:appr" out="-1:mod|1:mod|2:nobj">Holding</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">International</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">A/S</W>
<W msd="XP" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W msd="CS" tag="IN" in="5:mod" out="1:nobj|3:pnct">After</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">merger</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:subj|2:[subj]" out="">Hafnia</W>
<W msd="VA" tag="MD" in="" out="-5:mod|-1:subj|1:vobj|20:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:mod|5:dobj">have</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">its</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">disposal</W>
<W msd="ANP" tag="RB" in="1:mod" out="">approximately</W>
<W msd="AC" tag="CD" in="-5:dobj" out="-1:mod|1:nobj">40</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">percent</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">shares</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pnct|2:ref|3:rel">Norden</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-2:ref|1:subj|2:[subj]" out="">which</W>
<W msd="VA" tag="MD" in="-3:rel" out="-1:subj|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W msd="PD" tag="DT" in="-1:pred" out="1:mod|2:nobj">the</W>
<W msd="VAG" tag="VBG" in="-1:mod" out="">continuing</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">company</W>
<W msd="XP" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="2:conj|24:pnct">But</W>
<W msd="PP" tag="PRP" in="1:subj" out="4:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-2:conj" out="-1:subj|1:pred">is</W>
<W msd="PD" tag="DT" in="-1:pred" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">intent</W>
<W msd="SP" tag="IN" in="-4:nobj" out="3:vobj">that</W>
<W msd="NP=S" tag="NNP" in="2:subj|4:[subj]|5:[subj]" out="1:possd">Hafnia's</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">shares</W>
<W msd="VA" tag="MD" in="-3:vobj" out="-2:subj|1:mod|2:vobj|8:mod">will</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">gradually</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-4:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]|1:avobj">throttled</W>
<W msd="ANP" tag="RB" in="-1:avobj" out="1:mod">down</W>
<W msd="U=" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">25</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">percent</W>
<W msd="CS" tag="IN" in="-8:mod" out="4:vobj">as</W>
<W msd="PD" tag="DT" in="3:subj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">new</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">companies</W>
<W msd="VADR" tag="VBP" in="-4:vobj" out="-3:subj|1:lobj">come</W>
<W msd="SP" tag="IN" in="-1:lobj" out="1:nobj">through</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">door</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj" out="5:nobj">It</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:mod|2:pred|14:pnct">is</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">not</W>
<W msd="PD" tag="DT" in="-2:pred" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">intent</W>
<W msd="SP" tag="IN" in="-5:nobj" out="2:vobj">that</W>
<W msd="NP=S" tag="NNP" in="1:subj|2:[subj]" out="">Hafnia</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|3:dobj">have</W>
<W msd="ANP" tag="RB" in="1:mod" out="">too</W>
<W msd="ANP" tag="JJ" in="1:mod" out="-1:mod">great</W>
<W msd="PI" tag="DT" in="-3:dobj" out="-1:mod|1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">say</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">it</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="JJ" in="2:mod" out="">Future</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">merger</W>
<W msd="NC=P" tag="NNS" in="1:subj|4:[subj]|5:[subj]" out="-1:mod|-2:mod">partners</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|1:mod|2:pred|6:mod|16:pnct">are</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">not</W>
<W msd="U=" tag="TO" in="-2:pred" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-4:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]|1:part">chased</W>
<W msd="ANP" tag="RB" in="-1:part" out="">away</W>
<W msd="SP" tag="IN" in="-6:mod" out="1:nobj">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">fear</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:pred">being</W>
<W msd="ANP" tag="JJ" in="-1:pred" out="1:pobj">subject</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">control</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">others</W>
<W msd="XP" tag="." in="-16:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="1:conj">Or</W>
<W msd="SP" tag="IN" in="-1:conj" out="2:nobj">in</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Preben</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:namef|1:possd|2:pnct|13:xpl">Nygaard's</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">words</W>
<W msd="XP" tag=":" in="-2:pnct" out="">:</W>
</s>
<s>
<W msd="XP" tag="&quot;" in="8:pnct" out="">"</W>
<W msd="CS" tag="IN" in="7:mod" out="2:vobj">If</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Hafnia</W>
<W msd="VADR" tag="VBZ" in="-2:vobj" out="-1:subj|1:dobj|3:pnct">has</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">majority</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">it</W>
<W msd="VA" tag="MD" in="-13:xpl" out="-8:pnct|-7:mod|-1:subj|1:vobj|4:pnct#|5:pnct">may</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|2:vobj">make</W>
<W msd="NC=P" tag="NNS" in="-1:dobj|1:[subj]" out="">others</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-1:[subj]|1:lobj">stay</W>
<W msd="AC" tag="CD" in="-1:lobj|-4:pnct#" out="">away.</W>
<W msd="XP" tag="&quot;" in="-5:pnct" out="">"</W>
</s>
