<s>
<W msd="NP=S" tag="NNP" in="" out="1:pnct|3:xpl|9:pnct">Guide</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">:</W>
<W msd="U=" tag="EX" in="1:expl" out="">There</W>
<W msd="VADR" tag="VBZ" in="-3:xpl" out="-1:expl|1:dobj">IS</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="1:pobj">life</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">in</W>
<W msd="ANP" tag="JJ" in="2:attr|2:{source}" out="">Danish</W>
<W msd="NC=S" tag="NN" in="1:nobj.dobj|1:{patient}" out="">software</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-2:attr|-1:nobj.dobj|-1:{patient}|-2:{source}">development</W>
<W msd="XP" tag="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="CS" tag="IN" in="6:time" out="1:nobj|3:pnct">After</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">delay</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PI" tag="DT" in="2:subj|5:[subj]" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">program</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|-6:time|1:preds|19:pnct">is</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="1:nobj">ready</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-5:[subj]|1:dobj|2:@dir">help</W>
<W msd="NC=P" tag="NNS" in="-1:dobj" out="">customers</W>
<W msd="SP" tag="IN" in="-2:@dir" out="1:dir">around</W>
<W msd="SP" tag="IN" in="-1:dir" out="1:nobj">in</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:pnct|2:conj|3:pnct|5:conj|6:pnct|8:conj">museums</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="">supermarkets</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{loc}#" out="">city</W>
<W msd="NC=P" tag="NNS" in="-5:conj" out="-1:attr|-1:{loc}#">halls</W>
<W msd="XP" tag="&3a;" in="-6:pnct" out="">-</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="-8:conj" out="-1:coord|1:mod">MikroData</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Bella</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Centre</W>
<W msd="XP" tag="." in="-19:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W msd="NP=P" tag="NNPS" in="-1:nobj" out="">Europeans</W>
<W msd="VA" tag="MD" in="" out="-2:subj|1:vobj|4:pnct">should</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:preds">be</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="1:quant">intelligent</W>
<W msd="ANP" tag="RB" in="-1:quant" out="">enough</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="1:dobj" out="">So</W>
<W msd="VADR" tag="VBP" in="" out="-1:dobj|1:subj|25:pnct">believe</W>
<W msd="PD" tag="DT" in="-1:subj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{agent}#" out="">idea</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr|-1:{agent}#|1:pobj|1:{arg}">men</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">behind</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj|3:pnct|4:ref|12:relr">the</W>
<W msd="NP=S" tag="NNP" in="1:attr|1:{iden}" out="">Scout</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{iden}">program</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-4:ref|8:subj" out="">which</W>
<W msd="SP" tag="IN" in="7:loc" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">entrance</W>
<W msd="U=" tag="TO" in="-1:pobj|-1:{arg}" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="1:nobj|1:{arg}" out="">MikroData</W>
<W msd="ANP" tag="JJ" in="-2:nobj" out="-1:nobj|-1:{arg}">fair</W>
<W msd="NC=P" tag="NNS" in="-12:relr" out="-8:subj|-7:loc|1:dobj|3:loc">guides</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">way</W>
<W msd="SP" tag="IN" in="-3:loc" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:attr|1:{const}">jungle</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{const}" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">exhibitors</W>
<W msd="XP" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="8:add" out="26:pnct">And</W>
<W msd="SP" tag="IN" in="7:inst" out="1:nobj|5:pnct">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">that</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}#">word</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}#" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">praise</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj" out="">they</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|-8:add|-7:inst|1:dobj">indicate</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">they</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|2:pobj">leave</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="3:nobj">it</W>
<W msd="U=" tag="TO" in="-2:pobj" out="1:nobj">to</W>
<W msd="PP" tag="PRP" in="-1:nobj|2:[subj]" out="">us</W>
<W msd="U=" tag="TO" in="-3:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|3:inst">do</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">spelling</W>
<W msd="SP" tag="IN" in="-3:inst" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">help</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">keyboard</W>
<W msd="XP" tag="." in="-26:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="3:neg" out="">Nor</W>
<W msd="SP" tag="IN" in="2:inst" out="1:nobj">with</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Scout</W>
<W msd="VA" tag="MD" in="" out="-3:neg|-2:inst|1:expl|2:vobj|9:pnct|10:xpl">should</W>
<W msd="U=" tag="EX" in="-1:expl|1:[expl]" out="">there</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-1:[expl]|1:dobj">be</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">any</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj#">way</W>
<W msd="SP" tag="IN" in="-1:pobj#" out="1:nobj">of</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:dobj">making</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">mistake</W>
<W msd="XP" tag="&3a;" in="-9:pnct" out="">:</W>
<W msd="NP=S" tag="NNP" in="-10:xpl" out="1:part|2:dobj|8:conj|18:conj|28:pnct">Type</W>
<W msd="SP" tag="IN" in="-1:part" out="">in</W>
<W msd="PD" tag="DT" in="-2:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">name</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">firm</W>
<W msd="CC" tag="CC" in="1:coord" out="">or</W>
<W msd="NC=S" tag="NN" in="-8:conj" out="-1:coord|1:part|2:dobj">type</W>
<W msd="SP" tag="IN" in="-1:part" out="">in</W>
<W msd="PI" tag="DT" in="-2:dobj" out="2:nobj">a</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{func}#" out="">search</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{func}#">word</W>
<W msd="CC" tag="CC" in="5:coord" out="">and</W>
<W msd="PD" tag="DT" in="4:subj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">screen</W>
<W msd="ANP" tag="RB" in="1:quant" out="">very</W>
<W msd="ANP" tag="RB" in="1:man" out="-1:quant">instructively</W>
<W msd="VADR" tag="VBZ" in="-18:conj" out="-4:subj|-5:coord|1:dobj|-1:man">shows</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:attr|2:nobj">the</W>
<W msd="ANS" tag="JJS" in="-1:attr" out="">nearest</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj|1:{arg}">route</W>
<W msd="U=" tag="TO" in="-1:pobj|-1:{arg}" out="1:nobj">to</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="2:conj">it</W>
<W msd="CC" tag="CC" in="1:coord" out="">or</W>
<W msd="PD" tag="DT" in="-2:conj" out="-1:coord|1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">relevant</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">stand</W>
<W msd="XP" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W msd="PI" tag="DT" in="2:subj" out="1:nobj">A</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">forerunner</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|1:dobj|9:pnct|6:time|2:loc">helped</W>
<W msd="NC=P" tag="NNS" in="-1:dobj" out="">visitors</W>
<W msd="SP" tag="IN" in="-2:loc" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">last</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">MikroData</W>
<W msd="AC" tag="CD" in="-6:time" out="1:nobj|2:part">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="ANP" tag="RB" in="-2:part" out="">ago</W>
<W msd="XP" tag="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">We</W>
<W msd="VADR" tag="VBP" in="23:qobj" out="-2:pnct|-1:subj|1:vobj|10:pnct|13:conj|21:pnct|22:pnct">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|2:man|6:inst">programmed</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">everything</W>
<W msd="SP" tag="IN" in="-2:man" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:part">bottom</W>
<W msd="RG" tag="RP" in="-1:part" out="">up</W>
<W msd="SP" tag="IN" in="-6:inst" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:name">Turbo</W>
<W msd="NP=S" tag="NNP" in="-1:name" out="">Pascal</W>
<W msd="XP" tag="," in="-10:pnct" out="">,</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="PD" tag="DT" in="1:subj|3:[subj]" out="">this</W>
<W msd="VADR" tag="VBZ" in="-13:conj" out="-1:subj|-2:coord|2:vobj|1:epi">has</W>
<W msd="ANP" tag="RB" in="-1:epi" out="">probably</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-3:[subj]|1:dobj|2:pobj">robbed</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="">us</W>
<W msd="SP" tag="IN" in="-2:pobj" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">little</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">time</W>
<W msd="XP" tag="," in="-21:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-22:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="" out="-23:qobj|2:subj|13:pnct">says</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">John</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef|1:attr|1:{source}">Marrot</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{source}" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|3:pnct|4:ref|5:relr">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:appr">firm</W>
<W msd="NP=S" tag="NNP" in="-1:appr" out="">Scansoft</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-4:ref|1:subj" out="">which</W>
<W msd="VADR" tag="VBZ" in="-5:relr" out="-1:subj|1:preds">is</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj">behind</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">programming</W>
<W msd="XP" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="17:time" out="1:pnct">Originally</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PO" tag="PRP$" in="15:subj|16:[subj]|1:{arg}" out="1:possd|3:appr|4:pnct|5:ref|6:relr">his</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:{arg}">acquaintance</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Steen</W>
<W msd="NP=S" tag="NNP" in="-3:appr" out="-1:namef">Olsen</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-5:ref|1:subj" out="">who</W>
<W msd="VADR" tag="VBZ" in="-6:relr" out="-1:subj|8:pnct|1:@loc">works</W>
<W msd="SP" tag="IN" in="-1:@loc" out="1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="3:nobj|4:attr|4:{loc}">an</W>
<W msd="NC=S" tag="NN" in="1:nobj.dobj|1:{recipient}#" out="">office</W>
<W msd="NC=P" tag="NNS" in="1:attr|1:{func}#" out="-1:nobj.dobj|-1:{recipient}#">supplies</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:attr|-1:{func}#">firm</W>
<W msd="SP" tag="IN" in="-4:attr|-4:{loc}" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Copenhagen</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="VADA" tag="VBD" in="" out="-15:subj|1:vobj|11:pnct|-17:time">had</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-16:[subj]|1:dobj|3:other">ordered</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">program</W>
<W msd="SP" tag="IN" in="-3:other" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">price</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="AC" tag="CD" in="-1:nobj" out="2:nobj">100</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{goal}#" out="">programming</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr|-1:{goal}#">hours</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="3:subj" out="1:nobj">These</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">100</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">hours</W>
<W msd="VADA" tag="VBD" in="" out="-3:subj|2:preds|4:pnct|1:contr">became</W>
<W msd="ANP" tag="RB" in="-1:contr" out="">instead</W>
<W msd="AC" tag="CD" in="-2:preds" out="1:nobj">5,000</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">hours</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
