<s>
<W id="1" msd="NP=S" tag="NNP" in="" out="">Guide</W>
<W id="2" msd="XP" tag="&3a;" in="" out="">:</W>
<W id="3" msd="U=" tag="EX" in="" out="">There</W>
<W id="4" msd="VADR" tag="VBZ" in="" out="">IS</W>
<W id="5" msd="NC=S" tag="NN" in="" out="">life</W>
<W id="6" msd="SP" tag="IN" in="" out="">in</W>
<W id="7" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="8" msd="NC=S" tag="NN" in="" out="">software</W>
<W id="9" msd="NC=S" tag="NN" in="" out="">development</W>
<W id="10" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="13" msd="CS" tag="IN" in="" out="">After</W>
<W id="14" msd="PI" tag="DT" in="" out="">a</W>
<W id="15" msd="NC=S" tag="NN" in="" out="">delay</W>
<W id="16" msd="XP" tag="," in="" out="">,</W>
<W id="17" msd="PI" tag="DT" in="" out="">a</W>
<W id="18" msd="NC=S" tag="NN" in="" out="">program</W>
<W id="19" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="20" msd="ANP" tag="JJ" in="" out="">ready</W>
<W id="21" msd="U=" tag="TO" in="" out="">to</W>
<W id="22" msd="VAF" tag="VB" in="" out="">help</W>
<W id="23" msd="NC=P" tag="NNS" in="" out="">customers</W>
<W id="24" msd="SP" tag="IN" in="" out="">around</W>
<W id="25" msd="SP" tag="IN" in="" out="">in</W>
<W id="26" msd="NC=P" tag="NNS" in="" out="">museums</W>
<W id="27" msd="XP" tag="," in="" out="">,</W>
<W id="28" msd="NC=P" tag="NNS" in="" out="">supermarkets</W>
<W id="29" msd="XP" tag="," in="" out="">,</W>
<W id="30" msd="NC=S" tag="NN" in="" out="">city</W>
<W id="31" msd="NC=P" tag="NNS" in="" out="">halls</W>
<W id="32" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="33" msd="CC" tag="CC" in="" out="">and</W>
<W id="34" msd="NP=S" tag="NNP" in="" out="">MikroData</W>
<W id="35" msd="SP" tag="IN" in="" out="">in</W>
<W id="36" msd="NP=S" tag="NNP" in="" out="">Bella</W>
<W id="37" msd="NP=S" tag="NNP" in="" out="">Centre</W>
<W id="38" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="41" msd="PD" tag="DT" in="" out="">The</W>
<W id="42" msd="NP=P" tag="NNPS" in="" out="">Europeans</W>
<W id="43" msd="VA" tag="MD" in="" out="">should</W>
<W id="44" msd="VAF" tag="VB" in="" out="">be</W>
<W id="45" msd="ANP" tag="JJ" in="" out="">intelligent</W>
<W id="46" msd="ANP" tag="RB" in="" out="">enough</W>
<W id="47" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="50" msd="ANP" tag="RB" in="" out="">So</W>
<W id="51" msd="VADR" tag="VBP" in="" out="">believe</W>
<W id="52" msd="PD" tag="DT" in="" out="">the</W>
<W id="53" msd="NC=S" tag="NN" in="" out="">idea</W>
<W id="54" msd="NC=P" tag="NNS" in="" out="">men</W>
<W id="55" msd="SP" tag="IN" in="" out="">behind</W>
<W id="56" msd="PD" tag="DT" in="" out="">the</W>
<W id="57" msd="NP=S" tag="NNP" in="" out="">Scout</W>
<W id="58" msd="NC=S" tag="NN" in="" out="">program</W>
<W id="59" msd="XP" tag="," in="" out="">,</W>
<W id="60" msd="PT" tag="WDT" in="" out="">which</W>
<W id="61" msd="SP" tag="IN" in="" out="">at</W>
<W id="62" msd="PD" tag="DT" in="" out="">the</W>
<W id="63" msd="NC=S" tag="NN" in="" out="">entrance</W>
<W id="64" msd="U=" tag="TO" in="" out="">to</W>
<W id="65" msd="PD" tag="DT" in="" out="">the</W>
<W id="66" msd="NP=S" tag="NNP" in="" out="">MikroData</W>
<W id="67" msd="ANP" tag="JJ" in="" out="">fair</W>
<W id="68" msd="NC=P" tag="NNS" in="" out="">guides</W>
<W id="69" msd="PD" tag="DT" in="" out="">the</W>
<W id="70" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="71" msd="SP" tag="IN" in="" out="">in</W>
<W id="72" msd="PD" tag="DT" in="" out="">the</W>
<W id="73" msd="NC=S" tag="NN" in="" out="">jungle</W>
<W id="74" msd="SP" tag="IN" in="" out="">of</W>
<W id="75" msd="NC=P" tag="NNS" in="" out="">exhibitors</W>
<W id="76" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="79" msd="CC" tag="CC" in="" out="">And</W>
<W id="80" msd="SP" tag="IN" in="" out="">with</W>
<W id="81" msd="PD" tag="DT" in="" out="">that</W>
<W id="82" msd="NC=S" tag="NN" in="" out="">word</W>
<W id="83" msd="SP" tag="IN" in="" out="">of</W>
<W id="84" msd="NC=S" tag="NN" in="" out="">praise</W>
<W id="85" msd="XP" tag="," in="" out="">,</W>
<W id="86" msd="PP" tag="PRP" in="" out="">they</W>
<W id="87" msd="VADR" tag="VBP" in="" out="">indicate</W>
<W id="88" msd="SP" tag="IN" in="" out="">that</W>
<W id="89" msd="PP" tag="PRP" in="" out="">they</W>
<W id="90" msd="VA" tag="MD" in="" out="">will</W>
<W id="91" msd="VAF" tag="VB" in="" out="">leave</W>
<W id="92" msd="PP" tag="PRP" in="" out="">it</W>
<W id="93" msd="U=" tag="TO" in="" out="">to</W>
<W id="94" msd="PP" tag="PRP" in="" out="">us</W>
<W id="95" msd="U=" tag="TO" in="" out="">to</W>
<W id="96" msd="VAF" tag="VB" in="" out="">do</W>
<W id="97" msd="PD" tag="DT" in="" out="">the</W>
<W id="98" msd="NC=S" tag="NN" in="" out="">spelling</W>
<W id="99" msd="SP" tag="IN" in="" out="">with</W>
<W id="100" msd="PD" tag="DT" in="" out="">the</W>
<W id="101" msd="NC=S" tag="NN" in="" out="">help</W>
<W id="102" msd="SP" tag="IN" in="" out="">of</W>
<W id="103" msd="PD" tag="DT" in="" out="">the</W>
<W id="104" msd="NC=S" tag="NN" in="" out="">keyboard</W>
<W id="105" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="108" msd="CC" tag="CC" in="" out="">Nor</W>
<W id="109" msd="SP" tag="IN" in="" out="">with</W>
<W id="110" msd="NP=S" tag="NNP" in="" out="">Scout</W>
<W id="111" msd="VA" tag="MD" in="" out="">should</W>
<W id="112" msd="U=" tag="EX" in="" out="">there</W>
<W id="113" msd="VAF" tag="VB" in="" out="">be</W>
<W id="114" msd="PD" tag="DT" in="" out="">any</W>
<W id="115" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="116" msd="SP" tag="IN" in="" out="">of</W>
<W id="117" msd="VAG" tag="VBG" in="" out="">making</W>
<W id="118" msd="PI" tag="DT" in="" out="">a</W>
<W id="119" msd="NC=S" tag="NN" in="" out="">mistake</W>
<W id="120" msd="XP" tag="&3a;" in="" out="">:</W>
<W id="121" msd="NP=S" tag="NNP" in="" out="">Type</W>
<W id="122" msd="SP" tag="IN" in="" out="">in</W>
<W id="123" msd="PD" tag="DT" in="" out="">the</W>
<W id="124" msd="NC=S" tag="NN" in="" out="">name</W>
<W id="125" msd="SP" tag="IN" in="" out="">of</W>
<W id="126" msd="PI" tag="DT" in="" out="">a</W>
<W id="127" msd="NC=S" tag="NN" in="" out="">firm</W>
<W id="128" msd="CC" tag="CC" in="" out="">or</W>
<W id="129" msd="NC=S" tag="NN" in="" out="">type</W>
<W id="130" msd="SP" tag="IN" in="" out="">in</W>
<W id="131" msd="PI" tag="DT" in="" out="">a</W>
<W id="132" msd="NC=S" tag="NN" in="" out="">search</W>
<W id="133" msd="NC=S" tag="NN" in="" out="">word</W>
<W id="134" msd="CC" tag="CC" in="" out="">and</W>
<W id="135" msd="PD" tag="DT" in="" out="">the</W>
<W id="136" msd="NC=S" tag="NN" in="" out="">screen</W>
<W id="137" msd="ANP" tag="RB" in="" out="">very</W>
<W id="138" msd="ANP" tag="RB" in="" out="">instructively</W>
<W id="139" msd="VADR" tag="VBZ" in="" out="">shows</W>
<W id="140" msd="PD" tag="DT" in="" out="">the</W>
<W id="141" msd="ANS" tag="JJS" in="" out="">nearest</W>
<W id="142" msd="NC=S" tag="NN" in="" out="">route</W>
<W id="143" msd="U=" tag="TO" in="" out="">to</W>
<W id="144" msd="PP" tag="PRP" in="" out="">it</W>
<W id="145" msd="CC" tag="CC" in="" out="">or</W>
<W id="146" msd="PD" tag="DT" in="" out="">the</W>
<W id="147" msd="ANP" tag="JJ" in="" out="">relevant</W>
<W id="148" msd="NC=S" tag="NN" in="" out="">stand</W>
<W id="149" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="152" msd="PI" tag="DT" in="" out="">A</W>
<W id="153" msd="NC=S" tag="NN" in="" out="">forerunner</W>
<W id="154" msd="VADA" tag="VBD" in="" out="">helped</W>
<W id="155" msd="NC=P" tag="NNS" in="" out="">visitors</W>
<W id="156" msd="SP" tag="IN" in="" out="">at</W>
<W id="157" msd="PD" tag="DT" in="" out="">the</W>
<W id="158" msd="ANP" tag="JJ" in="" out="">last</W>
<W id="159" msd="NP=S" tag="NNP" in="" out="">MikroData</W>
<W id="160" msd="AC" tag="CD" in="" out="">two</W>
<W id="161" msd="NC=P" tag="NNS" in="" out="">years</W>
<W id="162" msd="ANP" tag="RB" in="" out="">ago</W>
<W id="163" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="166" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="167" msd="PP" tag="PRP" in="" out="">We</W>
<W id="168" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="169" msd="VAP" tag="VBN" in="" out="">programmed</W>
<W id="170" msd="NC=S" tag="NN" in="" out="">everything</W>
<W id="171" msd="SP" tag="IN" in="" out="">from</W>
<W id="172" msd="PD" tag="DT" in="" out="">the</W>
<W id="173" msd="NC=S" tag="NN" in="" out="">bottom</W>
<W id="174" msd="RG" tag="RP" in="" out="">up</W>
<W id="175" msd="SP" tag="IN" in="" out="">in</W>
<W id="176" msd="NP=S" tag="NNP" in="" out="">Turbo</W>
<W id="177" msd="NP=S" tag="NNP" in="" out="">Pascal</W>
<W id="178" msd="XP" tag="," in="" out="">,</W>
<W id="179" msd="CC" tag="CC" in="" out="">and</W>
<W id="180" msd="PD" tag="DT" in="" out="">this</W>
<W id="181" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="182" msd="ANP" tag="RB" in="" out="">probably</W>
<W id="183" msd="VAP" tag="VBN" in="" out="">robbed</W>
<W id="184" msd="PP" tag="PRP" in="" out="">us</W>
<W id="185" msd="SP" tag="IN" in="" out="">of</W>
<W id="186" msd="PI" tag="DT" in="" out="">a</W>
<W id="187" msd="ANP" tag="JJ" in="" out="">little</W>
<W id="188" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="189" msd="XP" tag="," in="" out="">,</W>
<W id="190" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="191" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="192" msd="NP=S" tag="NNP" in="" out="">John</W>
<W id="193" msd="NP=S" tag="NNP" in="" out="">Marrot</W>
<W id="194" msd="SP" tag="IN" in="" out="">from</W>
<W id="195" msd="PD" tag="DT" in="" out="">the</W>
<W id="196" msd="NC=S" tag="NN" in="" out="">firm</W>
<W id="197" msd="NP=S" tag="NNP" in="" out="">Scansoft</W>
<W id="198" msd="XP" tag="," in="" out="">,</W>
<W id="199" msd="PT" tag="WDT" in="" out="">which</W>
<W id="200" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="201" msd="SP" tag="IN" in="" out="">behind</W>
<W id="202" msd="PD" tag="DT" in="" out="">the</W>
<W id="203" msd="NC=S" tag="NN" in="" out="">programming</W>
<W id="204" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="207" msd="ANP" tag="RB" in="" out="">Originally</W>
<W id="208" msd="XP" tag="," in="" out="">,</W>
<W id="209" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="210" msd="NC=S" tag="NN" in="" out="">acquaintance</W>
<W id="211" msd="NP=S" tag="NNP" in="" out="">Steen</W>
<W id="212" msd="NP=S" tag="NNP" in="" out="">Olsen</W>
<W id="213" msd="XP" tag="," in="" out="">,</W>
<W id="214" msd="PT" tag="WP" in="" out="">who</W>
<W id="215" msd="VADR" tag="VBZ" in="" out="">works</W>
<W id="216" msd="SP" tag="IN" in="" out="">in</W>
<W id="217" msd="PI" tag="DT" in="" out="">an</W>
<W id="218" msd="NC=S" tag="NN" in="" out="">office</W>
<W id="219" msd="NC=P" tag="NNS" in="" out="">supplies</W>
<W id="220" msd="NC=S" tag="NN" in="" out="">firm</W>
<W id="221" msd="SP" tag="IN" in="" out="">in</W>
<W id="222" msd="NP=S" tag="NNP" in="" out="">Copenhagen</W>
<W id="223" msd="XP" tag="," in="" out="">,</W>
<W id="224" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="225" msd="VAP" tag="VBN" in="" out="">ordered</W>
<W id="226" msd="PD" tag="DT" in="" out="">the</W>
<W id="227" msd="NC=S" tag="NN" in="" out="">program</W>
<W id="228" msd="SP" tag="IN" in="" out="">for</W>
<W id="229" msd="PD" tag="DT" in="" out="">the</W>
<W id="230" msd="NC=S" tag="NN" in="" out="">price</W>
<W id="231" msd="SP" tag="IN" in="" out="">of</W>
<W id="232" msd="AC" tag="CD" in="" out="">100</W>
<W id="233" msd="NC=S" tag="NN" in="" out="">programming</W>
<W id="234" msd="NC=P" tag="NNS" in="" out="">hours</W>
<W id="235" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="238" msd="PD" tag="DT" in="" out="">These</W>
<W id="239" msd="AC" tag="CD" in="" out="">100</W>
<W id="240" msd="NC=P" tag="NNS" in="" out="">hours</W>
<W id="241" msd="VADA" tag="VBD" in="" out="">became</W>
<W id="242" msd="ANP" tag="RB" in="" out="">instead</W>
<W id="243" msd="AC" tag="CD" in="" out="">5,000</W>
<W id="244" msd="NC=P" tag="NNS" in="" out="">hours</W>
<W id="245" msd="XP" tag="." in="" out="">.</W>
</s>
