<s>
<W msd=":" in="3:pnct" out="">-</W>
<W msd="JJS" in="" out="">Most</W>
<W msd="NNS" in="" out="">people</W>
<W msd="VBP" in="" out="2:vobj|-3:pnct|1:mod|7:pnct|8:coord|16:pnct">do</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VB" in="-2:vobj" out="">have</W>
<W msd="DT" in="" out="">any</W>
<W msd="NN" in="" out="1:pobj">difficulty</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PRP" in="-1:nobj" out="">it</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="CC" in="-8:coord" out="2:conj">but</W>
<W msd="EX" in="1:expl" out="">there</W>
<W msd="VBP" in="-2:conj" out="-1:expl|1:mod|2:dobj">are</W>
<W msd="RB" in="-1:mod" out="">always</W>
<W msd="DT" in="-2:dobj" out="1:ref|2:rel">some</W>
<W msd="WP" in="-1:ref|1:subj" out="">who</W>
<W msd="VBP" in="-2:rel" out="-1:subj|1:pred">are</W>
<W msd="JJ" in="-1:pred" out="">slow</W>
<W msd="." in="-16:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj" out="4:ref|5:rel">They</W>
<W msd="VBP" in="" out="-1:subj|1:pred|42:pnct">are</W>
<W msd="DT" in="-1:pred" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">ones</W>
<W msd="WP" in="-4:ref|1:subj|3:[subj]|10:[subj]|12:[subj]" out="">who</W>
<W msd="VBP" in="-5:rel" out="-1:subj|2:vobj|8:coord">cannot</W>
<W msd="RB" in="1:mod" out="">physically</W>
<W msd="VBP" in="-2:vobj" out="-3:[subj]|1:dobj|-1:mod">do</W>
<W msd="DT" in="-1:dobj" out="3:mod|4:nobj">this</W>
<W msd="RB" in="2:mod" out="">otherwise</W>
<W msd="RB" in="1:mod" out="">very</W>
<W msd="JJ" in="-3:mod" out="-2:mod|-1:mod">simple</W>
<W msd="NN" in="-4:nobj" out="">task</W>
<W msd="CC" in="-8:coord" out="">but</W>
<W msd="VBP" in="" out="-10:[subj]">have</W>
<W msd="TO" in="" out="">to</W>
<W msd="VB" in="" out="-12:[subj]|1:lobj|12:mod">take</W>
<W msd="DT" in="-1:lobj" out="2:nobj">a</W>
<W msd="JJ" in="" out="">little</W>
<W msd="NN" in="-2:nobj" out="">trip</W>
<W msd="IN" in="" out="">over</W>
<W msd="TO" in="" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">logical</W>
<W msd="NN" in="-2:nobj" out="1:pobj">part</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">brain</W>
<W msd="TO" in="-12:mod" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:part|2:dobj">figure</W>
<W msd="IN" in="-1:part" out="">out</W>
<W msd="WP" in="-2:dobj|1:subj" out="1:rel|4:pnct|5:conj|8:coord">what</W>
<W msd="VBZ" in="-1:rel" out="-1:subj">is</W>
<W msd="DT" in="" out="">an</W>
<W msd="NN" in="" out="">arm</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="WP" in="-5:conj|1:subj" out="1:rel">what</W>
<W msd="VBZ" in="-1:rel" out="-1:subj|1:pred">is</W>
<W msd="NN" in="-1:pred" out="">right</W>
<W msd="CC" in="-8:coord" out="1:conj">and</W>
<W msd="WP" in="-1:conj|1:subj" out="1:rel">what</W>
<W msd="VBZ" in="-1:rel" out="-1:subj|1:pred">is</W>
<W msd="RP" in="-1:pred" out="">up</W>
<W msd="." in="-42:pnct" out="">.</W>
</s>
<s>
<W msd="CC" in="" out="6:conj">And</W>
<W msd="DT" in="" out="">that</W>
<W msd="VBZ" in="" out="">is</W>
<W msd="DT" in="" out="">the</W>
<W msd="NN" in="" out="">way</W>
<W msd="PRP" in="1:subj" out="">it</W>
<W msd="VBZ" in="-6:conj" out="-1:subj|1:mod|5:pnct|7:xpl">is</W>
<W msd="IN" in="-1:mod" out="2:nobj">for</W>
<W msd="RB" in="1:mod" out="">almost</W>
<W msd="DT" in="-2:nobj" out="-1:mod|1:nobj">all</W>
<W msd="NNS" in="-1:nobj" out="">tasks</W>
<W msd=":" in="-5:pnct" out="">:</W>
<W msd="PRP" in="1:subj|2:[subj]|3:[subj]" out="">They</W>
<W msd="MD" in="-7:xpl" out="-1:subj|1:vobj|6:pnct|7:coord|18:pnct">can</W>
<W msd="VB" in="-1:vobj" out="1:vobj|-2:[subj]|2:mod">be</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]">solved</W>
<W msd="IN" in="-2:mod" out="2:nobj">from</W>
<W msd="JJ" in="1:mod" out="">different</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">angles</W>
<W msd="," in="-6:pnct" out="">,</W>
<W msd="CC" in="-7:coord" out="2:conj">but</W>
<W msd="EX" in="1:expl" out="">there</W>
<W msd="VBZ" in="-2:conj" out="-1:expl|1:mod|2:dobj">is</W>
<W msd="RB" in="-1:mod" out="">always</W>
<W msd="CD" in="-2:dobj" out="1:nobj|2:ref|3:rel">one</W>
<W msd="NN" in="-1:nobj" out="">angle</W>
<W msd="WDT" in="-2:ref|1:subj" out="">that</W>
<W msd="VBZ" in="-3:rel" out="-1:subj">is</W>
<W msd="DT" in="" out="1:mod">the</W>
<W msd="JJS" in="-1:mod" out="">most</W>
<W msd="NN" in="" out="">expedient</W>
<W msd="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="RB" in="3:mod" out="4:mod|1:pnct">Therefore</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="PRP" in="1:subj" out="4:nobj">it</W>
<W msd="VBZ" in="12:qobj" out="-3:mod|-1:subj|2:pred|10:pnct">is</W>
<W msd="RB" in="-4:mod" out="">also</W>
<W msd="JJ" in="-2:pred" out="">important</W>
<W msd="TO" in="-4:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj">train</W>
<W msd="DT" in="-1:dobj" out="1:nobj">all</W>
<W msd="NNS" in="-1:nobj" out="1:pobj">aspects</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">brain</W>
<W msd="," in="-10:pnct" out="">,</W>
<W msd="PRP" in="1:subj" out="">he</W>
<W msd="VBZ" in="" out="-12:qobj|-1:subj|1:pnct">concludes</W>
<W msd="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="PRP$" in="3:subj|6:[subj]" out="1:mod|2:possd">His</W>
<W msd="JJ" in="-1:mod" out="">own</W>
<W msd="NN" in="-2:possd" out="">brain</W>
<W msd="VBZ" in="" out="1:mod|-3:subj|2:mod">is</W>
<W msd="RB" in="-1:mod" out="">actually</W>
<W msd="RBS" in="-2:mod" out="">most</W>
<W msd="VBN" in="" out="-6:[subj]">inclined</W>
<W msd="IN" in="" out="1:nobj|3:pnct">toward</W>
<W msd="DT" in="-1:nobj" out="1:mod">the</W>
<W msd="NN" in="-1:mod" out="">musical</W>
<W msd="." in="-3:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="7:mod" out="">Both</W>
<W msd="NN" in="" out="1:mod|12:pnct">music</W>
<W msd="IN" in="-1:mod" out="4:pnct|5:coord">in</W>
<W msd="DT" in="" out="1:mod">the</W>
<W msd="JJ" in="-1:mod" out="">narrow</W>
<W msd="NN" in="" out="">sense</W>
<W msd=":" in="-4:pnct" out="">-</W>
<W msd="CC" in="-5:coord" out="-7:mod|1:conj">and</W>
<W msd="IN" in="-1:conj" out="">in</W>
<W msd="DT" in="" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">sense</W>
<W msd="IN" in="" out="1:appr">of</W>
<W msd="NN" in="-1:appr" out="">creativity</W>
<W msd="." in="-12:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="10:mod" out="1:nobj">In</W>
<W msd="NN" in="-1:nobj" out="1:pnct">reality</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="PRP" in="1:subj" out="">he</W>
<W msd="VBZ" in="" out="-1:subj|1:pnct|6:qobj|18:pnct">believes</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="DT" in="4:subj" out="1:mod">a</W>
<W msd="VBN" in="-1:mod" out="">qualified</W>
<W msd="JJ" in="" out="">musical</W>
<W msd="NN" in="" out="">education</W>
<W msd="VBZ" in="-6:qobj" out="-10:mod|-4:subj">is</W>
<W msd="RBR" in="" out="">more</W>
<W msd="JJ" in="" out="1:pobj|7:pobj">important</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:mod">the</W>
<W msd="JJ" in="-1:mod" out="">early</W>
<W msd="NN" in="" out="">development</W>
<W msd="IN" in="" out="">of</W>
<W msd="NN" in="" out="">language</W>
<W msd="IN" in="-7:pobj" out="">than</W>
<W msd="JJ" in="" out="">Danish</W>
<W msd="NNS" in="" out="">lessons</W>
<W msd="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="" out="2:vobj|19:pnct">Because</W>
<W msd="NN" in="1:subj" out="">music</W>
<W msd="VBZ" in="-2:vobj" out="-1:subj|1:dobj">exercises</W>
<W msd="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">ability</W>
<W msd="TO" in="-1:pobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pnct|5:pobj">listen</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="RB" in="3:mod" out="">not</W>
<W msd="RB" in="" out="">only</W>
<W msd="RB" in="" out="">just</W>
<W msd="IN" in="-5:pobj" out="-3:mod|1:nobj|2:pnct|3:coord">for</W>
<W msd="NN" in="-1:nobj" out="">information</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="CC" in="-3:coord" out="1:conj">but</W>
<W msd="IN" in="-1:conj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="">a</W>
<W msd="JJ" in="" out="">unified</W>
<W msd="NN" in="" out="">whole</W>
<W msd="." in="-19:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="5:mod" out="1:nobj|2:pnct">In</W>
<W msd="NN" in="-1:nobj" out="">music</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="JJ" in="2:dobj" out="1:nobj">many</W>
<W msd="NNS" in="-1:nobj" out="">things</W>
<W msd="VBP" in="" out="-5:mod|-2:dobj|1:mod|3:pnct|4:coord|16:pnct">happen</W>
<W msd="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="RB" in="-1:nobj" out="">once</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="CC" in="-4:coord" out="2:conj">and</W>
<W msd="DT" in="1:subj" out="">this</W>
<W msd="VBZ" in="-2:conj" out="-1:subj|1:dobj">trains</W>
<W msd="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">ability</W>
<W msd="TO" in="-1:pobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|2:mod">shift</W>
<W msd="NN" in="-1:dobj" out="">focus</W>
<W msd="IN" in="-2:mod" out="1:nobj">without</W>
<W msd="VBG" in="-1:nobj" out="1:dobj">losing</W>
<W msd="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">overview</W>
<W msd="." in="-16:pnct" out="">.</W>
</s>
<s>
<W msd="CC" in="" out="2:conj|11:pnct">And</W>
<W msd="PRP" in="1:subj" out="">it</W>
<W msd="VBZ" in="-2:conj" out="-1:subj|5:pnct">facilitates</W>
<W msd="DT" in="" out="">the</W>
<W msd="NN" in="" out="">sense</W>
<W msd="IN" in="" out="">of</W>
<W msd="NN" in="" out="">language</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="IN" in="" out="">among</W>
<W msd="JJ" in="" out="">other</W>
<W msd="NNS" in="" out="">things</W>
<W msd="." in="-11:pnct" out="">.</W>
</s>
