<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">US</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:dobj|2:pobj|21:pnct">sees</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="6:nobj">it</W>
<W msd="CS" tag="IN" in="-2:pobj" out="1:obl">as</W>
<W msd="SP" tag="IN" in="-1:obl" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:attr|2:possd">its</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">clear</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="">interest</W>
<W msd="PT" tag="WDT" in="-6:nobj" out="2:vobj">that</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Europe</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-1:subj|7:mod|1:preds">become</W>
<W msd="PI" tag="DT" in="-1:preds" out="2:attr|5:nobj">a</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">strong</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="-1:mod|2:conj">political</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="-2:conj" out="-1:coord">economic</W>
<W msd="NC=S" tag="NN" in="-5:nobj" out="">factor</W>
<W msd="SP" tag="IN" in="-7:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">world</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">order</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|15:[subj]" out="">It</W>
<W msd="VA" tag="MD" in="" out="-1:subj|1:vobj|21:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|13:conj">ease</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj|2:attr|3:attr|4:possd">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">US's</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">own</W>
<W msd="ANP" tag="JJ" in="-3:attr" out="">global</W>
<W msd="NC=P" tag="NNS" in="-4:possd" out="">tasks</W>
<W msd="CC" tag="CC" in="7:coord" out="1:pnct">and</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="5:mod" out="1:nobj|4:pnct">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">same</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">time</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-13:conj" out="-15:[subj]|-5:mod|-7:coord|1:dobj">open</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">rich</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">market</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">American</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr">exports</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="27:conj|31:pnct">But</W>
<W msd="PD" tag="DT" in="26:subj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">prospect</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|2:pnct|3:attr|4:nobj|5:mod">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-3:attr" out="">unified</W>
<W msd="NP=S" tag="NNP" in="-4:nobj" out="">Europe</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj|9:coord|3:preds">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">EC</W>
<W msd="CS" tag="IN" in="-3:preds" out="1:nobj">as</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|4:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="2:conj">political</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="-2:conj" out="-1:coord">economic</W>
<W msd="NC=S" tag="NN" in="-4:nobj" out="">dynamo</W>
<W msd="CC" tag="CC" in="-9:coord" out="1:&lt;nobj&gt;|2:&lt;pred&gt;">and</W>
<W msd="NP=S" tag="NNP" in="-1:&lt;nobj&gt;" out="">Germany</W>
<W msd="CS" tag="IN" in="-2:&lt;pred&gt;" out="1:nobj">as</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:mod|3:attr|4:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="-2:mod" out="">leading</W>
<W msd="ANP" tag="JJ" in="-3:attr" out="">major</W>
<W msd="NC=S" tag="NN" in="-4:nobj" out="">power</W>
<W msd="ANP" tag="RB" in="1:mod" out="">nevertheless</W>
<W msd="VADR" tag="VBZ" in="-27:conj" out="-26:subj|-1:mod|1:dobj|3:preds">makes</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">some</W>
<W msd="NP=P" tag="NNPS" in="-1:nobj" out="">Americans</W>
<W msd="ANP" tag="JJ" in="-3:preds" out="">uncomfortable</W>
<W msd="XP" tag="." in="-31:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|4:[subj]" out="">They</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|1:vobj|3:conj|27:pnct">feel</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]">displaced</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VAF" tag="VB" in="-3:conj" out="-4:[subj]|-1:coord|1:dobj">see</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj" out="">they</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:preds">are</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj">about</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|2:mod">lose</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">influence</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pnct|2:ref|4:rel">Europe</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-2:ref|2:mod" out="">where</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">they</W>
<W msd="VADR" tag="VBP" in="-4:rel" out="-2:mod|-1:subj|1:vobj">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|3:dobj|5:mod">played</W>
<W msd="ANP" tag="RB" in="1:mod" out="">so</W>
<W msd="ANP" tag="JJ" in="1:attr" out="-1:mod">dominant</W>
<W msd="PI" tag="DT" in="-3:dobj" out="-1:attr|1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">role</W>
<W msd="SP" tag="IN" in="-5:mod" out="3:nobj">for</W>
<W msd="ANP" tag="JJ" in="2:attr" out="">almost</W>
<W msd="PD" tag="PDT" in="1:mod" out="">half</W>
<W msd="PI" tag="DT" in="-3:nobj" out="-1:mod|-2:attr|1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">century</W>
<W msd="XP" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="7:mod" out="1:nobj|5:pnct">In</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:attr|3:nobj">the</W>
<W msd="ANP" tag="RB" in="1:mod" out="">slightly</W>
<W msd="ANP" tag="RB" in="-2:attr" out="-1:mod">longer</W>
<W msd="VADR" tag="VBP" in="-3:nobj" out="">view</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj" out="">they</W>
<W msd="VADR" tag="VBP" in="" out="-7:mod|-1:subj|1:dobj|2:vobj|11:pnct|14:conj|21:pnct">see</W>
<W msd="NP=S" tag="NNP" in="-1:dobj|1:[subj]" out="">Europe</W>
<W msd="VAG" tag="VBG" in="-2:vobj" out="-1:[subj]|1:avobj|2:mod">rising</W>
<W msd="RG" tag="RP" in="-1:avobj" out="">up</W>
<W msd="CS" tag="IN" in="-2:mod" out="1:nobj">as</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|2:nobj|3:coord">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">political</W>
<W msd="ANP" tag="JJ" in="-2:nobj" out="">rival</W>
<W msd="CC" tag="CC" in="-3:coord" out="1:&lt;mod&gt;|2:&lt;nobj&gt;">and</W>
<W msd="ANP" tag="JJ" in="-1:&lt;mod&gt;" out="">economic</W>
<W msd="NC=S" tag="NN" in="-2:&lt;nobj&gt;" out="">competitor</W>
<W msd="XP" tag="," in="-11:pnct" out="">,</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="PD" tag="DT" in="1:subj|3:[subj]" out="">this</W>
<W msd="VADR" tag="VBZ" in="-14:conj" out="-1:subj|-2:coord|1:mod|2:vobj">does</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">not</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-3:[subj]|1:part|2:mod|3:mod">go</W>
<W msd="ANP" tag="RB" in="-1:part" out="">down</W>
<W msd="ANP" tag="RB" in="-2:mod" out="">well</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">with</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">everyone</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:subj|2:[subj]|10:[subj]|11:[subj]" out="">Europe</W>
<W msd="VA" tag="MD" in="" out="-1:subj|1:vobj|9:conj|27:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|2:dobj|3:mod">face</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">colossal</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="-1:attr">challenges</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="VAG" tag="VBG" in="-1:mod" out="">coming</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">years</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VA" tag="MD" in="-9:conj" out="-10:[subj]|-1:coord|1:vobj">must</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-11:[subj]|2:dobj|6:pobj">find</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">new</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="-1:attr|2:conj">paths</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="-1:coord">roles</W>
<W msd="PD" tag="DT" in="3:mod" out="">both</W>
<W msd="SP" tag="IN" in="-6:pobj" out="1:nobj|3:conj">for</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">itself</W>
<W msd="CC" tag="CC" in="1:coord" out="-3:mod">and</W>
<W msd="SP" tag="IN" in="-3:conj" out="-1:coord|1:nobj">for</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">its</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="1:pobj">relationship</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:mod|2:nobj">two</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">old</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">superpowers</W>
<W msd="XP" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="12:mod" out="1:nobj|8:pnct">From</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">each</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:attr|2:possd">its</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">own</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="1:pobj">corner</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">world</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="3:subj|4:[subj]" out="2:conj">Moscow</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:coord">Washington</W>
<W msd="VA" tag="MD" in="" out="-12:mod|-3:subj|1:vobj|15:pnct|16:mod|28:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-4:[subj]|1:dobj|4:mod">follow</W>
<W msd="NP=S" tag="NNP" in="-1:dobj" out="1:attr|2:possd">Europe's</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="">course</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">with</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">mix</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">benevolent</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|1:pnct|2:conj|4:conj">interest</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="">curiosity</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-4:conj" out="-1:coord">watchfulness</W>
<W msd="XP" tag="," in="-15:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-16:mod" out="7:vobj">while</W>
<W msd="PI" tag="DT" in="6:subj" out="1:attr|2:attr|3:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">global</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="1:pobj">field</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">tension</W>
<W msd="VADR" tag="VBZ" in="-7:vobj" out="-6:subj|1:preds">is</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj">about</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">take</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">shape</W>
<W msd="XP" tag="." in="-28:pnct" out="">.</W>
</s>
