<s>
<W id="1" msd="PP" tag="PRP" in="" out="">We</W>
<W id="2" msd="ANP" tag="RB" in="" out="">also</W>
<W id="3" msd="VADR" tag="VBP" in="" out="">want</W>
<W id="4" msd="U=" tag="TO" in="" out="">to</W>
<W id="5" msd="VAF" tag="VB" in="" out="">establish</W>
<W id="6" msd="ANP" tag="JJ" in="" out="">Nordic</W>
<W id="7" msd="NC=P" tag="NNS" in="" out="">contacts</W>
<W id="8" msd="XP" tag="," in="" out="">,</W>
<W id="9" msd="ANP" tag="RB" in="" out="">so</W>
<W id="10" msd="SP" tag="IN" in="" out="">that</W>
<W id="11" msd="PP" tag="PRP" in="" out="">we</W>
<W id="12" msd="VA" tag="MD" in="" out="">can</W>
<W id="13" msd="VAF" tag="VB" in="" out="">bring</W>
<W id="14" msd="ANP" tag="JJ" in="" out="">Norwegian</W>
<W id="15" msd="CC" tag="CC" in="" out="">and</W>
<W id="16" msd="ANP" tag="JJ" in="" out="">Swedish</W>
<W id="17" msd="SP" tag="IN" in="" out="">into</W>
<W id="18" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="19" msd="NC=S" tag="NN" in="" out="">education</W>
<W id="20" msd="SP" tag="IN" in="" out="">in</W>
<W id="21" msd="PI" tag="DT" in="" out="">a</W>
<W id="22" msd="ANC" tag="RBR" in="" out="">more</W>
<W id="23" msd="ANP" tag="JJ" in="" out="">interesting</W>
<W id="24" msd="CC" tag="CC" in="" out="">and</W>
<W id="25" msd="ANP" tag="JJ" in="" out="">natural</W>
<W id="26" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="27" msd="SP" tag="IN" in="" out="">than</W>
<W id="28" msd="PP" tag="PRP" in="" out="">we</W>
<W id="29" msd="VA" tag="MD" in="" out="">can</W>
<W id="30" msd="VAF" tag="VB" in="" out="">do</W>
<W id="31" msd="ANP" tag="RB" in="" out="">just</W>
<W id="32" msd="SP" tag="IN" in="" out="">by</W>
<W id="33" msd="NC=S" tag="NN" in="" out="">reading</W>
<W id="34" msd="NC=P" tag="NNS" in="" out="">texts</W>
<W id="35" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="38" msd="ANP" tag="JJ" in="" out="">Electronic</W>
<W id="39" msd="NC=S" tag="NN" in="" out="">network</W>
<W id="40" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="41" msd="CC" tag="CC" in="" out="">and</W>
<W id="42" msd="NC=S" tag="NN" in="" out="">network</W>
<W id="43" msd="SP" tag="IN" in="" out="">of</W>
<W id="44" msd="NC=P" tag="NNS" in="" out="">schools</W>
</s>
<s>
<W id="47" msd="PD" tag="DT" in="" out="">The</W>
<W id="48" msd="NC=P" tag="NNS" in="" out="">school's</W>
<W id="49" msd="VADR" tag="VBP" in="" out="">work</W>
<W id="50" msd="SP" tag="IN" in="" out="">with</W>
<W id="51" msd="ANP" tag="JJ" in="" out="">electronic</W>
<W id="52" msd="NC=S" tag="NN" in="" out="">mail</W>
<W id="53" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="54" msd="VAP" tag="VBN" in="" out="">made</W>
<W id="55" msd="ANP" tag="JJ" in="" out="">possible</W>
<W id="56" msd="SP" tag="IN" in="" out="">by</W>
<W id="57" msd="PI" tag="DT" in="" out="">a</W>
<W id="58" msd="NC=S" tag="NN" in="" out="">subscription</W>
<W id="59" msd="U=" tag="TO" in="" out="">to</W>
<W id="60" msd="PI" tag="DT" in="" out="">an</W>
<W id="61" msd="ANP" tag="JJ" in="" out="">electronic</W>
<W id="62" msd="NC=S" tag="NN" in="" out="">network</W>
<W id="63" msd="SP" tag="IN" in="" out="">with</W>
<W id="64" msd="NC=S" tag="NN" in="" out="">transit</W>
<W id="65" msd="NC=P" tag="NNS" in="" out="">nodes</W>
<W id="66" msd="PD" tag="DT" in="" out="">all</W>
<W id="67" msd="SP" tag="IN" in="" out="">over</W>
<W id="68" msd="PD" tag="DT" in="" out="">the</W>
<W id="69" msd="NC=S" tag="NN" in="" out="">world</W>
<W id="70" msd="XP" tag="," in="" out="">,</W>
<W id="71" msd="NP=S" tag="NNP" in="" out="">EARN</W>
<W id="72" msd="XP" tag="(" in="" out="">(</W>
<W id="73" msd="NP=S" tag="NNP" in="" out="">European</W>
<W id="74" msd="NP=S" tag="NNP" in="" out="">Academic</W>
<W id="75" msd="NP=S" tag="NNP" in="" out="">Research</W>
<W id="76" msd="NP=S" tag="NNP" in="" out="">Network</W>
<W id="77" msd="XP" tag=")" in="" out="">)</W>
<W id="78" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="81" msd="PP" tag="PRP" in="" out="">We</W>
<W id="82" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="83" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="84" msd="ANP" tag="JJ" in="" out="">fortunate</W>
<W id="85" msd="SP" tag="IN" in="" out="">in</W>
<W id="86" msd="VAG" tag="VBG" in="" out="">getting</W>
<W id="87" msd="NC=S" tag="NN" in="" out="">help</W>
<W id="88" msd="CC" tag="CC" in="" out="">and</W>
<W id="89" msd="NC=S" tag="NN" in="" out="">guidance</W>
<W id="90" msd="SP" tag="IN" in="" out="">from</W>
<W id="91" msd="AC" tag="CD" in="" out="">one</W>
<W id="92" msd="SP" tag="IN" in="" out="">of</W>
<W id="93" msd="PD" tag="DT" in="" out="">the</W>
<W id="94" msd="NC=P" tag="NNS" in="" out="">school's</W>
<W id="95" msd="NC=P" tag="NNS" in="" out="">parents</W>
<W id="96" msd="XP" tag="," in="" out="">,</W>
<W id="97" msd="NP=S" tag="NNP" in="" out="">Kirsten</W>
<W id="98" msd="NP=S" tag="NNP" in="" out="">Anttila</W>
<W id="99" msd="XP" tag="," in="" out="">,</W>
<W id="100" msd="PT" tag="WP" in="" out="">who</W>
<W id="101" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="102" msd="VAP" tag="VBN" in="" out="">connected</W>
<W id="103" msd="U=" tag="TO" in="" out="">to</W>
<W id="104" msd="PI" tag="DT" in="" out="">a</W>
<W id="105" msd="NC=S" tag="NN" in="" out="">research</W>
<W id="106" msd="NC=S" tag="NN" in="" out="">project</W>
<W id="107" msd="SP" tag="IN" in="" out="">on</W>
<W id="108" msd="NC=P" tag="NNS" in="" out="">informatics</W>
<W id="109" msd="SP" tag="IN" in="" out="">in</W>
<W id="110" msd="PD" tag="DT" in="" out="">the</W>
<W id="111" msd="NC=P" tag="NNS" in="" out="">school's</W>
<W id="112" msd="ANP" tag="JJ" in="" out="">subject</W>
<W id="113" msd="SP" tag="IN" in="" out="">at</W>
<W id="114" msd="PD" tag="DT" in="" out="">the</W>
<W id="115" msd="NP=S" tag="NNP" in="" out="">Danish</W>
<W id="116" msd="NP=S" tag="NNP" in="" out="">University</W>
<W id="117" msd="SP" tag="IN" in="" out="">of</W>
<W id="118" msd="NP=S" tag="NNP" in="" out="">Education</W>
<W id="119" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="122" msd="ANP" tag="RB" in="" out="">Here</W>
<W id="123" msd="XP" tag="," in="" out="">,</W>
<W id="124" msd="PP" tag="PRP" in="" out="">she</W>
<W id="125" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="126" msd="PD" tag="DT" in="" out="">the</W>
<W id="127" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="128" msd="NC=S" tag="NN" in="" out="">co-ordinator</W>
<W id="129" msd="SP" tag="IN" in="" out="">of</W>
<W id="130" msd="PI" tag="DT" in="" out="">a</W>
<W id="131" msd="NC=S" tag="NN" in="" out="">contact</W>
<W id="132" msd="NC=S" tag="NN" in="" out="">network</W>
<W id="133" msd="SP" tag="IN" in="" out="">of</W>
<W id="134" msd="NC=P" tag="NNS" in="" out="">schools</W>
<W id="135" msd="PD" tag="DT" in="" out="">all</W>
<W id="136" msd="SP" tag="IN" in="" out="">over</W>
<W id="137" msd="PD" tag="DT" in="" out="">the</W>
<W id="138" msd="NC=S" tag="NN" in="" out="">world</W>
<W id="139" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="142" msd="PP" tag="PRP" in="" out="">We</W>
<W id="143" msd="PP" tag="PRP" in="" out="">ourselves</W>
<W id="144" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="145" msd="ANP" tag="JJ" in="" out="">now</W>
<W id="146" msd="NC=S" tag="NN" in="" out="">part</W>
<W id="147" msd="SP" tag="IN" in="" out="">of</W>
<W id="148" msd="PD" tag="DT" in="" out="">the</W>
<W id="149" msd="NC=S" tag="NN" in="" out="">network</W>
<W id="150" msd="CS" tag="IN" in="" out="">as</W>
<W id="151" msd="PI" tag="DT" in="" out="">a</W>
<W id="152" msd="NC=S" tag="NN" in="" out="">contact</W>
<W id="153" msd="NC=S" tag="NN" in="" out="">school</W>
<W id="154" msd="CS" tag="IN" in="" out="">as</W>
<W id="155" msd="ANP" tag="RB" in="" out="">well</W>
<W id="156" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="159" msd="NP=P" tag="NNPS" in="" out="">Opportunities</W>
<W id="160" msd="SP" tag="IN" in="" out="">in</W>
<W id="161" msd="ANP" tag="JJ" in="" out="">many</W>
<W id="162" msd="NC=P" tag="NNS" in="" out="">subjects</W>
</s>
<s>
<W id="165" msd="PP" tag="PRP" in="" out="">We</W>
<W id="166" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="167" msd="XP" tag="," in="" out="">,</W>
<W id="168" msd="SP" tag="IN" in="" out="">for</W>
<W id="169" msd="ANP" tag="JJ" in="" out="">natural</W>
<W id="170" msd="NC=P" tag="NNS" in="" out="">reasons</W>
<W id="171" msd="XP" tag="," in="" out="">,</W>
<W id="172" msd="VAP" tag="VBN" in="" out="">begun</W>
<W id="173" msd="PD" tag="DT" in="" out="">the</W>
<W id="174" msd="NC=S" tag="NN" in="" out="">development</W>
<W id="175" msd="SP" tag="IN" in="" out="">of</W>
<W id="176" msd="PD" tag="DT" in="" out="">the</W>
<W id="177" msd="ANP" tag="JJ" in="" out="">electronic</W>
<W id="178" msd="NC=S" tag="NN" in="" out="">letter</W>
<W id="179" msd="VAG" tag="VBG" in="" out="">writing</W>
<W id="180" msd="SP" tag="IN" in="" out="">in</W>
<W id="181" msd="NC=P" tag="NNS" in="" out="">languages</W>
<W id="182" msd="XP" tag="," in="" out="">,</W>
<W id="183" msd="CC" tag="CC" in="" out="">but</W>
<W id="184" msd="U=" tag="EX" in="" out="">there</W>
<W id="185" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="186" msd="NC=P" tag="NNS" in="" out="">opportunities</W>
<W id="187" msd="SP" tag="IN" in="" out="">for</W>
<W id="188" msd="VAG" tag="VBG" in="" out="">bringing</W>
<W id="189" msd="SP" tag="IN" in="" out="">in</W>
<W id="190" msd="ANP" tag="JJ" in="" out="">international</W>
<W id="191" msd="NC=P" tag="NNS" in="" out="">contacts</W>
<W id="192" msd="SP" tag="IN" in="" out="">in</W>
<W id="193" msd="ANP" tag="JJ" in="" out="">many</W>
<W id="194" msd="NC=P" tag="NNS" in="" out="">subjects</W>
<W id="195" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="198" msd="SP" tag="IN" in="" out="">For</W>
<W id="199" msd="NC=S" tag="NN" in="" out="">example</W>
<W id="200" msd="XP" tag="," in="" out="">,</W>
<W id="201" msd="PP" tag="PRP" in="" out="">it</W>
<W id="202" msd="VADR" tag="VBZ" in="" out="">makes</W>
<W id="203" msd="ANP" tag="JJ" in="" out="">good</W>
<W id="204" msd="NC=S" tag="NN" in="" out="">sense</W>
<W id="205" msd="U=" tag="TO" in="" out="">to</W>
<W id="206" msd="VAF" tag="VB" in="" out="">use</W>
<W id="207" msd="NP=S" tag="NNP" in="" out="">one's</W>
<W id="208" msd="NP=S" tag="NNP" in="" out="">English</W>
<W id="209" msd="CC" tag="CC" in="" out="">or</W>
<W id="210" msd="NC=P" tag="NNS" in="" out="">one's</W>
<W id="211" msd="ANP" tag="JJ" in="" out="">German</W>
<W id="212" msd="SP" tag="IN" in="" out="">in</W>
<W id="213" msd="NC=S" tag="NN" in="" out="">connection</W>
<W id="214" msd="SP" tag="IN" in="" out="">with</W>
<W id="215" msd="PD" tag="DT" in="" out="">the</W>
<W id="216" msd="ANP" tag="JJ" in="" out="">Baltic</W>
<W id="217" msd="NC=S" tag="NN" in="" out="">project</W>
<W id="218" msd="XP" tag="." in="" out="">.</W>
</s>
