<s>
<W msd="NNP" in="" out="1:nobj">Subsection</W>
<W msd="VBG" in="-1:nobj" out="">5</W>
<W msd="DT" in="4:subj|5:[subj]" out="1:mod|3:nobj">The</W>
<W msd="NNP" in="-1:mod" out="">Danish</W>
<W msd="NNP" in="1:mod" out="">Consumer</W>
<W msd="NNP" in="-3:nobj" out="-1:mod">Council</W>
<W msd="MD" in="" out="-4:subj|1:vobj|23:pnct">may</W>
<W msd="VB" in="-1:vobj" out="-5:[subj]|1:dobj|10:mod">appeal</W>
<W msd="NNS" in="-1:dobj" out="1:mod">decisions</W>
<W msd="IN" in="-1:mod" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="2:nobj|3:coord">the</W>
<W msd="NN" in="1:mod" out="">district</W>
<W msd="NN" in="-2:nobj" out="-1:mod">council</W>
<W msd="CC" in="-3:coord" out="1:conj">and</W>
<W msd="DT" in="-1:conj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">county</W>
<W msd="NN" in="-2:nobj" out="-1:mod">council</W>
<W msd="TO" in="-10:mod" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:nobj">extent</W>
<W msd="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="PRP" in="1:subj" out="">they</W>
<W msd="VBP" in="-2:vobj" out="-1:subj|1:pred">are</W>
<W msd="NN" in="-1:pred" out="1:coord">material</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="IN" in="-1:conj" out="3:nobj">of</W>
<W msd="JJ" in="2:mod" out="">general</W>
<W msd="JJ" in="1:mod" out="">public</W>
<W msd="NN" in="-3:nobj" out="-1:mod|-2:mod">importance</W>
<W msd="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="" out="1:nobj">§</W>
<W msd="CD" in="-1:nobj" out="">100</W>
<W msd="JJ" in="1:mod" out="">Local</W>
<W msd="NNS" in="12:subj|13:[subj]" out="-1:mod|1:pnct|2:ref|5:rel">associations</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="WP$" in="-2:ref|3:subj" out="1:mod|2:possd">whose</W>
<W msd="JJ" in="-1:mod" out="">primary</W>
<W msd="NN" in="-2:possd" out="">purpose</W>
<W msd="VBZ" in="-5:rel" out="-3:subj|1:pred|6:pnct">is</W>
<W msd="DT" in="-1:pred" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">protection</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">environment</W>
<W msd="," in="-6:pnct" out="">,</W>
<W msd="MD" in="" out="-12:subj|1:vobj|10:pnct|11:modp|17:pnct">may</W>
<W msd="VB" in="-1:vobj" out="-13:[subj]|1:dobj">appeal</W>
<W msd="NNS" in="-1:dobj" out="2:ref|5:rel">decisions</W>
<W msd="IN" in="6:pobj" out="1:nobj">about</W>
<W msd="WDT" in="-2:ref|-1:nobj" out="">which</W>
<W msd="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">association</W>
<W msd="VBZ" in="-5:rel" out="-2:subj|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:dobj">requested</W>
<W msd="NN" in="-1:dobj" out="-6:pobj">information</W>
<W msd="," in="-10:pnct" out="">,</W>
<W msd="NN" in="-11:modp" out="1:pnct|4:nobj">cf</W>
<W msd="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="-4:nobj" out="1:nobj">§</W>
<W msd="CD" in="-1:nobj" out="">76</W>
<W msd="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="NNP" in="" out="1:nobj">Subsection</W>
<W msd="CD" in="-1:nobj" out="">2</W>
<W msd="JJ" in="1:mod" out="">Local</W>
<W msd="NNS" in="8:subj|10:[subj]" out="-1:mod|1:mod">divisions</W>
<W msd="IN" in="-1:mod" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">organizations</W>
<W msd="VBN" in="-2:mod" out="1:pobj">mentioned</W>
<W msd="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:nobj">§</W>
<W msd="CD" in="-1:nobj" out="">99</W>
<W msd="VBP" in="" out="-8:subj|1:mod|2:vobj|9:pnct">are</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VBN" in="-2:vobj" out="-10:[subj]|1:pobj">covered</W>
<W msd="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NN" in="-1:nobj" out="">provision</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:nobj">paragraph</W>
<W msd="CD" in="-1:nobj" out="">1</W>
<W msd="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="" out="1:nobj">§</W>
<W msd="CD" in="-1:nobj" out="">101</W>
<W msd="NNS" in="15:subj|16:[subj]|17:[subj]" out="1:mod">Actions</W>
<W msd="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="VB" in="-1:nobj" out="1:dobj">challenge</W>
<W msd="NNS" in="-1:dobj" out="1:mod">decisions</W>
<W msd="JJ" in="-1:mod" out="1:pobj">pursuant</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:coord">this</W>
<W msd="NN" in="-1:nobj" out="">law</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="NNS" in="-1:conj" out="1:mod">rules</W>
<W msd="VBD" in="-1:mod" out="1:mod">established</W>
<W msd="JJ" in="-1:mod" out="1:pobj">pursuant</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">law</W>
<W msd="MD" in="" out="-15:subj|1:vobj|14:pnct">must</W>
<W msd="VB" in="-1:vobj" out="-16:[subj]|1:vobj">be</W>
<W msd="VBD" in="-1:vobj" out="-17:[subj]|1:mod">commenced</W>
<W msd="IN" in="-1:mod" out="3:mod">within</W>
<W msd="CD" in="2:tobj" out="1:nobj">6</W>
<W msd="NNS" in="-1:nobj" out="">months</W>
<W msd="IN" in="-3:mod" out="-2:tobj|5:vobj">after</W>
<W msd="DT" in="4:subj|5:[subj]|6:[subj]" out="1:nobj|2:coord">the</W>
<W msd="NN" in="-1:nobj" out="">decision</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="NN" in="-1:conj" out="">ruling</W>
<W msd="VBZ" in="-5:vobj" out="-4:subj|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-5:[subj]|1:vobj">been</W>
<W msd="VBN" in="-1:vobj" out="-6:[subj]">reported</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="18:mod" out="5:vobj">If</W>
<W msd="DT" in="4:subj|5:[subj]|6:[subj]" out="1:nobj|2:coord">the</W>
<W msd="NN" in="-1:nobj" out="">decision</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="NN" in="-1:conj" out="">ruling</W>
<W msd="VBZ" in="-5:vobj" out="-4:subj|1:vobj|4:pnct">has</W>
<W msd="VBN" in="-1:vobj" out="-5:[subj]|1:vobj">been</W>
<W msd="VBN" in="-1:vobj" out="-6:[subj]|1:mod">promulgated</W>
<W msd="RB" in="-1:mod" out="">publicly</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="RB" in="8:mod" out="1:pnct">however</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="DT" in="6:subj|8:[subj]|9:[subj]" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">deadline</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="VBG" in="-1:nobj" out="1:dobj">commencing</W>
<W msd="DT" in="-1:dobj" out="1:nobj">an</W>
<W msd="NN" in="-1:nobj" out="">action</W>
<W msd="MD" in="" out="-8:mod|-18:mod|-6:subj|1:mod|2:vobj|9:pnct">shall</W>
<W msd="RB" in="-1:mod" out="">always</W>
<W msd="VB" in="-2:vobj" out="-8:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-9:[subj]|1:pobj">calculated</W>
<W msd="IN" in="-1:pobj" out="1:nobj">from</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">date</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">promulgation</W>
<W msd="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="NNP" in="" out="1:nobj">Subsection</W>
<W msd="CD" in="-1:nobj" out="">2</W>
<W msd="NNS" in="16:subj|18:[subj]|19:[subj]" out="1:ref|2:rel">Issues</W>
<W msd="WDT" in="-1:ref|1:subj|2:[subj]|3:[subj]" out="">that</W>
<W msd="MD" in="-2:rel" out="-1:subj|1:vobj|7:pnct|8:modp">may</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:pobj">determined</W>
<W msd="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">appraisal</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">authorities</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="NN" in="-8:modp" out="1:pnct|4:nobj|5:pnct#">cf</W>
<W msd="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="-4:nobj" out="1:nobj">Chapter</W>
<W msd="CD" in="-1:nobj|-5:pnct#" out="">8,</W>
<W msd="MD" in="" out="-16:subj|1:mod|2:vobj|7:pnct|8:mod|17:pnct">may</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VB" in="-2:vobj" out="-18:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-19:[subj]|1:pobj">brought</W>
<W msd="IN" in="-1:pobj" out="1:nobj">before</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">courts</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="IN" in="-8:mod" out="5:vobj">until</W>
<W msd="DT" in="4:subj|5:[subj]" out="3:nobj">the</W>
<W msd="NNP" in="2:mod" out="">Chief</W>
<W msd="NNP" in="1:mod" out="">Appraisal</W>
<W msd="NNP" in="-3:nobj" out="-2:mod|-1:mod">Commission</W>
<W msd="VBZ" in="-5:vobj" out="-4:subj|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-5:[subj]|1:dobj">issued</W>
<W msd="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="">decision</W>
<W msd="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="NNP" in="" out="1:nobj">Paragraph</W>
<W msd="CD" in="-1:nobj" out="">3</W>
<W msd="NNS" in="7:subj|8:[subj]|9:[subj]" out="1:pobj|3:mod">Actions</W>
<W msd="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="NN" in="-1:nobj" out="">expropriation</W>
<W msd="JJ" in="-3:mod" out="1:pobj">pursuant</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj">this</W>
<W msd="NN" in="-1:nobj" out="">law</W>
<W msd="MD" in="" out="-7:subj|1:vobj|14:pnct">must</W>
<W msd="VB" in="-1:vobj" out="-8:[subj]|1:vobj">be</W>
<W msd="VBD" in="-1:vobj" out="-9:[subj]|1:pobj">commenced</W>
<W msd="IN" in="-1:pobj" out="1:nobj">before</W>
<W msd="DT" in="-1:nobj" out="2:nobj|4:ref|8:rel">the</W>
<W msd="NNP" in="1:mod" out="">High</W>
<W msd="NNP" in="-2:nobj" out="-1:mod">Court</W>
<W msd="IN" in="6:lobj" out="1:nobj">under</W>
<W msd="WP$" in="-1:nobj|-4:ref" out="1:possd">whose</W>
<W msd="NN" in="-1:possd" out="">jurisdiction</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">property</W>
<W msd="VBZ" in="-8:rel" out="-2:subj|1:pred">is</W>
<W msd="VBN" in="-1:pred" out="-6:lobj">located</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="" out="1:nobj">Chapter</W>
<W msd="CD" in="-1:nobj" out="">12</W>
</s>
<s>
<W msd="NNP" in="1:mod" out="">Environmental</W>
<W msd="NNP" in="" out="-1:mod|1:pobj">Board</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNP" in="-1:nobj" out="">Appeal</W>
</s>
<s>
<W msd="NN" in="" out="1:nobj">§</W>
<W msd="CD" in="-1:nobj" out="">102</W>
<W msd="DT" in="5:subj|6:[subj]" out="1:mod|2:nobj">The</W>
<W msd="NNP" in="-1:mod" out="">Environmental</W>
<W msd="NNP" in="-2:nobj" out="1:pobj">Board</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNP" in="-1:nobj" out="">Appeal</W>
<W msd="MD" in="" out="-5:subj|1:vobj|14:pnct">shall</W>
<W msd="VB" in="-1:vobj" out="-6:[subj]|1:pred|7:mod">be</W>
<W msd="DT" in="-1:pred" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">appellate</W>
<W msd="NN" in="-2:nobj" out="1:pobj">instance</W>
<W msd="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="JJ" in="1:mod" out="">administrative</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">decisions</W>
<W msd="TO" in="-7:mod" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NN" in="-1:nobj" out="">extent</W>
<W msd="VBN" in="-2:mod" out="1:pobj">determined</W>
<W msd="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="NN" in="-1:nobj" out="">legislation</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
