<s>
<W msd="IN" in="7:mod" out="1:nobj|4:pnct">At</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">same</W>
<W msd="NN" in="-2:nobj" out="">time</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="DT" in="2:subj|3:[subj]" out="1:nobj">this</W>
<W msd="NN" in="-1:nobj" out="">power</W>
<W msd="VBZ" in="" out="-2:subj|1:vobj|3:pnct|-7:mod">has</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:pred">been</W>
<W msd="VBG" in="-1:pred" out="">demoralising</W>
<W msd="." in="-3:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="1:subj" out="">Nothing</W>
<W msd="VBZ" in="" out="-1:subj|50:pnct|2:pred">is</W>
<W msd="RBR" in="1:mod" out="9:pobj">more</W>
<W msd="JJ" in="-2:pred" out="1:pobj|-1:mod">dangerous</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NN" in="-1:nobj" out="1:coord">morality</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="DT" in="-1:conj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj">sense</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">justice</W>
<W msd="IN" in="-9:pobj" out="2:nobj">than</W>
<W msd="RB" in="1:mod" out="">constantly</W>
<W msd="VBG" in="-2:nobj" out="-1:mod|1:vobj">being</W>
<W msd="VBN" in="-1:vobj" out="1:coord|3:dobj">forced</W>
<W msd="CC" in="-1:coord" out="1:conj">or</W>
<W msd="VBD" in="-1:conj" out="1:[dobj]">enticed</W>
<W msd="TO" in="-3:dobj|-1:[dobj]" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|4:pobj|8:coord|17:pnct|18:coord">identify</W>
<W msd="NNS" in="-1:dobj" out="1:mod|2:possd">one's</W>
<W msd="JJ" in="-1:mod" out="">private</W>
<W msd="NN" in="-2:possd" out="">cause</W>
<W msd="IN" in="-4:pobj" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">Great</W>
<W msd="NNP" in="-2:nobj" out="">Cause</W>
<W msd="CC" in="-8:coord" out="1:conj">and</W>
<W msd="TO" in="-1:conj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|3:pobj">interpret</W>
<W msd="PRP$" in="-1:dobj" out="1:possd">its</W>
<W msd="NNS" in="-1:possd" out="">triumphs</W>
<W msd="IN" in="-3:pobj" out="1:nobj">as</W>
<W msd="NNS" in="-1:nobj" out="1:mod|2:possd">one's</W>
<W msd="JJ" in="-1:mod" out="">private</W>
<W msd="NN" in="-2:possd" out="">desert</W>
<W msd="," in="-17:pnct" out="">,</W>
<W msd="CC" in="-18:coord" out="1:conj">but</W>
<W msd="VB" in="-1:conj" out="1:dobj|5:pobj|7:pnct|8:mod">criminalize</W>
<W msd="DT" in="-1:dobj" out="1:nobj">all</W>
<W msd="NNS" in="-1:nobj" out="1:pobj">attacks</W>
<W msd="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="PRP" in="-1:nobj" out="">oneself</W>
<W msd="IN" in="-5:pobj" out="1:nobj">as</W>
<W msd="NN" in="-1:nobj" out="">sacrilege</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="IN" in="-8:mod" out="3:vobj">because</W>
<W msd="PRP" in="2:subj" out="">they</W>
<W msd="RB" in="1:mod" out="">also</W>
<W msd="VBP" in="-3:vobj" out="-2:subj|-1:mod|1:dobj">strike</W>
<W msd="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="">Cause</W>
<W msd="." in="-50:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="18:mod" out="8:vobj">Because</W>
<W msd="NNP" in="1:namef" out="">Georg</W>
<W msd="NNP" in="6:subj|8:[subj]" out="-1:namef">Brandes</W>
<W msd="TO" in="5:mod" out="2:nobj">to</W>
<W msd="JJ" in="1:mod" out="">such</W>
<W msd="DT" in="-2:nobj" out="1:mod|-1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">unique</W>
<W msd="NN" in="-2:nobj" out="">degree</W>
<W msd="VBD" in="-8:vobj" out="-6:subj|-5:mod|8:pnct|1:dobj">came</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pobj|-8:[subj]">act</W>
<W msd="IN" in="-1:pobj" out="1:nobj">like</W>
<W msd="DT" in="-1:nobj" out="1:nobj">this</W>
<W msd="NN" in="-1:nobj" out="1:pobj">sort</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">catalyst</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="PRP" in="1:subj|3:[subj]" out="">he</W>
<W msd="VBD" in="" out="-18:mod|-1:subj|1:mod|2:vobj|19:pnct">was</W>
<W msd="RB" in="-1:mod" out="">also</W>
<W msd="JJ" in="-2:vobj" out="-3:[subj]|1:pnct|7:pobj|3:modp">subject</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="RBR" in="1:mod" out="2:pobj">more</W>
<W msd="RB" in="-3:modp" out="-1:mod">intensely</W>
<W msd="IN" in="-2:pobj" out="1:nobj|2:pnct">than</W>
<W msd="JJS" in="-1:nobj" out="">most</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="TO" in="-7:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod|4:coord">the</W>
<W msd="NNS" in="-1:nobj" out="">dangers</W>
<W msd="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">power</W>
<W msd="CC" in="-4:coord" out="1:conj">and</W>
<W msd="DT" in="-1:conj" out="1:nobj|2:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">blessings</W>
<W msd="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">power</W>
<W msd="." in="-19:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|10:[subj]" out="">It</W>
<W msd="VBD" in="" out="-1:subj|1:dobj|2:pobj|8:coord|12:pnct|13:mod|35:coord|87:pnct">tempted</W>
<W msd="PRP" in="-1:dobj" out="">him</W>
<W msd="IN" in="-2:pobj" out="1:nobj">toward</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">a</W>
<W msd="VBG" in="-1:mod" out="">growing</W>
<W msd="NN" in="-2:nobj" out="1:coord">vanity</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NN" in="-1:conj" out="">sensitivity</W>
<W msd="CC" in="-8:coord" out="1:conj">and</W>
<W msd="VBN" in="-1:conj" out="-10:[subj]|1:dobj">threatened</W>
<W msd="PRP$" in="-1:dobj" out="1:possd">his</W>
<W msd="JJ" in="-1:possd" out="">self-understanding</W>
<W msd="," in="-12:pnct" out="">,</W>
<W msd="IN" in="-13:mod" out="2:vobj">so</W>
<W msd="PRP" in="1:subj" out="">he</W>
<W msd="VBD" in="-2:vobj" out="-1:subj|1:dobj|3:pobj">ended</W>
<W msd="PRP$" in="-1:dobj" out="1:possd">his</W>
<W msd="NNS" in="-1:possd" out="">days</W>
<W msd="IN" in="-3:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:mod|3:nobj|4:pnct|6:mod">a</W>
<W msd="NN" in="-1:mod" out="">grumpy</W>
<W msd="JJ" in="-2:mod" out="">old</W>
<W msd="NN" in="-3:nobj" out="">man</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="RB" in="1:mod" out="">personally</W>
<W msd="VBN" in="-6:mod" out="-1:mod|1:mod">wronged</W>
<W msd="IN" in="-1:mod" out="3:vobj">because</W>
<W msd="DT" in="2:subj|4:[subj]" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">world</W>
<W msd="VBD" in="-3:vobj" out="-2:subj|1:mod|2:vobj|5:pnct">had</W>
<W msd="RB" in="-1:mod" out="">indeed</W>
<W msd="VBN" in="-2:vobj" out="-4:[subj]|1:lobj">gone</W>
<W msd="TO" in="-1:lobj" out="1:nobj">to</W>
<W msd="NN" in="-1:nobj" out="">hell</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="CC" in="-35:coord" out="3:conj">but</W>
<W msd="PRP" in="2:subj|5:[subj]|9:[subj]" out="">it</W>
<W msd="RB" in="1:mod" out="">also</W>
<W msd="JJ" in="-3:conj" out="-2:subj|-1:mod|1:dobj|2:coord|6:coord">elevated</W>
<W msd="PRP" in="-1:dobj" out="">him</W>
<W msd="CC" in="-2:coord" out="1:conj">and</W>
<W msd="VBD" in="-1:conj" out="-5:[subj]|1:iobj|2:dobj">gave</W>
<W msd="PRP" in="-1:iobj" out="">him</W>
<W msd="NNS" in="-2:dobj" out="">wings</W>
<W msd="CC" in="-6:coord" out="1:conj">and</W>
<W msd="VBN" in="-1:conj" out="-9:[subj]|1:dobj|2:pobj">provided</W>
<W msd="PRP" in="-1:dobj" out="">him</W>
<W msd="IN" in="-2:pobj" out="18:pnct|19:mod|1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">satisfaction</W>
<W msd="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="RB" in="1:mod" out="">not</W>
<W msd="VBG" in="-2:nobj" out="-1:mod|1:dobj">commanding</W>
<W msd="NN" in="-1:dobj" out="1:nobj">anything</W>
<W msd="JJ" in="-1:nobj" out="1:pobj">other</W>
<W msd="IN" in="-1:pobj" out="1:nobj">than</W>
<W msd="NN" in="-1:nobj" out="2:coord">language</W>
<W msd="(" in="1:pnct" out="">(</W>
<W msd="CC" in="-2:coord" out="-1:pnct|1:mod|3:pnct|4:conj|6:pnct">and</W>
<W msd="IN" in="-1:mod" out="1:nobj">through</W>
<W msd="PRP" in="-1:nobj" out="">it</W>
<W msd=":" in="-3:pnct" out="">:</W>
<W msd="DT" in="-4:conj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">heart</W>
<W msd=")" in="-6:pnct" out="">)</W>
<W msd="," in="-18:pnct" out="">,</W>
<W msd="IN" in="-19:mod" out="1:nobj">by</W>
<W msd="VBG" in="-1:nobj" out="1:iobj|2:dobj">allowing</W>
<W msd="PRP" in="-1:iobj|2:[subj]" out="">him</W>
<W msd="TO" in="-2:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|3:pobj|-2:[subj]">develop</W>
<W msd="DT" in="-1:dobj" out="1:nobj">this</W>
<W msd="NN" in="-1:nobj" out="">language</W>
<W msd="IN" in="-3:pobj" out="1:nobj">into</W>
<W msd="CD" in="-1:nobj" out="1:pobj">one</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|8:mod">the</W>
<W msd="JJS" in="-1:mod" out="1:pnct|4:coord|3:conj">richest</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="RBS" in="1:mod" out="">most</W>
<W msd="JJ" in="-3:conj" out="-1:mod">beautiful</W>
<W msd="CC" in="-4:coord" out="2:conj">and</W>
<W msd="RBS" in="1:mod" out="">most</W>
<W msd="JJ" in="-2:conj" out="-1:mod">vital</W>
<W msd="IN" in="-8:mod" out="1:nobj">in</W>
<W msd="PRP$" in="-1:nobj" out="1:possd">our</W>
<W msd="NN" in="-1:possd" out="">literature</W>
<W msd="." in="-87:pnct" out="">.</W>
</s>
