<s>
<W msd="PRP" in="1:subj" out="">She</W>
<W msd="VBD" in="" out="-1:subj|1:pred|5:mod|8:pnct|9:mod|22:pnct">became</W>
<W msd="PRP$" in="-1:pred" out="1:possd">her</W>
<W msd="NNS" in="-1:possd" out="2:possd">team's</W>
<W msd="JJ" in="1:mod" out="">top</W>
<W msd="NN" in="-2:possd" out="-1:mod">scorer</W>
<W msd="IN" in="-5:mod" out="1:nobj">with</W>
<W msd="CD" in="-1:nobj" out="1:nobj">six</W>
<W msd="NNS" in="-1:nobj" out="">goals</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="IN" in="-9:mod" out="3:vobj">while</W>
<W msd="NNP" in="1:namef" out="">Betina</W>
<W msd="NNP" in="1:subj" out="-1:namef">Nørager</W>
<W msd="VBD" in="-3:vobj" out="-1:subj|1:pobj">accounted</W>
<W msd="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="DT" in="1:mod" out="">no</W>
<W msd="JJR" in="-2:nobj" out="-1:mod|1:pobj">fewer</W>
<W msd="IN" in="-1:pobj" out="1:nobj">than</W>
<W msd="CD" in="-1:nobj" out="1:pobj">eight</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">home</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">team's</W>
<W msd="." in="-22:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="14:mod" out="1:nobj|12:pnct">Despite</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">efforts</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NNP" in="-1:nobj" out="3:possd">Saturday's</W>
<W msd="NNP" in="1:mod" out="">IHF</W>
<W msd="NNP" in="1:mod" out="-1:mod">Cup</W>
<W msd="VB" in="-3:possd" out="-1:mod|1:pobj">match</W>
<W msd="IN" in="-1:pobj" out="2:nobj">against</W>
<W msd="JJ" in="1:mod" out="">Romanian</W>
<W msd="NNP" in="-2:nobj" out="-1:mod|1:name">Textila</W>
<W msd="NNP" in="-1:name" out="">Zalau</W>
<W msd="," in="-12:pnct" out="">,</W>
<W msd="NNP" in="1:subj" out="">Viborg</W>
<W msd="VBD" in="" out="-14:mod|-1:subj|1:pred|18:pnct">was</W>
<W msd="JJ" in="-1:pred" out="1:mod">strong</W>
<W msd="RB" in="-1:mod" out="1:nobj">enough</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:part|5:dobj|9:mod|11:mod">tear</W>
<W msd="RB" in="-1:part" out="">apart</W>
<W msd="JJ" in="3:mod" out="1:pobj">next</W>
<W msd="TO" in="-1:pobj" out="1:aobj">to</W>
<W msd="VB" in="-1:aobj" out="">last</W>
<W msd="VBD" in="-5:dobj" out="-3:mod|1:pnct|2:appa">ranked</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NNP" in="-2:appa" out="1:pnct">AIA</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="-9:mod" out="1:nobj">with</W>
<W msd="JJ" in="-1:nobj" out="">24-12</W>
<W msd="IN" in="-11:mod" out="1:nobj">at</W>
<W msd="NNP" in="-1:nobj" out="1:nobj">Grønløkke</W>
<W msd="NNP" in="-1:nobj" out="">Hall</W>
<W msd="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="NNP" in="1:subj" out="">AIA</W>
<W msd="VBD" in="" out="-1:subj|1:part|2:mod|4:coord|35:pnct">kept</W>
<W msd="RP" in="-1:part" out="">up</W>
<W msd="TO" in="-2:mod" out="1:nobj">to</W>
<W msd="VB" in="-1:nobj" out="">7-7</W>
<W msd="CC" in="-4:coord" out="1:pnct|7:conj">and</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="5:mod" out="1:nobj|3:pnct">at</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">break</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="NNP" in="1:subj" out="">Viborg</W>
<W msd="VBN" in="-7:conj" out="-5:mod|-1:subj|1:pobj|3:pnct#|4:coord">led</W>
<W msd="IN" in="-1:pobj" out="2:nobj">by</W>
<W msd="RB" in="1:mod" out="">only</W>
<W msd="CD" in="-2:nobj|-3:pnct#" out="-1:mod">12-9,</W>
<W msd="CC" in="-4:coord" out="7:conj">but</W>
<W msd="IN" in="6:mod" out="1:nobj|4:pnct">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">second</W>
<W msd="NN" in="-2:nobj" out="">half</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="EX" in="1:expl" out="">there</W>
<W msd="VBD" in="-7:conj" out="-6:mod|-1:expl|1:dobj">was</W>
<W msd="DT" in="-1:dobj" out="2:nobj|7:mod">a</W>
<W msd="NN" in="1:mod" out="">class</W>
<W msd="NN" in="-2:nobj" out="-1:mod|1:pobj">difference</W>
<W msd="IN" in="-1:pobj" out="1:nobj">between</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NNS" in="-1:nobj" out="">teams</W>
<W msd="IN" in="-7:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:mod">favour</W>
<W msd="IN" in="-1:mod" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">guests</W>
<W msd="." in="-35:pnct" out="">.</W>
</s>
<s>
<W msd="RB" in="3:mod" out="1:pnct">Here</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NNP" in="1:subj|3:[subj]" out="">AIA</W>
<W msd="VBD" in="" out="-3:mod|-1:subj|1:mod|2:vobj|7:pnct|8:mod|14:coord|33:pnct">did</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VB" in="-2:vobj" out="-3:[subj]|1:lobj">get</W>
<W msd="IN" in="-1:lobj" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="VBG" in="1:mod" out="">scoring</W>
<W msd="NN" in="-2:nobj" out="-1:mod">list</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="IN" in="-8:mod" out="2:vobj">until</W>
<W msd="EX" in="1:expl" out="">there</W>
<W msd="VBD" in="-2:vobj" out="-1:expl|1:dobj|3:vobj">were</W>
<W msd="CD" in="-1:dobj|2:[subj]" out="1:nobj">eight</W>
<W msd="NNS" in="-1:nobj" out="">minutes</W>
<W msd="VBG" in="-3:vobj" out="-2:[subj]">remaining</W>
<W msd="CC" in="-14:coord" out="1:pnct|13:conj">and</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="11:mod" out="1:nobj|3:pnct">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">meantime</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="NNP" in="7:subj|8:[subj]" out="">Viborg</W>
<W msd="IN" in="6:mod" out="1:nobj">with</W>
<W msd="CD" in="-1:nobj" out="1:nobj|2:pred">five</W>
<W msd="NNS" in="-1:nobj" out="">goals</W>
<W msd="IN" in="-2:pred" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="">row</W>
<W msd="VBD" in="-13:conj" out="-11:mod|-7:subj|-6:mod|1:vobj">had</W>
<W msd="VBN" in="-1:vobj" out="-8:[subj]|1:dobj|3:mod">increased</W>
<W msd="PRP$" in="-1:dobj" out="1:possd">its</W>
<W msd="NN" in="-1:possd" out="">lead</W>
<W msd="TO" in="-3:mod" out="1:nobj">to</W>
<W msd="CD" in="-1:nobj" out="">17-9</W>
<W msd="." in="-33:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="4:subj|6:[subj]" out="1:nobj">The</W>
<W msd="NNP" in="-1:nobj" out="1:appr">sternlight</W>
<W msd="NNP" in="-1:appr" out="">Roar</W>
<W msd="RB" in="1:mod" out="">likewise</W>
<W msd="VBD" in="" out="-4:subj|-1:mod|1:dobj|6:pnct|7:mod|31:pnct">had</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-6:[subj]|1:dobj">accept</W>
<W msd="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">clear</W>
<W msd="NN" in="-2:nobj" out="">defeat</W>
<W msd="," in="-6:pnct" out="">,</W>
<W msd="IN" in="-7:mod" out="8:vobj">as</W>
<W msd="NNP" in="7:subj" out="">Horsens</W>
<W msd="IN" in="6:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:pobj">front</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PRP$" in="-1:nobj" out="1:mod|2:possd">its</W>
<W msd="JJ" in="-1:mod" out="">own</W>
<W msd="NNS" in="-2:possd" out="">fans</W>
<W msd="VBN" in="-8:vobj" out="-7:subj|-6:mod|1:mod|2:nobj|8:mod">registered</W>
<W msd="RB" in="-1:mod" out="">only</W>
<W msd="PRP$" in="-2:nobj" out="1:mod|2:possd|3:mod">its</W>
<W msd="JJ" in="-1:mod" out="">third</W>
<W msd="NN" in="-2:possd" out="">victory</W>
<W msd="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">season</W>
<W msd="IN" in="-8:mod" out="1:nobj">by</W>
<W msd="VBG" in="-1:nobj" out="1:mod|2:pobj">winning</W>
<W msd="JJ" in="-1:mod" out="">22-13</W>
<W msd="IN" in="-2:pobj" out="1:nobj">over</W>
<W msd="DT" in="-1:nobj" out="2:mod|3:nobj">the</W>
<W msd="RB" in="1:mod" out="">newly</W>
<W msd="VBN" in="-2:mod" out="-1:mod">advanced</W>
<W msd="NNS" in="-3:nobj" out="">Zealanders</W>
<W msd="." in="-31:pnct" out="">.</W>
</s>
<s>
<W msd="NNP" in="4:subj" out="2:mod|3:possd">Horsens'</W>
<W msd="JJS" in="1:mod" out="">closest</W>
<W msd="JJ" in="-2:mod" out="-1:mod">previous</W>
<W msd="NN" in="-3:possd" out="">victory</W>
<W msd="VBD" in="" out="-4:subj|5:pobj|13:pnct">dated</W>
<W msd="PDT" in="3:mod" out="1:nobj">all</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">way</W>
<W msd="RB" in="1:tobj" out="-3:mod">back</W>
<W msd="TO" in="-5:pobj" out="-1:tobj|1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod|3:possd|4:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">tournament's</W>
<W msd="JJ" in="-2:mod" out="">second</W>
<W msd="NN" in="-3:possd" out="">round</W>
<W msd="IN" in="-4:mod" out="1:nobj">on</W>
<W msd="NNP" in="-1:nobj" out="1:mod">September</W>
<W msd="CD" in="-1:mod" out="">29</W>
<W msd="." in="-13:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="6:mod" out="1:nobj|3:pnct">At</W>
<W msd="DT" in="-1:nobj" out="1:nobj">that</W>
<W msd="NN" in="-1:nobj" out="">time</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="DT" in="2:subj|4:[subj]" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">opponent</W>
<W msd="VBD" in="" out="-2:subj|-6:mod|1:mod|2:vobj|4:pnct">was</W>
<W msd="RB" in="-1:mod" out="">also</W>
<W msd="VBN" in="-2:vobj" out="-4:[subj]|1:pred">called</W>
<W msd="NNP" in="-1:pred" out="">Roar</W>
<W msd="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="RB" in="4:mod" out="1:pnct">However</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">showdown</W>
<W msd="VBD" in="" out="-2:subj|-4:mod|1:mod|4:pred|9:pnct|10:mod|31:pnct">was</W>
<W msd="RB" in="-1:mod" out="1:part">far</W>
<W msd="IN" in="-1:part" out="">from</W>
<W msd="RB" in="1:mod" out="2:pobj">as</W>
<W msd="JJ" in="-4:pred" out="-1:mod">one-sided</W>
<W msd="IN" in="-2:pobj" out="3:vobj">as</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">numbers</W>
<W msd="VBP" in="-3:vobj" out="-2:subj">indicate</W>
<W msd="," in="-9:pnct" out="">,</W>
<W msd="IN" in="-10:mod" out="1:pnct|12:vobj">because</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="10:mod" out="1:nobj|7:pnct">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">middle</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">second</W>
<W msd="NN" in="-2:nobj" out="">half</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">scoreboard</W>
<W msd="VBD" in="-12:vobj" out="-2:subj|-10:mod|1:mod|2:dobj|3:mod">showed</W>
<W msd="RB" in="-1:mod" out="">only</W>
<W msd="JJ" in="-2:dobj" out="">14-12</W>
<W msd="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:pobj">favour</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NN" in="1:mod" out="">home</W>
<W msd="NN" in="-2:nobj" out="-1:mod">team</W>
<W msd="." in="-31:pnct" out="">.</W>
</s>
