<s>
<W id="1" msd="AC" tag="CD" in="" out="">19-year</W>
<W id="2" msd="ANP" tag="JJ" in="" out="">old</W>
<W id="3" msd="NP=S" tag="NNP" in="" out="">Frank</W>
<W id="4" msd="NP=S" tag="NNP" in="" out="">Olsen</W>
<W id="5" msd="SP" tag="IN" in="" out="">from</W>
<W id="6" msd="NP=S" tag="NNP" in="" out="">CIK</W>
<W id="7" msd="VADA" tag="VBD" in="" out="">demonstrated</W>
<W id="8" msd="SP" tag="IN" in="" out="">at</W>
<W id="9" msd="PD" tag="DT" in="" out="">the</W>
<W id="10" msd="NP=S" tag="NNP" in="" out="">Zealand</W>
<W id="11" msd="NC=P" tag="NNS" in="" out="">championships</W>
<W id="12" msd="SP" tag="IN" in="" out="">at</W>
<W id="13" msd="NP=S" tag="NNP" in="" out="">Dansborg</W>
<W id="14" msd="NP=S" tag="NNP" in="" out="">Hall</W>
<W id="15" msd="SP" tag="IN" in="" out="">in</W>
<W id="16" msd="NP=S" tag="NNP" in="" out="">Hvidovre</W>
<W id="17" msd="SP" tag="IN" in="" out="">that</W>
<W id="18" msd="PP" tag="PRP" in="" out="">he</W>
<W id="19" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="20" msd="PD" tag="DT" in="" out="">the</W>
<W id="21" msd="NC=S" tag="NN" in="" out="">potential</W>
<W id="22" msd="SP" tag="IN" in="" out="">of</W>
<W id="23" msd="VAG" tag="VBG" in="" out="">becoming</W>
<W id="24" msd="PI" tag="DT" in="" out="">a</W>
<W id="25" msd="ANP" tag="JJ" in="" out="">prominent</W>
<W id="26" msd="NC=S" tag="NN" in="" out="">figure</W>
<W id="27" msd="SP" tag="IN" in="" out="">in</W>
<W id="28" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="29" msd="NC=S" tag="NN" in="" out="">boxing</W>
<W id="30" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="33" msd="SP" tag="IN" in="" out="">With</W>
<W id="34" msd="ANP" tag="JJ" in="" out="">aggressive</W>
<W id="35" msd="NC=S" tag="NN" in="" out="">boxing</W>
<W id="36" msd="ANP" tag="JJ" in="" out="">mixed</W>
<W id="37" msd="SP" tag="IN" in="" out="">with</W>
<W id="38" msd="ANP" tag="JJ" in="" out="">nice</W>
<W id="39" msd="ANP" tag="JJ" in="" out="">1-2</W>
<W id="40" msd="NC=P" tag="NNS" in="" out="">combinations</W>
<W id="41" msd="XP" tag="," in="" out="">,</W>
<W id="42" msd="PP" tag="PRP" in="" out="">he</W>
<W id="43" msd="VADA" tag="VBD" in="" out="">triumphed</W>
<W id="44" msd="SP" tag="IN" in="" out="">over</W>
<W id="45" msd="NP=S" tag="NNP" in="" out="">Lars</W>
<W id="46" msd="NP=S" tag="NNP" in="" out="">B.</W>
<W id="47" msd="NP=S" tag="NNP" in="" out="">Hansen</W>
<W id="48" msd="SP" tag="IN" in="" out="">from</W>
<W id="49" msd="NP=S" tag="NNP" in="" out="">Korsør</W>
<W id="50" msd="SP" tag="IN" in="" out="">with</W>
<W id="51" msd="PI" tag="DT" in="" out="">a</W>
<W id="52" msd="ANP" tag="JJ" in="" out="">clear</W>
<W id="53" msd="NC=S" tag="NN" in="" out="">5-0</W>
<W id="54" msd="SP" tag="IN" in="" out="">in</W>
<W id="55" msd="NC=S" tag="NN" in="" out="">welterweight</W>
<W id="56" msd="CC" tag="CC" in="" out="">and</W>
<W id="57" msd="ANP" tag="RB" in="" out="">then</W>
<W id="58" msd="VADA" tag="VBD" in="" out="">continued</W>
<W id="59" msd="PD" tag="DT" in="" out="">the</W>
<W id="60" msd="ANP" tag="JJ" in="" out="">elegant</W>
<W id="61" msd="NC=P" tag="NNS" in="" out="">moves</W>
<W id="62" msd="PP" tag="PRP" in="" out="">he</W>
<W id="63" msd="VADA" tag="VBD" in="" out="">showed</W>
<W id="64" msd="SP" tag="IN" in="" out="">in</W>
<W id="65" msd="PD" tag="DT" in="" out="">the</W>
<W id="66" msd="NC=P" tag="NNS" in="" out="">semi-finals</W>
<W id="67" msd="SP" tag="IN" in="" out="">against</W>
<W id="68" msd="PD" tag="DT" in="" out="">the</W>
<W id="69" msd="VAP" tag="VBN" in="" out="">experienced</W>
<W id="70" msd="NP=S" tag="NNP" in="" out="">Isa</W>
<W id="71" msd="NP=S" tag="NNP" in="" out="">Fidan</W>
<W id="72" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="75" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="76" msd="PP" tag="PRP" in="" out="">I</W>
<W id="77" msd="VA" tag="MD" in="" out="">could</W>
<W id="78" msd="VAF" tag="VB" in="" out="">tell</W>
<W id="79" msd="SP" tag="IN" in="" out="">that</W>
<W id="80" msd="PP" tag="PRP" in="" out="">I</W>
<W id="81" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="82" msd="VAP" tag="VBN" in="" out="">boxed</W>
<W id="83" msd="PI" tag="DT" in="" out="">a</W>
<W id="84" msd="ANP" tag="JJ" in="" out="">hard</W>
<W id="85" msd="NC=S" tag="NN" in="" out="">fight</W>
<W id="86" msd="SP" tag="IN" in="" out="">against</W>
<W id="87" msd="NP=S" tag="NNP" in="" out="">Fidan</W>
<W id="88" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="91" msd="CC" tag="CC" in="" out="">But</W>
<W id="92" msd="PP" tag="PRP" in="" out="">I</W>
<W id="93" msd="ANP" tag="RB" in="" out="">also</W>
<W id="94" msd="VADR" tag="VBP" in="" out="">think</W>
<W id="95" msd="SP" tag="IN" in="" out="">that</W>
<W id="96" msd="PP" tag="PRP" in="" out="">it</W>
<W id="97" msd="ANP" tag="RB" in="" out="">really</W>
<W id="98" msd="VADA" tag="VBD" in="" out="">went</W>
<W id="99" msd="ANP" tag="RB" in="" out="">very</W>
<W id="100" msd="ANP" tag="JJ" in="" out="">well</W>
<W id="101" msd="NC=S" tag="NN" in="" out="">today</W>
<W id="102" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="105" msd="PP" tag="PRP" in="" out="">I</W>
<W id="106" msd="VADA" tag="VBD" in="" out="">knew</W>
<W id="107" msd="SP" tag="IN" in="" out="">that</W>
<W id="108" msd="PP" tag="PRP" in="" out="">I</W>
<W id="109" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="110" msd="ANC" tag="RBR" in="" out="">faster</W>
<W id="111" msd="SP" tag="IN" in="" out="">than</W>
<W id="112" msd="PP" tag="PRP" in="" out="">him</W>
<W id="113" msd="CC" tag="CC" in="" out="">and</W>
<W id="114" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="115" msd="NC=S" tag="NN" in="" out="">control</W>
<W id="116" msd="SP" tag="IN" in="" out="">of</W>
<W id="117" msd="PD" tag="DT" in="" out="">the</W>
<W id="118" msd="NC=S" tag="NN" in="" out="">fight</W>
<W id="119" msd="PD" tag="DT" in="" out="">the</W>
<W id="120" msd="ANP" tag="JJ" in="" out="">whole</W>
<W id="121" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="122" msd="XP" tag="," in="" out="">,</W>
<W id="123" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="124" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="125" msd="NP=S" tag="NNP" in="" out="">Frank</W>
<W id="126" msd="NP=S" tag="NNP" in="" out="">Olsen</W>
<W id="127" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="130" msd="PP" tag="PRP" in="" out="">He</W>
<W id="131" msd="ANP" tag="RB" in="" out="">also</W>
<W id="132" msd="VADA" tag="VBD" in="" out="">won</W>
<W id="133" msd="PD" tag="DT" in="" out="">the</W>
<W id="134" msd="NP=S" tag="NNP" in="" out="">Zealand</W>
<W id="135" msd="NC=S" tag="NN" in="" out="">championship</W>
<W id="136" msd="ANP" tag="JJ" in="" out="">last</W>
<W id="137" msd="NC=S" tag="NN" in="" out="">year</W>
<W id="138" msd="XP" tag="," in="" out="">,</W>
<W id="139" msd="CC" tag="CC" in="" out="">but</W>
<W id="140" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="141" msd="ANP" tag="RB" in="" out="">still</W>
<W id="142" msd="PI" tag="DT" in="" out="">a</W>
<W id="143" msd="NC=S" tag="NN" in="" out="">bit</W>
<W id="144" msd="ANP" tag="JJ" in="" out="">short</W>
<W id="145" msd="SP" tag="IN" in="" out="">in</W>
<W id="146" msd="PD" tag="DT" in="" out="">the</W>
<W id="147" msd="NC=S" tag="NN" in="" out="">resolve</W>
<W id="148" msd="U=" tag="TO" in="" out="">to</W>
<W id="149" msd="VAF" tag="VB" in="" out="">make</W>
<W id="150" msd="PD" tag="DT" in="" out="">the</W>
<W id="151" msd="NC=S" tag="NN" in="" out="">effort</W>
<W id="152" msd="U=" tag="TO" in="" out="">to</W>
<W id="153" msd="VAF" tag="VB" in="" out="">get</W>
<W id="154" msd="PD" tag="PDT" in="" out="">all</W>
<W id="155" msd="PD" tag="DT" in="" out="">the</W>
<W id="156" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="157" msd="U=" tag="TO" in="" out="">to</W>
<W id="158" msd="PD" tag="DT" in="" out="">the</W>
<W id="159" msd="NC=S" tag="NN" in="" out="">top</W>
<W id="160" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="163" msd="CC" tag="CC" in="" out="">Nor</W>
<W id="164" msd="VADA" tag="VBD" in="" out="">did</W>
<W id="165" msd="PD" tag="DT" in="" out="">the</W>
<W id="166" msd="NC=S" tag="NN" in="" out="">triumph</W>
<W id="167" msd="NC=S" tag="NN" in="" out="">yesterday</W>
<W id="168" msd="VAF" tag="VB" in="" out="">get</W>
<W id="169" msd="NP=S" tag="NNP" in="" out="">Frank</W>
<W id="170" msd="NP=S" tag="NNP" in="" out="">Olsen</W>
<W id="171" msd="U=" tag="TO" in="" out="">to</W>
<W id="172" msd="VAF" tag="VB" in="" out="">announce</W>
<W id="173" msd="SP" tag="IN" in="" out="">that</W>
<W id="174" msd="NC=P" tag="NNS" in="" out="">people</W>
<W id="175" msd="VA" tag="MD" in="" out="">can</W>
<W id="176" msd="VAF" tag="VB" in="" out="">expect</W>
<W id="177" msd="ANP" tag="JJ" in="" out="">great</W>
<W id="178" msd="NC=P" tag="NNS" in="" out="">things</W>
<W id="179" msd="SP" tag="IN" in="" out="">from</W>
<W id="180" msd="PP" tag="PRP" in="" out="">him</W>
<W id="181" msd="SP" tag="IN" in="" out="">in</W>
<W id="182" msd="PD" tag="DT" in="" out="">the</W>
<W id="183" msd="NC=S" tag="NN" in="" out="">future</W>
<W id="184" msd="XP" tag="." in="" out="">.</W>
</s>
