<s>
<W id="1" msd="ANP" tag="RB" in="" out="">Thus</W>
<W id="2" msd="XP" tag="," in="" out="">,</W>
<W id="3" msd="NC=P" tag="NNS" in="" out="">months</W>
<W id="4" msd="SP" tag="IN" in="" out="">of</W>
<W id="5" msd="NC=S" tag="NN" in="" out="">uncertainty</W>
<W id="6" msd="SP" tag="IN" in="" out="">about</W>
<W id="7" msd="PD" tag="DT" in="" out="">the</W>
<W id="8" msd="NC=S" tag="NN" in="" out="">status</W>
<W id="9" msd="SP" tag="IN" in="" out="">of</W>
<W id="10" msd="PD" tag="DT" in="" out="">the</W>
<W id="11" msd="AC" tag="CD" in="" out="">two</W>
<W id="12" msd="NC=P" tag="NNS" in="" out="">republics</W>
<W id="13" msd="SP" tag="IN" in="" out="">in</W>
<W id="14" msd="ANP" tag="JJ" in="" out="">international</W>
<W id="15" msd="NC=S" tag="NN" in="" out="">law</W>
<W id="16" msd="VADA" tag="VBD" in="" out="">ended</W>
<W id="17" msd="XP" tag="," in="" out="">,</W>
<W id="18" msd="CC" tag="CC" in="" out="">and</W>
<W id="19" msd="PD" tag="DT" in="" out="">the</W>
<W id="20" msd="ANP" tag="JJ" in="" out="">old</W>
<W id="21" msd="NP=S" tag="NNP" in="" out="">Yugoslavia</W>
<W id="22" msd="VADA" tag="VBD" in="" out="">ceased</W>
<W id="23" msd="U=" tag="TO" in="" out="">to</W>
<W id="24" msd="VAF" tag="VB" in="" out="">exist</W>
<W id="25" msd="SP" tag="IN" in="" out="">for</W>
<W id="26" msd="NC=S" tag="NN" in="" out="">everyone</W>
<W id="27" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="28" msd="SP" tag="IN" in="" out="">than</W>
<W id="29" msd="NP=S" tag="NNP" in="" out="">Serbs</W>
<W id="30" msd="XP" tag="," in="" out="">,</W>
<W id="31" msd="PT" tag="WP" in="" out="">who</W>
<W id="32" msd="ANP" tag="JJ" in="" out="">late</W>
<W id="33" msd="ANP" tag="JJ" in="" out="">last</W>
<W id="34" msd="NC=S" tag="NN" in="" out="">summer</W>
<W id="35" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="36" msd="VAP" tag="VBN" in="" out="">conducted</W>
<W id="37" msd="NC=S" tag="NN" in="" out="">war</W>
<W id="38" msd="SP" tag="IN" in="" out="">against</W>
<W id="39" msd="PD" tag="DT" in="" out="">the</W>
<W id="40" msd="NP=P" tag="NNPS" in="" out="">Croatians</W>
<W id="41" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="44" msd="PD" tag="DT" in="" out="">The</W>
<W id="45" msd="NP=S" tag="NNP" in="" out="">EC's</W>
<W id="46" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="47" msd="NC=S" tag="NN" in="" out="">member</W>
<W id="48" msd="NC=P" tag="NNS" in="" out="">states</W>
<W id="49" msd="XP" tag="," in="" out="">,</W>
<W id="50" msd="VAG" tag="VBG" in="" out="">including</W>
<W id="51" msd="NP=S" tag="NNP" in="" out="">Denmark</W>
<W id="52" msd="XP" tag="," in="" out="">,</W>
<W id="53" msd="ANP" tag="RB" in="" out="">likewise</W>
<W id="54" msd="VAP" tag="VBN" in="" out="">recognised</W>
<W id="55" msd="NP=S" tag="NNP" in="" out="">Croatia</W>
<W id="56" msd="CC" tag="CC" in="" out="">and</W>
<W id="57" msd="NP=S" tag="NNP" in="" out="">Slovenia</W>
<W id="58" msd="NC=S" tag="NN" in="" out="">yesterday</W>
<W id="59" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="62" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="63" msd="CC" tag="CC" in="" out="">But</W>
<W id="64" msd="PP" tag="PRP" in="" out="">they</W>
<W id="65" msd="VADR" tag="VBP" in="" out="">let</W>
<W id="66" msd="PD" tag="DT" in="" out="">the</W>
<W id="67" msd="NP=P" tag="NNPS" in="" out="">Germans</W>
<W id="68" msd="VADR" tag="VBP" in="" out="">do</W>
<W id="69" msd="PD" tag="DT" in="" out="">the</W>
<W id="70" msd="ANP" tag="JJ" in="" out="">dirty</W>
<W id="71" msd="NC=S" tag="NN" in="" out="">work</W>
<W id="72" msd="XP" tag="," in="" out="">,</W>
<W id="73" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="74" msd="VADA" tag="VBD" in="" out="">commented</W>
<W id="75" msd="PI" tag="DT" in="" out="">a</W>
<W id="76" msd="NP=S" tag="NNP" in="" out="">Croatian</W>
<W id="77" msd="NC=S" tag="NN" in="" out="">official</W>
<W id="78" msd="XP" tag="," in="" out="">,</W>
<W id="79" msd="PT" tag="WRB" in="" out="">when</W>
<W id="80" msd="PD" tag="DT" in="" out="">the</W>
<W id="81" msd="NC=S" tag="NN" in="" out="">champagne</W>
<W id="82" msd="NC=P" tag="NNS" in="" out="">corks</W>
<W id="83" msd="VADA" tag="VBD" in="" out="">flew</W>
<W id="84" msd="SP" tag="IN" in="" out="">through</W>
<W id="85" msd="PD" tag="DT" in="" out="">the</W>
<W id="86" msd="NC=S" tag="NN" in="" out="">air</W>
<W id="87" msd="CC" tag="CC" in="" out="">and</W>
<W id="88" msd="NP=S" tag="NNP" in="" out="">Bonn's</W>
<W id="89" msd="ANP" tag="JJ" in="" out="">special</W>
<W id="90" msd="NC=S" tag="NN" in="" out="">envoy</W>
<W id="91" msd="XP" tag="," in="" out="">,</W>
<W id="92" msd="NP=S" tag="NNP" in="" out="">Klaus-Peter</W>
<W id="93" msd="NP=S" tag="NNP" in="" out="">Klaiber</W>
<W id="94" msd="XP" tag="," in="" out="">,</W>
<W id="95" msd="VAP" tag="VBN" in="" out="">exchanged</W>
<W id="96" msd="NC=P" tag="NNS" in="" out="">handshakes</W>
<W id="97" msd="SP" tag="IN" in="" out="">with</W>
<W id="98" msd="NP=S" tag="NNP" in="" out="">Croatia's</W>
<W id="99" msd="NP=S" tag="NNP" in="" out="">President</W>
<W id="100" msd="NP=S" tag="NNP" in="" out="">Franjo</W>
<W id="101" msd="NP=S" tag="NNP" in="" out="">Tudjman</W>
<W id="102" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="105" msd="PD" tag="DT" in="" out="">The</W>
<W id="106" msd="NC=S" tag="NN" in="" out="">official</W>
<W id="107" msd="VADA" tag="VBD" in="" out="">alluded</W>
<W id="108" msd="U=" tag="TO" in="" out="">to</W>
<W id="109" msd="PD" tag="DT" in="" out="">the</W>
<W id="110" msd="NC=S" tag="NN" in="" out="">pressure</W>
<W id="111" msd="NP=S" tag="NNP" in="" out="">Germany</W>
<W id="112" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="113" msd="SP" tag="IN" in="" out="">for</W>
<W id="114" msd="PD" tag="DT" in="" out="">the</W>
<W id="115" msd="ANP" tag="JJ" in="" out="">last</W>
<W id="116" msd="AC" tag="CD" in="" out="">six</W>
<W id="117" msd="NC=P" tag="NNS" in="" out="">months</W>
<W id="118" msd="VADR" tag="VBP" in="" out="">put</W>
<W id="119" msd="SP" tag="IN" in="" out="">on</W>
<W id="120" msd="ANC" tag="RBR" in="" out="">more</W>
<W id="121" msd="ANP" tag="JJ" in="" out="">reluctant</W>
<W id="122" msd="NP=S" tag="NNP" in="" out="">EC</W>
<W id="123" msd="NC=P" tag="NNS" in="" out="">members</W>
<W id="124" msd="XP" tag="," in="" out="">,</W>
<W id="125" msd="ANP" tag="JJ" in="" out="">such</W>
<W id="126" msd="CS" tag="IN" in="" out="">as</W>
<W id="127" msd="NP=S" tag="NNP" in="" out="">Great</W>
<W id="128" msd="NP=S" tag="NNP" in="" out="">Britain</W>
<W id="129" msd="XP" tag="," in="" out="">,</W>
<W id="130" msd="NP=S" tag="NNP" in="" out="">France</W>
<W id="131" msd="CC" tag="CC" in="" out="">and</W>
<W id="132" msd="NP=S" tag="NNP" in="" out="">Greece</W>
<W id="133" msd="XP" tag="," in="" out="">,</W>
<W id="134" msd="U=" tag="TO" in="" out="">to</W>
<W id="135" msd="VAF" tag="VB" in="" out="">recognise</W>
<W id="136" msd="PD" tag="DT" in="" out="">the</W>
<W id="137" msd="AC" tag="CD" in="" out="">two</W>
<W id="138" msd="NC=P" tag="NNS" in="" out="">republics</W>
<W id="139" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="142" msd="CC" tag="CC" in="" out="">Nor</W>
<W id="143" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="144" msd="NP=S" tag="NNP" in="" out="">Denmark</W>
<W id="145" msd="SP" tag="IN" in="" out="">in</W>
<W id="146" msd="PD" tag="DT" in="" out="">the</W>
<W id="147" msd="VAG" tag="VBG" in="" out="">beginning</W>
<W id="148" msd="ANP" tag="RB" in="" out="">especially</W>
<W id="149" msd="ANP" tag="JJ" in="" out="">enthusiastic</W>
<W id="150" msd="XP" tag="," in="" out="">,</W>
<W id="151" msd="CC" tag="CC" in="" out="">and</W>
<W id="152" msd="NC=S" tag="NN" in="" out="">yesterday</W>
<W id="153" msd="PD" tag="DT" in="" out="">the</W>
<W id="154" msd="NP=S" tag="NNP" in="" out="">Ministry</W>
<W id="155" msd="SP" tag="IN" in="" out="">of</W>
<W id="156" msd="NP=S" tag="NNP" in="" out="">Foreign</W>
<W id="157" msd="NP=S" tag="NNP" in="" out="">Affairs</W>
<W id="158" msd="SP" tag="IN" in="" out="">in</W>
<W id="159" msd="NP=S" tag="NNP" in="" out="">Copenhagen</W>
<W id="160" msd="VADA" tag="VBD" in="" out="">avoided</W>
<W id="161" msd="VAG" tag="VBG" in="" out="">sending</W>
<W id="162" msd="PI" tag="DT" in="" out="">an</W>
<W id="163" msd="NC=S" tag="NN" in="" out="">ambassador</W>
<W id="164" msd="U=" tag="TO" in="" out="">to</W>
<W id="165" msd="NP=S" tag="NNP" in="" out="">Croatia</W>
<W id="166" msd="CC" tag="CC" in="" out="">and</W>
<W id="167" msd="NP=S" tag="NNP" in="" out="">Slovenia</W>
<W id="168" msd="SP" tag="IN" in="" out="">with</W>
<W id="169" msd="PD" tag="DT" in="" out="">the</W>
<W id="170" msd="ANP" tag="JJ" in="" out="">same</W>
<W id="171" msd="NC=S" tag="NN" in="" out="">speed</W>
<W id="172" msd="CS" tag="IN" in="" out="">as</W>
<W id="173" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="174" msd="VAP" tag="VBN" in="" out="">done</W>
<W id="175" msd="SP" tag="IN" in="" out="">in</W>
<W id="176" msd="PD" tag="DT" in="" out="">the</W>
<W id="177" msd="NC=S" tag="NN" in="" out="">fall</W>
<W id="178" msd="SP" tag="IN" in="" out="">with</W>
<W id="179" msd="PD" tag="DT" in="" out="">the</W>
<W id="180" msd="NC=S" tag="NN" in="" out="">recognition</W>
<W id="181" msd="SP" tag="IN" in="" out="">of</W>
<W id="182" msd="PD" tag="DT" in="" out="">the</W>
<W id="183" msd="ANP" tag="JJ" in="" out="">Baltic</W>
<W id="184" msd="NC=P" tag="NNS" in="" out="">countries</W>
<W id="185" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="188" msd="PD" tag="DT" in="" out="">The</W>
<W id="189" msd="NC=S" tag="NN" in="" out="">satisfaction</W>
<W id="190" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="191" msd="CC" tag="CC" in="" out="">and</W>
<W id="192" msd="ANP" tag="JJ" in="" out="">self-satisfaction</W>
<W id="193" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="194" msd="SP" tag="IN" in="" out="">of</W>
<W id="195" msd="PD" tag="DT" in="" out="">the</W>
<W id="196" msd="NP=P" tag="NNPS" in="" out="">Croatians</W>
<W id="197" msd="CC" tag="CC" in="" out="">and</W>
<W id="198" msd="NP=P" tag="NNPS" in="" out="">Slovenians</W>
<W id="199" msd="XP" tag="," in="" out="">,</W>
<W id="200" msd="ANP" tag="RB" in="" out="">however</W>
<W id="201" msd="XP" tag="," in="" out="">,</W>
<W id="202" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="203" msd="ANP" tag="JJ" in="" out="">untarnished</W>
<W id="204" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="207" msd="SP" tag="IN" in="" out="">In</W>
<W id="208" msd="PD" tag="DT" in="" out="">the</W>
<W id="209" msd="NC=S" tag="NN" in="" out="">ballroom</W>
<W id="210" msd="SP" tag="IN" in="" out="">in</W>
<W id="211" msd="NP=S" tag="NNP" in="" out="">Zagreb</W>
<W id="212" msd="XP" tag="," in="" out="">,</W>
<W id="213" msd="NP=S" tag="NNP" in="" out="">President</W>
<W id="214" msd="NP=S" tag="NNP" in="" out="">Tudjman's</W>
<W id="215" msd="NC=S" tag="NN" in="" out="">cabinet</W>
<W id="216" msd="NC=S" tag="NN" in="" out="">head</W>
<W id="217" msd="NP=S" tag="NNP" in="" out="">Hrvoje</W>
<W id="218" msd="NP=S" tag="NNP" in="" out="">Sarinc</W>
<W id="219" msd="VADA" tag="VBD" in="" out="">threw</W>
<W id="220" msd="PP" tag="PRP" in="" out="">himself</W>
<W id="221" msd="SP" tag="IN" in="" out="">into</W>
<W id="222" msd="PI" tag="DT" in="" out="">an</W>
<W id="223" msd="ANP" tag="JJ" in="" out="">extensive</W>
<W id="224" msd="NC=S" tag="NN" in="" out="">praise</W>
<W id="225" msd="SP" tag="IN" in="" out="">of</W>
<W id="226" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="227" msd="NC=S" tag="NN" in="" out="">country</W>
<W id="228" msd="CC" tag="CC" in="" out="">and</W>
<W id="229" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="230" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="231" msd="ANP" tag="JJ" in="" out="">successful</W>
<W id="232" msd="CC" tag="CC" in="" out="">and</W>
<W id="233" msd="ANP" tag="JJ" in="" out="">realistic</W>
<W id="234" msd="AC" tag="CD" in="" out="">policies.</W>
<W id="235" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
