<s>
<W msd="VADR" tag="VBP" in="" out="1:subj|4:pnct">Are</W>
<W msd="PP" tag="PRP" in="-1:subj" out="">they</W>
<W msd="ANP" tag="RB" in="" out="">completely</W>
<W msd="NC=P" tag="NNS" in="" out="">nuts</W>
<W msd="XP" tag="." in="-4:pnct" out="">?</W>
</s>
<s>
<W msd="SP" tag="IN" in="10:mod" out="1:nobj">For</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">several</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="ANP" tag="RB" in="7:time" out="1:pnct">now</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="5:subj|6:[subj]" out="1:pnct|2:conj">S</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="">SF</W>
<W msd="CC" tag="CC" in="" out="">and</W>
<W msd="NC=P" tag="NNS" in="" out="">others</W>
<W msd="VADR" tag="VBP" in="" out="-5:subj|-10:mod|-7:time|1:vobj|3:pnct|4:cause|14:pnct">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-6:[subj]|1:dobj">persecuted</W>
<W msd="NP=S" tag="NNP" in="-1:dobj" out="">Ninn-Hansen</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-4:cause" out="5:vobj">because</W>
<W msd="SP" tag="IN" in="4:mod" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">their</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">opinion</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]" out="">he</W>
<W msd="VADR" tag="VBZ" in="-5:vobj" out="-1:subj|-4:mod|1:neg|2:vobj">has</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-3:[subj]|1:dobj">followed</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">law</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="U=" tag="EX" in="1:expl|4:[expl]" out="">There</W>
<W msd="VADR" tag="VBP" in="" out="-1:expl|1:mod|2:epi|3:vobj|6:pnct|9:conj|30:pnct">have</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">indeed</W>
<W msd="ANP" tag="RB" in="-2:epi" out="">apparently</W>
<W msd="VAP" tag="VBN" in="-3:vobj" out="-4:[expl]|1:dobj">been</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">some</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">problems</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="CC" tag="CC" in="2:coord" out="">but</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADR" tag="VBZ" in="-9:conj" out="-1:expl|-2:coord|4:dobj|8:pnct|9:cause|1:contr">is</W>
<W msd="ANP" tag="RB" in="-1:contr" out="">nevertheless</W>
<W msd="ANP" tag="RB" in="1:quant" out="">very</W>
<W msd="ANP" tag="JJ" in="1:attr" out="-1:quant">wide-spread</W>
<W msd="NC=S" tag="NN" in="-4:dobj" out="-1:attr|1:pobj">understanding</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:possd">Ninn-Hansen's</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">actions</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-9:cause" out="2:vobj">because</W>
<W msd="PP" tag="PRP" in="1:subj" out="">he</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-1:subj|2:dobj|3:accom">safeguarded</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">Danish</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="-1:attr">interests</W>
<W msd="SP" tag="IN" in="-3:accom" out="1:nobj">without</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="4:@dir">acquiring</W>
<W msd="PD" tag="DT" in="" out="1:mod">any</W>
<W msd="NC=S" tag="NN" in="-1:mod" out="">person</W>
<W msd="NC=S" tag="NN" in="" out="">gain</W>
<W msd="SP" tag="IN" in="-4:@dir" out="1:nobj">from</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">it</W>
<W msd="XP" tag="." in="-30:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="3:time" out="1:pnct">Now</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|1:[subj]" out="">we</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|-1:[subj]|-3:time|1:dobj|19:conj|24:pnct">have</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|5:ref|6:rel">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W msd="SP" tag="IN" in="" out="">for</W>
<W msd="NP=S" tag="NNP" in="" out="">Justice</W>
<W msd="PT" tag="WP" in="-5:ref|1:subj" out="">who</W>
<W msd="VADR" tag="VBZ" in="-6:rel" out="-1:subj|1:dobj|3:pnct">follows</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">law</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="CC" tag="CC" in="8:coord" out="">but</W>
<W msd="PP" tag="PRP" in="" out="">it</W>
<W msd="VADR" tag="VBZ" in="" out="">is</W>
<W msd="PD" tag="DT" in="5:subj|7:[subj]" out="">the</W>
<W msd="ANP" tag="RB" in="" out="">very</W>
<W msd="ANP" tag="JJ" in="" out="1:nobj">same</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">parties</W>
<W msd="PT" tag="WDT" in="" out="">that</W>
<W msd="VA" tag="MD" in="-19:conj" out="-5:subj|-8:coord|1:neg">will</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAF" tag="VB" in="" out="-7:[subj]">stand</W>
<W msd="SP" tag="IN" in="" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="">this</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj" out="">They</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|1:dobj|6:pnct|10:pnct">demand</W>
<W msd="PI" tag="DT" in="-1:dobj" out="">an</W>
<W msd="NC=S" tag="NN" in="" out="">amendment</W>
<W msd="U=" tag="TO" in="" out="">to</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">law</W>
<W msd="XP" tag="&3a;" in="-6:pnct" out="">-</W>
<W msd="SP" tag="IN" in="" out="2:nobj">with</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">retroactive</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr">effect</W>
<W msd="XP" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Arne</W>
<W msd="NP=S" tag="NNP" in="" out="-1:namef|1:pnct|2:list|7:pnct">Fryman</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:list" out="1:attr|2:list">Vestersøgade</W>
<W msd="AC" tag="CD" in="-1:attr" out="">78,</W>
<W msd="AC" tag="CD" in="-2:list" out="1:list">1601</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="1:name">Copenhagen</W>
<W msd="NP=S" tag="NNP" in="-1:name" out="">V</W>
<W msd="XP" tag="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="NP=P" tag="NNPS" in="1:subj" out="">Danes</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|1:neg|2:preds">are</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="PI" tag="DT" in="-2:preds" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">race</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NP=P" tag="NNPS" in="-1:nobj" out="">Danes</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj|1:preds|3:pnct|4:&lt;mod&gt;|5:&lt;pred&gt;|7:pnct|8:mod|66:pnct">are</W>
<W msd="PI" tag="DT" in="-1:preds" out="1:nobj">a</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">people</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-4:&lt;mod&gt;" out="">not</W>
<W msd="PI" tag="DT" in="-5:&lt;pred&gt;" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">race</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-8:mod" out="23:vobj">so</W>
<W msd="PT" tag="WRB" in="22:time" out="4:vobj">when</W>
<W msd="PD" tag="DT" in="3:subj" out="1:attr|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:attr" out="">Danish</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">Association</W>
<W msd="NC=P" tag="NNS" in="-4:vobj" out="-3:subj|1:nobj|15:pnct">advocates</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:dobj|4:pobj">defending</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">Danish</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">people</W>
<W msd="SP" tag="IN" in="-4:pobj" out="1:nobj">against</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:vobj">being</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="1:mod|5:pobj">displaced</W>
<W msd="SP" tag="IN" in="-1:mod" out="">in</W>
<W msd="PO" tag="PRP$" in="" out="1:attr">their</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">own</W>
<W msd="NC=S" tag="NN" in="" out="">country</W>
<W msd="SP" tag="IN" in="-5:pobj" out="">by</W>
<W msd="ANP" tag="JJ" in="" out="">economic</W>
<W msd="NC=P" tag="NNS" in="" out="">refugees</W>
<W msd="XP" tag="," in="-15:pnct" out="">,</W>
<W msd="PD" tag="DT" in="2:subj|6:[subj]|7:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">association</W>
<W msd="NC=S" tag="NN" in="-23:vobj" out="-2:subj|-22:time|1:mod|4:vobj|9:pnct|10:mod">cannot</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">that</W>
<W msd="VADR" tag="VBP" in="-1:nobj" out="">reason</W>
<W msd="VAF" tag="VB" in="-4:vobj" out="-6:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-7:[subj]|1:pobj">accused</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:preds">being</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="">racist</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-10:mod" out="1:vobj">as</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="1:pobj">claimed</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj|5:conj">by</W>
<W msd="NC=S" tag="NN" in="2:title" out="">director</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Jens</W>
<W msd="NP=S" tag="NNP" in="-3:nobj" out="-2:title|-1:namef">Sejersen</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="SP" tag="IN" in="-5:conj" out="-1:coord|1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="2:mod|3:nobj|4:mod|9:pnct|10:ref|11:rel">a</W>
<W msd="ANP" tag="RB" in="1:quant" out="">completely</W>
<W msd="VAP" tag="VBN" in="-2:mod" out="-1:quant">mistaken</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">judgment</W>
<W msd="SP" tag="IN" in="-4:mod" out="2:nobj">of</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">Gentofte</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Civil</W>
<W msd="NP=S" tag="NNP" in="" out="-1:mod">Court</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-10:ref|1:subj" out="">which</W>
<W msd="VADR" tag="VBZ" in="-11:rel" out="-1:subj|1:preds">is</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="1:pobj">defamatory</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">Danish</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">people</W>
<W msd="XP" tag="." in="-66:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="2:namef" out="">Ivan</W>
<W msd="NP=S" tag="NNP" in="1:namel" out="">Vaarby</W>
<W msd="NP=S" tag="NNP" in="" out="-2:namef|-1:namel|1:pnct|2:list">Laursen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:list" out="1:pnct|1:attr|2:list">Guldvej</W>
<W msd="AC" tag="CD" in="-1:pnct|-1:attr" out="">6,</W>
<W msd="AC" tag="CD" in="-2:list" out="1:list">3060</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Espergærde</W>
</s>
