<s>
<W msd="CD" in="11:subj" out="1:pobj">One</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="1:nobj">reasons</W>
<W msd="IN" in="-1:nobj" out="3:vobj">that</W>
<W msd="DT" in="2:subj|3:[subj]" out="1:nobj">this</W>
<W msd="NN" in="-1:nobj" out="">genre</W>
<W msd="VBZ" in="-3:vobj" out="-2:subj|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|2:pred">become</W>
<W msd="RB" in="1:mod" out="">so</W>
<W msd="JJ" in="-2:pred" out="-1:mod">lucrative</W>
<W msd="VBZ" in="" out="-11:subj|1:pred|14:pnct">is</W>
<W msd="DT" in="-1:pred" out="1:mod|2:nobj|3:mod|5:mod|8:mod">the</W>
<W msd="VBN" in="-1:mod" out="">altered</W>
<W msd="NN" in="-2:nobj" out="">status</W>
<W msd="IN" in="-3:mod" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">science</W>
<W msd="IN" in="-5:mod" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">public</W>
<W msd="IN" in="-8:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">last</W>
<W msd="CD" in="-2:nobj" out="1:nobj">ten</W>
<W msd="NNS" in="-1:nobj" out="">years</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">1970s</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="NN" in="1:subj|2:[subj]|4:[subj]" out="">science</W>
<W msd="VBD" in="" out="-5:mod|-1:subj|1:vobj|11:pnct|14:conj|35:pnct#">was</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|1:dobj">considered</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-4:[subj]|1:pred">be</W>
<W msd="CD" in="-1:pred" out="1:pobj">one</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">pillars</W>
<W msd="IN" in="-2:mod" out="1:mod|2:nobj">of</W>
<W msd="VBN" in="-1:mod" out="">established</W>
<W msd="NN" in="-2:nobj" out="">society</W>
<W msd=":" in="-11:pnct" out="">-</W>
<W msd="JJ" in="1:mod" out="">nuclear</W>
<W msd="NN" in="1:subj" out="-1:mod">physics</W>
<W msd="VBN" in="-14:conj" out="-1:subj|1:lobj|7:pnct|9:<subj>|10:<lobj>|13:pnct|14:<subj>|15:<lobj>|20:pnct|21:mod">led</W>
<W msd="TO" in="-1:lobj" out="2:nobj">to</W>
<W msd="JJ" in="1:mod" out="">nuclear</W>
<W msd="NN" in="-2:nobj" out="-1:mod|1:coord">power</W>
<W msd="CC" in="-1:coord" out="2:conj">and</W>
<W msd="JJ" in="1:mod" out="">atomic</W>
<W msd="NNS" in="-2:conj" out="-1:mod">weapons</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="JJ" in="1:mod" out="">molecular</W>
<W msd="NN" in="-9:<subj>" out="-1:mod">biology</W>
<W msd="TO" in="-10:<lobj>" out="2:nobj">to</W>
<W msd="NN" in="1:mod" out="">gene</W>
<W msd="NN" in="-2:nobj" out="-1:mod">manipulation</W>
<W msd="," in="-13:pnct" out="">,</W>
<W msd="JJ" in="-14:<subj>" out="">socio-biology</W>
<W msd="TO" in="-15:<lobj>" out="2:nobj">to</W>
<W msd="VB" in="1:mod" out="">sex</W>
<W msd="NN" in="-2:nobj" out="-1:mod|1:coord">discrimination</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NN" in="-1:conj" out="">racism</W>
<W msd="," in="-20:pnct" out="">,</W>
<W msd="FW" in="-21:mod|-35:pnct#" out="">etc.</W>
<W msd="NNS" in="1:subj" out="">Scientists</W>
<W msd="VBD" in="" out="-1:subj|1:pred|4:pnct">were</W>
<W msd="NNS" in="-1:pred" out="1:mod">henchmen</W>
<W msd="IN" in="-1:mod" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">capital</W>
<W msd="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="5:mod" out="1:nobj|3:pnct">During</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNS" in="-1:nobj" out="">eighties</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="NN" in="1:subj" out="">science</W>
<W msd="VBD" in="" out="-5:mod|-1:subj|1:dobj">acquired</W>
<W msd="DT" in="-1:dobj" out="2:mod|3:nobj|4:pnct|5:mod">another</W>
<W msd="RBR" in="1:mod" out="">more</W>
<W msd="JJ" in="-2:mod" out="-1:mod">positive</W>
<W msd="NN" in="-3:nobj" out="">image</W>
<W msd=":" in="-4:pnct" out="">:</W>
<W msd="IN" in="-5:mod" out="1:nobj">as</W>
<W msd="NN" in="-1:nobj" out="1:pobj">supplier</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNS" in="-1:nobj" out="1:pobj">answers</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj|3:pnct|5:xpl">the</W>
<W msd="JJ" in="-1:mod" out="">great</W>
<W msd="NNS" in="-2:nobj" out="">questions</W>
<W msd=":" in="-3:pnct" out="">:</W>
<W msd="WRB" in="1:mod" out="">When</W>
<W msd="VBD" in="-5:xpl" out="-1:mod|1:subj|3:vobj|4:pnct">did</W>
<W msd="DT" in="-1:subj|2:[subj]" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">universe</W>
<W msd="VB" in="-3:vobj" out="-2:[subj]">begin</W>
<W msd="." in="-4:pnct" out="">?</W>
</s>
<s>
<W msd="WP" in="1:pred" out="">What</W>
<W msd="VBZ" in="" out="-1:pred|1:subj|7:pnct">is</W>
<W msd="DT" in="-1:subj" out="1:nobj|2:mod|3:nobj|4:mod">the</W>
<W msd="NN" in="-1:nobj" out="">place</W>
<W msd="IN" in="-2:mod" out="">of</W>
<W msd="NN" in="-3:nobj" out="">man</W>
<W msd="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="">evolution</W>
<W msd="." in="-7:pnct" out="">?</W>
</s>
<s>
<W msd="VBZ" in="" out="1:subj|2:lobj|5:pnct">Is</W>
<W msd="NN" in="-1:subj" out="">consciousness</W>
<W msd="IN" in="-2:lobj" out="1:nobj">inside</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">cranium</W>
<W msd="." in="-5:pnct" out="">?</W>
</s>
<s>
<W msd="VBZ" in="" out="1:subj|3:pred|10:pnct|11:coord|16:pnct">Is</W>
<W msd="DT" in="-1:subj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="">Earth</W>
<W msd="DT" in="-3:pred" out="1:mod|2:nobj|3:mod">a</W>
<W msd="JJ" in="-1:mod" out="">dead</W>
<W msd="NN" in="-2:nobj" out="">rock</W>
<W msd="IN" in="-3:mod" out="1:nobj|2:pred">with</W>
<W msd="NN" in="-1:nobj" out="">life</W>
<W msd="IN" in="-2:pred" out="1:nobj">on</W>
<W msd="PRP" in="-1:nobj" out="">it</W>
<W msd=":" in="-10:pnct" out="">-</W>
<W msd="CC" in="-11:coord" out="1:<subj>|4:<mod>">or</W>
<W msd="DT" in="-1:<subj>" out="1:mod|2:nobj">a</W>
<W msd="VBG" in="-1:mod" out="">living</W>
<W msd="NN" in="-2:nobj" out="">thing</W>
<W msd="PRP" in="-4:<mod>" out="">itself</W>
<W msd="." in="-16:pnct" out="">?</W>
</s>
<s>
<W msd="IN" in="5:mod" out="1:nobj|2:pnct">Of</W>
<W msd="NN" in="-1:nobj" out="">course</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="JJ" in="1:mod" out="">contemplative</W>
<W msd="NNS" in="1:subj|5:[subj]" out="-1:mod">researchers</W>
<W msd="VBP" in="" out="-1:subj|-5:mod|1:mod|4:vobj|8:pnct">have</W>
<W msd="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="DT" in="-1:nobj" out="1:nobj">all</W>
<W msd="NNS" in="-1:nobj" out="">times</W>
<W msd="VBD" in="-4:vobj" out="-5:[subj]|1:pobj">speculated</W>
<W msd="IN" in="-1:pobj" out="1:nobj">about</W>
<W msd="DT" in="-1:nobj" out="1:nobj">these</W>
<W msd="NNS" in="-1:nobj" out="">topics</W>
<W msd="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="CC" in="" out="2:conj|39:pnct">But</W>
<W msd="PRP" in="1:subj" out="12:nobj">it</W>
<W msd="VBD" in="-2:conj" out="-1:subj|1:mod|3:pred">was</W>
<W msd="RB" in="-1:mod" out="1:part">not</W>
<W msd="IN" in="-1:part" out="">until</W>
<W msd="IN" in="-3:pred" out="1:nobj">after</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj|3:coord">the</W>
<W msd="JJ" in="-1:mod" out="">technology-optimistic</W>
<W msd="NNS" in="-2:nobj" out="">'60s</W>
<W msd="CC" in="-3:coord" out="1:conj">and</W>
<W msd="DT" in="-1:conj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">technology-critical</W>
<W msd="NNS" in="-2:nobj" out="">'70s</W>
<W msd="IN" in="-12:nobj" out="3:vobj|9:coord">that</W>
<W msd="DT" in="2:subj" out="1:nobj">the</W>
<W msd="RB" in="-1:nobj" out="">public</W>
<W msd="VBN" in="-3:vobj" out="-2:subj|1:dobj|4:mod|5:pnct">caught</W>
<W msd="NN" in="-1:dobj" out="1:pobj">sight</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PRP" in="-1:nobj" out="">them</W>
<W msd="RB" in="-4:mod" out="">again</W>
<W msd=":" in="-5:pnct" out="">-</W>
<W msd="CC" in="-9:coord" out="1:conj">and</W>
<W msd="IN" in="-1:conj" out="6:vobj">that</W>
<W msd="DT" in="5:subj|6:[subj]" out="1:nobj|2:mod">a</W>
<W msd="JJ" in="-1:nobj" out="">trend-catalyst</W>
<W msd="JJ" in="-2:mod" out="1:pobj">such</W>
<W msd="IN" in="-1:pobj" out="1:nobj">as</W>
<W msd="NNP" in="-1:nobj" out="">Brockman</W>
<W msd="MD" in="-6:vobj" out="-5:subj|1:vobj">could</W>
<W msd="VB" in="-1:vobj" out="-6:[subj]|1:iobj|3:dobj">provide</W>
<W msd="DT" in="-1:iobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">tendency</W>
<W msd="DT" in="-3:dobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pnct|2:conj|3:coord">name</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NN" in="-2:conj" out="">voice</W>
<W msd="CC" in="-3:coord" out="1:conj">and</W>
<W msd="NN" in="-1:conj" out="">support</W>
<W msd="." in="-39:pnct" out="">.</W>
</s>
<s>
<W msd="CD" in="" out="1:pnct|2:list|20:pnct">1</W>
<W msd=")" in="-1:pnct" out="">)</W>
<W msd="NNP" in="-2:list" out="1:mod|2:pnct|5:xpl">Read</W>
<W msd="NN" in="-1:mod" out="">tomorrow</W>
<W msd=":" in="-2:pnct" out="">:</W>
<W msd="NNP" in="2:title" out="">Professor</W>
<W msd="NNP" in="1:namef" out="">Preben</W>
<W msd="NNP" in="-5:xpl" out="-2:title|-1:namef|1:list">Plum</W>
<W msd="IN" in="-1:list" out="2:nobj">in</W>
<W msd="&quot;" in="1:pnct" out="">"</W>
<W msd="DT" in="-2:nobj" out="-1:pnct|1:nobj|2:mod|3:possd|4:pnct|5:mod">The</W>
<W msd="NNP" in="-1:nobj" out="">Emperor's</W>
<W msd="NNP" in="-2:mod" out="">New</W>
<W msd="NNP" in="-3:possd" out="">Consciousness</W>
<W msd="&quot;" in="-4:pnct" out="">"</W>
<W msd="IN" in="-5:mod" out="2:nobj">by</W>
<W msd="NNP" in="1:namef" out="">Roger</W>
<W msd="NNP" in="-2:nobj" out="-1:namef|1:pnct|2:mod">Penrose</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NNP" in="-2:mod" out="">Oxford</W>
<W msd="." in="-20:pnct" out="">.</W>
</s>
