<s>
<W msd="XP" tag="&amp;quot;" in="6:pnct" out="">"</W>
<W msd="PD" tag="DT" in="5:subj" out="1:nobj|2:mod">No</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">one</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">group</W>
<W msd="VADA" tag="VBD" in="" out="-6:pnct|-5:subj|1:pred|12:pnct">was</W>
<W msd="SP" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">doubt</W>
<W msd="SP" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADA" tag="VBD" in="-2:vobj" out="-1:expl|1:dobj">was</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">legal</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">claim</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">family</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">reunification</W>
<W msd="XP" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">group</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj" out="">they</W>
<W msd="VADA" tag="VBD" in="" out="-5:mod|-1:subj|1:dobj|12:pnct">realised</W>
<W msd="SP" tag="IN" in="-1:dobj" out="8:vobj">that</W>
<W msd="PP" tag="PRP" in="7:subj" out="2:appa">it</W>
<W msd="XP" tag="(" in="1:pnct" out="">(</W>
<W msd="PD" tag="DT" in="-2:appa" out="-1:pnct|1:nobj|2:pnct|3:list|4:pnct">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">halt</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-3:list" out="">red.</W>
<W msd="XP" tag=")" in="-4:pnct" out="">)</W>
<W msd="VADA" tag="VBD" in="-8:vobj" out="-7:subj|2:pred">was</W>
<W msd="ANP" tag="RB" in="1:mod" out="">legally</W>
<W msd="ANP" tag="JJ" in="-2:pred" out="-1:mod">untenable</W>
<W msd="XP" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="2:conj|15:pnct">But</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADA" tag="VBD" in="-2:conj" out="-1:expl|1:dobj">was</W>
<W msd="PI" tag="DT" in="-1:dobj" out="2:nobj">a</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">minister</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod|1:nobj">instruction</W>
<W msd="SP" tag="IN" in="-1:nobj" out="3:vobj">that</W>
<W msd="PD" tag="DT" in="2:subj|5:[subj]|6:[subj]" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">cases</W>
<W msd="VADA" tag="VBD" in="-3:vobj" out="-2:subj|1:mod|2:pred">were</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">not</W>
<W msd="U=" tag="TO" in="-2:pred" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-5:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-6:[subj]|1:avobj">dealt</W>
<W msd="SP" tag="IN" in="-1:avobj" out="">with</W>
<W msd="XP" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W msd="ANC" tag="JJR" in="2:subj|3:[subj]|4:[subj]" out="1:nobj">More</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Tamils</W>
<W msd="VA" tag="MD" in="10:qobj" out="-2:subj|1:vobj|8:pnct|9:pnct">would</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-4:[subj]|1:pobj">prevented</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">from</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:lobj">coming</W>
<W msd="SP" tag="IN" in="-1:lobj" out="1:nobj">into</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">country</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-9:pnct" out="">"</W>
<W msd="VADA" tag="VBD" in="" out="-10:qobj|3:subj|11:pnct">explained</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Police</W>
<W msd="NP=S" tag="NNP" in="1:title" out="-1:mod">Commissioner</W>
<W msd="NP=S" tag="NNP" in="-3:subj" out="-1:title|1:pnct|2:ref|3:rel">Dahlfelt</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W msd="VADA" tag="VBD" in="-3:rel" out="-1:subj|1:mod">spoke</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="1:pobj">subject</W>
<W msd="U=" tag="TO" in="-1:pobj" out="2:nobj">to</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">criminal</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">liability</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="8:pred" out="1:nobj">Among</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:ref|2:rel">those</W>
<W msd="PT" tag="WP" in="-1:ref|1:subj" out="">who</W>
<W msd="VADA" tag="VBD" in="-2:rel" out="-1:subj|1:mod">participated</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">immigration</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">meetings</W>
<W msd="VADA" tag="VBD" in="" out="-8:pred|6:subj|23:pnct">were</W>
<W msd="ANP" tag="RB" in="2:mod" out="">then</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">Permanent</W>
<W msd="NP=S" tag="NNP" in="3:title" out="-1:mod|-2:mod">Secretary</W>
<W msd="NP=S" tag="NNP" in="2:namef" out="">Poul</W>
<W msd="NP=S" tag="NNP" in="1:namel" out="">Lundbæk</W>
<W msd="NP=S" tag="NNP" in="-6:subj" out="-2:namef|-1:namel|-3:title|6:pnct|13:mod|5:conj|12:conj">Andersen</W>
<W msd="CC" tag="CC" in="4:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Deputy</W>
<W msd="NP=S" tag="NNP" in="2:title" out="-1:mod">Director</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Claus</W>
<W msd="NP=S" tag="NNP" in="-5:conj" out="-2:title|-1:namef|-4:coord">Tornøe</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="2:mod" out="1:aobj">as</W>
<W msd="ANP" tag="RB" in="-1:aobj" out="">well</W>
<W msd="CS" tag="IN" in="3:coord" out="-2:mod">as</W>
<W msd="NP=S" tag="NNP" in="2:title" out="">Director</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Frederik</W>
<W msd="NP=S" tag="NNP" in="-12:conj" out="-2:title|-1:namef|-3:coord">Schydt</W>
<W msd="SP" tag="IN" in="-13:mod" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Immigration</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod">Office</W>
<W msd="XP" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="8:pnct" out="">"</W>
<W msd="SP" tag="IN" in="7:mod" out="1:nobj|5:pnct">At</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">meeting</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">May</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Lundbæk</W>
<W msd="VADA" tag="VBD" in="" out="-8:pnct|-7:mod|-1:subj|1:dobj|27:pnct">said</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W msd="VADA" tag="VBD" in="-2:vobj" out="-1:subj|1:vobj">had</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|3:pobj">discussed</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">case</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:pnct|3:ref|4:rel">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">minister</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-3:ref|1:subj|2:[subj]" out="">who</W>
<W msd="VADA" tag="VBD" in="-4:rel" out="-1:subj|1:vobj">had</W>
<W msd="VADA" tag="VBD" in="-1:vobj" out="-2:[subj]|1:dobj">said</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADA" tag="VBD" in="-2:vobj" out="-1:expl|2:dobj|6:mod">was</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">political</W>
<W msd="NC=S" tag="NN" in="-2:dobj" out="-1:mod|2:conj">backing</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="-1:coord">support</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">deep</W>
<W msd="SP" tag="IN" in="-6:mod" out="-1:mod|1:nobj">within</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:mod|3:nobj">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Social</W>
<W msd="NP=S" tag="NNP" in="-2:mod" out="-1:mod">Democratic</W>
<W msd="NP=S" tag="NNP" in="-3:nobj" out="">Party</W>
<W msd="XP" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Lundbæk</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|3:pred|4:pnct">seemed</W>
<W msd="PI" tag="DT" in="2:mod" out="1:mod">a</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">little</W>
<W msd="VAP" tag="VBN" in="-3:pred" out="-2:mod">shaken</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|5:[subj]" out="">He</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|1:mod|4:vobj|14:pnct#|15:pnct">had</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">at</W>
<W msd="VAP" tag="VBN" in="1:mod" out="">repeated</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">meetings</W>
<W msd="VADA" tag="VBD" in="-4:vobj" out="-5:[subj]|1:dobj">said</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">would</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|3:pobj|6:mod">discuss</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">case</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">minister</W>
<W msd="AC" tag="CD" in="-6:mod|-14:pnct#" out="">again.</W>
<W msd="XP" tag="&amp;quot;" in="-15:pnct" out="">"</W>
</s>
<s>
<W msd="PD" tag="DT" in="" out="1:nobj">No</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">connection</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Police</W>
<W msd="NP=S" tag="NNP" in="1:title" out="-1:mod">Commissioner</W>
<W msd="NP=S" tag="NNP" in="7:subj|9:[subj]" out="-1:title|1:pnct">Dahlfelt</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="5:modp" out="1:nobj|4:pnct">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">hand</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VA" tag="MD" in="" out="-7:subj|-5:modp|1:mod|2:vobj|62:pnct">could</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">not</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-9:[subj]|4:dobj">support</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Deputy</W>
<W msd="NP=S" tag="NNP" in="2:title" out="-1:mod">Director</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Claus</W>
<W msd="NP=S" tag="NNP" in="-4:dobj" out="-2:title|-1:namef|1:possd">Tornøe's</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="1:nobj">explanation</W>
<W msd="SP" tag="IN" in="-1:nobj" out="10:vobj">that</W>
<W msd="PD" tag="DT" in="9:subj|10:[subj]" out="1:nobj|6:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">halt</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Tamil</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">cases</W>
<W msd="SP" tag="IN" in="-6:mod" out="1:nobj">from</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">September</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1987</W>
<W msd="VADA" tag="VBD" in="-10:vobj" out="-9:subj|1:vobj">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-10:[subj]|1:pobj">connected</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj|21:pnct|22:appa">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:dobj">plan</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:lobj|2:mod|5:dobj">send</W>
<W msd="NC=S" tag="NN" in="-1:lobj" out="">home</W>
<W msd="ANP" tag="RB" in="-2:mod" out="">forcibly</W>
<W msd="ANP" tag="RB" in="1:mod" out="">just</W>
<W msd="SP" tag="IN" in="1:mod" out="-1:mod">under</W>
<W msd="AC" tag="CD" in="-5:dobj" out="-1:mod|2:nobj|3:ref|4:rel">3,000</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Tamil</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">refugees</W>
<W msd="PT" tag="WP" in="-3:ref|1:subj|2:[subj]" out="">who</W>
<W msd="VADA" tag="VBD" in="-4:rel" out="-1:subj|1:vobj">had</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pred|3:mod">been</W>
<W msd="SP" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Denmark</W>
<W msd="SP" tag="IN" in="-3:mod" out="3:nobj">for</W>
<W msd="ANC" tag="JJR" in="2:mod" out="1:pobj">less</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:[nobj]">than</W>
<W msd="AC" tag="CD" in="-3:nobj|-1:[nobj]" out="-2:mod|1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="XP" tag="&3a;" in="-21:pnct" out="">-</W>
<W msd="PI" tag="DT" in="-22:appa" out="1:nobj|2:ref|9:rel">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">plan</W>
<W msd="SP" tag="IN" in="-2:ref|11:iobj|13:[subj]|14:[subj]" out="">that</W>
<W msd="NP=S" tag="NNP" in="6:subj|7:[subj]|9:[subj]|10:[subj]" out="1:pnct">Ninn-Hansen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VAG" tag="VBG" in="4:modp" out="1:pobj|3:pnct">according</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Tornøe</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="VADA" tag="VBD" in="-9:rel" out="-6:subj|-4:modp|1:vobj">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-7:[subj]|1:dobj">supposed</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-9:[subj]|1:vobj">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-10:[subj]|-11:iobj|1:dobj">ordered</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-13:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-14:[subj]|1:pobj">put</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">into</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">motion</W>
<W msd="XP" tag="." in="-62:pnct" out="">.</W>
</s>
