<s>
<W msd="SP" tag="IN" in="6:mod" out="1:nobj|3:pnct">In</W>
<W msd="ANS" tag="JJS" in="-1:nobj" out="1:nobj">most</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">studies</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">student</W>
<W msd="NC=P" tag="NNS" in="1:subj|2:[subj]" out="-1:mod">admissions</W>
<W msd="VADR" tag="VBP" in="" out="-6:mod|-1:subj|1:vobj|5:pnct">are</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">divided</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">into</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">quotas</W>
<W msd="XP" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">quota</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">I</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NC=P" tag="NNS" in="1:subj|2:[subj]" out="">applicants</W>
<W msd="VADR" tag="VBP" in="" out="-5:mod|-1:subj|1:vobj|6:pnct|13:conj|18:pnct">are</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">assessed</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="2:possd">their</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">grade</W>
<W msd="ANP" tag="JJ" in="-2:possd" out="-1:mod">average</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="CC" tag="CC" in="6:coord" out="">and</W>
<W msd="ANP" tag="RB" in="5:mod" out="">here</W>
<W msd="PD" tag="DT" in="4:subj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">deadline</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">application</W>
<W msd="VADR" tag="VBZ" in="-13:conj" out="-5:mod|-4:subj|-6:coord|1:mod">expires</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">on</W>
<W msd="AC" tag="CD" in="1:attr" out="">1</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:attr|1:nobj">July</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1992</W>
<W msd="XP" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="8:mod" out="1:nobj|3:pnct">In</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">quota</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">II</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PD" tag="DT" in="4:subj|5:[subj]" out="1:nobj|2:attr|3:possd|6:pnct|10:modp">the</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="">applicants'</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">individual</W>
<W msd="NC=P" tag="NNS" in="-3:possd" out="">qualifications</W>
<W msd="VADR" tag="VBP" in="" out="-8:mod|-4:subj|1:vobj|13:pnct">are</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]">assessed</W>
<W msd="XP" tag="&3a;" in="-6:pnct" out="">-</W>
<W msd="SP" tag="IN" in="3:mod" out="1:nobj|2:pnct">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">example</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-10:modp" out="-3:mod|1:attr">residence</W>
<W msd="ANP" tag="RB" in="-1:attr" out="2:conj">abroad</W>
<W msd="CC" tag="CC" in="1:coord" out="">or</W>
<W msd="SP" tag="IN" in="-2:conj" out="-1:coord|1:nobj">at</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">high</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">school</W>
<W msd="XP" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="9:conj|14:pnct">And</W>
<W msd="SP" tag="IN" in="8:mod" out="1:nobj|3:pnct">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">quota</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">II</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PD" tag="DT" in="4:subj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">deadline</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">application</W>
<W msd="VADR" tag="VBZ" in="-9:conj" out="-8:mod|-4:subj|1:mod">expires</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">on</W>
<W msd="AC" tag="CD" in="1:attr" out="">15</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:attr|1:nobj">March</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1992</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="12:pnct" out="">"</W>
<W msd="CS" tag="IN" in="11:cond" out="2:vobj">If</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">you</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj|7:pnct">are</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|1:dobj|3:mod">seeking</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">place</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">quota</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">II</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj" out="6:nobj">it</W>
<W msd="VADR" tag="VBZ" in="" out="-12:pnct|-1:subj|-11:cond|1:preds|10:pnct">is</W>
<W msd="PI" tag="DT" in="-1:preds" out="2:attr|3:nobj">a</W>
<W msd="ANP" tag="RB" in="1:degr" out="">very</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="-1:degr">good</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">idea</W>
<W msd="U=" tag="TO" in="-6:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">contact</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">educational</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">institutions</W>
<W msd="XP" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="" out="3:vobj|11:pnct">For</W>
<W msd="PP" tag="PRP" in="2:subj" out="">they</W>
<W msd="PP" tag="PRP" in="1:focal" out="">themselves</W>
<W msd="VADR" tag="VBP" in="-3:vobj" out="-2:subj|1:dobj|-1:focal">determine</W>
<W msd="PT" tag="WP" in="-1:dobj|3:[dobj]" out="2:rel">what</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">they</W>
<W msd="VA" tag="MD" in="-2:rel" out="-1:subj|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|-3:[dobj]|1:mod">stress</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">for</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">their</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">applicants</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="13:qobj" out="6:conj|12:pnct">And</W>
<W msd="PD" tag="DT" in="3:[dobj]|5:mod" out="1:attr|3:rel">the</W>
<W msd="ANC" tag="JJR" in="-1:attr" out="">more</W>
<W msd="PP" tag="PRP" in="1:subj" out="">you</W>
<W msd="VADR" tag="VBP" in="-3:rel" out="-1:subj|-3:[dobj]|1:pnct">know</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="-6:conj|4:[dobj]" out="-5:mod|1:attr|2:nobj|4:rel">the</W>
<W msd="ANC" tag="JJR" in="-1:attr" out="">better</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">chance</W>
<W msd="PP" tag="PRP" in="1:subj" out="">you</W>
<W msd="VADR" tag="VBP" in="-4:rel" out="-1:subj|-4:[dobj]|1:pnct">have</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-12:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="" out="-13:qobj|1:subj|13:pnct">says</W>
<W msd="PD" tag="DT" in="-1:subj" out="2:nobj|9:pnct|11:appa">the</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Deputy</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:mod|1:pobj">Head</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="4:nobj">the</W>
<W msd="NP=S" tag="NNP" in="3:mod" out="2:conj">Administration</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:coord">Services</W>
<W msd="NP=S" tag="NNP" in="-4:nobj" out="-3:mod">Secretariat</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Merethe</W>
<W msd="NP=S" tag="NNP" in="-11:appa" out="-1:namef">Markvard</W>
<W msd="XP" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">All</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">applicants</W>
<W msd="VA" tag="MD" in="" out="-2:subj|1:vobj|10:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:dobj|7:mod">receive</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">response</W>
<W msd="PD" tag="DT" in="1:mod" out="">no</W>
<W msd="ANP" tag="RB" in="3:attr" out="-1:mod|1:pobj">later</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:[nobj]">than</W>
<W msd="AC" tag="CD" in="1:attr" out="">28</W>
<W msd="NP=S" tag="NNP" in="-7:mod|-2:[nobj]" out="-3:attr|-1:attr|1:nobj">July</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1992</W>
<W msd="XP" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="" out="1:pnct|4:list">Graphics</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">:</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Grade</W>
<W msd="NC=S" tag="NN" in="1:mod" out="-1:mod">point</W>
<W msd="ANP" tag="JJ" in="-4:list" out="-1:mod|1:mod">average</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">for</W>
<W msd="VAP" tag="VBN" in="1:mod" out="">guaranteed</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">admission</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="" out="1:nobj|2:list|29:conj">Copenhagen</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">University</W>
<W msd="AC" tag="CD" in="-2:list" out="2:list|3:conj|5:conj|7:conj|9:conj|11:conj|14:conj|16:conj|18:conj|21:conj|23:conj">8.1</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Computer</W>
<W msd="NP=S" tag="NNP" in="-2:list" out="-1:mod">Science</W>
<W msd="AC" tag="CD" in="-3:conj" out="1:list">8.5</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Mathematics-Economics</W>
<W msd="AC" tag="CD" in="-5:conj" out="1:list">8.1</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Geology</W>
<W msd="AC" tag="CD" in="-7:conj" out="1:list">8.6</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Geography</W>
<W msd="AC" tag="CD" in="-9:conj" out="1:list">9.5</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Humanities</W>
<W msd="AC" tag="CD" in="-11:conj" out="2:list">9.5</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Literature</W>
<W msd="NC=P" tag="NNS" in="-2:list" out="-1:mod">Studies</W>
<W msd="AC" tag="CD" in="-14:conj" out="1:list">9.8</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Psychology</W>
<W msd="AC" tag="CD" in="-16:conj" out="1:list">9.6</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Law</W>
<W msd="AC" tag="CD" in="-18:conj" out="2:list">9.6</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">Political/Social</W>
<W msd="NP=P" tag="NNPS" in="-2:list" out="-1:attr">Sciences</W>
<W msd="AC" tag="CD" in="-21:conj" out="1:list">8.9</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Economics</W>
<W msd="AC" tag="CD" in="-23:conj" out="1:list">8.4</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Theology</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="-29:conj" out="1:nobj|2:list">Aarhus</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">University</W>
<W msd="AC" tag="CD" in="-2:list" out="2:list|3:conj|5:conj|7:conj|9:conj|30:conj|49:conj|51:conj|54:conj|56:conj">8.3</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Natural</W>
<W msd="NP=P" tag="NNPS" in="-2:list" out="-1:mod">Sciences</W>
<W msd="AC" tag="CD" in="-3:conj" out="1:list">9.3</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Biology</W>
<W msd="AC" tag="CD" in="-5:conj" out="1:list">9.5</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Chemistry-Biotechnology</W>
<W msd="AC" tag="CD" in="-7:conj" out="1:list">8.4</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Theology</W>
<W msd="AC" tag="CD" in="-9:conj" out="1:list">9.5</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="1:nobj|3:modp">Humanities</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">I</W>
<W msd="XP" tag="(" in="1:pnct" out="">(</W>
<W msd="ANP" tag="JJ" in="-3:modp" out="-1:pnct|1:pnct|2:conj|3:pnct|4:conj|5:pnct|6:conj|7:pnct|8:conj|9:pnct|10:conj|11:pnct|12:conj|13:pnct|15:conj|16:pnct">Danish</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="">English</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-4:conj" out="">History</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-6:conj" out="">French</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-8:conj" out="">Spanish</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-10:conj" out="">Italian</W>
<W msd="XP" tag="," in="-11:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-12:conj" out="">Portuguese/Brazilian</W>
<W msd="XP" tag="," in="-13:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Information</W>
<W msd="NP=S" tag="NNP" in="-15:conj" out="-1:mod">Science</W>
<W msd="XP" tag=")" in="-16:pnct" out="">)</W>
<W msd="AC" tag="CD" in="-30:conj" out="1:list">9.7</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="1:nobj|3:modp">Humanities</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">II</W>
<W msd="XP" tag="(" in="1:pnct" out="">(</W>
<W msd="NC=S" tag="NN" in="-3:modp" out="-1:pnct|1:pnct|3:conj|4:pnct|6:conj|7:pnct|8:conj|9:pnct|10:conj|11:pnct|13:conj|14:pnct">dramaturgy</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">art</W>
<W msd="NC=S" tag="NN" in="-3:conj" out="-1:mod">history</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">literary</W>
<W msd="NC=S" tag="NN" in="-6:conj" out="-1:attr">history</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-8:conj" out="">ethnography</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-10:conj" out="">philosophy</W>
<W msd="XP" tag="," in="-11:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">intellectual</W>
<W msd="NC=S" tag="NN" in="-13:conj" out="-1:attr">history</W>
<W msd="XP" tag=")" in="-14:pnct" out="">)</W>
<W msd="AC" tag="CD" in="-49:conj" out="1:list">9.6</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Law</W>
<W msd="AC" tag="CD" in="-51:conj" out="2:list">9.6</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">Political/Social</W>
<W msd="NP=P" tag="NNPS" in="-2:list" out="-1:attr">Sciences</W>
<W msd="AC" tag="CD" in="-54:conj" out="1:list">8.9</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Economics</W>
<W msd="AC" tag="CD" in="-56:conj" out="1:list">9.8</W>
<W msd="NP=S" tag="NNP" in="-1:list" out="">Psychology</W>
</s>
