<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">amount</W>
<W msd="VA" tag="MD" in="" out="-2:subj|1:vobj|3:pnct|20:pnct|8:conj">may</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:pred">seem</W>
<W msd="ANP" tag="JJ" in="-1:pred" out="">large</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="CC" tag="CC" in="4:coord" out="">but</W>
<W msd="SP" tag="IN" in="3:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">reality</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VADR" tag="VBZ" in="-8:conj" out="-3:mod|-1:subj|1:mod|3:pred|4:pnct|5:mod|-4:coord">is</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">only</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">small</W>
<W msd="NC=S" tag="NN" in="-3:pred" out="-1:mod">change</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-5:mod" out="2:vobj">when</W>
<W msd="PP" tag="PRP" in="1:subj" out="">you</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:pobj">look</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:mod|2:possd">Carlsberg's</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">ongoing</W>
<W msd="NC=P" tag="NNS" in="-2:possd" out="">ventures</W>
<W msd="XP" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="12:mod" out="1:nobj">In</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="3:mod|2:conj">Spain</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:coord">Portugal</W>
<W msd="ANP" tag="RB" in="-3:mod" out="">alone</W>
<W msd="SP" tag="IN" in="7:mod" out="1:nobj|5:pnct">over</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">last</W>
<W msd="ANP" tag="JJ" in="-2:nobj" out="1:nobj">few</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="NC=P" tag="NNS" in="1:subj|2:[subj]|3:[subj]" out="4:mod">investments</W>
<W msd="VADR" tag="VBP" in="" out="-12:mod|-7:mod|-1:subj|1:vobj|55:pnct|18:conj">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:vobj">been</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]">made</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">for</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">total</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">of</W>
<W msd="NP=S" tag="NNP" in="2:mod" out="">DKK</W>
<W msd="AC" tag="CD" in="1:numm" out="">1.2</W>
<W msd="AC" tag="CD" in="-3:nobj" out="-1:numm|-2:mod">billion</W>
<W msd="CC" tag="CC" in="8:coord" out="1:pnct">and</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="6:mod" out="1:nobj|4:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:mod|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">few</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">months</W>
<W msd="XP" tag="," in="-4:nobj" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:subj|10:[subj]" out="">Carlsberg</W>
<W msd="VA" tag="MD" in="-18:conj" out="-6:mod|-1:subj|1:pnct|2:mod|9:vobj|-8:coord">can</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="CS" tag="IN" in="-2:mod" out="5:vobj">if</W>
<W msd="PD" tag="DT" in="4:subj" out="1:mod|3:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">English</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">anti-trust</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:mod">authorities</W>
<W msd="VADR" tag="VBP" in="-5:vobj" out="-4:subj|1:pnct">permit</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="VAF" tag="VB" in="-9:vobj" out="-10:[subj]|1:dobj|7:lobj|13:pnct|14:mod">send</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">cheque</W>
<W msd="SP" tag="IN" in="-2:mod" out="3:nobj">for</W>
<W msd="NP=S" tag="NNP" in="2:mod" out="">DKK</W>
<W msd="AC" tag="CD" in="1:numm" out="">1.5</W>
<W msd="AC" tag="CD" in="-3:nobj" out="-1:numm|-2:mod">billion</W>
<W msd="U=" tag="TO" in="-7:lobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|3:nobj|4:appr">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">English</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">beer</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">concern</W>
<W msd="NP=S" tag="NNP" in="-4:appr" out="">Allied-Lyon</W>
<W msd="XP" tag="," in="-13:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-14:mod" out="1:nobj">as</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">payment</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">future</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="5:pobj">collaboration</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">partners</W>
<W msd="SP" tag="IN" in="-5:pobj" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">English</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">market</W>
<W msd="XP" tag="." in="-55:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="17:conj|20:pnct">And</W>
<W msd="SP" tag="IN" in="16:mod" out="1:nobj|2:pnct|3:mod">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Denmark</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="I=" tag="UH" in="-3:mod" out="1:pnct">yes</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="11:subj|13:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">question</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="VAP" tag="VBN" in="-1:mod" out="">announced</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="1:pobj">rationalisations</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">two</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Copenhagen</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">breweries</W>
<W msd="VADR" tag="VBZ" in="-17:conj" out="-11:subj|-16:mod|1:mod|2:vobj">is</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">still</W>
<W msd="VAG" tag="VBG" in="-2:vobj" out="-13:[subj]">lurking</W>
<W msd="XP" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="3:subj|5:[subj]" out="1:mod|2:nobj">The</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">financial</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">calculations</W>
<W msd="VADR" tag="VBP" in="" out="-3:subj|1:mod|2:vobj|5:pnct|11:xpl">have</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">long</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-5:[subj]|1:pred">been</W>
<W msd="SP" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">place</W>
<W msd="XP" tag="&3a;" in="-5:pnct" out="">:</W>
<W msd="NP=S" tag="NNP" in="4:mod" out="">DKK</W>
<W msd="AC" tag="CD" in="3:numm" out="1:mod">1.5</W>
<W msd="U=" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">2</W>
<W msd="AC" tag="CD" in="1:subj|2:[subj]|3:[subj]" out="-3:numm|-4:mod">billion</W>
<W msd="VA" tag="MD" in="-11:xpl" out="-1:subj|1:vobj|17:pnct">must</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]|1:pobj">invested</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj|9:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">merger</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="3:possd|2:conj">Carlsberg's</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:coord">Tuborg's</W>
<W msd="AC" tag="CD" in="-3:possd" out="1:nobj">two</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Copenhagen</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">breweries</W>
<W msd="SP" tag="IN" in="-9:mod" out="1:nobj">into</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:mod|2:nobj">one</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">common</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">brewery</W>
<W msd="XP" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="AC" tag="CD" in="2:subj" out="1:nobj">800</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">jobs</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj">cut</W>
</s>
<s>
<W msd="PD" tag="DT" in="4:subj" out="1:mod|2:nobj|3:mod">The</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">only</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">question</W>
<W msd="VAG" tag="VBG" in="-3:mod" out="">remaining</W>
<W msd="VADR" tag="VBZ" in="" out="-4:subj|1:pred|38:pnct">is</W>
<W msd="SP" tag="IN" in="-1:pred" out="3:vobj|8:pnct|10:conj">whether</W>
<W msd="PD" tag="DT" in="2:subj|3:[subj]|5:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">address</W>
<W msd="VADR" tag="VBZ" in="-3:vobj" out="-2:subj|1:vobj">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-3:[subj]|1:dobj">going</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-5:[subj]|1:pred">be</W>
<W msd="NP=S" tag="NNP" in="-1:pred" out="">Valby</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="CC" tag="CC" in="1:coord" out="">or</W>
<W msd="SP" tag="IN" in="-10:conj" out="2:vobj|-1:coord">whether</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]" out="">they</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:mod|2:vobj">will</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">instead</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-3:[subj]|1:dobj">choose</W>
<W msd="PT" tag="WP" in="-1:dobj|3:[dobj]" out="3:rel">what</W>
<W msd="PP" tag="PRP" in="2:subj" out="">they</W>
<W msd="ANP" tag="RB" in="1:mod" out="">internally</W>
<W msd="VADR" tag="VBP" in="-3:rel" out="-3:[dobj]|-2:subj|-1:mod|2:pred">call</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="NP=S" tag="NNP" in="-2:pred" out="-1:pnct|1:pnct|2:pnct|3:appa">Greenfield</W>
<W msd="XP" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W msd="XP" tag="&3a;" in="-2:pnct" out="">-</W>
<W msd="PI" tag="DT" in="-3:appa" out="2:mod|3:nobj|4:mod">a</W>
<W msd="ANP" tag="RB" in="1:mod" out="">completely</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">new</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">brewery</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">a</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">bare</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">field</W>
<W msd="ANP" tag="RB" in="-3:mod" out="1:lobj">somewhere</W>
<W msd="NC=S" tag="NN" in="-1:lobj" out="1:pobj">east</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">Great</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">Belt</W>
<W msd="XP" tag="." in="-38:pnct" out="">.</W>
</s>
