<s>
<W id="1" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="2" msd="PP" tag="PRP" in="" out="">It</W>
<W id="3" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="4" msd="ANP" tag="RB" in="" out="">quite</W>
<W id="5" msd="ANP" tag="JJ" in="" out="">clear</W>
<W id="6" msd="SP" tag="IN" in="" out="">that</W>
<W id="7" msd="NC=P" tag="NNS" in="" out="">investments</W>
<W id="8" msd="ANP" tag="RB" in="" out="">abroad</W>
<W id="9" msd="VA" tag="MD" in="" out="">will</W>
<W id="10" msd="VAF" tag="VB" in="" out="">rise</W>
<W id="11" msd="PI" tag="DT" in="" out="">a</W>
<W id="12" msd="NC=S" tag="NN" in="" out="">bit</W>
<W id="13" msd="SP" tag="IN" in="" out="">in</W>
<W id="14" msd="PD" tag="DT" in="" out="">the</W>
<W id="15" msd="VAG" tag="VBG" in="" out="">coming</W>
<W id="16" msd="NC=P" tag="NNS" in="" out="">years</W>
<W id="17" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="20" msd="CC" tag="CC" in="" out="">But</W>
<W id="21" msd="PP" tag="PRP" in="" out="">we</W>
<W id="22" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="23" msd="ANP" tag="RB" in="" out="">not</W>
<W id="24" msd="VAG" tag="VBG" in="" out="">rushing</W>
<W id="25" msd="ANP" tag="RB" in="" out="">forward</W>
<W id="26" msd="ANP" tag="RB" in="" out="">blindly</W>
<W id="27" msd="XP" tag="," in="" out="">,</W>
<W id="28" msd="ANP" tag="RB" in="" out="">so</W>
<W id="29" msd="PT" tag="WDT" in="" out="">that</W>
<W id="30" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="31" msd="PT" tag="WRB" in="" out="">why</W>
<W id="32" msd="SP" tag="IN" in="" out="">for</W>
<W id="33" msd="PD" tag="DT" in="" out="">some</W>
<W id="34" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="35" msd="U=" tag="TO" in="" out="">to</W>
<W id="36" msd="VAF" tag="VB" in="" out="">come</W>
<W id="37" msd="PP" tag="PRP" in="" out="">we</W>
<W id="38" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="39" msd="ANP" tag="RB" in="" out="">only</W>
<W id="40" msd="VAG" tag="VBG" in="" out="">talking</W>
<W id="41" msd="SP" tag="IN" in="" out="">about</W>
<W id="42" msd="PD" tag="DT" in="" out="">the</W>
<W id="43" msd="NC=S" tag="NN" in="" out="">purchase</W>
<W id="44" msd="SP" tag="IN" in="" out="">of</W>
<W id="45" msd="NC=P" tag="NNS" in="" out="">stocks</W>
<W id="46" msd="SP" tag="IN" in="" out="">in</W>
<W id="47" msd="ANP" tag="JJ" in="" out="">foreign</W>
<W id="48" msd="NC=P" tag="NNS" in="" out="">companies</W>
<W id="49" msd="PT" tag="WDT" in="" out="">that</W>
<W id="50" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="51" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="52" msd="NC=P" tag="NNS" in="" out="">subsidiaries</W>
<W id="53" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="54" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="57" msd="ANP" tag="JJ" in="" out="">ATP</W>
<W id="58" msd="NC=S" tag="NN" in="" out="">director</W>
<W id="59" msd="NP=S" tag="NNP" in="" out="">Palle</W>
<W id="60" msd="NP=S" tag="NNP" in="" out="">Simonsen</W>
<W id="61" msd="VA" tag="MD" in="" out="">will</W>
<W id="62" msd="ANP" tag="RB" in="" out="">not</W>
<W id="63" msd="VAF" tag="VB" in="" out="">say</W>
<W id="64" msd="ANP" tag="RB" in="" out="">too</W>
<W id="65" msd="ANP" tag="JJ" in="" out="">much</W>
<W id="66" msd="XP" tag="," in="" out="">,</W>
<W id="67" msd="PT" tag="WRB" in="" out="">when</W>
<W id="68" msd="PP" tag="PRP" in="" out="">he</W>
<W id="69" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="70" msd="U=" tag="TO" in="" out="">to</W>
<W id="71" msd="VAF" tag="VB" in="" out="">comment</W>
<W id="72" msd="SP" tag="IN" in="" out="">on</W>
<W id="73" msd="ANP" tag="JJ" in="" out="">future</W>
<W id="74" msd="NC=S" tag="NN" in="" out="">investment</W>
<W id="75" msd="NC=S" tag="NN" in="" out="">strategy</W>
<W id="76" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="79" msd="PP" tag="PRP" in="" out="">He</W>
<W id="80" msd="VADR" tag="VBZ" in="" out="">realises</W>
<W id="81" msd="SP" tag="IN" in="" out="">that</W>
<W id="82" msd="PD" tag="DT" in="" out="">every</W>
<W id="83" msd="ANP" tag="JJ" in="" out="">little</W>
<W id="84" msd="NC=S" tag="NN" in="" out="">movement</W>
<W id="85" msd="SP" tag="IN" in="" out="">from</W>
<W id="86" msd="NP=S" tag="NNP" in="" out="">ATP</W>
<W id="87" msd="VA" tag="MD" in="" out="">will</W>
<W id="88" msd="VAF" tag="VB" in="" out="">be</W>
<W id="89" msd="VAP" tag="VBN" in="" out="">followed</W>
<W id="90" msd="ANP" tag="RB" in="" out="">closely</W>
<W id="91" msd="SP" tag="IN" in="" out="">by</W>
<W id="92" msd="PD" tag="DT" in="" out="">the</W>
<W id="93" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="94" msd="NC=S" tag="NN" in="" out="">stock</W>
<W id="95" msd="NC=S" tag="NN" in="" out="">market</W>
<W id="96" msd="CS" tag="IN" in="" out="">because</W>
<W id="97" msd="SP" tag="IN" in="" out="">of</W>
<W id="98" msd="NP=S" tag="NNP" in="" out="">ATP's</W>
<W id="99" msd="ANP" tag="RB" in="" out="">very</W>
<W id="100" msd="ANP" tag="JJ" in="" out="">large</W>
<W id="101" msd="NC=S" tag="NN" in="" out="">significance</W>
<W id="102" msd="SP" tag="IN" in="" out="">for</W>
<W id="103" msd="PD" tag="DT" in="" out="">the</W>
<W id="104" msd="NC=S" tag="NN" in="" out="">stock</W>
<W id="105" msd="NC=S" tag="NN" in="" out="">market</W>
<W id="106" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="109" msd="NP=S" tag="NNP" in="" out="">Palle</W>
<W id="110" msd="NP=S" tag="NNP" in="" out="">Simonsen</W>
<W id="111" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="112" msd="SP" tag="IN" in="" out="">that</W>
<W id="113" msd="XP" tag="," in="" out="">,</W>
<W id="114" msd="SP" tag="IN" in="" out="">at</W>
<W id="115" msd="PD" tag="DT" in="" out="">the</W>
<W id="116" msd="NC=S" tag="NN" in="" out="">moment</W>
<W id="117" msd="XP" tag="," in="" out="">,</W>
<W id="118" msd="U=" tag="EX" in="" out="">there</W>
<W id="119" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="120" msd="PI" tag="DT" in="" out="">a</W>
<W id="121" msd="NC=S" tag="NN" in="" out="">board</W>
<W id="122" msd="NC=S" tag="NN" in="" out="">resolution</W>
<W id="123" msd="U=" tag="TO" in="" out="">to</W>
<W id="124" msd="VAF" tag="VB" in="" out="">purchase</W>
<W id="125" msd="ANP" tag="JJ" in="" out="">foreign</W>
<W id="126" msd="NC=P" tag="NNS" in="" out="">stocks</W>
<W id="127" msd="CC" tag="CC" in="" out="">and</W>
<W id="128" msd="NC=P" tag="NNS" in="" out="">bonds</W>
<W id="129" msd="SP" tag="IN" in="" out="">for</W>
<W id="130" msd="RG" tag="RP" in="" out="">up</W>
<W id="131" msd="U=" tag="TO" in="" out="">to</W>
<W id="132" msd="AC" tag="CD" in="" out="">1.5</W>
<W id="133" msd="NC=S" tag="NN" in="" out="">percent</W>
<W id="134" msd="SP" tag="IN" in="" out="">of</W>
<W id="135" msd="PD" tag="DT" in="" out="">the</W>
<W id="136" msd="NC=S" tag="NN" in="" out="">asset</W>
<W id="137" msd="NC=S" tag="NN" in="" out="">portfolio</W>
<W id="138" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="141" msd="SP" tag="IN" in="" out="">Without</W>
<W id="142" msd="VAG" tag="VBG" in="" out="">wanting</W>
<W id="143" msd="U=" tag="TO" in="" out="">to</W>
<W id="144" msd="VAF" tag="VB" in="" out="">commit</W>
<W id="145" msd="U=" tag="TO" in="" out="">to</W>
<W id="146" msd="PD" tag="DT" in="" out="">any</W>
<W id="147" msd="ANP" tag="JJ" in="" out="">particular</W>
<W id="148" msd="NC=S" tag="NN" in="" out="">percentage</W>
<W id="149" msd="XP" tag="," in="" out="">,</W>
<W id="150" msd="NP=S" tag="NNP" in="" out="">Palle</W>
<W id="151" msd="NP=S" tag="NNP" in="" out="">Simonsen</W>
<W id="152" msd="VADR" tag="VBZ" in="" out="">does</W>
<W id="153" msd="ANP" tag="RB" in="" out="">not</W>
<W id="154" msd="VAF" tag="VB" in="" out="">hide</W>
<W id="155" msd="SP" tag="IN" in="" out="">that</W>
<W id="156" msd="NP=S" tag="NNP" in="" out="">ATP</W>
<W id="157" msd="SP" tag="IN" in="" out="">in</W>
<W id="158" msd="ANP" tag="JJ" in="" out="">five-ten</W>
<W id="159" msd="NC=P" tag="NNS" in="" out="">years</W>
<W id="160" msd="VA" tag="MD" in="" out="">will</W>
<W id="161" msd="VAF" tag="VB" in="" out="">have</W>
<W id="162" msd="PI" tag="DT" in="" out="">a</W>
<W id="163" msd="ANP" tag="RB" in="" out="">significantly</W>
<W id="164" msd="ANC" tag="JJR" in="" out="">larger</W>
<W id="165" msd="NC=S" tag="NN" in="" out="">share</W>
<W id="166" msd="SP" tag="IN" in="" out="">of</W>
<W id="167" msd="ANP" tag="JJ" in="" out="">foreign</W>
<W id="168" msd="NC=P" tag="NNS" in="" out="">securities</W>
<W id="169" msd="SP" tag="IN" in="" out="">in</W>
<W id="170" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="171" msd="NC=P" tag="NNS" in="" out="">holdings</W>
<W id="172" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="175" msd="PP" tag="PRP" in="" out="">He</W>
<W id="176" msd="VADR" tag="VBZ" in="" out="">believes</W>
<W id="177" msd="SP" tag="IN" in="" out="">that</W>
<W id="178" msd="PP" tag="PRP" in="" out="">it</W>
<W id="179" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="180" msd="PI" tag="DT" in="" out="">a</W>
<W id="181" msd="ANP" tag="JJ" in="" out="">natural</W>
<W id="182" msd="NC=S" tag="NN" in="" out="">development</W>
<W id="183" msd="SP" tag="IN" in="" out="">in</W>
<W id="184" msd="PI" tag="DT" in="" out="">a</W>
<W id="185" msd="NC=S" tag="NN" in="" out="">capital</W>
<W id="186" msd="NC=S" tag="NN" in="" out="">market</W>
<W id="187" msd="PT" tag="WDT" in="" out="">that</W>
<W id="188" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="189" msd="SP" tag="IN" in="" out="">on</W>
<W id="190" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="191" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="192" msd="SP" tag="IN" in="" out="">towards</W>
<W id="193" msd="ANP" tag="RB" in="" out="">completely</W>
<W id="194" msd="VAG" tag="VBG" in="" out="">abolishing</W>
<W id="195" msd="PD" tag="DT" in="" out="">any</W>
<W id="196" msd="NC=S" tag="NN" in="" out="">form</W>
<W id="197" msd="SP" tag="IN" in="" out="">of</W>
<W id="198" msd="NC=P" tag="NNS" in="" out="">barriers</W>
<W id="199" msd="SP" tag="IN" in="" out="">across</W>
<W id="200" msd="ANP" tag="JJ" in="" out="">national</W>
<W id="201" msd="NC=P" tag="NNS" in="" out="">boundaries</W>
<W id="202" msd="XP" tag="." in="" out="">.</W>
</s>
