<s>
<W msd="PD" tag="DT" in="12:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">collection</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd|4:mod">his</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="1:coord">articles</W>
<W msd="CC" tag="CC" in="-1:coord" out="1:conj">and</W>
<W msd="VADR" tag="VBZ" in="-1:conj" out="">lectures</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">over</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">last</W>
<W msd="AC" tag="CD" in="-2:nobj" out="1:nobj">ten</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="VADR" tag="VBZ" in="" out="-12:subj|1:dobj|12:pnct">reveals</W>
<W msd="SP" tag="IN" in="-1:dobj" out="3:vobj">that</W>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">world</W>
<W msd="VADR" tag="VBZ" in="-3:vobj" out="-2:subj|1:vobj">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-3:[subj]|1:dobj">lacking</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:pnct|4:appa">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">genuine</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">article</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PD" tag="DT" in="-4:appa" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">novel</W>
<W msd="XP" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="3:mod" out="1:pnct">Still</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">it</W>
<W msd="VADR" tag="VBZ" in="" out="-3:mod|-1:subj|1:vobj|50:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">resulted</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="2:mod|3:nobj|4:ref|5:rel">an</W>
<W msd="ANP" tag="RB" in="1:mod" out="">incredibly</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">beautiful</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">book</W>
<W msd="PT" tag="WDT" in="-4:ref|1:subj" out="">that</W>
<W msd="VADR" tag="VBZ" in="-5:rel" out="-1:subj|1:iobj|2:dobj|3:pred">shows</W>
<W msd="PP" tag="PRP" in="-1:iobj" out="">us</W>
<W msd="NP=S" tag="NNP" in="-2:dobj" out="">Rushdie</W>
<W msd="CS" tag="IN" in="-3:pred" out="1:nobj">as</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:mod|2:nobj">an</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">eminent</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:coord|3:pobj">reader</W>
<W msd="CC" tag="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NC=S" tag="NN" in="-1:conj" out="1:[pobj]">interpreter</W>
<W msd="SP" tag="IN" in="-3:pobj|-1:[pobj]" out="2:nobj">of</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">fantastical</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod|1:mod|3:pnct|4:ref|5:rel">literature</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="">particular</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-4:ref|1:mod" out="">as</W>
<W msd="VAP" tag="VBN" in="-5:rel" out="-1:mod|1:pobj">created</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod|4:possd|5:pnct|8:appr|13:pnct|14:coord">the</W>
<W msd="AC" tag="CD" in="-1:mod" out="">3rd</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">world's</W>
<W msd="ANS" tag="JJS" in="-3:mod" out="">greatest</W>
<W msd="NC=P" tag="NNS" in="-4:possd" out="">novelists</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="2:namef" out="">Gabriel</W>
<W msd="NP=S" tag="NNP" in="1:namel" out="">Garcia</W>
<W msd="NP=S" tag="NNP" in="-8:appr" out="-2:namef|-1:namel|1:coord">Márquez</W>
<W msd="CC" tag="CC" in="-1:coord" out="3:conj">and</W>
<W msd="NP=S" tag="NNP" in="2:namef" out="">Mario</W>
<W msd="NP=S" tag="NNP" in="1:namel" out="">Vargas</W>
<W msd="NP=S" tag="NNP" in="-3:conj" out="-2:namef|-1:namel">Llosa</W>
<W msd="XP" tag="," in="-13:pnct" out="">,</W>
<W msd="CC" tag="CC" in="-14:coord" out="1:conj">or</W>
<W msd="PO" tag="PRP$" in="-1:conj" out="1:mod|2:possd|3:pnct|5:appr">their</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">European</W>
<W msd="NC=P" tag="NNS" in="-2:possd" out="">relations</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Italo</W>
<W msd="NP=S" tag="NNP" in="-5:appr" out="-1:namef|1:coord">Calvino</W>
<W msd="CC" tag="CC" in="-1:coord" out="2:conj">and</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Günter</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:namef">Grass</W>
<W msd="XP" tag="." in="-50:pnct" out="">.</W>
</s>
<s>
<W msd="VAP" tag="VBN" in="" out="1:pobj|35:pnct">Interspersed</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">with</W>
<W msd="ANP" tag="RB" in="1:mod" out="">heavily</W>
<W msd="ANP" tag="JJ" in="1:mod" out="-1:mod">experience-based</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod|1:pobj|14:coord">commentary</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">political</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">situation</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd|2:appr">his</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">homelands</W>
<W msd="NP=S" tag="NNP" in="-2:appr" out="1:pnct|2:conj|3:coord">India</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="">Pakistan</W>
<W msd="CC" tag="CC" in="-3:coord" out="2:conj">and</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Great</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:mod">Britain</W>
<W msd="CC" tag="CC" in="-14:coord" out="1:conj">and</W>
<W msd="NC=P" tag="NNS" in="-1:conj" out="1:pobj|7:ref|8:rel">essays</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pnct|3:mod">religion</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="1:mod" out="">especially</W>
<W msd="NP=S" tag="NNP" in="-3:mod" out="-1:mod|1:pnct">Islam</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-7:ref|1:subj|2:[subj]" out="">that</W>
<W msd="VA" tag="MD" in="-8:rel" out="-1:subj|1:vobj">can</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|4:dobj">provide</W>
<W msd="ANP" tag="RB" in="1:mod" out="">slightly</W>
<W msd="ANP" tag="RB" in="1:mod" out="-1:mod">too</W>
<W msd="VADR" tag="VBP" in="1:mod" out="-1:mod">cocksure</W>
<W msd="NC=S" tag="NN" in="-4:dobj" out="-1:mod|1:pobj">material</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">reflection</W>
<W msd="XP" tag="." in="-35:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Rushdie</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:pred|11:pnct|14:mod|37:pnct">is</W>
<W msd="NC=S" tag="NN" in="-1:pred" out="1:pobj">part</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj" out="2:mod|3:mod|4:nobj">a</W>
<W msd="ANP" tag="RB" in="1:mod" out="">very</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">strong</W>
<W msd="NP=S" tag="NNP" in="-3:mod" out="">English</W>
<W msd="NC=S" tag="NN" in="-4:nobj" out="1:pobj">tradition</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">gifted</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">journalism</W>
<W msd="XP" tag=":" in="-11:pnct" out="">-</W>
<W msd="SP" tag="IN" in="2:mod" out="1:pnct">albeit</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-14:mod" out="-2:mod|1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="2:mod|3:nobj|4:mod">a</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">complete</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">misguided</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">critique</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj|5:mod">in</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:pobj">one</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">essays</W>
<W msd="SP" tag="IN" in="-5:mod" out="2:nobj">with</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">direct</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod|1:pobj">reference</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod|5:possd|6:pnct|8:appr">this</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">genre's</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="1:coord">modern</W>
<W msd="CC" tag="CC" in="-1:coord" out="1:conj">and</W>
<W msd="ANP" tag="JJ" in="-1:conj" out="">unsurpassed</W>
<W msd="NC=S" tag="NN" in="-5:possd" out="">master</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">George</W>
<W msd="NP=S" tag="NNP" in="-8:appr" out="-1:namef">Orwell</W>
<W msd="XP" tag="." in="-37:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="1:pred" out="">This</W>
<W msd="VADR" tag="VBZ" in="" out="-1:pred|1:pred|11:pnct">is</W>
<W msd="CS" tag="IN" in="-1:pred" out="3:vobj">because</W>
<W msd="NP=S" tag="NNP" in="2:subj" out="">Rushdie</W>
<W msd="ANP" tag="RB" in="1:mod" out="">apparently</W>
<W msd="VADR" tag="VBZ" in="-3:vobj" out="-2:subj|-1:mod|1:dobj|2:mod">reads</W>
<W msd="NP=S" tag="NNP" in="-1:dobj" out="">Orwell</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">through</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:mod|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">British</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="">leftist</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">tradition</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="8:conj|12:pnct">And</W>
<W msd="SP" tag="IN" in="7:mod" out="1:nobj|4:pnct">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">all</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">leftist</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">radicals</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PD" tag="DT" in="2:subj" out="1:mod">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">British</W>
<W msd="VADR" tag="VBP" in="-8:conj" out="-7:mod|-2:subj|1:pred">are</W>
<W msd="PD" tag="DT" in="-1:pred" out="2:mod">the</W>
<W msd="ANS" tag="RBS" in="1:mod" out="">most</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">hopeless</W>
<W msd="XP" tag="." in="-12:pnct" out="">.</W>
</s>
