<s>
<W id="1" msd="NP=S" tag="NNP" in="" out="">Steen</W>
<W id="2" msd="NP=S" tag="NNP" in="" out="">Gade</W>
<W id="3" msd="VADA" tag="VBD" in="" out="">prepared</W>
<W id="4" msd="PD" tag="DT" in="" out="">the</W>
<W id="5" msd="NC=P" tag="NNS" in="" out="">delegates</W>
<W id="6" msd="SP" tag="IN" in="" out="">for</W>
<W id="7" msd="PD" tag="DT" in="" out="">the</W>
<W id="8" msd="NC=S" tag="NN" in="" out="">possibility</W>
<W id="9" msd="SP" tag="IN" in="" out="">that</W>
<W id="10" msd="NC=P" tag="NNS" in="" out="">supporters</W>
<W id="11" msd="SP" tag="IN" in="" out="">of</W>
<W id="12" msd="PD" tag="DT" in="" out="">the</W>
<W id="13" msd="NC=S" tag="NN" in="" out="">union</W>
<W id="14" msd="VA" tag="MD" in="" out="">will</W>
<W id="15" msd="VAF" tag="VB" in="" out="">conduct</W>
<W id="16" msd="PI" tag="DT" in="" out="">a</W>
<W id="17" msd="NC=S" tag="NN" in="" out="">scare</W>
<W id="18" msd="NC=S" tag="NN" in="" out="">campaign</W>
<W id="19" msd="SP" tag="IN" in="" out="">over</W>
<W id="20" msd="PD" tag="DT" in="" out="">the</W>
<W id="21" msd="ANP" tag="JJ" in="" out="">next</W>
<W id="22" msd="NC=P" tag="NNS" in="" out="">weeks</W>
<W id="23" msd="SP" tag="IN" in="" out="">against</W>
<W id="24" msd="PI" tag="DT" in="" out="">a</W>
<W id="25" msd="PD" tag="DT" in="" out="">no</W>
<W id="26" msd="U=" tag="TO" in="" out="">to</W>
<W id="27" msd="PD" tag="DT" in="" out="">the</W>
<W id="28" msd="NP=S" tag="NNP" in="" out="">European</W>
<W id="29" msd="NP=S" tag="NNP" in="" out="">Union</W>
<W id="30" msd="SP" tag="IN" in="" out="">in</W>
<W id="31" msd="PD" tag="DT" in="" out="">the</W>
<W id="32" msd="NC=S" tag="NN" in="" out="">referendum</W>
<W id="33" msd="SP" tag="IN" in="" out="">on</W>
<W id="34" msd="AC" tag="CD" in="" out="">2</W>
<W id="35" msd="NP=S" tag="NNP" in="" out="">June</W>
<W id="36" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="39" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="40" msd="PP" tag="PRP" in="" out="">We</W>
<W id="41" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="42" msd="PD" tag="DT" in="" out="">the</W>
<W id="43" msd="NC=S" tag="NN" in="" out="">right</W>
<W id="44" msd="NC=P" tag="NNS" in="" out="">arguments</W>
<W id="45" msd="SP" tag="IN" in="" out="">against</W>
<W id="46" msd="PP" tag="PRP" in="" out="">it</W>
<W id="47" msd="CC" tag="CC" in="" out="">and</W>
<W id="48" msd="ANP" tag="JJ" in="" out="">active</W>
<W id="49" msd="ANP" tag="JJ" in="" out="">no-people</W>
<W id="50" msd="ANP" tag="RB" in="" out="">here</W>
<W id="51" msd="XP" tag="," in="" out="">,</W>
<W id="52" msd="U=" tag="EX" in="" out="">there</W>
<W id="53" msd="CC" tag="CC" in="" out="">and</W>
<W id="54" msd="ANP" tag="RB" in="" out="">everywhere</W>
<W id="55" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="58" msd="CC" tag="CC" in="" out="">And</W>
<W id="59" msd="CS" tag="IN" in="" out="">so</W>
<W id="60" msd="PP" tag="PRP" in="" out="">we</W>
<W id="61" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="62" msd="VAG" tag="VBG" in="" out="">counting</W>
<W id="63" msd="SP" tag="IN" in="" out="">on</W>
<W id="64" msd="PD" tag="DT" in="" out="">the</W>
<W id="65" msd="NC=P" tag="NNS" in="" out="">people</W>
<W id="66" msd="VAG" tag="VBG" in="" out="">having</W>
<W id="67" msd="ANP" tag="RB" in="" out="">already</W>
<W id="68" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="69" msd="ANP" tag="RB" in="" out="">thoroughly</W>
<W id="70" msd="VAP" tag="VBN" in="" out="">vaccinated</W>
<W id="71" msd="SP" tag="IN" in="" out="">against</W>
<W id="72" msd="NP=S" tag="NNP" in="" out="">Uffe</W>
<W id="73" msd="NP=S" tag="NNP" in="" out="">Ellemann</W>
<W id="74" msd="CC" tag="CC" in="" out="">and</W>
<W id="75" msd="NP=S" tag="NNP" in="" out="">Jacques</W>
<W id="76" msd="NP=S" tag="NNP" in="" out="">Delors</W>
<W id="77" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="80" msd="ANP" tag="RB" in="" out="">Then</W>
<W id="81" msd="XP" tag="," in="" out="">,</W>
<W id="82" msd="PD" tag="DT" in="" out="">the</W>
<W id="83" msd="PD" tag="DT" in="" out="">no</W>
<W id="84" msd="NC=S" tag="NN" in="" out="">vote</W>
<W id="85" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="86" msd="SP" tag="IN" in="" out="">in</W>
<W id="87" msd="PD" tag="DT" in="" out="">the</W>
<W id="88" msd="NC=S" tag="NN" in="" out="">bag</W>
<W id="89" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="90" msd="XP" tag="," in="" out="">,</W>
<W id="91" msd="NP=S" tag="NNP" in="" out="">Steen</W>
<W id="92" msd="NP=S" tag="NNP" in="" out="">Gade</W>
<W id="93" msd="VADA" tag="VBD" in="" out="">thought</W>
<W id="94" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="97" msd="ANP" tag="RB" in="" out="">As</W>
<W id="98" msd="ANP" tag="RB" in="" out="">far</W>
<W id="99" msd="CS" tag="IN" in="" out="">as</W>
<W id="100" msd="PD" tag="DT" in="" out="">the</W>
<W id="101" msd="ANP" tag="JJ" in="" out="">domestic</W>
<W id="102" msd="ANP" tag="JJ" in="" out="">political</W>
<W id="103" msd="NC=S" tag="NN" in="" out="">front</W>
<W id="104" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="105" msd="VAP" tag="VBN" in="" out="">concerned</W>
<W id="106" msd="XP" tag="," in="" out="">,</W>
<W id="107" msd="PP" tag="PRP" in="" out="">he</W>
<W id="108" msd="VADA" tag="VBD" in="" out="">stressed</W>
<W id="109" msd="SP" tag="IN" in="" out="">that</W>
<W id="110" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="111" msd="NP=S" tag="NNP" in="" out="">SF</W>
<W id="112" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="113" msd="PD" tag="DT" in="" out="">the</W>
<W id="114" msd="NC=S" tag="NN" in="" out="">think</W>
<W id="115" msd="NC=S" tag="NN" in="" out="">tank</W>
<W id="116" msd="SP" tag="IN" in="" out="">for</W>
<W id="117" msd="PD" tag="DT" in="" out="">the</W>
<W id="118" msd="NC=S" tag="NN" in="" out="">whole</W>
<W id="119" msd="SP" tag="IN" in="" out="">of</W>
<W id="120" msd="NP=S" tag="NNP" in="" out="">Denmark</W>
<W id="121" msd="XP" tag="," in="" out="">,</W>
<W id="122" msd="PT" tag="WRB" in="" out="">when</W>
<W id="123" msd="PP" tag="PRP" in="" out="">it</W>
<W id="124" msd="VADR" tag="VBZ" in="" out="">comes</W>
<W id="125" msd="U=" tag="TO" in="" out="">to</W>
<W id="126" msd="NC=S" tag="NN" in="" out="">innovation</W>
<W id="127" msd="CC" tag="CC" in="" out="">and</W>
<W id="128" msd="AC" tag="CD" in="" out="">change.</W>
<W id="129" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="132" msd="CC" tag="CC" in="" out="">And</W>
<W id="133" msd="PP" tag="PRP" in="" out="">he</W>
<W id="134" msd="VADA" tag="VBD" in="" out="">characterized</W>
<W id="135" msd="PD" tag="DT" in="" out="">the</W>
<W id="136" msd="NP=S" tag="NNP" in="" out="">KV</W>
<W id="137" msd="NC=S" tag="NN" in="" out="">government</W>
<W id="138" msd="CS" tag="IN" in="" out="">as</W>
<W id="139" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="140" msd="PD" tag="DT" in="" out="">the</W>
<W id="141" msd="ANS" tag="JJS" in="" out="">most</W>
<W id="142" msd="NC=S" tag="NN" in="" out="">ragtag</W>
<W id="143" msd="NC=S" tag="NN" in="" out="">government</W>
<W id="144" msd="SP" tag="IN" in="" out="">in</W>
<W id="145" msd="NC=P" tag="NNS" in="" out="">man's</W>
<W id="146" msd="AC" tag="CD" in="" out="">memory.</W>
<W id="147" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="150" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="151" msd="CS" tag="IN" in="" out="">If</W>
<W id="152" msd="PD" tag="DT" in="" out="">the</W>
<W id="153" msd="NP=S" tag="NNP" in="" out="">Social</W>
<W id="154" msd="NP=S" tag="NNP" in="" out="">Liberal</W>
<W id="155" msd="NP=S" tag="NNP" in="" out="">Party</W>
<W id="156" msd="XP" tag="," in="" out="">,</W>
<W id="157" msd="NP=S" tag="NNP" in="" out="">CD</W>
<W id="158" msd="CC" tag="CC" in="" out="">and</W>
<W id="159" msd="NP=S" tag="NNP" in="" out="">Christian</W>
<W id="160" msd="NP=S" tag="NNP" in="" out="">People's</W>
<W id="161" msd="NP=S" tag="NNP" in="" out="">Party</W>
<W id="162" msd="VADR" tag="VBP" in="" out="">do</W>
<W id="163" msd="ANP" tag="RB" in="" out="">not</W>
<W id="164" msd="VAF" tag="VB" in="" out="">say</W>
<W id="165" msd="VAF" tag="VB" in="" out="">stop</W>
<W id="166" msd="ANP" tag="RB" in="" out="">soon</W>
<W id="167" msd="U=" tag="TO" in="" out="">to</W>
<W id="168" msd="PD" tag="DT" in="" out="">this</W>
<W id="169" msd="NC=S" tag="NN" in="" out="">decline</W>
<W id="170" msd="PT" tag="WDT" in="" out="">that</W>
<W id="171" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="172" msd="VAP" tag="VBN" in="" out="">occurred</W>
<W id="173" msd="SP" tag="IN" in="" out="">in</W>
<W id="174" msd="ANP" tag="JJ" in="" out="">ordinary</W>
<W id="175" msd="XP" tag="," in="" out="">,</W>
<W id="176" msd="ANP" tag="JJ" in="" out="">decent</W>
<W id="177" msd="ANP" tag="JJ" in="" out="">parliamentary</W>
<W id="178" msd="NC=S" tag="NN" in="" out="">behavior</W>
<W id="179" msd="XP" tag="," in="" out="">,</W>
<W id="180" msd="ANP" tag="RB" in="" out="">then</W>
<W id="181" msd="PD" tag="DT" in="" out="">these</W>
<W id="182" msd="AC" tag="CD" in="" out="">three</W>
<W id="183" msd="NC=P" tag="NNS" in="" out="">parties</W>
<W id="184" msd="VA" tag="MD" in="" out="">will</W>
<W id="185" msd="VAF" tag="VB" in="" out="">assume</W>
<W id="186" msd="PI" tag="DT" in="" out="">a</W>
<W id="187" msd="ANP" tag="JJ" in="" out="">direct</W>
<W id="188" msd="NC=S" tag="NN" in="" out="">co-responsibility</W>
<W id="189" msd="SP" tag="IN" in="" out="">for</W>
<W id="190" msd="PD" tag="DT" in="" out="">this</W>
<W id="191" msd="NC=S" tag="NN" in="" out="">decline</W>
<W id="192" msd="XP" tag="," in="" out="">,</W>
<W id="193" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="194" msd="NP=S" tag="NNP" in="" out="">Steen</W>
<W id="195" msd="NP=S" tag="NNP" in="" out="">Gade</W>
<W id="196" msd="VADA" tag="VBD" in="" out="">maintained</W>
<W id="197" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="200" msd="NP=S" tag="NNP" in="" out="">Holger</W>
<W id="201" msd="NP=S" tag="NNP" in="" out="">K.</W>
<W id="202" msd="NP=S" tag="NNP" in="" out="">Nielsen</W>
<W id="203" msd="VADA" tag="VBD" in="" out="">thought</W>
<W id="204" msd="SP" tag="IN" in="" out="">that</W>
<W id="205" msd="PD" tag="DT" in="" out="">the</W>
<W id="206" msd="NC=S" tag="NN" in="" out="">government</W>
<W id="207" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="208" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="209" msd="ANP" tag="JJ" in="" out="">rife</W>
<W id="210" msd="SP" tag="IN" in="" out="">with</W>
<W id="211" msd="NC=P" tag="NNS" in="" out="">scandals</W>
<W id="212" msd="XP" tag="," in="" out="">,</W>
<W id="213" msd="CC" tag="CC" in="" out="">and</W>
<W id="214" msd="PD" tag="DT" in="" out="">any</W>
<W id="215" msd="ANP" tag="JJ" in="" out="">political</W>
<W id="216" msd="NC=S" tag="NN" in="" out="">logic</W>
<W id="217" msd="VA" tag="MD" in="" out="">should</W>
<W id="218" msd="VAF" tag="VB" in="" out="">dictate</W>
<W id="219" msd="SP" tag="IN" in="" out="">that</W>
<W id="220" msd="PP" tag="PRP" in="" out="">it</W>
<W id="221" msd="VA" tag="MD" in="" out="">would</W>
<W id="222" msd="VAF" tag="VB" in="" out="">have</W>
<W id="223" msd="VADA" tag="VBD" in="" out="">keeled</W>
<W id="224" msd="SP" tag="IN" in="" out="">over</W>
<W id="225" msd="PI" tag="DT" in="" out="">a</W>
<W id="226" msd="ANP" tag="JJ" in="" out="">long</W>
<W id="227" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="228" msd="ANP" tag="RB" in="" out="">ago.</W>
<W id="229" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="232" msd="PP" tag="PRP" in="" out="">He</W>
<W id="233" msd="VADA" tag="VBD" in="" out="">believed</W>
<W id="234" msd="SP" tag="IN" in="" out="">that</W>
<W id="235" msd="PD" tag="DT" in="" out="">the</W>
<W id="236" msd="NC=S" tag="NN" in="" out="">government</W>
<W id="237" msd="VA" tag="MD" in="" out="">would</W>
<W id="238" msd="VAF" tag="VB" in="" out="">be</W>
<W id="239" msd="VAP" tag="VBN" in="" out="">forced</W>
<W id="240" msd="U=" tag="TO" in="" out="">to</W>
<W id="241" msd="VAF" tag="VB" in="" out="">resign</W>
<W id="242" msd="SP" tag="IN" in="" out="">in</W>
<W id="243" msd="PD" tag="DT" in="" out="">the</W>
<W id="244" msd="NC=S" tag="NN" in="" out="">fall</W>
<W id="245" msd="XP" tag="." in="" out="">.</W>
</s>
