<s>
<W msd="NP=S" tag="NNP" in="5:namef" out="">Jens</W>
<W msd="NP=S" tag="NNP" in="" out="">Chr</W>
<W msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="6:subj|7:[subj]|16:[subj]" out="-5:namef|1:pnct">Birch</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="ANP" tag="JJ" in="" out="">municipal</W>
<W msd="NC=S" tag="NN" in="" out="1:pnct">manager</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VADR" tag="VBZ" in="" out="-6:subj|1:vobj|7:mod|9:mod|21:pnct">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-7:[subj]">leaving</W>
<W msd="PD" tag="DT" in="" out="1:nobj|2:pobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">municipality</W>
<W msd="SP" tag="IN" in="-2:pobj" out="">of</W>
<W msd="NP=S" tag="NNP" in="" out="">Rødovre</W>
<W msd="SP" tag="IN" in="" out="">on</W>
<W msd="NP=S" tag="NNP" in="-7:mod" out="1:mod">October</W>
<W msd="AC" tag="CD" in="-1:mod" out="">1</W>
<W msd="U=" tag="TO" in="-9:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-16:[subj]|3:pred">become</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="VAG" tag="VBG" in="" out="">managing</W>
<W msd="NC=S" tag="NN" in="-3:pred" out="1:pobj">director</W>
<W msd="SP" tag="IN" in="-1:pobj" out="">of</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">insurance</W>
<W msd="NC=S" tag="NN" in="" out="3:appr">company</W>
<W msd="NP=S" tag="NNP" in="2:mod" out="">United</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Group</W>
<W msd="NP=S" tag="NNP" in="-3:appr" out="-1:mod|-2:mod">Life</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">He</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:vobj|25:pnct">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|3:dobj">replacing</W>
<W msd="NC=S" tag="NN" in="2:title" out="">director</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Frederik</W>
<W msd="NP=S" tag="NNP" in="-3:dobj" out="-2:title|-1:namef|1:pnct|2:ref|3:rel">Teisen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-2:ref|1:subj|2:[subj]|16:[subj]|18:[subj]" out="">who</W>
<W msd="VADR" tag="VBZ" in="-3:rel" out="-1:subj|1:vobj|13:pnct|14:coord">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:lobj|7:pnct|8:mod">been</W>
<W msd="SP" tag="IN" in="-1:lobj" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">forefront</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">company</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-8:mod" out="">since</W>
<W msd="PO" tag="PRP$" in="" out="">its</W>
<W msd="NC=S" tag="NN" in="" out="1:mod">inception</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="AC" tag="CD" in="-1:nobj|-13:pnct" out="">1964,</W>
<W msd="CC" tag="CC" in="-14:coord" out="">but</W>
<W msd="VADR" tag="VBZ" in="" out="-16:[subj]|1:mod">is</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">now</W>
<W msd="VAG" tag="VBG" in="" out="-18:[subj]">retiring</W>
<W msd="XP" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Poul</W>
<W msd="NP=S" tag="NNP" in="8:subj|9:[subj]" out="-1:namef|1:pnct|2:title">Lauritzen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:title" out="1:pobj|5:pnct">chairman</W>
<W msd="SP" tag="IN" in="-1:pobj" out="">of</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NP=S" tag="NNP" in="" out="">PL</W>
<W msd="NP=S" tag="NNP" in="" out="">Foundation</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="VADR" tag="VBZ" in="" out="-8:subj|1:vobj|8:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-9:[subj]|1:dobj|5:mod">found</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:possd">year's</W>
<W msd="AC" tag="CD" in="-1:possd" out="1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">prize-winners</W>
<W msd="SP" tag="IN" in="-5:mod" out="">in</W>
<W msd="NP=S" tag="NNP" in="" out="">Romania</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="6:subj" out="1:nobj">The</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:pobj">prizes</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">of</W>
<W msd="NP=S" tag="NNP" in="1:nobj" out="">DKK</W>
<W msd="AC" tag="CD" in="1:nobj" out="-1:nobj">100,000</W>
<W msd="PD" tag="DT" in="-3:nobj" out="-1:nobj">each</W>
<W msd="VA" tag="MD" in="" out="-6:subj">will</W>
<W msd="VAF" tag="VB" in="" out="1:pobj|29:pnct">go</W>
<W msd="U=" tag="TO" in="-1:pobj" out="4:nobj">to</W>
<W msd="ANP" tag="JJ" in="" out="">civil</W>
<W msd="NC=S" tag="NN" in="" out="">engineer</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Radu</W>
<W msd="NP=S" tag="NNP" in="-4:nobj" out="-1:namef|1:pnct|2:ref|5:rel|13:coord">Filipescu</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-2:ref|3:subj|4:[subj]" out="">who</W>
<W msd="SP" tag="IN" in="2:mod" out="1:nobj">in</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1983</W>
<W msd="VADA" tag="VBD" in="-5:rel" out="-3:subj|-2:mod">was</W>
<W msd="VAP" tag="VBN" in="" out="-4:[subj]">sentenced</W>
<W msd="U=" tag="TO" in="" out="1:dobj">to</W>
<W msd="AC" tag="CD" in="-1:dobj" out="1:nobj">10</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="SP" tag="IN" in="" out="">in</W>
<W msd="NC=S" tag="NN" in="" out="1:pnct">prison</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="CC" tag="CC" in="-13:coord" out="2:conj">and</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Viorel</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:namef|1:pnct|2:title">Oancea</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:title" out="1:coord|5:mod">mayor</W>
<W msd="CC" tag="CC" in="-1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="" out="">champion</W>
<W msd="SP" tag="IN" in="" out="">of</W>
<W msd="NC=S" tag="NN" in="" out="">liberty</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Timisoara</W>
<W msd="XP" tag="." in="-29:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="" out="">The</W>
<W msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W msd="SP" tag="IN" in="" out="">for</W>
<W msd="NP=S" tag="NNP" in="" out="">Foreign</W>
<W msd="NP=S" tag="NNP" in="" out="1:pnct">Affairs</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Uffe</W>
<W msd="NP=S" tag="NNP" in="2:subj" out="-1:namef|1:pnct">Ellemann-Jensen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VA" tag="MD" in="" out="-2:subj">will</W>
<W msd="VAF" tag="VB" in="" out="1:dobj|3:mod|5:mod|8:pnct">present</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">prizes</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">December</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:possd">Copenhagen</W>
<W msd="NP=S" tag="NNP" in="-1:possd" out="">University</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Preben</W>
<W msd="NP=S" tag="NNP" in="5:subj" out="-1:namef|1:pnct">Andersen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="" out="">offset</W>
<W msd="NC=S" tag="NN" in="" out="1:pnct">expert</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VA" tag="MD" in="" out="-5:subj">will</W>
<W msd="VAF" tag="VB" in="" out="1:mod|8:pnct|10:dobj|14:pnct">receive</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">connection</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="3:possd">his</W>
<W msd="ANP" tag="JJ" in="" out="">70th</W>
<W msd="NC=S" tag="NN" in="" out="">year</W>
<W msd="NC=S" tag="NN" in="-3:possd" out="">birthday</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="XP" tag="&quot;" in="1:pnct" out="">"</W>
<W msd="PD" tag="DT" in="-10:dobj" out="-1:pnct|1:nobj|2:nobj|3:pnct">The</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Gremlin</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">Prize</W>
<W msd="XP" tag="&quot;" in="-3:pnct" out="">"</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|13:[subj]" out="">It</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|1:vobj|11:coord|28:pnct">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj|8:mod">established</W>
<W msd="SP" tag="IN" in="-1:pobj" out="">by</W>
<W msd="PD" tag="DT" in="" out="">the</W>
<W msd="NC=S" tag="NN" in="" out="">trade</W>
<W msd="NC=S" tag="NN" in="" out="3:appr">journal</W>
<W msd="NP=S" tag="NNP" in="2:mod" out="">Current</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Graphic</W>
<W msd="NP=S" tag="NNP" in="-3:appr" out="-2:mod|-1:mod">Information</W>
<W msd="SP" tag="IN" in="-8:mod" out="1:nobj">in</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">1984</W>
<W msd="CC" tag="CC" in="-11:coord" out="1:conj">and</W>
<W msd="VADR" tag="VBZ" in="-1:conj" out="-13:[subj]|1:pobj">consists</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj|2:[subj]" out="1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">statuette</W>
<W msd="NC=S" tag="NN" in="-2:mod" out="-2:[subj]|1:pobj|5:coord">cast</W>
<W msd="SP" tag="IN" in="-1:pobj" out="3:nobj">from</W>
<W msd="ANP" tag="JJ" in="2:mod" out="">old</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">handtype</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod|-2:mod">lead</W>
<W msd="CC" tag="CC" in="-5:coord" out="1:conj">and</W>
<W msd="VAP" tag="VBN" in="-1:conj" out="1:pobj">covered</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:mod">silver</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">from</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">graphic</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">film</W>
<W msd="XP" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Dan</W>
<W msd="NP=S" tag="NNP" in="4:subj|5:[subj]" out="-1:namef|1:pnct|2:title">Turèll</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-2:title" out="1:pnct">arch-Copenhagener</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VADR" tag="VBZ" in="" out="-4:subj|1:vobj|39:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]|2:dobj">written</W>
<W msd="XP" tag="&quot;" in="1:pnct" out="">"</W>
<W msd="NP=S" tag="NNP" in="-2:dobj" out="-1:pnct|3:pnct|4:pnct|5:appa">Jutlandese</W>
<W msd="SP" tag="IN" in="" out="">for</W>
<W msd="NP=S" tag="NNP" in="" out="">Travellers</W>
<W msd="XP" tag="&quot;" in="-3:pnct" out="">"</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PI" tag="DT" in="-5:appa|6:[dobj]" out="1:mod|2:nobj|6:rel">a</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">little</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">book</W>
<W msd="SP" tag="IN" in="" out="">that</W>
<W msd="NP=S" tag="NNP" in="2:subj" out="1:nobj">Thor</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Breweries</W>
<W msd="VADR" tag="VBZ" in="-6:rel" out="-6:[dobj]|-2:subj|1:mod|3:pnct|4:mod">publishes</W>
<W msd="PD" tag="DT" in="-1:mod" out="1:nobj">each</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">year</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-4:mod" out="8:vobj">so</W>
<W msd="NP=P" tag="NNPS" in="7:subj|8:[subj]" out="1:mod">Danes</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">from</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">other</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod|1:pobj">parts</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">country</W>
<W msd="VA" tag="MD" in="-8:vobj" out="-7:subj">can</W>
<W msd="VAF" tag="VB" in="" out="-8:[subj]">get</W>
<W msd="SP" tag="IN" in="" out="1:mod|3:mod">on</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Jutlandese</W>
<W msd="SP" tag="IN" in="-3:mod" out="">without</W>
<W msd="VAG" tag="VBG" in="" out="2:mod">making</W>
<W msd="ANP" tag="RB" in="1:mod" out="">too</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="-1:mod">big</W>
<W msd="PI" tag="DT" in="" out="">a</W>
<W msd="NC=S" tag="NN" in="" out="">fool</W>
<W msd="SP" tag="IN" in="" out="">of</W>
<W msd="PP" tag="PRP" in="" out="">themselves</W>
<W msd="XP" tag="." in="-39:pnct" out="">.</W>
</s>
