<s>
<W msd="XP" tag="&amp;quot;" in="33:pnct" out="">"</W>
<W msd="CS" tag="IN" in="32:xtop" out="2:vobj|18:ref">If</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADR" tag="VBZ" in="-2:vobj" out="-1:expl|1:dobj|15:pnct">is</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:attr|2:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">necessary</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">political</W>
<W msd="VA" tag="MD" in="-3:nobj" out="2:nobj">will</W>
<W msd="PD" tag="DT" in="4:mod" out="">both</W>
<W msd="U=" tag="TO" in="-2:nobj" out="1:vobj|4:conj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:avobj">build</W>
<W msd="ANP" tag="RB" in="-1:avobj" out="">anew</W>
<W msd="CC" tag="CC" in="1:coord" out="-4:mod">and</W>
<W msd="U=" tag="TO" in="-4:conj" out="-1:coord|1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|2:pobj">appropriate</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">money</W>
<W msd="SP" tag="IN" in="-2:pobj" out="1:nobj">for</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">operations</W>
<W msd="XP" tag="," in="-15:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-18:ref|14:mod" out="">then</W>
<W msd="PI" tag="DT" in="13:subj|14:[subj]" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|5:pobj">separation</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">drama</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">division</W>
<W msd="SP" tag="IN" in="-5:pobj" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|5:possd">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pnct">Kgs</W>
<W msd="XP" tag="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="-5:possd" out="">Nytorv</W>
<W msd="VA" tag="MD" in="" out="-33:pnct|-32:xtop|-14:mod|-13:subj|1:vobj|4:pnct#|5:pnct">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-14:[subj]|1:preds">be</W>
<W msd="PI" tag="DT" in="-1:preds" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">natural</W>
<W msd="ANP" tag="JJ" in="-2:nobj|-4:pnct#" out="">result.</W>
<W msd="XP" tag="&amp;quot;" in="-5:pnct" out="">"</W>
</s>
<s>
<W msd="PD" tag="DT" in="4:subj" out="2:nobj">The</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">drama</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">head</W>
<W msd="ANP" tag="RB" in="1:add" out="">also</W>
<W msd="VADR" tag="VBZ" in="" out="-4:subj|-1:add|1:dobj">has</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj|16:pnct|20:xpl">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">clear</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">answer</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="4:dobj">proposal</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">several</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">actors</W>
<W msd="U=" tag="TO" in="-4:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|2:preds">name</W>
<W msd="PO" tag="PRP$" in="-1:dobj" out="">her</W>
<W msd="PD" tag="DT" in="-2:preds" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="XF" tag="FW" in="1:mod" out="">theatre</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">head</W>
<W msd="XP" tag="&3a;" in="-16:pnct" out="">:</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="PD" tag="DT" in="-20:xpl" out="-1:pnct|1:pnct|2:conj|4:pnct">No</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-2:conj" out="1:dobj">thank</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="">you</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="" out="1:list|4:pnct#|5:pnct">Not</W>
<W msd="SP" tag="IN" in="-1:list" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">Royal</W>
<W msd="NP=S" tag="NNP" in="-2:nobj|-4:pnct#" out="">Theatre.</W>
<W msd="XP" tag="&amp;quot;" in="-5:pnct" out="">"</W>
</s>
<s>
<W msd="VADR" tag="VBZ" in="" out="1:dobj">Has</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">deadline</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:attr">December</W>
<W msd="AC" tag="CD" in="-1:attr" out="">1</W>
</s>
<s>
<W msd="PD" tag="DT" in="17:subj|18:[subj]|19:[subj]" out="1:attr|2:nobj|3:attr|4:possd|5:pnct|6:ref|12:rel">The</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">national</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">stage's</W>
<W msd="ANP" tag="JJ" in="-3:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="-4:possd" out="">board</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-6:ref|6:subj|7:[subj]" out="">which</W>
<W msd="SP" tag="IN" in="5:mod" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:attr|2:attr|3:possd">its</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">first</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">conspicuous</W>
<W msd="NC=S" tag="NN" in="-3:possd" out="">action</W>
<W msd="VADR" tag="VBZ" in="-12:rel" out="-6:subj|-5:mod|1:vobj|4:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-7:[subj]|2:dobj">fired</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Boel</W>
<W msd="NP=S" tag="NNP" in="-2:dobj" out="-1:namef">Jørgensen</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VADR" tag="VBZ" in="" out="-17:subj|1:vobj|30:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-18:[subj]|1:vobj">been</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-19:[subj]|1:dobj|6:pobj|16:mod">given</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">deadline</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:attr">December</W>
<W msd="AC" tag="CD" in="-1:attr" out="">1</W>
<W msd="SP" tag="IN" in="-6:pobj" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|5:appr">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Minister</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Culture</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Grethe</W>
<W msd="NP=S" tag="NNP" in="-5:appr" out="-1:namef|2:mod">Rostbøll</W>
<W msd="XP" tag="(" in="1:pnct" out="">(</W>
<W msd="NP=S" tag="NNP" in="-2:mod" out="-1:pnct|1:pnct">Cons.</W>
<W msd="XP" tag=")" in="-1:pnct" out="">)</W>
<W msd="U=" tag="TO" in="-16:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">make</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">proposal</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj|3:mod">the</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">future</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr">structure</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">Royal</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="">Theatre</W>
<W msd="XP" tag="." in="-30:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="3:subj|4:[subj]" out="1:attr|2:nobj">The</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">first</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">step</W>
<W msd="VADA" tag="VBD" in="" out="-3:subj|1:vobj|11:pnct">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-4:[subj]|1:mod|8:time">taken</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:mod|3:nobj">an</W>
<W msd="VAP" tag="VBN" in="-1:mod" out="">extended</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">board</W>
<W msd="VAG" tag="VBG" in="-3:nobj" out="-1:mod">meeting</W>
<W msd="PD" tag="DT" in="2:tobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">day</W>
<W msd="CS" tag="IN" in="-8:time" out="-2:tobj|1:nobj">before</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Whitsun</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">playhouse</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:add|2:preds|5:mod|44:pnct">is</W>
<W msd="ANP" tag="RB" in="-1:add" out="">also</W>
<W msd="SP" tag="IN" in="-2:preds" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">agenda</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj">in</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|2:nobj|3:mod|25:pnct|26:mod">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">committee</W>
<W msd="VAG" tag="VBG" in="-3:mod" out="1:pobj">cutting</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">across</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|4:pnct|5:conj|9:pnct|10:conj|15:conj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Culture</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PD" tag="DT" in="-5:conj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Finance</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="PD" tag="DT" in="-10:conj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Defence</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="PD" tag="DT" in="-15:conj" out="-1:coord|1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Environment</W>
<W msd="XP" tag="," in="-25:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-26:mod" out="4:nobj|10:preds">with</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">permanent</W>
<W msd="NC=S" tag="NN" in="2:title" out="-1:attr">secretary</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Michael</W>
<W msd="NP=S" tag="NNP" in="-4:nobj" out="-1:namef|-2:title|1:mod">Christiansen</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Defence</W>
<W msd="CS" tag="IN" in="-10:preds" out="1:nobj">as</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">chairperson</W>
<W msd="XP" tag="." in="-44:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">committee</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:vobj|17:pnct">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-3:[subj]|1:mod|4:pobj">working</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">moment</W>
<W msd="SP" tag="IN" in="-4:pobj" out="1:nobj">on</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:mod|2:nobj|4:ref|8:rel">several</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">concrete</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">proposals</W>
<W msd="SP" tag="IN" in="7:pobj" out="1:nobj">of</W>
<W msd="PT" tag="WDT" in="-1:nobj|-4:ref" out="">which</W>
<W msd="PI" tag="DT" in="3:subj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">playhouse</W>
<W msd="VADR" tag="VBZ" in="-8:rel" out="-3:subj|1:preds">is</W>
<W msd="PI" tag="DT" in="-1:preds" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="-7:pobj">part</W>
<W msd="XP" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">proposals</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj|1:pnct|7:dobj|14:pnct|18:conj|31:pnct">include</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="5:modp" out="1:nobj|3:pnct">among</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">things</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">building</W>
<W msd="NC=P" tag="NNS" in="-7:dobj" out="-1:mod|-5:modp|1:mod">plans</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="2:conj">Holmen</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="PD" tag="DT" in="-2:conj" out="-1:coord|2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">harbour</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">front</W>
<W msd="XP" tag="," in="-14:pnct" out="">,</W>
<W msd="CC" tag="CC" in="3:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="2:subj" out="1:nobj">several</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">sources</W>
<W msd="VADR" tag="VBP" in="-18:conj" out="-2:subj|-3:coord|1:dobj">estimate</W>
<W msd="SP" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="U=" tag="EX" in="1:expl|2:[expl]" out="">there</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:expl|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[expl]|1:dobj|6:time">be</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj|2:mod">an</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">initiative</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">committee</W>
<W msd="SP" tag="IN" in="-6:time" out="1:nobj">during</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fall</W>
<W msd="XP" tag="." in="-31:pnct" out="">.</W>
</s>
