<s>
<W msd="SP" tag="IN" in="6:mod" out="1:nobj|2:pnct">In</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="PD" tag="DT" in="3:subj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">forest</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">fire</W>
<W msd="VADA" tag="VBD" in="" out="-6:mod|-3:subj|2:preds|25:pnct">was</W>
<W msd="ANP" tag="RB" in="1:mod" out="2:nobj">so</W>
<W msd="ANP" tag="JJ" in="-2:preds" out="-1:mod">severe</W>
<W msd="SP" tag="IN" in="-2:nobj" out="1:pnct|12:vobj">that</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VAG" tag="VBG" in="10:mod" out="1:pobj|7:pnct">according</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj|4:appr">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">Finnish</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">news</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W msd="NP=S" tag="NNP" in="-4:appr" out="">FNB</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="PD" tag="DT" in="2:subj|3:[subj]|4:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">smoke</W>
<W msd="VA" tag="MD" in="-12:vobj" out="-2:subj|-10:mod|1:vobj">could</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W msd="VADA" tag="VBD" in="-1:vobj" out="-4:[subj]|4:@dir">smelled</W>
<W msd="PD" tag="PDT" in="3:mod" out="1:nobj">all</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">way</W>
<W msd="RG" tag="RP" in="-4:@dir" out="-3:mod|1:mod">up</W>
<W msd="SP" tag="IN" in="-1:mod" out="2:nobj">in</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">southern</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:attr">Finland</W>
<W msd="XP" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W msd="CS" tag="IN" in="14:mod" out="1:nobj|7:pnct">After</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj|2:possd">several</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">days'</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="1:pobj">struggle</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fire</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="PD" tag="DT" in="6:subj" out="3:nobj|4:mod">the</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">civil</W>
<W msd="NC=S" tag="NN" in="1:mod" out="-1:attr">defense</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:mod">resources</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W msd="VADA" tag="VBD" in="" out="-14:mod|-6:subj|2:preds|3:time|5:pnct">were</W>
<W msd="ANP" tag="RB" in="1:degr" out="">completely</W>
<W msd="VAP" tag="VBN" in="-2:preds" out="-1:degr">exhausted</W>
<W msd="NC=S" tag="NN" in="-3:time" out="1:nobj">yesterday</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">afternoon</W>
<W msd="XP" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="9:subj" out="1:nobj|2:mod|4:mod">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">official</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">on</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">duty</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">local</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">emergency</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">service</W>
<W msd="VADA" tag="VBD" in="" out="-9:subj|1:pobj|6:dobj|17:pnct">said</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">Swedish</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">news</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W msd="SP" tag="IN" in="-6:dobj" out="3:vobj">that</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">extra</W>
<W msd="NC=S" tag="NN" in="1:subj|2:[subj]|3:[subj]" out="-1:attr">material</W>
<W msd="VA" tag="MD" in="-3:vobj" out="-1:subj|1:vobj">would</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:vobj">be</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]|1:pobj">transferred</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj|3:pobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">island</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Stockholm</W>
<W msd="XP" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="NC=S" tag="NN" in="4:time" out="1:pnct">Yesterday</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="AC" tag="CD" in="2:subj" out="1:nobj">seven</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">helicopters</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|1:dobj|2:pobj|11:conj|21:pnct|-4:time">took</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">part</W>
<W msd="SP" tag="IN" in="-2:pobj" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="3:nobj|4:mod">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">fire</W>
<W msd="VAG" tag="VBG" in="1:mod" out="-1:mod">fighting</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:mod">operations</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="U=" tag="EX" in="1:expl" out="">there</W>
<W msd="VADA" tag="VBD" in="-11:conj" out="-1:expl|-2:coord|1:dobj|6:preds">was</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">certain</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">amount</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">optimism</W>
<W msd="SP" tag="IN" in="-6:preds" out="1:nobj">among</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">fire</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">fighters</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">wind</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|1:vobj|6:conj|8:pnct">had</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]|1:mod">subsided</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">somewhat</W>
<W msd="CC" tag="CC" in="3:coord" out="">and</W>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fire</W>
<W msd="VADA" tag="VBD" in="-6:conj" out="-2:subj|-3:coord|1:vobj">had</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]">stabilized</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="NC=S" tag="NN" in="14:time" out="1:pnct">Yesterday</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="12:subj|14:[subj]" out="1:nobj|2:ref|3:rel">some</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">people</W>
<W msd="PT" tag="WP" in="-2:ref|1:subj|2:[subj]" out="">who</W>
<W msd="VADA" tag="VBD" in="-3:rel" out="-1:subj|1:vobj">were</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:mod|3:pobj">evacuated</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">on</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Friday</W>
<W msd="SP" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">city</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Kräklingsbo</W>
<W msd="VADA" tag="VBD" in="" out="-12:subj|1:mod|2:vobj|8:pnct|-14:time">were</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">still</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-14:[subj]|1:mod|2:pobj">quartered</W>
<W msd="ANP" tag="RB" in="-1:mod" out="">haphazardly</W>
<W msd="SP" tag="IN" in="-2:pobj" out="1:nobj">with</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="2:conj">friends</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="-1:coord">acquaintances</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="4:conj|15:pnct">But</W>
<W msd="ANP" tag="JJ" in="3:subj|4:[subj]" out="1:pobj">many</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">them</W>
<W msd="VADA" tag="VBD" in="-4:conj" out="-3:subj|1:vobj">were</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-4:[subj]|1:dobj">given</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj|3:mod">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">brief</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">opportunity</W>
<W msd="U=" tag="TO" in="-3:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:@dir|3:conj">return</W>
<W msd="NC=S" tag="NN" in="-1:@dir" out="">home</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VAF" tag="VB" in="-3:conj" out="-1:coord|1:dobj">get</W>
<W msd="NC=P" tag="NNS" in="-1:dobj" out="">belongings</W>
<W msd="XP" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="8:mod" out="1:nobj|2:prec|4:pnct">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">night</W>
<W msd="CS" tag="IN" in="-2:prec" out="1:aobj">before</W>
<W msd="ANP" tag="JJ" in="-1:aobj" out="">last</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PD" tag="DT" in="3:subj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">fire</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:mod">department</W>
<W msd="VADA" tag="VBD" in="" out="-3:subj|-8:mod|1:mod|4:mod|8:pnct">shuttled</W>
<W msd="U=" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">sea</W>
<W msd="U=" tag="TO" in="-4:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="2:dobj">get</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">extra</W>
<W msd="NC=S" tag="NN" in="-2:dobj" out="-1:attr">water</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="VAG" tag="VBG" in="18:mod" out="1:pobj|9:pnct">According</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:mod">reporters</W>
<W msd="VAP" tag="VBN" in="-1:mod" out="1:pobj">dispatched</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">Swedish</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">news</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W msd="XP" tag="," in="-9:pnct" out="">,</W>
<W msd="PD" tag="DT" in="8:subj" out="1:nobj|3:conj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fire</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="PD" tag="DT" in="-3:conj" out="-1:coord|1:nobj">the</W>
<W msd="ANP" tag="RB" in="-1:nobj" out="1:mod|3:nobj">many</W>
<W msd="VAP" tag="VBN" in="-1:mod" out="">plowed</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">fire</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:mod">breaks</W>
<W msd="VADA" tag="VBD" in="" out="-8:subj|-18:mod|2:dobj|3:mod|6:pnct|7:mod|16:pnct#?">created</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">great</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="-1:attr">gashes</W>
<W msd="SP" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">terrain</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-7:mod" out="1:nobj">so</W>
<W msd="SP" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VADR" tag="VBZ" in="-2:vobj" out="-1:subj|2:dobj">resembles</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="PI" tag="DT" in="-2:dobj" out="-1:pnct|1:mod|2:pnct|3:mod|4:nobj|5:pnct">a</W>
<W msd="NC=S" tag="NN" in="-1:mod" out="">ghost-like</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="VAP" tag="VBN" in="-3:mod" out="">ravaged</W>
<W msd="ANP" tag="JJ" in="-4:nobj|-16:pnct#?" out="">landscape.</W>
<W msd="XP" tag="&amp;quot;" in="-5:pnct" out="">"</W>
</s>
