<s>
<W id="1" msd="SP" tag="IN" in="" out="">At</W>
<W id="2" msd="ANP" tag="RB" in="" out="">almost</W>
<W id="3" msd="PD" tag="DT" in="" out="">the</W>
<W id="4" msd="ANP" tag="JJ" in="" out="">same</W>
<W id="5" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="6" msd="CS" tag="IN" in="" out="">as</W>
<W id="7" msd="PD" tag="DT" in="" out="">the</W>
<W id="8" msd="NP=S" tag="NNP" in="" out="">Government's</W>
<W id="9" msd="NC=S" tag="NN" in="" out="">proposal</W>
<W id="10" msd="SP" tag="IN" in="" out="">of</W>
<W id="11" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="12" msd="NC=S" tag="NN" in="" out="">bill</W>
<W id="13" msd="XP" tag="," in="" out="">,</W>
<W id="14" msd="NP=S" tag="NNP" in="" out="">CD</W>
<W id="15" msd="VADA" tag="VBD" in="" out="">proposed</W>
<W id="16" msd="PI" tag="DT" in="" out="">a</W>
<W id="17" msd="NC=S" tag="NN" in="" out="">motion</W>
<W id="18" msd="SP" tag="IN" in="" out="">for</W>
<W id="19" msd="PD" tag="DT" in="" out="">the</W>
<W id="20" msd="NC=S" tag="NN" in="" out="">possibility</W>
<W id="21" msd="SP" tag="IN" in="" out="">for</W>
<W id="22" msd="ANP" tag="JJ" in="" out="">anonymous</W>
<W id="23" msd="NC=S" tag="NN" in="" out="">advice</W>
<W id="24" msd="SP" tag="IN" in="" out="">for</W>
<W id="25" msd="NC=P" tag="NNS" in="" out="">children</W>
<W id="26" msd="CC" tag="CC" in="" out="">and</W>
<W id="27" msd="NC=P" tag="NNS" in="" out="">parents</W>
<W id="28" msd="XP" tag="," in="" out="">,</W>
<W id="29" msd="U=" tag="TO" in="" out="">to</W>
<W id="30" msd="PT" tag="WDT" in="" out="">which</W>
<W id="31" msd="PP" tag="PRP" in="" out="">one</W>
<W id="32" msd="VA" tag="MD" in="" out="">can</W>
<W id="33" msd="VAF" tag="VB" in="" out="">have</W>
<W id="34" msd="NC=S" tag="NN" in="" out="">recourse</W>
<W id="35" msd="PT" tag="WRB" in="" out="">when</W>
<W id="36" msd="U=" tag="EX" in="" out="">there</W>
<W id="37" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="38" msd="NC=P" tag="NNS" in="" out="">problems</W>
<W id="39" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="40" msd="SP" tag="IN" in="" out="">without</W>
<W id="41" msd="PP" tag="PRP" in="" out="">it</W>
<W id="42" msd="VAG" tag="VBG" in="" out="">leading</W>
<W id="43" msd="U=" tag="TO" in="" out="">to</W>
<W id="44" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="45" msd="PI" tag="DT" in="" out="">a</W>
<W id="46" msd="NC=S" tag="NN" in="" out="">report</W>
<W id="47" msd="VAG" tag="VBG" in="" out="">being</W>
<W id="48" msd="VAP" tag="VBN" in="" out="">made</W>
<W id="49" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="50" msd="XP" tag="," in="" out="">,</W>
<W id="51" msd="PT" tag="WDT" in="" out="">which</W>
<W id="52" msd="ANP" tag="RB" in="" out="">immediately</W>
<W id="53" msd="VADR" tag="VBZ" in="" out="">makes</W>
<W id="54" msd="NC=S" tag="NN" in="" out="">someone</W>
<W id="55" msd="SP" tag="IN" in="" out="">into</W>
<W id="56" msd="PI" tag="DT" in="" out="">a</W>
<W id="57" msd="NC=S" tag="NN" in="" out="">case</W>
<W id="58" msd="SP" tag="IN" in="" out="">in</W>
<W id="59" msd="PD" tag="DT" in="" out="">the</W>
<W id="60" msd="NC=S" tag="NN" in="" out="">system</W>
<W id="61" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="64" msd="PD" tag="DT" in="" out="">This</W>
<W id="65" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="66" msd="VAP" tag="VBN" in="" out="">conceived</W>
<W id="67" msd="CS" tag="IN" in="" out="">as</W>
<W id="68" msd="PI" tag="DT" in="" out="">a</W>
<W id="69" msd="VADR" tag="VBZ" in="" out="">means</W>
<W id="70" msd="U=" tag="TO" in="" out="">to</W>
<W id="71" msd="VAF" tag="VB" in="" out="">prevent</W>
<W id="72" msd="NC=P" tag="NNS" in="" out="">problems</W>
<W id="73" msd="PT" tag="WDT" in="" out="">that</W>
<W id="74" msd="VA" tag="MD" in="" out="">can</W>
<W id="75" msd="ANP" tag="RB" in="" out="">still</W>
<W id="76" msd="VAF" tag="VB" in="" out="">be</W>
<W id="77" msd="VAP" tag="VBN" in="" out="">solved</W>
<W id="78" msd="SP" tag="IN" in="" out="">with</W>
<W id="79" msd="NC=S" tag="NN" in="" out="">assistance</W>
<W id="80" msd="SP" tag="IN" in="" out="">from</W>
<W id="81" msd="PI" tag="DT" in="" out="">an</W>
<W id="82" msd="ANP" tag="JJ" in="" out="">impartial</W>
<W id="83" msd="NC=S" tag="NN" in="" out="">expert</W>
<W id="84" msd="SP" tag="IN" in="" out="">from</W>
<W id="85" msd="VAG" tag="VBG" in="" out="">being</W>
<W id="86" msd="VAP" tag="VBN" in="" out="">allowed</W>
<W id="87" msd="U=" tag="TO" in="" out="">to</W>
<W id="88" msd="VAF" tag="VB" in="" out="">develop</W>
<W id="89" msd="SP" tag="IN" in="" out="">into</W>
<W id="90" msd="NC=S" tag="NN" in="" out="">something</W>
<W id="91" msd="PT" tag="WDT" in="" out="">that</W>
<W id="92" msd="VA" tag="MD" in="" out="">can</W>
<W id="93" msd="VAF" tag="VB" in="" out="">end</W>
<W id="94" msd="SP" tag="IN" in="" out="">in</W>
<W id="95" msd="PI" tag="DT" in="" out="">an</W>
<W id="96" msd="ANP" tag="JJ" in="" out="">unhappy</W>
<W id="97" msd="ANP" tag="JJ" in="" out="">forcible</W>
<W id="98" msd="NC=S" tag="NN" in="" out="">removal</W>
<W id="99" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="102" msd="PD" tag="DT" in="" out="">This</W>
<W id="103" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="104" msd="VAP" tag="VBN" in="" out="">proposed</W>
<W id="105" msd="CS" tag="IN" in="" out="">as</W>
<W id="106" msd="PI" tag="DT" in="" out="">an</W>
<W id="107" msd="NC=S" tag="NN" in="" out="">amendment</W>
<W id="108" msd="U=" tag="TO" in="" out="">to</W>
<W id="109" msd="PD" tag="DT" in="" out="">the</W>
<W id="110" msd="NC=P" tag="NNS" in="" out="">minister's</W>
<W id="111" msd="VADR" tag="VBP" in="" out="">bill</W>
<W id="112" msd="XP" tag="," in="" out="">,</W>
<W id="113" msd="PT" tag="WDT" in="" out="">which</W>
<W id="114" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="115" msd="VAP" tag="VBN" in="" out="">approved</W>
<W id="116" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="117" msd="CC" tag="CC" in="" out="">but</W>
<W id="118" msd="ANP" tag="RB" in="" out="">nevertheless</W>
<W id="119" msd="SP" tag="IN" in="" out="">without</W>
<W id="120" msd="NP=S" tag="NNP" in="" out="">CD</W>
<W id="121" msd="VAG" tag="VBG" in="" out="">being</W>
<W id="122" msd="ANP" tag="JJ" in="" out="">able</W>
<W id="123" msd="U=" tag="TO" in="" out="">to</W>
<W id="124" msd="VAF" tag="VB" in="" out="">vote</W>
<W id="125" msd="SP" tag="IN" in="" out="">for</W>
<W id="126" msd="PD" tag="DT" in="" out="">the</W>
<W id="127" msd="NC=S" tag="NN" in="" out="">law</W>
<W id="128" msd="CS" tag="IN" in="" out="">as</W>
<W id="129" msd="PI" tag="DT" in="" out="">a</W>
<W id="130" msd="NC=S" tag="NN" in="" out="">whole</W>
<W id="131" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="134" msd="SP" tag="IN" in="" out="">In</W>
<W id="135" msd="NP=S" tag="NNP" in="" out="">CD's</W>
<W id="136" msd="NC=S" tag="NN" in="" out="">view</W>
<W id="137" msd="XP" tag="," in="" out="">,</W>
<W id="138" msd="PP" tag="PRP" in="" out="">it</W>
<W id="139" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="140" msd="NC=P" tag="NNS" in="" out="">faults</W>
<W id="141" msd="CC" tag="CC" in="" out="">and</W>
<W id="142" msd="NC=P" tag="NNS" in="" out="">omissions</W>
<W id="143" msd="PT" tag="WDT" in="" out="">that</W>
<W id="144" msd="VADA" tag="VBD" in="" out="">made</W>
<W id="145" msd="PP" tag="PRP" in="" out="">us</W>
<W id="146" msd="VADR" tag="VBP" in="" out="">consider</W>
<W id="147" msd="PP" tag="PRP" in="" out="">it</W>
<W id="148" msd="ANP" tag="RB" in="" out="">too</W>
<W id="149" msd="ANP" tag="JJ" in="" out="">incomprehensible</W>
<W id="150" msd="SP" tag="IN" in="" out="">that</W>
<W id="151" msd="PI" tag="DT" in="" out="">a</W>
<W id="152" msd="ANP" tag="JJ" in="" out="">non-socialist</W>
<W id="153" msd="NC=S" tag="NN" in="" out="">government</W>
<W id="154" msd="VA" tag="MD" in="" out="">would</W>
<W id="155" msd="VAF" tag="VB" in="" out="">be</W>
<W id="156" msd="PI" tag="DT" in="" out="">a</W>
<W id="157" msd="NC=S" tag="NN" in="" out="">sponsor</W>
<W id="158" msd="SP" tag="IN" in="" out="">of</W>
<W id="159" msd="PP" tag="PRP" in="" out="">it</W>
<W id="160" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="163" msd="CS" tag="IN" in="" out="">As</W>
<W id="164" msd="ANP" tag="RB" in="" out="">undoubtedly</W>
<W id="165" msd="NC=S" tag="NN" in="" out="">everyone</W>
<W id="166" msd="ANP" tag="RB" in="" out="">else</W>
<W id="167" msd="VADR" tag="VBZ" in="" out="">does</W>
<W id="168" msd="XP" tag="," in="" out="">,</W>
<W id="169" msd="NP=S" tag="NNP" in="" out="">CD</W>
<W id="170" msd="VADR" tag="VBZ" in="" out="">puts</W>
<W id="171" msd="ANP" tag="JJ" in="" out="">decisive</W>
<W id="172" msd="NC=S" tag="NN" in="" out="">weight</W>
<W id="173" msd="SP" tag="IN" in="" out="">on</W>
<W id="174" msd="PD" tag="DT" in="" out="">the</W>
<W id="175" msd="NC=S" tag="NN" in="" out="">fact</W>
<W id="176" msd="SP" tag="IN" in="" out="">that</W>
<W id="177" msd="ANP" tag="JJ" in="" out="">forcible</W>
<W id="178" msd="NC=P" tag="NNS" in="" out="">removals</W>
<W id="179" msd="XP" tag="," in="" out="">,</W>
<W id="180" msd="PT" tag="WRB" in="" out="">when</W>
<W id="181" msd="PP" tag="PRP" in="" out="">they</W>
<W id="182" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="183" msd="ANP" tag="JJ" in="" out="">unavoidable</W>
<W id="184" msd="XP" tag="," in="" out="">,</W>
<W id="185" msd="VAF" tag="VB" in="" out="">happen</W>
<W id="186" msd="ANP" tag="RB" in="" out="">as</W>
<W id="187" msd="ANP" tag="RB" in="" out="">cautiously</W>
<W id="188" msd="CS" tag="IN" in="" out="">as</W>
<W id="189" msd="ANP" tag="JJ" in="" out="">possible</W>
<W id="190" msd="XP" tag="." in="" out="">.</W>
</s>
