<s>
<W msd="IN" in="14:mod" out="1:mod|2:nobj|12:pnct">At</W>
<W msd="RB" in="-1:mod" out="">almost</W>
<W msd="DT" in="-2:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">same</W>
<W msd="NN" in="-2:nobj" out="1:pobj">time</W>
<W msd="IN" in="-1:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:possd">the</W>
<W msd="NNP" in="-1:nobj" out="">Government's</W>
<W msd="NN" in="-2:possd" out="1:pobj">proposal</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PRP$" in="-1:nobj" out="1:possd">its</W>
<W msd="NN" in="-1:possd" out="">bill</W>
<W msd="," in="-12:pnct" out="">,</W>
<W msd="NNP" in="1:subj" out="">CD</W>
<W msd="VBD" in="" out="-1:subj|46:pnct|1:dobj|-14:mod">proposed</W>
<W msd="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj">motion</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">possibility</W>
<W msd="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="JJ" in="1:mod" out="">anonymous</W>
<W msd="NN" in="-2:nobj" out="-1:mod|1:mod|5:pnct|7:ref|9:rel">advice</W>
<W msd="IN" in="-1:mod" out="1:nobj">for</W>
<W msd="NNS" in="-1:nobj" out="1:coord">children</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NNS" in="-1:conj" out="">parents</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="TO" in="5:pobj" out="1:nobj">to</W>
<W msd="WDT" in="-7:ref|-1:nobj" out="">which</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">one</W>
<W msd="MD" in="-9:rel" out="-1:subj|3:mod|8:mod|1:vobj">can</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:dobj">have</W>
<W msd="NN" in="-1:dobj" out="-5:pobj">recourse</W>
<W msd="WRB" in="-3:mod" out="2:vobj">when</W>
<W msd="EX" in="1:expl" out="">there</W>
<W msd="VBP" in="-2:vobj" out="-1:expl|1:dobj|2:pnct">are</W>
<W msd="NNS" in="-1:dobj" out="">problems</W>
<W msd=":" in="-2:pnct" out="">-</W>
<W msd="IN" in="-8:mod" out="2:nobj">without</W>
<W msd="PRP" in="1:subj" out="">it</W>
<W msd="VBG" in="-2:nobj" out="-1:subj|1:lobj">leading</W>
<W msd="TO" in="-1:lobj" out="4:nobj">to</W>
<W msd="&quot;" in="3:pnct" out="">"</W>
<W msd="DT" in="2:subj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="">report</W>
<W msd="VBG" in="-4:nobj" out="-3:pnct|2:pnct|3:pnct|4:ref|6:rel|-2:subj|1:vobj">being</W>
<W msd="VBN" in="-1:vobj" out="">made</W>
<W msd="&quot;" in="-2:pnct" out="">"</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="WDT" in="-4:ref|2:subj" out="">which</W>
<W msd="RB" in="1:mod" out="">immediately</W>
<W msd="VBZ" in="-6:rel" out="-2:subj|-1:mod|1:dobj|2:pobj">makes</W>
<W msd="NN" in="-1:dobj" out="">someone</W>
<W msd="IN" in="-2:pobj" out="1:nobj">into</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">a</W>
<W msd="NN" in="-1:nobj" out="">case</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">system</W>
<W msd="." in="-46:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="1:subj|2:[subj]" out="">This</W>
<W msd="VBD" in="" out="-1:subj|1:vobj|34:pnct">was</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">conceived</W>
<W msd="IN" in="-1:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">a</W>
<W msd="VBZ" in="-1:nobj" out="">means</W>
<W msd="TO" in="-2:mod" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|13:pobj">prevent</W>
<W msd="NNS" in="-1:dobj" out="1:ref|2:rel">problems</W>
<W msd="WDT" in="-1:ref|1:subj|3:[subj]|4:[subj]" out="">that</W>
<W msd="MD" in="-2:rel" out="-1:subj|1:mod|2:vobj">can</W>
<W msd="RB" in="-1:mod" out="">still</W>
<W msd="VB" in="-2:vobj" out="-3:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-4:[subj]|1:mod">solved</W>
<W msd="IN" in="-1:mod" out="1:nobj">with</W>
<W msd="NN" in="-1:nobj" out="1:pobj">assistance</W>
<W msd="IN" in="-1:pobj" out="1:nobj">from</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">an</W>
<W msd="JJ" in="-1:mod" out="">impartial</W>
<W msd="NN" in="-2:nobj" out="">expert</W>
<W msd="IN" in="-13:pobj" out="1:nobj">from</W>
<W msd="VBG" in="-1:nobj" out="1:vobj">being</W>
<W msd="VBN" in="-1:vobj" out="1:dobj">allowed</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pobj">develop</W>
<W msd="IN" in="-1:pobj" out="1:nobj">into</W>
<W msd="NN" in="-1:nobj" out="1:ref|2:rel">something</W>
<W msd="WDT" in="-1:ref|1:subj|2:[subj]" out="">that</W>
<W msd="MD" in="-2:rel" out="-1:subj|1:vobj">can</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:pobj">end</W>
<W msd="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:mod|3:nobj">an</W>
<W msd="JJ" in="-1:mod" out="">unhappy</W>
<W msd="JJ" in="-2:mod" out="">forcible</W>
<W msd="NN" in="-3:nobj" out="">removal</W>
<W msd="." in="-34:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="1:subj|2:[subj]" out="">This</W>
<W msd="VBD" in="" out="-1:subj|1:vobj|14:coord|28:pnct">was</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">proposed</W>
<W msd="IN" in="-1:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:nobj">an</W>
<W msd="NN" in="-1:nobj" out="1:pobj">amendment</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:nobj|3:pnct|4:ref|5:rel|2:possd">the</W>
<W msd="NNS" in="-1:nobj" out="">minister's</W>
<W msd="VBP" in="-2:possd" out="">bill</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="WDT" in="-4:ref|1:subj|2:[subj]" out="">which</W>
<W msd="VBD" in="-5:rel" out="-1:subj|1:vobj|2:pnct">was</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]">approved</W>
<W msd=":" in="-2:pnct" out="">-</W>
<W msd="CC" in="-14:coord" out="1:<mod>|2:<mod>">but</W>
<W msd="RB" in="-1:<mod>" out="">nevertheless</W>
<W msd="IN" in="-2:<mod>" out="2:nobj">without</W>
<W msd="NNP" in="1:subj" out="">CD</W>
<W msd="VBG" in="-2:nobj" out="-1:subj|1:pred">being</W>
<W msd="JJ" in="-1:pred" out="1:nobj">able</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pobj">vote</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W msd="NN" in="-1:nobj" out="">law</W>
<W msd="IN" in="-2:mod" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="">whole</W>
<W msd="." in="-28:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W msd="NNP" in="-1:nobj" out="1:possd">CD's</W>
<W msd="NN" in="-1:possd" out="">view</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="PRP" in="1:subj" out="">it</W>
<W msd="VBD" in="" out="-1:subj|-5:mod|1:dobj|21:pnct">had</W>
<W msd="NNS" in="-1:dobj" out="1:coord|3:ref|4:rel">faults</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NNS" in="-1:conj" out="">omissions</W>
<W msd="WDT" in="-3:ref|1:subj" out="">that</W>
<W msd="VBD" in="-4:rel" out="-1:subj|2:vobj">made</W>
<W msd="PRP" in="1:subj" out="">us</W>
<W msd="VBP" in="-2:vobj" out="-1:subj|1:dobj|3:pred">consider</W>
<W msd="PRP" in="-1:dobj" out="3:nobj">it</W>
<W msd="RB" in="1:mod" out="">too</W>
<W msd="JJ" in="-3:pred" out="-1:mod">incomprehensible</W>
<W msd="IN" in="-3:nobj" out="4:vobj">that</W>
<W msd="DT" in="3:subj|4:[subj]" out="1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">non-socialist</W>
<W msd="NN" in="-2:nobj" out="">government</W>
<W msd="MD" in="-4:vobj" out="-3:subj|1:vobj">would</W>
<W msd="VB" in="-1:vobj" out="-4:[subj]|1:pred">be</W>
<W msd="DT" in="-1:pred" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj">sponsor</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PRP" in="-1:nobj" out="">it</W>
<W msd="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="7:mod" out="4:vobj">As</W>
<W msd="RB" in="3:mod" out="">undoubtedly</W>
<W msd="NN" in="2:subj" out="1:nobj">everyone</W>
<W msd="RB" in="-1:nobj" out="">else</W>
<W msd="VBZ" in="-4:vobj" out="-3:mod|-2:subj|1:pnct">does</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NNP" in="1:subj" out="">CD</W>
<W msd="VBZ" in="" out="-7:mod|-1:subj|2:dobj|20:pnct">puts</W>
<W msd="JJ" in="1:mod" out="">decisive</W>
<W msd="NN" in="-2:dobj" out="-1:mod|1:pobj">weight</W>
<W msd="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:nobj">fact</W>
<W msd="IN" in="-1:nobj" out="9:vobj">that</W>
<W msd="JJ" in="1:mod" out="">forcible</W>
<W msd="NNS" in="7:subj" out="1:pnct|-1:mod">removals</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="WRB" in="5:mod" out="2:vobj">when</W>
<W msd="PRP" in="1:subj" out="">they</W>
<W msd="VBP" in="-2:vobj" out="-1:subj|1:pred|2:pnct">are</W>
<W msd="JJ" in="-1:pred" out="">unavoidable</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="VB" in="-9:vobj" out="-5:mod|2:mod|-7:subj">happen</W>
<W msd="RB" in="1:mod" out="2:pobj">as</W>
<W msd="RB" in="-2:mod" out="-1:mod">cautiously</W>
<W msd="IN" in="-2:pobj" out="1:aobj">as</W>
<W msd="JJ" in="-1:aobj" out="">possible</W>
<W msd="." in="-20:pnct" out="">.</W>
</s>
