<s>
<W msd="CC" tag="CC" in="2:discmark" out="">But</W>
<W msd="PP" tag="PRP" in="1:subj" out="12:vobj">it</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|-2:discmark|1:preds|14:pnct">was</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="6:nobj|41:assoc-telic">the</W>
<W msd="NC=S" tag="NN" in="5:attr|5:{const}" out="1:attr|1:{const}">fricassee</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{const}" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="2:conj">pike</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="-1:coord">trout</W>
<W msd="NC=S" tag="NN" in="-6:nobj" out="-5:attr|-5:{const}">dish</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Preben</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:namef|2:coref|30:coref-iden">Madsen</W>
<W msd="VADA" tag="VBD" in="-12:vobj" out="-1:subj|1:dobj">landed</W>
<W msd="PO" tag="PRP$" in="-1:dobj|-2:coref|1:{agent}" out="1:possd|21:assoc-telic">his</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:{agent}">victory</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="14:add" out="1:nobj|5:pnct">In</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">addition</W>
<W msd="U=" tag="TO" in="-1:pobj" out="2:nobj">to</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">local</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr">judges</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Erwin</W>
<W msd="NP=S" tag="NNP" in="7:subj" out="-1:namef|1:pnct|2:attr|2:{source}">Lauterbach</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:attr|-2:{source}" out="1:attr|1:{loc}|4:pnct">Saison</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{loc}" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Skovshoved</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Hotel</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VADA" tag="VBD" in="" out="-7:subj|-14:add|1:preds|6:pnct">was</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj">on</W>
<W msd="PD" tag="DT" in="-1:nobj|-21:assoc-telic" out="1:nobj|2:attr">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:{const}">panel</W>
<W msd="SP" tag="IN" in="-2:attr|-1:{const}" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">judges</W>
<W msd="XP" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="-30:coref-iden|1:subj" out="174:coref-iden">Madsen</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|1:iobj|2:dobj|4:pnct">gave</W>
<W msd="PP" tag="PRP" in="-1:iobj" out="">me</W>
<W msd="PD" tag="DT" in="-2:dobj|-41:assoc-telic" out="1:nobj|5:assoc-const">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">recipe</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="-5:assoc-const|2:subj" out="1:nobj">The</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">ingredients</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj|1:pnct|2:preds|56:pnct">are</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">:</W>
<W msd="AC" tag="CD" in="-2:preds" out="2:nobj|3:pnct|4:conj|7:pnct|8:conj|14:pnct|15:conj|19:pnct|20:conj|24:pnct|25:conj|29:pnct|30:conj|36:pnct|37:conj|42:pnct|43:conj|47:pnct|48:conj|51:conj|58:coref-var">400g</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">pike</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{const}#">filet</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-4:conj" out="2:nobj|54:coref-var">400g</W>
<W msd="NC=P" tag="NNS" in="1:attr|1:{const}#" out="">trout</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{const}#">filet</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-8:conj" out="2:nobj|3:attr|134:coref-var">150g</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{loc}#" out="">country</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{loc}#|1:{form}">ham</W>
<W msd="SP" tag="IN" in="-3:attr|-1:{form}" out="2:nobj">in</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">julienne</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:mod">strips</W>
<W msd="XP" tag="," in="-14:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-15:conj" out="1:attr|3:nobj|63:coref-var">two</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">small</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{time}#" out="">spring</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:attr|-1:{time}#">cabbages</W>
<W msd="XP" tag="," in="-19:pnct" out="">,</W>
<W msd="PI" tag="DT" in="-20:conj" out="1:nobj|2:attr">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:{const}">bunch</W>
<W msd="SP" tag="IN" in="-2:attr|-1:{const}" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">parsley</W>
<W msd="XP" tag="," in="-24:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-25:conj" out="1:nobj">two</W>
<W msd="NC=S" tag="NN" in="-1:nobj|2:{apart}" out="2:nobj">dl</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">vegetable</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-2:{apart}|-1:attr|-1:{const}#">bouillon</W>
<W msd="XP" tag="," in="-29:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-30:conj" out="1:attr|2:nobj|3:attr|61:coref-var">two</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">thin</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="1:{form}">leeks</W>
<W msd="VADR" tag="VBP" in="-3:attr|-1:{form}" out="1:pobj">cut</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">rings</W>
<W msd="XP" tag="," in="-36:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-37:conj" out="1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj|3:{apart}" out="3:nobj">teaspoons</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">whole</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="-1:attr">seed</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:attr|-1:{const}#|-3:{apart}">mustard</W>
<W msd="XP" tag="," in="-42:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-43:conj" out="1:nobj">two</W>
<W msd="NC=P" tag="NNS" in="-1:nobj|2:{apart}" out="2:nobj">teaspoons</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">ordinary</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-2:{apart}">vinegar</W>
<W msd="XP" tag="," in="-47:pnct" out="">,</W>
<W msd="AC" tag="CD" in="-48:conj|1:{apart}" out="1:nobj">200g</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="-1:{apart}">butter</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-51:conj" out="-1:coord|2:conj">salt</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="-1:coord">pepper</W>
<W msd="XP" tag="." in="-56:pnct" out="">.</W>
</s>
<s>
<W msd="VAF" tag="VB" in="" out="1:dobj|3:man|5:pnct|6:conj|18:pnct">Cut</W>
<W msd="PD" tag="DT" in="-1:dobj|-58:coref-var|-54:coref-var" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fish</W>
<W msd="SP" tag="IN" in="-3:man" out="1:nobj">in</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="3:coref">cubes</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-6:conj" out="1:dobj|2:loc|6:loc|7:assoc-inst|9:man">bake</W>
<W msd="PP" tag="PRP" in="-1:dobj|-3:coref" out="57:coref-iden">them</W>
<W msd="SP" tag="IN" in="-2:loc" out="3:nobj">on</W>
<W msd="VAP" tag="VBN" in="2:attr" out="">buttered</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{goal}#" out="">baking</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-2:attr|-1:attr|-1:{goal}#">sheets</W>
<W msd="SP" tag="IN" in="-6:loc" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj|-7:assoc-inst" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">oven</W>
<W msd="SP" tag="IN" in="-9:man" out="1:nobj">at</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">140</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">degrees</W>
<W msd="XP" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="-63:coref-var|2:subj|3:[subj]" out="1:nobj|47:coref-iden">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">cabbage</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:vobj|4:pnct">is</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]|1:time">cooked</W>
<W msd="CS" tag="IN" in="-1:time" out="1:preds">until</W>
<W msd="NC=S" tag="NN" in="-1:preds" out="">tender</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="" out="1:nobj|2:pnct|3:xpl|30:pnct|48:coref-iden">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">sauce</W>
<W msd="XP" tag="&3a;" in="-2:pnct" out="">:</W>
<W msd="NP=S" tag="NNP" in="-3:xpl" out="1:dobj|4:loc|7:pnct|8:conj|10:pnct|11:conj|14:pnct|15:conj|19:pnct|20:conj|23:pnct|24:conj">Steam</W>
<W msd="PD" tag="DT" in="-1:dobj|-61:coref-var" out="2:nobj|8:coref">the</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">leek</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr|-1:{const}#">rings</W>
<W msd="SP" tag="IN" in="-4:loc" out="2:nobj">in</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">vegetable</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{const}#|6:coref-var">bouillon</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-8:conj" out="1:dobj">remove</W>
<W msd="PP" tag="PRP" in="-1:dobj|-8:coref" out="">them</W>
<W msd="XP" tag="," in="-10:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-11:conj" out="1:dobj">reduce</W>
<W msd="PD" tag="DT" in="-1:dobj|-6:coref-var" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">bouillon</W>
<W msd="XP" tag="," in="-14:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-15:conj" out="1:dobj">add</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="2:conj">vinegar</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="-1:coord">mustard</W>
<W msd="XP" tag="," in="-19:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-20:conj" out="1:loc">stir</W>
<W msd="SP" tag="IN" in="-1:loc" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">butter</W>
<W msd="XP" tag="," in="-23:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-24:conj" out="2:dobj">add</W>
<W msd="VAP" tag="VBN" in="1:attr" out="">chopped</W>
<W msd="NC=S" tag="NN" in="-2:dobj" out="-1:attr">parsley</W>
<W msd="XP" tag="." in="-30:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="" out="1:dobj|4:accom|10:pnct|11:conj|21:conj|26:pnct">Serve</W>
<W msd="PD" tag="DT" in="-1:dobj|-57:coref-iden" out="2:nobj|17:coref-iden">the</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">fish</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="-1:attr|-1:{const}#">cubes</W>
<W msd="SP" tag="IN" in="-4:accom" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj|-47:coref-iden" out="1:nobj|4:conj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">cabbage</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">leek</W>
<W msd="NC=P" tag="NNS" in="-4:conj" out="-2:coord|-1:attr|-1:{const}#">rings</W>
<W msd="XP" tag="," in="-10:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-11:conj" out="1:dobj|6:@loc">pour</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr">a</W>
<W msd="ANP" tag="JJ" in="-1:attr|1:{apart}" out="1:pobj">little</W>
<W msd="SP" tag="IN" in="-1:pobj" out="-1:{apart}|1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj|-48:coref-iden" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">sauce</W>
<W msd="SP" tag="IN" in="-6:@loc" out="1:nobj">over</W>
<W msd="PD" tag="DT" in="-1:nobj|-17:coref-iden" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fish</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VADR" tag="VBP" in="-21:conj" out="-1:coord|1:dobj|3:@loc">sprinkle</W>
<W msd="PD" tag="DT" in="-1:dobj|-134:coref-var" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">ham</W>
<W msd="SP" tag="IN" in="-3:@loc" out="1:nobj">on</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">top</W>
<W msd="XP" tag="." in="-26:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]" out="">You</W>
<W msd="VA" tag="MD" in="" out="-1:subj|1:add|2:vobj|8:pnct">may</W>
<W msd="ANP" tag="RB" in="-1:add" out="">also</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-3:[subj]|2:dobj|3:predo">serve</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">new</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="-1:attr">potatoes</W>
<W msd="ANP" tag="JJ" in="-3:predo" out="1:man">baked</W>
<W msd="SP" tag="IN" in="-1:man" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">butter</W>
<W msd="XP" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Preben</W>
<W msd="NP=S" tag="NNP" in="8:subj|9:[subj]|-174:coref-iden" out="-1:namef|1:pnct|2:ref|3:relr|19:coref">Madsen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W msd="VADR" tag="VBZ" in="-3:relr" out="-1:subj|3:preds|4:pnct">is</W>
<W msd="AC" tag="CD" in="2:attr" out="1:nobj">31</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="ANP" tag="JJ" in="-3:preds" out="-2:attr">old</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VADA" tag="VBD" in="" out="-8:subj|1:vobj|5:pnct">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-9:[subj]|1:loc">trained</W>
<W msd="SP" tag="IN" in="-1:loc" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Hovborg</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Inn</W>
<W msd="XP" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="CS" tag="IN" in="4:time" out="1:avobj|2:pnct">Since</W>
<W msd="ANP" tag="RB" in="-1:avobj" out="">then</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|6:[subj]|-19:coref" out="">he</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|-4:time|1:exem|4:pnct|5:vobj|20:pnct">has</W>
<W msd="SP" tag="IN" in="-1:exem" out="1:nobj">among</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">places</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VAP" tag="VBN" in="-5:vobj" out="-6:[subj]|1:preds">been</W>
<W msd="SP" tag="IN" in="-1:preds" out="1:nobj|4:pnct|5:conj|10:conj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:attr|1:{loc}">Pakhuset</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{loc}" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Esbjerg</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-5:conj" out="1:name">Hotel</W>
<W msd="NP=S" tag="NNP" in="-1:name" out="1:attr|1:{loc}">Plaza</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{loc}" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Copenhagen</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="SP" tag="IN" in="-10:conj" out="-1:coord|1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Henne</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:nobj">Kirkeby</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Inn</W>
<W msd="XP" tag="." in="-20:pnct" out="">.</W>
</s>
