<s>
<W id="1" msd="SP" tag="IN" in="" out="">For</W>
<W id="2" msd="NC=S" tag="NN" in="" out="">example</W>
<W id="3" msd="XP" tag="," in="" out="">,</W>
<W id="4" msd="U=" tag="EX" in="" out="">there</W>
<W id="5" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="6" msd="PD" tag="DT" in="" out="">no</W>
<W id="7" msd="NC=S" tag="NN" in="" out="">mention</W>
<W id="8" msd="SP" tag="IN" in="" out="">of</W>
<W id="9" msd="PI" tag="DT" in="" out="">a</W>
<W id="10" msd="NC=S" tag="NN" in="" out="">person</W>
<W id="11" msd="ANP" tag="JJ" in="" out="">such</W>
<W id="12" msd="CS" tag="IN" in="" out="">as</W>
<W id="13" msd="NC=S" tag="NN" in="" out="">director</W>
<W id="14" msd="VAG" tag="VBG" in="" out="">Flemming</W>
<W id="15" msd="NP=S" tag="NNP" in="" out="">Kristiansen</W>
<W id="16" msd="SP" tag="IN" in="" out="">with</W>
<W id="17" msd="PD" tag="DT" in="" out="">the</W>
<W id="18" msd="NC=S" tag="NN" in="" out="">nickname</W>
<W id="19" msd="PD" tag="DT" in="" out="">the</W>
<W id="20" msd="NC=S" tag="NN" in="" out="">junk</W>
<W id="21" msd="NC=S" tag="NN" in="" out="">dealer</W>
<W id="22" msd="XP" tag="," in="" out="">,</W>
<W id="23" msd="PT" tag="WP" in="" out="">who</W>
<W id="24" msd="SP" tag="IN" in="" out="">for</W>
<W id="25" msd="NC=P" tag="NNS" in="" out="">periods</W>
<W id="26" msd="SP" tag="IN" in="" out="">with</W>
<W id="27" msd="PI" tag="DT" in="" out="">a</W>
<W id="28" msd="ANP" tag="JJ" in="" out="">certain</W>
<W id="29" msd="NC=S" tag="NN" in="" out="">effect</W>
<W id="30" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="31" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="32" msd="NP=S" tag="NNP" in="" out="">Poul</W>
<W id="33" msd="NP=S" tag="NNP" in="" out="">Schlüter's</W>
<W id="34" msd="NC=S" tag="NN" in="" out="">confidant</W>
<W id="35" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="38" msd="PD" tag="DT" in="" out="">The</W>
<W id="39" msd="NC=S" tag="NN" in="" out="">close</W>
<W id="40" msd="NC=S" tag="NN" in="" out="">contact</W>
<W id="41" msd="SP" tag="IN" in="" out="">between</W>
<W id="42" msd="PD" tag="DT" in="" out="">the</W>
<W id="43" msd="AC" tag="CD" in="" out="">two</W>
<W id="44" msd="VAP" tag="VBN" in="" out="">led</W>
<W id="45" msd="XP" tag="," in="" out="">,</W>
<W id="46" msd="SP" tag="IN" in="" out="">among</W>
<W id="47" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="48" msd="NC=P" tag="NNS" in="" out="">things</W>
<W id="49" msd="XP" tag="," in="" out="">,</W>
<W id="50" msd="U=" tag="TO" in="" out="">to</W>
<W id="51" msd="VAG" tag="VBG" in="" out="">Flemming</W>
<W id="52" msd="NP=S" tag="NNP" in="" out="">Kristiansen</W>
<W id="53" msd="SP" tag="IN" in="" out="">at</W>
<W id="54" msd="NP=S" tag="NNP" in="" out="">Poul</W>
<W id="55" msd="NP=S" tag="NNP" in="" out="">Schlüter's</W>
<W id="56" msd="NC=S" tag="NN" in="" out="">initiative</W>
<W id="57" msd="SP" tag="IN" in="" out="">in</W>
<W id="58" msd="NP=S" tag="NNP" in="" out="">March</W>
<W id="59" msd="AC" tag="CD" in="" out="">1990</W>
<W id="60" msd="VAG" tag="VBG" in="" out="">being</W>
<W id="61" msd="VAP" tag="VBN" in="" out="">elected</W>
<W id="62" msd="U=" tag="TO" in="" out="">to</W>
<W id="63" msd="PD" tag="DT" in="" out="">the</W>
<W id="64" msd="NP=S" tag="NNP" in="" out="">Danish</W>
<W id="65" msd="NP=S" tag="NNP" in="" out="">Conservative</W>
<W id="66" msd="NP=S" tag="NNP" in="" out="">Party's</W>
<W id="67" msd="ANP" tag="JJ" in="" out="">main</W>
<W id="68" msd="NC=S" tag="NN" in="" out="">governing</W>
<W id="69" msd="NC=S" tag="NN" in="" out="">body</W>
<W id="70" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="71" msd="SP" tag="IN" in="" out="">at</W>
<W id="72" msd="PD" tag="DT" in="" out="">the</W>
<W id="73" msd="ANP" tag="JJ" in="" out="">same</W>
<W id="74" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="75" msd="SP" tag="IN" in="" out="">that</W>
<W id="76" msd="PD" tag="DT" in="" out="">the</W>
<W id="77" msd="NC=P" tag="NNS" in="" out="">party's</W>
<W id="78" msd="ANP" tag="JJ" in="" out="">visible</W>
<W id="79" msd="ANP" tag="JJ" in="" out="">right-wing</W>
<W id="80" msd="NC=S" tag="NN" in="" out="">profile</W>
<W id="81" msd="XP" tag="," in="" out="">,</W>
<W id="82" msd="NC=S" tag="NN" in="" out="">attorney</W>
<W id="83" msd="NP=S" tag="NNP" in="" out="">Kristian</W>
<W id="84" msd="NP=S" tag="NNP" in="" out="">Mogensen</W>
<W id="85" msd="XP" tag="," in="" out="">,</W>
<W id="86" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="87" msd="VAP" tag="VBN" in="" out="">scrapped</W>
<W id="88" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="91" msd="PD" tag="DT" in="" out="">The</W>
<W id="92" msd="ANC" tag="JJR" in="" out="">fewer</W>
<W id="93" msd="PD" tag="DT" in="" out="">the</W>
<W id="94" msd="NP=S" tag="NNP" in="" out="">Prime</W>
<W id="95" msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W id="96" msd="VADA" tag="VBD" in="" out="">listened</W>
<W id="97" msd="U=" tag="TO" in="" out="">to</W>
<W id="98" msd="CC" tag="CC" in="" out="">and</W>
<W id="99" msd="VAF" tag="VB" in="" out="">let</W>
<W id="100" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="101" msd="ANP" tag="JJ" in="" out="">political</W>
<W id="102" msd="NC=S" tag="NN" in="" out="">intuition</W>
<W id="103" msd="VAF" tag="VB" in="" out="">be</W>
<W id="104" msd="VAP" tag="VBN" in="" out="">influenced</W>
<W id="105" msd="SP" tag="IN" in="" out="">by</W>
<W id="106" msd="XP" tag="," in="" out="">,</W>
<W id="107" msd="PD" tag="DT" in="" out="">the</W>
<W id="108" msd="ANC" tag="JJR" in="" out="">greater</W>
<W id="109" msd="PD" tag="DT" in="" out="">the</W>
<W id="110" msd="NC=S" tag="NN" in="" out="">significance</W>
<W id="111" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="112" msd="NC=S" tag="NN" in="" out="">circle</W>
<W id="113" msd="SP" tag="IN" in="" out="">of</W>
<W id="114" msd="NC=P" tag="NNS" in="" out="">advisers</W>
<W id="115" msd="VAP" tag="VBN" in="" out="">obtained</W>
<W id="116" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="119" msd="SP" tag="IN" in="" out="">In</W>
<W id="120" msd="PD" tag="DT" in="" out="">the</W>
<W id="121" msd="NC=S" tag="NN" in="" out="">book</W>
<W id="122" msd="XP" tag="," in="" out="">,</W>
<W id="123" msd="PD" tag="DT" in="" out="">the</W>
<W id="124" msd="NC=S" tag="NN" in="" out="">point</W>
<W id="125" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="126" msd="VAP" tag="VBN" in="" out="">mentioned</W>
<W id="127" msd="SP" tag="IN" in="" out="">that</W>
<W id="128" msd="NP=S" tag="NNP" in="" out="">Schlüter</W>
<W id="129" msd="CS" tag="IN" in="" out="">as</W>
<W id="130" msd="PI" tag="DT" in="" out="">a</W>
<W id="131" msd="NC=S" tag="NN" in="" out="">person</W>
<W id="132" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="133" msd="NC=S" tag="NN" in="" out="">difficulty</W>
<W id="134" msd="SP" tag="IN" in="" out="">in</W>
<W id="135" msd="VAG" tag="VBG" in="" out="">saying</W>
<W id="136" msd="NC=S" tag="NN" in="" out="">goodbye</W>
<W id="137" msd="XP" tag="," in="" out="">,</W>
<W id="138" msd="PT" tag="WRB" in="" out="">when</W>
<W id="139" msd="PP" tag="PRP" in="" out="">he</W>
<W id="140" msd="VADA" tag="VBD" in="" out="">dismissed</W>
<W id="141" msd="NC=P" tag="NNS" in="" out="">ministers</W>
<W id="142" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="145" msd="SP" tag="IN" in="" out="">In</W>
<W id="146" msd="PD" tag="DT" in="" out="">this</W>
<W id="147" msd="NC=S" tag="NN" in="" out="">connection</W>
<W id="148" msd="XP" tag="," in="" out="">,</W>
<W id="149" msd="PP" tag="PRP" in="" out="">one</W>
<W id="150" msd="VA" tag="MD" in="" out="">could</W>
<W id="151" msd="VAF" tag="VB" in="" out="">add</W>
<W id="152" msd="SP" tag="IN" in="" out="">that</W>
<W id="153" msd="XP" tag="," in="" out="">,</W>
<W id="154" msd="SP" tag="IN" in="" out="">in</W>
<W id="155" msd="ANP" tag="JJ" in="" out="">such</W>
<W id="156" msd="NC=P" tag="NNS" in="" out="">cases</W>
<W id="157" msd="XP" tag="," in="" out="">,</W>
<W id="158" msd="PP" tag="PRP" in="" out="">it</W>
<W id="159" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="160" msd="PD" tag="DT" in="" out="">the</W>
<W id="161" msd="NP=S" tag="NNP" in="" out="">Foreign</W>
<W id="162" msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W id="163" msd="NP=S" tag="NNP" in="" out="">Uffe</W>
<W id="164" msd="NP=S" tag="NNP" in="" out="">Ellemann-Jensen</W>
<W id="165" msd="XP" tag="," in="" out="">,</W>
<W id="166" msd="PT" tag="WP" in="" out="">who</W>
<W id="167" msd="VADR" tag="VBZ" in="" out="">picks</W>
<W id="168" msd="RG" tag="RP" in="" out="">up</W>
<W id="169" msd="CS" tag="IN" in="" out="">after</W>
<W id="170" msd="PD" tag="DT" in="" out="">the</W>
<W id="171" msd="NP=S" tag="NNP" in="" out="">Prime</W>
<W id="172" msd="NP=S" tag="NNP" in="" out="">Minister</W>
<W id="173" msd="CC" tag="CC" in="" out="">and</W>
<W id="174" msd="VADR" tag="VBZ" in="" out="">sends</W>
<W id="175" msd="ANP" tag="JJ" in="" out="">personal</W>
<W id="176" msd="NC=P" tag="NNS" in="" out="">greetings</W>
<W id="177" msd="U=" tag="TO" in="" out="">to</W>
<W id="178" msd="PD" tag="DT" in="" out="">the</W>
<W id="179" msd="VAP" tag="VBN" in="" out="">dismissed</W>
<W id="180" msd="NC=P" tag="NNS" in="" out="">ministers</W>
<W id="181" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="184" msd="ANP" tag="JJ" in="" out="">Soft</W>
</s>
<s>
<W id="187" msd="SP" tag="IN" in="" out="">On</W>
<W id="188" msd="PD" tag="DT" in="" out="">the</W>
<W id="189" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="190" msd="NC=S" tag="NN" in="" out="">hand</W>
<W id="191" msd="XP" tag="," in="" out="">,</W>
<W id="192" msd="NP=S" tag="NNP" in="" out="">Poul</W>
<W id="193" msd="NP=S" tag="NNP" in="" out="">Schlüter</W>
<W id="194" msd="VADR" tag="VBZ" in="" out="">shows</W>
<W id="195" msd="AC" tag="CD" in="" out="">one</W>
<W id="196" msd="SP" tag="IN" in="" out="">of</W>
<W id="197" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="198" msd="ANC" tag="JJR" in="" out="">softer</W>
<W id="199" msd="NC=P" tag="NNS" in="" out="">sides</W>
<W id="200" msd="SP" tag="IN" in="" out="">by</W>
<W id="201" msd="ANP" tag="RB" in="" out="">carefully</W>
<W id="202" msd="VAG" tag="VBG" in="" out="">sending</W>
<W id="203" msd="NC=P" tag="NNS" in="" out="">flowers</W>
<W id="204" msd="CC" tag="CC" in="" out="">and</W>
<W id="205" msd="ANP" tag="JJ" in="" out="">handwritten</W>
<W id="206" msd="NC=P" tag="NNS" in="" out="">notes</W>
<W id="207" msd="SP" tag="IN" in="" out="">on</W>
<W id="208" msd="ANP" tag="JJ" in="" out="">red</W>
<W id="209" msd="NC=S" tag="NN" in="" out="">letter</W>
<W id="210" msd="NC=P" tag="NNS" in="" out="">days</W>
<W id="211" msd="SP" tag="IN" in="" out="">for</W>
<W id="212" msd="ANC" tag="JJR" in="" out="">greater</W>
<W id="213" msd="CC" tag="CC" in="" out="">or</W>
<W id="214" msd="ANC" tag="RBR" in="" out="">lesser</W>
<W id="215" msd="VAP" tag="VBN" in="" out="">known</W>
<W id="216" msd="NC=P" tag="NNS" in="" out="">citizens</W>
<W id="217" msd="SP" tag="IN" in="" out="">across</W>
<W id="218" msd="PD" tag="DT" in="" out="">the</W>
<W id="219" msd="NC=S" tag="NN" in="" out="">country</W>
<W id="220" msd="XP" tag="." in="" out="">.</W>
</s>
