<s>
<W msd="&quot;" in="20:pnct" out="">"</W>
<W msd="DT" in="19:subj|21:[subj]" out="1:nobj|2:ref|3:rel">The</W>
<W msd="NNS" in="-1:nobj" out="">people</W>
<W msd="WP" in="-2:ref|1:subj" out="">who</W>
<W msd="VBP" in="-3:rel" out="-1:subj|1:dobj|2:mod|4:pnct|5:coord">finance</W>
<W msd="NN" in="-1:dobj" out="">film</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="NNP" in="-1:nobj" out="">Sweden</W>
<W msd=":" in="-4:pnct" out="">-</W>
<W msd="CC" in="-5:coord" out="2:conj">and</W>
<W msd="RB" in="1:mod" out="">here</W>
<W msd="NNP" in="-2:conj|1:[subj]" out="-1:mod|1:vobj">I'm</W>
<W msd="VBG" in="-1:vobj" out="-1:[subj]|1:mod|2:pobj|7:pnct">thinking</W>
<W msd="RB" in="-1:mod" out="">particularly</W>
<W msd="IN" in="-2:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">Swedish</W>
<W msd="NNP" in="1:mod" out="">Film</W>
<W msd="NNP" in="-3:nobj" out="-1:mod">Institute</W>
<W msd=":" in="-7:pnct" out="">-</W>
<W msd="VBP" in="" out="-20:pnct|-19:subj|1:mod|2:vobj|5:pnct">do</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="VB" in="-2:vobj" out="-21:[subj]|1:dobj|2:aobj">take</W>
<W msd="NN" in="-1:dobj" out="">film</W>
<W msd="RB" in="-2:aobj" out="">seriously</W>
<W msd="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj" out="">They</W>
<W msd="VBP" in="" out="-1:subj|1:dobj|2:pred|7:pnct">want</W>
<W msd="NN" in="-1:dobj|2:[subj]" out="">film</W>
<W msd="TO" in="-2:pred" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W msd="DT" in="-1:pred" out="2:nobj">an</W>
<W msd="NN" in="1:mod" out="">entertainment</W>
<W msd="NN" in="-2:nobj" out="-1:mod">medium</W>
<W msd="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj" out="">I</W>
<W msd="VBP" in="" out="-1:subj|1:dobj|14:pnct">maintain</W>
<W msd="DT" in="-1:dobj" out="2:vobj">that</W>
<W msd="NN" in="1:subj|3:[subj]|4:[subj]" out="">film</W>
<W msd="VBZ" in="-2:vobj" out="-1:subj|1:coord|4:dobj">has</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="MD" in="-1:conj" out="-3:[subj]|1:vobj">must</W>
<W msd="VB" in="-1:vobj" out="-4:[subj]|1:[dobj]">have</W>
<W msd="DT" in="-4:dobj|-1:[dobj]" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="2:pobj">same</W>
<W msd="NN" in="-2:nobj" out="">power</W>
<W msd="IN" in="-2:pobj" out="1:nobj">as</W>
<W msd="NN" in="-1:nobj" out="1:coord">literature</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NN" in="-1:conj" out="">art</W>
<W msd="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="CC" in="" out="11:vobj|19:pnct">But</W>
<W msd="IN" in="10:mod" out="2:vobj">if</W>
<W msd="NN" in="1:subj|3:[subj]|4:[subj]" out="">film</W>
<W msd="VBZ" in="-2:vobj" out="-1:subj|1:pred|5:pnct">is</W>
<W msd="TO" in="-1:pred" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-4:[subj]|1:aobj">taken</W>
<W msd="RB" in="-1:aobj" out="">seriously</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="PRP" in="2:subj|4:[subj]" out="">you</W>
<W msd="RB" in="1:mod" out="">also</W>
<W msd="VBP" in="-11:vobj" out="-2:subj|-1:mod|-10:mod|1:dobj">have</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-4:[subj]|1:pobj|4:mod">deal</W>
<W msd="IN" in="-1:pobj" out="2:nobj">with</W>
<W msd="JJ" in="1:mod" out="">important</W>
<W msd="NNS" in="-2:nobj" out="-1:mod">subjects</W>
<W msd="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="">film</W>
<W msd="." in="-19:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="1:subj" out="">This</W>
<W msd="VBZ" in="" out="-1:subj|1:pnct|2:mod|5:mod|6:pred|11:pnct">is</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="NN" in="-2:mod" out="2:pnct|1:dobj">mind</W>
<W msd="PRP" in="-1:dobj" out="">you</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="RB" in="-5:mod" out="">not</W>
<W msd="JJ" in="-6:pred" out="1:pobj">synonymous</W>
<W msd="IN" in="-1:pobj" out="2:nobj">with</W>
<W msd="NN" in="1:subj" out="">film</W>
<W msd="VBG" in="-2:nobj" out="-1:subj|1:pred">being</W>
<W msd="JJ" in="-1:pred" out="">boring</W>
<W msd="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VBP" in="" out="-1:subj|1:vobj|17:pnct">have</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|3:tobj">taken</W>
<W msd="RB" in="1:mod" out="">just</W>
<W msd="IN" in="1:mod" out="-1:mod|9:pobj">as</W>
<W msd="JJ" in="-3:tobj" out="-1:mod|1:nobj">long</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="3:dobj">create</W>
<W msd="&quot;" in="2:pnct" out="">"</W>
<W msd="RB" in="1:pred" out="">Lovely</W>
<W msd="VBZ" in="-3:dobj" out="-2:pnct|-1:pred|1:subj|2:pnct">Is</W>
<W msd="NNP" in="-1:subj" out="">Earth</W>
<W msd="&quot;" in="-2:pnct" out="">"</W>
<W msd="IN" in="-9:pobj" out="1:nobj">as</W>
<W msd="DT" in="-1:nobj" out="1:mod|3:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">whole</W>
<W msd="NN" in="1:mod" out="">feature</W>
<W msd="NN" in="-3:nobj" out="-1:mod">film</W>
<W msd="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="2:subj|3:[subj]" out="1:nobj">Each</W>
<W msd="NN" in="-1:nobj" out="">scene</W>
<W msd="VBZ" in="15:qobj" out="-2:subj|1:vobj|6:mod|13:pnct|14:pnct">is</W>
<W msd="VBN" in="-1:vobj" out="-3:[subj]|1:mod">built</W>
<W msd="IN" in="-1:mod" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="2:nobj">a</W>
<W msd="NN" in="1:mod" out="">studio</W>
<W msd="NN" in="-2:nobj" out="-1:mod">stage</W>
<W msd="IN" in="-6:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:nobj">order</W>
<W msd="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:dobj|3:pred">get</W>
<W msd="PRP" in="-1:dobj" out="">it</W>
<W msd="RB" in="1:mod" out="">completely</W>
<W msd="JJ" in="-3:pred" out="-1:mod">accurate</W>
<W msd="," in="-13:pnct" out="">,</W>
<W msd="&quot;" in="-14:pnct" out="">"</W>
<W msd="VBZ" in="" out="-15:qobj|1:subj|17:pnct">says</W>
<W msd="DT" in="-1:subj" out="1:nobj|2:pnct|3:ref|4:rel">the</W>
<W msd="NN" in="-1:nobj" out="">director</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="WP" in="-3:ref|1:subj" out="">who</W>
<W msd="VBZ" in="-4:rel" out="-1:subj|1:pred">is</W>
<W msd="DT" in="-1:pred" out="1:nobj|2:mod">a</W>
<W msd="NN" in="-1:nobj" out="">perfectionist</W>
<W msd="IN" in="-2:mod" out="1:nobj">with</W>
<W msd="NN" in="-1:nobj" out="1:pobj">respect</W>
<W msd="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NN" in="-1:nobj" out="1:coord|3:mod">composition</W>
<W msd="CC" in="-1:coord" out="1:conj">and</W>
<W msd="NN" in="-1:conj" out="">statement</W>
<W msd="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">each</W>
<W msd="NN" in="-1:nobj" out="">image</W>
<W msd="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="IN" in="10:mod" out="4:mod|8:pnct">In</W>
<W msd="DT" in="3:tobj" out="1:nobj">the</W>
<W msd="VBN" in="-1:nobj" out="1:nobj">fifteen</W>
<W msd="NNS" in="-1:nobj" out="">years</W>
<W msd="IN" in="-4:mod" out="-3:tobj|2:nobj">since</W>
<W msd="&quot;" in="1:pnct" out="">"</W>
<W msd="NNP" in="-2:nobj" out="-1:pnct|1:pnct">Giliap</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">he</W>
<W msd="VBZ" in="" out="-10:mod|-1:subj|1:vobj|5:pnct">has</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">worked</W>
<W msd="IN" in="-1:pobj" out="2:nobj">with</W>
<W msd="NN" in="1:mod" out="">advertising</W>
<W msd="NN" in="-2:nobj" out="-1:mod">film</W>
<W msd="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="&quot;" in="3:pnct" out="">"</W>
<W msd="NNP" in="1:mod" out="">Advertising</W>
<W msd="NNS" in="1:subj" out="-1:mod">films</W>
<W msd="VBP" in="" out="-3:pnct|-1:subj|1:pred|2:pnct">are</W>
<W msd="JJ" in="-1:pred" out="">honest</W>
<W msd="." in="-2:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|2:[subj]|4:[subj]" out="">They</W>
<W msd="VBP" in="29:qobj" out="-1:subj|1:vobj|26:pnct|27:pnct">don't</W>
<W msd="VB" in="-1:vobj" out="-2:[subj]|1:dobj">pretend</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-4:[subj]|1:pred|3:coord">be</W>
<W msd="NN" in="-1:pred" out="1:mod">something</W>
<W msd="RB" in="-1:mod" out="">else</W>
<W msd="CC" in="-3:coord" out="1:pnct|7:conj">and</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="5:mod" out="2:nobj|3:pnct">in</W>
<W msd="JJ" in="1:mod" out="">commercial</W>
<W msd="NN" in="-2:nobj" out="-1:mod">film</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VBP" in="-7:conj" out="-5:mod|-1:subj|1:vobj">have</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|2:dobj">experienced</W>
<W msd="JJR" in="1:mod" out="7:pobj">greater</W>
<W msd="NN" in="-2:dobj" out="-1:mod|1:mod">latitude</W>
<W msd="TO" in="-1:mod" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="1:pobj">experiment</W>
<W msd="IN" in="-1:pobj" out="2:nobj">with</W>
<W msd="NN" in="1:mod" out="">film</W>
<W msd="NN" in="-2:nobj" out="-1:mod">language</W>
<W msd="IN" in="-7:pobj" out="1:nobj">than</W>
<W msd="DT" in="-1:nobj" out="1:nobj|2:mod">any</W>
<W msd="NN" in="-1:nobj" out="">place</W>
<W msd="RB" in="-2:mod" out="">else</W>
<W msd="," in="-26:pnct" out="">,</W>
<W msd="&quot;" in="-27:pnct" out="">"</W>
<W msd="PRP" in="1:subj" out="">he</W>
<W msd="VBZ" in="" out="-1:subj|-29:qobj|1:pnct">says</W>
<W msd="." in="-1:pnct" out="">.</W>
</s>
