<s>
<W msd="PRP" in="1:subj" out="3:nobj">It</W>
<W msd="VBZ" in="" out="-1:subj|1:pred|27:coord|55:pnct">is</W>
<W msd="JJ" in="-1:pred" out="">easy</W>
<W msd="TO" in="-3:nobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="3:dobj">mobilise</W>
<W msd="&quot;" in="2:pnct" out="">"</W>
<W msd="JJ" in="1:mod" out="">righteous</W>
<W msd="NN" in="-3:dobj" out="-2:pnct|-1:mod|1:pnct|2:pobj">indignation</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="IN" in="-2:pobj" out="1:nobj">over</W>
<W msd="WP" in="-1:nobj|2:[dobj]" out="2:rel">what</W>
<W msd="CD" in="1:subj" out="">one</W>
<W msd="VBZ" in="-2:rel" out="-2:[dobj]|-1:subj|3:pred|5:pnct|7:ref|13:rel">considers</W>
<W msd="&quot;" in="2:pnct" out="">"</W>
<W msd="JJ" in="1:mod" out="">outrageous</W>
<W msd="NN" in="-3:pred" out="-2:pnct|-1:mod|1:pnct">ignorance</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="(" in="7:pnct" out="">(</W>
<W msd="IN" in="-7:ref|6:dobj" out="">as</W>
<W msd="NNP" in="5:subj" out="1:pnct">Beinov</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="3:mod" out="1:nobj|2:pnct">for</W>
<W msd="NN" in="-1:nobj" out="">example</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="VBZ" in="-13:rel" out="-7:pnct|-6:dobj|-5:subj|-3:mod|1:pnct|2:pnct">does</W>
<W msd=")" in="-1:pnct" out="">)</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="CC" in="-27:coord" out="6:conj">but</W>
<W msd="DT" in="5:subj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">question</W>
<W msd="IN" in="" out="">in</W>
<W msd="DT" in="" out="">the</W>
<W msd="NN" in="" out="">end</W>
<W msd="VBZ" in="-6:conj" out="-5:subj|1:pred">is</W>
<W msd="IN" in="-1:pred" out="">whether</W>
<W msd="EX" in="" out="">there</W>
<W msd="VBZ" in="" out="6:mod">is</W>
<W msd="DT" in="" out="">a</W>
<W msd="NN" in="" out="">concept</W>
<W msd="IN" in="" out="2:appr">of</W>
<W msd="JJ" in="1:mod" out="">general</W>
<W msd="NN" in="-2:appr" out="-1:mod">education</W>
<W msd="IN" in="-6:mod" out="">that</W>
<W msd="DT" in="5:subj|7:[subj]" out="1:mod">a</W>
<W msd="JJR" in="-1:mod" out="">greater</W>
<W msd="NN" in="" out="">number</W>
<W msd="IN" in="" out="1:nobj">of</W>
<W msd="NNPS" in="-1:nobj" out="">Danes</W>
<W msd="MD" in="" out="-5:subj|2:vobj">can</W>
<W msd="RB" in="2:mod" out="">even</W>
<W msd="VB" in="-2:vobj" out="-7:[subj]|2:pred">be</W>
<W msd="RB" in="1:mod" out="-2:mod">somewhat</W>
<W msd="IN" in="-2:pred" out="1:nobj|-1:mod">in</W>
<W msd="NN" in="-1:nobj" out="1:pobj">agreement</W>
<W msd="RB" in="-1:pobj" out="">about</W>
<W msd="." in="-55:pnct" out="">?</W>
</s>
<s>
<W msd="JJ" in="2:subj" out="1:possd">People's</W>
<W msd="NNS" in="-1:possd" out="">children</W>
<W msd="VBP" in="" out="-2:subj|2:pred|3:pnct|4:coord|30:pnct">are</W>
<W msd="RB" in="1:mod" out="">quite</W>
<W msd="JJ" in="-2:pred" out="-1:mod">different</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="CC" in="-4:coord" out="13:conj">and</W>
<W msd="DT" in="12:subj" out="6:ref|8:rel">the</W>
<W msd="NN" in="" out="">need</W>
<W msd="IN" in="" out="">for</W>
<W msd="NNS" in="" out="">books</W>
<W msd="(" in="4:pnct" out="">(</W>
<W msd="IN" in="4:pobj" out="1:nobj">by</W>
<W msd="WDT" in="-6:ref|-1:nobj" out="">which</W>
<W msd="NNP" in="1:subj|2:[subj]" out="">Beinov</W>
<W msd="VBZ" in="-8:rel" out="-4:pnct|-1:subj|1:vobj|2:pnct|3:pnct">is</W>
<W msd="JJ" in="-1:vobj" out="-2:[subj]|-4:pobj">obsessed</W>
<W msd=")" in="-2:pnct" out="">)</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="VBZ" in="-13:conj" out="-12:subj|4:mod|1:mod|3:pred">is</W>
<W msd="RB" in="-1:mod" out="">not</W>
<W msd="IN" in="1:mod" out="3:pobj">as</W>
<W msd="JJ" in="-3:pred" out="-1:mod">ordinary</W>
<W msd="NN" in="-4:mod" out="">today</W>
<W msd="IN" in="-3:pobj" out="7:obl|1:pnct">as</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="5:mod" out="1:nobj|2:pnct">for</W>
<W msd="NN" in="-1:nobj" out="">example</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="CD" in="2:nobj" out="1:nobj">20</W>
<W msd="NNS" in="-1:nobj" out="">years</W>
<W msd="RB" in="-7:obl" out="-5:mod|-2:nobj">ago</W>
<W msd="." in="-30:pnct" out="">.</W>
</s>
<s>
<W msd="NNPS" in="1:subj" out="">Danes</W>
<W msd="VBP" in="" out="-1:subj|2:mod|14:pnct|15:mod|23:pnct|1:pnct|5:pnct">are</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="-2:mod" out="1:nobj">like</W>
<W msd="JJ" in="-1:nobj" out="1:nobj">other</W>
<W msd="NNS" in="-1:nobj" out="">peoples</W>
<W msd="," in="-5:pnct" out="">,</W>
<W msd="DT" in="" out="">a</W>
<W msd="NN" in="" out="1:pobj">product</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj|4:[dobj]" out="1:nobj|3:rel">the</W>
<W msd="NN" in="-1:nobj" out="">education</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">they</W>
<W msd="VBP" in="-3:rel" out="-1:subj|1:vobj">have</W>
<W msd="VBN" in="-1:vobj" out="-4:[dobj]|-2:[subj]">received</W>
<W msd=":" in="-14:pnct" out="">-</W>
<W msd="RB" in="-15:mod" out="1:pobj">apart</W>
<W msd="IN" in="-1:pobj" out="">from</W>
<W msd="DT" in="" out="3:pobj|1:mod|2:possd">the</W>
<W msd="JJ" in="-1:mod" out="">trendy</W>
<W msd="NNS" in="-2:possd" out="">currents</W>
<W msd="IN" in="-3:pobj" out="">of</W>
<W msd="DT" in="" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">time</W>
<W msd="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="NN" in="1:mod" out="">Television</W>
<W msd="NN" in="2:subj" out="-1:mod">culture</W>
<W msd="RB" in="1:mod" out="">certainly</W>
<W msd="VBZ" in="" out="-2:subj|-1:mod|1:dobj|23:pnct">has</W>
<W msd="NN" in="-1:dobj" out="1:pobj">part</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">blame</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj|6:mod">the</W>
<W msd="JJ" in="-1:mod" out="">predominant</W>
<W msd="NN" in="-2:nobj" out="1:pobj">antipathy</W>
<W msd="IN" in="-1:pobj" out="1:nobj">for</W>
<W msd="NN" in="-1:nobj" out="1:dobj">reading</W>
<W msd="NNS" in="-1:dobj" out="">novels</W>
<W msd="IN" in="-6:mod" out="">among</W>
<W msd="RB" in="2:mod" out="1:mod">not</W>
<W msd="RB" in="-1:mod" out="">only</W>
<W msd="JJ" in="" out="-2:mod">young</W>
<W msd="NNS" in="" out="1:coord">people</W>
<W msd="CC" in="-1:coord" out="1:mod">but</W>
<W msd="RB" in="-1:mod" out="">also</W>
<W msd="DT" in="" out="">the</W>
<W msd="JJ" in="" out="">tall</W>
<W msd="CC" in="" out="">and</W>
<W msd="JJ" in="" out="">burly</W>
<W msd="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj|4:[subj]" out="">You</W>
<W msd="VBP" in="" out="-1:subj|1:mod|13:pnct|14:mod|37:pnct">cannot</W>
<W msd="RB" in="-1:mod" out="">ordinarily</W>
<W msd="&quot;" in="1:pnct" out="">"</W>
<W msd="VB" in="" out="-4:[subj]|-1:pnct">beat</W>
<W msd="RP" in="" out="1:pnct">off</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="DT" in="" out="">the</W>
<W msd="NN" in="" out="">TV</W>
<W msd="NNS" in="" out="1:mod">media's</W>
<W msd="JJ" in="-1:mod" out="">ephemeral</W>
<W msd="NN" in="" out="">stream</W>
<W msd="IN" in="" out="">of</W>
<W msd="NN" in="" out="">information</W>
<W msd="," in="-13:pnct" out="">,</W>
<W msd="RB" in="-14:mod" out="1:pobj">just</W>
<W msd="IN" in="-1:pobj" out="">as</W>
<W msd="NN" in="11:subj" out="1:pnct|2:modp">entertainment</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="-2:modp" out="1:pred|8:pnct">whether</W>
<W msd="IN" in="-1:pred" out="1:nobj|2:coord">through</W>
<W msd="NN" in="-1:nobj" out="">television</W>
<W msd="CC" in="-2:coord" out="1:conj">or</W>
<W msd="IN" in="-1:conj" out="">in</W>
<W msd="DT" in="" out="">some</W>
<W msd="JJ" in="" out="1:nobj">other</W>
<W msd="NN" in="-1:nobj" out="">way</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="VBZ" in="" out="-11:subj">blocks</W>
<W msd="IN" in="" out="1:dobj">out</W>
<W msd="JJR" in="-1:dobj" out="1:nobj|2:pobj">more</W>
<W msd="NN" in="-1:nobj" out="">time</W>
<W msd="IN" in="-2:pobj" out="5:obl">than</W>
<W msd="DT" in="4:tobj" out="">a</W>
<W msd="NN" in="" out="">couple</W>
<W msd="IN" in="" out="1:nobj">of</W>
<W msd="NNS" in="-1:nobj" out="">decades</W>
<W msd="RB" in="-5:obl" out="-4:tobj">back</W>
<W msd="." in="-37:pnct" out="">.</W>
</s>
<s>
<W msd="NNS" in="6:subj|7:[subj]" out="1:pobj">Attitudes</W>
<W msd="IN" in="-1:pobj" out="">towards</W>
<W msd="DT" in="" out="">the</W>
<W msd="NN" in="" out="">acquisition</W>
<W msd="IN" in="" out="">of</W>
<W msd="NN" in="" out="">knowledge</W>
<W msd="VBP" in="" out="-6:subj|1:vobj|2:pnct|4:conj|16:pnct">have</W>
<W msd="VBN" in="-1:vobj" out="-7:[subj]">shifted</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="DT" in="1:subj|3:[subj]" out="">some</W>
<W msd="MD" in="-4:conj" out="-1:subj|1:mod|2:vobj">will</W>
<W msd="RB" in="-1:mod" out="">even</W>
<W msd="VB" in="-2:vobj" out="-3:[subj]|1:dobj">acknowledge</W>
<W msd="IN" in="-1:dobj" out="2:vobj">that</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">it</W>
<W msd="VBZ" in="-2:vobj" out="-1:subj|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-2:[subj]|3:pred">become</W>
<W msd="RB" in="1:mod" out="">much</W>
<W msd="RBR" in="1:mod" out="-1:mod|2:pobj">more</W>
<W msd="VBN" in="-3:pred" out="-1:mod">relaxed</W>
<W msd="IN" in="-2:pobj" out="1:obl">than</W>
<W msd="IN" in="-1:obl" out="">before</W>
<W msd="." in="-16:pnct" out="">.</W>
</s>
