<s>
<W msd="PRP" in="2:subj" out="">They</W>
<W msd="RB" in="1:mod" out="">also</W>
<W msd="VBP" in="" out="-1:mod|-2:subj|1:dobj|42:pnct">suggest</W>
<W msd="VBG" in="-1:dobj" out="1:avobj|8:mod|12:pnct|13:mod">cutting</W>
<W msd="RB" in="-1:avobj" out="1:pobj">back</W>
<W msd="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">time</W>
<W msd="IN" in="-1:pobj" out="2:nobj">for</W>
<W msd="JJ" in="1:mod" out="">national</W>
<W msd="NN" in="-2:nobj" out="-1:mod">service</W>
<W msd="TO" in="-8:mod" out="2:nobj">to</W>
<W msd="RB" in="1:mod" out="">approximately</W>
<W msd="CD" in="-2:nobj" out="-1:mod|1:nobj">one</W>
<W msd="NN" in="-1:nobj" out="">month</W>
<W msd="," in="-12:pnct" out="">,</W>
<W msd="IN" in="-13:mod" out="1:nobj">at</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="JJ" in="-1:mod" out="">same</W>
<W msd="NN" in="-2:nobj" out="1:nobj">time</W>
<W msd="IN" in="-1:nobj" out="1:pnct|13:vobj">that</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="11:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj|4:modp">the</W>
<W msd="JJ" in="-1:mod" out="">short</W>
<W msd="NN" in="-2:nobj" out="">run</W>
<W msd="(" in="1:pnct" out="">(</W>
<W msd="RP" in="-4:modp" out="-1:pnct|1:mod|3:pnct|4:pnct">up</W>
<W msd="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="CD" in="-1:nobj" out="">1996</W>
<W msd=")" in="-3:pnct" out="">)</W>
<W msd="," in="-4:pnct" out="">,</W>
<W msd="EX" in="1:expl|2:[expl]" out="">there</W>
<W msd="MD" in="-13:vobj" out="-1:expl|-11:mod|1:vobj">will</W>
<W msd="VB" in="-1:vobj" out="-2:[expl]|2:dobj">be</W>
<W msd="JJ" in="1:mod" out="">new</W>
<W msd="NN" in="-2:dobj" out="-1:mod|1:pobj|3:mod">investment</W>
<W msd="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="">equipment</W>
<W msd="IN" in="-3:mod" out="3:nobj">for</W>
<W msd="JJ" in="1:mod" out="">approximately</W>
<W msd="NN" in="1:numm" out="-1:mod">5</W>
<W msd="CD" in="-3:nobj" out="-1:numm|1:nobj">billion</W>
<W msd="NNS" in="-1:nobj" out="">crowns</W>
<W msd="." in="-42:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="2:subj|4:[subj]" out="1:nobj">The</W>
<W msd="NN" in="-1:nobj" out="">reduction</W>
<W msd="MD" in="" out="-2:subj|1:mod|2:vobj|26:pnct">must</W>
<W msd="RB" in="-1:mod" out="">necessarily</W>
<W msd="VB" in="-2:vobj" out="-4:[subj]|1:lobj">occur</W>
<W msd="IN" in="-1:lobj" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj|3:pnct|4:ref|11:rel">the</W>
<W msd="NNP" in="-1:mod" out="">Jutland</W>
<W msd="NNP" in="-2:nobj" out="">Division</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="WP$" in="-4:ref|7:subj|8:[subj]" out="1:possd|2:pnct">whose</W>
<W msd="NN" in="-1:possd" out="">purpose</W>
<W msd="," in="-2:pnct" out="">,</W>
<W msd="IN" in="4:mod" out="1:nobj|3:pnct">on</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">whole</W>
<W msd="," in="-3:pnct" out="">,</W>
<W msd="VBZ" in="-11:rel" out="-7:subj|-4:mod|1:vobj">has</W>
<W msd="VBN" in="-1:vobj" out="-8:[subj]|1:mod">disappeared</W>
<W msd="IN" in="-1:mod" out="1:pobj">along</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:nobj|4:mod">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj">threat</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NN" in="-1:nobj" out="">war</W>
<W msd="IN" in="-4:mod" out="1:nobj">from</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="">East</W>
<W msd="." in="-26:pnct" out="">.</W>
</s>
<s>
<W msd="PRP" in="1:subj" out="5:ref|15:rel">It</W>
<W msd="VBD" in="" out="-1:subj|1:pred|28:pnct">was</W>
<W msd="DT" in="-1:pred" out="1:mod|2:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">Jutland</W>
<W msd="NNP" in="-2:nobj" out="">Division</W>
<W msd="IN" in="-5:ref|10:subj|12:[subj]|13:[subj]" out="1:pnct">that</W>
<W msd="," in="-1:pnct" out="">,</W>
<W msd="IN" in="8:mod" out="1:pobj|7:pnct">along</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="4:nobj">the</W>
<W msd="RB" in="1:mod" out="">north</W>
<W msd="NNP" in="2:mod" out="-1:mod">German</W>
<W msd="NNP" in="1:mod" out="">NATO</W>
<W msd="NNS" in="-4:nobj" out="-1:mod|-2:mod">forces</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="VBD" in="-15:rel" out="-10:subj|-8:mod|1:pred">were</W>
<W msd="TO" in="-1:pred" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-12:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-13:[subj]|1:lobj">put</W>
<W msd="IN" in="-1:lobj" out="1:nobj">into</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="1:pobj|3:pobj">defence</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNP" in="-1:nobj" out="">Schleswig</W>
<W msd="IN" in="-3:pobj" out="1:nobj">against</W>
<W msd="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W msd="VBG" in="-1:mod" out="">advancing</W>
<W msd="NNP" in="1:mod" out="">DDR</W>
<W msd="NNS" in="-3:nobj" out="-1:mod">tanks</W>
<W msd="." in="-28:pnct" out="">.</W>
</s>
<s>
<W msd="RB" in="4:mod" out="">Now</W>
<W msd="DT" in="3:subj" out="2:nobj">the</W>
<W msd="NNP" in="1:mod" out="">DDR</W>
<W msd="NN" in="-2:nobj" out="-1:mod">equipment</W>
<W msd="VBP" in="" out="-4:mod|-3:subj|1:pred|7:pnct|8:coord|35:pnct">are</W>
<W msd="NN" in="-1:pred" out="1:pobj">part</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">German</W>
<W msd="NNP" in="1:mod" out="">NATO</W>
<W msd="NN" in="-3:nobj" out="-1:mod">army</W>
<W msd="," in="-7:pnct" out="">,</W>
<W msd="CC" in="-8:coord" out="23:conj">and</W>
<W msd="RB" in="22:mod" out="1:pobj">even</W>
<W msd="IN" in="-1:pobj" out="2:vobj">though</W>
<W msd="EX" in="1:expl|3:[expl]" out="">there</W>
<W msd="VBZ" in="-2:vobj" out="-1:expl|1:dobj|14:pnct">continues</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-3:[expl]|1:dobj|7:vobj">be</W>
<W msd="DT" in="-1:dobj|6:[subj]" out="1:mod|2:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">large</W>
<W msd="NN" in="-2:nobj" out="1:pobj">number</W>
<W msd="IN" in="-1:pobj" out="1:mod|2:nobj">of</W>
<W msd="JJ" in="-1:mod" out="">Russian</W>
<W msd="NNS" in="-2:nobj" out="">soldiers</W>
<W msd="VBN" in="-7:vobj" out="-6:[subj]|1:lobj">stationed</W>
<W msd="IN" in="-1:lobj" out="3:nobj">in</W>
<W msd="JJ" in="2:mod" out="">former</W>
<W msd="NNP" in="1:mod" out="">East</W>
<W msd="NNP" in="-3:nobj" out="-1:mod|-2:mod">Germany</W>
<W msd="," in="-14:pnct" out="">,</W>
<W msd="DT" in="4:subj|5:[subj]" out="1:nobj|2:mod">the</W>
<W msd="NN" in="-1:nobj" out="">threat</W>
<W msd="IN" in="-2:mod" out="1:nobj">from</W>
<W msd="EX" in="-1:nobj" out="">there</W>
<W msd="VBZ" in="-23:conj" out="-4:subj|-22:mod|1:vobj">is</W>
<W msd="VBN" in="-1:vobj" out="-5:[subj]|1:pobj">assessed</W>
<W msd="IN" in="-1:pobj" out="1:pred">as</W>
<W msd="JJ" in="-1:pred" out="">hypothetical</W>
<W msd="." in="-35:pnct" out="">.</W>
</s>
<s>
<W msd="DT" in="6:subj|7:[subj]" out="1:nobj">The</W>
<W msd="NNS" in="-1:nobj" out="1:pobj">remains</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NNP" in="-1:mod" out="">Jutland</W>
<W msd="NNP" in="-2:nobj" out="">Division</W>
<W msd="MD" in="11:qobj" out="-6:subj|1:vobj|9:pnct">will</W>
<W msd="VB" in="-1:vobj" out="-7:[subj]|1:pred">become</W>
<W msd="DT" in="-1:pred" out="1:nobj">a</W>
<W msd="NN" in="-1:nobj" out="1:pobj">part</W>
<W msd="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NNP" in="-1:nobj" out="3:possd">NATO's</W>
<W msd="NNP" in="2:mod" out="">Main</W>
<W msd="NNP" in="1:mod" out="">Defence</W>
<W msd="NNP" in="-3:possd" out="-1:mod|-2:mod">Forces</W>
<W msd="," in="-9:pnct" out="">,</W>
<W msd="PRP" in="1:subj|2:[subj]" out="">it</W>
<W msd="VBZ" in="" out="-11:qobj|-1:subj|1:vobj|5:pnct">is</W>
<W msd="VBD" in="-1:vobj" out="-2:[subj]|1:mod">said</W>
<W msd="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NN" in="-1:nobj" out="">report</W>
<W msd="." in="-5:pnct" out="">.</W>
</s>
<s>
<W msd="CC" in="" out="1:mod|5:conj|26:pnct">And</W>
<W msd="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">a</W>
<W msd="JJR" in="-1:mod" out="">lesser</W>
<W msd="NN" in="-2:nobj" out="">degree</W>
<W msd="IN" in="-5:conj" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|3:nobj|4:mod|6:pnct|7:ref|8:rel">the</W>
<W msd="JJ" in="-1:mod" out="">new</W>
<W msd="NN" in="1:mod" out="">Reaction</W>
<W msd="NNP" in="-3:nobj" out="-1:mod">Forces</W>
<W msd="IN" in="-4:mod" out="1:nobj">in</W>
<W msd="NNP" in="-1:nobj" out="">NATO</W>
<W msd="," in="-6:pnct" out="">,</W>
<W msd="WDT" in="-7:ref|1:subj|3:[subj]|4:[subj]" out="">which</W>
<W msd="MD" in="-8:rel" out="-1:subj|1:mod|2:vobj">will</W>
<W msd="RB" in="-1:mod" out="">particularly</W>
<W msd="VB" in="-2:vobj" out="-3:[subj]|1:vobj">be</W>
<W msd="VBN" in="-1:vobj" out="-4:[subj]|1:mod">used</W>
<W msd="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NN" in="-1:nobj" out="1:pobj">connection</W>
<W msd="IN" in="-1:pobj" out="4:nobj">with</W>
<W msd="JJ" in="3:mod" out="">international</W>
<W msd="&quot;" in="2:pnct" out="">"</W>
<W msd="NN" in="1:mod" out="">crisis</W>
<W msd="NN" in="-4:nobj" out="-1:mod|-3:mod|-2:pnct|1:pnct">management</W>
<W msd="&quot;" in="-1:pnct" out="">"</W>
<W msd="." in="-26:pnct" out="">.</W>
</s>
<s>
<W msd="JJ" in="1:mod" out="">New</W>
<W msd="NNS" in="" out="-1:mod">challenges</W>
</s>
<s>
<W msd="IN" in="26:mod" out="9:vobj">While</W>
<W msd="DT" in="8:subj|10:[subj]" out="1:mod|2:nobj|3:mod">the</W>
<W msd="JJS" in="-1:mod" out="">highest</W>
<W msd="NNS" in="-2:nobj" out="">officials</W>
<W msd="IN" in="-3:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="VBN" in="-1:mod" out="">armed</W>
<W msd="NNS" in="-2:nobj" out="">forces</W>
<W msd="RB" in="1:mod" out="">thus</W>
<W msd="VBP" in="-9:vobj" out="-8:subj|-1:mod|1:dobj|8:pnct">continue</W>
<W msd="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VB" in="-1:vobj" out="-10:[subj]|1:pobj">operate</W>
<W msd="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="DT" in="-1:nobj" out="1:mod|2:mod|3:nobj">a</W>
<W msd="JJ" in="-1:mod" out="">large</W>
<W msd="JJ" in="-2:mod" out="">national</W>
<W msd="NN" in="-3:nobj" out="">defence</W>
<W msd="," in="-8:pnct" out="">,</W>
<W msd="DT" in="8:subj" out="1:nobj|2:mod">the</W>
<W msd="NNS" in="-1:nobj" out="">experts</W>
<W msd="IN" in="-2:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W msd="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="NNP" in="1:mod" out="">Foreign</W>
<W msd="NNP" in="-2:nobj" out="-1:mod">Affairs</W>
<W msd="NN" in="" out="-26:mod|-8:subj|1:mod|6:dobj|15:pnct">emphasise</W>
<W msd="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="DT" in="-1:nobj" out="2:mod|3:nobj">the</W>
<W msd="RB" in="1:mod" out="">very</W>
<W msd="JJ" in="-2:mod" out="-1:mod">same</W>
<W msd="NN" in="-3:nobj" out="">report</W>
<W msd="IN" in="-6:dobj" out="4:vobj">that</W>
<W msd="NN" in="1:mod" out="">security</W>
<W msd="NNS" in="2:subj" out="-1:mod">problems</W>
<W msd="NN" in="1:mod" out="">today</W>
<W msd="VBP" in="-4:vobj" out="-2:subj|-1:mod|1:lobj">lie</W>
<W msd="DT" in="-1:lobj" out="2:mod|3:nobj">a</W>
<W msd="RB" in="1:mod" out="">completely</W>
<W msd="JJ" in="-2:mod" out="-1:mod">different</W>
<W msd="NN" in="-3:nobj" out="">place</W>
<W msd="." in="-15:pnct" out="">.</W>
</s>
