<s>
<W id="1" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="2" msd="NP=S" tag="NNP" in="" out="">Hash</W>
<W id="3" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="4" msd="ANP" tag="RB" in="" out="">also</W>
<W id="5" msd="PI" tag="DT" in="" out="">a</W>
<W id="6" msd="NC=S" tag="NN" in="" out="">narcotic</W>
<W id="7" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="10" msd="PP" tag="PRP" in="" out="">It</W>
<W id="11" msd="NC=P" tag="NNS" in="" out="">ruins</W>
<W id="12" msd="PD" tag="DT" in="" out="">the</W>
<W id="13" msd="NC=S" tag="NN" in="" out="">quality</W>
<W id="14" msd="SP" tag="IN" in="" out="">of</W>
<W id="15" msd="NC=P" tag="NNS" in="" out="">people's</W>
<W id="16" msd="NC=S" tag="NN" in="" out="">life</W>
<W id="17" msd="CC" tag="CC" in="" out="">and</W>
<W id="18" msd="VADR" tag="VBZ" in="" out="">destroys</W>
<W id="19" msd="NC=P" tag="NNS" in="" out="">people</W>
<W id="20" msd="ANP" tag="RB" in="" out="">psychologically</W>
<W id="21" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="24" msd="PP" tag="PRP" in="" out="">It</W>
<W id="25" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="26" msd="VAP" tag="VBN" in="" out="">forbidden</W>
<W id="27" msd="CC" tag="CC" in="" out="">and</W>
<W id="28" msd="VA" tag="MD" in="" out="">should</W>
<W id="29" msd="VAF" tag="VB" in="" out="">be</W>
<W id="30" msd="VAP" tag="VBN" in="" out="">forbidden</W>
<W id="31" msd="U=" tag="TO" in="" out="">to</W>
<W id="32" msd="VAF" tag="VB" in="" out="">possess</W>
<W id="33" msd="NC=S" tag="NN" in="" out="">hash</W>
<W id="34" msd="CC" tag="CC" in="" out="">or</W>
<W id="35" msd="U=" tag="TO" in="" out="">to</W>
<W id="36" msd="VAF" tag="VB" in="" out="">convey</W>
<W id="37" msd="PP" tag="PRP" in="" out="">it</W>
<W id="38" msd="XP" tag="," in="" out="">,</W>
<W id="39" msd="ANP" tag="RB" in="" out="">even</W>
<W id="40" msd="CS" tag="IN" in="" out="">if</W>
<W id="41" msd="PP" tag="PRP" in="" out="">it</W>
<W id="42" msd="VADR" tag="VBZ" in="" out="">happens</W>
<W id="43" msd="ANP" tag="JJ" in="" out="">free</W>
<W id="44" msd="SP" tag="IN" in="" out="">of</W>
<W id="45" msd="NC=S" tag="NN" in="" out="">charge</W>
<W id="46" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="49" msd="NP=S" tag="NNP" in="" out="">Hash</W>
<W id="50" msd="VADR" tag="VBZ" in="" out="">deserves</W>
<W id="51" msd="ANP" tag="RB" in="" out="">just</W>
<W id="52" msd="CS" tag="IN" in="" out="">as</W>
<W id="53" msd="ANP" tag="JJ" in="" out="">thorough</W>
<W id="54" msd="PI" tag="DT" in="" out="">a</W>
<W id="55" msd="NC=S" tag="NN" in="" out="">police</W>
<W id="56" msd="NC=S" tag="NN" in="" out="">effort</W>
<W id="57" msd="XP" tag="," in="" out="">,</W>
<W id="58" msd="CS" tag="IN" in="" out="">as</W>
<W id="59" msd="ANP" tag="JJ" in="" out="">hard</W>
<W id="60" msd="NC=P" tag="NNS" in="" out="">drugs</W>
<W id="61" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="62" msd="VAP" tag="VBN" in="" out="">subjected</W>
<W id="63" msd="U=" tag="TO" in="" out="">to</W>
<W id="64" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="65" msd="NC=P" tag="NNS" in="" out="">places</W>
<W id="66" msd="SP" tag="IN" in="" out="">in</W>
<W id="67" msd="PD" tag="DT" in="" out="">the</W>
<W id="68" msd="ANP" tag="JJ" in="" out="">city.</W>
<W id="69" msd="XP" tag="&amp;quot;" in="" out="">"</W>
</s>
<s>
<W id="72" msd="SP" tag="IN" in="" out="">For</W>
<W id="73" msd="AC" tag="CD" in="" out="">three</W>
<W id="74" msd="NC=P" tag="NNS" in="" out="">weeks</W>
<W id="75" msd="XP" tag="," in="" out="">,</W>
<W id="76" msd="PD" tag="DT" in="" out="">the</W>
<W id="77" msd="NC=S" tag="NN" in="" out="">police</W>
<W id="78" msd="SP" tag="IN" in="" out="">in</W>
<W id="79" msd="CC" tag="CC" in="" out="">and</W>
<W id="80" msd="SP" tag="IN" in="" out="">about</W>
<W id="81" msd="NP=S" tag="NNP" in="" out="">Christiania</W>
<W id="82" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="83" msd="VAP" tag="VBN" in="" out="">charged</W>
<W id="84" msd="AC" tag="CD" in="" out="">123</W>
<W id="85" msd="NC=P" tag="NNS" in="" out="">persons</W>
<W id="86" msd="SP" tag="IN" in="" out="">for</W>
<W id="87" msd="VAG" tag="VBG" in="" out="">possessing</W>
<W id="88" msd="CC" tag="CC" in="" out="">or</W>
<W id="89" msd="VAG" tag="VBG" in="" out="">dealing</W>
<W id="90" msd="SP" tag="IN" in="" out="">in</W>
<W id="91" msd="NC=S" tag="NN" in="" out="">hash</W>
<W id="92" msd="XP" tag="," in="" out="">,</W>
<W id="93" msd="AC" tag="CD" in="" out="">19</W>
<W id="94" msd="NC=P" tag="NNS" in="" out="">kilos</W>
<W id="95" msd="CC" tag="CC" in="" out="">and</W>
<W id="96" msd="NP=S" tag="NNP" in="" out="">DKK</W>
<W id="97" msd="AC" tag="CD" in="" out="">82,000</W>
<W id="98" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="99" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="100" msd="VAP" tag="VBN" in="" out="">confiscated</W>
<W id="101" msd="XP" tag="," in="" out="">,</W>
<W id="102" msd="CC" tag="CC" in="" out="">and</W>
<W id="103" msd="AC" tag="CD" in="" out="">165</W>
<W id="104" msd="NC=P" tag="NNS" in="" out="">kilos</W>
<W id="105" msd="SP" tag="IN" in="" out="">of</W>
<W id="106" msd="NC=S" tag="NN" in="" out="">marijuana</W>
<W id="107" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="108" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="109" msd="VAP" tag="VBN" in="" out="">harvested</W>
<W id="110" msd="SP" tag="IN" in="" out="">at</W>
<W id="111" msd="NP=S" tag="NNP" in="" out="">Christiania</W>
<W id="112" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="115" msd="CC" tag="CC" in="" out="">But</W>
<W id="116" msd="PD" tag="DT" in="" out="">the</W>
<W id="117" msd="NC=S" tag="NN" in="" out="">police</W>
<W id="118" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="119" msd="VAP" tag="VBN" in="" out="">ascertained</W>
<W id="120" msd="SP" tag="IN" in="" out="">that</W>
<W id="121" msd="NP=S" tag="NNP" in="" out="">Christiania</W>
<W id="122" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="123" msd="ANP" tag="RB" in="" out="">not</W>
<W id="124" msd="VAG" tag="VBG" in="" out="">living</W>
<W id="125" msd="RG" tag="RP" in="" out="">up</W>
<W id="126" msd="U=" tag="TO" in="" out="">to</W>
<W id="127" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="128" msd="ANP" tag="JJ" in="" out="">old</W>
<W id="129" msd="NC=S" tag="NN" in="" out="">reputation</W>
<W id="130" msd="CS" tag="IN" in="" out="">as</W>
<W id="131" msd="PI" tag="DT" in="" out="">a</W>
<W id="132" msd="NC=S" tag="NN" in="" out="">fencing</W>
<W id="133" msd="ANP" tag="JJ" in="" out="">central</W>
<W id="134" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="137" msd="PD" tag="DT" in="" out="">That</W>
<W id="138" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="139" msd="ANP" tag="JJ" in="" out="">gratifying</W>
<W id="140" msd="XP" tag="," in="" out="">,</W>
<W id="141" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="142" msd="NP=S" tag="NNP" in="" out="">Annemette</W>
<W id="143" msd="NP=S" tag="NNP" in="" out="">Møller</W>
<W id="144" msd="XP" tag="," in="" out="">,</W>
<W id="145" msd="PT" tag="WP" in="" out="">who</W>
<W id="146" msd="VADR" tag="VBZ" in="" out="">calls</W>
<W id="147" msd="NC=S" tag="NN" in="" out="">hash</W>
<W id="148" msd="PD" tag="DT" in="" out="">the</W>
<W id="149" msd="ANP" tag="JJ" in="" out="">free</W>
<W id="150" msd="NC=P" tag="NNS" in="" out="">state's</W>
<W id="151" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="152" msd="ANP" tag="JJ" in="" out="">true</W>
<W id="153" msd="NC=S" tag="NN" in="" out="">scourge</W>
<W id="154" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="155" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="158" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="159" msd="PP" tag="PRP" in="" out="">We</W>
<W id="160" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="161" msd="ANP" tag="RB" in="" out="">now</W>
<W id="162" msd="VAP" tag="VBN" in="" out="">bolstered</W>
<W id="163" msd="NC=P" tag="NNS" in="" out="">efforts</W>
<W id="164" msd="SP" tag="IN" in="" out="">against</W>
<W id="165" msd="PD" tag="DT" in="" out="">the</W>
<W id="166" msd="ANP" tag="JJ" in="" out="">open</W>
<W id="167" msd="NC=S" tag="NN" in="" out="">hash</W>
<W id="168" msd="NC=S" tag="NN" in="" out="">market</W>
<W id="169" msd="XP" tag="," in="" out="">,</W>
<W id="170" msd="CC" tag="CC" in="" out="">and</W>
<W id="171" msd="PP" tag="PRP" in="" out="">we</W>
<W id="172" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="173" msd="VAP" tag="VBN" in="" out="">received</W>
<W id="174" msd="ANP" tag="JJ" in="" out="">positive</W>
<W id="175" msd="NC=P" tag="NNS" in="" out="">signals</W>
<W id="176" msd="SP" tag="IN" in="" out="">that</W>
<W id="177" msd="PD" tag="DT" in="" out="">some</W>
<W id="178" msd="NC=P" tag="NNS" in="" out="">residents</W>
<W id="179" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="180" msd="VAP" tag="VBN" in="" out="">satisfied</W>
<W id="181" msd="SP" tag="IN" in="" out="">with</W>
<W id="182" msd="PO" tag="PRP$" in="" out="">our</W>
<W id="183" msd="NC=S" tag="NN" in="" out="">effort</W>
<W id="184" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="187" msd="PD" tag="DT" in="" out="">These</W>
<W id="188" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="189" msd="VADR" tag="VBZ" in="" out="">forces</W>
<W id="190" msd="PD" tag="DT" in="" out="">that</W>
<W id="191" msd="NC=S" tag="NN" in="" out="">support</W>
<W id="192" msd="PI" tag="DT" in="" out="">a</W>
<W id="193" msd="NC=S" tag="NN" in="" out="">legalisation</W>
<W id="194" msd="SP" tag="IN" in="" out="">of</W>
<W id="195" msd="NP=S" tag="NNP" in="" out="">Christiania</W>
<W id="196" msd="CC" tag="CC" in="" out="">and</W>
<W id="197" msd="PT" tag="WP" in="" out="">who</W>
<W id="198" msd="VADR" tag="VBP" in="" out="">realise</W>
<W id="199" msd="SP" tag="IN" in="" out="">that</W>
<W id="200" msd="PD" tag="DT" in="" out="">the</W>
<W id="201" msd="ANP" tag="JJ" in="" out="">free</W>
<W id="202" msd="NC=S" tag="NN" in="" out="">state</W>
<W id="203" msd="NC=S" tag="NN" in="" out="">cannot</W>
<W id="204" msd="VAF" tag="VB" in="" out="">base</W>
<W id="205" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="206" msd="ANP" tag="JJ" in="" out="">future</W>
<W id="207" msd="CC" tag="CC" in="" out="">and</W>
<W id="208" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="209" msd="NC=S" tag="NN" in="" out="">economy</W>
<W id="210" msd="SP" tag="IN" in="" out="">on</W>
<W id="211" msd="NC=S" tag="NN" in="" out="">hash</W>
<W id="212" msd="NC=S" tag="NN" in="" out="">trade</W>
<W id="213" msd="XP" tag="." in="" out="">.</W>
</s>
