<s>
<W id="1" msd="PP" tag="PRP" in="" out="">It</W>
<W id="2" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="3" msd="PD" tag="DT" in="" out="">the</W>
<W id="4" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="5" msd="NC=P" tag="NNS" in="" out="">divisions</W>
<W id="6" msd="SP" tag="IN" in="" out="">of</W>
<W id="7" msd="ANP" tag="JJ" in="" out="">large</W>
<W id="8" msd="ANP" tag="JJ" in="" out="">multinational</W>
<W id="9" msd="NC=P" tag="NNS" in="" out="">companies</W>
<W id="10" msd="PT" tag="WDT" in="" out="">that</W>
<W id="11" msd="VADR" tag="VBP" in="" out="">spend</W>
<W id="12" msd="NC=P" tag="NNS" in="" out="">millions</W>
<W id="13" msd="SP" tag="IN" in="" out="">on</W>
<W id="14" msd="NP=S" tag="NNP" in="" out="">TV-2</W>
<W id="15" msd="NC=P" tag="NNS" in="" out="">spots</W>
<W id="16" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="19" msd="NP=S" tag="NNP" in="" out="">ABBA</W>
<W id="20" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="21" msd="NP=S" tag="NNP" in="" out="">Gold</W>
<W id="22" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="23" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="24" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="25" msd="VAP" tag="VBN" in="" out="">advertised</W>
<W id="26" msd="ANP" tag="RB" in="" out="">massively</W>
<W id="27" msd="SP" tag="IN" in="" out="">on</W>
<W id="28" msd="NC=S" tag="NN" in="" out="">television</W>
<W id="29" msd="XP" tag="," in="" out="">,</W>
<W id="30" msd="ANP" tag="RB" in="" out="">just</W>
<W id="31" msd="CS" tag="IN" in="" out="">as</W>
<W id="32" msd="NP=S" tag="NNP" in="" out="">AC/DC</W>
<W id="33" msd="CC" tag="CC" in="" out="">and</W>
<W id="34" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="35" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="36" msd="ANS" tag="JJS" in="" out="">greatest</W>
<W id="37" msd="NC=P" tag="NNS" in="" out="">hits</W>
<W id="38" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="39" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="40" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="43" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="44" msd="PP" tag="PRP" in="" out="">I</W>
<W id="45" msd="VADR" tag="VBP" in="" out="">think</W>
<W id="46" msd="NC=S" tag="NN" in="" out="">TV</W>
<W id="47" msd="NC=S" tag="NN" in="" out="">advertisement</W>
<W id="48" msd="NC=P" tag="NNS" in="" out="">campaigns</W>
<W id="49" msd="VADR" tag="VBP" in="" out="">harm</W>
<W id="50" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="51" msd="NC=S" tag="NN" in="" out="">rock</W>
<W id="52" msd="ANP" tag="RB" in="" out="">quite</W>
<W id="53" msd="PI" tag="DT" in="" out="">a</W>
<W id="54" msd="NC=S" tag="NN" in="" out="">bit</W>
<W id="55" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="58" msd="PP" tag="PRP" in="" out="">We</W>
<W id="59" msd="VADR" tag="VBP" in="" out="">know</W>
<W id="60" msd="SP" tag="IN" in="" out="">from</W>
<W id="61" msd="NC=S" tag="NN" in="" out="">experience</W>
<W id="62" msd="SP" tag="IN" in="" out="">that</W>
<W id="63" msd="U=" tag="EX" in="" out="">there</W>
<W id="64" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="65" msd="PI" tag="DT" in="" out="">a</W>
<W id="66" msd="ANP" tag="JJ" in="" out="">large</W>
<W id="67" msd="NC=S" tag="NN" in="" out="">block</W>
<W id="68" msd="SP" tag="IN" in="" out="">of</W>
<W id="69" msd="PD" tag="DT" in="" out="">the</W>
<W id="70" msd="NC=S" tag="NN" in="" out="">audience</W>
<W id="71" msd="PT" tag="WDT" in="" out="">that</W>
<W id="72" msd="ANP" tag="RB" in="" out="">only</W>
<W id="73" msd="VAF" tag="VB" in="" out="">buy</W>
<W id="74" msd="AC" tag="CD" in="" out="">three</W>
<W id="75" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="76" msd="AC" tag="CD" in="" out="">four</W>
<W id="77" msd="VADR" tag="VBZ" in="" out="">records</W>
<W id="78" msd="PI" tag="DT" in="" out="">a</W>
<W id="79" msd="NC=S" tag="NN" in="" out="">year</W>
<W id="80" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="83" msd="CC" tag="CC" in="" out="">And</W>
<W id="84" msd="SP" tag="IN" in="" out="">whereas</W>
<W id="85" msd="CS" tag="IN" in="" out="">before</W>
<W id="86" msd="PP" tag="PRP" in="" out="">they</W>
<W id="87" msd="VA" tag="MD" in="" out="">might</W>
<W id="88" msd="VAF" tag="VB" in="" out="">have</W>
<W id="89" msd="VAP" tag="VBN" in="" out="">bought</W>
<W id="90" msd="NP=S" tag="NNP" in="" out="">Kim</W>
<W id="91" msd="NP=S" tag="NNP" in="" out="">Larsen</W>
<W id="92" msd="XP" tag="," in="" out="">,</W>
<W id="93" msd="NP=S" tag="NNP" in="" out="">Anne</W>
<W id="94" msd="NP=S" tag="NNP" in="" out="">Linnet</W>
<W id="95" msd="XP" tag="," in="" out="">,</W>
<W id="96" msd="NP=S" tag="NNP" in="" out="">TV-2,</W>
<W id="97" msd="PP" tag="PRP" in="" out="">they</W>
<W id="98" msd="ANP" tag="RB" in="" out="">now</W>
<W id="99" msd="VADR" tag="VBP" in="" out="">buy</W>
<W id="100" msd="PT" tag="WP" in="" out="">what</W>
<W id="101" msd="PP" tag="PRP" in="" out="">they</W>
<W id="102" msd="VADR" tag="VBP" in="" out="">see</W>
<W id="103" msd="NC=P" tag="NNS" in="" out="">advertisements</W>
<W id="104" msd="SP" tag="IN" in="" out="">for</W>
<W id="105" msd="SP" tag="IN" in="" out="">on</W>
<W id="106" msd="NC=S" tag="NN" in="" out="">TV</W>
<W id="107" msd="XP" tag="," in="" out="">,</W>
<W id="108" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="109" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="110" msd="NP=S" tag="NNP" in="" out="">Stefan</W>
<W id="111" msd="NP=S" tag="NNP" in="" out="">Fryland</W>
<W id="112" msd="XP" tag="," in="" out="">,</W>
<W id="113" msd="NC=S" tag="NN" in="" out="">chairman</W>
<W id="114" msd="SP" tag="IN" in="" out="">for</W>
<W id="115" msd="PD" tag="DT" in="" out="">the</W>
<W id="116" msd="NC=S" tag="NN" in="" out="">record</W>
<W id="117" msd="NC=S" tag="NN" in="" out="">company</W>
<W id="118" msd="NC=S" tag="NN" in="" out="">association</W>
<W id="119" msd="NP=S" tag="NNP" in="" out="">IFPI</W>
<W id="120" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="123" msd="CC" tag="CC" in="" out="">But</W>
<W id="124" msd="NP=S" tag="NNP" in="" out="">Fryland</W>
<W id="125" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="126" msd="ANP" tag="RB" in="" out="">also</W>
<W id="127" msd="NC=S" tag="NN" in="" out="">director</W>
<W id="128" msd="SP" tag="IN" in="" out="">for</W>
<W id="129" msd="NP=S" tag="NNP" in="" out="">Polygram</W>
<W id="130" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="131" msd="AC" tag="CD" in="" out="">one</W>
<W id="132" msd="SP" tag="IN" in="" out="">of</W>
<W id="133" msd="PD" tag="DT" in="" out="">the</W>
<W id="134" msd="NC=P" tag="NNS" in="" out="">companies</W>
<W id="135" msd="PT" tag="WDT" in="" out="">that</W>
<W id="136" msd="VADR" tag="VBP" in="" out="">advertise</W>
<W id="137" msd="NC=S" tag="NN" in="" out="">compilation</W>
<W id="138" msd="NC=P" tag="NNS" in="" out="">records</W>
<W id="139" msd="ANS" tag="RBS" in="" out="">most</W>
<W id="140" msd="ANP" tag="RB" in="" out="">extensively</W>
<W id="141" msd="SP" tag="IN" in="" out="">on</W>
<W id="142" msd="NC=S" tag="NN" in="" out="">TV</W>
<W id="143" msd="XP" tag="," in="" out="">,</W>
<W id="144" msd="PT" tag="WDT" in="" out="">which</W>
<W id="145" msd="VA" tag="MD" in="" out="">may</W>
<W id="146" msd="VAF" tag="VB" in="" out="">raise</W>
<W id="147" msd="NC=P" tag="NNS" in="" out="">doubts</W>
<W id="148" msd="SP" tag="IN" in="" out="">about</W>
<W id="149" msd="PD" tag="DT" in="" out="">the</W>
<W id="150" msd="NC=S" tag="NN" in="" out="">sincerity</W>
<W id="151" msd="SP" tag="IN" in="" out="">of</W>
<W id="152" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="153" msd="NC=S" tag="NN" in="" out="">statement</W>
<W id="154" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="157" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="158" msd="PP" tag="PRP" in="" out="">I</W>
<W id="159" msd="VADR" tag="VBP" in="" out="">realise</W>
<W id="160" msd="SP" tag="IN" in="" out="">that</W>
<W id="161" msd="NP=S" tag="NNP" in="" out="">I'm</W>
<W id="162" msd="VAG" tag="VBG" in="" out="">wearing</W>
<W id="163" msd="AC" tag="CD" in="" out="">two</W>
<W id="164" msd="NC=P" tag="NNS" in="" out="">hats</W>
<W id="165" msd="CC" tag="CC" in="" out="">and</W>
<W id="166" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="167" msd="AC" tag="CD" in="" out="">two</W>
<W id="168" msd="NC=P" tag="NNS" in="" out="">sets</W>
<W id="169" msd="SP" tag="IN" in="" out="">of</W>
<W id="170" msd="NC=P" tag="NNS" in="" out="">accounts</W>
<W id="171" msd="SP" tag="IN" in="" out="">in</W>
<W id="172" msd="PD" tag="DT" in="" out="">this</W>
<W id="173" msd="NC=S" tag="NN" in="" out="">matter</W>
<W id="174" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="177" msd="CC" tag="CC" in="" out="">But</W>
<W id="178" msd="PP" tag="PRP" in="" out="">it</W>
<W id="179" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="180" msd="ANP" tag="RB" in="" out="">also</W>
<W id="181" msd="PO" tag="PRP$" in="" out="">my</W>
<W id="182" msd="ANP" tag="JJ" in="" out="">own</W>
<W id="183" msd="ANP" tag="JJ" in="" out="">personal</W>
<W id="184" msd="NC=S" tag="NN" in="" out="">opinion</W>
<W id="185" msd="SP" tag="IN" in="" out="">that</W>
<W id="186" msd="NC=S" tag="NN" in="" out="">TV</W>
<W id="187" msd="NC=P" tag="NNS" in="" out="">spots</W>
<W id="188" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="189" msd="ANP" tag="JJ" in="" out="">harmful</W>
<W id="190" msd="XP" tag="," in="" out="">,</W>
<W id="191" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="192" msd="PP" tag="PRP" in="" out="">he</W>
<W id="193" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="194" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="197" msd="U=" tag="EX" in="" out="">There</W>
<W id="198" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="199" msd="PD" tag="DT" in="" out="">no</W>
<W id="200" msd="NC=P" tag="NNS" in="" out="">figures</W>
<W id="201" msd="SP" tag="IN" in="" out="">for</W>
<W id="202" msd="PT" tag="WRB" in="" out="">how</W>
<W id="203" msd="ANP" tag="JJ" in="" out="">many</W>
<W id="204" msd="NC=P" tag="NNS" in="" out="">millions</W>
<W id="205" msd="SP" tag="IN" in="" out="">of</W>
<W id="206" msd="VADR" tag="VBZ" in="" out="">crowns</W>
<W id="207" msd="PD" tag="DT" in="" out="">the</W>
<W id="208" msd="NC=S" tag="NN" in="" out="">record</W>
<W id="209" msd="NC=S" tag="NN" in="" out="">industry</W>
<W id="210" msd="VADR" tag="VBZ" in="" out="">throws</W>
<W id="211" msd="SP" tag="IN" in="" out="">into</W>
<W id="212" msd="NC=S" tag="NN" in="" out="">TV</W>
<W id="213" msd="NC=P" tag="NNS" in="" out="">campaigns</W>
<W id="214" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="217" msd="CC" tag="CC" in="" out="">But</W>
<W id="218" msd="PI" tag="DT" in="" out="">a</W>
<W id="219" msd="NC=S" tag="NN" in="" out="">number</W>
<W id="220" msd="SP" tag="IN" in="" out="">of</W>
<W id="221" msd="NC=P" tag="NNS" in="" out="">people</W>
<W id="222" msd="VADR" tag="VBP" in="" out="">believe</W>
<W id="223" msd="SP" tag="IN" in="" out="">that</W>
<W id="224" msd="PP" tag="PRP" in="" out="">it</W>
<W id="225" msd="VADR" tag="VBZ" in="" out="">provides</W>
<W id="226" msd="NC=S" tag="NN" in="" out="">food</W>
<W id="227" msd="SP" tag="IN" in="" out="">for</W>
<W id="228" msd="VAP" tag="VBN" in="" out="">thought</W>
<W id="229" msd="SP" tag="IN" in="" out="">that</W>
<W id="230" msd="PD" tag="DT" in="" out="">the</W>
<W id="231" msd="ANP" tag="JJ" in="" out="">total</W>
<W id="232" msd="NC=P" tag="NNS" in="" out="">sales</W>
<W id="233" msd="NC=S" tag="NN" in="" out="">have</W>
<W id="234" msd="ANP" tag="RB" in="" out="">nevertheless</W>
<W id="235" msd="VAP" tag="VBN" in="" out="">gone</W>
<W id="236" msd="ANP" tag="RB" in="" out="">down</W>
<W id="237" msd="XP" tag="." in="" out="">.</W>
</s>
