<s>
<W id="1" msd="PD" tag="DT" in="" out="">The</W>
<W id="2" msd="NC=S" tag="NN" in="" out="">course</W>
<W id="3" msd="XP" tag="," in="" out="">,</W>
<W id="4" msd="PT" tag="WDT" in="" out="">which</W>
<W id="5" msd="VADR" tag="VBZ" in="" out="">combines</W>
<W id="6" msd="AC" tag="CD" in="" out="">three</W>
<W id="7" msd="NC=P" tag="NNS" in="" out="">senses</W>
<W id="8" msd="XP" tag="&3a;" in="" out="">:</W>
<W id="9" msd="NC=S" tag="NN" in="" out="">sight</W>
<W id="10" msd="XP" tag="," in="" out="">,</W>
<W id="11" msd="NC=S" tag="NN" in="" out="">hearing</W>
<W id="12" msd="XP" tag="," in="" out="">,</W>
<W id="13" msd="CC" tag="CC" in="" out="">and</W>
<W id="14" msd="NC=S" tag="NN" in="" out="">touch</W>
<W id="15" msd="XP" tag="," in="" out="">,</W>
<W id="16" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="17" msd="ANP" tag="RB" in="" out="">normally</W>
<W id="18" msd="VAP" tag="VBN" in="" out="">offered</W>
<W id="19" msd="SP" tag="IN" in="" out="">at</W>
<W id="20" msd="PD" tag="DT" in="" out="">the</W>
<W id="21" msd="NC=S" tag="NN" in="" out="">Typing</W>
<W id="22" msd="NP=S" tag="NNP" in="" out="">School</W>
<W id="23" msd="SP" tag="IN" in="" out="">in</W>
<W id="24" msd="NP=S" tag="NNP" in="" out="">Copenhagen</W>
<W id="25" msd="CC" tag="CC" in="" out="">and</W>
<W id="26" msd="XP" tag="," in="" out="">,</W>
<W id="27" msd="ANP" tag="RB" in="" out="">here</W>
<W id="28" msd="XP" tag="," in="" out="">,</W>
<W id="29" msd="AC" tag="CD" in="" out="">24</W>
<W id="30" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="31" msd="NC=P" tag="NNS" in="" out="">teachers</W>
<W id="32" msd="SP" tag="IN" in="" out="">from</W>
<W id="33" msd="ANP" tag="JJ" in="" out="">high</W>
<W id="34" msd="NC=S" tag="NN" in="" out="">school</W>
<W id="35" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="36" msd="VAP" tag="VBN" in="" out="">been</W>
<W id="37" msd="VAG" tag="VBG" in="" out="">getting</W>
<W id="38" msd="NC=P" tag="NNS" in="" out="">lessons</W>
<W id="39" msd="CS" tag="IN" in="" out="">since</W>
<W id="40" msd="PD" tag="DT" in="" out="">the</W>
<W id="41" msd="NC=S" tag="NN" in="" out="">spring</W>
<W id="42" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="45" msd="ANP" tag="RB" in="" out="">Now</W>
<W id="46" msd="PP" tag="PRP" in="" out="">they</W>
<W id="47" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="48" msd="VAG" tag="VBG" in="" out="">passing</W>
<W id="49" msd="SP" tag="IN" in="" out="">on</W>
<W id="50" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="51" msd="NC=P" tag="NNS" in="" out="">talents</W>
<W id="52" msd="U=" tag="TO" in="" out="">to</W>
<W id="53" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="54" msd="NC=P" tag="NNS" in="" out="">students</W>
<W id="55" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="56" msd="PT" tag="WP" in="" out="">who</W>
<W id="57" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="58" msd="ANP" tag="JJ" in="" out="">crazy</W>
<W id="59" msd="SP" tag="IN" in="" out="">about</W>
<W id="60" msd="PP" tag="PRP" in="" out="">it</W>
<W id="61" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="64" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="65" msd="PT" tag="WRB" in="" out="">When</W>
<W id="66" msd="PP" tag="PRP" in="" out="">you</W>
<W id="67" msd="VADR" tag="VBP" in="" out="">begin</W>
<W id="68" msd="U=" tag="TO" in="" out="">to</W>
<W id="69" msd="VAF" tag="VB" in="" out="">be</W>
<W id="70" msd="ANP" tag="JJ" in="" out="">proficient</W>
<W id="71" msd="XP" tag="," in="" out="">,</W>
<W id="72" msd="PP" tag="PRP" in="" out="">it</W>
<W id="73" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="74" msd="ANP" tag="RB" in="" out="">just</W>
<W id="75" msd="ANP" tag="RB" in="" out="">incredibly</W>
<W id="76" msd="NC=S" tag="NN" in="" out="">fun</W>
<W id="77" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="80" msd="PP" tag="PRP" in="" out="">It</W>
<W id="81" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="82" msd="ANP" tag="RB" in="" out="">much</W>
<W id="83" msd="ANC" tag="JJR" in="" out="">easier</W>
<W id="84" msd="CC" tag="CC" in="" out="">and</W>
<W id="85" msd="ANC" tag="JJR" in="" out="">quicker</W>
<W id="86" msd="U=" tag="TO" in="" out="">to</W>
<W id="87" msd="VAF" tag="VB" in="" out="">type</W>
<W id="88" msd="SP" tag="IN" in="" out="">with</W>
<W id="89" msd="AC" tag="CD" in="" out="">ten</W>
<W id="90" msd="NC=P" tag="NNS" in="" out="">fingers</W>
<W id="91" msd="SP" tag="IN" in="" out="">than</W>
<W id="92" msd="SP" tag="IN" in="" out="">with</W>
<W id="93" msd="AC" tag="CD" in="" out="">two</W>
<W id="94" msd="XP" tag="," in="" out="">,</W>
<W id="95" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="96" msd="VADR" tag="VBZ" in="" out="">says</W>
<W id="97" msd="NP=S" tag="NNP" in="" out="">Filip</W>
<W id="98" msd="NP=S" tag="NNP" in="" out="">Willemoes</W>
<W id="99" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="102" msd="PP" tag="PRP" in="" out="">He</W>
<W id="103" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="104" msd="AC" tag="CD" in="" out="">one</W>
<W id="105" msd="SP" tag="IN" in="" out="">of</W>
<W id="106" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="107" msd="PD" tag="DT" in="" out="">the</W>
<W id="108" msd="NC=P" tag="NNS" in="" out="">experts</W>
<W id="109" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="110" msd="SP" tag="IN" in="" out="">from</W>
<W id="111" msd="PD" tag="DT" in="" out="">the</W>
<W id="112" msd="ANP" tag="JJ" in="" out="">4th</W>
<W id="113" msd="NC=S" tag="NN" in="" out="">grade</W>
<W id="114" msd="XP" tag="," in="" out="">,</W>
<W id="115" msd="PT" tag="WP" in="" out="">who</W>
<W id="116" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="117" msd="ANP" tag="RB" in="" out="">already</W>
<W id="118" msd="VAP" tag="VBN" in="" out="">finished</W>
<W id="119" msd="PD" tag="DT" in="" out="">the</W>
<W id="120" msd="ANP" tag="JJ" in="" out="">obligatory</W>
<W id="121" msd="AC" tag="CD" in="" out="">25</W>
<W id="122" msd="NC=P" tag="NNS" in="" out="">hours</W>
<W id="123" msd="SP" tag="IN" in="" out="">of</W>
<W id="124" msd="NC=P" tag="NNS" in="" out="">lessons</W>
<W id="125" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="128" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="129" msd="PP" tag="PRP" in="" out="">I</W>
<W id="130" msd="VADA" tag="VBD" in="" out="">thought</W>
<W id="131" msd="NP=S" tag="NNP" in="" out="">I'll</W>
<W id="132" msd="ANP" tag="RB" in="" out="">never</W>
<W id="133" msd="VAF" tag="VB" in="" out="">be</W>
<W id="134" msd="ANP" tag="JJ" in="" out="">able</W>
<W id="135" msd="U=" tag="TO" in="" out="">to</W>
<W id="136" msd="VAF" tag="VB" in="" out="">learn</W>
<W id="137" msd="PD" tag="DT" in="" out="">this</W>
<W id="138" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="141" msd="PP" tag="PRP" in="" out="">I</W>
<W id="142" msd="ANP" tag="RB" in="" out="">almost</W>
<W id="143" msd="VADA" tag="VBD" in="" out="">gave</W>
<W id="144" msd="RG" tag="RP" in="" out="">up</W>
<W id="145" msd="SP" tag="IN" in="" out="">in</W>
<W id="146" msd="NC=S" tag="NN" in="" out="">advance</W>
<W id="147" msd="XP" tag="," in="" out="">,</W>
<W id="148" msd="CC" tag="CC" in="" out="">but</W>
<W id="149" msd="CS" tag="IN" in="" out="">after</W>
<W id="150" msd="PI" tag="DT" in="" out="">a</W>
<W id="151" msd="NC=S" tag="NN" in="" out="">week</W>
<W id="152" msd="PP" tag="PRP" in="" out="">it</W>
<W id="153" msd="VADA" tag="VBD" in="" out="">went</W>
<W id="154" msd="ANC" tag="JJR" in="" out="">better</W>
<W id="155" msd="XP" tag="," in="" out="">,</W>
<W id="156" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="157" msd="VADR" tag="VBZ" in="" out="">adds</W>
<W id="158" msd="NP=S" tag="NNP" in="" out="">Ulrik</W>
<W id="159" msd="NP=S" tag="NNP" in="" out="">Holst</W>
<W id="160" msd="NP=S" tag="NNP" in="" out="">Hansen</W>
<W id="161" msd="XP" tag="&3a;" in="" out="">;</W>
<W id="162" msd="CC" tag="CC" in="" out="">and</W>
<W id="163" msd="NP=S" tag="NNP" in="" out="">Marie</W>
<W id="164" msd="NP=S" tag="NNP" in="" out="">Louise</W>
<W id="165" msd="NP=S" tag="NNP" in="" out="">Løvgren</W>
<W id="166" msd="VADR" tag="VBZ" in="" out="">sends</W>
<W id="167" msd="PI" tag="DT" in="" out="">a</W>
<W id="168" msd="ANP" tag="JJ" in="" out="">grateful</W>
<W id="169" msd="VAP" tag="VBN" in="" out="">thought</W>
<W id="170" msd="U=" tag="TO" in="" out="">to</W>
<W id="171" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="172" msd="PD" tag="DT" in="" out="">the</W>
<W id="173" msd="NC=S" tag="NN" in="" out="">gas</W>
<W id="174" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="175" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="176" msd="PD" tag="DT" in="" out="">the</W>
<W id="177" msd="NC=S" tag="NN" in="" out="">candy</W>
<W id="178" msd="SP" tag="IN" in="" out="">that</W>
<W id="179" msd="PD" tag="DT" in="" out="">the</W>
<W id="180" msd="NC=P" tag="NNS" in="" out="">teachers</W>
<W id="181" msd="VAP" tag="VBN" in="" out="">distributed</W>
<W id="182" msd="U=" tag="TO" in="" out="">to</W>
<W id="183" msd="VAF" tag="VB" in="" out="">keep</W>
<W id="184" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="185" msd="NC=P" tag="NNS" in="" out="">spirits</W>
<W id="186" msd="SP" tag="IN" in="" out="">up</W>
<W id="187" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="190" msd="U=" tag="EX" in="" out="">There</W>
<W id="191" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="192" msd="U=" tag="TO" in="" out="">to</W>
<W id="193" msd="VAF" tag="VB" in="" out="">be</W>
<W id="194" msd="PI" tag="DT" in="" out="">a</W>
<W id="195" msd="ANP" tag="JJ" in="" out="">little</W>
<W id="196" msd="NC=S" tag="NN" in="" out="">room</W>
<W id="197" msd="SP" tag="IN" in="" out="">for</W>
<W id="198" msd="NC=S" tag="NN" in="" out="">indulgence</W>
<W id="199" msd="XP" tag="," in="" out="">,</W>
<W id="200" msd="CS" tag="IN" in="" out="">because</W>
<W id="201" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="202" msd="PP" tag="PRP" in="" out="">you</W>
<W id="203" msd="VADR" tag="VBP" in="" out="">go</W>
<W id="204" msd="PI" tag="DT" in="" out="">a</W>
<W id="205" msd="ANP" tag="JJ" in="" out="">little</W>
<W id="206" msd="NC=S" tag="NN" in="" out="">cuckoo</W>
<W id="207" msd="SP" tag="IN" in="" out="">in</W>
<W id="208" msd="PD" tag="DT" in="" out="">the</W>
<W id="209" msd="NC=S" tag="NN" in="" out="">head</W>
<W id="210" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="211" msd="SP" tag="IN" in="" out="">from</W>
<W id="212" msd="VAG" tag="VBG" in="" out="">sitting</W>
<W id="213" msd="PD" tag="DT" in="" out="">every</W>
<W id="214" msd="NC=S" tag="NN" in="" out="">morning</W>
<W id="215" msd="SP" tag="IN" in="" out="">for</W>
<W id="216" msd="AC" tag="CD" in="" out="">two</W>
<W id="217" msd="NC=P" tag="NNS" in="" out="">weeks</W>
<W id="218" msd="SP" tag="IN" in="" out="">between</W>
<W id="219" msd="AC" tag="CD" in="" out="">eight</W>
<W id="220" msd="U=" tag="TO" in="" out="">to</W>
<W id="221" msd="AC" tag="CD" in="" out="">eleven</W>
<W id="222" msd="ANP" tag="RB" in="" out="">just</W>
<W id="223" msd="NC=S" tag="NN" in="" out="">typing</W>
<W id="224" msd="PD" tag="DT" in="" out="">the</W>
<W id="225" msd="ANP" tag="JJ" in="" out="">same</W>
<W id="226" msd="NC=S" tag="NN" in="" out="">series</W>
<W id="227" msd="SP" tag="IN" in="" out="">of</W>
<W id="228" msd="NC=P" tag="NNS" in="" out="">letters</W>
<W id="229" msd="CC" tag="CC" in="" out="">and</W>
<W id="230" msd="NC=P" tag="NNS" in="" out="">numbers</W>
<W id="231" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="234" msd="SP" tag="IN" in="" out="">On</W>
<W id="235" msd="PD" tag="DT" in="" out="">the</W>
<W id="236" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="237" msd="NC=S" tag="NN" in="" out="">hand</W>
<W id="238" msd="XP" tag="," in="" out="">,</W>
<W id="239" msd="PP" tag="PRP" in="" out="">it</W>
<W id="240" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="241" msd="NC=S" tag="NN" in="" out="">fun</W>
<W id="242" msd="U=" tag="TO" in="" out="">to</W>
<W id="243" msd="VAF" tag="VB" in="" out="">type</W>
<W id="244" msd="SP" tag="IN" in="" out="">at</W>
<W id="245" msd="NC=S" tag="NN" in="" out="">home</W>
<W id="246" msd="XP" tag="," in="" out="">,</W>
<W id="247" msd="PP" tag="PRP" in="" out="">they</W>
<W id="248" msd="PD" tag="DT" in="" out="">all</W>
<W id="249" msd="NC=S" tag="NN" in="" out="">say</W>
<W id="250" msd="SP" tag="IN" in="" out="">in</W>
<W id="251" msd="NC=S" tag="NN" in="" out="">concert</W>
<W id="252" msd="XP" tag="." in="" out="">.</W>
</s>
