<s>
<W id="1" msd="PD" tag="DT" in="" out="">The</W>
<W id="2" msd="ANP" tag="JJ" in="" out="">American</W>
<W id="3" msd="NC=S" tag="NN" in="" out="">election</W>
<W id="4" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="5" msd="VAP" tag="VBN" in="" out="">gone</W>
<W id="6" msd="SP" tag="IN" in="" out="">into</W>
<W id="7" msd="PO" tag="PRP$" in="" out="">its</W>
<W id="8" msd="ANP" tag="JJ" in="" out="">decisive</W>
<W id="9" msd="NC=S" tag="NN" in="" out="">phase</W>
<W id="10" msd="CC" tag="CC" in="" out="">and</W>
<W id="11" msd="XP" tag="," in="" out="">,</W>
<W id="12" msd="SP" tag="IN" in="" out="">for</W>
<W id="13" msd="NC=P" tag="NNS" in="" out="">people</W>
<W id="14" msd="PT" tag="WP" in="" out="">who</W>
<W id="15" msd="VADR" tag="VBP" in="" out="">claim</W>
<W id="16" msd="SP" tag="IN" in="" out="">that</W>
<W id="17" msd="NC=P" tag="NNS" in="" out="">politics</W>
<W id="18" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="19" msd="PI" tag="DT" in="" out="">a</W>
<W id="20" msd="ANP" tag="JJ" in="" out="">dirty</W>
<W id="21" msd="NC=S" tag="NN" in="" out="">business</W>
<W id="22" msd="XP" tag="," in="" out="">,</W>
<W id="23" msd="U=" tag="EX" in="" out="">there</W>
<W id="24" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="25" msd="NC=P" tag="NNS" in="" out="">lots</W>
<W id="26" msd="SP" tag="IN" in="" out="">of</W>
<W id="27" msd="NC=P" tag="NNS" in="" out="">arguments</W>
<W id="28" msd="U=" tag="TO" in="" out="">to</W>
<W id="29" msd="VAF" tag="VB" in="" out="">find</W>
<W id="30" msd="SP" tag="IN" in="" out="">in</W>
<W id="31" msd="PD" tag="DT" in="" out="">the</W>
<W id="32" msd="NC=S" tag="NN" in="" out="">way</W>
<W id="33" msd="PD" tag="DT" in="" out="">the</W>
<W id="34" msd="AC" tag="CD" in="" out="">three</W>
<W id="35" msd="NC=P" tag="NNS" in="" out="">candidates</W>
<W id="36" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="37" msd="VAG" tag="VBG" in="" out="">conducting</W>
<W id="38" msd="PP" tag="PRP" in="" out="">themselves</W>
<W id="39" msd="SP" tag="IN" in="" out="">with</W>
<W id="40" msd="PD" tag="DT" in="" out="">each</W>
<W id="41" msd="NC=S" tag="NN" in="" out="">other</W>
<W id="42" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="45" msd="NC=P" tag="NNS" in="" out="">Matters</W>
<W id="46" msd="VADR" tag="VBP" in="" out="">are</W>
<W id="47" msd="ANP" tag="RB" in="" out="">not</W>
<W id="48" msd="ANP" tag="RB" in="" out="">exactly</W>
<W id="49" msd="VAG" tag="VBG" in="" out="">being</W>
<W id="50" msd="VAP" tag="VBN" in="" out="">treated</W>
<W id="51" msd="SP" tag="IN" in="" out="">with</W>
<W id="52" msd="NC=S" tag="NN" in="" out="">kid</W>
<W id="53" msd="NC=P" tag="NNS" in="" out="">gloves</W>
<W id="54" msd="PD" tag="DT" in="" out="">these</W>
<W id="55" msd="NC=P" tag="NNS" in="" out="">days</W>
<W id="56" msd="XP" tag="," in="" out="">,</W>
<W id="57" msd="CS" tag="IN" in="" out="">since</W>
<W id="58" msd="PP" tag="PRP" in="" out="">it</W>
<W id="59" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="60" msd="U=" tag="TO" in="" out="">to</W>
<W id="61" msd="VAF" tag="VB" in="" out="">be</W>
<W id="62" msd="VAP" tag="VBN" in="" out="">decided</W>
<W id="63" msd="SP" tag="IN" in="" out="">whether</W>
<W id="64" msd="NP=S" tag="NNP" in="" out="">Democrat</W>
<W id="65" msd="NP=S" tag="NNP" in="" out="">Bill</W>
<W id="66" msd="NP=S" tag="NNP" in="" out="">Clinton</W>
<W id="67" msd="ANP" tag="RB" in="" out="">really</W>
<W id="68" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="69" msd="PI" tag="DT" in="" out="">a</W>
<W id="70" msd="NC=S" tag="NN" in="" out="">lead</W>
<W id="71" msd="SP" tag="IN" in="" out="">over</W>
<W id="72" msd="PD" tag="DT" in="" out="">the</W>
<W id="73" msd="VAG" tag="VBG" in="" out="">sitting</W>
<W id="74" msd="NC=S" tag="NN" in="" out="">president</W>
<W id="75" msd="XP" tag="," in="" out="">,</W>
<W id="76" msd="NP=S" tag="NNP" in="" out="">Republican</W>
<W id="77" msd="NP=S" tag="NNP" in="" out="">George</W>
<W id="78" msd="NP=S" tag="NNP" in="" out="">Bush</W>
<W id="79" msd="XP" tag="," in="" out="">,</W>
<W id="80" msd="CC" tag="CC" in="" out="">and</W>
<W id="81" msd="SP" tag="IN" in="" out="">whether</W>
<W id="82" msd="PD" tag="DT" in="" out="">the</W>
<W id="83" msd="ANP" tag="JJ" in="" out="">independent</W>
<W id="84" msd="NP=S" tag="NNP" in="" out="">Ross</W>
<W id="85" msd="NP=S" tag="NNP" in="" out="">Perot</W>
<W id="86" msd="VA" tag="MD" in="" out="">can</W>
<W id="87" msd="VAF" tag="VB" in="" out="">draw</W>
<W id="88" msd="ANP" tag="RB" in="" out="">so</W>
<W id="89" msd="ANP" tag="JJ" in="" out="">many</W>
<W id="90" msd="NC=P" tag="NNS" in="" out="">votes</W>
<W id="91" msd="SP" tag="IN" in="" out="">that</W>
<W id="92" msd="PP" tag="PRP" in="" out="">he</W>
<W id="93" msd="VADR" tag="VBZ" in="" out="">affects</W>
<W id="94" msd="PD" tag="DT" in="" out="">the</W>
<W id="95" msd="NC=S" tag="NN" in="" out="">result</W>
<W id="96" msd="XP" tag="," in="" out="">,</W>
<W id="97" msd="PT" tag="WDT" in="" out="">which</W>
<W id="98" msd="VADR" tag="VBZ" in="" out="">turns</W>
<W id="99" msd="SP" tag="IN" in="" out="">on</W>
<W id="100" msd="PD" tag="DT" in="" out="">the</W>
<W id="101" msd="NC=S" tag="NN" in="" out="">fact</W>
<W id="102" msd="SP" tag="IN" in="" out="">that</W>
<W id="103" msd="PD" tag="DT" in="" out="">the</W>
<W id="104" msd="NC=S" tag="NN" in="" out="">number</W>
<W id="105" msd="AC" tag="CD" in="" out="">one</W>
<W id="106" msd="NC=S" tag="NN" in="" out="">candidate</W>
<W id="107" msd="SP" tag="IN" in="" out="">in</W>
<W id="108" msd="PD" tag="DT" in="" out="">each</W>
<W id="109" msd="NC=S" tag="NN" in="" out="">state</W>
<W id="110" msd="VADR" tag="VBZ" in="" out="">takes</W>
<W id="111" msd="PD" tag="PDT" in="" out="">all</W>
<W id="112" msd="PD" tag="DT" in="" out="">the</W>
<W id="113" msd="ANP" tag="JJ" in="" out="">electoral</W>
<W id="114" msd="NC=P" tag="NNS" in="" out="">votes</W>
<W id="115" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="118" msd="PD" tag="DT" in="" out="">These</W>
<W id="119" msd="ANP" tag="JJ" in="" out="">electoral</W>
<W id="120" msd="NC=S" tag="NN" in="" out="">mathematics</W>
<W id="121" msd="VADR" tag="VBP" in="" out="">say</W>
<W id="122" msd="SP" tag="IN" in="" out="">that</W>
<W id="123" msd="PP" tag="PRP" in="" out="">you</W>
<W id="124" msd="VA" tag="MD" in="" out="">can</W>
<W id="125" msd="VAF" tag="VB" in="" out="">be</W>
<W id="126" msd="PI" tag="DT" in="" out="">an</W>
<W id="127" msd="ANP" tag="JJ" in="" out="">American</W>
<W id="128" msd="NC=S" tag="NN" in="" out="">president</W>
<W id="129" msd="SP" tag="IN" in="" out="">without</W>
<W id="130" msd="PI" tag="DT" in="" out="">a</W>
<W id="131" msd="NC=S" tag="NN" in="" out="">majority</W>
<W id="132" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="135" msd="SP" tag="IN" in="" out="">Of</W>
<W id="136" msd="PD" tag="DT" in="" out="">the</W>
<W id="137" msd="AC" tag="CD" in="" out="">two</W>
<W id="138" msd="ANP" tag="JJ" in="" out="">major</W>
<W id="139" msd="NC=P" tag="NNS" in="" out="">candidates</W>
<W id="140" msd="XP" tag="," in="" out="">,</W>
<W id="141" msd="NP=S" tag="NNP" in="" out="">Bill</W>
<W id="142" msd="NP=S" tag="NNP" in="" out="">Clinton</W>
<W id="143" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="144" msd="VAP" tag="VBN" in="" out="">tried</W>
<W id="145" msd="U=" tag="TO" in="" out="">to</W>
<W id="146" msd="VAF" tag="VB" in="" out="">make</W>
<W id="147" msd="PP" tag="PRP" in="" out="">it</W>
<W id="148" msd="SP" tag="IN" in="" out="">into</W>
<W id="149" msd="PI" tag="DT" in="" out="">an</W>
<W id="150" msd="ANP" tag="JJ" in="" out="">issues-oriented</W>
<W id="151" msd="NC=S" tag="NN" in="" out="">election</W>
<W id="152" msd="XP" tag="," in="" out="">,</W>
<W id="153" msd="VAP" tag="VBN" in="" out="">based</W>
<W id="154" msd="SP" tag="IN" in="" out="">on</W>
<W id="155" msd="PD" tag="DT" in="" out="">the</W>
<W id="156" msd="NP=S" tag="NNP" in="" out="">Republicans'</W>
<W id="157" msd="NC=S" tag="NN" in="" out="">tax</W>
<W id="158" msd="CC" tag="CC" in="" out="">and</W>
<W id="159" msd="ANP" tag="JJ" in="" out="">economic</W>
<W id="160" msd="NC=S" tag="NN" in="" out="">fiasco</W>
<W id="161" msd="XP" tag="," in="" out="">,</W>
<W id="162" msd="CS" tag="IN" in="" out="">while</W>
<W id="163" msd="NP=S" tag="NNP" in="" out="">George</W>
<W id="164" msd="NP=S" tag="NNP" in="" out="">Bush</W>
<W id="165" msd="XP" tag="," in="" out="">,</W>
<W id="166" msd="SP" tag="IN" in="" out="">on</W>
<W id="167" msd="PD" tag="DT" in="" out="">the</W>
<W id="168" msd="ANP" tag="JJ" in="" out="">other</W>
<W id="169" msd="NC=S" tag="NN" in="" out="">hand</W>
<W id="170" msd="XP" tag="," in="" out="">,</W>
<W id="171" msd="VADR" tag="VBZ" in="" out="">has</W>
<W id="172" msd="VAP" tag="VBN" in="" out="">tried</W>
<W id="173" msd="U=" tag="TO" in="" out="">to</W>
<W id="174" msd="VAF" tag="VB" in="" out="">make</W>
<W id="175" msd="PP" tag="PRP" in="" out="">it</W>
<W id="176" msd="ANP" tag="JJ" in="" out="">character-oriented</W>
<W id="177" msd="SP" tag="IN" in="" out="">by</W>
<W id="178" msd="VAG" tag="VBG" in="" out="">putting</W>
<W id="179" msd="ANP" tag="JJ" in="" out="">strong</W>
<W id="180" msd="NC=S" tag="NN" in="" out="">question</W>
<W id="181" msd="NC=P" tag="NNS" in="" out="">marks</W>
<W id="182" msd="SP" tag="IN" in="" out="">on</W>
<W id="183" msd="NP=S" tag="NNP" in="" out="">Bill</W>
<W id="184" msd="NP=S" tag="NNP" in="" out="">Clinton's</W>
<W id="185" msd="NC=S" tag="NN" in="" out="">suitability</W>
<W id="186" msd="XP" tag="," in="" out="">,</W>
<W id="187" msd="ANP" tag="JJ" in="" out="">first</W>
<W id="188" msd="CC" tag="CC" in="" out="">and</W>
<W id="189" msd="ANP" tag="JJ" in="" out="">foremost</W>
<W id="190" msd="XP" tag="," in="" out="">,</W>
<W id="191" msd="SP" tag="IN" in="" out="">on</W>
<W id="192" msd="PD" tag="DT" in="" out="">the</W>
<W id="193" msd="NC=S" tag="NN" in="" out="">basis</W>
<W id="194" msd="SP" tag="IN" in="" out="">of</W>
<W id="195" msd="PO" tag="PRP$" in="" out="">his</W>
<W id="196" msd="NC=S" tag="NN" in="" out="">draft</W>
<W id="197" msd="NC=S" tag="NN" in="" out="">resistance</W>
<W id="198" msd="CC" tag="CC" in="" out="">and</W>
<W id="199" msd="NC=S" tag="NN" in="" out="">opposition</W>
<W id="200" msd="U=" tag="TO" in="" out="">to</W>
<W id="201" msd="PD" tag="DT" in="" out="">the</W>
<W id="202" msd="NP=S" tag="NNP" in="" out="">Vietnam</W>
<W id="203" msd="NC=S" tag="NN" in="" out="">war</W>
<W id="204" msd="XP" tag="." in="" out="">.</W>
</s>
