<s>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VADR" tag="VBP" in="" out="-2:pnct|-1:subj|1:vobj|24:pnct">am</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|1:lobj">looking</W>
<W msd="ANP" tag="RB" in="-1:lobj" out="1:pobj">forward</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pnct|2:ref|4:rel">autumn</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-2:ref|2:mod" out="">when</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|7:[subj]|8:[subj]|13:[subj]" out="">I</W>
<W msd="VA" tag="MD" in="-4:rel" out="-2:mod|-1:subj|1:vobj">can</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:lobj|5:conj|11:conj">move</W>
<W msd="SP" tag="IN" in="-1:lobj" out="1:nobj">into</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">my</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">apartment</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VAF" tag="VB" in="-5:conj" out="-7:[subj]|-1:coord|1:vobj">get</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-8:[subj]|1:pobj">going</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">my</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">studies</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VAF" tag="VB" in="-11:conj" out="-13:[subj]|-1:coord|1:dobj">establish</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">daily</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">routine</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="7:subj|8:[subj]" out="1:nobj|4:pnct">The</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:mod|2:nobj">many</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">free</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">hours</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="2:mod" out="1:pnct">however</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VADR" tag="VBP" in="" out="-7:subj|-2:mod|1:vobj|10:pnct">have</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-8:[subj]|1:iobj|2:dobj">given</W>
<W msd="PP" tag="PRP" in="-1:iobj" out="">me</W>
<W msd="PD" tag="DT" in="-2:dobj" out="1:nobj|2:mod">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">tranquility</W>
<W msd="U=" tag="TO" in="-2:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">consider</W>
<W msd="PO" tag="PRP$" in="-1:dobj" out="1:attr|2:possd">my</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">whole</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="">situation</W>
<W msd="XP" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|6:[subj]" out="">I</W>
<W msd="VADR" tag="VBP" in="" out="-1:subj|1:dobj|5:conj|11:pnct">know</W>
<W msd="PT" tag="WP" in="-1:dobj|2:[dobj]" out="2:rel">what</W>
<W msd="PP" tag="PRP" in="1:subj" out="">I</W>
<W msd="VADR" tag="VBP" in="-2:rel" out="-2:[dobj]|-1:subj|1:pnct">want</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="VADR" tag="VBP" in="-5:conj" out="-6:[subj]|1:dobj">have</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj|2:mod">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">handle</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:dobj">on</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">future</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">fall</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VADR" tag="VBP" in="" out="-5:mod|-1:subj|1:vobj|4:pnct|9:conj|26:pnct">am</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|1:mod">starting</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">HH</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="CC" tag="CC" in="4:coord" out="">and</W>
<W msd="ANP" tag="RB" in="3:mod" out="">then</W>
<W msd="PD" tag="DT" in="2:preds" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">plan</W>
<W msd="VADR" tag="VBZ" in="-9:conj" out="-3:mod|-4:coord|-2:preds|1:subj">is</W>
<W msd="SP" tag="IN" in="-1:subj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|4:[subj]" out="">I</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj">am</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|1:dobj">going</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-4:[subj]|1:mod|8:mod">study</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|3:nobj|4:mod">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">Danish</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Business</W>
<W msd="NP=S" tag="NNP" in="-3:nobj" out="-1:mod">Academy</W>
<W msd="SP" tag="IN" in="-4:mod" out="1:nobj">for</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">Exports</W>
<W msd="ANP" tag="RB" in="-8:mod" out="1:mod">here</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">Århus</W>
<W msd="XP" tag="." in="-26:pnct" out="">.</W>
</s>
<s>
<W msd="PO" tag="PRP$" in="3:subj|4:[subj]" out="1:possd|2:attr">My</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">time</W>
<W msd="ANP" tag="RB" in="-2:attr" out="">abroad</W>
<W msd="VADA" tag="VBD" in="" out="-3:subj|1:vobj|4:pnct">was</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-4:[subj]|1:mod">appealing</W>
<W msd="U=" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">me</W>
<W msd="XP" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="2:conj|11:pnct">And</W>
<W msd="PP" tag="PRP" in="1:subj" out="4:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-2:conj" out="-1:subj|2:preds|1:neg">is</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="ANP" tag="JJ" in="-2:preds" out="">impossible</W>
<W msd="SP" tag="IN" in="-4:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:lobj|2:mod">go</W>
<W msd="ANP" tag="RB" in="-1:lobj" out="">abroad</W>
<W msd="ANP" tag="RB" in="-2:mod" out="">again</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="6:mod" out="1:nobj|3:pnct">At</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">any</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">rate</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="2:subj" out="">I</W>
<W msd="ANP" tag="RB" in="1:mod" out="">still</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj|-1:mod|-6:mod|1:dobj|5:lobj|12:pnct|15:conj|32:pnct#|33:pnct">have</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">number</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">contacts</W>
<W msd="SP" tag="IN" in="-5:lobj" out="1:nobj|5:conj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Brussels</W>
<W msd="ANP" tag="RB" in="2:mod" out="1:aobj">as</W>
<W msd="ANP" tag="RB" in="-1:aobj" out="">well</W>
<W msd="CS" tag="IN" in="1:coord" out="-2:mod">as</W>
<W msd="SP" tag="IN" in="-5:conj" out="-1:coord|1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Norwich</W>
<W msd="XP" tag="," in="-12:pnct" out="">,</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="PP" tag="PRP" in="1:subj" out="7:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-15:conj" out="-1:subj|-2:coord|1:pnct|2:mod|5:preds">is</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-2:mod" out="1:nobj|2:pnct">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">course</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-5:preds" out="">possible</W>
<W msd="SP" tag="IN" in="-7:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W msd="VA" tag="MD" in="-2:vobj" out="-1:subj|1:vobj|4:pnct|5:mod">will</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj">use</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">these</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">contacts</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-5:mod" out="3:vobj">when</W>
<W msd="PO" tag="PRP$" in="2:subj|3:[subj]" out="1:possd">my</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">studies</W>
<W msd="VADR" tag="VBP" in="-3:vobj" out="-2:subj|1:vobj">are</W>
<W msd="ANP" tag="JJ" in="-32:pnct#|-1:vobj" out="-3:[subj]">finished.</W>
<W msd="XP" tag="&amp;quot;" in="-33:pnct" out="">"</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Henrik</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:namef">Mortensen</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:pnct|2:modp|10:dobj|13:lobj|16:pnct">has</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="SP" tag="IN" in="-2:modp" out="1:nobj|6:pnct">like</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:attr|3:nobj|4:attr">all</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">other</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">Danish</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="">professionals</W>
<W msd="ANP" tag="RB" in="-4:attr" out="">abroad</W>
<W msd="XP" tag="&3a;" in="-6:pnct" out="">-</W>
<W msd="ANP" tag="RB" in="1:attr" out="">quite</W>
<W msd="PI" tag="DT" in="-10:dobj" out="-1:attr|1:attr|2:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">few</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">pennies</W>
<W msd="SP" tag="IN" in="-13:lobj" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">his</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">bankbook</W>
<W msd="XP" tag="." in="-16:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="" out="1:ref|2:rel|5:ref|17:pnct">Money</W>
<W msd="PT" tag="WDT" in="-1:ref|1:subj|2:[subj]" out="">that</W>
<W msd="VADR" tag="VBZ" in="-2:rel" out="-1:subj|1:vobj|7:conj">is</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]">invested</W>
<W msd="CC" tag="CC" in="5:coord" out="">and</W>
<W msd="PT" tag="WDT" in="-5:ref|7:dobj" out="">which</W>
<W msd="PD" tag="DT" in="3:subj|6:[subj]" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">unfortunate</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">player</W>
<W msd="VADR" tag="VBZ" in="-7:conj" out="-3:subj|-5:coord|2:dobj|1:neg">hopes</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="U=" tag="TO" in="-2:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-7:dobj|-6:[subj]|1:mod">touch</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="VAG" tag="VBG" in="-1:mod" out="">coming</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">years</W>
<W msd="XP" tag="." in="-17:pnct" out="">.</W>
</s>
