<s>
<W id="1" msd="SP" tag="IN" in="" out="">At</W>
<W id="2" msd="AC" tag="CD" in="" out="">one</W>
<W id="3" msd="NC=S" tag="NN" in="" out="">point</W>
<W id="4" msd="XP" tag="," in="" out="">,</W>
<W id="5" msd="PT" tag="WRB" in="" out="">when</W>
<W id="6" msd="PD" tag="DT" in="" out="">the</W>
<W id="7" msd="NC=S" tag="NN" in="" out="">fervour</W>
<W id="8" msd="SP" tag="IN" in="" out="">in</W>
<W id="9" msd="PD" tag="DT" in="" out="">the</W>
<W id="10" msd="NP=S" tag="NNP" in="" out="">Olé</W>
<W id="11" msd="NC=S" tag="NN" in="" out="">song</W>
<W id="12" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="13" msd="VAG" tag="VBG" in="" out="">missing</W>
<W id="14" msd="XP" tag="," in="" out="">,</W>
<W id="15" msd="CS" tag="IN" in="" out="">because</W>
<W id="16" msd="ANP" tag="RB" in="" out="">too</W>
<W id="17" msd="ANP" tag="JJ" in="" out="">little</W>
<W id="18" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="19" msd="VAG" tag="VBG" in="" out="">happening</W>
<W id="20" msd="XP" tag="," in="" out="">,</W>
<W id="21" msd="PP" tag="PRP" in="" out="">it</W>
<W id="22" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="23" msd="PI" tag="DT" in="" out="">a</W>
<W id="24" msd="ANP" tag="JJ" in="" out="">contagious</W>
<W id="25" msd="NC=S" tag="NN" in="" out="">effect</W>
<W id="26" msd="SP" tag="IN" in="" out="">in</W>
<W id="27" msd="PD" tag="DT" in="" out="">the</W>
<W id="28" msd="NC=P" tag="NNS" in="" out="">stands</W>
<W id="29" msd="XP" tag="," in="" out="">,</W>
<W id="30" msd="PP" tag="PRP" in="" out="">he</W>
<W id="31" msd="VADA" tag="VBD" in="" out="">struck</W>
<W id="32" msd="PD" tag="DT" in="" out="">the</W>
<W id="33" msd="NC=S" tag="NN" in="" out="">ball</W>
<W id="34" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="37" msd="NP=S" tag="NNP" in="" out="">Boom</W>
<W id="38" msd="XP" tag="." in="" out="">?</W>
</s>
<s>
<W id="41" msd="PP" tag="PRP" in="" out="">it</W>
<W id="42" msd="VADA" tag="VBD" in="" out="">went</W>
<W id="43" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="46" msd="CC" tag="CC" in="" out="">And</W>
<W id="47" msd="PD" tag="DT" in="" out="">the</W>
<W id="48" msd="NP=P" tag="NNPS" in="" out="">Germans</W>
<W id="49" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="50" msd="VAP" tag="VBN" in="" out="">received</W>
<W id="51" msd="PD" tag="DT" in="" out="">the</W>
<W id="52" msd="NC=S" tag="NN" in="" out="">shock</W>
<W id="53" msd="PP" tag="PRP" in="" out="">they</W>
<W id="54" msd="ANP" tag="RB" in="" out="">never</W>
<W id="55" msd="VADA" tag="VBD" in="" out="">overcame</W>
<W id="56" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="59" msd="PD" tag="DT" in="" out="">The</W>
<W id="60" msd="NC=S" tag="NN" in="" out="">goal</W>
<W id="61" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="62" msd="PD" tag="DT" in="" out="">the</W>
<W id="63" msd="NC=S" tag="NN" in="" out="">drug</W>
<W id="64" msd="PD" tag="DT" in="" out="">the</W>
<W id="65" msd="VAP" tag="VBN" in="" out="">exhausted</W>
<W id="66" msd="NC=P" tag="NNS" in="" out="">men</W>
<W id="67" msd="VAP" tag="VBN" in="" out="">needed</W>
<W id="68" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="71" msd="PD" tag="DT" in="" out="">That</W>
<W id="72" msd="VADR" tag="VBZ" in="" out="">is</W>
<W id="73" msd="PT" tag="WP" in="" out="">what</W>
<W id="74" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="75" msd="VAP" tag="VBN" in="" out="">needed</W>
<W id="76" msd="U=" tag="TO" in="" out="">to</W>
<W id="77" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="78" msd="NC=S" tag="NN" in="" out="">light</W>
<W id="79" msd="XP" tag="&amp;quot;" in="" out="">"</W>
<W id="80" msd="PD" tag="DT" in="" out="">the</W>
<W id="81" msd="NC=S" tag="NN" in="" out="">dynamite</W>
<W id="82" msd="CC" tag="CC" in="" out="">and</W>
<W id="83" msd="XP" tag="," in="" out="">,</W>
<W id="84" msd="SP" tag="IN" in="" out="">with</W>
<W id="85" msd="NP=S" tag="NNP" in="" out="">John</W>
<W id="86" msd="NP=S" tag="NNP" in="" out="">Jensen</W>
<W id="87" msd="CS" tag="IN" in="" out="">as</W>
<W id="88" msd="NC=S" tag="NN" in="" out="">inspirator</W>
<W id="89" msd="XP" tag="," in="" out="">,</W>
<W id="90" msd="PD" tag="DT" in="" out="">the</W>
<W id="91" msd="NP=P" tag="NNPS" in="" out="">Danes</W>
<W id="92" msd="VADA" tag="VBD" in="" out="">began</W>
<W id="93" msd="U=" tag="TO" in="" out="">to</W>
<W id="94" msd="VAF" tag="VB" in="" out="">challenge</W>
<W id="95" msd="PD" tag="DT" in="" out="">the</W>
<W id="96" msd="NP=P" tag="NNPS" in="" out="">Germans</W>
<W id="97" msd="SP" tag="IN" in="" out="">on</W>
<W id="98" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="99" msd="NC=S" tag="NN" in="" out="">half</W>
<W id="100" msd="SP" tag="IN" in="" out="">of</W>
<W id="101" msd="PD" tag="DT" in="" out="">the</W>
<W id="102" msd="NC=S" tag="NN" in="" out="">field</W>
<W id="103" msd="XP" tag="&3a;" in="" out="">-</W>
<W id="104" msd="PI" tag="DT" in="" out="">a</W>
<W id="105" msd="NC=S" tag="NN" in="" out="">style</W>
<W id="106" msd="SP" tag="IN" in="" out="">of</W>
<W id="107" msd="NC=S" tag="NN" in="" out="">play</W>
<W id="108" msd="PP" tag="PRP" in="" out="">they</W>
<W id="109" msd="VADA" tag="VBD" in="" out="">were</W>
<W id="110" msd="ANP" tag="RB" in="" out="">not</W>
<W id="111" msd="VAP" tag="VBN" in="" out="">used</W>
<W id="112" msd="U=" tag="TO" in="" out="">to</W>
<W id="113" msd="SP" tag="IN" in="" out="">in</W>
<W id="114" msd="PD" tag="DT" in="" out="">the</W>
<W id="115" msd="NP=S" tag="NNP" in="" out="">Bundes</W>
<W id="116" msd="NP=S" tag="NNP" in="" out="">League</W>
<W id="117" msd="XP" tag="," in="" out="">,</W>
<W id="118" msd="PT" tag="WRB" in="" out="">where</W>
<W id="119" msd="PP" tag="PRP" in="" out="">they</W>
<W id="120" msd="ANP" tag="RB" in="" out="">usually</W>
<W id="121" msd="VADR" tag="VBP" in="" out="">have</W>
<W id="122" msd="NC=S" tag="NN" in="" out="">time</W>
<W id="123" msd="CC" tag="CC" in="" out="">and</W>
<W id="124" msd="NC=S" tag="NN" in="" out="">space</W>
<W id="125" msd="SP" tag="IN" in="" out="">in</W>
<W id="126" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="127" msd="ANP" tag="JJ" in="" out="">own</W>
<W id="128" msd="NC=S" tag="NN" in="" out="">zone</W>
<W id="129" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="132" msd="CC" tag="CC" in="" out="">But</W>
<W id="133" msd="PD" tag="DT" in="" out="">this</W>
<W id="134" msd="NC=S" tag="NN" in="" out="">form</W>
<W id="135" msd="SP" tag="IN" in="" out="">of</W>
<W id="136" msd="NC=S" tag="NN" in="" out="">pressure</W>
<W id="137" msd="NC=S" tag="NN" in="" out="">football</W>
<W id="138" msd="VADR" tag="VBZ" in="" out="">requires</W>
<W id="139" msd="NC=S" tag="NN" in="" out="">strength</W>
<W id="140" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="143" msd="CC" tag="CC" in="" out="">And</W>
<W id="144" msd="U=" tag="EX" in="" out="">there</W>
<W id="145" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="146" msd="ANP" tag="RB" in="" out="">not</W>
<W id="147" msd="ANP" tag="JJ" in="" out="">much</W>
<W id="148" msd="SP" tag="IN" in="" out="">of</W>
<W id="149" msd="PD" tag="DT" in="" out="">that</W>
<W id="150" msd="VADA" tag="VBD" in="" out="">left</W>
<W id="151" msd="SP" tag="IN" in="" out="">in</W>
<W id="152" msd="PD" tag="DT" in="" out="">the</W>
<W id="153" msd="ANP" tag="JJ" in="" out="">Danish</W>
<W id="154" msd="NC=S" tag="NN" in="" out="">collective</W>
<W id="155" msd="XP" tag="," in="" out="">,</W>
<W id="156" msd="PT" tag="WDT" in="" out="">which</W>
<W id="157" msd="VADA" tag="VBD" in="" out="">had</W>
<W id="158" msd="U=" tag="TO" in="" out="">to</W>
<W id="159" msd="VAF" tag="VB" in="" out="">release</W>
<W id="160" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="161" msd="NC=S" tag="NN" in="" out="">grip</W>
<W id="162" msd="SP" tag="IN" in="" out="">at</W>
<W id="163" msd="NC=P" tag="NNS" in="" out="">times</W>
<W id="164" msd="XP" tag="," in="" out="">,</W>
<W id="165" msd="ANP" tag="RB" in="" out="">so</W>
<W id="166" msd="PD" tag="DT" in="" out="">the</W>
<W id="167" msd="NP=P" tag="NNPS" in="" out="">Germans</W>
<W id="168" msd="VADA" tag="VBD" in="" out="">were</W>
<W id="169" msd="ANP" tag="JJ" in="" out="">able</W>
<W id="170" msd="U=" tag="TO" in="" out="">to</W>
<W id="171" msd="VAF" tag="VB" in="" out="">put</W>
<W id="172" msd="SP" tag="IN" in="" out="">into</W>
<W id="173" msd="NC=S" tag="NN" in="" out="">motion</W>
<W id="174" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="175" msd="NC=S" tag="NN" in="" out="">fatiguing</W>
<W id="176" msd="CS" tag="IN" in="" out="">if</W>
<W id="177" msd="ANP" tag="JJ" in="" out="">predictable</W>
<W id="178" msd="NC=S" tag="NN" in="" out="">tempo</W>
<W id="179" msd="SP" tag="IN" in="" out="">of</W>
<W id="180" msd="NC=S" tag="NN" in="" out="">play</W>
<W id="181" msd="XP" tag="." in="" out="">.</W>
</s>
<s>
<W id="184" msd="PP" tag="PRP" in="" out="">It</W>
<W id="185" msd="VADA" tag="VBD" in="" out="">was</W>
<W id="186" msd="NC=S" tag="NN" in="" out="">something</W>
<W id="187" msd="U=" tag="TO" in="" out="">to</W>
<W id="188" msd="VAF" tag="VB" in="" out="">see</W>
<W id="189" msd="XP" tag="&3a;" in="" out="">:</W>
</s>
<s>
<W id="192" msd="CS" tag="IN" in="" out="">If</W>
<W id="193" msd="PD" tag="DT" in="" out="">the</W>
<W id="194" msd="NP=P" tag="NNPS" in="" out="">Danes</W>
<W id="195" msd="VA" tag="MD" in="" out="">could</W>
<W id="196" msd="VAF" tag="VB" in="" out="">clear</W>
<W id="197" msd="PD" tag="DT" in="" out="">the</W>
<W id="198" msd="NC=S" tag="NN" in="" out="">hurdle</W>
<W id="199" msd="CC" tag="CC" in="" out="">and</W>
<W id="200" msd="VAF" tag="VB" in="" out="">put</W>
<W id="201" msd="PO" tag="PRP$" in="" out="">their</W>
<W id="202" msd="VAP" tag="VBN" in="" out="">confused</W>
<W id="203" msd="NC=P" tag="NNS" in="" out="">opponents</W>
<W id="204" msd="SP" tag="IN" in="" out="">under</W>
<W id="205" msd="NC=S" tag="NN" in="" out="">pressure</W>
<W id="206" msd="XP" tag="," in="" out="">,</W>
<W id="207" msd="PD" tag="DT" in="" out="">the</W>
<W id="208" msd="NC=S" tag="NN" in="" out="">match</W>
<W id="209" msd="VA" tag="MD" in="" out="">could</W>
<W id="210" msd="VAF" tag="VB" in="" out="">be</W>
<W id="211" msd="VAP" tag="VBN" in="" out="">won</W>
<W id="212" msd="XP" tag="." in="" out="">.</W>
</s>
