<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Erling</W>
<W msd="NP=S" tag="NNP" in="10:subj" out="-1:namef|1:pnct|2:title">Brodersen</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:title" out="1:pobj">chairman</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="NP=S" tag="NNP" in="-1:mod" out="">Danish</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="1:pobj">Association</W>
<W msd="SP" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W msd="NP=S" tag="NNP" in="1:mod" out="">Travel</W>
<W msd="NP=P" tag="NNPS" in="-2:nobj" out="-1:mod">Agents</W>
<W msd="VADR" tag="VBZ" in="" out="-10:subj|1:dobj|6:pnct">signs</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:mod|2:nobj">this</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">frosty</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj">letter</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Spain</W>
<W msd="XP" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="3:subj" out="">R.I.D</W>
</s>
<s>
<W msd="VADR" tag="VBZ" in="" out="-3:subj|1:dobj|12:pnct">represents</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:mod|2:mod|4:nobj|5:pnct|9:modp">all</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">major</W>
<W msd="ANP" tag="JJ" in="-2:mod" out="">Danish</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">travel</W>
<W msd="NC=P" tag="NNS" in="-4:nobj" out="-1:mod">agencies</W>
<W msd="XP" tag=":" in="-5:pnct" out="">-</W>
<W msd="SP" tag="IN" in="3:mod" out="1:nobj|2:pnct">among</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">them</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-9:modp" out="-3:mod|1:nobj">Larsen</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Travel</W>
<W msd="XP" tag=":" in="-12:pnct" out="">:</W>
</s>
<s>
<W msd="XP" tag="&quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj" out="">We</W>
<W msd="VADR" tag="VBP" in="36:qobj" out="-2:pnct|-1:subj|1:mod|3:dobj|5:lobj|15:pnct|16:coord|34:pnct|35:pnct">send</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">season</W>
<W msd="AC" tag="CD" in="-3:dobj" out="1:nobj|4:mod|6:mod">four</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">planes</W>
<W msd="U=" tag="TO" in="-5:lobj" out="1:nobj">to</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Ibiza</W>
<W msd="PI" tag="DT" in="-4:mod" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">week</W>
<W msd="SP" tag="IN" in="-6:mod" out="1:nobj">with</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">total</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">700-750</W>
<W msd="NP=P" tag="NNPS" in="-1:nobj" out="">Danes</W>
<W msd="XP" tag="," in="-15:pnct" out="">,</W>
<W msd="CC" tag="CC" in="-16:coord" out="2:conj">and</W>
<W msd="PP" tag="PRP" in="1:subj" out="3:nobj">it</W>
<W msd="VADR" tag="VBZ" in="-2:conj" out="-1:subj|1:pred">is</W>
<W msd="ANP" tag="JJ" in="-1:pred" out="">clear</W>
<W msd="SP" tag="IN" in="-3:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">we</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj">cannot</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-2:[subj]|5:dobj">tolerate</W>
<W msd="AC" tag="CD" in="4:subj|5:[subj]" out="1:pobj">one</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="1:possd">our</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="">guests</W>
<W msd="VAG" tag="VBG" in="-5:dobj" out="-4:subj|1:vobj">being</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-5:[subj]|1:pobj">attacked</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">local</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">police</W>
<W msd="XP" tag="," in="-34:pnct" out="">,</W>
<W msd="XP" tag="&quot;" in="-35:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="" out="-36:qobj|2:subj|9:mod|45:pnct">says</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Jens</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef|1:pnct|2:title">Veino</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="-2:title" out="1:pnct|2:list">director</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="-2:list" out="1:nobj|2:pnct">Larsen</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Travel</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="CS" tag="IN" in="-9:mod" out="7:vobj">after</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">17-year</W>
<W msd="ANP" tag="JJ" in="2:mod" out="-1:mod">old</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Mark</W>
<W msd="NP=S" tag="NNP" in="3:subj|11:[subj]" out="-1:namef|-2:mod|1:mod">Georgi</W>
<W msd="SP" tag="IN" in="-1:mod" out="1:nobj">from</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Taastrup</W>
<W msd="VADA" tag="VBD" in="-7:vobj" out="-3:subj|1:lobj|2:mod|7:coord">came</W>
<W msd="ANP" tag="RB" in="-1:lobj" out="">forward</W>
<W msd="U=" tag="TO" in="-2:mod" out="1:nobj">to</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pnct">B.T</W>
<W msd="XP" tag="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="-7:coord" out="1:conj">and</W>
<W msd="VAP" tag="VBN" in="-1:conj" out="-11:[subj]|1:dobj">related</W>
<W msd="PT" tag="WP" in="-1:dobj|1:[subj]|2:[subj]" out="1:rel">what</W>
<W msd="VADR" tag="VBZ" in="-1:rel" out="-1:[subj]|1:vobj">is</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-2:[subj]|1:pobj">happening</W>
<W msd="U=" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:ref|10:rel">tourists</W>
<W msd="PT" tag="WP" in="-1:ref|9:subj|11:[subj]" out="">who</W>
<W msd="XP" tag="," in="" out="">,</W>
<W msd="SP" tag="IN" in="7:mod" out="1:nobj|6:pnct">for</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:mod|2:nobj|3:coord">one</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">trivial</W>
<W msd="NC=S" tag="NN" in="-2:nobj|2:[nobj]" out="">reason</W>
<W msd="CC" tag="CC" in="-3:coord" out="1:conj">or</W>
<W msd="PD" tag="DT" in="-1:conj" out="-2:[nobj]">another</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="VAF" tag="VB" in="-10:rel" out="-9:subj|-7:mod|1:dobj">happen</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-11:[subj]|1:dobj">irritate</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">Spanish</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">police</W>
<W msd="XP" tag="." in="-45:pnct" out="">.</W>
</s>
<s>
<W msd="NC=S" tag="NN" in="1:mod" out="">POLICE</W>
<W msd="NP=S" tag="NNP" in="" out="-1:mod">BLACKMAIL</W>
</s>
<s>
<W msd="PD" tag="DT" in="8:subj|9:[subj]|12:[subj]|14:[subj]" out="1:nobj|2:pnct">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">boy</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="5:mod" out="1:pobj|4:pnct">together</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">friend</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VADA" tag="VBD" in="" out="-8:subj|-5:mod|1:vobj|9:pnct">was</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-9:[subj]|1:avobj|2:pnct|3:conj|4:coord">knocked</W>
<W msd="ANP" tag="RB" in="-1:avobj" out="">down</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="VAP" tag="VBN" in="-3:conj" out="-12:[subj]">beaten</W>
<W msd="CC" tag="CC" in="-4:coord" out="1:conj">and</W>
<W msd="VAF" tag="VB" in="-1:conj" out="-14:[subj]|1:pobj">put</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">handcuffs</W>
<W msd="XP" tag="." in="-9:pnct" out="">.</W>
</s>
<s>
<W msd="PI" tag="DT" in="" out="1:nobj|2:ref|3:rel|23:pnct">An</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">attack</W>
<W msd="PT" tag="WDT" in="-2:ref|1:subj" out="">that</W>
<W msd="VADA" tag="VBD" in="-3:rel" out="-1:subj|2:pred">was</W>
<W msd="ANP" tag="RB" in="1:mod" out="2:nobj">so</W>
<W msd="ANP" tag="JJ" in="-2:pred" out="-1:mod">violent</W>
<W msd="SP" tag="IN" in="-2:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj|6:[subj]|8:[subj]" out="">he</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|1:dobj|3:coord">burst</W>
<W msd="PO" tag="PRP$" in="-1:dobj" out="1:possd">his</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="">eardrum</W>
<W msd="CC" tag="CC" in="-3:coord" out="2:conj">and</W>
<W msd="ANP" tag="RB" in="1:mod" out="">now</W>
<W msd="VADA" tag="VBD" in="-2:conj" out="-6:[subj]|-1:mod|1:dobj">had</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-8:[subj]|1:dobj|3:mod">undergo</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">an</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">operation</W>
<W msd="U=" tag="TO" in="-3:mod" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">get</W>
<W msd="PI" tag="DT" in="-1:dobj" out="2:nobj">a</W>
<W msd="ANP" tag="JJ" in="1:mod" out="">new</W>
<W msd="AC" tag="CD" in="-2:nobj" out="-1:mod">one</W>
<W msd="XP" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="6:mod" out="1:pnct">Then</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="4:subj" out="1:nobj">the</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:mod|2:nobj">two</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">young</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">people</W>
<W msd="VADA" tag="VBD" in="" out="-6:mod|-4:subj|1:pred|5:mod|9:pnct">became</W>
<W msd="PD" tag="DT" in="-1:pred" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">object</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">blackmail</W>
<W msd="SP" tag="IN" in="-5:mod" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:mod" out="">Spanish</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">policeman</W>
<W msd="XP" tag=":" in="-9:pnct" out="">:</W>
</s>
