<s>
<W msd="PD" tag="PD">De</W>
<W msd="AN" tag="AN">danske</W>
<W msd="NC" tag="NC">socialdemokrater</W>
<W msd="VA" tag="VA">har</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">dag</W>
<W msd="NC" tag="NC">stemt</W>
<W msd="SP" tag="SP">imod</W>
<W msd="NC" tag="NC">betænkningen</W>
<W msd="SP" tag="SP">af</W>
<W msd="NP" tag="NP">Dimitrakopoulos</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Leinen</W>
<W msd="XP" tag="XP">.</W>
</s>
<s>
<W msd="NC" tag="NC">Udvidelsen</W>
<W msd="SP" tag="SP">af</W>
<W msd="NP" tag="NP">EU</W>
<W msd="VA" tag="VA">er</W>
<W msd="PI" tag="PI">en</W>
<W msd="AN" tag="AN">historisk</W>
<W msd="NC" tag="NC">chance</W>
<W msd="SP" tag="SP">for</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">skabe</W>
<W msd="PI" tag="PI">et</W>
<W msd="AN" tag="AN">fredeligt</W>
<W msd="XP" tag="XP">,</W>
<W msd="AN" tag="AN">stabilt</W>
<W msd="CC" tag="CC">og</W>
<W msd="VA" tag="VA">samarbejdende</W>
<W msd="NP" tag="NP">Europa</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">samtidig</W>
<W msd="NP" tag="NP">EU</W>
<W msd="XA" tag="XA">'</W>
<W msd="NC" tag="NC">s</W>
<W msd="RG" tag="RG">hidtil</W>
<W msd="AN" tag="AN">største</W>
<W msd="NC" tag="NC">udfordring</W>
<W msd="XP" tag="XP">.</W>
<W msd="PI" tag="PI">En</W>
<W msd="NC" tag="NC">ændring</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">traktaterne</W>
<W msd="VA" tag="VA">er</W>
<W msd="PI" tag="PI">en</W>
<W msd="NC" tag="NC">forudsætning</W>
<W msd="SP" tag="SP">for</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">gøre</W>
<W msd="NP" tag="NP">EU</W>
<W msd="AN" tag="AN">klar</W>
<W msd="SP" tag="SP">til</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">optage</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">nye</W>
<W msd="XX" tag="XX">øst-</W>
<W msd="CC" tag="CC">og</W>
<W msd="AN" tag="AN">centraleuropæiske</W>
<W msd="NC" tag="NC">lande</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">er</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">disse</W>
<W msd="NC" tag="NC">dage</W>
<W msd="AC" tag="AC">10</W>
<W msd="NC" tag="NC">år</W>
<W msd="RG" tag="RG">siden</W>
<W msd="XP" tag="XP">,</W>
<W msd="NP" tag="NP">Berlinmuren</W>
<W msd="VA" tag="VA">faldt</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Vi</W>
<W msd="VA" tag="VA">er</W>
<W msd="AN" tag="AN">enige</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">den</W>
<W msd="NC" tag="NC">tidsplan</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">er</W>
<W msd="VA" tag="VA">foreslået</W>
<W msd="XP" tag="XP">,</W>
<W msd="RG" tag="RG">sådan</W>
<W msd="CS" tag="CS">at</W>
<W msd="NC" tag="NC">regeringskonferencen</W>
<W msd="VA" tag="VA">kan</W>
<W msd="VA" tag="VA">være</W>
<W msd="VA" tag="VA">afsluttet</W>
<W msd="SP" tag="SP">med</W>
<W msd="NC" tag="NC">udgangen</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">år</W>
<W msd="AC" tag="AC">2000</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">må</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="VA" tag="VA">være</W>
<W msd="AN" tag="AN">formelle</W>
<W msd="NC" tag="NC">forhold</W>
<W msd="U=" tag="U=">som</W>
<W msd="RG" tag="RG">f.eks.</W>
<W msd="NC" tag="NC">ændring</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">traktaterne</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">udsætter</W>
<W msd="NC" tag="NC">optagelsen</W>
<W msd="XP" tag="XP">.</W>
<W msd="RG" tag="RG">Derfor</W>
<W msd="VA" tag="VA">skal</W>
<W msd="PP" tag="PP">vi</W>
<W msd="RG" tag="RG">også</W>
<W msd="VA" tag="VA">være</W>
<W msd="AN" tag="AN">omhyggelige</W>
<W msd="SP" tag="SP">med</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">lægge</W>
<W msd="NC" tag="NC">sten</W>
<W msd="CC" tag="CC">eller</W>
<W msd="NC" tag="NC">blokeringer</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">vejen</W>
<W msd="SP" tag="SP">for</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="NC" tag="NC">regeringskonferencen</W>
<W msd="VA" tag="VA">kan</W>
<W msd="VA" tag="VA">slutte</W>
<W msd="SP" tag="SP">til</W>
<W msd="NC" tag="NC">tiden</W>
<W msd="XP" tag="XP">,</W>
<W msd="CC" tag="CC">og</W>
<W msd="CS" tag="CS">at</W>
<W msd="NC" tag="NC">resultatet</W>
<W msd="VA" tag="VA">kan</W>
<W msd="VA" tag="VA">godkendes</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">enkelte</W>
<W msd="NC" tag="NC">lande</W>
<W msd="SP" tag="SP">efter</W>
<W msd="NC" tag="NC">reglerne</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">respektive</W>
<W msd="NC" tag="NC">landes</W>
<W msd="NC" tag="NC">grundlove</W>
<W msd="XP" tag="XP">.</W>
</s>
<s>
<W msd="NC" tag="NC">Betænkningen</W>
<W msd="SP" tag="SP">af</W>
<W msd="NP" tag="NP">Dimitrakopoulos</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Leinen</W>
<W msd="VA" tag="VA">lægger</W>
<W msd="RG" tag="RG">op</W>
<W msd="SP" tag="SP">til</W>
<W msd="PI" tag="PI">en</W>
<W msd="AN" tag="AN">meget</W>
<W msd="AN" tag="AN">gennemgribende</W>
<W msd="NC" tag="NC">revision</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">som</W>
<W msd="PP" tag="PP">vi</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="VA" tag="VA">mener</W>
<W msd="XP" tag="XP">,</W>
<W msd="PP" tag="PP">det</W>
<W msd="VA" tag="VA">vil</W>
<W msd="VA" tag="VA">være</W>
<W msd="AN" tag="AN">muligt</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">gennemføre</W>
<W msd="RG" tag="RG">inden</W>
<W msd="SP" tag="SP">for</W>
<W msd="PD" tag="PD">den</W>
<W msd="AN" tag="AN">fastlagte</W>
<W msd="NC" tag="NC">tidsramme</W>
<W msd="XP" tag="XP">-</W>
<W msd="RG" tag="RG">derfor</W>
<W msd="VA" tag="VA">har</W>
<W msd="PP" tag="PP">vi</W>
<W msd="AN" tag="AN">stemt</W>
<W msd="RG" tag="RG">imod</W>
<W msd="XP" tag="XP">.</W>
<W msd="PD" tag="PD">De</W>
<W msd="AN" tag="AN">mange</W>
<W msd="NC" tag="NC">ændringsforslag</W>
<W msd="CC" tag="CC">og</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">mange</W>
<W msd="AN" tag="AN">forskellige</W>
<W msd="NC" tag="NC">meninger</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">er</W>
<W msd="VA" tag="VA">tilkendegivet</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">forbindelse</W>
<W msd="SP" tag="SP">med</W>
<W msd="NC" tag="NC">afstemningen</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">dag</W>
<W msd="XP" tag="XP">,</W>
<W msd="VA" tag="VA">illustrerer</W>
<W msd="SP" tag="SP">med</W>
<W msd="AN" tag="AN">al</W>
<W msd="AN" tag="AN">ønskelig</W>
<W msd="NC" tag="NC">tydelighed</W>
<W msd="XP" tag="XP">,</W>
<W msd="PT" tag="PT">hvilke</W>
<W msd="NC" tag="NC">problemer</W>
<W msd="PI" tag="PI">en</W>
<W msd="AN" tag="AN">meget</W>
<W msd="AN" tag="AN">omfattende</W>
<W msd="NC" tag="NC">dagsorden</W>
<W msd="VA" tag="VA">vil</W>
<W msd="VA" tag="VA">medføre</W>
<W msd="XP" tag="XP">.</W>
</s>
<s>
<W msd="U=" tag="U=">Som</W>
<W msd="NC" tag="NC">medlemmer</W>
<W msd="SP" tag="SP">af</W>
<W msd="PD" tag="PD">den</W>
<W msd="AN" tag="AN">socialdemokratiske</W>
<W msd="NC" tag="NC">gruppe</W>
<W msd="VA" tag="VA">har</W>
<W msd="PP" tag="PP">vi</W>
<W msd="VA" tag="VA">stemt</W>
<W msd="RG" tag="RG">sammen</W>
<W msd="SP" tag="SP">med</W>
<W msd="PO" tag="PO">vores</W>
<W msd="NC" tag="NC">partifæller</W>
<W msd="RG" tag="RG">for</W>
<W msd="CC" tag="CC">og</W>
<W msd="SP" tag="SP">imod</W>
<W msd="PI" tag="PI">en</W>
<W msd="NC" tag="NC">række</W>
<W msd="NC" tag="NC">ændringsforslag</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">har</W>
<W msd="PP" tag="PP">vi</W>
<W msd="VA" tag="VA">gjort</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">fordi</W>
<W msd="PP" tag="PP">vi</W>
<W msd="RG" tag="RG">gerne</W>
<W msd="VA" tag="VA">vil</W>
<W msd="VA" tag="VA">præge</W>
<W msd="NC" tag="NC">udviklingen</W>
<W msd="SP" tag="SP">i</W>
<W msd="NP" tag="NP">Europa</W>
<W msd="SP" tag="SP">i</W>
<W msd="PI" tag="PI">en</W>
<W msd="AN" tag="AN">socialdemokratisk</W>
<W msd="NC" tag="NC">retning</W>
<W msd="XP" tag="XP">.</W>
<W msd="PD" tag="PD">Dette</W>
<W msd="VA" tag="VA">ændrer</W>
<W msd="RG" tag="RG">dog</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="SP" tag="SP">ved</W>
<W msd="PO" tag="PO">vores</W>
<W msd="AN" tag="AN">generelle</W>
<W msd="NC" tag="NC">opfattelse</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">betænkningen</W>
<W msd="XP" tag="XP">.</W>
<W msd="U=" tag="U=">Der</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">dog</W>
<W msd="PI" tag="PI">en</W>
<W msd="NC" tag="NC">række</W>
<W msd="NC" tag="NC">punkter</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">som</W>
<W msd="PP" tag="PP">vi</W>
<W msd="AN" tag="AN">klart</W>
<W msd="VA" tag="VA">må</W>
<W msd="VA" tag="VA">tage</W>
<W msd="NC" tag="NC">afstand</W>
<W msd="SP" tag="SP">fra</W>
<W msd="XP" tag="XP">,</W>
<W msd="RG" tag="RG">herunder</W>
<W msd="NC" tag="NC">initiativer</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">fjerner</W>
<W msd="PD" tag="PD">det</W>
<W msd="AN" tag="AN">grundlæggende</W>
<W msd="NC" tag="NC">princip</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="PP" tag="PP">det</W>
<W msd="VA" tag="VA">er</W>
<W msd="NC" tag="NC">medlemsstaterne</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">overensstemmelse</W>
<W msd="SP" tag="SP">med</W>
<W msd="PO" tag="PO">deres</W>
<W msd="AN" tag="AN">respektive</W>
<W msd="NC" tag="NC">grundlove</W>
<W msd="VA" tag="VA">indgår</W>
<W msd="CC" tag="CC">og</W>
<W msd="VA" tag="VA">ændrer</W>
<W msd="NC" tag="NC">traktaten</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Vi</W>
<W msd="VA" tag="VA">må</W>
<W msd="RG" tag="RG">også</W>
<W msd="AN" tag="AN">klart</W>
<W msd="VA" tag="VA">tage</W>
<W msd="NC" tag="NC">afstand</W>
<W msd="SP" tag="SP">fra</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="NP" tag="NP">EU</W>
<W msd="VA" tag="VA">gøres</W>
<W msd="SP" tag="SP">til</W>
<W msd="PI" tag="PI">en</W>
<W msd="NC" tag="NC">forsvarsalliance</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="PI" tag="PI">en</W>
<W msd="NC" tag="NC">opgave</W>
<W msd="SP" tag="SP">for</W>
<W msd="NP" tag="NP">EU</W>
<W msd="XP" tag="XP">,</W>
<W msd="CC" tag="CC">men</W>
<W msd="SP" tag="SP">for</W>
<W msd="NP" tag="NP">NATO</W>
<W msd="XP" tag="XP">.</W>
</s>
