<s>
<W id="1" msd="NC" tag="NC" in="" out="">Tak</W>
<W id="2" msd="AN" tag="AN" in="" out="">hr.</W>
<W id="3" msd="NC" tag="NC" in="" out="">formand</W>
<W id="4" msd="XP" tag="XP" in="" out="">.</W>
<W id="5" msd="PP" tag="PP" in="" out="3:coref">Jeg</W>
<W id="6" msd="VA" tag="VA" in="" out="">vil</W>
<W id="7" msd="SP" tag="SP" in="" out="">i</W>
<W id="8" msd="PO" tag="PO" in="-3:coref" out="10:coref|211:coref">mit</W>
<W id="9" msd="NC" tag="NC" in="" out="">indlæg</W>
<W id="10" msd="RG" tag="RG" in="" out="">her</W>
<W id="11" msd="RG" tag="RG" in="" out="">alene</W>
<W id="12" msd="NC" tag="NC" in="" out="">tale</W>
<W id="13" msd="SP" tag="SP" in="" out="">om</W>
<W id="14" msd="PD" tag="PD" in="" out="">det</W>
<W id="15" msd="AN" tag="AN" in="" out="">europæiske</W>
<W id="16" msd="NC" tag="NC" in="" out="">patent</W>
<W id="17" msd="XP" tag="XP" in="" out="">.</W>
<W id="18" msd="PP" tag="PP" in="-10:coref" out="">Det</W>
<W id="19" msd="VA" tag="VA" in="" out="">er</W>
<W id="20" msd="SP" tag="SP" in="" out="">på</W>
<W id="21" msd="NC" tag="NC" in="" out="">linje</W>
<W id="22" msd="SP" tag="SP" in="" out="">med</W>
<W id="23" msd="XP" tag="XP" in="" out="">,</W>
<W id="24" msd="PT" tag="PT" in="" out="">hvad</W>
<W id="25" msd="NC" tag="NC" in="" out="">kommissær</W>
<W id="26" msd="NC" tag="NC" in="" out="">Bolkestein</W>
<W id="27" msd="VA" tag="VA" in="" out="">sagde</W>
<W id="28" msd="XP" tag="XP" in="" out="">,</W>
<W id="29" msd="PT" tag="PT" in="" out="">hvad</W>
<W id="30" msd="PD" tag="PD" in="" out="">de</W>
<W id="31" msd="AN" tag="AN" in="" out="">fleste</W>
<W id="32" msd="NC" tag="NC" in="" out="">talere</W>
<W id="33" msd="RG" tag="RG" in="" out="">her</W>
<W id="34" msd="VA" tag="VA" in="" out="">har</W>
<W id="35" msd="VA" tag="VA" in="" out="">nævnt</W>
<W id="36" msd="XP" tag="XP" in="" out="">,</W>
<W id="37" msd="CC" tag="CC" in="" out="">men</W>
<W id="38" msd="PT" tag="PT" in="" out="">hvad</W>
<W id="39" msd="NC" tag="NC" in="" out="6:coref">formanden</W>
<W id="40" msd="SP" tag="SP" in="" out="">for</W>
<W id="41" msd="NC" tag="NC" in="0:assoc-frame" out="14:coref-iden|0:assoc-frame">Rådet</W>
<W id="42" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="43" msd="VA" tag="VA" in="" out="">havde</W>
<W id="44" msd="SP" tag="SP" in="" out="">i</W>
<W id="45" msd="PO" tag="PO" in="-6:coref" out="">sit</W>
<W id="46" msd="NC" tag="NC" in="" out="">indlæg</W>
<W id="47" msd="XP" tag="XP" in="" out="">.</W>
</s>
<s>
<W id="50" msd="PP" tag="PP" in="0:assoc-frame" out="59:coref|0:assoc-frame">Vi</W>
<W id="51" msd="VA" tag="VA" in="" out="">bør</W>
<W id="52" msd="VA" tag="VA" in="" out="">skubbe</W>
<W id="53" msd="AN" tag="AN" in="" out="">kraftigt</W>
<W id="54" msd="SP" tag="SP" in="" out="">til</W>
<W id="55" msd="NC" tag="NC" in="-14:coref-iden" out="3:coref">Rådet</W>
<W id="56" msd="CC" tag="CC" in="" out="">og</W>
<W id="57" msd="VA" tag="VA" in="" out="">bede</W>
<W id="58" msd="PP" tag="PP" in="-3:coref" out="20:coref-var">det</W>
<W id="59" msd="SP" tag="SP" in="" out="">om</W>
<W id="60" msd="XP" tag="XP" in="" out="">,</W>
<W id="61" msd="AN" tag="AN" in="" out="">hurtigst</W>
<W id="62" msd="AN" tag="AN" in="" out="">muligt</W>
<W id="63" msd="U=" tag="U=" in="" out="">at</W>
<W id="64" msd="VA" tag="VA" in="" out="">få</W>
<W id="65" msd="VA" tag="VA" in="" out="">gennemført</W>
<W id="66" msd="PI" tag="PI" in="" out="">et</W>
<W id="67" msd="AN" tag="AN" in="" out="">europæisk</W>
<W id="68" msd="NC" tag="NC" in="" out="">patent</W>
<W id="69" msd="XP" tag="XP" in="" out="">.</W>
<W id="70" msd="PD" tag="PD" in="" out="">Det</W>
<W id="71" msd="NC" tag="NC" in="" out="2:ref">problem</W>
<W id="72" msd="XP" tag="XP" in="" out="">,</W>
<W id="73" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="74" msd="PP" tag="PP" in="" out="">vi</W>
<W id="75" msd="VA" tag="VA" in="" out="">forstår</W>
<W id="76" msd="XP" tag="XP" in="" out="">,</W>
<W id="77" msd="CS" tag="CS" in="" out="">at</W>
<W id="78" msd="NC" tag="NC" in="-20:coref-var" out="23:assoc-const|190:coref-iden">Rådet</W>
<W id="79" msd="VA" tag="VA" in="" out="">står</W>
<W id="80" msd="RG" tag="RG" in="" out="">over</W>
<W id="81" msd="SP" tag="SP" in="" out="">for</W>
<W id="82" msd="XP" tag="XP" in="" out="">,</W>
<W id="83" msd="VA" tag="VA" in="" out="">er</W>
<W id="84" msd="NC" tag="NC" in="" out="7:coref">sprogproblemet</W>
<W id="85" msd="XP" tag="XP" in="" out="">,</W>
<W id="86" msd="CC" tag="CC" in="" out="">men</W>
<W id="87" msd="PP" tag="PP" in="" out="">det</W>
<W id="88" msd="VA" tag="VA" in="" out="">skal</W>
<W id="89" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="90" msd="VA" tag="VA" in="" out="">være</W>
<W id="91" msd="PP" tag="PP" in="-7:coref" out="2:ref">det</W>
<W id="92" msd="XP" tag="XP" in="" out="">,</W>
<W id="93" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="94" msd="VA" tag="VA" in="" out="">hindrer</W>
<W id="95" msd="PI" tag="PI" in="" out="">en</W>
<W id="96" msd="AN" tag="AN" in="" out="">konkurrencedygtig</W>
<W id="97" msd="NC" tag="NC" in="" out="">økonomi</W>
<W id="98" msd="XP" tag="XP" in="" out="">,</W>
<W id="99" msd="RG" tag="RG" in="" out="">således</W>
<W id="100" msd="U=" tag="U=" in="" out="">som</W>
<W id="101" msd="NC" tag="NC" in="-23:assoc-const" out="3:coref">rådsformanden</W>
<W id="102" msd="VA" tag="VA" in="" out="">fremhævede</W>
<W id="103" msd="SP" tag="SP" in="" out="">i</W>
<W id="104" msd="PO" tag="PO" in="-3:coref" out="">sit</W>
<W id="105" msd="NC" tag="NC" in="" out="">indlæg</W>
<W id="106" msd="XP" tag="XP" in="" out="">.</W>
<W id="107" msd="PD" tag="PD" in="" out="">De</W>
<W id="108" msd="NC" tag="NC" in="0:ref" out="0:ref">patenter</W>
<W id="109" msd="PP" tag="PP" in="-59:coref" out="6:coref">vi</W>
<W id="110" msd="VA" tag="VA" in="" out="">udtager</W>
<W id="111" msd="SP" tag="SP" in="" out="">i</W>
<W id="112" msd="NP" tag="NP" in="" out="">EU</W>
<W id="113" msd="XP" tag="XP" in="" out="">,</W>
<W id="114" msd="VA" tag="VA" in="" out="7:coref-res">udtager</W>
<W id="115" msd="PP" tag="PP" in="-6:coref" out="10:coref">vi</W>
<W id="116" msd="AN" tag="AN" in="" out="">normalt</W>
<W id="117" msd="RG" tag="RG" in="" out="">også</W>
<W id="118" msd="SP" tag="SP" in="" out="">i</W>
<W id="119" msd="NP" tag="NP" in="" out="">USA</W>
<W id="120" msd="XP" tag="XP" in="" out="">,</W>
<W id="121" msd="PP" tag="PP" in="-7:coref-res" out="">det</W>
<W id="122" msd="VA" tag="VA" in="" out="">vil</W>
<W id="123" msd="VA" tag="VA" in="" out="">sige</W>
<W id="124" msd="CS" tag="CS" in="" out="">at</W>
<W id="125" msd="PP" tag="PP" in="-10:coref" out="103:coref">vi</W>
<W id="126" msd="VA" tag="VA" in="" out="">skal</W>
<W id="127" msd="VA" tag="VA" in="" out="">oversætte</W>
<W id="128" msd="SP" tag="SP" in="" out="">til</W>
<W id="129" msd="NC" tag="NC" in="" out="">engelsk</W>
<W id="130" msd="XP" tag="XP" in="" out="">,</W>
<W id="131" msd="CC" tag="CC" in="" out="">og</W>
<W id="132" msd="RG" tag="RG" in="" out="">hvorfor</W>
<W id="133" msd="RG" tag="RG" in="" out="">så</W>
<W id="134" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="135" msd="VA" tag="VA" in="" out="">beslutte</W>
<W id="136" msd="PI" tag="PI" in="" out="">én</W>
<W id="137" msd="NC" tag="NC" in="" out="">gang</W>
<W id="138" msd="SP" tag="SP" in="" out="">for</W>
<W id="139" msd="AN" tag="AN" in="" out="">alle</W>
<W id="140" msd="XP" tag="XP" in="" out="">,</W>
<W id="141" msd="CS" tag="CS" in="" out="">at</W>
<W id="142" msd="PI" tag="PI" in="" out="">et</W>
<W id="143" msd="NC" tag="NC" in="" out="">patent</W>
<W id="144" msd="SP" tag="SP" in="" out="">i</W>
<W id="145" msd="NP" tag="NP" in="" out="">EU</W>
<W id="146" msd="RG" tag="RG" in="" out="">kun</W>
<W id="147" msd="VA" tag="VA" in="" out="7:coref-res|12:coref-res|18:coref-res">behøver</W>
<W id="148" msd="U=" tag="U=" in="" out="">at</W>
<W id="149" msd="VA" tag="VA" in="" out="">blive</W>
<W id="150" msd="VA" tag="VA" in="" out="">udstedt</W>
<W id="151" msd="SP" tag="SP" in="" out="">på</W>
<W id="152" msd="NC" tag="NC" in="" out="">engelsk</W>
<W id="153" msd="XP" tag="XP" in="" out="">;</W>
<W id="154" msd="PP" tag="PP" in="-7:coref-res" out="">det</W>
<W id="155" msd="VA" tag="VA" in="" out="">vil</W>
<W id="156" msd="VA" tag="VA" in="" out="">simplificere</W>
<W id="157" msd="XP" tag="XP" in="" out="">,</W>
<W id="158" msd="CC" tag="CC" in="" out="">og</W>
<W id="159" msd="PP" tag="PP" in="-12:coref-res" out="">det</W>
<W id="160" msd="VA" tag="VA" in="" out="">vil</W>
<W id="161" msd="VA" tag="VA" in="" out="">spare</W>
<W id="162" msd="AN" tag="AN" in="" out="">enorme</W>
<W id="163" msd="NC" tag="NC" in="" out="">omkostninger</W>
<W id="164" msd="XP" tag="XP" in="" out="">,</W>
<W id="165" msd="PP" tag="PP" in="-18:coref-res" out="">det</W>
<W id="166" msd="VA" tag="VA" in="" out="">vil</W>
<W id="167" msd="VA" tag="VA" in="" out="">være</W>
<W id="168" msd="SP" tag="SP" in="" out="">i</W>
<W id="169" msd="NC" tag="NC" in="" out="">overensstemmelse</W>
<W id="170" msd="SP" tag="SP" in="" out="">med</W>
<W id="171" msd="PP" tag="PP" in="" out="2:ref">det</W>
<W id="172" msd="XP" tag="XP" in="" out="">,</W>
<W id="173" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="174" msd="PD" tag="PD" in="" out="6:coref">de</W>
<W id="175" msd="AN" tag="AN" in="" out="">innovative</W>
<W id="176" msd="NC" tag="NC" in="" out="">folk</W>
<W id="177" msd="VA" tag="VA" in="" out="">arbejder</W>
<W id="178" msd="RG" tag="RG" in="" out="">med</W>
<W id="179" msd="XP" tag="XP" in="" out="">.</W>
<W id="180" msd="PP" tag="PP" in="-6:coref" out="3:coref">De</W>
<W id="181" msd="VA" tag="VA" in="" out="">siger</W>
<W id="182" msd="XP" tag="XP" in="" out="">:</W>
<W id="183" msd="PP" tag="PP" in="-3:coref" out="6:coref">vi</W>
<W id="184" msd="VA" tag="VA" in="" out="">har</W>
<W id="185" msd="PI" tag="PI" in="" out="7:coref">en</W>
<W id="186" msd="AN" tag="AN" in="" out="">innovativ</W>
<W id="187" msd="NC" tag="NC" in="" out="">idé</W>
<W id="188" msd="XP" tag="XP" in="" out="">,</W>
<W id="189" msd="PP" tag="PP" in="-6:coref" out="9:coref">vi</W>
<W id="190" msd="VA" tag="VA" in="" out="">kan</W>
<W id="191" msd="VA" tag="VA" in="" out="">sælge</W>
<W id="192" msd="PD" tag="PD" in="-7:coref" out="11:coref">den</W>
<W id="193" msd="AN" tag="AN" in="" out="">globalt</W>
<W id="194" msd="XP" tag="XP" in="" out="">,</W>
<W id="195" msd="CC" tag="CC" in="" out="">og</W>
<W id="196" msd="RG" tag="RG" in="" out="">derfor</W>
<W id="197" msd="VA" tag="VA" in="" out="">er</W>
<W id="198" msd="PP" tag="PP" in="-9:coref" out="">vi</W>
<W id="199" msd="AN" tag="AN" in="" out="">nødt</W>
<W id="200" msd="SP" tag="SP" in="" out="">til</W>
<W id="201" msd="U=" tag="U=" in="" out="">at</W>
<W id="202" msd="VA" tag="VA" in="" out="">oversætte</W>
<W id="203" msd="PP" tag="PP" in="-11:coref" out="">den</W>
<W id="204" msd="SP" tag="SP" in="" out="">til</W>
<W id="205" msd="NC" tag="NC" in="" out="">engelsk</W>
<W id="206" msd="XP" tag="XP" in="" out="">.</W>
<W id="207" msd="AN" tag="AN" in="" out="2:ref">Alle</W>
<W id="208" msd="XP" tag="XP" in="" out="">,</W>
<W id="209" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="210" msd="VA" tag="VA" in="" out="">er</W>
<W id="211" msd="AN" tag="AN" in="" out="">innovative</W>
<W id="212" msd="XP" tag="XP" in="" out="">,</W>
<W id="213" msd="VA" tag="VA" in="" out="">taler</W>
<W id="214" msd="NC" tag="NC" in="" out="">engelsk</W>
<W id="215" msd="XP" tag="XP" in="" out="">,</W>
<W id="216" msd="CC" tag="CC" in="" out="">og</W>
<W id="217" msd="RG" tag="RG" in="" out="">derfor</W>
<W id="218" msd="VA" tag="VA" in="" out="">vil</W>
<W id="219" msd="PP" tag="PP" in="-211:coref" out="46:coref">jeg</W>
<W id="220" msd="VA" tag="VA" in="" out="">gøre</W>
<W id="221" msd="PP" tag="PP" in="" out="">mig</W>
<W id="222" msd="SP" tag="SP" in="" out="">til</W>
<W id="223" msd="AN" tag="AN" in="" out="">stærk</W>
<W id="224" msd="NC" tag="NC" in="" out="">talsmand</W>
<W id="225" msd="SP" tag="SP" in="" out="">for</W>
<W id="226" msd="XP" tag="XP" in="" out="">,</W>
<W id="227" msd="CS" tag="CS" in="" out="">at</W>
<W id="228" msd="PP" tag="PP" in="-103:coref" out="27:coref">vi</W>
<W id="229" msd="RG" tag="RG" in="" out="">nu</W>
<W id="230" msd="VA" tag="VA" in="" out="14:coref-res">får</W>
<W id="231" msd="PI" tag="PI" in="" out="">et</W>
<W id="232" msd="AN" tag="AN" in="" out="">europæisk</W>
<W id="233" msd="NC" tag="NC" in="" out="">patent</W>
<W id="234" msd="SP" tag="SP" in="" out="">med</W>
<W id="235" msd="PI" tag="PI" in="" out="7:coref">ét</W>
<W id="236" msd="NC" tag="NC" in="" out="">sprog</W>
<W id="237" msd="XP" tag="XP" in="" out="">-</W>
<W id="238" msd="NC" tag="NC" in="" out="">engelsk</W>
<W id="239" msd="XP" tag="XP" in="" out="">-</W>
<W id="240" msd="CC" tag="CC" in="" out="">og</W>
<W id="241" msd="RG" tag="RG" in="" out="">kun</W>
<W id="242" msd="PD" tag="PD" in="-7:coref" out="">dette</W>
<W id="243" msd="XP" tag="XP" in="" out="">.</W>
<W id="244" msd="PP" tag="PP" in="-14:coref-res" out="31:coref">Det</W>
<W id="245" msd="VA" tag="VA" in="" out="">vil</W>
<W id="246" msd="VA" tag="VA" in="" out="">øge</W>
<W id="247" msd="NC" tag="NC" in="" out="">konkurrenceevnen</W>
<W id="248" msd="XP" tag="XP" in="" out="">,</W>
<W id="249" msd="VA" tag="VA" in="" out="">være</W>
<W id="250" msd="SP" tag="SP" in="" out="">i</W>
<W id="251" msd="NC" tag="NC" in="" out="">overensstemmelse</W>
<W id="252" msd="SP" tag="SP" in="" out="">med</W>
<W id="253" msd="PD" tag="PD" in="" out="">de</W>
<W id="254" msd="NC" tag="NC" in="0:ref" out="0:ref">udgifter</W>
<W id="255" msd="PP" tag="PP" in="-27:coref" out="">vi</W>
<W id="256" msd="SP" tag="SP" in="" out="">i</W>
<W id="257" msd="AN" tag="AN" in="" out="">alle</W>
<W id="258" msd="NC" tag="NC" in="" out="">tilfælde</W>
<W id="259" msd="VA" tag="VA" in="" out="">skal</W>
<W id="260" msd="VA" tag="VA" in="" out="">afholde</W>
<W id="261" msd="XP" tag="XP" in="" out="">,</W>
<W id="262" msd="CC" tag="CC" in="" out="">og</W>
<W id="263" msd="RG" tag="RG" in="" out="">nu</W>
<W id="264" msd="VE" tag="VE" in="" out="">syntes</W>
<W id="265" msd="PP" tag="PP" in="-46:coref" out="">jeg</W>
<W id="266" msd="XP" tag="XP" in="" out="">,</W>
<W id="267" msd="CS" tag="CS" in="" out="">at</W>
<W id="268" msd="NC" tag="NC" in="-190:coref-iden" out="">Rådet</W>
<W id="269" msd="VA" tag="VA" in="" out="">skal</W>
<W id="270" msd="VA" tag="VA" in="" out="">tage</W>
<W id="271" msd="PP" tag="PP" in="" out="">sig</W>
<W id="272" msd="RG" tag="RG" in="" out="">sammen</W>
<W id="273" msd="CC" tag="CC" in="" out="">og</W>
<W id="274" msd="VA" tag="VA" in="" out="">få</W>
<W id="275" msd="PP" tag="PP" in="-31:coref" out="">det</W>
<W id="276" msd="VA" tag="VA" in="" out="">gennemført</W>
<W id="277" msd="XP" tag="XP" in="" out="">.</W>
</s>
