<s>
<W msd="XA" tag="XA">Fru</W>
<W msd="NC" tag="NC">formand</W>
<W msd="XP" tag="XP">,</W>
<W msd="VA" tag="VA">hr.</W>
<W msd="NC" tag="NC">kommissær</W>
<W msd="CC" tag="CC">og</W>
<W msd="NC" tag="NC">hr.</W>
<W msd="NC" tag="NC">rådsformand</W>
<W msd="XP" tag="XP">,</W>
<W msd="PP" tag="PP">jeg</W>
<W msd="VA" tag="VA">har</W>
<W msd="SP" tag="SP">med</W>
<W msd="NC" tag="NC">glæde</W>
<W msd="VA" tag="VA">lyttet</W>
<W msd="SP" tag="SP">til</W>
<W msd="NC" tag="NC">bemærkningerne</W>
<W msd="SP" tag="SP">om</W>
<W msd="NC" tag="NC">Østersøsamarbejdet</W>
<W msd="XP" tag="XP">.</W>
<W msd="SP" tag="SP">I</W>
<W msd="NC" tag="NC">dag</W>
<W msd="VA" tag="VA">har</W>
<W msd="PP" tag="PP">jeg</W>
<W msd="VA" tag="VA">haft</W>
<W msd="NC" tag="NC">besøg</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">fjernsynsfolk</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">som</W>
<W msd="VA" tag="VA">arbejder</W>
<W msd="AN" tag="AN">meget</W>
<W msd="SP" tag="SP">med</W>
<W msd="NC" tag="NC">mediesamarbejdet</W>
<W msd="RG" tag="RG">ovre</W>
<W msd="VA" tag="VA">østpå</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Vi</W>
<W msd="VA" tag="VA">talte</W>
<W msd="RG" tag="RG">også</W>
<W msd="SP" tag="SP">om</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">kulturelle</W>
<W msd="NC" tag="NC">aspekter</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Jeg</W>
<W msd="VA" tag="VA">vil</W>
<W msd="RG" tag="RG">gerne</W>
<W msd="VA" tag="VA">anbefale</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="PI" tag="PI">man</W>
<W msd="RG" tag="RG">også</W>
<W msd="VA" tag="VA">tager</W>
<W msd="NC" tag="NC">hånd</W>
<W msd="SP" tag="SP">om</W>
<W msd="PD" tag="PD">disse</W>
<W msd="NC" tag="NC">aspekter</W>
<W msd="RG" tag="RG">midt</W>
<W msd="SP" tag="SP">i</W>
<W msd="AN" tag="AN">al</W>
<W msd="NC" tag="NC">diskussionen</W>
<W msd="SP" tag="SP">om</W>
<W msd="NC" tag="NC">økonomi</W>
<W msd="XP" tag="XP">.</W>
</s>
<s>
<W msd="PP" tag="PP">Jeg</W>
<W msd="VE" tag="VE">synes</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="U=" tag="U=">der</W>
<W msd="SP" tag="SP">på</W>
<W msd="PD" tag="PD">denne</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">aften</W>
<W msd="XP" tag="XP">,</W>
<W msd="XA" tag="XA">fru</W>
<W msd="NC" tag="NC">formand</W>
<W msd="XP" tag="XP">,</W>
<W msd="RG" tag="RG">også</W>
<W msd="VA" tag="VA">skal</W>
<W msd="VA" tag="VA">lyde</W>
<W msd="PI" tag="PI">en</W>
<W msd="AN" tag="AN">lille</W>
<W msd="NC" tag="NC">hilsen</W>
<W msd="SP" tag="SP">fra</W>
<W msd="NP" tag="NP">Danmark</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">det</W>
<W msd="NC" tag="NC">kor</W>
<W msd="SP" tag="SP">af</W>
<W msd="NC" tag="NC">stemmer</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">har</W>
<W msd="VA" tag="VA">været</W>
<W msd="RG" tag="RG">fremme</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Jeg</W>
<W msd="VA" tag="VA">bor</W>
<W msd="PD" tag="PD">selv</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">nærheden</W>
<W msd="SP" tag="SP">af</W>
<W msd="PD" tag="PD">den</W>
<W msd="AN" tag="AN">dansk-tyske</W>
<W msd="NC" tag="NC">grænse</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">jo</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="RG" tag="RG">blot</W>
<W msd="NC" tag="NC">grænsen</W>
<W msd="SP" tag="SP">mellem</W>
<W msd="NP" tag="NP">Danmark</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Tyskland</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">også</W>
<W msd="NC" tag="NC">grænsen</W>
<W msd="SP" tag="SP">mellem</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">øvrige</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">lande</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Tyskland</W>
<W msd="XP" tag="XP">.</W>
<W msd="PD" tag="PD">Den</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">pasunion</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">som</W>
<W msd="SP" tag="SP">ifølge</W>
<W msd="PO" tag="PO">min</W>
<W msd="NC" tag="NC">landsmand</W>
<W msd="XP" tag="XP">,</W>
<W msd="NP" tag="NP">Ole</W>
<W msd="NP" tag="NP">Krarup</W>
<W msd="XP" tag="XP">,</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="VA" tag="VA">må</W>
<W msd="VA" tag="VA">hedde</W>
<W msd="RG" tag="RG">således</W>
<W msd="XP" tag="XP">,</W>
<W msd="CC" tag="CC">men</W>
<W msd="VA" tag="VA">bør</W>
<W msd="VA" tag="VA">kaldes</W>
<W msd="PI" tag="PI">et</W>
<W msd="AN" tag="AN">nordisk</W>
<W msd="AN" tag="AN">pasfrit</W>
<W msd="NC" tag="NC">område</W>
<W msd="XP" tag="XP">,</W>
<W msd="VA" tag="VA">er</W>
<W msd="RG" tag="RG">jo</W>
<W msd="RG" tag="RG">ikke</W>
<W msd="RG" tag="RG">blot</W>
<W msd="PI" tag="PI">noget</W>
<W msd="AN" tag="AN">praktisk</W>
<W msd="XP" tag="XP">,</W>
<W msd="PP" tag="PP">det</W>
<W msd="VA" tag="VA">er</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">virkeligheden</W>
<W msd="RG" tag="RG">også</W>
<W msd="PI" tag="PI">et</W>
<W msd="NC" tag="NC">politikum</W>
<W msd="XP" tag="XP">,</W>
<W msd="U=" tag="U=">som</W>
<W msd="VA" tag="VA">siger</W>
<W msd="PI" tag="PI">noget</W>
<W msd="SP" tag="SP">om</W>
<W msd="PD" tag="PD">den</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">sammenhæng</W>
<W msd="CC" tag="CC">og</W>
<W msd="RG" tag="RG">også</W>
<W msd="SP" tag="SP">om</W>
<W msd="PD" tag="PD">den</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">samfølelse</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VE" tag="VE">synes</W>
<W msd="PP" tag="PP">jeg</W>
<W msd="U=" tag="U=">som</W>
<W msd="NC" tag="NC">dansker</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="PP" tag="PP">det</W>
<W msd="VA" tag="VA">er</W>
<W msd="AN" tag="AN">vigtigt</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">pege</W>
<W msd="SP" tag="SP">på</W>
<W msd="RG" tag="RG">midt</W>
<W msd="SP" tag="SP">i</W>
<W msd="AN" tag="AN">alt</W>
<W msd="PD" tag="PD">det</W>
<W msd="AN" tag="AN">europæiske</W>
<W msd="CC" tag="CC">og</W>
<W msd="RG" tag="RG">midt</W>
<W msd="SP" tag="SP">i</W>
<W msd="PD" tag="PD">disse</W>
<W msd="NC" tag="NC">Schengen-tider</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Jeg</W>
<W msd="VA" tag="VA">håber</W>
<W msd="XP" tag="XP">-</W>
<W msd="CC" tag="CC">og</W>
<W msd="PP" tag="PP">jeg</W>
<W msd="VA" tag="VA">glædede</W>
<W msd="PP" tag="PP">mig</W>
<W msd="SP" tag="SP">over</W>
<W msd="XP" tag="XP">,</W>
<W msd="PT" tag="PT">hvad</W>
<W msd="NC" tag="NC">Kommissionen</W>
<W msd="VA" tag="VA">sagde</W>
<W msd="RG" tag="RG">herom</W>
<W msd="XP" tag="XP">-</W>
<W msd="CS" tag="CS">at</W>
<W msd="PP" tag="PP">det</W>
<W msd="VA" tag="VA">vil</W>
<W msd="VE" tag="VE">lykkes</W>
<W msd="SP" tag="SP">for</W>
<W msd="NP" tag="NP">Norge</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Island</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">komme</W>
<W msd="RG" tag="RG">ind</W>
<W msd="SP" tag="SP">i</W>
<W msd="NC" tag="NC">samarbejdet</W>
<W msd="XP" tag="XP">,</W>
<W msd="RG" tag="RG">således</W>
<W msd="CS" tag="CS">at</W>
<W msd="PP" tag="PP">den</W>
<W msd="VA" tag="VA">samlede</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">pasunion</W>
<W msd="VA" tag="VA">reddes</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Vi</W>
<W msd="VA" tag="VA">skal</W>
<W msd="SP" tag="SP">om</W>
<W msd="AN" tag="AN">kort</W>
<W msd="NC" tag="NC">tid</W>
<W msd="SP" tag="SP">med</W>
<W msd="NC" tag="NC">delegationen</W>
<W msd="SP" tag="SP">fra</W>
<W msd="NC" tag="NC">Europa-Parlamentet</W>
<W msd="SP" tag="SP">til</W>
<W msd="NP" tag="NP">Norge</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Island</W>
<W msd="XP" tag="XP">.</W>
<W msd="PP" tag="PP">Det</W>
<W msd="VA" tag="VA">kunne</W>
<W msd="VA" tag="VA">være</W>
<W msd="AN" tag="AN">flot</W>
<W msd="CC" tag="CC">og</W>
<W msd="AN" tag="AN">godt</W>
<W msd="SP" tag="SP">i</W>
<W msd="NP" tag="NP">Oslo</W>
<W msd="CC" tag="CC">og</W>
<W msd="NP" tag="NP">Reykjavik</W>
<W msd="U=" tag="U=">at</W>
<W msd="VA" tag="VA">kunne</W>
<W msd="VA" tag="VA">sige</W>
<W msd="SP" tag="SP">fra</W>
<W msd="NC" tag="NC">Europa-Parlamentet</W>
<W msd="XP" tag="XP">-</W>
<W msd="CC" tag="CC">og</W>
<W msd="RG" tag="RG">sådan</W>
<W msd="VA" tag="VA">har</W>
<W msd="PP" tag="PP">jeg</W>
<W msd="RG" tag="RG">også</W>
<W msd="VA" tag="VA">forstået</W>
<W msd="NC" tag="NC">kommissæren</W>
<W msd="XP" tag="XP">-</W>
<W msd="CS" tag="CS">at</W>
<W msd="U=" tag="U=">der</W>
<W msd="VA" tag="VA">er</W>
<W msd="PD" tag="PD">de</W>
<W msd="AN" tag="AN">bedste</W>
<W msd="NC" tag="NC">muligheder</W>
<W msd="SP" tag="SP">for</W>
<W msd="XP" tag="XP">,</W>
<W msd="CS" tag="CS">at</W>
<W msd="PP" tag="PP">den</W>
<W msd="VA" tag="VA">samlede</W>
<W msd="AN" tag="AN">nordiske</W>
<W msd="NC" tag="NC">pasunion</W>
<W msd="VA" tag="VA">overlever</W>
<W msd="RG" tag="RG">inden</W>
<W msd="SP" tag="SP">for</W>
<W msd="NC" tag="NC">ordningen</W>
<W msd="SP" tag="SP">i</W>
<W msd="NP" tag="NP">Europa</W>
<W msd="XP" tag="XP">.</W>
</s>
