<s>
<W id="1" msd="NP" tag="NP" in="" out="">Hr.</W>
<W id="2" msd="NC" tag="NC" in="" out="">formand</W>
<W id="3" msd="XP" tag="XP" in="" out="">,</W>
<W id="4" msd="VA" tag="VA" in="" out="">lad</W>
<W id="5" msd="PP" tag="PP" in="" out="11:coref">mig</W>
<W id="6" msd="VA" tag="VA" in="" out="">indlede</W>
<W id="7" msd="SP" tag="SP" in="" out="">med</W>
<W id="8" msd="U=" tag="U=" in="" out="">at</W>
<W id="9" msd="VA" tag="VA" in="" out="">takke</W>
<W id="10" msd="NC" tag="NC" in="0:assoc-frame" out="0:assoc-frame">ordføreren</W>
<W id="11" msd="SP" tag="SP" in="" out="">for</W>
<W id="12" msd="NC" tag="NC" in="" out="">samarbejdet</W>
<W id="13" msd="XP" tag="XP" in="" out="">.</W>
<W id="14" msd="AN" tag="AN" in="" out="">Specielt</W>
<W id="15" msd="VA" tag="VA" in="" out="">har</W>
<W id="16" msd="PP" tag="PP" in="-11:coref" out="22:coref">jeg</W>
<W id="17" msd="VA" tag="VA" in="" out="">været</W>
<W id="18" msd="AN" tag="AN" in="" out="">meget</W>
<W id="19" msd="AN" tag="AN" in="" out="">glad</W>
<W id="20" msd="SP" tag="SP" in="" out="">for</W>
<W id="21" msd="PD" tag="PD" in="" out="">den</W>
<W id="22" msd="NC" tag="NC" in="" out="2:ref">opbakning</W>
<W id="23" msd="XP" tag="XP" in="" out="">,</W>
<W id="24" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="25" msd="VA" tag="VA" in="" out="">har</W>
<W id="26" msd="VA" tag="VA" in="" out="">været</W>
<W id="27" msd="SP" tag="SP" in="" out="">til</W>
<W id="28" msd="PI" tag="PI" in="" out="">en</W>
<W id="29" msd="NC" tag="NC" in="" out="">række</W>
<W id="30" msd="NC" tag="NC" in="" out="2:ref">ændringsforslag</W>
<W id="31" msd="XP" tag="XP" in="" out="">,</W>
<W id="32" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="33" msd="PP" tag="PP" in="0:assoc-frame" out="11:coref|0:assoc-frame">vi</W>
<W id="34" msd="VA" tag="VA" in="" out="">har</W>
<W id="35" msd="VA" tag="VA" in="" out="">stillet</W>
<W id="36" msd="XP" tag="XP" in="" out="">,</W>
<W id="37" msd="CC" tag="CC" in="" out="">og</W>
<W id="38" msd="PP" tag="PP" in="-22:coref" out="121:coref">jeg</W>
<W id="39" msd="VA" tag="VA" in="" out="">er</W>
<W id="40" msd="AN" tag="AN" in="" out="">glad</W>
<W id="41" msd="SP" tag="SP" in="" out="">for</W>
<W id="42" msd="XP" tag="XP" in="" out="">,</W>
<W id="43" msd="CS" tag="CS" in="" out="">at</W>
<W id="44" msd="PP" tag="PP" in="-11:coref" out="86:coref">vi</W>
<W id="45" msd="VA" tag="VA" in="" out="">er</W>
<W id="46" msd="AN" tag="AN" in="" out="">enige</W>
<W id="47" msd="SP" tag="SP" in="" out="">om</W>
<W id="48" msd="PI" tag="PI" in="" out="">en</W>
<W id="49" msd="NC" tag="NC" in="" out="2:ref">linje</W>
<W id="50" msd="XP" tag="XP" in="" out="">,</W>
<W id="51" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="52" msd="VA" tag="VA" in="" out="">går</W>
<W id="53" msd="SP" tag="SP" in="" out="">på</W>
<W id="54" msd="U=" tag="U=" in="" out="">at</W>
<W id="55" msd="VA" tag="VA" in="" out="">få</W>
<W id="56" msd="VA" tag="VA" in="" out="">placeret</W>
<W id="57" msd="NC" tag="NC" in="" out="">ansvaret</W>
<W id="58" msd="SP" tag="SP" in="" out="">i</W>
<W id="59" msd="NC" tag="NC" in="0:assoc-frame" out="16:coref-iden|0:assoc-frame">Kommissionen</W>
<W id="60" msd="CC" tag="CC" in="" out="">og</W>
<W id="61" msd="VA" tag="VA" in="" out="">undlade</W>
<W id="62" msd="U=" tag="U=" in="" out="">at</W>
<W id="63" msd="VA" tag="VA" in="" out="">»</W>
<W id="64" msd="VA" tag="VA" in="" out="">pinpointe</W>
<W id="65" msd="XX" tag="XX" in="" out="">«</W>
<W id="66" msd="AN" tag="AN" in="" out="">bestemte</W>
<W id="67" msd="NC" tag="NC" in="" out="">embedsmænd</W>
<W id="68" msd="XP" tag="XP" in="" out="">,</W>
<W id="69" msd="CC" tag="CC" in="" out="">men</W>
<W id="70" msd="VA" tag="VA" in="" out="">kræve</W>
<W id="71" msd="XP" tag="XP" in="" out="">,</W>
<W id="72" msd="CS" tag="CS" in="" out="">at</W>
<W id="73" msd="PP" tag="PP" in="" out="">det</W>
<W id="74" msd="VA" tag="VA" in="" out="">er</W>
<W id="75" msd="NC" tag="NC" in="-16:coref-iden" out="2:ref|18:coref-iden">Kommissionen</W>
<W id="76" msd="XP" tag="XP" in="" out="">,</W>
<W id="77" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="78" msd="VA" tag="VA" in="" out="">påtager</W>
<W id="79" msd="PP" tag="PP" in="" out="">sig</W>
<W id="80" msd="PD" tag="PD" in="" out="">det</W>
<W id="81" msd="AN" tag="AN" in="" out="">politiske</W>
<W id="82" msd="NC" tag="NC" in="" out="">ansvar</W>
<W id="83" msd="SP" tag="SP" in="" out="">for</W>
<W id="84" msd="NC" tag="NC" in="" out="">situationen</W>
<W id="85" msd="XP" tag="XP" in="" out="">.</W>
<W id="86" msd="PP" tag="PP" in="" out="">Det</W>
<W id="87" msd="VA" tag="VA" in="" out="">må</W>
<W id="88" msd="RG" tag="RG" in="" out="">nemlig</W>
<W id="89" msd="VA" tag="VA" in="" out="">være</W>
<W id="90" msd="RG" tag="RG" in="" out="">sådan</W>
<W id="91" msd="XP" tag="XP" in="" out="">,</W>
<W id="92" msd="CS" tag="CS" in="" out="">at</W>
<W id="93" msd="NC" tag="NC" in="-18:coref-iden" out="10:coref">Kommissionen</W>
<W id="94" msd="RG" tag="RG" in="" out="">hverken</W>
<W id="95" msd="VA" tag="VA" in="" out="">må</W>
<W id="96" msd="VA" tag="VA" in="" out="">dække</W>
<W id="97" msd="SP" tag="SP" in="" out="">over</W>
<W id="98" msd="NC" tag="NC" in="" out="">embedsmænd</W>
<W id="99" msd="CC" tag="CC" in="" out="">eller</W>
<W id="100" msd="VA" tag="VA" in="" out="">skubbe</W>
<W id="101" msd="NC" tag="NC" in="" out="">embedsmænd</W>
<W id="102" msd="SP" tag="SP" in="" out="">foran</W>
<W id="103" msd="PP" tag="PP" in="-10:coref" out="6:coref">sig</W>
<W id="104" msd="XP" tag="XP" in="" out="">,</W>
<W id="105" msd="CC" tag="CC" in="" out="">men</W>
<W id="106" msd="RG" tag="RG" in="" out="">netop</W>
<W id="107" msd="RG" tag="RG" in="" out="">selv</W>
<W id="108" msd="VA" tag="VA" in="" out="">påtage</W>
<W id="109" msd="PP" tag="PP" in="-6:coref" out="81:coref-var">sig</W>
<W id="110" msd="NC" tag="NC" in="" out="">ansvaret</W>
<W id="111" msd="SP" tag="SP" in="" out="">for</W>
<W id="112" msd="XP" tag="XP" in="" out="">,</W>
<W id="113" msd="CS" tag="CS" in="" out="">at</W>
<W id="114" msd="NC" tag="NC" in="" out="4:coref">tingene</W>
<W id="115" msd="VA" tag="VA" in="" out="">er</W>
<W id="116" msd="XP" tag="XP" in="" out="">,</W>
<W id="117" msd="U=" tag="U=" in="" out="">som</W>
<W id="118" msd="PP" tag="PP" in="-4:coref" out="">de</W>
<W id="119" msd="VA" tag="VA" in="" out="">er</W>
<W id="120" msd="XP" tag="XP" in="" out="">.</W>
</s>
<s>
<W id="123" msd="PP" tag="PP" in="" out="">Det</W>
<W id="124" msd="VA" tag="VA" in="" out="">er</W>
<W id="125" msd="PI" tag="PI" in="" out="21:coref-iden.sb">en</W>
<W id="126" msd="RG" tag="RG" in="" out="">ganske</W>
<W id="127" msd="AN" tag="AN" in="" out="">alvorlig</W>
<W id="128" msd="NC" tag="NC" in="" out="1:ref">sag</W>
<W id="129" msd="XP" tag="XP" in="-1:ref" out="">,</W>
<W id="130" msd="PP" tag="PP" in="-86:coref" out="8:coref">vi</W>
<W id="131" msd="VA" tag="VA" in="" out="">arbejder</W>
<W id="132" msd="RG" tag="RG" in="" out="">med</W>
<W id="133" msd="SP" tag="SP" in="" out="">i</W>
<W id="134" msd="NC" tag="NC" in="" out="">dag</W>
<W id="135" msd="XP" tag="XP" in="" out="">.</W>
<W id="136" msd="RG" tag="RG" in="" out="">Hvor</W>
<W id="137" msd="VA" tag="VA" in="" out="">har</W>
<W id="138" msd="PP" tag="PP" in="-8:coref" out="12:coref">vi</W>
<W id="139" msd="VA" tag="VA" in="" out="">brugt</W>
<W id="140" msd="AN" tag="AN" in="" out="">mange</W>
<W id="141" msd="NC" tag="NC" in="" out="8:ref">kræfter</W>
<W id="142" msd="CC" tag="CC" in="" out="">og</W>
<W id="143" msd="AN" tag="AN" in="" out="">mange</W>
<W id="144" msd="NC" tag="NC" in="" out="">timer</W>
<W id="145" msd="SP" tag="SP" in="" out="">på</W>
<W id="146" msd="PD" tag="PD" in="-21:coref-iden.sb" out="36:coref-iden">denne</W>
<W id="147" msd="NC" tag="NC" in="" out="">sag</W>
<W id="148" msd="XP" tag="XP" in="" out="">,</W>
<W id="149" msd="U=" tag="U=" in="-8:ref" out="">som</W>
<W id="150" msd="PP" tag="PP" in="-12:coref" out="25:coref">vi</W>
<W id="151" msd="RG" tag="RG" in="" out="">hellere</W>
<W id="152" msd="VA" tag="VA" in="" out="">ville</W>
<W id="153" msd="VA" tag="VA" in="" out="">have</W>
<W id="154" msd="VA" tag="VA" in="" out="">brugt</W>
<W id="155" msd="SP" tag="SP" in="" out="">på</W>
<W id="156" msd="PI" tag="PI" in="" out="">andre</W>
<W id="157" msd="NC" tag="NC" in="" out="">ting</W>
<W id="158" msd="XP" tag="XP" in="" out="">!</W>
<W id="159" msd="PP" tag="PP" in="-121:coref" out="66:coref">Jeg</W>
<W id="160" msd="VA" tag="VA" in="" out="">må</W>
<W id="161" msd="VA" tag="VA" in="" out="">beklage</W>
<W id="162" msd="PD" tag="PD" in="" out="">det</W>
<W id="163" msd="NC" tag="NC" in="" out="2:ref">forløb</W>
<W id="164" msd="XP" tag="XP" in="" out="">,</W>
<W id="165" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="166" msd="VA" tag="VA" in="" out="">har</W>
<W id="167" msd="VA" tag="VA" in="" out="">været</W>
<W id="168" msd="XP" tag="XP" in="" out="">,</W>
<W id="169" msd="CC" tag="CC" in="" out="">for</W>
<W id="170" msd="NC" tag="NC" in="" out="">sagen</W>
<W id="171" msd="VA" tag="VA" in="" out="">er</W>
<W id="172" msd="RG" tag="RG" in="" out="">jo</W>
<W id="173" msd="XP" tag="XP" in="" out="">,</W>
<W id="174" msd="CS" tag="CS" in="" out="">at</W>
<W id="175" msd="PP" tag="PP" in="-25:coref" out="29:coref">vi</W>
<W id="176" msd="SP" tag="SP" in="" out="">med</W>
<W id="177" msd="PD" tag="PD" in="0:assoc-frame" out="73:coref-iden|0:assoc-frame">denne</W>
<W id="178" msd="NC" tag="NC" in="" out="">betænkning</W>
<W id="179" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="180" msd="VA" tag="VA" in="" out="">kan</W>
<W id="181" msd="VA" tag="VA" in="" out="">afslutte</W>
<W id="182" msd="NC" tag="NC" in="-36:coref-iden" out="176:coref-iden">sagen</W>
<W id="183" msd="XP" tag="XP" in="" out="">,</W>
<W id="184" msd="CC" tag="CC" in="" out="">men</W>
<W id="185" msd="RG" tag="RG" in="" out="">endnu</W>
<W id="186" msd="PI" tag="PI" in="" out="">en</W>
<W id="187" msd="NC" tag="NC" in="" out="">gang</W>
<W id="188" msd="VA" tag="VA" in="" out="">må</W>
<W id="189" msd="VA" tag="VA" in="" out="">opfordre</W>
<W id="190" msd="NC" tag="NC" in="-81:coref-var" out="22:coref-iden">Kommissionen</W>
<W id="191" msd="SP" tag="SP" in="" out="">til</W>
<W id="192" msd="U=" tag="U=" in="" out="">at</W>
<W id="193" msd="VA" tag="VA" in="" out="">tage</W>
<W id="194" msd="NC" tag="NC" in="" out="">initiativer</W>
<W id="195" msd="CC" tag="CC" in="" out="">og</W>
<W id="196" msd="RG" tag="RG" in="" out="">endnu</W>
<W id="197" msd="PI" tag="PI" in="" out="">en</W>
<W id="198" msd="NC" tag="NC" in="" out="">gang</W>
<W id="199" msd="VA" tag="VA" in="" out="">må</W>
<W id="200" msd="VA" tag="VA" in="" out="">meddele</W>
<W id="201" msd="XP" tag="XP" in="" out="">,</W>
<W id="202" msd="PT" tag="PT" in="" out="">hvilke</W>
<W id="203" msd="NC" tag="NC" in="0:ref" out="0:ref">skridt</W>
<W id="204" msd="PP" tag="PP" in="-29:coref" out="14:coref">vi</W>
<W id="205" msd="VA" tag="VA" in="" out="">må</W>
<W id="206" msd="VA" tag="VA" in="" out="">tage</W>
<W id="207" msd="SP" tag="SP" in="" out="">fra</W>
<W id="208" msd="NC" tag="NC" in="84:coref-iden|0:assoc-frame" out="0:assoc-frame">Parlamentets</W>
<W id="209" msd="NC" tag="NC" in="" out="">side</W>
<W id="210" msd="XP" tag="XP" in="" out="">,</W>
<W id="211" msd="CS" tag="CS" in="" out="">hvis</W>
<W id="212" msd="NC" tag="NC" in="-22:coref-iden" out="30:coref-iden">Kommissionen</W>
<W id="213" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="214" msd="VA" tag="VA" in="" out="">efterkommer</W>
<W id="215" msd="PD" tag="PD" in="" out="">de</W>
<W id="216" msd="NC" tag="NC" in="" out="1:ref">krav</W>
<W id="217" msd="XP" tag="XP" in="-1:ref" out="">,</W>
<W id="218" msd="PP" tag="PP" in="-14:coref" out="12:coref">vi</W>
<W id="219" msd="VA" tag="VA" in="" out="">stiller</W>
<W id="220" msd="XP" tag="XP" in="" out="">.</W>
</s>
<s>
<W id="223" msd="RG" tag="RG" in="" out="">Derfor</W>
<W id="224" msd="VA" tag="VA" in="" out="">vil</W>
<W id="225" msd="PP" tag="PP" in="-66:coref" out="122:coref">jeg</W>
<W id="226" msd="VA" tag="VA" in="" out="">spørge</W>
<W id="227" msd="NC" tag="NC" in="0:assoc-frame" out="0:assoc-frame">kommissæren</W>
<W id="228" msd="XP" tag="XP" in="" out="">,</W>
<W id="229" msd="CS" tag="CS" in="" out="">om</W>
<W id="230" msd="PP" tag="PP" in="-12:coref" out="33:coref">vi</W>
<W id="231" msd="RG" tag="RG" in="" out="">allerede</W>
<W id="232" msd="SP" tag="SP" in="" out="">i</W>
<W id="233" msd="NC" tag="NC" in="" out="">dag</W>
<W id="234" msd="VA" tag="VA" in="" out="">kan</W>
<W id="235" msd="VA" tag="VA" in="" out="">få</W>
<W id="236" msd="PI" tag="PI" in="" out="">et</W>
<W id="237" msd="AN" tag="AN" in="" out="">klart</W>
<W id="238" msd="NC" tag="NC" in="" out="">svar</W>
<W id="239" msd="SP" tag="SP" in="" out="">på</W>
<W id="240" msd="XP" tag="XP" in="" out="">,</W>
<W id="241" msd="CS" tag="CS" in="" out="">hvorvidt</W>
<W id="242" msd="NC" tag="NC" in="-30:coref-iden" out="163:coref-iden">Kommissionen</W>
<W id="243" msd="VA" tag="VA" in="" out="">vil</W>
<W id="244" msd="VA" tag="VA" in="" out="">følge</W>
<W id="245" msd="RG" tag="RG" in="" out="">op</W>
<W id="246" msd="SP" tag="SP" in="" out="">på</W>
<W id="247" msd="NC" tag="NC" in="" out="">punkt</W>
<W id="248" msd="AC" tag="AC" in="" out="">3</W>
<W id="249" msd="SP" tag="SP" in="" out="">i</W>
<W id="250" msd="NC" tag="NC" in="-73:coref-iden" out="">betænkningen</W>
<W id="251" msd="CC" tag="CC" in="" out="">og</W>
<W id="252" msd="VA" tag="VA" in="" out="">tage</W>
<W id="253" msd="PD" tag="PD" in="" out="">de</W>
<W id="254" msd="AN" tag="AN" in="" out="">konkrete</W>
<W id="255" msd="NC" tag="NC" in="" out="2:ref">initiativer</W>
<W id="256" msd="XP" tag="XP" in="" out="">,</W>
<W id="257" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="258" msd="VA" tag="VA" in="" out="">bliver</W>
<W id="259" msd="VA" tag="VA" in="" out="">bedt</W>
<W id="260" msd="SP" tag="SP" in="" out="">om</W>
<W id="261" msd="XP" tag="XP" in="" out="">.</W>
<W id="262" msd="VA" tag="VA" in="" out="">Lad</W>
<W id="263" msd="PP" tag="PP" in="-33:coref" out="92:coref">os</W>
<W id="264" msd="RG" tag="RG" in="" out="">allerede</W>
<W id="265" msd="SP" tag="SP" in="" out="">i</W>
<W id="266" msd="NC" tag="NC" in="" out="">dag</W>
<W id="267" msd="VA" tag="VA" in="" out="">få</W>
<W id="268" msd="NC" tag="NC" in="" out="">klarhed</W>
<W id="269" msd="SP" tag="SP" in="" out="">over</W>
<W id="270" msd="XP" tag="XP" in="" out="">,</W>
<W id="271" msd="CS" tag="CS" in="" out="">om</W>
<W id="272" msd="PI" tag="PI" in="" out="">man</W>
<W id="273" msd="VA" tag="VA" in="" out="">er</W>
<W id="274" msd="AN" tag="AN" in="" out="">parat</W>
<W id="275" msd="SP" tag="SP" in="" out="">til</W>
<W id="276" msd="PP" tag="PP" in="" out="">det</W>
<W id="277" msd="XP" tag="XP" in="" out="">,</W>
<W id="278" msd="CC" tag="CC" in="" out="">eller</W>
<W id="279" msd="CS" tag="CS" in="" out="">om</W>
<W id="280" msd="PI" tag="PI" in="" out="">man</W>
<W id="281" msd="RG" tag="RG" in="" out="">bare</W>
<W id="282" msd="VA" tag="VA" in="" out="">vil</W>
<W id="283" msd="VA" tag="VA" in="" out="">blæse</W>
<W id="284" msd="AN" tag="AN" in="" out="">højt</W>
<W id="285" msd="CC" tag="CC" in="" out="">og</W>
<W id="286" msd="AN" tag="AN" in="" out="">flot</W>
<W id="287" msd="SP" tag="SP" in="" out="">på</W>
<W id="288" msd="PD" tag="PD" in="" out="">de</W>
<W id="289" msd="NC" tag="NC" in="" out="2:ref">henstillinger</W>
<W id="290" msd="XP" tag="XP" in="" out="">,</W>
<W id="291" msd="U=" tag="U=" in="-2:ref" out="">som</W>
<W id="292" msd="NC" tag="NC" in="" out="-84:coref-iden">Parlamentet</W>
<W id="293" msd="VA" tag="VA" in="" out="">kommer</W>
<W id="294" msd="RG" tag="RG" in="" out="">med</W>
<W id="295" msd="XP" tag="XP" in="" out="">.</W>
<W id="296" msd="CS" tag="CS" in="" out="">Hvis</W>
<W id="297" msd="U=" tag="U=" in="" out="">der</W>
<W id="298" msd="VA" tag="VA" in="" out="">er</W>
<W id="299" msd="PI" tag="PI" in="" out="2:ref">noget</W>
<W id="300" msd="XP" tag="XP" in="" out="">,</W>
<W id="301" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="302" msd="VA" tag="VA" in="" out="">kan</W>
<W id="303" msd="VA" tag="VA" in="" out="">rokke</W>
<W id="304" msd="SP" tag="SP" in="" out="">ved</W>
<W id="305" msd="NP" tag="NP" in="" out="">EU-borgeres</W>
<W id="306" msd="NC" tag="NC" in="" out="">tillid</W>
<W id="307" msd="SP" tag="SP" in="" out="">til</W>
<W id="308" msd="NC" tag="NC" in="" out="17:assoc-const">EU-systemet</W>
<W id="309" msd="XP" tag="XP" in="" out="">,</W>
<W id="310" msd="RG" tag="RG" in="" out="">så</W>
<W id="311" msd="VA" tag="VA" in="" out="">er</W>
<W id="312" msd="PP" tag="PP" in="" out="">det</W>
<W id="313" msd="RG" tag="RG" in="" out="">netop</W>
<W id="314" msd="NC" tag="NC" in="" out="">mistanke</W>
<W id="315" msd="SP" tag="SP" in="" out="">om</W>
<W id="316" msd="XP" tag="XP" in="" out="">,</W>
<W id="317" msd="CS" tag="CS" in="" out="">at</W>
<W id="318" msd="AN" tag="AN" in="" out="">visse</W>
<W id="319" msd="NC" tag="NC" in="" out="">ting</W>
<W id="320" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="321" msd="VA" tag="VA" in="" out="">er</W>
<W id="322" msd="SP" tag="SP" in="" out="">i</W>
<W id="323" msd="NC" tag="NC" in="" out="">overensstemmelse</W>
<W id="324" msd="SP" tag="SP" in="" out="">med</W>
<W id="325" msd="NC" tag="NC" in="-17:assoc-const" out="">reglerne</W>
<W id="326" msd="XP" tag="XP" in="" out="">,</W>
<W id="327" msd="CS" tag="CS" in="" out="">at</W>
<W id="328" msd="U=" tag="U=" in="" out="">der</W>
<W id="329" msd="VA" tag="VA" in="" out="">foregår</W>
<W id="330" msd="NC" tag="NC" in="" out="">uregelmæssigheder</W>
<W id="331" msd="XP" tag="XP" in="" out="">,</W>
<W id="332" msd="CC" tag="CC" in="" out="">eller</W>
<W id="333" msd="CS" tag="CS" in="" out="">at</W>
<W id="334" msd="U=" tag="U=" in="" out="">der</W>
<W id="335" msd="VA" tag="VA" in="" out="">bliver</W>
<W id="336" msd="VA" tag="VA" in="" out="">dækket</W>
<W id="337" msd="SP" tag="SP" in="" out="">over</W>
<W id="338" msd="AN" tag="AN" in="" out="">visse</W>
<W id="339" msd="NC" tag="NC" in="" out="">personer</W>
<W id="340" msd="XP" tag="XP" in="" out="">.</W>
<W id="341" msd="RG" tag="RG" in="" out="">Derfor</W>
<W id="342" msd="XP" tag="XP" in="" out="">,</W>
<W id="343" msd="VA" tag="VA" in="" out="">hr.</W>
<W id="344" msd="NC" tag="NC" in="" out="">kommissær</W>
<W id="345" msd="XP" tag="XP" in="" out="">,</W>
<W id="346" msd="VA" tag="VA" in="" out="">kan</W>
<W id="347" msd="PP" tag="PP" in="-122:coref" out="">jeg</W>
<W id="348" msd="RG" tag="RG" in="" out="">ikke</W>
<W id="349" msd="AN" tag="AN" in="" out="">kraftigt</W>
<W id="350" msd="RG" tag="RG" in="" out="">nok</W>
<W id="351" msd="VA" tag="VA" in="" out="">opfordre</W>
<W id="352" msd="SP" tag="SP" in="" out="">til</W>
<W id="353" msd="XP" tag="XP" in="" out="">,</W>
<W id="354" msd="CS" tag="CS" in="" out="">at</W>
<W id="355" msd="PP" tag="PP" in="-92:coref" out="8:coref">vi</W>
<W id="356" msd="VA" tag="VA" in="" out="">får</W>
<W id="357" msd="VA" tag="VA" in="" out="">afsluttet</W>
<W id="358" msd="PD" tag="PD" in="-176:coref-iden" out="">denne</W>
<W id="359" msd="NC" tag="NC" in="" out="">sag</W>
<W id="360" msd="XP" tag="XP" in="" out="">,</W>
<W id="361" msd="CC" tag="CC" in="" out="">og</W>
<W id="362" msd="CS" tag="CS" in="" out="">at</W>
<W id="363" msd="PP" tag="PP" in="-8:coref" out="10:coref">vi</W>
<W id="364" msd="VA" tag="VA" in="" out="">får</W>
<W id="365" msd="VA" tag="VA" in="" out="">taget</W>
<W id="366" msd="PD" tag="PD" in="" out="">de</W>
<W id="367" msd="AN" tag="AN" in="" out="">nødvendige</W>
<W id="368" msd="NC" tag="NC" in="" out="">initiativer</W>
<W id="369" msd="XP" tag="XP" in="" out="">,</W>
<W id="370" msd="RG" tag="RG" in="" out="">sådan</W>
<W id="371" msd="RG" tag="RG" in="" out="">så</W>
<W id="372" msd="CS" tag="CS" in="" out="">at</W>
<W id="373" msd="PP" tag="PP" in="-10:coref" out="">vi</W>
<W id="374" msd="AN" tag="AN" in="" out="">alle</W>
<W id="375" msd="RG" tag="RG" in="" out="">sammen</W>
<W id="376" msd="AN" tag="AN" in="" out="">ærligt</W>
<W id="377" msd="VA" tag="VA" in="" out="">kan</W>
<W id="378" msd="VA" tag="VA" in="" out="">gå</W>
<W id="379" msd="RG" tag="RG" in="" out="">ud</W>
<W id="380" msd="CC" tag="CC" in="" out="">og</W>
<W id="381" msd="VA" tag="VA" in="" out="">sige</W>
<W id="382" msd="XP" tag="XP" in="" out="">,</W>
<W id="383" msd="CS" tag="CS" in="" out="">at</W>
<W id="384" msd="RG" tag="RG" in="" out="">nu</W>
<W id="385" msd="VA" tag="VA" in="" out="">er</W>
<W id="386" msd="U=" tag="U=" in="" out="">der</W>
<W id="387" msd="VA" tag="VA" in="" out="">blevet</W>
<W id="388" msd="VA" tag="VA" in="" out="">rettet</W>
<W id="389" msd="RG" tag="RG" in="" out="">op</W>
<W id="390" msd="SP" tag="SP" in="" out="">på</W>
<W id="391" msd="NC" tag="NC" in="" out="">fejlene</W>
<W id="392" msd="CC" tag="CC" in="" out="">og</W>
<W id="393" msd="NC" tag="NC" in="" out="">manglerne</W>
<W id="394" msd="CC" tag="CC" in="" out="">og</W>
<W id="395" msd="SP" tag="SP" in="" out="">på</W>
<W id="396" msd="PD" tag="PD" in="" out="">de</W>
<W id="397" msd="NC" tag="NC" in="" out="2:ref">procedurer</W>
<W id="398" msd="XP" tag="XP" in="" out="">,</W>
<W id="399" msd="U=" tag="U=" in="-2:ref" out="">der</W>
<W id="400" msd="VA" tag="VA" in="" out="">er</W>
<W id="401" msd="AN" tag="AN" in="" out="">nødvendige</W>
<W id="402" msd="SP" tag="SP" in="" out="">for</W>
<W id="403" msd="XP" tag="XP" in="" out="">,</W>
<W id="404" msd="CS" tag="CS" in="" out="">at</W>
<W id="405" msd="NC" tag="NC" in="-163:coref-iden" out="5:coref">Kommissionen</W>
<W id="406" msd="VA" tag="VA" in="" out="">kan</W>
<W id="407" msd="VA" tag="VA" in="" out="">leve</W>
<W id="408" msd="RG" tag="RG" in="" out="">op</W>
<W id="409" msd="SP" tag="SP" in="" out="">til</W>
<W id="410" msd="PO" tag="PO" in="-5:coref" out="">sit</W>
<W id="411" msd="NC" tag="NC" in="" out="">ansvar</W>
<W id="412" msd="XP" tag="XP" in="" out="">.</W>
</s>
