<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="1:nobj">Der</W>
<W lemma="Dom" msd="NC" tag="NN" in="-1:nobj" out="">Dom</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Roskilde</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-4:subj|-2:loc|1:preds|3:pnct">ist</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-1:preds" out="1:nobj">am</W>
<W lemma="12" msd="AC" tag="CARD" in="-1:nobj" out="">12</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="November" msd="NC" tag="NN" in="" out="1:nobj">November</W>
<W lemma="Rahmen" msd="NC" tag="NN" in="-1:nobj" out="">Rahmen</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="1:nobj|4:pnct|13:relr|14:pnct">einer</W>
<W lemma="Reihe" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Reihe</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">von</W>
<W lemma="Konzert" msd="NC" tag="NN" in="-1:nobj" out="">Konzerten</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="8:dobj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:dobj" out="1:attr|2:nobj|4:appr">die</W>
<W lemma="norwegisch" msd="AN" tag="ADJA" in="-1:attr" out="">norwegische</W>
<W lemma="Sängerin" msd="NC" tag="NN" in="-2:nobj" out="">Sängerin</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="1:namef" out="">Sissel</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-4:appr" out="-1:namef">Kyrkjebø</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="Dänemark" msd="NP" tag="NE" in="-1:nobj" out="">Dänemark</W>
<W lemma="geben" msd="VA" tag="VVFIN" in="-13:relr" out="-8:dobj|-7:dobj|-2:loc">gibt</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="1:namef" out="">Sissel</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="4:subj" out="-1:namef|1:pnct">Kyrkjebø</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="15:subj" out="">die</W>
<W lemma="vor" msd="SP" tag="APPR" in="14:time" out="1:nobj">vor</W>
<W lemma="zwei" msd="AC" tag="CARD" in="-1:nobj" out="-4:subj|1:nobj">zwei</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahren</W>
<W lemma="mehr" msd="RG" tag="ADV" in="11:dobj" out="1:pobj">mehr</W>
<W lemma="als" msd="CS" tag="KOKOM" in="-1:pobj" out="1:nobj">als</W>
<W lemma="20" msd="AC" tag="CARD" in="-1:nobj" out="1:+">20</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:+" out="1:nobj">000</W>
<W lemma="Zuhörer" msd="NC" tag="NN" in="-1:nobj" out="">Zuhörer</W>
<W lemma="in" msd="SP" tag="APPR" in="6:man" out="2:nobj">in</W>
<W lemma="ausverkauft" msd="AN" tag="ADJA" in="1:attr" out="">ausverkaufte</W>
<W lemma="Konzert" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Konzerte</W>
<W lemma="in" msd="SP" tag="APPR" in="3:man" out="2:nobj">in</W>
<W lemma="groß" msd="AN" tag="ADJA" in="1:attr" out="">großen</W>
<W lemma="Konzertsäle" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Konzertsälen</W>
<W lemma="ziehen" msd="VA" tag="VVFIN" in="2:qobj" out="-15:subj|-14:time|-11:dobj|-6:man|-3:man|1:pnct">zog</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="zeihen&7c;ziehen" msd="VA" tag="VVFIN" in="" out="-2:qobj|1:subj|2:dobj|4:part|5:pnct|9:dobj|10:pnct">zieht</W>
<W lemma="es" msd="PP" tag="PPER" in="-1:subj" out="">es</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-2:dobj" out="1:nobj">dieses</W>
<W lemma="Mal" msd="NC" tag="NN" in="-1:nobj" out="">Mal</W>
<W lemma="vor" msd="RG" tag="PTKVZ" in="-4:part" out="">vor</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="nur" msd="RG" tag="ADV" in="1:focal" out="">nur</W>
<W lemma="in" msd="SP" tag="APPR" in="2:man" out="-1:focal|1:nobj">in</W>
<W lemma="Kirche" msd="NC" tag="NN" in="-1:nobj" out="">Kirchen</W>
<W lemma="auftreten" msd="VAF" tag="VVIZU" in="-9:dobj" out="-2:man">aufzutreten</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
<W lemma="d" msd="PP" tag="PDS" in="1:subj" out="">Das</W>
<W lemma="bedeuten" msd="VA" tag="VVFIN" in="" out="-1:subj|1:pnct|2:dobj|14:pnct">bedeutet</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="7:vobj">dass</W>
<W lemma="wesentlich" msd="AN" tag="ADJD" in="1:quant" out="">wesentlich</W>
<W lemma="wenig" msd="PI" tag="PIAT" in="4:dobj" out="-1:quant|1:nobj">weniger</W>
<W lemma="Mensch" msd="NC" tag="NN" in="-1:nobj" out="">Menschen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">die</W>
<W lemma="Gelegenheit" msd="NC" tag="NN" in="-1:nobj" out="">Gelegenheit</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="1:vobj" out="-4:dobj|5:vobj">haben</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-7:vobj" out="-3:subj|-1:vobj|1:pnct">werden</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="2:dobj" out="1:possd">ihren</W>
<W lemma="Konzert" msd="NC" tag="NN" in="-1:possd" out="">Konzerten</W>
<W lemma="beiwohnen" msd="VAF" tag="VVIZU" in="-5:vobj" out="-2:dobj">beizuwohnen</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
<W lemma="nach" msd="SP" tag="APPR" in="11:scene" out="1:nobj">Nach</W>
<W lemma="Aussage" msd="NC" tag="NN" in="-1:nobj" out="1:relpa">Aussage</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-1:relpa" out="1:attr|2:possd">ihres</W>
<W lemma="dänisch" msd="AN" tag="ADJA" in="-1:attr" out="">dänischen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:possd" out="2:subj">Promoters</W>
<W lemma="Jens" msd="NP" tag="NE" in="1:namef" out="">Jens</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:subj" out="-1:namef|1:attr">Hofman</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">von</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:appr">der</W>
<W lemma="Plattengesellschaft" msd="NC" tag="NN" in="-1:nobj" out="">Plattengesellschaft</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:appr" out="">Medley</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-11:scene|1:subj|6:preds|8:preds|16:pnct">war</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|2:pnct">die</W>
<W lemma="Lust" msd="NC" tag="NN" in="-1:nobj" out="">Lust</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="in" msd="SP" tag="APPR" in="3:man" out="1:nobj">in</W>
<W lemma="Kirchenraum" msd="NC" tag="NN" in="-1:nobj" out="">Kirchenräumen</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-6:preds" out="1:vobj">zu</W>
<W lemma="singen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:man">singen</W>
<W lemma="ausschlaggebend" msd="AN" tag="ADJD" in="-8:preds" out="5:pobj">ausschlaggebender</W>
<W lemma="für" msd="SP" tag="APPR" in="4:goal" out="1:nobj">für</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:name">Sissel</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:name" out="1:pnct">Kyrkjebø</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="als" msd="CS" tag="KOKOM" in="-5:pobj" out="-4:goal|1:nobj">als</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">das</W>
<W lemma="Geschäftliche" msd="NC" tag="NN" in="-1:nobj" out="">Geschäftliche</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="außer" msd="SP" tag="APPR" in="3:add" out="">Außer</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Roskilde</W>
<W lemma="treten" msd="VA" tag="VVFIN" in="" out="-3:add|-2:loc|1:subj">tritt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|2:pnct|10:relr">die</W>
<W lemma="Sängerin" msd="NC" tag="NN" in="-1:nobj" out="">Sängerin</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELAT" in="7:preds" out="1:nobj">deren</W>
<W lemma="Stimme" msd="NC" tag="NN" in="-1:nobj" out="">Stimme</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="2:nobj">so</W>
<W lemma="klar" msd="AN" tag="ADJD" in="4:preds" out="-1:quant">klar</W>
<W lemma="wie" msd="CS" tag="KOKOM" in="-2:nobj" out="2:nobj">wie</W>
<W lemma="norwegisch" msd="AN" tag="ADJA" in="1:attr" out="">norwegische</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Fjell-Luft</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-10:relr" out="-7:preds|-4:preds|1:pnct|3:preds|14:pnct">ist</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="in" msd="SP" tag="APPR" in="-3:preds" out="-1:add|1:nobj">in</W>
<W lemma="Kopenhagen" msd="NP" tag="NE" in="-1:nobj" out="1:pnct|2:conj">Kopenhagen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:conj" out="1:pnct|2:conj">Odense</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:conj" out="1:pnct|2:conj|5:part">Århus</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:conj" out="2:conj">Randers</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Holstebro</W>
<W lemma="auf" msd="RG" tag="PTKVZ" in="-5:part" out="">auf</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
<W lemma="unter" msd="SP" tag="APPR" in="4:time" out="1:nobj">Unter</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Till" msd="NP" tag="NE" in="-1:nobj" out="1:nobj">Till</W>
<W lemma="Küstenland" msd="NC" tag="NN" in="-1:nobj" out="">Küstenland</W>
<W lemma="singen" msd="VA" tag="VVFIN" in="" out="-4:time|1:subj|2:dobj|24:pnct">singt</W>
<W lemma="sie" msd="PP" tag="PPER" in="-1:subj" out="">sie</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-2:dobj" out="1:nobj">eine</W>
<W lemma="Mischung" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Mischung</W>
<W lemma="aus" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">aus</W>
<W lemma="Hymne" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj">Hymnen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Psalm" msd="NC" tag="NN" in="-2:conj" out="3:conj">Psalmen</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="neu" msd="AN" tag="ADJA" in="1:attr" out="">neueren</W>
<W lemma="Lied" msd="NC" tag="NN" in="-3:conj" out="-2:coord|-1:attr|1:attr">Liedern</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="Begleitung" msd="NC" tag="NN" in="-1:nobj" out="">Begleitung</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="1:attr">eines</W>
<W lemma="aus" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">aus</W>
<W lemma="Flöte" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj|3:pnct|4:conj|6:conj|8:nobj">Flöte</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Kontrabaß" msd="NC" tag="NN" in="-2:conj" out="">Kontrabass</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="Cello" msd="NC" tag="NN" in="-4:conj" out="">Cello</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Synthesizer" msd="NC" tag="NN" in="-6:conj" out="-1:coord">Synthesizer</W>
<W lemma="bestehend" msd="AN" tag="ADJA" in="1:attr" out="">bestehenden</W>
<W lemma="Quartett" msd="NC" tag="NN" in="-8:nobj" out="-1:attr">Quartetts</W>
<W lemma="." msd="XP" tag="$." in="-24:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="1:nobj">Das</W>
<W lemma="Konzert" msd="NC" tag="NN" in="-1:nobj" out="">Konzert</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Roskilde</W>
<W lemma="unterscheiden" msd="VA" tag="VVFIN" in="" out="-4:subj|-2:loc|1:dobj|2:pobj|3:pobj|17:pnct">unterscheidet</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-1:dobj" out="">sich</W>
<W lemma="dadurch" msd="RG" tag="PAV" in="-2:pobj" out="">dadurch</W>
<W lemma="von" msd="SP" tag="APPR" in="-3:pobj" out="1:nobj">von</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|3:pnct|4:nobj">den</W>
<W lemma="fünf" msd="AC" tag="CARD" in="-1:nobj" out="1:attr">fünf</W>
<W lemma="ander" msd="AN" tag="ADJA" in="-1:attr" out="">anderen</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="8:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Veranstaltungsüberschuss</W>
<W lemma="in" msd="SP" tag="APPR" in="5:loc" out="1:nobj">in</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">ein</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:attr">AIDS-Projekt</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="Tansania" msd="NP" tag="NE" in="-1:nobj" out="">Tansania</W>
<W lemma="fließen" msd="VA" tag="VVFIN" in="-8:vobj" out="-7:subj|-5:loc">fließt</W>
<W lemma="." msd="XP" tag="$." in="-17:pnct" out="">.</W>
<W lemma="Initiator" msd="NC" tag="NN" in="1:subj" out="">Initiatoren</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:subj|1:preds|10:pnct">sind</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:preds" out="1:nobj|4:appr">der</W>
<W lemma="Gemeinderat" msd="NC" tag="NN" in="-1:nobj" out="">Gemeinderat</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Domgemeinde" msd="NC" tag="NN" in="-1:nobj" out="">Domgemeinde</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-4:appr" out="2:conj">Roskilde</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="mehrere" msd="PI" tag="PIAT" in="-2:conj" out="-1:coord|1:attr|2:nobj">mehrere</W>
<W lemma="privat" msd="AN" tag="ADJA" in="-1:attr" out="">private</W>
<W lemma="Sponsor" msd="NC" tag="NN" in="-2:nobj" out="">Sponsoren</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
</s>
</p>
