<p>
<s>
<W lemma="Inger" msd="NP" tag="NE" in="" out="">Inger</W>
<W lemma="&3a;" msd="XP" tag="$." in="" out="">:</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="von" msd="SP" tag="APPR" in="" out="">Von</W>
<W lemma="Seite" msd="NC" tag="NN" in="" out="">Seiten</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="Sportjournalist" msd="NC" tag="NN" in="" out="">Sportjournalisten</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">ist</W>
<W lemma="es" msd="PP" tag="PPER" in="" out="">es</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">ein</W>
<W lemma="klar" msd="AN" tag="ADJA" in="" out="">klarer</W>
<W lemma="Fall" msd="NC" tag="NN" in="" out="">Fall</W>
<W lemma="von" msd="SP" tag="APPR" in="" out="">von</W>
<W lemma="Neid" msd="NC" tag="NN" in="" out="">Neid</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="" out="">wenn</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="nie" msd="RG" tag="ADV" in="" out="">nie</W>
<W lemma="über" msd="SP" tag="APPR" in="" out="">über</W>
<W lemma="Meisterschaft" msd="NC" tag="NN" in="" out="">Meisterschaften</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="">im</W>
<W lemma="Bodybuilding" msd="NC" tag="NN" in="" out="">Bodybuilding</W>
<W lemma="berichten" msd="VAF" tag="VVINF" in="" out="">berichten</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="Sie&7c;sie" msd="PP" tag="PPER" in="" out="">Sie</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">sind</W>
<W lemma="eifersüchtig" msd="AN" tag="ADJD" in="" out="">eifersüchtig</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="selber" msd="RG" tag="ADV" in="" out="">selber</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="" out="">nicht</W>
<W lemma="über" msd="SP" tag="APPR" in="" out="">über</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">einen</W>
<W lemma="derart" msd="RG" tag="ADV" in="" out="">derart</W>
<W lemma="muskulös" msd="AN" tag="ADJA" in="" out="">muskulösen</W>
<W lemma="Körper" msd="NC" tag="NN" in="" out="">Körper</W>
<W lemma="verfügen" msd="VA" tag="VVFIN" in="" out="">verfügen</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="vom" msd="SP+P" tag="APPRART" in="" out="">Vom</W>
<W lemma="Bodybuilding" msd="NC" tag="NN" in="" out="">Bodybuilding</W>
<W lemma="hören" msd="VA" tag="VVFIN" in="" out="">hört</W>
<W lemma="man" msd="PP" tag="PIS" in="" out="">man</W>
<W lemma="nur" msd="RG" tag="ADV" in="" out="">nur</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="Verbindung" msd="NC" tag="NN" in="" out="">Verbindung</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Hormonskandalen</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="auch" msd="RG" tag="ADV" in="" out="">Auch</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="" out="">wenn</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="zur" msd="SP+P" tag="APPRART" in="" out="">zur</W>
<W lemma="Ausnahme" msd="NC" tag="NN" in="" out="">Ausnahme</W>
<W lemma="gehören" msd="VA" tag="VVFIN" in="" out="">gehören</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="es" msd="PP" tag="PPER" in="" out="">Es</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">war</W>
<W lemma="auch" msd="RG" tag="ADV" in="" out="">auch</W>
<W lemma="typisch" msd="AN" tag="ADJD" in="" out="">typisch</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="nach" msd="SP" tag="APPR" in="" out="">nach</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">dem</W>
<W lemma="Beitrag" msd="NC" tag="NN" in="" out="">Beitrag</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="wir" msd="PR" tag="PRF" in="" out="">uns</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">Eleva2ren</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="" out="">am</W>
<W lemma="Freitag" msd="NC" tag="NN" in="" out="">Freitag</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="Junge" msd="NC" tag="NN" in="" out="">Junge</W>
<W lemma="aus" msd="SP" tag="APPR" in="" out="">aus</W>
<W lemma="Grönland" msd="NP" tag="NE" in="" out="">Grönland</W>
<W lemma="sofort" msd="RG" tag="ADV" in="" out="">sofort</W>
<W lemma="auffordern" msd="VAP" tag="VVPP" in="" out="">aufgefordert</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">wurde</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="etwas" msd="RG" tag="ADV" in="" out="">etwas</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="Lustige" msd="NC" tag="NN" in="" out="">Lustiges</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="über" msd="SP" tag="APPR" in="" out="">über</W>
<W lemma="unser" msd="PO" tag="PPOSAT" in="" out="">unsere</W>
<W lemma="Muskel" msd="NC" tag="NN" in="" out="">Muskeln</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="" out="">zu</W>
<W lemma="sagen" msd="VAF" tag="VVINF" in="" out="">sagen</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="nein" msd="RG" tag="PTKANT" in="" out="">Nein</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="kein" msd="PI" tag="PIAT" in="" out="">keine</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Hormonrinder</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="man" msd="PP" tag="PIS" in="" out="">Man</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="">kann</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="" out="">sich</W>
<W lemma="überhaupt" msd="RG" tag="ADV" in="" out="">überhaupt</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="" out="">nicht</W>
<W lemma="vorstellen" msd="VAF" tag="VVINF" in="" out="">vorstellen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="wir" msd="PP" tag="PPER" in="" out="">wir</W>
<W lemma="unser" msd="PO" tag="PPOSAT" in="" out="">unsere</W>
<W lemma="Muskel" msd="NC" tag="NN" in="" out="">Muskeln</W>
<W lemma="ohne" msd="SP" tag="APPR" in="" out="">ohne</W>
<W lemma="Zusatz" msd="NC" tag="NN" in="" out="">Zusatz</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="sondern" msd="CC" tag="KON" in="" out="">sondern</W>
<W lemma="nur" msd="RG" tag="ADV" in="" out="">nur</W>
<W lemma="durch" msd="SP" tag="APPR" in="" out="">durch</W>
<W lemma="hart" msd="AN" tag="ADJA" in="" out="">hartes</W>
<W lemma="Training" msd="NC" tag="NN" in="" out="">Training</W>
<W lemma="bekommen" msd="VAP" tag="VVPP" in="" out="">bekommen</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="">haben</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="warum" msd="PT" tag="PWAV" in="" out="">Warum</W>
<W lemma="wählen" msd="VA" tag="VVFIN" in="" out="">wählen</W>
<W lemma="Mädchen" msd="NC" tag="NN" in="" out="">Mädchen</W>
<W lemma="denn" msd="CC" tag="KON" in="" out="">denn</W>
<W lemma="so" msd="RG" tag="ADV" in="" out="">so</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">eine</W>
<W lemma="traditionell" msd="AN" tag="ADJD" in="" out="">traditionell</W>
<W lemma="maskulin" msd="AN" tag="ADJA" in="" out="">maskuline</W>
<W lemma="Sportart" msd="NC" tag="NN" in="" out="">Sportart</W>
<W lemma="?" msd="XP" tag="$." in="" out="">?</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="als" msd="CS" tag="KOUS" in="" out="">Als</W>
<W lemma="ich" msd="PP" tag="PPER" in="" out="">ich</W>
<W lemma="klein" msd="AN" tag="ADJD" in="" out="">klein</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">war</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="träumen" msd="VA" tag="VVFIN" in="" out="">träumte</W>
<W lemma="ich" msd="PP" tag="PPER" in="" out="">ich</W>
<W lemma="davon" msd="RG" tag="PAV" in="" out="">davon</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">eine</W>
<W lemma="Prinzessin" msd="NC" tag="NN" in="" out="">Prinzessin</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="Taft" msd="NC" tag="NN" in="" out="">Taft</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Tüll" msd="NC" tag="NN" in="" out="">Tüll</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="" out="">zu</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="" out="">sein</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="viel" msd="PI" tag="PIDAT" in="" out="">Viele</W>
<W lemma="Jahr" msd="NC" tag="NN" in="" out="">Jahre</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="">habe</W>
<W lemma="ich" msd="PP" tag="PPER" in="" out="">ich</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Jazzballet</W>
<W lemma="tanzen" msd="VAP" tag="VVPP" in="" out="">getanzt</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="">sagt</W>
<W lemma="Helle" msd="NC" tag="NN" in="" out="">Helle</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="" out="">die</W>
<W lemma="normalerweise" msd="AN" tag="ADJD" in="" out="">normalerweise</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">das</W>
<W lemma="Studio" msd="NC" tag="NN" in="" out="">Studio</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Better</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Bodies</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Køge</W>
<W lemma="leiten" msd="VA" tag="VVFIN" in="" out="">leitet</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">das</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Work-out</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Aerobic</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Bodybuilding" msd="NC" tag="NN" in="" out="">Bodybuilding</W>
<W lemma="anbieten" msd="VA" tag="VVFIN" in="" out="">anbietet</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="" out="">Zum</W>
<W lemma="Bodybuilding" msd="NC" tag="NN" in="" out="">Bodybuilding</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="" out="">kam</W>
<W lemma="ich" msd="PP" tag="PPER" in="" out="">ich</W>
<W lemma="eigentlich" msd="RG" tag="ADV" in="" out="">eigentlich</W>
<W lemma="durch" msd="SP" tag="APPR" in="" out="">durch</W>
<W lemma="Zufall" msd="NC" tag="NN" in="" out="">Zufall</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="ich" msd="PP" tag="PPER" in="" out="">Ich</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="">habe</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="Gewichtheben" msd="NC" tag="NN" in="" out="">Gewichtheben</W>
<W lemma="anfangen" msd="VAP" tag="VVPP" in="" out="">angefangen</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">wurde</W>
<W lemma="auffordern" msd="VAP" tag="VVPP" in="" out="">aufgefordert</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="es" msd="PP" tag="PPER" in="" out="">es</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="">auf</W>
<W lemma="Wettkampfebene" msd="NC" tag="NN" in="" out="">Wettkampfebene</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="" out="">zu</W>
<W lemma="versuchen" msd="VAF" tag="VVINF" in="" out="">versuchen</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
</s>
</p>
