<p>
<s>
<W lemma="für" msd="SP" tag="APPR" in="2:scene" out="1:nobj">Für</W>
<W lemma="Freitag" msd="NC" tag="NN" in="-1:nobj" out="">Freitag</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-2:scene|1:dobj|10:vobj|11:pnct|23:pnct">hat</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:dobj" out="">SID</W>
<W lemma="zu" msd="SP" tag="APPR" in="8:pobj" out="1:nobj">zu</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:loc">einem</W>
<W lemma="Empfang" msd="NC" tag="NN" in="-1:nobj" out="">Empfang</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-2:loc" out="1:nobj">im</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">SID-Haus</W>
<W lemma="aus" msd="SP" tag="APPR" in="3:pobj" out="1:nobj">aus</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Anlaß" msd="NC" tag="NN" in="-1:nobj" out="">Anlass</W>
<W lemma="einladen" msd="VAP" tag="VVPP" in="-10:vobj" out="-8:pobj|-3:pobj|2:dobj">eingeladen</W>
<W lemma="," msd="XP" tag="$," in="-11:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="10:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="9:subj" out="1:nobj|2:pnct|4:appr">der</W>
<W lemma="Vorsitzende" msd="NC" tag="NN" in="-1:nobj" out="">Vorsitzende</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="Kjeld" msd="NP" tag="NE" in="1:namef" out="">Kjeld</W>
<W lemma="Christensen" msd="NP" tag="NE" in="-4:appr" out="-1:namef|1:pnct|2:attr">Christensen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="glücklich" msd="AN" tag="ADJA" in="-2:attr" out="">glückliche</W>
<W lemma="sechzig" msd="AC" tag="CARD" in="2:subj" out="1:nobj">sechzig</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahre</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-10:vobj" out="-9:subj|-2:subj">wird</W>
<W lemma="." msd="XP" tag="$." in="-23:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Der</W>
<W lemma="Geburtstag" msd="NC" tag="NN" in="-1:nobj" out="">Geburtstag</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-2:subj|2:preds|5:pnct">ist</W>
<W lemma="zwar" msd="RG" tag="ADV" in="1:quant" out="">zwar</W>
<W lemma="erst" msd="AN" tag="ADJD" in="-2:preds" out="-1:quant|1:time">erst</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-1:time" out="1:nobj">am</W>
<W lemma="21" msd="AC" tag="CARD" in="-1:nobj" out="">21</W>
<W lemma="." msd="XP" tag="$." in="-5:pnct" out="">.</W>
<W lemma="Januar" msd="NC" tag="NN" in="4:subj" out="1:pnct">Januar</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="aber" msd="CC" tag="KON" in="4:coord" out="">aber</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="5:cond" out="3:vobj">wenn</W>
<W lemma="Mensch" msd="NC" tag="NN" in="2:subj" out="-4:subj">Menschen</W>
<W lemma="zusammen" msd="RG" tag="ADV" in="1:time" out="">zusammen</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="-3:vobj" out="-4:coord|-2:subj|-1:time|1:pnct">kommen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="" out="-5:cond|10:vobj|21:pnct">sollte</W>
<W lemma="d" msd="PP" tag="PDS" in="9:dobj" out="">das</W>
<W lemma="aus" msd="SP" tag="APPR" in="8:pobj" out="2:nobj">aus</W>
<W lemma="praktisch" msd="AN" tag="ADJA" in="1:attr" out="">praktischen</W>
<W lemma="Grund&7c;Gründen" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Gründen</W>
<W lemma="am" msd="RG" tag="PTKA" in="5:dobj" out="1:nobj">am</W>
<W lemma="lieb" msd="AN" tag="ADJD" in="-1:nobj" out="">liebsten</W>
<W lemma="an" msd="SP" tag="APPR" in="3:pobj" out="1:nobj">an</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einem</W>
<W lemma="Freitag" msd="NC" tag="NN" in="-1:nobj" out="">Freitag</W>
<W lemma="passieren" msd="VAF" tag="VVINF" in="-10:vobj" out="-9:dobj|-8:pobj|-5:dobj|-3:pobj|1:pnct|2:conj">passieren</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="-2:conj" out="8:vobj">wenn</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="ander" msd="PP" tag="PIS" in="6:subj" out="-1:add|1:pobj">andere</W>
<W lemma="als" msd="CS" tag="KOKOM" in="-1:pobj" out="1:nobj">als</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">die</W>
<W lemma="üblich" msd="AN" tag="ADJA" in="-1:attr" out="">üblichen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="">Empfangslöwen</W>
<W lemma="auftauchen" msd="VAF" tag="VVINF" in="1:vobj" out="">auftauchen</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="-8:vobj" out="-6:subj|-1:vobj">sollen</W>
<W lemma="." msd="XP" tag="$." in="-21:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="1:subj|6:time|7:subj|8:vobj|9:pnct|12:subj|21:pnct">Ist</W>
<W lemma="Kopenhagener" msd="NC" tag="NN" in="-1:subj" out="">Kopenhagener</W>
</s>
</p>
<p>
<s>
<W lemma="nur" msd="RG" tag="ADV" in="-6:time" out="">Nur</W>
<W lemma="wenig" msd="PP" tag="PIS" in="-7:subj" out="">wenige</W>
<W lemma="wissen" msd="VAF" tag="VVINF" in="-8:vobj" out="2:dobj">wissen</W>
<W lemma="," msd="XP" tag="$," in="-9:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="6:vobj">dass</W>
<W lemma="Kjeld" msd="NP" tag="NE" in="1:namef" out="">Kjeld</W>
<W lemma="Christensen" msd="NP" tag="NE" in="-12:subj" out="-1:namef">Christensen</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="Kopenhagen" msd="NP" tag="NE" in="-1:nobj" out="">Kopenhagen</W>
<W lemma="gebären" msd="VAP" tag="VVPP" in="1:vobj" out="-2:loc">geboren</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-6:vobj" out="-1:vobj|1:pnct|2:conj">wurde</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Bob" msd="NC" tag="NN" in="-2:conj" out="1:pnct|2:conj">bob</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Bob" msd="NC" tag="NN" in="-2:conj" out="">bob</W>
<W lemma="!" msd="XP" tag="$." in="-21:pnct" out="">!</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:subj|1:conc|4:vobj|5:pnct|6:cause|16:pnct">wurde</W>
<W lemma="aber" msd="RG" tag="ADV" in="-1:conc" out="">aber</W>
<W lemma="nach" msd="SP" tag="APPR" in="2:cause" out="1:nobj">nach</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Jütland</W>
<W lemma="retten" msd="VAP" tag="VVPP" in="-4:vobj" out="-2:cause">gerettet</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="da" msd="CS" tag="KOUS" in="-6:cause" out="9:vobj">da</W>
<W lemma="er" msd="PP" tag="PPER" in="8:subj" out="">er</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="7:dobj" out="1:attr|2:possd">seine</W>
<W lemma="ganz" msd="AN" tag="ADJA" in="-1:attr" out="">ganze</W>
<W lemma="Kindheit" msd="NC" tag="NN" in="-2:possd" out="2:conj">Kindheit</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Jugend" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Jugend</W>
<W lemma="in" msd="SP" tag="APPR" in="2:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Århus</W>
<W lemma="verbringen" msd="VA" tag="VVFIN" in="-9:vobj" out="-8:subj|-7:dobj|-2:loc">verbrachte</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="als" msd="CS" tag="KOKOM" in="2:time" out="">Als</W>
<W lemma="14jährig" msd="AN" tag="ADJA" in="1:qobj" out="">14jähriger</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="" out="-2:time|-1:qobj|2:subj|3:pobj">kam</W>
<W lemma="Kjeld" msd="NP" tag="NE" in="1:namef" out="">Kjeld</W>
<W lemma="Christensen" msd="NP" tag="NE" in="-2:subj" out="-1:namef">Christensen</W>
<W lemma="zur" msd="SP+P" tag="APPRART" in="-3:pobj" out="1:nobj|2:pnct|9:conj">zur</W>
<W lemma="Landwirtschaft" msd="NC" tag="NN" in="-1:nobj" out="">Landwirtschaft</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="aber" msd="RG" tag="ADV" in="6:time" out="">aber</W>
<W lemma="nach" msd="SP" tag="APPR" in="5:time" out="1:nobj">nach</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="-1:nobj" out="1:possd">seiner</W>
<W lemma="Zeit" msd="NC" tag="NN" in="-1:possd" out="">Zeit</W>
<W lemma="als" msd="CS" tag="KOKOM" in="2:time" out="1:nobj">als</W>
<W lemma="Soldat" msd="NC" tag="NN" in="-1:nobj" out="">Soldat</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="-9:conj" out="-6:time|-5:time|-2:time|1:subj|2:time|5:pnct|11:conj|12:pnct">kam</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:time" out="1:nobj">in</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">eine</W>
<W lemma="Fabrik" msd="NC" tag="NN" in="-1:nobj" out="">Fabrik</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="in" msd="SP" tag="APPR" in="5:loc" out="1:nobj">in</W>
<W lemma="d" msd="PT" tag="PRELS" in="-1:nobj" out="">der</W>
<W lemma="er" msd="PP" tag="PPER" in="3:subj" out="">er</W>
<W lemma="18" msd="AC" tag="CARD" in="2:dobj" out="1:nobj">18</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahre</W>
<W lemma="arbeiten" msd="VA" tag="VVFIN" in="-11:conj" out="-5:loc|-3:subj|-2:dobj">arbeitete</W>
<W lemma="." msd="XP" tag="$." in="-12:pnct" out="">.</W>
<W lemma="als" msd="CS" tag="KOKOM" in="10:qobj" out="8:vobj">Als</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Korsholmskole</W>
<W lemma="in" msd="SP" tag="APPR" in="5:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Hinnerup</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="3:dobj" out="1:attr|2:nobj">einen</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-1:attr" out="">neuen</W>
<W lemma="Hausmeister" msd="NC" tag="NN" in="-2:nobj" out="">Hausmeister</W>
<W lemma="suchen" msd="VA" tag="VVFIN" in="-8:vobj" out="-7:subj|-5:loc|-3:dobj|1:pnct">suchte</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="bekommen" msd="VA" tag="VVFIN" in="" out="-10:qobj|2:subj|3:dobj|5:pnct">bekam</W>
<W lemma="Kjeld" msd="NP" tag="NE" in="1:namef" out="">Kjeld</W>
<W lemma="Christensen" msd="NP" tag="NE" in="-2:subj" out="-1:namef">Christensen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:dobj" out="1:nobj">die</W>
<W lemma="Stelle" msd="NC" tag="NN" in="-1:nobj" out="">Stelle</W>
<W lemma="." msd="XP" tag="$." in="-5:pnct" out="">.</W>
<W lemma="dort" msd="RG" tag="ADV" in="1:add" out="">Dort</W>
<W lemma="arbeiten" msd="VA" tag="VVFIN" in="" out="-1:add|1:subj|2:dobj|6:pnct">arbeitete</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-2:dobj" out="1:attr|2:nobj">die</W>
<W lemma="nah" msd="AN" tag="ADJA" in="-1:attr" out="">nächsten</W>
<W lemma="10" msd="AC" tag="CARD" in="-2:nobj" out="1:nobj">10</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahre</W>
<W lemma="." msd="XP" tag="$." in="-6:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="acht" msd="AC" tag="CARD" in="3:subj" out="1:nobj">Acht</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="1:aobj">Jahre</W>
<W lemma="lang" msd="AN" tag="ADJD" in="-1:aobj" out="">lang</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-3:subj|1:subj|2:preds|9:pnct">war</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="Mitglied" msd="NC" tag="NN" in="-2:preds" out="1:attr">Mitglied</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-1:attr" out="1:attr|2:attr|3:nobj">im</W>
<W lemma="sozialdemokratisch" msd="AN" tag="ADJD" in="-1:attr" out="">sozialdemokratisch</W>
<W lemma="gewählt" msd="AN" tag="ADJA" in="-2:attr" out="">gewählten</W>
<W lemma="Stadtrat" msd="NC" tag="NN" in="-3:nobj" out="1:attr">Stadtrat</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Hinnerum</W>
<W lemma="." msd="XP" tag="$." in="-9:pnct" out="">.</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:subj|1:time|2:vobj|3:pnct|7:preds|9:pnct|10:time|52:pnct">wurde</W>
<W lemma="oft" msd="RG" tag="ADV" in="-1:time" out="">oft</W>
<W lemma="auffordern" msd="VAP" tag="VVPP" in="-2:vobj" out="">aufgefordert</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="4:robj" out="">sich</W>
<W lemma="wieder" msd="RG" tag="ADV" in="3:dobj" out="">wieder</W>
<W lemma="aufstellen" msd="VAF" tag="VVINF" in="2:vobj" out="">aufstellen</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-7:preds" out="1:vobj">zu</W>
<W lemma="lassen" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:robj|-3:dobj|-2:vobj|43:vobj">lassen</W>
<W lemma="," msd="XP" tag="$," in="-9:pnct" out="">,</W>
<W lemma="nachdem" msd="CS" tag="KOUS" in="-10:time" out="5:vobj">nachdem</W>
<W lemma="er" msd="PP" tag="PPER" in="4:subj" out="9:conj">er</W>
<W lemma="nach" msd="SP" tag="APPR" in="2:time" out="1:nobj">nach</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Hadsten</W>
<W lemma="umziehen" msd="VAP" tag="VVPP" in="1:vobj" out="-2:time">umgezogen</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-1:vobj|1:pnct">war</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="aber" msd="CC" tag="KON" in="3:coord" out="">aber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">SID-Vorsitzende</W>
<W lemma="wissen" msd="VA" tag="VVFIN" in="-9:conj" out="-3:coord|-2:subj|1:pnct|2:dobj">weiß</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="5:vobj">dass</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">ein</W>
<W lemma="Abteilungsleiter" msd="NC" tag="NN" in="-1:nobj" out="">Abteilungsleiter</W>
<W lemma="alle" msd="PP" tag="PIS" in="2:subj" out="">alle</W>
<W lemma="repräsentieren" msd="VAF" tag="VVINF" in="1:vobj" out="-3:subj">repräsentieren</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="-5:vobj" out="-2:subj|-1:vobj|3:pnct|12:vobj">muss</W>
<W lemma="und" msd="CC" tag="KON" in="9:coord" out="">und</W>
<W lemma="auch" msd="RG" tag="ADV" in="2:add" out="">auch</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="8:time" out="-2:add|6:vobj">wenn</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:subj" out="1:nobj">die</W>
<W lemma="Sozialdemokrat" msd="NC" tag="NN" in="-1:nobj" out="">Sozialdemokraten</W>
<W lemma="in" msd="SP" tag="APPR" in="3:preds" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Überzahl" msd="NC" tag="NN" in="-1:nobj" out="">Überzahl</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-6:vobj" out="-9:coord|-5:subj|-3:preds|1:pnct">sind</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-12:vobj" out="-8:time|2:conj">haben</W>
<W lemma="sowohl" msd="CC" tag="KON" in="3:correl" out="">sowohl</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:conj" out="1:pnct">SF</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="als" msd="CS" tag="KOKOM" in="2:coord" out="-3:correl">als</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="-2:coord|-1:add|1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:dobj">Fremdskridtsparti</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-1:dobj" out="1:possd">ihre</W>
<W lemma="Chance" msd="NC" tag="NN" in="-1:possd" out="">Chance</W>
<W lemma="in" msd="SP" tag="APPR" in="2:man" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Vestergade</W>
<W lemma="erhalten" msd="VAF" tag="VVINF" in="-43:vobj" out="-6:dobj|-2:man">erhalten</W>
<W lemma="." msd="XP" tag="$." in="-52:pnct" out="">.</W>
</s>
</p>
