<p>
<s>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">Es</W>
<W lemma="stellen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:robj|2:subj|5:pnct|36:pnct">stellt</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-1:robj" out="">sich</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-2:subj" out="1:attr|2:nobj|7:appr">die</W>
<W lemma="groß" msd="AN" tag="ADJA" in="-1:attr" out="">große</W>
<W lemma="Frage" msd="NC" tag="NN" in="-2:nobj" out="">Frage</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="womit" msd="PT" tag="PWAV" in="3:namel" out="">womit</W>
<W lemma="Poul" msd="NP" tag="NE" in="2:namef" out="">Poul</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="1:namel" out="5:relpa">Nyrup</W>
<W lemma="Rasmussen" msd="NP" tag="NE" in="-7:appr" out="-3:namel|-2:namef|-1:namel">Rasmussen</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="3:robj" out="">sich</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="2:time" out="">jetzt</W>
<W lemma="beschäftigen" msd="VAF" tag="VVINF" in="1:vobj" out="">beschäftigen</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="-5:relpa" out="-3:robj|-2:time|-1:vobj|1:pnct|2:time">soll</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="bis" msd="CS" tag="KOUS" in="-2:time" out="20:vobj">bis</W>
<W lemma="d" msd="P[ID]" tag="ART" in="19:subj" out="1:nobj">der</W>
<W lemma="Bericht" msd="NC" tag="NN" in="-1:nobj" out="">Bericht</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj|2:attr">des</W>
<W lemma="Richter" msd="NC" tag="NN" in="-1:nobj" out="">Richters</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-2:attr" out="1:attr|2:nobj|3:pnct|5:nobj">am</W>
<W lemma="ober" msd="AN" tag="ADJA" in="-1:attr" out="">obersten</W>
<W lemma="Gericht" msd="NC" tag="NN" in="-2:nobj" out="">Gericht</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="1:namef" out="">Mogens</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-5:nobj" out="-1:namef|1:pnct">Hornslet</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="über" msd="SP" tag="APPR" in="8:time" out="1:nobj">über</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:nobj">Tamilenangelegenheit</W>
<W lemma="Anfang" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Anfang</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:pobj" out="1:attr|2:nobj">des</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-1:attr" out="">neuen</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="">Jahres</W>
<W lemma="veröffentlichen" msd="VAP" tag="VVPP" in="1:vobj" out="">veröffentlicht</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-20:vobj" out="-19:subj|-8:time|-1:vobj">wird</W>
<W lemma="." msd="XP" tag="$." in="-36:pnct" out="">.</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-1:subj|1:eval|9:vobj|10:pnct|28:pnct">könnte</W>
<W lemma="natürlich" msd="AN" tag="ADJD" in="-1:eval" out="">natürlich</W>
<W lemma="wieder" msd="RG" tag="ADV" in="1:time" out="">wieder</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="1:attr" out="-1:time">westentaschenfilosofische</W>
<W lemma="Betrachtung" msd="NC" tag="NN" in="5:dobj" out="-1:attr">Betrachtungen</W>
<W lemma="über" msd="SP" tag="APPR" in="4:pobj" out="1:nobj">über</W>
<W lemma="Moral" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Moral</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Politik" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Politik</W>
<W lemma="anstellen" msd="VAF" tag="VVINF" in="-9:vobj" out="-5:dobj|-4:pobj|3:vobj">anstellen</W>
<W lemma="," msd="XP" tag="$," in="-10:pnct" out="">,</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">er</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-3:vobj" out="-1:subj|2:conc|3:add|5:vobj|6:pnct">könnte</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="4:dobj" out="">sich</W>
<W lemma="aber" msd="RG" tag="ADV" in="-2:conc" out="">aber</W>
<W lemma="auch" msd="RG" tag="ADV" in="-3:add" out="">auch</W>
<W lemma="dafür" msd="RG" tag="PAV" in="1:pobj" out="10:nobj">dafür</W>
<W lemma="entscheiden" msd="VAF" tag="VVINF" in="-5:vobj" out="-4:dobj|-1:pobj">entscheiden</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="2:dobj" out="1:possd">seine</W>
<W lemma="Rolle" msd="NC" tag="NN" in="-1:possd" out="">Rolle</W>
<W lemma="als" msd="CS" tag="KOKOM" in="6:pobj" out="-2:dobj|1:nobj">als</W>
<W lemma="Leiter" msd="NC" tag="NN" in="-1:nobj" out="">Leiter</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Opposition" msd="NC" tag="NN" in="-1:nobj" out="">Opposition</W>
<W lemma="ernst" msd="AN" tag="ADJD" in="2:dobj" out="">ernst</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-10:nobj" out="1:vobj">zu</W>
<W lemma="nehmen" msd="VAF" tag="VVINF" in="-1:vobj" out="-6:pobj|-2:dobj">nehmen</W>
<W lemma="." msd="XP" tag="$." in="-28:pnct" out="">.</W>
<W lemma="z." msd="SP+P" tag="APPRART" in="" out="">Z.</W>
<W lemma="B." msd="NC" tag="NN" in="" out="1:pnct|2:cause">B.</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="indem" msd="CS" tag="KOUS" in="-2:cause" out="1:subj|2:vobj|3:vobj">indem</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-2:vobj" out="">sich</W>
<W lemma="eingehend" msd="AN" tag="ADJD" in="-3:vobj" out="1:pobj">eingehend</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr">der</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="">sog.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="1:vobj|2:pnct|10:relr|11:pnct">Gebührenangelegenheit</W>
<W lemma="beschäftigen" msd="VAP" tag="VVPP" in="-1:vobj" out="">beschäftigt</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="7:subj" out="">die</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="1:quant" out="">gleichzeitig</W>
<W lemma="sehr" msd="RG" tag="ADV" in="1:quant" out="-1:quant">sehr</W>
<W lemma="prinzipiell" msd="AN" tag="ADJD" in="4:preds" out="-1:quant">prinzipiell</W>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">und</W>
<W lemma="sehr" msd="RG" tag="ADV" in="1:quant" out="">sehr</W>
<W lemma="realistisch" msd="AN" tag="ADJD" in="1:preds" out="-1:quant">realistisch</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-10:relr" out="-7:subj|-4:preds|-3:coord|-1:preds">ist</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
<W lemma="prinzipiell" msd="AN" tag="ADJD" in="" out="1:pnct|2:cause">Prinzipiell</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="da" msd="CS" tag="KOUS" in="-2:cause" out="15:vobj|16:pnct">da</W>
<W lemma="es" msd="PP" tag="PPER" in="14:subj" out="">es</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="13:robj" out="">sich</W>
<W lemma="um" msd="SP" tag="APPR" in="12:pobj" out="1:nobj">um</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj|6:appa">den</W>
<W lemma="mangelnd" msd="AN" tag="ADJA" in="-1:attr" out="">mangelnden</W>
<W lemma="Respekt" msd="NC" tag="NN" in="-2:nobj" out="">Respekt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">des</W>
<W lemma="Justizministerien" msd="NC" tag="NN" in="-1:nobj" out="">Justizministeriums</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-6:appa" out="-1:coord|1:nobj|2:attr">der</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Rigspoliti</W>
<W lemma="für" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">für</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">das</W>
<W lemma="Grundgesetz" msd="NC" tag="NN" in="-1:nobj" out="">Grundgesetz</W>
<W lemma="handeln" msd="VA" tag="VVFIN" in="-15:vobj" out="-14:subj|-13:robj|-12:pobj">handelt</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="realistisch" msd="AN" tag="ADJD" in="2:cause" out="1:pnct">Realistisch</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="weil" msd="CS" tag="KOUS" in="" out="-2:cause|8:vobj">weil</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj|15:relr">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:nobj">Gebührenaffäre</W>
<W lemma="Zustand" msd="NC" tag="NN" in="-1:nobj" out="1:loc">Zustände</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-1:loc" out="1:nobj">im</W>
<W lemma="Justizministerien" msd="NC" tag="NN" in="-1:nobj" out="">Justizministerium</W>
<W lemma="offen" msd="AN" tag="ADJD" in="1:man" out="">offen</W>
<W lemma="legen" msd="VAP" tag="VVPP" in="1:vobj" out="-1:man">gelegt</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-8:vobj" out="-7:subj|-1:vobj|1:pnct|9:pnct">hat</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="6:subj" out="1:neg">die</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-1:neg" out="">nicht</W>
<W lemma="mehr" msd="RG" tag="ADV" in="1:quant" out="">mehr</W>
<W lemma="lang" msd="AN" tag="ADJA" in="1:attr" out="-1:quant">lange</W>
<W lemma="Bestand" msd="NC" tag="NN" in="1:dobj" out="-1:attr">Bestand</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="1:vobj" out="-1:dobj">haben</W>
<W lemma="dürfen" msd="VA" tag="VMFIN" in="-15:relr" out="-6:subj|-1:vobj">dürfen</W>
<W lemma="." msd="XP" tag="$." in="-9:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="als" msd="CS" tag="KOKOM" in="72:man" out="1:nobj">Als</W>
<W lemma="Mann" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|9:relr">Mann</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="7:subj" out="1:nobj">der</W>
<W lemma="kein" msd="PI" tag="PIAT" in="-1:nobj" out="1:nobj">keine</W>
<W lemma="Berührungsangst" msd="NC" tag="NN" in="-1:nobj" out="">Berührungsangst</W>
<W lemma="gegenüber" msd="SP" tag="APPR" in="4:loc" out="1:nobj">gegenüber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:appr">dem</W>
<W lemma="bürgerlich" msd="AN" tag="ADJA" in="-1:attr" out="">bürgerlichen</W>
<W lemma="Dänemark" msd="NP" tag="NE" in="-2:appr" out="">Dänemark</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-9:relr" out="-7:subj|-4:loc|1:pnct|65:pnct">hat</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="1:subj|4:vobj|5:pnct|15:vobj|16:pnct">könnte</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:subj" out="1:nobj">Nyrup</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Rassmussen</W>
<W lemma="zunächst" msd="RG" tag="ADV" in="1:man" out="">zunächst</W>
<W lemma="lesen" msd="VAF" tag="VVINF" in="-4:vobj" out="-1:man">lesen</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="was" msd="PT" tag="PRELS" in="9:subj" out="39:vobj">was</W>
<W lemma="sogar" msd="RG" tag="ADV" in="8:focal" out="">sogar</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj|2:nobj">die</W>
<W lemma="Tageszeitung" msd="NC" tag="NN" in="-1:nobj" out="">Tageszeitung</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="">Børsen</W>
<W lemma="kürzlich" msd="AN" tag="ADJD" in="1:eval" out="">kürzlich</W>
<W lemma="in" msd="SP" tag="APPR" in="3:loc" out="-1:eval|1:nobj">in</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einem</W>
<W lemma="Leitartikel" msd="NC" tag="NN" in="-1:nobj" out="">Leitartikel</W>
<W lemma="feststellen" msd="VA" tag="VVFIN" in="-15:vobj" out="-9:subj|-8:focal|-7:subj|-3:loc|3:dobj">feststellte</W>
<W lemma="&3a;" msd="XP" tag="$." in="-16:pnct" out="">:</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="4:pnct" out="">"</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-3:dobj" out="16:vobj">dass</W>
<W lemma="Justizminister" msd="NC" tag="NN" in="2:title" out="">Justizminister</W>
<W lemma="Hans" msd="NP" tag="NE" in="1:namef" out="">Hans</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="13:subj" out="-4:pnct|-2:title|-1:namef|2:appa">Engell</W>
<W lemma="(" msd="XP" tag="$(" in="1:pnct" out="">(</W>
<W lemma="K" msd="NC" tag="NN" in="-2:appa" out="-1:pnct|1:pnct">K</W>
<W lemma=")" msd="XP" tag="$(" in="-1:pnct" out="">)</W>
<W lemma="offensichtlich" msd="AN" tag="ADJD" in="1:quant" out="">offensichtlich</W>
<W lemma="vollkommen" msd="AN" tag="ADJD" in="1:quant" out="-1:quant">vollkommen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="-1:quant|1:nobj|2:attr">die</W>
<W lemma="Kontrolle" msd="NC" tag="NN" in="-1:nobj" out="">Kontrolle</W>
<W lemma="über" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">über</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="-1:nobj" out="1:attr|2:possd">sein</W>
<W lemma="eigen" msd="AN" tag="ADJA" in="-1:attr" out="">eigenes</W>
<W lemma="Ministerium" msd="NC" tag="NN" in="-2:possd" out="">Ministerium</W>
<W lemma="verlieren" msd="VAP" tag="VVPP" in="1:vobj" out="-6:dobj">verloren</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-16:vobj" out="-13:subj|-1:vobj">hat</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="10:pnct" out="1:pnct">"</W>
<W lemma="-" msd="XP" tag="$(" in="-1:pnct" out="">-</W>
<W lemma="und" msd="CC" tag="KON" in="8:coord" out="">und</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="7:pnct" out="">"</W>
<W lemma="dass" msd="CS" tag="KOUS" in="3:quant" out="">dass</W>
<W lemma="es" msd="PP" tag="PPER" in="5:subj" out="">es</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="4:time" out="">jetzt</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="-3:quant|5:nobj">so</W>
<W lemma="weit" msd="AN" tag="ADJD" in="1:man" out="-1:quant">weit</W>
<W lemma="kommen" msd="VAP" tag="VVPP" in="1:vobj" out="-1:man">gekommen</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-39:vobj" out="-10:pnct|-8:coord|-7:pnct|-5:subj|-4:time|-1:vobj|1:pnct|4:preds">ist</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-5:nobj" out="14:vobj">dass</W>
<W lemma="nur" msd="RG" tag="ADV" in="1:quant" out="">nur</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-4:preds" out="-1:quant|1:attr|2:nobj|4:nobj">ein</W>
<W lemma="groß" msd="AN" tag="ADJA" in="-1:attr" out="">größerer</W>
<W lemma="Austausch" msd="NC" tag="NN" in="-2:nobj" out="">Austausch</W>
<W lemma="leitender" msd="AN" tag="ADJA" in="1:attr" out="">leitender</W>
<W lemma="Angestellte" msd="NC" tag="NN" in="-4:nobj" out="-1:attr">Angestellte</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj|2:attr">das</W>
<W lemma="Vertrauen" msd="NC" tag="NN" in="-1:nobj" out="">Vertrauen</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">das</W>
<W lemma="Justizministerien" msd="NC" tag="NN" in="-1:nobj" out="">Justizministerium</W>
<W lemma="wieder" msd="RG" tag="ADV" in="1:iter" out="">wieder</W>
<W lemma="herstellen" msd="VAF" tag="VVINF" in="1:vobj" out="-72:man|-1:iter">herstellen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-14:vobj" out="-7:subj|-1:vobj|1:pnct">kann</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="." msd="XP" tag="$." in="-65:pnct" out="">.</W>
</s>
</p>
