<p>
<s>
<W lemma="was" msd="PT" tag="PWS" in="1:dobj" out="">Was</W>
<W lemma="verstehen" msd="VA" tag="VVFIN" in="" out="-1:dobj|1:subj|2:man|8:pnct">versteht</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="unter" msd="SP" tag="APPR" in="-2:man" out="2:nobj">unter</W>
<W lemma="schlecht" msd="AN" tag="ADJA" in="1:attr" out="">schlechter</W>
<W lemma="Blutzirkulation" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|1:attr">Blutzirkulation</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">den</W>
<W lemma="Bein&7c;Beinen" msd="NC" tag="NN" in="-1:nobj" out="">Beinen</W>
<W lemma="?" msd="XP" tag="$." in="-8:pnct" out="">?</W>
<W lemma="woher" msd="PT" tag="PWAV" in="1:cause" out="">Woher</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="" out="-1:cause|1:dobj|2:pnct|4:conj">kommt</W>
<W lemma="d" msd="PP" tag="PDS" in="-1:dobj" out="">das</W>
<W lemma="-" msd="XP" tag="$(" in="-2:pnct" out="">-</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-4:conj" out="-1:coord|1:subj|4:vobj|11:pnct">kann</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="etwas" msd="RG" tag="ADV" in="2:dobj" out="">etwas</W>
<W lemma="dafür" msd="RG" tag="PAV" in="1:pobj" out="2:pnct|3:cons">dafür</W>
<W lemma="tun" msd="VAF" tag="VVINF" in="-4:vobj" out="-2:dobj|-1:pobj">tun</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="damit" msd="CS" tag="KOUS" in="-3:cons" out="4:vobj">damit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="schnell" msd="AN" tag="ADJD" in="1:man" out="">schneller</W>
<W lemma="fließen" msd="VA" tag="VVFIN" in="-4:vobj" out="-3:subj|-1:man">fließt</W>
<W lemma="?" msd="XP" tag="$." in="-11:pnct" out="">?</W>
</s>
</p>
<p>
<s>
<W lemma="wenn" msd="CS" tag="KOUS" in="6:cond" out="4:vobj">Wenn</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">die</W>
<W lemma="Pulsader" msd="NC" tag="NN" in="-1:nobj" out="">Pulsadern</W>
<W lemma="verkalken" msd="VAP" tag="VVPP" in="1:vobj" out="">verkalkt</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:subj|-1:vobj|1:pnct">sind</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-6:cond|1:subj|8:neg|13:vobj|14:pnct">kann</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="d" msd="P[ID]" tag="ART" in="10:dobj" out="1:nobj|3:conj">den</W>
<W lemma="Muskel" msd="NC" tag="NN" in="-1:nobj" out="">Muskeln</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:conj" out="-1:coord|1:nobj">der</W>
<W lemma="Haut" msd="NC" tag="NN" in="-1:nobj" out="">Haut</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-8:neg" out="">nicht</W>
<W lemma="ausreichend" msd="AN" tag="ADJD" in="1:quant" out="">ausreichend</W>
<W lemma="Sauerstoff" msd="NC" tag="NN" in="3:dobj" out="-1:quant|2:conj">Sauerstoff</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Nahrung" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Nahrung</W>
<W lemma="zuführen" msd="VAF" tag="VVINF" in="-13:vobj" out="-10:dobj|-3:dobj">zuführen</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
<W lemma="dann" msd="RG" tag="ADV" in="1:add" out="">Dann</W>
<W lemma="bekommen" msd="VA" tag="VVFIN" in="" out="-1:add|1:subj|3:nobj|4:resem|12:vobj|14:pnct">bekommt</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="kalt" msd="AN" tag="ADJA" in="1:attr" out="">kalte</W>
<W lemma="Fuß" msd="NC" tag="NN" in="-3:nobj" out="-1:attr">Füße</W>
<W lemma="ohne" msd="SP" tag="APPR" in="-4:resem" out="1:nobj">ohne</W>
<W lemma="Pulsschlag" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj">Pulsschlag</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Störung" msd="NC" tag="NN" in="-2:conj" out="">Störungen</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="4:loc" out="1:nobj">im</W>
<W lemma="Tastsinn" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Tastsinn</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Wunde" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Wunden</W>
<W lemma="verheilen" msd="VA" tag="VVFIN" in="-12:vobj" out="-4:loc|1:man">verheilen</W>
<W lemma="schlecht" msd="AN" tag="ADJD" in="-1:man" out="">schlecht</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="außerdem" msd="RG" tag="ADV" in="1:add" out="">Außerdem</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-1:add|1:subj|5:vobj|6:pnct|9:vobj|14:pnct">kann</W>
<W lemma="es" msd="PP" tag="PPER" in="-1:subj" out="">es</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:dobj" out="1:nobj">den</W>
<W lemma="Vene" msd="NC" tag="NN" in="-1:nobj" out="">Venen</W>
<W lemma="schwer" msd="AN" tag="ADJD" in="1:aobj" out="">schwer</W>
<W lemma="fallen" msd="VAF" tag="VVINF" in="-5:vobj" out="-3:dobj|-1:aobj">fallen</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="1:nobj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="zurück" msd="RG" tag="PTKVZ" in="-9:vobj" out="3:nobj">zurück</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="3:pobj" out="1:nobj">zum</W>
<W lemma="Herz&7c;Herzen" msd="NC" tag="NN" in="-1:nobj" out="">Herzen</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-3:nobj" out="1:vobj">zu</W>
<W lemma="leiten" msd="VAF" tag="VVINF" in="-1:vobj" out="-6:dobj|-3:pobj">leiten</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="3:loc" out="1:nobj">In</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-1:nobj" out="1:nobj">diesem</W>
<W lemma="Fall" msd="NC" tag="NN" in="-1:nobj" out="">Fall</W>
<W lemma="stauen" msd="VA" tag="VVFIN" in="" out="-3:loc|7:conj">staut</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="6:robj" out="">sich</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:subj" out="1:nobj|3:conj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:conj" out="-1:coord|1:nobj">die</W>
<W lemma="Bein" msd="NC" tag="NN" in="-1:nobj" out="">Beine</W>
<W lemma="schwellen" msd="VA" tag="VVFIN" in="-7:conj" out="-6:robj|-5:subj|1:part|2:pnct">schwellen</W>
<W lemma="an" msd="RG" tag="PTKVZ" in="-1:part" out="">an</W>
<W lemma="." msd="XP" tag="$." in="-2:pnct" out="">.</W>
<W lemma="Ergebnis" msd="NC" tag="NN" in="" out="1:pnct|5:nobj|9:nobj|12:pnct">Ergebnis</W>
<W lemma="&3a;" msd="XP" tag="$." in="-1:pnct" out="">:</W>
<W lemma="schmerzhaft" msd="AN" tag="ADJA" in="3:attr" out="2:conj">Schmerzhafte</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="müde" msd="AN" tag="ADJA" in="-2:conj" out="-1:coord">müde</W>
<W lemma="Bein" msd="NC" tag="NN" in="-5:nobj" out="-3:attr">Beine</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="häufig" msd="AN" tag="ADJD" in="1:man" out="-1:coord">häufig</W>
<W lemma="nächtlich" msd="AN" tag="ADJA" in="1:attr" out="-1:man">nächtliche</W>
<W lemma="Unruhe" msd="NC" tag="NN" in="-9:nobj" out="-1:attr|2:conj">Unruhe</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Krampf" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Krämpfe</W>
<W lemma="." msd="XP" tag="$." in="-12:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="es" msd="PP" tag="PPER" in="1:expl" out="">Es</W>
<W lemma="geben" msd="VA" tag="VVFIN" in="" out="-1:expl|1:dobj|3:pnct">gibt</W>
<W lemma="mehrere" msd="PI" tag="PIAT" in="-1:dobj" out="1:nobj">mehrere</W>
<W lemma="Behandlungsmöglichkeit" msd="NC" tag="NN" in="-1:nobj" out="">Behandlungsmöglichkeiten</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:subj" out="1:attr|2:pnct|3:attr|4:nobj">Die</W>
<W lemma="groß" msd="AN" tag="ADJA" in="-1:attr" out="">großen</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="verkalkt" msd="AN" tag="ADJA" in="-3:attr" out="">verkalkten</W>
<W lemma="Gefäß" msd="NC" tag="NN" in="-4:nobj" out="">Gefäße</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-5:subj|3:vobj|16:pnct">können</W>
<W lemma="dadurch" msd="RG" tag="PAV" in="1:pobj" out="3:pnct|4:nobj">dadurch</W>
<W lemma="erweitern" msd="VAP" tag="VVPP" in="1:vobj" out="-1:pobj">erweitert</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-3:vobj" out="-1:vobj|5:vobj">werden</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="10:vobj">dass</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="9:subj" out="1:nobj">ein</W>
<W lemma="Ballon" msd="NC" tag="NN" in="-1:nobj" out="">Ballon</W>
<W lemma="einführen" msd="VAP" tag="VVPP" in="-5:vobj" out="">eingeführt</W>
<W lemma="und" msd="CC" tag="KON" in="5:coord" out="">und</W>
<W lemma="in" msd="SP" tag="APPR" in="4:loc" out="1:nobj">in</W>
<W lemma="Höhe" msd="NC" tag="NN" in="-1:nobj" out="">Höhe</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Verengung" msd="NC" tag="NN" in="-1:nobj" out="">Verengungen</W>
<W lemma="aufblasen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:coord|-4:loc">aufgeblasen</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-10:vobj" out="-9:subj|-1:vobj">wird</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="meist" msd="RG" tag="ADV" in="1:add" out="">Meist</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:add|1:subj|11:pnct">werden</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|4:pnct|9:relr">die</W>
<W lemma="Gefäßchirurg" msd="NC" tag="NN" in="-1:nobj" out="">Gefäßchirurgen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:dobj" out="1:attr|3:attr|4:nobj">die</W>
<W lemma="alt" msd="AN" tag="ADJA" in="-1:attr" out="">alten</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="zerstört" msd="AN" tag="ADJA" in="-3:attr" out="">zerstörten</W>
<W lemma="Ader" msd="NC" tag="NN" in="-4:nobj" out="">Adern</W>
<W lemma="durch" msd="SP" tag="APPR" in="2:man" out="1:nobj">durch</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Kunstadern</W>
<W lemma="ersetzen" msd="VA" tag="VVFIN" in="-9:relr" out="-7:dobj|-2:man">ersetzen</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="schlecht" msd="AN" tag="ADJA" in="1:attr" out="">Schlechte</W>
<W lemma="Vene" msd="NC" tag="NN" in="3:subj" out="-1:attr|1:attr">Venen</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">mit</W>
<W lemma="Krampfader" msd="NC" tag="NN" in="-1:nobj" out="">Krampfadern</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-3:subj|4:vobj|5:pnct|6:cons|19:pnct">können</W>
<W lemma="mit" msd="SP" tag="APPR" in="2:pobj" out="1:nobj">mit</W>
<W lemma="Stützstrumpf" msd="NC" tag="NN" in="-1:nobj" out="">Stützstrümpfen</W>
<W lemma="behandeln" msd="VAP" tag="VVPP" in="1:vobj" out="-2:pobj">behandelt</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-4:vobj" out="-1:vobj">werden</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="so" msd="RG" tag="ADV" in="-6:cons" out="1:nobj">so</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-1:nobj" out="5:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="1:nobj|10:relr">die</W>
<W lemma="Ader" msd="NC" tag="NN" in="-1:nobj" out="">Adern</W>
<W lemma="zusammen" msd="RG" tag="ADV" in="8:man" out="">zusammen</W>
<W lemma="drücken" msd="VAP" tag="VVPP" in="1:vobj" out="">gedrückt</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-1:vobj">werden</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="-1:coord|1:nobj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="2:robj" out="">sich</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="1:neg" out="">nicht</W>
<W lemma="stauen" msd="VA" tag="VVFIN" in="-10:relr" out="-8:man|-4:subj|-2:robj|-1:neg">staut</W>
<W lemma="." msd="XP" tag="$." in="-19:pnct" out="">.</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">Es</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:subj|1:conc|2:preds|4:pnct|8:preds|10:pnct">ist</W>
<W lemma="aber" msd="RG" tag="ADV" in="-1:conc" out="">aber</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-2:preds" out="1:vobj">zu</W>
<W lemma="bevorzugen" msd="VAF" tag="VVINF" in="-1:vobj" out="">bevorzugen</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:dobj" out="1:attr|2:nobj">die</W>
<W lemma="schlecht" msd="AN" tag="ADJA" in="-1:attr" out="">schlechten</W>
<W lemma="Vene" msd="NC" tag="NN" in="-2:nobj" out="">Venen</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-8:preds" out="1:vobj">zu</W>
<W lemma="entfernen" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:dobj">entfernen</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
<W lemma="anschließend" msd="AN" tag="ADJD" in="1:subj" out="">Anschließend</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-1:subj|7:vobj|8:pnct|15:pnct">kann</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="1:nobj">das</W>
<W lemma="Blut" msd="NC" tag="NN" in="-1:nobj" out="">Blut</W>
<W lemma="durch" msd="SP" tag="APPR" in="4:man" out="1:nobj">durch</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">die</W>
<W lemma="tief" msd="AN" tag="ADJA" in="-1:attr" out="">tiefen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="">Bein-Venen</W>
<W lemma="laufen" msd="VAF" tag="VVINF" in="-7:vobj" out="-6:dobj|-4:man|7:relr">laufen</W>
<W lemma="," msd="XP" tag="$," in="-8:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="5:subj" out="">die</W>
<W lemma="in" msd="SP" tag="APPR" in="4:loc" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Regel" msd="NC" tag="NN" in="-1:nobj" out="">Regel</W>
<W lemma="normal" msd="AN" tag="ADJD" in="1:man" out="">normal</W>
<W lemma="arbeiten" msd="VA" tag="VVFIN" in="-7:relr" out="-5:subj|-4:loc|-1:man">arbeiten</W>
<W lemma="." msd="XP" tag="$." in="-15:pnct" out="">.</W>
</s>
</p>
