<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Der</W>
<W lemma="Fußbodenbelag" msd="NC" tag="NN" in="-1:nobj" out="">Fußbodenbelag</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="" out="-2:subj|7:vobj|8:pnct">muss</W>
<W lemma="robust" msd="AN" tag="ADJD" in="6:preds" out="2:conj">robust</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="leicht" msd="AN" tag="ADJD" in="-2:conj" out="-1:coord">leicht</W>
<W lemma="sauber" msd="AN" tag="ADJD" in="3:preds" out="">sauber</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="2:preds" out="1:vobj">zu</W>
<W lemma="halten" msd="VAF" tag="VVINF" in="-1:vobj" out="">halten</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-7:vobj" out="-6:preds|-3:preds|-2:preds">sein</W>
<W lemma="." msd="XP" tag="$." in="-8:pnct" out="">.</W>
<W lemma="nirgends" msd="RG" tag="ADV" in="1:add" out="">Nirgends</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:add|1:subj|4:subj|10:vobj|11:pnct|16:pnct">ist</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Fußböden" msd="NC" tag="NN" in="-1:nobj" out="">Fußboden</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="9:nobj">so</W>
<W lemma="viel" msd="PI" tag="PIAT" in="-4:subj" out="-1:quant|1:nobj">viel</W>
<W lemma="Verschmutzung" msd="NC" tag="NN" in="-1:nobj" out="">Verschmutzung</W>
<W lemma="durch" msd="SP" tag="APPR" in="4:man" out="1:nobj">durch</W>
<W lemma="Fett" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Fett</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Schmutz" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Schmutz</W>
<W lemma="aussetzen" msd="VAP" tag="VVPP" in="-10:vobj" out="-4:man">ausgesetzt</W>
<W lemma="," msd="XP" tag="$," in="-11:pnct" out="">,</W>
<W lemma="wie" msd="CS" tag="KOUS" in="-9:nobj" out="1:pobj">wie</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Küche" msd="NC" tag="NN" in="-1:nobj" out="">Küche</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="1:time" out="">Gleichzeitig</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="" out="-1:time|1:subj|3:add|10:vobj|11:pnct">muss</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Fußböden" msd="NC" tag="NN" in="-1:nobj" out="">Fußboden</W>
<W lemma="auch" msd="RG" tag="ADV" in="-3:add" out="">auch</W>
<W lemma="bei" msd="SP" tag="APPR" in="5:man" out="2:nobj">bei</W>
<W lemma="lang" msd="AN" tag="ADJA" in="1:attr" out="">längerem</W>
<W lemma="Stehen" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|2:conj">Stehen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Gehen" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Gehen</W>
<W lemma="angenehm" msd="AN" tag="ADJD" in="1:preds" out="-5:man">angenehm</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-10:vobj" out="-1:preds">sein</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="ein" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Ein</W>
<W lemma="Holzfußböden" msd="NC" tag="NN" in="-1:nobj" out="">Holzfußboden</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-2:subj|2:preds|3:pnct|4:cons|17:pnct">ist</W>
<W lemma="ausreichend" msd="AN" tag="ADJD" in="1:quant" out="">ausreichend</W>
<W lemma="weich" msd="AN" tag="ADJD" in="-2:preds" out="-1:quant">weich</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="so" msd="RG" tag="ADV" in="-4:cons" out="1:nobj">so</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-1:nobj" out="11:vobj">dass</W>
<W lemma="man" msd="PP" tag="PIS" in="10:subj" out="">man</W>
<W lemma="selbst" msd="RG" tag="ADV" in="9:man" out="">selbst</W>
<W lemma="nach" msd="SP" tag="APPR" in="8:time" out="2:nobj">nach</W>
<W lemma="lang" msd="AN" tag="ADJA" in="1:attr" out="">längerem</W>
<W lemma="Gehen" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|2:conj">Gehen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Stehen" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Stehen</W>
<W lemma="kein" msd="PI" tag="PIAT" in="3:dobj" out="1:attr|2:nobj">keine</W>
<W lemma="müde" msd="AN" tag="ADJA" in="-1:attr" out="">müden</W>
<W lemma="Bein" msd="NC" tag="NN" in="-2:nobj" out="">Beine</W>
<W lemma="bekommen" msd="VA" tag="VVFIN" in="-11:vobj" out="-10:subj|-9:man|-8:time|-3:dobj">bekommt</W>
<W lemma="." msd="XP" tag="$." in="-17:pnct" out="">.</W>
<W lemma="aber" msd="CC" tag="KON" in="6:coord" out="">Aber</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="5:subj" out="1:attr">ein</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="2:conj">unbehandelter</W>
<W lemma="oder" msd="CC" tag="KON" in="1:coord" out="">oder</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-2:conj" out="-1:coord|1:nobj">gelaugter</W>
<W lemma="Holzfußböden" msd="NC" tag="NN" in="-1:nobj" out="">Holzfußboden</W>
<W lemma="gehören" msd="VA" tag="VVFIN" in="" out="-6:coord|-5:subj|1:neg|2:pobj|5:pnct">gehört</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-1:neg" out="">nicht</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:pobj" out="1:nobj">in</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">eine</W>
<W lemma="Küche" msd="NC" tag="NN" in="-1:nobj" out="">Küche</W>
<W lemma="." msd="XP" tag="$." in="-5:pnct" out="">.</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:subj|5:vobj|9:conj">würde</W>
<W lemma="alle" msd="PI" tag="PIAT" in="8:subj" out="1:nobj">alle</W>
<W lemma="Fettfleck" msd="NC" tag="NN" in="-1:nobj" out="">Fettflecken</W>
<W lemma="wie" msd="CS" tag="KOKOM" in="2:man" out="1:nobj">wie</W>
<W lemma="Löschpapier" msd="NC" tag="NN" in="-1:nobj" out="">Löschpapier</W>
<W lemma="aufsaugen" msd="VAF" tag="VVINF" in="-5:vobj" out="-2:man|22:conj">aufsaugen</W>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">das</W>
<W lemma="Ergebnis" msd="NC" tag="NN" in="-1:nobj" out="">Ergebnis</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-9:conj" out="-8:subj|-3:coord|-2:subj|1:time|4:preds|10:pnct|11:cause|19:pnct">wäre</W>
<W lemma="nach" msd="SP" tag="APPR" in="-1:time" out="2:nobj">nach</W>
<W lemma="kurz" msd="AN" tag="ADJA" in="1:attr" out="">kurzer</W>
<W lemma="Zeit" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Zeit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-4:preds" out="1:nobj|4:attr|5:nobj">ein</W>
<W lemma="traurig" msd="AN" tag="ADJD" in="-1:nobj" out="2:conj">traurig</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="schmutzig" msd="AN" tag="ADJD" in="-2:conj" out="-1:coord">schmutzig</W>
<W lemma="aussehend" msd="AN" tag="ADJA" in="-4:attr" out="">aussehender</W>
<W lemma="Boden" msd="NC" tag="NN" in="-5:nobj" out="">Boden</W>
<W lemma="," msd="XP" tag="$," in="-10:pnct" out="">,</W>
<W lemma="denn" msd="CC" tag="KON" in="-11:cause" out="3:vobj">denn</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">die</W>
<W lemma="Fleck&7c;Flecken" msd="NC" tag="NN" in="-1:nobj" out="">Flecken</W>
<W lemma="lassen" msd="VA" tag="VVFIN" in="-3:vobj" out="-2:subj|2:neg">lassen</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="3:robj" out="">sich</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-2:neg" out="">nicht</W>
<W lemma="mehr" msd="RG" tag="ADV" in="1:dobj" out="">mehr</W>
<W lemma="entfernen" msd="VAF" tag="VVINF" in="-22:conj" out="-3:robj|-1:dobj">entfernen</W>
<W lemma="." msd="XP" tag="$." in="-19:pnct" out="">.</W>
<W lemma="entscheiden" msd="VAM" tag="VVIMP" in="9:cond" out="1:subj|8:pnct">Entscheidet</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="7:robj" out="">sich</W>
<W lemma="hingegen" msd="RG" tag="ADV" in="1:quant" out="">hingegen</W>
<W lemma="für" msd="SP" tag="APPR" in="5:goal" out="-1:quant|1:nobj">für</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einen</W>
<W lemma="lackiert" msd="AN" tag="ADJA" in="-1:attr" out="">lackierten</W>
<W lemma="Holzböden" msd="NC" tag="NN" in="-2:nobj" out="">Holzboden</W>
<W lemma="," msd="XP" tag="$," in="-8:pnct" out="">,</W>
<W lemma="vermeiden" msd="VA" tag="VVFIN" in="" out="-9:cond|-7:robj|-5:goal|1:subj|2:dobj|4:pnct">vermeidet</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-2:dobj" out="1:nobj">dieses</W>
<W lemma="Problem" msd="NC" tag="NN" in="-1:nobj" out="">Problem</W>
<W lemma="." msd="XP" tag="$." in="-4:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="Linoleum" msd="NC" tag="NN" in="1:subj" out="">Linoleum</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:subj|9:vobj|11:conj|15:pnct">wurde</W>
<W lemma="über" msd="SP" tag="APPR" in="8:pobj" out="2:nobj">über</W>
<W lemma="lang" msd="AN" tag="ADJA" in="1:attr" out="">lange</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Jahre</W>
<W lemma="als" msd="CS" tag="KOKOM" in="10:man" out="1:nobj">als</W>
<W lemma="Fußbodenbelag" msd="NC" tag="NN" in="-1:nobj" out="">Fußbodenbelag</W>
<W lemma="in" msd="SP" tag="APPR" in="3:loc" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Küche" msd="NC" tag="NN" in="-1:nobj" out="">Küche</W>
<W lemma="verwenden" msd="VAP" tag="VVPP" in="-9:vobj" out="-8:pobj|-3:loc">verwendet</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-11:conj" out="-1:coord|3:vobj">hat</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="2:dobj" out="">sich</W>
<W lemma="glänzend" msd="AN" tag="ADJD" in="1:man" out="">glänzend</W>
<W lemma="bewähren" msd="VAP" tag="VVPP" in="-3:vobj" out="-10:man|-2:dobj|-1:man">bewährt</W>
<W lemma="." msd="XP" tag="$." in="-15:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="Linoleum" msd="NC" tag="NN" in="1:subj" out="">Linoleum</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:subj|12:preds|13:pnct">ist</W>
<W lemma="sowohl" msd="CC" tag="KON" in="5:correl" out="">sowohl</W>
<W lemma="in" msd="SP" tag="APPR" in="4:correl" out="2:nobj|3:pnct">in</W>
<W lemma="ganz" msd="AN" tag="ADJA" in="1:attr" out="">ganzen</W>
<W lemma="Bahn&7c;Bahnen" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Bahnen</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="als" msd="CS" tag="KOKOM" in="2:coord" out="-5:correl|-4:correl">als</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="in" msd="SP" tag="APPR" in="4:pobj" out="-2:coord|-1:add|1:nobj">in</W>
<W lemma="Form" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Form</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">von</W>
<W lemma="Platte&7c;Platten" msd="NC" tag="NN" in="-1:nobj" out="">Platten</W>
<W lemma="erhältlich" msd="AN" tag="ADJD" in="-12:preds" out="-4:pobj">erhältlich</W>
<W lemma="." msd="XP" tag="$." in="-13:pnct" out="">.</W>
<W lemma="einfarbig" msd="AN" tag="ADJD" in="1:correl" out="">Einfarbig</W>
<W lemma="oder" msd="CC" tag="KON" in="1:coord" out="-1:correl">oder</W>
<W lemma="melieren" msd="VA" tag="VVFIN" in="" out="-1:coord|1:pnct">meliert</W>
<W lemma="." msd="XP" tag="$." in="-1:pnct" out="">.</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="5:nobj">Es</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:subj|1:preds|2:pnct|8:conj">ist</W>
<W lemma="angenehm" msd="AN" tag="ADJD" in="-1:preds" out="">angenehm</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="darauf" msd="RG" tag="PAV" in="2:pobj" out="">darauf</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-5:nobj" out="1:vobj|9:nobj">zu</W>
<W lemma="gehen" msd="VAF" tag="VVINF" in="-1:vobj" out="-2:pobj">gehen</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">er</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-8:conj" out="-2:coord|-1:subj|1:preds|4:eval|7:pnct">ist</W>
<W lemma="leicht" msd="AN" tag="ADJD" in="-1:preds" out="">leicht</W>
<W lemma="mit" msd="SP" tag="APPR" in="4:pobj" out="1:nobj">mit</W>
<W lemma="Seifenwasser" msd="NC" tag="NN" in="-1:nobj" out="">Seifenwasser</W>
<W lemma="sauber" msd="AN" tag="ADJD" in="-4:eval" out="">sauber</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-9:nobj" out="1:vobj">zu</W>
<W lemma="halten" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:pobj">halten</W>
<W lemma="." msd="XP" tag="$." in="-7:pnct" out="">.</W>
<W lemma="Linoleum" msd="NC" tag="NN" in="1:subj" out="">Linoleum</W>
<W lemma="eignen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:dobj|2:add|3:man|4:pobj|9:pnct">eignet</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-1:dobj" out="">sich</W>
<W lemma="auch" msd="RG" tag="ADV" in="-2:add" out="">auch</W>
<W lemma="gut" msd="AN" tag="ADJD" in="-3:man" out="">gut</W>
<W lemma="für" msd="SP" tag="APPR" in="-4:pobj" out="1:nobj">für</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">den</W>
<W lemma="Küchentisch" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Küchentisch</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Luke" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Luken</W>
<W lemma="." msd="XP" tag="$." in="-9:pnct" out="">.</W>
</s>
</p>
