<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">Die</W>
<W lemma="USA" msd="NP" tag="NE" in="" out="">USA</W>
<W lemma="betrachten" msd="VA" tag="VVFIN" in="" out="">betrachten</W>
<W lemma="es" msd="PP" tag="PPER" in="" out="">es</W>
<W lemma="als" msd="CS" tag="KOKOM" in="" out="">als</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="" out="">ihr</W>
<W lemma="eindeutig" msd="AN" tag="ADJA" in="" out="">eindeutiges</W>
<W lemma="Interesse" msd="NC" tag="NN" in="" out="">Interesse</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europa</W>
<W lemma="zu" msd="SP" tag="APPR" in="" out="">zu</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">einem</W>
<W lemma="stark" msd="AN" tag="ADJA" in="" out="">starken</W>
<W lemma="politisch" msd="AN" tag="ADJA" in="" out="">politischen</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="wirtschaftlich" msd="AN" tag="ADJA" in="" out="">wirtschaftlichen</W>
<W lemma="Faktor" msd="NC" tag="NN" in="" out="">Faktor</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neuen</W>
<W lemma="Weltordnung" msd="NC" tag="NN" in="" out="">Weltordnung</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">wird</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="dadurch" msd="RG" tag="PAV" in="" out="">Dadurch</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">würden</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="weltweit" msd="AN" tag="ADJA" in="" out="">weltweiten</W>
<W lemma="Aufgabe" msd="NC" tag="NN" in="" out="">Aufgaben</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="USA" msd="NP" tag="NE" in="" out="">USA</W>
<W lemma="erleichtert" msd="AN" tag="ADJD" in="" out="">erleichtert</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="" out="">gleichzeitig</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">ein</W>
<W lemma="reich" msd="AN" tag="ADJA" in="" out="">reicher</W>
<W lemma="Markt" msd="NC" tag="NN" in="" out="">Markt</W>
<W lemma="für" msd="SP" tag="APPR" in="" out="">für</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="amerikanisch" msd="AN" tag="ADJA" in="" out="">amerikanischen</W>
<W lemma="Export" msd="NC" tag="NN" in="" out="">Export</W>
<W lemma="öffnen" msd="VAP" tag="VVPP" in="" out="">geöffnet</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="aber" msd="CC" tag="KON" in="" out="">Aber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="Aussicht" msd="NC" tag="NN" in="" out="">Aussichten</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">das</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neue</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="vereint" msd="AN" tag="ADJA" in="" out="">vereinte</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europa</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="EG" msd="NC" tag="NN" in="" out="">EG</W>
<W lemma="als" msd="CS" tag="KOKOM" in="" out="">als</W>
<W lemma="politisch" msd="AN" tag="ADJA" in="" out="">politischem</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="wirtschaftlich" msd="AN" tag="ADJA" in="" out="">wirtschaftlichem</W>
<W lemma="Dynamo" msd="NP" tag="NE" in="" out="">Dynamo</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Deutschland" msd="NP" tag="NE" in="" out="">Deutschland</W>
<W lemma="als" msd="CS" tag="KOKOM" in="" out="">als</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neuer</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="" out="">tonangebender</W>
<W lemma="Großmacht" msd="NC" tag="NN" in="" out="">Großmacht</W>
<W lemma="beunruhigen" msd="VA" tag="VVFIN" in="" out="">beunruhigt</W>
<W lemma="trotzdem" msd="RG" tag="PAV" in="" out="">trotzdem</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">einen</W>
<W lemma="Teil" msd="NC" tag="NN" in="" out="">Teil</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="Amerikaner" msd="NC" tag="NN" in="" out="">Amerikaner</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="Sie&7c;sie" msd="PP" tag="PPER" in="" out="">Sie</W>
<W lemma="fühlen" msd="VA" tag="VVFIN" in="" out="">fühlen</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="" out="">sich</W>
<W lemma="verdrängen" msd="VAP" tag="VVPP" in="" out="">verdrängt</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="sehen" msd="VAF" tag="VVINF" in="" out="">sehen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="dabei" msd="RG" tag="PAV" in="" out="">dabei</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">sind</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europa</W>
<W lemma="an" msd="SP" tag="APPR" in="" out="">an</W>
<W lemma="Einfluß" msd="NC" tag="NN" in="" out="">Einfluss</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="" out="">zu</W>
<W lemma="verlieren" msd="VAF" tag="VVINF" in="" out="">verlieren</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="wo" msd="PT" tag="PWAV" in="" out="">wo</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="knapp" msd="AN" tag="ADJD" in="" out="">knapp</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">ein</W>
<W lemma="halb" msd="AN" tag="ADJA" in="" out="">halbes</W>
<W lemma="Jahrhundert" msd="NC" tag="NN" in="" out="">Jahrhundert</W>
<W lemma="lang" msd="AN" tag="ADJD" in="" out="">lang</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">eine</W>
<W lemma="so" msd="RG" tag="ADV" in="" out="">so</W>
<W lemma="dominierend" msd="AN" tag="ADJA" in="" out="">dominierende</W>
<W lemma="Rolle" msd="NC" tag="NN" in="" out="">Rolle</W>
<W lemma="spielen" msd="VAP" tag="VVPP" in="" out="">gespielt</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="">haben</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="">Auf</W>
<W lemma="etwas" msd="PP" tag="PIS" in="" out="">etwas</W>
<W lemma="lang" msd="AN" tag="ADJA" in="" out="">längere</W>
<W lemma="Sicht" msd="NC" tag="NN" in="" out="">Sicht</W>
<W lemma="sehen" msd="VA" tag="VVFIN" in="" out="">sehen</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="" out="">dass</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europa</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="" out="">zum</W>
<W lemma="politisch" msd="AN" tag="ADJA" in="" out="">politischen</W>
<W lemma="Rivale" msd="NC" tag="NN" in="" out="">Rivalen</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="wirtschaftlich" msd="AN" tag="ADJA" in="" out="">wirtschaftlichen</W>
<W lemma="Konkurrent" msd="NC" tag="NN" in="" out="">Konkurrenten</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">wird</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="d" msd="PT" tag="PRELS" in="" out="">das</W>
<W lemma="bekommen" msd="VA" tag="VVFIN" in="" out="">bekommt</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="" out="">nicht</W>
<W lemma="alle" msd="PP" tag="PIS" in="" out="">allen</W>
<W lemma="gleich" msd="SP" tag="APPR" in="" out="">gleich</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">gut.</W>
</s>
</p>
<p>
<s>
<W lemma="in" msd="SP" tag="APPR" in="" out="">In</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="kommend" msd="AN" tag="ADJA" in="" out="">kommenden</W>
<W lemma="Jahr" msd="NC" tag="NN" in="" out="">Jahren</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">wird</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europa</W>
<W lemma="enorm" msd="AN" tag="ADJA" in="" out="">enormen</W>
<W lemma="Herausforderung" msd="NC" tag="NN" in="" out="">Herausforderungen</W>
<W lemma="gegenüber" msd="SP" tag="APPO" in="" out="">gegenüber</W>
<W lemma="stehen" msd="VA" tag="VVFIN" in="" out="">stehen</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="" out="">muss</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neue</W>
<W lemma="Weg" msd="NC" tag="NN" in="" out="">Wege</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Rolle&7c;Rollen" msd="NC" tag="NN" in="" out="">Rollen</W>
<W lemma="sowohl" msd="CC" tag="KON" in="" out="">sowohl</W>
<W lemma="für" msd="SP" tag="APPR" in="" out="">für</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="" out="">sich</W>
<W lemma="selbst" msd="RG" tag="ADV" in="" out="">selbst</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="als" msd="CS" tag="KOUS" in="" out="">als</W>
<W lemma="auch" msd="RG" tag="ADV" in="" out="">auch</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="" out="">seinem</W>
<W lemma="Verhältnis" msd="NC" tag="NN" in="" out="">Verhältnis</W>
<W lemma="zu" msd="SP" tag="APPR" in="" out="">zu</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="alt" msd="AN" tag="ADJA" in="" out="">alten</W>
<W lemma="Supermacht" msd="NC" tag="NN" in="" out="">Supermächten</W>
<W lemma="finden" msd="VA" tag="VVFIN" in="" out="">finden</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="aus" msd="SP" tag="APPR" in="" out="">Aus</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="jeweilig" msd="AN" tag="ADJA" in="" out="">jeweiligen</W>
<W lemma="Eck&7c;Ecke&7c;Ecken" msd="NC" tag="NN" in="" out="">Ecken</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="Welt" msd="NC" tag="NN" in="" out="">Welt</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="">werden</W>
<W lemma="Moskau" msd="NP" tag="NE" in="" out="">Moskau</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Washington" msd="NP" tag="NE" in="" out="">Washington</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neuen</W>
<W lemma="Kurs" msd="NC" tag="NN" in="" out="">Kurs</W>
<W lemma="Europa" msd="NP" tag="NE" in="" out="">Europas</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">einer</W>
<W lemma="Mischung" msd="NC" tag="NN" in="" out="">Mischung</W>
<W lemma="wohlwollend" msd="AN" tag="ADJA" in="" out="">wohlwollenden</W>
<W lemma="Interesse" msd="NC" tag="NN" in="" out="">Interesses</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="Neugier" msd="NC" tag="NN" in="" out="">Neugier</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Achtsamkeit" msd="NC" tag="NN" in="" out="">Achtsamkeit</W>
<W lemma="verfolgen" msd="VA" tag="VVFIN" in="" out="">verfolgen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="während" msd="CS" tag="KOUS" in="" out="">während</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">ein</W>
<W lemma="neu" msd="AN" tag="ADJA" in="" out="">neues</W>
<W lemma="global" msd="AN" tag="ADJA" in="" out="">globales</W>
<W lemma="Spannungsfeld" msd="NC" tag="NN" in="" out="">Spannungsfeld</W>
<W lemma="Form" msd="NC" tag="NN" in="" out="">Form</W>
<W lemma="annehmen" msd="VA" tag="VVFIN" in="" out="">annimmt</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
</s>
</p>
