<p>
<s>
<W lemma="vor" msd="SP" tag="APPR" in="3:time" out="1:nobj">Vor</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Untersuchungsrichter" msd="NC" tag="NN" in="-1:nobj" out="">Untersuchungsrichter</W>
<W lemma="bringen" msd="VA" tag="VVFIN" in="" out="-3:time|2:subj|5:add|6:subj">brachte</W>
<W lemma="Michael" msd="NP" tag="NE" in="1:namef" out="">Michael</W>
<W lemma="Christianse" msd="NC" tag="NN" in="-2:subj" out="-1:namef|1:attr">Christiansen</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-1:attr" out="1:nobj">am</W>
<W lemma="Mittwoch" msd="NC" tag="NN" in="-1:nobj" out="">Mittwoch</W>
<W lemma="auch" msd="RG" tag="ADV" in="-5:add" out="">auch</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="-6:subj" out="1:possd">sein</W>
<W lemma="Erstaunen" msd="NC" tag="NN" in="-1:possd" out="1:attr">Erstaunen</W>
<W lemma="über" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">über</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">die</W>
<W lemma="Erklärung" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Erklärung</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:pobj" out="2:nobj|3:pobj">von</W>
<W lemma="Erik" msd="NP" tag="NE" in="1:namef" out="">Erik</W>
<W lemma="Ninn-Hansen" msd="NP" tag="NE" in="-2:nobj" out="-1:namef">Ninn-Hansen</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="-3:pobj" out="1:nobj|2:pnct|3:nobj">zum</W>
<W lemma="Ausdruck" msd="NC" tag="NN" in="-1:nobj" out="">Ausdruck</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-3:nobj" out="">dass</W>
<W lemma="er" msd="PP" tag="PPER" in="3:subj" out="">er</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="2:nobj">im</W>
<W lemma="Dezember" msd="NC" tag="NN" in="1:nobj" out="">Dezember</W>
<W lemma="1987" msd="AC" tag="CARD" in="-2:nobj" out="-3:subj|-1:nobj|1:time">1987</W>
<W lemma="vor" msd="SP" tag="APPR" in="-1:time" out="1:nobj">vor</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Hintergrund" msd="NC" tag="NN" in="-1:nobj" out="">Hintergrund</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Notiz" msd="NC" tag="NN" in="-1:nobj" out="">Notiz</W>
<W lemma="vom" msd="SP+P" tag="APPRART" in="" out="1:attr">vom</W>
<W lemma="2." msd="AN" tag="ADJA" in="-1:attr" out="">2.</W>
<W lemma="Dezember" msd="NC" tag="NN" in="9:qobj" out="">Dezember</W>
<W lemma="d" msd="PP" tag="PDS" in="10:dobj" out="1:pnct|8:relr">das</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="was" msd="PT" tag="PWS" in="6:dobj" out="">was</W>
<W lemma="er" msd="PP" tag="PPER" in="9:subj" out="">er</W>
<W lemma="selbst" msd="RG" tag="ADV" in="4:man" out="">selbst</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="3:dobj" out="1:nobj">eine</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:pnct">,,Richtlinie</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="nennen" msd="VA" tag="VVFIN" in="-8:relr" out="-9:qobj|-6:dobj|-4:man|-3:dobj|1:pnct">nennt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="ausgeben" msd="VAP" tag="VVPP" in="1:vobj" out="-10:dobj">ausgegeben</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="1:vobj" out="-1:vobj">haben</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="" out="-9:subj|-1:vobj|1:pnct|2:dobj|20:pnct">soll</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="8:vobj|10:pnct|11:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:nobj">die</W>
<W lemma="Familienzusammenführung" msd="NC" tag="NN" in="-1:nobj" out="">Familienzusammenführungen</W>
<W lemma="mit" msd="SP" tag="APPR" in="4:pobj" out="2:nobj">mit</W>
<W lemma="gering" msd="AN" tag="ADJA" in="1:attr" out="">geringerer</W>
<W lemma="Priorität" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Priorität</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="2:preds" out="1:vobj">zu</W>
<W lemma="behandeln" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:pobj">behandeln</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-8:vobj" out="-7:subj|-2:preds">sind</W>
<W lemma="und" msd="CC" tag="KON" in="8:coord" out="">und</W>
<W lemma="," msd="XP" tag="$," in="-10:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-11:vobj" out="6:vobj">dass</W>
<W lemma="davon" msd="RG" tag="PAV" in="5:conc" out="">davon</W>
<W lemma="insbesondere" msd="RG" tag="ADV" in="1:quant" out="">insbesondere</W>
<W lemma="tamilisch" msd="AN" tag="ADJA" in="1:attr" out="-1:quant">tamilische</W>
<W lemma="Flüchtling" msd="NC" tag="NN" in="2:preds" out="-1:attr">Flüchtlinge</W>
<W lemma="betreffen" msd="VAP" tag="VVPP" in="1:vobj" out="">betroffen</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-6:vobj" out="-8:coord|-5:conc|-2:preds|-1:vobj">sind</W>
<W lemma="." msd="XP" tag="$." in="-20:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Der</W>
<W lemma="Abteilungsleiter" msd="NC" tag="NN" in="-1:nobj" out="">Abteilungsleiter</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-2:subj|1:eval|2:neg|3:quant|9:vobj|10:pnct">war</W>
<W lemma="jedoch" msd="RG" tag="ADV" in="-1:eval" out="">jedoch</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-2:neg" out="">nicht</W>
<W lemma="nur" msd="RG" tag="ADV" in="-3:quant" out="">nur</W>
<W lemma="über" msd="SP" tag="APPR" in="5:pobj" out="2:nobj">über</W>
<W lemma="Ninn-Hansen" msd="NP" tag="NE" in="1:namef" out="">Ninn-Hansens</W>
<W lemma="Erklärung" msd="NC" tag="NN" in="-2:nobj" out="-1:namef">Erklärung</W>
<W lemma="vor" msd="SP" tag="APPR" in="2:time" out="1:nobj">vor</W>
<W lemma="Gericht" msd="NC" tag="NN" in="-1:nobj" out="">Gericht</W>
<W lemma="überraschen" msd="VAP" tag="VVPP" in="-9:vobj" out="-5:pobj|-2:time">überrascht</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
<W lemma="aus" msd="SP" tag="APPR" in="" out="1:nobj">Aus</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:attr">dem</W>
<W lemma="Verhör" msd="NC" tag="NN" in="-1:nobj" out="">Verhör</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-2:attr" out="1:nobj">am</W>
<W lemma="Mittwoch" msd="NC" tag="NN" in="-1:nobj" out="">Mittwoch</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="1:add|2:part|3:pnct|4:dobj|15:pnct">ging</W>
<W lemma="auch" msd="RG" tag="ADV" in="-1:add" out="">auch</W>
<W lemma="hervor" msd="RG" tag="PTKVZ" in="-2:part" out="">hervor</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:dobj" out="10:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="9:subj" out="1:nobj">die</W>
<W lemma="Erklärung" msd="NC" tag="NN" in="-1:nobj" out="">Erklärungen</W>
<W lemma="früh" msd="AN" tag="ADJA" in="1:attr" out="">früherer</W>
<W lemma="Kollege" msd="NC" tag="NN" in="6:dobj" out="-1:attr|1:attr">Kollegen</W>
<W lemma="aus" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">aus</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Justizministerien" msd="NC" tag="NN" in="-1:nobj" out="">Justizministerium</W>
<W lemma="er" msd="PP" tag="PPER" in="2:dobj" out="">ihn</W>
<W lemma="ebenfalls" msd="RG" tag="ADV" in="1:prg" out="">ebenfalls</W>
<W lemma="wundern" msd="VA" tag="VVFIN" in="-10:vobj" out="-9:subj|-6:dobj|-2:dobj|-1:prg">wunderten</W>
<W lemma="." msd="XP" tag="$." in="-15:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="vor" msd="SP" tag="APPR" in="2:time" out="1:nobj">Vor</W>
<W lemma="Gericht" msd="NC" tag="NN" in="-1:nobj" out="">Gericht</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-2:time|1:dobj|7:vobj|8:pnct|10:conj|16:pnct">hat</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:dobj" out="1:nobj">eine</W>
<W lemma="Reihe" msd="NC" tag="NN" in="-1:nobj" out="2:nobj">Reihe</W>
<W lemma="herausragender" msd="AN" tag="ADJA" in="1:attr" out="">herausragender</W>
<W lemma="Beamter" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Beamter</W>
<W lemma="sehr" msd="RG" tag="ADV" in="1:quant" out="">sehr</W>
<W lemma="eingehend" msd="AN" tag="ADJD" in="1:man" out="-1:quant">eingehend</W>
<W lemma="erklären" msd="VAP" tag="VVPP" in="-7:vobj" out="-1:man">erklärt</W>
<W lemma="," msd="XP" tag="$," in="-8:pnct" out="">,</W>
<W lemma="wie" msd="CS" tag="KOUS" in="1:man" out="">wie</W>
<W lemma="beunruhigen" msd="VA" tag="VVFIN" in="-10:conj" out="-1:man|1:subj|5:vobj">beunruhigt</W>
<W lemma="sie" msd="PP" tag="PPER" in="-1:subj" out="">sie</W>
<W lemma="über" msd="SP" tag="APPR" in="3:preds" out="1:nobj">über</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">den</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Tamilen-Stopp</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:vobj" out="-3:preds">sind</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">Auch</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="3:time" out="-1:add">wenn</W>
<W lemma="Michael" msd="NP" tag="NE" in="1:namef" out="">Michael</W>
<W lemma="Christianse" msd="NC" tag="NN" in="" out="-1:namef|1:aobj">Christiansen</W>
<W lemma="spät" msd="AN" tag="ADJD" in="-1:aobj" out="-3:time|1:pobj|9:exem">später</W>
<W lemma="bei" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">bei</W>
<W lemma="mehrere" msd="PI" tag="PIAT" in="-1:nobj" out="1:nobj">mehreren</W>
<W lemma="Gelegenheit" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Gelegenheiten</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="-1:nobj" out="1:attr|2:possd|3:pnct">seinen</W>
<W lemma="früh" msd="AN" tag="ADJA" in="-1:attr" out="">früheren</W>
<W lemma="Kollege" msd="NC" tag="NN" in="-2:possd" out="">Kollegen</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="um" msd="SP" tag="APPR" in="-9:exem" out="">u.</W>
<W lemma="A." msd="NP" tag="NE" in="15:subj" out="1:dobj">A.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:dobj" out="1:nobj">den</W>
<W lemma="Leiter" msd="NC" tag="NN" in="-1:nobj" out="">Leiter</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj|2:pnct|10:relr">des</W>
<W lemma="Ausländeramt" msd="NC" tag="NN" in="-1:nobj" out="">Ausländeramtes</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="Frederik" msd="NP" tag="NE" in="1:namef" out="">Frederik</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="6:subj" out="-1:namef|1:pnct">Schydt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="über" msd="SP" tag="APPR" in="3:pobj" out="1:nobj">über</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">den</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Tamilenvorgang</W>
<W lemma="sprechen" msd="VAP" tag="VVPP" in="1:vobj" out="-3:pobj">gesprochen</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-10:relr" out="-6:subj|-1:vobj|1:pnct">hat</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-15:subj|1:subj|2:dobj|4:time|6:vobj|10:pnct|11:conj|14:pnct">haben</W>
<W lemma="dies" msd="PP" tag="PDS" in="-1:subj" out="">diese</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-2:dobj" out="1:possd">ihre</W>
<W lemma="Sorge&7c;Sorgen" msd="NC" tag="NN" in="-1:possd" out="">Sorgen</W>
<W lemma="nie" msd="RG" tag="ADV" in="-4:time" out="">nie</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="">so</W>
<W lemma="detaillieren" msd="VA" tag="VVFIN" in="-6:vobj" out="-1:quant|3:vobj">detailliert</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="2:pobj" out="1:nobj">zum</W>
<W lemma="Ausdruck" msd="NC" tag="NN" in="-1:nobj" out="">Ausdruck</W>
<W lemma="bringen" msd="VAP" tag="VVPP" in="-3:vobj" out="-2:pobj">gebracht</W>
<W lemma="," msd="XP" tag="$," in="-10:pnct" out="">,</W>
<W lemma="erklären" msd="VA" tag="VVFIN" in="-11:conj" out="1:subj">erklärte</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Abteilungsleiter" msd="NC" tag="NN" in="-1:nobj" out="">Abteilungsleiter</W>
<W lemma="." msd="XP" tag="$." in="-14:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">Und</W>
<W lemma="Michael" msd="NP" tag="NE" in="1:namef" out="">Michael</W>
<W lemma="Christianse" msd="NC" tag="NN" in="1:subj" out="-1:namef">Christiansen</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-3:coord|-1:subj|1:add|2:neg|10:vobj|18:pnct|30:pnct">hat</W>
<W lemma="auch" msd="RG" tag="ADV" in="-1:add" out="">auch</W>
<W lemma="nie" msd="RG" tag="ADV" in="-2:neg" out="">nie</W>
<W lemma="etwas" msd="RG" tag="ADV" in="1:quant" out="">etwas</W>
<W lemma="von" msd="SP" tag="APPR" in="6:pobj" out="-1:quant|1:nobj">von</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einer</W>
<W lemma="gering" msd="AN" tag="ADJA" in="-1:attr" out="">geringeren</W>
<W lemma="Priorität" msd="NC" tag="NN" in="-2:nobj" out="">Priorität</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Tamilenvorgänge</W>
<W lemma="gehören" msd="VA" tag="VVFIN" in="-10:vobj" out="-6:pobj|1:pnct|2:time">gehört</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="während" msd="CS" tag="KOUS" in="-2:time" out="5:vobj">während</W>
<W lemma="er" msd="PP" tag="PPER" in="4:subj" out="">er</W>
<W lemma="selbst" msd="RG" tag="ADV" in="3:time" out="">selbst</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="2:preds" out="1:nobj">im</W>
<W lemma="Justizministerien" msd="NC" tag="NN" in="-1:nobj" out="">Justizministerium</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-3:time|-2:preds|3:preds">war</W>
<W lemma="," msd="XP" tag="$," in="-18:pnct" out="">,</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="-3:preds" out="-1:add|9:vobj">wenn</W>
<W lemma="Frederik" msd="NP" tag="NE" in="1:namef" out="">Frederik</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="7:subj" out="-1:namef">Schydt</W>
<W lemma="mehrfach" msd="AN" tag="ADJD" in="5:man" out="">mehrfach</W>
<W lemma="über" msd="SP" tag="APPR" in="4:pobj" out="">über</W>
<W lemma="zu" msd="SP" tag="APPR" in="3:pobj" out="2:nobj">zu</W>
<W lemma="gering" msd="AN" tag="ADJA" in="1:attr" out="">geringe</W>
<W lemma="Mittel" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Mittel</W>
<W lemma="klagen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:man|-4:pobj|-3:pobj">geklagt</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-9:vobj" out="-7:subj|-1:vobj">hat</W>
<W lemma="." msd="XP" tag="$." in="-30:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="18:subj" out="1:attr|2:nobj">Die</W>
<W lemma="offiziell" msd="AN" tag="ADJA" in="-1:attr" out="">offizielle</W>
<W lemma="Erläuterung" msd="NC" tag="NN" in="-2:nobj" out="1:goal">Erläuterung</W>
<W lemma="für" msd="SP" tag="APPR" in="-1:goal" out="1:nobj">für</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj|7:nobj|8:pnct|9:appa">die</W>
<W lemma="gering" msd="AN" tag="ADJA" in="-1:attr" out="">geringere</W>
<W lemma="Priorität" msd="NC" tag="NN" in="-2:nobj" out="">Priorität</W>
<W lemma="bei" msd="SP" tag="APPR" in="" out="1:nobj">bei</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Zusammenführung" msd="NC" tag="NN" in="-1:nobj" out="">Zusammenführung</W>
<W lemma="tamilisch" msd="AN" tag="ADJA" in="1:attr" out="">tamilischer</W>
<W lemma="Familie" msd="NC" tag="NN" in="-7:nobj" out="-1:attr">Familien</W>
<W lemma="-" msd="XP" tag="$(" in="-8:pnct" out="">-</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-9:appa" out="1:nobj|3:nobj|4:pnct">die</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">sog.</W>
<W lemma="falsch" msd="AN" tag="ADJA" in="1:attr" out="">falsche</W>
<W lemma="Melodie" msd="NC" tag="NN" in="-3:nobj" out="-1:attr">Melodie</W>
<W lemma="-" msd="XP" tag="$(" in="-4:pnct" out="">-</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-18:subj|1:preds|2:subj|8:pnct">war</W>
<W lemma="genau" msd="AN" tag="ADJD" in="-1:preds" out="">genau</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-2:subj" out="1:nobj">dieser</W>
<W lemma="Mangel" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Mangel</W>
<W lemma="an" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">an</W>
<W lemma="Mittel&7c;Mitteln" msd="NC" tag="NN" in="-1:nobj" out="1:pobj.subj">Mitteln</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:pobj.subj" out="1:nobj">des</W>
<W lemma="Ministerium" msd="NC" tag="NN" in="-1:nobj" out="">Ministeriums</W>
<W lemma="." msd="XP" tag="$." in="-8:pnct" out="">.</W>
</s>
</p>
