<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="6:subj" out="1:attr">Der</W>
<W lemma="19jährig" msd="AN" tag="ADJA" in="-1:attr" out="">19jährige</W>
<W lemma="Frank" msd="NP" tag="NE" in="1:namef" out="">Frank</W>
<W lemma="Olsen" msd="NP" tag="NE" in="" out="-1:namef">Olsen</W>
<W lemma="vom" msd="SP+P" tag="APPRART" in="2:man" out="1:nobj">vom</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">CIK</W>
<W lemma="beweisen" msd="VA" tag="VVFIN" in="" out="-6:subj|-2:man|26:pnct">bewies</W>
<W lemma="bei" msd="SP" tag="APPR" in="" out="1:nobj">bei</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:nobj">den</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Seeländischen</W>
<W lemma="Meisterschaft" msd="NC" tag="NN" in="-2:nobj" out="">Meisterschaften</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Dansborghalle</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:nobj">Hvidovre</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:nobj" out="4:vobj">dass</W>
<W lemma="er" msd="PP" tag="PPER" in="3:subj" out="">er</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj">das</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Potenzial</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:subj|-2:dobj|1:pnct|9:nobj">hat</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="zu" msd="SP" tag="APPR" in="8:pobj" out="1:nobj">zu</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einer</W>
<W lemma="herausragend" msd="AN" tag="ADJA" in="-1:attr" out="">herausragenden</W>
<W lemma="Figur" msd="NC" tag="NN" in="-2:nobj" out="">Figur</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">des</W>
<W lemma="dänisch" msd="AN" tag="ADJA" in="-1:attr" out="">dänischen</W>
<W lemma="Boxsport" msd="NC" tag="NN" in="-2:nobj" out="">Boxsports</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-9:nobj" out="1:vobj">zu</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-1:vobj" out="-8:pobj">werden</W>
<W lemma="." msd="XP" tag="$." in="-26:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="1:nobj">In</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einem</W>
<W lemma="aggressiv" msd="AN" tag="ADJA" in="-1:attr" out="">aggressiven</W>
<W lemma="Boxkampf" msd="NC" tag="NN" in="-2:nobj" out="">Boxkampf</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:man" out="2:nobj">mit</W>
<W lemma="schön" msd="AN" tag="ADJA" in="1:attr" out="">schönen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">1-2-Kombinationen</W>
<W lemma="siegen" msd="VA" tag="VVFIN" in="" out="-3:man|1:subj">siegte</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="über" msd="SP" tag="APPR" in="" out="2:nobj">über</W>
<W lemma="Lars" msd="NP" tag="NE" in="1:namef" out="">Lars</W>
<W lemma="B." msd="NP" tag="NE" in="-2:nobj" out="-1:namef">B.</W>
<W lemma="Hansen" msd="NP" tag="NE" in="9:subj" out="1:attr">Hansen</W>
<W lemma="aus" msd="SP" tag="APPR" in="-1:attr" out="1:nobj|2:nobj">aus</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Korsør</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-2:nobj" out="1:nobj">im</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Weltergewicht</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="2:nobj">mit</W>
<W lemma="klar" msd="AN" tag="ADJA" in="1:quant" out="">klaren</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-2:nobj" out="-1:quant">5-0</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="setzen" msd="VAM" tag="VVIMP" in="" out="-9:subj|-1:coord|1:contr|2:dobj|5:part|6:pnct|16:vobj|17:pnct">setz</W>
<W lemma="damit" msd="RG" tag="PAV" in="-1:contr" out="">damit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-2:dobj" out="1:attr|2:nobj">den</W>
<W lemma="beschleunigt" msd="AN" tag="ADJA" in="-1:attr" out="">beschleunigten</W>
<W lemma="Takt" msd="NC" tag="NN" in="-2:nobj" out="">Takt</W>
<W lemma="fort" msd="RG" tag="PTKVZ" in="-5:part" out="">fort</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="9:dobj" out="">den</W>
<W lemma="er" msd="PP" tag="PPER" in="8:subj" out="">er</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="1:nobj">im</W>
<W lemma="Halbfinale" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Halbfinale</W>
<W lemma="gegen" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">gegen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr">den</W>
<W lemma="routiniert" msd="AN" tag="ADJA" in="-1:attr" out="">routinierten</W>
<W lemma="Isla" msd="NP" tag="NE" in="1:namef" out="">Isla</W>
<W lemma="Fidan" msd="NP" tag="NE" in="1:dobj" out="-1:namef">Fidan</W>
<W lemma="zeigen" msd="VA" tag="VVFIN" in="-16:vobj" out="-9:dobj|-8:subj|-1:dobj">zeigt</W>
<W lemma="." msd="XP" tag="$." in="-17:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="ich" msd="PP" tag="PPER" in="1:subj" out="">Ich</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-2:pnct|-1:subj|2:vobj|13:pnct">habe</W>
<W lemma="schon" msd="RG" tag="ADV" in="1:time" out="">schon</W>
<W lemma="spüren" msd="VAP" tag="VVPP" in="-2:vobj" out="-1:time|1:pnct|2:dobj">gespürt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="8:vobj">dass</W>
<W lemma="ich" msd="PP" tag="PPER" in="7:subj" out="">ich</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="5:dobj" out="1:attr|2:nobj">einen</W>
<W lemma="hart" msd="AN" tag="ADJA" in="-1:attr" out="">harten</W>
<W lemma="Kampf" msd="NC" tag="NN" in="-2:nobj" out="1:pobj">Kampf</W>
<W lemma="gegen" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">gegen</W>
<W lemma="Fidan" msd="NP" tag="NE" in="-1:nobj" out="">Fidan</W>
<W lemma="kämpfen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:dobj">gekämpft</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-8:vobj" out="-7:subj|-1:vobj">hatte</W>
<W lemma="." msd="XP" tag="$." in="-13:pnct" out="">.</W>
<W lemma="ich" msd="PP" tag="PPER" in="1:subj" out="">Ich</W>
<W lemma="finden" msd="VA" tag="VVFIN" in="" out="-1:subj|1:conc|2:<coord|3:pnct|4:dobj|11:pnct">finde</W>
<W lemma="aber" msd="RG" tag="ADV" in="-1:conc" out="">aber</W>
<W lemma="eigentlich" msd="RG" tag="ADV" in="-2:<coord:1>" out="">eigentlich</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:dobj" out="6:vobj">dass</W>
<W lemma="es" msd="PP" tag="PPER" in="5:subj" out="">es</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="heute" msd="RG" tag="ADV" in="3:time" out="-1:add">heute</W>
<W lemma="sehr" msd="RG" tag="ADV" in="1:quant" out="">sehr</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:man" out="-1:quant">gut</W>
<W lemma="laufen" msd="VA" tag="VVFIN" in="-6:vobj" out="-5:subj|-3:time|-1:man">lief</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
<W lemma="ich" msd="PP" tag="PPER" in="1:subj" out="">Ich</W>
<W lemma="wissen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:pnct|2:dobj">wusste</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="3:vobj">dass</W>
<W lemma="ich" msd="PP" tag="PPER" in="2:subj" out="">ich</W>
<W lemma="schnell" msd="AN" tag="ADJD" in="1:preds" out="">schneller</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-3:vobj" out="-2:subj|-1:preds">bin</W>
<W lemma="als" msd="CC" tag="KON" in="3:coord" out="">als</W>
<W lemma="er" msd="PP" tag="PPER" in="2:subj" out="">er</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="9:qobj" out="-3:coord|-2:subj|-1:coord|6:vobj|7:pnct|8:pnct">habe</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:dobj" out="1:nobj">den</W>
<W lemma="Kampf" msd="NC" tag="NN" in="-1:nobj" out="">Kampf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:dobj" out="1:attr|2:nobj">die</W>
<W lemma="ganz" msd="AN" tag="ADJA" in="-1:attr" out="">ganze</W>
<W lemma="Zeit" msd="NC" tag="NN" in="-2:nobj" out="">Zeit</W>
<W lemma="kontrollieren" msd="VAP" tag="VVPP" in="-6:vobj" out="-5:dobj|-3:dobj">kontrolliert</W>
<W lemma="," msd="XP" tag="$," in="-7:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-8:pnct" out="">"</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="-9:qobj|2:subj|3:pnct">sagt</W>
<W lemma="Frank" msd="NP" tag="NE" in="1:namef" out="">Frank</W>
<W lemma="Olsen" msd="NP" tag="NE" in="-2:subj" out="-1:namef">Olsen</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="gewinnen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:add|2:dobj|8:pnct|11:conj|22:pnct">gewann</W>
<W lemma="auch" msd="RG" tag="ADV" in="-1:add" out="">auch</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-2:dobj" out="1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:nobj">Seeländische</W>
<W lemma="Meisterschaft" msd="NC" tag="NN" in="-1:nobj" out="">Meisterschaft</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="1:attr|2:nobj">im</W>
<W lemma="vergangen" msd="AN" tag="ADJA" in="-1:attr" out="">vergangenen</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="">Jahr</W>
<W lemma="," msd="XP" tag="$," in="-8:pnct" out="">,</W>
<W lemma="aber" msd="CC" tag="KON" in="2:coord" out="">aber</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">es</W>
<W lemma="fehlen" msd="VA" tag="VVFIN" in="-11:conj" out="-2:coord|-1:subj|1:eval|2:<coord|3:preds|5:pnct|9:nobj">fehlte</W>
<W lemma="trotzdem" msd="RG" tag="PAV" in="-1:eval" out="">trotzdem</W>
<W lemma="etwas" msd="RG" tag="ADV" in="-2:<coord:1>" out="">etwas</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:preds" out="1:nobj">der</W>
<W lemma="Wille" msd="NC" tag="NN" in="-1:nobj" out="">Wille</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="ganz" msd="AN" tag="ADJD" in="1:quant" out="">ganz</W>
<W lemma="nach" msd="RG" tag="ADV" in="3:time" out="-1:quant|1:avobj">nach</W>
<W lemma="oben" msd="RG" tag="ADV" in="-1:avobj" out="">oben</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-9:nobj" out="1:vobj">zu</W>
<W lemma="kommen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:time">kommen</W>
<W lemma="." msd="XP" tag="$." in="-22:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:attr|2:nobj">Der</W>
<W lemma="gestrig" msd="AN" tag="ADJA" in="-1:attr" out="">gestrige</W>
<W lemma="Triumph" msd="NC" tag="NN" in="-2:nobj" out="">Triumph</W>
<W lemma="veranlassen" msd="VA" tag="VVFIN" in="" out="-3:subj|2:subj|3:prg|4:time|5:part|6:pnct|7:vobj|21:pnct">veranlasste</W>
<W lemma="Frank" msd="NP" tag="NE" in="1:namef" out="">Frank</W>
<W lemma="Olsen" msd="NP" tag="NE" in="-2:subj" out="-1:namef">Olsen</W>
<W lemma="da" msd="RG" tag="ADV" in="-3:prg" out="">da</W>
<W lemma="schon" msd="RG" tag="ADV" in="-4:time" out="">schon</W>
<W lemma="eher" msd="RG" tag="ADV" in="-5:part" out="">eher</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="ankündigen" msd="VAF" tag="VVIZU" in="-7:vobj" out="1:pnct|2:dobj">anzukündigen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="11:vobj">dass</W>
<W lemma="man" msd="PP" tag="PIS" in="10:subj" out="">man</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="9:time" out="">jetzt</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="1:nobj">in</W>
<W lemma="Zukunft" msd="NC" tag="NN" in="-1:nobj" out="">Zukunft</W>
<W lemma="ganz" msd="AN" tag="ADJD" in="1:quant" out="">ganz</W>
<W lemma="groß" msd="AN" tag="ADJA" in="1:attr" out="-1:quant">große</W>
<W lemma="Leistung" msd="NC" tag="NN" in="4:subj" out="-1:attr|1:attr">Leistungen</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">von</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:nobj" out="">ihm</W>
<W lemma="erwarten" msd="VAF" tag="VVINF" in="1:vobj" out="">erwarten</W>
<W lemma="dürfen" msd="VA" tag="VMFIN" in="-11:vobj" out="-10:subj|-9:time|-4:subj|-1:vobj">darf</W>
<W lemma="." msd="XP" tag="$." in="-21:pnct" out="">.</W>
</s>
</p>
