<p>
<s>
<W lemma="ein" msd="P[ID]" tag="ART" in="6:subj" out="1:attr|2:nobj">Ein</W>
<W lemma="durchgehend" msd="AN" tag="ADJA" in="-1:attr" out="">durchgehender</W>
<W lemma="Zug" msd="NC" tag="NN" in="-2:nobj" out="">Zug</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">der</W>
<W lemma="befragt" msd="AN" tag="ADJA" in="-1:attr" out="">befragten</W>
<W lemma="Tamile" msd="NC" tag="NN" in="-2:nobj" out="">Tamilen</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-6:subj|1:pnct|2:dobj|18:pnct">war</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="15:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="14:subj" out="1:nobj|5:conj">die</W>
<W lemma="Däne" msd="NC" tag="NN" in="-1:nobj" out="">Dänen</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="" out="1:possd">ihre</W>
<W lemma="Religion" msd="NC" tag="NN" in="-1:possd" out="">Religion</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-5:conj" out="-1:coord|1:nobj|2:pnct|7:relr">die</W>
<W lemma="Lebensweise" msd="NC" tag="NN" in="-1:nobj" out="">Lebensweise</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="4:subj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">die</W>
<W lemma="Religion" msd="NC" tag="NN" in="-1:nobj" out="">Religion</W>
<W lemma="sie" msd="PP" tag="PPER" in="1:dobj" out="">ihnen</W>
<W lemma="auferlegen" msd="VAP" tag="VVPP" in="-7:relr" out="-4:subj|-3:subj|-1:dobj|1:pnct">auferlegt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="respektieren" msd="VA" tag="VVFIN" in="-15:vobj" out="-14:subj">respektieren</W>
<W lemma="." msd="XP" tag="$." in="-18:pnct" out="">.</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="1:time" out="">Gleichzeitig</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:time|1:subj|3:preds|4:pnct|5:preds|22:pnct">sind</W>
<W lemma="sie" msd="PP" tag="PPER" in="-1:subj" out="">sie</W>
<W lemma="es" msd="PP" tag="PPER" in="1:dobj" out="8:nobj">es</W>
<W lemma="leid" msd="AN" tag="ADJD" in="-3:preds" out="-1:dobj">leid</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="als" msd="CS" tag="KOUS" in="-5:preds" out="2:nobj">als</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="1:attr" out="">,,exotische</W>
<W lemma="Seltenheit" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|1:pnct">Seltenheiten</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="betrachten" msd="VAP" tag="VVPP" in="2:vobj" out="">betrachtet</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-8:nobj" out="1:vobj|2:pnct|7:conj">zu</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-1:vobj" out="-2:vobj">werden</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="4:subj" out="">die</W>
<W lemma="per" msd="SP" tag="APPR" in="2:eval" out="1:nobj">per</W>
<W lemma="Definition" msd="NC" tag="NN" in="-1:nobj" out="">Definition</W>
<W lemma="schwach" msd="AN" tag="ADJD" in="1:preds" out="-2:eval">schwach</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-7:conj" out="-4:subj|-1:preds|4:conj">ist</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="beschützen" msd="VAM" tag="VVIMP" in="1:vobj" out="-1:coord">beschützt</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="1:vobj" out="-1:vobj">werden</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="-4:conj" out="-1:vobj">muss</W>
<W lemma="." msd="XP" tag="$." in="-22:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="9:pnct" out="">"</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="23:cond" out="8:vobj">Wenn</W>
<W lemma="wohlmeinend" msd="AN" tag="ADJA" in="1:attr" out="">wohlmeinende</W>
<W lemma="Däne" msd="NC" tag="NN" in="6:dobj" out="-1:attr">Dänen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:dobj" out="1:nobj">den</W>
<W lemma="Kind" msd="NC" tag="NN" in="-1:nobj" out="">Kindern</W>
<W lemma="weiterhin" msd="RG" tag="ADV" in="3:time" out="">weiterhin</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj">den</W>
<W lemma="Eindruck" msd="NC" tag="NN" in="-1:nobj" out="">Eindruck</W>
<W lemma="vermitteln" msd="VA" tag="VVFIN" in="-8:vobj" out="-9:pnct|-6:dobj|-5:dobj|-3:time|-2:dobj|1:pnct|2:dobj">vermitteln</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="11:vobj">dass</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="10:subj" out="2:conj">Einwanderer</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Flüchtling" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Flüchtlinge</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="2:neg" out="">nicht</W>
<W lemma="alleine" msd="RG" tag="ADV" in="1:focal" out="">alleine</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="-2:neg|-1:focal|1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="dänisch" msd="AN" tag="ADJA" in="-1:attr" out="">dänischen</W>
<W lemma="Gesellschaft" msd="NC" tag="NN" in="-2:nobj" out="">Gesellschaft</W>
<W lemma="klar" msd="AN" tag="ADJD" in="1:man" out="">klar</W>
<W lemma="kommen" msd="VA" tag="VVFIN" in="-11:vobj" out="-10:subj|-1:man|1:pnct">kommen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="8:qobj" out="-23:cond|1:subj|5:vobj|6:pnct|7:pnct">wird</W>
<W lemma="d" msd="PP" tag="PDS" in="-1:subj" out="">das</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="3:dobj" out="1:attr|2:nobj">eine</W>
<W lemma="verstärkend" msd="AN" tag="ADJA" in="-1:attr" out="">verstärkende</W>
<W lemma="Wirkung" msd="NC" tag="NN" in="-2:nobj" out="">Wirkung</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="-5:vobj" out="-3:dobj">haben</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-7:pnct" out="">"</W>
<W lemma="schlußfolgern" msd="VA" tag="VVFIN" in="" out="-8:qobj|1:subj|3:pnct">schlussfolgert</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Bericht" msd="NC" tag="NN" in="-1:nobj" out="">Bericht</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="Einwandererkind" msd="NC" tag="NN" in="14:subj" out="">Einwandererkinder</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="1:nobj|2:pnct|3:conj">im</W>
<W lemma="Ausbildungssystem" msd="NC" tag="NN" in="-1:nobj" out="">Ausbildungssystem</W>
<W lemma="&3a;" msd="XP" tag="$." in="-2:pnct" out="">:</W>
<W lemma="13" msd="AC" tag="CARD" in="-3:conj" out="1:nobj">13</W>
<W lemma="Prozent" msd="NC" tag="NN" in="-1:nobj" out="">Prozent</W>
<W lemma="alle" msd="PI" tag="PIAT" in="" out="1:nobj|2:pnct|6:relr">aller</W>
<W lemma="Kind" msd="NC" tag="NN" in="-1:nobj" out="">Kinder</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="3:subj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">die</W>
<W lemma="Gesamtschule" msd="NC" tag="NN" in="-1:nobj" out="">Gesamtschule</W>
<W lemma="verlassen" msd="VAP" tag="VVPP" in="-6:relr" out="-3:subj|-2:subj|1:pnct">verlassen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-14:subj|1:dobj|3:time|4:time|7:vobj|8:pnct">haben</W>
<W lemma="15" msd="AC" tag="CARD" in="-1:dobj" out="1:nobj">15</W>
<W lemma="Monat" msd="NC" tag="NN" in="-1:nobj" out="">Monate</W>
<W lemma="spät" msd="AN" tag="ADJD" in="-3:time" out="">später</W>
<W lemma="noch" msd="RG" tag="ADV" in="-4:time" out="">noch</W>
<W lemma="kein" msd="PI" tag="PIAT" in="2:dobj" out="1:nobj">keine</W>
<W lemma="Ausbildung" msd="NC" tag="NN" in="-1:nobj" out="">Ausbildung</W>
<W lemma="antreten" msd="VAP" tag="VVPP" in="-7:vobj" out="-2:dobj">angetreten</W>
<W lemma="." msd="XP" tag="$." in="-8:pnct" out="">.</W>
<W lemma="bei" msd="SP" tag="APPR" in="2:scene" out="1:nobj">Bei</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="-1:nobj" out="">Einwanderern</W>
<W lemma="liegen" msd="VA" tag="VVFIN" in="" out="-2:scene|1:subj|3:conj|6:pnct|7:conj|20:conj|28:conj|31:pnct">liegt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">die</W>
<W lemma="Zahl" msd="NC" tag="NN" in="-1:nobj" out="">Zahl</W>
<W lemma="bei" msd="SP" tag="APPR" in="-3:conj" out="1:nobj">bei</W>
<W lemma="41" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">41</W>
<W lemma="%" msd="NC" tag="NN" in="-1:nobj" out="">%</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="bei" msd="SP" tag="APPR" in="-7:conj" out="1:nobj">bei</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="-1:nobj" out="">Einwanderern</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="zweit" msd="AN" tag="ADJA" in="-1:attr" out="">zweiten</W>
<W lemma="Generation" msd="NC" tag="NN" in="-2:nobj" out="1:attr">Generation</W>
<W lemma="bei" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">bei</W>
<W lemma="15" msd="AC" tag="CARD" in="-1:nobj" out="2:nobj">15</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="1:quant" out="">%.</W>
<W lemma="31" msd="AC" tag="CARD" in="-2:nobj" out="-1:quant|1:nobj">31</W>
<W lemma="%" msd="NC" tag="NN" in="-1:nobj" out="">%</W>
<W lemma="alle" msd="PI" tag="PIAT" in="2:subj" out="1:nobj">aller</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Gesamtschulschüler</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="-20:conj" out="-2:subj|1:man|2:pobj">gehen</W>
<W lemma="anschließend" msd="AN" tag="ADJD" in="-1:man" out="">anschließend</W>
<W lemma="auf" msd="SP" tag="APPR" in="-2:pobj" out="1:nobj">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:pnct">das</W>
<W lemma="Gymnasium" msd="NC" tag="NN" in="-1:nobj" out="">Gymnasium</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="@card@" msd="AC" tag="CARD" in="2:time" out="1:nobj">42</W>
<W lemma="%" msd="NC" tag="NN" in="-1:nobj" out="">%</W>
<W lemma="beginnen" msd="VA" tag="VVFIN" in="-28:conj" out="-2:time|1:dobj">beginnen</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:dobj" out="1:nobj">eine</W>
<W lemma="Berufsausbildung" msd="NC" tag="NN" in="-1:nobj" out="">Berufsausbildung</W>
<W lemma="." msd="XP" tag="$." in="-31:pnct" out="">.</W>
<W lemma="21" msd="AC" tag="CARD" in="12:subj" out="1:other">21</W>
<W lemma="%" msd="NC" tag="NN" in="-1:other" out="">%</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Einwanderer</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-2:conj" out="-1:coord|1:nobj">42</W>
<W lemma="%" msd="NC" tag="NN" in="-1:nobj" out="">%</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="-1:nobj" out="">Einwanderer</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="2:nobj">in</W>
<W lemma="zweit" msd="AN" tag="ADJA" in="1:attr" out="">zweiter</W>
<W lemma="Generation" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Generation</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="-12:subj|1:man|2:pobj|5:pnct|6:time|15:pnct">gehen</W>
<W lemma="anschließend" msd="AN" tag="ADJD" in="-1:man" out="">anschließend</W>
<W lemma="auf" msd="SP" tag="APPR" in="-2:pobj" out="1:nobj">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">das</W>
<W lemma="Gymnasium" msd="NC" tag="NN" in="-1:nobj" out="">Gymnasium</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="während" msd="CS" tag="KOUS" in="-6:time" out="8:vobj">während</W>
<W lemma="13" msd="AC" tag="CARD" in="7:dobj" out="2:conj">13</W>
<W lemma="bzw." msd="CS" tag="KOKOM" in="1:quant" out="">bzw.</W>
<W lemma="22" msd="AC" tag="CARD" in="-2:conj" out="-1:quant|1:nobj">22</W>
<W lemma="%" msd="NC" tag="NN" in="-1:nobj" out="">%</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:pobj" out="1:nobj">mit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einer</W>
<W lemma="Berufsausbildung" msd="NC" tag="NN" in="-1:nobj" out="">Berufsausbildung</W>
<W lemma="beginnen" msd="VA" tag="VVFIN" in="-8:vobj" out="-7:dobj|-3:pobj">beginnen</W>
<W lemma="." msd="XP" tag="$." in="-15:pnct" out="">.</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="5:time" out="1:nobj">Im</W>
<W lemma="Lauf" msd="NC" tag="NN" in="-1:nobj" out="">Laufe</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr">der</W>
<W lemma="80er" msd="AN" tag="ADJA" in="-1:attr" out="1:nobj">80er</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahre</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-5:time|1:subj|9:pnct|16:vobj|17:pnct">ist</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Anteil" msd="NC" tag="NN" in="-1:nobj" out="">Anteil</W>
<W lemma="Einwanderer" msd="NC" tag="NN" in="13:dobj" out="11:relr">Einwanderer</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="1:nobj|4:nobj">in</W>
<W lemma="erst" msd="AN" tag="ADJA" in="-1:nobj" out="2:conj">erster</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="zweit" msd="AN" tag="ADJA" in="-2:conj" out="-1:coord">zweiter</W>
<W lemma="Generation" msd="NC" tag="NN" in="-4:nobj" out="">Generation</W>
<W lemma="," msd="XP" tag="$," in="-9:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="4:subj" out="">die</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="1:nobj">im</W>
<W lemma="Ausbildungssystem" msd="NC" tag="NN" in="-1:nobj" out="">Ausbildungssystem</W>
<W lemma="weit" msd="AN" tag="ADJD" in="1:aobj" out="">weiter</W>
<W lemma="machen" msd="VA" tag="VVFIN" in="-11:relr" out="-4:subj|-1:aobj|1:pnct">machen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="steigen" msd="VAP" tag="VVPP" in="-16:vobj" out="-13:dobj">gestiegen</W>
<W lemma="." msd="XP" tag="$." in="-17:pnct" out="">.</W>
</s>
</p>
