<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="ja" msd="RG" tag="PTKANT" in="" out="">Ja</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="" out="">im</W>
<W lemma="Grund" msd="NC" tag="NN" in="" out="">Grunde</W>
<W lemma="mögen" msd="VA" tag="VMFIN" in="" out="">möchten</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="gerne" msd="RG" tag="ADV" in="" out="">gerne</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJD" in="" out="">fit</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="" out="">sein</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="antworten" msd="VA" tag="VVFIN" in="" out="">antwortet</W>
<W lemma="Bettina" msd="NP" tag="NE" in="" out="">Bettina</W>
<W lemma="Borg" msd="NC" tag="NN" in="" out="">Borg</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="aber" msd="CC" tag="KON" in="" out="">Aber</W>
<W lemma="sie" msd="PP" tag="PPER" in="" out="">sie</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="" out="">wollen</W>
<W lemma="kein" msd="PI" tag="PIAT" in="" out="">keine</W>
<W lemma="dick" msd="AN" tag="ADJA" in="" out="">dicken</W>
<W lemma="Muskelpaket" msd="NC" tag="NN" in="" out="">Muskelpakete</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="" out="">haben</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="vor" msd="SP" tag="APPR" in="" out="">Vor</W>
<W lemma="etwa" msd="RG" tag="ADV" in="" out="">etwa</W>
<W lemma="zehn" msd="AC" tag="CARD" in="" out="">zehn</W>
<W lemma="Jahr" msd="NC" tag="NN" in="" out="">Jahren</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">waren</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="" out="">Jetzt</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="" out="">soll</W>
<W lemma="er" msd="PP" tag="PPER" in="" out="">er</W>
<W lemma="sportlich" msd="AN" tag="ADJD" in="" out="">sportlich</W>
<W lemma="aussehen" msd="VAF" tag="VVINF" in="" out="">aussehen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="ohne" msd="CS" tag="KOUI" in="" out="">ohne</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="dick" msd="AN" tag="ADJA" in="" out="">dicken</W>
<W lemma="Muskelpaket" msd="NC" tag="NN" in="" out="">Muskelpaketen</W>
<W lemma="aufwarten" msd="VAF" tag="VVIZU" in="" out="">aufzuwarten</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">Der</W>
<W lemma="Mann" msd="NC" tag="NN" in="" out="">Mann</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="" out="">will</W>
<W lemma="gerne" msd="RG" tag="ADV" in="" out="">gerne</W>
<W lemma="roh" msd="AN" tag="ADJD" in="" out="">roh</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="aber" msd="RG" tag="ADV" in="" out="">aber</W>
<W lemma="gut" msd="AN" tag="ADJD" in="" out="">gut</W>
<W lemma="kleiden" msd="VAP" tag="VVPP" in="" out="">gekleidet</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="pflegen" msd="VAP" tag="VVPP" in="" out="">gepflegt</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="" out="">sein</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">Das</W>
<W lemma="Ideal" msd="NC" tag="NN" in="" out="">Ideal</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="">geht</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="Richtung" msd="NC" tag="NN" in="" out="">Richtung</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">eines</W>
<W lemma="gut" msd="AN" tag="ADJD" in="" out="">gut</W>
<W lemma="aussehend" msd="AN" tag="ADJA" in="" out="">aussehenden</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="nobel" msd="AN" tag="ADJA" in="" out="">noblen</W>
<W lemma="Geschäftsmann" msd="NC" tag="NN" in="" out="">Geschäftsmannes</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="">geht</W>
<W lemma="hier" msd="RG" tag="ADV" in="" out="">hier</W>
<W lemma="auch" msd="RG" tag="ADV" in="" out="">auch</W>
<W lemma="einher" msd="RG" tag="ADV" in="" out="">einher</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">dem</W>
<W lemma="Direktor" msd="NC" tag="NN" in="" out="">Direktor</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="Jurist" msd="NC" tag="NN" in="" out="">Juristen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="Arbeiter" msd="NC" tag="NN" in="" out="">Arbeiter</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">..</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="zwei" msd="AC" tag="CARD" in="" out="">Zwei</W>
<W lemma="Mann" msd="NC" tag="NN" in="" out="">Männer</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="Welt" msd="NC" tag="NN" in="" out="">Welt</W>
</s>
</p>
<p>
<s>
<W lemma="und" msd="CC" tag="KON" in="" out="">Und</W>
<W lemma="was" msd="PT" tag="PWS" in="" out="">was</W>
<W lemma="wünschen" msd="VA" tag="VVFIN" in="" out="">wünscht</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="Frau" msd="NC" tag="NN" in="" out="">Frau</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="" out="">sich</W>
<W lemma="?" msd="XP" tag="$." in="" out="">?</W>
<W lemma="Jugend" msd="NC" tag="NN" in="" out="">Jugend</W>
<W lemma="?" msd="XP" tag="$." in="" out="">?</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="">Ein</W>
<W lemma="Körper" msd="NC" tag="NN" in="" out="">Körper</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="" out="">der</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="">auf</W>
<W lemma="Erfolg" msd="NC" tag="NN" in="" out="">Erfolg</W>
<W lemma="schließen" msd="VAF" tag="VVINF" in="" out="">schließen</W>
<W lemma="lassen" msd="VA" tag="VVFIN" in="" out="">lässt</W>
<W lemma="?" msd="XP" tag="$." in="" out="">?</W>
<W lemma="gut" msd="AN" tag="ADJD" in="" out="">Gut</W>
<W lemma="trainieren" msd="VA" tag="VVFIN" in="" out="">trainierte</W>
<W lemma="Muskel" msd="NC" tag="NN" in="" out="">Muskeln</W>
<W lemma="?" msd="XP" tag="$." in="" out="">?</W>
</s>
</p>
<p>
<s>
<W lemma="ja" msd="RG" tag="PTKANT" in="" out="">Ja</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="nein" msd="RG" tag="PTKANT" in="" out="">nein</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">In</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="letzt" msd="AN" tag="ADJA" in="" out="">letzten</W>
<W lemma="Jahr" msd="NC" tag="NN" in="" out="">Jahren</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="">haben</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">die</W>
<W lemma="Frau" msd="NC" tag="NN" in="" out="">Frauen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="Blick" msd="NC" tag="NN" in="" out="">Blick</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="smart" msd="AN" tag="ADJA" in="" out="">smarten</W>
<W lemma="Typ" msd="NC" tag="NN" in="" out="">Typ</W>
<W lemma="werfen" msd="VAP" tag="VVPP" in="" out="">geworfen</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="beispielsweise" msd="AN" tag="ADJD" in="" out="">beispielsweise</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="Schauspieler" msd="NC" tag="NN" in="" out="">Schauspieler</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Partick</W>
<W lemma="&lt;unknown&gt;" msd="VA" tag="VVFIN" in="" out="">Swayze</W>
<W lemma="(" msd="XP" tag="$(" in="" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">Ghost</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="Point" msd="NP" tag="NE" in="" out="">Point</W>
<W lemma="Break" msd="NC" tag="NN" in="" out="">Break</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="" out="">)</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="Richard" msd="NP" tag="NE" in="" out="">Richard</W>
<W lemma="&lt;unknown&gt;" msd="VA" tag="VVFIN" in="" out="">Gere</W>
<W lemma="(" msd="XP" tag="$(" in="" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="Pretty" msd="NP" tag="NE" in="" out="">Pretty</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">Woman</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="" out="">)</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Kevin" msd="NP" tag="NE" in="" out="">Kevin</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">Costner</W>
<W lemma="(" msd="XP" tag="$(" in="" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="Tanz" msd="NC" tag="NN" in="" out="">Tanz</W>
<W lemma="mit" msd="SP" tag="APPR" in="" out="">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">dem</W>
<W lemma="Wolf" msd="NP" tag="NE" in="" out="">Wolf</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="JFK" msd="NP" tag="NE" in="" out="">JFK</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="" out="">)</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="" out="">die</W>
<W lemma="alle" msd="PP" tag="PIS" in="" out="">alle</W>
<W lemma="gut" msd="AN" tag="ADJD" in="" out="">gut</W>
<W lemma="aussehen" msd="VAF" tag="VVINF" in="" out="">aussehen</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="alle" msd="PP" tag="PIS" in="" out="">alles</W>
<W lemma="unter" msd="SP" tag="APPR" in="" out="">unter</W>
<W lemma="Kontrolle" msd="NC" tag="NN" in="" out="">Kontrolle</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="" out="">zu</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="" out="">haben</W>
<W lemma="scheinen" msd="VA" tag="VVFIN" in="" out="">scheinen</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="" out="">In</W>
<W lemma="jed" msd="PI" tag="PIDAT" in="" out="">jedem</W>
<W lemma="Fall" msd="NC" tag="NN" in="" out="">Fall</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="">ist</W>
<W lemma="d" msd="PD" tag="PDAT" in="" out="">deren</W>
<W lemma="Körper" msd="NC" tag="NN" in="" out="">Körper</W>
<W lemma="weit" msd="AN" tag="ADJD" in="" out="">weit</W>
<W lemma="von" msd="SP" tag="APPR" in="" out="">von</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">den</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Cowboys</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="">der</W>
<W lemma="80er" msd="AN" tag="ADJA" in="" out="">80er</W>
<W lemma="," msd="XP" tag="$," in="" out="">,</W>
<W lemma="Sylvester" msd="NC" tag="NN" in="" out="">Sylvester</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="" out="">Rambo</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Stallone</W>
<W lemma="und" msd="CC" tag="KON" in="" out="">und</W>
<W lemma="Arnold" msd="NP" tag="NE" in="" out="">Arnold</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="" out="">Schwarzenegger</W>
<W lemma="entfernt" msd="AN" tag="ADJD" in="" out="">entfernt</W>
<W lemma="." msd="XP" tag="$." in="" out="">.</W>
</s>
</p>
