<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="ja" msd="RG" tag="PTKANT" in="11:qobj" out="-1:pnct|1:pnct|4:conj|9:pnct|10:pnct">Ja</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="2:eval" out="1:nobj">im</W>
<W lemma="Grund" msd="NC" tag="NN" in="-1:nobj" out="">Grunde</W>
<W lemma="mögen" msd="VA" tag="VMFIN" in="-4:conj" out="-2:eval|1:subj|2:eval|4:vobj">möchten</W>
<W lemma="sie" msd="PP" tag="PPER" in="-1:subj" out="">sie</W>
<W lemma="gerne" msd="RG" tag="ADV" in="-2:eval" out="">gerne</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJD" in="1:preds" out="">fit</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-4:vobj" out="-1:preds">sein</W>
<W lemma="," msd="XP" tag="$," in="-9:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-10:pnct" out="">"</W>
<W lemma="antworten" msd="VA" tag="VVFIN" in="" out="-11:qobj|2:subj|3:pnct">antwortet</W>
<W lemma="Bettina" msd="NP" tag="NE" in="1:namef" out="">Bettina</W>
<W lemma="Borg" msd="NC" tag="NN" in="-2:subj" out="-1:namef">Borg</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="3:pnct" out="">"</W>
<W lemma="aber" msd="CC" tag="KON" in="2:coord" out="">Aber</W>
<W lemma="sie" msd="PP" tag="PPER" in="1:subj" out="">sie</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="" out="-3:pnct|-2:coord|-1:subj|4:vobj|5:pnct">wollen</W>
<W lemma="kein" msd="PI" tag="PIAT" in="3:dobj" out="1:attr|2:nobj">keine</W>
<W lemma="dick" msd="AN" tag="ADJA" in="-1:attr" out="">dicken</W>
<W lemma="Muskelpaket" msd="NC" tag="NN" in="-2:nobj" out="">Muskelpakete</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="-4:vobj" out="-3:dobj">haben</W>
<W lemma="." msd="XP" tag="$." in="-5:pnct" out="">.</W>
<W lemma="vor" msd="SP" tag="APPR" in="4:time" out="2:nobj">Vor</W>
<W lemma="etwa" msd="RG" tag="ADV" in="1:quant" out="">etwa</W>
<W lemma="zehn" msd="AC" tag="CARD" in="-2:nobj" out="-1:quant|1:nobj">zehn</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahren</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-4:time|1:subj|2:preds|3:pnct">waren</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="">die</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:preds" out="">in</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="1:time" out="">Jetzt</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="" out="-1:time|1:subj|3:vobj|10:pnct">soll</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="sportlich" msd="AN" tag="ADJD" in="1:aobj" out="">sportlich</W>
<W lemma="aussehen" msd="VAF" tag="VVINF" in="-3:vobj" out="-1:aobj|1:pnct|2:man">aussehen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="ohne" msd="CS" tag="KOUI" in="-2:man" out="4:vobj">ohne</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:man" out="2:nobj">mit</W>
<W lemma="dick" msd="AN" tag="ADJA" in="1:attr" out="">dicken</W>
<W lemma="Muskelpaket" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Muskelpaketen</W>
<W lemma="aufwarten" msd="VAF" tag="VVIZU" in="-4:vobj" out="-3:man">aufzuwarten</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Der</W>
<W lemma="Mann" msd="NC" tag="NN" in="-1:nobj" out="">Mann</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="" out="-2:subj|1:eval|9:vobj|10:pnct">will</W>
<W lemma="gerne" msd="RG" tag="ADV" in="-1:eval" out="">gerne</W>
<W lemma="roh" msd="AN" tag="ADJD" in="7:preds" out="1:pnct|4:conj">roh</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="aber" msd="RG" tag="ADV" in="2:coord" out="">aber</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:aobj" out="">gut</W>
<W lemma="kleiden" msd="VAP" tag="VVPP" in="-4:conj" out="-2:coord|-1:aobj|2:conj">gekleidet</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="pflegen" msd="VAP" tag="VVPP" in="-2:conj" out="-1:coord">gepflegt</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-9:vobj" out="-7:preds">sein</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Das</W>
<W lemma="Ideal" msd="NC" tag="NN" in="-1:nobj" out="">Ideal</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="-2:subj|1:@dir|10:conj|21:pnct|22:pnct">geht</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:@dir" out="1:nobj">in</W>
<W lemma="Richtung" msd="NC" tag="NN" in="-1:nobj" out="">Richtung</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="2:nobj|3:pnct|4:attr|5:nobj">eines</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:man" out="">gut</W>
<W lemma="aussehend" msd="AN" tag="ADJA" in="-2:nobj" out="-1:man">aussehenden</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="nobel" msd="AN" tag="ADJA" in="-4:attr" out="">noblen</W>
<W lemma="Geschäftsmann" msd="NC" tag="NN" in="-5:nobj" out="">Geschäftsmannes</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="-10:conj" out="-1:coord|1:@loc|2:add|3:accom">geht</W>
<W lemma="hier" msd="RG" tag="ADV" in="-1:@loc" out="">hier</W>
<W lemma="auch" msd="RG" tag="ADV" in="-2:add" out="">auch</W>
<W lemma="einher" msd="RG" tag="ADV" in="-3:accom" out="1:pobj">einher</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Direktor" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj|3:pnct|4:conj">Direktor</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Jurist" msd="NC" tag="NN" in="-2:conj" out="">Juristen</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="Arbeiter" msd="NC" tag="NN" in="-4:conj" out="">Arbeiter</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-21:pnct" out="">..</W>
<W lemma="." msd="XP" tag="$." in="-22:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="zwei" msd="AC" tag="CARD" in="11:dobj" out="-1:pnct|1:nobj|2:attr">Zwei</W>
<W lemma="Mann" msd="NC" tag="NN" in="-1:nobj" out="">Männer</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Welt" msd="NC" tag="NN" in="-1:nobj" out="">Welt</W>
</s>
</p>
<p>
<s>
<W lemma="und" msd="CC" tag="KON" in="2:discmark" out="">Und</W>
<W lemma="was" msd="PT" tag="PWS" in="1:dobj" out="">was</W>
<W lemma="wünschen" msd="VA" tag="VVFIN" in="" out="-11:dobj|-2:discmark|-1:dobj|1:subj|3:robj|4:pnct">wünscht</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">die</W>
<W lemma="Frau" msd="NC" tag="NN" in="-1:nobj" out="">Frau</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-3:robj" out="">sich</W>
<W lemma="?" msd="XP" tag="$." in="-4:pnct" out="">?</W>
<W lemma="Jugend" msd="NC" tag="NN" in="" out="1:pnct">Jugend</W>
<W lemma="?" msd="XP" tag="$." in="-1:pnct" out="">?</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="1:nobj|2:pnct|7:relr|8:pnct">Ein</W>
<W lemma="Körper" msd="NC" tag="NN" in="-1:nobj" out="">Körper</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="4:subj" out="">der</W>
<W lemma="auf" msd="SP" tag="APPR" in="2:pobj" out="1:nobj">auf</W>
<W lemma="Erfolg" msd="NC" tag="NN" in="-1:nobj" out="">Erfolg</W>
<W lemma="schließen" msd="VAF" tag="VVINF" in="1:vobj" out="-2:pobj">schließen</W>
<W lemma="lassen" msd="VA" tag="VVFIN" in="-7:relr" out="-4:subj|-1:vobj">lässt</W>
<W lemma="?" msd="XP" tag="$." in="-8:pnct" out="">?</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:aobj" out="">Gut</W>
<W lemma="trainieren" msd="VA" tag="VVFIN" in="1:attr" out="-1:aobj">trainierte</W>
<W lemma="Muskel" msd="NC" tag="NN" in="" out="-1:attr|1:pnct">Muskeln</W>
<W lemma="?" msd="XP" tag="$." in="-1:pnct" out="">?</W>
</s>
</p>
<p>
<s>
<W lemma="ja" msd="RG" tag="PTKANT" in="" out="2:conj|3:pnct">Ja</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="nein" msd="RG" tag="PTKANT" in="-2:conj" out="-1:coord">nein</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="4:time" out="1:nobj">In</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">den</W>
<W lemma="letzt" msd="AN" tag="ADJA" in="-1:attr" out="">letzten</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="">Jahren</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-4:time|1:subj|9:vobj|62:pnct">haben</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">die</W>
<W lemma="Frau" msd="NC" tag="NN" in="-1:nobj" out="">Frauen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="1:nobj">den</W>
<W lemma="Blick" msd="NC" tag="NN" in="-1:nobj" out="">Blick</W>
<W lemma="auf" msd="SP" tag="APPR" in="4:pobj" out="1:nobj">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj|4:pnct|6:appa">den</W>
<W lemma="smart" msd="AN" tag="ADJA" in="-1:attr" out="">smarten</W>
<W lemma="Typ" msd="NC" tag="NN" in="-2:nobj" out="">Typ</W>
<W lemma="werfen" msd="VAP" tag="VVPP" in="-9:vobj" out="-6:dobj|-4:pobj">geworfen</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="beispielsweise" msd="AN" tag="ADJD" in="1:exem" out="">beispielsweise</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-6:appa" out="-1:exem|1:nobj|3:relr|38:pnct|42:relr">den</W>
<W lemma="Schauspieler" msd="NC" tag="NN" in="-1:nobj" out="">Schauspieler</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="1:dobj" out="">Partick</W>
<W lemma="&lt;unknown&gt;" msd="VA" tag="VVFIN" in="-3:relr" out="-1:dobj|3:conj|11:pnct|13:conj|22:conj">Swayze</W>
<W lemma="(" msd="XP" tag="$(" in="2:pnct" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-3:conj" out="-2:pnct|-1:pnct|1:pnct|5:conj">Ghost</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">und</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="Point" msd="NP" tag="NE" in="1:nobj#" out="">Point</W>
<W lemma="Break" msd="NC" tag="NN" in="-5:conj" out="-3:coord|-2:pnct|-1:nobj#|1:pnct|2:pnct">Break</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="-2:pnct" out="">)</W>
<W lemma="," msd="XP" tag="$," in="-11:pnct" out="">,</W>
<W lemma="Richard" msd="NP" tag="NE" in="1:namef" out="">Richard</W>
<W lemma="&lt;unknown&gt;" msd="VA" tag="VVFIN" in="-13:conj" out="-1:namef|4:appa">Gere</W>
<W lemma="(" msd="XP" tag="$(" in="3:pnct" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="Pretty" msd="NP" tag="NE" in="1:namef" out="">Pretty</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-4:appa" out="-3:pnct|-2:pnct|-1:namef|1:pnct|2:pnct">Woman</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="-2:pnct" out="">)</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="Kevin" msd="NP" tag="NE" in="1:namef" out="">Kevin</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-22:conj" out="-2:coord|-1:namef|3:appa">Costner</W>
<W lemma="(" msd="XP" tag="$(" in="2:pnct" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="Tanz" msd="NC" tag="NN" in="-3:appa" out="-2:pnct|-1:pnct|1:pobj|4:pnct|5:pnct|7:appa|9:pnct">Tanz</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Wolf" msd="NP" tag="NE" in="-1:nobj" out="">Wolf</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-4:pnct" out="">"</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="JFK" msd="NP" tag="NE" in="-7:appa" out="-1:pnct|1:pnct">JFK</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma=")" msd="XP" tag="$(" in="-9:pnct" out="">)</W>
<W lemma="," msd="XP" tag="$," in="-38:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="3:dobj" out="1:attr">die</W>
<W lemma="alle" msd="PP" tag="PIS" in="-1:attr" out="">alle</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:aobj" out="">gut</W>
<W lemma="aussehen" msd="VAF" tag="VVINF" in="-42:relr" out="-3:dobj|-1:aobj|7:conj">aussehen</W>
<W lemma="und" msd="CC" tag="KON" in="6:coord" out="">und</W>
<W lemma="alle" msd="PP" tag="PIS" in="4:dobj" out="1:attr">alles</W>
<W lemma="unter" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">unter</W>
<W lemma="Kontrolle" msd="NC" tag="NN" in="-1:nobj" out="">Kontrolle</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="2:nobj" out="1:vobj">zu</W>
<W lemma="haben" msd="VAF" tag="VAINF" in="-1:vobj" out="-4:dobj">haben</W>
<W lemma="scheinen" msd="VA" tag="VVFIN" in="-7:conj" out="-6:coord|-2:nobj">scheinen</W>
<W lemma="." msd="XP" tag="$." in="-62:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="3:eval" out="1:nobj">In</W>
<W lemma="jed" msd="PI" tag="PIDAT" in="-1:nobj" out="1:nobj">jedem</W>
<W lemma="Fall" msd="NC" tag="NN" in="-1:nobj" out="">Fall</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-3:eval|1:subj|3:preds|18:eval|19:pnct">ist</W>
<W lemma="d" msd="PD" tag="PDAT" in="-1:subj" out="1:nobj">deren</W>
<W lemma="Körper" msd="NC" tag="NN" in="-1:nobj" out="">Körper</W>
<W lemma="weit" msd="AN" tag="ADJD" in="-3:preds" out="1:pobj">weit</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">von</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|4:pnct|9:appa">den</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Cowboys</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="80er" msd="AN" tag="ADJA" in="-1:nobj" out="">80er</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="Sylvester" msd="NC" tag="NN" in="4:namef" out="">Sylvester</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="2:name" out="-1:pnct|1:pnct">Rambo</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-9:appa" out="-4:namef|-2:name|3:conj">Stallone</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="Arnold" msd="NP" tag="NE" in="1:namef" out="">Arnold</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-3:conj" out="-2:coord|-1:namef">Schwarzenegger</W>
<W lemma="entfernt" msd="AN" tag="ADJD" in="-18:eval" out="">entfernt</W>
<W lemma="." msd="XP" tag="$." in="-19:pnct" out="">.</W>
</s>
</p>
