<p>
<s>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="2:subj" out="1:possd">SFs</W>
<W lemma="Vorschlag" msd="NC" tag="NN" in="-1:possd" out="">Vorschlag</W>
<W lemma="beinhalten" msd="VA" tag="VVFIN" in="" out="-2:subj|1:dobj|3:pnct|6:conj|36:pnct">beinhaltet</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:dobj" out="1:nobj">eine</W>
<W lemma="Dreiteilung" msd="NC" tag="NN" in="-1:nobj" out="">Dreiteilung</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj|9:relr">die</W>
<W lemma="Punkt" msd="NC" tag="NN" in="-1:nobj" out="">Punkte</W>
<W lemma="enthalten" msd="VA" tag="VVFIN" in="-6:conj" out="-2:dobj|1:pnct">enthält</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:dobj" out="1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">SF</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="3:neg" out="">nicht</W>
<W lemma="mit" msd="RG" tag="PTKVZ" in="1:part" out="">mit</W>
<W lemma="tragen" msd="VAF" tag="VVINF" in="1:vobj" out="-1:part">tragen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-9:relr" out="-5:dobj|-3:neg|-1:vobj|1:pnct|11:vobj">kann</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="solch" msd="PI" tag="PIDAT" in="9:subj" out="1:pnct">solche</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="7:subj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:subj" out="1:nobj">die</W>
<W lemma="Partei" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Partei</W>
<W lemma="ohne" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">ohne</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Weiteres</W>
<W lemma="mit" msd="RG" tag="PTKVZ" in="1:part" out="">mit</W>
<W lemma="tragen" msd="VAF" tag="VVINF" in="1:vobj" out="-1:part">tragen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-11:vobj" out="-9:subj|-7:subj|-6:subj|-1:vobj|2:subj|3:pnct|11:vobj">kann</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="solch" msd="PP" tag="PIS" in="-2:subj" out="-1:coord">solche</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="7:subj" out="">die</W>
<W lemma="nach" msd="SP" tag="APPR" in="4:time" out="1:nobj">nach</W>
<W lemma="Auffassung" msd="NC" tag="NN" in="-1:nobj" out="">Auffassung</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">SF</W>
<W lemma="verbessern" msd="VAP" tag="VVPP" in="1:vobj" out="-4:time">verbessert</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="1:vobj" out="-1:vobj">werden</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="-11:vobj" out="-7:subj|-1:vobj">müssen</W>
<W lemma="." msd="XP" tag="$." in="-36:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="Steen" msd="NP" tag="NE" in="1:namef" out="">Steen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="1:subj" out="-1:namef">Gade</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:pnct|2:dobj|3:subj|4:dobj|24:pnct">sagt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="21:vobj">dass</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-3:subj" out="">SF</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-4:dobj" out="1:attr|2:nobj|3:pnct">eine</W>
<W lemma="gemeinsam" msd="AN" tag="ADJA" in="-1:attr" out="">gemeinsame</W>
<W lemma="Verteidigung" msd="NC" tag="NN" in="-2:nobj" out="">Verteidigung</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:dobj" out="1:nobj|4:pnct">die</W>
<W lemma="Wirtschaft-" msd="XA" tag="TRUNC" in="-1:nobj" out="2:conj">Wirtschaft-</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Währungsunion" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Währungsunion</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="10:subj" out="-5:dobj|1:nobj">die</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="2:conj">Unionsstaatsbürgerschaft</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Teil" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Teile</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">der</W>
<W lemma="rechtlich" msd="AN" tag="ADJA" in="-1:attr" out="">rechtlichen</W>
<W lemma="Zusammenarbeit" msd="NC" tag="NN" in="-2:nobj" out="">Zusammenarbeit</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="3:neg" out="">nicht</W>
<W lemma="mit" msd="RG" tag="PTKVZ" in="1:part" out="">mit</W>
<W lemma="tragen" msd="VAF" tag="VVINF" in="1:vobj" out="-1:part">tragen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-21:vobj" out="-10:subj|-3:neg|-1:vobj">kann</W>
<W lemma="." msd="XP" tag="$." in="-24:pnct" out="">.</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">Es</W>
<W lemma="können" msd="VA" tag="VMFIN" in="" out="-1:subj|2:neg|6:vobj|7:pnct|9:vobj|10:pnct">kann</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-2:neg" out="-1:add">nicht</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:preds" out="1:nobj">die</W>
<W lemma="Rede" msd="NC" tag="NN" in="-1:nobj" out="">Rede</W>
<W lemma="davon" msd="RG" tag="PAV" in="1:pobj" out="">davon</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-6:vobj" out="-3:preds|-1:pobj">sein</W>
<W lemma="," msd="XP" tag="$," in="-7:pnct" out="">,</W>
<W lemma="Souveränität" msd="NC" tag="NN" in="1:dobj" out="">Souveränität</W>
<W lemma="abgeben" msd="VAF" tag="VVIZU" in="-9:vobj" out="-1:dobj">abzugeben</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="aber" msd="CC" tag="KON" in="3:coord" out="">Aber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">die</W>
<W lemma="Partei" msd="NC" tag="NN" in="-1:nobj" out="">Partei</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-3:coord|-2:subj|1:eval|2:dobj|39:pnct">würde</W>
<W lemma="gerne" msd="RG" tag="ADV" in="-1:eval" out="9:conj">gerne</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-2:dobj" out="1:nobj">einen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj">EG-Ombudsmann</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Verbraucherpolitik" msd="NC" tag="NN" in="-2:conj" out="">Verbraucherpolitik</W>
<W lemma="und" msd="CC" tag="KON" in="4:coord" out="">und</W>
<W lemma="vermutlich" msd="AN" tag="ADJD" in="3:time" out="">vermutlich</W>
<W lemma="auch" msd="RG" tag="ADV" in="2:add" out="">auch</W>
<W lemma="Industriepolitik" msd="NC" tag="NN" in="1:dobj" out="">Industriepolitik</W>
<W lemma="sehen" msd="VA" tag="VVFIN" in="-9:conj" out="-4:coord|-3:time|-2:add|-1:dobj|1:pnct|2:time">sehen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="während" msd="CS" tag="KOUS" in="-2:time" out="7:vobj">während</W>
<W lemma="infolge" msd="SP" tag="APPR" in="5:pobj" out="1:nobj">infolge</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">SF</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="3:dobj" out="1:nobj">eine</W>
<W lemma="Verbesserung" msd="NC" tag="NN" in="-1:nobj" out="">Verbesserung</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="2:preds" out="1:vobj">zu</W>
<W lemma="verhandeln" msd="VAF" tag="VVINF" in="-1:vobj" out="-5:pobj|-3:dobj">verhandeln</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-7:vobj" out="-2:preds|1:pnct|3:subj">ist</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="um" msd="SP" tag="APPR" in="1:quant" out="">um</W>
<W lemma="mehr" msd="PI" tag="PIAT" in="-3:subj" out="-1:quant|1:nobj|2:pnct|3:dobj|8:pnct|10:nobj">mehr</W>
<W lemma="Demokratie" msd="NC" tag="NN" in="-1:nobj" out="">Demokratie</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-3:dobj" out="1:attr|2:nobj">ein</W>
<W lemma="tatsächlich" msd="AN" tag="ADJA" in="-1:attr" out="">tatsächliches</W>
<W lemma="Prinzip" msd="NC" tag="NN" in="-2:nobj" out="">Prinzip</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj|9:nobj">der</W>
<W lemma="Nähe" msd="NC" tag="NN" in="-1:nobj" out="">Nähe</W>
<W lemma="," msd="XP" tag="$," in="-8:pnct" out="">,</W>
<W lemma="gut" msd="AN" tag="ADJA" in="1:attr" out="">bessere</W>
<W lemma="Umweltbestimmung" msd="NC" tag="NN" in="-10:nobj" out="-1:attr|2:conj">Umweltbestimmungen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Recht&7c;Rechte" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Rechte</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:dobj" out="1:nobj">der</W>
<W lemma="Gehaltsempfänger" msd="NC" tag="NN" in="-1:nobj" out="">Gehaltsempfänger</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-9:nobj" out="1:vobj">zu</W>
<W lemma="erreichen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:dobj">erreichen</W>
<W lemma="." msd="XP" tag="$." in="-39:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="3:pnct" out="">"</W>
<W lemma="dies" msd="PD" tag="PDAT" in="2:subj" out="1:nobj">Diese</W>
<W lemma="Dreiteilung" msd="NC" tag="NN" in="-1:nobj" out="">Dreiteilung</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="" out="-3:pnct|-2:subj|1:subj|2:eval|3:vobj|4:pnct">müssen</W>
<W lemma="wir" msd="PP" tag="PPER" in="-1:subj" out="">wir</W>
<W lemma="notwendigerweise" msd="RG" tag="ADV" in="-2:eval" out="">notwendigerweise</W>
<W lemma="anpacken" msd="VAF" tag="VVINF" in="-3:vobj" out="">anpacken</W>
<W lemma="." msd="XP" tag="$." in="-4:pnct" out="">.</W>
<W lemma="wir" msd="PP" tag="PPER" in="1:subj" out="">Wir</W>
<W lemma="mögen" msd="VA" tag="VMFIN" in="37:qobj" out="-1:subj|4:vobj|36:pnct">möchten</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:attr|2:nobj">die</W>
<W lemma="ander" msd="AN" tag="ADJA" in="-1:attr" out="">anderen</W>
<W lemma="Partei" msd="NC" tag="NN" in="-2:nobj" out="">Parteien</W>
<W lemma="bitten" msd="VA" tag="VVFIN" in="-4:vobj" out="-3:subj|1:pnct|4:nobj|7:conj">bitten</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="unser" msd="PO" tag="PPOSAT" in="3:dobj" out="1:possd">unser</W>
<W lemma="Papier" msd="NC" tag="NN" in="-1:possd" out="">Papier</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-4:nobj" out="1:vobj">zu</W>
<W lemma="lesen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:dobj">lesen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="wissen" msd="VA" tag="VVFIN" in="-7:conj" out="-1:coord|1:eval|2:pnct|3:dobj">wüssten</W>
<W lemma="gerne" msd="RG" tag="ADV" in="-1:eval" out="">gerne</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="ob" msd="CS" tag="KOUS" in="-3:dobj" out="5:vobj">ob</W>
<W lemma="sie" msd="PP" tag="PPER" in="4:subj" out="">sie</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="3:neg" out="">nicht</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:preds" out="1:nobj">der</W>
<W lemma="Meinung" msd="NC" tag="NN" in="-1:nobj" out="3:nobj">Meinung</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-3:neg|-2:preds|1:pnct">sind</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-3:nobj" out="13:vobj">dass</W>
<W lemma="wir" msd="PP" tag="PPER" in="12:subj" out="">wir</W>
<W lemma="auf" msd="SP" tag="APPR" in="10:pobj" out="1:nobj">auf</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-1:nobj" out="1:nobj">dieser</W>
<W lemma="Grundlage" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Grundlage</W>
<W lemma="in" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">in</W>
<W lemma="Loyalität" msd="NC" tag="NN" in="-1:nobj" out="">Loyalität</W>
<W lemma="gegenüber" msd="SP" tag="APPR" in="5:pobj" out="1:nobj">gegenüber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Nein" msd="NC" tag="NN" in="-1:nobj" out="">Nein</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Volksabstimmung" msd="NC" tag="NN" in="-1:nobj" out="">Volksabstimmung</W>
<W lemma="anfangen" msd="VAF" tag="VVINF" in="1:vobj" out="-10:pobj|-5:pobj">anfangen</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="-13:vobj" out="-12:subj|-1:vobj|1:pnct">sollen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-36:pnct" out="">"</W>
<W lemma="meinen" msd="VA" tag="VVFIN" in="" out="-37:qobj|2:subj|3:pnct">meint</W>
<W lemma="Steen" msd="NP" tag="NE" in="1:namef" out="">Steen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:subj" out="-1:namef">Gade</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="d" msd="P[ID]" tag="ART" in="16:subj" out="1:nobj">Der</W>
<W lemma="Vorsitzende" msd="NC" tag="NN" in="-1:nobj" out="1:possr">Vorsitzende</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:possr" out="1:nobj|2:attr">des</W>
<W lemma="Ausschuß" msd="NC" tag="NN" in="-1:nobj" out="">Ausschusses</W>
<W lemma="für" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">für</W>
<W lemma="Europafrage" msd="NC" tag="NN" in="-1:nobj" out="">Europafragen</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj|3:pnct|5:appr">des</W>
<W lemma="dänisch" msd="AN" tag="ADJA" in="-1:attr" out="">dänischen</W>
<W lemma="Parlament" msd="NC" tag="NN" in="-2:nobj" out="">Parlaments</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="Ivar" msd="NP" tag="NE" in="1:namef" out="">Ivar</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-5:appr" out="-1:namef|2:appa">Nørgaard</W>
<W lemma="(" msd="XP" tag="$(" in="1:pnct" out="">(</W>
<W lemma="S" msd="NC" tag="NN" in="-2:appa" out="-1:pnct|1:pnct|2:pnct">S</W>
<W lemma=")" msd="XP" tag="$(" in="-1:pnct" out="">)</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-16:subj|1:vobj|28:pnct">hat</W>
<W lemma="sagen" msd="VAP" tag="VVPP" in="-1:vobj" out="1:pnct|2:dobj">gesagt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="10:vobj|14:vobj">dass</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="9:subj" out="">SF</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="7:iobj" out="1:attr|2:attr|3:nobj">einem</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-1:attr" out="">neuen</W>
<W lemma="dänisch" msd="AN" tag="ADJA" in="-2:attr" out="">dänischen</W>
<W lemma="Übereinkommen" msd="NC" tag="NN" in="-3:nobj" out="">Übereinkommen</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:inst" out="1:nobj">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="EG" msd="NC" tag="NN" in="-1:nobj" out="">EG</W>
<W lemma="zustimmen" msd="VAF" tag="VVINF" in="1:vobj" out="-7:iobj|-3:inst">zustimmen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-10:vobj" out="-9:subj|-1:vobj|1:pnct">kann</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="aber" msd="CC" tag="KON" in="2:coord" out="">aber</W>
<W lemma="d" msd="PP" tag="PDS" in="1:subj" out="">das</W>
<W lemma="mögen" msd="VA" tag="VMFIN" in="-14:vobj" out="-2:coord|-1:subj|1:subj|3:pnct|4:appa">möchte</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="-1:subj" out="1:possd">sein</W>
<W lemma="Parteifreund" msd="NC" tag="NN" in="-1:possd" out="">Parteifreund</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-4:appa" out="1:nobj|3:appr">der</W>
<W lemma="EG-Sprecher" msd="NC" tag="NN" in="-1:nobj" out="">EG-Sprecher</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="1:namef" out="">Bjørn</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-3:appr" out="-1:namef|1:pnct|3:relpa">Westh</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="1:neg" out="">nicht</W>
<W lemma="wiederholen" msd="VA" tag="VVFIN" in="-3:relpa" out="-1:neg">wiederholen</W>
<W lemma="." msd="XP" tag="$." in="-28:pnct" out="">.</W>
</s>
</p>
