<p>
<s>
<W lemma="als" msd="CS" tag="KOKOM" in="3:time" out="2:nobj">Als</W>
<W lemma="erfahren" msd="AN" tag="ADJA" in="1:attr" out="">erfahrene</W>
<W lemma="Minderheitsregierung" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Minderheitsregierung</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-3:time|1:dobj|12:vobj|47:pnct">hat</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:dobj" out="1:nobj|4:appr">das</W>
<W lemma="Kabinett" msd="NC" tag="NN" in="-1:nobj" out="">Kabinett</W>
<W lemma="Poul" msd="NP" tag="NE" in="2:namef" out="1:namef">Poul</W>
<W lemma="Schlüter" msd="NP" tag="NE" in="-1:namef" out="">Schlüter</W>
<W lemma="IV" msd="NP" tag="NE" in="-4:appr" out="-2:namef">IV</W>
<W lemma="gerade" msd="RG" tag="PTKVZ" in="1:quant" out="">gerade</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="2:dobj" out="-1:quant|1:nobj">einen</W>
<W lemma="Vorschlag" msd="NC" tag="NN" in="-1:nobj" out="">Vorschlag</W>
<W lemma="für" msd="SP" tag="APPR" in="3:goal" out="-2:dobj|1:nobj">für</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|3:pnct|11:relr">eine</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Finanzgesetzgebung</W>
<W lemma="vorlegen" msd="VAP" tag="VVPP" in="-12:vobj" out="-3:goal">vorgelegt</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="7:subj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:subj" out="1:attr|2:nobj|15:pnct|31:relr">die</W>
<W lemma="gemäßigt" msd="AN" tag="ADJA" in="-1:attr" out="">gemäßigte</W>
<W lemma="Wirtschaftspolitik" msd="NC" tag="NN" in="-2:nobj" out="">Wirtschaftspolitik</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="">letzen</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="">Jahre</W>
<W lemma="fortführen" msd="VA" tag="VVFIN" in="-11:relr" out="-7:subj|-6:subj|1:pnct|2:conc|3:man">fortführt</W>
<W lemma="-" msd="XP" tag="$(" in="-1:pnct" out="">-</W>
<W lemma="aber" msd="RG" tag="ADV" in="-2:conc" out="">aber</W>
<W lemma="ohne" msd="SP" tag="APPR" in="-3:man" out="5:nobj">ohne</W>
<W lemma="provozierend" msd="AN" tag="ADJA" in="4:attr" out="">provozierende</W>
<W lemma="oder" msd="CC" tag="KON" in="1:coord" out="">oder</W>
<W lemma="ideologisch" msd="AN" tag="ADJD" in="1:man" out="-1:coord">ideologisch</W>
<W lemma="bedingt" msd="AN" tag="ADJA" in="1:attr" out="-1:man">bedingte</W>
<W lemma="Sparvorschlag" msd="NC" tag="NN" in="-5:nobj" out="-4:attr|-1:attr">Sparvorschläge</W>
<W lemma="," msd="XP" tag="$," in="-15:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="1:subj" out="">die</W>
<W lemma="d" msd="P[ID]" tag="ART" in="14:dobj" out="-1:subj|1:attr|2:attr|3:nobj">die</W>
<W lemma="ausschlaggebend" msd="AN" tag="ADJA" in="-1:attr" out="">ausschlaggebenden</W>
<W lemma="bürgerlich" msd="AN" tag="ADJA" in="-2:attr" out="">bürgerlichen</W>
<W lemma="Partei" msd="NC" tag="NN" in="-3:nobj" out="">Parteien</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Mitte" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Mitte</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:pobj" out="1:avobj">von</W>
<W lemma="vorn" msd="RG" tag="ADV" in="-1:avobj" out="1:avobj">vorn</W>
<W lemma="herein" msd="RG" tag="ADV" in="-1:avobj" out="">herein</W>
<W lemma="in" msd="SP" tag="APPR" in="5:loc" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">die</W>
<W lemma="Arm&7c;Arme" msd="NC" tag="NN" in="-1:nobj" out="">Arme</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">der</W>
<W lemma="Sozialdemokrat" msd="NC" tag="NN" in="-1:nobj" out="">Sozialdemokraten</W>
<W lemma="treiben" msd="VA" tag="VVFIN" in="-31:relr" out="-14:dobj|-5:loc">treiben</W>
<W lemma="." msd="XP" tag="$." in="-47:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="trotzdem" msd="RG" tag="PAV" in="1:contr" out="">Trotzdem</W>
<W lemma="riskieren" msd="VA" tag="VVFIN" in="" out="-1:contr|1:subj|3:pobj|7:pobj|16:time|24:pnct">riskiert</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">die</W>
<W lemma="Diskussion" msd="NC" tag="NN" in="-1:nobj" out="">Diskussion</W>
<W lemma="über" msd="SP" tag="APPR" in="-3:pobj" out="1:nobj">über</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:appr">die</W>
<W lemma="Wirtschaftspolitik" msd="NC" tag="NN" in="-1:nobj" out="">Wirtschaftspolitik</W>
<W lemma="Dänemark" msd="NP" tag="NE" in="-2:appr" out="">Dänemarks</W>
<W lemma="trotzdem" msd="RG" tag="PAV" in="-7:pobj" out="1:avobj">trotzdem</W>
<W lemma="wieder" msd="RG" tag="ADV" in="-1:avobj" out="1:pobj">wieder</W>
<W lemma="zu" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">zu</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:attr">einer</W>
<W lemma="Frage" msd="NC" tag="NN" in="-1:nobj" out="">Frage</W>
<W lemma="um" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">um</W>
<W lemma="Ideologie" msd="NC" tag="NN" in="-1:nobj" out="">Ideologie</W>
<W lemma="oder" msd="CC" tag="KON" in="2:coord" out="1:pnct">oder</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="-16:time" out="-2:coord|3:vobj">wenn</W>
<W lemma="man" msd="PP" tag="PIS" in="2:subj" out="">man</W>
<W lemma="so" msd="RG" tag="ADV" in="1:eval" out="">so</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="-3:vobj" out="-2:subj|-1:eval|1:pnct|3:nobj">will</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Moral" msd="NC" tag="NN" in="2:dobj" out="">Moral</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-3:nobj" out="1:vobj">zu</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-1:vobj" out="-2:dobj">werden</W>
<W lemma="." msd="XP" tag="$." in="-24:pnct" out="">.</W>
<W lemma="denn" msd="CC" tag="KON" in="5:coord" out="">Denn</W>
<W lemma="mit" msd="SP" tag="APPR" in="4:man" out="3:nobj">mit</W>
<W lemma="sorgfältig" msd="AN" tag="ADJD" in="1:man" out="">sorgfältig</W>
<W lemma="geplant" msd="AN" tag="ADJA" in="1:attr" out="-1:man">geplanter</W>
<W lemma="Präzision" msd="NC" tag="NN" in="-3:nobj" out="-1:attr">Präzision</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-5:coord|-4:man|1:subj|8:pnct|9:conj|11:pnct|16:pnct|17:vobj|18:pnct">haben</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|2:attr">die</W>
<W lemma="Sozialdemokrat" msd="NC" tag="NN" in="-1:nobj" out="">Sozialdemokraten</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-2:attr" out="2:nobj|4:nobj">am</W>
<W lemma="gleich" msd="AN" tag="ADJA" in="1:attr" out="">gleichen</W>
<W lemma="Tag" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Tag</W>
<W lemma="-" msd="XP" tag="$(" in="1:pnct" out="">-</W>
<W lemma="Dienstag" msd="NC" tag="NN" in="-4:nobj" out="-1:pnct">Dienstag</W>
<W lemma="-" msd="XP" tag="$(" in="-8:pnct" out="">-</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-9:conj" out="1:attr|3:possd">ihren</W>
<W lemma="alternativ" msd="AN" tag="ADJA" in="-1:attr" out="">alternativen</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-11:pnct" out="">"</W>
<W lemma="Vorschlag" msd="NC" tag="NN" in="-3:possd" out="">Vorschlag</W>
<W lemma="für" msd="SP" tag="APPR" in="4:goal" out="1:nobj">für</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">ein</W>
<W lemma="Finanzgesetz" msd="NC" tag="NN" in="-1:nobj" out="">Finanzgesetz</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-16:pnct" out="">"</W>
<W lemma="vorlegen" msd="VAP" tag="VVPP" in="-17:vobj" out="-4:goal">vorgelegt</W>
<W lemma="." msd="XP" tag="$." in="-18:pnct" out="">.</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:attr|2:nobj">Die</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="">ideologischen/moralischen</W>
<W lemma="Unterschied" msd="NC" tag="NN" in="-2:nobj" out="">Unterschiede</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-3:subj|1:preds|3:conj|9:pnct">sind</W>
<W lemma="deutlich" msd="AN" tag="ADJD" in="-1:preds" out="">deutlich</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-3:conj" out="-1:coord|3:man|5:vobj|12:pnct">können</W>
<W lemma="grob" msd="AN" tag="ADJD" in="1:man" out="">grob</W>
<W lemma="sagen" msd="VAP" tag="VVPP" in="2:vobj" out="-1:man">gesagt</W>
<W lemma="folgendermaßen" msd="RG" tag="ADV" in="-3:man" out="">folgendermaßen</W>
<W lemma="formulieren" msd="VAP" tag="VVPP" in="1:vobj" out="-2:vobj">formuliert</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-5:vobj" out="-1:vobj|9:vobj">werden</W>
<W lemma="&3a;" msd="XP" tag="$." in="-9:pnct" out="">:</W>
</s>
</p>
<p>
<s>
<W lemma="Sozialdemokratie" msd="NC" tag="NN" in="7:preds" out="">Sozialdemokratie</W>
<W lemma="&3a;" msd="XP" tag="$." in="-12:pnct" out="">:</W>
<W lemma="wir" msd="PP" tag="PPER" in="1:subj" out="">Wir</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-9:vobj" out="-1:subj|1:neg|4:vobj|5:pnct|16:pnct">können</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-1:neg" out="">nicht</W>
<W lemma="dafür" msd="RG" tag="PAV" in="1:pobj" out="12:nobj">dafür</W>
<W lemma="bekennen" msd="VAP" tag="VVPP" in="1:vobj" out="-1:pobj">bekannt</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="-4:vobj" out="-7:preds|-1:vobj">sein</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="9:dobj" out="1:nobj">die</W>
<W lemma="Arbeitslos&7c;Arbeitslose&7c;Arbeitslosen" msd="NC" tag="NN" in="-1:nobj" out="">Arbeitslosen</W>
<W lemma="nach" msd="SP" tag="APPO" in="2:time" out="1:resem">nach</W>
<W lemma="wie" msd="CS" tag="KOKOM" in="-1:resem" out="">wie</W>
<W lemma="vor" msd="SP" tag="APPR" in="3:time" out="-2:time|1:nobj">vor</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">die</W>
<W lemma="Zeche" msd="NC" tag="NN" in="-1:nobj" out="">Zeche</W>
<W lemma="zahlen" msd="VAF" tag="VVINF" in="2:vobj" out="-3:time">zahlen</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-12:nobj" out="1:vobj">zu</W>
<W lemma="lassen" msd="VAF" tag="VVINF" in="-1:vobj" out="-9:dobj|-2:vobj">lassen</W>
<W lemma="." msd="XP" tag="$." in="-16:pnct" out="">.</W>
<W lemma="unser" msd="PO" tag="PPOSAT" in="2:subj" out="1:possd">Unsere</W>
<W lemma="Zahlungsbilanz" msd="NC" tag="NN" in="-1:possd" out="">Zahlungsbilanz</W>
<W lemma="weisen" msd="VA" tag="VVFIN" in="" out="-2:subj|1:dobj|5:part|6:pnct|7:dobj|19:pnct">weist</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:dobj" out="2:attr|3:nobj">einen</W>
<W lemma="derart" msd="RG" tag="ADV" in="1:quant" out="">derart</W>
<W lemma="groß" msd="AN" tag="ADJA" in="-2:attr" out="-1:quant">großen</W>
<W lemma="Überschuß" msd="NC" tag="NN" in="-3:nobj" out="">Überschuss</W>
<W lemma="auf" msd="RG" tag="PTKVZ" in="-5:part" out="">auf</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-7:dobj" out="4:vobj">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:subj" out="1:nobj">das</W>
<W lemma="Geld" msd="NC" tag="NN" in="-1:nobj" out="">Geld</W>
<W lemma="da" msd="RG" tag="ADV" in="1:prg" out="3:goal">da</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:subj|-1:prg|1:pnct">ist</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="um" msd="CS" tag="KOUI" in="-3:goal" out="4:nobj">um</W>
<W lemma="mehr" msd="RG" tag="ADV" in="4:dobj" out="">mehr</W>
<W lemma="in" msd="SP" tag="APPR" in="3:loc" out="1:nobj">in</W>
<W lemma="Dänemark" msd="NP" tag="NE" in="-1:nobj" out="">Dänemark</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-4:nobj" out="1:vobj">zu</W>
<W lemma="bewirken" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:dobj|-3:loc">bewirken</W>
<W lemma="." msd="XP" tag="$." in="-19:pnct" out="">.</W>
<W lemma="wir" msd="PP" tag="PPER" in="1:subj" out="">Wir</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="-1:subj|14:conj">gehen</W>
<W lemma="jetzt" msd="RG" tag="ADV" in="1:focal" out="">jetzt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="12:subj" out="-1:focal|1:nobj|2:appr">das</W>
<W lemma="Risiko" msd="NC" tag="NN" in="-1:nobj" out="">Risiko</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:appr" out="">ein.</W>
<W lemma="bei" msd="SP" tag="APPR" in="9:time" out="1:nobj">Bei</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einer</W>
<W lemma="finanzpolitisch" msd="AN" tag="ADJA" in="-1:attr" out="">finanzpolitischen</W>
<W lemma="Lockerung" msd="NC" tag="NN" in="-2:nobj" out="1:pnct">Lockerung</W>
<W lemma="(" msd="XP" tag="$(" in="-1:pnct" out="3:nobj|4:pnct">(</W>
<W lemma="groß" msd="AN" tag="ADJA" in="2:attr" out="">größeres</W>
<W lemma="öffentlich" msd="AN" tag="ADJA" in="1:attr" out="">öffentliches</W>
<W lemma="Defizit" msd="NC" tag="NN" in="-3:nobj" out="-2:attr|-1:attr">Defizit</W>
<W lemma=")" msd="XP" tag="$(" in="-4:pnct" out="">)</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-14:conj" out="-12:subj|-9:time|1:subj|5:vobj|6:pnct">wird</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:attr|2:nobj">der</W>
<W lemma="privat" msd="AN" tag="ADJA" in="-1:attr" out="">private</W>
<W lemma="Verbrauch" msd="NC" tag="NN" in="-2:nobj" out="">Verbrauch</W>
<W lemma="markant" msd="AN" tag="ADJD" in="1:man" out="">markant</W>
<W lemma="ansteigen" msd="VAF" tag="VVINF" in="-5:vobj" out="-1:man">ansteigen</W>
<W lemma="." msd="XP" tag="$." in="-6:pnct" out="">.</W>
<W lemma="dann" msd="RG" tag="ADV" in="1:cons" out="">Dann</W>
<W lemma="fallen&7c;fällen" msd="VA" tag="VVFIN" in="" out="-1:cons|1:subj|6:vobj|7:pnct">fällt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|3:conj">die</W>
<W lemma="Arbeitslosigkeit" msd="NC" tag="NN" in="-1:nobj" out="">Arbeitslosigkeit</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:conj" out="-1:coord|1:nobj">die</W>
<W lemma="Steuereinnahme" msd="NC" tag="NN" in="-1:nobj" out="">Steuereinnahmen</W>
<W lemma="steigen" msd="VAF" tag="VVINF" in="-6:vobj" out="">steigen</W>
<W lemma="." msd="XP" tag="$." in="-7:pnct" out="">.</W>
<W lemma="Titel" msd="NC" tag="NN" in="" out="8:pnct">Titel</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj|2:pnct">des</W>
<W lemma="Plan" msd="NC" tag="NN" in="-1:nobj" out="4:nobj">Plans</W>
<W lemma="&3a;" msd="XP" tag="$." in="-2:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="2:attr" out="">,,Der</W>
<W lemma="positiv" msd="AN" tag="ADJA" in="1:attr" out="">positive</W>
<W lemma="Kreis" msd="NC" tag="NN" in="-4:nobj" out="-2:attr|-1:attr|1:pnct">Kreis</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="." msd="XP" tag="$." in="-8:pnct" out="">.</W>
</s>
</p>
