<p>
<s>
<W lemma="mit" msd="SP" tag="APPR" in="3:man" out="1:nobj">Mit</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-1:nobj" out="1:pnct">neuer</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="stilvoll" msd="AN" tag="ADJD" in="1:man" out="-3:man">stilvoller</W>
<W lemma="schwarz-weiß" msd="AN" tag="ADJD" in="1:quant" out="-1:man">schwarz-weiß</W>
<W lemma="Vignette" msd="NC" tag="NN" in="3:correl" out="-1:quant|2:conj">Vignette</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Warhol-Pastiches</W>
<W lemma="als" msd="CS" tag="KOKOM" in="20:pobj" out="-3:correl|1:nobj">als</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Studioszenographie</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="2:conj|18:vobj|19:pnct">hat</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-2:conj" out="-1:pnct|1:pnct|2:attr">Synnøve's</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="erst" msd="AN" tag="ADJA" in="-1:attr" out="">ersten</W>
<W lemma="Ausstrahlung" msd="NC" tag="NN" in="-2:nobj" out="">Ausstrahlung</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">des</W>
<W lemma="Herbst" msd="NC" tag="NN" in="-1:nobj" out="">Herbstes</W>
<W lemma="auf" msd="SP" tag="APPR" in="" out="1:nobj">auf</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">TV3</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="1:nobj|2:nobj">die</W>
<W lemma="Low-Budget" msd="NC" tag="NN" in="-1:nobj" out="">Low-Budget</W>
<W lemma="Prägung" msd="NC" tag="NN" in="-2:nobj" out="">Prägung</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">der</W>
<W lemma="erst" msd="AN" tag="ADJA" in="-1:attr" out="">ersten</W>
<W lemma="Ausstrahlung" msd="NC" tag="NN" in="-2:nobj" out="">Ausstrahlungen</W>
<W lemma="verlieren" msd="VAP" tag="VVPP" in="-18:vobj" out="-20:pobj|-6:dobj">verloren</W>
<W lemma="." msd="XP" tag="$." in="-19:pnct" out="">.</W>
<W lemma="auf" msd="SP" tag="APPR" in="4:scene" out="1:nobj">Auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="ander" msd="AN" tag="ADJA" in="-1:attr" out="">anderen</W>
<W lemma="Seite" msd="NC" tag="NN" in="-2:nobj" out="">Seite</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="6:qobj" out="-4:scene|1:dobj|2:eval|4:vobj|5:pnct">hat</W>
<W lemma="es" msd="PP" tag="PPER" in="-1:dobj" out="">es</W>
<W lemma="letzthin" msd="RG" tag="ADV" in="-2:eval" out="">letzthin</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="">so</W>
<W lemma="wirken" msd="VAP" tag="VVPP" in="-4:vobj" out="-1:quant">gewirkt</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="VA" tag="VVFIN" in="" out="-6:qobj|1:subj|10:pnct|11:exem">alsob</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|2:relr|8:relr">die</W>
<W lemma="Gastgeberin" msd="NC" tag="NN" in="-1:nobj" out="">Gastgeberin</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-2:relr" out="1:attr|2:attr|3:possd">ihre</W>
<W lemma="eigen" msd="AN" tag="ADJA" in="-1:attr" out="">eigne</W>
<W lemma="tragend" msd="AN" tag="ADJA" in="-2:attr" out="">tragende</W>
<W lemma="Rolle" msd="NC" tag="NN" in="-3:possd" out="">Rolle</W>
<W lemma="weit" msd="AN" tag="ADJD" in="1:@time" out="">weiter</W>
<W lemma="ausnutzen" msd="VAP" tag="VVPP" in="1:vobj" out="-1:@time">ausgenutzt</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-8:relr" out="-1:vobj">hat</W>
<W lemma="-" msd="XP" tag="$(" in="-10:pnct" out="">-</W>
<W lemma="z." msd="SP+P" tag="APPRART" in="-11:exem" out="">z.</W>
<W lemma="B." msd="NC" tag="NN" in="" out="1:time">B.</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-1:time" out="1:nobj|13:pnct">dieses</W>
<W lemma="Mal" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Mal</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj|2:pnct|9:relr">einem</W>
<W lemma="Striptease" msd="NC" tag="NN" in="-1:nobj" out="">Striptease</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="5:dobj" out="">das</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:subj" out="1:nobj">der</W>
<W lemma="Unterzeichner" msd="NC" tag="NN" in="-1:nobj" out="">Unterzeichner</W>
<W lemma="leider" msd="RG" tag="ADV" in="1:quant" out="">leider</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="2:neg" out="-1:quant">nicht</W>
<W lemma="sehen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:dobj">gesehen</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-9:relr" out="-5:subj|-2:neg|-1:vobj">hat</W>
<W lemma="." msd="XP" tag="$." in="-13:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="zwischen" msd="SP" tag="APPR" in="28:cause" out="2:nobj">Zwischen</W>
<W lemma="schwer" msd="AN" tag="ADJA" in="1:attr" out="">schweren</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|1:attr">Jungens</W>
<W lemma="aus" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">aus</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Klatschpresse" msd="NC" tag="NN" in="-1:nobj" out="3:conj">Klatschpresse</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="stark" msd="AN" tag="ADJA" in="1:attr" out="">starken</W>
<W lemma="Mädchen" msd="NC" tag="NN" in="-3:conj" out="-2:coord|-1:attr|1:resem">Mädchen</W>
<W lemma="wie" msd="CS" tag="KOKOM" in="-1:resem" out="2:nobj">wie</W>
<W lemma="Maiken" msd="NP" tag="NE" in="1:namef" out="">Maiken</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="-1:namef">Wexøe</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="Lone" msd="NP" tag="NE" in="1:namef" out="">Lone</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="1:subj" out="-2:coord|-1:namef">Dybkjær</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-1:subj|1:preds|2:preds|6:eval|9:vobj|12:pnct|13:cause|29:pnct">ist</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:preds" out="">Synnøve</W>
<W lemma="in" msd="SP" tag="APPR" in="-2:preds" out="1:nobj">in</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="gestrig" msd="AN" tag="ADJA" in="-1:attr" out="">gestrigen</W>
<W lemma="Show" msd="NC" tag="NN" in="-2:nobj" out="">Show</W>
<W lemma="jedoch" msd="RG" tag="ADV" in="-6:eval" out="">jedoch</W>
<W lemma="etwas" msd="RG" tag="ADV" in="1:quant" out="">etwas</W>
<W lemma="gedämpfter" msd="AN" tag="ADJD" in="1:man" out="-1:quant">gedämpfter</W>
<W lemma="auftreten" msd="VAP" tag="VVPP" in="-9:vobj" out="-1:man|2:epi">aufgetreten</W>
<W lemma="-" msd="XP" tag="$(" in="1:pnct" out="">-</W>
<W lemma="vielleicht" msd="AN" tag="ADJD" in="-2:epi" out="-1:pnct">vielleicht</W>
<W lemma="," msd="XP" tag="$," in="-12:pnct" out="">,</W>
<W lemma="weil" msd="CS" tag="KOUS" in="-13:cause" out="-28:cause|5:vobj">weil</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="1:nobj">das</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Lack-Kleid</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="4:nobj">so</W>
<W lemma="eng" msd="AN" tag="ADJD" in="1:man" out="-1:quant">eng</W>
<W lemma="sitzen" msd="VA" tag="VVFIN" in="-5:vobj" out="-4:subj|-1:man|1:pnct">saß</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="2:vobj">dass</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">es</W>
<W lemma="knistern" msd="VA" tag="VVFIN" in="-2:vobj" out="-1:subj|1:pnct|2:time">knisterte</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="-2:time" out="4:vobj">wenn</W>
<W lemma="sie" msd="PP" tag="PPER" in="3:subj" out="">sie</W>
<W lemma="zu" msd="RG" tag="PTKA" in="2:quant" out="">zu</W>
<W lemma="sehr" msd="RG" tag="ADV" in="1:quant" out="">sehr</W>
<W lemma="gestikulieren" msd="VA" tag="VVFIN" in="-4:vobj" out="-3:subj|-2:quant|-1:quant">gestikulierte</W>
<W lemma="!" msd="XP" tag="$." in="-29:pnct" out="">!</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">Das</W>
<W lemma="Thema" msd="NC" tag="NN" in="-1:nobj" out="">Thema</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-2:subj|1:preds|4:conj">war</W>
<W lemma="Klatsch" msd="NC" tag="NN" in="-1:preds" out="">Klatsch</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="4:nobj">es</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-4:conj" out="-2:coord|-1:subj|1:preds|2:pnct|15:pnct">ist</W>
<W lemma="typisch" msd="AN" tag="ADJD" in="-1:preds" out="">typisch</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="4:vobj">dass</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="3:subj" out="">Synnøve</W>
<W lemma="zu" msd="SP" tag="APPR" in="2:pobj" out="1:nobj">zu</W>
<W lemma="Hochform" msd="NC" tag="NN" in="-1:nobj" out="">Hochform</W>
<W lemma="auflaufen" msd="VA" tag="VVFIN" in="-4:vobj" out="-3:subj|-2:pobj|1:pnct|2:time">aufläuft</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="-2:time" out="5:vobj">wenn</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="1:nobj">der</W>
<W lemma="Stoff" msd="NC" tag="NN" in="-1:nobj" out="">Stoff</W>
<W lemma="sie" msd="PP" tag="PPER" in="2:dobj" out="">sie</W>
<W lemma="persönlich" msd="AN" tag="ADJD" in="1:man" out="">persönlich</W>
<W lemma="betreffen" msd="VA" tag="VVFIN" in="-5:vobj" out="-4:subj|-2:dobj|-1:man">betrifft</W>
<W lemma="." msd="XP" tag="$." in="-15:pnct" out="">.</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">Auch</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="16:conc" out="-1:add|14:vobj">wenn</W>
<W lemma="nur" msd="RG" tag="ADV" in="1:focal" out="">nur</W>
<W lemma="Maiken" msd="NP" tag="NE" in="1:namef" out="-1:focal">Maiken</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="13:subj" out="-1:namef|1:possd">Wexø</W>
<W lemma="Ziel" msd="NC" tag="NN" in="-1:possd" out="2:conj">Ziele</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Mittel" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Mittel</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj|2:attr">der</W>
<W lemma="Klatschpresse" msd="NC" tag="NN" in="-1:nobj" out="">Klatschpresse</W>
<W lemma="vor" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">vor</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Hintergrund" msd="NC" tag="NN" in="-1:nobj" out="">Hintergrund</W>
<W lemma="eigen" msd="AN" tag="ADJA" in="1:attr" out="">eigener</W>
<W lemma="Erfahrung" msd="NC" tag="NN" in="1:dobj" out="-1:attr">Erfahrungen</W>
<W lemma="kritisieren" msd="VA" tag="VVFIN" in="-14:vobj" out="-1:dobj|1:pnct">kritisierte</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="" out="-16:conc|-13:subj|1:subj|2:subj|24:pnct">war</W>
<W lemma="dies" msd="PP" tag="PDS" in="-1:subj" out="">dies</W>
<W lemma="ein" msd="PP" tag="PIS" in="-2:subj" out="1:pobj">eines</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:pobj" out="1:nobj|2:pnct|20:relr">der</W>
<W lemma="Programm" msd="NC" tag="NN" in="-1:nobj" out="">Programme</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="17:subj" out="">das</W>
<W lemma="d" msd="P[ID]" tag="ART" in="16:subj" out="1:nobj">die</W>
<W lemma="Gastgeberin" msd="NC" tag="NN" in="-1:nobj" out="">Gastgeberin</W>
<W lemma="nach" msd="SP" tag="APPR" in="14:time" out="1:nobj">nach</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:pnct|4:attr|5:nobj">einem</W>
<W lemma="unterhaltend" msd="AN" tag="ADJA" in="-1:attr" out="">unterhaltenden</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:man" out="">gut</W>
<W lemma="gedreht" msd="AN" tag="ADJA" in="-4:attr" out="-1:man">gedrehten</W>
<W lemma="Ablauf" msd="NC" tag="NN" in="-5:nobj" out="1:attr">Ablauf</W>
<W lemma="ohne" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">ohne</W>
<W lemma="Kurzschluß" msd="NC" tag="NN" in="-1:nobj" out="">Kurzschlüsse</W>
<W lemma="unterwegs" msd="RG" tag="ADV" in="5:time" out="">unterwegs</W>
<W lemma="sicher" msd="AN" tag="ADJD" in="4:man" out="">sicher</W>
<W lemma="bis" msd="CC" tag="KON" in="3:time" out="">bis</W>
<W lemma="zum" msd="SP+P" tag="APPRART" in="2:pobj" out="1:nobj">zum</W>
<W lemma="Schluß" msd="NC" tag="NN" in="-1:nobj" out="">Schluss</W>
<W lemma="führen" msd="VA" tag="VVFIN" in="-20:relr" out="-17:subj|-16:subj|-14:time|-5:time|-4:man|-3:time|-2:pobj">führte</W>
<W lemma="." msd="XP" tag="$." in="-24:pnct" out="">.</W>
</s>
</p>
