<p>
<s>
<W lemma="Sie&7c;sie" msd="PP" tag="PPER" in="1:subj" out="">Sie</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-1:subj|1:time|2:time|4:vobj|6:conj|10:pnct">hat</W>
<W lemma="nie" msd="RG" tag="ADV" in="-1:time" out="">nie</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="-2:time" out="">irgendeinen</W>
<W lemma="Notplan" msd="NC" tag="NN" in="1:dobj" out="">Notplan</W>
<W lemma="sehen" msd="VAP" tag="VVPP" in="-4:vobj" out="-1:dobj">gesehen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="kennen" msd="VA" tag="VVFIN" in="-6:conj" out="-1:coord|1:dobj|3:neg">kannte</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="-1:dobj" out="1:possd">ihre</W>
<W lemma="Notrufnummer" msd="NC" tag="NN" in="-1:possd" out="">Notrufnummer</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-3:neg" out="">nicht</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="Anne" msd="NP" tag="NE" in="2:namef" out="1:namef">Anne</W>
<W lemma="Lisbeth" msd="NP" tag="NE" in="-1:namef" out="">Lisbeth</W>
<W lemma="Hammer" msd="NP" tag="NE" in="1:subj" out="-2:namef">Hammer</W>
<W lemma="erzählen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:pnct|2:time|6:vobj|46:pnct">erzählte</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="immer" msd="RG" tag="ADV" in="-2:time" out="1:avobj">immer</W>
<W lemma="wieder" msd="RG" tag="ADV" in="-1:avobj" out="">wieder</W>
<W lemma="von" msd="SP" tag="APPR" in="2:pobj" out="1:nobj">von</W>
<W lemma="Träne&7c;Tränen" msd="NC" tag="NN" in="-1:nobj" out="3:pobj">Tränen</W>
<W lemma="unterbrechen" msd="VAP" tag="VVPP" in="-6:vobj" out="-2:pobj|1:pnct">unterbrochen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="von" msd="SP" tag="APPR" in="-3:pobj" out="1:nobj">von</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:loc">einer</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-1:loc" out="1:nobj">im</W>
<W lemma="Große" msd="NC" tag="NN" in="-1:nobj" out="2:conj|5:nobj">Großen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Ganze" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Ganzen</W>
<W lemma="vollkommen" msd="AN" tag="ADJD" in="2:attr" out="">vollkommen</W>
<W lemma="neu" msd="AN" tag="ADJA" in="1:attr" out="">neuen</W>
<W lemma="Besatzung" msd="NC" tag="NN" in="-5:nobj" out="-2:attr|-1:attr|1:attr">Besatzung</W>
<W lemma="auf" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">auf</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="2:attr|3:nobj|4:pnct|15:relr">einem</W>
<W lemma="ganz" msd="AN" tag="ADJD" in="1:quant" out="">ganz</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-2:attr" out="-1:quant">neuen</W>
<W lemma="Schiff" msd="NC" tag="NN" in="-3:nobj" out="">Schiff</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="auf" msd="SP" tag="APPR" in="10:loc" out="1:nobj">auf</W>
<W lemma="d" msd="PT" tag="PRELS" in="-1:nobj" out="">dem</W>
<W lemma="d" msd="P[ID]" tag="ART" in="8:subj" out="1:nobj">die</W>
<W lemma="Arbeit&7c;Arbeiten" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Arbeiten</W>
<W lemma="zur" msd="SP+P" tag="APPRART" in="-1:pobj" out="1:nobj">zur</W>
<W lemma="Inbetriebnahme" msd="NC" tag="NN" in="-1:nobj" out="">Inbetriebnahme</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">des</W>
<W lemma="Schiff&7c;Schiffes" msd="NC" tag="NN" in="-1:nobj" out="">Schiffes</W>
<W lemma="so" msd="RG" tag="ADV" in="1:quant" out="4:nobj">so</W>
<W lemma="umfangreich" msd="AN" tag="ADJD" in="1:preds" out="-1:quant">umfangreich</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-15:relr" out="-10:loc|-8:subj|-1:preds|1:pnct">waren</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="4:vobj">dass</W>
<W lemma="man" msd="PP" tag="PIS" in="3:subj" out="">man</W>
<W lemma="kein" msd="PI" tag="PIAT" in="2:dobj" out="1:nobj">keine</W>
<W lemma="Zeit" msd="NC" tag="NN" in="-1:nobj" out="2:pnct|6:nobj">Zeit</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:subj|-2:dobj">hatte</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="4:robj" out="">sich</W>
<W lemma="auf" msd="SP" tag="APPR" in="3:pobj" out="1:nobj">auf</W>
<W lemma="Sicherheitsaufgabe" msd="NC" tag="NN" in="-1:nobj" out="">Sicherheitsaufgaben</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-6:nobj" out="1:vobj">zu</W>
<W lemma="konzentrieren" msd="VAF" tag="VVINF" in="-1:vobj" out="-4:robj|-3:pobj">konzentrieren</W>
<W lemma="." msd="XP" tag="$." in="-46:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="3:qobj" out="-1:pnct|1:possd|2:pnct">Scandinavian</W>
<W lemma="Star" msd="NC" tag="NN" in="-1:possd" out="">Star</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-2:pnct" out="">"</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="-3:qobj|1:time">ging</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-1:time" out="1:nobj">am</W>
<W lemma="1." msd="AN" tag="ADJA" in="-1:nobj" out="">1.</W>
<W lemma="April" msd="NC" tag="NN" in="1:nobj" out="">April</W>
<W lemma="1990" msd="AC" tag="CARD" in="12:time" out="-1:nobj|1:attr">1990</W>
<W lemma="auf" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">auf</W>
<W lemma="Jungfernfahrt" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Jungfernfahrt</W>
<W lemma="von" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">von</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="1:attr">Fredrikshavn</W>
<W lemma="nach" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">nach</W>
<W lemma="Oslo" msd="NP" tag="NE" in="-1:nobj" out="">Oslo</W>
<W lemma="und" msd="CC" tag="KON" in="5:coord" out="">und</W>
<W lemma="bereits" msd="RG" tag="ADV" in="4:time" out="">bereits</W>
<W lemma="vor" msd="SP" tag="APPR" in="3:time" out="1:nobj">vor</W>
<W lemma="dies" msd="PD" tag="PDAT" in="-1:nobj" out="1:nobj">dieser</W>
<W lemma="Fahrt" msd="NC" tag="NN" in="-1:nobj" out="">Fahrt</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-12:time|-5:coord|-4:time|-3:time|3:dobj">hatte</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="1:title" out="">Reedereidirektor</W>
<W lemma="Ole" msd="NP" tag="NE" in="1:namef" out="-1:title">Ole</W>
<W lemma="B." msd="NP" tag="NE" in="-3:dobj" out="-1:namef">B.</W>
<W lemma="Hanse" msd="NC" tag="NN" in="" out="1:expl">Hansen</W>
<W lemma="es" msd="PP" tag="PPER" in="-1:expl" out="6:vobj">es</W>
<W lemma="d" msd="P[ID]" tag="ART" in="5:iobj" out="1:nobj">der</W>
<W lemma="Besatzung" msd="NC" tag="NN" in="-1:nobj" out="">Besatzung</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJD" in="3:man" out="2:conj">klipp</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="klar" msd="AN" tag="ADJD" in="-2:conj" out="-1:coord">klar</W>
<W lemma="machen" msd="VAP" tag="VVPP" in="-6:vobj" out="-5:iobj|-3:man|1:pnct|2:dobj|5:attr">gemacht</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="">dass</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">das</W>
<W lemma="Schiff" msd="NC" tag="NN" in="-1:nobj" out="">Schiff</W>
<W lemma="am" msd="SP+P" tag="APPRART" in="-5:attr" out="-2:subj|1:nobj">am</W>
<W lemma="1." msd="AN" tag="ADJA" in="-1:nobj" out="">1.</W>
<W lemma="April" msd="NC" tag="NN" in="6:preds" out="1:pobj">April</W>
<W lemma="zur" msd="SP+P" tag="APPRART" in="-1:pobj" out="1:nobj">zur</W>
<W lemma="Fahrt" msd="NC" tag="NN" in="-1:nobj" out="">Fahrt</W>
<W lemma="mit" msd="SP" tag="APPR" in="2:pobj" out="1:nobj">mit</W>
<W lemma="Passagier" msd="NC" tag="NN" in="-1:nobj" out="">Passagieren</W>
<W lemma="bereit" msd="AN" tag="ADJD" in="1:preds" out="-2:pobj">bereit</W>
<W lemma="sein" msd="VAF" tag="VAINF" in="1:vobj" out="-6:preds|-1:preds">sein</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="2:qobj" out="-1:vobj|1:pnct">musste</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="erläutern" msd="VA" tag="VVFIN" in="" out="-2:qobj|1:subj|3:pnct">erläuterte</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">der</W>
<W lemma="Vertrauensmann" msd="NC" tag="NN" in="-1:nobj" out="">Vertrauensmann</W>
<W lemma="." msd="XP" tag="$." in="-3:pnct" out="">.</W>
<W lemma="d" msd="PP" tag="PDS" in="1:subj" out="">Das</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:subj|4:vobj|5:pnct|17:pnct">wurde</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:accom" out="2:nobj">mit</W>
<W lemma="derartig" msd="AN" tag="ADJA" in="1:attr" out="">derartiger</W>
<W lemma="Bestimmtheit" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Bestimmtheit</W>
<W lemma="sagen" msd="VAP" tag="VVPP" in="-4:vobj" out="-3:accom|2:dobj">gesagt</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="5:vobj">dass</W>
<W lemma="es" msd="PP" tag="PPER" in="4:subj" out="8:nobj">es</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="3:neg" out="">nicht</W>
<W lemma="einmal" msd="RG" tag="ADV" in="1:time" out="">einmal</W>
<W lemma="ansprechen" msd="VAP" tag="VVPP" in="1:vobj" out="-1:time">angesprochen</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-3:neg|-1:vobj|1:pnct">wurde</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:dobj" out="1:nobj">die</W>
<W lemma="Fahrt" msd="NC" tag="NN" in="-1:nobj" out="">Fahrt</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-8:nobj" out="1:vobj">zu</W>
<W lemma="verschieben" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:dobj">verschieben</W>
<W lemma="." msd="XP" tag="$." in="-17:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="Sie&7c;sie" msd="PP" tag="PPER" in="1:subj" out="">Sie</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-1:subj|1:loc">hatte</W>
<W lemma="an" msd="SP" tag="APPR" in="-1:loc" out="1:nobj">an</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einem</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">der</W>
<W lemma="erst" msd="AN" tag="ADJA" in="-1:attr" out="">ersten</W>
<W lemma="Tag" msd="NC" tag="NN" in="-2:nobj" out="1:attr">Tage</W>
<W lemma="nach" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">nach</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="1." msd="AN" tag="ADJA" in="-1:nobj" out="">1.</W>
<W lemma="April" msd="NC" tag="NN" in="" out="1:pobj">April</W>
<W lemma="an" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">an</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einer</W>
<W lemma="Sitzung" msd="NC" tag="NN" in="-1:nobj" out="1:attr">Sitzung</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:attr" out="2:nobj">mit</W>
<W lemma="Ole" msd="NP" tag="NE" in="1:namef" out="">Ole</W>
<W lemma="B." msd="NP" tag="NE" in="-2:nobj" out="-1:namef">B.</W>
<W lemma="Hansen" msd="NP" tag="NE" in="4:subj" out="">Hansen</W>
<W lemma="an" msd="SP" tag="APPR" in="6:pobj" out="1:nobj">an</W>
<W lemma="Bord" msd="NC" tag="NN" in="-1:nobj" out="">Bord</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:attr|2:nobj">der</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="-4:subj">,,Scandinavian</W>
<W lemma="Star" msd="NC" tag="NN" in="-2:nobj" out="1:pnct">Star</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="teilnehmen" msd="VAP" tag="VVPP" in="5:vobj" out="-6:pobj|1:pnct">teilgenommen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="aber" msd="CC" tag="KON" in="3:coord" out="">aber</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">die</W>
<W lemma="Sicherheit" msd="NC" tag="NN" in="-1:nobj" out="">Sicherheit</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-5:vobj|-3:coord|-2:subj|1:cause|3:neg|4:vobj|5:pnct">wurde</W>
<W lemma="dabei" msd="RG" tag="PAV" in="-1:cause" out="">dabei</W>
<W lemma="überhaupt" msd="RG" tag="ADV" in="1:quant" out="">überhaupt</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-3:neg" out="-1:quant">nicht</W>
<W lemma="ansprechen" msd="VAP" tag="VVPP" in="-4:vobj" out="">angesprochen</W>
<W lemma="." msd="XP" tag="$." in="-5:pnct" out="">.</W>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">Es</W>
<W lemma="gehen" msd="VA" tag="VVFIN" in="" out="-1:subj|1:quant|2:pobj|3:pnct|4:dobj|10:pnct">ging</W>
<W lemma="nur" msd="RG" tag="ADV" in="-1:quant" out="">nur</W>
<W lemma="darum" msd="RG" tag="PAV" in="-2:pobj" out="">darum</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="wie" msd="CS" tag="KOUS" in="-4:dobj" out="5:relr">wie</W>
<W lemma="man" msd="PP" tag="PIS" in="4:subj" out="">man</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj">die</W>
<W lemma="Arbeit" msd="NC" tag="NN" in="-1:nobj" out="">Arbeit</W>
<W lemma="bewältigen" msd="VAF" tag="VVINF" in="1:vobj" out="-2:dobj">bewältigen</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="-5:relr" out="-4:subj|-1:vobj">sollte</W>
<W lemma="." msd="XP" tag="$." in="-10:pnct" out="">.</W>
</s>
</p>
