<p>
<s>
<W lemma="er" msd="PP" tag="PPER" in="1:subj" out="">Er</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-1:subj|3:vobj|5:conj|9:pnct">hat</W>
<W lemma="sein" msd="PO" tag="PPOSAT" in="2:dobj" out="1:possd">seinen</W>
<W lemma="Wehrdienst" msd="NC" tag="NN" in="-1:possd" out="">Wehrdienst</W>
<W lemma="leisten" msd="VAP" tag="VVPP" in="-3:vobj" out="-2:dobj">geleistet</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:conj" out="-1:coord|1:preds">war</W>
<W lemma="Mitglied" msd="NC" tag="NN" in="-1:preds" out="">Mitglied</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">des</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="">Territorialheers</W>
<W lemma="." msd="XP" tag="$." in="-9:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="d" msd="PP" tag="PDS" in="1:subj" out="">Das</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="7:qobj" out="-2:pnct|-1:subj|1:subj|2:preds|4:preds|5:pnct|6:pnct|22:pnct">bin</W>
<W lemma="ich" msd="PP" tag="PPER" in="-1:subj" out="">ich</W>
<W lemma="mein" msd="PO" tag="PPOSAT" in="-2:preds" out="1:possd">meinem</W>
<W lemma="Land" msd="NC" tag="NN" in="-1:possd" out="">Land</W>
<W lemma="schuldig" msd="AN" tag="ADJD" in="-4:preds" out="">schuldig</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-6:pnct" out="">"</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="-7:qobj|1:subj|2:pnct|3:conj|25:pnct">sagt</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="räumen" msd="VA" tag="VVFIN" in="-3:conj" out="1:coord|2:fpreds|3:part|4:pnct">räumt</W>
<W lemma="aber" msd="RG" tag="ADV" in="-1:coord" out="4:nobj">aber</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="-2:fpreds" out="">gleichzeitig</W>
<W lemma="ein" msd="RG" tag="PTKVZ" in="-3:part" out="">ein</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-4:nobj" out="5:vobj|8:nobj">dass</W>
<W lemma="d" msd="PP" tag="PDS" in="4:subj" out="">das</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="3:neg" out="">nicht</W>
<W lemma="realistisch" msd="AN" tag="ADJD" in="2:preds" out="">realistisch</W>
<W lemma="genug" msd="RG" tag="ADV" in="1:time" out="">genug</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-5:vobj" out="-4:subj|-3:neg|-2:preds|-1:time">war</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="," msd="XP" tag="$," in="-22:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-8:nobj" out="-2:coord|8:vobj">dass</W>
<W lemma="er" msd="PP" tag="PPER" in="7:subj" out="">er</W>
<W lemma="gerne" msd="RG" tag="ADV" in="6:eval" out="">gerne</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="4:dobj" out="1:attr">einen</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-1:attr" out="">,,richtigen</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="Krieg" msd="NC" tag="NN" in="1:dobj" out="">Krieg</W>
<W lemma="erleben" msd="VAF" tag="VVINF" in="1:vobj" out="-4:dobj|-2:pnct|-1:dobj">erleben</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-8:vobj" out="-7:subj|-6:eval|-1:vobj">würde</W>
<W lemma="." msd="XP" tag="$." in="-25:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="John" msd="NP" tag="NE" in="2:qobj" out="-1:pnct|1:pnct">John</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="-1:pnct" out="">"</W>
<W lemma="erzählen" msd="VA" tag="VVFIN" in="" out="-2:qobj|1:pnct|2:dobj|13:pnct">erzählt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="10:vobj">dass</W>
<W lemma="er" msd="PP" tag="PPER" in="9:subj" out="">er</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="7:robj" out="">sich</W>
<W lemma="vor" msd="SP" tag="APPR" in="3:time" out="1:nobj">vor</W>
<W lemma="einige" msd="PI" tag="PIAT" in="-1:nobj" out="1:nobj">einigen</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahren</W>
<W lemma="zur" msd="SP+P" tag="APPRART" in="3:pobj" out="-3:time|2:nobj">zur</W>
<W lemma="französisch" msd="AN" tag="ADJA" in="1:attr" out="">französischen</W>
<W lemma="Fremdenlegion" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Fremdenlegion</W>
<W lemma="melden" msd="VAP" tag="VVPP" in="1:vobj" out="-7:robj|-3:pobj">gemeldet</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="-10:vobj" out="-9:subj|-1:vobj">hat</W>
<W lemma="." msd="XP" tag="$." in="-13:pnct" out="">.</W>
<W lemma="nach" msd="SP" tag="APPR" in="5:time" out="1:nobj">Nach</W>
<W lemma="sechs" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">sechs</W>
<W lemma="Monat" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Monaten</W>
<W lemma="als" msd="CS" tag="KOKOM" in="-1:pobj" out="1:nobj">als</W>
<W lemma="Rekrut" msd="NC" tag="NN" in="-1:nobj" out="">Rekrut</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-5:time|1:subj|2:eval|3:iter|5:pnct|6:cause|38:pnct">hatte</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="jedoch" msd="RG" tag="ADV" in="-2:eval" out="">jedoch</W>
<W lemma="genug" msd="RG" tag="ADV" in="-3:iter" out="">genug</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="da" msd="CS" tag="KOUS" in="-6:cause" out="-2:coord|8:vobj">da</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:subj" out="1:attr|2:nobj|3:pnct">der</W>
<W lemma="neu" msd="AN" tag="ADJA" in="-1:attr" out="">neue</W>
<W lemma="Vertrag" msd="NC" tag="NN" in="-2:nobj" out="">Vertrag</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="3:dobj" out="">den</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">die</W>
<W lemma="Rekrut" msd="NC" tag="NN" in="-1:nobj" out="">Rekruten</W>
<W lemma="unterzeichnen" msd="VA" tag="VVFIN" in="-8:vobj" out="-7:subj|-3:dobj|-2:subj|1:pnct|3:subj|4:pnct|5:resem">unterzeichnen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="sowohl" msd="CC" tag="KON" in="3:coord" out="">sowohl</W>
<W lemma="sie" msd="PP" tag="PPER" in="-3:subj" out="">ihnen</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="als" msd="CS" tag="KOUS" in="-5:resem" out="-3:coord|6:vobj">als</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="d" msd="P[ID]" tag="ART" in="4:subj" out="-1:add|1:nobj">der</W>
<W lemma="Legion" msd="NC" tag="NN" in="-1:nobj" out="">Legion</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj">das</W>
<W lemma="Recht" msd="NC" tag="NN" in="-1:nobj" out="">Recht</W>
<W lemma="einräumen" msd="VA" tag="VVFIN" in="-6:vobj" out="-4:subj|-2:dobj|1:pnct">einräumen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="nach" msd="SP" tag="APPR" in="7:time" out="1:nobj">nach</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einem</W>
<W lemma="halb" msd="AN" tag="ADJA" in="-1:attr" out="">halben</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-2:nobj" out="1:nobj">Jahr</W>
<W lemma="Probezeit" msd="NC" tag="NN" in="-1:nobj" out="1:vobj">Probezeit</W>
<W lemma="aufhören" msd="VAF" tag="VVIZU" in="-1:vobj" out="1:pnct">aufzuhören</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="fahren" msd="VA" tag="VVFIN" in="4:pnct" out="-7:time|1:subj|2:time">fuhr</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="nach" msd="SP" tag="APPR" in="-2:time" out="1:nobj">nach</W>
<W lemma="Haus" msd="NC" tag="NN" in="-1:nobj" out="">Hause</W>
<W lemma="." msd="XP" tag="$." in="-38:pnct" out="-4:pnct">.</W>
</s>
</p>
<p>
<s>
<W lemma="anschließend" msd="AN" tag="ADJD" in="1:time" out="">Anschließend</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-1:time|1:subj|2:time|10:vobj|11:pnct">hat</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="im" msd="SP+P" tag="APPRART" in="-2:time" out="1:nobj|2:appr">im</W>
<W lemma="Inland" msd="NC" tag="NN" in="-1:nobj" out="">Inland</W>
<W lemma="drei" msd="AC" tag="CARD" in="-2:appr" out="1:nobj">drei</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahre</W>
<W lemma="mit" msd="SP" tag="APPR" in="4:pobj" out="1:nobj">mit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einer</W>
<W lemma="privat" msd="AN" tag="ADJA" in="-1:attr" out="">privaten</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="">Militärgruppe</W>
<W lemma="trainieren" msd="VAP" tag="VVPP" in="-10:vobj" out="-4:pobj">trainiert</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
<W lemma="um" msd="CS" tag="KOUI" in="5:contr" out="">Um</W>
<W lemma="wer" msd="PT" tag="PWS" in="4:subj" out="">wen</W>
<W lemma="es" msd="PP" tag="PPER" in="3:dobj" out="">es</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="2:robj" out="">sich</W>
<W lemma="dabei" msd="RG" tag="PAV" in="1:pobj" out="">dabei</W>
<W lemma="handeln" msd="VA" tag="VVFIN" in="2:cond" out="-5:contr|-4:subj|-3:dobj|-2:robj|-1:pobj|1:pnct">handelt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="" out="-2:cond|1:subj|2:neg|3:vobj|4:pnct|6:conj|20:pnct">will</W>
<W lemma="er" msd="PP" tag="PPER" in="-1:subj" out="">er</W>
<W lemma="nicht" msd="RG" tag="PTKNEG" in="-2:neg" out="">nicht</W>
<W lemma="verraten" msd="VAF" tag="VVINF" in="-3:vobj" out="">verraten</W>
<W lemma="," msd="XP" tag="$," in="-4:pnct" out="">,</W>
<W lemma="offensichtlich" msd="AN" tag="ADJD" in="1:epi" out="">offensichtlich</W>
<W lemma="handeln" msd="VA" tag="VVFIN" in="-6:conj" out="-1:epi|1:subj|2:robj|3:coord|4:pobj">handelt</W>
<W lemma="es" msd="PP" tag="PPER" in="-1:subj" out="">es</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="-2:robj" out="">sich</W>
<W lemma="aber" msd="RG" tag="ADV" in="-3:coord" out="">aber</W>
<W lemma="um" msd="SP" tag="APPR" in="-4:pobj" out="1:nobj">um</W>
<W lemma="Leute" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|8:relr">Leute</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="d" msd="PT" tag="PRELS" in="6:subj" out="">die</W>
<W lemma="für" msd="SP" tag="APPR" in="5:pobj" out="1:nobj">für</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">eine</W>
<W lemma="amerikanisch" msd="AN" tag="ADJA" in="-1:attr" out="">amerikanische</W>
<W lemma="Organisation" msd="NC" tag="NN" in="-2:nobj" out="1:nobj">Organisation</W>
<W lemma="Söldner" msd="NC" tag="NN" in="-1:nobj" out="">Söldner</W>
<W lemma="anheuern" msd="VA" tag="VVFIN" in="-8:relr" out="-6:subj|-5:pobj">anheuern</W>
<W lemma="." msd="XP" tag="$." in="-20:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="15:pnct" out="">"</W>
<W lemma="um" msd="SP" tag="APPR" in="14:time" out="1:nobj">Um</W>
<W lemma="mehr" msd="PI" tag="PIAT" in="-1:nobj" out="1:attr|2:nobj">mehr</W>
<W lemma="richtig" msd="AN" tag="ADJA" in="-1:attr" out="">richtige</W>
<W lemma="Kampferfahrung" msd="NC" tag="NN" in="-2:nobj" out="3:conj">Kampferfahrung</W>
<W lemma="und" msd="CC" tag="KON" in="2:coord" out="">und</W>
<W lemma="damit" msd="RG" tag="PAV" in="1:cause" out="6:nobj">damit</W>
<W lemma="Aussicht" msd="NC" tag="NN" in="-3:conj" out="-2:coord|-1:cause">Aussichten</W>
<W lemma="auf" msd="SP" tag="APPR" in="5:pobj" out="1:nobj">auf</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:nobj">einen</W>
<W lemma="gut" msd="AN" tag="ADJA" in="-1:attr" out="">besseren</W>
<W lemma="Job" msd="NC" tag="NN" in="-2:nobj" out="">Job</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-6:nobj" out="1:vobj">zu</W>
<W lemma="bekommen" msd="VAF" tag="VVINF" in="-1:vobj" out="-5:pobj|1:pnct">bekommen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="haben" msd="VA" tag="VAFIN" in="" out="-15:pnct|-14:time|1:subj|2:time|7:vobj|13:pnct">habe</W>
<W lemma="ich" msd="PP" tag="PPER" in="-1:subj" out="">ich</W>
<W lemma="dann" msd="RG" tag="ADV" in="-2:time" out="">dann</W>
<W lemma="zusammen" msd="RG" tag="ADV" in="4:accom" out="1:pobj">zusammen</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="1:nobj">mit</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">einem</W>
<W lemma="Kamerad" msd="NC" tag="NN" in="-1:nobj" out="">Kameraden</W>
<W lemma="beschließen" msd="VAP" tag="VVPP" in="-7:vobj" out="-4:accom|1:pnct|4:dobj">beschlossen</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="nach" msd="SP" tag="APPR" in="3:@dir" out="1:nobj">nach</W>
<W lemma="Bosnien" msd="NP" tag="NE" in="-1:nobj" out="">Bosnien</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-4:dobj" out="1:vobj">zu</W>
<W lemma="gehen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:@dir">gehen</W>
<W lemma="." msd="XP" tag="$." in="-13:pnct" out="">.</W>
<W lemma="teilweise" msd="AN" tag="ADJD" in="5:man" out="1:pnct">Teilweise</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="weil" msd="CS" tag="KOUS" in="" out="4:vobj">weil</W>
<W lemma="dort" msd="RG" tag="ADV" in="3:loc" out="">dort</W>
<W lemma="gut" msd="AN" tag="ADJD" in="1:man" out="">gut</W>
<W lemma="bezahlen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:man|-1:man|3:man">bezahlt</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:loc|-1:vobj|1:pnct|3:pnct|4:cause|18:pnct">wird</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="teilweise" msd="AN" tag="ADJD" in="-3:man" out="">teilweise</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="weil" msd="CS" tag="KOUS" in="-4:cause" out="4:vobj">weil</W>
<W lemma="ich" msd="PP" tag="PPER" in="3:subj" out="">ich</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:preds" out="1:nobj">der</W>
<W lemma="Meinung" msd="NC" tag="NN" in="-1:nobj" out="">Meinung</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-4:vobj" out="-3:subj|-2:preds|1:pnct|4:preds|6:pnct|9:relr">war</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dadurch" msd="RG" tag="PAV" in="3:pobj" out="">dadurch</W>
<W lemma="jemand" msd="PP" tag="PIS" in="2:dobj" out="">jemandem</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-4:preds" out="1:vobj">zu</W>
<W lemma="helfen" msd="VAF" tag="VVINF" in="-1:vobj" out="-3:pobj|-2:dobj">helfen</W>
<W lemma="," msd="XP" tag="$," in="-6:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">der</W>
<W lemma="Hilfe" msd="NC" tag="NN" in="-1:nobj" out="">Hilfe</W>
<W lemma="brauchen" msd="VA" tag="VVFIN" in="-9:relr" out="-2:subj">brauchte</W>
<W lemma="." msd="XP" tag="$." in="-18:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="" out="">"</W>
</s>
</p>
