<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="3:pnct" out="">"</W>
<W lemma="Aufhören" msd="NC" tag="NN" in="2:subj" out="">Aufhören</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="durchhalten" msd="VA" tag="VVFIN" in="" out="-3:pnct|-2:subj|-1:coord|1:pnct|2:nobj">durchhalten</W>
<W lemma="..." msd="XP" tag="$(" in="-1:pnct" out="">...</W>
<W lemma="!" msd="XP" tag="$." in="-2:nobj" out="">!</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="1:pnct" out="">"</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-1:pnct|1:time|4:vobj|5:pnct|31:vobj|32:pnct">wird</W>
<W lemma="zunächst" msd="RG" tag="ADV" in="-1:time" out="">zunächst</W>
<W lemma="auf" msd="SP" tag="APPR" in="2:loc" out="1:nobj">auf</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NE" in="-1:nobj" out="">Bornholm</W>
<W lemma="ausprobieren" msd="VAP" tag="VVPP" in="-4:vobj" out="-2:loc">ausprobiert</W>
<W lemma="," msd="XP" tag="$," in="-5:pnct" out="">,</W>
<W lemma="wo" msd="PT" tag="PWAV" in="25:time" out="1:nobj">wo</W>
<W lemma="Schätzung" msd="NC" tag="NN" in="-1:nobj" out="1:other">Schätzungen</W>
<W lemma="zufolge" msd="SP" tag="APPO" in="-1:other" out="2:nobj">zufolge</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="1:attr" out="">3 000</W>
<W lemma="Raucher" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|1:pobj">Raucher</W>
<W lemma="mit" msd="SP" tag="APPR" in="-1:pobj" out="2:nobj">mit</W>
<W lemma="erheblich" msd="AN" tag="ADJA" in="1:attr" out="">erheblichem</W>
<W lemma="Zigarettenkonsum" msd="NC" tag="NN" in="-2:nobj" out="-1:attr|1:attr">Zigarettenkonsum</W>
<W lemma="ab" msd="SP" tag="APPR" in="-1:attr" out="1:nobj">ab</W>
<W lemma="Montag" msd="NC" tag="NN" in="-1:nobj" out="">Montag</W>
<W lemma="d" msd="P[ID]" tag="ART" in="7:dobj" out="1:attr|2:nobj">die</W>
<W lemma="kostenlos" msd="AN" tag="ADJA" in="-1:attr" out="">kostenlose</W>
<W lemma="Telefonnummer" msd="NC" tag="NN" in="-2:nobj" out="1:nobj">Telefonnummer</W>
<W lemma="80" msd="AC" tag="CARD" in="-1:nobj" out="1:+">80</W>
<W lemma="30" msd="AC" tag="CARD" in="-1:+" out="1:+">30</W>
<W lemma="31" msd="AC" tag="CARD" in="-1:+" out="1:+">31</W>
<W lemma="30" msd="AC" tag="CARD" in="-1:+" out="">30</W>
<W lemma="anrufen" msd="VAF" tag="VVINF" in="7:dobj" out="-7:dobj|2:conj">anrufen</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="Hilfe" msd="NC" tag="NN" in="-2:conj" out="-1:coord">Hilfe</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="" out="1:nobj">eines</W>
<W lemma="Team" msd="NC" tag="NN" in="-1:nobj" out="">Teams</W>
<W lemma="freiwillig" msd="AN" tag="ADJA" in="1:attr" out="">freiwilliger</W>
<W lemma="Ex-Raucher" msd="NC" tag="NN" in="1:dobj" out="-1:attr">Ex-Raucher</W>
<W lemma="bekommen" msd="VAF" tag="VVINF" in="1:vobj" out="-7:dobj|-1:dobj">bekommen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-31:vobj" out="-25:time|-1:vobj">können</W>
<W lemma="." msd="XP" tag="$." in="-32:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="APPR" in="4:loc" out="1:nobj">In</W>
<W lemma="etwa" msd="RG" tag="ADV" in="-1:nobj" out="">etwa</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="2:subj" out="1:nobj">einem</W>
<W lemma="Jahr" msd="NC" tag="NN" in="-1:nobj" out="">Jahr</W>
<W lemma="sollen" msd="VA" tag="VMFIN" in="" out="-4:loc|-2:subj|1:subj|3:time|10:vobj|11:pnct">soll</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">das</W>
<W lemma="System" msd="NC" tag="NN" in="-1:nobj" out="">System</W>
<W lemma="dann" msd="RG" tag="ADV" in="-3:time" out="">dann</W>
<W lemma="auf" msd="SP" tag="APPR" in="5:pobj" out="1:nobj">auf</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">den</W>
<W lemma="Rest" msd="NC" tag="NN" in="-1:nobj" out="">Rest</W>
<W lemma="d" msd="P[ID]" tag="ART" in="" out="1:nobj">des</W>
<W lemma="Land" msd="NC" tag="NN" in="-1:nobj" out="">Landes</W>
<W lemma="ausdehnen" msd="VAP" tag="VVPP" in="1:vobj" out="-5:pobj">ausgedehnt</W>
<W lemma="werden" msd="VAF" tag="VAINF" in="-10:vobj" out="-1:vobj">werden</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="in" msd="SP" tag="APPR" in="3:time" out="2:nobj">In</W>
<W lemma="früh" msd="AN" tag="ADJA" in="1:attr" out="">früheren</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-2:nobj" out="-1:attr">Raucherkampagnen</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="" out="-3:time|1:subj|3:man|10:vobj|11:pnct">wurden</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj">die</W>
<W lemma="Raucher" msd="NC" tag="NN" in="-1:nobj" out="">Raucher</W>
<W lemma="tendenziell" msd="AN" tag="ADJD" in="-3:man" out="">tendenziell</W>
<W lemma="als" msd="CS" tag="KOKOM" in="6:pobj" out="1:nobj">als</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="-1:nobj" out="1:attr|2:pnct|3:attr|4:nobj">eine</W>
<W lemma="groß" msd="AN" tag="ADJA" in="-1:attr" out="">große</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJA" in="-3:attr" out="">rauchfarbene</W>
<W lemma="Masse" msd="NC" tag="NN" in="-4:nobj" out="">Masse</W>
<W lemma="betrachten" msd="VAP" tag="VVPP" in="-10:vobj" out="-6:pobj">betrachtet</W>
<W lemma="." msd="XP" tag="$." in="-11:pnct" out="">.</W>
<W lemma="aber" msd="RG" tag="ADV" in="9:add" out="1:pnct">Aber</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="7:time" out="5:vobj">wenn</W>
<W lemma="man" msd="PP" tag="PIS" in="74:subj" out="">man</W>
<W lemma="d" msd="P[ID]" tag="ART" in="2:dobj" out="1:nobj">die</W>
<W lemma="Kettenraucher" msd="NC" tag="NN" in="-1:nobj" out="">Kettenraucher</W>
<W lemma="erreichen" msd="VAF" tag="VVINF" in="1:vobj" out="-2:dobj">erreichen</W>
<W lemma="wollen" msd="VA" tag="VMFIN" in="-5:vobj" out="-1:vobj|1:pnct">will</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="müssen" msd="VA" tag="VMFIN" in="25:qobj" out="-9:add|-7:time|1:subj|2:vobj|3:pnct|54:vobj|82:pnct">muss</W>
<W lemma="man" msd="PP" tag="PIS" in="-1:subj" out="">man</W>
<W lemma="verstehen" msd="VAF" tag="VVINF" in="-2:vobj" out="2:dobj">verstehen</W>
<W lemma="," msd="XP" tag="$," in="-3:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:dobj" out="19:vobj">dass</W>
<W lemma="ihr" msd="PO" tag="PPOSAT" in="60:dobj" out="1:possd|3:conj">ihre</W>
<W lemma="Tabaksucht" msd="NC" tag="NN" in="-1:possd" out="">Tabaksucht</W>
<W lemma="und" msd="CC" tag="KON" in="1:coord" out="">und</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-3:conj" out="-1:coord|1:nobj|2:pnct|7:nobj|10:attr">die</W>
<W lemma="Schwierigkeit" msd="NC" tag="NN" in="-1:nobj" out="">Schwierigkeiten</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="er&7c;es&7c;sie&7c;Sie" msd="PR" tag="PRF" in="5:robj" out="">sich</W>
<W lemma="von" msd="SP" tag="APPR" in="4:pobj" out="1:nobj">von</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">der</W>
<W lemma="Zigarette" msd="NC" tag="NN" in="-1:nobj" out="">Zigarette</W>
<W lemma="zu" msd="U=" tag="PTKZU" in="-7:nobj" out="1:vobj">zu</W>
<W lemma="verabschieden" msd="VAF" tag="VVINF" in="-1:vobj" out="-5:robj|-4:pobj|1:pnct">verabschieden</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="von" msd="SP" tag="APPR" in="-10:attr" out="1:nobj">von</W>
<W lemma="Mensch" msd="NC" tag="NN" in="-1:nobj" out="1:pobj.iobj">Mensch</W>
<W lemma="zu" msd="SP" tag="APPR" in="-1:pobj.iobj" out="1:nobj">zu</W>
<W lemma="Mensch" msd="NC" tag="NN" in="-1:nobj" out="">Mensch</W>
<W lemma="anders" msd="RG" tag="ADV" in="1:preds" out="">anders</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-19:vobj" out="-1:preds|1:pnct">sind</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="-25:qobj|1:subj|12:pnct|19:conj">sagt</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|10:nobj">der</W>
<W lemma="Vorsitzende" msd="NC" tag="NN" in="-1:nobj" out="1:possr">Vorsitzende</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:possr" out="1:nobj|2:attr">des</W>
<W lemma="Ausschuß" msd="NC" tag="NN" in="-1:nobj" out="">Ausschusses</W>
<W lemma="für" msd="SP" tag="APPR" in="-2:attr" out="1:nobj">für</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NN" in="-1:nobj" out="1:pnct|2:conj">Tabakschäden</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="Oberarzt" msd="NC" tag="NN" in="-2:conj" out="">Oberarzt</W>
<W lemma="Poul" msd="NP" tag="NE" in="2:namef" out="">Poul</W>
<W lemma="Ebbe" msd="NC" tag="NN" in="1:namel" out="">Ebbe</W>
<W lemma="Nielsen" msd="NP" tag="NE" in="-10:nobj" out="-2:namef|-1:namel">Nielsen</W>
<W lemma="&3a;" msd="XP" tag="$." in="-12:pnct" out="">:</W>
</s>
</p>
<p>
<s>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="2:pnct" out="">"</W>
<W lemma="dafür" msd="RG" tag="PAV" in="1:cons" out="">Dafür</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-19:conj" out="-2:pnct|-1:cons|1:subj">sind</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:subj" out="1:nobj|2:pnct">die</W>
<W lemma="Chance" msd="NC" tag="NN" in="-1:nobj" out="">Chancen</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="d" msd="P[ID]" tag="ART" in="6:dobj" out="1:nobj|2:pnct|26:relr">die</W>
<W lemma="Entscheidung" msd="NC" tag="NN" in="-1:nobj" out="">Entscheidung</W>
<W lemma="," msd="XP" tag="$," in="-2:pnct" out="">,</W>
<W lemma="mit" msd="SP" tag="APPR" in="3:accom" out="1:nobj">mit</W>
<W lemma="d" msd="P[ID]" tag="ART" in="-1:nobj" out="1:nobj">dem</W>
<W lemma="Rauchen" msd="NC" tag="NN" in="-1:nobj" out="">Rauchen</W>
<W lemma="aufhören" msd="VAF" tag="VVIZU" in="-54:vobj" out="-6:dobj|-3:accom|1:pnct">aufzuhören</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="auch" msd="RG" tag="ADV" in="1:add" out="">auch</W>
<W lemma="durchführen" msd="VAF" tag="VVIZU" in="1:vobj" out="-1:add">durchzuführen</W>
<W lemma="groß" msd="AN" tag="ADJD" in="4:fpreds" out="-1:vobj|1:pnct">größer</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="wenn" msd="CS" tag="KOUS" in="14:scene" out="3:vobj|8:vobj">wenn</W>
<W lemma="man" msd="PP" tag="PIS" in="2:subj" out="">man</W>
<W lemma="beraten" msd="VAP" tag="VVPP" in="1:vobj" out="-4:fpreds">beraten</W>
<W lemma="werden" msd="VA" tag="VAFIN" in="-3:vobj" out="-2:subj|-1:vobj">werden</W>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">und</W>
<W lemma="ein" msd="P[ID]" tag="ART" in="2:dobj" out="-60:dobj|1:nobj">eine</W>
<W lemma="Methode" msd="NC" tag="NN" in="-1:nobj" out="">Methode</W>
<W lemma="auswählen" msd="VAF" tag="VVINF" in="1:vobj" out="-3:coord|-2:dobj">auswählen</W>
<W lemma="können" msd="VA" tag="VMFIN" in="-8:vobj" out="-74:subj|-1:vobj|1:pnct">kann</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="hinter" msd="SP" tag="APPR" in="4:source" out="1:nobj">hinter</W>
<W lemma="d" msd="PT" tag="PRELS" in="-1:nobj" out="">der</W>
<W lemma="man" msd="PP" tag="PIS" in="2:subj" out="">man</W>
<W lemma="selber" msd="RG" tag="ADV" in="1:scene" out="">selber</W>
<W lemma="stehen" msd="VA" tag="VVFIN" in="-26:relr" out="-14:scene|-4:source|-2:subj|-1:scene|1:pnct|5:vobj">steht</W>
<W lemma="-" msd="XP" tag="$(" in="-1:pnct" out="">-</W>
<W lemma="und" msd="CC" tag="KON" in="3:coord" out="">und</W>
<W lemma="gleichzeitig" msd="AN" tag="ADJD" in="2:man" out="">gleichzeitig</W>
<W lemma="Hilfe" msd="NC" tag="NN" in="1:dobj" out="">Hilfe</W>
<W lemma="bekommen" msd="VA" tag="VVFIN" in="-5:vobj" out="-3:coord|-2:man|-1:dobj|1:pnct|2:vobj">bekommt</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="durchhalten" msd="VAF" tag="VVIZU" in="-2:vobj" out="">durchzuhalten</W>
<W lemma="." msd="XP" tag="$." in="-82:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="$(" in="6:pnct" out="">"</W>
</s>
</p>
<p>
<s>
<W lemma="es" msd="PP" tag="PPER" in="1:subj" out="">Es</W>
<W lemma="bestehen" msd="VA" tag="VVFIN" in="13:qobj" out="-6:pnct|-1:subj|1:dobj">besteht</W>
<W lemma="kein" msd="PI" tag="PIAT" in="-1:dobj" out="1:nobj">kein</W>
<W lemma="Zweifel" msd="NC" tag="NN" in="-1:nobj" out="1:pobj">Zweifel</W>
<W lemma="daran" msd="RG" tag="PAV" in="-1:pobj" out="1:pnct|2:nobj">daran</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="dass" msd="CS" tag="KOUS" in="-2:nobj" out="6:vobj">dass</W>
<W lemma="viel" msd="PI" tag="PIDAT" in="5:subj" out="1:nobj">viele</W>
<W lemma="Raucher" msd="NC" tag="NN" in="-1:nobj" out="">Raucher</W>
<W lemma="d" msd="P[ID]" tag="ART" in="3:preds" out="1:nobj|8:nobj">den</W>
<W lemma="Tabak" msd="NC" tag="NN" in="-1:nobj" out="">Tabak</W>
<W lemma="leid" msd="AN" tag="ADJD" in="1:preds" out="">leid</W>
<W lemma="sein" msd="VA" tag="VAFIN" in="-6:vobj" out="-5:subj|-3:preds|-1:preds|1:pnct">sind</W>
<W lemma="," msd="XP" tag="$," in="-1:pnct" out="">,</W>
<W lemma="sagen" msd="VA" tag="VVFIN" in="" out="-13:qobj|2:subj|4:pnct">sagt</W>
<W lemma="Poul" msd="NP" tag="NE" in="2:namef" out="">Poul</W>
<W lemma="Ebbe" msd="NC" tag="NN" in="-2:subj" out="">Ebbe</W>
<W lemma="Nielsen" msd="NP" tag="NE" in="-8:nobj" out="-2:namef">Nielsen</W>
<W lemma="&3a;" msd="XP" tag="$." in="-4:pnct" out="">:</W>
</s>
</p>
