<s>
<W id="1" msd="NN" tag="NN" in="" out="">﻿</W>
<W id="2" msd="PRP" tag="PRP" in="1:subj" out="">I</W>
<W id="3" msd="MD" tag="MD" in="" out="-1:subj">will</W>
<W id="4" msd="VB" tag="VB" in="" out="">tell</W>
<W id="5" msd="PRP$" tag="PRP$" in="" out="">my</W>
<W id="6" msd="NN" tag="NN" in="" out="">colleague</W>
<W id="7" msd="," tag="," in="" out="">,</W>
<W id="8" msd="NNP" tag="NNP" in="" out="">Commissioner</W>
<W id="9" msd="NNP" tag="NNP" in="" out="">Verheugen</W>
<W id="10" msd="," tag="," in="" out="">,</W>
<W id="11" msd="IN" tag="IN" in="" out="">of</W>
<W id="12" msd="DT" tag="DT" in="" out="">the</W>
<W id="13" msd="NNS" tag="NNS" in="" out="">views</W>
<W id="14" msd="WDT" tag="WDT" in="" out="">that</W>
<W id="15" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="16" msd="RB" tag="RB" in="" out="">just</W>
<W id="17" msd="VBN" tag="VBN" in="" out="">been</W>
<W id="18" msd="VBN" tag="VBN" in="" out="">expressed</W>
<W id="19" msd="," tag="," in="" out="">,</W>
<W id="20" msd="WDT" tag="WDT" in="" out="">which</W>
<W id="21" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="22" msd="VBP" tag="VBP" in="" out="">know</W>
<W id="23" msd="VBP" tag="VBP" in="" out="">are</W>
<W id="24" msd="VBN" tag="VBN" in="" out="">held</W>
<W id="25" msd="IN" tag="IN" in="" out="">by</W>
<W id="26" msd="JJ" tag="JJ" in="" out="">other</W>
<W id="27" msd="NNS" tag="NNS" in="" out="">Members</W>
<W id="28" msd="IN" tag="IN" in="" out="">of</W>
<W id="29" msd="NNP" tag="NNP" in="" out="">Parliament</W>
<W id="30" msd="." tag="." in="" out="">.</W>
<W id="31" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="32" msd="VBP" tag="VBP" in="" out="">am</W>
<W id="33" msd="JJ" tag="JJ" in="" out="">sure</W>
<W id="34" msd="IN" tag="IN" in="" out="">that</W>
<W id="35" msd="PRP" tag="PRP" in="" out="">he</W>
<W id="36" msd="MD" tag="MD" in="" out="">will</W>
<W id="37" msd="VB" tag="VB" in="" out="">want</W>
<W id="38" msd="TO" tag="TO" in="" out="">to</W>
<W id="39" msd="VB" tag="VB" in="" out="">respond</W>
<W id="40" msd="RB" tag="RB" in="" out="">fully</W>
<W id="41" msd="CC" tag="CC" in="" out="">and</W>
<W id="42" msd="RB" tag="RB" in="" out="">rapidly</W>
<W id="43" msd="TO" tag="TO" in="" out="">to</W>
<W id="44" msd="DT" tag="DT" in="" out="">the</W>
<W id="45" msd="NNS" tag="NNS" in="" out="">concerns</W>
<W id="46" msd="WDT" tag="WDT" in="" out="">which</W>
<W id="47" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="48" msd="RB" tag="RB" in="" out="">just</W>
<W id="49" msd="VBN" tag="VBN" in="" out="">been</W>
<W id="50" msd="VBN" tag="VBN" in="" out="">raised</W>
<W id="51" msd="." tag="." in="" out="">.</W>
</s>
<s>
<W id="54" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="55" msd="VBP" tag="VBP" in="" out="">want</W>
<W id="56" msd="TO" tag="TO" in="" out="">to</W>
<W id="57" msd="VB" tag="VB" in="" out="">make</W>
<W id="58" msd="CD" tag="CD" in="" out="">two</W>
<W id="59" msd="NNS" tag="NNS" in="" out="">points</W>
<W id="60" msd="RB" tag="RB" in="" out="">absolutely</W>
<W id="61" msd="JJ" tag="JJ" in="" out="">clear</W>
<W id="62" msd="." tag="." in="" out="">.</W>
<W id="63" msd="DT" tag="DT" in="" out="">These</W>
<W id="64" msd="VBP" tag="VBP" in="" out="">are</W>
<W id="65" msd="DT" tag="DT" in="" out="">the</W>
<W id="66" msd="JJ" tag="JJ" in="" out="">strong</W>
<W id="67" msd="NNS" tag="NNS" in="" out="">views</W>
<W id="68" msd="IN" tag="IN" in="" out="">of</W>
<W id="69" msd="DT" tag="DT" in="" out="">the</W>
<W id="70" msd="NNP" tag="NNP" in="" out="">Commission</W>
<W id="71" msd="," tag="," in="" out="">,</W>
<W id="72" msd="VBG" tag="VBG" in="" out="">including</W>
<W id="73" msd="PRP$" tag="PRP$" in="" out="">my</W>
<W id="74" msd="NN" tag="NN" in="" out="">colleague</W>
<W id="75" msd="NNP" tag="NNP" in="" out="">Mr</W>
<W id="76" msd="NNP" tag="NNP" in="" out="">Verheugen</W>
<W id="77" msd="." tag="." in="" out="">.</W>
<W id="78" msd="RB" tag="RB" in="" out="">First</W>
<W id="79" msd="IN" tag="IN" in="" out="">of</W>
<W id="80" msd="DT" tag="DT" in="" out="">all</W>
<W id="81" msd="," tag="," in="" out="">,</W>
<W id="82" msd="IN" tag="IN" in="" out="">in</W>
<W id="83" msd="PRP$" tag="PRP$" in="" out="">our</W>
<W id="84" msd="NN" tag="NN" in="" out="">view</W>
<W id="85" msd="," tag="," in="" out="">,</W>
<W id="86" msd="DT" tag="DT" in="" out="">the</W>
<W id="87" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="88" msd="IN" tag="IN" in="" out="">of</W>
<W id="89" msd="DT" tag="DT" in="" out="">the</W>
<W id="90" msd="NNP" tag="NNP" in="" out="">Union</W>
<W id="91" msd="," tag="," in="" out="">,</W>
<W id="92" msd="DT" tag="DT" in="" out="">the</W>
<W id="93" msd="NN" tag="NN" in="" out="">incorporation</W>
<W id="94" msd="IN" tag="IN" in="" out="">of</W>
<W id="95" msd="JJ" tag="JJ" in="" out="">other</W>
<W id="96" msd="JJ" tag="JJ" in="" out="">European</W>
<W id="97" msd="NNS" tag="NNS" in="" out="">countries</W>
<W id="98" msd="IN" tag="IN" in="" out="">in</W>
<W id="99" msd="DT" tag="DT" in="" out="">the</W>
<W id="100" msd="JJ" tag="JJ" in="" out="">liberal</W>
<W id="101" msd="NN" tag="NN" in="" out="">order</W>
<W id="102" msd="IN" tag="IN" in="" out="">of</W>
<W id="103" msd="NNP" tag="NNP" in="" out="">Europe</W>
<W id="104" msd="," tag="," in="" out="">,</W>
<W id="105" msd="VBZ" tag="VBZ" in="" out="">is</W>
<W id="106" msd="DT" tag="DT" in="" out="">the</W>
<W id="107" msd="NN" tag="NN" in="" out="">number</W>
<W id="108" msd="CD" tag="CD" in="" out="">one</W>
<W id="109" msd="NN" tag="NN" in="" out="">priority</W>
<W id="110" msd="IN" tag="IN" in="" out="">that</W>
<W id="111" msd="PRP" tag="PRP" in="" out="">we</W>
<W id="112" msd="VBP" tag="VBP" in="" out="">face</W>
<W id="113" msd="IN" tag="IN" in="" out="">in</W>
<W id="114" msd="DT" tag="DT" in="" out="">the</W>
<W id="115" msd="JJ" tag="JJ" in="" out="">next</W>
<W id="116" msd="JJ" tag="JJ" in="" out="">few</W>
<W id="117" msd="NNS" tag="NNS" in="" out="">years</W>
<W id="118" msd="." tag="." in="" out="">.</W>
<W id="119" msd="IN" tag="IN" in="" out="">In</W>
<W id="120" msd="PRP$" tag="PRP$" in="" out="">my</W>
<W id="121" msd="NN" tag="NN" in="" out="">view</W>
<W id="122" msd="CC" tag="CC" in="" out="">and</W>
<W id="123" msd="DT" tag="DT" in="" out="">the</W>
<W id="124" msd="NN" tag="NN" in="" out="">view</W>
<W id="125" msd="IN" tag="IN" in="" out="">of</W>
<W id="126" msd="JJ" tag="JJ" in="" out="">other</W>
<W id="127" msd="NNS" tag="NNS" in="" out="">members</W>
<W id="128" msd="IN" tag="IN" in="" out="">of</W>
<W id="129" msd="DT" tag="DT" in="" out="">the</W>
<W id="130" msd="NNP" tag="NNP" in="" out="">Commission</W>
<W id="131" msd="," tag="," in="" out="">,</W>
<W id="132" msd="EX" tag="EX" in="" out="">there</W>
<W id="133" msd="VBZ" tag="VBZ" in="" out="">is</W>
<W id="134" msd="RB" tag="RB" in="" out="">not</W>
<W id="135" msd="RB" tag="RB" in="" out="">only</W>
<W id="136" msd="DT" tag="DT" in="" out="">a</W>
<W id="137" msd="JJ" tag="JJ" in="" out="">strategic</W>
<W id="138" msd="CC" tag="CC" in="" out="">and</W>
<W id="139" msd="JJ" tag="JJ" in="" out="">economic</W>
<W id="140" msd="NN" tag="NN" in="" out="">argument</W>
<W id="141" msd="CC" tag="CC" in="" out="">but</W>
<W id="142" msd="RB" tag="RB" in="" out="">also</W>
<W id="143" msd="DT" tag="DT" in="" out="">a</W>
<W id="144" msd="JJ" tag="JJ" in="" out="">moral</W>
<W id="145" msd="NN" tag="NN" in="" out="">argument</W>
<W id="146" msd="IN" tag="IN" in="" out="">for</W>
<W id="147" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="148" msd="." tag="." in="" out="">.</W>
</s>
<s>
<W id="151" msd="PRP" tag="PRP" in="" out="">We</W>
<W id="152" msd="VBP" tag="VBP" in="" out="">want</W>
<W id="153" msd="DT" tag="DT" in="" out="">that</W>
<W id="154" msd="NN" tag="NN" in="" out="">message</W>
<W id="155" msd="TO" tag="TO" in="" out="">to</W>
<W id="156" msd="VB" tag="VB" in="" out="">go</W>
<W id="157" msd="RP" tag="RP" in="" out="">out</W>
<W id="158" msd="JJ" tag="JJ" in="" out="">loud</W>
<W id="159" msd="CC" tag="CC" in="" out="">and</W>
<W id="160" msd="JJ" tag="JJ" in="" out="">clear</W>
<W id="161" msd="TO" tag="TO" in="" out="">to</W>
<W id="162" msd="PDT" tag="PDT" in="" out="">all</W>
<W id="163" msd="DT" tag="DT" in="" out="">the</W>
<W id="164" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="165" msd="NNS" tag="NNS" in="" out="">candidates</W>
<W id="166" msd="." tag="." in="" out="">.</W>
<W id="167" msd="RB" tag="RB" in="" out="">Secondly</W>
<W id="168" msd="," tag="," in="" out="">,</W>
<W id="169" msd="DT" tag="DT" in="" out="">all</W>
<W id="170" msd="IN" tag="IN" in="" out="">of</W>
<W id="171" msd="PRP" tag="PRP" in="" out="">us</W>
<W id="172" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="173" msd="DT" tag="DT" in="" out="">the</W>
<W id="174" msd="NN" tag="NN" in="" out="">task</W>
<W id="175" msd="IN" tag="IN" in="" out="">in</W>
<W id="176" msd="DT" tag="DT" in="" out="">the</W>
<W id="177" msd="JJ" tag="JJ" in="" out="">next</W>
<W id="178" msd="JJ" tag="JJ" in="" out="">few</W>
<W id="179" msd="NNS" tag="NNS" in="" out="">years</W>
<W id="180" msd="IN" tag="IN" in="" out="">of</W>
<W id="181" msd="VBG" tag="VBG" in="" out="">convincing</W>
<W id="182" msd="JJ" tag="JJ" in="" out="">public</W>
<W id="183" msd="NN" tag="NN" in="" out="">opinion</W>
<W id="184" msd="IN" tag="IN" in="" out="">of</W>
<W id="185" msd="WP" tag="WP" in="" out="">what</W>
<W id="186" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="187" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="188" msd="RB" tag="RB" in="" out="">just</W>
<W id="189" msd="VBN" tag="VBN" in="" out="">said</W>
<W id="190" msd="." tag="." in="" out="">.</W>
<W id="191" msd="NNP" tag="NNP" in="" out="">Mr</W>
<W id="192" msd="NNP" tag="NNP" in="" out="">Verheugen</W>
<W id="193" msd="VBD" tag="VBD" in="" out="">was</W>
<W id="194" msd="VBG" tag="VBG" in="" out="">trying</W>
<W id="195" msd="TO" tag="TO" in="" out="">to</W>
<W id="196" msd="VB" tag="VB" in="" out="">make</W>
<W id="197" msd="DT" tag="DT" in="" out="">that</W>
<W id="198" msd="NN" tag="NN" in="" out="">point</W>
<W id="199" msd="RB" tag="RB" in="" out="">very</W>
<W id="200" msd="RB" tag="RB" in="" out="">strongly</W>
<W id="201" msd="." tag="." in="" out="">.</W>
<W id="202" msd="PRP" tag="PRP" in="" out="">We</W>
<W id="203" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="204" msd="TO" tag="TO" in="" out="">to</W>
<W id="205" msd="VB" tag="VB" in="" out="">go</W>
<W id="206" msd="RP" tag="RP" in="" out="">out</W>
<W id="207" msd="CC" tag="CC" in="" out="">and</W>
<W id="208" msd="VB" tag="VB" in="" out="">sell</W>
<W id="209" msd="DT" tag="DT" in="" out="">the</W>
<W id="210" msd="NN" tag="NN" in="" out="">case</W>
<W id="211" msd="IN" tag="IN" in="" out="">for</W>
<W id="212" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="213" msd="TO" tag="TO" in="" out="">to</W>
<W id="214" msd="JJ" tag="JJ" in="" out="">public</W>
<W id="215" msd="NN" tag="NN" in="" out="">opinion</W>
<W id="216" msd="IN" tag="IN" in="" out="">in</W>
<W id="217" msd="PDT" tag="PDT" in="" out="">all</W>
<W id="218" msd="DT" tag="DT" in="" out="">the</W>
<W id="219" msd="NNP" tag="NNP" in="" out="">Member</W>
<W id="220" msd="NNPS" tag="NNPS" in="" out="">States</W>
<W id="221" msd="IN" tag="IN" in="" out="">of</W>
<W id="222" msd="DT" tag="DT" in="" out="">the</W>
<W id="223" msd="NNP" tag="NNP" in="" out="">European</W>
<W id="224" msd="NNP" tag="NNP" in="" out="">Union</W>
<W id="225" msd="." tag="." in="" out="">.</W>
<W id="226" msd="PRP" tag="PRP" in="" out="">It</W>
<W id="227" msd="MD" tag="MD" in="" out="">would</W>
<W id="228" msd="VB" tag="VB" in="" out="">be</W>
<W id="229" msd="JJ" tag="JJ" in="" out="">wrong</W>
<W id="230" msd="IN" tag="IN" in="" out="">if</W>
<W id="231" msd="PRP" tag="PRP" in="" out="">it</W>
<W id="232" msd="VBD" tag="VBD" in="" out="">seemed</W>
<W id="233" msd="TO" tag="TO" in="" out="">to</W>
<W id="234" msd="DT" tag="DT" in="" out="">some</W>
<W id="235" msd="IN" tag="IN" in="" out="">of</W>
<W id="236" msd="PRP$" tag="PRP$" in="" out="">our</W>
<W id="237" msd="NNS" tag="NNS" in="" out="">voters</W>
<W id="238" msd="IN" tag="IN" in="" out="">in</W>
<W id="239" msd="DT" tag="DT" in="" out="">the</W>
<W id="240" msd="JJ" tag="JJ" in="" out="">fifteen</W>
<W id="241" msd="NNP" tag="NNP" in="" out="">Member</W>
<W id="242" msd="NNPS" tag="NNPS" in="" out="">States</W>
<W id="243" msd="IN" tag="IN" in="" out="">that</W>
<W id="244" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="245" msd="VBD" tag="VBD" in="" out="">was</W>
<W id="246" msd="DT" tag="DT" in="" out="">an</W>
<W id="247" msd="NN" tag="NN" in="" out="">issue</W>
<W id="248" msd="IN" tag="IN" in="" out="">for</W>
<W id="249" msd="DT" tag="DT" in="" out="">the</W>
<W id="250" msd="JJ" tag="JJ" in="" out="">political</W>
<W id="251" msd="NNS" tag="NNS" in="" out="">elites</W>
<W id="252" msd="IN" tag="IN" in="" out="">of</W>
<W id="253" msd="NNP" tag="NNP" in="" out="">Europe</W>
<W id="254" msd="." tag="." in="" out="">.</W>
<W id="255" msd="PRP" tag="PRP" in="" out="">We</W>
<W id="256" msd="VBP" tag="VBP" in="" out="">have</W>
<W id="257" msd="TO" tag="TO" in="" out="">to</W>
<W id="258" msd="VB" tag="VB" in="" out="">convince</W>
<W id="259" msd="PRP" tag="PRP" in="" out="">them</W>
<W id="260" msd="IN" tag="IN" in="" out="">that</W>
<W id="261" msd="PRP" tag="PRP" in="" out="">it</W>
<W id="262" msd="VBZ" tag="VBZ" in="" out="">is</W>
<W id="263" msd="IN" tag="IN" in="" out="">in</W>
<W id="264" msd="PRP$" tag="PRP$" in="" out="">their</W>
<W id="265" msd="NNS" tag="NNS" in="" out="">interests</W>
<W id="266" msd="IN" tag="IN" in="" out="">that</W>
<W id="267" msd="PRP" tag="PRP" in="" out="">we</W>
<W id="268" msd="VB" tag="VB" in="" out="">enlarge</W>
<W id="269" msd="CC" tag="CC" in="" out="">and</W>
<W id="270" msd="IN" tag="IN" in="" out="">that</W>
<W id="271" msd="EX" tag="EX" in="" out="">there</W>
<W id="272" msd="VBZ" tag="VBZ" in="" out="">is</W>
<W id="273" msd="DT" tag="DT" in="" out="">an</W>
<W id="274" msd="NN" tag="NN" in="" out="">obligation</W>
<W id="275" msd="IN" tag="IN" in="" out="">on</W>
<W id="276" msd="PRP" tag="PRP" in="" out="">us</W>
<W id="277" msd="TO" tag="TO" in="" out="">to</W>
<W id="278" msd="VB" tag="VB" in="" out="">press</W>
<W id="279" msd="DT" tag="DT" in="" out="">the</W>
<W id="280" msd="NN" tag="NN" in="" out="">case</W>
<W id="281" msd="IN" tag="IN" in="" out="">for</W>
<W id="282" msd="NN" tag="NN" in="" out="">enlargement</W>
<W id="283" msd="." tag="." in="" out="">.</W>
<W id="284" msd="DT" tag="DT" in="" out="">That</W>
<W id="285" msd="VBZ" tag="VBZ" in="" out="">is</W>
<W id="286" msd="RB" tag="RB" in="" out="">certainly</W>
<W id="287" msd="DT" tag="DT" in="" out="">a</W>
<W id="288" msd="NN" tag="NN" in="" out="">cause</W>
<W id="289" msd="IN" tag="IN" in="" out="">about</W>
<W id="290" msd="WDT" tag="WDT" in="" out="">which</W>
<W id="291" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="292" msd="VBP" tag="VBP" in="" out="">feel</W>
<W id="293" msd="RB" tag="RB" in="" out="">very</W>
<W id="294" msd="RB" tag="RB" in="" out="">strongly</W>
<W id="295" msd="CC" tag="CC" in="" out="">and</W>
<W id="296" msd="WDT" tag="WDT" in="" out="">which</W>
<W id="297" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="298" msd="VBP" tag="VBP" in="" out="">know</W>
<W id="299" msd="NNP" tag="NNP" in="" out="">President</W>
<W id="300" msd="NNP" tag="NNP" in="" out="">Prodi</W>
<W id="301" msd="CC" tag="CC" in="" out="">and</W>
<W id="302" msd="DT" tag="DT" in="" out="">the</W>
<W id="303" msd="NN" tag="NN" in="" out="">rest</W>
<W id="304" msd="IN" tag="IN" in="" out="">of</W>
<W id="305" msd="DT" tag="DT" in="" out="">the</W>
<W id="306" msd="NNP" tag="NNP" in="" out="">Commission</W>
<W id="307" msd="MD" tag="MD" in="" out="">will</W>
<W id="308" msd="VB" tag="VB" in="" out="">be</W>
<W id="309" msd="VBG" tag="VBG" in="" out="">arguing</W>
<W id="310" msd="IN" tag="IN" in="" out="">with</W>
<W id="311" msd="NN" tag="NN" in="" out="">vigour</W>
<W id="312" msd="CC" tag="CC" in="" out="">and</W>
<W id="313" msd="NN" tag="NN" in="" out="">passion</W>
<W id="314" msd="IN" tag="IN" in="" out="">over</W>
<W id="315" msd="DT" tag="DT" in="" out="">the</W>
<W id="316" msd="JJ" tag="JJ" in="" out="">next</W>
<W id="317" msd="JJ" tag="JJ" in="" out="">few</W>
<W id="318" msd="NNS" tag="NNS" in="" out="">years</W>
<W id="319" msd="." tag="." in="" out="">.</W>
</s>
<s>
<W id="322" msd="DT" tag="DT" in="" out="">The</W>
<W id="323" msd="NN" tag="NN" in="" out="">point</W>
<W id="324" msd="IN" tag="IN" in="" out="">that</W>
<W id="325" msd="DT" tag="DT" in="" out="">the</W>
<W id="326" msd="JJ" tag="JJ" in="" out="">honourable</W>
<W id="327" msd="NNP" tag="NNP" in="" out="">Member</W>
<W id="328" msd="VBD" tag="VBD" in="" out="">raised</W>
<W id="329" msd="VBZ" tag="VBZ" in="" out="">expresses</W>
<W id="330" msd="DT" tag="DT" in="" out="">a</W>
<W id="331" msd="JJ" tag="JJ" in="" out="">legitimate</W>
<W id="332" msd="CC" tag="CC" in="" out="">and</W>
<W id="333" msd="JJ" tag="JJ" in="" out="">understandable</W>
<W id="334" msd="NN" tag="NN" in="" out="">concern</W>
<W id="335" msd="." tag="." in="" out="">.</W>
<W id="336" msd="PRP" tag="PRP" in="" out="">I</W>
<W id="337" msd="MD" tag="MD" in="" out="">will</W>
<W id="338" msd="VB" tag="VB" in="" out="">relay</W>
<W id="339" msd="PRP" tag="PRP" in="" out="">it</W>
<W id="340" msd="TO" tag="TO" in="" out="">to</W>
<W id="341" msd="NNP" tag="NNP" in="" out="">Commissioner</W>
<W id="342" msd="NNP" tag="NNP" in="" out="">Verheugen</W>
<W id="343" msd="." tag="." in="" out="">.</W>
</s>
<s>
<W id="346" msd="(" tag="(" in="" out="">(</W>
<W id="347" msd="NN" tag="NN" in="" out="">Applause</W>
<W id="348" msd=")" tag=")" in="" out="">)</W>
</s>
