<s>
<W msd="NN" tag="NN">﻿</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">tell</W>
<W msd="PRP$" tag="PRP$">my</W>
<W msd="NN" tag="NN">colleague</W>
<W msd="," tag=",">,</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="NNP" tag="NNP">Verheugen</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">views</W>
<W msd="WDT" tag="WDT">that</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="RB" tag="RB">just</W>
<W msd="VBN" tag="VBN">been</W>
<W msd="VBN" tag="VBN">expressed</W>
<W msd="," tag=",">,</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">know</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="VBN" tag="VBN">held</W>
<W msd="IN" tag="IN">by</W>
<W msd="JJ" tag="JJ">other</W>
<W msd="NNS" tag="NNS">Members</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">am</W>
<W msd="JJ" tag="JJ">sure</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">want</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">respond</W>
<W msd="RB" tag="RB">fully</W>
<W msd="CC" tag="CC">and</W>
<W msd="RB" tag="RB">rapidly</W>
<W msd="TO" tag="TO">to</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">concerns</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="RB" tag="RB">just</W>
<W msd="VBN" tag="VBN">been</W>
<W msd="VBN" tag="VBN">raised</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">want</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">make</W>
<W msd="CD" tag="CD">two</W>
<W msd="NNS" tag="NNS">points</W>
<W msd="RB" tag="RB">absolutely</W>
<W msd="JJ" tag="JJ">clear</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">These</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">strong</W>
<W msd="NNS" tag="NNS">views</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="," tag=",">,</W>
<W msd="VBG" tag="VBG">including</W>
<W msd="PRP$" tag="PRP$">my</W>
<W msd="NN" tag="NN">colleague</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">Verheugen</W>
<W msd="." tag=".">.</W>
<W msd="RB" tag="RB">First</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">all</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">in</W>
<W msd="PRP$" tag="PRP$">our</W>
<W msd="NN" tag="NN">view</W>
<W msd="," tag=",">,</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Union</W>
<W msd="," tag=",">,</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">incorporation</W>
<W msd="IN" tag="IN">of</W>
<W msd="JJ" tag="JJ">other</W>
<W msd="JJ" tag="JJ">European</W>
<W msd="NNS" tag="NNS">countries</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">liberal</W>
<W msd="NN" tag="NN">order</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNP" tag="NNP">Europe</W>
<W msd="," tag=",">,</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">number</W>
<W msd="CD" tag="CD">one</W>
<W msd="NN" tag="NN">priority</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">face</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">next</W>
<W msd="JJ" tag="JJ">few</W>
<W msd="NNS" tag="NNS">years</W>
<W msd="." tag=".">.</W>
<W msd="IN" tag="IN">In</W>
<W msd="PRP$" tag="PRP$">my</W>
<W msd="NN" tag="NN">view</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">view</W>
<W msd="IN" tag="IN">of</W>
<W msd="JJ" tag="JJ">other</W>
<W msd="NNS" tag="NNS">members</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="," tag=",">,</W>
<W msd="EX" tag="EX">there</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="RB" tag="RB">not</W>
<W msd="RB" tag="RB">only</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">strategic</W>
<W msd="CC" tag="CC">and</W>
<W msd="JJ" tag="JJ">economic</W>
<W msd="NN" tag="NN">argument</W>
<W msd="CC" tag="CC">but</W>
<W msd="RB" tag="RB">also</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">moral</W>
<W msd="NN" tag="NN">argument</W>
<W msd="IN" tag="IN">for</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">want</W>
<W msd="DT" tag="DT">that</W>
<W msd="NN" tag="NN">message</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">go</W>
<W msd="RP" tag="RP">out</W>
<W msd="JJ" tag="JJ">loud</W>
<W msd="CC" tag="CC">and</W>
<W msd="JJ" tag="JJ">clear</W>
<W msd="TO" tag="TO">to</W>
<W msd="PDT" tag="PDT">all</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="NNS" tag="NNS">candidates</W>
<W msd="." tag=".">.</W>
<W msd="RB" tag="RB">Secondly</W>
<W msd="," tag=",">,</W>
<W msd="DT" tag="DT">all</W>
<W msd="IN" tag="IN">of</W>
<W msd="PRP" tag="PRP">us</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">task</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">next</W>
<W msd="JJ" tag="JJ">few</W>
<W msd="NNS" tag="NNS">years</W>
<W msd="IN" tag="IN">of</W>
<W msd="VBG" tag="VBG">convincing</W>
<W msd="JJ" tag="JJ">public</W>
<W msd="NN" tag="NN">opinion</W>
<W msd="IN" tag="IN">of</W>
<W msd="WP" tag="WP">what</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="RB" tag="RB">just</W>
<W msd="VBN" tag="VBN">said</W>
<W msd="." tag=".">.</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">Verheugen</W>
<W msd="VBD" tag="VBD">was</W>
<W msd="VBG" tag="VBG">trying</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">make</W>
<W msd="DT" tag="DT">that</W>
<W msd="NN" tag="NN">point</W>
<W msd="RB" tag="RB">very</W>
<W msd="RB" tag="RB">strongly</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">go</W>
<W msd="RP" tag="RP">out</W>
<W msd="CC" tag="CC">and</W>
<W msd="VB" tag="VB">sell</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">case</W>
<W msd="IN" tag="IN">for</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="TO" tag="TO">to</W>
<W msd="JJ" tag="JJ">public</W>
<W msd="NN" tag="NN">opinion</W>
<W msd="IN" tag="IN">in</W>
<W msd="PDT" tag="PDT">all</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="NNPS" tag="NNPS">States</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">European</W>
<W msd="NNP" tag="NNP">Union</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">It</W>
<W msd="MD" tag="MD">would</W>
<W msd="VB" tag="VB">be</W>
<W msd="JJ" tag="JJ">wrong</W>
<W msd="IN" tag="IN">if</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="VBD" tag="VBD">seemed</W>
<W msd="TO" tag="TO">to</W>
<W msd="DT" tag="DT">some</W>
<W msd="IN" tag="IN">of</W>
<W msd="PRP$" tag="PRP$">our</W>
<W msd="NNS" tag="NNS">voters</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">fifteen</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="NNPS" tag="NNPS">States</W>
<W msd="IN" tag="IN">that</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="VBD" tag="VBD">was</W>
<W msd="DT" tag="DT">an</W>
<W msd="NN" tag="NN">issue</W>
<W msd="IN" tag="IN">for</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">political</W>
<W msd="NNS" tag="NNS">elites</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNP" tag="NNP">Europe</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">convince</W>
<W msd="PRP" tag="PRP">them</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="IN" tag="IN">in</W>
<W msd="PRP$" tag="PRP$">their</W>
<W msd="NNS" tag="NNS">interests</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VB" tag="VB">enlarge</W>
<W msd="CC" tag="CC">and</W>
<W msd="IN" tag="IN">that</W>
<W msd="EX" tag="EX">there</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="DT" tag="DT">an</W>
<W msd="NN" tag="NN">obligation</W>
<W msd="IN" tag="IN">on</W>
<W msd="PRP" tag="PRP">us</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">press</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">case</W>
<W msd="IN" tag="IN">for</W>
<W msd="NN" tag="NN">enlargement</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">That</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="RB" tag="RB">certainly</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">cause</W>
<W msd="IN" tag="IN">about</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">feel</W>
<W msd="RB" tag="RB">very</W>
<W msd="RB" tag="RB">strongly</W>
<W msd="CC" tag="CC">and</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">know</W>
<W msd="NNP" tag="NNP">President</W>
<W msd="NNP" tag="NNP">Prodi</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">rest</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">be</W>
<W msd="VBG" tag="VBG">arguing</W>
<W msd="IN" tag="IN">with</W>
<W msd="NN" tag="NN">vigour</W>
<W msd="CC" tag="CC">and</W>
<W msd="NN" tag="NN">passion</W>
<W msd="IN" tag="IN">over</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">next</W>
<W msd="JJ" tag="JJ">few</W>
<W msd="NNS" tag="NNS">years</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="DT" tag="DT">The</W>
<W msd="NN" tag="NN">point</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">honourable</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="VBD" tag="VBD">raised</W>
<W msd="VBZ" tag="VBZ">expresses</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">legitimate</W>
<W msd="CC" tag="CC">and</W>
<W msd="JJ" tag="JJ">understandable</W>
<W msd="NN" tag="NN">concern</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">relay</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="TO" tag="TO">to</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="NNP" tag="NNP">Verheugen</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="(" tag="(">(</W>
<W msd="NN" tag="NN">Applause</W>
<W msd=")" tag=")">)</W>
</s>
