<s>
<W msd="NN" tag="NN">﻿</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">President</W>
<W msd="," tag=",">,</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">thank</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="IN" tag="IN">for</W>
<W msd="PRP$" tag="PRP$">his</W>
<W msd="NNS" tag="NNS">comments</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="RB" tag="RB">especially</W>
<W msd="VBP" tag="VBP">welcome</W>
<W msd="DT" tag="DT">those</W>
<W msd="NNS" tag="NNS">comments</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">in</W>
<W msd="NN" tag="NN">effect</W>
<W msd="," tag=",">,</W>
<W msd="VBD" tag="VBD">suggested</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">repercussions</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">go</W>
<W msd="RB" tag="RB">far</W>
<W msd="IN" tag="IN">beyond</W>
<W msd="NNS" tag="NNS">bananas</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">That</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="JJ" tag="JJ">true</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">This</W>
<W msd="NN" tag="NN">ruling</W>
<W msd="NNS" tag="NNS">spells</W>
<W msd="NN" tag="NN">despair</W>
<W msd="IN" tag="IN">for</W>
<W msd="JJ" tag="JJ">many</W>
<W msd="NNP" tag="NNP">ACP</W>
<W msd="NNS" tag="NNS">countries</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">They</W>
<W msd="RB" tag="RB">now</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">tremendous</W>
<W msd="NN" tag="NN">fear</W>
<W msd="IN" tag="IN">of</W>
<W msd="JJ" tag="JJ">future</W>
<W msd="NNP" tag="NNP">WTO</W>
<W msd="NNS" tag="NNS">rulings</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="IN" tag="IN">Unlike</W>
<W msd="DT" tag="DT">some</W>
<W msd="IN" tag="IN">of</W>
<W msd="PRP$" tag="PRP$">my</W>
<W msd="NNS" tag="NNS">colleagues</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBD" tag="VBD">did</W>
<W msd="RB" tag="RB">not</W>
<W msd="VB" tag="VB">expect</W>
<W msd="RB" tag="RB">too</W>
<W msd="RB" tag="RB">much</W>
<W msd="IN" tag="IN">from</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="POS" tag="POS">'s</W>
<W msd="NN" tag="NN">statement</W>
<W msd="IN" tag="IN">at</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">point</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">The</W>
<W msd="NN" tag="NN">reason</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">say</W>
<W msd="DT" tag="DT">that</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="IN" tag="IN">because</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">hope</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="RB" tag="RB">still</W>
<W msd="VBG" tag="VBG">discussing</W>
<W msd="IN" tag="IN">with</W>
<W msd="PRP$" tag="PRP$">his</W>
<W msd="NNS" tag="NNS">colleagues</W>
<W msd="WDT" tag="WDT">what</W>
<W msd="VBP" tag="VBP">approach</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">take</W>
<W msd="TO" tag="TO">to</W>
<W msd="NN" tag="NN">arbitration</W>
<W msd="IN" tag="IN">on</W>
<W msd="CD" tag="CD">25</W>
<W msd="NNP" tag="NNP">September</W>
<W msd="." tag=".">.</W>
<W msd="WP" tag="WP">What</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">need</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">know</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="IN" tag="IN">whether</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="VBN" tag="VBN">determined</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">get</W>
<W msd="IN" tag="IN">as</W>
<W msd="JJ" tag="JJ">good</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">result</W>
<W msd="IN" tag="IN">as</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="MD" tag="MD">can</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="RB" tag="RB">now</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">make</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJS" tag="JJS">best</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">bad</W>
<W msd="NN" tag="NN">job</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">The</W>
<W msd="NN" tag="NN">ruling</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="VBN" tag="VBN">been</W>
<W msd="VBN" tag="VBN">made</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">whether</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="IN" tag="IN">like</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="CC" tag="CC">or</W>
<W msd="RB" tag="RB">not</W>
<W msd="." tag=".">.</W>
<W msd="WP" tag="WP">What</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="RB" tag="RB">now</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">do</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="VB" tag="VB">try</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">salvage</W>
<W msd="NN" tag="NN">something</W>
<W msd="IN" tag="IN">from</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="WRB" tag="WRB">When</W>
<W msd="NNP" tag="NNP">Mrs</W>
<W msd="NNP" tag="NNP">Kinnock</W>
<W msd="," tag=",">,</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">Thomas</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBD" tag="VBD">were</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Windward</W>
<W msd="NNP" tag="NNP">Islands</W>
<W msd="IN" tag="IN">in</W>
<W msd="NNP" tag="NNP">May</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="VBD" tag="VBD">was</W>
<W msd="RB" tag="RB">quite</W>
<W msd="JJ" tag="JJ">obvious</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">producers</W>
<W msd="EX" tag="EX">there</W>
<W msd="VBD" tag="VBD">were</W>
<W msd="VBG" tag="VBG">living</W>
<W msd="IN" tag="IN">in</W>
<W msd="NN" tag="NN">fear</W>
<W msd=":" tag=":">-</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">mean</W>
<W msd="NN" tag="NN">fear</W>
<W msd=":" tag=":">-</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">WTO</W>
<W msd="NN" tag="NN">ruling</W>
<W msd="." tag=".">.</W>
<W msd="RB" tag="RB">Now</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="VBN" tag="VBN">appeared</W>
<W msd="," tag=",">,</W>
<W msd="NN" tag="NN">goodness</W>
<W msd="VBZ" tag="VBZ">knows</W>
<W msd="WP" tag="WP">what</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="VBP" tag="VBP">feel</W>
<W msd="IN" tag="IN">like</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">They</W>
<W msd="VBD" tag="VBD">said</W>
<W msd="TO" tag="TO">to</W>
<W msd="PRP" tag="PRP">us</W>
<W msd="IN" tag="IN">that</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="VBP" tag="VBP">accept</W>
<W msd="DT" tag="DT">that</W>
<W msd="NN" tag="NN">liberalization</W>
<W msd="CC" tag="CC">and</W>
<W msd="NN" tag="NN">globalization</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="JJ" tag="JJ">inevitable</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">future</W>
<W msd="." tag=".">.</W>
<W msd="CC" tag="CC">But</W>
<W msd="WP" tag="WP">what</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="VBP" tag="VBP">need</W>
<W msd="JJR" tag="JJR">more</W>
<W msd="IN" tag="IN">than</W>
<W msd="NN" tag="NN">anything</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="NN" tag="NN">time</W>
<W msd=":" tag=":">-</W>
<W msd="NN" tag="NN">time</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">adjust</W>
<W msd="TO" tag="TO">to</W>
<W msd="DT" tag="DT">a</W>
<W msd="RB" tag="RB">very</W>
<W msd="JJ" tag="JJ">competitive</W>
<W msd="NN" tag="NN">market</W>
<W msd=":" tag=":">;</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">some</W>
<W msd="NNS" tag="NNS">cases</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">take</W>
<W msd="IN" tag="IN">at</W>
<W msd="JJS" tag="JJS">least</W>
<W msd="CD" tag="CD">five</W>
<W msd="NNS" tag="NNS">years</W>
<W msd="CC" tag="CC">and</W>
<W msd="IN" tag="IN">in</W>
<W msd="JJ" tag="JJ">other</W>
<W msd="NNS" tag="NNS">cases</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">take</W>
<W msd="DT" tag="DT">a</W>
<W msd="RB" tag="RB">far</W>
<W msd="JJR" tag="JJR">longer</W>
<W msd="NN" tag="NN">period</W>
<W msd="IN" tag="IN">until</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="MD" tag="MD">can</W>
<W msd="VB" tag="VB">compete</W>
<W msd="IN" tag="IN">with</W>
<W msd="JJ" tag="JJ">dollar-banana</W>
<W msd="NNS" tag="NNS">producers</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="PRP" tag="PRP">I</W>
<W msd="RB" tag="RB">therefore</W>
<W msd="VBP" tag="VBP">ask</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">take</W>
<W msd="DT" tag="DT">that</W>
<W msd="IN" tag="IN">on</W>
<W msd="NN" tag="NN">board</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">It</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="JJ" tag="JJ">essential</W>
<W msd="." tag=".">.</W>
<W msd="IN" tag="IN">If</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="MD" tag="MD">can</W>
<W msd="VB" tag="VB">get</W>
<W msd="DT" tag="DT">those</W>
<W msd="NNS" tag="NNS">types</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNS" tag="NNS">concessions</W>
<W msd="IN" tag="IN">from</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">arbitration</W>
<W msd="NN" tag="NN">deal</W>
<W msd="IN" tag="IN">on</W>
<W msd="CD" tag="CD">25</W>
<W msd="NNP" tag="NNP">September</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">have</W>
<W msd="VBN" tag="VBN">done</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Windward</W>
<W msd="NNPS" tag="NNPS">Islands</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">tremendous</W>
<W msd="NN" tag="NN">favour</W>
<W msd="." tag=".">.</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="VBZ" tag="VBZ">wants</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">help</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">want</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">play</W>
<W msd="PRP$" tag="PRP$">our</W>
<W msd="NN" tag="NN">part</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">do</W>
<W msd="RB" tag="RB">so</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">support</W>
<W msd="PRP" tag="PRP">you</W>
<W msd=":" tag=":">;</W>
<W msd="CC" tag="CC">but</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">need</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">commitment</W>
<W msd="IN" tag="IN">from</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">this</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">real</W>
<W msd="NN" tag="NN">attempt</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">salvage</W>
<W msd="NN" tag="NN">something</W>
<W msd="IN" tag="IN">from</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">deal</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">am</W>
<W msd="JJ" tag="JJ">afraid</W>
<W msd="IN" tag="IN">that</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">case</W>
<W msd="JJ" tag="JJ">free</W>
<W msd="NN" tag="NN">trade</W>
<W msd="VBZ" tag="VBZ">means</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">those</W>
<W msd="NNS" tag="NNS">countries</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="JJ" tag="JJ">free</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">see</W>
<W msd="PRP$" tag="PRP$">their</W>
<W msd="NNS" tag="NNS">economies</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP$" tag="PRP$">their</W>
<W msd="NNS" tag="NNS">democracies</W>
<W msd="RB" tag="RB">actually</W>
<W msd="NN" tag="NN">collapse</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">This</W>
<W msd="NN" tag="NN">arbitration</W>
<W msd="NN" tag="NN">outcome</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="JJ" tag="JJ">essential</W>
<W msd="." tag=".">.</W>
</s>
