<s>
<W msd="NN" tag="NN">﻿</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">President</W>
<W msd="," tag=",">,</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">at</W>
<W msd="NN" tag="NN">sea</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">priority</W>
<W msd="IN" tag="IN">for</W>
<W msd="PRP" tag="PRP">us</W>
<W msd="DT" tag="DT">all</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">European</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">in</W>
<W msd="JJ" tag="JJ">particular</W>
<W msd="IN" tag="IN">for</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Socialist</W>
<W msd="NNP" tag="NNP">Group</W>
<W msd="." tag=".">.</W>
<W msd="NNP" tag="NNP">Tonight</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="VBN" tag="VBN">pleased</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">be</W>
<W msd="JJ" tag="JJ">able</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">offer</W>
<W msd="PRP$" tag="PRP$">our</W>
<W msd="JJ" tag="JJ">full</W>
<W msd="NN" tag="NN">support</W>
<W msd="TO" tag="TO">to</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">rapporteur</W>
<W msd="," tag=",">,</W>
<W msd="NNP" tag="NNP">Mr</W>
<W msd="NNP" tag="NNP">Stenmarck</W>
<W msd="," tag=",">,</W>
<W msd="WP" tag="WP">who</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">as</W>
<W msd="RB" tag="RB">ever</W>
<W msd="," tag=",">,</W>
<W msd="VBD" tag="VBD">worked</W>
<W msd="IN" tag="IN">on</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">proposal</W>
<W msd="IN" tag="IN">for</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">directive</W>
<W msd="IN" tag="IN">with</W>
<W msd="JJ" tag="JJ">great</W>
<W msd="NN" tag="NN">skill</W>
<W msd="CC" tag="CC">and</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="VBN" tag="VBN">steered</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">proposal</W>
<W msd="IN" tag="IN">through</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">committee</W>
<W msd="IN" tag="IN">with</W>
<W msd="JJ" tag="JJ">great</W>
<W msd="NN" tag="NN">speed</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="VBP" tag="VBP">am</W>
<W msd="JJ" tag="JJ">happy</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">endorse</W>
<W msd="WP" tag="WP">what</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="RB" tag="RB">just</W>
<W msd="VBN" tag="VBN">said</W>
<W msd="CC" tag="CC">and</W>
<W msd="VB" tag="VB">thank</W>
<W msd="PRP" tag="PRP">him</W>
<W msd="," tag=",">,</W>
<W msd="PRP$" tag="PRP$">our</W>
<W msd="NN" tag="NN">staff</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="NN" tag="NN">staff</W>
<W msd="IN" tag="IN">for</W>
<W msd="VBG" tag="VBG">producing</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">proposal</W>
<W msd="WDT" tag="WDT">which</W>
<W msd="MD" tag="MD">will</W>
<W msd="RB" tag="RB">significantly</W>
<W msd="VB" tag="VB">enhance</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">at</W>
<W msd="NN" tag="NN">sea</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="PRP$" tag="PRP$">Our</W>
<W msd="NN" tag="NN">argument</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="RB" tag="RB">simply</W>
<W msd="IN" tag="IN">that</W>
<W msd="NNS" tag="NNS">millions</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNP" tag="NNP">EU</W>
<W msd="NNS" tag="NNS">citizens</W>
<W msd="VBP" tag="VBP">travel</W>
<W msd="IN" tag="IN">by</W>
<W msd="DT" tag="DT">some</W>
<W msd="NN" tag="NN">form</W>
<W msd="IN" tag="IN">of</W>
<W msd="JJ" tag="JJ">maritime</W>
<W msd="NN" tag="NN">vehicle</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">They</W>
<W msd="RB" tag="RB">already</W>
<W msd="VBP" tag="VBP">believe</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="VBN" tag="VBN">protected</W>
<W msd="IN" tag="IN">by</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">EU</W>
<W msd="." tag=".">.</W>
<W msd="IN" tag="IN">In</W>
<W msd="DT" tag="DT">some</W>
<W msd="NNS" tag="NNS">cases</W>
<W msd="," tag=",">,</W>
<W msd="UH" tag="UH">alas</W>
<W msd="," tag=",">,</W>
<W msd="WDT" tag="WDT">that</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="RB" tag="RB">not</W>
<W msd="RB" tag="RB">so</W>
<W msd="." tag=".">.</W>
<W msd="NN" tag="NN">Passenger</W>
<W msd="NNS" tag="NNS">ships</W>
<W msd="VBN" tag="VBN">involved</W>
<W msd="IN" tag="IN">in</W>
<W msd="JJ" tag="JJ">domestic</W>
<W msd="NNS" tag="NNS">voyages</W>
<W msd="CC" tag="CC">and</W>
<W msd="JJ" tag="JJ">international</W>
<W msd="NN" tag="NN">passenger</W>
<W msd="NNS" tag="NNS">ships</W>
<W msd="VBN" tag="VBN">engaged</W>
<W msd="IN" tag="IN">in</W>
<W msd="NNS" tag="NNS">voyages</W>
<W msd="WRB" tag="WRB">where</W>
<W msd="PRP" tag="PRP">they</W>
<W msd="VBP" tag="VBP">do</W>
<W msd="RB" tag="RB">not</W>
<W msd="VB" tag="VB">venture</W>
<W msd="RB" tag="RB">further</W>
<W msd="IN" tag="IN">than</W>
<W msd="CD" tag="CD">20</W>
<W msd="NNS" tag="NNS">miles</W>
<W msd="IN" tag="IN">from</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJS" tag="JJS">nearest</W>
<W msd="NN" tag="NN">land</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="RB" tag="RB">not</W>
<W msd="VBN" tag="VBN">covered</W>
<W msd="IN" tag="IN">at</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">moment</W>
<W msd="IN" tag="IN">by</W>
<W msd="JJ" tag="JJ">sufficient</W>
<W msd="NNS" tag="NNS">safeguards</W>
<W msd="IN" tag="IN">for</W>
<W msd="NN" tag="NN">safety</W>
<W msd="CC" tag="CC">and</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="JJ" tag="JJ">glad</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="VBN" tag="VBN">brought</W>
<W msd="JJ" tag="JJ">forward</W>
<W msd="NNS" tag="NNS">proposals</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">close</W>
<W msd="DT" tag="DT">these</W>
<W msd="NNS" tag="NNS">loopholes</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="RB" tag="RB">Moreover</W>
<W msd="," tag=",">,</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">context</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">single</W>
<W msd="NN" tag="NN">market</W>
<W msd="," tag=",">,</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">think</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="JJ" tag="JJ">important</W>
<W msd=":" tag=":">-</W>
<W msd="NN" tag="NN">bearing</W>
<W msd="IN" tag="IN">in</W>
<W msd="NN" tag="NN">mind</W>
<W msd="IN" tag="IN">in</W>
<W msd="CD" tag="CD">1993</W>
<W msd="JJ" tag="JJ">maritime</W>
<W msd="JJ" tag="JJ">domestic</W>
<W msd="NN" tag="NN">trade</W>
<W msd="VBD" tag="VBD">was</W>
<W msd="VBN" tag="VBN">liberalized</W>
<W msd=":" tag=":">-</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">measure</W>
<W msd="MD" tag="MD">will</W>
<W msd="RB" tag="RB">further</W>
<W msd="VB" tag="VB">consolidate</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">single</W>
<W msd="NN" tag="NN">market</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">welcome</W>
<W msd="PRP" tag="PRP">it</W>
<W msd="IN" tag="IN">for</W>
<W msd="DT" tag="DT">that</W>
<W msd="NN" tag="NN">reason</W>
<W msd="RB" tag="RB">as</W>
<W msd="RB" tag="RB">well</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">It</W>
<W msd="VBZ" tag="VBZ">represents</W>
<W msd="DT" tag="DT">a</W>
<W msd="JJ" tag="JJ">single</W>
<W msd="," tag=",">,</W>
<W msd="JJ" tag="JJ">simple</W>
<W msd="," tag=",">,</W>
<W msd="JJ" tag="JJ">safe</W>
<W msd="," tag=",">,</W>
<W msd="JJ" tag="JJ">harmonized</W>
<W msd="NN" tag="NN">regime</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">all</W>
<W msd="NNS" tag="NNS">sides</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">this</W>
<W msd="NNP" tag="NNP">House</W>
<W msd="MD" tag="MD">can</W>
<W msd="VB" tag="VB">support</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="RB" tag="RB">However</W>
<W msd="," tag=",">,</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="MD" tag="MD">should</W>
<W msd="VB" tag="VB">like</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">focus</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commission</W>
<W msd="POS" tag="POS">'s</W>
<W msd="NN" tag="NN">mind</W>
<W msd="IN" tag="IN">on</W>
<W msd="DT" tag="DT">another</W>
<W msd="NN" tag="NN">issue</W>
<W msd="." tag=".">.</W>
<W msd="DT" tag="DT">This</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="CD" tag="CD">one</W>
<W msd="IN" tag="IN">of</W>
<W msd="JJ" tag="JJ">many</W>
<W msd="NNS" tag="NNS">measures</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="VBN" tag="VBN">been</W>
<W msd="RB" tag="RB">proudly</W>
<W msd="VBN" tag="VBN">associated</W>
<W msd="IN" tag="IN">with</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">enhance</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">at</W>
<W msd="NN" tag="NN">sea</W>
<W msd="." tag=".">.</W>
<W msd="CC" tag="CC">But</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">issue</W>
<W msd="WDT" tag="WDT">that</W>
<W msd="RB" tag="RB">now</W>
<W msd="VBZ" tag="VBZ">comes</W>
<W msd="IN" tag="IN">before</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="VBZ" tag="VBZ">is</W>
<W msd="WRB" tag="WRB">how</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="MD" tag="MD">can</W>
<W msd="JJS" tag="JJS">best</W>
<W msd="VB" tag="VB">ensure</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">this</W>
<W msd="NN" tag="NN">measure</W>
<W msd="CC" tag="CC">and</W>
<W msd="PDT" tag="PDT">all</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">measures</W>
<W msd="IN" tag="IN">for</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">at</W>
<W msd="NN" tag="NN">sea</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="RB" tag="RB">swiftly</W>
<W msd="VBN" tag="VBN">implemented</W>
<W msd="IN" tag="IN">by</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="NNPS" tag="NNPS">States</W>
<W msd="RB" tag="RB">rigorously</W>
<W msd="CC" tag="CC">and</W>
<W msd="RB" tag="RB">fairly</W>
<W msd="." tag=".">.</W>
<W msd="JJ" tag="JJ">Many</W>
<W msd="IN" tag="IN">of</W>
<W msd="PRP" tag="PRP">us</W>
<W msd="IN" tag="IN">on</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">committee</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="VBN" tag="VBN">concerned</W>
<W msd="IN" tag="IN">that</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">good</W>
<W msd="NN" tag="NN">work</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="CC" tag="CC">and</W>
<W msd="IN" tag="IN">of</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="MD" tag="MD">will</W>
<W msd="VB" tag="VB">come</W>
<W msd="TO" tag="TO">to</W>
<W msd="RB" tag="RB">very</W>
<W msd="JJ" tag="JJ">little</W>
<W msd="IN" tag="IN">unless</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="NNPS" tag="NNPS">States</W>
<W msd="VB" tag="VB">abide</W>
<W msd="IN" tag="IN">by</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">letter</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">laws</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">agree</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">European</W>
<W msd="NNP" tag="NNP">Union</W>
<W msd="." tag=".">.</W>
</s>
<s>
<W msd="RB" tag="RB">Perhaps</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="MD" tag="MD">could</W>
<W msd="VB" tag="VB">comment</W>
<W msd="NN" tag="NN">briefly</W>
<W msd="IN" tag="IN">on</W>
<W msd="WRB" tag="WRB">how</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="MD" tag="MD">can</W>
<W msd="JJS" tag="JJS">best</W>
<W msd="NN" tag="NN">work</W>
<W msd="RB" tag="RB">together</W>
<W msd="IN" tag="IN">in</W>
<W msd="DT" tag="DT">the</W>
<W msd="VBG" tag="VBG">coming</W>
<W msd="NN" tag="NN">year</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">ensure</W>
<W msd="NNS" tag="NNS">proposals</W>
<W msd="JJ" tag="JJ">such</W>
<W msd="IN" tag="IN">as</W>
<W msd="DT" tag="DT">this</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">many</W>
<W msd="NNS" tag="NNS">others</W>
<W msd="IN" tag="IN">on</W>
<W msd="JJ" tag="JJ">port</W>
<W msd="NN" tag="NN">state</W>
<W msd="NN" tag="NN">control</W>
<W msd="VBP" tag="VBP">are</W>
<W msd="RB" tag="RB">effectively</W>
<W msd="VBN" tag="VBN">implemented</W>
<W msd="IN" tag="IN">by</W>
<W msd="NNP" tag="NNP">Member</W>
<W msd="NNPS" tag="NNPS">States</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">I</W>
<W msd="MD" tag="MD">would</W>
<W msd="VB" tag="VB">like</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">see</W>
<W msd="DT" tag="DT">a</W>
<W msd="NN" tag="NN">time</W>
<W msd="WRB" tag="WRB">when</W>
<W msd="DT" tag="DT">this</W>
<W msd="NNP" tag="NNP">Parliament</W>
<W msd="MD" tag="MD">could</W>
<W msd="VB" tag="VB">spend</W>
<W msd="JJR" tag="JJR">more</W>
<W msd="NN" tag="NN">time</W>
<W msd="VBG" tag="VBG">focusing</W>
<W msd="IN" tag="IN">on</W>
<W msd="CC" tag="CC">and</W>
<W msd="VBG" tag="VBG">reviewing</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">legislation</W>
<W msd="WDT" tag="WDT">that</W>
<W msd="VBZ" tag="VBZ">has</W>
<W msd="RB" tag="RB">already</W>
<W msd="VBN" tag="VBN">been</W>
<W msd="VBN" tag="VBN">agreed</W>
<W msd="RB" tag="RB">rather</W>
<W msd="IN" tag="IN">than</W>
<W msd="VBG" tag="VBG">commenting</W>
<W msd="IN" tag="IN">on</W>
<W msd="CC" tag="CC">and</W>
<W msd="VBG" tag="VBG">contemplating</W>
<W msd="JJ" tag="JJ">future</W>
<W msd="NN" tag="NN">legislation</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="RB" tag="RB">now</W>
<W msd="VBP" tag="VBP">have</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">ammunition</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNS" tag="NNS">tools</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">need</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">achieve</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">at</W>
<W msd="NN" tag="NN">sea</W>
<W msd="IN" tag="IN">at</W>
<W msd="DT" tag="DT">a</W>
<W msd="RB" tag="RB">much</W>
<W msd="JJR" tag="JJR">higher</W>
<W msd="CC" tag="CC">and</W>
<W msd="RBR" tag="RBR">more</W>
<W msd="JJ" tag="JJ">acceptable</W>
<W msd="NN" tag="NN">level</W>
<W msd="." tag=".">.</W>
<W msd="PRP" tag="PRP">We</W>
<W msd="VBP" tag="VBP">need</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">work</W>
<W msd="IN" tag="IN">with</W>
<W msd="DT" tag="DT">the</W>
<W msd="NNP" tag="NNP">Commissioner</W>
<W msd="TO" tag="TO">to</W>
<W msd="VB" tag="VB">ensure</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">good</W>
<W msd="NN" tag="NN">work</W>
<W msd="PRP" tag="PRP">he</W>
<W msd="VBZ" tag="VBZ">does</W>
<W msd="CC" tag="CC">and</W>
<W msd="DT" tag="DT">the</W>
<W msd="JJ" tag="JJ">good</W>
<W msd="NN" tag="NN">work</W>
<W msd="PRP" tag="PRP">we</W>
<W msd="VBP" tag="VBP">do</W>
<W msd="IN" tag="IN">with</W>
<W msd="PRP" tag="PRP">him</W>
<W msd="MD" tag="MD">can</W>
<W msd="VB" tag="VB">be</W>
<W msd="VBN" tag="VBN">implemented</W>
<W msd="IN" tag="IN">for</W>
<W msd="DT" tag="DT">the</W>
<W msd="NN" tag="NN">safety</W>
<W msd="IN" tag="IN">of</W>
<W msd="DT" tag="DT">the</W>
<W msd="VBG" tag="VBG">traveling</W>
<W msd="NN" tag="NN">public</W>
<W msd="." tag=".">.</W>
</s>
