<s>
<W id="1" msd="NOM" tag="NOM" in="" out="">Signor</W>
<W id="2" msd="ADJ" tag="ADJ" in="" out="">Presidente</W>
<W id="3" msd="PON" tag="PON" in="" out="">,</W>
<W id="4" msd="DET&3a;def" tag="DET&3a;def" in="" out="">la</W>
<W id="5" msd="NOM" tag="NOM" in="" out="1:ref">relazione</W>
<W id="6" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="7" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">viene</W>
<W id="8" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">proposta</W>
<W id="9" msd="NOM" tag="NOM" in="" out="">è</W>
<W id="10" msd="DET&3a;def" tag="DET&3a;def" in="" out="">il</W>
<W id="11" msd="NOM" tag="NOM" in="" out="">frutto</W>
<W id="12" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="13" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">un</W>
<W id="14" msd="NOM" tag="NOM" in="" out="">dibattito</W>
<W id="15" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">approfondito</W>
<W id="16" msd="PRE" tag="PRE" in="" out="">in</W>
<W id="17" msd="NOM" tag="NOM" in="" out="">sede</W>
<W id="18" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="19" msd="NOM" tag="NOM" in="" out="">commissione</W>
<W id="20" msd="CON" tag="CON" in="" out="">e</W>
<W id="21" msd="PRO&3a;pers" tag="PRO&3a;pers" in="" out="">mi</W>
<W id="22" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">pare</W>
<W id="23" msd="PRO&3a;rela" tag="PRO&3a;rela" in="" out="">che</W>
<W id="24" msd="DET&3a;def" tag="DET&3a;def" in="" out="">gli</W>
<W id="25" msd="NOM" tag="NOM" in="" out="2:ref">emendamenti</W>
<W id="26" msd="ADJ" tag="ADJ" in="" out="">ulteriori</W>
<W id="27" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-2:ref" out="">che</W>
<W id="28" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">vengono</W>
<W id="29" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">presentati</W>
<W id="30" msd="VER&3a;cpre" tag="VER&3a;cpre" in="" out="">tengano</W>
<W id="31" msd="NOM" tag="NOM" in="" out="">conto</W>
<W id="32" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="33" msd="PRO&3a;indef" tag="PRO&3a;indef" in="" out="">alcune</W>
<W id="34" msd="NOM" tag="NOM" in="" out="1:ref">incongruenze</W>
<W id="35" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="36" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="37" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">sono</W>
<W id="38" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">state</W>
<W id="39" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">accettate</W>
<W id="40" msd="PRE&3a;det" tag="PRE&3a;det" in="0:assoc-frame" out="0:assoc-frame">dal</W>
<W id="41" msd="NOM" tag="NOM" in="" out="">Consiglio</W>
<W id="42" msd="PON" tag="PON" in="" out="">:</W>
<W id="43" msd="PRO&3a;pers" tag="PRO&3a;pers" in="" out="">mi</W>
<W id="44" msd="VER&3a;pres" tag="VER&3a;pres" in="3:coref" out="">riferisco</W>
<W id="45" msd="ADV" tag="ADV" in="" out="">naturalmente</W>
<W id="46" msd="ADV" tag="ADV" in="" out="">anch'</W>
<W id="47" msd="PRO&3a;pers" tag="PRO&3a;pers" in="" out="-3:coref|140:coref">io</W>
<W id="48" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="47:coref-iden">alla</W>
<W id="49" msd="NOM" tag="NOM" in="" out="5:ref">flotta</W>
<W id="50" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dell'</W>
<W id="51" msd="NPR" tag="NPR" in="" out="">Arabia</W>
<W id="52" msd="ADJ" tag="ADJ" in="" out="">Saudita</W>
<W id="53" msd="PON" tag="PON" in="" out="">,</W>
<W id="54" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-5:ref" out="">che</W>
<W id="55" msd="ADV" tag="ADV" in="" out="">sostanzialmente</W>
<W id="56" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="12:coref-res">viene</W>
<W id="57" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">classificata</W>
<W id="58" msd="PRE" tag="PRE" in="" out="">come</W>
<W id="59" msd="NOM" tag="NOM" in="" out="">flotta</W>
<W id="60" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="61" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">un</W>
<W id="62" msd="NOM" tag="NOM" in="" out="">paese</W>
<W id="63" msd="PRE" tag="PRE" in="" out="">in</W>
<W id="64" msd="NOM" tag="NOM" in="" out="">via</W>
<W id="65" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="66" msd="NOM" tag="NOM" in="" out="">sviluppo</W>
<W id="67" msd="PON" tag="PON" in="" out="">,</W>
<W id="68" msd="DET&3a;def" tag="DET&3a;def" in="-12:coref-res" out="">la</W>
<W id="69" msd="ADJ" tag="ADJ" in="" out="">qual</W>
<W id="70" msd="NOM" tag="NOM" in="" out="">cosa</W>
<W id="71" msd="PRO&3a;refl" tag="PRO&3a;refl" in="0:assoc-frame" out="0:assoc-frame">ci</W>
<W id="72" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="5:coref-res">pare</W>
<W id="73" msd="ADV" tag="ADV" in="" out="">molto</W>
<W id="74" msd="ADJ" tag="ADJ" in="" out="">anacronistica</W>
<W id="75" msd="SENT" tag="SENT" in="" out="">.</W>
<W id="76" msd="PRE" tag="PRE" in="" out="">In</W>
<W id="77" msd="PRO&3a;demo" tag="PRO&3a;demo" in="-5:coref-res" out="">questo</W>
<W id="78" msd="NOM" tag="NOM" in="" out="">senso</W>
<W id="79" msd="PRO&3a;refl" tag="PRO&3a;refl" in="" out="">si</W>
<W id="80" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">propone</W>
<W id="81" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="64:coref-var">un</W>
<W id="82" msd="NOM" tag="NOM" in="" out="1:ref|9:ref">emendamento</W>
<W id="83" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="84" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">fa</W>
<W id="85" msd="NOM" tag="NOM" in="" out="">riferimento</W>
<W id="86" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">alla</W>
<W id="87" msd="NOM" tag="NOM" in="" out="">classificazione</W>
<W id="88" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dell'</W>
<W id="89" msd="NOM" tag="NOM" in="" out="">OCSE</W>
<W id="90" msd="CON" tag="CON" in="" out="">e</W>
<W id="91" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-9:ref" out="">che</W>
<W id="92" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="38:coref-res">dovrebbe</W>
<W id="93" msd="ADV" tag="ADV" in="" out="">quindi</W>
<W id="94" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">escludere</W>
<W id="95" msd="DET&3a;def" tag="DET&3a;def" in="-47:coref-iden" out="">la</W>
<W id="96" msd="NOM" tag="NOM" in="" out="">flotta</W>
<W id="97" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dell'</W>
<W id="98" msd="NPR" tag="NPR" in="" out="">Arabia</W>
<W id="99" msd="NOM" tag="NOM" in="" out="">Saudita</W>
<W id="100" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dai</W>
<W id="101" msd="NOM" tag="NOM" in="" out="1:ref">benefici</W>
<W id="102" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="103" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">derivano</W>
<W id="104" msd="PON" tag="PON" in="" out="">,</W>
<W id="105" msd="ADV" tag="ADV" in="" out="">appunto</W>
<W id="106" msd="PON" tag="PON" in="" out="">,</W>
<W id="107" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dal</W>
<W id="108" msd="NOM" tag="NOM" in="" out="1:ref">provvedimento</W>
<W id="109" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="110" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">riguarda</W>
<W id="111" msd="DET&3a;def" tag="DET&3a;def" in="" out="">gli</W>
<W id="112" msd="NOM" tag="NOM" in="" out="3:ref|8:ref">aerei</W>
<W id="113" msd="VER&3a;ppre" tag="VER&3a;ppre" in="" out="">inquinanti</W>
<W id="114" msd="PON" tag="PON" in="" out="">,</W>
<W id="115" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-3:ref" out="">che</W>
<W id="116" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="117" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">fanno</W>
<W id="118" msd="NOM" tag="NOM" in="" out="">rumore</W>
<W id="119" msd="CON" tag="CON" in="" out="">e</W>
<W id="120" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-8:ref" out="">che</W>
<W id="121" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">hanno</W>
<W id="122" msd="NOM" tag="NOM" in="" out="">più</W>
<W id="123" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="124" msd="NUM" tag="NUM" in="" out="">25</W>
<W id="125" msd="NOM" tag="NOM" in="" out="">anni</W>
<W id="126" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="127" msd="NOM" tag="NOM" in="" out="">età</W>
<W id="128" msd="SENT" tag="SENT" in="" out="">.</W>
<W id="129" msd="PRE" tag="PRE" in="" out="">Da</W>
<W id="130" msd="PRO&3a;demo" tag="PRO&3a;demo" in="-38:coref-res" out="">questo</W>
<W id="131" msd="NOM" tag="NOM" in="" out="">punto</W>
<W id="132" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="133" msd="NOM" tag="NOM" in="" out="">vista</W>
<W id="134" msd="PON" tag="PON" in="" out="">,</W>
<W id="135" msd="ADV" tag="ADV" in="" out="">pertanto</W>
<W id="136" msd="PON" tag="PON" in="" out="">,</W>
<W id="137" msd="PRO&3a;pers" tag="PRO&3a;pers" in="" out="">si</W>
<W id="138" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="">verrebbe</W>
<W id="139" msd="PRE" tag="PRE" in="" out="">a</W>
<W id="140" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">ristabilire</W>
<W id="141" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">una</W>
<W id="142" msd="NOM" tag="NOM" in="" out="">condizione</W>
<W id="143" msd="ADJ" tag="ADJ" in="" out="">positiva</W>
<W id="144" msd="PON" tag="PON" in="" out="">:</W>
<W id="145" msd="DET&3a;def" tag="DET&3a;def" in="-64:coref-var" out="4:assoc-formal">la</W>
<W id="146" msd="NOM" tag="NOM" in="" out="">proposta</W>
<W id="147" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="">riguarderebbe</W>
<W id="148" msd="PON" tag="PON" in="" out="">,</W>
<W id="149" msd="PRE&3a;det" tag="PRE&3a;det" in="-4:assoc-formal" out="">nella</W>
<W id="150" msd="NOM" tag="NOM" in="" out="">sostanza</W>
<W id="151" msd="PON" tag="PON" in="" out="">,</W>
<W id="152" msd="PRO&3a;demo" tag="PRO&3a;demo" in="" out="">quei</W>
<W id="153" msd="NOM" tag="NOM" in="" out="1:ref">paesi</W>
<W id="154" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="155" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">sono</W>
<W id="156" msd="ADV" tag="ADV" in="" out="">effettivamente</W>
<W id="157" msd="PRE" tag="PRE" in="" out="">in</W>
<W id="158" msd="NOM" tag="NOM" in="" out="">difficoltà</W>
<W id="159" msd="CON" tag="CON" in="" out="">e</W>
<W id="160" msd="PRO&3a;pers" tag="PRO&3a;pers" in="" out="">si</W>
<W id="161" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="">garantirebbero</W>
<W id="162" msd="DET&3a;def" tag="DET&3a;def" in="" out="">la</W>
<W id="163" msd="NOM" tag="NOM" in="" out="">sicurezza</W>
<W id="164" msd="CON" tag="CON" in="" out="">e</W>
<W id="165" msd="PON" tag="PON" in="" out="">,</W>
<W id="166" msd="ADV" tag="ADV" in="" out="">naturalmente</W>
<W id="167" msd="PON" tag="PON" in="" out="">,</W>
<W id="168" msd="ADV" tag="ADV" in="" out="">anche</W>
<W id="169" msd="DET&3a;def" tag="DET&3a;def" in="" out="">la</W>
<W id="170" msd="NOM" tag="NOM" in="" out="">qualità</W>
<W id="171" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">della</W>
<W id="172" msd="NOM" tag="NOM" in="" out="">vita</W>
<W id="173" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">dei</W>
<W id="174" msd="NOM" tag="NOM" in="" out="1:ref">cittadini</W>
<W id="175" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="176" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">abitano</W>
<W id="177" msd="PRE" tag="PRE" in="" out="">in</W>
<W id="178" msd="NOM" tag="NOM" in="" out="">prossimità</W>
<W id="179" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">degli</W>
<W id="180" msd="NOM" tag="NOM" in="" out="">aeroporti</W>
<W id="181" msd="SENT" tag="SENT" in="" out="">.</W>
<W id="182" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">Un</W>
<W id="183" msd="ADJ" tag="ADJ" in="" out="">altro</W>
<W id="184" msd="NOM" tag="NOM" in="" out="2:ref|7:ref|17:coref-ell">punto</W>
<W id="185" msd="PON" tag="PON" in="" out="">,</W>
<W id="186" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-2:ref" out="">che</W>
<W id="187" msd="PRO&3a;pers" tag="PRO&3a;pers" in="-140:coref" out="18:coref">mi</W>
<W id="188" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="">pare</W>
<W id="189" msd="ADJ" tag="ADJ" in="" out="">importante</W>
<W id="190" msd="CON" tag="CON" in="" out="">ma</W>
<W id="191" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-7:ref" out="">che</W>
<W id="192" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="193" msd="NOM" tag="NOM" in="" out="">è</W>
<W id="194" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">stato</W>
<W id="195" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">sollevato</W>
<W id="196" msd="PON" tag="PON" in="" out="">,</W>
<W id="197" msd="NOM" tag="NOM" in="" out="">è</W>
<W id="198" msd="PON" tag="PON" in="" out="">,</W>
<W id="199" msd="ADV" tag="ADV" in="" out="">naturalmente</W>
<W id="200" msd="PON" tag="PON" in="" out="">,</W>
<W id="201" msd="PRO&3a;demo" tag="PRO&3a;demo" in="-17:coref-ell" out="">quello</W>
<W id="202" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">della</W>
<W id="203" msd="NOM" tag="NOM" in="" out="">concorrenza</W>
<W id="204" msd="SENT" tag="SENT" in="" out="">.</W>
<W id="205" msd="PRO&3a;pers" tag="PRO&3a;pers" in="-18:coref" out="">Io</W>
<W id="206" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="">vorrei</W>
<W id="207" msd="PRO&3a;rela" tag="PRO&3a;rela" in="" out="">che</W>
<W id="208" msd="VER&3a;cimp" tag="VER&3a;cimp" in="" out="">venisse</W>
<W id="209" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">evidenziato</W>
<W id="210" msd="PON" tag="PON" in="" out="">-</W>
<W id="211" msd="CON" tag="CON" in="" out="">e</W>
<W id="212" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="213" msd="ADV" tag="ADV" in="" out="">solo</W>
<W id="214" msd="PRE&3a;det" tag="PRE&3a;det" in="0:assoc-frame" out="0:assoc-frame">dalla</W>
<W id="215" msd="NOM" tag="NOM" in="" out="">Commissione</W>
<W id="216" msd="PON" tag="PON" in="" out="">-</W>
<W id="217" msd="PRO&3a;demo" tag="PRO&3a;demo" in="" out="">questo</W>
<W id="218" msd="NOM" tag="NOM" in="" out="">aspetto</W>
<W id="219" msd="PON" tag="PON" in="" out="">,</W>
<W id="220" msd="NOM" tag="NOM" in="" out="">cioè</W>
<W id="221" msd="PRO&3a;rela" tag="PRO&3a;rela" in="" out="">che</W>
<W id="222" msd="DET&3a;def" tag="DET&3a;def" in="" out="">il</W>
<W id="223" msd="NOM" tag="NOM" in="" out="">diritto</W>
<W id="224" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="225" msd="NOM" tag="NOM" in="" out="">atterraggio</W>
<W id="226" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="227" msd="VER&3a;cpre" tag="VER&3a;cpre" in="" out="">debba</W>
<W id="228" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">essere</W>
<W id="229" msd="NOM" tag="NOM" in="" out="">oggetto</W>
<W id="230" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="231" msd="NOM" tag="NOM" in="" out="">cessione</W>
<W id="232" msd="NOM" tag="NOM" in="" out="">perché</W>
<W id="233" msd="PON" tag="PON" in="" out="">,</W>
<W id="234" msd="ADV" tag="ADV" in="" out="">naturalmente</W>
<W id="235" msd="PON" tag="PON" in="" out="">,</W>
<W id="236" msd="DET&3a;def" tag="DET&3a;def" in="" out="">la</W>
<W id="237" msd="NOM" tag="NOM" in="" out="">possibilità</W>
<W id="238" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="239" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">avere</W>
<W id="240" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="23:coref-iden">uno</W>
<W id="241" msd="NOM" tag="NOM" in="" out="">slot</W>
<W id="242" msd="PRE" tag="PRE" in="" out="">con</W>
<W id="243" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">un</W>
<W id="244" msd="NOM" tag="NOM" in="" out="">aereo</W>
<W id="245" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">autorizzato</W>
<W id="246" msd="NOM" tag="NOM" in="" out="">è</W>
<W id="247" msd="ADV" tag="ADV" in="" out="">molto</W>
<W id="248" msd="ADJ" tag="ADJ" in="" out="">importante</W>
<W id="249" msd="ADV" tag="ADV" in="" out="">oggi</W>
<W id="250" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">nella</W>
<W id="251" msd="NOM" tag="NOM" in="" out="">concorrenza</W>
<W id="252" msd="PRE" tag="PRE" in="" out="">tra</W>
<W id="253" msd="DET&3a;def" tag="DET&3a;def" in="" out="">i</W>
<W id="254" msd="ADJ" tag="ADJ" in="" out="">vari</W>
<W id="255" msd="NOM" tag="NOM" in="" out="">paesi</W>
<W id="256" msd="PON" tag="PON" in="" out="">:</W>
<W id="257" msd="PRO&3a;demo" tag="PRO&3a;demo" in="" out="">vi</W>
<W id="258" msd="NOM" tag="NOM" in="" out="46:coref-res">può</W>
<W id="259" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">essere</W>
<W id="260" msd="DET&3a;def" tag="DET&3a;def" in="" out="">il</W>
<W id="261" msd="NOM" tag="NOM" in="" out="">rischio</W>
<W id="262" msd="PRO&3a;rela" tag="PRO&3a;rela" in="" out="">che</W>
<W id="263" msd="PRO&3a;demo" tag="PRO&3a;demo" in="-23:coref-iden" out="">questo</W>
<W id="264" msd="NOM" tag="NOM" in="" out="">slot</W>
<W id="265" msd="VER&3a;cpre" tag="VER&3a;cpre" in="" out="">venga</W>
<W id="266" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">ceduto</W>
<W id="267" msd="PRE" tag="PRE" in="" out="">a</W>
<W id="268" msd="NOM" tag="NOM" in="" out="">paesi</W>
<W id="269" msd="ADJ" tag="ADJ" in="" out="">terzi</W>
<W id="270" msd="CON" tag="CON" in="" out="">e</W>
<W id="271" msd="PON" tag="PON" in="" out="">,</W>
<W id="272" msd="ADV" tag="ADV" in="" out="">quindi</W>
<W id="273" msd="PON" tag="PON" in="" out="">,</W>
<W id="274" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="275" msd="NOM" tag="NOM" in="" out="">fatto</W>
<W id="276" msd="PON" tag="PON" in="" out="">,</W>
<W id="277" msd="PRO&3a;demo" tag="PRO&3a;demo" in="" out="">vi</W>
<W id="278" msd="NOM" tag="NOM" in="" out="">è</W>
<W id="279" msd="DET&3a;def" tag="DET&3a;def" in="" out="">il</W>
<W id="280" msd="NOM" tag="NOM" in="" out="">rischio</W>
<W id="281" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="282" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">una</W>
<W id="283" msd="ADJ" tag="ADJ" in="" out="">vera</W>
<W id="284" msd="CON" tag="CON" in="" out="">e</W>
<W id="285" msd="ADJ" tag="ADJ" in="" out="">propria</W>
<W id="286" msd="NOM" tag="NOM" in="" out="">commercializzazione</W>
<W id="287" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">degli</W>
<W id="288" msd="NOM" tag="NOM" in="" out="">slot</W>
<W id="289" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">fatta</W>
<W id="290" msd="PRE" tag="PRE" in="" out="">su</W>
<W id="291" msd="NOM" tag="NOM" in="" out="1:ref">aerei</W>
<W id="292" msd="PRO&3a;rela" tag="PRO&3a;rela" in="-1:ref" out="">che</W>
<W id="293" msd="VER&3a;pres" tag="VER&3a;pres" in="" out="4:coref">sono</W>
<W id="294" msd="ADV" tag="ADV" in="" out="">sostanzialmente</W>
<W id="295" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">autorizzati</W>
<W id="296" msd="CON" tag="CON" in="" out="">e</W>
<W id="297" msd="VER&3a;pres" tag="VER&3a;pres" in="-4:coref" out="">sono</W>
<W id="298" msd="ADJ" tag="ADJ" in="" out="">inquinanti</W>
<W id="299" msd="CON" tag="CON" in="" out="">ed</W>
<W id="300" msd="ADV" tag="ADV" in="" out="">anche</W>
<W id="301" msd="ADJ" tag="ADJ" in="" out="">rumorosi</W>
<W id="302" msd="SENT" tag="SENT" in="" out="">.</W>
<W id="303" msd="PRO&3a;indef" tag="PRO&3a;indef" in="" out="">Tutto</W>
<W id="304" msd="NOM" tag="NOM" in="-46:coref-res" out="">ciò</W>
<W id="305" msd="VER&3a;cond" tag="VER&3a;cond" in="" out="">potrebbe</W>
<W id="306" msd="PRE&3a;det" tag="PRE&3a;det" in="" out="">alla</W>
<W id="307" msd="NOM" tag="NOM" in="" out="">fine</W>
<W id="308" msd="VER&3a;infi" tag="VER&3a;infi" in="" out="">aprire</W>
<W id="309" msd="PRE" tag="PRE" in="" out="">ad</W>
<W id="310" msd="DET&3a;indef" tag="DET&3a;indef" in="" out="">un</W>
<W id="311" msd="NOM" tag="NOM" in="" out="">meccanismo</W>
<W id="312" msd="PRE" tag="PRE" in="" out="">di</W>
<W id="313" msd="NOM" tag="NOM" in="" out="">mercato</W>
<W id="314" msd="ADV" tag="ADV" in="" out="">non</W>
<W id="315" msd="ADV" tag="ADV" in="" out="">molto</W>
<W id="316" msd="VER&3a;pper" tag="VER&3a;pper" in="" out="">corretto</W>
<W id="317" msd="SENT" tag="SENT" in="" out="">.</W>
</s>
