<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">La</W>
<W lemma="lettera" msd="NC" tag="NOM" in="" out="">lettera</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="autorizzare" msd="VAP" tag="VER&3a;pper" in="" out="">autorizzato</W>
<W lemma="ufficialmente" msd="RG" tag="ADV" in="" out="">ufficialmente</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Crescent</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="discutere" msd="VAF" tag="VER&3a;infi" in="" out="">discutere</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="negoziare" msd="VAF" tag="VER&3a;infi" in="" out="">negoziare</W>
<W lemma="possibilità" msd="NC" tag="NOM" in="" out="">possibilità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="acquisto" msd="NC" tag="NOM" in="" out="">acquisti</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">all'</W>
<W lemma="interno" msd="NC" tag="NOM" in="" out="">interno</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">joint-venture</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="concordare" msd="VAF" tag="VER&3a;infi" in="" out="">concordare</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">?le</W>
<W lemma="condizione" msd="NC" tag="NOM" in="" out="">condizioni</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="garantire" msd="VAF" tag="VER&3a;infi" in="" out="">garantire</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="lungo" msd="AN" tag="ADJ" in="" out="">lunga</W>
<W lemma="scadenza" msd="NC" tag="NOM" in="" out="">scadenza</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="petrolio" msd="NC" tag="NOM" in="" out="">petrolio</W>
<W lemma="grezzo" msd="AN" tag="ADJ" in="" out="">grezzo</W>
<W lemma="iracheno" msd="AN" tag="ADJ" in="" out="">iracheno</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Hamid</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Jafar</W>
<W lemma="era" msd="NC" tag="NOM" in="" out="">era</W>
<W lemma="ansioso" msd="AN" tag="ADJ" in="" out="">ansioso</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="mostrare" msd="VAF" tag="VER&3a;infi" in="" out="">mostrare</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">agli</W>
<W lemma="interlocutore" msd="NC" tag="NOM" in="" out="">interlocutori</W>
<W lemma="iracheno" msd="AN" tag="ADJ" in="" out="">iracheni</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="suo" msd="PO" tag="PRO&3a;poss" in="" out="">suo</W>
<W lemma="apprezzamento" msd="NC" tag="NOM" in="" out="">apprezzamento</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">l'</W>
<W lemma="accordo" msd="NC" tag="NOM" in="" out="">accordo</W>
<W lemma="&3a;" msd="XP" tag="PON" in="" out="">:</W>
<W lemma="poco" msd="RG" tag="ADV" in="" out="">poco</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">prima</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">dell'</W>
<W lemma="invasione" msd="NC" tag="NOM" in="" out="">invasione</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="ordinare" msd="VAP" tag="VER&3a;pper" in="" out="">ordinato</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="" out="">una</W>
<W lemma="pistola" msd="NC" tag="NOM" in="" out="">pistola</W>
<W lemma="svizzero" msd="AN" tag="ADJ" in="" out="">svizzera</W>
<W lemma="intarsiare" msd="VAP" tag="VER&3a;pper" in="" out="">intarsiata</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="oro" msd="NC" tag="NOM" in="" out="">oro</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="valore" msd="NC" tag="NOM" in="" out="">valore</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">7.000</W>
<W lemma="sterlina" msd="NC" tag="NOM" in="" out="">sterline</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="Londra" msd="NP" tag="NPR" in="" out="">Londra</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Asprey'</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">s</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="gioielliere" msd="NC" tag="NOM" in="" out="">gioielliere</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">della</W>
<W lemma="regina" msd="NC" tag="NOM" in="" out="">regina</W>
<W lemma="britannico" msd="AN" tag="ADJ" in="" out="">britannica</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="lo" msd="PP" tag="PRO&3a;pers" in="" out="">Lo</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="fare" msd="VAP" tag="VER&3a;pper" in="" out="">fatto</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="mostrare" msd="VAF" tag="VER&3a;infi" in="" out="">mostrare</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="pistola" msd="NC" tag="NOM" in="" out="">pistola</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">al</W>
<W lemma="cugino" msd="NC" tag="NOM" in="" out="">cugino</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="genero" msd="NC" tag="NOM" in="" out="">genero</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Saddam</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Husseins</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Hussein</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kamal</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">al</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Majid</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="tempo" msd="NC" tag="NOM" in="" out="">tempo</W>
<W lemma="ministro" msd="NC" tag="NOM" in="" out="">ministro</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">dell'</W>
<W lemma="industria" msd="NC" tag="NOM" in="" out="">industria</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="Iraq" msd="NP" tag="NPR" in="" out="">Iraq</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="quando" msd="PT" tag="PRO&3a;inter" in="" out="">Quando</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="" out="">sono</W>
<W lemma="cominciare" msd="VAP" tag="VER&3a;pper" in="" out="">cominciate</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">le</W>
<W lemma="ostilità" msd="NC" tag="NOM" in="" out="">ostilità</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="comunque" msd="RG" tag="ADV" in="" out="">comunque</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">l'</W>
<W lemma="arma" msd="NC" tag="NOM" in="" out="">arma</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="essere" msd="VADA" tag="VER&3a;impf" in="" out="">era</W>
<W lemma="ancora" msd="RG" tag="ADV" in="" out="">ancora</W>
<W lemma="uscire" msd="VAP" tag="VER&3a;pper" in="" out="">uscita</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="" out="">dall'</W>
<W lemma="aeroporto" msd="NC" tag="NOM" in="" out="">aeroporto</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Bagdad</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="oltre" msd="RG" tag="ADV" in="" out="">Oltre</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Petrofina</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Crescent</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="inoltre" msd="RG" tag="ADV" in="" out="">inoltre</W>
<W lemma="valutare" msd="VAP" tag="VER&3a;pper" in="" out="">valutato</W>
<W lemma="potenziale" msd="AN" tag="ADJ" in="" out="">potenziali</W>
<W lemma="altri&7c;altro" msd="PI" tag="PRO&3a;indef" in="" out="">altri</W>
<W lemma="obiettivo" msd="NC" tag="NOM" in="" out="">obiettivi</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">joint-venture</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="sia" msd="CS" tag="CON" in="" out="">sia</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="America" msd="NP" tag="NPR" in="" out="">America</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="nord" msd="NC" tag="NOM" in="" out="">nord</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="Europa" msd="NP" tag="NPR" in="" out="">Europa</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Hamid</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Jafar</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="@card@" msd="XP" tag="PON" in="" out="">45</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="studiare" msd="VAP" tag="VER&3a;pper" in="" out="">studiato</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="Londra" msd="NP" tag="NPR" in="" out="">Londra</W>
<W lemma="ed" msd="CS" tag="CON" in="" out="">ed</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="">è</W>
<W lemma="figlio" msd="NC" tag="NOM" in="" out="">figlio</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="ex" msd="AN" tag="ADJ" in="" out="">ex</W>
<W lemma="ministro" msd="NC" tag="NOM" in="" out="">ministro</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="governo" msd="NC" tag="NOM" in="" out="">governo</W>
<W lemma="iracheno" msd="AN" tag="ADJ" in="" out="">iracheno</W>
<W lemma=";" msd="XP" tag="PON" in="" out="">;</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="abitare" msd="VAP" tag="VER&3a;pper" in="" out="">abitato</W>
<W lemma="molto" msd="AN" tag="ADJ" in="" out="">molti</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Sharjeh</W>
<W lemma="ed" msd="CS" tag="CON" in="" out="">ed</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="ottenere" msd="VAP" tag="VER&3a;pper" in="" out="">ottenuto</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="passaporto" msd="NC" tag="NOM" in="" out="">passaporto</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">degli</W>
<W lemma="emirato" msd="NC" tag="NOM" in="" out="">Emirati</W>
<W lemma="arabo" msd="AN" tag="ADJ" in="" out="">Arabi</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="" out="">nel</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1986</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="gli" msd="PP" tag="PRO&3a;pers" in="" out="">gli</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="dare" msd="VAP" tag="VER&3a;pper" in="" out="">dato</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="legame" msd="NC" tag="NOM" in="" out="">legame</W>
<W lemma="nazionale" msd="AN" tag="ADJ" in="" out="">nazionale</W>
<W lemma="sia" msd="CS" tag="CON" in="" out="">sia</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">all'</W>
<W lemma="Iraq" msd="NP" tag="NPR" in="" out="">Iraq</W>
<W lemma="che" msd="CS" tag="CON" in="" out="">che</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">agli</W>
<W lemma="emirato" msd="NC" tag="NOM" in="" out="">Emirati</W>
<W lemma="arabo" msd="AN" tag="ADJ" in="" out="">Arabi</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
