<W lemma="settimana" msd="NC" tag="NOM" in="15:xtop" out="1:attrr|13:pnct">Settimane</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">con</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="programma" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|2:attrr">programma</W>
<W lemma="alimentare" msd="AN" tag="ADJ" in="-1:attrr" out="">alimentare</W>
<W lemma="a" msd="SP" tag="PRE" in="-2:attrr" out="1:nobj">a</W>
<W lemma="base" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">base</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="pemmican" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">pemmican</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">in</W>
<W lemma="centinaio" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">centinaia</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="versione" msd="NC" tag="NOM" in="-1:nobj" out="">versioni</W>
<W lemma="," msd="XP" tag="PON" in="-13:pnct" out="">,</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="1:subj" out="">questo</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-15:xtop|-1:subj|1:preds|4:pnct">è</W>
<W lemma="quanto" msd="RG" tag="ADV" in="-1:preds" out="2:vobj">quanto</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="1:subj" out="">si</W>
<W lemma="prevedere" msd="VADR" tag="VER:pres" in="-2:vobj" out="-1:subj">prevede</W>
<W lemma="." msd="XP" tag="SENT" in="-4:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj|3:[subj]" out="1:nobj">Il</W>
<W lemma="pemmican" msd="NC" tag="NOM" in="-1:nobj" out="">pemmican</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-2:subj|1:vobj|35:pnct">è</W>
<W lemma="costituire" msd="VAP" tag="VER:pper" in="-1:vobj" out="-3:[subj]|1:pobj">costituito</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">da</W>
<W lemma="tavoletta" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|24:relr|23:ref">tavolette</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="lipide" msd="NC" tag="NOM" in="-1:nobj|6:[subj]" out="2:conj|4:conj|1:pnct|5:pnct|6:appa">lipidi</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="vitamina" msd="NC" tag="NOM" in="-2:conj" out="">vitamine</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="minerale" msd="NC" tag="NOM" in="-4:conj" out="-1:coord">minerali</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="indicare" msd="VAP" tag="VER:pper" in="-6:appa" out="2:ben|-6:[subj]|14:pnct">indicati</W>
<W lemma="sia" msd="CS" tag="CON" in="4:correl" out="">sia</W>
<W lemma="per" msd="SP" tag="PRE" in="-2:ben" out="4:conj|1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">gli</W>
<W lemma="uomo" msd="NC" tag="NOM" in="-1:nobj" out="">uomini</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:coord" out="-4:correl">che</W>
<W lemma="per" msd="SP" tag="PRE" in="-4:conj" out="1:nobj|-1:coord">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">i</W>
<W lemma="cane" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">cani</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">in</W>
<W lemma="condizione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">condizioni</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="freddo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">freddo</W>
<W lemma="polare" msd="AN" tag="ADJ" in="-1:attrr" out="">polare</W>
<W lemma="," msd="XP" tag="PON" in="-14:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:subj|-23:ref" out="">che</W>
<W lemma="assumere" msd="VADR" tag="VER:pres" in="-24:relr" out="-1:subj|2:dobj|1:degr">assumono</W>
<W lemma="esattamente" msd="RG" tag="ADV" in="-1:degr" out="">esattamente</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:dobj" out="1:nobj">il</W>
<W lemma="sapore" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">sapore</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">delle</W>
<W lemma="sostanza" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|2:attrr">sostanze</W>
<W lemma="aromatico" msd="AN" tag="ADJ" in="-1:attrr" out="">aromatiche</W>
<W lemma="aggiunto" msd="AN" tag="ADJ" in="-2:attrr" out="">aggiunte</W>
<W lemma="." msd="XP" tag="SENT" in="-35:pnct" out="">.</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">Con</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">queste</W>
<W lemma="premessa" msd="NC" tag="NOM" in="" out="">premesse</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="desto" msd="AN" tag="ADJ" in="" out="">desta</W>
<W lemma="meraviglia" msd="NC" tag="NOM" in="" out="">meraviglia</W>
<W lemma="che" msd="CS" tag="CON" in="" out="">che</W>
<W lemma="anche" msd="RG" tag="ADV" in="" out="">anche</W>
<W lemma="quattro" msd="AN" tag="ADJ" in="" out="">quattro</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">alleatissimi</W>
<W lemma="sportivo" msd="AN" tag="ADJ" in="" out="">sportivi</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:cpre" in="" out="">abbiano</W>
<W lemma="impiegare" msd="VAP" tag="VER:pper" in="" out="">impiegato</W>
<W lemma="giovedì" msd="NC" tag="NOM" in="" out="">giovedì</W>
<W lemma="sera" msd="NC" tag="NOM" in="" out="">sera</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="">ad</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Akureyri-</W>
<W lemma="sera" msd="NC" tag="NOM" in="" out="">sera</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="credere" msd="VADA" tag="VER:impf" in="" out="">credevano</W>
<W lemma="essere" msd="VADA" tag="VER:cimp" in="" out="">fosse</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="ultimo" msd="NC" tag="NOM" in="" out="">ultima</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="terra" msd="NC" tag="NOM" in="" out="">terre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">civili-</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="assicurare" msd="VAF" tag="VER:infi" in="" out="">assicurarsi</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="migliore" msd="AN" tag="ADJ" in="" out="">migliore</W>
<W lemma="cena" msd="NC" tag="NOM" in="" out="">cena</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="città" msd="NC" tag="NOM" in="" out="">città</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="innaffiare" msd="VAP" tag="VER:pper" in="" out="">innaffiata</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="vino" msd="NC" tag="NOM" in="" out="">vino</W>
<W lemma="rosso" msd="AN" tag="ADJ" in="" out="">rosso</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">Per</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="occasione" msd="NC" tag="NOM" in="" out="">occasione</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="indossare" msd="VAP" tag="VER:pper" in="" out="">indossati</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">gli</W>
<W lemma="abito" msd="NC" tag="NOM" in="" out="">abiti</W>
<W lemma="elegante" msd="AN" tag="ADJ" in="" out="">eleganti</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="c'" msd="PD" tag="PRO:demo" in="" out="">c'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="chi" msd="PT" tag="PRO:rela" in="" out="">chi</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="mettere" msd="VAP" tag="VER:pper" in="" out="">messo</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="fard" msd="NC" tag="NOM" in="" out="">fard</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulle</W>
<W lemma="guancia" msd="NC" tag="NOM" in="" out="">guance</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="poi" msd="RG" tag="ADV" in="" out="">Poi</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stato</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="momento" msd="NC" tag="NOM" in="" out="">momento</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="tagliare" msd="VAF" tag="VER:infi" in="" out="">tagliarsi</W>
<W lemma="corto" msd="AN" tag="ADJ" in="" out="">corte</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="unghia" msd="NC" tag="NOM" in="" out="">unghie</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="visto" msd="CS" tag="CON" in="" out="">visto</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="ora" msd="RG" tag="ADV" in="" out="">ora</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="" out="">quello</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="conta" msd="NC" tag="NOM" in="" out="">conta</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="muscolo" msd="NC" tag="NOM" in="" out="">muscoli</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Iver</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Høj</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Foto</W>
<W lemma=":" msd="XP" tag="PON" in="" out="">:</W>
<W lemma="Jan" msd="NP" tag="NPR" in="" out="">Jan</W>
<W lemma="Jørgensen" msd="NP" tag="NPR" in="" out="">Jørgensen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Durante</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="attesa" msd="NC" tag="NOM" in="" out="">attesa</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Karo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Thomsen</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="avere" msd="VAP" tag="VER:pper" in="" out="">avuto</W>
<W lemma="ampio" msd="AN" tag="ADJ" in="" out="">ampia</W>
<W lemma="possibilità" msd="NC" tag="NOM" in="" out="">possibilità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="imparare" msd="VAF" tag="VER:infi" in="" out="">imparare</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="conoscere" msd="VAF" tag="VER:infi" in="" out="">conoscere</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="sestante" msd="NC" tag="NOM" in="" out="">sestante</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="dopo" msd="SP" tag="PRE" in="" out="">Dopo</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="settimana" msd="NC" tag="NOM" in="" out="">settimana</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="campo" msd="NC" tag="NOM" in="" out="">campo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="addestramento" msd="NC" tag="NOM" in="" out="">addestramento</W>
<W lemma="-" msd="XP" tag="PON" in="" out="">-</W>
<W lemma="comunque" msd="RG" tag="ADV" in="" out="">comunque</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="tenda" msd="NC" tag="NOM" in="" out="">tenda</W>
<W lemma="-" msd="XP" tag="PON" in="" out="">-</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="">ad</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Akureyri</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="Islanda" msd="NP" tag="NPR" in="" out="">Islanda</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Mie</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Graversen</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Olga</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Osetrova</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Karo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Thomsen</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="Susan" msd="NP" tag="NPR" in="" out="">Susan</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Frankenstein</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">hanno</W>
<W lemma="iniziare" msd="VAP" tag="VER:pper" in="" out="">iniziato</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="traversata" msd="NC" tag="NOM" in="" out="">traversata</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="Groenlandia" msd="NP" tag="NPR" in="" out="">Groenlandia</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
