<p>
<s>
<W lemma="non" msd="RG" tag="ADV" in="" out="">Non</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="49:+CONJ/(e)">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="" out="">stata</W>
<W lemma="commentare" msd="VAP" tag="VER&3a;pper" in="" out="">commentata</W>
<W lemma="nemmeno" msd="RG" tag="ADV" in="" out="">nemmeno</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="critica" msd="NC" tag="NOM" in="" out="">critica</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="membro" msd="NC" tag="NOM" in="" out="">membro</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Folketing</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Arne</W>
<W lemma="Melchior" msd="NP" tag="NPR" in="" out="">Melchior</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="presentare" msd="VAP" tag="VER&3a;pper" in="" out="">presentato</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">lo</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="dato" msd="NC" tag="NOM" in="" out="">dato</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="cioè" msd="RG" tag="ADV" in="" out="">cioè</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="" out="">nella</W>
<W lemma="direzione" msd="NC" tag="NOM" in="" out="">direzione</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kræftens</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bekæmpelse</W>
<W lemma="(" msd="XP" tag="PON" in="" out="">(</W>
<W lemma="&lt;unknown&gt;" msd="VAP" tag="VER&3a;pper" in="" out="">Lotta</W>
<W lemma="contro" msd="SP" tag="PRE" in="" out="">contro</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">i</W>
<W lemma="tumore" msd="NC" tag="NOM" in="" out="">tumori</W>
<W lemma=")" msd="XP" tag="PON" in="" out="">)</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="sedere" msd="VADR" tag="VER&3a;pres" in="" out="">siede</W>
<W lemma="neanche" msd="RG" tag="ADV" in="" out="">neanche</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="ricercatore" msd="NC" tag="NOM" in="" out="">ricercatore</W>
<W lemma="attivo" msd="AN" tag="ADJ" in="" out="">attivo</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="" out="">sul</W>
<W lemma="cancro" msd="NC" tag="NOM" in="" out="">cancro</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">Lo</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="destino" msd="NC" tag="NOM" in="" out="">destino</W>
<W lemma="tocco" msd="AN" tag="ADJ" in="-49:+CONJ/(e)" out="54:+CONC/tuttavia">tocca</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">alla</W>
<W lemma="domanda" msd="NC" tag="NOM" in="" out="">domanda</W>
<W lemma="principale" msd="AN" tag="ADJ" in="" out="">principale</W>
<W lemma="presentare" msd="VAP" tag="VER&3a;pper" in="" out="">presentata</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="Ole" msd="NP" tag="NPR" in="" out="">Ole</W>
<W lemma="bang" msd="NC" tag="NOM" in="" out="">Bang</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="allegare" msd="VAP" tag="VER&3a;pper" in="" out="">allegato</W>
<W lemma="inviare" msd="VAP" tag="VER&3a;pper" in="" out="">inviato</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="me" msd="PP" tag="PRO&3a;pers" in="" out="">me</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">13</W>
<W lemma="ottobre" msd="NC" tag="NOM" in="" out="">ottobre</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="" out="">sulla</W>
<W lemma="questione" msd="NC" tag="NOM" in="" out="">questione</W>
<W lemma="se" msd="CS" tag="CON" in="" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="67:+CONST&3a;elab">Kræftens</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bekæmpelse</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="" out="">si</W>
<W lemma="considerare" msd="VADR" tag="VER&3a;pres" in="" out="">consideri</W>
<W lemma="un'" msd="PI" tag="DET&3a;indef" in="" out="">un'</W>
<W lemma="attività" msd="NC" tag="NOM" in="" out="">attività</W>
<W lemma="orientare" msd="VAP" tag="VER&3a;pper" in="" out="">orientata</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">al</W>
<W lemma="profitto" msd="NC" tag="NOM" in="" out="">profitto</W>
<W lemma="oppure" msd="CS" tag="CON" in="" out="">oppure</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="mediatore" msd="NC" tag="NOM" in="" out="">mediatore</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="sussidio" msd="NC" tag="NOM" in="" out="">sussidi</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="" out="">dalla</W>
<W lemma="popolazione" msd="NC" tag="NOM" in="" out="">popolazione</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">alla</W>
<W lemma="ricerca" msd="NC" tag="NOM" in="" out="">ricerca</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="" out="">sul</W>
<W lemma="cancro" msd="NC" tag="NOM" in="" out="">cancro</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">l'</W>
<W lemma="assistenza" msd="NC" tag="NOM" in="" out="">assistenza</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">ai</W>
<W lemma="paziente" msd="NC" tag="NOM" in="" out="">pazienti</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="indirettamente" msd="RG" tag="ADV" in="" out="">Indirettamente</W>
<W lemma="mi" msd="PP" tag="PRO&3a;pers" in="" out="">mi</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-54:+CONC/tuttavia" out="">è</W>
<W lemma="tuttavia" msd="RG" tag="ADV" in="" out="">tuttavia</W>
<W lemma="arrivare" msd="VAP" tag="VER&3a;pper" in="" out="">arrivata</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="" out="">una</W>
<W lemma="risposta" msd="NC" tag="NOM" in="" out="">risposta</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="solito" msd="AN" tag="ADJ" in="" out="">solita</W>
<W lemma="abitudine" msd="NC" tag="NOM" in="" out="">abitudine</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">del</W>
<W lemma="direttore" msd="NC" tag="NOM" in="" out="">direttore</W>
<W lemma="economico" msd="AN" tag="ADJ" in="" out="">economico</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="argomentare" msd="VAF" tag="VER&3a;infi" in="" out="">argomentare</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="modo" msd="NC" tag="NOM" in="" out="">modo</W>
<W lemma="puramente" msd="RG" tag="ADV" in="" out="">puramente</W>
<W lemma="economico" msd="AN" tag="ADJ" in="" out="">economico</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="">ad</W>
<W lemma="esempio" msd="NC" tag="NOM" in="" out="">esempio</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="" out="">sull'</W>
<W lemma="attività" msd="NC" tag="NOM" in="" out="">attività</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="raccolta" msd="NC" tag="NOM" in="" out="">raccolta</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">dei</W>
<W lemma="fondo" msd="NC" tag="NOM" in="" out="">fondi</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kræftens</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bekæmpelse</W>
<W lemma="sembrare" msd="VADR" tag="VER&3a;pres" in="-67:+CONST&3a;elab" out="40:CONJ/(e)">sembra</W>
<W lemma="concepire" msd="VAF" tag="VER&3a;infi" in="" out="">concepire</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">i</W>
<W lemma="contribuente" msd="NC" tag="NOM" in="" out="">contribuenti</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">allo</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="modo" msd="NC" tag="NOM" in="" out="">modo</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="cui" msd="PT" tag="PRO&3a;rela" in="" out="">cui</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Coca-Cola</W>
<W lemma="trattare" msd="VADR" tag="VER&3a;pres" in="" out="">tratta</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">i</W>
<W lemma="consumatore" msd="NC" tag="NOM" in="" out="">consumatori</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="cioè" msd="RG" tag="ADV" in="" out="">cioè</W>
<W lemma="come" msd="SP" tag="PRE" in="" out="">come</W>
<W lemma="oggetto" msd="NC" tag="NOM" in="" out="">oggetti</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="moderno" msd="AN" tag="ADJ" in="" out="">moderni</W>
<W lemma="metodo" msd="NC" tag="NOM" in="" out="">metodi</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="marketing" msd="NC" tag="NOM" in="" out="">marketing</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="dovere" msd="VADR" tag="VER&3a;pres" in="" out="">devono</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="essere" msd="VAF" tag="VER&3a;infi" in="" out="">essere</W>
<W lemma="motivare" msd="VAP" tag="VER&3a;pper" in="" out="">motivati</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="">ad</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VER&3a;infi" in="" out="">acquistare/a</W>
<W lemma="contribuire" msd="VAF" tag="VER&3a;infi" in="" out="">contribuire</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="più" msd="RG" tag="ADV" in="" out="">più</W>
<W lemma="possibile" msd="AN" tag="ADJ" in="" out="">possibile</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
<s>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="-40:CONJ/(e)" out="27:;AGENTIVE&3a;expl|66:+CONC/(però)">Posso</W>
<W lemma="ben" msd="RG" tag="ADV" in="" out="">ben</W>
<W lemma="capire" msd="VAF" tag="VER&3a;infi" in="" out="">capire</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">i</W>
<W lemma="costo" msd="NC" tag="NOM" in="" out="">costi</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="marketing" msd="NC" tag="NOM" in="" out="">marketing</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kræftens</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bekæmpelse</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="" out="">dal</W>
<W lemma="punto" msd="NC" tag="NOM" in="" out="">punto</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="vista" msd="NC" tag="NOM" in="" out="">vista</W>
<W lemma="puramente" msd="RG" tag="ADV" in="" out="">puramente</W>
<W lemma="economico" msd="AN" tag="ADJ" in="" out="">economico</W>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="" out="">possono</W>
<W lemma="anche" msd="RG" tag="ADV" in="" out="">anche</W>
<W lemma="ammontare" msd="VAF" tag="VER&3a;infi" in="" out="">ammontare</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="circa" msd="RG" tag="ADV" in="" out="">circa</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1/3</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">delle</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="vendita" msd="NC" tag="NOM" in="" out="">vendite</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma=";" msd="XP" tag="PON" in="-27:;AGENTIVE&3a;expl" out="">;</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="surplus" msd="NC" tag="NOM" in="" out="">surplus</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="" out="">dei</W>
<W lemma="contributo" msd="NC" tag="NOM" in="" out="">contributi</W>
<W lemma="(" msd="XP" tag="PON" in="" out="">(</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="manna" msd="NC" tag="NOM" in="" out="">manna</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="" out="">dal</W>
<W lemma="cielo" msd="NC" tag="NOM" in="" out="">cielo</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="" out="">"</W>
<W lemma="l'" msd="PP" tag="PRO&3a;pers" in="" out="">l'</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="">ha</W>
<W lemma="chiamare" msd="VAP" tag="VER&3a;pper" in="" out="">chiamato</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">il</W>
<W lemma="direttore" msd="NC" tag="NOM" in="" out="">direttore</W>
<W lemma="economico" msd="AN" tag="ADJ" in="" out="">economico</W>
<W lemma=")" msd="XP" tag="PON" in="" out="">)</W>
<W lemma="si" msd="PP" tag="PRO&3a;pers" in="" out="">si</W>
<W lemma="attestare" msd="VADR" tag="VER&3a;pres" in="" out="">attestano</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="" out="">al</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">10</W>
<W lemma="percento" msd="NC" tag="NOM" in="" out="">percento</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="quindi" msd="RG" tag="ADV" in="" out="">quindi</W>
<W lemma="c'" msd="PD" tag="PRO&3a;demo" in="" out="">c'</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="">è</W>
<W lemma="sempre" msd="RG" tag="ADV" in="" out="">sempre</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="surplus" msd="NC" tag="NOM" in="" out="">surplus</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="in" msd="SP" tag="PRE" in="" out="">In</W>
<W lemma="ogni" msd="AN" tag="ADJ" in="" out="">ogni</W>
<W lemma="caso" msd="NC" tag="NOM" in="" out="">caso</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-66:+CONC/(però)" out="">sono</W>
<W lemma="convincere" msd="VAP" tag="VER&3a;pper" in="" out="">convinto</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="" out="">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">i</W>
<W lemma="contribuente" msd="NC" tag="NOM" in="" out="">contribuenti</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="trovare" msd="VADR" tag="VER&3a;cpre" in="" out="">trovino</W>
<W lemma="giusto" msd="AN" tag="ADJ" in="" out="">giusto</W>
<W lemma="che" msd="CS" tag="CON" in="" out="">che</W>
<W lemma="circa" msd="RG" tag="ADV" in="" out="">circa</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="" out="">un</W>
<W lemma="terzo" msd="NC" tag="NOM" in="" out="">terzo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="quanto" msd="PI" tag="PRO&3a;indef" in="" out="">quanto</W>
<W lemma="essi" msd="PP" tag="PRO&3a;pers" in="" out="">essi</W>
<W lemma="elargire" msd="VADR" tag="VER&3a;pres" in="" out="">elargiscono</W>
<W lemma="venire" msd="VADR" tag="VER&3a;cpre" in="" out="">venga</W>
<W lemma="usare" msd="VAP" tag="VER&3a;pper" in="" out="">usato</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="" out="">la</W>
<W lemma="pubblicità" msd="NC" tag="NOM" in="" out="">pubblicità</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
