<W lemma="vedere" msd="VAP" tag="VER:pper" in="11:cause" out="1:dobj">Visto</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="4:vobj">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj|4:[subj]" out="1:nobj">l'</W>
<W lemma="azienda" msd="NC" tag="NOM" in="-1:nobj" out="">azienda</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="potere" msd="VADR" tag="VER:pres" in="-4:vobj" out="-3:subj|-1:neg|1:vobj|5:pnct">può</W>
<W lemma="effettuare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj|-4:[subj]">effettuare</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">le</W>
<W lemma="misurazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">misurazioni</W>
<W lemma="richiedere" msd="VAP" tag="VER:pper" in="-1:attrr" out="">richieste</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-11:cause|1:vobj|13:pnct">deve</W>
<W lemma="rivolgere" msd="VAF" tag="VER:infi" in="-1:vobj" out="2:man|6:iobj">rivolgersi</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="a" msd="SP" tag="PRE" in="-2:man" out="-1:pnct|2:nobj|3:pnct">a</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="1:attrd" out="">proprie</W>
<W lemma="spesa" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">spese</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="a" msd="SP" tag="PRE" in="-6:iobj" out="1:nobj|3:conj">a</W>
<W lemma="privato" msd="NC" tag="NOM" in="-1:nobj" out="">privati</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-3:conj" out="-1:coord|1:nobj">ai</W>
<W lemma="laboratorio" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">laboratori</W>
<W lemma="pubblico" msd="AN" tag="ADJ" in="-1:attrr" out="">pubblici</W>
<W lemma="." msd="XP" tag="SENT" in="-13:pnct" out="">.</W>
<W lemma="inoltre" msd="RG" tag="ADV" in="5:struct" out="1:pnct">Inoltre</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj|4:[subj]" out="1:nobj">le</W>
<W lemma="autorità" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">autorità</W>
<W lemma="competente" msd="AN" tag="ADJ" in="-1:attrr" out="">competenti</W>
<W lemma="potere" msd="VADR" tag="VER:pres" in="" out="-5:struct|-3:subj|1:vobj|29:pnct">possono</W>
<W lemma="richiedere" msd="VAF" tag="VER:infi" in="-1:vobj" out="-4:[subj]|1:dobj">richiedere</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="7:vobj">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="6:subj|7:[subj]|8:[subj]" out="1:nobj|24:coref-id">le</W>
<W lemma="analisi" msd="NC" tag="NOM" in="-1:nobj" out="1:ben">analisi</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:ben" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj|15:coref-id">i</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">controlli</W>
<W lemma="interno" msd="AN" tag="ADJ" in="-1:attrr" out="">interni</W>
<W lemma="dovere" msd="VADR" tag="VER:cpre" in="-7:vobj" out="-6:subj|1:vobj|8:bg|7:pnct">debbano</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="-7:[subj]|1:vobj">essere</W>
<W lemma="svolgere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-8:[subj]|1:pobj">svolte</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">da</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="laboratorio" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">laboratorio</W>
<W lemma="indipendente" msd="AN" tag="ADJ" in="-1:attrr" out="">indipendente</W>
<W lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="-8:bg" out="1:nobj">in</W>
<W lemma="caso" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">caso</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="dubbio" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">dubbi</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-1:pobj|-15:coref-id" out="1:nobj|4:conj">sui</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="1:focal">controlli</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="-1:focal" out="">stessi</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-4:conj" out="-1:coord|1:nobj">sul</W>
<W lemma="risultato" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:arg#">risultato</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj:arg#|-24:coref-id" out="1:nobj">delle</W>
<W lemma="analisi" msd="NC" tag="NOM" in="-1:nobj" out="">analisi</W>
<W lemma="." msd="XP" tag="SENT" in="-29:pnct" out="">.</W>
<W lemma="vedere" msd="VADR" tag="VER:pres" in="" out="1:focal|2:pnct|3:source|18:pnct">Vedi</W>
<W lemma="anche" msd="RG" tag="ADV" in="-1:focal" out="">anche</W>
<W lemma=":" msd="XP" tag="PON" in="-2:pnct" out="">:</W>
<W lemma="paragrafo" msd="NC" tag="NOM" in="-3:source" out="1:nobj|7:conj">paragrafo</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:pnct|2:appa">5.3</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-2:appa" out="1:pobj:dobj#">controllo</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj:dobj#" out="1:nobj">a</W>
<W lemma="campione" msd="NC" tag="NOM" in="-1:nobj" out="">campione</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="paragrafo" msd="NC" tag="NOM" in="-7:conj" out="-1:coord|1:nobj">paragrafo</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:pnct|2:appa">5.6</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="svolgimento" msd="NC" tag="NOM" in="-2:appa" out="1:attrr">svolgimento</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="ricerca" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">ricerche</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="laboratorio" msd="NC" tag="NOM" in="-1:nobj" out="">laboratorio</W>
<W lemma="." msd="XP" tag="SENT" in="-18:pnct" out="">.</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="1:appa">5.2</W>
<W lemma="registrazione" msd="NC" tag="NOM" in="-1:appa" out="1:attrr">Registrazione</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">controlli</W>
<W lemma="interno" msd="AN" tag="ADJ" in="-1:attrr" out="">interni</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="5:subj|6:[subj]|7:[subj]" out="1:nobj">I</W>
<W lemma="risultato" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj">risultati</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj:dobj" out="1:nobj">dei</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">controlli</W>
<W lemma="interno" msd="AN" tag="ADJ" in="-1:attrr" out="">interni</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-5:subj|1:vobj|28:qobj|37:pnct|15:pnct">devono</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="-6:[subj]|1:vobj">essere</W>
<W lemma="indicare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-7:[subj]|2:conj">indicati</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="catalogare" msd="VAP" tag="VER:pper" in="-2:conj" out="-1:coord|1:lobj">catalogati</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:lobj" out="1:nobj">in</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="2:nobj">un</W>
<W lemma="apposito" msd="AN" tag="ADJ" in="1:attrd" out="">apposito</W>
<W lemma="registro" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|8:man|1:man">registro</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:man" out="1:nobj">a</W>
<W lemma="disposizione" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">disposizione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">delle</W>
<W lemma="autorità" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">autorità</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="">controllo</W>
<W lemma="," msd="XP" tag="PON" in="-15:pnct" out="">,</W>
<W lemma="da" msd="SP" tag="PRE" in="-8:man" out="1:vobj">da</W>
<W lemma="tenere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:loc|3:time">tenere</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="archivio" msd="NC" tag="NOM" in="-1:nobj" out="">archivio</W>
<W lemma="per" msd="SP" tag="PRE" in="-3:time" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="numero" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|3:attrr">numero</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="prefissato" msd="AN" tag="ADJ" in="-3:attrr" out="">prefissato</W>
<W lemma="(" msd="XP" tag="PON" in="2:pnct" out="">(</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="1:subj" out="">si</W>
<W lemma="consigliare" msd="VADR" tag="VER:pres" in="-28:qobj" out="-1:subj|-2:pnct|1:dobj|8:pnct">consiglia</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="periodo" msd="NC" tag="NOM" in="-1:nobj" out="2:attrr">periodo</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="inferiore" msd="AN" tag="ADJ" in="-2:attrr" out="-1:neg|1:pobj">inferiore</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">ai</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">5</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma=")" msd="XP" tag="PON" in="-8:pnct" out="">)</W>
<W lemma="." msd="XP" tag="SENT" in="-37:pnct" out="">.</W>
<W lemma="occorrere" msd="VADR" tag="VER:pres" in="" out="1:struct|2:vobj|9:¹man|16:pnct">Occorre</W>
<W lemma="inoltre" msd="RG" tag="ADV" in="-1:struct" out="">inoltre</W>
<W lemma="registrare" msd="VAF" tag="VER:infi" in="-2:vobj" out="2:dobj">registrare</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="1:degr" out="">tutte</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:dobj" out="-1:degr|1:nobj|5:²assoc">le</W>
<W lemma="irregolarità" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">irregolarità</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="funzionamento" msd="NC" tag="NOM" in="-1:nobj" out="">funzionamento</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W compound="¹indicando²ne" lemma="indicare" msd="VAG" tag="VER:geru" in="-9:¹man|-5:²assoc|0:²pobj¹" out="-1:pnct|1:dobj|0:²pobj¹">indicandone</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj|3:conj">le</W>
<W lemma="conseguenza" msd="NC" tag="NOM" in="-1:nobj" out="">conseguenze</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="-3:conj" out="-1:coord|2:nobj">le</W>
<W lemma="relativo" msd="AN" tag="ADJ" in="1:attrd" out="">relative</W>
<W lemma="disposizione" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">disposizioni</W>
<W lemma="." msd="XP" tag="SENT" in="-16:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="4:subj|5:[subj]|6:[subj]" out="1:nobj">I</W>
<W lemma="risultato" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">risultati</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">delle</W>
<W lemma="analisi" msd="NC" tag="NOM" in="-1:nobj" out="">analisi</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-4:subj|1:vobj|17:pnct">devono</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="-5:[subj]|1:vobj">essere</W>
<W lemma="accompagnare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-6:[subj]|1:pobj">accompagnati</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="2:nobj">da</W>
<W lemma="preciso" msd="AN" tag="ADJ" in="1:attrd" out="">precise</W>
<W lemma="indicazione" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:pobj">indicazioni</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj|4:conj">sui</W>
<W lemma="metodo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|7:relr">metodi</W>
<W lemma="adottare" msd="VAP" tag="VER:pper" in="-1:attrr" out="">adottati</W>
<W lemma="nonché" msd="CS" tag="CON" in="1:coord" out="">nonché</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-4:conj" out="-1:coord|1:nobj">sull'</W>
<W lemma="orario" msd="NC" tag="NOM" in="-1:nobj" out="2:ref">orario</W>
<W lemma="in" msd="SP" tag="PRE" in="2:time" out="1:nobj">in</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="-1:nobj|-2:ref" out="">cui</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="-7:relr|1:[subj]|2:[subj]" out="-2:time|1:vobj">sono</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:vobj">stati</W>
<W lemma="effettuare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-2:[subj]">effettuati</W>
<W lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W lemma="in" msd="SP" tag="PRE" in="32:cond" out="1:nobj|4:pnct">In</W>
<W lemma="caso" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">caso</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="2:cons|30:²assoc">malfunzionamento</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="con" msd="SP" tag="PRE" in="-2:cons" out="2:nobj|18:pnct">con</W>
<W lemma="conseguente" msd="AN" tag="ADJ" in="1:attrd" out="">conseguente</W>
<W lemma="emissione" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:attrr|2:pobj:subj">emissione</W>
<W lemma="irregolare" msd="AN" tag="ADJ" in="-1:attrr" out="">irregolare</W>
<W lemma="di" msd="SP" tag="PRE" in="-2:pobj:subj" out="1:nobj">di</W>
<W lemma="sostanza" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">sostanze</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="scarico" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">scarico</W>
<W lemma="pericoloso" msd="AN" tag="ADJ" in="-1:attrr" out="2:conj">pericolose</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="nocivo" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord|1:ben">nocive</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:ben" out="1:nobj|4:conj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">l'</W>
<W lemma="ambiente" msd="NC" tag="NOM" in="-1:nobj" out="">ambiente</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="per" msd="SP" tag="PRE" in="-4:conj" out="-1:coord|1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="salute" msd="NC" tag="NOM" in="-1:nobj" out="">salute</W>
<W lemma="," msd="XP" tag="PON" in="-18:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="8:subj" out="1:nobj|5:conj">le</W>
<W lemma="autorità" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">autorità</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="controllo" msd="NC" tag="NOM" in="-1:nobj" out="">controllo</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="-5:conj" out="-1:coord|1:nobj">le</W>
<W lemma="autorità" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">autorità</W>
<W lemma="sanitario" msd="AN" tag="ADJ" in="-1:attrr" out="">sanitarie</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-32:cond|-8:subj|1:¹vobj|4:pnct|5:source">devono</W>
<W compound="¹esser²ne" lemma="essere" msd="VAF" tag="VER:infi" in="-1:¹vobj|-30:²assoc|0:²pobj¹" out="2:vobj|0:²pobj¹">esserne</W>
<W lemma="immediatamente" msd="RG" tag="ADV" in="1:time" out="">immediatamente</W>
<W lemma="informato" msd="AN" tag="ADJ" in="-2:vobj" out="-1:time">informate</W>
<W lemma="." msd="XP" tag="SENT" in="-4:pnct" out="">.</W>
<W lemma="a" msd="SP" tag="PRE" in="-5:source" out="1:nobj|5:pnct">A</W>
<W lemma="norma" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">norma</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">dell'</W>
<W lemma="art." msd="XA" tag="ABR" in="-1:nobj" out="1:nobj">art.</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">20</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
