<W lemma="box" msd="NC" tag="NOM" in="" out="1:nobj">Box</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:loc">64</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:loc" out="2:loc">Linderöd</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="Svezia" msd="NP" tag="NPR" in="-2:loc" out="-1:pnct">Svezia</W>
<W lemma="idiota" msd="NC" tag="NOM" in="" out="1:appr|3:pnct">Idiota</W>
<W lemma="chi" msd="PT" tag="PRO:rela" in="-1:appr" out="1:vobj">chi</W>
<W lemma="lavorare" msd="VADR" tag="VER:pres" in="-1:vobj" out="">lavora</W>
<W lemma="." msd="XP" tag="SENT" in="-3:pnct" out="">.</W>
<W lemma="rapporto" msd="NC" tag="NOM" in="" out="1:attrr">Rapporto</W>
<W lemma="veritiero" msd="AN" tag="ADJ" in="-1:attrr" out="1:pobj">veritiero</W>
<W lemma="su" msd="SP" tag="PRE" in="-1:pobj" out="1:man">su</W>
<W lemma="come" msd="SP" tag="PRE" in="-1:man" out="4:vobj">come</W>
<W lemma="un" msd="PI" tag="DET:indef" in="3:subj" out="1:nobj">un</W>
<W lemma="disoccupato" msd="NC" tag="NOM" in="-1:nobj" out="">disoccupato</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="1:robj" out="">si</W>
<W lemma="sentire" msd="VADR" tag="VER:pres" in="-4:vobj" out="-3:subj|-1:robj|1:predo|2:cause|5:pnct">sente</W>
<W lemma="ridicolo" msd="AN" tag="ADJ" in="-1:predo" out="">ridicolo</W>
<W lemma="perché" msd="RG" tag="ADV" in="-2:cause" out="1:vobj">perché</W>
<W lemma="desiderare" msd="VADR" tag="VER:pres" in="-1:vobj|1:[subj]" out="1:vobj">desidera</W>
<W lemma="lavorare" msd="VAF" tag="VER:infi" in="-1:vobj" out="-1:[subj]">lavorare</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
<W lemma="andare" msd="VAF" tag="VER:infi" in="6:bg" out="1:man|3:concom">Andare</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="giro" msd="NC" tag="NOM" in="-1:nobj" out="">giro</W>
<W lemma="distribuire" msd="VAG" tag="VER:geru" in="-3:concom" out="1:dobj">distribuendo</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">i</W>
<W lemma="giornale" msd="NC" tag="NOM" in="-1:nobj" out="">giornali</W>
<W lemma="potere" msd="VA" tag="VER:cond" in="1:[subj]" out="-6:bg|1:vobj|12:pnct|9:vobj">potrebbe</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="2:comp|-1:[subj]">essere</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-2:comp" out="-1:degr|1:man">che</W>
<W lemma="soddisfare" msd="VAG" tag="VER:ppre" in="-1:man" out="">soddisfacente</W>
<W lemma="," msd="XP" tag="PON" in="4:pnct" out="">,</W>
<W lemma="se" msd="CS" tag="CON" in="3:cond" out="">se</W>
<W lemma="poi" msd="RG" tag="ADV" in="2:cons" out="">poi</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="1:subj|3:[subj]" out="">si</W>
<W lemma="venire" msd="VADA" tag="VER:cimp" in="-9:vobj" out="-4:pnct|-2:cons|-1:subj|2:vobj|-3:cond">venisse</W>
<W lemma="giustamente" msd="RG" tag="ADV" in="1:prg" out="">giustamente</W>
<W lemma="retribuire" msd="VAP" tag="VER:pper" in="-2:vobj" out="-1:prg|-3:[subj]">retribuiti</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
<W lemma="(" msd="XP" tag="PON" in="1:pnct" out="">(</W>
<W lemma="foto" msd="NC" tag="NOM" in="" out="-1:pnct|4:pnct|1:pnct|3:nobj">Foto</W>
<W lemma=":" msd="XP" tag="PON" in="-1:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Bent</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:nobj" out="-1:namef">Rej</W>
<W lemma=")" msd="XP" tag="PON" in="-4:pnct" out="">)</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="1:dobj|4:conj|14:pnct">Ho</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:dobj" out="1:nobj">42</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="-4:conj" out="-1:pnct|1:preds|5:conj">sono</W>
<W lemma="disoccupare" msd="VAP" tag="VER:pper" in="-1:preds" out="1:time">disoccupata</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:time" out="1:nobj">da</W>
<W lemma="due" msd="AN" tag="ADJ" in="-1:nobj" out="">due</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-5:conj" out="-1:coord|1:dobj">ho</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="diploma" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj">diploma</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj" out="1:nobj">di</W>
<W lemma="segretario" msd="NC" tag="NOM" in="-1:nobj" out="">segretaria</W>
<W lemma="." msd="XP" tag="SENT" in="-14:pnct" out="">.</W>
<W lemma="quando" msd="PT" tag="PRO:inter" in="1:time" out="">Quando</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]|6:vobj" out="-1:time|1:vobj">ho</W>
<W lemma="perdere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj|-1:[subj]">perso</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="">lavoro</W>
<W lemma="," msd="XP" tag="PON" in="2:pnct" out="">,</W>
<W lemma="mi" msd="PP" tag="PRO:pers" in="1:robj" out="">mi</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="1:[subj]" out="-2:pnct|-1:robj|1:vobj|-6:vobj|7:conj|17:pnct">sono</W>
<W lemma="iscrivere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:pobj">iscritta</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="2:nobj">a</W>
<W lemma="vario|varo" msd="AN" tag="ADJ" in="1:attrd" out="">vari</W>
<W lemma="corso" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">corsi</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="li" msd="PP" tag="PRO:pers" in="1:dobj" out="">li</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-7:conj|1:[subj]" out="-2:coord|1:vobj|-1:dobj">ho</W>
<W lemma="completare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:man">completati</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">l'</W>
<W lemma="approvazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">approvazione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">della</W>
<W lemma="cassa" msd="NC" tag="NOM" in="-1:nobj" out="1:nobj">cassa</W>
<W lemma="mutuo" msd="AN" tag="ADJ" in="-1:nobj" out="1:pobj:dobj#">mutua</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj#" out="1:nobj">di</W>
<W lemma="disoccupazione" msd="NC" tag="NOM" in="-1:nobj" out="">disoccupazione</W>
<W lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="2:time" out="1:nobj">Nel</W>
<W lemma="contempo" msd="NC" tag="NOM" in="-1:nobj" out="">contempo</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]" out="-2:time|1:vobj|6:man|10:conj|36:pnct">ho</W>
<W lemma="inviare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|2:dobj">inviato</W>
<W lemma="innumerevole" msd="AN" tag="ADJ" in="1:attrd" out="">innumerevoli</W>
<W lemma="domanda" msd="NC" tag="NOM" in="-2:dobj" out="-1:attrd|1:pobj:dobj">domande</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj" out="1:nobj">di</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="">lavoro</W>
<W lemma="rispondere" msd="VAG" tag="VER:geru" in="-6:man" out="1:pobj">rispondendo</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">agli</W>
<W lemma="annuncio" msd="NC" tag="NOM" in="-1:nobj" out="">annunci</W>
<W lemma="ed" msd="CS" tag="CON" in="1:coord" out="">ed</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-10:conj|1:[subj]" out="-1:coord|1:vobj|5:pnct|7:coref-res|9:qobj">ho</W>
<W lemma="ricevere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|3:dobj">ricevuto</W>
<W lemma="altrettanto" msd="AN" tag="ADJ" in="1:attrd" out="">altrettanti</W>
<W lemma="cortese" msd="AN" tag="ADJ" in="1:attrd" out="-1:attrd">cortesi</W>
<W lemma="rifiuto" msd="NC" tag="NOM" in="-3:dobj" out="-1:attrd">rifiuti</W>
<W lemma=";" msd="XP" tag="PON" in="-5:pnct" out="">;</W>
<W lemma="a" msd="SP" tag="PRE" in="3:time" out="1:nobj">a</W>
<W lemma="quel" msd="PD" tag="PRO:demo" in="-7:coref-res|-1:nobj" out="1:nobj">quel</W>
<W lemma="punto" msd="NC" tag="NOM" in="-1:nobj" out="">punto</W>
<W lemma="pensare" msd="VADA" tag="VER:impf" in="-9:qobj" out="-3:time|1:dobj">pensavo</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="1:vobj">che</W>
<W lemma="essere" msd="VADA" tag="VER:cimp" in="-1:vobj" out="1:time">fosse</W>
<W lemma="ora" msd="RG" tag="ADV" in="-1:time" out="1:pobj">ora</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="guadagnare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj|2:contr|7:goal">guadagnare</W>
<W lemma="qualcosa" msd="PI" tag="PRO:indef" in="-1:dobj" out="">qualcosa</W>
<W lemma="invece" msd="RG" tag="ADV" in="-2:contr" out="1:pobj">invece</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="ricevere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">ricevere</W>
<W lemma="sussidio" msd="NC" tag="NOM" in="-1:dobj" out="44:coref-id">sussidi</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="-7:goal" out="-1:pnct|1:vobj">per</W>
<W lemma="ridurre" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">ridurre</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="2:nobj">i</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="1:attrd" out="">miei</W>
<W lemma="debito" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">debiti</W>
<W lemma="." msd="XP" tag="SENT" in="-36:pnct" out="">.</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]" out="1:vobj|13:concom|32:pnct">Ho</W>
<W lemma="accettare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:cause|2:dobj">accettato</W>
<W lemma="quindi" msd="RG" tag="ADV" in="-1:cause" out="">quindi</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-2:dobj" out="1:nobj|50:coref-var">un</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="1:comp">lavoro</W>
<W lemma="come" msd="SP" tag="PRE" in="-1:comp" out="1:nobj">come</W>
<W lemma="distributore" msd="NC" tag="NOM" in="-1:nobj" out="1:agent">distributrice</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:agent" out="1:nobj">di</W>
<W lemma="giornale" msd="NC" tag="NOM" in="-1:nobj" out="1:ben">giornali</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:ben" out="1:nobj">per</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="1:nobj">A/S</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">Bladkompagniet</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W compound="¹sentendo²me³ne" lemma="sentire" msd="VAG" tag="VER:geru" in="-13:concom|0:²robj¹|0:³pobj²" out="-1:pnct|0:²robj¹|0:³pobj²|2:attrr|4:cons">sentendomene</W>
<W lemma="veramente" msd="RG" tag="ADV" in="1:prg" out="">veramente</W>
<W lemma="contento" msd="AN" tag="ADJ" in="-2:attrr" out="-1:prg">contenta</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="visto" msd="CS" tag="CON" in="-4:cons" out="-1:pnct|1:dobj">visto</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="6:vobj">che</W>
<W lemma="per" msd="SP" tag="PRE" in="5:time" out="2:nobj">per</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="1:degr" out="">tutta</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:nobj" out="-1:degr|1:nobj">la</W>
<W lemma="vita" msd="NC" tag="NOM" in="-1:nobj" out="">vita</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="2:neg">non</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="-6:vobj|2:[subj]" out="-5:time|-1:neg|2:vobj">sono</W>
<W lemma="mai" msd="RG" tag="ADV" in="-2:neg" out="">mai</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-2:vobj" out="1:man|-2:[subj]">stata</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">le</W>
<W lemma="mani|mano" msd="NC" tag="NOM" in="-1:nobj" out="1:loc">mani</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="mano" msd="NC" tag="NOM" in="-1:nobj" out="">mano</W>
<W lemma="." msd="XP" tag="SENT" in="-32:pnct" out="">.</W>
<W lemma="visto" msd="CS" tag="CON" in="11:cons" out="1:dobj|9:pnct">Visto</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="1:vobj">che</W>
<W lemma="ricevere" msd="VADR" tag="VER:pres" in="-1:vobj" out="1:dobj">ricevo</W>
<W lemma="il" msd="PD" tag="DET:def" in="-44:coref-id|-1:dobj" out="1:nobj">i</W>
<W lemma="sussidio" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">sussidi</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">della</W>
<W lemma="cassa" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj">cassa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj" out="1:nobj">di</W>
<W lemma="disoccupazione" msd="NC" tag="NOM" in="-1:nobj" out="">disoccupazione</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="ovviamente" msd="RG" tag="ADV" in="1:prg" out="">ovviamente</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]|2:[subj]" out="-11:cons|-1:prg|1:vobj|20:pnct|13:cons">ho</W>
<W lemma="dovere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:vobj">dovuto</W>
<W lemma="indicare" msd="VAF" tag="VER:infi" in="-1:vobj" out="-2:[subj]|1:loc|7:dobj">indicare</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">sullo</W>
<W lemma="schema" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj">schema</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj:dobj" out="1:nobj">delle</W>
<W lemma="ora" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">ore</W>
<W lemma="lavorativo" msd="AN" tag="ADJ" in="-1:attrr" out="1:attrr">lavorative</W>
<W lemma="effettuare" msd="VAP" tag="VER:pper" in="-1:attrr" out="">effettuate</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="-7:dobj|-50:coref-var" out="1:nobj">questo</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">lavoro</W>
<W lemma="temporaneo" msd="AN" tag="ADJ" in="-1:attrr" out="">temporaneo</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W compound="¹chiedendo²mi" lemma="chiedere" msd="VAG" tag="VER:geru" in="0:²robj¹|-13:cons" out="-1:pnct|0:²robj¹|3:vobj">chiedendomi</W>
<W lemma="quale" msd="PT" tag="PRO:rela" in="2:subj|3:[subj]" out="">quali</W>
<W lemma="ne" msd="RG" tag="ADV" in="1:pobj" out="">ne</W>
<W lemma="essere" msd="VA" tag="VER:cond" in="-3:vobj" out="-1:pobj|1:vobj|-2:subj">sarebbero</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:preds|-3:[subj]">state</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:preds" out="1:nobj">le</W>
<W lemma="conseguenza" msd="NC" tag="NOM" in="-1:nobj" out="">conseguenze</W>
<W lemma="." msd="XP" tag="SENT" in="-20:pnct" out="">.</W>
<W lemma="e" msd="CS" tag="CON" in="3:discmark" out="">E</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj|3:[subj]" out="1:nobj">il</W>
<W lemma="risultato" msd="NC" tag="NOM" in="-1:nobj" out="">risultato</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-3:discmark|1:vobj|3:pnct|-2:subj">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:preds|-3:[subj]">stato</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="-1:preds" out="">questo</W>
<W lemma=":" msd="XP" tag="PON" in="-3:pnct" out="">:</W>
