<W lemma="Peter" msd="NP" tag="NPR" in="2:subj|3:[subj]" out="">Peter</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="sentire" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|-1:robj|1:vobj|4:pnct|6:conj|17:pnct">sente</W>
<W lemma="stringere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-3:[subj]|1:pobj">stringere</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj|11:assoc-const|63:coref-id">dalla</W>
<W lemma="cravatta" msd="NC" tag="NOM" in="-1:nobj" out="">cravatta</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="osare" msd="VADR" tag="VER&3a;pres" in="-6:conj|1:[subj]" out="-1:neg|1:vobj">osa</W>
<W lemma="muovere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-1:[subj]|1:dobj|3:cause">muovere</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="testa" msd="NC" tag="NOM" in="-1:nobj" out="">testa</W>
<W lemma="per" msd="SP" tag="PRE" in="-3:cause" out="1:nobj">per</W>
<W lemma="paura" msd="NC" tag="NOM" in="-1:nobj" out="1:dobj">paura</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="4:vobj">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-11:assoc-const|3:subj" out="1:nobj">il</W>
<W lemma="nodo" msd="NC" tag="NOM" in="-1:nobj" out="">nodo</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="slegare" msd="VADR" tag="VER&3a;cpre" in="-4:vobj" out="-3:subj|-1:robj">sleghi</W>
<W lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W lemma="Berlino" msd="NP" tag="NPR" in="3:qobj" out="1:pnct|15:coref-id">Berlino</W>
<W lemma="?" msd="XP" tag="SENT" in="-1:pnct" out="">?</W>
<W lemma="-" msd="XP" tag="PON" in="1:pnct" out="">-</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-1:pnct|-3:qobj|7:qobj">dice-</W>
<W lemma="oh" msd="I=" tag="INT" in="3:other" out="">oh</W>
<W lemma="," msd="XP" tag="PON" in="2:pnct" out="">,</W>
<W lemma="santo" msd="AN" tag="ADJ" in="1:attr" out="">santo</W>
<W lemma="cielo" msd="NC" tag="NOM" in="3:list" out="-2:pnct|-3:other|1:pnct|-1:attr">cielo</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="credere" msd="VADA" tag="VER&3a;impf" in="-7:qobj" out="-1:neg|-3:list|1:dobj|2:pnct">credevo</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="">che</W>
<W lemma="?" msd="XP" tag="SENT" in="-2:pnct" out="">?</W>
<W lemma="sì" msd="RG" tag="ADV" in="3:qobj" out="1:pnct|2:nobj">Sì</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj|-15:coref-id" out="11:assoc-loc">Berlino-</W>
<W lemma="dire" msd="VADR" tag="VER&3a;pres" in="" out="-3:qobj|1:subj|3:pnct">dice</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj" out="1:nobj">il</W>
<W lemma="caporedattore" msd="NC" tag="NOM" in="-1:nobj" out="">caporedattore</W>
<W lemma="." msd="XP" tag="SENT" in="-3:pnct" out="">.</W>
<W lemma="lei" msd="PP" tag="PRO&3a;pers" in="1:subj|3:[subj]" out="">Lei</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|1:time|2:vobj|9:pnct|12:conj">ha</W>
<W lemma="già" msd="RG" tag="ADV" in="-1:time" out="">già</W>
<W lemma="scrivere" msd="VAP" tag="VER&3a;pper" in="-2:vobj" out="-3:[subj]|2:dobj">scritto</W>
<W lemma="magnifico" msd="AN" tag="ADJ" in="1:attr" out="">magnifici</W>
<W lemma="articolo" msd="NC" tag="NOM" in="-2:dobj" out="1:pobj&3a;arg|-1:attr">articoli</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg|-11:assoc-loc" out="1:nobj|11:coref">sulla</W>
<W lemma="repubblica" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">Repubblica</W>
<W lemma="federale" msd="AN" tag="ADJ" in="-1:attr" out="1:attr">Federale</W>
<W lemma="tedesco" msd="AN" tag="ADJ" in="-1:attr" out="">Tedesca</W>
<W lemma=";" msd="XP" tag="PON" in="-9:pnct" out="">;</W>
<W lemma="ora" msd="RG" tag="ADV" in="2:time" out="">ora</W>
<W lemma="vi" msd="PR" tag="PRO&3a;refl" in="1:lobj" out="">vi</W>
<W lemma="andare" msd="VADR" tag="VER&3a;futu" in="-12:conj" out="-2:time|-1:lobj|1:man|3:pnct">andrà</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:man" out="1:nobj">di</W>
<W lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="">persona</W>
<W lemma="." msd="XP" tag="SENT" in="-3:pnct" out="">.</W>
<W lemma="ci" msd="PR" tag="PRO&3a;refl" in="-11:coref|1:loc" out="">Ci</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="2:[subj]" out="-1:loc|1:time|2:vobj|3:pnct|5:conj">è</W>
<W lemma="già" msd="RG" tag="ADV" in="-1:time" out="">già</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-2:vobj" out="-2:[subj]">stato</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="sbaglio" msd="NC" tag="NOM" in="-5:conj" out="-1:coord|1:pnct">sbaglio</W>
<W lemma="?" msd="XP" tag="SENT" in="-1:pnct" out="">?</W>
<W lemma="Peter" msd="NP" tag="NPR" in="1:subj" out="">Peter</W>
<W lemma="dimenticare" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|1:dobj|4:conj|7:pnct">dimentica</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-63:coref-id|-1:dobj" out="1:nobj">la</W>
<W lemma="cravatta" msd="NC" tag="NOM" in="-1:nobj" out="">cravatta</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="annuire" msd="VADR" tag="VER&3a;pres" in="-4:conj" out="-1:coord|2:nobj">annuisce</W>
<W lemma="più" msd="RG" tag="ADV" in="1:ext" out="">più</W>
<W lemma="volto" msd="AN" tag="ADJ" in="-2:nobj" out="-1:ext">volte</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="sì" msd="RG" tag="ADV" in="2:qobj" out="1:pnct">Sì</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="1:[subj]" out="-2:qobj|1:vobj|25:pnct">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|1:man|10:time">stato</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="vacanza" msd="NC" tag="NOM" in="-1:nobj" out="1:loc|3:man">vacanza</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">a</W>
<W lemma="Berlino" msd="NP" tag="NPR" in="-1:nobj" out="14:²coref">Berlino</W>
<W lemma="con" msd="SP" tag="PRE" in="-3:man" out="2:nobj">con</W>
<W lemma="suo" msd="PO" tag="PRO&3a;poss" in="1:attr" out="19:coref-id">suo</W>
<W lemma="padre" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">padre</W>
<W lemma="," msd="XP" tag="PON" in="2:pnct" out="">,</W>
<W lemma="proprio" msd="RG" tag="ADV" in="1:focal" out="">proprio</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-10:time" out="-1:focal|-2:pnct|2:nobj|3:pnct|4:time|78:coref-res">nel</W>
<W lemma="novembre" msd="NC" tag="NOM" in="1:nobj" out="">novembre</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:nobj" out="-1:nobj">1918</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="quando" msd="CS" tag="CON" in="-4:time" out="">quando</W>
<W lemma="nessuno" msd="AN" tag="ADJ" in="2:subj|3:[subj]" out="1:nobj">nessuno</W>
<W lemma="straniero" msd="NC" tag="NOM" in="-1:nobj" out="">straniero</W>
<W lemma="osare" msd="VADA" tag="VER&3a;impf" in="" out="-2:subj|1:¹vobj|2:pnct|3:cause">osava</W>
<W compound="¹andar²ci" lemma="andare" msd="VAF" tag="VER&3a;infi" in="-1:¹vobj|-14:²coref|0:²lobj¹" out="-3:[subj]|0:²lobj¹">andarci</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="dare" msd="VAP" tag="VER&3a;pper" in="-3:cause" out="1:dobj">dato</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="disordine" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">disordine</W>
<W lemma="generale" msd="AN" tag="ADJ" in="-1:attr" out="">generale</W>
<W lemma="." msd="XP" tag="SENT" in="-25:pnct" out="">.</W>
<W lemma="suo" msd="PO" tag="PRO&3a;poss" in="-19:coref-id|1:attr" out="18:coref-var">Suo</W>
<W lemma="padre" msd="NC" tag="NOM" in="1:subj|2:[subj]" out="-1:attr">padre</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|1:vobj|15:pnct">ha</W>
<W lemma="sentire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-2:[subj]|1:dobj">sentito</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj|3:[subj]" out="1:nobj">il</W>
<W lemma="socialdemocratico" msd="AN" tag="ADJ" in="-1:nobj" out="1:appr">socialdemocratico</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:appr" out="1:vobj">Scheidemann</W>
<W lemma="&lt;unknown&gt;" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-3:[subj]|1:dobj|4:loc">annunziare</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="repubblica" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">Repubblica</W>
<W lemma="democratico" msd="AN" tag="ADJ" in="-1:attr" out="">Democratica</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-4:loc" out="1:nobj">dal</W>
<W lemma="balcone" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">balcone</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:const">del</W>
<W lemma="palazzo" msd="NC" tag="NOM" in="-1:const" out="1:attr">palazzo</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:agent">del</W>
<W lemma="parlamento" msd="NC" tag="NOM" in="-1:agent" out="">Parlamento</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
<W lemma="lui" msd="PP" tag="PRO&3a;pers" in="-18:coref-var|4:subj|5:[subj]" out="1:focal">Lui</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:focal" out="1:nobj">in</W>
<W lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="">persona</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-4:subj|-1:robj|1:vobj|13:conj|29:pnct">è</W>
<W lemma="aprire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-5:[subj]|1:dobj">aperto</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="varco" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">varco</W>
<W lemma="attraverso" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">attraverso</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="folla" msd="NC" tag="NOM" in="-1:nobj" out="1:loc">folla</W>
<W lemma="davanti" msd="AN" tag="ADJ" in="-1:loc" out="1:pobj">davanti</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="2:nobj">al</W>
<W lemma="precedente" msd="AN" tag="ADJ" in="1:attr" out="">precedente</W>
<W lemma="palazzo" msd="NC" tag="NOM" in="-2:nobj" out="1:attr|-1:attr">palazzo</W>
<W lemma="imperiale" msd="AN" tag="ADJ" in="-1:attr" out="">imperiale</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="-13:conj|1:[subj]" out="-1:coord|1:vobj">ha</W>
<W lemma="ascoltare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|2:dobj">ascoltato</W>
<W lemma="Karl" msd="NP" tag="NPR" in="1:namef" out="">Karl</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:dobj|1:[subj]" out="-1:namef|1:vobj">Liebknecht</W>
<W lemma="proclamare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-1:[subj]|1:dobj">proclamare</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="1:attr|2:attr">Repubblica</W>
<W lemma="socialista" msd="NC" tag="NOM" in="-1:attr" out="">Socialista</W>
<W lemma="reggere" msd="VAP" tag="VER&3a;pper" in="-2:attr" out="1:pobj">retta</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">dal</W>
<W lemma="consiglio" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">Consiglio</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj|3:conj">dei</W>
<W lemma="lavoratore" msd="NC" tag="NOM" in="-1:nobj" out="">lavoratori</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">dei</W>
<W lemma="militare" msd="AN" tag="ADJ" in="-1:nobj" out="">militari</W>
<W lemma="." msd="XP" tag="SENT" in="-29:pnct" out="">.</W>
<W lemma="caspita" msd="I=" tag="INT" in="" out="2:nobj|5:vobj|13:pnct">Caspita</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="Lange" msd="NP" tag="NPR" in="-2:nobj" out="-1:pnct|1:pnct">Lange</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="ne" msd="RG" tag="ADV" in="1:pobj" out="">ne</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-5:vobj" out="-1:pobj|1:vobj|4:pnct|5:time">sono</W>
<W lemma="succedere" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="1:pobj">successe</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="cosa" msd="NC" tag="NOM" in="-1:nobj" out="">cose</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="a" msd="SP" tag="PRE" in="-5:time" out="1:nobj">a</W>
<W lemma="quei" msd="PD" tag="PRO&3a;demo" in="-78:coref-res|-1:nobj" out="1:nobj">quei</W>
<W lemma="tempo" msd="NC" tag="NOM" in="-1:nobj" out="">tempi</W>
<W lemma="." msd="XP" tag="SENT" in="-13:pnct" out="">.</W>
<W lemma="ecco" msd="RG" tag="ADV" in="3:focal" out="1:pnct">Ecco</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="ora" msd="RG" tag="ADV" in="1:time" out="">ora</W>
<W lemma="arrivare" msd="VADR" tag="VER&3a;pres" in="" out="-1:time|-3:focal|1:subj|5:pnct">arrivano</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj" out="2:nobj">le</W>
<W lemma="nostro" msd="PO" tag="PRO&3a;poss" in="1:attr" out="">nostre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj" out="1:attr|-1:attr">tortine</W>
<W lemma="salato" msd="AN" tag="ADJ" in="-1:attr" out="">salate</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
