<W lemma="Peter" msd="NP" tag="NPR" in="" out="">Peter</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="sentire" msd="VADR" tag="VER:pres" in="" out="">sente</W>
<W lemma="stringere" msd="VAF" tag="VER:infi" in="" out="">stringere</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="">dalla</W>
<W lemma="cravatta" msd="NC" tag="NOM" in="" out="">cravatta</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="osare" msd="VADR" tag="VER:pres" in="" out="">osa</W>
<W lemma="muovere" msd="VAF" tag="VER:infi" in="" out="">muovere</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="testa" msd="NC" tag="NOM" in="" out="">testa</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="paura" msd="NC" tag="NOM" in="" out="">paura</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="nodo" msd="NC" tag="NOM" in="" out="">nodo</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="slegare" msd="VADR" tag="VER:cpre" in="" out="">sleghi</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="Berlino" msd="NP" tag="NPR" in="" out="">Berlino</W>
<W lemma="?" msd="XP" tag="SENT" in="" out="">?</W>
<W lemma="-" msd="XP" tag="PON" in="" out="">-</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">dice-</W>
<W lemma="oh" msd="I=" tag="INT" in="" out="">oh</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="santo" msd="AN" tag="ADJ" in="" out="">santo</W>
<W lemma="cielo" msd="NC" tag="NOM" in="" out="">cielo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="credere" msd="VADA" tag="VER:impf" in="" out="">credevo</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="?" msd="XP" tag="SENT" in="" out="">?</W>
<W lemma="sì" msd="RG" tag="ADV" in="" out="">Sì</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Berlino-</W>
<W lemma="dire" msd="VADR" tag="VER:pres" in="" out="">dice</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="caporedattore" msd="NC" tag="NOM" in="" out="">caporedattore</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="lei" msd="PP" tag="PRO:pers" in="" out="">Lei</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="già" msd="RG" tag="ADV" in="" out="">già</W>
<W lemma="scrivere" msd="VAP" tag="VER:pper" in="" out="">scritto</W>
<W lemma="magnifico" msd="AN" tag="ADJ" in="" out="">magnifici</W>
<W lemma="articolo" msd="NC" tag="NOM" in="" out="">articoli</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulla</W>
<W lemma="repubblica" msd="NC" tag="NOM" in="" out="">Repubblica</W>
<W lemma="federale" msd="AN" tag="ADJ" in="" out="">Federale</W>
<W lemma="tedesco" msd="AN" tag="ADJ" in="" out="">Tedesca</W>
<W lemma=";" msd="XP" tag="PON" in="" out="">;</W>
<W lemma="ora" msd="RG" tag="ADV" in="" out="">ora</W>
<W lemma="vi" msd="PR" tag="PRO:refl" in="" out="">vi</W>
<W lemma="andare" msd="VADR" tag="VER:futu" in="" out="">andrà</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="persona" msd="NC" tag="NOM" in="" out="">persona</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="ci" msd="PR" tag="PRO:refl" in="" out="">Ci</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="già" msd="RG" tag="ADV" in="" out="">già</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stato</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="o" msd="CS" tag="CON" in="" out="">o</W>
<W lemma="sbaglio" msd="NC" tag="NOM" in="" out="">sbaglio</W>
<W lemma="?" msd="XP" tag="SENT" in="" out="">?</W>
<W lemma="Peter" msd="NP" tag="NPR" in="" out="">Peter</W>
<W lemma="dimenticare" msd="VADR" tag="VER:pres" in="" out="">dimentica</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="cravatta" msd="NC" tag="NOM" in="" out="">cravatta</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="annuire" msd="VADR" tag="VER:pres" in="" out="">annuisce</W>
<W lemma="più" msd="RG" tag="ADV" in="" out="">più</W>
<W lemma="volto" msd="AN" tag="ADJ" in="" out="">volte</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="sì" msd="RG" tag="ADV" in="" out="">Sì</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stato</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="vacanza" msd="NC" tag="NOM" in="" out="">vacanza</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="Berlino" msd="NP" tag="NPR" in="" out="">Berlino</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="" out="">suo</W>
<W lemma="padre" msd="NC" tag="NOM" in="" out="">padre</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="proprio" msd="RG" tag="ADV" in="" out="">proprio</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nel</W>
<W lemma="novembre" msd="NC" tag="NOM" in="" out="">novembre</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1918</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="quando" msd="CS" tag="CON" in="" out="">quando</W>
<W lemma="nessuno" msd="AN" tag="ADJ" in="" out="">nessuno</W>
<W lemma="straniero" msd="NC" tag="NOM" in="" out="">straniero</W>
<W lemma="osare" msd="VADA" tag="VER:impf" in="" out="">osava</W>
<W lemma="andare" msd="VAF" tag="VER:infi" in="" out="">andarci</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="dare" msd="VAP" tag="VER:pper" in="" out="">dato</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="disordine" msd="NC" tag="NOM" in="" out="">disordine</W>
<W lemma="generale" msd="AN" tag="ADJ" in="" out="">generale</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="" out="">Suo</W>
<W lemma="padre" msd="NC" tag="NOM" in="" out="">padre</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="sentire" msd="VAP" tag="VER:pper" in="" out="">sentito</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="socialdemocratico" msd="AN" tag="ADJ" in="" out="">socialdemocratico</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Scheidemann</W>
<W lemma="&lt;unknown&gt;" msd="VAP" tag="VER:pper" in="" out="">annunziare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="repubblica" msd="NC" tag="NOM" in="" out="">Repubblica</W>
<W lemma="democratico" msd="AN" tag="ADJ" in="" out="">Democratica</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="">dal</W>
<W lemma="balcone" msd="NC" tag="NOM" in="" out="">balcone</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="palazzo" msd="NC" tag="NOM" in="" out="">palazzo</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="parlamento" msd="NC" tag="NOM" in="" out="">Parlamento</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="lui" msd="PP" tag="PRO:pers" in="" out="">Lui</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="persona" msd="NC" tag="NOM" in="" out="">persona</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="aprire" msd="VAP" tag="VER:pper" in="" out="">aperto</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="varco" msd="NC" tag="NOM" in="" out="">varco</W>
<W lemma="attraverso" msd="SP" tag="PRE" in="" out="">attraverso</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="folla" msd="NC" tag="NOM" in="" out="">folla</W>
<W lemma="davanti" msd="AN" tag="ADJ" in="" out="">davanti</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="precedente" msd="AN" tag="ADJ" in="" out="">precedente</W>
<W lemma="palazzo" msd="NC" tag="NOM" in="" out="">palazzo</W>
<W lemma="imperiale" msd="AN" tag="ADJ" in="" out="">imperiale</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="ascoltare" msd="VAP" tag="VER:pper" in="" out="">ascoltato</W>
<W lemma="Karl" msd="NP" tag="NPR" in="" out="">Karl</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Liebknecht</W>
<W lemma="proclamare" msd="VAF" tag="VER:infi" in="" out="">proclamare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Repubblica</W>
<W lemma="socialista" msd="NC" tag="NOM" in="" out="">Socialista</W>
<W lemma="reggere" msd="VAP" tag="VER:pper" in="" out="">retta</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="">dal</W>
<W lemma="consiglio" msd="NC" tag="NOM" in="" out="">Consiglio</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="lavoratore" msd="NC" tag="NOM" in="" out="">lavoratori</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="militare" msd="AN" tag="ADJ" in="" out="">militari</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="caspita" msd="I=" tag="INT" in="" out="">Caspita</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="Lange" msd="NP" tag="NPR" in="" out="">Lange</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="ne" msd="RG" tag="ADV" in="" out="">ne</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="succedere" msd="VAP" tag="VER:pper" in="" out="">successe</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="cosa" msd="NC" tag="NOM" in="" out="">cose</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="quei" msd="PD" tag="PRO:demo" in="" out="">quei</W>
<W lemma="tempo" msd="NC" tag="NOM" in="" out="">tempi</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="ecco" msd="RG" tag="ADV" in="" out="">Ecco</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="ora" msd="RG" tag="ADV" in="" out="">ora</W>
<W lemma="arrivare" msd="VADR" tag="VER:pres" in="" out="">arrivano</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="" out="">nostre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">tortine</W>
<W lemma="salato" msd="AN" tag="ADJ" in="" out="">salate</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
