<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:neg" out="">“Non</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="-1:neg|1:dobj|2:pnct">in</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="-1:dobj" out="">tutte</W>
<W lemma="." msd="XP" tag="SENT" in="-2:pnct" out="">.</W>
<W lemma="tuo" msd="PO" tag="PRO:poss" in="2:subj" out="1:nobj">Tua</W>
<W lemma="madre" msd="NC" tag="NOM" in="-1:nobj" out="">madre</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="-2:subj|2:preds|4:dobj|7:pnct">era</W>
<W lemma="molto" msd="RG" tag="ADV" in="1:degr" out="">molto</W>
<W lemma="snello" msd="AN" tag="ADJ" in="-2:preds" out="-1:degr">snella</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-4:dobj" out="-1:pnct|1:nobj">un</W>
<W lemma="tipo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">tipo</W>
<W lemma="atletico" msd="AN" tag="ADJ" in="-1:attrr" out="">atletico</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="quando" msd="CS" tag="CON" in="10:time" out="1:vobj">Quando</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="-1:vobj" out="1:dobj|6:pnct">era</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:dobj" out="1:vobj">in</W>
<W lemma="attesa" msd="NC" tag="NOM" in="-1:vobj" out="1:pobj">attesa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:dobj">di</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="-1:dobj" out="1:nobj">nostra</W>
<W lemma="figlio" msd="NC" tag="NOM" in="-1:nobj" out="">figlia</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="2:neg" out="">non</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="1:subj" out="">si</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-10:time|-2:neg|-1:subj|1:degr|2:neg|3:time|7:pnct">notò</W>
<W lemma="quasi" msd="RG" tag="ADV" in="-1:degr" out="">quasi</W>
<W lemma="nulla" msd="RG" tag="ADV" in="-2:neg" out="">nulla</W>
<W lemma="primo" msd="AN" tag="ADJ" in="-3:time" out="1:pobj">prima</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">del</W>
<W lemma="settimo" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">settimo</W>
<W lemma="mesa|mese" msd="NC" tag="NOM" in="-1:nobj" out="">mese</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="la" msd="PP" tag="PRO:pers" in="1:dobj" out="">La</W>
<W lemma="portare" msd="VADA" tag="VER:impf" in="" out="-1:dobj|1:man|2:pnct|3:ref|5:rel">portava</W>
<W lemma="bene" msd="I=" tag="INT" in="-1:man" out="">bene</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="come" msd="CS" tag="CON" in="-3:ref" out="">come</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="1:subj" out="">si</W>
<W lemma="usare" msd="VADR" tag="VER:pres" in="-5:rel" out="-1:subj|1:vobj">usa</W>
<W lemma="dire" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:loc|4:loc">dire</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:possr">dalle</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="-1:possr" out="1:possd">mie</W>
<W lemma="parte|parto" msd="NC" tag="NOM" in="-1:possd" out="">parti</W>
<W lemma="in" msd="SP" tag="PRE" in="-4:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Danimarca.”</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:subj" out="">“Ci</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="7:qobj" out="-1:subj|1:vobj|14:vobj">deve</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:vobj">esser</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj">stato</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="altro" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">altro</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">uomo”</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-7:qobj|-1:pnct|1:subj|5:pnct">constatò</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:subj" out="">Loulou</W>
<W lemma="con" msd="SP" tag="PRE" in="0:man" out="1:nobj|0:man">con</W>
<W lemma="tono" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">tono</W>
<W lemma="imparziale" msd="AN" tag="ADJ" in="-1:attrr" out="">imparziale</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:neg" out="">“non</W>
<W lemma="avere" msd="VADA" tag="VER:impf" in="-14:vobj" out="-1:neg|1:vobj|6:pnct">avevi</W>
<W lemma="notare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj">notato</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="1:dobj">che</W>
<W lemma="&lt;unknown&gt;" msd="VADR" tag="VER:pres" in="-1:dobj" out="1:nobj">c’era</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="altro" msd="AN" tag="ADJ" in="-1:nobj" out="">altro</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-6:pnct" out="">?”</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:subj" out="">Bernie</W>
<W lemma="stare" msd="VADA" tag="VER:remo" in="" out="-1:subj|1:man|3:pobj|5:pnct|8:conj|15:pnct">stette</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:man" out="1:nobj">a</W>
<W lemma="lungo" msd="AN" tag="ADJ" in="-1:nobj" out="">lungo</W>
<W lemma="in" msd="SP" tag="PRE" in="-3:pobj" out="1:nobj">in</W>
<W lemma="silenzio" msd="NC" tag="NOM" in="-1:nobj" out="">silenzio</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="poi" msd="RG" tag="ADV" in="2:coord" out="">poi</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="1:subj" out="">si</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-8:conj" out="-1:subj|-2:coord|1:dir">piegò</W>
<W lemma="verso" msd="SP" tag="PRE" in="-1:dir" out="1:dobj">verso</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:dobj" out="1:vobj">l’altro</W>
<W lemma="guardare" msd="VAG" tag="VER:geru" in="-1:vobj" out="1:man">guardandola</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="1:nobj">con</W>
<W lemma="occhio" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">occhi</W>
<W lemma="penetrante" msd="AN" tag="ADJ" in="-1:attrr" out="">penetranti</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="4:coref-res" out="1:nobj|3:conj">“Tua</W>
<W lemma="madre" msd="NC" tag="NOM" in="-1:nobj" out="">madre</W>
<W lemma="ed" msd="CS" tag="CON" in="1:coord" out="">ed</W>
<W lemma="io" msd="PP" tag="PRO:pers" in="-3:conj|1:coref-res" out="-1:coord">io</W>
<W lemma="ci" msd="PR" tag="PRO:refl" in="1:subj" out="-4:coref-res|-1:coref-res">ci</W>
<W lemma="amare" msd="VADA" tag="VER:impf" in="" out="-1:subj|1:pnct|3:vobj">amavamo</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="lo" msd="PP" tag="PRO:pers" in="1:dobj" out="">lo</W>
<W lemma="capire" msd="VADR" tag="VER:pres" in="-3:vobj" out="-1:dobj|1:pnct|2:pnct|3:pnct">capisci</W>
<W lemma="?" msd="XP" tag="SENT" in="-1:pnct" out="">?</W>
<W lemma="!" msd="XP" tag="SENT" in="-2:pnct" out="">!</W>
<W lemma="!" msd="XP" tag="SENT" in="-3:pnct" out="">!</W>
<W lemma="ci" msd="PP" tag="PRO:pers" in="1:subj" out="">Ci</W>
<W lemma="incontrare" msd="VADA" tag="VER:remo" in="" out="-1:subj|1:loc|4:conj|10:pnct">incontrammo</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">a</W>
<W lemma="Parigi" msd="NP" tag="NPR" in="-1:nobj" out="">Parigi</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="essere" msd="VADA" tag="VER:remo" in="-4:conj" out="-1:coord|1:dobj">fu</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="2:nobj">un</W>
<W lemma="vero" msd="AN" tag="ADJ" in="1:degr" out="">vero</W>
<W lemma="colpo" msd="NC" tag="NOM" in="-2:nobj" out="-1:degr|1:pobj">colpo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="fulmine" msd="NC" tag="NOM" in="-1:nobj" out="">fulmine</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">Non</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="-1:neg|1:dobj|8:pnct|10:conj">era</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="tipo" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">tipo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="donna" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">donna</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">da</W>
<W lemma="tresca" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr:dobj#">tresche</W>
<W lemma="amoroso" msd="AN" tag="ADJ" in="-1:attrr:dobj#" out="">amorose</W>
<W lemma="," msd="XP" tag="PON" in="-8:pnct" out="">,</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-10:conj" out="-1:neg|1:neg|2:vobj">ha</W>
<W lemma="mai" msd="RG" tag="ADV" in="-1:neg" out="">mai</W>
<W lemma="&lt;unknown&gt;" msd="VAP" tag="VER:pper" in="-2:vobj" out="">mentito.”</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:subj" out="">“Lei</W>
<W lemma="mi" msd="PP" tag="PRO:pers" in="1:iobj" out="">mi</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="-2:subj|-1:iobj|1:vobj|2:pnct">ha</W>
<W lemma="mentire" msd="VAP" tag="VER:pper" in="-1:vobj" out="">mentito</W>
<W lemma="." msd="XP" tag="SENT" in="-2:pnct" out="">.</W>
<W lemma="mi" msd="PP" tag="PRO:pers" in="1:iobj" out="">Mi</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="-1:iobj|1:vobj">ha</W>
<W lemma="fare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:vobj">fatto</W>
<W lemma="credere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">credere</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="2:vobj|42:conj?">che</W>
<W lemma="tu" msd="PP" tag="PRO:pers" in="1:subj" out="">tu</W>
<W lemma="essere" msd="VADA" tag="VER:cimp" in="-2:vobj" out="-1:subj|1:possr">fossi</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="-1:possr" out="1:possd">mio</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:possd" out="">padre.”</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:prg" out="">“Probabilmente</W>
<W lemma="&lt;unknown&gt;" msd="VADR" tag="VER:futu" in="" out="-1:prg|1:vobj|5:pnct|6:voc|7:pnct">avrà</W>
<W lemma="avere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj">avuto</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:possr">i</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-1:possr" out="1:possd">suoi</W>
<W lemma="motivo" msd="NC" tag="NOM" in="-1:possd" out="">motivi</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-6:voc" out="">Loulou</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">Non</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-1:neg|1:vobj|13:pnct">deve</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:vobj">esser</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:nobj">stato</W>
<W lemma="facile" msd="AN" tag="ADJ" in="-1:nobj" out="1:pobj|3:vobj">facile</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:pobj" out="">per</W>
<W lemma="lei" msd="PP" tag="PRO:pers" in="0:nobj" out="0:nobj">lei</W>
<W lemma="tornare" msd="VAF" tag="VER:infi" in="-3:vobj" out="1:pobj|4:pobj">tornare</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:possr">dai</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-1:possr" out="1:possd">suoi</W>
<W lemma="genitore" msd="NC" tag="NOM" in="-1:possd" out="">genitori</W>
<W lemma="in" msd="SP" tag="PRE" in="-4:pobj" out="1:dobj">in</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:dobj" out="1:nobj">quello</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:nobj" out="">stato</W>
<W lemma="." msd="XP" tag="SENT" in="-13:pnct" out="">.</W>
<W lemma="forse" msd="RG" tag="ADV" in="1:prg" out="">Forse</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="1:vobj|15:pnct|-1:prg">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:vobj">stata</W>
<W lemma="costringere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:pobj">costretta</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="nascondere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">nascondere</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">verità</W>
<W lemma="e" msd="CS" tag="CON" in="5:coord" out="">e</W>
<W lemma="col" msd="SP+P" tag="PRE:det" in="" out="1:vobj">col</W>
<W lemma="passare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">passar</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:dobj" out="1:nobj">del</W>
<W lemma="tempo" msd="NC" tag="NOM" in="-1:nobj" out="">tempo</W>
<W lemma="il" msd="PD" tag="DET:def" in="-42:conj?" out="1:vobj|-5:coord">la</W>
<W lemma="rimuovere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:degr">rimossa</W>
<W lemma="completamente" msd="RG" tag="ADV" in="-1:degr" out="">completamente</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
<W lemma="era" msd="NC" tag="NOM" in="" out="6:pnct|11:pnct|2:fpreds">Era</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:degr" out="">più</W>
<W lemma="semplice" msd="AN" tag="ADJ" in="-2:fpreds" out="-1:degr|1:man|2:iobj">semplice</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:man" out="">così</W>
<W lemma="per" msd="SP" tag="PRE" in="-2:iobj" out="1:nobj|5:conj">per</W>
<W lemma="lei" msd="PP" tag="PRO:pers" in="-1:nobj" out="">lei</W>
<W lemma="..." msd="XP" tag="PON" in="-6:pnct" out="">...</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="anche" msd="RG" tag="ADV" in="1:coord" out="-1:coord">anche</W>
<W lemma="per" msd="SP" tag="PRE" in="-5:conj" out="-1:coord|1:nobj">per</W>
<W lemma="te" msd="PP" tag="PRO:pers" in="-1:nobj" out="">te</W>
<W lemma="." msd="XP" tag="SENT" in="-11:pnct" out="">.</W>
<W lemma="sicuramente" msd="RG" tag="ADV" in="1:prg" out="">Sicuramente</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="1:vobj|-1:prg">ha</W>
<W lemma="agire" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:man|4:cause">agito</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:dobj">in</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="-1:dobj" out="1:nobj">questo</W>
<W lemma="modo" msd="NC" tag="NOM" in="-1:nobj" out="">modo</W>
<W lemma="per" msd="SP" tag="PRE" in="-4:cause" out="1:dobj">per</W>
<W lemma="amor" msd="NC" tag="NOM" in="-1:dobj" out="1:iobj">amor</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:iobj" out="">tuo.”</W>
