<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kapitel</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">I</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Capitolo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">I</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Come</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="1:subj" out="">si</W>
<W lemma="rapportare" msd="VADR" tag="VER:pres" in="" out="-1:subj|1:dobj|3:pobj|6:pnct">rapporta</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="bambino" msd="NC" tag="NOM" in="-1:nobj" out="">bambino</W>
<W lemma="ad" msd="SP" tag="PRE" in="-3:pobj" out="1:nobj">ad</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">una</W>
<W lemma="lingua" msd="NC" tag="NOM" in="-1:nobj" out="">lingua</W>
<W lemma="?" msd="XP" tag="SENT" in="-6:pnct" out="">?</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:loc" out="">Dov'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-1:loc|1:subj|8:pnct">è</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:subj" out="1:nobj">il</W>
<W lemma="bambino" msd="NC" tag="NOM" in="-1:nobj" out="1:ref|3:relr">bambino</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:ref|2:dobj" out="">che</W>
<W lemma="io" msd="PP" tag="PRO:pers" in="1:subj" out="">io</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="-3:relr" out="-2:dobj|-1:subj|1:time">ero</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:time" out="1:nobj">un</W>
<W lemma="tempo" msd="NC" tag="NOM" in="-1:nobj" out="">tempo</W>
<W lemma="?" msd="XP" tag="SENT" in="-8:pnct" out="">?</W>
<W compound="¹E²´³in" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:³loc¹" out="1:nobj|3:conj|6:pnct|-2:³loc¹">E´in</W>
<W lemma="me" msd="PP" tag="PRO:pers" in="-1:nobj" out="">me</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-3:conj" out="-1:coord|1:time|2:loc">è</W>
<W lemma="oramai" msd="RG" tag="ADV" in="-1:time" out="">oramai</W>
<W lemma="lontano" msd="AN" tag="ADJ" in="-2:loc" out="">lontano</W>
<W lemma="?" msd="XP" tag="SENT" in="-6:pnct" out="">?</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Pablo</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="-1:namef|1:pnct|2:time">Neruda</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:time" out="">1978</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:subj" out="1:nobj|19:coref-var">Un</W>
<W lemma="neonato" msd="AN" tag="ADJ" in="-1:nobj" out="">neonato</W>
<W lemma="sapere" msd="VADR" tag="VER:pres" in="" out="-2:subj|1:degr|4:vobj|15:cause|30:pnct">sa</W>
<W lemma="più" msd="RG" tag="ADV" in="-1:degr" out="1:comp">più</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:comp" out="1:nobj">di</W>
<W lemma="quanto" msd="RG" tag="ADV" in="-1:nobj|1:[dobj]" out="">quanto</W>
<W lemma="ritenere" msd="VADR" tag="VER:pres" in="-4:vobj" out="-1:[dobj]|1:subj|4:pnct">ritengono</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:subj" out="2:nobj">i</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="1:attrd" out="">suoi</W>
<W lemma="genitore" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">genitori</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="o" msd="CS" tag="CON" in="" out="">o</W>
<W lemma="piuttosto" msd="RG" tag="ADV" in="" out="">piuttosto</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="quanto" msd="RG" tag="ADV" in="" out="">quanto</W>
<W lemma="notare" msd="VADR" tag="VER:pres" in="" out="">notano</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="dare" msd="VAP" tag="VER:pper" in="-15:cause" out="1:dobj">dato</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="3:vobj">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="-19:coref-var|2:subj|4:[subj]|8:[subj]" out="1:nobj">il</W>
<W lemma="bimbo" msd="NC" tag="NOM" in="-1:nobj" out="">bimbo</W>
<W lemma="potere" msd="VADR" tag="VER:pres" in="-3:vobj" out="-2:subj|1:degr|2:vobj">può</W>
<W lemma="solo" msd="RG" tag="ADV" in="-1:degr" out="">solo</W>
<W lemma="mostrare" msd="VAF" tag="VER:infi" in="-2:vobj" out="-4:[subj]|4:conj">mostrare</W>
<W lemma="," msd="XP" tag="PON" in="3:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="dire" msd="VAF" tag="VER:infi" in="-4:conj" out="-3:pnct|-1:neg|-2:coord|-8:[subj]">dire</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="" out="">quello</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="sapere" msd="VADR" tag="VER:pres" in="" out="">sa</W>
<W lemma="fare" msd="VAF" tag="VER:infi" in="" out="">fare</W>
<W lemma="." msd="XP" tag="SENT" in="-30:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">Il</W>
<W lemma="fatto" msd="NC" tag="NOM" in="" out="">fatto</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="neonato" msd="NC" tag="NOM" in="" out="">neonato</W>
<W lemma="sapere" msd="VADR" tag="VER:pres" in="" out="">sa</W>
<W lemma="più" msd="RG" tag="ADV" in="" out="">più</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="quanto" msd="RG" tag="ADV" in="" out="">quanto</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="" out="">si</W>
<W lemma="noto" msd="AN" tag="ADJ" in="" out="">noti</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="complesso" msd="AN" tag="ADJ" in="" out="">complesso</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="tutto" msd="PI" tag="PRO:indef" in="" out="">Tutti</W>
<W lemma="ne" msd="RG" tag="ADV" in="" out="">ne</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">siamo</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stati</W>
<W lemma="capace" msd="AN" tag="ADJ" in="" out="">capaci</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="comunque" msd="RG" tag="ADV" in="" out="">comunque</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">Per</W>
<W lemma="fortuna" msd="NC" tag="NOM" in="" out="">fortuna</W>
<W lemma="ci" msd="PR" tag="PRO:refl" in="" out="">ci</W>
<W lemma="capitare" msd="VADR" tag="VER:pres" in="" out="">capita</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="2:nobj">una</W>
<W lemma="solo" msd="AN" tag="ADJ" in="1:degr" out="">sola</W>
<W lemma="volta" msd="NC" tag="NOM" in="-2:nobj" out="-1:degr|1:loc">volta</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">nella</W>
<W lemma="vita" msd="NC" tag="NOM" in="-1:nobj" out="">vita</W>
<W lemma=":" msd="XP" tag="PON" in="" out="">:</W>
<W lemma="imparare" msd="VADR" tag="VER:pres" in="" out="">impariamo</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="conoscere" msd="VAF" tag="VER:infi" in="" out="">conoscere</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="mondo" msd="NC" tag="NOM" in="" out="">mondo</W>
<W lemma="così" msd="CS" tag="CON" in="" out="">così</W>
<W lemma="come" msd="PT" tag="PRO:inter" in="" out="">come</W>
<W lemma="lo" msd="PP" tag="PRO:pers" in="" out="">lo</W>
<W lemma="vedere" msd="VADR" tag="VER:pres" in="" out="">vedono</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nell'</W>
<W lemma="ambiente" msd="NC" tag="NOM" in="" out="">ambiente</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="" out="">cui</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">siamo</W>
<W lemma="nascere" msd="VAP" tag="VER:pper" in="" out="">nati</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="mentre" msd="CS" tag="CON" in="" out="">Mentre</W>
<W lemma="imparare" msd="VADR" tag="VER:pres" in="" out="">impariamo</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:vobj">a</W>
<W lemma="conoscere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">conoscere</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="mondo" msd="NC" tag="NOM" in="-1:nobj" out="">mondo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="apprendere" msd="VADR" tag="VER:pres" in="" out="2:time|5:dobj">apprendiamo</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-2:time" out="-1:pnct|1:nobj|2:pnct">nel</W>
<W lemma="contempo" msd="NC" tag="NOM" in="-1:nobj" out="">contempo</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="-5:dobj" out="3:nobj">la</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="1:attrd" out="">nostra</W>
<W lemma="primo" msd="AN" tag="ADJ" in="1:attrd" out="-1:attrd">prima</W>
<W lemma="lingua" msd="NC" tag="NOM" in="-3:nobj" out="-1:attrd">lingua</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="modo" msd="NC" tag="NOM" in="" out="">modo</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="potere" msd="VAF" tag="VER:infi" in="" out="">poterne</W>
<W lemma="successivamente" msd="RG" tag="ADV" in="" out="">successivamente</W>
<W lemma="parlare" msd="VAF" tag="VER:infi" in="" out="">parlare</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="per" msd="SP" tag="PRE" in="6:prg" out="1:nobj|2:pnct">Per</W>
<W lemma="fortuna" msd="NC" tag="NOM" in="-1:nobj" out="">fortuna</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="tutto" msd="PI" tag="PRO:indef" in="1:degr" out="">tutti</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj|7:[subj]" out="-1:degr|1:nobj">i</W>
<W lemma="neonato" msd="NC" tag="NOM" in="-1:nobj" out="">neonati</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="-6:prg|-2:subj|1:prg|2:preds|14:conj|34:pnct">sono</W>
<W lemma="normalmente" msd="RG" tag="ADV" in="-1:prg" out="">normalmente</W>
<W lemma="in" msd="SP" tag="PRE" in="-2:preds" out="1:nobj">in</W>
<W lemma="grado" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">grado</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="imparare" msd="VAF" tag="VER:infi" in="-1:vobj" out="-7:[subj]|1:dobj">imparare</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="lingua" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|2:loc">lingua</W>
<W lemma="parlare" msd="VAP" tag="VER:pper" in="-1:attrr" out="">parlata</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-2:loc" out="2:nobj">nel</W>
<W lemma="loro" msd="PO" tag="PRO:poss" in="1:attrd" out="">loro</W>
<W lemma="ambiente" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">ambiente</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="succedere" msd="VADR" tag="VER:pres" in="-14:conj" out="-2:coord|-1:neg|1:dobj">succede</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="10:vobj">che</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="3:ext" out="-1:pnct|1:nobj|2:pnct">per</W>
<W lemma="esempio" msd="NC" tag="NOM" in="-1:nobj" out="">esempio</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="5:subj|7:[subj]" out="-3:ext|1:nobj">i</W>
<W lemma="bambino" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">bambini</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Valby</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="1:robj" out="">si</W>
<W lemma="mettere" msd="VADR" tag="VER:cpre" in="-10:vobj" out="-5:subj|-1:robj|1:pobj">mettano</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="parlare" msd="VAF" tag="VER:infi" in="-1:vobj" out="-7:[subj]|1:dobj">parlare</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">una</W>
<W lemma="lingua" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|2:comp">lingua</W>
<W lemma="difficile" msd="AN" tag="ADJ" in="-1:attrr" out="">difficile</W>
<W lemma="come" msd="CS" tag="CON" in="-2:comp" out="1:nobj">come</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="finlandese" msd="AN" tag="ADJ" in="-1:nobj" out="">finlandese</W>
<W lemma="." msd="XP" tag="SENT" in="-34:pnct" out="">.</W>
