<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="9:loc" out="1:nobj|4:pnct">Alla</W>
<W lemma="fiera" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg">fiera</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj&3a;arg" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Vejle</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namel" out="">Rensch</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="3:subj|4:[subj]|8:[subj]" out="-1:namel|1:pnct|2:origin">Nielsen</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:origin" out="">Ebeltoft</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|-9:loc|1:vobj|11:pnct">ha</W>
<W lemma="indire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:dobj|3:goal">indetto</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj|19:assoc-const">un</W>
<W lemma="concorso" msd="NC" tag="NOM" in="-1:nobj" out="">concorso</W>
<W lemma="per" msd="SP" tag="PRE" in="-3:goal" out="1:vobj">per</W>
<W lemma="dare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-8:[subj]|1:dobj|3:iobj">dare</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj|6:coref-id">un</W>
<W lemma="nome" msd="NC" tag="NOM" in="-1:nobj" out="">nome</W>
<W lemma="ad" msd="SP" tag="PRE" in="-3:iobj" out="1:nobj">ad</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="gioiello" msd="NC" tag="NOM" in="-1:nobj" out="">gioiello</W>
<W lemma="." msd="XP" tag="SENT" in="-11:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-6:coref-id|3:subj|4:[subj]" out="1:nobj">Il</W>
<W lemma="nome" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">nome</W>
<W lemma="scegliere" msd="VAP" tag="VER&3a;pper" in="-1:attr" out="">scelto</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|1:vobj|8:conj">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|2:preds">stato</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:preds" out="-1:pnct|1:pnct">Personality</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="-1:pnct" out="">"</W>
<W lemma="ed" msd="CS" tag="CON" in="3:coord" out="">ed</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-19:assoc-const|2:subj|3:[subj]|4:[subj]" out="1:nobj">il</W>
<W lemma="premio" msd="NC" tag="NOM" in="-1:nobj" out="">premio</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-8:conj" out="-3:coord|-2:subj|1:vobj|8:pnct">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-3:[subj]|1:vobj">stato</W>
<W lemma="vincere" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:agent">vinto</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:agent" out="2:nobj">da</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Harald</W>
<W lemma="Jensen" msd="NP" tag="NPR" in="-2:nobj" out="-1:namef|1:pnct|2:loc">Jensen</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:loc" out="">Vejle</W>
<W lemma="." msd="XP" tag="SENT" in="-8:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="9:time" out="2:nobj">L'</W>
<W lemma="@card@" msd="AN" tag="NUM" in="1:nobj" out="">8</W>
<W lemma="settembre" msd="NC" tag="NOM" in="-2:nobj" out="-1:nobj">settembre</W>
<W lemma="a" msd="SP" tag="PRE" in="6:loc" out="1:nobj">a</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">Mosca</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="4:subj|5:[subj]" out="1:name">la</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:name" out="1:name">DE</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:name" out="1:name">BEERS</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:name" out="">CENTENARY</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-9:time|-6:loc|-4:subj|1:vobj|5:pnct|6:coref-res">ha</W>
<W lemma="aprire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-5:[subj]|1:dobj">aperto</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="2:nobj">la</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="1:attr" out="">propria</W>
<W lemma="sede" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">sede</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-6:coref-res|10:time" out="1:nobj|8:pnct">All'</W>
<W lemma="apertura" msd="NC" tag="NOM" in="-1:nobj" out="">apertura</W>
<W lemma="oltre" msd="RG" tag="ADV" in="8:add" out="1:pobj">oltre</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">ai</W>
<W lemma="vertice" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg">vertici</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:name">della</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:name" out="1:name">DE</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:name" out="">BEERS</W>
<W lemma="," msd="XP" tag="PON" in="-8:pnct" out="">,</W>
<W lemma="c'" msd="PD" tag="PRO&3a;demo" in="1:expl" out="">c'</W>
<W lemma="essere" msd="VADA" tag="VER&3a;impf" in="" out="-1:expl|-10:time|-8:add|1:dobj|15:pnct">erano</W>
<W lemma="politico" msd="NC" tag="NOM" in="-1:dobj" out="1:attr|2:pnct|3:conj|5:conj">politici</W>
<W lemma="russo" msd="AN" tag="ADJ" in="-1:attr" out="">russi</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="diplomatico" msd="NC" tag="NOM" in="-3:conj" out="">diplomatici</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="rappresentante" msd="NC" tag="NOM" in="-5:conj" out="-1:coord|1:pobj&3a;arg">rappresentanti</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:nobj|3:conj">del</W>
<W lemma="commercio" msd="NC" tag="NOM" in="-1:nobj" out="5:pobj&3a;arg">commercio</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">dell'</W>
<W lemma="industria" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">industria</W>
<W lemma="diamantifero" msd="AN" tag="ADJ" in="-1:attr" out="">diamantiferi</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-5:pobj&3a;arg" out="1:nobj">del</W>
<W lemma="paese" msd="NC" tag="NOM" in="-1:nobj" out="">paese</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
<W lemma="IB" msd="NP" tag="NPR" in="1:namef" out="">IB</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="6:subj|7:[subj]" out="-1:namef|1:pnct|2:appa">GAARN</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="orafo" msd="NC" tag="NOM" in="-2:appa" out="1:origin|3:pnct">orafo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:origin" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Køge</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-6:subj|1:vobj|13:pnct">ha</W>
<W lemma="restaurare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-7:[subj]|1:time|3:dobj">restaurato</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:time" out="1:nobj">di</W>
<W lemma="recente" msd="AN" tag="ADJ" in="-1:nobj" out="">recente</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-3:dobj" out="1:nobj|3:conj|14:coref-part">l'</W>
<W lemma="argenteria" msd="NC" tag="NOM" in="-1:nobj" out="">argenteria</W>
<W lemma="ed" msd="CS" tag="CON" in="1:coord" out="">ed</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-3:conj" out="-1:coord|1:nobj">un</W>
<W lemma="lampadario" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg">lampadario</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:nobj">della</W>
<W lemma="chiesa" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg">chiesa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj&3a;arg" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Lellinge</W>
<W lemma="." msd="XP" tag="SENT" in="-13:pnct" out="">.</W>
<W lemma="qui" msd="RG" tag="ADV" in="1:loc" out="">Qui</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="1:[subj]" out="-1:loc|1:vobj|12:pnct">è</W>
<W lemma="riprendere" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|1:accom">ripreso</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:accom" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-14:coref-part|-1:nobj" out="1:nobj|3:pnct|4:appa">il</W>
<W lemma="calice" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">calice</W>
<W lemma="restaurare" msd="VAP" tag="VER&3a;pper" in="-1:attr" out="">restaurato</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="un'" msd="PI" tag="DET&3a;indef" in="-4:appa" out="1:nobj">un'</W>
<W lemma="antichità" msd="NC" tag="NOM" in="-1:nobj" out="">antichità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">300</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
<W lemma="(" msd="XP" tag="PON" in="1:pnct" out="">(</W>
<W lemma="foto" msd="NC" tag="NOM" in="" out="-1:pnct|1:pnct|3:other|4:pnct|5:pnct">Foto</W>
<W lemma="&3a;" msd="XP" tag="PON" in="-1:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Stig</W>
<W lemma="Hansen" msd="NP" tag="NPR" in="-3:other" out="-1:namef">Hansen</W>
<W lemma=")" msd="XP" tag="PON" in="-4:pnct" out="">)</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
<W lemma="henry" msd="NC" tag="NOM" in="1:namef" out="">HENRY</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="6:subj|7:[subj]" out="-1:namef|1:pnct|3:title|21:coref">HEERUP</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="famoso" msd="AN" tag="ADJ" in="1:attr" out="">famoso</W>
<W lemma="artista" msd="NC" tag="NOM" in="-3:title" out="-1:attr|1:attr|2:pnct">artista</W>
<W lemma="figurativo" msd="AN" tag="ADJ" in="-1:attr" out="">figurativo</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-6:subj|1:vobj|12:pnct">ha</W>
<W lemma="disegnare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-7:[subj]|1:dobj|7:ben">disegnato</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="gioiello" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;iden|3:pobj&3a;func">gioiello</W>
<W lemma="d'" msd="SP" tag="PRE" in="-1:pobj&3a;iden" out="1:nobj">d'</W>
<W lemma="arte" msd="NC" tag="NOM" in="-1:nobj" out="">arte</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-3:pobj&3a;func" out="1:nobj">dell'</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anno</W>
<W lemma="per" msd="SP" tag="PRE" in="-7:ben" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|2:appr">la</W>
<W lemma="catena" msd="NC" tag="NOM" in="-1:nobj" out="">catena</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:appr" out="">Smykkekæden</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="7:pnct|1:preds">È</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:preds" out="1:possr&3a;subj|3:nobj">la</W>
<W lemma="suo" msd="PO" tag="PRO&3a;poss" in="-21:coref|-1:possr&3a;subj" out="">sua</W>
<W lemma="primo" msd="AN" tag="ADJ" in="1:attr" out="">prima</W>
<W lemma="opera" msd="NC" tag="NOM" in="-3:nobj" out="-1:attr|1:pobj&3a;const">opera</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:pobj&3a;const" out="1:nobj">in</W>
<W lemma="argento" msd="NC" tag="NOM" in="-1:nobj" out="">argento</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="francobollo" msd="NC" tag="NOM" in="" out="1:attr">Francobolli</W>
<W lemma="commemorativo" msd="AN" tag="ADJ" in="-1:attr" out="">commemorativi</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="5:subj" out="1:nobj">L'</W>
<W lemma="industria" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">industria</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attr" out="2:conj">orafa</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="orologiaio" msd="NC" tag="NOM" in="-2:conj" out="-1:coord">orologiaia</W>
<W lemma="compiere" msd="VADR" tag="VER&3a;pres" in="" out="-5:subj|1:dobj|3:loc|5:pnct|10:coref-res">compie</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:dobj" out="1:nobj">225</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="a" msd="SP" tag="PRE" in="-3:loc" out="1:nobj">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="11:assoc-loc">Pforzheim</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
<W lemma="fra" msd="SP" tag="PRE" in="6:exem" out="1:nobj|3:pnct">Fra</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:attr">gli</W>
<W lemma="altro" msd="AN" tag="ADJ" in="-1:attr" out="">altri</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-10:coref-res|2:subj|3:[subj]|4:[subj]" out="1:nobj">il</W>
<W lemma="giubileo" msd="NC" tag="NOM" in="-1:nobj" out="">giubileo</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|-6:exem|1:vobj|15:pnct">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-3:[subj]|1:vobj">stato</W>
<W lemma="celebrare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:agent|3:man">celebrato</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-11:assoc-loc|-1:agent" out="1:nobj">dalle</W>
<W lemma="posta" msd="NC" tag="NOM" in="-1:nobj" out="">poste</W>
<W lemma="con" msd="SP" tag="PRE" in="-3:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="pubblicazione" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;dobj">pubblicazione</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj&3a;dobj" out="1:nobj">di</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj|10:assoc-other|16:²coref-part">100</W>
<W lemma="francobollo" msd="NC" tag="NOM" in="-1:nobj" out="1:accom">francobolli</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:accom" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|2:appr">la</W>
<W lemma="moneta" msd="NC" tag="NOM" in="-1:nobj" out="">moneta</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:appr" out="">Pfennig</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
<W lemma="fino" msd="CS" tag="CON" in="8:dur" out="1:pobj|5:pnct">Fino</W>
<W lemma="ad" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">ad</W>
<W lemma="esaurimento" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;subj">esaurimento</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;subj|-10:assoc-other" out="1:nobj">della</W>
<W lemma="tiratura" msd="NC" tag="NOM" in="-1:nobj" out="">tiratura</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj|3:[subj]" out="1:attr">gli</W>
<W lemma="interessato" msd="AN" tag="ADJ" in="-1:attr" out="">interessati</W>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|-8:dur|1:¹vobj|19:pnct">possono</W>
<W compound="¹ricever²ne" lemma="ricevere" msd="VAF" tag="VER&3a;infi" in="-1:¹vobj|-16:²coref-part" out="-3:[subj]|1:dobj|7:man">riceverne</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="esemplare" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">esemplare</W>
<W lemma="timbrare" msd="VAP" tag="VER&3a;pper" in="-1:attr" out="1:accom">timbrato</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:accom" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="data" msd="NC" tag="NOM" in="-1:nobj" out="">data</W>
<W lemma="rivolgere" msd="VAG" tag="VER&3a;geru" in="-7:man" out="1:pobj">rivolgendosi</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="1:nobj|2:pnct|3:other">Ständige</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">Musterausstellung</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:other" out="1:other|2:pnct|3:other">Poststrasse</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:other" out="">1</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:other" out="1:pnct|2:other">W-7530</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:other" out="">Pforzheim</W>
<W lemma="." msd="XP" tag="SENT" in="-19:pnct" out="">.</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="1:attr" out="">Nuovi</W>
<W lemma="orefice" msd="NC" tag="NOM" in="" out="-1:attr">orefici</W>
<W lemma="due" msd="AN" tag="ADJ" in="4:subj|5:[subj]|6:[subj]" out="1:nobj|11:assoc-agent">Due</W>
<W lemma="esame" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;func">esami</W>
<W lemma="d'" msd="SP" tag="PRE" in="-1:pobj&3a;func" out="1:nobj">d'</W>
<W lemma="apprendistato" msd="NC" tag="NOM" in="-1:nobj" out="">apprendistato</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="" out="-4:subj|1:vobj|3:time|5:pnct">sono</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-5:[subj]|1:vobj">stati</W>
<W lemma="superare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-6:[subj]">superati</W>
<W lemma="in" msd="SP" tag="PRE" in="-3:time" out="1:nobj">in</W>
<W lemma="agosto" msd="NC" tag="NOM" in="-1:nobj" out="">agosto</W>
<W lemma="." msd="XP" tag="SENT" in="-5:pnct" out="">.</W>
<W lemma="entrambi" msd="AN" tag="ADJ" in="1:degr" out="">Entrambi</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-11:assoc-agent|3:subj|4:[subj]" out="-1:degr|1:nobj">gli</W>
<W lemma="apprendista" msd="NC" tag="NOM" in="-1:nobj" out="">apprendisti</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="2:robj" out="">si</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|1:vobj|2:loc|10:pnct">sono</W>
<W lemma="formare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|-2:robj">formati</W>
<W lemma="presso" msd="SP" tag="PRE" in="-2:loc" out="1:nobj">presso</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="2:nobj|5:other">la</W>
<W lemma="Royal" msd="NP" tag="NPR" in="1:attr" out="">Royal</W>
<W lemma="Copenhagen" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr|1:nobj">Copenhagen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">A/S</W>
<W lemma="Georg" msd="NP" tag="NPR" in="1:namef" out="">Georg</W>
<W lemma="Jensen" msd="NP" tag="NPR" in="-5:other" out="-1:namef|1:nobj">Jensen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Sølvsmedie</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W lemma="congratulazione" msd="NC" tag="NOM" in="" out="1:ben|12:pnct">Congratulazioni</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:ben" out="1:nobj|6:conj">all'</W>
<W lemma="orafo" msd="NC" tag="NOM" in="-1:nobj" out="3:appr">orafo</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="2:namef" out="">LYKKE</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:namel" out="">ELKJÆR</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:appr" out="-2:namef|-1:namel">OLSEN</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-6:conj" out="-1:coord|1:nobj">all'</W>
<W lemma="argentiere" msd="NC" tag="NOM" in="-1:nobj" out="3:appr">argentiere</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="2:namef" out="">GITTE</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namel" out="">TOFTESKOV</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:appr" out="-2:namef|-1:namel">RASMUSSEN</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
