<W lemma="il" msd="PD" tag="DET:def" in="5:subj|6:[subj]" out="1:nobj">Il</W>
<W lemma="gruppo" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:arg#">gruppo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:arg#" out="1:nobj">di</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="">lavoro</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="1:robj" out="">si</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-5:subj|-1:robj|1:vobj|17:pnct|22:pnct">deve</W>
<W lemma="basare" msd="VAF" tag="VER:infi" in="-1:vobj" out="-6:[subj]|1:pobj">basare</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj|3:pnct|4:conj|7:conj|17:coref|21:coref-var">sulla</W>
<W lemma="rete" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|8:attrr|15:appa">rete</W>
<W lemma="operativo" msd="AN" tag="ADJ" in="-1:attrr" out="">operativa</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="-4:conj" out="1:nobj">i</W>
<W lemma="medicinale" msd="NC" tag="NOM" in="-1:nobj" out="">medicinali</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="-7:conj" out="-1:coord|1:nobj">le</W>
<W lemma="scorta" msd="NC" tag="NOM" in="-1:nobj" out="">scorte</W>
<W lemma="a" msd="SP" tag="PRE" in="-8:attrr" out="1:nobj">a</W>
<W lemma="disposizione" msd="NC" tag="NOM" in="-1:nobj" out="1:time">disposizione</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:time" out="1:nobj">in</W>
<W lemma="periodo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">periodo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="pace" msd="NC" tag="NOM" in="-1:nobj" out="">pace</W>
<W lemma="," msd="XP" tag="PON" in="-17:pnct" out="">,</W>
<W lemma="includere" msd="VAP" tag="VER:pper" in="-15:appa" out="1:subj">inclusi</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:subj|-17:coref" out="1:attrr">quelli</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">della</W>
<W lemma="difesa" msd="NC" tag="NOM" in="-1:nobj" out="">Difesa</W>
<W lemma="." msd="XP" tag="SENT" in="-22:pnct" out="">.</W>
<W lemma="tale" msd="PD" tag="PRO:demo" in="-21:coref-var|10:subj|3:[subj]|11:[subj]" out="1:nobj|2:pnct">Tali</W>
<W lemma="strumento" msd="NC" tag="NOM" in="-1:nobj" out="2:appa">strumenti</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="rendere" msd="VAP" tag="VER:pper" in="-2:appa" out="6:pnct|-3:[subj]|1:preds">resi</W>
<W lemma="efficiente" msd="AN" tag="ADJ" in="-1:preds" out="1:bg">efficienti</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:bg" out="1:nobj">per</W>
<W lemma="condizione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr#">condizioni</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr#" out="1:nobj">di</W>
<W lemma="guerra" msd="NC" tag="NOM" in="-1:nobj" out="">guerra</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-10:subj|1:vobj">devono</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="-11:[subj]|1:preds">essere</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:preds" out="1:nobj">in</W>
<W lemma="grado" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">grado</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="coprire" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">coprire</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="2:nobj">un</W>
<W lemma="breve" msd="AN" tag="ADJ" in="1:attrd" out="">breve</W>
<W lemma="fase" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:attrr|2:attrr">fase</W>
<W lemma="preliminare" msd="AN" tag="ADJ" in="-1:attrr" out="">preliminare</W>
<W lemma="di" msd="SP" tag="PRE" in="-2:attrr" out="2:nobj">di</W>
<W lemma="circa" msd="RG" tag="ADV" in="1:degr" out="">circa</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-2:nobj" out="-1:degr|1:conj|2:nobj">una</W>
<W lemma="due" msd="AN" tag="ADJ" in="-1:conj" out="">due</W>
<W lemma="settimana" msd="NC" tag="NOM" in="-2:nobj" out="">settimane</W>
<W lemma="oltre" msd="CS" tag="CON" in="" out="">oltre</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="circa" msd="RG" tag="ADV" in="" out="">circa</W>
<W lemma="due" msd="AN" tag="ADJ" in="" out="">due</W>
<W lemma="settimana" msd="NC" tag="NOM" in="" out="">settimane</W>
<W lemma="seguente" msd="AN" tag="ADJ" in="" out="">seguenti</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alle</W>
<W lemma="vero" msd="AN" tag="ADJ" in="" out="">vere</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="" out="">proprie</W>
<W lemma="azione" msd="NC" tag="NOM" in="" out="">azioni</W>
<W lemma="bellico" msd="AN" tag="ADJ" in="" out="">belliche</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="circa" msd="RG" tag="ADV" in="" out="">circa</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">30</W>
<W lemma="giorno" msd="NC" tag="NOM" in="" out="">giorni</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">Il</W>
<W lemma="gruppo" msd="NC" tag="NOM" in="" out="">gruppo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="" out="">lavoro</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="">deve</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="altro" msd="PI" tag="PRO:indef" in="" out="">altro</W>
<W lemma="aggiornare" msd="VAF" tag="VER:infi" in="" out="">aggiornare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="lista" msd="NC" tag="NOM" in="" out="">liste</W>
<W lemma="attuale" msd="AN" tag="ADJ" in="" out="">attuali</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="medicinale" msd="NC" tag="NOM" in="" out="">medicinali</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="mezza|mezzo" msd="NC" tag="NOM" in="" out="">mezzi</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="utilizzare" msd="VAF" tag="VER:infi" in="" out="">utilizzarsi</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nel</W>
<W lemma="sistema" msd="NC" tag="NOM" in="" out="">sistema</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="pronto" msd="AN" tag="ADJ" in="" out="">pronto</W>
<W lemma="intervento" msd="NC" tag="NOM" in="" out="">intervento</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="situazione" msd="NC" tag="NOM" in="" out="">situazioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="crisi" msd="NC" tag="NOM" in="" out="">crisi</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="senza" msd="SP" tag="PRE" in="" out="">senza</W>
<W lemma="tralasciare" msd="VAF" tag="VER:infi" in="" out="">tralasciare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="variabile" msd="NC" tag="NOM" in="" out="">variabili</W>
<W lemma="geografico" msd="AN" tag="ADJ" in="" out="">geografiche</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="indagare" msd="VAF" tag="VER:infi" in="" out="">indagare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="possibilità" msd="NC" tag="NOM" in="" out="">possibilità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="aumentare" msd="VAF" tag="VER:infi" in="" out="">aumentarne</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="produzione" msd="NC" tag="NOM" in="" out="">produzione</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">La</W>
<W lemma="situazione" msd="NC" tag="NOM" in="" out="">situazione</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="crisi" msd="NC" tag="NOM" in="" out="">crisi</W>
<W lemma="potere" msd="VADR" tag="VER:pres" in="" out="">può</W>
<W lemma="rapidamente" msd="RG" tag="ADV" in="" out="">rapidamente</W>
<W lemma="spargere" msd="VAF" tag="VER:infi" in="" out="">spargersi</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nel</W>
<W lemma="paese" msd="NC" tag="NOM" in="" out="">paese</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="coinvolgere" msd="VAG" tag="VER:geru" in="" out="">coinvolgendo</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="sistema" msd="NC" tag="NOM" in="" out="">sistema</W>
<W lemma="ospedaliero" msd="AN" tag="ADJ" in="" out="">ospedaliero</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="servizio" msd="NC" tag="NOM" in="" out="">servizio</W>
<W lemma="sanitario" msd="AN" tag="ADJ" in="" out="">sanitario</W>
<W lemma=";" msd="XP" tag="PON" in="" out="">;</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="dovere" msd="VADR" tag="VER:futu" in="" out="">dovrà</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="altro" msd="PI" tag="PRO:indef" in="" out="">altro</W>
<W lemma="articolare" msd="VAF" tag="VER:infi" in="" out="">articolare</W>
<W lemma="adeguatamente" msd="RG" tag="ADV" in="" out="">adeguatamente</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="collaborazione" msd="NC" tag="NOM" in="" out="">collaborazione</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="autorità" msd="NC" tag="NOM" in="" out="">autorità</W>
<W lemma="centrale" msd="AN" tag="ADJ" in="" out="">centrali</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="statale" msd="AN" tag="ADJ" in="" out="">statali</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="provinciale" msd="AN" tag="ADJ" in="" out="">provinciali</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="comunale" msd="AN" tag="ADJ" in="" out="">comunali</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="produttore" msd="NC" tag="NOM" in="" out="">produttori</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="medicinale" msd="NC" tag="NOM" in="" out="">medicinali</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="distributore" msd="NC" tag="NOM" in="" out="">distributori</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">Il</W>
<W lemma="ministero" msd="NC" tag="NOM" in="" out="">Ministero</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="interno" msd="NC" tag="NOM" in="" out="">Interni</W>
<W lemma="prevedere" msd="VADR" tag="VER:pres" in="" out="">prevede</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">questa</W>
<W lemma="parte" msd="NC" tag="NOM" in="" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dell'</W>
<W lemma="impegno" msd="NC" tag="NOM" in="" out="">impegno</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="gruppo" msd="NC" tag="NOM" in="" out="">gruppo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="" out="">lavoro</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="concludere" msd="VADR" tag="VER:cpre" in="" out="">concluda</W>
<W lemma="prima" msd="RG" tag="ADV" in="" out="">prima</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1</W>
<W lemma="giugno" msd="NC" tag="NOM" in="" out="">giugno</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1984</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="subito" msd="RG" tag="ADV" in="" out="">Subito</W>
<W lemma="dopo" msd="RG" tag="ADV" in="" out="">dopo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="ministero" msd="NC" tag="NOM" in="" out="">Ministero</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="difesa" msd="NC" tag="NOM" in="" out="">Difesa</W>
<W lemma="civile" msd="AN" tag="ADJ" in="" out="">civile</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="direzione" msd="NC" tag="NOM" in="" out="">Direzione</W>
<W lemma="generale" msd="AN" tag="ADJ" in="" out="">generale</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="servizio" msd="NC" tag="NOM" in="" out="">servizio</W>
<W lemma="sanitario" msd="AN" tag="ADJ" in="" out="">sanitario</W>
<W lemma="valutare" msd="VADR" tag="VER:futu" in="" out="">valuteranno</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="eventualità" msd="NC" tag="NOM" in="" out="">eventualità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="fare" msd="VAF" tag="VER:infi" in="" out="">far</W>
<W lemma="proseguire" msd="VAF" tag="VER:infi" in="" out="">proseguire</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="lavorio|lavoro" msd="NC" tag="NOM" in="" out="">lavori</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="creare" msd="VAG" tag="VER:geru" in="" out="">creando</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="sistema" msd="NC" tag="NOM" in="" out="">sistema</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="pronto" msd="AN" tag="ADJ" in="" out="">pronto</W>
<W lemma="intervento" msd="NC" tag="NOM" in="" out="">intervento</W>
<W lemma="medico" msd="AN" tag="ADJ" in="" out="">medico</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="essere" msd="VADR" tag="VER:cpre" in="" out="">sia</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="funzione" msd="NC" tag="NOM" in="" out="">funzione</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="fuori" msd="RG" tag="ADV" in="" out="">fuori</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="tempo" msd="NC" tag="NOM" in="" out="">tempi</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="presupposto" msd="NC" tag="NOM" in="" out="">presupposti</W>
<W lemma="sopraindicato" msd="AN" tag="ADJ" in="" out="">sopraindicati</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
