<W id="0" lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:neg" out="">“Nemmeno</W>
<W id="1" lemma="io" msd="PP" tag="PRO&3a;pers" in="7:coref" out="-1:neg|1:pnct|2:CONJ/ATTR1">io</W>
<W id="2" lemma="." msd="XP" tag="SENT" in="-1:pnct" out="">.</W>
<W id="3" lemma="andare" msd="VADR" tag="VER&3a;pres" in="4:qobj|-2:CONJ/ATTR1" out="1:@dir">Andiamo</W>
<W id="4" lemma="a" msd="SP" tag="PRE" in="-1:@dir" out="2:nobj">a</W>
<W id="5" lemma="casa" msd="NC" tag="NOM" in="1:possd" out="1:{poss}">casa</W>
<W id="6" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:{poss}|-2:nobj" out="-1:possd">tua”</W>
<W id="7" lemma="dire" msd="VADA" tag="VER&3a;remo" in="" out="-4:qobj|1:subj|2:pnct">disse</W>
<W id="8" lemma="lei" msd="PP" tag="PRO&3a;pers" in="-1:subj" out="-7:coref|2:*coref|2:+FORMAL&3a;eval">lei</W>
<W id="9" lemma="." msd="XP" tag="SENT" in="-2:pnct" out="">.</W>
<W id="10" lemma="era" msd="NC" tag="NOM" in="-2:*coref|-2:+FORMAL&3a;eval" out="1:preds|5:¹coref|7:pnct|10:CONJ&3a;elab&7c;CONST&3a;exem/(per_esempio)">Era</W>
<W id="11" lemma="diverso" msd="AN" tag="ADJ" in="-1:preds" out="1:pobj">diversa</W>
<W id="12" lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">da</W>
<W id="13" lemma="come" msd="SP" tag="PRE" in="-1:nobj" out="2:vobj">come</W>
<W id="14" lemma="me" msd="PP" tag="PRO&3a;pers" in="1:coref*$|2:robj" out="">me</W>
<W compound="¹l’²ero" id="15" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:vobj|-5:¹coref|1:¹dobj" out="-1:coref*$|1:preds|5:*coref¹|10:*coref²">l’ero</W>
<W id="16" lemma="immaginare" msd="VAP" tag="VER&3a;pper" in="-1:preds" out="-2:robj|-1:¹dobj">immaginata</W>
<W id="17" lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W id="18" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="2:loc" out="1:nobj">Nel</W>
<W id="19" lemma="taxi" msd="NC" tag="NOM" in="-1:nobj" out="">taxi</W>
<W id="20" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-5:*coref¹|14:*[subj]|-10:CONJ&3a;elab&7c;CONST&3a;exem/(per_esempio)" out="-2:loc|1:dobj|2:*coref|4:@dir|14:conj|21:pnct|22:+CONJ/ATTR2">appoggiò</W>
<W id="21" lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">il</W>
<W id="22" lemma="suo" msd="PO" tag="PRO&3a;poss" in="-1:nobj|-2:*coref|1:{const}" out="1:possd|51:*coref">suo</W>
<W id="23" lemma="capo" msd="NC" tag="NOM" in="-1:possd" out="-1:{const}">capo</W>
<W id="24" lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-4:@dir" out="1:nobj">sulla</W>
<W id="25" lemma="mio" msd="PO" tag="PRO&3a;poss" in="-1:nobj|-10:*coref²|1:{const}" out="1:possd">mia</W>
<W id="26" lemma="spalla" msd="NC" tag="NOM" in="-1:possd" out="-1:{const}">spalla</W>
<W id="27" lemma="e" msd="CS" tag="CON" in="7:coord" out="">e</W>
<W id="28" lemma="mentre" msd="CS" tag="CON" in="6:time" out="1:vobj">mentre</W>
<W _noerror="&3a;nosubj&3a;" id="29" lemma="salire" msd="VADA" tag="VER&3a;impf" in="-1:vobj" out="1:dobj|3:iter|13:$*coref">salivamo</W>
<W id="30" lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">le</W>
<W id="31" lemma="scala" msd="NC" tag="NOM" in="-1:nobj" out="">scale</W>
<W id="32" lemma="di" msd="SP" tag="PRE" in="-3:iter" out="1:nobj">di</W>
<W id="33" lemma="nuovo" msd="AN" tag="ADJ" in="-1:nobj" out="">nuovo</W>
<W id="34" lemma="dire" msd="VADA" tag="VER&3a;remo" in="-14:conj" out="-7:coord|-6:time|-14:*[subj]|1:dobj">disse</W>
<W id="35" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="4:vobj">che</W>
<W id="36" lemma="il" msd="PD" tag="DET&3a;def" in="3:subj" out="1:nobj">le</W>
<W id="37" lemma="cosa" msd="NC" tag="NOM" in="-1:nobj" out="">cose</W>
<W id="38" lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W id="39" lemma="stare" msd="VADA" tag="VER&3a;impf" in="-4:vobj" out="-1:neg|-3:subj|1:preds">stavano</W>
<W id="40" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:preds" out="">così</W>
<W id="41" lemma="." msd="XP" tag="SENT" in="-21:pnct" out="">.</W>
<W id="42" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-13:$*coref|15:*[subj]|-22:+CONJ/ATTR2" out="1:preds|23:pnct|26:QUEST/ATTR2">“Siamo</W>
<W id="43" lemma="due" msd="AN" tag="ADJ" in="-1:preds" out="1:nobj|2:ref|7:relr">due</W>
<W id="44" lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="">persone</W>
<W id="45" lemma="che" msd="PT" tag="PRO&3a;rela" in="-2:ref|5:subj|6:[subj]" out="6:²coref">che</W>
<W id="46" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="4:time" out="1:nobj">nel</W>
<W id="47" lemma="pieno" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj|1:{arg}">pieno</W>
<W id="48" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj|-1:{arg}" out="1:nobj">della</W>
<W id="49" lemma="notte" msd="NC" tag="NOM" in="-1:nobj" out="">notte</W>
<W id="50" lemma="camminare" msd="VADR" tag="VER&3a;pres" in="-7:relr" out="-4:time|-5:subj|1:concom|17:coref-res">camminano</W>
<W id="51" lemma="scusare" msd="VAG" tag="VER&3a;geru" in="-1:concom|-6:²coref" out="-6:[subj]|1:iter|2:resem">scusandosi</W>
<W id="52" lemma="ripetutamente" msd="RG" tag="ADV" in="-1:iter" out="">ripetutamente</W>
<W id="53" lemma="come" msd="CS" tag="CON" in="-2:resem" out="1:nobj#">come</W>
<W id="54" lemma="se" msd="CS" tag="CON" in="-1:nobj#" out="5:vobj">se</W>
<W id="55" lemma="quello" msd="PD" tag="PRO&3a;demo" in="4:subj" out="1:ref|2:relr">quello</W>
<W id="56" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:ref|1:dobj" out="">che</W>
<W id="57" lemma="stare" msd="VADA" tag="VER&3a;cimp" in="-2:relr|1:[subj]" out="-1:dobj|-15:*[subj]|1:vobj|11:*coref">stessimo</W>
<W id="58" lemma="fare" msd="VAG" tag="VER&3a;geru" in="-1:vobj" out="-1:[subj]">facendo</W>
<W id="59" lemma="essere" msd="VADA" tag="VER&3a;cimp" in="-5:vobj" out="-4:subj|1:preds">fosse</W>
<W id="60" lemma="qualcosa" msd="PI" tag="PRO&3a;indef" in="-1:preds" out="1:attr">qualcosa</W>
<W id="61" lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W id="62" lemma="segreto" msd="NC" tag="NOM" in="-1:nobj" out="2:conj">segreto</W>
<W id="63" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="64" lemma="proibito" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">proibito</W>
<W id="65" lemma="." msd="XP" tag="SENT" in="-23:pnct" out="">.</W>
<W id="66" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:cause" out="">Perché</W>
<W id="67" lemma="lo" msd="PP" tag="PRO&3a;pers" in="-17:coref-res|1:dobj" out="3:coref">lo</W>
<W id="68" lemma="fare" msd="VADR" tag="VER&3a;cpre" in="-11:*coref|-26:QUEST/ATTR2" out="-1:dobj|-2:cause|1:pnct|3:*coref|5:+ANSW/ATTR1*">facciamo</W>
<W id="69" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:pnct" out="">?”</W>
<W id="70" lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-3:coref|1:dobj" out="">“Lo</W>
<W id="71" lemma="fare" msd="VADR" tag="VER&3a;cpre" in="-3:*coref|2:qobj" out="-1:dobj|1:pnct|20:*coref">facciamo</W>
<W id="72" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:pnct" out="">?”</W>
<W id="73" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-51:*coref|-5:+ANSW/ATTR1*" out="-2:qobj|1:pnct|31:*coref|5:CONJ">domandò</W>
<W id="74" lemma="." msd="XP" tag="SENT" in="-1:pnct" out="">.</W>
<W id="75" lemma="a" msd="SP" tag="PRE" in="3:loc" out="1:nobj">A</W>
<W id="76" lemma="letto" msd="NC" tag="NOM" in="-1:nobj" out="">letto</W>
<W id="77" lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W id="78" lemma="accadere" msd="VADA" tag="VER&3a;remo" in="-5:CONJ" out="-1:neg|-3:loc|1:subj|2:pnct|5:conj|6:pnct|13:CONJ&3a;elab">accadde</W>
<W id="79" lemma="nullo" msd="AN" tag="ADJ" in="-1:subj" out="">nulla</W>
<W id="80" lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W id="81" lemma="ma" msd="CS" tag="CON" in="2:coord" out="">ma</W>
<W id="82" lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W id="83" lemma="importare" msd="VADA" tag="VER&3a;impf" in="-5:conj" out="-2:coord|-1:neg">importava</W>
<W id="84" lemma="." msd="XP" tag="SENT" in="-6:pnct" out="">.</W>
<W id="85" lemma="nudo" msd="AN" tag="ADJ" in="6:fpreds" out="">Nudi</W>
<W id="86" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="87" lemma="uno" msd="PI" tag="DET&3a;indef" in="4:man" out="-1:pnct|1:attr|1:{loc}|3:pnct">uno</W>
<W id="88" lemma="vicino" msd="AN" tag="ADJ" in="-1:attr|-1:{loc}" out="1:pobj">vicino</W>
<W id="89" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:pobj" out="">all’altra</W>
<W id="90" lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W id="91" lemma="chiacchierare" msd="VADA" tag="VER&3a;impf" in="-20:*coref|2:*[subj]|-13:CONJ&3a;elab" out="-6:fpreds|-4:man|2:conj|6:pnct|13:+CONJ&3a;elab/ATTR1*">chiacchieravamo</W>
<W id="92" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="93" lemma="bere" msd="VADA" tag="VER&3a;impf" in="-2:conj" out="-1:coord|-2:*[subj]|1:dobj">bevevamo</W>
<W id="94" lemma="te" msd="PP" tag="PRO&3a;pers" in="-1:dobj" out="2:conj">te</W>
<W id="95" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="96" lemma="porto" msd="NC" tag="NOM" in="-2:conj" out="-1:coord">porto</W>
<W id="97" lemma="." msd="XP" tag="SENT" in="-6:pnct" out="">.</W>
<W id="98" lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:time" out="">“Prima</W>
<W id="99" lemma="passare" msd="VADA" tag="VER&3a;impf" in="5:qobj" out="-1:time|1:@dir|5:[subj]*|7:conj|19:coref-res">passavo</W>
<W id="100" lemma="da" msd="SP" tag="PRE" in="-1:@dir" out="1:nobj|3:pobj">da</W>
<W id="101" lemma="un" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">un</W>
<W id="102" lemma="uomo" msd="NC" tag="NOM" in="-1:nobj" out="">uomo</W>
<W id="103" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:pobj" out="">all’altro”</W>
<W id="104" lemma="dire" msd="VADA" tag="VER&3a;remo" in="-31:*coref|-5:[subj]*|2:*[subj]|10:*[subj]|-13:+CONJ&3a;elab/ATTR1*" out="-5:qobj|1:pnct|17:pnct">disse</W>
<W id="105" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="106" lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-7:conj" out="-2:*[subj]|1:iter|2:dobj|5:time|16:CONJ&3a;add/(e)/ATTR1">“avevo</W>
<W id="107" lemma="sempre" msd="RG" tag="ADV" in="-1:iter" out="">sempre</W>
<W id="108" lemma="qualcuno" msd="PI" tag="PRO&3a;indef" in="-2:dobj" out="1:attr|1:{loc}">qualcuno</W>
<W id="109" lemma="in" msd="SP" tag="PRE" in="-1:attr|-1:{loc}" out="1:nobj">in</W>
<W id="110" lemma="menta&7c;mente" msd="NC" tag="NOM" in="-1:nobj" out="">mente</W>
<W id="111" lemma="fino" msd="CS" tag="CON" in="-5:time" out="1:pobj">fino</W>
<W id="112" lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">a</W>
<W id="113" lemma="quando" msd="PT" tag="PRO&3a;inter" in="-1:nobj" out="1:vobj">quando</W>
<W _noerror="&3a;nosubj&3a;" id="114" lemma="capire" msd="VADA" tag="VER&3a;remo" in="-1:vobj" out="-10:*[subj]|1:dobj|8:*coref">capii</W>
<W id="115" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="2:vobj">che</W>
<W id="116" lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W id="117" lemma="essere" msd="VADA" tag="VER&3a;impf" in="-2:vobj" out="-1:neg|1:subj|2:preds">era</W>
<W id="118" lemma="quello" msd="PD" tag="PRO&3a;demo" in="-1:subj|-19:coref-res" out="">quello</W>
<W id="119" lemma="il" msd="PD" tag="DET&3a;def" in="-2:preds" out="1:nobj">il</W>
<W id="120" lemma="punto" msd="NC" tag="NOM" in="-1:nobj" out="">punto</W>
<W id="121" lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W id="122" lemma="credere" msd="VADA" tag="VER&3a;impf" in="-8:*coref|3:*[subj]|-16:CONJ&3a;add/(e)/ATTR1" out="1:dobj">Credevo</W>
<W id="123" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="17:vobj">che</W>
<W id="124" lemma="se" msd="CS" tag="CON" in="16:xtop" out="1:vobj|14:ref">se</W>
<W _noerror="&3a;nosubj&3a;" id="125" lemma="essere" msd="VADA" tag="VER&3a;cimp" in="-1:vobj|3:[subj]" out="-3:*[subj]|1:preds|11:*coref|12:pnct">fossi</W>
<W id="126" lemma="riuscire" msd="VAP" tag="VER&3a;pper" in="-1:preds" out="1:pobj">riuscita</W>
<W id="127" lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W id="128" lemma="fare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-3:[subj]|1:pobj">far</W>
<W id="129" lemma="in" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">in</W>
<W id="130" lemma="modo" msd="NC" tag="NOM" in="-1:nobj" out="1:dobj">modo</W>
<W id="131" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="3:vobj">che</W>
<W id="132" lemma="un" msd="PI" tag="DET&3a;indef" in="2:subj" out="1:nobj">un</W>
<W id="133" lemma="uomo" msd="NC" tag="NOM" in="-1:nobj" out="">uomo</W>
<W id="134" lemma="stesso" msd="AN" tag="ADJ" in="-3:vobj" out="-2:subj|1:accom">stesse</W>
<W id="135" lemma="con" msd="SP" tag="PRE" in="-1:accom" out="1:nobj">con</W>
<W id="136" lemma="me" msd="PP" tag="PRO&3a;pers" in="-1:nobj|-11:*coref" out="">me</W>
<W id="137" lemma="," msd="XP" tag="PON" in="-12:pnct" out="">,</W>
<W id="138" lemma="allora" msd="RG" tag="ADV" in="-14:ref|2:cons" out="">allora</W>
<W id="139" lemma="tutto" msd="PI" tag="PRO&3a;indef" in="1:subj|2:[subj]" out="">tutto</W>
<W id="140" lemma="essere" msd="VA" tag="VER&3a;cond" in="-17:vobj" out="-1:subj|-16:xtop|-2:cons|1:vobj">sarebbe</W>
<W id="141" lemma="andare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-2:[subj]|1:preds">andato</W>
<W id="142" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:preds" out="">bene.”</W>
