<W lemma="Thomas" msd="NP" tag="NPR" in="1:namef" out="">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:subj|2:[subj]|3:[subj]" out="-1:namef">Stuer</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="-1:subj|1:vobj|5:iobj|10:conj|20:pnct">ha</W>
<W lemma="dovere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:vobj|-2:[subj]">dovuto</W>
<W lemma="cedere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj|-3:[subj]">cedere</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="set" msd="NC" tag="NOM" in="-1:nobj" out="">set</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-5:iobj" out="1:nobj">al</W>
<W lemma="coreano" msd="AN" tag="ADJ" in="-1:nobj" out="2:appr">coreano</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:namef" out="">Lee</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:appr" out="-1:namef">Kwan-Jin</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="-10:conj" out="-1:pnct|1:loc">ma</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">nei</W>
<W lemma="quarto" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj#">quarti</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj#" out="1:nobj">di</W>
<W lemma="finale" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">finale</W>
<W lemma="contro" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">contro</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="cinese" msd="AN" tag="ADJ" in="-1:nobj" out="2:appr">cinese</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Wan</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:appr" out="-1:namef">Shengwen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-20:pnct" out="">:&lt;&lt;</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:[subj]" out="1:vobj|26:pnct|7:conj">Ho</W>
<W lemma="vinto" msd="NC" tag="NOM" in="-1:vobj" out="1:dobj|-1:[subj]">vinto</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:dobj" out="2:conj">15-9</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:conj" out="-1:pnct">15-8</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="1:coord" out="-1:pnct">ma</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="-7:conj" out="2:preds|13:time|-1:coord">ero</W>
<W lemma="fortemente" msd="RG" tag="ADV" in="1:man" out="">fortemente</W>
<W lemma="indietro" msd="RG" tag="ADV" in="-2:preds" out="-1:man|1:loc|6:elab">indietro</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="2:nobj">in</W>
<W lemma="entrambi" msd="AN" tag="ADJ" in="1:attrd" out="">entrambi</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:nobj" out="-1:attrd|1:nobj">i</W>
<W lemma="set" msd="NC" tag="NOM" in="-1:nobj" out="">set</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="rispettivamente" msd="RG" tag="ADV" in="-6:elab" out="-1:pnct|1:nobj|4:pnct">rispettivamente</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="2:conj">0-7</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:conj" out="-1:coord">2-7</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="prima" msd="CS" tag="CON" in="-13:time" out="1:pobj">prima</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="ritrovare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">ritrovare</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="2:nobj">il</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="1:attrd" out="">mio</W>
<W lemma="gioco" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">gioco</W>
<W lemma="." msd="XP" tag="SENT" in="-26:pnct" out="">.</W>
<W lemma="particolarmente" msd="RG" tag="ADV" in="1:focal" out="">Particolarmente</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="3:loc" out="-1:focal|2:nobj">nel</W>
<W lemma="primo" msd="AN" tag="ADJ" in="1:attrd" out="">primo</W>
<W lemma="set" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">set</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]" out="-3:loc|1:vobj|6:pnct|7:pnct">ho</W>
<W lemma="variare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:man|2:dobj|-1:[subj]">variato</W>
<W lemma="bene" msd="RG" tag="ADV" in="-1:man" out="">bene</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:dobj" out="2:nobj">il</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="1:attrd" out="">mio</W>
<W lemma="gioco" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">gioco</W>
<W lemma="." msd="XP" tag="SENT" in="-6:pnct" out="">.</W>
<W lemma="&gt;&gt;" msd="XP" tag="PON" in="-7:pnct" out="">&gt;&gt;</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="6:time" out="1:nobj">Le</W>
<W lemma="due" msd="AN" tag="ADJ" in="-1:nobj" out="2:nobj">due</W>
<W lemma="ultimo" msd="AN" tag="ADJ" in="1:attrd" out="">ultime</W>
<W lemma="volta" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">volte</W>
<W lemma="Thomas" msd="NP" tag="NPR" in="1:namef" out="">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:subj|2:[subj]" out="-1:namef">Stuer</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="-1:subj|-6:time|1:vobj|17:conj">ha</W>
<W lemma="vincere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj|-2:[subj]">vinto</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="primo" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">primo</W>
<W lemma="set" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">set</W>
<W lemma="contro" msd="SP" tag="PRE" in="-1:pobj" out="2:nobj">contro</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="14:coref-id">Ardy</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:nobj" out="-1:namef">Wiranata</W>
<W lemma="e" msd="CS" tag="CON" in="9:coord" out="">e</W>
<W lemma="primo" msd="AN" tag="ADJ" in="8:time" out="1:pobj">prima</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">della</W>
<W lemma="semifinale" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">semifinale</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="oggi" msd="RG" tag="ADV" in="-1:nobj" out="">oggi</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="2:nobj">la</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="1:attrd" out="">sua</W>
<W lemma="tattica" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">tattica</W>
<W lemma="suonare" msd="VADR" tag="VER:pres" in="-17:conj" out="-9:coord|-3:subj|-8:time|1:elab">suona</W>
<W lemma="così" msd="RG" tag="ADV" in="-1:elab" out="">così</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:pnct" out="">:&lt;&lt;</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:subj|2:[subj]|3:[subj]|-14:coref-id" out="">Ardy</W>
<W lemma="dovere" msd="VADR" tag="VER:pres" in="" out="-2:pnct|-1:subj|1:vobj|45:pnct|12:elab">deve</W>
<W lemma="essere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:vobj|-2:[subj]">esser</W>
<W lemma="tenere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-3:[subj]|1:man">tenuto</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="scacco" msd="NC" tag="NOM" in="-1:nobj" out="1:inst">scacco</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:inst" out="1:nobj">con</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="2:nobj">un</W>
<W lemma="solido" msd="AN" tag="ADJ" in="1:attrd" out="">solido</W>
<W lemma="gioco" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:pobj:dobj#">gioco</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj#" out="1:nobj">di</W>
<W lemma="base" msd="NC" tag="NOM" in="-1:nobj" out="">base</W>
<W lemma="," msd="XP" tag="PON" in="4:pnct" out="">,</W>
<W lemma="così" msd="RG" tag="ADV" in="-12:elab" out="3:vobj">così</W>
<W lemma="come" msd="CS" tag="CON" in="2:comp" out="">come</W>
<W lemma="il" msd="PD" tag="DET:def" in="1:dobj" out="">l'</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="1:[subj]|-3:vobj" out="-2:comp|-1:dobj|1:vobj|12:conj|-4:pnct">ho</W>
<W lemma="praticare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-1:[subj]|1:loc">praticato</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">nei</W>
<W lemma="due" msd="AN" tag="ADJ" in="-1:nobj" out="2:nobj">due</W>
<W lemma="primo" msd="AN" tag="ADJ" in="1:attrd" out="">primi</W>
<W lemma="set" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">set</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="5:coord" out="-1:pnct">ma</W>
<W lemma="in" msd="SP" tag="PRE" in="4:loc" out="2:nobj">in</W>
<W lemma="entrambi" msd="AN" tag="ADJ" in="1:attrd" out="">entrambe</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:nobj" out="-1:attrd|1:nobj">le</W>
<W lemma="volta" msd="NC" tag="NOM" in="-1:nobj" out="">volte</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-12:conj|1:[subj]" out="-4:loc|1:vobj|8:loc|-5:coord">ho</W>
<W lemma="perdere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj|-1:[subj]">perso</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="prendere" msd="VAP" tag="VER:pper" in="-1:nobj" out="1:loc">presa</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">al</W>
<W lemma="secondo" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">secondo</W>
<W lemma="set" msd="NC" tag="NOM" in="-1:nobj" out="">set</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="dove" msd="PT" tag="PRO:rela" in="-8:loc" out="-1:pnct|2:vobj">dove</W>
<W lemma="mi" msd="PR" tag="PRO:refl" in="1:robj" out="">mi</W>
<W lemma="trovare" msd="VADA" tag="VER:impf" in="-2:vobj" out="-1:robj|1:pobj">trovavo</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">dalla</W>
<W lemma="parte" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">parte</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="vento" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">vento</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">a</W>
<W lemma="favore" msd="NC" tag="NOM" in="-1:nobj" out="">favore</W>
<W lemma="." msd="XP" tag="SENT" in="-45:pnct" out="">.</W>
<W lemma="qui" msd="RG" tag="ADV" in="4:loc" out="1:loc">Qui</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="Giappone" msd="NP" tag="NPR" in="-1:nobj" out="">Giappone</W>
<W lemma="c'" msd="PD" tag="PRO:demo" in="1:expl" out="">c'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-4:loc|-1:expl|1:dobj|9:conj|14:pnct">è</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="vento" msd="NC" tag="NOM" in="-1:nobj" out="2:relr|1:ref">vento</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:subj|-1:ref" out="">che</W>
<W lemma="soffiare" msd="VADR" tag="VER:pres" in="-2:relr" out="1:man|-1:subj">soffia</W>
<W lemma="lateralmente" msd="RG" tag="ADV" in="-1:man" out="">lateralmente</W>
<W lemma="e" msd="CS" tag="CON" in="3:coord" out="">e</W>
<W lemma="per" msd="SP" tag="PRE" in="2:ben" out="1:nobj">per</W>
<W lemma="me" msd="PP" tag="PRO:pers" in="-1:nobj" out="">me</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-9:conj" out="-3:coord|2:preds|-2:ben">è</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="facile" msd="AN" tag="ADJ" in="-2:preds" out="-1:degr|1:pobj">facile</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">da</W>
<W lemma="gestire" msd="VAF" tag="VER:infi" in="-1:vobj" out="">gestire</W>
<W lemma="." msd="XP" tag="SENT" in="-14:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="7:subj|8:[subj]" out="1:nobj|22:coref">Le</W>
<W lemma="coppia" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">coppie</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:attrr" out="2:attrr">danesi</W>
<W lemma="essere" msd="VADR" tag="VER:cpre" in="2:correl" out="">sia</W>
<W lemma="femminile" msd="AN" tag="ADJ" in="-2:attrr" out="2:conj">femminile</W>
<W lemma="che" msd="CS" tag="CON" in="1:coord" out="-2:correl">che</W>
<W lemma="maschile" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">maschile</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="-7:subj|1:vobj|44:pnct|18:conj">hanno</W>
<W lemma="perdere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:time|-8:[subj]">perso</W>
<W lemma="ieri" msd="RG" tag="ADV" in="-1:time" out="1:loc">ieri</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:loc" out="1:nobj">nel</W>
<W lemma="doppio" msd="AN" tag="ADJ" in="-1:nobj" out="">doppio</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="12:coord" out="-1:pnct">ma</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="11:loc" out="1:nobj">nel</W>
<W lemma="gioco" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">gioco</W>
<W lemma="misto" msd="AN" tag="ADJ" in="-1:attrr" out="">misto</W>
<W lemma="@card@" msd="AN" tag="NUM" in="8:subj" out="1:nobj">3</W>
<W lemma="coppia" msd="NC" tag="NOM" in="-1:nobj" out="1:ext">coppie</W>
<W lemma="su" msd="SP" tag="PRE" in="-1:ext" out="1:nobj">su</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:attrr">4</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:nobj|-22:coref" out="1:loc">quelle</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="semifinale" msd="NC" tag="NOM" in="-1:nobj" out="">semifinale</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="-18:conj" out="-11:loc|-8:subj|1:preds|3:cons|-12:coord">sono</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:preds" out="">danesi</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="-3:cons" out="-1:pnct|1:nobj|2:vobj">per</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="-1:nobj" out="">cui</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-2:vobj" out="1:preds|8:time">siamo</W>
<W lemma="sicuro" msd="AN" tag="ADJ" in="-1:preds" out="1:pobj">sicuri</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">di</W>
<W lemma="avere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">aver</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="porre" msd="VAP" tag="VER:pper" in="-1:nobj" out="1:loc">posto</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="finale" msd="NC" tag="NOM" in="-1:nobj" out="">finale</W>
<W lemma="quando" msd="CS" tag="CON" in="-8:time" out="4:vobj">quando</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="3:subj" out="2:conj">Henrik</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:coord" out="">Svarrer/Marlene</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:conj" out="-1:coord">Thomsen</W>
<W lemma="incontrare" msd="VADR" tag="VER:futu" in="-4:vobj" out="-3:subj|1:dobj">incontreranno</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="4:nobj">la</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="3:attrd" out="">nostra</W>
<W lemma="normalmente" msd="RG" tag="ADV" in="1:prg" out="">normalmente</W>
<W lemma="migliore" msd="AN" tag="ADJ" in="1:attrd" out="-1:prg">migliore</W>
<W lemma="configurazione" msd="NC" tag="NOM" in="-4:nobj" out="-1:attrd|1:appr|-3:attrd">configurazione</W>
<W lemma="Thomas" msd="NP" tag="NPR" in="-1:appr" out="2:conj">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:coord" out="">Lund/Pernille</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">Dupont</W>
<W lemma="." msd="XP" tag="SENT" in="-44:pnct" out="">.</W>
