<p>
<s>
<W lemma="&quot;" msd="XP" tag="PON" in="1:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-1:pnct|1:pnct">Unforgettable</W>
<W lemma="&quot;" msd="XP" tag="PON" in="-1:pnct" out="">"</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="" out="">si</W>
<W lemma="chiamare" msd="VADR" tag="VER:pres" in="" out="1:dobj|21:pnct">chiama</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="duetto" msd="NC" tag="NOM" in="-1:nobj" out="">duetto</W>
<W lemma="vincitore" msd="AN" tag="ADJ" in="" out="">vincitore</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Grammy</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="2:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Natalie</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:nobj" out="-1:namef|2:nobj">Cole</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-2:nobj" out="-1:coord|1:possd|2:pnct">suo</W>
<W lemma="padre" msd="NC" tag="NOM" in="-1:possd" out="">padre</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:namef" out="">Nat</W>
<W lemma="King" msd="NP" tag="NPR" in="1:namel" out="">King</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="-2:namef|-1:namel|1:pnct">Cole</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="decedere" msd="VAP" tag="VER:pper" in="" out="1:time">deceduto</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:time" out="1:nobj">da</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">27</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="." msd="XP" tag="SENT" in="-21:pnct" out="">.</W>
</s>
<s>
<W lemma="ovviamente" msd="RG" tag="ADV" in="1:eval" out="">Ovviamente</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="-1:eval|1:preds|9:preds|21:pnct">era</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="-1:preds" out="1:nobj">questo</W>
<W lemma="raffinamento" msd="NC" tag="NOM" in="-1:nobj" out="">raffinamento</W>
<W lemma="tecnico" msd="AN" tag="ADJ" in="" out="">tecnico</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="brano" msd="NC" tag="NOM" in="-1:nobj" out="">brano</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="successo" msd="NC" tag="NOM" in="-1:nobj" out="">successo</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-9:preds" out="3:relr">quello</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="3:dobj" out="">che</W>
<W lemma="molto" msd="PI" tag="PRO:indef" in="1:subj" out="">molti</W>
<W lemma="avere" msd="VADA" tag="VER:impf" in="-3:relr" out="-1:subj|1:vobj">avevano</W>
<W lemma="attendere" msd="VAP" tag="VER:pper" in="-1:vobj" out="-3:dobj">atteso</W>
<W lemma="come" msd="SP" tag="PRE" in="" out="1:nobj">come</W>
<W lemma="punto" msd="NC" tag="NOM" in="-1:nobj" out="">punto</W>
<W lemma="culminante" msd="AN" tag="ADJ" in="" out="2:conj">culminante</W>
<W lemma="ed" msd="CS" tag="CON" in="1:coord" out="">ed</W>
<W lemma="indimenticabile" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">indimenticabile</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="serata" msd="NC" tag="NOM" in="-1:nobj" out="">serata</W>
<W lemma="." msd="XP" tag="SENT" in="-21:pnct" out="">.</W>
</s>
<s>
<W lemma="ma" msd="CS" tag="CON" in="4:discmark" out="">Ma</W>
<W lemma="in" msd="SP" tag="PRE" in="3:epi" out="1:nobj">in</W>
<W lemma="effetto" msd="NC" tag="NOM" in="-1:nobj" out="">effetti</W>
<W lemma="c'" msd="PD" tag="PRO:demo" in="1:expl" out="">c'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-4:discmark|-3:epi|-1:expl|1:vobj|6:pnct">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="2:dobj">stata</W>
<W lemma="ampiamente" msd="RG" tag="ADV" in="1:man" out="">ampiamente</W>
<W lemma="occasione" msd="NC" tag="NOM" in="-2:dobj" out="-1:man">occasione</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="1:nobj">per</W>
<W lemma="dimenticare" msd="VAF" tag="VER:infi" in="-1:nobj" out="">dimenticare</W>
<W lemma="." msd="XP" tag="SENT" in="-6:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="perché" msd="CS" tag="CON" in="6:cause" out="">Perché</W>
<W lemma="prima" msd="RG" tag="ADV" in="5:time" out="3:pnct">prima</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:vobj">di</W>
<W lemma="arrivare" msd="VAF" tag="VER:infi" in="-1:vobj" out="">arrivarci</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="ci" msd="PR" tag="PRO:refl" in="3:iobj" out="">ci</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-6:cause|-5:time|1:vobj|3:subj|10:pnct">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:preds">stato</W>
<W lemma="presentare" msd="VAP" tag="VER:pper" in="-1:preds" out="-3:iobj">presentato</W>
<W lemma="uno" msd="PI" tag="DET:indef" in="-3:subj" out="1:nobj">uno</W>
<W lemma="show" msd="NC" tag="NOM" in="-1:nobj" out="">show</W>
<W lemma="musicale" msd="AN" tag="ADJ" in="" out="">musicale</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:quant" out="">insolitamente</W>
<W lemma="bello" msd="AN" tag="ADJ" in="" out="-1:quant|2:conj">bello</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="convincente" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">convincente</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
</s>
<s>
<W lemma="in" msd="SP" tag="PRE" in="8:subj" out="1:nobj">In</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="tempo" msd="NC" tag="NOM" in="-1:nobj" out="">tempo</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="1:nobj">in</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="-1:nobj" out="">cui</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="1:nobj">la</W>
<W lemma="musica" msd="NC" tag="NOM" in="-1:nobj" out="">musica</W>
<W lemma="pop" msd="AN" tag="ADJ" in="" out="">pop</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-8:subj|-3:subj|3:preds|9:pnct|14:preds|25:conj">è</W>
<W lemma="sempre" msd="RG" tag="ADV" in="1:quant" out="">sempre</W>
<W lemma="più" msd="RG" tag="ADV" in="1:quant" out="-1:quant">più</W>
<W lemma="legare" msd="VAP" tag="VER:pper" in="-3:preds" out="-1:quant">legata</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="1:nobj|3:conj">all'</W>
<W lemma="energia" msd="NC" tag="NOM" in="-1:nobj" out="">energia</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-3:conj" out="-1:coord|1:nobj">al</W>
<W lemma="rumore" msd="NC" tag="NOM" in="-1:nobj" out="">rumore</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="4:coord" out="">e</W>
<W lemma="dove" msd="RG" tag="ADV" in="3:time" out="">dove</W>
<W lemma="ogni" msd="AN" tag="ADJ" in="2:subj" out="1:nobj">ogni</W>
<W lemma="artista" msd="NC" tag="NOM" in="-1:nobj" out="">artista</W>
<W lemma="proteggere" msd="VADR" tag="VER:pres" in="-14:preds" out="-4:coord|-3:time|-2:subj|1:man|5:dobj|10:pnct">protegge</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="modo" msd="NC" tag="NOM" in="-1:nobj" out="">modo</W>
<W lemma="quasi" msd="RG" tag="ADV" in="1:quant" out="">quasi</W>
<W lemma="maniacale" msd="AN" tag="ADJ" in="" out="-1:quant">maniacale</W>
<W lemma="il" msd="PD" tag="DET:def" in="-5:dobj" out="1:nobj">l'</W>
<W lemma="esclusività" msd="NC" tag="NOM" in="-1:nobj" out="">esclusività</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="2:nobj">del</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="" out="">proprio</W>
<W lemma="repertorio" msd="NC" tag="NOM" in="-2:nobj" out="">repertorio</W>
<W lemma="," msd="XP" tag="PON" in="-10:pnct" out="">,</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-25:conj" out="1:vobj|6:vobj|22:pnct">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="2:preds">stato</W>
<W lemma="veramente" msd="RG" tag="ADV" in="1:quant" out="">veramente</W>
<W lemma="liberatorio" msd="AN" tag="ADJ" in="-2:preds" out="-1:quant|2:conj">liberatorio</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="affascinare" msd="VAG" tag="VER:ppre" in="-2:conj" out="-1:coord">affascinante</W>
<W lemma="vedere" msd="VAF" tag="VER:infi" in="-6:vobj" out="1:vobj">vedersi</W>
<W lemma="aprire" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">aprire</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">lo</W>
<W lemma="scrigno" msd="NC" tag="NOM" in="-1:nobj" out="">scrigno</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj|3:relr">della</W>
<W lemma="musica" msd="NC" tag="NOM" in="-1:nobj" out="">musica</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:subj" out="">che</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-3:relr" out="-1:subj|1:vobj|6:time">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:preds">stata</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:preds" out="1:nobj">in</W>
<W lemma="possesso" msd="NC" tag="NOM" in="-1:nobj" out="">possesso</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="tutto" msd="PI" tag="PRO:indef" in="-1:nobj" out="">tutti</W>
<W lemma="per" msd="SP" tag="PRE" in="-6:time" out="1:nobj">per</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="secolo" msd="NC" tag="NOM" in="-1:nobj" out="">secolo</W>
<W lemma="." msd="XP" tag="SENT" in="-22:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj" out="1:nobj">La</W>
<W lemma="musica" msd="NC" tag="NOM" in="-1:nobj" out="">musica</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-2:subj|1:preds|4:pnct|8:conj|15:pnct">è</W>
<W lemma="scrivere" msd="VAP" tag="VER:pper" in="-1:preds" out="">scritta</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="1:nobj">da</W>
<W lemma="compositore" msd="NC" tag="NOM" in="-1:nobj" out="">compositori</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="che" msd="CS" tag="CON" in="4:dobj" out="">che</W>
<W lemma="innumerevole" msd="AN" tag="ADJ" in="" out="">innumerevoli</W>
<W lemma="artista" msd="NC" tag="NOM" in="1:subj" out="">artisti</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-8:conj" out="-1:subj|1:vobj">hanno</W>
<W lemma="introdurre" msd="VAP" tag="VER:pper" in="-1:vobj" out="-4:dobj|1:man">introdotto</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="1:nobj">con</W>
<W lemma="passione" msd="NC" tag="NOM" in="-1:nobj" out="">passione</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="2:nobj">nel</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="" out="">proprio</W>
<W lemma="repertorio" msd="NC" tag="NOM" in="-2:nobj" out="">repertorio</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
</s>
<s>
<W lemma="quale" msd="PT" tag="PRO:inter" in="14:subj" out="">Quale</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj|4:relr">delle</W>
<W lemma="canzone" msd="NC" tag="NOM" in="-1:nobj" out="">canzoni</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="serata" msd="NC" tag="NOM" in="-1:nobj" out="">serata</W>
<W lemma="essere" msd="VADA" tag="VER:remo" in="-4:relr" out="1:vobj|4:time">furono</W>
<W lemma="portare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:@dir">portate</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-1:@dir" out="1:nobj">al</W>
<W lemma="successo" msd="NC" tag="NOM" in="-1:nobj" out="">successo</W>
<W lemma="originariamente" msd="RG" tag="ADV" in="-4:time" out="">originariamente</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="3:nobj">da</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="2:namef" out="">Nat</W>
<W lemma="King" msd="NP" tag="NPR" in="1:namef" out="">King</W>
<W lemma="cola" msd="NC" tag="NOM" in="-3:nobj" out="-2:namef|-1:namef">Cole</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-14:subj|1:preds|4:preds">è</W>
<W lemma="argomento" msd="NC" tag="NOM" in="-1:preds" out="">argomento</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="discussione" msd="NC" tag="NOM" in="-1:nobj" out="">discussione</W>
<W lemma="così" msd="RG" tag="ADV" in="-4:preds" out="">così</W>
<W lemma="come" msd="SP" tag="PRE" in="" out="1:nobj">come</W>
<W lemma="parte" msd="NC" tag="NOM" in="-1:nobj" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">delle</W>
<W lemma="informazione" msd="NC" tag="NOM" in="-1:nobj" out="">informazioni</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="1:nobj|5:relr">sulle</W>
<W lemma="dichiarazione" msd="NC" tag="NOM" in="-1:nobj" out="">dichiarazioni</W>
<W lemma="che" msd="CS" tag="CON" in="4:dobj" out="12:vobj">che</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Natalie</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:subj" out="-1:namef">Cole</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-5:relr" out="-1:subj|1:vobj|12:pnct">ha</W>
<W lemma="rilasciare" msd="VAP" tag="VER:pper" in="-1:vobj" out="-4:dobj">rilasciato</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="1:nobj">in</W>
<W lemma="quell'" msd="PD" tag="PRO:demo" in="-1:nobj" out="1:nobj">quell'</W>
<W lemma="occasione" msd="NC" tag="NOM" in="-1:nobj" out="">occasione</W>
<W lemma="ma" msd="NC" tag="NOM" in="" out="">Ma</W>
<W lemma="entrare" msd="VAF" tag="VER:infi" in="3:subj" out="1:@dir">entrare</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:@dir" out="1:nobj">nel</W>
<W lemma="merito" msd="NC" tag="NOM" in="-1:nobj" out="">merito</W>
<W lemma="essere" msd="VA" tag="VER:cond" in="-12:vobj" out="-3:subj|2:preds">sarebbe</W>
<W lemma="puro" msd="AN" tag="ADJ" in="" out="">pura</W>
<W lemma="pedanteria" msd="NC" tag="NOM" in="-2:preds" out="">pedanteria</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
</s>
</p>
