0:pnctout="0:pnct"
<s>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">La</W>
<W lemma="raccolta" msd="NC" tag="NOM" in="" out="">raccolta</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="articolo" msd="NC" tag="NOM" in="" out="">articoli</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="intervento" msd="NC" tag="NOM" in="" out="">interventi</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="ultimo" msd="AN" tag="ADJ" in="" out="">ultimi</W>
<W lemma="dieci" msd="AN" tag="ADJ" in="" out="">dieci</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="fare" msd="VADR" tag="VER:pres" in="" out="">fa</W>
<W lemma="lievemente" msd="RG" tag="ADV" in="" out="">lievemente</W>
<W lemma="rimpiangere" msd="VAF" tag="VER:infi" in="" out="">rimpiangere</W>
<W lemma="ciò" msd="PD" tag="PRO:demo" in="" out="">ciò</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="più" msd="RG" tag="ADV" in="" out="">più</W>
<W lemma="gli" msd="PP" tag="PRO:pers" in="" out="">gli</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="congeniale" msd="AN" tag="ADJ" in="" out="">congeniale</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="cioè" msd="RG" tag="ADV" in="" out="">cioè</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="romanzo" msd="NC" tag="NOM" in="" out="">romanzo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="" out="">ma</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="libro" msd="NC" tag="NOM" in="" out="">libro</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="comunque" msd="RG" tag="ADV" in="" out="">comunque</W>
<W lemma="splendido" msd="AN" tag="ADJ" in="" out="">splendido</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="rivelare" msd="VADR" tag="VER:pres" in="" out="">rivela</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="Rushdie" msd="NP" tag="NPR" in="" out="">Rushdie</W>
<W lemma="lettore" msd="NC" tag="NOM" in="" out="">lettore</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="critico" msd="NC" tag="NOM" in="" out="">critico</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="interpretare" msd="VADR" tag="VER:pres" in="" out="">interpreta</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="particolare" msd="AN" tag="ADJ" in="" out="">particolare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="letteratura" msd="NC" tag="NOM" in="" out="">letteratura</W>
<W lemma="fantastico" msd="AN" tag="ADJ" in="" out="">fantastica</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="principale" msd="AN" tag="ADJ" in="" out="">principali</W>
<W lemma="romanziere" msd="NC" tag="NOM" in="" out="">romanzieri</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="terzo" msd="NC" tag="NOM" in="" out="">Terzo</W>
<W lemma="mondo" msd="AN" tag="ADJ" in="" out="">Mondo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Gabriel</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Garcia</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Márquez</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="Mario" msd="NP" tag="NPR" in="" out="">Mario</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Vargas</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Llosa</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="o" msd="CS" tag="CON" in="" out="">o</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="loro" msd="PO" tag="PRO:poss" in="" out="">loro</W>
<W lemma="corrispondente" msd="NC" tag="NOM" in="" out="">corrispondenti</W>
<W lemma="europeo" msd="AN" tag="ADJ" in="" out="">europei</W>
<W lemma="italo" msd="AN" tag="ADJ" in="" out="">Italo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Calvino</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Günter</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Grass</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
<s>
<p>
<s>
<W lemma="vi" msd="PD" tag="PRO:demo" in="" out="">Vi</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="ritrovare" msd="VADR" tag="VER:pres" in="" out="">ritrovano</W>
<W lemma="vario|varo" msd="AN" tag="ADJ" in="" out="">vari</W>
<W lemma="commento" msd="NC" tag="NOM" in="" out="">commenti</W>
<W lemma="vivere" msd="VAP" tag="VER:pper" in="" out="">vissuti</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">prima</W>
<W lemma="persona" msd="NC" tag="NOM" in="" out="">persona</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulla</W>
<W lemma="situazione" msd="NC" tag="NOM" in="" out="">situazione</W>
<W lemma="politico" msd="AN" tag="ADJ" in="" out="">politica</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nella</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="" out="">sua</W>
<W lemma="madrepatria" msd="NC" tag="NOM" in="" out="">madrepatria</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="indio" msd="NC" tag="NOM" in="" out="">India</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="Pakistan" msd="NP" tag="NPR" in="" out="">Pakistan</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Gran</W>
<W lemma="Bretagna" msd="NP" tag="NPR" in="" out="">Bretagna</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="articolo" msd="NC" tag="NOM" in="" out="">articoli</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulla</W>
<W lemma="religione" msd="NC" tag="NOM" in="" out="">religione</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="particolare" msd="AN" tag="ADJ" in="" out="">particolare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="islam" msd="NC" tag="NOM" in="" out="">islam</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">hanno</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="insegnare" msd="VAF" tag="VER:infi" in="" out="">insegnare</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">-soprattutto</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="coloro" msd="P" tag="PRO" in="" out="">coloro</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="sentire" msd="VADR" tag="VER:pres" in="" out="">sentono</W>
<W lemma="esperto" msd="NC" tag="NOM" in="" out="">esperti</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
<s>
<p>
<s>
<W lemma="Rushdie" msd="NP" tag="NPR" in="" out="">Rushdie</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="inserire" msd="VADR" tag="VER:pres" in="" out="">inserisce</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="solido" msd="AN" tag="ADJ" in="" out="">solida</W>
<W lemma="scuola" msd="NC" tag="NOM" in="" out="">scuola</W>
<W lemma="anglosassone" msd="AN" tag="ADJ" in="" out="">anglosassone</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="giornalismo" msd="NC" tag="NOM" in="" out="">giornalismo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="qualità" msd="NC" tag="NOM" in="" out="">qualità</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="riferimento" msd="NC" tag="NOM" in="" out="">riferimento</W>
<W lemma="fra" msd="SP" tag="PRE" in="" out="">fra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="altro" msd="AN" tag="ADJ" in="" out="">altro</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="uno" msd="NC" tag="NOM" in="" out="">uno</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="articolo" msd="NC" tag="NOM" in="" out="">articoli</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">all'</W>
<W lemma="ineguagliabile" msd="AN" tag="ADJ" in="" out="">ineguagliabile</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="moderno" msd="AN" tag="ADJ" in="" out="">moderno</W>
<W lemma="maestro" msd="NC" tag="NOM" in="" out="">maestro</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">questo</W>
<W lemma="genere" msd="NC" tag="NOM" in="" out="">genere</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="George" msd="NP" tag="NPR" in="" out="">George</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Orwell</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="" out="">cui</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="contrapporre" msd="VADR" tag="VER:pres" in="" out="">contrappone</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="maniera" msd="NC" tag="NOM" in="" out="">maniera</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="tutto" msd="NC" tag="NOM" in="" out="">tutto</W>
<W lemma="ingiustificato" msd="AN" tag="ADJ" in="" out="">ingiustificata</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="probabilmente" msd="RG" tag="ADV" in="" out="">probabilmente</W>
<W lemma="perché" msd="RG" tag="ADV" in="" out="">perché</W>
<W lemma="leggere" msd="VADR" tag="VER:pres" in="" out="">legge</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Orwell</W>
<W lemma="attraverso" msd="SP" tag="PRE" in="" out="">attraverso</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="tradizione" msd="NC" tag="NOM" in="" out="">tradizione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="sinistra" msd="NC" tag="NOM" in="" out="">sinistra</W>
<W lemma="britannico" msd="AN" tag="ADJ" in="" out="">britannica</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="meno" msd="RG" tag="ADV" in="" out="">meno</W>
<W lemma="dotare" msd="VAP" tag="VER:pper" in="" out="">dotata</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="area" msd="NC" tag="NOM" in="" out="">aree</W>
<W lemma="radicale" msd="AN" tag="ADJ" in="" out="">radicali</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="sinistra" msd="NC" tag="NOM" in="" out="">sinistra</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
