<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="7:subj" out="2:nobj">La</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">prima</W>
<W lemma="apparizione" msd="NC" tag="NOM" in="-2:nobj" out="">apparizione</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Pio</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="1:nobj">nel</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">1871</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="-7:subj|1:vobj|14:pnct">era</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="2:preds">stata</W>
<W lemma="direttamente" msd="RG" tag="ADV" in="1:man" out="">direttamente</W>
<W lemma="causare" msd="VAP" tag="VER:pper" in="-2:preds" out="-1:man">causata</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="2:nobj">dalla</W>
<W lemma="grande" msd="AN" tag="ADJ" in="" out="">grande</W>
<W lemma="rivoluzione" msd="NC" tag="NOM" in="-2:nobj" out="">Rivoluzione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="comune" msd="NC" tag="NOM" in="-1:nobj" out="">Comune</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="Parigi" msd="NP" tag="NPR" in="-1:nobj" out="">Parigi</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="2:nobj">dello</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="anno" msd="NC" tag="NOM" in="-2:nobj" out="">anno</W>
<W lemma="." msd="XP" tag="SENT" in="-14:pnct" out="">.</W>
</s>
<s>
<W lemma="in" msd="SP" tag="PRE" in="5:time" out="1:nobj|2:nobj">In</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="-1:nobj" out="">tutta</W>
<W lemma="Europa" msd="NP" tag="NPR" in="-2:nobj" out="">Europa</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj" out="1:nobj">la</W>
<W lemma="rivoluzione" msd="NC" tag="NOM" in="-1:nobj" out="">rivoluzione</W>
<W lemma="avere" msd="VADA" tag="VER:impf" in="" out="-5:time|-2:subj|1:vobj|12:pnct">aveva</W>
<W lemma="alimentare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:dobj">alimentato</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">l'</W>
<W lemma="entusiasmo" msd="NC" tag="NOM" in="-1:nobj" out="">entusiasmo</W>
<W lemma="tra" msd="SP" tag="PRE" in="" out="1:nobj">tra</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj|3:conj">i</W>
<W lemma="lavoratore" msd="NC" tag="NOM" in="-1:nobj" out="">lavoratori</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="-3:conj" out="-1:coord|1:nobj">il</W>
<W lemma="terrore" msd="NC" tag="NOM" in="-1:nobj" out="">terrore</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="1:nobj">nelle</W>
<W lemma="autorità" msd="NC" tag="NOM" in="-1:nobj" out="">autorità</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
</s>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="17:subj" out="1:nobj|6:pnct">Gli</W>
<W lemma="operaio" msd="NC" tag="NOM" in="-1:nobj" out="">operai</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="giornata" msd="NC" tag="NOM" in="-1:nobj" out="">giornata</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Copenaghen</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="oppresso" msd="NC" tag="NOM" in="" out="9:pnct">oppressi</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="2:nobj">dalla</W>
<W lemma="libero" msd="AN" tag="ADJ" in="" out="">libera</W>
<W lemma="concorrenza" msd="NC" tag="NOM" in="-2:nobj" out="1:time">concorrenza</W>
<W lemma="dopo" msd="SP" tag="PRE" in="-1:time" out="1:nobj">dopo</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">l'</W>
<W lemma="abolizione" msd="NC" tag="NOM" in="-1:nobj" out="">abolizione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="corporazione" msd="NC" tag="NOM" in="-1:nobj" out="">corporazione</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="-17:subj|1:preds|2:subj|11:subj|20:pnct">erano</W>
<W lemma="volenteroso" msd="AN" tag="ADJ" in="-1:preds" out="">volenterosi</W>
<W lemma="partecipare" msd="VAG" tag="VER:ppre" in="-2:subj" out="">partecipanti</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dell'</W>
<W lemma="ordine" msd="NC" tag="NOM" in="-1:nobj" out="">Ordine</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Pio</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="-1:coord|1:nobj">il</W>
<W lemma="governo" msd="NC" tag="NOM" in="-1:nobj" out="">governo</W>
<W lemma="conservativo" msd="AN" tag="ADJ" in="" out="">conservativo</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="-11:subj" out="-3:subj|2:preds">era</W>
<W lemma="altrettanto" msd="RG" tag="ADV" in="1:quant" out="">altrettanto</W>
<W lemma="ansioso" msd="AN" tag="ADJ" in="-2:preds" out="-1:quant">ansioso</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:vobj">di</W>
<W lemma="soffocare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">soffocare</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="rivolta" msd="NC" tag="NOM" in="-1:nobj" out="">rivolta</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="1:vobj">sul</W>
<W lemma="nascere" msd="VAF" tag="VER:infi" in="-1:vobj" out="">nascere</W>
<W lemma="." msd="XP" tag="SENT" in="-20:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="" out="1:nobj">La</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="">storia</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dell'</W>
<W lemma="avanzata" msd="NC" tag="NOM" in="-1:nobj" out="">avanzata</W>
<W lemma="ingegnoso" msd="AN" tag="ADJ" in="" out="">ingegnosa</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Pio</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="1:nobj|6:pnct|8:conj">dal</W>
<W lemma="punto" msd="NC" tag="NOM" in="-1:nobj" out="">punto</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="vista" msd="NC" tag="NOM" in="-1:nobj" out="">vista</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">delle</W>
<W lemma="agitazione" msd="NC" tag="NOM" in="-1:nobj" out="">agitazioni</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="1:coord" out="">ma</W>
<W lemma="da" msd="SP" tag="PRE" in="-8:conj" out="-1:coord|1:nobj">da</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:nobj" out="">quello</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj|4:pnct|20:relr">dell'</W>
<W lemma="organizzazione" msd="NC" tag="NOM" in="-1:nobj" out="">organizzazione</W>
<W lemma="assolutamente" msd="RG" tag="ADV" in="1:quant" out="">assolutamente</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="-1:quant">amatoriale</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="15:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="14:subj" out="2:nobj">il</W>
<W lemma="cinico" msd="AN" tag="ADJ" in="" out="">cinico</W>
<W lemma="sfruttamento" msd="NC" tag="NOM" in="-2:nobj" out="">sfruttamento</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">del</W>
<W lemma="ministro" msd="NC" tag="NOM" in="-1:nobj" out="">ministro</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="giustizia" msd="NC" tag="NOM" in="-1:nobj" out="">giustizia</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="qualsiasi" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">qualsiasi</W>
<W lemma="possibilità" msd="NC" tag="NOM" in="-1:nobj" out="">possibilità</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:vobj">di</W>
<W lemma="spezzare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj">spezzare</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="movimento" msd="NC" tag="NOM" in="-1:nobj" out="">movimento</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-20:relr" out="-15:coord|-14:subj|1:preds|32:pnct">è</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:preds" out="1:nobj">una</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="2:pnct">storia</W>
<W lemma="triste|tristo" msd="AN" tag="ADJ" in="" out="">triste</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="altrettanto" msd="RG" tag="ADV" in="1:quant" out="">altrettanto</W>
<W lemma="compromettente" msd="AN" tag="ADJ" in="" out="-1:quant">compromettente</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="1:nobj|3:conj">per</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Pio</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="in" msd="SP" tag="PRE" in="-3:conj" out="-1:coord|1:nobj">in</W>
<W lemma="particolare" msd="NC" tag="NOM" in="-1:nobj" out="">particolare</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="1:nobj|12:conj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj|16:conj">i</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-1:nobj" out="1:possd">suoi</W>
<W lemma="collaboratore" msd="NC" tag="NOM" in="-1:possd" out="3:pnct|4:conj">collaboratori</W>
<W lemma="più" msd="RG" tag="ADV" in="1:quant" out="">più</W>
<W lemma="stretto" msd="AN" tag="ADJ" in="" out="-1:quant">stretti</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-4:conj" out="2:conj|3:pnct">Geleff</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:conj" out="-1:coord">Brix</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:coord" out="">che</W>
<W lemma="per" msd="SP" tag="PRE" in="-12:conj" out="-1:coord|1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="polizia" msd="NC" tag="NOM" in="-1:nobj" out="">polizia</W>
<W lemma="danese" msd="AN" tag="ADJ" in="" out="">danese</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET:def" in="-16:conj" out="-1:coord|1:nobj">il</W>
<W lemma="sistema" msd="NC" tag="NOM" in="-1:nobj" out="">sistema</W>
<W lemma="giudiziario" msd="AN" tag="ADJ" in="" out="">giudiziario</W>
<W lemma="." msd="XP" tag="SENT" in="-32:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj" out="1:nobj">La</W>
<W lemma="questione" msd="NC" tag="NOM" in="-1:nobj" out="">questione</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-2:subj|2:preds|15:pnct">è</W>
<W lemma="quanto" msd="AN" tag="ADJ" in="" out="2:relr">quanta</W>
<W lemma="attenzione" msd="NC" tag="NOM" in="-2:preds" out="">attenzione</W>
<W lemma="meritare" msd="VADR" tag="VER:cpre" in="-2:relr" out="1:dobj">meriti</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">l'</W>
<W lemma="episodio" msd="NC" tag="NOM" in="-1:nobj" out="">episodio</W>
<W lemma="pio" msd="AN" tag="ADJ" in="" out="">Pio</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">degli</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">1871-77</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="1:nobj">nella</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="">storia</W>
<W lemma="danese" msd="AN" tag="ADJ" in="" out="">danese</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="lavoratore" msd="NC" tag="NOM" in="-1:nobj" out="">lavoratori</W>
<W lemma="." msd="XP" tag="SENT" in="-15:pnct" out="">.</W>
</s>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="5:subj" out="1:nobj|3:appr">Il</W>
<W lemma="professor" msd="NC" tag="NOM" in="-1:nobj" out="">professor</W>
<W lemma="Jens" msd="NP" tag="NPR" in="1:namef" out="">Jens</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-3:appr" out="-1:namef">Engberg</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="dedicare" msd="VADR" tag="VER:pres" in="" out="-5:subj|9:pnct|16:pnct">dedica</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dal</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">1973</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="1:nobj">alla</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="">storia</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="lavoratore" msd="NC" tag="NOM" in="-1:nobj" out="">lavoratori</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="1:nobj|4:conj">in</W>
<W lemma="generale" msd="NC" tag="NOM" in="-1:nobj" out="">generale</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-4:conj" out="-1:coord|1:nobj">del</W>
<W lemma="caso" msd="NC" tag="NOM" in="-1:nobj" out="">caso</W>
<W lemma="pio" msd="AN" tag="ADJ" in="" out="">Pio</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="1:nobj">in</W>
<W lemma="particolare" msd="AN" tag="ADJ" in="-1:nobj" out="">particolare</W>
<W lemma="." msd="XP" tag="SENT" in="-16:pnct" out="">.</W>
</s>
<s>
<W lemma="egli" msd="PP" tag="PRO:pers" in="1:subj" out="">Egli</W>
<W lemma="meritare" msd="VADR" tag="VER:pres" in="" out="-1:subj|1:dobj|20:pnct">merita</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="2:nobj">un</W>
<W lemma="grande" msd="AN" tag="ADJ" in="" out="">grande</W>
<W lemma="elogio" msd="NC" tag="NOM" in="-2:nobj" out="">elogio</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-1:nobj" out="1:possd">sua</W>
<W lemma="biografia" msd="NC" tag="NOM" in="-1:possd" out="">biografia</W>
<W lemma="su" msd="SP" tag="PRE" in="" out="1:nobj">su</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Pio</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj|2:pnct|6:relr">del</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">1979</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="me" msd="PP" tag="PRO:pers" in="3:subj" out="">me</W>
<W lemma="non" msd="RG" tag="ADV" in="2:neg" out="">non</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-6:relr" out="-3:subj|-2:neg|1:preds">è</W>
<W lemma="fermare" msd="VAP" tag="VER:pper" in="-1:preds" out="">fermato</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:nobj" out="">quello</W>
<W lemma="." msd="XP" tag="SENT" in="-20:pnct" out="">.</W>
</s>
<s>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="1:vobj|14:pnct">Ha</W>
<W lemma="volere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:vobj">voluto</W>
<W lemma="rendere" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:dobj|2:dobj">rendere</W>
<W lemma="pubblico" msd="AN" tag="ADJ" in="-1:dobj" out="">pubbliche</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="-2:dobj" out="1:nobj">tutte</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">le</W>
<W lemma="fonte" msd="NC" tag="NOM" in="-1:nobj" out="">fonti</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">della</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="">storia</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="martire|martirio" msd="NC" tag="NOM" in="-1:nobj" out="">martiri</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="leader" msd="NC" tag="NOM" in="-1:nobj" out="">leader</W>
<W lemma="socialista" msd="AN" tag="ADJ" in="" out="">socialisti</W>
<W lemma="." msd="XP" tag="SENT" in="-14:pnct" out="">.</W>
</s>
</p>
