<W lemma="il" msd="PD" tag="DET&3a;def" in="5:time" out="2:nobj|3:nobj">Il</W>
<W lemma="primo" msd="AN" tag="ADJ" in="1:attr" out="">primo</W>
<W lemma="dicembre" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">dicembre</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-3:nobj" out="">1883</W>
<W lemma="si" msd="PP" tag="PRO&3a;pers" in="1:robj" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-1:robj|-5:time|1:vobj|4:subj|12:pnct">è</W>
<W lemma="aperto" msd="AN" tag="ADJ" in="-1:vobj" out="1:pobj">aperta</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">al</W>
<W lemma="pubblico" msd="NC" tag="NOM" in="-1:nobj" out="">pubblico</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-4:subj" out="1:nobj">la</W>
<W lemma="linea" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">linea</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="comunicazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">comunicazione</W>
<W lemma="marittimo" msd="AN" tag="ADJ" in="-1:attr" out="1:attr">marittima</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="2:nobj">del</W>
<W lemma="grande" msd="NC" tag="NOM" in="1:attr" out="">Grande</W>
<W lemma="Belt" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr">Belt</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="15:subj" out="3:nobj">Il</W>
<W lemma="primo" msd="AN" tag="ADJ" in="2:attr" out="">primo</W>
<W lemma="grosso" msd="AN" tag="ADJ" in="1:attr" out="">grosso</W>
<W lemma="colpo" msd="NC" tag="NOM" in="-3:nobj" out="-2:attr|-1:attr|1:pobj">colpo</W>
<W lemma="contro" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">contro</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="predominio" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">predominio</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">della</W>
<W lemma="navigazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">navigazione</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">in</W>
<W lemma="traghetto" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">traghetto</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">nelle</W>
<W lemma="acqua" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">acque</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:attr" out="">danesi</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-15:subj|-1:robj|1:vobj|9:pnct|22:pnct">è</W>
<W lemma="verificare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="2:time|9:man">verificato</W>
<W lemma="solo" msd="RG" tag="ADV" in="1:degr" out="">solo</W>
<W lemma="dopo" msd="CS" tag="CON" in="-2:time" out="-1:degr|4:nobj">dopo</W>
<W lemma="poco" msd="RG" tag="ADV" in="1:degr" out="">poco</W>
<W lemma="più" msd="RG" tag="ADV" in="2:degr" out="-1:degr|1:pobj">più</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-4:nobj" out="-2:degr|1:nobj">cinquant'</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="con" msd="SP" tag="PRE" in="-9:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">l'</W>
<W lemma="inaugurazione" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj|6:time">inaugurazione</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">del</W>
<W lemma="ponte" msd="NC" tag="NOM" in="-1:nobj" out="1:loc">ponte</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-1:loc" out="2:nobj">sul</W>
<W lemma="piccolo" msd="NC" tag="NOM" in="1:attr" out="">Piccolo</W>
<W lemma="Belt" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr">Belt</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-6:time" out="3:nobj">il</W>
<W lemma="@card@" msd="AN" tag="NUM" in="1:nobj" out="">15</W>
<W lemma="maggio" msd="NC" tag="NOM" in="1:nobj" out="-1:nobj">maggio</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-3:nobj" out="-1:nobj">1935</W>
<W lemma="." msd="XP" tag="SENT" in="-22:pnct" out="">.</W>
<W lemma="tra" msd="SP" tag="PRE" in="14:time" out="1:nobj">Tra</W>
<W lemma="tre" msd="AN" tag="ADJ" in="-1:nobj" out="1:nobj">tre</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="11:subj|12:[subj]" out="2:nobj">un</W>
<W lemma="grande" msd="AN" tag="ADJ" in="1:attr" out="">grande</W>
<W lemma="numero" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr|1:pobj">numero</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="traghetto" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">traghetti</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">del</W>
<W lemma="sistema" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|2:attr|3:attr">sistema</W>
<W lemma="nazionale" msd="AN" tag="ADJ" in="-1:attr" out="">nazionale</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-2:attr" out="">danese</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-3:attr" out="1:nobj">dei</W>
<W lemma="trasporto" msd="NC" tag="NOM" in="-1:nobj" out="">trasporti</W>
<W lemma="dovere" msd="VADR" tag="VER&3a;futu" in="" out="-11:subj|-14:time|1:vobj|5:pnct|22:pnct">dovrà</W>
<W lemma="cercare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-12:[subj]|1:pobj">cercare</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="2:nobj">dei</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="1:attr" out="">nuovi</W>
<W lemma="mare" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">mari</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="quando" msd="CS" tag="CON" in="6:time" out="">quando</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="5:subj" out="1:nobj">il</W>
<W lemma="collegamento" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">Collegamento</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="2:nobj">del</W>
<W lemma="grande" msd="NC" tag="NOM" in="1:attr" out="">Grande</W>
<W lemma="Belt" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr">Belt</W>
<W lemma="diventare" msd="VADR" tag="VER&3a;futu" in="" out="-5:subj|-6:time|1:preds|3:pnct|7:cons|1:preds">diventerà</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="-1:preds|-1:preds" out="1:nobj">una</W>
<W lemma="realtà" msd="NC" tag="NOM" in="-1:nobj" out="">realtà</W>
<W lemma="&3a;" msd="XP" tag="PON" in="-3:pnct" out="">:</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="3:subj" out="1:nobj">una</W>
<W lemma="vicenda" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">vicenda</W>
<W lemma="emozionante" msd="AN" tag="ADJ" in="-1:attr" out="">emozionante</W>
<W lemma="entrare" msd="VADR" tag="VER&3a;futu" in="-7:cons" out="-3:subj|1:pobj">entrerà</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">nella</W>
<W lemma="storia" msd="NC" tag="NOM" in="-1:nobj" out="">storia</W>
<W lemma="." msd="XP" tag="SENT" in="-22:pnct" out="">.</W>
<W lemma="cinque" msd="AN" tag="ADJ" in="9:subj" out="1:nobj">Cinque</W>
<W lemma="linea" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">linee</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">del</W>
<W lemma="sistema" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">sistema</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="comunicazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|2:attr">comunicazione</W>
<W lemma="marittimo" msd="AN" tag="ADJ" in="-1:attr" out="">marittima</W>
<W lemma="nazionale" msd="AN" tag="ADJ" in="-2:attr" out="1:appr">nazionale</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:appr" out="">DSB</W>
<W lemma="continuare" msd="VADR" tag="VER&3a;pres" in="" out="-9:subj|1:pobj|3:pnct">continuano</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="sussistere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="">sussistere</W>
<W lemma="." msd="XP" tag="SENT" in="-3:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="5:subj" out="1:nobj">La</W>
<W lemma="flotta" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|2:attr">flotta</W>
<W lemma="mercantile" msd="AN" tag="ADJ" in="-1:attr" out="">mercantile</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-2:attr" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">DSB</W>
<W lemma="ricerca" msd="NC" tag="NOM" in="" out="-5:subj|1:dobj|3:loc|10:pnct|11:cause|48:pnct">ricerca</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="-1:dobj" out="1:nobj">nuovi</W>
<W lemma="mercato" msd="NC" tag="NOM" in="-1:nobj" out="">mercati</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-3:loc" out="1:nobj">nelle</W>
<W lemma="area" msd="NC" tag="NOM" in="-1:nobj" out="1:loc">aree</W>
<W lemma="ad" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">ad</W>
<W lemma="est" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj">est</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">del</W>
<W lemma="Mar" msd="NP" tag="NPR" in="-1:nobj" out="1:attr">Mar</W>
<W lemma="Baltico" msd="NP" tag="NPR" in="-1:attr" out="">Baltico</W>
<W lemma="," msd="XP" tag="PON" in="-10:pnct" out="">,</W>
<W lemma="poiché" msd="CS" tag="CON" in="-11:cause" out="5:vobj|15:pnct">poiché</W>
<W lemma="a" msd="SP" tag="PRE" in="4:time" out="1:vobj">a</W>
<W lemma="partire" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:pobj">partire</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">dal</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">2005</W>
<W lemma="restare" msd="VADR" tag="VER&3a;futu" in="-5:vobj" out="-4:time|1:pobj|4:subj|24:conc|33:coref-res">resteranno</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">in</W>
<W lemma="funzione" msd="NC" tag="NOM" in="-1:nobj" out="">funzione</W>
<W lemma="solo" msd="RG" tag="ADV" in="1:focal" out="">solo</W>
<W lemma="cinque" msd="AN" tag="ADJ" in="-4:subj" out="-1:focal|1:pobj&3a;subj|8:elab">cinque</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;subj" out="2:nobj">delle</W>
<W lemma="attuale" msd="AN" tag="ADJ" in="1:attr" out="">attuali</W>
<W lemma="dieci" msd="AN" tag="ADJ" in="-2:nobj" out="-1:attr|1:nobj">dieci</W>
<W lemma="linea" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">linee</W>
<W lemma="marittimo" msd="AN" tag="ADJ" in="-1:attr" out="">marittime</W>
<W lemma="," msd="XP" tag="PON" in="-15:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="cioè" msd="RG" tag="ADV" in="-8:elab" out="-1:coord|1:nobj">cioè</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|3:conj|18:conj">le</W>
<W lemma="linea" msd="NC" tag="NOM" in="-1:nobj" out="1:appr">linee</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:appr" out="2:conj|4:conj|6:conj">Esbjerg-Fanø</W>
<W lemma="," msd="XP" tag="PON" in="-3:conj" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:conj" out="1:pnct">Bøjden-Fynshav</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-4:conj" out="1:pnct">Kalundborg-Samsø</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-6:conj" out="1:list|2:pnct">Helsingør</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:list" out="">Helsingborg</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="anche" msd="RG" tag="ADV" in="-24:conc" out="1:cond">anche</W>
<W lemma="se" msd="CS" tag="CON" in="-1:cond" out="1:man">se</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="2:nobj">con</W>
<W lemma="forte" msd="AN" tag="ADJ" in="1:attr" out="">forti</W>
<W lemma="riduzione" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">riduzioni</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="infine" msd="RG" tag="ADV" in="1:struct" out="">infine</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-18:conj" out="-2:coord|-1:struct">Gedser-Warnemünde</W>
<W lemma="." msd="XP" tag="SENT" in="-48:pnct" out="">.</W>
<W lemma="questo" msd="PD" tag="PRO&3a;demo" in="-33:coref-res|3:subj" out="1:nobj">Questa</W>
<W lemma="prognosi" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">prognosi</W>
<W lemma="fosco" msd="AN" tag="ADJ" in="-1:attr" out="">fosca</W>
<W lemma="deriva" msd="NC" tag="NOM" in="" out="-3:subj|1:pobj|38:pnct">deriva</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">dall'</W>
<W lemma="attivazione" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj|6:loc">attivazione</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="2:nobj">delle</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="1:attr" out="">nuove</W>
<W lemma="via" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr|1:attr">vie</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="comunicazione" msd="NC" tag="NOM" in="-1:nobj" out="">comunicazione</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-6:loc" out="2:nobj|11:conj">sul</W>
<W lemma="grande" msd="NC" tag="NOM" in="1:attr" out="">Grande</W>
<W lemma="Belt" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr|2:conj|4:conj">Belt</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="Øresund" msd="NP" tag="NPR" in="-2:conj" out="">Øresund</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="Baltico" msd="NP" tag="NPR" in="-4:conj" out="-1:coord|1:pnct">Baltico</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="3:coord" out="">e</W>
<W lemma="in" msd="SP" tag="PRE" in="2:struct" out="1:nobj">in</W>
<W lemma="particolare" msd="NC" tag="NOM" in="-1:nobj" out="">particolare</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-11:conj" out="-3:coord|-2:struct|2:nobj|3:time|10:conj|15:conj">sul</W>
<W lemma="grande" msd="NC" tag="NOM" in="1:attr" out="">Grande</W>
<W lemma="Belt" msd="NP" tag="NPR" in="-2:nobj" out="-1:attr">Belt</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-3:time" out="1:nobj">nel</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:pnct|2:conj">1996</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:conj" out="2:conj">1997</W>
<W lemma="o" msd="CS" tag="CON" in="1:coord" out="">o</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:conj" out="-1:coord|1:pnct">1998</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-10:conj" out="1:nobj|2:time">nell'</W>
<W lemma="Øresund" msd="NP" tag="NPR" in="-1:nobj" out="">Øresund</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-2:time" out="1:nobj">nel</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">2000</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="sul" msd="SP+P" tag="PRE&3a;det" in="-15:conj" out="-1:coord|1:nobj|2:time">sul</W>
<W lemma="Baltico" msd="NP" tag="NPR" in="-1:nobj" out="">Baltico</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-2:time" out="1:nobj">nel</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">2005</W>
<W lemma="." msd="XP" tag="SENT" in="-38:pnct" out="">.</W>
<W lemma="quindi" msd="RG" tag="ADV" in="8:cons" out="">Quindi</W>
<W lemma="gran" msd="AN" tag="ADJ" in="7:subj" out="1:nobj">gran</W>
<W lemma="parte" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;dobj">parte</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;dobj" out="1:nobj">dei</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">34</W>
<W lemma="traghetto" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">traghetti</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">DSB</W>
<W lemma="diventare" msd="VADR" tag="VER&3a;futu" in="" out="-7:subj|-8:cons|1:preds|2:pnct|1:preds">diventerà</W>
<W lemma="superfluo" msd="AN" tag="ADJ" in="-1:preds|-1:preds" out="">superflua</W>
<W lemma="." msd="XP" tag="SENT" in="-2:pnct" out="">.</W>
