<W lemma="il" msd="PD" tag="DET:def" in="7:xtop" out="1:nobj">La</W>
<W lemma="mancanza" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj">mancanza</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj" out="1:nobj">di</W>
<W lemma="contrasto" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">contrasti</W>
<W lemma="interno" msd="AN" tag="ADJ" in="-1:attrr" out="">interni</W>
<W lemma="egli" msd="PP" tag="PRO:pers" in="2:subj" out="">egli</W>
<W lemma="la" msd="PP" tag="PRO:pers" in="1:dobj" out="">la</W>
<W lemma="ritenere" msd="VADR" tag="VER:pres" in="" out="-2:subj|-7:xtop|-1:dobj|1:preds|7:pnct">ritiene</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:preds" out="1:nobj">il</W>
<W lemma="punto" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:arg#">punto</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:arg#" out="1:nobj">di</W>
<W lemma="forza" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">forza</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">dei</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:nobj" out="">danesi</W>
<W lemma="." msd="XP" tag="SENT" in="-7:pnct" out="">.</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="1:dobj|12:pnct">Abbiamo</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">una</W>
<W lemma="tradizione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">tradizione</W>
<W lemma="basare" msd="VAP" tag="VER:pper" in="-1:attrr" out="1:pobj">basata</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">sulla</W>
<W lemma="ricerca" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr|4:conj">ricerca</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">del</W>
<W lemma="consenso" msd="NC" tag="NOM" in="-1:nobj" out="">consenso</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-4:conj" out="-1:coord|2:nobj">delle</W>
<W lemma="largo" msd="AN" tag="ADJ" in="1:attrd" out="">larghe</W>
<W lemma="intesa" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">intese</W>
<W lemma="." msd="XP" tag="SENT" in="-12:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="1:preds|19:pnct">“Siete</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:preds" out="1:attrr">un’etnia</W>
<W lemma="caratterizzare" msd="VAP" tag="VER:pper" in="-1:attrr" out="1:pobj">caratterizzata</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:dobj">da</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:dobj" out="2:nobj">una</W>
<W lemma="straordinario" msd="AN" tag="ADJ" in="1:attrd" out="">straordinaria</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:attrr|2:ref|4:relr">unità</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attrr" out="">cultural-popolare</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-2:ref|2:subj" out="">che</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-4:relr" out="-1:neg|-2:subj|1:preds">è</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:preds" out="2:nobj">la</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="1:attrr" out="">stessa</W>
<W lemma="cosa" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrr|1:comp">cosa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:comp" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">quell’uniformità</W>
<W lemma="descrivere" msd="VAP" tag="VER:pper" in="-1:attrr" out="1:pobj">descritta</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">da</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Molesworth</W>
<W lemma="." msd="XP" tag="SENT" in="-19:pnct" out="">.</W>
<W lemma="avere" msd="VADR" tag="VER:pres" in="" out="1:dobj|14:conc|23:pnct">Avete</W>
<W lemma="fantasia" msd="NC" tag="NOM" in="-1:dobj" out="1:man|4:conj">fantasia</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="abbondanza" msd="NC" tag="NOM" in="-1:nobj" out="">abbondanza</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-4:conj" out="-1:coord|1:pobj:dobj">personalità</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:pobj:dobj" out="1:comp">d’ingegno</W>
<W lemma="come" msd="CS" tag="CON" in="-1:comp" out="1:ext|5:nobj">come</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:ext" out="1:nobj">per</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="1:+">es</W>
<W lemma="." msd="XP" tag="SENT" in="-1:+" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:namef" out="">Halfdan</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-5:nobj" out="-1:namef">Rasmussen</W>
<W lemma="," msd="XP" tag="PON" in="2:pnct" out="">,</W>
<W lemma="eppure" msd="RG" tag="ADV" in="-14:conc" out="1:vobj">eppure</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-1:vobj" out="-2:pnct|1:nobj|2:preds|4:conj">siete</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="-1:nobj" out="">tutti</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-2:preds" out="">danesi</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-4:conj" out="-1:coord|1:preds">siete</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:preds" out="1:pobj">d’accordo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:¹vobj">di</W>
<W compound="¹esser²lo" lemma="essere" msd="VAF" tag="VER:infi" in="-1:¹vobj|0:²dobj¹" out="0:²dobj¹">esserlo</W>
<W lemma="." msd="XP" tag="SENT" in="-23:pnct" out="">.</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="9:loc" out="2:nobj">Nel</W>
<W lemma="mio" msd="PO" tag="PRO:poss" in="1:attrd" out="">mio</W>
<W lemma="paese" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|2:appa">paese</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:appa" out="-1:pnct|1:nobj|2:pnct">la</W>
<W lemma="scozia" msd="NC" tag="NOM" in="-1:nobj" out="">Scozia</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="2:contr" out="1:nobj">al</W>
<W lemma="contrario" msd="NC" tag="NOM" in="-1:nobj" out="">contrario</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-9:loc|-2:contr|2:preds">siamo</W>
<W lemma="diverso" msd="AN" tag="ADJ" in="1:attrd" out="">diversi</W>
<W lemma="tipo" msd="NC" tag="NOM" in="-2:preds" out="-1:attrd|1:attrr">tipi</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">scozzesi.”</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="21:cause" out="1:pnct">Quindi</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="9:ben" out="2:nobj">per</W>
<W lemma="James" msd="NP" tag="NPR" in="1:namef" out="">James</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj" out="-1:namef">Mellon</W>
<W lemma="se" msd="CS" tag="CON" in="6:cond" out="">se</W>
<W lemma="capello" msd="NC" tag="NOM" in="5:subj" out="1:attrr|4:conj">capelli</W>
<W lemma="biondo" msd="AN" tag="ADJ" in="-1:attrr" out="">biondi</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="bello" msd="AN" tag="ADJ" in="1:attrd" out="">belle</W>
<W lemma="ragazza|ragazzo" msd="NC" tag="NOM" in="-4:conj" out="-1:attrd|-2:coord">ragazze</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="10:vobj" out="-5:subj|-6:cond|-9:ben|1:preds">sono</W>
<W lemma="segno" msd="NC" tag="NOM" in="-1:preds" out="1:attrr">segni</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">tipicità</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:attrr" out="">danese</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="tuttavia" msd="RG" tag="ADV" in="4:conc" out="-1:pnct">tuttavia</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="3:subj" out="1:attrr">l’essenza</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">danesità</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-21:cause|-10:vobj|-4:conc|-3:subj|1:pobj|31:pnct">è</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">da</W>
<W lemma="ricercare" msd="VAF" tag="VER:infi" in="-1:vobj" out="1:struct">ricercarsi</W>
<W lemma="primariamente" msd="RG" tag="ADV" in="-1:struct" out="1:loc">primariamente</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-1:loc" out="2:nobj|6:conj">nella</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="1:attrd" out="">nostra</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:pobj:dobj">capacità</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj:dobj" out="1:vobj">di</W>
<W lemma="collaborare" msd="VAF" tag="VER:infi" in="-1:vobj" out="">collaborare</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-6:conj" out="-1:coord|1:attrr">nell’unicità</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:attrr" out="2:nobj">della</W>
<W lemma="nostro" msd="PO" tag="PRO:poss" in="1:attrd" out="">nostra</W>
<W lemma="lingua" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|6:relr|6:ref">lingua</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="5:subj" out="">che</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="3:man" out="1:nobj|-1:pnct|2:pnct">nel</W>
<W lemma="complesso" msd="NC" tag="NOM" in="-1:nobj" out="">complesso</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="rimanere" msd="VADR" tag="VER:pres" in="-6:relr|-6:ref" out="-3:man|1:dobj|-5:subj">rimane</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="mistero" msd="NC" tag="NOM" in="-1:nobj" out="1:ben">mistero</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:ben" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="2:nobj">i</W>
<W lemma="restante" msd="AN" tag="ADJ" in="1:attrd" out="">restanti</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:nobj" out="-1:attrd|1:nobj">5</W>
<W lemma="miliardo" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">miliardi</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="abitante" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:arg">abitanti</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj:arg" out="1:nobj">del</W>
<W lemma="mondo" msd="NC" tag="NOM" in="-1:nobj" out="">mondo</W>
<W lemma="." msd="XP" tag="SENT" in="-31:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="6:neg" out="1:pobj">“Non</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">per</W>
<W lemma="nulla" msd="RG" tag="ADV" in="-1:nobj" out="">nulla</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="1:nobj">il</W>
<W lemma="movimento" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">movimento</W>
<W lemma="cooperativo" msd="AN" tag="ADJ" in="-1:attrr" out="">cooperativo</W>
<W lemma="avere|riavere" msd="VADA" tag="VER:remo" in="" out="-3:subj|5:contr|-6:neg|1:preds">ebbe</W>
<W lemma="successo" msd="NC" tag="NOM" in="-1:preds" out="1:loc">successo</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="Danimarca" msd="NP" tag="NPR" in="-1:nobj" out="">Danimarca</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="mentre" msd="CS" tag="CON" in="-5:contr" out="1:vobj|-1:pnct">mentre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:vobj" out="1:loc">fallì</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:loc" out="1:nobj">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Scozia.”</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="2:subj" out="1:nobj">La</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">danesità</W>
<W lemma="sopravvivere" msd="VADR" tag="VER:pres" in="" out="-2:subj|1:pnct">sopravvive</W>
<W lemma="." msd="XP" tag="SENT" in="-1:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="6:coord" out="">Però</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="solo" msd="RG" tag="ADV" in="4:degr" out="-1:neg">solo</W>
<W lemma="lo" msd="PP" tag="PRO:pers" in="3:subj|4:[subj]" out="1:nobj">lo</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:nobj" out="1:attrr">stato</W>
<W lemma="sociale" msd="AN" tag="ADJ" in="-1:attrr" out="">sociale</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-3:subj|-4:degr|1:vobj|9:vobj|10:pnct|-6:coord">è</W>
<W lemma="minacciare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:pobj|-4:[subj]">minacciato</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="-1:pobj" out="1:nobj">dalla</W>
<W lemma="globalizzazione" msd="NC" tag="NOM" in="-1:nobj" out="">globalizzazione</W>
<W lemma="," msd="XP" tag="PON" in="4:pnct" out="">,</W>
<W lemma="pure" msd="RG" tag="ADV" in="4:focal" out="">pure</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="1:nobj">la</W>
<W lemma="cultura" msd="NC" tag="NOM" in="-1:nobj" out="">cultura</W>
<W lemma="il" msd="PD" tag="DET:def" in="1:dobj" out="-4:pnct">lo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-9:vobj" out="-4:focal|-3:subj|-1:dobj">è</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj|3:[subj]" out="1:nobj">La</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">danesità</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-2:subj|1:vobj|4:pnct">è</W>
<W lemma="prendere" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:pobj|-3:[subj]">presa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="mira" msd="NC" tag="NOM" in="-1:nobj" out="">mira</W>
<W lemma="." msd="XP" tag="SENT" in="-4:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="3:subj|5:[subj]" out="1:nobj">“I</W>
<W lemma="danese" msd="AN" tag="ADJ" in="-1:nobj" out="">danesi</W>
<W lemma="lo" msd="PP" tag="PRO:pers" in="1:dobj" out="">lo</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="4:qobj" out="-3:subj|-1:dobj|1:time|2:vobj|8:focal|13:cause|20:pnct">sono</W>
<W lemma="sempre" msd="RG" tag="ADV" in="-1:time" out="">sempre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:vobj" out="-5:[subj]">stati”</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="continuare" msd="VADR" tag="VER:pres" in="" out="-1:pnct|2:subj|3:pnct|-4:qobj">continua</W>
<W lemma="James" msd="NP" tag="NPR" in="1:namef" out="">James</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:subj" out="-1:namef">Mellon</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-8:focal" out="1:nobj">“anche</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">300</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="1:time">anni</W>
<W lemma="fare" msd="VADR" tag="VER:pres" in="-1:time" out="">fa</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-13:cause" out="-1:pnct|1:vobj">perciò</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="-1:vobj" out="1:preds">sono</W>
<W lemma="ottimista" msd="NC" tag="NOM" in="-1:preds" out="1:bg">ottimista</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:bg" out="1:nobj">per</W>
<W lemma="quanto" msd="PI" tag="PRO:indef" in="-1:nobj" out="2:vobj">quanto</W>
<W lemma="vi" msd="PR" tag="PRO:refl" in="1:iobj" out="">vi</W>
<W lemma="riguardare" msd="VADR" tag="VER:pres" in="-2:vobj" out="-1:iobj">riguarda</W>
<W lemma="." msd="XP" tag="SENT" in="-20:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="2:nobj">Il</W>
<W lemma="vero" msd="AN" tag="ADJ" in="1:attrd" out="">vero</W>
<W lemma="pericolo" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd">pericolo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="-3:subj|1:preds">è</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:preds" out="1:nobj">il</W>
<W lemma="livellamento" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj:dobj|6:appa">livellamento</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="-1:pobj:dobj" out="2:nobj">delle</W>
<W lemma="differente" msd="AN" tag="ADJ" in="1:attrd" out="">differenti</W>
<W lemma="cultura" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:attrr">culture</W>
<W lemma="europeo" msd="AN" tag="ADJ" in="-1:attrr" out="">europee</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-6:appa" out="-1:pnct|1:nobj">una</W>
<W lemma="sorta" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">sorta</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attrr" out="1:nobj">di</W>
<W lemma="americanizzazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attrr">americanizzazione</W>
<W lemma="dovere" msd="VAP" tag="VER:pper" in="-1:attrr" out="1:pobj">dovuta</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-1:pobj" out="2:nobj|5:conj">ai</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="1:attrd" out="">nuovi</W>
<W lemma="rapporto" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:attrr">rapporti</W>
<W lemma="commerciale" msd="AN" tag="ADJ" in="-1:attrr" out="">commerciali</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-5:conj" out="-1:coord|2:nobj">alla</W>
<W lemma="generale" msd="AN" tag="ADJ" in="1:attrd" out="">generale</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:nobj" out="-1:attrd|1:pobj:dobj">libertà</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:pobj:dobj" out="">d’insediamento.”</W>
