<p>
<s>
<W lemma="boom" msd="NC" tag="NOM" in="13:subj" out="">Boom</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">degli</W>
<W lemma="accessorio" msd="NC" tag="NOM" in="-1:nobj" out="">accessori</W>
<W lemma="nautico" msd="AN" tag="ADJ" in="" out="">nautici</W>
</s>
</p>
<p>
<s>
<W lemma="anche" msd="RG" tag="ADV" in="1:focal" out="">Anche</W>
<W lemma="il" msd="PD" tag="DET:def" in="4:subj" out="-1:focal|1:nobj">l'</W>
<W lemma="export" msd="NC" tag="NOM" in="-1:nobj" out="">export</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="motoscafo" msd="NC" tag="NOM" in="-1:nobj" out="">motoscafi</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-13:subj|-4:subj|1:preds|2:pnct|14:pnct">è</W>
<W lemma="crescere" msd="VAP" tag="VER:pper" in="-1:preds" out="6:time">cresciuto</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="2:coord" out="">ma</W>
<W lemma="relativamente" msd="RG" tag="ADV" in="1:quant" out="">relativamente</W>
<W lemma="poco" msd="RG" tag="ADV" in="5:quant" out="-2:coord|-1:quant|1:pnct">poco</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="da" msd="SP" tag="PRE" in="-6:time" out="1:nobj">da</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">44</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="-5:quant|1:nobj">50</W>
<W lemma="milione" msd="NC" tag="NOM" in="-1:nobj" out="">milioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="corona" msd="NC" tag="NOM" in="-1:nobj" out="">corone</W>
<W lemma="." msd="XP" tag="SENT" in="-14:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="c'" msd="PD" tag="PRO:demo" in="1:expl" out="">C'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-1:expl|1:time|2:preds|10:pnct">è</W>
<W lemma="poi" msd="RG" tag="ADV" in="-1:time" out="">poi</W>
<W lemma="da" msd="SP" tag="PRE" in="-2:preds" out="1:vobj">da</W>
<W lemma="aggiungere" msd="VAF" tag="VER:infi" in="-1:vobj" out="3:dobj">aggiungere</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="1:nobj">al</W>
<W lemma="quadro" msd="NC" tag="NOM" in="-1:nobj" out="">quadro</W>
<W lemma="il" msd="PD" tag="DET:def" in="-3:dobj" out="1:nobj">il</W>
<W lemma="fatturato" msd="NC" tag="NOM" in="-1:nobj" out="">fatturato</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">degli</W>
<W lemma="accessorio" msd="NC" tag="NOM" in="-1:nobj" out="">accessori</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
</s>
<s>
<W lemma="per" msd="SP" tag="PRE" in="8:time" out="1:nobj">Per</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anni</W>
<W lemma="il" msd="PD" tag="DET:def" in="6:subj" out="1:nobj">le</W>
<W lemma="cifra" msd="NC" tag="NOM" in="-1:nobj" out="">cifre</W>
<W lemma="relativo" msd="AN" tag="ADJ" in="" out="">relative</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="-1:nobj" out="1:nobj">questo</W>
<W lemma="export" msd="NC" tag="NOM" in="-1:nobj" out="">export</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="-8:time|-6:subj|1:vobj|6:pnct|9:conj|89:pnct|101:pnct">sono</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:vobj">state</W>
<W lemma="valutare" msd="VAP" tag="VER:pper" in="-1:vobj" out="1:man">valutate</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="modo" msd="NC" tag="NOM" in="-1:nobj" out="">modo</W>
<W lemma="approssimativo" msd="AN" tag="ADJ" in="" out="">approssimativo</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="2:subj" out="">che</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="risultare" msd="VADR" tag="VER:pres" in="-9:conj" out="-2:subj|-1:neg|1:man|7:pnct|8:concom|63:pnct">risultano</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="modo" msd="NC" tag="NOM" in="-1:nobj" out="">modo</W>
<W lemma="chiaro" msd="AN" tag="ADJ" in="" out="">chiaro</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dalla</W>
<W lemma="statistica|statistico" msd="NC" tag="NOM" in="-1:nobj" out="">Statistica</W>
<W lemma="danese" msd="AN" tag="ADJ" in="" out="">Danese</W>
<W lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W lemma="calcolare" msd="VAG" tag="VER:geru" in="-8:concom" out="">calcolandole</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="1:nobj">ad</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="valore" msd="NC" tag="NOM" in="-1:nobj" out="">valore</W>
<W lemma="grosso" msd="AN" tag="ADJ" in="" out="">grosso</W>
<W lemma="modo" msd="NC" tag="NOM" in="" out="">modo</W>
<W lemma="uguale" msd="AN" tag="ADJ" in="" out="">uguale</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="-1:nobj" out="5:pnct|7:conj">quello</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dell'</W>
<W lemma="esportazione" msd="NC" tag="NOM" in="-1:nobj" out="">esportazione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="natante" msd="NC" tag="NOM" in="-1:nobj" out="">natanti</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="27:coord" out="">ma</W>
<W lemma="il" msd="PD" tag="DET:def" in="-7:conj" out="1:nobj|9:pnct|10:conj">il</W>
<W lemma="responsabile" msd="NC" tag="NOM" in="-1:nobj" out="">responsabile</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dell'</W>
<W lemma="associazione" msd="NC" tag="NOM" in="-1:nobj" out="">associazione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">del</W>
<W lemma="settore" msd="NC" tag="NOM" in="-1:nobj" out="">settore</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">degli</W>
<W lemma="sport" msd="NC" tag="NOM" in="-1:nobj" out="">sport</W>
<W lemma="nautico" msd="AN" tag="ADJ" in="" out="">nautici</W>
<W lemma="," msd="XP" tag="PON" in="-9:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="-10:conj" out="1:nobj|3:appr">il</W>
<W lemma="direttore" msd="NC" tag="NOM" in="-1:nobj" out="">direttore</W>
<W lemma="John" msd="NP" tag="NPR" in="1:namef" out="">John</W>
<W lemma="Christensen" msd="NP" tag="NPR" in="-3:appr" out="-1:namef|1:pnct|13:conj">Christensen</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="6:subj" out="">che</W>
<W lemma="con" msd="SP" tag="PRE" in="5:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="-1:nobj" out="2:possd">sua</W>
<W lemma="John" msd="NP" tag="NPR" in="1:namef" out="">John</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-2:possd" out="-1:namef">Mast</W>
<W lemma="registrare" msd="VADR" tag="VER:pres" in="5:qobj" out="-6:subj|-5:man|1:dobj|4:pnct">registra</W>
<W lemma="un'" msd="PI" tag="DET:indef" in="-1:dobj" out="2:nobj">un'</W>
<W lemma="ottimo" msd="AN" tag="ADJ" in="" out="">ottima</W>
<W lemma="crescita" msd="NC" tag="NOM" in="-2:nobj" out="">crescita</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="ritenere" msd="VADR" tag="VER:pres" in="-13:conj" out="-27:coord|-5:qobj|1:dobj|2:preds">ritiene</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="-1:dobj" out="">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="-2:preds" out="1:nobj|4:pnct|6:relr">l'</W>
<W lemma="export" msd="NC" tag="NOM" in="-1:nobj" out="">export</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">degli</W>
<W lemma="accessorio" msd="NC" tag="NOM" in="-1:nobj" out="">accessori</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:subj" out="">che</W>
<W lemma="andare|riandare" msd="VADR" tag="VER:pres" in="-6:relr" out="-1:subj|4:@time|24:conj">vanno</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dagli</W>
<W lemma="albero" msd="NC" tag="NOM" in="-1:nobj" out="">alberi</W>
<W lemma="nautico" msd="AN" tag="ADJ" in="" out="">nautici</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-4:@time" out="1:nobj|6:conj">alle</W>
<W lemma="vela" msd="NC" tag="NOM" in="-1:nobj" out="">vele</W>
<W lemma="," msd="XP" tag="PON" in="-63:pnct" out="">,</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="1:nobj">ai</W>
<W lemma="completo" msd="NC" tag="NOM" in="-1:nobj" out="">completi</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="-6:conj" out="-1:coord|1:nobj">agli</W>
<W lemma="strumento" msd="NC" tag="NOM" in="-1:nobj" out="">strumenti</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="1:nobj|6:conj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">i</W>
<W lemma="vetro" msd="NC" tag="NOM" in="-1:nobj" out="">vetri</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">delle</W>
<W lemma="imbarcazione" msd="NC" tag="NOM" in="-1:nobj" out="">imbarcazioni</W>
<W lemma="e" msd="CS" tag="CON" in="7:coord" out="">e</W>
<W lemma="per" msd="SP" tag="PRE" in="-6:conj" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:nobj" out="1:nobj">le</W>
<W lemma="barca" msd="NC" tag="NOM" in="-1:nobj" out="">barche</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="vela" msd="NC" tag="NOM" in="-1:nobj" out="">vela</W>
<W lemma="," msd="XP" tag="PON" in="-89:pnct" out="">,</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="-24:conj" out="-7:coord|1:time|2:vobj">ha</W>
<W lemma="ora" msd="RG" tag="ADV" in="-1:time" out="">ora</W>
<W lemma="raggiungere" msd="VAP" tag="VER:pper" in="-2:vobj" out="1:dobj">raggiunto</W>
<W lemma="un" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj|3:relr">un</W>
<W lemma="volume" msd="NC" tag="NOM" in="-1:nobj" out="">volume</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="1:subj" out="">che</W>
<W lemma="superare" msd="VADR" tag="VER:pres" in="-3:relr" out="-1:subj|1:dobj">supera</W>
<W lemma="il" msd="PD" tag="DET:def" in="-1:dobj" out="1:nobj">l'</W>
<W lemma="export" msd="NC" tag="NOM" in="-1:nobj" out="">export</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">dei</W>
<W lemma="natante" msd="NC" tag="NOM" in="-1:nobj" out="">natanti</W>
<W lemma="." msd="XP" tag="SENT" in="-101:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="12:time" out="1:nobj|4:pnct">Sul</W>
<W lemma="fronte" msd="NC" tag="NOM" in="-1:nobj" out="">fronte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="1:nobj">delle</W>
<W lemma="importazione" msd="NC" tag="NOM" in="-1:nobj" out="">importazioni</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="7:subj" out="1:nobj">il</W>
<W lemma="numero" msd="NC" tag="NOM" in="-1:nobj" out="">numero</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="2:nobj">di</W>
<W lemma="grande" msd="AN" tag="ADJ" in="" out="">grandi</W>
<W lemma="barca" msd="NC" tag="NOM" in="-2:nobj" out="">barche</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="vela" msd="NC" tag="NOM" in="-1:nobj" out="">vela</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="-12:time|-7:subj|1:man|2:preds|3:pnct|5:preds|17:pnct|22:conj|37:pnct">è</W>
<W lemma="certamente" msd="RG" tag="ADV" in="-1:man" out="">certamente</W>
<W lemma="salire" msd="VAP" tag="VER:pper" in="-2:preds" out="">salito</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="quasi" msd="RG" tag="ADV" in="1:quant" out="">quasi</W>
<W lemma="raddoppiare" msd="VAP" tag="VER:pper" in="-5:preds" out="-1:quant|1:time|5:time">raddoppiato</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:time" out="1:nobj">da</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">42</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">23</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="-5:time" out="2:nobj">nello</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="periodo" msd="NC" tag="NOM" in="-2:nobj" out="">periodo</W>
<W lemma="rispettare" msd="VADR" tag="VER:pres" in="" out="">rispetto</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="1:nobj">all'</W>
<W lemma="anno" msd="NC" tag="NOM" in="-1:nobj" out="">anno</W>
<W lemma="precedente" msd="AN" tag="ADJ" in="" out="">precedente</W>
<W lemma="," msd="XP" tag="PON" in="-17:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="4:coord" out="">ma</W>
<W lemma="il" msd="PD" tag="DET:def" in="3:subj" out="1:nobj">il</W>
<W lemma="valore" msd="NC" tag="NOM" in="-1:nobj" out="">valore</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-22:conj" out="-4:coord|-3:subj|1:quant|2:preds|3:pnct">è</W>
<W lemma="quasi" msd="RG" tag="ADV" in="-1:quant" out="">quasi</W>
<W lemma="dimezzare" msd="VAP" tag="VER:pper" in="-2:preds" out="2:time">dimezzato</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="da" msd="SP" tag="PRE" in="-2:time" out="1:nobj">da</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">20</W>
<W lemma="milione" msd="NC" tag="NOM" in="-1:nobj" out="">milioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="corona" msd="NC" tag="NOM" in="-1:nobj" out="">corone</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="2:nobj">a</W>
<W lemma="neppure" msd="RG" tag="ADV" in="1:quant" out="">neppure</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-2:nobj" out="-1:quant|1:nobj">11</W>
<W lemma="milione" msd="NC" tag="NOM" in="-1:nobj" out="">milioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="corona" msd="NC" tag="NOM" in="-1:nobj" out="">corone</W>
<W lemma="." msd="XP" tag="SENT" in="-37:pnct" out="">.</W>
</s>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj" out="1:nobj">I</W>
<W lemma="motoscafo" msd="NC" tag="NOM" in="-1:nobj" out="">motoscafi</W>
<W lemma="vantare" msd="VADR" tag="VER:pres" in="" out="-2:subj|1:dobj|5:pnct|9:conj|20:pnct">vantano</W>
<W lemma="una" msd="PI" tag="DET:indef" in="-1:dobj" out="1:nobj">una</W>
<W lemma="cifra" msd="NC" tag="NOM" in="-1:nobj" out="">cifra</W>
<W lemma="quasi" msd="RG" tag="ADV" in="1:quant" out="">quasi</W>
<W lemma="uguale" msd="AN" tag="ADJ" in="" out="-1:quant">uguale</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="3:coord" out="">ma</W>
<W lemma="il" msd="PD" tag="DET:def" in="2:subj" out="1:nobj">il</W>
<W lemma="valore" msd="NC" tag="NOM" in="-1:nobj" out="">valore</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="-9:conj" out="-3:coord|-2:subj|1:preds|3:pnct|4:preds">è</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:preds" out="1:nobj">in</W>
<W lemma="discesa" msd="NC" tag="NOM" in="-1:nobj" out="">discesa</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="da" msd="SP" tag="PRE" in="-4:preds" out="1:nobj">da</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="">39</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="1:nobj">a</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">28</W>
<W lemma="milione" msd="NC" tag="NOM" in="-1:nobj" out="">milioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="1:nobj">di</W>
<W lemma="corona" msd="NC" tag="NOM" in="-1:nobj" out="">corone</W>
<W lemma="." msd="XP" tag="SENT" in="-20:pnct" out="">.</W>
</s>
</p>
