<W id="0" lemma="il" msd="PD" tag="DET&3a;def" in="3:subj" out="1:nobj">Gli</W>
<W id="1" lemma="argomento" msd="NC" tag="NOM" in="-1:nobj" out="">argomenti</W>
<W id="2" lemma="comunque" msd="RG" tag="ADV" in="1:eval" out="">comunque</W>
<W id="3" lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|-1:eval|1:preds|2:pnct|5:xpl|51:pnct|52:+CONJ&3a;add/anche">sono</W>
<W id="4" lemma="chiaro" msd="AN" tag="ADJ" in="-1:preds" out="">chiari</W>
<W id="5" lemma="&3a;" msd="XP" tag="PON" in="-2:pnct" out="">:</W>
<W id="6" lemma="il" msd="PD" tag="DET&3a;def" in="2:subj|3:[subj]" out="1:nobj">lo</W>
<W id="7" lemma="stato" msd="NC" tag="NOM" in="-1:nobj" out="">stato</W>
<W id="8" lemma="dovere" msd="VADR" tag="VER&3a;pres" in="-5:xpl" out="-2:subj|1:vobj|36:pnct|38:coref-res|44:conj">deve</W>
<W id="9" lemma="preservare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-3:[subj]|1:dobj">preservare</W>
<W id="10" lemma="ciò" msd="PD" tag="PRO&3a;demo" in="-1:dobj" out="2:ref|3:relr">ciò</W>
<W id="11" lemma="di" msd="SP" tag="PRE" in="3:pobj" out="1:nobj">di</W>
<W id="12" lemma="cui" msd="PT" tag="PRO&3a;rela" in="-1:nobj|-2:ref" out="">cui</W>
<W id="13" lemma="fare" msd="VADR" tag="VER&3a;pres" in="-3:relr" out="1:dobj|2:subj|4:pnct|5:elab">fa</W>
<W id="14" lemma="uso" msd="NC" tag="NOM" in="-1:dobj" out="-3:pobj">uso</W>
<W id="15" lemma="il" msd="PD" tag="DET&3a;def" in="-2:subj" out="1:nobj">la</W>
<W id="16" lemma="collettività" msd="NC" tag="NOM" in="-1:nobj" out="">collettività</W>
<W id="17" lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W id="18" lemma="cioè" msd="RG" tag="ADV" in="-5:elab" out="1:nobj">cioè</W>
<W id="19" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|20:conj">i</W>
<W id="20" lemma="sentiero" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|1:{goal}">sentieri</W>
<W id="21" lemma="per" msd="SP" tag="PRE" in="-1:attr|-1:{goal}" out="1:vobj|3:pnct|4:conj|7:pnct|8:conj|13:pnct|14:conj|17:pnct">per</W>
<W _noerror="&3a;nosubj&3a;" id="22" lemma="fare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:dobj">fare</W>
<W id="23" lemma="allenamento" msd="NC" tag="NOM" in="-1:dobj" out="">allenamento</W>
<W id="24" lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W id="25" lemma="per" msd="SP" tag="PRE" in="-4:conj" out="1:nobj">per</W>
<W id="26" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">il</W>
<W id="27" lemma="jogging" msd="NC" tag="NOM" in="-1:nobj" out="">jogging</W>
<W id="28" lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W id="29" lemma="per" msd="SP" tag="PRE" in="-8:conj" out="1:nobj">per</W>
<W id="30" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">le</W>
<W id="31" lemma="gara" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|1:{goal}#">gare</W>
<W id="32" lemma="di" msd="SP" tag="PRE" in="-1:attr|-1:{goal}#" out="1:nobj">di</W>
<W id="33" lemma="orientamento" msd="NC" tag="NOM" in="-1:nobj" out="">orientamento</W>
<W id="34" lemma="," msd="XP" tag="PON" in="-13:pnct" out="">,</W>
<W id="35" lemma="per" msd="SP" tag="PRE" in="-14:conj" out="1:nobj">per</W>
<W id="36" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">i</W>
<W id="37" lemma="cavallo" msd="NC" tag="NOM" in="-1:nobj" out="">cavalli</W>
<W id="38" lemma="," msd="XP" tag="PON" in="-17:pnct" out="">,</W>
<W id="39" lemma="il" msd="PD" tag="DET&3a;def" in="-20:conj" out="1:nobj|33:coref-iden">gli</W>
<W id="40" lemma="accesso" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|1:{goal}|2:man">accessi</W>
<W id="41" lemma="pubblico" msd="AN" tag="ADJ" in="-1:attr|-1:{goal}" out="">pubblici</W>
<W id="42" lemma="in" msd="SP" tag="PRE" in="-2:man" out="1:attr">in</W>
<W id="43" lemma="generale" msd="AN" tag="ADJ" in="-1:attr" out="">generale</W>
<W id="44" lemma="," msd="XP" tag="PON" in="-36:pnct" out="">,</W>
<W id="45" lemma="e" msd="CS" tag="CON" in="7:coord" out="">e</W>
<W id="46" lemma="questo" msd="PD" tag="PRO&3a;demo" in="-38:coref-res|6:xtop" out="5:ref">questo</W>
<W id="47" lemma="il" msd="PD" tag="DET&3a;def" in="5:subj|6:[subj]" out="2:nobj|29:coref-var">i</W>
<W id="48" lemma="singolo" msd="AN" tag="ADJ" in="1:attr" out="">singoli</W>
<W id="49" lemma="cacciatore" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">cacciatori</W>
<W id="50" lemma="non" msd="RG" tag="ADV" in="2:neg" out="">non</W>
<W id="51" lemma="lo" msd="PP" tag="PRO&3a;pers" in="-5:ref|2:dobj" out="">lo</W>
<W id="52" lemma="potere" msd="VADR" tag="VER&3a;pres" in="-44:conj" out="-6:xtop|-7:coord|-2:neg|-5:subj|1:vobj">possono</W>
<W id="53" lemma="assicurare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-6:[subj]|-2:dobj">assicurare</W>
<W id="54" lemma="." msd="XP" tag="SENT" in="-51:pnct" out="">.</W>
<W id="55" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-52:+CONJ&3a;add/anche" out="1:add|2:preds|4:conc|6:subj|28:CONJ&3a;add/inoltre">E'</W>
<W id="56" lemma="anche" msd="RG" tag="ADV" in="-1:add" out="">anche</W>
<W id="57" lemma="evidente" msd="AN" tag="ADJ" in="-2:preds" out="">evidente</W>
<W id="58" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="59" lemma="tuttavia" msd="RG" tag="ADV" in="-4:conc" out="-1:pnct|1:pnct">tuttavia</W>
<W id="60" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="61" lemma="che" msd="PT" tag="PRO&3a;rela" in="-6:subj" out="7:vobj">che</W>
<W id="62" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="6:loc" out="1:nobj|3:conj">nei</W>
<W id="63" lemma="bosco" msd="NC" tag="NOM" in="-1:nobj" out="">boschi</W>
<W id="64" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="65" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">nei</W>
<W id="66" lemma="terreno" msd="AN" tag="ADJ" in="-1:nobj" out="1:attr">terreni</W>
<W id="67" lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="">privati</W>
<W id="68" lemma="coesistere" msd="VADR" tag="VER&3a;pres" in="-7:vobj" out="-6:loc|1:man|4:subj|10:pnct">coesistono</W>
<W id="69" lemma="senza" msd="SP" tag="PRE" in="-1:man" out="1:nobj">senza</W>
<W id="70" lemma="difficoltà" msd="NC" tag="NOM" in="-1:nobj" out="">difficoltà</W>
<W id="71" lemma="sia" msd="CS" tag="CON" in="4:correl" out="">sia</W>
<W id="72" lemma="il" msd="PD" tag="DET&3a;def" in="-4:subj|-33:coref-iden" out="1:nobj|4:conj|9:assoc-telic">gli</W>
<W id="73" lemma="accesso" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|1:{goal}">accessi</W>
<W id="74" lemma="pubblico" msd="AN" tag="ADJ" in="-1:attr|-1:{goal}" out="">pubblici</W>
<W id="75" lemma="che" msd="PT" tag="PRO&3a;rela" in="1:coord" out="-4:correl">che</W>
<W id="76" lemma="il" msd="PD" tag="DET&3a;def" in="-4:conj|-29:coref-var" out="-1:coord|1:nobj|12:assoc-telic">i</W>
<W id="77" lemma="cacciatore" msd="NC" tag="NOM" in="-1:nobj" out="">cacciatori</W>
<W id="78" lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W id="79" lemma="il" msd="PD" tag="DET&3a;def" in="4:subj" out="1:nobj">Le</W>
<W id="80" lemma="statistica&7c;statistico" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj|1:{arg}">statistiche</W>
<W id="81" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj|-1:{arg}|-9:assoc-telic" out="1:nobj">del</W>
<W id="82" lemma="settore" msd="NC" tag="NOM" in="-1:nobj" out="">settore</W>
<W id="83" lemma="dimostrare" msd="VADR" tag="VER&3a;pres" in="-28:CONJ&3a;add/inoltre" out="-4:subj|2:add|4:dobj|19:pnct|64:+CONST&3a;exem/ad_esempio">dimostrano</W>
<W id="84" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="85" lemma="inoltre" msd="RG" tag="ADV" in="-2:add" out="-1:pnct|1:pnct">inoltre</W>
<W id="86" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="87" lemma="che" msd="PT" tag="PRO&3a;rela" in="-4:dobj" out="6:vobj">che</W>
<W id="88" lemma="il" msd="PD" tag="DET&3a;def" in="-12:assoc-telic|5:subj" out="1:nobj|15:assoc-patient|54:coref-iden|10:coref">la</W>
<W id="89" lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W id="90" lemma="in" msd="SP" tag="PRE" in="3:eval" out="1:nobj">in</W>
<W id="91" lemma="realtà" msd="NC" tag="NOM" in="-1:nobj" out="">realtà</W>
<W id="92" lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W id="93" lemma="avvantaggiare" msd="VADR" tag="VER&3a;pres" in="-6:vobj" out="-1:robj|-5:subj|-3:eval|1:pobj|12:CONJ&3a;elab">avvantaggia</W>
<W id="94" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">del</W>
<W id="95" lemma="fare" msd="VAP" tag="VER&3a;pper" in="-1:nobj" out="1:nobj">fatto</W>
<W id="96" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:nobj" out="3:vobj">che</W>
<W id="97" lemma="se" msd="CS" tag="CON" in="2:robj" out="">se</W>
<W id="98" lemma="ne" msd="RG" tag="ADV" in="1:dobj|-10:coref" out="">ne</W>
<W id="99" lemma="occupare" msd="VADR" tag="VER&3a;cpre" in="-3:vobj" out="-1:dobj|-2:robj|1:subj">occupino</W>
<W id="100" lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj" out="1:attr|78:coref-var">i</W>
<W id="101" lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="">privati</W>
<W id="102" lemma="." msd="XP" tag="SENT" in="-19:pnct" out="">.</W>
<W id="103" lemma="il" msd="PD" tag="DET&3a;def" in="-15:assoc-patient|2:subj" out="1:nobj|4:assoc-telic|13:coref-iden">La</W>
<W id="104" lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W id="105" lemma="aumentare" msd="VADR" tag="VER&3a;pres" in="-12:CONJ&3a;elab" out="-2:subj|1:pnct|4:conj|7:conj|17:pnct">aumenta</W>
<W id="106" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="107" lemma="il" msd="PD" tag="DET&3a;def" in="-4:assoc-telic|2:subj" out="1:nobj">l'</W>
<W id="108" lemma="alimentazione" msd="NC" tag="NOM" in="-1:nobj" out="">alimentazione</W>
<W id="109" lemma="migliorare" msd="VADR" tag="VER&3a;pres" in="-4:conj" out="-2:subj">migliora</W>
<W id="110" lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W id="111" lemma="si" msd="PP" tag="PRO&3a;pers" in="1:subj" out="">si</W>
<W id="112" lemma="prestare" msd="VADR" tag="VER&3a;pres" in="-7:conj" out="-1:subj|-2:coord|2:dobj">presta</W>
<W id="113" lemma="maggiore" msd="AN" tag="ADJ" in="1:attr" out="">maggiore</W>
<W id="114" lemma="attenzione" msd="NC" tag="NOM" in="-2:dobj" out="-1:attr|2:pobj">attenzione</W>
<W id="115" lemma="sia" msd="CS" tag="CON" in="3:correl" out="">sia</W>
<W id="116" lemma="al" msd="SP+P" tag="PRE&3a;det" in="-2:pobj|-13:coref-iden" out="1:nobj|3:conj|29:coref-iden">alla</W>
<W id="117" lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W id="118" lemma="che" msd="PT" tag="PRO&3a;rela" in="1:coord" out="-3:correl">che</W>
<W id="119" lemma="al" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">alle</W>
<W id="120" lemma="zona" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">zone</W>
<W id="121" lemma="naturale" msd="AN" tag="ADJ" in="-1:attr" out="">naturali</W>
<W id="122" lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W id="123" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="24:loc" out="1:nobj|5:exem|9:ref|38:assoc-loc">Nel</W>
<W id="124" lemma="sud" msd="NC" tag="NOM" in="-1:nobj|1:{apart}" out="1:pobj|13:relr">sud</W>
<W id="125" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="-1:{apart}|1:nobj">della</W>
<W id="126" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Selandia</W>
<W id="127" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="128" lemma="ad" msd="SP" tag="PRE" in="-5:exem" out="-1:pnct|1:nobj|2:pnct">ad</W>
<W id="129" lemma="esempio" msd="NC" tag="NOM" in="-1:nobj" out="">esempio</W>
<W id="130" lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W id="131" lemma="in" msd="SP" tag="PRE" in="6:loc" out="1:nobj">in</W>
<W id="132" lemma="cui" msd="PT" tag="PRO&3a;rela" in="-1:nobj|-9:ref" out="">cui</W>
<W id="133" lemma="gran" msd="AN" tag="ADJ" in="1:attr" out="">gran</W>
<W id="134" lemma="parte" msd="NC" tag="NOM" in="1:{apart}|3:subj|4:[subj]" out="-1:attr|1:pobj">parte</W>
<W id="135" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="-1:{apart}|1:nobj">dei</W>
<W id="136" lemma="terreno" msd="NC" tag="NOM" in="-1:nobj" out="">terreni</W>
<W id="137" lemma="essere" msd="VADR" tag="VER&3a;pres" in="-13:relr" out="-6:loc|-3:subj|1:vobj|7:pnct">è</W>
<W id="138" lemma="affittare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:agent|3:goal">affittata</W>
<W id="139" lemma="da" msd="SP" tag="PRE" in="-1:agent" out="1:attr">da</W>
<W id="140" lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="">privati</W>
<W id="141" lemma="per" msd="SP" tag="PRE" in="-3:goal" out="1:nobj">per</W>
<W id="142" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj|-54:coref-iden" out="1:nobj|23:coref-var">la</W>
<W id="143" lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W id="144" lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W id="145" lemma="il" msd="PD" tag="DET&3a;def" in="-29:coref-iden|2:subj" out="1:nobj">la</W>
<W id="146" lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W id="147" lemma="essere" msd="VADR" tag="VER&3a;pres" in="-64:+CONST&3a;exem/ad_esempio" out="-2:subj|-24:loc|3:preds|8:conj|21:pnct|48:pnct|56:CONTR&3a;dir/invece">è</W>
<W id="148" lemma="molto" msd="RG" tag="ADV" in="2:quant" out="1:avobj">molto</W>
<W id="149" lemma="più" msd="RG" tag="ADV" in="-1:avobj" out="">più</W>
<W id="150" lemma="abbondante" msd="AN" tag="ADJ" in="-3:preds" out="-2:quant">abbondante</W>
<W id="151" lemma="e" msd="CS" tag="CON" in="4:coord" out="">e</W>
<W id="152" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="3:time" out="1:nobj">nel</W>
<W id="153" lemma="contempo" msd="NC" tag="NOM" in="-1:nobj" out="">contempo</W>
<W id="154" lemma="c'" msd="PD" tag="PRO&3a;demo" in="1:expl" out="">c'</W>
<W id="155" lemma="essere" msd="VADR" tag="VER&3a;pres" in="-8:conj" out="-4:coord|-1:expl|-3:time|1:dobj|14:cause">è</W>
<W id="156" lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W id="157" lemma="rapporto" msd="NC" tag="NOM" in="-1:nobj" out="2:attr|3:attr|3:{agent}">rapporto</W>
<W id="158" lemma="più" msd="RG" tag="ADV" in="1:quant" out="">più</W>
<W id="159" lemma="naturale" msd="AN" tag="ADJ" in="-2:attr" out="-1:quant">naturale</W>
<W id="160" lemma="tra" msd="SP" tag="PRE" in="-3:attr|-3:{agent}" out="1:nobj">tra</W>
<W id="161" lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj|-38:assoc-loc" out="1:nobj|4:conj|10:coref-var">la</W>
<W id="162" lemma="popolazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">popolazione</W>
<W id="163" lemma="locale" msd="AN" tag="ADJ" in="-1:attr" out="">locale</W>
<W id="164" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="165" lemma="il" msd="PD" tag="DET&3a;def" in="-4:conj|-23:coref-var" out="-1:coord|1:nobj|2:focal|12:assoc-agentive">la</W>
<W id="166" lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W id="167" lemma="stesso" msd="AN" tag="ADJ" in="-2:focal" out="">stessa</W>
<W id="168" lemma="," msd="XP" tag="PON" in="-21:pnct" out="">,</W>
<W id="169" lemma="visto" msd="CS" tag="CON" in="-14:cause" out="1:dobj">visto</W>
<W id="170" lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="3:vobj">che</W>
<W id="171" lemma="il" msd="PD" tag="DET&3a;def" in="-10:coref-var|2:subj|5:[subj]|10:[subj]|17:[subj]" out="1:nobj">la</W>
<W id="172" lemma="gente" msd="NC" tag="NOM" in="-1:nobj" out="">gente</W>
<W id="173" lemma="essere" msd="VADR" tag="VER&3a;pres" in="-3:vobj" out="-2:subj|1:preds|6:pnct|8:conj">è</W>
<W id="174" lemma="abituare" msd="VAP" tag="VER&3a;pper" in="-1:preds" out="1:pobj">abituata</W>
<W id="175" lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W id="176" lemma="vedere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-5:[subj]|1:dobj">vedere</W>
<W id="177" lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj|-12:assoc-agentive" out="1:nobj">i</W>
<W id="178" lemma="cacciatore" msd="NC" tag="NOM" in="-1:nobj|-78:coref-var" out="">cacciatori</W>
<W id="179" lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W id="180" lemma="si" msd="PP" tag="PRO&3a;pers" in="1:robj" out="">si</W>
<W id="181" lemma="nutrire" msd="VADR" tag="VER&3a;pres" in="-8:conj" out="-1:robj|-10:[subj]|1:quant|4:pobj|7:conj">nutre</W>
<W id="182" lemma="con" msd="SP" tag="PRE" in="-1:quant" out="2:nobj">con</W>
<W id="183" lemma="maggiore" msd="AN" tag="ADJ" in="1:attr" out="">maggiore</W>
<W id="184" lemma="frequenza" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">frequenza</W>
<W id="185" lemma="di" msd="SP" tag="PRE" in="-4:pobj" out="1:nobj">di</W>
<W id="186" lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W id="187" lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W id="188" lemma="godere" msd="VADR" tag="VER&3a;pres" in="-7:conj" out="-17:[subj]|-1:coord|1:pobj|3:man">gode</W>
<W id="189" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">della</W>
<W id="190" lemma="natura" msd="NC" tag="NOM" in="-1:nobj" out="">natura</W>
<W id="191" lemma="in" msd="SP" tag="PRE" in="-3:man" out="1:nobj">in</W>
<W id="192" lemma="maniera" msd="NC" tag="NOM" in="-1:nobj" out="2:attr">maniera</W>
<W id="193" lemma="più" msd="RG" tag="ADV" in="1:quant" out="">più</W>
<W id="194" lemma="pieno" msd="AN" tag="ADJ" in="-2:attr" out="-1:quant">piena</W>
<W id="195" lemma="." msd="XP" tag="SENT" in="-48:pnct" out="">.</W>
<W id="196" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="7:loc" out="1:nobj|48:assoc-loc">Nel</W>
<W id="197" lemma="nord" msd="NC" tag="NOM" in="-1:nobj|1:{apart}" out="1:pobj">nord</W>
<W id="198" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="-1:{apart}|1:nobj">della</W>
<W id="199" lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Selandia</W>
<W id="200" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="201" lemma="invece" msd="RG" tag="ADV" in="2:contr" out="-1:pnct|1:pnct">invece</W>
<W id="202" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="203" lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-56:CONTR&3a;dir/invece" out="-7:loc|-2:contr|1:subj|4:preds|14:pnct|15:time|21:pnct|39:coref-res|25:CONJ&3a;elab">sono</W>
<W id="204" lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj|4:[subj]" out="1:nobj">i</W>
<W id="205" lemma="dipendente" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">dipendenti</W>
<W id="206" lemma="statale" msd="AN" tag="ADJ" in="-1:attr" out="">statali</W>
<W id="207" lemma="ad" msd="SP" tag="PRE" in="-4:preds" out="1:vobj">ad</W>
<W id="208" lemma="andare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-4:[subj]|1:@dir|6:time">andare</W>
<W id="209" lemma="a" msd="SP" tag="PRE" in="-1:@dir" out="1:nobj">a</W>
<W id="210" lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="2:man|15:assoc-telic">caccia</W>
<W id="211" lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W id="212" lemma="discretamente" msd="RG" tag="ADV" in="-2:man" out="-1:pnct|1:pnct">discretamente</W>
<W id="213" lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W id="214" lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-6:time" out="1:nobj">nei</W>
<W id="215" lemma="giorno" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|1:{goal}#">giorni</W>
<W id="216" lemma="feriale" msd="AN" tag="ADJ" in="-1:attr|-1:{goal}#" out="">feriali</W>
<W id="217" lemma="," msd="XP" tag="PON" in="-14:pnct" out="">,</W>
<W id="218" lemma="quando" msd="CS" tag="CON" in="-15:time" out="3:vobj">quando</W>
<W id="219" lemma="il" msd="PD" tag="DET&3a;def" in="2:subj" out="1:attr">gli</W>
<W id="220" lemma="altro" msd="AN" tag="ADJ" in="-1:attr" out="">altri</W>
<W id="221" lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-3:vobj" out="-2:subj|1:preds">sono</W>
<W id="222" lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:preds" out="1:nobj">al</W>
<W id="223" lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="">lavoro</W>
<W id="224" lemma="." msd="XP" tag="SENT" in="-21:pnct" out="">.</W>
<W id="225" lemma="il" msd="PD" tag="DET&3a;def" in="-15:assoc-telic|3:subj" out="1:nobj">La</W>
<W id="226" lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W id="227" lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W id="228" lemma="vendere" msd="VADR" tag="VER&3a;pres" in="-25:CONJ&3a;elab" out="-3:subj|-1:robj|1:pobj|7:man|12:pnct|15:;TELIC&3a;cons.dir">vende</W>
<W id="229" lemma="ad" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">ad</W>
<W id="230" lemma="una" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">una</W>
<W id="231" lemma="cerchia" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">cerchia</W>
<W id="232" lemma="restringere&7c;ristringere" msd="VAP" tag="VER&3a;pper" in="-1:attr" out="1:pobj">ristretta</W>
<W id="233" lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W id="234" lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="">persone</W>
<W id="235" lemma="a" msd="SP" tag="PRE" in="-7:man" out="1:nobj">a</W>
<W id="236" lemma="vantaggio" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj.iobj|1:{recipient}">vantaggio</W>
<W id="237" lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj.iobj|-1:{recipient}" out="1:nobj">delle</W>
<W id="238" lemma="cassa" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">casse</W>
<W id="239" lemma="statale" msd="AN" tag="ADJ" in="-1:attr" out="">statali</W>
<W id="240" lemma=";" msd="XP" tag="PON" in="-12:pnct" out="">;</W>
<W id="241" lemma="tutto" msd="AN" tag="ADJ" in="2:subj" out="1:nobj">tutto</W>
<W id="242" lemma="questo" msd="PD" tag="PRO&3a;demo" in="-1:nobj|-39:coref-res" out="">questo</W>
<W id="243" lemma="allontanare" msd="VADR" tag="VER&3a;pres" in="-15:;TELIC&3a;cons.dir" out="-2:subj|1:dobj|3:@dir|10:pnct">allontana</W>
<W id="244" lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj|-48:assoc-loc" out="1:nobj">la</W>
<W id="245" lemma="gente" msd="NC" tag="NOM" in="-1:nobj" out="">gente</W>
<W id="246" lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-3:@dir" out="1:nobj|4:pnct|5:appa">dall'</W>
<W id="247" lemma="attività" msd="NC" tag="NOM" in="-1:nobj" out="2:attr">attività</W>
<W id="248" lemma="più" msd="RG" tag="ADV" in="1:quant" out="">più</W>
<W id="249" lemma="naturale" msd="AN" tag="ADJ" in="-2:attr" out="-1:quant">naturale</W>
<W id="250" lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W id="251" lemma="il" msd="PD" tag="DET&3a;def" in="-5:appa" out="1:nobj">la</W>
<W id="252" lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W id="253" lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
