<W lemma="il" msd="PD" tag="DET&3a;def" in="3:subj" out="1:nobj">Gli</W>
<W lemma="argomento" msd="NC" tag="NOM" in="-1:nobj" out="">argomenti</W>
<W lemma="comunque" msd="RG" tag="ADV" in="1:eval" out="">comunque</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|-1:eval|2:pnct|5:xpl|51:pnct|1:preds">sono</W>
<W lemma="chiaro" msd="AN" tag="ADJ" in="-1:preds" out="">chiari</W>
<W lemma="&3a;" msd="XP" tag="PON" in="-2:pnct" out="">:</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj|3:[subj]" out="1:nobj">lo</W>
<W lemma="stato" msd="NC" tag="NOM" in="-1:nobj" out="">stato</W>
<W lemma="dovere" msd="VADR" tag="VER&3a;pres" in="-5:xpl" out="-2:subj|1:vobj|36:pnct|38:coref-res|44:conj">deve</W>
<W lemma="preservare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-3:[subj]|1:dobj">preservare</W>
<W lemma="ciò" msd="PD" tag="PRO&3a;demo" in="-1:dobj" out="2:ref|3:relr">ciò</W>
<W lemma="di" msd="SP" tag="PRE" in="3:pobj" out="1:nobj">di</W>
<W lemma="cui" msd="PT" tag="PRO&3a;rela" in="-1:nobj|-2:ref" out="">cui</W>
<W lemma="fare" msd="VADR" tag="VER&3a;pres" in="-3:relr" out="1:dobj|2:subj|4:pnct|5:elab">fa</W>
<W lemma="uso" msd="NC" tag="NOM" in="-1:dobj" out="-3:pobj">uso</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-2:subj" out="1:nobj">la</W>
<W lemma="collettività" msd="NC" tag="NOM" in="-1:nobj" out="">collettività</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="cioè" msd="RG" tag="ADV" in="-5:elab" out="1:nobj">cioè</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|5:pnct|20:conj">i</W>
<W lemma="sentiero" msd="NC" tag="NOM" in="-1:nobj" out="1:goal">sentieri</W>
<W lemma="per" msd="SP" tag="PRE" in="-1:goal" out="1:vobj|4:conj|7:pnct|8:conj|13:pnct|14:conj|17:pnct">per</W>
<W _noerror="&3a;nosubj&3a;" lemma="fare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:dobj">fare</W>
<W lemma="allenamento" msd="NC" tag="NOM" in="-1:dobj" out="">allenamento</W>
<W lemma="," msd="XP" tag="PON" in="-5:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="-4:conj" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">il</W>
<W lemma="jogging" msd="NC" tag="NOM" in="-1:nobj" out="">jogging</W>
<W lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="-8:conj" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">le</W>
<W lemma="gara" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;func#">gare</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj&3a;func#" out="1:nobj">di</W>
<W lemma="orientamento" msd="NC" tag="NOM" in="-1:nobj" out="">orientamento</W>
<W lemma="," msd="XP" tag="PON" in="-13:pnct" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="-14:conj" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">i</W>
<W lemma="cavallo" msd="NC" tag="NOM" in="-1:nobj" out="">cavalli</W>
<W lemma="," msd="XP" tag="PON" in="-17:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-20:conj" out="1:nobj">gli</W>
<W lemma="accesso" msd="NC" tag="NOM" in="-1:nobj" out="1:attr|2:other">accessi</W>
<W lemma="pubblico" msd="AN" tag="ADJ" in="-1:attr" out="">pubblici</W>
<W lemma="in" msd="SP" tag="PRE" in="-2:other" out="1:attr">in</W>
<W lemma="generale" msd="AN" tag="ADJ" in="-1:attr" out="">generale</W>
<W lemma="," msd="XP" tag="PON" in="-36:pnct" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="7:coord" out="">e</W>
<W lemma="questo" msd="PD" tag="PRO&3a;demo" in="-38:coref-res|6:xtop" out="5:ref">questo</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="5:subj|6:[subj]" out="2:nobj">i</W>
<W lemma="singolo" msd="AN" tag="ADJ" in="1:attr" out="">singoli</W>
<W lemma="cacciatore" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr|33:assoc-const">cacciatori</W>
<W lemma="non" msd="RG" tag="ADV" in="2:neg" out="">non</W>
<W lemma="lo" msd="PP" tag="PRO&3a;pers" in="-5:ref|1:dobj" out="">lo</W>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="-44:conj" out="-6:xtop|-1:dobj|-7:coord|-2:neg|-5:subj|1:vobj">possono</W>
<W lemma="assicurare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-6:[subj]">assicurare</W>
<W lemma="." msd="XP" tag="SENT" in="-51:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="4:conc|6:nobj|2:preds">E'</W>
<W lemma="anche" msd="RG" tag="ADV" in="1:focal" out="">anche</W>
<W lemma="evidente" msd="AN" tag="ADJ" in="-2:preds" out="-1:focal">evidente</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="tuttavia" msd="RG" tag="ADV" in="-4:conc" out="-1:pnct|1:pnct">tuttavia</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-6:nobj" out="7:vobj">che</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="6:loc" out="1:nobj|3:conj">nei</W>
<W lemma="bosco" msd="NC" tag="NOM" in="-1:nobj" out="">boschi</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">nei</W>
<W lemma="terreno" msd="AN" tag="ADJ" in="-1:nobj" out="1:attr">terreni</W>
<W lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="">privati</W>
<W lemma="coesistere" msd="VADR" tag="VER&3a;pres" in="-7:vobj" out="-6:loc|1:man|4:subj|10:pnct">coesistono</W>
<W lemma="senza" msd="SP" tag="PRE" in="-1:man" out="1:nobj">senza</W>
<W lemma="difficoltà" msd="NC" tag="NOM" in="-1:nobj" out="">difficoltà</W>
<W lemma="sia" msd="CS" tag="CON" in="4:correl" out="">sia</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-4:subj" out="1:nobj|4:conj">gli</W>
<W lemma="accesso" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">accessi</W>
<W lemma="pubblico" msd="AN" tag="ADJ" in="-1:attr" out="">pubblici</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="1:coord" out="-4:correl">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-4:conj" out="-1:coord|1:nobj">i</W>
<W lemma="cacciatore" msd="NC" tag="NOM" in="-1:nobj" out="">cacciatori</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="4:subj" out="1:nobj">Le</W>
<W lemma="statistica&7c;statistico" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg">statistiche</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:nobj">del</W>
<W lemma="settore" msd="NC" tag="NOM" in="-1:nobj|-33:assoc-const" out="">settore</W>
<W lemma="dimostrare" msd="VADR" tag="VER&3a;pres" in="" out="-4:subj|2:add|4:dobj|19:pnct">dimostrano</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="inoltre" msd="RG" tag="ADV" in="-2:add" out="-1:pnct|1:pnct">inoltre</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-4:dobj" out="6:vobj">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="5:subj" out="1:nobj">la</W>
<W lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W lemma="in" msd="SP" tag="PRE" in="3:eval" out="1:nobj">in</W>
<W lemma="realtà" msd="NC" tag="NOM" in="-1:nobj" out="">realtà</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="avvantaggiare" msd="VADR" tag="VER&3a;pres" in="-6:vobj" out="-1:robj|-5:subj|-3:eval|1:pobj">avvantaggia</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">del</W>
<W lemma="fare" msd="VAP" tag="VER&3a;pper" in="-1:nobj" out="1:nobj">fatto</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:nobj" out="3:vobj">che</W>
<W lemma="se" msd="CS" tag="CON" in="2:robj" out="">se</W>
<W lemma="ne" msd="RG" tag="ADV" in="1:dobj" out="">ne</W>
<W lemma="occupare" msd="VADR" tag="VER&3a;cpre" in="-3:vobj" out="-1:dobj|-2:robj|1:subj">occupino</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj" out="1:attr">i</W>
<W lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="77:coref-var">privati</W>
<W lemma="." msd="XP" tag="SENT" in="-19:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj" out="1:nobj">La</W>
<W lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W lemma="aumentare" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|1:pnct|4:conj|7:conj|17:pnct">aumenta</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj" out="1:nobj">l'</W>
<W lemma="alimentazione" msd="NC" tag="NOM" in="-1:nobj" out="">alimentazione</W>
<W lemma="migliorare" msd="VADR" tag="VER&3a;pres" in="-4:conj" out="-2:subj">migliora</W>
<W lemma="e" msd="CS" tag="CON" in="2:coord" out="">e</W>
<W lemma="si" msd="PP" tag="PRO&3a;pers" in="1:subj" out="">si</W>
<W lemma="prestare" msd="VADR" tag="VER&3a;pres" in="-7:conj" out="-1:subj|-2:coord|2:dobj">presta</W>
<W lemma="maggiore" msd="AN" tag="ADJ" in="1:attr" out="">maggiore</W>
<W lemma="attenzione" msd="NC" tag="NOM" in="-2:dobj" out="-1:attr|2:pobj">attenzione</W>
<W lemma="sia" msd="CS" tag="CON" in="3:correl" out="">sia</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-2:pobj" out="1:nobj|3:conj">alla</W>
<W lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="1:coord" out="-3:correl">che</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-3:conj" out="-1:coord|1:nobj">alle</W>
<W lemma="zona" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">zone</W>
<W lemma="naturale" msd="AN" tag="ADJ" in="-1:attr" out="">naturali</W>
<W lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="24:loc" out="1:nobj|5:exem|9:ref">Nel</W>
<W lemma="sud" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg|13:relr">sud</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Selandia</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="ad" msd="SP" tag="PRE" in="-5:exem" out="-1:pnct|1:nobj|2:pnct">ad</W>
<W lemma="esempio" msd="NC" tag="NOM" in="-1:nobj" out="">esempio</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="6:loc" out="1:nobj">in</W>
<W lemma="cui" msd="PT" tag="PRO&3a;rela" in="-1:nobj|-9:ref" out="">cui</W>
<W lemma="gran" msd="AN" tag="ADJ" in="1:attr" out="">gran</W>
<W lemma="parte" msd="NC" tag="NOM" in="3:subj|4:[subj]" out="-1:attr|1:pobj&3a;apart">parte</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;apart" out="1:nobj">dei</W>
<W lemma="terreno" msd="NC" tag="NOM" in="-1:nobj" out="">terreni</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-13:relr" out="-6:loc|-3:subj|1:vobj|7:pnct">è</W>
<W lemma="affittare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:agent|3:goal">affittata</W>
<W lemma="da" msd="SP" tag="PRE" in="-1:agent" out="1:attr">da</W>
<W lemma="privato" msd="NC" tag="NOM" in="-1:attr" out="">privati</W>
<W lemma="per" msd="SP" tag="PRE" in="-3:goal" out="1:nobj">per</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj">la</W>
<W lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W lemma="," msd="XP" tag="PON" in="-7:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj" out="1:nobj">la</W>
<W lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|-24:loc|8:conj|21:pnct|48:pnct|95:coref-res|3:preds">è</W>
<W lemma="molto" msd="RG" tag="ADV" in="2:degr" out="1:avobj">molto</W>
<W lemma="più" msd="RG" tag="ADV" in="-1:avobj" out="">più</W>
<W lemma="abbondante" msd="AN" tag="ADJ" in="-3:preds" out="-2:degr">abbondante</W>
<W lemma="e" msd="CS" tag="CON" in="4:coord" out="">e</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="3:cont" out="1:nobj">nel</W>
<W lemma="contempo" msd="NC" tag="NOM" in="-1:nobj" out="">contempo</W>
<W lemma="c'" msd="PD" tag="PRO&3a;demo" in="1:expl" out="">c'</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-8:conj" out="-4:coord|-1:expl|-3:cont|1:dobj|14:reas">è</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="rapporto" msd="NC" tag="NOM" in="-1:nobj" out="2:attr|3:pobj">rapporto</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="naturale" msd="AN" tag="ADJ" in="-2:attr" out="-1:degr">naturale</W>
<W lemma="tra" msd="SP" tag="PRE" in="-3:pobj" out="1:nobj">tra</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|4:conj">la</W>
<W lemma="popolazione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">popolazione</W>
<W lemma="locale" msd="AN" tag="ADJ" in="-1:attr" out="">locale</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-4:conj" out="-1:coord|1:nobj|2:focal">la</W>
<W lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="-2:focal" out="">stessa</W>
<W lemma="," msd="XP" tag="PON" in="-21:pnct" out="">,</W>
<W lemma="visto" msd="CS" tag="CON" in="-14:reas" out="1:dobj">visto</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="3:vobj">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj|5:[subj]|10:[subj]|17:[subj]" out="1:nobj">la</W>
<W lemma="gente" msd="NC" tag="NOM" in="-1:nobj" out="">gente</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-3:vobj" out="-2:subj|6:pnct|8:conj|1:preds">è</W>
<W lemma="abituare" msd="VAP" tag="VER&3a;pper" in="-1:preds" out="1:pobj">abituata</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="vedere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-5:[subj]|1:dobj">vedere</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">i</W>
<W lemma="cacciatore" msd="NC" tag="NOM" in="-1:nobj|-77:coref-var" out="">cacciatori</W>
<W lemma="," msd="XP" tag="PON" in="-6:pnct" out="">,</W>
<W lemma="si" msd="PP" tag="PRO&3a;pers" in="1:robj" out="">si</W>
<W lemma="nutrire" msd="VADR" tag="VER&3a;pres" in="-8:conj" out="-1:robj|-10:[subj]|1:ext|4:pobj|7:conj">nutre</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:ext" out="2:nobj">con</W>
<W lemma="maggiore" msd="AN" tag="ADJ" in="1:attr" out="">maggiore</W>
<W lemma="frequenza" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">frequenza</W>
<W lemma="di" msd="SP" tag="PRE" in="-4:pobj" out="1:nobj">di</W>
<W lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="godere" msd="VADR" tag="VER&3a;pres" in="-7:conj" out="-17:[subj]|-1:coord|1:pobj|3:man">gode</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">della</W>
<W lemma="natura" msd="NC" tag="NOM" in="-1:nobj" out="">natura</W>
<W lemma="in" msd="SP" tag="PRE" in="-3:man" out="1:nobj">in</W>
<W lemma="maniera" msd="NC" tag="NOM" in="-1:nobj" out="2:attr">maniera</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="pieno" msd="AN" tag="ADJ" in="-2:attr" out="-1:degr">piena</W>
<W lemma="." msd="XP" tag="SENT" in="-48:pnct" out="">.</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="7:loc" out="1:nobj">Nel</W>
<W lemma="nord" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;arg|6:vobj">nord</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;arg" out="1:nobj">della</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Selandia</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="invece" msd="RG" tag="ADV" in="2:contr" out="-1:pnct|1:pnct">invece</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-6:vobj" out="-7:loc|-2:contr|1:subj|4:pobj|14:pnct|21:pnct">sono</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:subj" out="1:nobj">i</W>
<W lemma="dipendente" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">dipendenti</W>
<W lemma="statale" msd="AN" tag="ADJ" in="-1:attr" out="">statali</W>
<W lemma="ad" msd="SP" tag="PRE" in="-4:pobj" out="1:vobj">ad</W>
<W lemma="andare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:@dir|6:time">andare</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:@dir" out="1:nobj">a</W>
<W lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="2:man|8:time">caccia</W>
<W lemma="," msd="XP" tag="PON" in="1:pnct" out="">,</W>
<W lemma="discretamente" msd="RG" tag="ADV" in="-2:man" out="-1:pnct|1:pnct">discretamente</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="nel" msd="SP+P" tag="PRE&3a;det" in="-6:time" out="1:nobj">nei</W>
<W lemma="giorno" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">giorni</W>
<W lemma="feriale" msd="AN" tag="ADJ" in="-1:attr" out="">feriali</W>
<W lemma="," msd="XP" tag="PON" in="-14:pnct" out="">,</W>
<W lemma="quando" msd="CS" tag="CON" in="-8:time" out="3:vobj">quando</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="2:subj" out="1:attr">gli</W>
<W lemma="altro" msd="AN" tag="ADJ" in="-1:attr" out="">altri</W>
<W lemma="essere&7c;sonare" msd="VADR" tag="VER&3a;pres" in="-3:vobj" out="-2:subj|1:loc">sono</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:loc" out="1:nobj">al</W>
<W lemma="lavoro" msd="NC" tag="NOM" in="-1:nobj" out="">lavoro</W>
<W lemma="." msd="XP" tag="SENT" in="-21:pnct" out="">.</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="3:subj" out="1:nobj">La</W>
<W lemma="selvaggina" msd="NC" tag="NOM" in="-1:nobj" out="">selvaggina</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="vendere" msd="VADR" tag="VER&3a;pres" in="" out="-3:subj|-1:robj|1:pobj|7:man|12:pnct|15:cons">vende</W>
<W lemma="ad" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">ad</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">una</W>
<W lemma="cerchia" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">cerchia</W>
<W lemma="restringere&7c;ristringere" msd="VAP" tag="VER&3a;pper" in="-1:attr" out="1:pobj">ristretta</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">di</W>
<W lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="">persone</W>
<W lemma="a" msd="SP" tag="PRE" in="-7:man" out="1:nobj">a</W>
<W lemma="vantaggio" msd="NC" tag="NOM" in="-1:nobj" out="1:pobj&3a;ben">vantaggio</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj&3a;ben" out="1:nobj">delle</W>
<W lemma="cassa" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">casse</W>
<W lemma="statale" msd="AN" tag="ADJ" in="-1:attr" out="">statali</W>
<W lemma=";" msd="XP" tag="PON" in="-12:pnct" out="">;</W>
<W lemma="tutto" msd="AN" tag="ADJ" in="1:degr" out="">tutto</W>
<W lemma="questo" msd="PD" tag="PRO&3a;demo" in="-95:coref-res|1:subj" out="-1:degr">questo</W>
<W lemma="allontanare" msd="VADR" tag="VER&3a;pres" in="-15:cons" out="-1:subj|1:dobj|3:@dir|10:pnct">allontana</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="gente" msd="NC" tag="NOM" in="-1:nobj" out="">gente</W>
<W lemma="dal" msd="SP+P" tag="PRE&3a;det" in="-3:@dir" out="1:nobj|4:pnct|5:appa">dall'</W>
<W lemma="attività" msd="NC" tag="NOM" in="-1:nobj" out="2:attr">attività</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="naturale" msd="AN" tag="ADJ" in="-2:attr" out="-1:degr">naturale</W>
<W lemma="," msd="XP" tag="PON" in="-4:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-5:appa" out="1:nobj">la</W>
<W lemma="caccia" msd="NC" tag="NOM" in="-1:nobj" out="">caccia</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
