<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="1:subj" out="10:coref-var|81:coref-id">Larsen</W>
<W lemma="resistere" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|2:man|4:pnct">resiste</W>
<W lemma="più" msd="RG" tag="ADV" in="1:degr" out="">più</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-2:man" out="-1:degr|1:nobj">del</W>
<W lemma="previsto" msd="NC" tag="NOM" in="-1:nobj" out="">previsto</W>
<W lemma="?" msd="XP" tag="SENT" in="-4:pnct" out="">?</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="2:pnct" out="">"</W>
<W lemma="si" msd="PP" tag="PRO&3a;pers" in="1:subj" out="">Si</W>
<W lemma="sapere" msd="VADR" tag="VER&3a;pres" in="" out="-2:pnct|-1:subj|1:dobj|10:pnct">sa</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="3:vobj">che</W>
<W lemma="questo" msd="PD" tag="PRO&3a;demo" in="-10:coref-var|2:subj" out="1:nobj|14:coref">questo</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">jutlandese</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-3:vobj" out="-2:subj|1:preds">è</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:preds" out="1:nobj">un</W>
<W lemma="tipo" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">tipo</W>
<W lemma="forte" msd="AN" tag="ADJ" in="-1:attr" out="2:conj">forte</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="capace" msd="AN" tag="ADJ" in="-2:conj" out="-1:coord">capace</W>
<W lemma="." msd="XP" tag="SENT" in="-10:pnct" out="">.</W>
<W lemma="a" msd="SP" tag="PRE" in="7:prg" out="2:nobj|3:pnct">A</W>
<W lemma="mio" msd="PO" tag="PRO&3a;poss" in="1:attr" out="">mio</W>
<W lemma="parere" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">parere</W>
<W lemma="," msd="XP" tag="PON" in="-3:pnct" out="">,</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="3:subj|4:[subj]" out="2:nobj">il</W>
<W lemma="suo" msd="PO" tag="PRO&3a;poss" in="-14:coref|1:attr" out="">suo</W>
<W lemma="arrivo" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">arrivo</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-7:prg|-3:subj|1:vobj|10:pnct|11:conj">ha</W>
<W lemma="portare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-4:[subj]|1:dir|4:dobj">portato</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:dir" out="1:nobj">in</W>
<W lemma="questo" msd="PD" tag="PRO&3a;demo" in="-1:nobj" out="1:nobj|48:coref-id">questo</W>
<W lemma="settore" msd="NC" tag="NOM" in="-1:nobj" out="">settore</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="-4:dobj" out="1:nobj">una</W>
<W lemma="ventata" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">ventata</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="-1:attr" out="1:pnct|2:conj">nuova</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="necessario" msd="AN" tag="ADJ" in="-2:conj" out="">necessaria</W>
<W lemma=";" msd="XP" tag="PON" in="-10:pnct" out="">;</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="-11:conj|1:[subj]" out="1:vobj|13:conj|17:conj">ha</W>
<W lemma="cominciare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|1:man">cominciato</W>
<W lemma="con" msd="SP" tag="PRE" in="-1:man" out="1:nobj">con</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:nobj" out="1:nobj|9:coref">il</W>
<W lemma="volere" msd="VAF" tag="VER&3a;infi" in="-1:nobj" out="1:vobj">voler</W>
<W lemma="rivoluzionare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:dobj">rivoluzionare</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="sacco" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">sacco</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="cosa" msd="NC" tag="NOM" in="-1:nobj" out="">cose</W>
<W lemma="e" msd="CS" tag="CON" in="3:coord" out="">e</W>
<W lemma="non" msd="RG" tag="ADV" in="2:neg" out="">non</W>
<W lemma="lo" msd="PP" tag="PRO&3a;pers" in="-9:coref|1:dobj" out="">lo</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="-13:conj|1:[subj]" out="-3:coord|-2:neg|-1:dobj|1:vobj|2:pnct">ha</W>
<W lemma="fare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]">fatto</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="1:coord" out="">ma</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-17:conj|1:[subj]" out="-1:coord|1:vobj|16:pnct">è</W>
<W lemma="riuscire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|1:pobj">riuscito</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="convogliare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:vobj|7:dobj">convogliare</W>
<W lemma="condensare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:loc">condensare</W>
<W lemma="intorno" msd="RG" tag="ADV" in="-1:loc" out="1:pobj">intorno</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="1:nobj">all'</W>
<W lemma="idea" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">idea</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:attr" out="1:nobj">del</W>
<W lemma="viaggiare" msd="VAF" tag="VER&3a;infi" in="-1:nobj" out="">viaggiare</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-7:dobj" out="1:nobj">l'</W>
<W lemma="attenzione" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">attenzione</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="2:nobj">un</W>
<W lemma="vastissimo" msd="AN" tag="ADJ" in="1:attr" out="">vastissimo</W>
<W lemma="pubblico" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">pubblico</W>
<W lemma="." msd="XP" tag="SENT" in="-16:pnct" out="">.</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="1:[subj]" out="1:vobj|9:pnct">Ha</W>
<W lemma="contribuire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-1:[subj]|1:pobj|5:iobj">contribuito</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">a</W>
<W lemma="dare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:dobj">dare</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">una</W>
<W lemma="scrollata" msd="NC" tag="NOM" in="-1:nobj" out="">scrollata</W>
<W lemma="al" msd="SP+P" tag="PRE&3a;det" in="-48:coref-id|-5:iobj" out="2:nobj">al</W>
<W lemma="nostro" msd="PO" tag="PRO&3a;poss" in="1:attr" out="">nostro</W>
<W lemma="settore" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr">settore</W>
<W lemma="." msd="XP" tag="SENT" in="-9:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-81:coref-id|1:subj|2:[subj]" out="">Larsen</W>
<W lemma="avere&7c;riavere" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|1:vobj|17:pnct">ha</W>
<W lemma="dire" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-2:[subj]|1:man|2:dobj">detto</W>
<W lemma="pubblicamente" msd="RG" tag="ADV" in="-1:man" out="">pubblicamente</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-2:dobj" out="2:vobj">che</W>
<W lemma="non" msd="RG" tag="ADV" in="1:neg" out="">non</W>
<W lemma="considerare" msd="VADR" tag="VER&3a;pres" in="-2:vobj" out="-1:neg|1:dobj">considera</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">i</W>
<W lemma="@card@" msd="AN" tag="NUM" in="-1:nobj" out="1:nobj">70</W>
<W lemma="milione" msd="NC" tag="NOM" in="-1:nobj" out="1:comp">milioni</W>
<W lemma="come" msd="SP" tag="PRE" in="-1:comp" out="1:nobj|4:contr">come</W>
<W lemma="una" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">una</W>
<W lemma="perdita" msd="NC" tag="NOM" in="-1:nobj" out="">perdita</W>
<W lemma="ma" msd="CS" tag="CON" in="1:coord" out="">ma</W>
<W lemma="come" msd="SP" tag="PRE" in="-4:contr" out="-1:coord|1:nobj">come</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="investimento" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">investimento</W>
<W lemma="istruttivo" msd="AN" tag="ADJ" in="-1:attr" out="">istruttivo</W>
<W lemma="." msd="XP" tag="SENT" in="-17:pnct" out="">.</W>
<W lemma="ci" msd="PR" tag="PRO&3a;refl" in="2:subj|3:[subj]" out="">Ci</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">si</W>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="" out="-2:subj|-1:robj|1:vobj|18:pnct">può</W>
<W lemma="chiedere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-3:[subj]|2:dobj">chiedere</W>
<W lemma="allora" msd="RG" tag="ADV" in="1:cond" out="">allora</W>
<W lemma="quanto" msd="RG" tag="ADV" in="-2:dobj" out="-1:cond|1:vobj">quanto</W>
<W lemma="volere" msd="VADR" tag="VER&3a;pres" in="-1:vobj|1:[subj]" out="1:vobj|2:pnct">vuole</W>
<W lemma="investire" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-1:[subj]|2:dir">investire</W>
<W lemma="," msd="XP" tag="PON" in="-2:pnct" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="-2:dir" out="1:nobj">in</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:nobj" out="1:nobj">un</W>
<W lemma="settore" msd="NC" tag="NOM" in="-1:nobj" out="1:ref|2:relr">settore</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:ref|1:subj" out="">che</W>
<W lemma="attraversare" msd="VADR" tag="VER&3a;pres" in="-2:relr" out="-1:subj|1:dobj">attraversa</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:dobj" out="1:nobj">un</W>
<W lemma="periodo" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">periodo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="calo" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">calo</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="mercato" msd="NC" tag="NOM" in="-1:nobj" out="">mercato</W>
<W lemma="." msd="XP" tag="SENT" in="-18:pnct" out="">.</W>
<W lemma="tutto" msd="PI" tag="PRO&3a;indef" in="1:subj" out="">Tutti</W>
<W lemma="continuare" msd="VADR" tag="VER&3a;pres" in="" out="-1:subj|1:pobj|19:pnct|22:conj">continuano</W>
<W lemma="ad" msd="SP" tag="PRE" in="-1:pobj" out="1:vobj">ad</W>
<W lemma="avere&7c;riavere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:dobj">avere</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">il</W>
<W lemma="sogno" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">sogno</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:vobj|8:conj">di</W>
<W lemma="viaggiare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="2:conj">viaggiare</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="scoprire" msd="VAF" tag="VER&3a;infi" in="-2:conj" out="-1:coord|1:nobj">scoprire</W>
<W lemma="qualcosa" msd="PI" tag="PRO&3a;indef" in="-1:nobj" out="1:attr">qualcosa</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="-1:nobj" out="">nuovo</W>
<W lemma="e" msd="CS" tag="CON" in="1:coord" out="">e</W>
<W lemma="di" msd="SP" tag="PRE" in="-8:conj" out="-1:coord|1:vobj">di</W>
<W lemma="stare" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="1:man">stare</W>
<W lemma="insieme" msd="RG" tag="ADV" in="-1:man" out="1:pobj">insieme</W>
<W lemma="a" msd="SP" tag="PRE" in="-1:pobj" out="1:nobj">a</W>
<W lemma="persona" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">persone</W>
<W lemma="sconosciuto" msd="AN" tag="ADJ" in="-1:attr" out="">sconosciute</W>
<W lemma="," msd="XP" tag="PON" in="-19:pnct" out="">,</W>
<W lemma="ma" msd="CS" tag="CON" in="2:coord" out="">ma</W>
<W lemma="molto" msd="PI" tag="PRO&3a;indef" in="1:subj" out="">molti</W>
<W lemma="restare" msd="VADR" tag="VER&3a;pres" in="-22:conj" out="-2:coord|-1:subj|1:man|3:cause|19:pnct">restano</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="attesa" msd="NC" tag="NOM" in="-1:nobj" out="">attesa</W>
<W lemma="perché" msd="RG" tag="ADV" in="-3:cause" out="2:vobj">perché</W>
<W lemma="si" msd="PR" tag="PRO&3a;refl" in="1:subj" out="">si</W>
<W lemma="sentire" msd="VADR" tag="VER&3a;pres" in="-2:vobj" out="-1:subj|6:pnct|7:ref|9:relelab|1:preds">sentono</W>
<W lemma="insicuro" msd="AN" tag="ADJ" in="-1:preds" out="1:pobj">insicuri</W>
<W lemma="del" msd="SP+P" tag="PRE&3a;det" in="-1:pobj" out="2:nobj">dell'</W>
<W lemma="attuale" msd="AN" tag="ADJ" in="1:attr" out="">attuale</W>
<W lemma="situazione" msd="NC" tag="NOM" in="-2:nobj" out="-1:attr|1:attr">situazione</W>
<W lemma="economico" msd="AN" tag="ADJ" in="-1:attr" out="">economica</W>
<W lemma="-" msd="XP" tag="PON" in="-6:pnct" out="">-</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-7:ref|2:subj" out="1:nobj">il</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:nobj" out="">che</W>
<W lemma="riguardare" msd="VADR" tag="VER&3a;pres" in="-9:relelab" out="-2:subj|1:dobj">riguarda</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="-1:dobj" out="1:nobj">la</W>
<W lemma="società" msd="NC" tag="NOM" in="-1:nobj" out="1:man">società</W>
<W lemma="in" msd="SP" tag="PRE" in="-1:man" out="1:nobj">in</W>
<W lemma="generale" msd="AN" tag="ADJ" in="-1:nobj" out="">generale</W>
<W lemma="." msd="XP" tag="SENT" in="-19:pnct" out="">.</W>
<W lemma="&amp;quot;" msd="XP" tag="PON" in="7:pnct" out="">"</W>
<W lemma="oggi" msd="RG" tag="ADV" in="6:time" out="1:pnct">Oggi</W>
<W lemma="," msd="XP" tag="PON" in="-1:pnct" out="">,</W>
<W lemma="quando" msd="CS" tag="CON" in="4:cond" out="2:vobj">quando</W>
<W lemma="vi" msd="PR" tag="PRO&3a;refl" in="1:robj" out="">vi</W>
<W lemma="guardare" msd="VADR" tag="VER&3a;pres" in="-2:vobj" out="-1:robj|1:man">guardate</W>
<W lemma="indietro" msd="RG" tag="ADV" in="-1:man" out="">indietro</W>
<W lemma="potere" msd="VADR" tag="VER&3a;pres" in="1:[subj]" out="-7:pnct|-6:time|-4:cond|1:vobj|11:pnct">potete</W>
<W lemma="riconoscere" msd="VAF" tag="VER&3a;infi" in="-1:vobj" out="-1:[subj]|1:dobj">riconoscere</W>
<W lemma="che" msd="PT" tag="PRO&3a;rela" in="-1:dobj" out="5:vobj">che</W>
<W lemma="il" msd="PD" tag="DET&3a;def" in="4:subj|5:[subj]" out="1:nobj">l'</W>
<W lemma="acquisto" msd="NC" tag="NOM" in="-1:nobj" out="1:attr">acquisto</W>
<W lemma="di" msd="SP" tag="PRE" in="-1:attr" out="1:nobj">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="-1:nobj" out="">Tjæreborg</W>
<W lemma="essere" msd="VADR" tag="VER&3a;pres" in="-5:vobj" out="-4:subj|1:vobj">è</W>
<W lemma="essere&7c;stare" msd="VAP" tag="VER&3a;pper" in="-1:vobj" out="-5:[subj]|1:preds">stato</W>
<W lemma="un" msd="PI" tag="DET&3a;indef" in="-1:preds" out="1:nobj">un</W>
<W lemma="errore" msd="NC" tag="NOM" in="-1:nobj" out="">errore</W>
<W lemma="?" msd="XP" tag="SENT" in="-11:pnct" out="">?</W>
