<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">Nella</W>
<W lemma="maggiore" msd="AN" tag="ADJ" in="" out="">maggior</W>
<W lemma="parte" msd="NC" tag="NOM" in="" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">delle</W>
<W lemma="istituzione" msd="NC" tag="NOM" in="" out="">istituzioni</W>
<W lemma="scolastico" msd="AN" tag="ADJ" in="" out="">scolastiche</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="facile" msd="AN" tag="ADJ" in="" out="">facile</W>
<W lemma="valutare" msd="VAF" tag="VER:infi" in="" out="">valutare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="grado" msd="NC" tag="NOM" in="" out="">grado</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="partecipazione" msd="NC" tag="NOM" in="" out="">partecipazione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="studente" msd="NC" tag="NOM" in="" out="">studenti</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">già</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">dall’inizio</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">dell’anno</W>
<W lemma="scolastico" msd="AN" tag="ADJ" in="" out="">scolastico</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="se" msd="CS" tag="CON" in="" out="">Se</W>
<W lemma="uno" msd="PI" tag="DET:indef" in="" out="">uno</W>
<W lemma="studente" msd="NC" tag="NOM" in="" out="">studente</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="presente" msd="AN" tag="ADJ" in="" out="">presente</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alle</W>
<W lemma="lezione" msd="NC" tag="NOM" in="" out="">lezioni</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alle</W>
<W lemma="diverso" msd="AN" tag="ADJ" in="" out="">diverse</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">attività</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alle</W>
<W lemma="vario" msd="AN" tag="ADJ" in="" out="">varie</W>
<W lemma="prova" msd="NC" tag="NOM" in="" out="">prove</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="allora" msd="RG" tag="ADV" in="" out="">allora</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="uno" msd="PI" tag="DET:indef" in="" out="">uno</W>
<W lemma="studente" msd="NC" tag="NOM" in="" out="">studente</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="partecipare" msd="VADR" tag="VER:pres" in="" out="">partecipa</W>
<W lemma="attivamente" msd="RG" tag="ADV" in="" out="">attivamente</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="diversamente" msd="RG" tag="ADV" in="" out="">diversamente</W>
<W lemma="no." msd="XA" tag="ABR" in="" out="">no.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">In</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="" out="">quelle</W>
<W lemma="istituzione" msd="NC" tag="NOM" in="" out="">istituzioni</W>
<W lemma="scolastico" msd="AN" tag="ADJ" in="" out="">scolastiche</W>
<W lemma="dove" msd="PT" tag="PRO:rela" in="" out="">dove</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">c’è</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">l’obbligo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="frequenza" msd="NC" tag="NOM" in="" out="">frequenza</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="genere" msd="NC" tag="NOM" in="" out="">genere</W>
<W lemma="tale" msd="CS" tag="CON" in="" out="">tale</W>
<W lemma="valutazione" msd="NC" tag="NOM" in="" out="">valutazione</W>
<W lemma="si" msd="PR" tag="PRO:refl" in="" out="">si</W>
<W lemma="basare" msd="VADR" tag="VER:pres" in="" out="">basa</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulla</W>
<W lemma="consegna" msd="NC" tag="NOM" in="" out="">consegna</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">dei</W>
<W lemma="compito" msd="NC" tag="NOM" in="" out="">compiti</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="parte" msd="NC" tag="NOM" in="" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="studente" msd="NC" tag="NOM" in="" out="">studenti</W>
<W lemma="o" msd="CS" tag="CON" in="" out="">o</W>
<W lemma="simile" msd="NC" tag="NOM" in="" out="">simili</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="eppoi" msd="RG" tag="ADV" in="" out="">eppoi</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="ogni" msd="AN" tag="ADJ" in="" out="">ogni</W>
<W lemma="tipo" msd="NC" tag="NOM" in="" out="">tipo</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="studio" msd="NC" tag="NOM" in="" out="">studio</W>
<W lemma="ci" msd="PR" tag="PRO:refl" in="" out="">ci</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="prova" msd="NC" tag="NOM" in="" out="">prove</W>
<W lemma="periodico" msd="AN" tag="ADJ" in="" out="">periodiche</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">Questo</W>
<W lemma="genere" msd="NC" tag="NOM" in="" out="">genere</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="valutazione" msd="NC" tag="NOM" in="" out="">valutazione</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="compito" msd="NC" tag="NOM" in="" out="">compito</W>
<W lemma="specifico" msd="AN" tag="ADJ" in="" out="">specifico</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">delle</W>
<W lemma="istituzione" msd="NC" tag="NOM" in="" out="">istituzioni</W>
<W lemma="scolastico" msd="AN" tag="ADJ" in="" out="">scolastiche</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ho</W>
<W lemma="nessuno" msd="AN" tag="ADJ" in="" out="">nessun</W>
<W lemma="motivo" msd="NC" tag="NOM" in="" out="">motivo</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="ritenere" msd="VAF" tag="VER:infi" in="" out="">ritenere</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">quest’ultime</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="lo" msd="PP" tag="PRO:pers" in="" out="">lo</W>
<W lemma="svolgere" msd="VADR" tag="VER:cpre" in="" out="">svolgano</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="dovuto" msd="AN" tag="ADJ" in="" out="">dovuta</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">serietà</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">Una</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">possibilità</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="imbrogliare" msd="VAF" tag="VER:infi" in="" out="">imbrogliare</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="presente" msd="AN" tag="ADJ" in="" out="">presente</W>
<W lemma="normalmente" msd="RG" tag="ADV" in="" out="">normalmente</W>
<W lemma="durante" msd="SP" tag="PRE" in="" out="">durante</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">primo</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anno</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="studio" msd="NC" tag="NOM" in="" out="">studi</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">Per</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">questa</W>
<W lemma="ragione" msd="NC" tag="NOM" in="" out="">ragione</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">introdurrò</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="" out="">nuova</W>
<W lemma="disposizione" msd="NC" tag="NOM" in="" out="">disposizione</W>
<W lemma="secondo" msd="SP" tag="PRE" in="" out="">secondo</W>
<W lemma="cui" msd="PT" tag="PRO:rela" in="" out="">cui</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">istitituzioni</W>
<W lemma="dovere" msd="VADR" tag="VER:futu" in="" out="">dovranno</W>
<W lemma="effettuare" msd="VAF" tag="VER:infi" in="" out="">effettuare</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">prima</W>
<W lemma="valutazione" msd="NC" tag="NOM" in="" out="">valutazione</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">più</W>
<W lemma="tardo" msd="AN" tag="ADJ" in="" out="">tardi</W>
<W lemma="entro" msd="SP" tag="PRE" in="" out="">entro</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="primo" msd="AN" tag="ADJ" in="" out="">primi</W>
<W lemma="sei" msd="AN" tag="ADJ" in="" out="">sei</W>
<W lemma="mese" msd="NC" tag="NOM" in="" out="">mesi</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">dall’inizio</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">delle</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">attività</W>
<W lemma="scolastico" msd="AN" tag="ADJ" in="" out="">scolastiche</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="Jens" msd="NP" tag="NPR" in="" out="">Jens</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Sandfeld</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Søndergaard</W>
<W lemma="sostenere" msd="VADR" tag="VER:pres" in="" out="">sostiene</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="regola" msd="NC" tag="NOM" in="" out="">regole</W>
<W lemma="relativo" msd="AN" tag="ADJ" in="" out="">relative</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="sussidio" msd="NC" tag="NOM" in="" out="">sussidio</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="studio" msd="NC" tag="NOM" in="" out="">studio</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">così</W>
<W lemma="poco" msd="RG" tag="ADV" in="" out="">poco</W>
<W lemma="restrittivo" msd="AN" tag="ADJ" in="" out="">restrittive</W>
<W lemma="che" msd="CS" tag="CON" in="" out="">che</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="possibile" msd="AN" tag="ADJ" in="" out="">possibile</W>
<W lemma="ricevere" msd="VAF" tag="VER:infi" in="" out="">ricevere</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="">dalle</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">3.198</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alle</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">38.376</W>
<W lemma="corona" msd="NC" tag="NOM" in="" out="">corone</W>
<W lemma="danese" msd="AN" tag="ADJ" in="" out="">danesi</W>
<W lemma="&lt;unknown&gt;" msd="VADR" tag="VER:pres" in="" out="">all’anno</W>
<W lemma="senza" msd="SP" tag="PRE" in="" out="">senza</W>
<W lemma="avere" msd="VAF" tag="VER:infi" in="" out="">aver</W>
<W lemma="mai" msd="RG" tag="ADV" in="" out="">mai</W>
<W lemma="frequentare" msd="VAP" tag="VER:pper" in="" out="">frequentato</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">né</W>
<W lemma="aprire" msd="VAP" tag="VER:pper" in="" out="">aperto</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="libro" msd="NC" tag="NOM" in="" out="">libro</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="" out="">Si</W>
<W lemma="citare" msd="VADR" tag="VER:pres" in="" out="">cita</W>
<W lemma="come" msd="SP" tag="PRE" in="" out="">come</W>
<W lemma="esempio" msd="NC" tag="NOM" in="" out="">esempio</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="se" msd="PR" tag="PRO:refl" in="" out="">se</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="persona" msd="NC" tag="NOM" in="" out="">persona</W>
<W lemma="guadagnare" msd="VADR" tag="VER:pres" in="" out="">guadagna</W>
<W lemma="@card@" msd="XP" tag="PON" in="" out="">300.000</W>
<W lemma="corona" msd="NC" tag="NOM" in="" out="">corone</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="persona" msd="NC" tag="NOM" in="" out="">persona</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="questione" msd="NC" tag="NOM" in="" out="">questione</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">può</W>
<W lemma="ricevere" msd="VAF" tag="VER:infi" in="" out="">ricevere</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="sussidio" msd="NC" tag="NOM" in="" out="">sussidio</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="studio" msd="NC" tag="NOM" in="" out="">studio</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="mesa|mese" msd="NC" tag="NOM" in="" out="">mese</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
