<W lemma="ci" msd="PR" tag="PRO:refl" in="" out="">Ci</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="" out="">si</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">può</W>
<W lemma="lasciare" msd="VAF" tag="VER:infi" in="" out="">lasciar</W>
<W lemma="sedurre" msd="VAF" tag="VER:infi" in="" out="">sedurre</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">nel</W>
<W lemma="parco" msd="NC" tag="NOM" in="" out="">parco</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kongens</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Have</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">35</W>
<W lemma="grado" msd="NC" tag="NOM" in="" out="">gradi</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="sdraiare" msd="VAP" tag="VER:pper" in="" out="">sdraiati</W>
<W lemma="sotto" msd="SP" tag="PRE" in="" out="">sotto</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">l’ombra</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="albero" msd="NC" tag="NOM" in="" out="">albero</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">più</W>
<W lemma="completamente" msd="RG" tag="ADV" in="" out="">completamente</W>
<W lemma="vestito" msd="AN" tag="ADJ" in="" out="">vestiti</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="bere" msd="VAG" tag="VER:geru" in="" out="">bevendo</W>
<W lemma="acqua" msd="NC" tag="NOM" in="" out="">acqua</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="fumare" msd="VAG" tag="VER:geru" in="" out="">fumando</W>
<W lemma="sigaretta" msd="NC" tag="NOM" in="" out="">sigarette</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="ascoltare" msd="VAG" tag="VER:geru" in="" out="">ascoltando</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="confessione" msd="NC" tag="NOM" in="" out="">confessioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="provocatore" msd="NC" tag="NOM" in="" out="">provocatore</W>
<W lemma="pop" msd="AN" tag="ADJ" in="" out="">pop</W>
<W lemma="?" msd="XP" tag="SENT" in="" out="">?</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Sì</W>
<W lemma="!" msd="XP" tag="SENT" in="" out="">!</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Carsten</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bo</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="tanto" msd="RG" tag="ADV" in="" out="">tanto</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="precisare" msd="VAF" tag="VER:infi" in="" out="">precisare</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="@card@" msd="XP" tag="PON" in="" out="">33</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma=";" msd="XP" tag="PON" in="" out="">;</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="figlio" msd="NC" tag="NOM" in="" out="">figlio</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">dell’ex</W>
<W lemma="ministro" msd="NC" tag="NOM" in="" out="">ministro</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">l’industria</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">E</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="Jensen" msd="NP" tag="NPR" in="" out="">Jensen</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="poeta" msd="NC" tag="NOM" in="" out="">poeta</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="cantante" msd="NC" tag="NOM" in="" out="">cantante</W>
<W lemma="pop" msd="AN" tag="ADJ" in="" out="">pop</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="scrittore" msd="NC" tag="NOM" in="" out="">scrittore</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Primus</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">motor</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="diverso" msd="AN" tag="ADJ" in="" out="">diversi</W>
<W lemma="gruppo" msd="NC" tag="NOM" in="" out="">gruppi</W>
<W lemma="musicale" msd="AN" tag="ADJ" in="" out="">musicali</W>
<W lemma="dal" msd="SP+P" tag="PRE:det" in="" out="">dai</W>
<W lemma="nome" msd="NC" tag="NOM" in="" out="">nomi</W>
<W lemma="criptico" msd="AN" tag="ADJ" in="" out="">criptici</W>
<W lemma="come" msd="CS" tag="CON" in="" out="">come</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">es</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">“40</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">feber”</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">“Mænd</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">i</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">blåt”</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">più</W>
<W lemma="tardo" msd="AN" tag="ADJ" in="" out="">tardi</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">“Sea</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Bee</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">&amp”</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">The</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">D’Generation</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="contro" msd="SP" tag="PRE" in="" out="">contro</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="proprio" msd="AN" tag="ADJ" in="" out="">propria</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">volontà</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stato</W>
<W lemma="definire" msd="VAP" tag="VER:pper" in="" out="">definito</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Steffen</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Brandt</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">degli</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">’90</W>
<W lemma="o" msd="CS" tag="CON" in="" out="">o</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">C.V.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Jørgensen</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="questo" msd="PD" tag="PRO:demo" in="" out="">questa</W>
<W lemma="non" msd="RG" tag="ADV" in="" out="">non</W>
<W lemma="gli" msd="PP" tag="PRO:pers" in="" out="">gli</W>
<W lemma="andare|riandare" msd="VADR" tag="VER:pres" in="" out="">va</W>
<W lemma="proprio" msd="RG" tag="ADV" in="" out="">proprio</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="niente" msd="AN" tag="ADJ" in="" out="">niente</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">giù</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">“Io</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="io" msd="PP" tag="PRO:pers" in="" out="">io</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">!”</W>
<W lemma="insistere" msd="VADR" tag="VER:pres" in="" out="">insiste</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Carsten</W>
<W lemma="sotto" msd="SP" tag="PRE" in="" out="">sotto</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="quercia" msd="NC" tag="NOM" in="" out="">quercia</W>
<W lemma="centenario" msd="AN" tag="ADJ" in="" out="">centenaria</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="sdraiare" msd="VAP" tag="VER:pper" in="" out="">sdraiato</W>
<W lemma="sul" msd="SP+P" tag="PRE:det" in="" out="">sulla</W>
<W lemma="schiena" msd="NC" tag="NOM" in="" out="">schiena</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="quello" msd="PD" tag="PRO:demo" in="" out="">quella</W>
<W lemma="suo" msd="PO" tag="PRO:poss" in="" out="">sua</W>
<W lemma="aria" msd="NC" tag="NOM" in="" out="">aria</W>
<W lemma="sfrontato" msd="AN" tag="ADJ" in="" out="">sfrontata</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="addosso" msd="RG" tag="ADV" in="" out="">addosso</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="paio" msd="NC" tag="NOM" in="" out="">paio</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="jeans" msd="NC" tag="NOM" in="" out="">jeans</W>
<W lemma="arancione" msd="AN" tag="ADJ" in="" out="">arancioni</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="maglietta" msd="NC" tag="NOM" in="" out="">maglietta</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="naturalmente" msd="RG" tag="ADV" in="" out="">naturalmente</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="lasciare" msd="VADR" tag="VER:pres" in="" out="">lascia</W>
<W lemma="intravedere" msd="VAF" tag="VER:infi" in="" out="">intravedere</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="petto" msd="NC" tag="NOM" in="" out="">petto</W>
<W lemma="villoso" msd="AN" tag="ADJ" in="" out="">villoso</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="abbronzare" msd="VAP" tag="VER:pper" in="" out="">abbronzato</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="paio" msd="NC" tag="NOM" in="" out="">paio</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">d’occhiali</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="solo" msd="AN" tag="ADJ" in="" out="">sole</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">’68</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="tipo" msd="NC" tag="NOM" in="" out="">tipo</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">“make</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">love</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">not</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">war”</W>
<W lemma="appena" msd="RG" tag="ADV" in="" out="">appena</W>
<W lemma="comprare" msd="VAP" tag="VER:pper" in="" out="">comprati</W>
<W lemma="a" msd="SP" tag="PRE" in="" out="">a</W>
<W lemma="Parigi" msd="NP" tag="NPR" in="" out="">Parigi</W>
<W lemma="ed" msd="CS" tag="CON" in="" out="">ed</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="sigaretta" msd="NC" tag="NOM" in="" out="">sigaretta</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Kings</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="bocca" msd="NC" tag="NOM" in="" out="">bocca</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
