<p>
<s>
<W lemma="parallelamente" msd="RG" tag="ADV" in="" out="">Parallelamente</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">ai</W>
<W lemma="preparativo" msd="NC" tag="NOM" in="" out="">preparativi</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="corsa|corso" msd="NC" tag="NOM" in="" out="">corsa</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">Le</W>
<W lemma="Mans" msd="NP" tag="NPR" in="" out="">Mans</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="prossimo" msd="AN" tag="ADJ" in="" out="">prossimo</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anno</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">ACO</W>
<W lemma="presentare" msd="VADR" tag="VER:pres" in="" out="">presenta</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="caso" msd="NC" tag="NOM" in="" out="">caso</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="rimborso" msd="NC" tag="NOM" in="" out="">rimborso</W>
<W lemma="contro" msd="SP" tag="PRE" in="" out="">contro</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">FIA</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="perdita" msd="NC" tag="NOM" in="" out="">perdite</W>
<W lemma="che" msd="PT" tag="PRO:rela" in="" out="">che</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">il</W>
<W lemma="club" msd="NC" tag="NOM" in="" out="">club</W>
<W lemma="avere|riavere" msd="VADR" tag="VER:pres" in="" out="">ha</W>
<W lemma="subito" msd="RG" tag="ADV" in="" out="">subito</W>
<W lemma="come" msd="SP" tag="PRE" in="" out="">come</W>
<W lemma="conseguenza" msd="NC" tag="NOM" in="" out="">conseguenza</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="mancato" msd="AN" tag="ADJ" in="" out="">mancato</W>
<W lemma="pagamento" msd="NC" tag="NOM" in="" out="">pagamento</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="parte" msd="NC" tag="NOM" in="" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="commissione" msd="NC" tag="NOM" in="" out="">commissione</W>
<W lemma="sportivo" msd="AN" tag="ADJ" in="" out="">sportiva</W>
<W lemma="&lt;unknown&gt;" msd="VAP" tag="VER:pper" in="" out="">FISA</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="promessa|promesso" msd="NC" tag="NOM" in="" out="">promesse</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="obbligo" msd="NC" tag="NOM" in="" out="">obblighi</W>
<W lemma="assumere" msd="VAP" tag="VER:pper" in="" out="">assunti</W>
<W lemma="in" msd="SP" tag="PRE" in="" out="">in</W>
<W lemma="occasione" msd="NC" tag="NOM" in="" out="">occasione</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="procedura" msd="NC" tag="NOM" in="" out="">procedura</W>
<W lemma="obbligatorio" msd="AN" tag="ADJ" in="" out="">obbligatoria</W>
<W lemma="riguardo" msd="NC" tag="NOM" in="" out="">riguardo</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">alla</W>
<W lemma="classico" msd="AN" tag="ADJ" in="" out="">classica</W>
<W lemma="gara" msd="NC" tag="NOM" in="" out="">gara</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">La</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">FISA</W>
<W lemma="avere" msd="VADA" tag="VER:impf" in="" out="">aveva</W>
<W lemma="obbligare" msd="VAP" tag="VER:pper" in="" out="">obbligato</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">ACO</W>
<W lemma="ad" msd="SP" tag="PRE" in="" out="">ad</W>
<W lemma="apportare" msd="VAF" tag="VER:infi" in="" out="">apportare</W>
<W lemma="diverso" msd="AN" tag="ADJ" in="" out="">diverse</W>
<W lemma="modifica" msd="NC" tag="NOM" in="" out="">modifiche</W>
<W lemma="contro" msd="SP" tag="PRE" in="" out="">contro</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="garanzia" msd="NC" tag="NOM" in="" out="">garanzia</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="copertura" msd="NC" tag="NOM" in="" out="">copertura</W>
<W lemma="mediatico" msd="AN" tag="ADJ" in="" out="">mediatica</W>
<W lemma="completo" msd="AN" tag="ADJ" in="" out="">completa</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="massiccio" msd="AN" tag="ADJ" in="" out="">massiccia</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="ma" msd="CS" tag="CON" in="" out="">Ma</W>
<W lemma="nel" msd="SP+P" tag="PRE:det" in="" out="">negli</W>
<W lemma="ultimo" msd="AN" tag="ADJ" in="" out="">ultimi</W>
<W lemma="due" msd="AN" tag="ADJ" in="" out="">due</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anni</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="andare" msd="VAP" tag="VER:pper" in="" out="">andato</W>
<W lemma="tutto" msd="RG" tag="ADV" in="" out="">tutto</W>
<W lemma="storto" msd="RG" tag="ADV" in="" out="">storto</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">La</W>
<W lemma="pista" msd="NC" tag="NOM" in="" out="">pista</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="essere|stare" msd="VAP" tag="VER:pper" in="" out="">stata</W>
<W lemma="ridurre" msd="VAP" tag="VER:pper" in="" out="">ridotta</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="@card@" msd="AN" tag="NUM" in="" out="">50%</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="migliaio" msd="NC" tag="NOM" in="" out="">migliaia</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="spettatore" msd="NC" tag="NOM" in="" out="">spettatori</W>
<W lemma="se" msd="CS" tag="CON" in="" out="">se</W>
<W lemma="ne" msd="RG" tag="ADV" in="" out="">ne</W>
<W lemma="essere|sonare" msd="VADR" tag="VER:pres" in="" out="">sono</W>
<W lemma="andare" msd="VAP" tag="VER:pper" in="" out="">andati</W>
<W lemma="perché" msd="RG" tag="ADV" in="" out="">perché</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">l'</W>
<W lemma="emozione" msd="NC" tag="NOM" in="" out="">emozione</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="gara" msd="NC" tag="NOM" in="" out="">gara</W>
<W lemma="essere" msd="VADA" tag="VER:impf" in="" out="">era</W>
<W lemma="andare" msd="VAP" tag="VER:pper" in="" out="">andata</W>
<W lemma="perdere" msd="VAP" tag="VER:pper" in="" out="">persa</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">lo</W>
<W lemma="stesso" msd="AN" tag="ADJ" in="" out="">stesso</W>
<W lemma="motivo" msd="NC" tag="NOM" in="" out="">motivo</W>
<W lemma="anche" msd="RG" tag="ADV" in="" out="">anche</W>
<W lemma="gran" msd="AN" tag="ADJ" in="" out="">gran</W>
<W lemma="parte" msd="NC" tag="NOM" in="" out="">parte</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">della</W>
<W lemma="stampa" msd="NC" tag="NOM" in="" out="">stampa</W>
<W lemma="sportivo" msd="AN" tag="ADJ" in="" out="">sportiva</W>
<W lemma="se" msd="CS" tag="CON" in="" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">n'</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="andare" msd="VAP" tag="VER:pper" in="" out="">andata</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="quindi" msd="RG" tag="ADV" in="" out="">quindi</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">ACO</W>
<W lemma="si" msd="PP" tag="PRO:pers" in="" out="">si</W>
<W lemma="essere" msd="VADR" tag="VER:pres" in="" out="">è</W>
<W lemma="trovare" msd="VAP" tag="VER:pper" in="" out="">trovata</W>
<W lemma="con" msd="SP" tag="PRE" in="" out="">con</W>
<W lemma="una" msd="PI" tag="DET:indef" in="" out="">una</W>
<W lemma="pista" msd="NC" tag="NOM" in="" out="">pista</W>
<W lemma="rinnovare" msd="VAP" tag="VER:pper" in="" out="">rinnovata</W>
<W lemma="ed" msd="CS" tag="CON" in="" out="">ed</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">pit-stop</W>
<W lemma="nuovissimo" msd="AN" tag="ADJ" in="" out="">nuovissimo</W>
<W lemma="dopo" msd="SP" tag="PRE" in="" out="">dopo</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="investimento" msd="NC" tag="NOM" in="" out="">investimento</W>
<W lemma="milionario" msd="AN" tag="ADJ" in="" out="">milionario</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="e" msd="CS" tag="CON" in="" out="">e</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="buco" msd="NC" tag="NOM" in="" out="">buco</W>
<W lemma="economico" msd="AN" tag="ADJ" in="" out="">economico</W>
<W lemma="così" msd="RG" tag="ADV" in="" out="">così</W>
<W lemma="notevole" msd="AN" tag="ADJ" in="" out="">notevole</W>
<W lemma="da" msd="SP" tag="PRE" in="" out="">da</W>
<W lemma="avere" msd="VAF" tag="VER:infi" in="" out="">aver</W>
<W lemma="trascinare" msd="VAP" tag="VER:pper" in="" out="">trascinato</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NOM" in="" out="">FIA</W>
<W lemma="davanti" msd="AN" tag="ADJ" in="" out="">davanti</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="giudice" msd="NC" tag="NOM" in="" out="">giudice</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="ottenere" msd="VAF" tag="VER:infi" in="" out="">ottenere</W>
<W lemma="un" msd="PI" tag="DET:indef" in="" out="">un</W>
<W lemma="rimborso" msd="NC" tag="NOM" in="" out="">rimborso</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">Il</W>
<W lemma="prossimo" msd="AN" tag="ADJ" in="" out="">prossimo</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anno</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="gara" msd="NC" tag="NOM" in="" out="">gara</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">Le</W>
<W lemma="Mans" msd="NP" tag="NPR" in="" out="">Mans</W>
<W lemma="essere" msd="VADR" tag="VER:futu" in="" out="">sarà</W>
<W lemma="aperto" msd="AN" tag="ADJ" in="" out="">aperta</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="quattro" msd="AN" tag="ADJ" in="" out="">quattro</W>
<W lemma="tipo" msd="NC" tag="NOM" in="" out="">tipi</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="auto" msd="NC" tag="NOM" in="" out="">auto</W>
<W lemma="senza" msd="SP" tag="PRE" in="" out="">senza</W>
<W lemma="restrizione" msd="NC" tag="NOM" in="" out="">restrizioni</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="benzina" msd="NC" tag="NOM" in="" out="">benzina</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="così" msd="RG" tag="ADV" in="" out="">così</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="gara" msd="NC" tag="NOM" in="" out="">gara</W>
<W lemma="andare" msd="VADR" tag="VER:futu" in="" out="">andrà</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="nuovo" msd="AN" tag="ADJ" in="" out="">nuovo</W>
<W lemma="al" msd="SP+P" tag="PRE:det" in="" out="">al</W>
<W lemma="massimo" msd="NC" tag="NOM" in="" out="">massimo</W>
<W lemma="." msd="XP" tag="SENT" in="" out="">.</W>
</s>
<s>
<W lemma="giovedì" msd="NC" tag="NOM" in="" out="">Giovedì</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">ACO</W>
<W lemma="aprire" msd="VADR" tag="VER:futu" in="" out="">aprirà</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">le</W>
<W lemma="iscrizione" msd="NC" tag="NOM" in="" out="">iscrizioni</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="il" msd="PD" tag="DET:def" in="" out="">la</W>
<W lemma="gara" msd="NC" tag="NOM" in="" out="">gara</W>
<W lemma="del" msd="SP+P" tag="PRE:det" in="" out="">del</W>
<W lemma="prossimo" msd="AN" tag="ADJ" in="" out="">prossimo</W>
<W lemma="anno" msd="NC" tag="NOM" in="" out="">anno</W>
<W lemma="," msd="XP" tag="PON" in="" out="">,</W>
<W lemma="per" msd="SP" tag="PRE" in="" out="">per</W>
<W lemma="auto" msd="NC" tag="NOM" in="" out="">auto</W>
<W lemma="di" msd="SP" tag="PRE" in="" out="">di</W>
<W lemma="quattro" msd="AN" tag="ADJ" in="" out="">quattro</W>
<W lemma="categoria" msd="NC" tag="NOM" in="" out="">categorie</W>
<W lemma=":" msd="XP" tag="PON" in="" out="">:</W>
</s>
</p>
