<W gloss="I" msd="PP" in="1:subj" out="">Jeg</W>
<W gloss="am" msd="VA" in="5:vobj" out="-1:subj|4:pnct|1:preds">er</W>
<W gloss="a" msd="PI" in="-1:preds" out="1:attr|2:nobj">en</W>
<W gloss="nice" msd="AN" in="-1:attr" out="">sød</W>
<W gloss="boy" msd="NC" in="-2:nobj" out="">dreng</W>
<W gloss="," msd="XP" in="-4:pnct" out="">,</W>
<W gloss="thinks" msd="VE" in="" out="-5:vobj|1:subj">synes</W>
<W gloss="my" msd="PO" in="-1:subj" out="1:possd">min</W>
<W gloss="grandmother" msd="NC" in="-1:possd" out="">mormor</W>
