<s>
<W msd="PD" tag="DT" in="2:subj|3:[subj]|5:[subj]" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">press</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:vobj|7:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-3:[subj]|1:dobj">begun</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-5:[subj]|1:dobj">take</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="1:pobj">notice</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">him</W>
<W msd="XP" tag="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="PO" tag="PRP$" in="2:subj|3:[subj]|1:{agent}" out="1:possd">His</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="-1:{agent}">books</W>
<W msd="VADR" tag="VBP" in="" out="-2:subj|1:vobj|3:pnct">are</W>
<W msd="VAG" tag="VBG" in="-1:vobj" out="-3:[subj]|1:preds">being</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="">reviewed</W>
<W msd="XP" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">height</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|2:preds|3:pnct|4:time|25:pnct">was</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">last</W>
<W msd="NC=S" tag="NN" in="-2:preds" out="-1:attr">year</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PT" tag="WRB" in="-4:time" out="3:vobj">when</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Jørgen</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:namef">Thorgaard</W>
<W msd="VADA" tag="VBD" in="-3:vobj" out="-1:subj|1:dobj|11:@loc">had</W>
<W msd="AC" tag="CD" in="-1:dobj|1:{quant}" out="1:pobj|6:pnct|8:appa">one</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj|-1:{quant}">of</W>
<W msd="PO" tag="PRP$" in="-1:nobj|3:{other}" out="2:attr|3:possd">his</W>
<W msd="ANS" tag="RBS" in="1:quant" out="">most</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="-1:quant">important</W>
<W msd="NC=P" tag="NNS" in="-3:possd" out="-3:{other}">authors</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Vagn</W>
<W msd="NP=S" tag="NNP" in="-8:appa" out="-1:namef|1:pnct">Predbjørn</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-11:@loc" out="1:nobj">on</W>
<W msd="PO" tag="PRP$" in="-1:nobj|3:{agent}" out="3:possd|4:attr">his</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{source}#" out="">television</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{other}#" out="-1:attr|-1:{source}#">magazine</W>
<W msd="NC=S" tag="NN" in="-3:possd" out="-3:{agent}|-1:attr|-1:{other}#|1:{about}">program</W>
<W msd="SP" tag="IN" in="-4:attr|-1:{about}" out="1:nobj">on</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">books</W>
<W msd="XP" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="" out="2:conj|19:pnct">And</W>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W msd="VADR" tag="VBZ" in="-2:conj" out="-1:subj|1:vobj|9:concom">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|2:inst">had</W>
<W msd="NC=S" tag="NN" in="-1:dobj" out="">success</W>
<W msd="SP" tag="IN" in="-2:inst" out="1:nobj">with</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="3:possd|4:pnct">his</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{about}#" out="">poetry</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{goal}#" out="-1:attr|-1:{about}#">book</W>
<W msd="NC=S" tag="NN" in="-3:possd" out="-1:attr|-1:{goal}#">club</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VAG" tag="VBG" in="-9:concom" out="1:dobj|5:time">issuing</W>
<W msd="AC" tag="CD" in="-1:dobj" out="1:attr|3:nobj">three</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">new</W>
<W msd="NC=S" tag="NN" in="1:mod" out="">poetry</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="-1:mod">collections</W>
<W msd="PD" tag="DT" in="-5:time" out="1:attr|2:nobj">every</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">other</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">month</W>
<W msd="XP" tag="." in="-19:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="6:time" out="">Now</W>
<W msd="PD" tag="DT" in="5:subj|7:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="2:appr">word</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="NC=S" tag="NN" in="-2:appr" out="-1:pnct|1:pnct">success</W>
<W msd="XP" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W msd="VA" tag="MD" in="" out="-5:subj|-6:time|1:neg|2:vobj|23:pnct">may</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-7:[subj]|2:preds|12:pnct|17:mod|4:goal">be</W>
<W msd="ANP" tag="RB" in="1:attr" out="">quite</W>
<W msd="PD" tag="DT" in="-2:preds" out="-1:attr|1:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="">same</W>
<W msd="SP" tag="IN" in="-4:goal" out="2:nobj|6:conj">for</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Jørgen</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="-1:namef|1:attr|1:{goal}">Fallesen</W>
<W msd="SP" tag="IN" in="-1:attr|-1:{goal}" out="1:nobj">at</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Almind</W>
<W msd="CS" tag="IN" in="1:coord" out="">as</W>
<W msd="SP" tag="IN" in="-6:conj" out="-1:coord|1:nobj">for</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Gyldendal</W>
<W msd="XP" tag="&3a;" in="-12:pnct" out="">-</W>
<W msd="SP" tag="IN" in="4:eval" out="1:avobj|2:pnct">at</W>
<W msd="ANS" tag="JJS" in="-1:avobj" out="">least</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="1:neg" out="">not</W>
<W msd="VAP" tag="VBN" in="-17:mod" out="-1:neg|-4:eval|1:inst">measured</W>
<W msd="SP" tag="IN" in="-1:inst" out="2:nobj">in</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{other}#" out="">print</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{other}#">run</W>
<W msd="XP" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="8:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">number</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:pobj|1:{arg}">members</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj" out="2:possd">his</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{goal}#" out="">poetry</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-1:attr|-1:{goal}#">club</W>
<W msd="VADR" tag="VBZ" in="" out="-8:subj|1:preds|24:conj|29:pnct">is</W>
<W msd="AC" tag="CD" in="-1:preds" out="1:pnct|2:appa">15</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="VAP" tag="VBN" in="-2:appa" out="1:pnct">fifteen</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="CC" tag="CC" in="19:coord" out="">and</W>
<W msd="ANP" tag="RB" in="18:conc" out="1:other#|3:vobj">even</W>
<W msd="CS" tag="IN" in="-1:other#" out="">though</W>
<W msd="PP" tag="PRP" in="1:subj" out="">he</W>
<W msd="VADR" tag="VBZ" in="-3:vobj" out="-1:subj|1:dobj">recognises</W>
<W msd="SP" tag="IN" in="-1:dobj" out="4:vobj">that</W>
<W msd="XP" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">this</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">number</W>
<W msd="VADR" tag="VBZ" in="-4:vobj" out="-3:pnct|-2:subj|1:preds|6:pnct|7:pnct">is</W>
<W msd="NC=S" tag="NN" in="-1:preds" out="1:nobj">nothing</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W _noerror="&3a;nosubj&3a;" msd="VAF" tag="VB" in="-1:vobj" out="1:@dir|2:pobj">write</W>
<W msd="NC=S" tag="NN" in="-1:@dir" out="">home</W>
<W msd="SP" tag="IN" in="-2:pobj" out="">about</W>
<W msd="XP" tag="," in="-6:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-7:pnct" out="">"</W>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">these</W>
<W msd="VAP" tag="VBN" in="-1:nobj" out="">fifteen</W>
<W msd="VADR" tag="VBP" in="-24:conj" out="-2:subj|-19:coord|1:preds|-18:conc">are</W>
<W msd="NC=S" tag="NN" in="-1:preds" out="1:nobj">nothing</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W _noerror="&3a;nosubj&3a;" msd="VAF" tag="VB" in="-1:vobj" out="1:pobj">sneeze</W>
<W msd="ANP" tag="RB" in="-1:pobj" out="">at</W>
<W msd="XP" tag="." in="-29:pnct" out="">.</W>
</s>
<s>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj" out="">They</W>
<W msd="VADR" tag="VBP" in="18:qobj" out="-2:pnct|-1:subj|1:dobj|15:pnct|16:pnct">have</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:attr|2:nobj">an</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">important</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:pobj|1:{arg}">share</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">in</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:dobj">ensuring</W>
<W msd="SP" tag="IN" in="-1:dobj" out="3:vobj">that</W>
<W msd="PD" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">series</W>
<W msd="VA" tag="MD" in="-3:vobj" out="-2:subj|1:vobj">can</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-3:[subj]|1:eval">continue</W>
<W msd="SP" tag="IN" in="-1:eval" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">spite</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">everything</W>
<W msd="XP" tag="," in="-15:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="-16:pnct" out="">"</W>
<W msd="PP" tag="PRP" in="1:subj" out="">he</W>
<W msd="VADR" tag="VBZ" in="" out="-18:qobj|-1:subj|1:pnct">says</W>
<W msd="XP" tag="." in="-1:pnct" out="">.</W>
</s>
<s>
<W msd="U=" tag="EX" in="1:expl" out="">There</W>
<W msd="VADR" tag="VBP" in="" out="-1:expl|1:dobj|8:pnct|11:pnct|5:@loc|10:&lt;dobj&3a;2&gt;">are</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">no</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="2:conj">institutions</W>
<W msd="CC" tag="CC" in="1:coord" out="">or</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="-1:coord">libraries</W>
<W msd="SP" tag="IN" in="-5:@loc" out="1:nobj">among</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">subscribers</W>
<W msd="XP" tag="," in="-8:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="1:attr" out="">just</W>
<W msd="NC=P" tag="NNS" in="-10:&lt;dobj&3a;2&gt;" out="-1:attr">individuals</W>
<W msd="XP" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="4:coord" out="">And</W>
<W msd="PD" tag="DT" in="3:subj" out="2:nobj">the</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{other}#" out="">print</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr|-1:{other}#">run</W>
<W msd="VADR" tag="VBZ" in="" out="-3:subj|2:preds|4:pnct|1:eval|-4:coord|13:pnct|5:modp|5:{elab}">is</W>
<W msd="ANP" tag="RB" in="-1:eval" out="">normally</W>
<W msd="SP" tag="IN" in="-2:preds" out="1:nobj">in</W>
<W msd="AC" tag="CD" in="-1:nobj" out="">the100s</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="VAG" tag="VBG" in="-5:modp|-5:{elab}" out="2:dobj">including</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{goal}#" out="">review</W>
<W msd="NC=P" tag="NNS" in="-2:dobj" out="3:conj|-1:attr|-1:{goal}#">copies</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">free</W>
<W msd="NC=P" tag="NNS" in="-3:conj" out="-2:coord|-1:attr|1:attr|1:{goal}">copies</W>
<W msd="U=" tag="TO" in="-1:attr|-1:{goal}" out="1:nobj">to</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">authors</W>
<W msd="XP" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj" out="">He</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:dobj|10:pnct|18:conj|24:pnct|2:fpredo">mentions</W>
<W msd="NP=S" tag="NNP" in="-1:dobj" out="">Parzival</W>
<W msd="CS" tag="IN" in="-2:fpredo" out="1:nobj">as</W>
<W msd="AC" tag="CD" in="-1:nobj|1:{quant}" out="1:pobj">one</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj|-1:{quant}">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:pnct|3:nobj|4:pnct|2:attr">the</W>
<W msd="XP" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W msd="NC=S" tag="NN" in="-2:attr" out="">staple</W>
<W msd="NC=P" tag="NNS" in="-3:nobj" out="">articles</W>
<W msd="XP" tag="&amp;quot;" in="-4:pnct" out="">"</W>
<W msd="XP" tag="&3a;" in="-10:pnct" out="">-</W>
<W msd="CC" tag="CC" in="7:coord" out="1:pnct">and</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="5:pobj" out="1:nobj|2:pnct">of</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">it</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="U=" tag="EX" in="2:expl" out="">there</W>
<W msd="ANP" tag="RB" in="1:time" out="">still</W>
<W msd="VAF" tag="VB" in="-18:conj" out="-2:expl|-7:coord|1:dobj|-5:pobj|-1:time|4:time">go</W>
<W msd="AC" tag="CD" in="-1:dobj" out="1:nobj">75</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="1:err">copies</W>
<W msd="SP" tag="IN" in="-1:err" out="">of</W>
<W msd="PI" tag="DT" in="-4:time" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">year</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="3:cause" out="1:pnct">Therefore</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]|7:[subj]" out="">he</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|-3:cause|1:add|2:vobj|12:pnct">has</W>
<W msd="ANP" tag="RB" in="-1:add" out="">also</W>
<W msd="VAP" tag="VBN" in="-2:vobj" out="-3:[subj]|1:preds">felt</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="1:pobj|2:goal">called</W>
<W msd="SP" tag="IN" in="-1:pobj" out="">upon</W>
<W msd="U=" tag="TO" in="-2:goal" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|2:pnct|-7:[subj]|3:quant">reprint</W>
<W msd="PP" tag="PRP" in="-1:dobj" out="">it</W>
<W msd="XP" tag="&3a;" in="-2:pnct" out="">-</W>
<W msd="SP" tag="IN" in="-3:quant" out="1:nobj">in</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">100</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">copies</W>
<W msd="XP" tag="." in="-12:pnct" out="">.</W>
</s>
