<s>
<W msd="PD" tag="DT" in="3:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">letter</W>
<W msd="ANP" tag="RB" in="1:man" out="">officially</W>
<W msd="VADA" tag="VBD" in="" out="-3:subj|1:iobj|39:pnct|-1:man|2:pobj|38:²pnct">authorised</W>
<W msd="NP=S" tag="NNP" in="-1:iobj|3:[subj]|5:[subj]|18:[subj]" out="">Crescent</W>
<W msd="U=" tag="TO" in="-2:pobj" out="2:vobj|16:conj">to</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-1:pnct|-3:[subj]|2:conj|3:pnct|4:dobj">discuss</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VAF" tag="VB" in="-2:conj" out="-5:[subj]|-1:coord|2:[dobj]">negotiate</W>
<W msd="XP" tag="&amp;quot;" in="-3:pnct" out="">"</W>
<W msd="PI" tag="DT" in="-4:dobj|-2:[dobj]" out="1:attr|2:nobj|3:attr">a</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">possible</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="1:{other}">purchase</W>
<W msd="SP" tag="IN" in="-3:attr|-1:{other}" out="1:nobj">within</W>
<W msd="PD" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W msd="ANP" tag="JJ" in="1:attr#" out="">joint</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{about}#" out="-1:attr#">venture</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:attr|-1:{about}#">agreement</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="XP" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W msd="U=" tag="TO" in="-16:conj" out="-1:pnct|-2:coord|1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-18:[subj]|4:dobj">discuss</W>
<W msd="XP" tag="." in="0:err" out="0:err">?</W>
</s>
<s>
<W msd="PD" tag="DT" in="-4:dobj" out="1:nobj">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="2:conj|3:pobj|3:{arg}">terms</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=P" tag="NNS" in="-2:conj" out="-1:coord">conditions</W>
<W msd="SP" tag="IN" in="-3:pobj|-3:{arg}" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj|7:attr">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj.dobj|1:{patient}|6:{time}">procurement</W>
<W msd="SP" tag="IN" in="-1:pobj.dobj|-1:{patient}" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|3:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr|2:{source}" out="">Iraqi</W>
<W msd="ANP" tag="JJ" in="1:attr|1:{form}#" out="">raw</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:attr|-1:{form}#|-2:{source}">oil</W>
<W msd="SP" tag="IN" in="-7:attr|-6:{time}" out="1:nobj">over</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:¹nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">long</W>
<W compound="¹term²." msd="ANP" tag="JJ" in="-2:¹nobj|-38:²pnct" out="">term.</W>
<W msd="XP" tag="&amp;quot;" in="-39:pnct" out="">"</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Hamid</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:namef">Jafar</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|2:preds|14:pnct">was</W>
<W msd="ANP" tag="RB" in="1:quant" out="">very</W>
<W msd="ANP" tag="JJ" in="-2:preds" out="-1:quant|1:nobj">eager</W>
<W msd="U=" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|6:pobj">show</W>
<W msd="PO" tag="PRP$" in="-1:dobj|1:[subj]|1:{agent}" out="1:possd">his</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:[subj]|-1:{agent}|1:pobj.dobj|1:{patient}">appreciation</W>
<W msd="SP" tag="IN" in="-1:pobj.dobj|-1:{patient}" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">agreement</W>
<W msd="U=" tag="TO" in="-6:pobj" out="1:nobj">to</W>
<W msd="PO" tag="PRP$" in="-1:nobj|2:{arg}" out="1:attr|2:possd">his</W>
<W msd="ANP" tag="JJ" in="-1:attr|1:{source}" out="">Iraqi</W>
<W msd="NC=P" tag="NNS" in="-2:possd" out="-2:{arg}|-1:{source}">partners</W>
<W msd="XP" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="1:@time" out="">Shortly</W>
<W msd="CS" tag="IN" in="5:time" out="1:nobj|3:pnct|-1:@time">before</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">invasion</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj" out="">he</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|-5:time|1:dobj|23:pnct|12:pobj">ordered</W>
<W msd="PI" tag="DT" in="-1:dobj" out="2:pnct|3:attr|4:pnct|6:nobj|1:attr|7:attr">an</W>
<W msd="VAP" tag="VBN" in="-1:attr|5:{form}" out="">engraved</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-3:attr|3:{source}" out="">Swiss</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{const}#" out="">gold</W>
<W msd="NC=S" tag="NN" in="-6:nobj" out="-3:{source}|-1:attr|-1:{const}#|-5:{form}">pistol</W>
<W msd="VAP" tag="VBN" in="-7:attr" out="1:pobj">assessed</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">at</W>
<W msd="AC" tag="CD" in="-1:nobj" out="1:nobj">7,000</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">pounds</W>
<W msd="SP" tag="IN" in="-12:pobj" out="1:nobj">from</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="1:pnct|2:ref|3:relpa">Asprey's</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PT" tag="WDT" in="-2:ref|1:subj" out="">which</W>
<W msd="VADR" tag="VBZ" in="-3:relpa" out="-1:subj|1:preds">is</W>
<W msd="PD" tag="DT" in="-1:preds" out="2:nobj|3:possd|4:attr">the</W>
<W msd="NP=S" tag="NNP" in="1:aobj|1:{arg}" out="">English</W>
<W msd="NP=S" tag="NNP" in="-2:nobj|1:{other}" out="-1:aobj|-1:{arg}">Queen's</W>
<W msd="NC=S" tag="NN" in="-3:possd" out="-1:{other}|1:{loc}">jeweller</W>
<W msd="SP" tag="IN" in="-4:attr|-1:{loc}" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">London</W>
<W msd="XP" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">purpose</W>
<W msd="VADA" tag="VBD" in="" out="-2:subj|1:preds|24:pnct">was</W>
<W msd="U=" tag="TO" in="-1:preds" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:dobj|3:pobj">show</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">pistol</W>
<W msd="U=" tag="TO" in="-3:pobj" out="2:nobj">to</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Saddam</W>
<W msd="NP=S" tag="NNP" in="-2:nobj|1:{arg}" out="-1:namef|1:possd|4:pnct|7:appa|10:ref|11:relr">Hussein's</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="2:conj|-1:{arg}">cousin</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-2:conj" out="-1:coord">son-in-law</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="2:namef" out="1:namef">Hussein</W>
<W msd="NP=S" tag="NNP" in="-1:namef" out="">Kamal</W>
<W msd="NP=S" tag="NNP" in="-7:appa" out="-2:namef|1:namel|2:pnct">al</W>
<W msd="NP=S" tag="NNP" in="-1:namel" out="">Majid</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-10:ref|1:subj" out="">who</W>
<W msd="VADA" tag="VBD" in="-11:relr" out="-1:subj|2:preds|1:time">was</W>
<W msd="ANP" tag="RB" in="-1:time" out="">once</W>
<W msd="NP=S" tag="NNP" in="-2:preds|1:{arg}" out="1:possd">Iraq's</W>
<W msd="NP=S" tag="NNP" in="-1:possd" out="1:pobj|-1:{arg}|1:{arg}">Minister</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">for</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">Industry</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="PT" tag="WRB" in="5:time" out="2:vobj">When</W>
<W msd="NC=P" tag="NNS" in="1:subj" out="">hostilities</W>
<W msd="VADA" tag="VBD" in="-2:vobj" out="-1:subj|1:pnct">began</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PP" tag="PRP" in="1:subj|3:[subj]" out="">it</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|1:neg|2:vobj|7:pnct|-5:time">did</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-3:[subj]|1:@loc">get</W>
<W msd="SP" tag="IN" in="-1:@loc" out="1:pobj">outside</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W msd="NP=S" tag="NNP" in="-1:nobj|1:{loc}" out="1:possd">Baghdad's</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:{loc}">airport</W>
<W msd="XP" tag="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="SP" tag="IN" in="4:add" out="1:nobj|2:pnct">Beyond</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Petrofina</W>
<W msd="XP" tag="," in="-2:pnct" out="">,</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="">Crescent</W>
<W msd="VADA" tag="VBD" in="" out="-1:subj|2:dobj|21:pnct|-4:add">investigated</W>
<W msd="ANP" tag="RB" in="1:attr" out="">quite</W>
<W msd="PI" tag="DT" in="-2:dobj" out="-1:attr|1:nobj|5:ref|10:relr">a</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="1:nobj">few</W>
<W msd="ANP" tag="JJ" in="-1:nobj" out="2:nobj|1:attr">other</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">possible</W>
<W msd="NC=P" tag="NNS" in="-2:nobj" out="">targets</W>
<W msd="SP" tag="IN" in="-5:ref|6:dobj" out="">that</W>
<W msd="PD" tag="DT" in="4:subj|5:[subj]" out="3:nobj">the</W>
<W msd="ANP" tag="JJ" in="1:attr#" out="">joint</W>
<W msd="NC=S" tag="NN" in="1:attr|1:{about}#" out="-1:attr#">venture</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="-1:attr|-1:{about}#">alliance</W>
<W msd="VA" tag="MD" in="-10:relr" out="-4:subj|1:vobj">could</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-6:dobj|-5:[subj]|1:pnct|3:modp|3:{elab}">acquire</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="PD" tag="DT" in="4:correl" out="">both</W>
<W msd="SP" tag="IN" in="-3:modp|-3:{elab}" out="2:nobj">in</W>
<W msd="NP=S" tag="NNP" in="1:attr|1:{const}#" out="">North</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="2:conj|-1:attr|-1:{const}#">America</W>
<W msd="CC" tag="CC" in="1:coord" out="-4:correl">and</W>
<W msd="NP=S" tag="NNP" in="-2:conj" out="-1:coord">Europe</W>
<W msd="XP" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Hamid</W>
<W msd="NP=S" tag="NNP" in="1:subj" out="-1:namef">Jafar</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|3:preds|17:pnct">is</W>
<W msd="AC" tag="CD" in="2:attr|2:{quant}" out="1:nobj">45</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="ANP" tag="JJ" in="-3:preds" out="1:pnct|2:conj|5:pnct|7:conj|-2:attr|-2:{quant}">old</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="VAP" tag="VBN" in="-2:conj" out="1:pobj">educated</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">London</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="NC=S" tag="NN" in="-7:conj" out="-1:coord|1:pobj|1:{arg}">son</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="PI" tag="DT" in="-1:nobj" out="1:attr|4:nobj">a</W>
<W msd="ANP" tag="JJ" in="-1:attr|3:{time}" out="">former</W>
<W msd="ANP" tag="JJ" in="2:aobj|2:{arg}" out="">Iraqi</W>
<W msd="NC=S" tag="NN" in="1:nobj|1:{arg}#" out="">government</W>
<W msd="NC=S" tag="NN" in="-4:nobj" out="-3:{time}|-2:aobj|-2:{arg}|-1:nobj|-1:{arg}#">minister</W>
<W msd="XP" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj|2:[subj]|8:[subj]" out="">He</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:vobj|7:conj|30:pnct">has</W>
<W msd="VAP" tag="VBN" in="-1:vobj" out="-2:[subj]|1:time|3:@loc">lived</W>
<W msd="ANP" tag="JJ" in="-1:time" out="1:nobj">many</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">years</W>
<W msd="SP" tag="IN" in="-3:@loc" out="1:nobj">in</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Sharjeh</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="VADA" tag="VBD" in="-7:conj" out="-8:[subj]|-1:coord|1:dobj|10:ref|8:time|9:²pnct|11:relelab">received</W>
<W msd="PI" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">passport</W>
<W msd="U=" tag="TO" in="-1:pobj|-1:{arg}" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="3:nobj|1:attr">the</W>
<W msd="NP=S" tag="NNP" in="-1:attr" out="1:attr">United</W>
<W msd="NP=S" tag="NNP" in="-1:attr" out="">Arab</W>
<W msd="NP=P" tag="NNPS" in="-3:nobj" out="">Emirates</W>
<W msd="SP" tag="IN" in="-8:time" out="1:¹nobj">in</W>
<W compound="¹1986²," msd="AC" tag="CD" in="-1:¹nobj|-9:²pnct" out="">1986,</W>
<W msd="PT" tag="WDT" in="-10:ref|1:subj" out="">which</W>
<W msd="NC=P" tag="NNS" in="-11:relelab" out="-1:subj|1:iobj|3:dobj">grants</W>
<W msd="PP" tag="PRP" in="-1:iobj" out="">him</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">national</W>
<W msd="NC=S" tag="NN" in="-3:dobj" out="-1:attr|1:pobj|1:{arg}">affiliation</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="2:nobj">in</W>
<W msd="PD" tag="DT" in="2:correl" out="">both</W>
<W msd="NP=S" tag="NNP" in="-2:nobj" out="2:conj">Iraq</W>
<W msd="CC" tag="CC" in="1:coord" out="-2:correl">and</W>
<W msd="PD" tag="DT" in="-2:conj" out="-1:coord|3:nobj|1:attr|2:attr">the</W>
<W msd="NP=S" tag="NNP" in="-1:attr" out="">United</W>
<W msd="NP=S" tag="NNP" in="-2:attr" out="">Arab</W>
<W msd="NP=P" tag="NNPS" in="-3:nobj" out="">Emirates</W>
<W msd="XP" tag="." in="-30:pnct" out="">.</W>
</s>
