<s>
<W msd="CC" tag="CC" in="4:coord" out="">But</W>
<W msd="PO" tag="PRP$" in="3:subj|4:[subj]|2:{arg}" out="1:attr|2:possd">their</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">mutual</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-2:{arg}">relationship</W>
<W msd="VADR" tag="VBZ" in="" out="-3:subj|-4:coord|1:preds|33:pnct">is</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="-4:[subj]|1:agent">complicated</W>
<W msd="SP" tag="IN" in="-1:agent" out="1:nobj">by</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:nobj">fact</W>
<W msd="SP" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W msd="PP" tag="PRP" in="1:subj" out="">they</W>
<W msd="VADR" tag="VBP" in="-2:vobj" out="-1:subj|2:preds|1:other">are</W>
<W msd="PD" tag="DT" in="-1:other" out="">both</W>
<W msd="SP" tag="IN" in="-2:preds" out="1:nobj">in</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj">love</W>
<W msd="SP" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj|3:pnct|4:appa">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">same</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">man</W>
<W msd="XP" tag="&3a;" in="-3:pnct" out="">:</W>
<W msd="PD" tag="DT" in="-4:appa" out="6:nobj|7:pnct|8:ref|1:attr|12:relr">the</W>
<W msd="VAP" tag="VBN" in="-1:attr" out="3:conj">exiled</W>
<W msd="CC" tag="CC" in="2:coord" out="">and</W>
<W msd="ANP" tag="RB" in="1:time" out="">later</W>
<W msd="VADA" tag="VBD" in="-3:conj" out="-2:coord|-1:time">returned</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Peder</W>
<W msd="NP=S" tag="NNP" in="-6:nobj" out="-1:namef">Oxe</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="PT" tag="WP" in="-8:ref|4:dobj" out="">whom</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Mette</W>
<W msd="NP=S" tag="NNP" in="2:attr" out="-1:namef">Rosenkrantz</W>
<W msd="ANP" tag="RB" in="1:mod" out="">ultimately</W>
<W msd="VADR" tag="VBZ" in="-12:relr" out="-1:mod|-4:dobj|-2:attr|1:time">marries</W>
<W msd="CS" tag="IN" in="-1:time" out="1:nobj">after</W>
<W msd="PO" tag="PRP$" in="-1:nobj|1:{arg}" out="1:possd|2:possd">her</W>
<W msd="NC=P" tag="NNS" in="-1:possd|1:[subj]|1:{experiencer}" out="-1:{arg}">husband's</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-1:[subj]|-1:{experiencer}">death</W>
<W msd="XP" tag="." in="-33:pnct" out="">.</W>
</s>
<s>
<W msd="PD" tag="DT" in="2:subj|4:[subj]" out="1:nobj">The</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">novel</W>
<W msd="VADR" tag="VBZ" in="" out="-2:subj|1:neg|2:vobj|5:pnct|28:conj|42:pnct|4:@loc|6:conc">does</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="VAF" tag="VB" in="-2:vobj" out="-4:[subj]">go</W>
<W msd="SP" tag="IN" in="1:quant" out="">that</W>
<W msd="ANP" tag="RB" in="-4:@loc" out="-1:quant">far</W>
<W msd="XP" tag="," in="-5:pnct" out="">,</W>
<W msd="ANP" tag="RB" in="-6:conc" out="1:pobj#">even</W>
<W msd="CS" tag="IN" in="-1:pobj#" out="2:vobj">though</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VADR" tag="VBZ" in="-2:vobj" out="1:preds|-1:subj">is</W>
<W msd="PD" tag="DT" in="-1:preds|7:[nobj]" out="1:attr|2:nobj|4:relr">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">happy</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">ending</W>
<W msd="PP" tag="PRP" in="1:subj" out="">it</W>
<W msd="VADR" tag="VBZ" in="-4:relr" out="-1:subj|1:dobj|4:pnct|3:goal">sets</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">stage</W>
<W msd="SP" tag="IN" in="-3:goal" out="-7:[nobj]">for</W>
<W msd="XP" tag="&3a;" in="-4:pnct" out="">-</W>
<W msd="PD" tag="DT" in="9:subj" out="1:pobj|1:{arg}|5:attr|5:{loc}">some</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANS" tag="JJS" in="-1:attr" out="">finest</W>
<W msd="VAG" tag="VBG" in="-2:nobj" out="">writing</W>
<W msd="SP" tag="IN" in="-5:attr|-5:{loc}" out="1:nobj">in</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">long</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">story</W>
<W msd="VADR" tag="VBZ" in="-28:conj" out="-9:subj|1:preds">is</W>
<W msd="PD" tag="DT" in="-1:preds" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj.dobj|1:{patient}">description</W>
<W msd="SP" tag="IN" in="-1:pobj.dobj|-1:{patient}" out="1:nobj">of</W>
<W msd="PT" tag="WRB" in="-1:nobj|5:[man]" out="5:relr">how</W>
<W msd="PD" tag="DT" in="4:subj" out="1:attr|2:nobj">this</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">mutual</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">love</W>
<W msd="ANP" tag="RB" in="1:man" out="">hesitantly</W>
<W msd="VADR" tag="VBZ" in="-5:relr" out="-4:subj|1:dobj|-5:[man]|-1:man|3:goal">clears</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">path</W>
<W msd="SP" tag="IN" in="-3:goal" out="1:nobj">for</W>
<W msd="PP" tag="PRP" in="-1:nobj" out="">itself</W>
<W msd="XP" tag="." in="-42:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="28:discmark" out="">But</W>
<W msd="SP" tag="IN" in="27:subj" out="6:vobj">that</W>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="NP=S" tag="NNP" in="1:title" out="">Saint</W>
<W msd="NP=S" tag="NNP" in="3:subj|4:[subj]|5:[subj]" out="-2:pnct|-1:title|1:nobj|2:pnct">Marcus</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Night</W>
<W msd="XP" tag="&amp;quot;" in="-2:pnct" out="">"</W>
<W msd="VA" tag="MD" in="-6:vobj" out="-3:subj|1:vobj|7:pnct|8:modp|8:{elab}">may</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-4:[subj]|1:preds">be</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="-5:[subj]|2:preds">called</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Helle</W>
<W msd="NP=S" tag="NNP" in="-2:preds|2:{agent}" out="-1:namef|1:attr|2:possd">Stangerup's</W>
<W msd="ANS" tag="JJS" in="-1:attr" out="">best</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-2:{agent}">novel</W>
<W msd="XP" tag="&3a;" in="-7:pnct" out="">-</W>
<W msd="SP" tag="IN" in="-8:modp|-8:{elab}" out="1:nobj|9:pnct|12:pnct">without</W>
<W msd="PP" tag="PRP" in="-1:nobj|2:[subj]|4:[subj]" out="2:vobj">it</W>
<W msd="ANP" tag="RB" in="1:cause" out="">therefore</W>
<W msd="VAG" tag="VBG" in="-2:vobj" out="-1:cause|1:dobj|-2:[subj]">needing</W>
<W msd="U=" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="1:preds|-4:[subj]">be</W>
<W msd="PO" tag="PRP$" in="-1:preds" out="2:attr">her</W>
<W msd="ANS" tag="RBS" in="1:quant" out="">most</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="-1:quant">popular</W>
<W msd="XP" tag="." in="-9:pnct" out="">!</W>
</s>
<s>
<W msd="XP" tag="&3a;" in="-12:pnct" out="">-</W>
<W msd="VADR" tag="VBZ" in="" out="-27:subj|1:preds|-28:discmark|24:pnct">is</W>
<W msd="ANP" tag="JJ" in="-1:preds" out="1:pnct|6:pobj|2:eval">due</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="ANP" tag="JJ" in="-2:eval" out="2:conj|3:pnct">first</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="ANP" tag="JJ" in="-2:conj" out="-1:coord">foremost</W>
<W msd="XP" tag="," in="-3:pnct" out="">,</W>
<W msd="U=" tag="TO" in="-6:pobj" out="1:nobj">to</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:attr|3:nobj|5:ref|7:relr">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">cool</W>
<W msd="ANP" tag="JJ" in="-2:attr" out="">passionate</W>
<W msd="NC=S" tag="NN" in="-3:nobj" out="">brilliance</W>
<W msd="SP" tag="IN" in="3:man" out="1:nobj">with</W>
<W msd="PT" tag="WDT" in="-1:nobj|-5:ref" out="">which</W>
<W msd="PP" tag="PRP" in="1:subj" out="">she</W>
<W msd="NC=P" tag="NNS" in="-7:relr" out="-1:subj|1:dobj|-3:man">masters</W>
<W msd="PD" tag="DT" in="-1:dobj|7:[dobj]" out="1:nobj|7:relr">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">complex</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">of</W>
<W msd="NC=P" tag="NNS" in="-1:nobj" out="">themes</W>
<W msd="PD" tag="DT" in="3:subj" out="1:nobj|2:possd">the</W>
<W msd="NC=P" tag="NNS" in="-1:nobj|1:{arg}" out="">novel's</W>
<W msd="NC=S" tag="NN" in="-2:possd" out="-1:{arg}">plot</W>
<W msd="VADR" tag="VBZ" in="-7:relr" out="-7:[dobj]|-3:subj">contains</W>
<W msd="XP" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W msd="NP=S" tag="NNP" in="8:subj|9:[subj]|10:[subj]" out="2:conj">Time</W>
<W msd="CC" tag="CC" in="1:coord" out="">and</W>
<W msd="PO" tag="PRP$" in="-2:conj|1:{time}" out="-1:coord|1:possd|4:appa">its</W>
<W msd="NC=P" tag="NNS" in="-1:possd" out="1:pnct|-1:{time}">fates</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">female</W>
<W msd="NC=P" tag="NNS" in="-4:appa" out="-1:attr|1:pnct">fates</W>
<W msd="XP" tag="&3a;" in="-1:pnct" out="">-</W>
<W msd="NC=S" tag="NN" in="" out="-8:subj|1:vobj|3:pnct">cannot</W>
<W msd="VAF" tag="VB" in="-1:vobj" out="-9:[subj]|1:preds">be</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="-10:[subj]">separated</W>
<W msd="XP" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W msd="CC" tag="CC" in="4:correl" out="">Neither</W>
<W msd="SP" tag="IN" in="" out="1:nobj|4:conj|7:pnct">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj|1:{other}" out="1:possd">their</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:{other}">tragedy</W>
<W msd="CC" tag="CC" in="1:coord" out="-4:correl">nor</W>
<W msd="SP" tag="IN" in="-4:conj" out="-1:coord|1:nobj">in</W>
<W msd="PO" tag="PRP$" in="-1:nobj|1:[subj]|1:{experiencer}" out="1:possd">their</W>
<W msd="NC=S" tag="NN" in="-1:possd" out="-1:[subj]|-1:{experiencer}">triumph</W>
<W msd="XP" tag="." in="-7:pnct" out="">.</W>
</s>
<s>
<W msd="PP" tag="PRP" in="1:subj" out="4:nobj">It</W>
<W msd="VADR" tag="VBZ" in="" out="-1:subj|1:neg|2:preds|42:pnct">is</W>
<W msd="ANP" tag="RB" in="-1:neg" out="">not</W>
<W msd="ANP" tag="JJ" in="-2:preds" out="">wrong</W>
<W msd="SP" tag="IN" in="-4:nobj" out="1:pnct|12:vobj">that</W>
<W msd="XP" tag="," in="-1:pnct" out="">,</W>
<W msd="SP" tag="IN" in="10:loc" out="1:nobj|4:pnct">on</W>
<W msd="PD" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W msd="ANP" tag="JJ" in="1:attr" out="">back</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="-1:attr">cover</W>
<W msd="XP" tag="," in="-4:pnct" out="">,</W>
<W msd="XP" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W msd="NP=S" tag="NNP" in="1:title" out="">Saint</W>
<W msd="NP=S" tag="NNP" in="3:subj|4:[subj]" out="-2:pnct|-1:title|1:nobj|2:pnct">Marcus</W>
<W msd="NP=S" tag="NNP" in="-1:nobj" out="">Night</W>
<W msd="XP" tag="&amp;quot;" in="-2:pnct" out="">"</W>
<W msd="VADR" tag="VBZ" in="-12:vobj" out="-3:subj|-10:loc|1:preds">is</W>
<W msd="VAP" tag="VBN" in="-1:preds" out="-4:[subj]|1:preds">called</W>
<W msd="PI" tag="DT" in="-1:preds" out="1:nobj">an</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj.dobj|1:{patient}">account</W>
<W msd="SP" tag="IN" in="-1:pobj.dobj|-1:{patient}" out="1:nobj|7:pnct|8:conj|14:pnct|15:conj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj.pobj|1:{patient}">longing</W>
<W msd="U=" tag="TO" in="-1:pobj.pobj|-1:{patient}" out="1:vobj">to</W>
<W _noerror="&3a;nosubj&3a;" msd="VAF" tag="VB" in="-1:vobj" out="1:dobj">understand</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:attr">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">inconceivable</W>
<W msd="XP" tag="," in="-7:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-8:conj" out="1:nobj">of</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj.pobj|1:{patient}">search</W>
<W msd="SP" tag="IN" in="-1:pobj.pobj|-1:{patient}" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr">the</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">impossible</W>
<W msd="XP" tag="," in="-14:pnct" out="">,</W>
<W msd="SP" tag="IN" in="-15:conj" out="1:nobj">of</W>
<W msd="VAG" tag="VBG" in="-1:nobj" out="1:dobj">exceeding</W>
<W msd="PD" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="1:pobj|1:{arg}">boundary</W>
<W msd="SP" tag="IN" in="-1:pobj|-1:{arg}" out="1:nobj">for</W>
<W msd="PD" tag="DT" in="-1:nobj" out="1:attr|2:nobj">all</W>
<W msd="ANP" tag="JJ" in="-1:attr" out="">human</W>
<W msd="NC=S" tag="NN" in="-2:nobj" out="">ability</W>
<W msd="XP" tag="." in="-42:pnct" out="">.</W>
</s>
<s>
<W msd="ANP" tag="RB" in="1:quant" out="">So</W>
<W msd="ANP" tag="JJ" in="1:attr" out="-1:quant">great</W>
<W msd="PI" tag="DT" in="6:nobj" out="-1:attr|1:nobj">an</W>
<W msd="NC=S" tag="NN" in="-1:nobj" out="">errand</W>
<W msd="VADR" tag="VBZ" in="" out="2:subj|3:add|4:preds|5:pnct">is</W>
<W msd="NP=S" tag="NNP" in="1:namef" out="">Helle</W>
<W msd="NP=S" tag="NNP" in="-2:subj" out="-1:namef">Stangerup</W>
<W msd="ANP" tag="RB" in="-3:add" out="">also</W>
<W msd="SP" tag="IN" in="-4:preds" out="-6:nobj">on</W>
<W msd="XP" tag="." in="-5:pnct" out="">.</W>
</s>
