<W lemma="si" msd="CSUBX" in="" out="">Si</W>
<W lemma="el" msd="ART" in="" out="1:nobj">la</W>
<W lemma="empresa" msd="NC" in="-1:nobj" out="">empresa</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="ser" msd="VSfin" in="" out="-1:neg">sea</W>
<W lemma="capaz" msd="ADJ" in="" out="">capaz</W>
<W lemma="realizar" msd="VLinf" in="" out="">realizar</W>
<W lemma="el" msd="ART" in="" out="1:nobj">las</W>
<W lemma="medición" msd="NC" in="-1:nobj" out="">mediciones</W>
<W lemma="exigir" msd="VLadj" in="" out="">exigidas</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:pnct|1:vobj|6:loc|11:pnct">deberÃ¡</W>
<W lemma="buscar" msd="VLinf" in="-1:vobj" out="4:dobj">buscar</W>
<W lemma="por" msd="PREP" in="" out="1:nobj">por</W>
<W lemma="cuenta" msd="NC" in="-1:nobj" out="1:attrr">cuenta</W>
<W lemma="propio" msd="ADJ" in="-1:attrr" out="">propia</W>
<W lemma="asistencia" msd="NC" in="-4:dobj" out="">asistencia</W>
<W lemma="en" msd="PREP" in="-6:loc" out="1:nobj">en</W>
<W lemma="laboratorio" msd="NC" in="-1:nobj" out="1:attrr">laboratorios</W>
<W lemma="privado" msd="ADJ" in="-1:attrr" out="2:conj">privados</W>
<W lemma="o" msd="CC" in="1:coord" out="">o</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:conj" out="-1:coord">pÃºblicos</W>
<W lemma="." msd="FS" in="-11:pnct" out="">.</W>
<W lemma="el" msd="ART" in="4:subj" out="1:nobj">Las</W>
<W lemma="autoridad" msd="NC" in="-1:nobj" out="1:pobj:subj#">autoridades</W>
<W lemma="de" msd="PREP" in="-1:pobj:subj#" out="1:nobj">de</W>
<W lemma="control" msd="NC" in="-1:nobj" out="">control</W>
<W lemma="poder" msd="VMfin" in="" out="-4:subj|1:pnct|2:struct|3:pnct|4:dobj">pueden</W>
<W lemma="," msd="CM" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="ADV" in="-2:struct" out="">ademÃ¡s</W>
<W lemma="," msd="CM" in="-3:pnct" out="">,</W>
<W lemma="ordenar" msd="VLinf" in="-4:dobj" out="">ordenar</W>
<W lemma="que" msd="CQUE" in="" out="">que</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">anÃ¡lisis</W>
<W lemma="relacionar" msd="VLadj" in="" out="">relacionados</W>
<W lemma="al" msd="PAL" in="" out="">al</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">autocontrol</W>
<W lemma="se" msd="SE" in="" out="">se</W>
<W lemma="realizar" msd="VLfin" in="" out="">realicen</W>
<W lemma="total" msd="ADJ" in="" out="">total</W>
<W lemma="o" msd="CC" in="" out="">o</W>
<W lemma="parcialmente" msd="ADV" in="" out="">parcialmente</W>
<W lemma="por" msd="PREP" in="" out="">por</W>
<W lemma="un" msd="ART" in="" out="">un</W>
<W lemma="laboratorio" msd="NC" in="" out="">laboratorio</W>
<W lemma="independiente" msd="ADJ" in="" out="">independiente</W>
<W lemma="si" msd="CSUBX" in="" out="">si</W>
<W lemma="surgir" msd="VLfin" in="" out="">surgen</W>
<W lemma="duda" msd="NC" in="" out="">dudas</W>
<W lemma="sobre" msd="PREP" in="" out="">sobre</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="control" msd="NC" in="" out="">control</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="resultado" msd="NC" in="" out="">resultados</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">anÃ¡lisis</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="">VÃ©ase</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">ademÃ¡s</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="apartado" msd="NC" in="" out="">apartado</W>
<W lemma="@card@" msd="CODE" in="" out="">5.3</W>
<W lemma="sobre" msd="PREP" in="" out="">sobre</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="control" msd="NC" in="" out="">controles</W>
<W lemma="por" msd="PREP" in="" out="">por</W>
<W lemma="muestreo" msd="NC" in="" out="">muestreo</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="apartado" msd="NC" in="" out="">apartado</W>
<W lemma="@card@" msd="CODE" in="" out="">5.6</W>
<W lemma="sobre" msd="PREP" in="" out="">sobre</W>
<W lemma="el" msd="ART" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">realizaciÃ³n</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">anÃ¡lisis</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="laboratorio" msd="NC" in="" out="">laboratorios</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="@card@" msd="CODE" in="" out="">5.2</W>
<W lemma="registro" msd="NC" in="" out="">Registro</W>
<W lemma="del" msd="PDEL" in="" out="">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">autocontrol</W>
<W lemma="el" msd="ART" in="" out="">Los</W>
<W lemma="resultado" msd="NC" in="" out="">resultados</W>
<W lemma="del" msd="PDEL" in="" out="">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">autocontrol</W>
<W lemma="deber" msd="VMfin" in="" out="">deben</W>
<W lemma="registrarse" msd="VCLI" in="" out="">registrarse</W>
<W lemma="y" msd="CC" in="" out="">e</W>
<W lemma="introducirse" msd="VCLI" in="" out="">introducirse</W>
<W lemma="en" msd="PREP" in="" out="">en</W>
<W lemma="un" msd="ART" in="" out="">un</W>
<W lemma="libro" msd="NC" in="" out="">libro</W>
<W lemma="diario" msd="ADJ" in="" out="">diario</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="que" msd="CQUE" in="" out="">que</W>
<W lemma="deber" msd="VMfin" in="" out="">debe</W>
<W lemma="estar" msd="VEinf" in="" out="">estar</W>
<W lemma="disponible" msd="ADJ" in="" out="">disponible</W>
<W lemma="para" msd="PREP" in="" out="">para</W>
<W lemma="el" msd="ART" in="" out="">las</W>
<W lemma="autoridad" msd="NC" in="" out="">autoridades</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="control" msd="NC" in="" out="">control</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="conservarse" msd="VCLI" in="" out="">conservarse</W>
<W lemma="durante" msd="PREP" in="" out="">durante</W>
<W lemma="un" msd="ART" in="" out="">una</W>
<W lemma="cantidad" msd="NC" in="" out="">cantidad</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">aÃ±os</W>
<W lemma="determinar" msd="VLadj" in="" out="">determinada</W>
<W lemma="por" msd="PREP" in="" out="">por</W>
<W lemma="el" msd="ART" in="" out="">las</W>
<W lemma="autoridad" msd="NC" in="" out="">autoridades</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="control" msd="NC" in="" out="">control</W>
<W lemma="(" msd="LP" in="" out="">(</W>
<W lemma="se" msd="SE" in="" out="">se</W>
<W lemma="recomendar" msd="VLfin" in="" out="">recomienda</W>
<W lemma="un" msd="ART" in="" out="">un</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">perÃ­odo</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="al~menos" msd="ADV" in="" out="">al menos</W>
<W lemma="5" msd="CARD" in="" out="">5</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">aÃ±os</W>
<W lemma=")" msd="RP" in="" out="">)</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="en" msd="PREP" in="" out="">En</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="libro" msd="NC" in="" out="">libro</W>
<W lemma="diario" msd="ADJ" in="" out="">diario</W>
<W lemma="deber" msd="VMfin" in="" out="">deben</W>
<W lemma="registrarse" msd="VCLI" in="" out="">registrarse</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">ademÃ¡s</W>
<W lemma="todo" msd="QU" in="" out="">todas</W>
<W lemma="el" msd="ART" in="" out="">las</W>
<W lemma="irregularidad" msd="NC" in="" out="">irregularidades</W>
<W lemma="en" msd="PREP" in="" out="">en</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="funcionamiento" msd="NC" in="" out="">funcionamiento</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="suyo" msd="PPO" in="" out="">sus</W>
<W lemma="consecuencia" msd="NC" in="" out="">consecuencias</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">soluciones.Todos</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="resultado" msd="NC" in="" out="">resultados</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">anÃ¡lisis</W>
<W lemma="deber" msd="VMfin" in="" out="">deben</W>
<W lemma="&lt;unknown&gt;" msd="VLinf" in="" out="">acompaÃ±arse</W>
<W lemma="en" msd="PREP" in="" out="">en</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="registro" msd="NC" in="" out="">registro</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="información" msd="NC" in="" out="">informaciones</W>
<W lemma="preciso" msd="ADJ" in="" out="">precisas</W>
<W lemma="sobre" msd="PREP" in="" out="">sobre</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="tiempo" msd="NC" in="" out="">tiempo</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="lugar" msd="NC" in="" out="">lugar</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="suyo" msd="PPO" in="" out="">su</W>
<W lemma="toma" msd="NC" in="" out="">toma</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="" out="">asÃ­</W>
<W lemma="como" msd="CSUBX" in="" out="">como</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">mÃ©todos</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">anÃ¡lisis</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="en~todo~caso" msd="ADV" in="" out="">En todo caso</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="irregularidad" msd="NC" in="" out="">irregularidad</W>
<W lemma="en" msd="PREP" in="" out="">en</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="funcionamiento" msd="NC" in="" out="">funcionamiento</W>
<W lemma="que" msd="CQUE" in="" out="">que</W>
<W lemma="poder" msd="VMfin" in="" out="">pueda</W>
<W lemma="implicar" msd="VLinf" in="" out="">implicar</W>
<W lemma="emisión" msd="NC" in="" out="">emisiones</W>
<W lemma="perjudicial" msd="ADJ" in="" out="">perjudiciales</W>
<W lemma="para" msd="PREP" in="" out="">para</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="medio" msd="NC" in="" out="">medio</W>
<W lemma="ambiente" msd="ADJ" in="" out="">ambiente</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="el" msd="ART" in="" out="">la</W>
<W lemma="naturaleza" msd="NC" in="" out="">naturaleza</W>
<W lemma="o" msd="CC" in="" out="">o</W>
<W lemma="el" msd="ART" in="" out="">la</W>
<W lemma="salud" msd="NC" in="" out="">salud</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="o" msd="CC" in="" out="">o</W>
<W lemma="que" msd="CQUE" in="" out="">que</W>
<W lemma="simplemente" msd="ADV" in="" out="">simplemente</W>
<W lemma="implicar" msd="VLfin" in="" out="">implique</W>
<W lemma="un" msd="ART" in="" out="">un</W>
<W lemma="riesgo" msd="NC" in="" out="">riesgo</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="él" msd="PPX" in="" out="">ello</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="se" msd="SE" in="" out="">se</W>
<W lemma="deber" msd="VMfin" in="" out="">debe</W>
<W lemma="informar" msd="VLinf" in="" out="">informar</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="forma" msd="NC" in="" out="">forma</W>
<W lemma="inmediato" msd="ADJ" in="" out="">inmediata</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="el" msd="ART" in="" out="">las</W>
<W lemma="autoridad" msd="NC" in="" out="">autoridades</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="control" msd="NC" in="" out="">control</W>
<W lemma="o" msd="CC" in="" out="">o</W>
<W lemma="al" msd="PAL" in="" out="">al</W>
<W lemma="instituto" msd="NC" in="" out="">instituto</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="veterinario" msd="NC" in="" out="">veterinarios</W>
<W lemma="oficial" msd="ADJ" in="" out="">oficiales</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="">vÃ©ase</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">Â§20</W>
<W lemma="." msd="FS" in="" out="">.</W>
