<W lemma="y" msd="CC" in="" out="">Y</W>
<W lemma="luego" msd="CSUBF" in="1:struct" out="">luego</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:struct|1:dobj">habÃ­a</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="tema" msd="NC" in="-1:nobj" out="1:about">tema</W>
<W lemma="de" msd="PREP" in="-1:about" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj|4:ref|5:relr">las</W>
<W lemma="lista" msd="NC" in="-1:nobj" out="1:about#">listas</W>
<W lemma="de" msd="PREP" in="-1:about#" out="1:nobj">de</W>
<W lemma="espera" msd="NC" in="-1:nobj" out="">espera</W>
<W lemma="que" msd="CQUE" in="-4:ref|1:subj|2:[subj]" out="">que</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-5:relr" out="-1:subj|1:vobj|2:pnct|3:coref-res">debÃ­an</W>
<W lemma="eliminarse" msd="VCLI" in="-1:vobj" out="-2:[subj]">eliminarse</W>
<W lemma="." msd="FS" in="-2:pnct" out="">.</W>
<W lemma="este" msd="DM" in="-3:coref-res|2:xtop" out="1:ref">Esto</W>
<W lemma="él" msd="PPO" in="-1:ref|1:dobj" out="">lo</W>
<W lemma="solucionar" msd="VLfin" in="" out="-2:xtop|-1:dobj|2:subj|3:pnct|4:bg|9:pnct|10:vobj">soluciona</W>
<W lemma="John" msd="NP" in="1:namef" out="">John</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:subj|8:[subj]" out="-1:namef">Winther</W>
<W lemma="," msd="CM" in="-3:pnct" out="">,</W>
<W lemma="en" msd="PREP" in="-4:bg" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="caso" msd="NC" in="-1:nobj" out="1:pobj:arg">caso</W>
<W lemma="de" msd="PREP" in="-1:pobj:arg" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">TEBA</W>
<W lemma="," msd="CM" in="-9:pnct" out="">,</W>
<W lemma="incorporar" msd="VLadj" in="-10:vobj" out="1:pobj|22:coref-res|-8:[subj]">incorporando</W>
<W lemma="a" msd="PREP" in="-1:pobj" out="1:nobj">a</W>
<W lemma="todo" msd="QU" in="-1:nobj" out="1:nobj">todos</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj|2:ref|3:relr">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">niÃ±os</W>
<W lemma="que" msd="CQUE" in="-2:ref|1:subj" out="">que</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-3:relr" out="-1:subj|1:loc|5:pnct">estan</W>
<W lemma="en" msd="PREP" in="-1:loc" out="1:nobj">en</W>
<W lemma="lista" msd="NC" in="-1:nobj" out="1:about#">lista</W>
<W lemma="de" msd="PREP" in="-1:about#" out="1:nobj">de</W>
<W lemma="espera" msd="NC" in="-1:nobj" out="">espera</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="ser" msd="VSfin" in="" out="1:degr">Es</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="-1:degr" out="">asÃ­</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="simple" msd="ADJ" in="" out="">simple</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="en" msd="PREP" in="6:bg" out="1:nobj">En</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="caso" msd="NC" in="-1:nobj" out="1:pobj:arg">caso</W>
<W lemma="de" msd="PREP" in="-1:pobj:arg" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">TEBA</W>
<W lemma="este" msd="DM" in="-22:coref-res|1:subj" out="">esto</W>
<W lemma="significar" msd="VLfin" in="" out="-1:subj|-6:bg|1:dobj">significa</W>
<W lemma="que" msd="CQUE" in="-1:dobj" out="2:other|8:vobj">que</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="de" msd="CSUBI" in="-2:other" out="1:vobj">de</W>
<W lemma="ser" msd="VSinf" in="-1:vobj" out="1:subj|3:time">ser</W>
<W lemma="@card@" msd="CARD" in="-1:subj" out="1:nobj|12:struct">45</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">niÃ±os</W>
<W lemma="en" msd="PREP" in="-3:time" out="1:nobj">en</W>
<W lemma="@card@" msd="CARD" in="-1:nobj" out="">1991</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-8:vobj" out="1:subj|3:time|5:pnct">serÃ¡n</W>
<W lemma="@card@" msd="CODE" in="-1:subj" out="1:nobj">55</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">niÃ±os</W>
<W lemma="en" msd="PREP" in="-3:time" out="1:nobj">en</W>
<W lemma="@card@" msd="CARD" in="-1:nobj" out="">1992</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="estar" msd="VLfin" in="" out="1:vobj|23:assoc-cause">Estamos</W>
<W lemma="hablar" msd="VLger" in="-1:vobj" out="2:pobj">hablando</W>
<W lemma="entonces" msd="ADV" in="-12:struct" out="">entonces</W>
<W lemma="de" msd="PREP" in="-2:pobj" out="1:nobj">de</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="aumento" msd="NC" in="-1:nobj" out="">aumento</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">mÃ¡s</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="un" msd="ART" in="" out="">un</W>
<W lemma="@card@" msd="CARD" in="" out="">10</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">%.</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:preds" out="">Claro</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:preds|1:subj">estÃ¡</W>
<W lemma="que" msd="CQUE" in="-1:subj" out="6:vobj">que</W>
<W lemma="el" msd="ART" in="5:subj" out="1:nobj">la</W>
<W lemma="superficie" msd="NC" in="-1:nobj" out="1:pobj:arg">superficie</W>
<W lemma="de" msd="PREP" in="-1:pobj:arg" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">TEBA</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-6:vobj" out="-5:subj|-1:neg|1:preds|2:cause|5:pnct">serÃ¡</W>
<W lemma="ampliar" msd="VLadj" in="-1:preds" out="">ampliada</W>
<W lemma="por" msd="PREP" in="-2:cause" out="1:nobj">por</W>
<W lemma="este" msd="DM" in="-1:nobj|-23:assoc-cause" out="1:nobj">esta</W>
<W lemma="causa" msd="NC" in="-1:nobj" out="">causa</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="no" msd="NEG" in="1:neg" out="">No</W>
<W lemma="ser" msd="VSfin" in="" out="-1:neg|1:subj|3:preds">es</W>
<W lemma="el" msd="ART" in="-1:subj" out="1:nobj">la</W>
<W lemma="idea" msd="NC" in="-1:nobj" out="">idea</W>
<W lemma="poner" msd="VLinf" in="-3:preds" out="1:dir|4:dobj">poner</W>
<W lemma="en" msd="PREP" in="-1:dir" out="1:nobj">en</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="lado" msd="NC" in="-1:nobj" out="">lado</W>
<W lemma="el" msd="ART" in="-4:dobj" out="1:ref|3:relr">lo</W>
<W lemma="que" msd="CQUE" in="-1:ref|2:dobj" out="">que</W>
<W lemma="se" msd="SE" in="1:subj" out="">se</W>
<W lemma="ganar" msd="VLfin" in="-3:relr" out="-1:subj|-2:dobj|1:loc|3:pnct">gana</W>
<W lemma="por" msd="PREP" in="-1:loc" out="1:nobj">por</W>
<W lemma="otro" msd="QU" in="-1:nobj" out="">otro</W>
<W lemma="." msd="FS" in="-3:pnct" out="">.</W>
<W lemma="en" msd="PREP" in="3:time" out="1:nobj">En</W>
<W lemma="@card@" msd="CARD" in="-1:nobj" out="">1992</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="haber" msd="VHfin" in="" out="-3:time|1:vobj|8:pnct|-1:robj">han</W>
<W lemma="destinar" msd="VLadj" in="-1:vobj" out="1:dobj|4:other">destinado</W>
<W lemma="dos" msd="CARD" in="-1:dobj" out="1:nobj">dos</W>
<W lemma="metro" msd="NC" in="-1:nobj" out="1:attrr">metros</W>
<W lemma="cuadrar" msd="VLadj" in="-1:attrr" out="">cuadrados</W>
<W lemma="por" msd="PREP" in="-4:other" out="1:nobj">por</W>
<W lemma="cada" msd="QU" in="-1:nobj" out="1:nobj">cada</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">niÃ±o</W>
<W lemma="." msd="FS" in="-8:pnct" out="">.</W>
<W lemma="y" msd="CC" in="" out="">Y</W>
<W lemma="se" msd="SE" in="1:subj" out="">se</W>
<W lemma="calcular" msd="VLfin" in="" out="-1:subj|1:man|7:pnct">calcula</W>
<W lemma="de" msd="PREP" in="-1:man" out="2:nobj">de</W>
<W lemma="igual" msd="ADJ" in="1:attrd" out="">igual</W>
<W lemma="manera" msd="NC" in="-2:nobj" out="-1:attrd|1:comp">manera</W>
<W lemma="que" msd="CQUE" in="-1:comp" out="1:nobj">que</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="alquiler" msd="NC" in="-1:nobj" out="">alquiler</W>
<W lemma=":" msd="COLON" in="-7:pnct" out="">:</W>
<W lemma="todo" msd="QU" in="1:subj" out="">todo</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="-1:subj|1:preds|2:pnct">estÃ¡</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="-1:preds" out="">incluÃ­do</W>
<W lemma="." msd="FS" in="-2:pnct" out="">.</W>
<W lemma="servicio" msd="NC" in="" out="">Servicios</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="superficie" msd="NC" in="" out="">superficies</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="corredor" msd="NC" in="" out="">corredores</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="pasillo|paso" msd="NC" in="" out="">pasillos</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="cocinar" msd="VLfin" in="" out="">cocinas</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="el" msd="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">pedagogos</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="etc." msd="PE" in="" out="">etc.</W>
<W lemma="un" msd="ART" in="7:subj" out="1:nobj">Un</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="2:attrr">niÃ±o</W>
<W lemma="bien" msd="ADV" in="1:degr" out="">bien</W>
<W lemma="desarrollar" msd="VLadj" in="-2:attrr" out="-1:degr">desarrollado</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="5" msd="CARD" in="" out="">5</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">aÃ±os</W>
<W lemma="pesar" msd="VLfin" in="" out="-7:subj|5:pnct">pesa</W>
<W lemma="alrededor" msd="PREP" in="" out="">alrededor</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="@card@" msd="CARD" in="" out="3:ref|6:relr">19</W>
<W lemma="kilo" msd="NC" in="" out="">kilos</W>
<W lemma="," msd="CM" in="-5:pnct" out="">,</W>
<W lemma="que" msd="CQUE" in="-3:ref|3:subj" out="">que</W>
<W lemma="por~lo~tanto" msd="CSUBF" in="2:cons" out="">por lo tanto</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="repartir" msd="VLfin" in="-6:relr" out="-3:subj|-1:robj|-2:cons|1:pobj|5:pnct">reparten</W>
<W lemma="en" msd="PREP" in="-1:pobj" out="1:nobj">en</W>
<W lemma="2" msd="CARD" in="-1:nobj" out="1:nobj">2</W>
<W lemma="metro" msd="NC" in="-1:nobj" out="1:attrr">metros</W>
<W lemma="cuadrar" msd="VLadj" in="-1:attrr" out="">cuadrados</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="ser" msd="VSfin" in="" out="1:subj|3:other|6:pnct">Son</W>
<W lemma="@card@" msd="CARD" in="-1:subj" out="1:nobj">9,5</W>
<W lemma="kilo" msd="NC" in="-1:nobj" out="">kilos</W>
<W lemma="por" msd="PREP" in="-3:other" out="1:nobj">por</W>
<W lemma="metro" msd="NMEA" in="-1:nobj" out="1:attrr">metro</W>
<W lemma="cuadrado" msd="NC" in="-1:attrr" out="">cuadrado</W>
<W lemma="." msd="FS" in="-6:pnct" out="">.</W>
<W lemma="o" msd="CC" in="" out="">O</W>
<W lemma="aproximadamente" msd="ADV" in="" out="">aproximadamente</W>
<W lemma="@card@" msd="CARD" in="" out="">1050</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">centÃ­metros</W>
<W lemma="cuadrar" msd="VLadj" in="" out="">cuadrados</W>
<W lemma="por" msd="PREP" in="" out="">por</W>
<W lemma="kilo" msd="NC" in="" out="">kilo</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">niÃ±o</W>
<W lemma="." msd="FS" in="" out="">.</W>
