<W lemma="si" msd="CSUBX" in="6:cond" out="1:vobj">Si</W>
<W lemma="haber" msd="VHfin" in="-1:vobj" out="1:dobj|4:pnct">hay</W>
<W lemma="problema" msd="NC" in="-1:dobj" out="1:pobj&3a;about|6:assoc">problemas</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;about" out="1:nobj">de</W>
<W lemma="salud" msd="NC" in="-1:nobj" out="">salud</W>
<W lemma="," msd="CM" in="-4:pnct" out="">,</W>
<W lemma="escriba" msd="NC" in="" out="-6:cond|1:iobj|25:assoc-scope">escriba</W>
<W lemma="a" msd="PREP" in="-1:iobj" out="1:nobj">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj|-6:assoc" out="1:pnct|2:pnct|3:list|5:pnct|6:list|8:pnct|9:list|13:coref-id">“Los</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:pnct" out="">médicos”</W>
<W lemma="," msd="CM" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-3:list" out="1:appr|13:coref-var">Ugemagasinet</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:appr" out="">SØNDAG</W>
<W lemma="," msd="CM" in="-5:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-6:list" out="1:list">Vesterbrogade</W>
<W lemma="@card@" msd="CODE" in="-1:list" out="">16</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="@card@" msd="CODE" in="-9:list" out="1:list">1505</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:list" out="1:list">København</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:list" out="">V.</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:degr" out="">Sólo</W>
<W lemma="el" msd="ART" in="-13:coref-id|7:subj" out="-1:degr|1:nobj|18:coref-id|18:coref-id">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:pobj&3a;origin">médicos</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;origin" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj|-13:coref-var" out="1:nobj|3:appr">la</W>
<W lemma="revista" msd="NC" in="-1:nobj" out="1:attrr#">revista</W>
<W lemma="semanal" msd="ADJ" in="-1:attrr#" out="">semanal</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-3:appr" out="">SØNDAG</W>
<W lemma="tener" msd="VLfin" in="" out="-7:subj|1:dobj|5:pnct">tienen</W>
<W lemma="permiso" msd="NC" in="-1:dobj" out="1:pobj">permiso</W>
<W lemma="a" msd="PREP" in="-1:pobj" out="1:nobj">a</W>
<W lemma="suyo" msd="PPO" in="-1:nobj|-25:assoc-scope" out="1:possd|13:coref-var">su</W>
<W lemma="carta" msd="NC" in="-1:possd" out="">carta</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="1:pnct|2:pnct|8:xpl">¡Note</W>
<W lemma="!" msd="FS" in="-1:pnct" out="">!</W>
<W lemma="&3a;" msd="COLON" in="-2:pnct" out="">:</W>
<W lemma="lamentable" msd="ADV" in="5:prg" out="1:pnct">Lamentablemente</W>
<W lemma="," msd="CM" in="-1:pnct" out="">,</W>
<W lemma="el" msd="ART" in="-18:coref-id|-18:coref-id|3:subj|4:[subj]" out="1:nobj|44:coref-id">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">médicos</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="poder" msd="VMfin" in="-8:xpl" out="-3:subj|-5:prg|-1:neg|1:vobj|5:pnct">pueden</W>
<W lemma="brindar" msd="VLinf" in="-1:vobj" out="-4:[subj]|1:dobj">brindar</W>
<W lemma="un" msd="ART" in="-1:dobj|-13:coref-var" out="1:nobj">una</W>
<W lemma="respuesta" msd="NC" in="-1:nobj" out="1:attr">respuesta</W>
<W lemma="personal" msd="NC" in="-1:attr" out="">personal</W>
<W lemma="." msd="FS" in="-5:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="1:attrr#|2:time|5:pnct|11:coref-id">¿PÍLDORAS</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:attrr#" out="">ANTICONCEPTIVAS</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:time" out="1:nobj">EN</W>
<W lemma="La" msd="NP" in="-1:nobj" out="1:nobj">LA</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">MENOPAUSIA</W>
<W lemma="?" msd="FS" in="-5:pnct" out="">?</W>
<W lemma="mucho" msd="QU" in="2:subj|3:[subj]" out="1:nobj">Muchas</W>
<W lemma="mujer" msd="NC" in="-1:nobj" out="">mujeres</W>
<W lemma="desear" msd="VLfin" in="" out="-2:subj|1:vobj|6:time|15:pnct|17:coref-res">desean</W>
<W lemma="prescindir" msd="VLinf" in="-1:vobj" out="-3:[subj]|1:pobj">prescindir</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj|-11:coref-id" out="1:nobj|38:coref-id">las</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attrr#">píldoras</W>
<W lemma="anticonceptivo" msd="ADJ" in="-1:attrr#" out="">anticonceptivas</W>
<W lemma="cuando" msd="CSUBX" in="-6:time" out="2:vobj">cuando</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="acercar" msd="VLfin" in="-2:vobj" out="-1:robj|1:pobj">acercan</W>
<W lemma="a" msd="PREP" in="-1:pobj" out="1:nobj">a</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="edad" msd="NC" in="-1:nobj" out="1:pobj">edad</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="cincuenta" msd="CARD" in="-1:nobj" out="1:nobj">cincuenta</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">años</W>
<W lemma="." msd="FS" in="-15:pnct" out="">.</W>
<W lemma="pero" msd="CCAD" in="" out="2:conj|28:pnct">Pero</W>
<W lemma="este" msd="DM" in="-17:coref-res|1:subj" out="">esto</W>
<W lemma="implicar" msd="VLfin" in="-2:conj" out="-1:subj|1:dobj">implica</W>
<W lemma="un" msd="ART" in="-1:dobj" out="2:nobj">una</W>
<W lemma="largo" msd="ADJ" in="1:attr" out="">larga</W>
<W lemma="serie" msd="NC" in="-2:nobj" out="-1:attr|1:pobj&3a;arg">serie</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;arg" out="1:nobj">de</W>
<W lemma="pregunta" msd="NC" in="-1:nobj" out="6:rel|12:mod">preguntas</W>
<W lemma="a" msd="PREP" in="5:pobj" out="1:nobj">a</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="que" msd="CQUE" in="-1:nobj" out="">que</W>
<W lemma="el" msd="ART" in="-44:coref-id|2:subj" out="1:nobj">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">médicos</W>
<W lemma="responder" msd="VLfin" in="-6:rel" out="-5:pobj|-2:subj|1:loc|2:pnct">responden</W>
<W lemma="&lt;unknown&gt;" msd="VLinf" in="-1:loc" out="">aquí</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="-2:pnct" out="">–</W>
<W lemma="entre" msd="PREP" in="3:ex" out="1:nobj">entre</W>
<W lemma="otro" msd="QU" in="-1:nobj" out="1:nobj">otras</W>
<W lemma="cosa" msd="NC" in="-1:nobj" out="">cosas</W>
<W lemma="acerca~de" msd="PREP" in="-12:mod" out="-3:ex|1:nobj">acerca de</W>
<W lemma="si" msd="NC" in="-1:nobj" out="3:vobj">si</W>
<W lemma="el" msd="ART" in="2:subj|3:[subj]" out="1:nobj">las</W>
<W lemma="hormona" msd="NC" in="-1:nobj" out="">hormonas</W>
<W lemma="poder" msd="VMfin" in="-3:vobj" out="-2:subj|1:vobj">pueden</W>
<W lemma="reemplazar" msd="VLinf" in="-1:vobj" out="-3:[subj]|1:dobj">reemplazar</W>
<W lemma="el" msd="ART" in="-1:dobj|-38:coref-id" out="1:nobj|15:coref-id|15:coref-id">las</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attrr#">píldoras</W>
<W lemma="anticonceptivo" msd="ADJ" in="-1:attrr#" out="">anticonceptivas</W>
<W lemma="." msd="FS" in="-28:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="1:pnct|3:list">Ilustración</W>
<W lemma="&3a;" msd="COLON" in="-1:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:namef" out="">Ole</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-3:list" out="-1:namef">Clausen</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:subj" out="5:coref">Bodil</W>
<W lemma="tener" msd="VLfin" in="" out="-1:subj|1:dobj|3:pnct">tiene</W>
<W lemma="@card@" msd="CARD" in="-1:dobj" out="1:nobj">49</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">años</W>
<W lemma="." msd="FS" in="-3:pnct" out="">.</W>
<W lemma="haber" msd="VHfin" in="-5:coref" out="1:vobj|4:time|7:pnct|8:coref">Ha</W>
<W lemma="tomar" msd="VLadj" in="-1:vobj" out="1:dobj">tomado</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:dobj|-15:coref-id|-15:coref-id" out="1:attrr#|37:coref-id">píldoras</W>
<W lemma="anticonceptivo" msd="ADJ" in="-1:attrr#" out="">anticonceptivas</W>
<W lemma="durante" msd="PREP" in="-4:time" out="1:nobj">durante</W>
<W lemma="mucho" msd="QU" in="-1:nobj" out="1:nobj">muchos</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">años</W>
<W lemma="." msd="FS" in="-7:pnct" out="">.</W>
<W lemma="tener" msd="VLfin" in="-8:coref" out="1:dobj|3:fpredo|4:time|8:pnct|10:conj|10:coref|14:conj|25:pnct|26:coref-res">Tuvo</W>
<W lemma="3" msd="CARD" in="-1:dobj" out="1:nobj">3</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">niños</W>
<W lemma="seguir" msd="VLadj" in="-3:fpredo" out="">seguidos</W>
<W lemma="a" msd="PREP" in="-4:time" out="1:nobj">a</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj">una</W>
<W lemma="edad" msd="NC" in="-1:nobj" out="1:attr">edad</W>
<W lemma="temprano" msd="ADJ" in="-1:attr" out="">temprana</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="desear" msd="VLfin" in="-10:conj|-10:coref" out="-1:neg|1:vobj|4:coref">deseaba</W>
<W lemma="tener" msd="VLinf" in="-1:vobj" out="1:dobj">tener</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:dobj" out="">más</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-4:coref|-14:conj" out="-1:coord|1:vobj|4:cause|7:coref|16:coref">quería</W>
<W lemma="estar" msd="VEinf" in="-1:vobj" out="2:preds">estar</W>
<W lemma="completamente" msd="ADV" in="1:degr" out="">completamente</W>
<W lemma="seguro" msd="ADJ" in="-2:preds" out="-1:degr">segura</W>
<W lemma="a" msd="PREP" in="-4:cause" out="1:nobj">a</W>
<W lemma="causa" msd="NC" in="-1:nobj" out="1:pobj">causa</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="suyo" msd="PPO" in="-1:nobj|-7:coref" out="1:possd">su</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:possd" out="1:pobj&3a;arg">oposición</W>
<W lemma="al" msd="PAL" in="-1:pobj&3a;arg" out="1:nobj">al</W>
<W lemma="aborto" msd="NC" in="-1:nobj" out="">aborto</W>
<W lemma="." msd="FS" in="-25:pnct" out="">.</W>
<W lemma="esto~es" msd="ADV" in="-26:coref-res" out="1:preds">Esto es</W>
<W lemma="por" msd="PREP" in="-1:preds" out="1:nobj|3:rel">por</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj|30:coref-id">lo</W>
<W lemma="cual" msd="REL" in="-1:nobj" out="">cual</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-3:rel|-16:coref" out="1:dobj|7:coref|14:pnct">eligió</W>
<W lemma="el" msd="ART" in="-1:dobj|-37:coref-id" out="1:nobj|3:pnct|7:rel|11:assoc-scope">las</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attrr#">píldoras</W>
<W lemma="anticonceptivo" msd="ADJ" in="-1:attrr#" out="">anticonceptivas</W>
<W lemma="," msd="CM" in="-3:pnct" out="">,</W>
<W lemma="que" msd="CQUE" in="3:subj" out="">que</W>
<W lemma="en" msd="PREP" in="2:loc" out="1:nobj">en</W>
<W lemma="l" msd="PPX" in="-1:nobj|-7:coref" out="9:coref">ella</W>
<W lemma="funcionar" msd="VLfin" in="-7:rel" out="-3:subj|-2:loc|1:man">funcionaban</W>
<W lemma="bien" msd="ADV" in="-1:man" out="2:conj">bien</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="sin" msd="PREP" in="-2:conj" out="-1:coord|1:nobj">sin</W>
<W lemma="efecto" msd="NC" in="-1:nobj|-11:assoc-scope" out="1:attrr#">efectos</W>
<W lemma="secundario" msd="ADJ" in="-1:attrr#" out="">secundarios</W>
<W lemma="." msd="FS" in="-14:pnct" out="">.</W>
<W lemma="cuando" msd="CSUBX" in="4:time" out="1:vobj">Cuando</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-1:vobj|-9:coref" out="1:dobj|5:coref">cumplió</W>
<W lemma="@card@" msd="CARD" in="-1:dobj" out="1:nobj">40</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">años</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-4:time|1:pobj|3:pobj|12:pnct|17:conj|20:conj|36:pnct">hablé</W>
<W lemma="con" msd="PREP" in="-1:pobj" out="1:nobj">con</W>
<W lemma="l" msd="PPX" in="-1:nobj|-5:coref" out="12:coref-id">ella</W>
<W lemma="sobre" msd="PREP" in="-3:pobj" out="1:nobj">sobre</W>
<W lemma="otro" msd="QU" in="-1:nobj" out="1:nobj|4:contr">otro</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:pobj&3a;func#">método</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;func#" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">prevención</W>
<W lemma="en~lugar~de" msd="PREP" in="-4:contr" out="1:nobj">en lugar de</W>
<W lemma="el" msd="ART" in="-1:nobj|-30:coref-id" out="1:nobj">las</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attrr#">píldoras</W>
<W lemma="anticonceptivo" msd="ADJ" in="-1:attrr#" out="">anticonceptivas</W>
<W lemma="," msd="CM" in="-12:pnct" out="">,</W>
<W lemma="pero" msd="CCAD" in="4:coord" out="">pero</W>
<W lemma="l" msd="PPX" in="-12:coref-id|3:subj" out="">ella</W>
<W lemma="no" msd="NEG" in="2:neg" out="">no</W>
<W lemma="l" msd="PPO" in="1:dobj" out="">lo</W>
<W lemma="desear" msd="VLfin" in="-17:conj" out="-1:dobj|-3:subj|-2:neg|-4:coord|1:degr|3:coref|11:coref-res">deseaba</W>
<W lemma="en~absoluto" msd="ADV" in="-1:degr" out="">en absoluto</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-3:coref|-20:conj" out="-1:coord|1:avobj|4:dobj">tomó</W>
<W lemma="por" msd="PREP" in="-1:avobj" out="1:nobj">por</W>
<W lemma="cuenta" msd="NC" in="-1:nobj" out="1:attr">cuenta</W>
<W lemma="propio" msd="ADJ" in="-1:attr" out="">propia</W>
<W lemma="el" msd="ART" in="-4:dobj" out="2:nobj|3:ref|5:rel">los</W>
<W lemma="eventual" msd="ADJ" in="1:attr" out="">eventuales</W>
<W lemma="riesgo" msd="NC" in="-2:nobj" out="-1:attr">riesgos</W>
<W lemma="que" msd="CQUE" in="-3:ref|2:dobj" out="">que</W>
<W lemma="este" msd="DM" in="-11:coref-res|1:subj" out="">esto</W>
<W lemma="significar" msd="VLfin" in="-5:rel" out="-1:subj|-2:dobj|1:ben">significaba</W>
<W lemma="para" msd="PREP" in="-1:ben" out="1:nobj">para</W>
<W lemma="mujer" msd="NC" in="-1:nobj" out="1:attr">mujeres</W>
<W lemma="grande" msd="ADJ" in="-1:attr" out="1:pobj">mayores</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="@card@" msd="CARD" in="-1:nobj" out="1:nobj">40</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">años</W>
<W lemma="." msd="FS" in="-36:pnct" out="">.</W>
