<W msd="DASH" lemma="-">-</W>
<W msd="NEG" lemma="no">No</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="igual">igual</W>
<W msd="PREP" lemma="para">para</W>
<W msd="QU" lemma="todo">todos</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPO" lemma="t�">Tu</W>
<W msd="NC" lemma="madre">madre</W>
<W msd="VEfin" lemma="era">era</W>
<W msd="ADV" lemma="muy">muy</W>
<W msd="ADJ" lemma="delgado">delgada</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADJ" lemma="deportivo">deportiva</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="cuando">Cuando</W>
<W msd="PPX" lemma="�l">ella</W>
<W msd="VLfin" lemma="esperar">esperaba</W>
<W msd="PPO" lemma="nuestro">nuestra</W>
<W msd="NC" lemma="hijo">hija</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADV" lemma="apenas">apenas</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">podía</W>
<W msd="VLinf" lemma="ver">ver</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="estar">estaba</W>
<W msd="VLadj" lemma="embarazar">embarazada</W>
<W msd="PREP" lemma="hasta">hasta</W>
<W msd="ART" lemma="el">el</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">séptimo</W>
<W msd="NC" lemma="mes">mes</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPO" lemma="�l">Lo</W>
<W msd="VLfin" lemma="llevar">llevaba</W>
<W msd="ADV" lemma="bien">bien</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="VLfin" lemma="solar|soler">solemos</W>
<W msd="VLinf" lemma="decir">decir</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">aquí</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="Dinamarca">Dinamarca</W>
<W msd="FS" lemma=".">.</W>
<W msd="DASH" lemma="-">-</W>
<W msd="VMfin" lemma="deber">Debe</W>
<W msd="VHinf" lemma="haber">haber</W>
<W msd="VHadj" lemma="haber">habido</W>
<W msd="QU" lemma="otro">otro</W>
<W msd="NC" lemma="hombre">hombre</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">constató</W>
<W msd="NP" lemma="&lt;unknown&gt;">Loulou</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADJ" lemma="objetivo">objetiva</W>
<W msd="FS" lemma=".">.</W>
<W msd="DASH" lemma="-">-</W>
<W msd="NC" lemma="&lt;unknown&gt;">¿No</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">notabas</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="PPX" lemma="�l">ella</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">tenía</W>
<W msd="QU" lemma="otro">otro</W>
<W msd="NC" lemma="hombre">hombre</W>
<W msd="FS" lemma="?">?</W>
<W msd="NP" lemma="&lt;unknown&gt;">Bernie</W>
<W msd="VLfin" lemma="estar">estaba</W>
<W msd="ADJ" lemma="sentado">sentado</W>
<W msd="CC" lemma="y">y</W>
<W msd="VLadj" lemma="callar">callado</W>
<W msd="PREP" lemma="durante">durante</W>
<W msd="ADJ" lemma="largo">largo</W>
<W msd="NC" lemma="tiempo">tiempo</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADV" lemma="entonces">entonces</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">inclinó</W>
<W msd="PREP" lemma="hacia">hacia</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="interlocutor">interlocutora</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">miró</W>
<W msd="ADV" lemma="fijo">fijamente</W>
<W msd="FS" lemma=".">.</W>
<W msd="DASH" lemma="-">-</W>
<W msd="PPO" lemma="t�">Tu</W>
<W msd="NC" lemma="madre">madre</W>
<W msd="CC" lemma="y">y</W>
<W msd="PPX" lemma="yo">yo</W>
<W msd="PPX" lemma="nosotros">nos</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">amábamos</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="tener">tienes</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLinf" lemma="entender">entender</W>
<W msd="DM" lemma="este">esto</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPX" lemma="nosotros">Nos</W>
<W msd="VLfin" lemma="encontrar">encontramos</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="&lt;unknown&gt;">París</W>
<W msd="CC" lemma="y">y</W>
<W msd="VSfin" lemma="ser">fue</W>
<W msd="NC" lemma="amor">amor</W>
<W msd="ADV" lemma="a~primera~vista">a primera vista</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPX" lemma="�l">Ella</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VEfin" lemma="era">era</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="mujer">mujer</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VMfin" lemma="poder">pudiera</W>
<W msd="VLinf" lemma="tener">tener</W>
<W msd="NC" lemma="amor">amores</W>
<W msd="NC" lemma="secreto">secretos</W>
<W msd="CM" lemma=",">,</W>
<W msd="PPX" lemma="�l">ella</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">mentía</W>
<W msd="ADV" lemma="nunca">nunca</W>
<W msd="FS" lemma=".">.</W>
<W msd="DASH" lemma="-">-</W>
<W msd="ALFS" lemma="A">A</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">mí</W>
<W msd="PPX" lemma="yo">me</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">mintió</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPX" lemma="�l">Ella</W>
<W msd="PPX" lemma="yo">me</W>
<W msd="VLfin" lemma="hacer">hizo</W>
<W msd="VLinf" lemma="creer">creer</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">tú</W>
<W msd="VLfin" lemma="erar|ser">eras</W>
<W msd="PPO" lemma="m�o">mi</W>
<W msd="NC" lemma="padre">padre</W>
<W msd="FS" lemma=".">.</W>
<W msd="DASH" lemma="-">-</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Debió</W>
<W msd="VLinf" lemma="tener">tener</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="NC" lemma="motivo">motivos</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Loulou</W>
<W msd="FS" lemma=".">.</W>
<W msd="NEG" lemma="no">No</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VHinf" lemma="haber">haber</W>
<W msd="VS" lemma="ser">sido</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">fácil</W>
<W msd="PREP" lemma="para">para</W>
<W msd="PPX" lemma="�l">ella</W>
<W msd="VLinf" lemma="volver">volver</W>
<W msd="PREP" lemma="a">a</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="NC" lemma="padre">padres</W>
<W msd="PREP" lemma="bajo">bajo</W>
<W msd="DM" lemma="ese">esas</W>
<W msd="NC" lemma="circunstancia">circunstancias</W>
<W msd="FS" lemma=".">.</W>
<W msd="VEfin" lemma="estar">Estuvo</W>
<W msd="ADV" lemma="&lt;unknown&gt;">quizá</W>
<W msd="VLadj" lemma="obligar">obligada</W>
<W msd="PREP" lemma="a">a</W>
<W msd="VLinf" lemma="ocultar">ocultar</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="verdad">verdad</W>
<W msd="CC" lemma="y">y</W>
<W msd="QU" lemma="pocos">poco</W>
<W msd="PREP" lemma="a">a</W>
<W msd="QU" lemma="pocos">poco</W>
<W msd="PPO" lemma="�l">lo</W>
<W msd="VLfin" lemma="ir">fue</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">reprimiendo</W>
<W msd="ADV" lemma="totalmente">totalmente</W>
<W msd="FS" lemma=".">.</W>
<W msd="VEfin" lemma="era">Era</W>
<W msd="NC" lemma="&lt;unknown&gt;">más</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">fácil</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">así</W>
<W msd="CSUBI" lemma="para">para</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">ella...</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADV" lemma="&lt;unknown&gt;">quizá</W>
<W msd="PREP" lemma="para">para</W>
<W msd="NC" lemma="&lt;unknown&gt;">ti</W>
<W msd="FS" lemma=".">.</W>
<W msd="VMfin" lemma="deber">Debe</W>
<W msd="VHinf" lemma="haber">haber</W>
<W msd="VLadj" lemma="actuar">actuado</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">así</W>
<W msd="PREP" lemma="por">por</W>
<W msd="NC" lemma="amor">amor</W>
<W msd="PREP" lemma="a">a</W>
<W msd="NC" lemma="&lt;unknown&gt;">ti</W>
<W msd="FS" lemma=".">.</W>
