<W msd="NP" lemma="&lt;unknown&gt;">Rensch</W>
<W msd="NP" lemma="&lt;unknown&gt;">Nielsen</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Ebeltoft</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">tenía</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="concurso">concurso</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="feria">feria</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Vejle</W>
<W msd="ADV" lemma="acerca">acerca</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="nombre">nombre</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">alhaja</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">La</W>
<W msd="NC" lemma="&lt;unknown&gt;">solución</W>
<W msd="VEfin" lemma="era">era</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">“Personality”</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="premio">premio</W>
<W msd="PPO" lemma="l">lo</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">ganó</W>
<W msd="NP" lemma="&lt;unknown&gt;">Harald</W>
<W msd="NP" lemma="&lt;unknown&gt;">Jensen</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Vejle</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="de">DE</W>
<W msd="NP" lemma="&lt;unknown&gt;">BEERS</W>
<W msd="NP" lemma="&lt;unknown&gt;">CENTENARY</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">abrió</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="NC" lemma="oficina">oficinas</W>
<W msd="ART" lemma="el">el</W>
<W msd="CARD" lemma="8">8</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="setiembre">setiembre</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">Moscú</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="estar">Estaban</W>
<W msd="ADJ" lemma="presente">presentes</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="&lt;unknown&gt;">además</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="directivo">directivos</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">De</W>
<W msd="NP" lemma="&lt;unknown&gt;">Beers</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="&lt;unknown&gt;">políticos</W>
<W msd="ADJ" lemma="ruso">rusos</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">diplomáticos</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="representante">representantes</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="VLfin" lemma="industriar">industria</W>
<W msd="CC" lemma="y">y</W>
<W msd="VLfin" lemma="comerciar">comercio</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="diamante">diamantes</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="&lt;unknown&gt;">país</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="hacer">Hace</W>
<W msd="ADV" lemma="poco">poco</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">IB</W>
<W msd="NP" lemma="&lt;unknown&gt;">GAARN</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">orfebre</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Køge</W>
<W msd="CM" lemma=",">,</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="restaurar">restaurado</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="&lt;unknown&gt;">platería</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="un">una</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">araña</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="iglesia">iglesia</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Lellinge</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="&lt;unknown&gt;">Aquí</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="ver">ve</W>
<W msd="ADJ" lemma="junto">junto</W>
<W msd="PAL" lemma="al">al</W>
<W msd="VLadj" lemma="restaurar">restaurado</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">cáliz</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">300</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="FS" lemma=".">.</W>
<W msd="LP" lemma="(">(</W>
<W msd="NC" lemma="foto">Foto</W>
<W msd="COLON" lemma=":">:</W>
<W msd="NP" lemma="&lt;unknown&gt;">Stig</W>
<W msd="NP" lemma="&lt;unknown&gt;">Hansen</W>
<W msd="RP" lemma=")">)</W>
<W msd="FS" lemma=".">.</W>
<W msd="NP" lemma="Henry">HENRY</W>
<W msd="NP" lemma="&lt;unknown&gt;">HEERUP</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADJ" lemma="famoso">famoso</W>
<W msd="NC" lemma="escultor">escultor</W>
<W msd="CM" lemma=",">,</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">diseñado</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="joya">joya</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">artística</W>
<W msd="PREP" lemma="de">de</W>
<W msd="DM" lemma="este">este</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="PREP" lemma="para">para</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="cadena">cadena</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">joyerías</W>
<W msd="NP" lemma="&lt;unknown&gt;">Smykkekæden</W>
<W msd="FS" lemma=".">.</W>
<W msd="VSfin" lemma="ser">Es</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="ORD" lemma="primero">primer</W>
<W msd="NC" lemma="trabajo">trabajo</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="plata">plata</W>
<W msd="FS" lemma=".">.</W>
<W msd="NC" lemma="sello">Sello</W>
<W msd="ADJ" lemma="conmemorativo">conmemorativo</W>
<W msd="FS" lemma=".">.</W>
<W msd="NP" lemma="&lt;unknown&gt;">Pforzheim</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="tener">tenido</W>
<W msd="ART" lemma="un">una</W>
<W msd="VLfin" lemma="industriar">industria</W>
<W msd="NC" lemma="&lt;unknown&gt;">joyera</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="&lt;unknown&gt;">relojera</W>
<W msd="PREP" lemma="durante">durante</W>
<W msd="CARD" lemma="@card@">225</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="aniversario">aniversario</W>
<W msd="VSfin" lemma="ser">fue</W>
<W msd="VLadj" lemma="celebrar">celebrado</W>
<W msd="PREP" lemma="por">por</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="servicio">servicio</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="correo">correos</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="entre">entre</W>
<W msd="QU" lemma="otro">otros</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">emisión</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="sello">sello</W>
<W msd="ADJ" lemma="conmemorativo">conmemorativo</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">100</W>
<W msd="NC" lemma="&lt;unknown&gt;">pfennig</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="hasta">Hasta</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="agotar">agoten</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">los</W>
<W msd="ADJ" lemma="interesado">interesados</W>
<W msd="VMfin" lemma="poder">pueden</W>
<W msd="VLinf" lemma="obtener">obtener</W>
<W msd="ART" lemma="un">un</W>
<W msd="ADJ" lemma="ejemplar">ejemplar</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">timbrado</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="ORD" lemma="primero">primer</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">día</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="&lt;unknown&gt;">Ständige</W>
<W msd="NP" lemma="&lt;unknown&gt;">Musterausstellung</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Poststrasse</W>
<W msd="CARD" lemma="1">1</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">W-7530</W>
<W msd="NP" lemma="&lt;unknown&gt;">Pforzheim</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADJ" lemma="nuevo">Nuevos</W>
<W msd="ADJ" lemma="oficial">oficiales</W>
<W msd="NC" lemma="&lt;unknown&gt;">herreros</W>
<W msd="NP" lemma="&lt;unknown&gt;">Fueron</W>
<W msd="VLadj" lemma="aprobar">aprobadas</W>
<W msd="CARD" lemma="dos">dos</W>
<W msd="NC" lemma="prueba">pruebas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ADJ" lemma="oficial">oficial</W>
<W msd="NC" lemma="herrero">herrero</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="agosto">agosto</W>
<W msd="FS" lemma=".">.</W>
<W msd="QU" lemma="ambo">Ambos</W>
<W msd="NC" lemma="aprendiz">aprendices</W>
<W msd="VSfin" lemma="ser">fueron</W>
<W msd="VLadj" lemma="instruir">instruidos</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">platería</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Georg</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Jensen</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="&lt;unknown&gt;">Royal</W>
<W msd="NP" lemma="&lt;unknown&gt;">Copenhagen</W>
<W msd="NP" lemma="&lt;unknown&gt;">A/S</W>
<W msd="FS" lemma=".">.</W>
<W msd="NC" lemma="felicitacin">Felicitaciones</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">orfebre</W>
<W msd="NP" lemma="&lt;unknown&gt;">LYKKE</W>
<W msd="NP" lemma="&lt;unknown&gt;">ELKJÆR</W>
<W msd="NP" lemma="Olsen">OLSEN</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">platera</W>
<W msd="NP" lemma="&lt;unknown&gt;">GITTE</W>
<W msd="NP" lemma="&lt;unknown&gt;">TOFTESKOV</W>
<W msd="NP" lemma="&lt;unknown&gt;">RASMUSSEN</W>
<W msd="FS" lemma=".">.</W>
