<W lemma="Thomas" msd="NP" in="1:namef" out="">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:subj" out="-1:namef">Stuer</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:subj|1:dobj|8:pnct|22:conj">perdió</W>
<W lemma="un" msd="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="set" msd="NC" in="-1:nobj" out="1:pobj:arg">set</W>
<W lemma="contra" msd="PREP" in="-1:pobj:arg" out="1:nobj">contra</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="2:appr">coreano</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:namef" out="">Lee</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:appr" out="-1:namef">Kwan-Jin</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="pero" msd="CCAD" in="13:coord" out="">pero</W>
<W lemma="en" msd="PREP" in="12:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="cuarto" msd="NC" in="-1:nobj" out="1:pobj:arg#">cuartos</W>
<W lemma="de" msd="PREP" in="-1:pobj:arg#" out="1:nobj">de</W>
<W lemma="final" msd="NC" in="-1:nobj" out="">final</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="contra" msd="PREP" in="" out="1:nobj|-1:pnct">contra</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="chino" msd="NC" in="-1:nobj" out="2:appr">chino</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:namef" out="">Wan</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-2:appr" out="-1:namef">Shengwen</W>
<W lemma=":" msd="COLON" in="" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-22:conj" out="-13:coord|-12:loc|1:dobj|6:conj|29:pnct">“Gané</W>
<W lemma="@card@" msd="CODE" in="-1:dobj" out="">15-9</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="@card@" msd="CODE" in="" out="-1:pnct|1:pnct">15-8</W>
<W lemma="," msd="CM" in="-1:pnct" out="">,</W>
<W lemma="pero" msd="CCAD" in="1:coord" out="">pero</W>
<W lemma="estar" msd="VLfin" in="-6:conj" out="-1:coord|1:vobj|15:time">estaba</W>
<W lemma="perder" msd="VLger" in="-1:vobj" out="1:degr|4:loc">perdiendo</W>
<W lemma="a" msd="PREP" in="-1:degr" out="1:nobj">a</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">lo</W>
<W lemma="grande" msd="ADJ" in="-1:nobj" out="">grande</W>
<W lemma="en" msd="PREP" in="-4:loc" out="1:nobj">en</W>
<W lemma="ambo" msd="QU" in="-1:nobj" out="1:nobj">ambos</W>
<W lemma="set" msd="NC" in="-1:nobj" out="">sets</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="@card@" msd="CODE" in="" out="-1:pnct">0-7</W>
<W lemma="y" msd="CC" in="" out="">y</W>
<W lemma="@card@" msd="CODE" in="" out="">2-7</W>
<W lemma="respectivamente" msd="ADV" in="" out="">respectivamente</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="antes" msd="ADV" in="" out="">antes</W>
<W lemma="de" msd="PREP" in="-15:time" out="1:nobj">de</W>
<W lemma="que" msd="CQUE" in="-1:nobj" out="1:vobj">que</W>
<W lemma="llegar" msd="VLfin" in="-1:vobj" out="1:pobj">llegara</W>
<W lemma="a" msd="PREP" in="-1:pobj" out="1:vobj">a</W>
<W lemma="estructurar" msd="VLinf" in="-1:vobj" out="1:dobj">estructurar</W>
<W lemma="mo" msd="PPO" in="-1:dobj" out="1:possd|2:attrr">mi</W>
<W lemma="juego" msd="NC" in="-1:possd" out="">juego</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:attrr" out="">básico</W>
<W lemma="." msd="FS" in="-29:pnct" out="">.</W>
<W lemma="especialmente" msd="ADV" in="1:degr" out="">Especialmente</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="1:dobj|3:loc|-1:degr|7:pnct|10:conj">varié</W>
<W lemma="mo" msd="PPO" in="-1:dobj" out="1:nobj">mi</W>
<W lemma="juego" msd="NC" in="-1:nobj" out="">juego</W>
<W lemma="en" msd="PREP" in="-3:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:attrd|2:nobj">el</W>
<W lemma="primero" msd="ORD" in="-1:attrd" out="">primer</W>
<W lemma="set" msd="NC" in="-2:nobj" out="">set</W>
<W lemma="," msd="CM" in="-7:pnct" out="">,</W>
<W lemma="y" msd="CC" in="2:coord" out="">y</W>
<W lemma="l" msd="PPO" in="1:dobj" out="">lo</W>
<W lemma="hacer" msd="VLfin" in="-10:conj" out="-2:coord|-1:dobj|1:man">hice</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:man" out="">bien.”</W>
<W lemma="en" msd="PREP" in="11:loc" out="8:pnct|1:nobj">En</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="dos" msd="CARD" in="-1:nobj" out="1:attrd|2:nobj">dos</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-1:attrd" out="">últimos</W>
<W lemma="encuentro" msd="NC" in="-2:nobj" out="1:pobj:arg">encuentros</W>
<W lemma="contra" msd="PREP" in="-1:pobj:arg" out="2:nobj">contra</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:namef" out="">Ardy</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:nobj" out="-1:namef">Wiranata</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="Thomas" msd="NP" in="1:namef" out="">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="1:subj" out="-1:namef">Stuer</W>
<W lemma="haber" msd="VHfin" in="" out="-1:subj|1:vobj|-11:loc|16:conj">ha</W>
<W lemma="ganar" msd="VLadj" in="-1:vobj" out="1:dobj">ganado</W>
<W lemma="el" msd="ART" in="-1:dobj" out="2:nobj|1:attrd">el</W>
<W lemma="primero" msd="ORD" in="-1:attrd" out="">primer</W>
<W lemma="set" msd="NC" in="-2:nobj" out="">set</W>
<W lemma="," msd="CM" in="3:pnct" out="">,</W>
<W lemma="y" msd="CC" in="10:coord" out="">y</W>
<W lemma="antes" msd="ADV" in="" out="">antes</W>
<W lemma="de" msd="PREP" in="8:time" out="-3:pnct|5:pnct|1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:time">semifinal</W>
<W lemma="de" msd="PREP" in="-1:time" out="1:nobj">de</W>
<W lemma="hoy" msd="ADV" in="-1:nobj" out="">hoy</W>
<W lemma="," msd="CM" in="-5:pnct" out="">,</W>
<W lemma="el" msd="ART" in="2:subj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">táctica</W>
<W lemma="ser" msd="VSfin" in="-16:conj" out="-10:coord|-2:subj|1:preds|-8:time">es</W>
<W lemma="el" msd="ART" in="-1:preds" out="1:nobj">la</W>
<W lemma="siguiente" msd="ADJ" in="-1:nobj" out="1:pnct">siguiente</W>
<W lemma=":" msd="COLON" in="-1:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="1:vobj|14:man|41:pnct">“Debo</W>
<W lemma="mantener" msd="VLinf" in="-1:vobj" out="2:dobj|3:predo|6:man">mantener</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:dobj" out="">Ardy</W>
<W lemma="a" msd="PREP" in="-3:predo" out="1:nobj">a</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="defensa" msd="NC" in="-1:nobj" out="">defensa</W>
<W lemma="con" msd="PREP" in="-6:man" out="1:nobj">con</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:attrd|2:nobj|3:attrd">un</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:attrd" out="">sólido</W>
<W lemma="juego" msd="NC" in="-2:nobj" out="">juego</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-3:attrd" out="">básico</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="">así</W>
<W lemma="como" msd="CSUBX" in="-14:man" out="2:vobj">como</W>
<W lemma="l" msd="PPO" in="1:dobj" out="">lo</W>
<W lemma="haber" msd="VLfin" in="-2:vobj" out="1:vobj|-1:dobj|6:pnct|7:conc|2:loc">he</W>
<W lemma="practicar" msd="VLadj" in="-1:vobj" out="">practicado</W>
<W lemma="en" msd="PREP" in="-2:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:attrd|2:nobj">el</W>
<W lemma="primero" msd="ORD" in="-1:attrd" out="">primer</W>
<W lemma="set" msd="NC" in="-2:nobj" out="">set</W>
<W lemma="," msd="CM" in="-6:pnct" out="">,</W>
<W lemma="aunque" msd="CSUBX" in="-7:conc" out="3:vobj">aunque</W>
<W lemma="ambo" msd="QU" in="2:degr" out="1:nobj">ambas</W>
<W lemma="vez" msd="NC" in="-1:nobj" out="">veces</W>
<W lemma="haber" msd="VLfin" in="-3:vobj" out="1:vobj|-2:degr|4:loc|8:pnct|9:time">he</W>
<W lemma="perder" msd="VLadj" in="-1:vobj" out="1:dobj">perdido</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">la</W>
<W lemma="ventaja" msd="NC" in="-1:nobj" out="">ventaja</W>
<W lemma="en" msd="PREP" in="-4:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:attrd">el</W>
<W lemma="segundo" msd="ORD" in="-1:attrd" out="1:nobj">segundo</W>
<W lemma="set" msd="NC" in="-1:nobj" out="">set</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="cuando" msd="CSUBX" in="-9:time" out="1:vobj">cuando</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-1:vobj" out="1:nobj|3:loc">tenía</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="viento" msd="NC" in="-1:nobj" out="">viento</W>
<W lemma="por" msd="PREP" in="-3:loc" out="1:nobj">por</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">atrás</W>
<W lemma="." msd="FS" in="-41:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="2:loc" out="">Aquí</W>
<W lemma="en" msd="PREP" in="1:loc" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="-2:loc|-1:loc">Japón</W>
<W lemma="haber" msd="VHfin" in="" out="1:dobj|5:conj">hay</W>
<W lemma="viento" msd="NC" in="-1:dobj" out="1:dir#">viento</W>
<W lemma="de" msd="PREP" in="-1:dir#" out="1:nobj">de</W>
<W lemma="costado" msd="NC" in="-1:nobj" out="">costado</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="sentar|sentir" msd="VLfin" in="-5:conj" out="-1:coord|1:dobj">siento</W>
<W lemma="que" msd="CQUE" in="-1:dobj" out="3:vobj">que</W>
<W lemma="este" msd="DM" in="2:xtop" out="">esto</W>
<W lemma="l" msd="PPO" in="1:dobj" out="">lo</W>
<W lemma="poder" msd="VLfin" in="-3:vobj" out="1:vobj|2:man|-2:xtop|-1:dobj">puedo</W>
<W lemma="manejar" msd="VLinf" in="-1:vobj" out="">manejar</W>
<W lemma="con" msd="PREP" in="-2:man" out="2:nobj">con</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="1:degr" out="">más</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-2:nobj" out="-1:degr">facilidad.”</W>
<W lemma="el" msd="ART" in="6:subj" out="1:nobj|2:attrr|5:attrr">Los</W>
<W lemma="doble" msd="QU" in="-1:nobj" out="">dobles</W>
<W lemma="masculino" msd="ADJ" in="-2:attrr" out="2:conj">masculinos</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="femenino" msd="ADJ" in="-2:conj" out="-1:coord">femeninos</W>
<W lemma="dans" msd="ADJ" in="-5:attrr" out="">daneses</W>
<W lemma="caer" msd="VLfin" in="" out="-6:subj|1:preds|2:time|15:conj">cayeron</W>
<W lemma="eliminar" msd="VLadj" in="-1:preds" out="">eliminados</W>
<W lemma="ayer" msd="ADV" in="-2:time" out="">ayer</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="pero" msd="CCAD" in="11:coord" out="-1:pnct|4:pnct">pero</W>
<W lemma="en" msd="PREP" in="10:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="mixto" msd="ADJ" in="-1:nobj" out="">mixtos</W>
<W lemma="," msd="CM" in="-4:pnct" out="">,</W>
<W lemma="tres" msd="CARD" in="6:subj" out="1:ext">tres</W>
<W lemma="de" msd="PREP" in="-1:ext" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="cuatro" msd="CARD" in="-1:nobj" out="1:nobj|2:attrr">cuatro</W>
<W lemma="pareja" msd="NC" in="-1:nobj" out="">parejas</W>
<W lemma="semifinalista" msd="ADJ" in="-2:attrr" out="">semifinalistas</W>
<W lemma="ser" msd="VSfin" in="-15:conj" out="-6:subj|1:preds|-11:coord|-10:loc|2:pnct|4:cons">son</W>
<W lemma="dans" msd="ADJ" in="-1:preds" out="">danesas</W>
<W lemma="," msd="CM" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="">así</W>
<W lemma="que" msd="CQUE" in="-4:cons" out="1:vobj">que</W>
<W lemma="estar" msd="VLfin" in="-1:vobj" out="1:preds|8:pnct|9:time">estamos</W>
<W lemma="seguro" msd="ADJ" in="-1:preds" out="1:pobj">seguros</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="poner" msd="VLadj" in="-1:nobj" out="1:loc">puesto</W>
<W lemma="en" msd="PREP" in="-1:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="final" msd="NC" in="-1:nobj" out="">final</W>
<W lemma="," msd="CM" in="-8:pnct" out="">,</W>
<W lemma="cuando" msd="CSUBX" in="-9:time" out="7:vobj">cuando</W>
<W lemma="Henry" msd="NP" in="1:namef" out="">Henry</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="5:subj" out="-1:namef|3:conj|1:coord">Svarrer</W>
<W lemma="/" msd="SLASH" in="-1:coord" out="">/</W>
<W lemma="Marlene" msd="NP" in="1:namef" out="">Marlene</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-3:conj" out="-1:namef">Thomsen</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-7:vobj" out="-1:robj|2:dobj|9:pnct|-5:subj">enfrentarán</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="nosotros" msd="PPX" in="-2:dobj" out="2:attrd">nuestra</W>
<W lemma="generalmente" msd="ADV" in="1:prg" out="2:nobj">generalmente</W>
<W lemma="bueno" msd="ADJ" in="-2:attrd" out="-1:prg">mejor</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-2:nobj" out="">constelación</W>
<W lemma="Thomas" msd="NP" in="" out="">Thomas</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="" out="">Lund/Pernille</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="" out="">Dupont</W>
<W lemma="." msd="FS" in="-9:pnct" out="">.</W>
