<W lemma="@card@" msd="XS" tag="CODE" in="1:numm" out="">11</W>
<W lemma="muerto" msd="AN" tag="ADJ" in="" out="-1:numm|1:pobj|6:pnct">muertos</W>
<W lemma="por" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">por</W>
<W lemma="consumo" msd="NC" tag="NC" in="-1:nobj" out="1:pobj">consumo</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">de</W>
<W lemma="drogar" msd="VAD" tag="VLfin" in="-1:nobj" out="">drogas</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">ODENSE</W>
<W lemma="&3a;" msd="XP" tag="COLON" in="-6:pnct" out="">:</W>
<W lemma="@card@" msd="AC" tag="CARD" in="1:numm" out="">11</W>
<W lemma="persona" msd="NC" tag="NC" in="1:subj" out="-1:numm">personas</W>
<W lemma="morir" msd="VAD" tag="VLfin" in="" out="-1:subj|1:time|4:loc|11:pobj|17:pnct">murieron</W>
<W lemma="el" msd="PD" tag="ART" in="-1:time" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr">año</W>
<W lemma="pasar" msd="VAF" tag="VLadj" in="-1:attr" out="">pasado</W>
<W lemma="en" msd="SP" tag="SCENE" in="-4:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="distrito" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">distrito</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="1:pobj|1:{arg}">policía</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Odense</W>
<W lemma="como" msd="CS" tag="CSUBX" in="-11:pobj" out="1:nobj">como</W>
<W lemma="consecuencia" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">consecuencia</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="consumo" msd="NC" tag="NC" in="-1:nobj" out="1:pobj.dobj|1:{patient}#">consumo</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj.dobj|-1:{patient}#" out="1:nobj">de</W>
<W lemma="drogar" msd="VAD" tag="VLfin" in="-1:nobj" out="">drogas</W>
<W lemma="." msd="XP" tag="FS" in="-17:pnct" out="">.</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="1:prg|2:preds|7:pnct|10:vobj">Es</W>
<W lemma="casi" msd="RG" tag="ADV" in="-1:prg" out="">casi</W>
<W lemma="el" msd="PD" tag="ART" in="-2:preds" out="1:nobj">el</W>
<W lemma="doble" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">doble</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr">año</W>
<W lemma="anterior" msd="AN" tag="ADJ" in="-1:attr" out="">anterior</W>
<W lemma="," msd="XP" tag="CM" in="-7:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="2:source" out="">según</W>
<W lemma="se" msd="PC" tag="SE" in="1:subj" out="">se</W>
<W lemma="desprender" msd="VAD" tag="VLfin" in="-10:vobj" out="-1:subj|-2:source|1:pobj|11:pnct">desprende</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj" out="1:nobj">del</W>
<W lemma="informe" msd="NC" tag="NC" in="-1:nobj" out="1:aobj.dobj|1:{patient}#|7:tobj">informe</W>
<W lemma="anual" msd="AN" tag="ADJ" in="-1:aobj.dobj|-1:{patient}#" out="1:pobj|1:{arg}">anual</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="1:pobj|1:{arg}">Policía</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Odense</W>
<W lemma="para" msd="SP" tag="SCENE" in="-7:tobj" out="1:nobj">para</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="">1991</W>
<W lemma="." msd="XP" tag="FS" in="-11:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="3:subj|4:[subj]" out="1:nobj">La</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">policía</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="poder" msd="VAD" tag="VMfin" in="43:dobj/qobj??" out="-3:subj|-1:neg|1:vobj|14:pnct">puede</W>
<W lemma="aclarar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="-4:[subj]|1:dobj|16:vobj">aclarar</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="2:nobj">el</W>
<W lemma="enorme" msd="AN" tag="ADJ" in="1:degr" out="">enorme</W>
<W lemma="aumento" msd="NC" tag="NC" in="-2:nobj" out="-1:degr|1:other">aumento</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:other" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="cantidad" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">cantidad</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="muerto" msd="AN" tag="ADJ" in="-1:nobj" out="1:pobj">muertos</W>
<W lemma="por" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">por</W>
<W lemma="consumo" msd="NC" tag="NC" in="-1:nobj" out="1:pobj.dobj|1:{patient}#">consumo</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj.dobj|-1:{patient}#" out="1:nobj">de</W>
<W lemma="drogar" msd="VAD" tag="VLfin" in="-1:nobj" out="">drogas</W>
<W lemma="," msd="XP" tag="CM" in="-14:pnct" out="">,</W>
<W lemma="pero" msd="CC" tag="CCAD" in="2:coord" out="">pero</W>
<W lemma="en~cambio" msd="RG" tag="ADV" in="1:struct" out="">en cambio</W>
<W lemma="afirmar" msd="VAD" tag="VLfin" in="-16:vobj" out="-2:coord|-1:struct|1:dobj">afirma</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:dobj" out="2:vobj">que</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="-2:vobj" out="-1:neg|1:neg|2:dobj">hay</W>
<W lemma="ninguno" msd="AN" tag="QU" in="-1:neg" out="">ninguna</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-2:dobj" out="1:pobj">conexión</W>
<W lemma="entre" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">entre</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|3:conj">los</W>
<W lemma="muerto" msd="AN" tag="ADJ" in="-1:nobj" out="">muertos</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="el" msd="PD" tag="ART" in="-3:conj" out="-1:coord|1:cons">el</W>
<W lemma="hecho" msd="NC" tag="NC" in="-1:cons" out="">hecho</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="todo" msd="AN" tag="QU" in="" out="">todas</W>
<W lemma="el" msd="PD" tag="ART" in="2:subj" out="1:nobj">las</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">víctimas</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-2:subj|1:vobj">habían</W>
<W lemma="ser" msd="VAF" tag="VS" in="-1:vobj" out="1:preds">sido</W>
<W lemma="consumidor" msd="NC" tag="NC" in="-1:preds" out="1:pobj.dobj|1:{patient}|4:time">consumidores</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj.dobj|-1:{patient}" out="1:nobj">de</W>
<W lemma="drogar" msd="VAD" tag="VLfin" in="-1:nobj" out="1:aobj.dobj|1:{patient}#">drogas</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:aobj.dobj|-1:{patient}#" out="">euforizantes</W>
<W lemma="durante" msd="SP" tag="SCENE" in="-4:time" out="1:nobj">durante</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="," msd="XP" tag="CM" in="1:pnct" out="">,</W>
<W lemma="escribir" msd="VAD" tag="VLfin" in="" out="-43:dobj/qobj??|-1:pnct|2:subj|3:pnct">escribe</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Fyens</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-2:subj" out="-1:namef">Stiftstidende</W>
<W lemma="." msd="XP" tag="FS" in="-3:pnct" out="">.</W>
<W lemma="(" msd="XP" tag="LP" in="" out="">(</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">RB</W>
<W lemma=")" msd="XP" tag="RP" in="" out="">)</W>
<W lemma="cerrar" msd="VAD" tag="VLfin" in="" out="1:subj|6:pnct">Cierran</W>
<W lemma="dos" msd="AC" tag="CARD" in="-1:subj" out="1:nobj">dos</W>
<W lemma="escuela" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">escuelas</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="1:nobj">Fyn</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">ÅRUP</W>
<W lemma="&3a;" msd="XP" tag="COLON" in="-6:pnct" out="">:</W>
<W lemma="dos" msd="AC" tag="CARD" in="9:subj" out="1:nobj">Dos</W>
<W lemma="escuela" msd="NC" tag="NC" in="-1:nobj" out="1:loc">escuelas</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="municipalidad" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">municipalidad</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:loc">Årup</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Fyn</W>
<W lemma="ir" msd="VAD" tag="VLfin" in="" out="-9:subj|1:vp&3a;fut#|3:time|8:pnct">van</W>
<W lemma="a" msd="SP" tag="SCENE" in="-1:vp&3a;fut#" out="1:vobj">a</W>
<W lemma="cerrar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="">cerrar</W>
<W lemma="en" msd="SP" tag="SCENE" in="-3:time" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="verano" msd="NC" tag="NC" in="-1:nobj" out="">verano</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="">1993</W>
<W lemma="." msd="XP" tag="FS" in="-8:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="3:subj" out="1:nobj">El</W>
<W lemma="concejo" msd="NC" tag="NC" in="-1:nobj" out="1:aobj.dobj|1:{patient}#">concejo</W>
<W lemma="municipal" msd="AN" tag="ADJ" in="-1:aobj.dobj|-1:{patient}#" out="">municipal</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-3:subj|1:vobj|9:pnct|10:vobj">ha</W>
<W lemma="decidir" msd="VAF" tag="VLadj" in="-1:vobj" out="1:dobj|9:vobj">decidido</W>
<W lemma="cerrar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:dobj" out="1:nobj">cerrar</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="escuela" msd="NC" tag="NC" in="-1:nobj" out="1:loc">escuelas</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="2:conj">Orte</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-2:conj" out="-1:coord">Kerte</W>
<W lemma="," msd="XP" tag="CM" in="-9:pnct" out="">,</W>
<W lemma="ahorrar" msd="VAF" tag="VLadj" in="-10:vobj|-9:vobj" out="1:man|7:dobj">ahorrando</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:man" out="1:nobj">de</W>
<W lemma="este" msd="" tag="DM" in="-1:nobj" out="1:nobj">este</W>
<W lemma="modo" msd="NC" tag="NC" in="-1:nobj" out="">modo</W>
<W lemma="alrededor" msd="SP" tag="SCENE" in="3:degr" out="">alrededor</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="1:numm" out="">800.000</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-7:dobj" out="-3:degr|-1:numm">coronas.</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">awb</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:degr" out="">Más</W>
<W lemma="hospital" msd="NC" tag="NC" in="" out="-1:degr|1:space|6:pnct">hospitales</W>
<W lemma="a" msd="SP" tag="SCENE" in="-1:space" out="1:nobj">a</W>
<W lemma="Europa" msd="NP" tag="NP" in="-1:nobj" out="1:space">Europa</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:space" out="1:nobj">del</W>
<W lemma="esto" msd="" tag="DM" in="-1:nobj" out="">Este</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">VEJLE</W>
<W lemma="&3a;" msd="XP" tag="COLON" in="-6:pnct" out="">:</W>
<W lemma="numeroso" msd="AN" tag="ADJ" in="5:subj" out="1:nobj">Numerosos</W>
<W lemma="hospital" msd="NC" tag="NC" in="-1:nobj" out="1:pobj.pobj|1:{location}#|3:attr">hospitales</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj.pobj|-1:{location}#" out="1:nobj">de</W>
<W lemma="emergencia" msd="NC" tag="NC" in="-1:nobj" out="">emergencia</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-3:attr" out="">exhaustos</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-5:subj|1:vobj|9:pnct|12:conj">han</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:vobj" out="1:time|2:loc|4:dir">partido</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:time" out="">últimamente</W>
<W lemma="desde" msd="SP" tag="SCENE" in="-2:loc" out="1:nobj">desde</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="hacia" msd="SP" tag="SCENE" in="-4:dir" out="3:nobj">hacia</W>
<W lemma="Europa" msd="NP" tag="NP" in="2:namef" out="">Europa</W>
<W lemma="del" msd="SP" tag="PDEL" in="" out="">del</W>
<W lemma="esto" msd="" tag="DM" in="-3:nobj" out="-2:namef">Este</W>
<W lemma="," msd="XP" tag="CM" in="-9:pnct" out="">,</W>
<W lemma="y" msd="CC" tag="CC" in="2:coord" out="">y</W>
<W lemma="ahora" msd="RG" tag="ADV" in="1:time" out="">ahora</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="-12:conj" out="-2:coord|-1:time|1:dobj|5:pnct">hay</W>
<W lemma="dos" msd="AC" tag="CARD" in="-1:dobj" out="1:degr|2:dir">dos</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:degr" out="">más</W>
<W lemma="en" msd="SP" tag="SCENE" in="-2:dir" out="1:nobj">en</W>
<W lemma="camino" msd="NC" tag="NC" in="-1:nobj" out="">camino</W>
<W lemma="." msd="XP" tag="FS" in="-5:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="4:subj" out="1:nobj">El</W>
<W lemma="municipio" msd="NC" tag="NC" in="-1:nobj" out="">municipio</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Vejle</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-4:subj|1:vobj|13:pnct">ha</W>
<W lemma="decidir" msd="VAF" tag="VLadj" in="-1:vobj" out="1:dobj|19:vobj">decidido</W>
<W lemma="enviar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:dobj" out="1:nobj">enviar</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="hospital" msd="NC" tag="NC" in="-1:nobj" out="1:pobj.pobj|1:{location}#|3:loc|5:dir">hospital</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj.pobj|-1:{location}#" out="1:nobj">de</W>
<W lemma="emergencia" msd="NC" tag="NC" in="-1:nobj" out="">emergencia</W>
<W lemma="de" msd="SP" tag="SCENE" in="-3:loc" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Brædstrup</W>
<W lemma="a" msd="SP" tag="SCENE" in="-5:dir" out="1:nobj">a</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:loc">Zagreb</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">en</W>
<W lemma="Croacia" msd="NP" tag="NP" in="-1:nobj" out="">Croacia</W>
<W lemma="," msd="XP" tag="CM" in="-13:pnct" out="">,</W>
<W lemma="mientras~que" msd="CS" tag="CSUBX" in="6:struct" out="">mientras que</W>
<W lemma="otro" msd="AN" tag="QU" in="5:subj" out="1:nobj">otro</W>
<W lemma="hospital" msd="NC" tag="NC" in="-1:nobj" out="1:attr">hospital</W>
<W lemma="similar" msd="AN" tag="ADJ" in="-1:attr" out="">similar</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Give</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="-19:vobj" out="-6:struct|-5:subj|1:dir">partirá</W>
<W lemma="hacia" msd="SP" tag="SCENE" in="-1:dir" out="1:nobj">hacia</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="">Polonia.</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">hel</W>
