<W msd="ART" lemma="el">La</W>
<W msd="NC" lemma="prensa">prensa</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="comenzar">comenzado</W>
<W msd="PREP" lemma="a">a</W>
<W msd="VLinf" lemma="prestar">prestarle</W>
<W msd="NC" lemma="&lt;unknown&gt;">atención</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPO" lemma="suyo">Sus</W>
<W msd="NC" lemma="libro">libros</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">reseñados</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">La</W>
<W msd="NC" lemma="cima">cima</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">ocurrió</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="VLadj" lemma="pasar">pasado</W>
<W msd="CSUBX" lemma="cuando">cuando</W>
<W msd="NP" lemma="&lt;unknown&gt;">Jørgen</W>
<W msd="NP" lemma="&lt;unknown&gt;">Thorsgaard</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">presentó</W>
<W msd="PREP" lemma="a">a</W>
<W msd="CARD" lemma="uno">uno</W>
<W msd="PREP" lemma="de">de</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="NC" lemma="autor">autores</W>
<W msd="ADJ" lemma="principal">principales</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Vagn</W>
<W msd="NP" lemma="&lt;unknown&gt;">Predbjørn</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="en">en</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="programa">programa</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="NC" lemma="libro">libros</W>
<W msd="FS" lemma=".">.</W>
<W msd="CC" lemma="y">Y</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="tener">tenido</W>
<W msd="NC" lemma="&lt;unknown&gt;">éxito</W>
<W msd="PREP" lemma="con">con</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="club">club</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="lector">lectores</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">poesía</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="publicar">publica</W>
<W msd="CARD" lemma="tres">tres</W>
<W msd="NC" lemma="nueva">nuevas</W>
<W msd="NC" lemma="colecci�n">colecciones</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">poesías</W>
<W msd="QU" lemma="cada">cada</W>
<W msd="CARD" lemma="dos">dos</W>
<W msd="NC" lemma="mes">meses</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="ahora">Ahora</W>
<W msd="VLfin" lemma="significar">significa</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="palabra">palabra</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">“éxito”</W>
<W msd="ADV" lemma="&lt;unknown&gt;">quizá</W>
<W msd="NEG" lemma="no">no</W>
<W msd="PPO" lemma="�l">lo</W>
<W msd="ADJ" lemma="mismo">mismo</W>
<W msd="PREP" lemma="para">para</W>
<W msd="NP" lemma="&lt;unknown&gt;">Jørgen</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Fallesen</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="&lt;unknown&gt;">Almind</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="PREP" lemma="para">para</W>
<W msd="NP" lemma="&lt;unknown&gt;">Gyldendal</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">–</W>
<W msd="ADV" lemma="por~lo~menos">por lo menos</W>
<W msd="CSUBX" lemma="cuando">cuando</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="comparar">compara</W>
<W msd="ART" lemma="el">la</W>
<W msd="VLadj" lemma="tirar">tirada</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="&lt;unknown&gt;">número</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="miembro">miembros</W>
<W msd="PREP" lemma="de">de</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="club">club</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">poesía</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">15</W>
<W msd="NC" lemma="&lt;unknown&gt;">–</W>
<W msd="CARD" lemma="quince">quince</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">–</W>
<W msd="CC" lemma="y">y</W>
<W msd="CSUBX" lemma="aunque">aunque</W>
<W msd="VLfin" lemma="reconocer">reconoce</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="NC" lemma="&lt;unknown&gt;">“no</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">número</W>
<W msd="PREP" lemma="para">para</W>
<W msd="NC" lemma="&lt;unknown&gt;">vanagloriarse,”</W>
<W msd="ADV" lemma="&lt;unknown&gt;">también</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="cierto">cierto</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">“los</W>
<W msd="CARD" lemma="quince">quince</W>
<W msd="ADV" lemma="tampoco">tampoco</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="QU" lemma="nada">nada</W>
<W msd="NC" lemma="&lt;unknown&gt;">despreciable.“</W>
<W msd="NP" lemma="&lt;unknown&gt;">A pesar de</W>
<W msd="QU" lemma="todo">todo</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="tener">tienen</W>
<W msd="ART" lemma="un">una</W>
<W msd="ADJ" lemma="bueno">buena</W>
<W msd="NC" lemma="&lt;unknown&gt;">participación</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="hecho">hecho</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="serie">serie</W>
<W msd="VMfin" lemma="poder">pueda</W>
<W msd="ADV" lemma="&lt;unknown&gt;">continuar”</W>
<W msd="VLfin" lemma="decir">dice</W>
<W msd="FS" lemma=".">.</W>
<W msd="NEG" lemma="no">No</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="QU" lemma="ninguno">ninguna</W>
<W msd="NC" lemma="&lt;unknown&gt;">institución</W>
<W msd="CCNEG" lemma="ni">ni</W>
<W msd="NC" lemma="biblioteca">biblioteca</W>
<W msd="PREP" lemma="entre">entre</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="suscriptor">suscriptores</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">sólo</W>
<W msd="NC" lemma="persona">personas</W>
<W msd="ADJ" lemma="individual">individuales</W>
<W msd="FS" lemma=".">.</W>
<W msd="CC" lemma="y">Y</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">impresión</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADV" lemma="en~general">en general</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">100</W>
<W msd="VLfin" lemma="ejemplar">ejemplares</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLger" lemma="incluir">incluyendo</W>
<W msd="ART" lemma="el">los</W>
<W msd="ADJ" lemma="ejemplar">ejemplares</W>
<W msd="PREP" lemma="para">para</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">críticos</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">los</W>
<W msd="ADJ" lemma="gratuito">gratuitos</W>
<W msd="PREP" lemma="para">para</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="autor">autores</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="considerar">Considera</W>
<W msd="PREP" lemma="a">a</W>
<W msd="NP" lemma="&lt;unknown&gt;">Parzival</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">artículo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="dar">da</W>
<W msd="NC" lemma="provecho">provecho</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">económico</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">–</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">todavía</W>
<W msd="VLfin" lemma="vendar|vender">vende</W>
<W msd="ART" lemma="un">unos</W>
<W msd="CARD" lemma="@card@">75</W>
<W msd="ADJ" lemma="ejemplar">ejemplares</W>
<W msd="PAL" lemma="al">al</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBF" lemma="por~lo~tanto">Por lo tanto</W>
<W msd="CM" lemma=",">,</W>
<W msd="SE" lemma="se">se</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="NC" lemma="sentido">sentido</W>
<W msd="VLadj" lemma="motivar">motivado</W>
<W msd="PREP" lemma="a">a</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">reimprimirlo</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">–</W>
<W msd="PREP" lemma="en">en</W>
<W msd="CARD" lemma="@card@">100</W>
<W msd="ADJ" lemma="ejemplar">ejemplares</W>
<W msd="FS" lemma=".">.</W>
