<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="pasaje">pasaje</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="NP" lemma="&lt;unknown&gt;">Storebælt</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">abrió</W>
<W msd="PREP" lemma="para">para</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">tráfico</W>
<W msd="ADJ" lemma="ordinario">ordinario</W>
<W msd="ART" lemma="el">el</W>
<W msd="CARD" lemma="1">1</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NMON" lemma="diciembre">diciembre</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">1883</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">La</W>
<W msd="ORD" lemma="primero">primera</W>
<W msd="NC" lemma="amenaza">amenaza</W>
<W msd="ADJ" lemma="serio">seria</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">dominancia</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="ruta">rutas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">ferries</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="agua">aguas</W>
<W msd="ADJ" lemma="dan�s">danesas</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">ocurrió</W>
<W msd="PREP" lemma="hasta">hasta</W>
<W msd="NC" lemma="&lt;unknown&gt;">más</W>
<W msd="PREP" lemma="de">de</W>
<W msd="QU" lemma="medio">medio</W>
<W msd="NC" lemma="siglo">siglo</W>
<W msd="ADV" lemma="&lt;unknown&gt;">después</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Sucedió</W>
<W msd="ART" lemma="el">el</W>
<W msd="CARD" lemma="@card@">15</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="mayo">mayo</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">1935</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBX" lemma="cuando">cuando</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">inauguró</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="puente">puente</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="NP" lemma="&lt;unknown&gt;">Lillebælt</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="dentro~de">Dentro de</W>
<W msd="CARD" lemma="tres">tres</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="CC" lemma="y">y</W>
<W msd="QU" lemma="medio">medio</W>
<W msd="ART" lemma="un">una</W>
<W msd="ADJ" lemma="bueno">buena</W>
<W msd="NC" lemma="parte">parte</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">ferries</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">DSB</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">deberán</W>
<W msd="VLinf" lemma="buscar">buscar</W>
<W msd="ADJ" lemma="nuevo">nuevas</W>
<W msd="NC" lemma="agua">aguas</W>
<W msd="CSUBX" lemma="cuando">cuando</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="puente">puente</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Storebælt</W>
<W msd="VSfin" lemma="ser">sea</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="realidad">realidad</W>
<W msd="FS" lemma=".">.</W>
<W msd="CC" lemma="y">Y</W>
<W msd="PREP" lemma="con">con</W>
<W msd="DM" lemma="este">esto</W>
<W msd="SE" lemma="se">se</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="decir">decir</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="un">una</W>
<W msd="ADJ" lemma="interesante">interesante</W>
<W msd="NC" lemma="historia">historia</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">está</W>
<W msd="PREP" lemma="a~punto~de">a punto de</W>
<W msd="VSinf" lemma="ser">ser</W>
<W msd="NC" lemma="historia">historia</W>
<W msd="FS" lemma=".">.</W>
<W msd="CARD" lemma="cinco">Cinco</W>
<W msd="NC" lemma="ruta">rutas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">DSB</W>
<W msd="VLfin" lemma="sobrevivir">sobreviven</W>
<W msd="NP" lemma="La">La</W>
<W msd="NC" lemma="&lt;unknown&gt;">división</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">marítima</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">DSB</W>
<W msd="VLfin" lemma="buscar">busca</W>
<W msd="ADJ" lemma="nuevo">nuevos</W>
<W msd="VLadj" lemma="mercar">mercados</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="parte">parte</W>
<W msd="NC" lemma="este">este</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NP" lemma="Mar">Mar</W>
<W msd="NC" lemma="&lt;unknown&gt;">Báltico</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBF" lemma="ya~que">ya que</W>
<W msd="PREP" lemma="en">en</W>
<W msd="CARD" lemma="@card@">2005</W>
<W msd="NC" lemma="&lt;unknown&gt;">sólo</W>
<W msd="CARD" lemma="cinco">cinco</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="ADJ" lemma="actual">actuales</W>
<W msd="CARD" lemma="@card@">10</W>
<W msd="NC" lemma="ruta">rutas</W>
<W msd="ADV" lemma="&lt;unknown&gt;">seguirán</W>
<W msd="ADJ" lemma="intacto">intactas</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">Las</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ADV" lemma="&lt;unknown&gt;">sobrevivirán</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="NP" lemma="&lt;unknown&gt;">Esbjerg-Fanø</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Bøjden-Fynshav</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Kalundborg-Samsø</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Helsingør-Helsinborg</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBX" lemma="aunque">aunque</W>
<W msd="ADV" lemma="muy">muy</W>
<W msd="VLadj" lemma="reducir">reducida</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADV" lemma="finalmente">finalmente</W>
<W msd="NC" lemma="&lt;unknown&gt;">Gedser-Warnemünde</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="&lt;unknown&gt;">sombrío</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">pronóstico</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="basar">basa</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="consecuencia">consecuencias</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="conexi�n">conexiones</W>
<W msd="ADJ" lemma="fijo">fijas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Storebælt</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Øresund</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">el</W>
<W msd="NP" lemma="Mar">Mar</W>
<W msd="NP" lemma="&lt;unknown&gt;">Báltico</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">Las</W>
<W msd="NC" lemma="consecuencia">consecuencias</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">verán</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NP" lemma="&lt;unknown&gt;">Storebælt</W>
<W msd="PREP" lemma="en">en</W>
<W msd="CODE" lemma="@card@">1996</W>
<W msd="CM" lemma=",">,</W>
<W msd="CODE" lemma="@card@">1997</W>
<W msd="CC" lemma="y">y</W>
<W msd="CODE" lemma="@card@">1998</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NP" lemma="&lt;unknown&gt;">Øresund</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="CODE" lemma="@card@">2000</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NP" lemma="Mar">Mar</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Báltico</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="CODE" lemma="@card@">2005</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBF" lemma="por~lo~tanto">Por lo tanto</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">la</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">mayoría</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="CARD" lemma="@card@">34</W>
<W msd="NC" lemma="&lt;unknown&gt;">ferries</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">DSB</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">estarán</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">más</W>
<W msd="FS" lemma=".">.</W>
