<W lemma="el" msd="PD" tag="ART" in="5:subj" out="1:nobj">El</W>
<W lemma="pasaje" msd="NC" tag="NC" in="-1:nobj" out="1:loc">pasaje</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">sobre</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Storebælt</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-5:subj|-1:robj|1:goal|5:time|11:pnct">abrió</W>
<W lemma="para" msd="SP" tag="SCENE" in="-1:goal" out="1:nobj">para</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|2:attr">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">tráfico</W>
<W lemma="ordinario" msd="AN" tag="ADJ" in="-2:attr" out="">ordinario</W>
<W lemma="el" msd="PD" tag="ART" in="-5:time" out="1:nobj">el</W>
<W lemma="1" msd="AC" tag="CARD" in="-1:nobj" out="1:time">1</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">de</W>
<W lemma="diciembre" msd="NC" tag="NMON" in="-1:nobj" out="1:time">diciembre</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="">1883</W>
<W lemma="." msd="XP" tag="FS" in="-11:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="17:subj" out="1:attr|2:nobj|3:attr|4:attr|25:coref">La</W>
<W lemma="primero" msd="AO" tag="ORD" in="-1:attr" out="">primera</W>
<W lemma="amenaza" msd="NC" tag="NC" in="-2:nobj" out="">amenaza</W>
<W lemma="serio" msd="AN" tag="ADJ" in="-3:attr" out="">seria</W>
<W lemma="a" msd="SP" tag="SCENE" in="-4:attr" out="1:nobj">a</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:agent">dominancia</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:agent" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="ruta" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}#|3:loc">rutas</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}#" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="29:coref-iden">ferries</W>
<W lemma="en" msd="SP" tag="SCENE" in="-3:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|2:attr">las</W>
<W lemma="agua" msd="NC" tag="NC" in="-1:nobj" out="">aguas</W>
<W lemma="dans" msd="AN" tag="ADJ" in="-2:attr" out="">danesas</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-1:neg|-17:subj|1:time|7:pnct">ocurrió</W>
<W lemma="hasta" msd="SP" tag="SCENE" in="-1:time" out="">hasta</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="2:resem" out="">más</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="medio" msd="AN" tag="QU" in="-1:nobj" out="-2:resem|1:nobj">medio</W>
<W lemma="siglo" msd="NC" tag="NC" in="-1:nobj" out="1:time">siglo</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="-1:time" out="">después</W>
<W lemma="." msd="XP" tag="FS" in="-7:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="-25:coref" out="1:time|7:pnct|8:time">Sucedió</W>
<W lemma="el" msd="PD" tag="ART" in="-1:time" out="1:nobj">el</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:time">15</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">de</W>
<W lemma="mayo" msd="NC" tag="NC" in="-1:nobj" out="1:time">mayo</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="">1935</W>
<W lemma="," msd="XP" tag="CM" in="-7:pnct" out="">,</W>
<W lemma="cuando" msd="CS" tag="CSUBX" in="-8:time" out="2:vobj">cuando</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="-2:vobj" out="-1:robj|1:subj|3:loc|5:pnct">inauguró</W>
<W lemma="el" msd="PD" tag="ART" in="-1:subj" out="1:nobj">el</W>
<W lemma="puente" msd="NC" tag="NC" in="-1:nobj" out="">puente</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="-3:loc" out="1:nobj">sobre</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Lillebælt</W>
<W lemma="." msd="XP" tag="FS" in="-5:pnct|-29:coref-iden" out="">.</W>
<W lemma="dentro~de" msd="SP" tag="SCENE" in="13:time" out="1:nobj">Dentro de</W>
<W lemma="tres" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj|3:conj">tres</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="medio" msd="AN" tag="QU" in="-3:conj" out="-1:coord">medio</W>
<W lemma="un" msd="PD" tag="ART" in="8:subj|9:[subj]" out="1:attr|2:nobj">una</W>
<W lemma="bueno" msd="AN" tag="ADJ" in="-1:attr" out="">buena</W>
<W lemma="parte" msd="NC" tag="NC" in="-2:nobj" out="1:pobj|1:{arg}">parte</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr|1:{poss}">ferries</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:attr|-1:{poss}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="32:coref-iden">DSB</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-13:time|-8:subj|1:vobj|4:time|12:pnct">deberán</W>
<W lemma="buscar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="-9:[subj]|2:dobj">buscar</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="">nuevas</W>
<W lemma="agua" msd="NC" tag="NC" in="-2:dobj" out="-1:attr">aguas</W>
<W lemma="cuando" msd="CS" tag="CSUBX" in="-4:time" out="5:vobj">cuando</W>
<W lemma="el" msd="PD" tag="ART" in="4:subj" out="1:nobj">el</W>
<W lemma="puente" msd="NC" tag="NC" in="-1:nobj" out="1:loc">puente</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Storebælt</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="-5:vobj" out="-4:subj|1:preds">sea</W>
<W lemma="un" msd="PD" tag="ART" in="-1:preds" out="1:nobj">una</W>
<W lemma="realidad" msd="NC" tag="NC" in="-1:nobj" out="">realidad</W>
<W lemma="." msd="XP" tag="FS" in="-12:pnct" out="">.</W>
<W lemma="y" msd="CC" tag="CC" in="4:scene" out="">Y</W>
<W lemma="con" msd="SP" tag="SCENE" in="3:cause" out="">con</W>
<W lemma="este" msd="" tag="DM" in="" out="">esto</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="poder" msd="VAD" tag="VMfin" in="" out="-1:robj|-3:cause|-4:scene|1:vobj|10:pnct">puede</W>
<W lemma="decir" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">decir</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:dobj" out="4:vobj">que</W>
<W lemma="un" msd="PD" tag="ART" in="3:subj" out="1:attr|2:nobj|5:[subj]">una</W>
<W lemma="interesante" msd="AN" tag="ADJ" in="-1:attr" out="">interesante</W>
<W lemma="historia" msd="NC" tag="NC" in="-2:nobj" out="">historia</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="-4:vobj" out="-3:subj|1:loc">está</W>
<W lemma="a~punto~de" msd="SP" tag="SCENE" in="-1:loc" out="1:vobj">a punto de</W>
<W lemma="ser" msd="VAF" tag="VSinf" in="-1:vobj|-5:[subj]" out="1:preds">ser</W>
<W lemma="historia" msd="NC" tag="NC" in="-1:preds" out="">historia</W>
<W lemma="." msd="XP" tag="FS" in="-10:pnct" out="">.</W>
<W lemma="cinco" msd="AC" tag="CARD" in="4:subj" out="1:nobj|25:coref">Cinco</W>
<W lemma="ruta" msd="NC" tag="NC" in="-1:nobj" out="1:other">rutas</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:other" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-32:coref-iden|-1:nobj" out="2:assoc-const">DSB</W>
<W lemma="sobrevivir" msd="VAD" tag="VLfin" in="" out="-4:subj">sobreviven</W>
<W lemma="La" msd="NP" tag="NP" in="-2:assoc-const|5:subj" out="1:nobj|2:attr|106:assoc-const">La</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">división</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:attr" out="1:other">marítima</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:other" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">DSB</W>
<W lemma="buscar" msd="VAD" tag="VLfin" in="" out="-5:subj|3:loc|10:pnct|11:cause|23:pnct">busca</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="1:dobj">nuevos</W>
<W lemma="mercar" msd="VAF" tag="VLadj" in="-1:dobj" out="-1:attr">mercados</W>
<W lemma="en" msd="SP" tag="SCENE" in="-3:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|2:attr">la</W>
<W lemma="parte" msd="NC" tag="NC" in="-1:nobj" out="2:pobj|2:{arg}">parte</W>
<W lemma="este" msd="NC" tag="NC" in="-2:attr" out="">este</W>
<W lemma="del" msd="SP" tag="PDEL" in="-2:pobj|-2:{arg}" out="1:nobj">del</W>
<W lemma="Mar" msd="NP" tag="NP" in="-1:nobj" out="1:nobj">Mar</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Báltico</W>
<W lemma="," msd="XP" tag="CM" in="-10:pnct" out="">,</W>
<W lemma="ya~que" msd="CS" tag="CSUBF" in="-11:cause" out="10:vobj">ya que</W>
<W lemma="en" msd="SP" tag="SCENE" in="9:time" out="1:nobj">en</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="">2005</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="1:prg" out="">sólo</W>
<W lemma="cinco" msd="AC" tag="CARD" in="-25:coref|6:subj" out="-1:prg|1:time|9:coref">cinco</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="2:nobj">las</W>
<W lemma="actual" msd="AN" tag="ADJ" in="1:attr" out="">actuales</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-2:nobj" out="-1:attr|1:nobj">10</W>
<W lemma="ruta" msd="NC" tag="NC" in="-1:nobj" out="">rutas</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="-10:vobj" out="-9:time|-6:subj|1:preds">seguirán</W>
<W lemma="intacto" msd="AN" tag="ADJ" in="-1:preds" out="">intactas</W>
<W lemma="." msd="XP" tag="FS" in="-23:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="-9:coref" out="">Las</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="" out="">sobrevivirán</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="">son</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Esbjerg-Fanø</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Bøjden-Fynshav</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Kalundborg-Samsø</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Helsingør-Helsinborg</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="aunque" msd="CS" tag="CSUBX" in="" out="">aunque</W>
<W lemma="muy" msd="RG" tag="ADV" in="" out="">muy</W>
<W lemma="reducir" msd="VAF" tag="VLadj" in="" out="">reducida</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="finalmente" msd="RG" tag="ADV" in="" out="">finalmente</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">Gedser-Warnemünde</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="4:subj" out="1:attr|2:nobj">El</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:attr" out="">sombrío</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-2:nobj" out="">pronóstico</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="basar" msd="VAD" tag="VLfin" in="" out="-4:subj|-1:robj|1:pobj|16:pnct">basa</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|15:coref-iden">las</W>
<W lemma="consecuencia" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">consecuencias</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|2:attr">las</W>
<W lemma="conexin" msd="NC" tag="NC" in="-1:nobj" out="">conexiones</W>
<W lemma="fijo" msd="AN" tag="ADJ" in="-2:attr" out="1:loc">fijas</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="2:conj|13:coref-iden">Storebælt</W>
<W lemma="," msd="XP" tag="CM" in="1:coord" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-2:conj" out="-1:coord|2:conj|21:coref-iden">Øresund</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="el" msd="PD" tag="ART" in="-2:conj" out="-1:coord|1:nobj|27:coref-iden">el</W>
<W lemma="Mar" msd="NP" tag="NP" in="-1:nobj" out="1:attr">Mar</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:attr" out="">Báltico</W>
<W lemma="." msd="XP" tag="FS" in="-16:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="-15:coref-iden|3:subj" out="1:nobj">Las</W>
<W lemma="consecuencia" msd="NC" tag="NC" in="-1:nobj" out="">consecuencias</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-3:subj|-1:robj|1:loc|4:time|27:pnct">verán</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj|10:conj|18:conj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj|-13:coref-iden" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Storebælt</W>
<W lemma="en" msd="SP" tag="SCENE" in="-4:time" out="1:nobj|10:conj|19:conj">en</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-1:nobj" out="1:pnct|2:conj|4:conj">1996</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-2:conj" out="">1997</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-4:conj" out="-1:coord">1998</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="en" msd="SP" tag="SCENE" in="-10:conj" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj|-21:coref-iden" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Øresund</W>
<W lemma="en" msd="SP" tag="SCENE" in="-10:conj" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:numm">año</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-1:numm" out="">2000</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="en" msd="SP" tag="SCENE" in="-18:conj" out="-1:coord|1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj|-27:coref-iden" out="1:nobj|2:attr">el</W>
<W lemma="Mar" msd="NP" tag="NP" in="-1:nobj" out="">Mar</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="-2:attr" out="">Báltico</W>
<W lemma="en" msd="SP" tag="SCENE" in="-19:conj" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:numm">año</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-1:numm" out="">2005</W>
<W lemma="." msd="XP" tag="FS" in="-27:pnct" out="">.</W>
<W lemma="por~lo~tanto" msd="CS" tag="CSUBF" in="10:scene" out="1:pnct">Por lo tanto</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="el" msd="PD" tag="ART" in="8:subj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:nobj" out="1:pobj|1:{arg}">mayoría</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj|-106:assoc-const" out="1:nobj">los</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">34</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr|1:{poss}">ferries</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:attr|-1:{poss}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">DSB</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-10:scene|-8:subj|1:preds|3:pnct">estarán</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:preds" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">más</W>
<W lemma="." msd="XP" tag="FS" in="-3:pnct" out="">.</W>
