<p>
<s>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Maribo</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:subj" out="-1:namef">Frø</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-1:subj|1:vobj|37:pnct">ha</W>
<W lemma="avanzar" msd="VAF" tag="VLadj" in="-1:vobj" out="1:time">avanzado</W>
<W lemma="tanto" msd="RG" tag="ADV" in="-1:time" out="">tanto</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="suyo" msd="PP" tag="PPO" in="-1:nobj" out="1:nobj">su</W>
<W lemma="búsqueda" msd="NC" tag="NC" in="-1:nobj" out="">búsqueda</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|4:pnct">la</W>
<W lemma="remolacha" msd="NC" tag="NC" in="-1:nobj" out="1:attr">remolacha</W>
<W lemma="azucarero" msd="AN" tag="ADJ" in="-1:attr" out="1:attr">azucarera</W>
<W lemma="perfecto" msd="AN" tag="ADJ" in="-1:attr" out="">perfecta</W>
<W lemma="," msd="XP" tag="CM" in="-4:pnct" out="">,</W>
<W lemma="que" msd="CS" tag="CQUE" in="2:dobj" out="">que</W>
<W lemma="el" msd="PD" tag="ART" in="7:subj" out="1:nobj">la</W>
<W lemma="empresa" msd="NC" tag="NC" in="-1:nobj" out="-2:dobj|1:attr">empresa</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:attr" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="1:nobj">Lolland</W>
<W lemma="propiedad" msd="NC" tag="NC" in="-1:nobj" out="">propiedad</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Danisco</W>
<W lemma="estar" msd="VAD" tag="VEfin" in="" out="-7:subj|1:preds">está</W>
<W lemma="convencer" msd="VAF" tag="VLadj" in="-1:preds" out="">convencida</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:nobj" out="3:vobj">que</W>
<W lemma="el" msd="PD" tag="ART" in="2:subj" out="1:nobj">la</W>
<W lemma="remolacha" msd="NC" tag="NC" in="-1:nobj" out="">remolacha</W>
<W lemma="estar" msd="VAD" tag="VEfin" in="-3:vobj" out="-2:subj|1:time|7:time">estará</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="campo" msd="NC" tag="NC" in="-1:nobj" out="">campos</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="agricultor" msd="NC" tag="NC" in="-1:nobj" out="">agricultores</W>
<W lemma="antes" msd="RG" tag="ADV" in="-7:time" out="">antes</W>
<W lemma="del" msd="SP" tag="PDEL" in="" out="1:nobj">del</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="1:nobj">año</W>
<W lemma="@card@" msd="XS" tag="CODE" in="-1:nobj" out="">2000</W>
<W lemma="." msd="XP" tag="FS" in="-37:pnct" out="">.</W>
</s>
<s>
<W lemma="el" msd="PD" tag="ART" in="7:subj" out="1:nobj">La</W>
<W lemma="manipulación" msd="NC" tag="NC" in="-1:nobj" out="1:attr">manipulación</W>
<W lemma="genético" msd="AN" tag="ADJ" in="-1:attr" out="">genética</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="remolacha" msd="NC" tag="NC" in="-1:nobj" out="1:attr">remolacha</W>
<W lemma="azucarero" msd="AN" tag="ADJ" in="-1:attr" out="">azucarera</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-7:subj|1:vobj|4:pnct|27:pnct">ha</W>
<W lemma="acelerar" msd="VAF" tag="VLadj" in="-1:vobj" out="1:dobj">acelerado</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="proceso" msd="NC" tag="NC" in="-1:nobj" out="">proceso</W>
<W lemma="," msd="XP" tag="CM" in="-4:pnct" out="">,</W>
<W lemma="y" msd="CC" tag="CC" in="4:coord" out="">y</W>
<W lemma="actualmente" msd="RG" tag="ADV" in="3:epi" out="">actualmente</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Maribo</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:subj" out="-1:namef">Frø</W>
<W lemma="recibir" msd="VAD" tag="VLfin" in="" out="-4:coord|-3:epi|-1:subj|1:dobj|4:goal">recibe</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="permiso" msd="NC" tag="NC" in="-1:nobj" out="1:attr">permiso</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:attr" out="">medioambiental</W>
<W lemma="para" msd="CS" tag="CSUBI" in="-4:goal" out="1:vobj">para</W>
<W lemma="plantar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">plantar</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="2:nobj">la</W>
<W lemma="tercero" msd="AO" tag="ORD" in="1:attr" out="">tercera</W>
<W lemma="generación" msd="NC" tag="NC" in="-2:nobj" out="-1:attr|1:attr">generación</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:attr" out="1:nobj">de</W>
<W lemma="remolacha" msd="NC" tag="NC" in="-1:nobj" out="1:attr">remolachas</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="-1:attr" out="">manipuladas</W>
<W lemma="genético" msd="RG" tag="ADV" in="" out="">genéticamente</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="campo" msd="NC" tag="NC" in="-1:nobj" out="">campos</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="ensayo" msd="NC" tag="NC" in="-1:nobj" out="">ensayo</W>
<W lemma="." msd="XP" tag="FS" in="-27:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&quot;" msd="XP" tag="QT" in="2:pnct¹" out="">"</W>
<W lemma="pero" msd="CC" tag="CCAD" in="1:coord" out="">Pero</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="-2:pnct¹|-1:coord|1:preds|3:subj|47:pnct">es</W>
<W lemma="un" msd="PD" tag="ART" in="-1:preds" out="1:nobj">una</W>
<W lemma="equivocación" msd="NC" tag="NC" in="-1:nobj" out="">equivocación</W>
<W lemma="hacer" msd="VAF lexical verb infinite" tag="VLinf" in="-3:subj" out="2:dobj">hacer</W>
<W lemma="tanto" msd="AN" tag="ADJ" in="1:attr" out="">tantos</W>
<W lemma="experimento" msd="NC" tag="NC" in="-2:dobj" out="-1:attr">experimentos</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="laboratorio" msd="NC" tag="NC" in="-1:nobj" out="">laboratorios</W>
<W lemma="antes" msd="RG" tag="ADV" in="" out="">antes</W>
<W lemma="de" msd="CS" tag="CSUBI" in="" out="1:vobj">de</W>
<W lemma="obtener" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">obtener</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="permiso" msd="NC" tag="NC" in="-1:nobj" out="">permiso</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Dirección</W>
<W lemma="general" msd="NC" tag="NC" in="" out="">General</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="medio" msd="NC" tag="NC" in="-1:nobj" out="1:nobj|2:pnct">Medio</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Ambiente</W>
<W lemma="&quot;" msd="XP" tag="QT" in="-2:pnct" out="1:pnct|2:conj">"</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="explicar" msd="VAD" tag="VLfin" in="-2:conj" out="2:subj|3:pnct">explica</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Leif</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-2:subj" out="-1:namef|3:relr">Kjærgaard</W>
<W lemma="," msd="XP" tag="CM" in="-3:pnct" out="">,</W>
<W lemma="que" msd="CS" tag="CQUE" in="1:subj" out="">que</W>
<W lemma="ver" msd="VAD" tag="VLfin" in="-3:relr" out="-1:subj|1:dobj|11:pnct">ve</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="conflicto" msd="NC" tag="NC" in="-1:nobj" out="1:attr">conflicto</W>
<W lemma="ético" msd="AN" tag="ADJ" in="-1:attr" out="">ético</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="cambio" msd="NC" tag="NC" in="-1:nobj" out="1:attr">cambio</W>
<W lemma="genético" msd="AN" tag="ADJ" in="-1:attr" out="">genético</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="animal" msd="NC" tag="NC" in="-1:nobj" out="">animales</W>
<W lemma="," msd="XP" tag="CM" in="-11:pnct" out="">,</W>
<W lemma="pero" msd="CC" tag="CCAD" in="2:coord" out="">pero</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="-2:coord|-1:neg|1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="">el</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="planta" msd="NC" tag="NC" in="-1:nobj" out="">plantas</W>
<W lemma="." msd="XP" tag="FS" in="-47:pnct" out="">.</W>
</s>
<s>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Leif</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:subj" out="-1:namef">Kjærgaard</W>
<W lemma="necesitar" msd="VAD" tag="VLfin" in="" out="-1:subj|1:dobj|44:pnct">necesita</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="permiso" msd="NC" tag="NC" in="-1:nobj" out="">permiso</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="producción" msd="NC" tag="NC" in="-1:nobj" out="">producción</W>
<W lemma="para" msd="SP" tag="SCENE" in="" out="1:nobj">para</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="semilla" msd="NC" tag="NC" in="-1:nobj" out="2:attr">semilla</W>
<W lemma="genético" msd="RG" tag="ADV" in="1:quant" out="">genéticamente</W>
<W lemma="manipular" msd="VAF" tag="VLadj" in="-2:attr" out="-1:quant">manipulada</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="plazo" msd="NC" tag="NC" in="-1:nobj" out="1:attr">plazo</W>
<W lemma="inferior" msd="AN" tag="ADJ" in="-1:attr" out="">inferior</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">a</W>
<W lemma="dos" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj|2:pnct|7:relr">dos</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="," msd="XP" tag="CM" in="-2:pnct" out="">,</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">lo</W>
<W lemma="contrario" msd="NC" tag="NC" in="-1:nobj" out="">contrario</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="interrumpir" msd="VAD" tag="VLfin" in="-7:relr" out="-1:robj|1:time">interrumpirá</W>
<W lemma="este" msd="" tag="DM" in="-1:time" out="1:nobj">esta</W>
<W lemma="parte" msd="NC" tag="NC" in="-1:nobj" out="">parte</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="actividad" msd="NC" tag="NC" in="-1:nobj" out="1:pobj.subj">actividad</W>
<W lemma="entre" msd="SP" tag="SCENE" in="-1:pobj.subj" out="1:nobj">entre</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">30</W>
<W lemma="empleado" msd="NC" tag="NC" in="-1:nobj" out="1:attr">empleados</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:attr" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="laboratorio" msd="NC" tag="NC" in="-1:nobj" out="1:attr">laboratorio</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attr" out="">biotecnológico</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="departamento" msd="NC" tag="NC" in="-1:nobj" out="">departamento</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="1:attr">Lolland</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:attr" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:nobj">Maribo</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Frø</W>
<W lemma="." msd="XP" tag="FS" in="-44:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">En</W>
<W lemma="realidad" msd="NC" tag="NC" in="-1:nobj" out="">realidad</W>
<W lemma="todo" msd="AN" tag="QU" in="5:subj" out="1:nobj">toda</W>
<W lemma="transformación" msd="NC" tag="NC" in="-1:nobj" out="">transformación</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="semilla" msd="NC" tag="NC" in="-1:nobj" out="">semillas</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="-5:subj|1:preds|3:pnct">es</W>
<W lemma="un" msd="PD" tag="ART" in="-1:preds" out="1:nobj">una</W>
<W lemma="mutación" msd="NC" tag="NC" in="-1:nobj" out="">mutación</W>
<W lemma="." msd="XP" tag="FS" in="-3:pnct" out="">.</W>
</s>
<s>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">En</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="método" msd="NC" tag="NC" in="-1:nobj" out="">métodos</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="cruce" msd="NC" tag="NC" in="-1:nobj" out="1:attr">cruce</W>
<W lemma="tradicional" msd="AN" tag="ADJ" in="-1:attr" out="">tradicionales</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="tardar" msd="VAD" tag="VLfin" in="" out="-1:robj|11:pnct|26:pnct|34:conj">tarda</W>
<W lemma="entre" msd="SP" tag="SCENE" in="" out="1:nobj">entre</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="2:conj">14</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-2:conj" out="-1:coord|1:nobj">15</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:vobj">en</W>
<W lemma="desarrollar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">desarrollar</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="2:nobj">un</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="">nuevo</W>
<W lemma="método" msd="NC" tag="NC" in="-2:nobj" out="-1:attr">método</W>
<W lemma="," msd="XP" tag="CM" in="-11:pnct" out="">,</W>
<W lemma="pero" msd="CC" tag="CCAD" in="1:coord" out="">pero</W>
<W lemma="con" msd="SP" tag="SCENE" in="" out="-1:coord|1:nobj">con</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="técnica" msd="NC" tag="NC" in="-1:nobj" out="">técnica</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="manipulación" msd="NC" tag="NC" in="-1:nobj" out="1:attr|2:conj">manipulación</W>
<W lemma="genético" msd="AN" tag="ADJ" in="-1:attr" out="">genética</W>
<W lemma="poder" msd="VAD" tag="VMfin" in="-2:conj" out="1:vobj">puede</W>
<W lemma="hacerse" msd="VA" tag="VCLI" in="-1:vobj" out="1:time">hacerse</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">en</W>
<W lemma="ocho" msd="AC" tag="CARD" in="-1:nobj" out="2:conj">ocho</W>
<W lemma="o" msd="CC" tag="CC" in="1:coord" out="">o</W>
<W lemma="nueve" msd="AC" tag="CARD" in="-2:conj" out="-1:coord|1:nobj">nueve</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="," msd="XP" tag="CM" in="-26:pnct" out="">,</W>
<W lemma="porque" msd="CS" tag="CSUBX" in="7:cond" out="2:vobj">porque</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="saltar" msd="VAD" tag="VLfin" in="-2:vobj" out="-1:robj|1:subj">saltan</W>
<W lemma="alguno" msd="AN" tag="QU" in="-1:subj" out="1:nobj">algunos</W>
<W lemma="paso" msd="NC" tag="NC" in="-1:nobj" out="">pasos</W>
<W lemma="y" msd="CC" tag="CC" in="2:coord" out="">y</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="ver" msd="VAD" tag="VLfin" in="-34:conj" out="-7:cond|-2:coord|-1:robj|1:man|2:conj|9:pnct">ve</W>
<W lemma="rápidamente" msd="RG" tag="ADV" in="-1:man" out="">rápidamente</W>
<W lemma="si" msd="CS" tag="CSUBX" in="-2:conj" out="3:vobj">si</W>
<W lemma="el" msd="PD" tag="ART" in="2:subj" out="1:nobj">la</W>
<W lemma="planta" msd="NC" tag="NC" in="-1:nobj" out="">planta</W>
<W lemma="tener" msd="VAD" tag="VLfin" in="-3:vobj" out="-2:subj|1:dobj">tiene</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">los</W>
<W lemma="genes" msd="NC" tag="NC" in="-1:nobj" out="1:attr">genes</W>
<W lemma="desear" msd="VAF" tag="VLadj" in="-1:attr" out="">deseados</W>
<W lemma="." msd="XP" tag="FS" in="-9:pnct" out="">.</W>
</s>
</p>
