<W msd="VSfin" lemma="ser">Es</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="poder">poder</W>
<W msd="ADJ" lemma="popular">popular</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="constar">consta</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ADJ" lemma="tanto">tantos</W>
<W msd="NC" lemma="voto">votos</W>
<W msd="ADJ" lemma="individual">individuales</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ADV" lemma="colectivo">colectivamente</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="decidir">decide</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="con">con</W>
<W msd="DM" lemma="este">esto</W>
<W msd="VLfin" lemma="ejercer">ejerce</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="autoridad">autoridad</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="&lt;unknown&gt;">Así</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ART" lemma="el">el</W>
<W msd="ADJ" lemma="ideal">ideal</W>
<W msd="NC" lemma="&lt;unknown&gt;">democrático</W>
<W msd="CM" lemma=",">,</W>
<W msd="CCAD" lemma="pero">pero</W>
<W msd="ADV" lemma="en~realidad">en realidad</W>
<W msd="VLfin" lemma="pensar">pienso</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">la</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">mayoría</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="elector">electores</W>
<W msd="DASH" lemma="-">-</W>
<W msd="PREP" lemma="con">con</W>
<W msd="NC" lemma="&lt;unknown&gt;">excepción</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">Uffe</W>
<W msd="NP" lemma="&lt;unknown&gt;">Ellemann</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">–</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="sentar|sentir">sienten</W>
<W msd="ADJ" lemma="impotente">impotentes</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="hora">hora</W>
<W msd="PREP" lemma="de">de</W>
<W msd="VLinf" lemma="elegir">elegir</W>
<W msd="PREP" lemma="a">a</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">políticos</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADV" lemma="sobre~todo">sobre todo</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">relación</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">referéndum</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="CE">CE</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="porque">Porque</W>
<W msd="ADV" lemma="&lt;unknown&gt;">¿quién</W>
<W msd="VLfin" lemma="comprender">comprende</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="significado">significado</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="VLadj" lemma="tratar">tratado</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Maastricht</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="&lt;unknown&gt;">qué</W>
<W msd="NC" lemma="consecuencia">consecuencias</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="tener">tener</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">“no”</W>
<W msd="FS" lemma="?">?</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">¿O</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">“sí”</W>
<W msd="FS" lemma="?">?</W>
<W msd="NC" lemma="nadie">Nadie</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="responder">responder</W>
<W msd="PREP" lemma="a">a</W>
<W msd="DM" lemma="este">esto</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="por">por</W>
<W msd="ART" lemma="el">lo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="mano">mano</W>
<W msd="VLfin" lemma="temblar">tiembla</W>
<W msd="CSUBX" lemma="cuando">cuando</W>
<W msd="VMfin" lemma="haber~que">hay que</W>
<W msd="VLinf" lemma="votar">votar</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="de">de</W>
<W msd="DM" lemma="este">este</W>
<W msd="NC" lemma="modo">modo</W>
<W msd="NC" lemma="ser">ser</W>
<W msd="ADJ" lemma="responsable">responsable</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="desarrollo">desarrollo</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">histórico</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">está</W>
<W msd="NC" lemma="&lt;unknown&gt;">implícito</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="cruz">cruz</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VMfin" lemma="haber~que">hay que</W>
<W msd="VLinf" lemma="poner">poner</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="papeleta">papeleta</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">votación</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="ADJ" lemma="ideal">ideal</W>
<W msd="NC" lemma="&lt;unknown&gt;">democrático</W>
<W msd="VLfin" lemma="implicar">implica</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="elector">electores</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="vez">vez</W>
<W msd="VLfin" lemma="dirigir">dirijan</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="sentido">sentido</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="desarrollo">desarrollo</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="historia">historia</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="sonar">Suena</W>
<W msd="ADJ" lemma="poderoso">poderoso</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="por">por</W>
<W msd="DM" lemma="ese">eso</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">iza</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="bandera">bandera</W>
<W msd="ADJ" lemma="dan�s">danesa</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">mayoría</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="colegio">colegios</W>
<W msd="ADJ" lemma="electoral">electorales</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="cuando">Cuando</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBI" lemma="a~pesar~de">a pesar de</W>
<W msd="PPX" lemma="�l">ello</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="votante">votantes</W>
<W msd="VLfin" lemma="sentar|sentir">sienten</W>
<W msd="NC" lemma="impotencia">impotencia</W>
<W msd="CM" lemma=",">,</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="PREP" lemma="por">por</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="sentimiento">sentimiento</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="historia">historia</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="desarrollo">desarrollo</W>
<W msd="REL" lemma="quien">quienes</W>
<W msd="PPX" lemma="nosotros">nos</W>
<W msd="VLfin" lemma="dirigir">dirigen</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="por">por</W>
<W msd="DM" lemma="ese">eso</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="cruz">cruz</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="papeleta">papeleta</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">votación</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="volver">vuelve</W>
<W msd="QU" lemma="algo">algo</W>
<W msd="NC" lemma="&lt;unknown&gt;">ilusoria</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">–</W>
<W msd="CSUBF" lemma="ya~que">ya que</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">más</W>
<W msd="ADV" lemma="bien">bien</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">reacción</W>
<W msd="PREP" lemma="a">a</W>
<W msd="QU" lemma="algo">algo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">decisión</W>
<W msd="PREP" lemma="por">por</W>
<W msd="QU" lemma="algo">algo</W>
<W msd="FS" lemma=".">.</W>
