<W msd="CSUBX" lemma="como">Como</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">taimado</W>
<W msd="NC" lemma="gobierno">gobierno</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">minorías</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="ministerio">ministerio</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">Poul</W>
<W msd="NP" lemma="&lt;unknown&gt;">Schlüter</W>
<W msd="CARD" lemma="IV">IV</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="emitir">emitido</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="proyecto">proyecto</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="&lt;unknown&gt;">Presupuesto</W>
<W msd="NP" lemma="&lt;unknown&gt;">Nacional</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">el</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">continúa</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">política</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">económica</W>
<W msd="VLadj" lemma="moderar">moderada</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">últimos</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">–</W>
<W msd="CCAD" lemma="pero">pero</W>
<W msd="PREP" lemma="sin">sin</W>
<W msd="NC" lemma="propuesta">propuestas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="ahorro">ahorro</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">provocativas</W>
<W msd="CC" lemma="o">o</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">ideológicas</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ADV" lemma="de~antemano">de antemano</W>
<W msd="VMfin" lemma="poder">puedan</W>
<W msd="VLinf" lemma="empujar">empujar</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">los</W>
<W msd="ADJ" lemma="decisivo">decisivos</W>
<W msd="NC" lemma="partido">partidos</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="centro">centro</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="brazo">brazos</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="partido">partido</W>
<W msd="NP" lemma="&lt;unknown&gt;">Socialdemócrata</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="de">De</W>
<W msd="QU" lemma="todo">todos</W>
<W msd="NC" lemma="modo">modos</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">el</W>
<W msd="VLfin" lemma="debatir">debate</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">política</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">económica</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="Dinamarca">Dinamarca</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">está</W>
<W msd="VLadj" lemma="volver">volviendo</W>
<W msd="ADV" lemma="de~nuevo">de nuevo</W>
<W msd="PREP" lemma="a">a</W>
<W msd="VSinf" lemma="ser">ser</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">cuestión</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">ideología</W>
<W msd="CC" lemma="o">o</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="moral">moral</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="porque">Porque</W>
<W msd="DM" lemma="ese">ese</W>
<W msd="ADJ" lemma="mismo">mismo</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">día</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">–</W>
<W msd="NC" lemma="martes">martes</W>
<W msd="DASH" lemma="-">-</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="partido">partido</W>
<W msd="NP" lemma="&lt;unknown&gt;">Socialdemócrata</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">emitió</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">precisión</W>
<W msd="ADJ" lemma="minucioso">minuciosa</W>
<W msd="CM" lemma=",">,</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="propuesta">propuesta</W>
<W msd="ADJ" lemma="alternativo">alternativa</W>
<W msd="PREP" lemma="para">para</W>
<W msd="ART" lemma="un">un</W>
<W msd="QT" lemma="&quot;">"</W>
<W msd="NC" lemma="&lt;unknown&gt;">Presupuesto</W>
<W msd="NP" lemma="&lt;unknown&gt;">Nacional</W>
<W msd="QT" lemma="&quot;">"</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">Las</W>
<W msd="NC" lemma="diferencia">diferencias</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">ideológicas</W>
<W msd="SLASH" lemma="/">/</W>
<W msd="ADJ" lemma="moral">morales</W>
<W msd="VLfin" lemma="quedar">quedan</W>
<W msd="ADJ" lemma="claro">claras</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="resumen">resumen</W>
<W msd="VMfin" lemma="poder">pueden</W>
<W msd="VCLI" lemma="expresarse">expresarse</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">así</W>
<W msd="COLON" lemma=":">:</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="partido">partido</W>
<W msd="NP" lemma="&lt;unknown&gt;">Socialdemócrata</W>
<W msd="COLON" lemma=":">:</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="podar|poder">podemos</W>
<W msd="VLinf" lemma="permitir">permitir</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="desempleado">desempleados</W>
<W msd="VLfin" lemma="seguir">sigan</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="pato">pato</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="tener">Tenemos</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">superávit</W>
<W msd="ADV" lemma="tan">tan</W>
<W msd="ADJ" lemma="grande">grande</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="balanza">balanza</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="pago">pagos</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="NC" lemma="medio">medios</W>
<W msd="CSUBI" lemma="para">para</W>
<W msd="VLinf" lemma="aumentar">aumentar</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">producción</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NP" lemma="Dinamarca">Dinamarca</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="deber">Debemos</W>
<W msd="VLinf" lemma="aprovechar">aprovechar</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">ocasión</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="con">Con</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">política</W>
<W msd="ADJ" lemma="financiero">financiera</W>
<W msd="ADV" lemma="menos">menos</W>
<W msd="VLadj" lemma="restringir">restringida</W>
<W msd="LP" lemma="(">(</W>
<W msd="ADJ" lemma="grande">mayor</W>
<W msd="NC" lemma="&lt;unknown&gt;">déficit</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">público</W>
<W msd="RP" lemma=")">)</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="consumo">consumo</W>
<W msd="ADJ" lemma="privado">privado</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">aumentaría</W>
<W msd="ADV" lemma="considerablemente">considerablemente</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="entonces">Entonces</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">descendería</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="paro">paro</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="ingreso">ingresos</W>
<W msd="ADJ" lemma="fiscal">fiscales</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">aumentarían</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="&lt;unknown&gt;">título</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="plan">plan</W>
<W msd="COLON" lemma=":">:</W>
<W msd="NC" lemma="&lt;unknown&gt;">“El</W>
<W msd="ADJ" lemma="bueno">buen</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">círculo”</W>
<W msd="FS" lemma=".">.</W>
