<W lemma="como" msd="CSUBX" in="15:comp" out="1:nobj">Como</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:attr|2:nobj|5:ref|6:relr">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:attr" out="">taimado</W>
<W lemma="gobierno" msd="NC" in="-2:nobj" out="1:about#">gobierno</W>
<W lemma="de" msd="PREP" in="-1:about#" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">minorías</W>
<W lemma="que" msd="CQUE" in="-5:ref|1:subj" out="">que</W>
<W lemma="ser" msd="VSfin" in="-6:relr|3:coref" out="-1:subj">es</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="el" msd="ART" in="6:subj|7:[subj]" out="1:nobj">el</W>
<W lemma="ministerio" msd="NC" in="-1:nobj" out="-3:coref|1:other">ministerio</W>
<W lemma="de" msd="PREP" in="-1:other" out="2:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="1:namef" out="">Poul</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:nobj" out="-1:namef|1:namel">Schlüter</W>
<W lemma="IV" msd="CARD" in="-1:namel" out="">IV</W>
<W lemma="haber" msd="VHfin" in="" out="-15:comp|-6:subj|1:vobj|45:pnct">ha</W>
<W lemma="emitir" msd="VLadj" in="-1:vobj" out="-7:[subj]|1:dobj">emitido</W>
<W lemma="un" msd="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="proyecto" msd="NC" in="-1:nobj" out="1:about">proyecto</W>
<W lemma="del" msd="PDEL" in="-1:about" out="1:nobj">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attr">Presupuesto</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:attr" out="">Nacional</W>
<W lemma="con" msd="PREP" in="" out="15:conj">con</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="que" msd="CQUE" in="" out="">que</W>
<W lemma="se" msd="SE" in="" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="1:subj">continúa</W>
<W lemma="el" msd="ART" in="-1:subj" out="1:nobj|2:attr|3:attr|4:time">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">política</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:attr" out="">económica</W>
<W lemma="moderar" msd="VLadj" in="-3:attr" out="">moderada</W>
<W lemma="de" msd="PREP" in="-4:time" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:attr|2:nobj">los</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">últimos</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-2:nobj" out="">años</W>
<W lemma="&lt;unknown&gt;" msd="VLadj" in="1:pnct" out="">–</W>
<W lemma="pero" msd="CCAD" in="1:coord" out="-1:pnct">pero</W>
<W lemma="sin" msd="PREP" in="-15:conj" out="-1:coord|1:nobj">sin</W>
<W lemma="propuesta" msd="NC" in="-1:nobj" out="1:pobj&3a;arg|3:attr|6:ref|8:relr">propuestas</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;arg" out="1:nobj">de</W>
<W lemma="ahorro" msd="NC" in="-1:nobj" out="">ahorro</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-3:attr" out="2:conj">provocativas</W>
<W lemma="o" msd="CC" in="1:coord" out="">o</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:conj" out="-1:coord">ideológicas</W>
<W lemma="que" msd="CQUE" in="-6:ref|2:subj|3:[subj]" out="">que</W>
<W lemma="de~antemano" msd="ADV" in="1:time" out="">de antemano</W>
<W lemma="poder" msd="VMfin" in="-8:relr" out="-2:subj|-1:time|1:vobj|8:dir">puedan</W>
<W lemma="empujar" msd="VLinf" in="-1:vobj" out="-3:[subj]|2:dobj">empujar</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="el" msd="ART" in="-2:dobj" out="1:attr|2:nobj">los</W>
<W lemma="decisivo" msd="ADJ" in="-1:attr" out="">decisivos</W>
<W lemma="partido" msd="NC" in="-2:nobj" out="1:loc">partidos</W>
<W lemma="del" msd="PDEL" in="-1:loc" out="1:nobj">del</W>
<W lemma="centro" msd="NC" in="-1:nobj" out="">centro</W>
<W lemma="a" msd="PREP" in="-8:dir" out="1:nobj">a</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="brazo" msd="NC" in="-1:nobj" out="1:const">brazos</W>
<W lemma="del" msd="PDEL" in="-1:const" out="1:nobj|37:coref-id">del</W>
<W lemma="partido" msd="NC" in="-1:nobj" out="1:attr">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:attr" out="">Socialdemócrata</W>
<W lemma="." msd="FS" in="-45:pnct" out="">.</W>
<W lemma="de" msd="PREP" in="13:prg" out="1:nobj|3:pnct">De</W>
<W lemma="todo" msd="QU" in="-1:nobj" out="1:nobj">todos</W>
<W lemma="modo" msd="NC" in="-1:nobj" out="">modos</W>
<W lemma="," msd="CM" in="-3:pnct" out="">,</W>
<W lemma="el" msd="ART" in="9:subj|10:[subj]" out="1:nobj">el</W>
<W lemma="debatir" msd="VLfin" in="-1:nobj" out="1:elab">debate</W>
<W lemma="sobre" msd="PREP" in="-1:elab" out="1:nobj">sobre</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj|2:attr|3:loc">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">política</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:attr" out="">económica</W>
<W lemma="de" msd="PREP" in="-3:loc" out="1:nobj">de</W>
<W lemma="Dinamarca" msd="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-13:prg|-9:subj|-1:robj|1:vobj|2:other|12:pnct">está</W>
<W lemma="volver" msd="VLadj" in="-1:vobj" out="-10:[subj]|3:vobj">volviendo</W>
<W lemma="de~nuevo" msd="ADV" in="-2:other" out="">de nuevo</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="ser" msd="VSinf" in="-3:vobj" out="1:preds">ser</W>
<W lemma="un" msd="ART" in="-1:preds" out="1:nobj">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:pobj&3a;arg">cuestión</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;arg" out="1:nobj|3:conj">de</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:nobj" out="">ideología</W>
<W lemma="o" msd="CC" in="1:coord" out="">o</W>
<W lemma="de" msd="PREP" in="-3:conj" out="-1:coord|1:nobj">de</W>
<W lemma="moral" msd="NC" in="-1:nobj" out="">moral</W>
<W lemma="." msd="FS" in="-12:pnct" out="">.</W>
<W lemma="porque" msd="CSUBX" in="10:struct" out="">Porque</W>
<W lemma="ese" msd="DM" in="9:time" out="1:focal|3:pnct|4:appa">ese</W>
<W lemma="mismo" msd="ADJ" in="-1:focal" out="1:nobj">mismo</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-1:nobj" out="">día</W>
<W lemma="&lt;unknown&gt;" msd="VLinf" in="-3:pnct" out="">–</W>
<W lemma="martes" msd="NC" in="-4:appa" out="1:pnct">martes</W>
<W lemma="-" msd="DASH" in="-1:pnct" out="">-</W>
<W lemma="el" msd="ART" in="-37:coref-id|3:subj" out="1:nobj|10:coref">el</W>
<W lemma="partido" msd="NC" in="-1:nobj" out="1:attr">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:attr" out="">Socialdemócrata</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-3:subj|-10:struct|-9:time|2:man|7:dobj|16:pnct">emitió</W>
<W lemma="," msd="CM" in="1:pnct" out="">,</W>
<W lemma="con" msd="PREP" in="-2:man" out="-1:pnct|1:nobj|4:pnct">con</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj|2:attr">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">precisión</W>
<W lemma="minucioso" msd="ADJ" in="-2:attr" out="">minuciosa</W>
<W lemma="," msd="CM" in="-4:pnct" out="">,</W>
<W lemma="suyo" msd="PPO" in="-7:dobj|-10:coref" out="1:nobj|2:attr|24:coref">su</W>
<W lemma="propuesta" msd="NC" in="-1:nobj" out="2:other">propuesta</W>
<W lemma="alternativo" msd="ADJ" in="-2:attr" out="">alternativa</W>
<W lemma="para" msd="PREP" in="-2:other" out="1:nobj">para</W>
<W lemma="un" msd="ART" in="-1:nobj" out="3:attr">un</W>
<W lemma="&amp;quot;" msd="QT" in="" out="1:nobj">"</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">Presupuesto</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-3:attr" out="">Nacional</W>
<W lemma="&amp;quot;" msd="QT" in="" out="">"</W>
<W lemma="." msd="FS" in="-16:pnct" out="">.</W>
<W lemma="el" msd="ART" in="5:subj" out="1:nobj|2:attr|10:coref">Las</W>
<W lemma="diferencia" msd="NC" in="-1:nobj" out="">diferencias</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:attr" out="2:conj">ideológicas</W>
<W lemma="/" msd="SLASH" in="1:coord" out="">/</W>
<W lemma="moral" msd="ADJ" in="-2:conj" out="-1:coord">morales</W>
<W lemma="quedar" msd="VLfin" in="" out="-5:subj|5:conj|1:preds">quedan</W>
<W lemma="claro" msd="ADJ" in="-1:preds" out="">claras</W>
<W lemma="y" msd="CC" in="3:coord" out="">y</W>
<W lemma="en" msd="PREP" in="2:man" out="1:nobj">en</W>
<W lemma="resumen" msd="NC" in="-1:nobj" out="">resumen</W>
<W lemma="poder" msd="VMfin" in="-5:conj|-10:coref" out="-3:coord|-2:man|1:vobj|2:man|3:pnct">pueden</W>
<W lemma="expresarse" msd="VCLI" in="-1:vobj" out="">expresarse</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-2:man" out="">así</W>
<W lemma="&3a;" msd="COLON" in="-3:pnct" out="">:</W>
<W lemma="el" msd="ART" in="-24:coref" out="1:nobj|2:attr|3:pnct|5:assoc-agent">El</W>
<W lemma="partido" msd="NC" in="-1:nobj" out="">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-2:attr" out="">Socialdemócrata</W>
<W lemma="&3a;" msd="COLON" in="-3:pnct" out="">:</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="podar&7c;poder" msd="VLfin" in="-5:assoc-agent" out="-1:neg|1:vobj|8:pnct">podemos</W>
<W lemma="permitir" msd="VLinf" in="-1:vobj" out="1:dobj">permitir</W>
<W lemma="que" msd="CQUE" in="-1:dobj" out="3:vobj">que</W>
<W lemma="el" msd="ART" in="2:subj" out="1:nobj">los</W>
<W lemma="desempleado" msd="NC" in="-1:nobj" out="">desempleados</W>
<W lemma="seguir" msd="VLfin" in="-3:vobj" out="-2:subj|1:dobj">sigan</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="pato" msd="NC" in="-1:nobj" out="">pato</W>
<W lemma="." msd="FS" in="-8:pnct" out="">.</W>
<W lemma="tener" msd="VLfin" in="" out="1:dobj|5:loc|19:pnct|20:coref">Tenemos</W>
<W lemma="un" msd="ART" in="-1:dobj" out="1:nobj|3:attr">un</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">superávit</W>
<W lemma="tan" msd="ADV" in="1:degr" out="">tan</W>
<W lemma="grande" msd="ADJ" in="-3:attr" out="-1:degr">grande</W>
<W lemma="en" msd="PREP" in="-5:loc" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="balanza" msd="NC" in="-1:nobj" out="1:pobj&3a;arg#">balanza</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;arg#" out="1:nobj">de</W>
<W lemma="pago" msd="NC" in="-1:nobj" out="">pagos</W>
<W lemma="que" msd="CQUE" in="" out="1:vobj">que</W>
<W lemma="haber" msd="VHfin" in="-1:vobj" out="1:dobj">hay</W>
<W lemma="medio" msd="NC" in="-1:dobj" out="1:goal">medios</W>
<W lemma="para" msd="CSUBI" in="-1:goal" out="1:vobj">para</W>
<W lemma="aumentar" msd="VLinf" in="-1:vobj" out="1:dobj">aumentar</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:loc">producción</W>
<W lemma="en" msd="PREP" in="-1:loc" out="1:nobj">en</W>
<W lemma="Dinamarca" msd="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="." msd="FS" in="-19:pnct" out="">.</W>
<W lemma="deber" msd="VLfin" in="-20:coref" out="1:vobj|4:pnct">Debemos</W>
<W lemma="aprovechar" msd="VLinf" in="-1:vobj" out="1:dobj">aprovechar</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">ocasión</W>
<W lemma="." msd="FS" in="-4:pnct" out="">.</W>
<W lemma="con" msd="PREP" in="14:man" out="1:nobj">Con</W>
<W lemma="un" msd="ART" in="-1:nobj" out="1:nobj|2:attr|4:attr">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">política</W>
<W lemma="financiero" msd="ADJ" in="-2:attr" out="">financiera</W>
<W lemma="menos" msd="ADV" in="1:degr" out="">menos</W>
<W lemma="restringir" msd="VLadj" in="-4:attr" out="-1:degr">restringida</W>
<W lemma="(" msd="LP" in="2:pnct" out="">(</W>
<W lemma="grande" msd="ADJ" in="1:attr" out="">mayor</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="-2:pnct|-1:attr|1:attr|2:pnct">déficit</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">público</W>
<W lemma=")" msd="RP" in="-2:pnct" out="">)</W>
<W lemma="el" msd="ART" in="3:subj" out="1:nobj|2:attr">el</W>
<W lemma="consumo" msd="NC" in="-1:nobj" out="">consumo</W>
<W lemma="privado" msd="ADJ" in="-2:attr" out="">privado</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-3:subj|-14:man|1:degr|2:pnct">aumentaría</W>
<W lemma="considerablemente" msd="ADV" in="-1:degr" out="">considerablemente</W>
<W lemma="." msd="FS" in="-2:pnct" out="">.</W>
<W lemma="entonces" msd="ADV" in="1:struct" out="">Entonces</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:struct|1:subj|7:conj">descendería</W>
<W lemma="el" msd="ART" in="-1:subj" out="1:nobj">el</W>
<W lemma="paro" msd="NC" in="-1:nobj" out="">paro</W>
<W lemma="y" msd="CC" in="4:coord" out="">y</W>
<W lemma="el" msd="ART" in="3:subj" out="1:nobj|2:attr">los</W>
<W lemma="ingreso" msd="NC" in="-1:nobj" out="">ingresos</W>
<W lemma="fiscal" msd="ADJ" in="-2:attr" out="">fiscales</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-7:conj" out="-4:coord|-3:subj|1:pnct">aumentarían</W>
<W lemma="." msd="FS" in="-1:pnct" out="">.</W>
<W lemma="el" msd="ART" in="" out="1:nobj|4:pnct">El</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:pobj&3a;arg">título</W>
<W lemma="del" msd="PDEL" in="-1:pobj&3a;arg" out="1:nobj">del</W>
<W lemma="plan" msd="NC" in="-1:nobj" out="">plan</W>
<W lemma="&3a;" msd="COLON" in="-4:pnct" out="">:</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="1:attr|2:nobj|3:pnct">“El</W>
<W lemma="bueno" msd="ADJ" in="-1:attr" out="">buen</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-2:nobj" out="">círculo”</W>
<W lemma="." msd="FS" in="-3:pnct" out="">.</W>
