<W msd="VSfin" lemma="ser">Son</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="sucursal">sucursales</W>
<W msd="ADJ" lemma="dan�s">danesas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="ADJ" lemma="grande">grandes</W>
<W msd="NC" lemma="empresa">empresas</W>
<W msd="ADJ" lemma="multinacional">multinacionales</W>
<W msd="ART" lemma="el">las</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="usar">usan</W>
<W msd="CARD" lemma="millones">millones</W>
<W msd="PREP" lemma="para">para</W>
<W msd="NC" lemma="&lt;unknown&gt;">publicidades</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">TV-2.</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">“Gold”</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">ABBA</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VS" lemma="ser">sido</W>
<W msd="ADV" lemma="masivo">masivamente</W>
<W msd="VLadj" lemma="anunciar">anunciado</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión</W>
<W msd="CM" lemma=",">,</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">así</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">“grandes</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">éxitos”</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">AC/DC</W>
<W msd="CC" lemma="y">y</W>
<W msd="QU" lemma="otro">otros</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">“Creo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="&lt;unknown&gt;">campañas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="anuncio">anuncios</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">dañan</W>
<W msd="ADV" lemma="mucho">mucho</W>
<W msd="PAL" lemma="al">al</W>
<W msd="NC" lemma="&lt;unknown&gt;">rock</W>
<W msd="NC" lemma="&lt;unknown&gt;">danés</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="saber">Sabemos</W>
<W msd="PREP" lemma="por">por</W>
<W msd="NC" lemma="experiencia">experiencia</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="grupo">grupo</W>
<W msd="ADJ" lemma="grande">grande</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">público</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">sólo</W>
<W msd="VLfin" lemma="comprar">compran</W>
<W msd="CARD" lemma="tres">tres</W>
<W msd="CC" lemma="o">o</W>
<W msd="CARD" lemma="cuatro">cuatro</W>
<W msd="NC" lemma="disco">discos</W>
<W msd="PREP" lemma="por">por</W>
<W msd="NC" lemma="&lt;unknown&gt;">año</W>
<W msd="FS" lemma=".">.</W>
<W msd="CC" lemma="y">Y</W>
<W msd="CSUBX" lemma="mientras~que">mientras que</W>
<W msd="ADV" lemma="antes">antes</W>
<W msd="VLfin" lemma="haber">hubieran</W>
<W msd="VLadj" lemma="comprar">comprado</W>
<W msd="NC" lemma="disco">discos</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Kim</W>
<W msd="NP" lemma="&lt;unknown&gt;">Larsen</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Anne</W>
<W msd="NP" lemma="&lt;unknown&gt;">Linnet</W>
<W msd="CC" lemma="y">y</W>
<W msd="NP" lemma="&lt;unknown&gt;">TV-2</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADV" lemma="ahora">ahora</W>
<W msd="VLfin" lemma="comprar">compran</W>
<W msd="ART" lemma="el">lo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="ver">ven</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="&lt;unknown&gt;">publicidades</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión,”</W>
<W msd="VLfin" lemma="decir">dice</W>
<W msd="NP" lemma="Stefan">Stefan</W>
<W msd="NP" lemma="&lt;unknown&gt;">Fryland</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="presidente">presidente</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">unión</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="empresa">empresas</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">discográficas</W>
<W msd="NP" lemma="&lt;unknown&gt;">IFPI</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="NP" lemma="&lt;unknown&gt;">Fryland</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADV" lemma="&lt;unknown&gt;">también</W>
<W msd="NC" lemma="director">director</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">Polygram</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">–</W>
<W msd="ART" lemma="un">una</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="empresa">empresas</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">más</W>
<W msd="VLfin" lemma="anunciar">anuncia</W>
<W msd="PREP" lemma="por">por</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="disco">discos</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ADJ" lemma="grande">grandes</W>
<W msd="NC" lemma="&lt;unknown&gt;">éxitos</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">lo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ADV" lemma="bien">bien</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="poner">poner</W>
<W msd="PAL" lemma="al">al</W>
<W msd="VLadj" lemma="descubrir">descubierto</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="PPO" lemma="suyo">sus</W>
<W msd="NC" lemma="declaraci�n">declaraciones</W>
<W msd="ADV" lemma="&lt;unknown&gt;">quizá</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ADJ" lemma="bueno">buena</W>
<W msd="NC" lemma="voluntad">voluntad</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">“Sé</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="tener">tengo</W>
<W msd="CARD" lemma="dos">dos</W>
<W msd="NC" lemma="papel">papeles</W>
<W msd="CC" lemma="y">y</W>
<W msd="CARD" lemma="dos">dos</W>
<W msd="NC" lemma="&lt;unknown&gt;">cálculos</W>
<W msd="ADJ" lemma="diferente">diferentes</W>
<W msd="PREP" lemma="en">en</W>
<W msd="DM" lemma="este">este</W>
<W msd="NC" lemma="asunto">asunto</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="ADV" lemma="&lt;unknown&gt;">también</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="PPO" lemma="m�o">mi</W>
<W msd="NC" lemma="&lt;unknown&gt;">opinión</W>
<W msd="ADV" lemma="totalmente">totalmente</W>
<W msd="ADJ" lemma="personal">personal</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="&lt;unknown&gt;">publicidades</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">televisión</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">perjudiciales,”</W>
<W msd="VLfin" lemma="decir">dice</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">él</W>
<W msd="FS" lemma=".">.</W>
<W msd="NEG" lemma="no">No</W>
<W msd="VLfin" lemma="existir">existen</W>
<W msd="NC" lemma="cuenta">cuentas</W>
<W msd="PREP" lemma="acerca~de">acerca de</W>
<W msd="NC" lemma="&lt;unknown&gt;">cuántos</W>
<W msd="CARD" lemma="millones">millones</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="corona">coronas</W>
<W msd="VLfin" lemma="utilizar">utiliza</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="sector">sector</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">discográfico</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">campañas</W>
<W msd="ADJ" lemma="televisivo">televisivas</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="ADJ" lemma="mucho">mucha</W>
<W msd="NC" lemma="gente">gente</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="pensar">piensa</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="llamar">llama</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">reflexión</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="hecho">hecho</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="venta">venta</W>
<W msd="ADJ" lemma="total">total</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="disminuir">disminuido</W>
<W msd="CSUBI" lemma="a~pesar~de">a pesar de</W>
<W msd="QU" lemma="todo">todo</W>
<W msd="FS" lemma=".">.</W>
