<W msd="NC" lemma="&lt;unknown&gt;">¿Qué</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">hacías</W>
<W msd="ADV" lemma="antes">antes</W>
<W msd="CSUBI" lemma="de">de</W>
<W msd="VLinf" lemma="comenzar">comenzar</W>
<W msd="PREP" lemma="a">a</W>
<W msd="VLinf" lemma="buscar">buscar</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="contrato">contrato</W>
<W msd="FS" lemma="?">?</W>
<W msd="NC" lemma="&lt;unknown&gt;">“Entonces</W>
<W msd="VLfin" lemma="trabajar">trabajaba</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="control">control</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="calidad">calidad</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="empresa">empresa</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="circuito">circuitos</W>
<W msd="VLadj" lemma="integrar">integrados</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="VLfin" lemma="usar">usaba</W>
<W msd="QU" lemma="demasiado">demasiado</W>
<W msd="NC" lemma="tiempo">tiempo</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">ello.”</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">¿Entonces</W>
<W msd="VLfin" lemma="dejar">dejaste</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="trabajo">trabajo</W>
<W msd="FS" lemma="?">?</W>
<W msd="NC" lemma="&lt;unknown&gt;">“No</W>
<W msd="CM" lemma=",">,</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">diría</W>
<W msd="DM" lemma="ese">eso</W>
<W msd="FS" lemma=".">.</W>
<W msd="DM" lemma="ese">Eso</W>
<W msd="PPO" lemma="�l">lo</W>
<W msd="VLfin" lemma="decir">dicen</W>
<W msd="ADV" lemma="siempre">siempre</W>
<W msd="FS" lemma=".">.</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">Tomé</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">decisión</W>
<W msd="CSUBI" lemma="de">de</W>
<W msd="VLinf" lemma="averiguar">averiguar</W>
<W msd="CSUBX" lemma="si">si</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">había</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="lugar">lugar</W>
<W msd="CSUBI" lemma="para">para</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">mí</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="VLfin" lemma="industriar">industria</W>
<W msd="NC" lemma="&lt;unknown&gt;">musical.”</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">Débiles</W>
<W msd="VLfin" lemma="hollar">huellas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="dolor">dolor</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="de~hecho">De hecho</W>
<W msd="CM" lemma=",">,</W>
<W msd="NP" lemma="&lt;unknown&gt;">Ester</W>
<W msd="NP" lemma="&lt;unknown&gt;">Brohus</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="QU" lemma="todo">todo</W>
<W msd="NC" lemma="desconocida">desconocida</W>
<W msd="FS" lemma=".">.</W>
<W msd="QU" lemma="mucho">Muchos</W>
<W msd="ADJ" lemma="dan�s">daneses</W>
<W msd="PPO" lemma="�l">la</W>
<W msd="VHfin" lemma="haber">han</W>
<W msd="VLadj" lemma="escuchar">escuchado</W>
<W msd="VLinf" lemma="cantar">cantar</W>
<W msd="VLfin" lemma="hacer">hace</W>
<W msd="NC" lemma="tiempo">tiempo</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="desde">Desde</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">tenía</W>
<W msd="CARD" lemma="@card@">12</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="PREP" lemma="hasta">hasta</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">cumplió</W>
<W msd="CARD" lemma="@card@">25</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">recurría</W>
<W msd="QU" lemma="todo">todo</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">país</W>
<W msd="PREP" lemma="junto~con">junto con</W>
<W msd="CARD" lemma="dos">dos</W>
<W msd="NC" lemma="hermano">hermanas</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="hermano">hermano</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="padre">padres</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">La</W>
<W msd="NC" lemma="familia">familia</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">aprovechaba</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="fin">fines</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="semana">semana</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="vacaci�n">vacaciones</W>
<W msd="CSUBI" lemma="para">para</W>
<W msd="VLinf" lemma="tocar">tocar</W>
<W msd="CC" lemma="y">y</W>
<W msd="VLinf" lemma="cantar">cantar</W>
<W msd="NC" lemma="&lt;unknown&gt;">gospels</W>
<W msd="ADJ" lemma="cristiano">cristianos</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="&lt;unknown&gt;">romerías</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="&lt;unknown&gt;">cárceles</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="centro">centros</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="reuni�n">reuniones</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="cuenta">cuenta</W>
<W msd="PPX" lemma="�l">ella</W>
<W msd="FS" lemma=".">.</W>
<W msd="NC" lemma="&lt;unknown&gt;">“Mucha</W>
<W msd="NC" lemma="gente">gente</W>
<W msd="VLfin" lemma="pensar">pensaba</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VEfin" lemma="era">era</W>
<W msd="ADJ" lemma="raro">raro</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="continuar">continuara</W>
<W msd="VLadj" lemma="andar">andando</W>
<W msd="PREP" lemma="con">con</W>
<W msd="PPO" lemma="m�o">mi</W>
<W msd="NC" lemma="familia">familia</W>
<W msd="PREP" lemma="hasta">hasta</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">tenía</W>
<W msd="CARD" lemma="@card@">25</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="VLfin" lemma="estar">estamos</W>
<W msd="ADV" lemma="muy">muy</W>
<W msd="VLadj" lemma="unir">unidos</W>
<W msd="FS" lemma=".">.</W>
<W msd="PPO" lemma="m�o">Mi</W>
<W msd="VLfin" lemma="maridar">marido</W>
<W msd="CC" lemma="y">y</W>
<W msd="PPX" lemma="yo">yo</W>
<W msd="VLfin" lemma="vivir">vivimos</W>
<W msd="ADV" lemma="&lt;unknown&gt;">aún</W>
<W msd="ADV" lemma="muy">muy</W>
<W msd="ADV" lemma="cerca">cerca</W>
<W msd="PREP" lemma="de">de</W>
<W msd="PPO" lemma="yo">mis</W>
<W msd="NC" lemma="&lt;unknown&gt;">padres.”</W>
