<W msd="CSUBX" lemma="como">Como</W>
<W msd="NC" lemma="&lt;unknown&gt;">Pia</W>
<W msd="NP" lemma="&lt;unknown&gt;">Kjærsgaard</W>
<W msd="VMfin" lemma="deber">debe</W>
<W msd="VLinf" lemma="saber">saber</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">países</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="comunidad">Comunidad</W>
<W msd="NP" lemma="&lt;unknown&gt;">Europea</W>
<W msd="CM" lemma=",">,</W>
<W msd="VHfin" lemma="haber">han</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">colaboradodurante</W>
<W msd="QU" lemma="varios">varios</W>
<W msd="NC" lemma="&lt;unknown&gt;">años</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">política</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">inmigración</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">político</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">colaboración</W>
<W msd="VHfin" lemma="haber">ha</W>
<W msd="VLadj" lemma="resultar">resultado</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="&lt;unknown&gt;">Convención</W>
<W msd="PREP" lemma="sobre">sobre</W>
<W msd="NP" lemma="&lt;unknown&gt;">Asilo</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="CE">CE</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="establecer">establece</W>
<W msd="VLinf" lemma="&lt;unknown&gt;">qué</W>
<W msd="NC" lemma="estado">estado</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">será</W>
<W msd="ADJ" lemma="responsable">responsable</W>
<W msd="NC" lemma="&lt;unknown&gt;">deltratamiento</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="solicitud">solicitudes</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="dar">dan</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="estado">estado</W>
<W msd="NC" lemma="miembro">miembro</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="CE">CE</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="cuando">Cuando</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">convención</W>
<W msd="PREP" lemma="entre">entre</W>
<W msd="PREP" lemma="en">en</W>
<W msd="NC" lemma="vigencia">vigencia</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">podrá</W>
<W msd="ADV" lemma="por~ejemplo">por ejemplo</W>
<W msd="VLinf" lemma="impedir">impedir</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="solicitante">solicitante</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="VMfin" lemma="poder">pueda</W>
<W msd="VLinf" lemma="solicitar">solicitar</W>
<W msd="QU" lemma="dicho">dicho</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="PREP" lemma="en">en</W>
<W msd="QU" lemma="varios">varios</W>
<W msd="NC" lemma="&lt;unknown&gt;">países</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">simultáneamente</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBF" lemma="ya~que">ya que</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="solicitud">solicitud</W>
<W msd="ADV" lemma="solamente">solamente</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="tratar">trata</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="&lt;unknown&gt;">país</W>
<W msd="FS" lemma=".">.</W>
<W msd="DM" lemma="este">Esto</W>
<W msd="VLfin" lemma="significar">significa</W>
<W msd="CM" lemma=",">,</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="solicitante">solicitante</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBF" lemma="una~vez~que">una vez que</W>
<W msd="VHfin" lemma="haber">haya</W>
<W msd="VLadj" lemma="entregar">entregado</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="solicitud">solicitud</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ADV" lemma="por~ejemplo">por ejemplo</W>
<W msd="NP" lemma="Portugal">Portugal</W>
<W msd="CC" lemma="o">o</W>
<W msd="NP" lemma="&lt;unknown&gt;">España</W>
<W msd="CM" lemma=",">,</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VCLI" lemma="dirigirse">dirigirse</W>
<W msd="PREP" lemma="a">a</W>
<W msd="NP" lemma="Dinamarca">Dinamarca</W>
<W msd="ADV" lemma="&lt;unknown&gt;">después</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="VLfin" lemma="sostener">sostiene</W>
<W msd="NC" lemma="&lt;unknown&gt;">Pia</W>
<W msd="NP" lemma="&lt;unknown&gt;">Kjærsgaard</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="ADV" lemma="simplemente">simplemente</W>
<W msd="VLinf" lemma="lograr">lograr</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="solicitud">solicitud</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="tratar">trate</W>
<W msd="VLadj" lemma="&lt;unknown&gt;">allí</W>
<W msd="FS" lemma=".">.</W>
<W msd="DM" lemma="ese">ESE</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">será</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="resultado">resultado</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">convención</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">países</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="CE">CE</W>
<W msd="VHfin" lemma="haber">han</W>
<W msd="VLadj" lemma="elaborar">elaborado</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="NC" lemma="parte">parte</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">colaboración</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">ámbito</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">inmigración</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="FS" lemma=".">.</W>
<W msd="CCAD" lemma="pero">Pero</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="tener">tiene</W>
<W msd="QU" lemma="nada">nada</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLinf" lemma="ver">ver</W>
<W msd="PREP" lemma="con">con</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">Tratado</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="&lt;unknown&gt;">Unión</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">La</W>
<W msd="NC" lemma="novedad">novedad</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">Tratado</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="&lt;unknown&gt;">Unión</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">la</W>
<W msd="ADV" lemma="ya">ya</W>
<W msd="ADJ" lemma="existente">existente</W>
<W msd="NC" lemma="&lt;unknown&gt;">colaboración</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="&lt;unknown&gt;">ámbito</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">política</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">inmigración</W>
<W msd="CC" lemma="y">y</W>
<W msd="NC" lemma="asilo">asilo</W>
<W msd="VLfin" lemma="encontrar">encuentre</W>
<W msd="PPO" lemma="suyo">su</W>
<W msd="NC" lemma="sitio">sitio</W>
<W msd="PDEL" lemma="dentro~del">dentro del</W>
<W msd="NC" lemma="marco">marco</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="VLadj" lemma="tratar">tratado</W>
<W msd="FS" lemma=".">.</W>
<W msd="NP" lemma="&lt;unknown&gt;">Todavía</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="tratar">trata</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">colaboración</W>
<W msd="ADJ" lemma="interestatal">interestatal</W>
<W msd="CM" lemma=",">,</W>
<W msd="CCAD" lemma="pero">pero</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">países</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NP" lemma="CE">CE</W>
<W msd="VHfin" lemma="haber">han</W>
<W msd="VLadj" lemma="desear">deseado</W>
<W msd="VLinf" lemma="incorporar">incorporar</W>
<W msd="DM" lemma="este">esta</W>
<W msd="NC" lemma="pregunta">pregunta</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="VLadj" lemma="tratar">tratado</W>
<W msd="CSUBX" lemma="como">como</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="pregunta">pregunta</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">interés</W>
<W msd="ADV" lemma="&lt;unknown&gt;">común</W>
<W msd="FS" lemma=".">.</W>
