<W msd="PREP" lemma="en">EN</W>
<W msd="ART" lemma="el">la</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">mayorÃ­a</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="institución">instituciones</W>
<W msd="ADJ" lemma="educativo">educativas</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="control">control</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="actividad">actividades</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="&lt;unknown&gt;">fÃ¡cil</W>
<W msd="CSUBI" lemma="de">de</W>
<W msd="VLinf" lemma="realizar">realizar</W>
<W msd="PREP" lemma="desde">desde</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="comienzo">comienzo</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">educaciÃ³n</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="si">Si</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="alumno">alumno</W>
<W msd="VLfin" lemma="participar">participa</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">enseÃ±anza</W>
<W msd="CM" lemma=",">,</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="tarea">tareas</W>
<W msd="CC" lemma="y">y</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="&lt;unknown&gt;">exÃ¡menes</W>
<W msd="CM" lemma=",">,</W>
<W msd="PPX" lemma="él">ello</W>
<W msd="VLfin" lemma="significar">significa</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="activo">activo</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="si">Si</W>
<W msd="NEG" lemma="no">no</W>
<W msd="CM" lemma=",">,</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="ADJ" lemma="inactivo">inactivo</W>
<W msd="FS" lemma=".">.</W>
<W msd="ADV" lemma="donde">DONDE</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="NC" lemma="asistencia">asistencia</W>
<W msd="ADJ" lemma="obligatorio">obligatoria</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADV" lemma="en~general">en general</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="NC" lemma="tarea">tareas</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VLfin" lemma="&lt;unknown&gt;">posibilitan</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="control">control</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="actividad">actividades</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="estudio">estudio</W>
<W msd="CM" lemma=",">,</W>
<W msd="CC" lemma="y">y</W>
<W msd="VHfin" lemma="haber">hay</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="desde">desde</W>
<W msd="ADV" lemma="luego">luego</W>
<W msd="CM" lemma=",">,</W>
<W msd="NC" lemma="&lt;unknown&gt;">exÃ¡menes</W>
<W msd="ADJ" lemma="parcial">parciales</W>
<W msd="PREP" lemma="en">en</W>
<W msd="QU" lemma="todo">todos</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="tipo">tipos</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">educaciÃ³n</W>
<W msd="FS" lemma=".">.</W>
<W msd="ART" lemma="el">El</W>
<W msd="NC" lemma="control">control</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="actividad">actividades</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="estudio">estudio</W>
<W msd="VSfin" lemma="ser">es</W>
<W msd="NC" lemma="responsabilidad">responsabilidad</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">los</W>
<W msd="NC" lemma="instituto">institutos</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">enseÃ±anza</W>
<W msd="FS" lemma=".">.</W>
<W msd="NEG" lemma="no">No</W>
<W msd="VLfin" lemma="tener">tengo</W>
<W msd="NC" lemma="&lt;unknown&gt;">ningÃºn</W>
<W msd="ADJ" lemma="motivo">motivo</W>
<W msd="CSUBI" lemma="para">para</W>
<W msd="VLinf" lemma="creer">creer</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VHfin" lemma="haber">haya</W>
<W msd="NC" lemma="institución">instituciones</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="NEG" lemma="no">no</W>
<W msd="VLfin" lemma="tomar">tomen</W>
<W msd="PREP" lemma="en">en</W>
<W msd="VLfin" lemma="seriar">serio</W>
<W msd="DM" lemma="este">esta</W>
<W msd="NC" lemma="tarea">tarea</W>
<W msd="FS" lemma=".">.</W>
<W msd="VSfin" lemma="ser">Es</W>
<W msd="ADJ" lemma="natural">natural</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="VHfin" lemma="haber">haya</W>
<W msd="NC" lemma="posibilidad">posibilidades</W>
<W msd="CSUBI" lemma="de">de</W>
<W msd="VLinf" lemma="hacer">hacer</W>
<W msd="NC" lemma="trampa">trampas</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="ORD" lemma="primero">primer</W>
<W msd="NC" lemma="&lt;unknown&gt;">aÃ±o</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">enseÃ±anza</W>
<W msd="FS" lemma=".">.</W>
<W msd="PREP" lemma="por">Por</W>
<W msd="DM" lemma="este">esto</W>
<W msd="VLfin" lemma="querer">quiero</W>
<W msd="VLinf" lemma="introducir">introducir</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="&lt;unknown&gt;">disposiciÃ³n</W>
<W msd="PREP" lemma="en~cuanto~a">en cuanto a</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="institución">instituciones</W>
<W msd="VMfin" lemma="deber">deben</W>
<W msd="VLinf" lemma="realizar">realizar</W>
<W msd="ART" lemma="el">el</W>
<W msd="ORD" lemma="primero">primer</W>
<W msd="NC" lemma="control">control</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="actividad">actividades</W>
<W msd="PREP" lemma="a">a</W>
<W msd="ART" lemma="el">los</W>
<W msd="CARD" lemma="6">6</W>
<W msd="NC" lemma="mes">meses</W>
<W msd="CM" lemma=",">,</W>
<W msd="PREP" lemma="a">a</W>
<W msd="NC" lemma="&lt;unknown&gt;">mÃ¡s</W>
<W msd="VLinf" lemma="tardar">tardar</W>
<W msd="CM" lemma=",">,</W>
<W msd="ADV" lemma="&lt;unknown&gt;">despuÃ©s</W>
<W msd="PDEL" lemma="del">del</W>
<W msd="NC" lemma="inicio">inicio</W>
<W msd="PREP" lemma="de">de</W>
<W msd="ART" lemma="el">la</W>
<W msd="NC" lemma="&lt;unknown&gt;">educaciÃ³n</W>
<W msd="FS" lemma=".">.</W>
<W msd="NP" lemma="&lt;unknown&gt;">JENS</W>
<W msd="NP" lemma="&lt;unknown&gt;">Sandfeld</W>
<W msd="NP" lemma="&lt;unknown&gt;">SÃ¸ndergaard</W>
<W msd="VLfin" lemma="destacar">destaca</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="ART" lemma="el">las</W>
<W msd="NC" lemma="regla">reglas</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NP" lemma="&lt;unknown&gt;">SU</W>
<W msd="VSfin" lemma="ser">son</W>
<W msd="ADV" lemma="tan">tan</W>
<W msd="ADJ" lemma="favorable">favorables</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="SE" lemma="se">se</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="recibir">recibir</W>
<W msd="PREP" lemma="de">de</W>
<W msd="CARD" lemma="@card@">3.198</W>
<W msd="PREP" lemma="hasta">hasta</W>
<W msd="CARD" lemma="@card@">38.376</W>
<W msd="VLfin" lemma="coronar">coronas</W>
<W msd="PAL" lemma="al">al</W>
<W msd="NC" lemma="&lt;unknown&gt;">aÃ±o</W>
<W msd="PREP" lemma="sin">sin</W>
<W msd="CCNEG" lemma="ni">ni</W>
<W msd="ADV" lemma="siquiera">siquiera</W>
<W msd="VCLI" lemma="presentarse">presentarse</W>
<W msd="PREP" lemma="en">en</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="establecimiento">establecimiento</W>
<W msd="ADJ" lemma="educativo">educativo</W>
<W msd="CC" lemma="y">y</W>
<W msd="PREP" lemma="sin">sin</W>
<W msd="VLinf" lemma="abrir">abrir</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="libro">libro</W>
<W msd="FS" lemma=".">.</W>
<W msd="CSUBX" lemma="como">Como</W>
<W msd="NC" lemma="ejemplo">ejemplo</W>
<W msd="SE" lemma="se">se</W>
<W msd="VLfin" lemma="citar">cita</W>
<W msd="CQUE" lemma="que">que</W>
<W msd="CM" lemma=",">,</W>
<W msd="CSUBX" lemma="si">si</W>
<W msd="ART" lemma="un">una</W>
<W msd="NC" lemma="persona">persona</W>
<W msd="VLfin" lemma="ganar">gana</W>
<W msd="CARD" lemma="@card@">300.000</W>
<W msd="NC" lemma="corona">coronas</W>
<W msd="PAL" lemma="al">al</W>
<W msd="NC" lemma="&lt;unknown&gt;">aÃ±o</W>
<W msd="CM" lemma=",">,</W>
<W msd="QU" lemma="dicho">dicha</W>
<W msd="NC" lemma="persona">persona</W>
<W msd="VMfin" lemma="poder">puede</W>
<W msd="VLinf" lemma="recibir">recibir</W>
<W msd="ART" lemma="el">el</W>
<W msd="NC" lemma="subsidio">subsidio</W>
<W msd="PREP" lemma="de">de</W>
<W msd="NC" lemma="&lt;unknown&gt;">educaciÃ³n</W>
<W msd="PREP" lemma="durante">durante</W>
<W msd="ART" lemma="un">un</W>
<W msd="NC" lemma="mes">mes</W>
<W msd="FS" lemma=".">.</W>
