<W lemma="el" msd="PD" tag="ART" in="" out="">La</W>
<W lemma="meta" msd="NC" tag="NC" in="" out="">meta</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="">es</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">además</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="poder" msd="VAF" tag="VMinf" in="" out="">poder</W>
<W lemma="absorber" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">absorber</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">el</W>
<W lemma="conocimiento" msd="NC" tag="NC" in="" out="">conocimiento</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="" out="">sobre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">conducción</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">técnica</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="" out="">también</W>
<W lemma="poder" msd="VAD" tag="VMfin" in="" out="">puedan</W>
<W lemma="aprovechar" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">aprovechar</W>
<W lemma="suyo" msd="PP" tag="PPO" in="" out="">su</W>
<W lemma="experiencia" msd="NC" tag="NC" in="" out="">experiencia</W>
<W lemma="en~cuanto~a" msd="SP" tag="SCENE" in="" out="">en cuanto a</W>
<W lemma="conseguir" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">conseguir</W>
<W lemma="dinero" msd="NC" tag="NC" in="" out="">dinero</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="patrocinador" msd="NC" tag="NC" in="" out="">patrocinadores</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="publicidad" msd="NC" tag="NC" in="" out="">publicidad</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="de~manera~que" msd="CS" tag="CSUBF" in="" out="">de manera que</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">interés</W>
<W lemma="por" msd="SP" tag="SCENE" in="" out="">por</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">la</W>
<W lemma="velocidad" msd="NC" tag="NC" in="" out="">velocidad</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">las</W>
<W lemma="carrera" msd="NC" tag="NC" in="" out="">carreras</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">también</W>
<W lemma="poder" msd="VAD" tag="VMfin" in="" out="">pueda</W>
<W lemma="funcionar" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">funcionar</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="" out="">económicamente</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="">“La</W>
<W lemma="meta" msd="NC" tag="NC" in="" out="">meta</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="">es</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">las</W>
<W lemma="clase" msd="NC" tag="NC" in="" out="">clases</W>
<W lemma="superior" msd="AN" tag="ADJ" in="" out="">superiores</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">las</W>
<W lemma="carrera" msd="NC" tag="NC" in="" out="">carreras</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="moto" msd="NC" tag="NC" in="" out="">motos</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="">en</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="" out="">Dinamarca</W>
<W lemma="recibir" msd="VAD" tag="VLfin" in="" out="">reciban</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="" out="">nuevos</W>
<W lemma="talento" msd="NC" tag="NC" in="" out="">talentos</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="" out="">también</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="">en</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">años</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="" out="">venideros</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">Y</W>
<W lemma="este" msd="" tag="DM" in="" out="">esto</W>
<W lemma="ocurrir" msd="VAD" tag="VLfin" in="" out="">ocurre</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">sólo</W>
<W lemma="si" msd="CS" tag="CSUBX" in="" out="">si</W>
<W lemma="nosotros" msd="PP" tag="PPX" in="" out="">nosotros</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="">“los</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">veteranos”</W>
<W lemma="hacer" msd="VAD" tag="VLfin" in="" out="">hacemos</W>
<W lemma="un" msd="PD" tag="ART" in="" out="">un</W>
<W lemma="esfuerzo" msd="NC" tag="NC" in="" out="">esfuerzo</W>
<W lemma="activo" msd="AN" tag="ADJ" in="" out="">activo</W>
<W lemma="para" msd="CS" tag="CSUBI" in="" out="">para</W>
<W lemma="atrapar" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">atrapar</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">interés</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">jóvenes</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="yo" msd="PP" tag="PPX" in="" out="">Yo</W>
<W lemma="mismo" msd="AN" tag="ADJ" in="" out="">mismo</W>
<W lemma="haber" msd="VAD" tag="VLfin" in="" out="">he</W>
<W lemma="ser" msd="VAF" tag="VS" in="" out="">sido</W>
<W lemma="tan" msd="RG" tag="ADV" in="" out="">tan</W>
<W lemma="afortunar" msd="VAF" tag="VLadj" in="" out="">afortunado</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="con" msd="SP" tag="SCENE" in="" out="">con</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">la</W>
<W lemma="ayuda" msd="NC" tag="NC" in="" out="">ayuda</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Yamaha</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Enghave</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Motor</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="poder" msd="VAD" tag="VLfin" in="" out="">puedo</W>
<W lemma="ofrecer" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">ofrecer</W>
<W lemma="un" msd="PD" tag="ART" in="" out="">un</W>
<W lemma="equipo" msd="NC" tag="NC" in="" out="">equipo</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="">a</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">disposición</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">los</W>
<W lemma="dos" msd="AC" tag="CARD" in="" out="">dos</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">“aprendices”</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">Y</W>
<W lemma="ambo" msd="AN" tag="QU" in="" out="">ambos</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">están</W>
<W lemma="lleno" msd="AN" tag="ADJ" in="" out="">llenos</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="empujar" msd="VAD" tag="VLfin" in="" out="">empuje</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="tener" msd="VAD" tag="VLfin" in="" out="">tienen</W>
<W lemma="grande" msd="AN" tag="ADJ" in="" out="">grandes</W>
<W lemma="ambicin" msd="NC" tag="NC" in="" out="">ambiciones</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="lamentable" msd="RG" tag="ADV" in="" out="">Lamentablemente</W>
<W lemma="no" msd="U=" tag="NEG" in="" out="">no</W>
<W lemma="poder" msd="VAD" tag="VLfin" in="" out="">puedo</W>
<W lemma="dar" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">dar</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">garantías</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="tener" msd="VAD" tag="VLfin" in="" out="">tengan</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">éxito</W>
<W lemma="con" msd="SP" tag="SCENE" in="" out="">con</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">los</W>
<W lemma="dos" msd="AC" tag="CARD" in="" out="">dos</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="" out="">80-cúbicos</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="pero" msd="CC" tag="CCAD" in="" out="">pero</W>
<W lemma="de~hecho" msd="RG" tag="ADV" in="" out="">de hecho</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="">haré</W>
<W lemma="todo" msd="AN" tag="QU" in="" out="">todo</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">lo</W>
<W lemma="posible" msd="AN" tag="ADJ" in="" out="">posible</W>
<W lemma="para" msd="CS" tag="CSUBI" in="" out="">para</W>
<W lemma="apoyar" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">apoyarlos</W>
<W lemma="y" msd="CC" tag="CC" in="" out="">y</W>
<W lemma="&lt;unknown&gt;" msd="VAF lexical verb infinite" tag="VLinf" in="" out="">entrenarlos</W>
<W lemma="," msd="XP" tag="CM" in="" out="">,</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="tal" msd="AN" tag="QU" in="" out="">tal</W>
<W lemma="modo" msd="NC" tag="NC" in="" out="">modo</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="suyo" msd="PP" tag="PPO" in="" out="">su</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">interés</W>
<W lemma="por" msd="SP" tag="SCENE" in="" out="">por</W>
<W lemma="el" msd="PD" tag="ART" in="" out="">las</W>
<W lemma="carrera" msd="NC" tag="NC" in="" out="">carreras</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="moto" msd="NC" tag="NC" in="" out="">motos</W>
<W lemma="no" msd="U=" tag="NEG" in="" out="">no</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="" out="">desaparezca,”</W>
<W lemma="decir" msd="VAD" tag="VLfin" in="" out="">dice</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Claus</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Wulff</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
