<W lemma="el" msd="PD" tag="ART" in="5:dobj|15:subj" out="">Lo</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="el" msd="PD" tag="ART" in="3:subj" out="1:nobj">el</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:nobj" out="1:attrr#">partido</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attrr#" out="">socialdemócrata</W>
<W lemma="pensar" msd="VAD" tag="VLfin" in="" out="-5:dobj|-3:subj|1:pobj|3:time">piensa</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">sobre</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="-3:time" out="1:pobj">después</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj" out="1:nobj">del</W>
<W lemma="no" msd="U=" tag="NEG" in="-1:nobj" out="1:pobj">no</W>
<W lemma="a" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">a</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="comunidad" msd="NC" tag="NC" in="-1:nobj" out="">Comunidad</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Europea</W>
<W lemma="depender" msd="VAD" tag="VLfin" in="" out="-15:subj|1:pobj|7:pnct">depende</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="persona" msd="NC" tag="NC" in="-1:nobj" out="1:ref|3:relr">persona</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:ref|2:dobj" out="">que</W>
<W lemma="se" msd="PC" tag="SE" in="1:subj" out="">se</W>
<W lemma="pregunta" msd="NC" tag="NC" in="-3:relr" out="-1:subj|-2:dobj">pregunta</W>
<W lemma="." msd="XP" tag="FS" in="-7:pnct" out="">.</W>
<W lemma="el" msd="PD" tag="ART" in="2:subj" out="1:nobj">El</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:nobj" out="">partido</W>
<W lemma="tener" msd="VAD" tag="VLfin" in="" out="-2:subj|2:dobj|6:pnct">tiene</W>
<W lemma="mucho" msd="AN" tag="QU" in="1:ext" out="">muchos</W>
<W lemma="punto" msd="NC" tag="NC" in="-2:dobj" out="-1:ext|1:pobj&3a;other#">puntos</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj&3a;other#" out="1:nobj">de</W>
<W lemma="vista" msd="NC" tag="NC" in="-1:nobj" out="1:attr">vista</W>
<W lemma="interesante" msd="AN" tag="ADJ" in="-1:attr" out="">interesantes</W>
<W lemma="." msd="XP" tag="FS" in="-6:pnct" out="">.</W>
<W lemma="en" msd="SP" tag="SCENE" in="12:loc" out="1:nobj|2:pnct">En</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Christiansborg</W>
<W lemma="," msd="XP" tag="CM" in="-2:pnct" out="">,</W>
<W lemma="el" msd="PD" tag="ART" in="9:subj" out="2:nobj|7:appr">el</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="">nuevo</W>
<W lemma="presidente" msd="NC" tag="NC" in="-2:nobj" out="-1:attr|1:pobj|1:{arg}">presidente</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:nobj" out="">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="2:namef" out="">Poul</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namel" out="">Nyrup</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-7:appr" out="-2:namef|-1:namel">Rasmussen</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="unir" msd="VAD" tag="VLfin" in="" out="-12:loc|-9:subj|-1:robj|1:pobj|6:vobj|27:pnct">une</W>
<W lemma="al" msd="SP" tag="PAL" in="-1:pobj" out="1:nobj">al</W>
<W lemma="punto" msd="NC" tag="NC" in="-1:nobj" out="1:pobj&3a;other">punto</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj&3a;other" out="1:nobj">de</W>
<W lemma="vista" msd="NC" tag="NC" in="-1:nobj" out="1:attr">vista</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attr" out="">“oficial”</W>
<W lemma="decir" msd="VAF" tag="VLadj" in="-6:vobj" out="1:dobj">diciendo</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:dobj" out="2:vobj">que</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="deber" msd="VAD" tag="VLfin" in="-2:vobj" out="-1:neg|1:vobj|4:time">debemos</W>
<W lemma="proponer" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">proponer</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">solución</W>
<W lemma="antes" msd="RG" tag="ADV" in="-4:time" out="1:pobj">antes</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj" out="">de</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="1:vobj">que</W>
<W lemma="haber" msd="VAD" tag="VLfin" in="-1:vobj" out="1:vobj">hayamos</W>
<W lemma="ver" msd="VAF" tag="VLadj" in="-1:vobj" out="1:dobj">visto</W>
<W lemma="si" msd="CS" tag="CSUBX" in="-1:dobj" out="4:vobj">si</W>
<W lemma="Francia" msd="NP" tag="NP" in="3:subj" out="2:conj">Francia</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">e</W>
<W lemma="Inglaterra" msd="NP" tag="NP" in="-2:conj" out="-1:coord">Inglaterra</W>
<W lemma="aprobar" msd="VAD" tag="VLfin" in="-4:vobj" out="-3:subj|1:dobj">aprueben</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Tratado</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Maastricht</W>
<W lemma="." msd="XP" tag="FS" in="-27:pnct" out="">.</W>
<W lemma="un" msd="PD" tag="ART" in="" out="1:nobj">Un</W>
<W lemma="punto" msd="NC" tag="NC" in="-1:nobj" out="1:pobj&3a;other#|6:ref|7:relr">punto</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj&3a;other#" out="1:nobj">de</W>
<W lemma="vista" msd="NC" tag="NC" in="-1:nobj" out="1:attr|2:attr|2:{about}">vista</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-1:attr" out="">táctico</W>
<W lemma="de" msd="SP" tag="SCENE" in="-2:attr|-2:{about}" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">negociación</W>
<W lemma="que" msd="CS" tag="CQUE" in="-6:ref|1:subj" out="">que</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="-7:relr" out="-1:subj|1:preds|7:pnct">es</W>
<W lemma="compartir" msd="VAF" tag="VLadj" in="-1:preds" out="1:pobj">compartido</W>
<W lemma="por" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">por</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">partidos</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="gobierno" msd="NC" tag="NC" in="-1:nobj" out="">gobierno</W>
<W lemma="." msd="XP" tag="FS" in="-7:pnct" out="">.</W>
<W lemma="en" msd="SP" tag="SCENE" in="6:loc" out="1:nobj">En</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="">Det</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Fri</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Aktuelt</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Ritt</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:subj" out="-1:namef">Bjerregaard</W>
<W lemma="exhortar" msd="VAD" tag="VLfin" in="" out="-6:loc|-1:subj|1:pobj">exhorta</W>
<W lemma="a" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">a</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="2:nobj">un</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="">nuevo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-2:nobj" out="-1:attr">referéndum</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="" out="">sobre</W>
<W lemma="algo" msd="AN" tag="QU" in="" out="">algo</W>
<W lemma="que" msd="CS" tag="CQUE" in="" out="">que</W>
<W lemma="se" msd="PC" tag="SE" in="" out="">se</W>
<W lemma="parecer" msd="VAD" tag="VLfin" in="" out="">parece</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="">a</W>
<W lemma="un" msd="PD" tag="ART" in="" out="">un</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="" out="">Tratado</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Maastricht</W>
<W lemma="." msd="XP" tag="FS" in="" out="">.</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">No</W>
<W lemma="pensar" msd="VAD" tag="VLfin" in="" out="-1:neg|1:vobj|8:pnct|9:cause|15:pnct">piensa</W>
<W lemma="tomar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">tomar</W>
<W lemma="nota" msd="NC" tag="NC" in="-1:dobj" out="1:pobj">nota</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="resultado" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">resultados</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">referéndum</W>
<W lemma="," msd="XP" tag="CM" in="-8:pnct" out="">,</W>
<W lemma="porque" msd="CS" tag="CSUBX" in="-9:cause" out="2:vobj">porque</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="-2:vobj" out="-1:neg|1:dobj">hay</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr">solución</W>
<W lemma="intermedio" msd="AN" tag="ADJ" in="-1:attr" out="">intermedia</W>
<W lemma="." msd="XP" tag="FS" in="-15:pnct" out="">.</W>
<W lemma="o" msd="CC" tag="CC" in="4:correl|8:dobj" out="7:pnct">O</W>
<W lemma="estar" msd="VAD" tag="VLfin" in="" out="1:loc|2:pnct|4:conj">estamos</W>
<W lemma="fuera" msd="RG" tag="ADV" in="-1:loc" out="">fuera</W>
<W lemma="," msd="XP" tag="CM" in="-2:pnct" out="">,</W>
<W lemma="o" msd="CC" tag="CC" in="1:coord" out="-4:correl">o</W>
<W lemma="estar" msd="VAD" tag="VLfin" in="-4:conj" out="-1:coord|1:loc">estamos</W>
<W lemma="dentro" msd="RG" tag="ADV" in="-1:loc" out="">dentro</W>
<W lemma="," msd="XP" tag="CM" in="-7:pnct" out="">,</W>
<W lemma="opinar" msd="VAD" tag="VLfin" in="" out="-8:dobj|1:subj|5:pnct">opina</W>
<W lemma="el" msd="PD" tag="ART" in="-1:subj" out="1:nobj">la</W>
<W lemma="Seora" msd="NP" tag="NP" in="-1:nobj" out="1:pnct|2:nobj">Sra</W>
<W lemma="." msd="XP" tag="FS" in="-1:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-2:nobj" out="">Bjerregaard</W>
<W lemma="." msd="XP" tag="FS" in="-5:pnct" out="">.</W>
<W lemma="un" msd="PD" tag="ART" in="14:subj" out="1:nobj|4:pnct|5:appa|13:pnct">Un</W>
<W lemma="tercero" msd="AO" tag="ORD" in="-1:nobj" out="1:nobj">tercer</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr">socialdemócrata</W>
<W lemma="prominente" msd="AN" tag="ADJ" in="-1:attr" out="">prominente</W>
<W lemma="," msd="XP" tag="CM" in="-4:pnct" out="">,</W>
<W lemma="el" msd="PD" tag="ART" in="-5:appa" out="3:nobj|7:appr">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="2:attr" out="">destronado</W>
<W lemma="ex" msd="AN" tag="ADJ" in="" out="">ex</W>
<W lemma="presidente" msd="NC" tag="NC" in="-3:nobj" out="-2:attr|1:pobj|1:{arg}">presidente</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="partido" msd="NC" tag="NC" in="-1:nobj" out="">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="">Svend</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-7:appr" out="-1:namef">Auken</W>
<W lemma="," msd="XP" tag="CM" in="-13:pnct" out="">,</W>
<W lemma="contribuir" msd="VAD" tag="VLfin" in="" out="-14:subj|1:pobj|7:loc|15:pnct">contribuye</W>
<W lemma="con" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">con</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="tercero" msd="AO" tag="ORD" in="-1:nobj" out="1:nobj">tercer</W>
<W lemma="punto" msd="NC" tag="NC" in="-1:nobj" out="1:pobj&3a;other#">punto</W>
<W lemma="de" msd="SP" tag="SCENE" in="-1:pobj&3a;other#" out="1:nobj">de</W>
<W lemma="vista" msd="NC" tag="NC" in="-1:nobj" out="">vista</W>
<W lemma="en" msd="SP" tag="SCENE" in="-7:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|5:appr|8:coref-prg">la</W>
<W lemma="revista" msd="NC" tag="NC" in="-1:nobj" out="1:pobj|1:{arg}">revista</W>
<W lemma="del" msd="SP" tag="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="parlamento" msd="NC" tag="NC" in="-1:nobj" out="1:attr">parlamento</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:attr" out="">inglés</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-5:appr" out="">Parliamentary</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Brief</W>
<W lemma="." msd="XP" tag="FS" in="-15:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="-8:coref-prg" out="1:pnct">Aquí</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="1:subj" out="">él</W>
<W lemma="considerar" msd="VAD" tag="VLfin" in="" out="-1:subj|2:dobj|8:man|13:pnct">considera</W>
<W lemma="todo" msd="AN" tag="QU" in="1:ext" out="">todas</W>
<W lemma="el" msd="PD" tag="ART" in="-2:dobj" out="-1:ext|1:nobj">las</W>
<W lemma="especulacin" msd="NC" tag="NC" in="-1:nobj" out="1:pobj">especulaciones</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="-1:pobj" out="1:nobj">sobre</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="2:nobj">un</W>
<W lemma="nuevo" msd="AN" tag="ADJ" in="1:attr" out="">nuevo</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-2:nobj" out="-1:attr">referéndum</W>
<W lemma="como" msd="RG" tag="ADV" in="-8:man" out="1:nobj">como</W>
<W lemma="casto" msd="AN" tag="ADJ" in="-1:nobj" out="1:loc">castillos</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="aire" msd="NC" tag="NC" in="-1:nobj" out="">aire</W>
<W lemma="." msd="XP" tag="FS" in="-13:pnct" out="">.</W>
<W lemma="porque" msd="CS" tag="CSUBX" in="" out="">Porque</W>
<W lemma="&3a;" msd="XP" tag="COLON" in="" out="">:</W>
<W lemma="el" msd="PD" tag="ART" in="3:subj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:attr">referéndum</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:attr" out="">danés</W>
<W lemma="ser" msd="VAD" tag="VSfin" in="" out="-3:subj|2:preds|9:conj|18:pnct">es</W>
<W lemma="&lt;unknown&gt;" msd="RG" tag="ADV" in="1:man" out="">jurídicamente</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="-2:preds" out="-1:man">vinculante</W>
<W lemma="y" msd="CC" tag="CC" in="6:coord" out="">y</W>
<W lemma="," msd="XP" tag="CM" in="1:pnct" out="">,</W>
<W lemma="en~consecuencia" msd="RG" tag="ADV" in="4:cause" out="-1:pnct|1:pnct">en consecuencia</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="2:subj" out="">Dinamarca</W>
<W lemma="no" msd="U=" tag="NEG" in="1:neg" out="">no</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="-9:conj" out="-4:cause|-2:subj|-1:neg|-6:coord|1:loc???">está</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:loc???" out="1:nobj">en</W>
<W lemma="condicin" msd="NC" tag="NC" in="-1:nobj" out="1:pobj">condiciones</W>
<W lemma="de" msd="CS" tag="CSUBI" in="-1:pobj" out="1:vobj">de</W>
<W lemma="ratificar" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">ratificar</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Tratado</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="">de</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="">Maastricht</W>
<W lemma="." msd="XP" tag="FS" in="-18:pnct" out="">.</W>
