<W lemma="cuando" msd="CSUBX" in="10:time" out="5:vobj">CUANDO</W>
<W lemma="el" msd="ART" in="4:subj" out="1:nobj">el</W>
<W lemma="partido" msd="NC" in="-1:nobj" out="1:nobj">partido</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">Socialdemócrata</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-5:vobj" out="-4:subj|-1:robj|1:time">rindió</W>
<W lemma="en" msd="PREP" in="-1:time" out="1:nobj">en</W>
<W lemma="septiembre" msd="NC" in="-1:nobj" out="1:pobj&3a;time">septiembre</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;time" out="1:nobj">de</W>
<W lemma="@card@" msd="CODE" in="-1:nobj" out="">1982</W>
<W lemma="ser" msd="VSfin" in="" out="-10:time|1:struct|4:pobj">fue</W>
<W lemma="en" msd="PREP" in="-1:struct" out="2:nobj">en</W>
<W lemma="grande" msd="ADJ" in="1:attr" out="">gran</W>
<W lemma="medida" msd="NC" in="-2:nobj" out="-1:attr">medida</W>
<W lemma="por" msd="PREP" in="-4:pobj" out="1:nobj">por</W>
<W lemma="cuestin" msd="NC" in="-1:nobj" out="1:attr">cuestiones</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">estratégicas</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="con" msd="PREP" in="" out="">Con</W>
<W lemma="el" msd="ART" in="" out="">la</W>
<W lemma="esperanza" msd="NC" in="" out="">esperanza</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="volver" msd="VLinf" in="" out="">volver</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="formar" msd="VLinf" in="" out="">formar</W>
<W lemma="gobernar" msd="VLfin" in="" out="">gobierno</W>
<W lemma="cuando" msd="CSUBX" in="" out="">cuando</W>
<W lemma="el" msd="ART" in="" out="">el</W>
<W lemma="gobierno" msd="NC" in="" out="">gobierno</W>
<W lemma="actual" msd="ADJ" in="" out="">actual</W>
<W lemma="del" msd="PDEL" in="" out="">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="" out="">trébol</W>
<W lemma="de" msd="PREP" in="" out="">de</W>
<W lemma="cuatro" msd="CARD" in="" out="">cuatro</W>
<W lemma="hoja" msd="NC" in="" out="">hojas</W>
<W lemma="quedar" msd="VLfin" in="" out="">quedara</W>
<W lemma="atascar" msd="VLadj" in="" out="">atascado</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="pero" msd="CCAD" in="1:diskmark" out="">PERO</W>
<W lemma="ser" msd="VSfin" in="" out="-1:diskmark|1:ext|4:preds|11:pnct">fue</W>
<W lemma="un" msd="ART" in="-1:ext" out="1:nobj">una</W>
<W lemma="vez" msd="NC" in="-1:nobj" out="1:degr">vez</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:degr" out="">más</W>
<W lemma="un" msd="ART" in="-4:preds" out="1:nobj">un</W>
<W lemma="error" msd="NC" in="-1:nobj" out="1:attr|2:pobj">error</W>
<W lemma="fatal" msd="ADJ" in="-1:attr" out="">fatal</W>
<W lemma="por~parte~de" msd="PREP" in="-2:pobj" out="1:nobj">por parte de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attr">líderes</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">políticos</W>
<W lemma="." msd="FS" in="-11:pnct" out="">.</W>
<W lemma="el" msd="ART" in="8:subj" out="1:nobj">EL</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="1:pobj&3a;resem">GOBIERNO</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:pobj&3a;resem" out="1:nobj">DEL</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="1:pobj|1:{arg}">TRÉBOL</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:pobj|-1:{arg}" out="1:nobj">DE</W>
<W lemma="cuatro" msd="CARD" in="-1:nobj" out="1:nobj">CUATRO</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">HOJAS</W>
<W lemma="no" msd="NEG" in="1:neg" out="">no</W>
<W lemma="era" msd="VEfin" in="" out="-8:subj|-1:neg|1:preds|3:pnct">era</W>
<W lemma="un" msd="ART" in="-1:preds" out="1:nobj">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">efímera</W>
<W lemma="." msd="FS" in="-3:pnct" out="">.</W>
<W lemma="bajo" msd="PREP" in="4:loc&3a;met" out="2:nobj">Bajo</W>
<W lemma="determinado" msd="ADJ" in="1:attr" out="">determinadas</W>
<W lemma="circunstancia" msd="NC" in="-2:nobj" out="-1:attr">circunstancias</W>
<W lemma="&lt;unknown&gt;" msd="ADV" in="1:prg" out="">aún</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-1:prg|-4:loc&3a;met|1:vobj|6:time|9:pnct">podría</W>
<W lemma="haber" msd="VHinf" in="-1:vobj" out="1:vobj">haber</W>
<W lemma="estado" msd="NC" in="-1:vobj" out="1:loc&3a;met">estado</W>
<W lemma="en" msd="PREP" in="-1:loc&3a;met" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="poder" msd="NC" in="-1:nobj" out="">poder</W>
<W lemma="hoy" msd="ADV" in="-6:time" out="1:nobj">hoy</W>
<W lemma="en" msd="PREP" in="-1:nobj" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:nobj" out="">día</W>
<W lemma="." msd="FS" in="-9:pnct" out="">.</W>
<W lemma="tampoco" msd="ADV" in="2:neg" out="">Tampoco</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="poder" msd="VMfin" in="" out="-1:robj|-2:neg|1:vobj|9:pnct">puede</W>
<W lemma="descartar" msd="VLinf" in="-1:vobj" out="1:dobj">descartar</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">la</W>
<W lemma="idea" msd="NC" in="-1:nobj" out="1:pobj">idea</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="que" msd="CQUE" in="-1:nobj" out="1:vobj">que</W>
<W lemma="poder" msd="VMfin" in="-1:vobj" out="1:vobj|2:time">pueda</W>
<W lemma="surgir" msd="VLinf" in="-1:vobj" out="">surgir</W>
<W lemma="de~nuevo" msd="ADV" in="-2:time" out="">de nuevo</W>
<W lemma="." msd="FS" in="-9:pnct" out="">.</W>
<W lemma="&lt;unknown&gt;" msd="ADV" in="2:subj" out="">¿Quién</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="atrever" msd="VLfin" in="" out="-2:subj|-1:robj|2:vobj">atreve</W>
<W lemma="a" msd="PREP" in="" out="">a</W>
<W lemma="descartar" msd="VLinf" in="-2:vobj" out="1:dobj">descartar</W>
<W lemma="l" msd="PPO" in="-1:dobj" out="">lo</W>
<W lemma="?" msd="FS" in="" out="">?</W>
<W lemma="en~todo~caso" msd="ADV" in="4:struct" out="">En todo caso</W>
<W lemma="," msd="CM" in="" out="">,</W>
<W lemma="suyo" msd="PPO" in="" out="">su</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="1:subj" out="">formación</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="" out="-4:struct|-1:subj|1:preds">significó</W>
<W lemma="el" msd="ART" in="-1:preds" out="1:nobj">el</W>
<W lemma="comienzo" msd="NC" in="-1:nobj" out="1:pobj.dobj|1:{patient}|61:fpredo">comienzo</W>
<W lemma="de" msd="PREP" in="-1:pobj.dobj|-1:{patient}" out="1:nobj">de</W>
<W lemma="un" msd="ART" in="-1:nobj" out="2:nobj">una</W>
<W lemma="nuevo" msd="ADJ" in="1:attr" out="">nueva</W>
<W lemma="fase" msd="NC" in="-2:nobj" out="-1:attr|1:loc&3a;met">fase</W>
<W lemma="en" msd="PREP" in="-1:loc&3a;met" out="1:nobj">en</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj|3:time">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attr">política</W>
<W lemma="dans" msd="ADJ" in="-1:attr" out="">danesa</W>
<W lemma="&lt;unknown&gt;" msd="ADV" in="-3:time" out="1:pobj&3a;time">después</W>
<W lemma="de" msd="PREP" in="-1:pobj&3a;time" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">Segunda</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="" out="">Guerra</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="" out="">Mundial</W>
<W lemma="." msd="FS" in="" out="">.</W>
<W lemma="el" msd="ART" in="4:subj" out="1:nobj">EL</W>
<W lemma="Jefe" msd="NP" in="-1:nobj" out="1:pobj|1:{arg}#">JEFE</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:pobj|-1:{arg}#" out="1:nobj">DE</W>
<W lemma="&lt;unknown&gt;" msd="NP" in="-1:nobj" out="">GOBIERNO</W>
<W lemma="tener" msd="VLfin" in="" out="-4:subj|2:dobj|5:other|6:pnct|9:conj|16:pnct">tiene</W>
<W lemma="bueno" msd="ADJ" in="1:attr" out="">buena</W>
<W lemma="parte" msd="NC" in="-2:dobj" out="-1:attr|1:pobj|1:{arg}">parte</W>
<W lemma="del" msd="PDEL" in="-1:pobj|-1:{arg}" out="1:nobj">del</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">mérito</W>
<W lemma="al~respecto" msd="ADV" in="-5:other" out="">al respecto</W>
<W lemma="," msd="CM" in="-6:pnct" out="">,</W>
<W lemma="pero" msd="CCAD" in="2:coord" out="">pero</W>
<W lemma="&lt;unknown&gt;" msd="ADV" in="1:diskmark" out="">también</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-9:conj" out="-2:coord|-1:diskmark|1:vobj">deberían</W>
<W lemma="mencionar" msd="VLinf" in="-1:vobj" out="1:subj">mencionarse</W>
<W lemma="un" msd="ART" in="-1:subj" out="1:nobj">un</W>
<W lemma="par" msd="NC" in="-1:nobj" out="1:pobj|1:{arg}">par</W>
<W lemma="de" msd="PREP" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="otro" msd="QU" in="-1:nobj" out="1:nobj">otros</W>
<W lemma="aspecto" msd="NC" in="-1:nobj" out="">aspectos</W>
<W lemma="." msd="FS" in="-16:pnct" out="">.</W>
<W lemma="el" msd="ART" in="3:subj" out="1:nobj">LOS</W>
<W lemma="cuatro" msd="CARD" in="-1:nobj" out="1:nobj">cuatro</W>
<W lemma="partido" msd="NC" in="-1:nobj" out="">partidos</W>
<W lemma="estar" msd="VLfin" in="" out="-3:subj|1:preds|6:time|11:pnct">estaban</W>
<W lemma="de" msd="PREP" in="-1:preds" out="1:nobj">de</W>
<W lemma="acuerdo" msd="NC" in="-1:nobj" out="1:pobj">acuerdo</W>
<W lemma="en" msd="PREP" in="-1:pobj" out="1:nobj">en</W>
<W lemma="mucho" msd="QU" in="-1:nobj" out="1:nobj">muchas</W>
<W lemma="cosa" msd="NC" in="-1:nobj" out="8:coref-res">cosas</W>
<W lemma="cuando" msd="CSUBX" in="-6:time" out="2:vobj">cuando</W>
<W lemma="se" msd="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-2:vobj" out="-1:robj|1:subj">formó</W>
<W lemma="el" msd="ART" in="-1:subj" out="1:nobj">el</W>
<W lemma="gobierno" msd="NC" in="-1:nobj" out="">gobierno</W>
<W lemma="." msd="FS" in="-11:pnct" out="">.</W>
<W lemma="mucho" msd="QU" in="1:ext" out="">Mucho</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-8:coref-res" out="-1:ext|1:pobj">más</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="">lo</W>
<W lemma="que" msd="CQUE" in="" out="3:vobj">que</W>
<W lemma="suyo" msd="PPO" in="2:subj" out="1:nobj">sus</W>
<W lemma="opositor" msd="NC" in="-1:nobj" out="">opositores</W>
<W lemma="haber" msd="VLfin" in="-3:vobj" out="-2:subj|1:vobj|3:pnct">hubieran</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:vobj" out="">creído</W>
<W lemma="posible" msd="ADJ" in="-61:fpredo" out="">posible</W>
<W lemma="." msd="FS" in="-3:pnct" out="">.</W>
<W lemma="un" msd="ART" in="5:subj" out="1:nobj">Una</W>
<W lemma="causa" msd="NC" in="-1:nobj" out="1:attr|2:pobj">causa</W>
<W lemma="esencial" msd="ADJ" in="-1:attr" out="">esencial</W>
<W lemma="de" msd="PREP" in="-2:pobj" out="1:nobj">de</W>
<W lemma="este" msd="DM" in="-1:nobj" out="">esto</W>
<W lemma="era" msd="VEfin" in="" out="-5:subj|1:preds|39:pnct">era</W>
<W lemma="que" msd="CQUE" in="-1:preds" out="2:vobj">que</W>
<W lemma="todo" msd="QU" in="1:subj" out="">todos</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-2:vobj" out="-1:subj|1:dobj">teníamos</W>
<W lemma="un" msd="ART" in="-1:dobj" out="1:nobj">una</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="1:attr|2:pobj">sensación</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">intuitiva</W>
<W lemma="de" msd="PREP" in="-2:pobj" out="1:nobj">de</W>
<W lemma="que" msd="CQUE" in="-1:nobj" out="5:vobj">que</W>
<W lemma="el" msd="ART" in="4:subj" out="1:nobj">la</W>
<W lemma="supervivencia" msd="NC" in="-1:nobj" out="1:pobj.subj|1:{agent}">supervivencia</W>
<W lemma="del" msd="PDEL" in="-1:pobj.subj|-1:{agent}" out="1:nobj">del</W>
<W lemma="gobierno" msd="NC" in="-1:nobj" out="">gobierno</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-5:vobj" out="-4:subj|1:pobj">dependería</W>
<W lemma="de" msd="PREP" in="-1:pobj" out="1:cond">de</W>
<W lemma="si" msd="CSUBX" in="-1:cond" out="1:vobj">si</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-1:vobj" out="1:dobj">teníamos</W>
<W lemma="el" msd="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="coraje" msd="NC" in="-1:nobj" out="1:pobj">coraje</W>
<W lemma="para" msd="CSUBI" in="-1:pobj" out="1:vobj">para</W>
<W lemma="poner" msd="VLinf" in="-1:vobj" out="1:pobj|3:dobj">poner</W>
<W lemma="en" msd="PREP" in="-1:pobj" out="1:nobj">en</W>
<W lemma="juego" msd="NC" in="-1:nobj" out="">juego</W>
<W lemma="un" msd="ART" in="-3:dobj" out="1:nobj">unas</W>
<W lemma="propuesta" msd="NC" in="-1:nobj" out="2:attr|3:ref|4:relr">propuestas</W>
<W lemma="muy" msd="ADV" in="1:degr" out="">muy</W>
<W lemma="radical" msd="ADJ" in="-2:attr" out="-1:degr">radicales</W>
<W lemma="que" msd="CQUE" in="-3:ref|1:subj" out="">que</W>
<W lemma="&lt;unknown&gt;" msd="VLfin" in="-4:relr" out="-1:subj|1:man|2:dobj">cambiarían</W>
<W lemma="decisivo" msd="ADV" in="-1:man" out="">decisivamente</W>
<W lemma="el" msd="ART" in="-2:dobj" out="1:nobj|6:conj">las</W>
<W lemma="expectativa" msd="NC" in="-1:nobj" out="1:pobj|1:{arg}">expectativas</W>
<W lemma="de" msd="PREP" in="-1:pobj|-1:{arg}" out="1:nobj">de</W>
<W lemma="el" msd="ART" in="-1:nobj" out="1:nobj">la</W>
<W lemma="&lt;unknown&gt;" msd="NC" in="-1:nobj" out="">población</W>
<W lemma="y" msd="CC" in="1:coord" out="">y</W>
<W lemma="el" msd="ART" in="-6:conj" out="-1:coord|1:nobj">la</W>
<W lemma="vida" msd="NC" in="-1:nobj" out="1:attr">vida</W>
<W lemma="&lt;unknown&gt;" msd="ADJ" in="-1:attr" out="">económico-industrial</W>
<W lemma="." msd="FS" in="-39:pnct" out="">.</W>
