<p>
<s>
<W lemma="&quot;" msd="XP" tag="QT" in="1:pnct" out="">"</W>
<W lemma="vale" msd="NC" tag="NC" in="" out="-1:pnct|3:conj">Vale</W>
<W lemma="," msd="XP" tag="CM" in="2:pnct" out="">,</W>
<W lemma="nosotros" msd="PP" tag="PPX" in="1:iobj" out="">nos</W>
<W lemma="encontrar" msd="VAD" tag="VLfin" in="-3:conj" out="-2:pnct|-1:iobj|1:dobj|12:pnct">encontramos</W>
<W lemma="mañana" msd="NC" tag="NC" in="-1:dobj" out="">mañana</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">a</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">14:00</W>
<W lemma="hora" msd="NC" tag="NC" in="-1:nobj" out="">horas</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="lugar" msd="NC" tag="NC" in="-1:nobj" out="">lugar</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="siempre" msd="RG" tag="ADV" in="-1:nobj" out="">siempre</W>
<W lemma="&quot;" msd="XP" tag="QT" in="" out="">"</W>
<W lemma="." msd="XP" tag="FS" in="-12:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="4:subj" out="1:nobj">Crípticas</W>
<W lemma="conversación" msd="NC" tag="NC" in="-1:nobj" out="">conversaciones</W>
<W lemma="telefónico" msd="AN" tag="ADJ" in="" out="">telefónicas</W>
<W lemma="que" msd="CS" tag="CQUE" in="1:subj" out="">que</W>
<W lemma="estar" msd="VAD" tag="VLfin" in="" out="-4:subj|-1:subj|1:vobj|3:pnct">estaban</W>
<W lemma="ser" msd="VAG" tag="VSger" in="-1:vobj" out="1:vobj">siendo</W>
<W lemma="intervenir" msd="VAF" tag="VLadj" in="-1:vobj" out="3:conj">intervenidas</W>
<W lemma="," msd="XP" tag="CM" in="-3:pnct" out="">,</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="encuentro" msd="NC" tag="NC" in="-3:conj" out="-1:coord|1:time|7:pnct">encuentros</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:time" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="1:exem">tabernas</W>
<W lemma="entre" msd="SP" tag="SCENE" in="-1:exem" out="2:nobj|6:nobj">entre</W>
<W lemma="antiguo" msd="AN" tag="ADJ" in="" out="">antiguos</W>
<W lemma="criminal" msd="NC" tag="NC" in="-2:nobj" out="">criminales</W>
<W lemma="conocer" msd="VAF" tag="VLadj" in="" out="">conocidos</W>
<W lemma="," msd="XP" tag="CM" in="-7:pnct" out="">,</W>
<W lemma="que" msd="CS" tag="CQUE" in="3:subj" out="">que</W>
<W lemma="según" msd="SP" tag="SCENE" in="-6:nobj" out="1:nobj">según</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="acusar" msd="VAF" tag="VLadj" in="-1:nobj" out="-3:subj">acusado</W>
<W lemma="por" msd="SP" tag="SCENE" in="" out="1:nobj">por</W>
<W lemma="narcotráfico" msd="NC" tag="NC" in="-1:nobj" out="1:pnct">narcotráfico</W>
<W lemma="&quot;" msd="XP" tag="QT" in="-1:pnct" out="1:nobj">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-1:nobj" out="2:pnct|6:appr">Lonne</W>
<W lemma="&quot;" msd="XP" tag="QT" in="" out="">"</W>
<W lemma="," msd="XP" tag="CM" in="-2:pnct" out="">,</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="2:namef" out="">Leon</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="2:namef" out="">Erling</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="1:namef" out="-2:namef">Fristrup</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-6:appr" out="-2:namef|-1:namef|1:pnct|5:pnct">Jensen</W>
<W lemma="," msd="XP" tag="CM" in="-1:pnct" out="">,</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">44</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="," msd="XP" tag="CM" in="-5:pnct" out="">,</W>
<W lemma="sólo" msd="RG" tag="ADV" in="1:quant" out="">sólo</W>
<W lemma="tratar" msd="VAD" tag="VLfin" in="" out="-1:quant">trataban</W>
<W lemma="sobre" msd="SP" tag="SCENE" in="" out="1:nobj">sobre</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|9:conj">la</W>
<W lemma="posibilidad" msd="NC" tag="NC" in="-1:nobj" out="">posibilidad</W>
<W lemma="de" msd="CS" tag="CSUBI" in="" out="1:vobj">de</W>
<W lemma="&lt;unknown&gt;" msd="VAF lexical verb infinite" tag="VLinf" in="-1:vobj" out="1:dobj">conseguirle</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="kiosco" msd="NC" tag="NC" in="-1:nobj" out="">kiosco</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="salchicha" msd="NC" tag="NC" in="-1:nobj" out="">salchichas</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="un" msd="PD" tag="ART" in="-9:conj" out="-1:coord|1:nobj">un</W>
<W lemma="poner" msd="VAF" tag="VLadj" in="-1:nobj" out="1:pnct">puesto</W>
<W lemma="!" msd="XP" tag="FS" in="-1:pnct" out="">!</W>
</s>
</p>
<p>
<s>
<W lemma="este" msd="" tag="DM" in="1:subj" out="">Esto</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="" out="-1:subj">alegaba</W>
<W lemma="&quot;" msd="XP" tag="QT" in="" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="11:conj">Lonne</W>
<W lemma="&quot;" msd="XP" tag="QT" in="" out="">"</W>
<W lemma="ayer" msd="RG" tag="ADV" in="9:time" out="">ayer</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj|3:nobj|4:appr">la</W>
<W lemma="audiencia" msd="NC" tag="NC" in="-1:nobj" out="">Audiencia</W>
<W lemma="territorial" msd="AN" tag="ADJ" in="" out="">Territorial</W>
<W lemma="&lt;unknown&gt;" msd="AN" tag="ADJ" in="-3:nobj" out="">Østre</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="-4:appr" out="">Landsret</W>
<W lemma="," msd="XP" tag="CM" in="2:pnct" out="">,</W>
<W lemma="donde" msd="RG" tag="ADV" in="1:time" out="">donde</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="-11:conj" out="-9:time|-2:pnct|-1:time|1:vobj|30:pnct">ha</W>
<W lemma="ser" msd="VAF" tag="VS" in="-1:vobj" out="1:preds">sido</W>
<W lemma="acusar" msd="VAF" tag="VLadj" in="-1:preds" out="1:dobj|23:pnct">acusado</W>
<W lemma="como" msd="CS" tag="CSUBX" in="-1:dobj" out="1:nobj">como</W>
<W lemma="uno" msd="AC" tag="CARD" in="-1:nobj" out="">uno</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="cabeza" msd="NC" tag="NC" in="-1:nobj" out="">cabecillas</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">una</W>
<W lemma="liga" msd="NC" tag="NC" in="-1:nobj" out="">liga</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="danés" msd="NC" tag="NC" in="-1:nobj" out="1:nobj">daneses</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:nobj" out="1:vobj">que</W>
<W lemma="según" msd="CS" tag="CSUBF" in="-1:vobj" out="3:vobj">según</W>
<W lemma="el" msd="PD" tag="ART" in="2:subj" out="1:nobj">la</W>
<W lemma="policía" msd="NC" tag="NC" in="-1:nobj" out="">policía</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="-3:vobj" out="-2:subj|1:vobj">ha</W>
<W lemma="introducir" msd="VAF" tag="VLadj" in="-1:vobj" out="2:dobj">introducido</W>
<W lemma="clandestino" msd="RG" tag="ADV" in="1:quant" out="">clandestinamente</W>
<W lemma="kilo" msd="NC" tag="NC" in="-2:dobj" out="-1:quant">kilos</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="héroe" msd="NC" tag="NC" in="-1:nobj" out="">heroína</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Pattaya</W>
<W lemma="(" msd="XP" tag="LP" in="-23:pnct" out="">(</W>
<W lemma="Tailandia" msd="NP" tag="NP" in="" out="1:pnct">Tailandia</W>
<W lemma=")" msd="XP" tag="RP" in="-1:pnct" out="">)</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">a</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="." msd="XP" tag="FS" in="-30:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">A</W>
<W lemma="juicio" msd="NC" tag="NC" in="-1:nobj" out="">juicio</W>
<W lemma="del" msd="SP" tag="PDEL" in="" out="1:nobj|3:pnct|4:appa">del</W>
<W lemma="ministerio" msd="NC" tag="NC" in="-1:nobj" out="">ministerio</W>
<W lemma="fiscal" msd="AN" tag="ADJ" in="" out="">fiscal</W>
<W lemma="," msd="XP" tag="CM" in="-3:pnct" out="">,</W>
<W lemma="el" msd="PD" tag="ART" in="-4:appa" out="1:nobj">la</W>
<W lemma="serie" msd="NC" tag="NC" in="-1:nobj" out="">serie</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="conversación" msd="NC" tag="NC" in="-1:nobj" out="3:conj">conversaciones</W>
<W lemma="telefónico" msd="AN" tag="ADJ" in="" out="">telefónicas</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="reunión" msd="NC" tag="NC" in="-3:conj" out="-1:coord|1:pobj.subj">reuniones</W>
<W lemma="en" msd="SP" tag="SCENE" in="-1:pobj.subj" out="1:nobj">en</W>
<W lemma="octubre" msd="NC" tag="NMON" in="-1:nobj" out="2:conj">octubre</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="noviembre" msd="NC" tag="NMON" in="-2:conj" out="-1:coord|5:pnct|7:pnct|8:pnct">noviembre</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="@card@" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">1991</W>
<W lemma="revelar|reveler" msd="VAD" tag="VLfin" in="-1:nobj" out="1:dobj|25:pnct">revelan</W>
<W lemma="que" msd="CS" tag="CQUE" in="-1:dobj" out="">que</W>
<W lemma="&quot;" msd="XP" tag="QT" in="-5:pnct" out="">"</W>
<W lemma="&lt;unknown&gt;" msd="NP" tag="NP" in="" out="12:pnct">Lonne</W>
<W lemma="&quot;" msd="XP" tag="QT" in="-7:pnct" out="">"</W>
<W lemma="," msd="XP" tag="CM" in="-8:pnct" out="">,</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="colaboración" msd="NC" tag="NC" in="-1:nobj" out="">colaboración</W>
<W lemma="con" msd="SP" tag="SCENE" in="" out="1:nobj|19:conj">con</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="2:nobj|5:nobj">un</W>
<W lemma="antiguo" msd="AN" tag="ADJ" in="" out="">antiguo</W>
<W lemma="amigo" msd="AN" tag="ADJ" in="-2:nobj" out="">amigo</W>
<W lemma="y" msd="CC" tag="CC" in="2:coord" out="">y</W>
<W lemma="antiguo" msd="AN" tag="ADJ" in="" out="">antiguo</W>
<W lemma="contrabandista" msd="NC" tag="NC" in="-5:nobj" out="-2:coord">contrabandista</W>
<W lemma="," msd="XP" tag="CM" in="-12:pnct" out="">,</W>
<W lemma="ahora" msd="RG" tag="ADV" in="1:quant" out="">ahora</W>
<W lemma="propietario" msd="AN" tag="ADJ" in="" out="-1:quant">propietario</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="kiosco" msd="NC" tag="NC" in="-1:nobj" out="">kiosco</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="salchicha" msd="NC" tag="NC" in="-1:nobj" out="">salchichas</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Copenhague</W>
<W lemma="," msd="XP" tag="CM" in="-25:pnct" out="">,</W>
<W lemma="y" msd="CC" tag="CC" in="1:coord" out="">y</W>
<W lemma="con" msd="SP" tag="SCENE" in="-19:conj" out="-1:coord|1:nobj|4:conj|6:pnct|7:conj">con</W>
<W lemma="un" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">un</W>
<W lemma="danés" msd="NC" tag="NC" in="-1:nobj" out="">danés</W>
<W lemma="residente" msd="AN" tag="ADJ" in="" out="">residente</W>
<W lemma="en" msd="SP" tag="SCENE" in="-4:conj" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Pattaya</W>
<W lemma="," msd="XP" tag="CM" in="-6:pnct" out="">,</W>
<W lemma="planear" msd="VAD" tag="VLfin" in="-7:conj" out="1:dobj|7:pnct">planearon</W>
<W lemma="el" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">el</W>
<W lemma="contrabando" msd="NC" tag="NC" in="-1:nobj" out="">contrabando</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="héroe" msd="NC" tag="NC" in="-1:nobj" out="">heroína</W>
<W lemma="desde" msd="SP" tag="SCENE" in="" out="1:nobj">desde</W>
<W lemma="Tailandia" msd="NP" tag="NP" in="-1:nobj" out="">Tailandia</W>
<W lemma="." msd="XP" tag="FS" in="-7:pnct" out="">.</W>
</s>
</p>
<p>
<s>
<W lemma="el" msd="PD" tag="ART" in="13:subj" out="1:nobj">El</W>
<W lemma="danés" msd="NC" tag="NC" in="-1:nobj" out="">danés</W>
<W lemma="residente" msd="AN" tag="ADJ" in="" out="">residente</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">el</W>
<W lemma="extranjero" msd="NC" tag="NC" in="-1:nobj" out="">extranjero</W>
<W lemma="con" msd="SP" tag="SCENE" in="" out="1:nobj">con</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">propensión</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">a</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="joya" msd="NC" tag="NC" in="-1:nobj" out="">joyas</W>
<W lemma="de" msd="SP" tag="SCENE" in="" out="1:nobj">de</W>
<W lemma="oro" msd="NC" tag="NC" in="-1:nobj" out="">oro</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-13:subj|1:vobj|6:time|9:pnct">ha</W>
<W lemma="llevar" msd="VAF" tag="VLadj" in="-1:vobj" out="1:dobj">llevado</W>
<W lemma="un" msd="PD" tag="ART" in="-1:dobj" out="1:nobj">un</W>
<W lemma="bar" msd="NC" tag="NC" in="-1:nobj" out="">bar</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="&lt;unknown&gt;" msd="NC" tag="NC" in="-1:nobj" out="">Pattaya</W>
<W lemma="durante" msd="SP" tag="SCENE" in="-6:time" out="1:nobj">durante</W>
<W lemma="mucho" msd="AN" tag="QU" in="-1:nobj" out="1:nobj">muchos</W>
<W lemma="año" msd="NC" tag="NC" in="-1:nobj" out="">años</W>
<W lemma="." msd="XP" tag="FS" in="-9:pnct" out="">.</W>
</s>
<s>
<W lemma="pero" msd="CC" tag="CCAD" in="9:discmark" out="3:relr">Pero</W>
<W lemma="ahora" msd="RG" tag="ADV" in="2:time" out="">ahora</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="encontrar" msd="VAD" tag="VLfin" in="-3:relr" out="-2:time|-1:robj">encuentra</W>
<W lemma="entre" msd="SP" tag="SCENE" in="" out="1:nobj">entre</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">los</W>
<W lemma="tres" msd="AC" tag="CARD" in="-1:nobj" out="1:nobj">tres</W>
<W lemma="danés" msd="NC" tag="NC" in="-1:nobj" out="">daneses</W>
<W lemma="que" msd="CS" tag="CQUE" in="1:subj" out="">que</W>
<W lemma="haber" msd="VAD" tag="VHfin" in="" out="-9:discmark|-1:subj|1:vobj|2:time">han</W>
<W lemma="viajar" msd="VAF" tag="VLadj" in="-1:vobj" out="2:iobj">viajado</W>
<W lemma="voluntario" msd="RG" tag="ADV" in="-2:time" out="">voluntariamente</W>
<W lemma="a" msd="SP" tag="SCENE" in="-2:iobj" out="1:nobj">a</W>
<W lemma="casa" msd="NC" tag="NC" in="-1:nobj" out="">casa</W>
<W lemma="desde" msd="SP" tag="SCENE" in="" out="1:nobj">desde</W>
<W lemma="Tailandia" msd="NP" tag="NP" in="-1:nobj" out="">Tailandia</W>
<W lemma="para" msd="CS" tag="CSUBI" in="" out="1:vobj">para</W>
<W lemma="ser" msd="VAF" tag="VSinf" in="-1:vobj" out="1:preds">ser</W>
<W lemma="meter" msd="VAF" tag="VLadj" in="-1:preds" out="">metidos</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="prisión" msd="NC" tag="NC" in="-1:nobj" out="">prisión</W>
<W lemma="preventivo" msd="AN" tag="ADJ" in="" out="">preventiva</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="porque" msd="CS" tag="CSUBX" in="" out="5:vobj">porque</W>
<W lemma="en" msd="SP" tag="SCENE" in="4:time" out="1:nobj">en</W>
<W lemma="caso" msd="NC" tag="NC" in="-1:nobj" out="">caso</W>
<W lemma="contrario" msd="AN" tag="ADJ" in="" out="">contrario</W>
<W lemma="se" msd="PC" tag="SE" in="1:robj" out="">se</W>
<W lemma="&lt;unknown&gt;" msd="VAD" tag="VLfin" in="-5:vobj" out="-4:time|-1:robj">arriesgaban</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:vobj">a</W>
<W lemma="ser" msd="VAF" tag="VSinf" in="-1:vobj" out="1:preds">ser</W>
<W lemma="encarcelar" msd="VAF" tag="VLadj" in="-1:preds" out="">encarcelados</W>
<W lemma="en" msd="SP" tag="SCENE" in="" out="1:nobj">en</W>
<W lemma="el" msd="PD" tag="ART" in="-1:nobj" out="1:nobj">las</W>
<W lemma="cárcel" msd="NC" tag="NC" in="-1:nobj" out="">cárceles</W>
<W lemma="&lt;unknown&gt;" msd="VAF" tag="VLadj" in="" out="1:time">tailandesas</W>
<W lemma="mientras" msd="CS" tag="CSUBX" in="-1:time" out="1:vobj">mientras</W>
<W lemma="esperar" msd="VAD" tag="VLfin" in="-1:vobj" out="1:dobj|5:pnct">esperaban</W>
<W lemma="suyo" msd="PP" tag="PPO" in="-1:dobj" out="1:nobj">su</W>
<W lemma="extradición" msd="NC" tag="NC" in="-1:nobj" out="">extradición</W>
<W lemma="a" msd="SP" tag="SCENE" in="" out="1:nobj">a</W>
<W lemma="Dinamarca" msd="NP" tag="NP" in="-1:nobj" out="">Dinamarca</W>
<W lemma="." msd="XP" tag="FS" in="-5:pnct" out="">.</W>
</s>
</p>
