<s>
<W id="1" tag="(" in="2:pnct" out="">(</W>
<W id="2" tag="CD" in="1:mod" out="">2nd</W>
<W id="3" tag="NN" in="" out="-2:pnct|-1:mod|1:pnct">edition</W>
<W id="4" tag=")" in="-1:pnct" out="">)</W>
<W id="5" tag="DT" in="5:subj|7:[subj]" out="3:nobj">The</W>
<W id="6" tag="JJ" in="1:mod" out="">real</W>
<W id="7" tag="NN" in="1:mod" out="-1:mod">estate</W>
<W id="8" tag="NN" in="-3:nobj" out="-1:mod|1:appr">company</W>
<W id="9" tag="NNP" in="-1:appr" out="">Norden</W>
<W id="10" tag="VBZ" in="" out="-5:subj|1:dobj|27:pnct">wants</W>
<W id="11" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="12" tag="VB" in="-1:vobj" out="-7:[subj]|2:pred">grow</W>
<W id="13" tag="RB" in="1:mod" out="">even</W>
<W id="14" tag="JJR" in="-2:pred" out="-1:mod|1:pobj">bigger</W>
<W id="15" tag="IN" in="-1:pobj" out="2:vobj">than</W>
<W id="16" tag="PRP" in="1:subj" out="">it</W>
<W id="17" tag="MD" in="-2:vobj" out="-1:subj|1:vobj|2:mod">will</W>
<W id="18" tag="VB" in="-1:vobj" out="">be</W>
<W id="19" tag="IN" in="-2:mod" out="1:nobj">after</W>
<W id="20" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="21" tag="NN" in="-1:nobj" out="1:pobj">merger</W>
<W id="22" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="23" tag="CD" in="-1:nobj" out="1:pobj|6:pnct|9:appa">one</W>
<W id="24" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="25" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="26" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W id="27" tag="NNS" in="-1:nobj" out="1:possd">group's</W>
<W id="28" tag="NNS" in="-1:possd" out="">companies</W>
<W id="29" tag="," in="-6:pnct" out="">,</W>
<W id="30" tag="NNP" in="2:mod" out="">Public</W>
<W id="31" tag="NNP" in="1:mod" out="">Limited</W>
<W id="32" tag="NN" in="-9:appa" out="-1:mod|-2:mod|1:mod">Company</W>
<W id="33" tag="IN" in="-1:mod" out="2:nobj">of</W>
<W id="34" tag="CD" in="1:mod" out="">15</W>
<W id="35" tag="NNP" in="-2:nobj" out="-1:mod|1:nobj">April</W>
<W id="36" tag="CD" in="-1:nobj" out="">1980</W>
<W id="37" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W id="40" tag="DT" in="4:subj|6:[subj]" out="1:mod|2:mod|3:nobj">The</W>
<W id="41" tag="JJ" in="-1:mod" out="">first</W>
<W id="42" tag="JJ" in="-2:mod" out="">interested</W>
<W id="43" tag="NNS" in="-3:nobj" out="">companies</W>
<W id="44" tag="VBP" in="" out="-4:subj|1:mod|2:vobj|3:pnct|4:mod|21:pnct">have</W>
<W id="45" tag="RB" in="-1:mod" out="">already</W>
<W id="46" tag="VBN" in="-2:vobj" out="-6:[subj]">appeared</W>
<W id="47" tag="," in="-3:pnct" out="">,</W>
<W id="48" tag="IN" in="-4:mod" out="4:vobj">after</W>
<W id="49" tag="NNP" in="3:subj" out="">Norden</W>
<W id="50" tag="NN" in="2:mod" out="">yesterday</W>
<W id="51" tag="RB" in="1:mod" out="">officially</W>
<W id="52" tag="VBD" in="-4:vobj" out="-3:subj|-2:mod|-1:mod|1:dobj">announced</W>
<W id="53" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="54" tag="NNS" in="1:subj|2:[subj]" out="">negotiations</W>
<W id="55" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj">have</W>
<W id="56" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|7:pobj">put</W>
<W id="57" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="58" tag="NN" in="-1:nobj" out="1:pobj">consolidation</W>
<W id="59" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="60" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="61" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W id="62" tag="NN" in="-1:nobj" out="">company</W>
<W id="63" tag="IN" in="-7:pobj" out="1:nobj">into</W>
<W id="64" tag="NN" in="-1:nobj" out="">place</W>
<W id="65" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W id="68" tag="&amp;quot;" in="4:pnct" out="">"</W>
<W id="69" tag="NNP" in="3:subj|4:[subj]" out="1:coord">Hafnia</W>
<W id="70" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="71" tag="NNP" in="-1:conj" out="">Norden</W>
<W id="72" tag="VBP" in="9:qobj" out="-4:pnct|-3:subj|1:vobj|7:pnct|8:pnct">are</W>
<W id="73" tag="VBG" in="-1:vobj" out="-4:[subj]|1:dobj|3:pred">leaving</W>
<W id="74" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="75" tag="NN" in="-1:nobj" out="">door</W>
<W id="76" tag="JJ" in="-3:pred" out="1:mod">open</W>
<W id="77" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W id="78" tag="NNS" in="-1:nobj" out="">others</W>
<W id="79" tag="," in="-7:pnct" out="">,</W>
<W id="80" tag="&amp;quot;" in="-8:pnct" out="">"</W>
<W id="81" tag="VBZ" in="" out="-9:qobj|2:subj|15:pnct">says</W>
<W id="82" tag="NNP" in="1:namef" out="">Preben</W>
<W id="83" tag="NNP" in="-2:subj" out="-1:namef|1:pnct|2:ref|3:rel">Nygaard</W>
<W id="84" tag="," in="-1:pnct" out="">,</W>
<W id="85" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W id="86" tag="VBZ" in="-3:rel" out="-1:subj|1:pred">is</W>
<W id="87" tag="NN" in="-1:pred" out="1:pobj">director</W>
<W id="88" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="89" tag="NNP" in="-1:nobj" out="2:possd|4:appr">Norden's</W>
<W id="90" tag="NN" in="1:mod" out="">parent</W>
<W id="91" tag="NN" in="-2:possd" out="-1:mod">company</W>
<W id="92" tag="NNP" in="1:mod" out="">Commercial</W>
<W id="93" tag="NNP" in="-4:appr" out="-1:mod|1:mod|2:nobj">Holding</W>
<W id="94" tag="NNP" in="-1:mod" out="">International</W>
<W id="95" tag="S" in="-2:nobj" out="">A</W>
<W id="96" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="99" tag="IN" in="5:mod" out="1:nobj|3:pnct">After</W>
<W id="100" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="101" tag="NN" in="-1:nobj" out="">merger</W>
<W id="102" tag="," in="-3:pnct" out="">,</W>
<W id="103" tag="NNP" in="1:subj|2:[subj]" out="">Hafnia</W>
<W id="104" tag="MD" in="" out="-5:mod|-1:subj|1:vobj|20:pnct">will</W>
<W id="105" tag="VB" in="-1:vobj" out="-2:[subj]|1:mod|5:dobj">have</W>
<W id="106" tag="IN" in="-1:mod" out="1:nobj">at</W>
<W id="107" tag="PRP$" in="-1:nobj" out="1:possd">its</W>
<W id="108" tag="NN" in="-1:possd" out="">disposal</W>
<W id="109" tag="RB" in="1:mod" out="">approximately</W>
<W id="110" tag="CD" in="-5:dobj" out="-1:mod|1:nobj">40</W>
<W id="111" tag="NN" in="-1:nobj" out="1:pobj">percent</W>
<W id="112" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="113" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="114" tag="NNS" in="-1:nobj" out="">shares</W>
<W id="115" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="116" tag="NNP" in="-1:nobj" out="1:pnct|2:ref|3:rel">Norden</W>
<W id="117" tag="," in="-1:pnct" out="">,</W>
<W id="118" tag="WDT" in="-2:ref|1:subj|2:[subj]" out="">which</W>
<W id="119" tag="MD" in="-3:rel" out="-1:subj|1:vobj">will</W>
<W id="120" tag="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W id="121" tag="DT" in="-1:pred" out="1:mod|2:nobj">the</W>
<W id="122" tag="VBG" in="-1:mod" out="">continuing</W>
<W id="123" tag="NN" in="-2:nobj" out="">company</W>
<W id="124" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W id="127" tag="CC" in="" out="2:conj|24:pnct">But</W>
<W id="128" tag="PRP" in="1:subj" out="4:nobj">it</W>
<W id="129" tag="VBZ" in="-2:conj" out="-1:subj|1:pred">is</W>
<W id="130" tag="DT" in="-1:pred" out="1:nobj">the</W>
<W id="131" tag="NN" in="-1:nobj" out="">intent</W>
<W id="132" tag="IN" in="-4:nobj" out="3:vobj">that</W>
<W id="133" tag="NNP" in="2:subj|4:[subj]|5:[subj]" out="1:possd">Hafnia's</W>
<W id="134" tag="NNS" in="-1:possd" out="">shares</W>
<W id="135" tag="MD" in="-3:vobj" out="-2:subj|1:mod|2:vobj|8:mod">will</W>
<W id="136" tag="RB" in="-1:mod" out="">gradually</W>
<W id="137" tag="VB" in="-2:vobj" out="-4:[subj]|1:vobj">be</W>
<W id="138" tag="VBN" in="-1:vobj" out="-5:[subj]|1:avobj">throttled</W>
<W id="139" tag="RB" in="-1:avobj" out="1:mod">down</W>
<W id="140" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W id="141" tag="CD" in="-1:nobj" out="1:nobj">25</W>
<W id="142" tag="NN" in="-1:nobj" out="">percent</W>
<W id="143" tag="IN" in="-8:mod" out="4:vobj">as</W>
<W id="144" tag="DT" in="3:subj" out="1:mod|2:nobj">the</W>
<W id="145" tag="JJ" in="-1:mod" out="">new</W>
<W id="146" tag="NNS" in="-2:nobj" out="">companies</W>
<W id="147" tag="VBP" in="-4:vobj" out="-3:subj|1:lobj">come</W>
<W id="148" tag="IN" in="-1:lobj" out="1:nobj">through</W>
<W id="149" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="150" tag="NN" in="-1:nobj" out="">door</W>
<W id="151" tag="." in="-24:pnct" out="">.</W>
</s>
<s>
<W id="154" tag="PRP" in="1:subj" out="5:nobj">It</W>
<W id="155" tag="VBZ" in="" out="-1:subj|1:mod|2:pred|14:pnct">is</W>
<W id="156" tag="RB" in="-1:mod" out="">not</W>
<W id="157" tag="DT" in="-2:pred" out="1:nobj">the</W>
<W id="158" tag="NN" in="-1:nobj" out="">intent</W>
<W id="159" tag="IN" in="-5:nobj" out="2:vobj">that</W>
<W id="160" tag="NNP" in="1:subj|2:[subj]" out="">Hafnia</W>
<W id="161" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">will</W>
<W id="162" tag="VB" in="-1:vobj" out="-2:[subj]|3:dobj">have</W>
<W id="163" tag="RB" in="1:mod" out="">too</W>
<W id="164" tag="JJ" in="1:mod" out="-1:mod">great</W>
<W id="165" tag="DT" in="-3:dobj" out="-1:mod|1:nobj|2:mod">a</W>
<W id="166" tag="NN" in="-1:nobj" out="">say</W>
<W id="167" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="168" tag="PRP" in="-1:nobj" out="">it</W>
<W id="169" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W id="172" tag="JJ" in="2:mod" out="">Future</W>
<W id="173" tag="NN" in="1:mod" out="">merger</W>
<W id="174" tag="NNS" in="1:subj|4:[subj]|5:[subj]" out="-1:mod|-2:mod">partners</W>
<W id="175" tag="VBP" in="" out="-1:subj|1:mod|2:pred|6:mod|16:pnct">are</W>
<W id="176" tag="RB" in="-1:mod" out="">not</W>
<W id="177" tag="TO" in="-2:pred" out="1:vobj">to</W>
<W id="178" tag="VB" in="-1:vobj" out="-4:[subj]|1:vobj">be</W>
<W id="179" tag="VBN" in="-1:vobj" out="-5:[subj]|1:part">chased</W>
<W id="180" tag="RB" in="-1:part" out="">away</W>
<W id="181" tag="IN" in="-6:mod" out="1:nobj">for</W>
<W id="182" tag="NN" in="-1:nobj" out="1:pobj">fear</W>
<W id="183" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="184" tag="VBG" in="-1:nobj" out="1:pred">being</W>
<W id="185" tag="JJ" in="-1:pred" out="1:pobj">subject</W>
<W id="186" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="187" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="188" tag="NN" in="-1:nobj" out="">control</W>
<W id="189" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="190" tag="NNS" in="-1:nobj" out="">others</W>
<W id="191" tag="." in="-16:pnct" out="">.</W>
</s>
<s>
<W id="194" tag="CC" in="" out="1:conj">Or</W>
<W id="195" tag="IN" in="-1:conj" out="2:nobj">in</W>
<W id="196" tag="NNP" in="1:namef" out="">Preben</W>
<W id="197" tag="NNP" in="-2:nobj" out="-1:namef|1:possd|2:pnct|13:xpl">Nygaard's</W>
<W id="198" tag="NNS" in="-1:possd" out="">words</W>
<W id="199" tag="&3a;" in="-2:pnct" out="">:</W>
</s>
<s>
<W id="202" tag="&amp;quot;" in="8:pnct" out="">"</W>
<W id="203" tag="IN" in="7:mod" out="2:vobj">If</W>
<W id="204" tag="NNP" in="1:subj" out="">Hafnia</W>
<W id="205" tag="VBZ" in="-2:vobj" out="-1:subj|1:dobj|3:pnct">has</W>
<W id="206" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W id="207" tag="NN" in="-1:nobj" out="">majority</W>
<W id="208" tag="," in="-3:pnct" out="">,</W>
<W id="209" tag="PRP" in="1:subj|2:[subj]" out="">it</W>
<W id="210" tag="MD" in="-13:xpl" out="-8:pnct|-7:mod|-1:subj|1:vobj|4:pnct#|5:pnct">may</W>
<W id="211" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|2:vobj">make</W>
<W id="212" tag="NNS" in="-1:dobj|1:[subj]" out="">others</W>
<W id="213" tag="VB" in="-2:vobj" out="-1:[subj]|1:lobj">stay</W>
<W id="214" tag="CD" in="-1:lobj|-4:pnct#" out="">away.</W>
<W id="215" tag="&amp;quot;" in="-5:pnct" out="">"</W>
</s>
