<s>
<W id="1" tag="IN" in="10:mod" out="2:vobj">If</W>
<W id="2" tag="NN" in="1:subj" out="">everything</W>
<W id="3" tag="VBZ" in="-2:vobj" out="-1:subj|1:avobj|5:pnct">goes</W>
<W id="4" tag="VBG" in="-1:avobj" out="1:pobj">according</W>
<W id="5" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="6" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="7" tag="NNS" in="-1:nobj" out="">plans</W>
<W id="8" tag="," in="-5:pnct" out="">,</W>
<W id="9" tag="CD" in="2:subj|3:[subj]" out="1:nobj">15</W>
<W id="10" tag="NNS" in="-1:nobj" out="">families</W>
<W id="11" tag="MD" in="" out="-10:mod|-2:subj|1:vobj|14:pnct">can</W>
<W id="12" tag="VB" in="-1:vobj" out="-3:[subj]|1:dobj|3:lobj">celebrate</W>
<W id="13" tag="NNP" in="-1:dobj" out="1:nobj">Christmas</W>
<W id="14" tag="CD" in="-1:nobj" out="">1987</W>
<W id="15" tag="IN" in="-3:lobj" out="1:nobj">in</W>
<W id="16" tag="PRP$" in="-1:nobj" out="1:mod|4:possd|5:mod">their</W>
<W id="17" tag="JJ" in="-1:mod" out="">new</W>
<W id="18" tag="NN" in="2:mod" out="">co-op</W>
<W id="19" tag="NN" in="1:mod" out="">housing</W>
<W id="20" tag="NNS" in="-4:possd" out="-1:mod|-2:mod">units</W>
<W id="21" tag="IN" in="-5:mod" out="1:nobj">on</W>
<W id="22" tag="NNP" in="-1:nobj" out="1:mod">Stokkebjergvej</W>
<W id="23" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="24" tag="NNP" in="-1:nobj" out="">Jyderup</W>
<W id="25" tag="." in="-14:pnct" out="">.</W>
</s>
<s>
<W id="28" tag="IN" in="12:mod" out="1:nobj|9:pnct">After</W>
<W id="29" tag="JJ" in="-1:nobj" out="1:nobj|4:coord">several</W>
<W id="30" tag="NNS" in="-1:nobj" out="1:pobj">years</W>
<W id="31" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="32" tag="NN" in="-1:nobj" out="">preparation</W>
<W id="33" tag="CC" in="-4:coord" out="1:conj">and</W>
<W id="34" tag="JJ" in="-1:conj" out="1:mod|2:nobj">several</W>
<W id="35" tag="JJ" in="-1:mod" out="">major</W>
<W id="36" tag="NNS" in="-2:nobj" out="">meetings</W>
<W id="37" tag="," in="-9:pnct" out="">,</W>
<W id="38" tag="CD" in="2:subj|3:[subj]|6:[subj]" out="1:nobj">15</W>
<W id="39" tag="NNS" in="-1:nobj" out="">families</W>
<W id="40" tag="VBP" in="" out="-12:mod|-2:subj|1:vobj|11:pnct">have</W>
<W id="41" tag="VBN" in="-1:vobj" out="-3:[subj]|1:part|2:dobj">signed</W>
<W id="42" tag="RP" in="-1:part" out="">up</W>
<W id="43" tag="TO" in="-2:dobj" out="1:vobj">to</W>
<W id="44" tag="VB" in="-1:vobj" out="-6:[subj]|1:pred">be</W>
<W id="45" tag="DT" in="-1:pred" out="1:nobj">a</W>
<W id="46" tag="NN" in="-1:nobj" out="1:pobj">part</W>
<W id="47" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="48" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="49" tag="NN" in="1:mod" out="">housing</W>
<W id="50" tag="NN" in="-2:nobj" out="-1:mod">co-op</W>
<W id="51" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W id="54" tag="RB" in="7:mod" out="">Now</W>
<W id="55" tag="DT" in="6:subj|8:[subj]" out="1:nobj|2:mod">the</W>
<W id="56" tag="NNS" in="-1:nobj" out="">people</W>
<W id="57" tag="IN" in="-2:mod" out="2:nobj">behind</W>
<W id="58" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="59" tag="NNP" in="-2:nobj" out="-1:pnct|1:pnct">Stokken</W>
<W id="60" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W id="61" tag="VBP" in="" out="-7:mod|-6:subj|1:mod|2:vobj|17:pnct">are</W>
<W id="62" tag="RB" in="-1:mod" out="">only</W>
<W id="63" tag="VBG" in="-2:vobj" out="-8:[subj]|1:pobj">waiting</W>
<W id="64" tag="IN" in="-1:pobj" out="1:nobj|4:nobj">for</W>
<W id="65" tag="DT" in="-1:nobj|4:[subj]" out="2:nobj">the</W>
<W id="66" tag="NN" in="1:mod" out="">housing</W>
<W id="67" tag="NN" in="-2:nobj" out="-1:mod">co-op</W>
<W id="68" tag="TO" in="-4:nobj" out="1:vobj">to</W>
<W id="69" tag="VB" in="-1:vobj" out="-4:[subj]|1:pred|6:mod">become</W>
<W id="70" tag="NN" in="-1:pred" out="1:pobj">part</W>
<W id="71" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="72" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="73" tag="JJ" in="-1:mod" out="">residential</W>
<W id="74" tag="NN" in="-2:nobj" out="">quota</W>
<W id="75" tag="IN" in="-6:mod" out="1:nobj">before</W>
<W id="76" tag="NNP" in="-1:nobj" out="1:nobj">April</W>
<W id="77" tag="CD" in="-1:nobj" out="">1987</W>
<W id="78" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W id="81" tag="DT" in="2:subj|4:[subj]|5:[subj]" out="1:nobj">The</W>
<W id="82" tag="NN" in="-1:nobj" out="">construction</W>
<W id="83" tag="VBZ" in="17:qobj" out="-2:subj|1:pred|9:mod|16:pnct#">is</W>
<W id="84" tag="TO" in="-1:pred" out="1:vobj">to</W>
<W id="85" tag="VB" in="-1:vobj" out="-4:[subj]|1:vobj">be</W>
<W id="86" tag="VBN" in="-1:vobj" out="-5:[subj]|2:tobj">started</W>
<W id="87" tag="DT" in="1:mod" out="">no</W>
<W id="88" tag="RB" in="-2:tobj" out="-1:mod|1:pobj">later</W>
<W id="89" tag="IN" in="-1:pobj" out="1:nobj">than</W>
<W id="90" tag="NNP" in="-1:nobj" out="1:nobj">April</W>
<W id="91" tag="CD" in="-1:nobj" out="">1987</W>
<W id="92" tag="IN" in="-9:mod" out="1:nobj">in</W>
<W id="93" tag="NN" in="-1:nobj" out="1:nobj">order</W>
<W id="94" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W id="95" tag="VB" in="-1:vobj" out="1:pred|2:tobj">be</W>
<W id="96" tag="JJ" in="-1:pred" out="">ready</W>
<W id="97" tag="IN" in="-2:tobj" out="1:nobj">by</W>
<W id="98" tag="NNP" in="-1:nobj" out="1:nobj">December</W>
<W id="99" tag="CD" in="-1:nobj|-16:pnct#" out="">1987,</W>
<W id="100" tag="VBZ" in="" out="-17:qobj|1:subj|11:pnct">says</W>
<W id="101" tag="CD" in="-1:subj" out="1:pobj|4:pnct|7:appa">one</W>
<W id="102" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="103" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="104" tag="NNS" in="-1:nobj" out="">originators</W>
<W id="105" tag="," in="-4:pnct" out="">,</W>
<W id="106" tag="NN" in="2:title" out="">architect</W>
<W id="107" tag="VBG" in="1:namef" out="">Flemming</W>
<W id="108" tag="NN" in="-7:appa" out="-2:title|-1:namef|1:pnct|2:mod">Østergaard</W>
<W id="109" tag="," in="-1:pnct" out="">,</W>
<W id="110" tag="NNP" in="-2:mod" out="">Jyderup</W>
<W id="111" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W id="114" tag="&3a;" in="4:pnct" out="">-</W>
<W id="115" tag="JJ" in="3:subj|4:[subj]" out="1:pobj">Several</W>
<W id="116" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="117" tag="PRP" in="-1:nobj" out="">us</W>
<W id="118" tag="VBP" in="" out="-4:pnct|-3:subj|1:vobj|13:pnct">have</W>
<W id="119" tag="VBN" in="-1:vobj" out="-4:[subj]|1:pred|5:mod">been</W>
<W id="120" tag="DT" in="-1:pred" out="1:nobj">a</W>
<W id="121" tag="NN" in="-1:nobj" out="1:pobj">part</W>
<W id="122" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="123" tag="PRP" in="-1:nobj" out="">it</W>
<W id="124" tag="IN" in="-5:mod" out="1:nobj">since</W>
<W id="125" tag="PRP$" in="-1:nobj" out="1:possd|5:mod">its</W>
<W id="126" tag="NN" in="-1:possd" out="">start</W>
<W id="127" tag="IN" in="1:mod" out="">over</W>
<W id="128" tag="CD" in="2:tobj" out="-1:mod|1:nobj">two</W>
<W id="129" tag="NNS" in="-1:nobj" out="">years</W>
<W id="130" tag="RB" in="-5:mod" out="-2:tobj">ago</W>
<W id="131" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W id="134" tag="RB" in="2:mod" out="">Now</W>
<W id="135" tag="NN" in="1:subj|2:[subj]|4:[subj]" out="">something</W>
<W id="136" tag="VBZ" in="" out="-2:mod|-1:subj|1:vobj|4:pnct">is</W>
<W id="137" tag="VBG" in="-1:vobj" out="-2:[subj]|1:dobj">going</W>
<W id="138" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="139" tag="VB" in="-1:vobj" out="-4:[subj]">happen</W>
<W id="140" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W id="143" tag="DT" in="3:subj|4:[subj]" out="2:nobj">The</W>
<W id="144" tag="NN" in="1:mod" out="">housing</W>
<W id="145" tag="NN" in="-2:nobj" out="-1:mod">co-op</W>
<W id="146" tag="VBZ" in="" out="-3:subj|1:vobj|17:pnct|18:coord|43:pnct">has</W>
<W id="147" tag="VBN" in="-1:vobj" out="-4:[subj]|1:pred|10:tobj">been</W>
<W id="148" tag="IN" in="-1:pred" out="1:nobj">on</W>
<W id="149" tag="DT" in="-1:nobj" out="2:nobj|3:mod">the</W>
<W id="150" tag="VBG" in="1:mod" out="">waiting</W>
<W id="151" tag="NN" in="-2:nobj" out="-1:mod">list</W>
<W id="152" tag="IN" in="-3:mod" out="1:nobj">at</W>
<W id="153" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="154" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W id="155" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="156" tag="NNP" in="-1:nobj" out="">Housing</W>
<W id="157" tag="IN" in="-10:tobj" out="1:nobj">for</W>
<W id="158" tag="DT" in="-1:nobj" out="1:nobj|2:coord">a</W>
<W id="159" tag="NN" in="-1:nobj" out="">year</W>
<W id="160" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="161" tag="DT" in="-1:conj" out="1:nobj">a</W>
<W id="162" tag="NN" in="-1:nobj" out="">half</W>
<W id="163" tag="," in="-17:pnct" out="">,</W>
<W id="164" tag="CC" in="-18:coord" out="3:conj">but</W>
<W id="165" tag="VBG" in="1:namef" out="">Flemming</W>
<W id="166" tag="NN" in="1:subj|3:[subj]|5:[subj]" out="-1:namef">Østergaard</W>
<W id="167" tag="VBZ" in="-3:conj" out="-1:subj|1:coord|3:dobj">hopes</W>
<W id="168" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="169" tag="VBZ" in="-1:conj" out="-3:[subj]|1:[dobj]">expects</W>
<W id="170" tag="TO" in="-1:[dobj]|-3:dobj" out="1:vobj">to</W>
<W id="171" tag="VB" in="-1:vobj" out="-5:[subj]|1:dobj|11:mod">receive</W>
<W id="172" tag="DT" in="-1:dobj" out="1:nobj|2:mod">a</W>
<W id="173" tag="UH" in="-1:nobj" out="">yes</W>
<W id="174" tag="IN" in="-2:mod" out="1:nobj">for</W>
<W id="175" tag="CD" in="-1:nobj" out="3:nobj|4:mod">20</W>
<W id="176" tag="NN" in="2:mod" out="">co-op</W>
<W id="177" tag="NN" in="1:mod" out="">housing</W>
<W id="178" tag="NNS" in="-3:nobj" out="-1:mod|-2:mod">units</W>
<W id="179" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="180" tag="NNP" in="-1:nobj" out="">Jyderup</W>
<W id="181" tag="DT" in="1:mod" out="">no</W>
<W id="182" tag="RB" in="-11:mod" out="-1:mod|1:pobj">later</W>
<W id="183" tag="IN" in="-1:pobj" out="1:nobj">than</W>
<W id="184" tag="DT" in="-1:nobj" out="2:nobj|3:mod">the</W>
<W id="185" tag="NNP" in="1:mod" out="">April</W>
<W id="186" tag="NN" in="-2:nobj" out="-1:mod">quarter</W>
<W id="187" tag="IN" in="-3:mod" out="1:nobj">of</W>
<W id="188" tag="CD" in="-1:nobj" out="">1987</W>
<W id="189" tag="." in="-43:pnct" out="">.</W>
</s>
<s>
<W id="192" tag="NNS" in="1:subj|3:[subj]" out="">People</W>
<W id="193" tag="VBP" in="" out="-1:subj|1:mod|2:vobj|13:pnct">are</W>
<W id="194" tag="RB" in="-1:mod" out="">not</W>
<W id="195" tag="VBG" in="-2:vobj" out="-3:[subj]|1:mod|2:pobj|5:mod">waiting</W>
<W id="196" tag="IN" in="-1:mod" out="">around</W>
<W id="197" tag="IN" in="-2:pobj" out="1:nobj">for</W>
<W id="198" tag="DT" in="-1:nobj" out="1:nobj">an</W>
<W id="199" tag="NN" in="-1:nobj" out="">answer</W>
<W id="200" tag="IN" in="-5:mod" out="1:nobj|3:pred">with</W>
<W id="201" tag="PRP$" in="-1:nobj" out="1:possd">their</W>
<W id="202" tag="NNS" in="-1:possd" out="">hands</W>
<W id="203" tag="IN" in="-3:pred" out="1:nobj">in</W>
<W id="204" tag="PRP$" in="-1:nobj" out="1:possd">their</W>
<W id="205" tag="NNS" in="-1:possd" out="">laps</W>
<W id="206" tag="." in="-13:pnct" out="">.</W>
</s>
<s>
<W id="209" tag="DT" in="17:subj" out="1:mod|2:nobj|8:coord">A</W>
<W id="210" tag="JJ" in="-1:mod" out="">rough</W>
<W id="211" tag="NN" in="-2:nobj" out="1:pobj">blueprint</W>
<W id="212" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="213" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W id="214" tag="NN" in="2:mod" out="">co-op</W>
<W id="215" tag="NN" in="1:mod" out="">housing</W>
<W id="216" tag="NNS" in="-3:nobj" out="-1:mod|-2:mod">units</W>
<W id="217" tag="CC" in="-8:coord" out="1:conj">and</W>
<W id="218" tag="DT" in="-1:conj" out="1:nobj">a</W>
<W id="219" tag="NN" in="-1:nobj" out="1:pobj">number</W>
<W id="220" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="221" tag="NNS" in="-1:nobj" out="1:pobj">bylaws</W>
<W id="222" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W id="223" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="224" tag="NN" in="1:mod" out="">housing</W>
<W id="225" tag="NN" in="-2:nobj" out="-1:mod">co-op</W>
<W id="226" tag="VB" in="" out="-17:subj|1:pnct">exist</W>
<W id="227" tag="." in="-1:pnct" out="">.</W>
</s>
