<s>
<W id="1" tag="NNP" in="2:namef" out="1:namef">Hans</W>
<W id="2" tag="NNP" in="-1:namef" out="">Otto</W>
<W id="3" tag="NNP" in="1:subj" out="-2:namef">Bisgaard</W>
<W id="4" tag="VBZ" in="" out="-1:subj|1:dobj|8:pnct|9:mod|22:pnct">has</W>
<W id="5" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W id="6" tag="NN" in="-1:nobj" out="1:pobj">way</W>
<W id="7" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="8" tag="VBG" in="-1:nobj" out="1:pobj">dealing</W>
<W id="9" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="10" tag="VBG" in="-1:nobj" out="1:pred">becoming</W>
<W id="11" tag="NN" in="-1:pred" out="">drowsy</W>
<W id="12" tag="," in="-8:pnct" out="">,</W>
<W id="13" tag="WRB" in="-9:mod" out="2:vobj">when</W>
<W id="14" tag="PRP" in="1:subj|3:[subj]" out="">he</W>
<W id="15" tag="VBZ" in="-2:vobj" out="-1:subj|1:pred">is</W>
<W id="16" tag="TO" in="-1:pred" out="1:vobj">to</W>
<W id="17" tag="VB" in="-1:vobj" out="-3:[subj]|1:lobj|4:mod">go</W>
<W id="18" tag="IN" in="-1:lobj" out="1:nobj">on</W>
<W id="19" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="20" tag="NN" in="-1:nobj" out="">air</W>
<W id="21" tag="IN" in="-4:mod" out="1:nobj">with</W>
<W id="22" tag="DT" in="-1:nobj" out="1:mod|3:nobj">a</W>
<W id="23" tag="JJ" in="-1:mod" out="">direct</W>
<W id="24" tag="NN" in="1:mod" out="">TV</W>
<W id="25" tag="NN" in="-3:nobj" out="-1:mod">programme</W>
<W id="26" tag="." in="-22:pnct" out="">.</W>
</s>
<s>
<W id="29" tag="IN" in="7:mod" out="2:vobj">If</W>
<W id="30" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="31" tag="MD" in="-2:vobj" out="-1:subj|1:vobj|3:pnct">can</W>
<W id="32" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj">do</W>
<W id="33" tag="PRP" in="-1:dobj" out="">it</W>
<W id="34" tag="," in="-3:pnct" out="">,</W>
<W id="35" tag="PRP" in="1:subj|5:[subj]|7:[subj]" out="">he</W>
<W id="36" tag="VBZ" in="" out="-1:subj|-7:mod|1:dobj|3:coord|28:pnct">snatches</W>
<W id="37" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W id="38" tag="NN" in="-1:nobj" out="">nap</W>
<W id="39" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="40" tag="VBZ" in="-1:conj" out="-5:[subj]|1:mod|2:vobj">is</W>
<W id="41" tag="RB" in="-1:mod" out="">only</W>
<W id="42" tag="VBN" in="-2:vobj" out="-7:[subj]|3:mod">awakened</W>
<W id="43" tag="VBN" in="2:tobj" out="1:nobj">fifteen</W>
<W id="44" tag="NNS" in="-1:nobj" out="">minutes</W>
<W id="45" tag="IN" in="-3:mod" out="-2:tobj|3:vobj">before</W>
<W id="46" tag="NN" in="2:subj" out="1:nobj">family</W>
<W id="47" tag="NNP" in="-1:nobj" out="">Denmark</W>
<W id="48" tag="VBZ" in="-3:vobj" out="-2:subj|1:lobj|2:mod|7:mod">settles</W>
<W id="49" tag="RB" in="-1:lobj" out="">down</W>
<W id="50" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="51" tag="NN" in="-1:nobj" out="1:pobj">front</W>
<W id="52" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="53" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="54" tag="NN" in="-1:nobj" out="">screen</W>
<W id="55" tag="IN" in="-7:mod" out="1:nobj|7:pred">with</W>
<W id="56" tag="NN" in="-1:nobj" out="1:pnct|2:conj|3:coord">coffee</W>
<W id="57" tag="," in="-1:pnct" out="">,</W>
<W id="58" tag="NN" in="-2:conj" out="">cake</W>
<W id="59" tag="CC" in="-3:coord" out="2:conj">and</W>
<W id="60" tag="JJ" in="1:mod" out="">remote</W>
<W id="61" tag="NN" in="-2:conj" out="-1:mod">control</W>
<W id="62" tag="IN" in="-7:pred" out="1:nobj">within</W>
<W id="63" tag="NN" in="-1:nobj" out="">reach</W>
<W id="64" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W id="67" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="68" tag="CC" in="" out="-1:pnct|1:pnct|7:conj|18:pnct">But</W>
<W id="69" tag="," in="-1:pnct" out="">,</W>
<W id="70" tag="JJS" in="5:mod" out="1:pobj|3:pnct">most</W>
<W id="71" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="72" tag="DT" in="-1:nobj" out="">all</W>
<W id="73" tag="," in="-3:pnct" out="">,</W>
<W id="74" tag="PRP" in="1:subj|3:[subj]" out="">I</W>
<W id="75" tag="VBP" in="-7:conj" out="-1:subj|-5:mod|1:dobj|5:pnct|7:mod">want</W>
<W id="76" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="77" tag="VB" in="-1:vobj" out="-3:[subj]|1:dobj">brush</W>
<W id="78" tag="PRP$" in="-1:dobj" out="1:nobj">my</W>
<W id="79" tag="NNS" in="-1:nobj" out="">teeth</W>
<W id="80" tag="," in="-5:pnct" out="">,</W>
<W id="81" tag="RB" in="1:mod" out="">just</W>
<W id="82" tag="IN" in="-7:mod" out="-1:mod|2:vobj">before</W>
<W id="83" tag="PRP" in="1:subj" out="">we</W>
<W id="84" tag="VBP" in="-2:vobj" out="-1:subj|1:lobj">go</W>
<W id="85" tag="RB" in="-1:lobj" out="">on</W>
<W id="86" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W id="89" tag="CC" in="" out="8:conj|22:pnct">And</W>
<W id="90" tag="IN" in="7:mod" out="2:vobj">if</W>
<W id="91" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W id="92" tag="VBP" in="-2:vobj" out="-1:subj|1:vobj|3:pnct">don't</W>
<W id="93" tag="VBP" in="-1:vobj" out="-2:[subj]|1:dobj">do</W>
<W id="94" tag="IN" in="-1:dobj" out="">that</W>
<W id="95" tag="," in="-3:pnct" out="">,</W>
<W id="96" tag="PRP" in="1:subj|2:[subj]" out="">I</W>
<W id="97" tag="MD" in="-8:conj" out="-1:subj|-7:mod|1:vobj">can</W>
<W id="98" tag="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W id="99" tag="VBN" in="-1:pred" out="1:nobj">pleased</W>
<W id="100" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W id="101" tag="EX" in="1:expl" out="">there</W>
<W id="102" tag="VBZ" in="-2:vobj" out="-1:expl|1:dobj|4:pred">is</W>
<W id="103" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="104" tag="JJ" in="-1:mod" out="">thick</W>
<W id="105" tag="NN" in="-2:nobj" out="">filter</W>
<W id="106" tag="IN" in="-4:pred" out="2:nobj">between</W>
<W id="107" tag="NN" in="1:mod" out="">TV</W>
<W id="108" tag="NNS" in="-2:nobj" out="-1:mod|1:coord">viewers</W>
<W id="109" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="110" tag="PRP" in="-1:conj" out="">me</W>
<W id="111" tag="." in="-22:pnct" out="">.</W>
</s>
<s>
<W id="114" tag="RB" in="3:mod" out="1:pnct">Actually</W>
<W id="115" tag="," in="-1:pnct" out="">,</W>
<W id="116" tag="PRP" in="1:subj" out="">I</W>
<W id="117" tag="VBP" in="25:qobj" out="-3:mod|-1:subj|1:dobj|7:mod|12:pnct|13:mod|23:pnct|24:pnct">experience</W>
<W id="118" tag="DT" in="-1:dobj" out="1:pobj">some</W>
<W id="119" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="120" tag="PRP$" in="-1:nobj" out="1:possd">my</W>
<W id="121" tag="NNS" in="-1:possd" out="1:mod|2:possd">life's</W>
<W id="122" tag="JJS" in="-1:mod" out="">happiest</W>
<W id="123" tag="NNS" in="-2:possd" out="">moments</W>
<W id="124" tag="IN" in="-7:mod" out="1:nobj">during</W>
<W id="125" tag="DT" in="-1:nobj" out="1:mod|3:nobj">a</W>
<W id="126" tag="JJ" in="-1:mod" out="">direct</W>
<W id="127" tag="NN" in="1:mod" out="">TV</W>
<W id="128" tag="NN" in="-3:nobj" out="-1:mod">broadcast</W>
<W id="129" tag="," in="-12:pnct" out="">,</W>
<W id="130" tag="IN" in="-13:mod" out="2:vobj">because</W>
<W id="131" tag="EX" in="1:expl" out="">there</W>
<W id="132" tag="VBP" in="-2:vobj" out="-1:expl|1:dobj">are</W>
<W id="133" tag="DT" in="-1:dobj" out="1:nobj|2:mod">no</W>
<W id="134" tag="NNS" in="-1:nobj" out="">telephones</W>
<W id="135" tag="TO" in="-2:mod" out="1:vobj">to</W>
<W id="136" tag="VB" in="-1:vobj" out="1:pobj">interfere</W>
<W id="137" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="138" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="139" tag="NN" in="-1:nobj" out="">rhythm</W>
<W id="140" tag="," in="-23:pnct" out="">,</W>
<W id="141" tag="&amp;quot;" in="-24:pnct" out="">"</W>
<W id="142" tag="VBZ" in="" out="-25:qobj|1:subj|23:pnct">says</W>
<W id="143" tag="DT" in="-1:subj" out="1:mod|3:nobj|4:pnct|5:ref|6:rel">the</W>
<W id="144" tag="JJ" in="-1:mod" out="">likeable</W>
<W id="145" tag="NN" in="1:mod" out="">television</W>
<W id="146" tag="NN" in="-3:nobj" out="-1:mod">host</W>
<W id="147" tag="," in="-4:pnct" out="">,</W>
<W id="148" tag="WP" in="-5:ref|1:subj" out="">who</W>
<W id="149" tag="VBZ" in="-6:rel" out="-1:subj|1:dobj|9:pnct|10:mod">has</W>
<W id="150" tag="NNS" in="-1:dobj" out="1:pobj|3:coord">nerves</W>
<W id="151" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="152" tag="NN" in="-1:nobj" out="">steel</W>
<W id="153" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="154" tag="NN" in="-1:conj" out="1:pobj">warmth</W>
<W id="155" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W id="156" tag="PRP$" in="-1:nobj" out="1:possd">his</W>
<W id="157" tag="NN" in="-1:possd" out="">gaze</W>
<W id="158" tag="," in="-9:pnct" out="">,</W>
<W id="159" tag="WRB" in="-10:mod" out="4:vobj">when</W>
<W id="160" tag="DT" in="3:subj|4:[subj]" out="2:nobj">the</W>
<W id="161" tag="NN" in="1:mod" out="">television</W>
<W id="162" tag="NNS" in="-2:nobj" out="-1:mod">cameras</W>
<W id="163" tag="VBP" in="-4:vobj" out="-3:subj|1:vobj">are</W>
<W id="164" tag="VBG" in="-1:vobj" out="-4:[subj]">running</W>
<W id="165" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W id="168" tag="NN" in="11:mod" out="1:coord|7:pnct">Tomorrow</W>
<W id="169" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="170" tag="IN" in="-1:conj" out="1:nobj">for</W>
<W id="171" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="172" tag="VBG" in="-1:mod" out="">following</W>
<W id="173" tag="CD" in="-2:nobj" out="1:nobj">five</W>
<W id="174" tag="NNPS" in="-1:nobj" out="">Saturdays</W>
<W id="175" tag="," in="-7:pnct" out="">,</W>
<W id="176" tag="NNP" in="2:namef" out="1:namef">Hans</W>
<W id="177" tag="NNP" in="-1:namef" out="">Otto</W>
<W id="178" tag="NNP" in="1:subj|2:[subj]" out="-2:namef">Bisgaard</W>
<W id="179" tag="MD" in="" out="-11:mod|-1:subj|1:vobj|9:pnct#|10:mod|31:pnct">will</W>
<W id="180" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|3:pred|5:mod">have</W>
<W id="181" tag="PRP$" in="-1:dobj" out="1:possd">his</W>
<W id="182" tag="NN" in="-1:possd" out="">toothbrush</W>
<W id="183" tag="IN" in="-3:pred" out="1:nobj">on</W>
<W id="184" tag="NN" in="-1:nobj" out="">hand</W>
<W id="185" tag="IN" in="-5:mod" out="1:nobj">at</W>
<W id="186" tag="NNP" in="-1:nobj" out="1:possd">DR's</W>
<W id="187" tag="NNP" in="-1:possd" out="1:nobj">Studio</W>
<W id="188" tag="CD" in="-1:nobj|-9:pnct#" out="">3,</W>
<W id="189" tag="IN" in="-10:mod" out="2:vobj">because</W>
<W id="190" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="191" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">will</W>
<W id="192" tag="VB" in="-1:vobj" out="-2:[subj]|1:pred">be</W>
<W id="193" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W id="194" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="195" tag="NN" in="-1:nobj" out="1:pobj">middle</W>
<W id="196" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="197" tag="DT" in="-1:nobj" out="1:mod|2:mod|4:nobj|6:appr">the</W>
<W id="198" tag="JJ" in="-1:mod" out="">new</W>
<W id="199" tag="JJ" in="-2:mod" out="">direct</W>
<W id="200" tag="NN" in="1:mod" out="">entertainment</W>
<W id="201" tag="NN" in="-4:nobj" out="-1:mod">programme</W>
<W id="202" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="203" tag="NNP" in="-6:appr" out="-1:pnct|1:nobj|2:pnct|4:mod|6:pnct">Rio</W>
<W id="204" tag="NNP" in="-1:nobj" out="">Bio</W>
<W id="205" tag="&3a;" in="-2:pnct" out="">-</W>
<W id="206" tag="RB" in="1:mod" out="">Only</W>
<W id="207" tag="IN" in="-4:mod" out="-1:mod|1:nobj">for</W>
<W id="208" tag="NNPS" in="-1:nobj" out="">Ottomans</W>
<W id="209" tag="&amp;quot;" in="-6:pnct" out="">"</W>
<W id="210" tag="." in="-31:pnct" out="">.</W>
</s>
