<s>
<W id="1" tag="&amp;quot;" in="6:pnct" out="">"</W>
<W id="2" tag="DT" in="5:subj" out="1:nobj|2:mod">No</W>
<W id="3" tag="CD" in="-1:nobj" out="">one</W>
<W id="4" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="5" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="6" tag="NN" in="-1:nobj" out="">group</W>
<W id="7" tag="VBD" in="" out="-6:pnct|-5:subj|1:pred|12:pnct">was</W>
<W id="8" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W id="9" tag="NN" in="-1:nobj" out="1:nobj">doubt</W>
<W id="10" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W id="11" tag="EX" in="1:expl" out="">there</W>
<W id="12" tag="VBD" in="-2:vobj" out="-1:expl|1:dobj">was</W>
<W id="13" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="14" tag="JJ" in="-1:mod" out="">legal</W>
<W id="15" tag="NN" in="-2:nobj" out="1:pobj">claim</W>
<W id="16" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W id="17" tag="NN" in="1:mod" out="">family</W>
<W id="18" tag="NN" in="-2:nobj" out="-1:mod">reunification</W>
<W id="19" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W id="22" tag="IN" in="5:mod" out="1:nobj|3:pnct">In</W>
<W id="23" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="24" tag="NN" in="-1:nobj" out="">group</W>
<W id="25" tag="," in="-3:pnct" out="">,</W>
<W id="26" tag="PRP" in="1:subj" out="">they</W>
<W id="27" tag="VBD" in="" out="-5:mod|-1:subj|1:dobj|12:pnct">realised</W>
<W id="28" tag="IN" in="-1:dobj" out="8:vobj">that</W>
<W id="29" tag="PRP" in="7:subj" out="2:appa">it</W>
<W id="30" tag="(" in="1:pnct" out="">(</W>
<W id="31" tag="DT" in="-2:appa" out="-1:pnct|1:nobj|2:pnct|3:list|4:pnct">the</W>
<W id="32" tag="NN" in="-1:nobj" out="">halt</W>
<W id="33" tag="," in="-2:pnct" out="">,</W>
<W id="34" tag="JJ" in="-3:list" out="">red.</W>
<W id="35" tag=")" in="-4:pnct" out="">)</W>
<W id="36" tag="VBD" in="-8:vobj" out="-7:subj|2:pred">was</W>
<W id="37" tag="RB" in="1:mod" out="">legally</W>
<W id="38" tag="JJ" in="-2:pred" out="-1:mod">untenable</W>
<W id="39" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W id="42" tag="CC" in="" out="2:conj|15:pnct">But</W>
<W id="43" tag="EX" in="1:expl" out="">there</W>
<W id="44" tag="VBD" in="-2:conj" out="-1:expl|1:dobj">was</W>
<W id="45" tag="DT" in="-1:dobj" out="2:nobj">a</W>
<W id="46" tag="NN" in="1:mod" out="">minister</W>
<W id="47" tag="NN" in="-2:nobj" out="-1:mod|1:nobj">instruction</W>
<W id="48" tag="IN" in="-1:nobj" out="3:vobj">that</W>
<W id="49" tag="DT" in="2:subj|5:[subj]|6:[subj]" out="1:nobj">the</W>
<W id="50" tag="NNS" in="-1:nobj" out="">cases</W>
<W id="51" tag="VBD" in="-3:vobj" out="-2:subj|1:mod|2:pred">were</W>
<W id="52" tag="RB" in="-1:mod" out="">not</W>
<W id="53" tag="TO" in="-2:pred" out="1:vobj">to</W>
<W id="54" tag="VB" in="-1:vobj" out="-5:[subj]|1:vobj">be</W>
<W id="55" tag="VBN" in="-1:vobj" out="-6:[subj]|1:avobj">dealt</W>
<W id="56" tag="IN" in="-1:avobj" out="">with</W>
<W id="57" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="60" tag="JJR" in="2:subj|3:[subj]|4:[subj]" out="1:nobj">More</W>
<W id="61" tag="NNP" in="-1:nobj" out="">Tamils</W>
<W id="62" tag="MD" in="10:qobj" out="-2:subj|1:vobj|8:pnct|9:pnct">would</W>
<W id="63" tag="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W id="64" tag="VBN" in="-1:vobj" out="-4:[subj]|1:pobj">prevented</W>
<W id="65" tag="IN" in="-1:pobj" out="1:nobj">from</W>
<W id="66" tag="VBG" in="-1:nobj" out="1:lobj">coming</W>
<W id="67" tag="IN" in="-1:lobj" out="1:nobj">into</W>
<W id="68" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="69" tag="NN" in="-1:nobj" out="">country</W>
<W id="70" tag="," in="-8:pnct" out="">,</W>
<W id="71" tag="&amp;quot;" in="-9:pnct" out="">"</W>
<W id="72" tag="VBD" in="" out="-10:qobj|3:subj|11:pnct">explained</W>
<W id="73" tag="NNP" in="1:mod" out="">Police</W>
<W id="74" tag="NNP" in="1:title" out="-1:mod">Commissioner</W>
<W id="75" tag="NNP" in="-3:subj" out="-1:title|1:pnct|2:ref|3:rel">Dahlfelt</W>
<W id="76" tag="," in="-1:pnct" out="">,</W>
<W id="77" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W id="78" tag="VBD" in="-3:rel" out="-1:subj|1:mod">spoke</W>
<W id="79" tag="JJ" in="-1:mod" out="1:pobj">subject</W>
<W id="80" tag="TO" in="-1:pobj" out="2:nobj">to</W>
<W id="81" tag="JJ" in="1:mod" out="">criminal</W>
<W id="82" tag="NN" in="-2:nobj" out="-1:mod">liability</W>
<W id="83" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W id="86" tag="IN" in="8:pred" out="1:nobj">Among</W>
<W id="87" tag="DT" in="-1:nobj" out="1:ref|2:rel">those</W>
<W id="88" tag="WP" in="-1:ref|1:subj" out="">who</W>
<W id="89" tag="VBD" in="-2:rel" out="-1:subj|1:mod">participated</W>
<W id="90" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="91" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="92" tag="NN" in="1:mod" out="">immigration</W>
<W id="93" tag="NNS" in="-2:nobj" out="-1:mod">meetings</W>
<W id="94" tag="VBD" in="" out="-8:pred|6:subj|23:pnct">were</W>
<W id="95" tag="RB" in="2:mod" out="">then</W>
<W id="96" tag="JJ" in="1:mod" out="">Permanent</W>
<W id="97" tag="NNP" in="3:title" out="-1:mod|-2:mod">Secretary</W>
<W id="98" tag="NNP" in="2:namef" out="">Poul</W>
<W id="99" tag="NNP" in="1:namel" out="">Lundbæk</W>
<W id="100" tag="NNP" in="-6:subj" out="-2:namef|-1:namel|-3:title|1:coord|6:pnct|9:coord|13:mod">Andersen</W>
<W id="101" tag="CC" in="-1:coord" out="4:conj">and</W>
<W id="102" tag="NNP" in="1:mod" out="">Deputy</W>
<W id="103" tag="NNP" in="2:title" out="-1:mod">Director</W>
<W id="104" tag="NNP" in="1:namef" out="">Claus</W>
<W id="105" tag="NNP" in="-4:conj" out="-2:title|-1:namef">Tornøe</W>
<W id="106" tag="," in="-6:pnct" out="">,</W>
<W id="107" tag="RB" in="2:mod" out="1:aobj">as</W>
<W id="108" tag="RB" in="-1:aobj" out="">well</W>
<W id="109" tag="IN" in="-9:coord" out="-2:mod|3:conj">as</W>
<W id="110" tag="NNP" in="2:title" out="">Director</W>
<W id="111" tag="NNP" in="1:namef" out="">Frederik</W>
<W id="112" tag="NNP" in="-3:conj" out="-2:title|-1:namef">Schydt</W>
<W id="113" tag="IN" in="-13:mod" out="1:nobj">for</W>
<W id="114" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="115" tag="NNP" in="1:mod" out="">Immigration</W>
<W id="116" tag="NNP" in="-2:nobj" out="-1:mod">Office</W>
<W id="117" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W id="120" tag="&amp;quot;" in="8:pnct" out="">"</W>
<W id="121" tag="IN" in="7:mod" out="1:nobj|5:pnct">At</W>
<W id="122" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="123" tag="NN" in="-1:nobj" out="">meeting</W>
<W id="124" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="125" tag="NNP" in="-1:nobj" out="">May</W>
<W id="126" tag="," in="-5:pnct" out="">,</W>
<W id="127" tag="NNP" in="1:subj" out="">Lundbæk</W>
<W id="128" tag="VBD" in="" out="-8:pnct|-7:mod|-1:subj|1:dobj|27:pnct">said</W>
<W id="129" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="130" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="131" tag="VBD" in="-2:vobj" out="-1:subj|1:vobj">had</W>
<W id="132" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|3:pobj">discussed</W>
<W id="133" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="134" tag="NN" in="-1:nobj" out="">case</W>
<W id="135" tag="IN" in="-3:pobj" out="1:nobj">with</W>
<W id="136" tag="DT" in="-1:nobj" out="1:nobj|2:pnct|3:ref|4:rel">the</W>
<W id="137" tag="NN" in="-1:nobj" out="">minister</W>
<W id="138" tag="," in="-2:pnct" out="">,</W>
<W id="139" tag="WP" in="-3:ref|1:subj|2:[subj]" out="">who</W>
<W id="140" tag="VBD" in="-4:rel" out="-1:subj|1:vobj">had</W>
<W id="141" tag="VBD" in="-1:vobj" out="-2:[subj]|1:dobj">said</W>
<W id="142" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="143" tag="EX" in="1:expl" out="">there</W>
<W id="144" tag="VBD" in="-2:vobj" out="-1:expl|2:dobj|6:mod">was</W>
<W id="145" tag="JJ" in="1:mod" out="">political</W>
<W id="146" tag="NN" in="-2:dobj" out="-1:mod|1:coord">backing</W>
<W id="147" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="148" tag="NN" in="-1:conj" out="">support</W>
<W id="149" tag="JJ" in="1:mod" out="">deep</W>
<W id="150" tag="IN" in="-6:mod" out="-1:mod|1:nobj">within</W>
<W id="151" tag="DT" in="-1:nobj" out="2:mod|3:nobj">the</W>
<W id="152" tag="NNP" in="1:mod" out="">Social</W>
<W id="153" tag="NNP" in="-2:mod" out="-1:mod">Democratic</W>
<W id="154" tag="NNP" in="-3:nobj" out="">Party</W>
<W id="155" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W id="158" tag="NNP" in="1:subj" out="">Lundbæk</W>
<W id="159" tag="VBD" in="" out="-1:subj|3:pred|4:pnct">seemed</W>
<W id="160" tag="DT" in="2:mod" out="1:mod">a</W>
<W id="161" tag="RB" in="-1:mod" out="">little</W>
<W id="162" tag="VBN" in="-3:pred" out="-2:mod">shaken</W>
<W id="163" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W id="166" tag="PRP" in="1:subj|5:[subj]" out="">He</W>
<W id="167" tag="VBD" in="" out="-1:subj|1:mod|4:vobj|14:pnct#|15:pnct">had</W>
<W id="168" tag="IN" in="-1:mod" out="2:nobj">at</W>
<W id="169" tag="VBN" in="1:mod" out="">repeated</W>
<W id="170" tag="NNS" in="-2:nobj" out="-1:mod">meetings</W>
<W id="171" tag="VBD" in="-4:vobj" out="-5:[subj]|1:dobj">said</W>
<W id="172" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="173" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="174" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">would</W>
<W id="175" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|3:pobj|6:mod">discuss</W>
<W id="176" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="177" tag="NN" in="-1:nobj" out="">case</W>
<W id="178" tag="IN" in="-3:pobj" out="1:nobj">with</W>
<W id="179" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="180" tag="NN" in="-1:nobj" out="">minister</W>
<W id="181" tag="CD" in="-6:mod|-14:pnct#" out="">again.</W>
<W id="182" tag="&amp;quot;" in="-15:pnct" out="">"</W>
</s>
<s>
<W id="185" tag="DT" in="" out="1:nobj">No</W>
<W id="186" tag="NN" in="-1:nobj" out="">connection</W>
</s>
<s>
<W id="189" tag="NNP" in="1:mod" out="">Police</W>
<W id="190" tag="NNP" in="1:title" out="-1:mod">Commissioner</W>
<W id="191" tag="NNP" in="7:subj|9:[subj]" out="-1:title|1:pnct">Dahlfelt</W>
<W id="192" tag="," in="-1:pnct" out="">,</W>
<W id="193" tag="IN" in="5:modp" out="1:nobj|4:pnct">on</W>
<W id="194" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="195" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W id="196" tag="NN" in="-1:nobj" out="">hand</W>
<W id="197" tag="," in="-4:pnct" out="">,</W>
<W id="198" tag="MD" in="" out="-7:subj|-5:modp|1:mod|2:vobj|62:pnct">could</W>
<W id="199" tag="RB" in="-1:mod" out="">not</W>
<W id="200" tag="VB" in="-2:vobj" out="-9:[subj]|4:dobj">support</W>
<W id="201" tag="NNP" in="1:mod" out="">Deputy</W>
<W id="202" tag="NNP" in="2:title" out="-1:mod">Director</W>
<W id="203" tag="NNP" in="1:namef" out="">Claus</W>
<W id="204" tag="NNP" in="-4:dobj" out="-2:title|-1:namef|1:possd">Tornøe's</W>
<W id="205" tag="NN" in="-1:possd" out="1:nobj">explanation</W>
<W id="206" tag="IN" in="-1:nobj" out="10:vobj">that</W>
<W id="207" tag="DT" in="9:subj|10:[subj]" out="1:nobj|6:mod">the</W>
<W id="208" tag="NN" in="-1:nobj" out="1:pobj">halt</W>
<W id="209" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W id="210" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="211" tag="NNP" in="1:mod" out="">Tamil</W>
<W id="212" tag="NNS" in="-2:nobj" out="-1:mod">cases</W>
<W id="213" tag="IN" in="-6:mod" out="1:nobj">from</W>
<W id="214" tag="NNP" in="-1:nobj" out="1:nobj">September</W>
<W id="215" tag="CD" in="-1:nobj" out="">1987</W>
<W id="216" tag="VBD" in="-10:vobj" out="-9:subj|1:vobj">was</W>
<W id="217" tag="VBN" in="-1:vobj" out="-10:[subj]|1:pobj">connected</W>
<W id="218" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="219" tag="DT" in="-1:nobj" out="1:nobj|21:pnct|22:appa">a</W>
<W id="220" tag="NN" in="-1:nobj" out="1:dobj">plan</W>
<W id="221" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="222" tag="VB" in="-1:vobj" out="1:lobj|2:mod|5:dobj">send</W>
<W id="223" tag="NN" in="-1:lobj" out="">home</W>
<W id="224" tag="RB" in="-2:mod" out="">forcibly</W>
<W id="225" tag="RB" in="1:mod" out="">just</W>
<W id="226" tag="IN" in="1:mod" out="-1:mod">under</W>
<W id="227" tag="CD" in="-5:dobj" out="-1:mod|2:nobj|3:ref|4:rel">3,000</W>
<W id="228" tag="NNP" in="1:mod" out="">Tamil</W>
<W id="229" tag="NNS" in="-2:nobj" out="-1:mod">refugees</W>
<W id="230" tag="WP" in="-3:ref|1:subj|2:[subj]" out="">who</W>
<W id="231" tag="VBD" in="-4:rel" out="-1:subj|1:vobj">had</W>
<W id="232" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pred|3:mod">been</W>
<W id="233" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W id="234" tag="NNP" in="-1:nobj" out="">Denmark</W>
<W id="235" tag="IN" in="-3:mod" out="3:nobj">for</W>
<W id="236" tag="JJR" in="2:mod" out="1:pobj">less</W>
<W id="237" tag="IN" in="-1:pobj" out="1:[nobj]">than</W>
<W id="238" tag="CD" in="-3:nobj|-1:[nobj]" out="-2:mod|1:nobj">two</W>
<W id="239" tag="NNS" in="-1:nobj" out="">years</W>
<W id="240" tag="&3a;" in="-21:pnct" out="">-</W>
<W id="241" tag="DT" in="-22:appa" out="1:nobj|2:ref|9:rel">a</W>
<W id="242" tag="NN" in="-1:nobj" out="">plan</W>
<W id="243" tag="IN" in="-2:ref|11:iobj|13:[subj]|14:[subj]" out="">that</W>
<W id="244" tag="NNP" in="6:subj|7:[subj]|9:[subj]|10:[subj]" out="1:pnct">Ninn-Hansen</W>
<W id="245" tag="," in="-1:pnct" out="">,</W>
<W id="246" tag="VBG" in="4:modp" out="1:pobj|3:pnct">according</W>
<W id="247" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="248" tag="NNP" in="-1:nobj" out="">Tornøe</W>
<W id="249" tag="," in="-3:pnct" out="">,</W>
<W id="250" tag="VBD" in="-9:rel" out="-6:subj|-4:modp|1:vobj">was</W>
<W id="251" tag="VBN" in="-1:vobj" out="-7:[subj]|1:dobj">supposed</W>
<W id="252" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="253" tag="VB" in="-1:vobj" out="-9:[subj]|1:vobj">have</W>
<W id="254" tag="VBN" in="-1:vobj" out="-10:[subj]|-11:iobj|1:dobj">ordered</W>
<W id="255" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="256" tag="VB" in="-1:vobj" out="-13:[subj]|1:vobj">be</W>
<W id="257" tag="VBN" in="-1:vobj" out="-14:[subj]|1:pobj">put</W>
<W id="258" tag="IN" in="-1:pobj" out="1:nobj">into</W>
<W id="259" tag="NN" in="-1:nobj" out="">motion</W>
<W id="260" tag="." in="-62:pnct" out="">.</W>
</s>
