<s>
<W id="1" tag="NNP" in="3:subj|6:[subj]|7:[subj]" out="2:possd">Horsens</W>
<W id="2" tag="NNP" in="1:mod" out="">Art</W>
<W id="3" tag="NNP" in="-2:possd" out="-1:mod">Museum</W>
<W id="4" tag="VBZ" in="" out="-3:subj|1:mod|3:vobj|9:pnct">has</W>
<W id="5" tag="IN" in="-1:mod" out="1:nobj">since</W>
<W id="6" tag="CD" in="-1:nobj" out="">1984</W>
<W id="7" tag="VBN" in="-3:vobj" out="-6:[subj]|1:vobj">been</W>
<W id="8" tag="VBN" in="-1:vobj" out="-7:[subj]|1:pobj">housed</W>
<W id="9" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W id="10" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="11" tag="NNP" in="1:mod" out="">Grove</W>
<W id="12" tag="NNP" in="-2:nobj" out="-1:mod">Pavilion</W>
<W id="13" tag="." in="-9:pnct" out="">.</W>
</s>
<s>
<W id="16" tag="PRP" in="1:subj" out="">It</W>
<W id="17" tag="VBZ" in="" out="-1:subj|1:pred|8:pnct|21:pnct">is</W>
<W id="18" tag="DT" in="-1:pred" out="1:mod|2:pnct|5:mod|6:nobj|11:ref|12:rel">a</W>
<W id="19" tag="JJ" in="-1:mod" out="">beautiful</W>
<W id="20" tag="," in="-2:pnct" out="">,</W>
<W id="21" tag="RB" in="1:mod" out="">approximately</W>
<W id="22" tag="JJ" in="1:mod" out="-1:mod">150-year</W>
<W id="23" tag="JJ" in="-5:mod" out="-1:mod">old</W>
<W id="24" tag="NN" in="-6:nobj" out="">building</W>
<W id="25" tag="," in="-8:pnct" out="">,</W>
<W id="26" tag="DT" in="4:subj|5:[subj]" out="1:nobj|2:mod">the</W>
<W id="27" tag="NN" in="-1:nobj" out="">foundation</W>
<W id="28" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="29" tag="WDT" in="-1:nobj|-11:ref" out="">which</W>
<W id="30" tag="VBD" in="-12:rel" out="-4:subj|1:vobj">was</W>
<W id="31" tag="VBN" in="-1:vobj" out="-5:[subj]|1:pobj">laid</W>
<W id="32" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W id="33" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="34" tag="NNP" in="-1:nobj" out="1:mod|2:nobj|3:possd">Horsens</W>
<W id="35" tag="NNP" in="-1:mod" out="">Civil</W>
<W id="36" tag="NNP" in="-2:nobj" out="">Marksmen's</W>
<W id="37" tag="NNP" in="-3:possd" out="">Guild</W>
<W id="38" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W id="41" tag="IN" in="8:mod" out="1:avobj|2:pnct">Since</W>
<W id="42" tag="RB" in="-1:avobj" out="">then</W>
<W id="43" tag="," in="-2:pnct" out="">,</W>
<W id="44" tag="IN" in="5:modp" out="1:nobj|3:pnct">among</W>
<W id="45" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W id="46" tag="NNS" in="-1:nobj" out="">things</W>
<W id="47" tag="," in="-3:pnct" out="">,</W>
<W id="48" tag="PRP" in="1:subj|2:[subj]" out="">it</W>
<W id="49" tag="VBZ" in="" out="-1:subj|-8:mod|-5:modp|1:vobj|5:pnct">has</W>
<W id="50" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pred">been</W>
<W id="51" tag="DT" in="-1:pred" out="2:nobj">a</W>
<W id="52" tag="NN" in="1:mod" out="">summer</W>
<W id="53" tag="NN" in="-2:nobj" out="-1:mod">restaurant</W>
<W id="54" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W id="57" tag="DT" in="2:subj" out="1:nobj">The</W>
<W id="58" tag="NN" in="-1:nobj" out="">museum</W>
<W id="59" tag="VBZ" in="" out="-2:subj|1:pred|15:pnct">is</W>
<W id="60" tag="IN" in="-1:pred" out="1:nobj">in</W>
<W id="61" tag="DT" in="-1:nobj" out="1:nobj|4:pnct|5:appa">the</W>
<W id="62" tag="NNP" in="-1:nobj" out="1:nobj">Caroline</W>
<W id="63" tag="NNP" in="-1:nobj" out="1:nobj">Amalie</W>
<W id="64" tag="NNP" in="-1:nobj" out="">Grove</W>
<W id="65" tag="," in="-4:pnct" out="">,</W>
<W id="66" tag="DT" in="-5:appa" out="1:mod|2:nobj|3:mod">a</W>
<W id="67" tag="JJ" in="-1:mod" out="">large</W>
<W id="68" tag="NN" in="-2:nobj" out="">park</W>
<W id="69" tag="IN" in="-3:mod" out="4:nobj">with</W>
<W id="70" tag="JJ" in="3:mod" out="1:pnct">stately</W>
<W id="71" tag="," in="-1:pnct" out="">,</W>
<W id="72" tag="JJ" in="1:mod" out="">old</W>
<W id="73" tag="NNS" in="-4:nobj" out="-3:mod|-1:mod">trees</W>
<W id="74" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="77" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W id="78" tag="DT" in="2:subj" out="1:nobj">The</W>
<W id="79" tag="NN" in="-1:nobj" out="">criticism</W>
<W id="80" tag="VBZ" in="5:qobj" out="-3:pnct|-2:subj|1:dobj|3:pnct|4:pnct">misses</W>
<W id="81" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="82" tag="NN" in="-1:nobj" out="">mark</W>
<W id="83" tag="," in="-3:pnct" out="">,</W>
<W id="84" tag="&amp;quot;" in="-4:pnct" out="">"</W>
<W id="85" tag="VBZ" in="" out="-5:qobj|2:subj|3:pnct">says</W>
<W id="86" tag="NNP" in="1:namef" out="">Claus</W>
<W id="87" tag="NNP" in="-2:subj" out="-1:namef">Hagedorn-Olsen</W>
<W id="88" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W id="91" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W id="92" tag="DT" in="2:subj" out="1:nobj">The</W>
<W id="93" tag="NN" in="-1:nobj" out="">addition</W>
<W id="94" tag="NNS" in="" out="-3:pnct|-2:subj|1:dobj|9:pnct|10:coord|44:pnct#|45:pnct">touches</W>
<W id="95" tag="JJR" in="-1:dobj" out="1:pobj">less</W>
<W id="96" tag="IN" in="-1:pobj" out="1:nobj">than</W>
<W id="97" tag="CD" in="-1:nobj" out="1:nobj">one</W>
<W id="98" tag="NN" in="-1:nobj" out="1:pobj">percent</W>
<W id="99" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="100" tag="DT" in="-1:nobj" out="1:nobj|2:possd">the</W>
<W id="101" tag="NNS" in="-1:nobj" out="">park's</W>
<W id="102" tag="NN" in="-2:possd" out="">area</W>
<W id="103" tag="," in="-9:pnct" out="">,</W>
<W id="104" tag="CC" in="-10:coord" out="9:conj">and</W>
<W id="105" tag="NNP" in="1:mod" out="">Horsens</W>
<W id="106" tag="NNS" in="7:subj" out="-1:mod|3:appr">architects</W>
<W id="107" tag="NNP" in="2:namef" out="">Niels</W>
<W id="108" tag="NNP" in="1:namel" out="">Thorup</W>
<W id="109" tag="NNP" in="-3:appr" out="-2:namef|-1:namel|1:coord">Pedersen</W>
<W id="110" tag="CC" in="-1:coord" out="2:conj">and</W>
<W id="111" tag="NNP" in="1:namef" out="">Poul</W>
<W id="112" tag="NNP" in="-2:conj" out="-1:namef">Schwartz</W>
<W id="113" tag="VBD" in="-9:conj" out="-7:subj|1:pred|15:coord">were</W>
<W id="114" tag="JJ" in="-1:pred" out="1:nobj">able</W>
<W id="115" tag="TO" in="-1:nobj" out="1:vobj">to</W>
<W id="116" tag="VB" in="-1:vobj" out="1:dobj">design</W>
<W id="117" tag="DT" in="-1:dobj" out="1:nobj|2:ref|3:rel">an</W>
<W id="118" tag="NN" in="-1:nobj" out="">extension</W>
<W id="119" tag="WDT" in="-2:ref|1:subj" out="">that</W>
<W id="120" tag="VBZ" in="-3:rel" out="-1:subj|1:avobj|3:aobj">fits</W>
<W id="121" tag="IN" in="-1:avobj" out="3:mod">in</W>
<W id="122" tag="RB" in="1:mod" out="">particularly</W>
<W id="123" tag="RB" in="-3:aobj" out="-1:mod">well</W>
<W id="124" tag="IN" in="-3:mod" out="1:nobj">with</W>
<W id="125" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="126" tag="JJ" in="-1:mod" out="">old</W>
<W id="127" tag="NN" in="-2:nobj" out="">building</W>
<W id="128" tag="CC" in="-15:coord" out="1:pnct|5:conj">and</W>
<W id="129" tag="," in="-1:pnct" out="">,</W>
<W id="130" tag="RB" in="3:mod" out="1:pnct">therefore</W>
<W id="131" tag="," in="-1:pnct" out="">,</W>
<W id="132" tag="PRP" in="1:subj|2:[subj]" out="">we</W>
<W id="133" tag="MD" in="-5:conj" out="-3:mod|-1:subj|1:vobj">can</W>
<W id="134" tag="VB" in="-1:vobj" out="-2:[subj]|1:dobj|4:aobj">regard</W>
<W id="135" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="136" tag="NN" in="-1:nobj" out="">criticism</W>
<W id="137" tag="RB" in="1:mod" out="">quite</W>
<W id="138" tag="CD" in="-4:aobj|-44:pnct#" out="-1:mod">calmly.</W>
<W id="139" tag="&amp;quot;" in="-45:pnct" out="">"</W>
</s>
<s>
<W id="142" tag="JJ" in="" out="1:pobj">Ready</W>
<W id="143" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W id="144" tag="DT" in="-1:nobj" out="2:nobj">a</W>
<W id="145" tag="NN" in="1:mod" out="">city</W>
<W id="146" tag="NN" in="-2:nobj" out="-1:mod">jubilee</W>
</s>
<s>
<W id="149" tag="IN" in="11:mod" out="3:vobj">If</W>
<W id="150" tag="DT" in="2:subj" out="1:nobj">the</W>
<W id="151" tag="NN" in="-1:nobj" out="">construction</W>
<W id="152" tag="VBZ" in="-3:vobj" out="-2:subj|1:aobj|4:pnct">goes</W>
<W id="153" tag="VBG" in="-1:aobj" out="1:pobj">according</W>
<W id="154" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="155" tag="VB" in="-1:nobj" out="">plan</W>
<W id="156" tag="," in="-4:pnct" out="">,</W>
<W id="157" tag="DT" in="3:subj|4:[subj]" out="1:mod|2:nobj">the</W>
<W id="158" tag="VBN" in="-1:mod" out="">expanded</W>
<W id="159" tag="NN" in="-2:nobj" out="">museum</W>
<W id="160" tag="MD" in="" out="-3:subj|-11:mod|1:vobj|3:mod|5:pnct|6:mod|15:pnct">will</W>
<W id="161" tag="VB" in="-1:vobj" out="-4:[subj]|1:pred">be</W>
<W id="162" tag="JJ" in="-1:pred" out="">ready</W>
<W id="163" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="164" tag="NNP" in="-1:nobj" out="">November</W>
<W id="165" tag="," in="-5:pnct" out="">,</W>
<W id="166" tag="WRB" in="-6:mod" out="2:vobj">when</W>
<W id="167" tag="NNP" in="1:subj" out="">Horsens</W>
<W id="168" tag="VBZ" in="-2:vobj" out="-1:subj|1:dobj">celebrates</W>
<W id="169" tag="PRP$" in="-1:dobj" out="1:mod|2:possd">its</W>
<W id="170" tag="JJ" in="-1:mod" out="">550th</W>
<W id="171" tag="NN" in="-2:possd" out="1:pobj">jubilee</W>
<W id="172" tag="IN" in="-1:pobj" out="1:nobj">as</W>
<W id="173" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="174" tag="NN" in="-1:nobj" out="">city</W>
<W id="175" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="178" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="179" tag="CC" in="22:qobj" out="-1:pnct|7:conj|20:pnct|21:pnct">And</W>
<W id="180" tag="IN" in="6:mod" out="1:nobj|4:pnct">with</W>
<W id="181" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="182" tag="JJ" in="-1:mod" out="">new</W>
<W id="183" tag="NN" in="-2:nobj" out="">setting</W>
<W id="184" tag="," in="-4:pnct" out="">,</W>
<W id="185" tag="PRP" in="1:subj" out="">we</W>
<W id="186" tag="VBP" in="-7:conj" out="-6:mod|-1:subj|1:dobj">have</W>
<W id="187" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:mod">an</W>
<W id="188" tag="JJ" in="-1:mod" out="">excellent</W>
<W id="189" tag="NN" in="-2:nobj" out="">opportunity</W>
<W id="190" tag="TO" in="-3:mod" out="1:vobj">to</W>
<W id="191" tag="VB" in="-1:vobj" out="1:dobj|4:pred">make</W>
<W id="192" tag="NNP" in="-1:dobj" out="">Horsens</W>
<W id="193" tag="RB" in="1:mod" out="">even</W>
<W id="194" tag="RBR" in="1:mod" out="-1:mod">more</W>
<W id="195" tag="JJ" in="-4:pred" out="-1:mod|1:mod">well-known</W>
<W id="196" tag="IN" in="-1:mod" out="2:nobj">as</W>
<W id="197" tag="NNS" in="1:mod" out="">arts</W>
<W id="198" tag="NN" in="-2:nobj" out="-1:mod">city</W>
<W id="199" tag="," in="-20:pnct" out="">,</W>
<W id="200" tag="&amp;quot;" in="-21:pnct" out="">"</W>
<W id="201" tag="VBZ" in="" out="-22:qobj|2:subj|29:pnct">says</W>
<W id="202" tag="NNP" in="1:namef" out="">Claus</W>
<W id="203" tag="NNP" in="-2:subj" out="-1:namef|1:pnct|2:ref|3:rel">Hagedorn-Olsen</W>
<W id="204" tag="," in="-1:pnct" out="">,</W>
<W id="205" tag="WP" in="-2:ref|1:subj" out="">who</W>
<W id="206" tag="VBD" in="-3:rel" out="-1:subj|1:lobj|4:mod|8:mod|9:pnct#|10:mod">came</W>
<W id="207" tag="TO" in="-1:lobj" out="1:nobj">to</W>
<W id="208" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="209" tag="NN" in="-1:nobj" out="">city</W>
<W id="210" tag="IN" in="-4:mod" out="1:nobj">as</W>
<W id="211" tag="DT" in="-1:nobj" out="2:nobj">a</W>
<W id="212" tag="NN" in="1:mod" out="">museum</W>
<W id="213" tag="NN" in="-2:nobj" out="-1:mod">keeper</W>
<W id="214" tag="IN" in="-8:mod" out="1:nobj">in</W>
<W id="215" tag="CD" in="-1:nobj|-9:pnct#" out="">1984,</W>
<W id="216" tag="WRB" in="-10:mod" out="4:vobj">when</W>
<W id="217" tag="DT" in="3:subj" out="2:nobj">the</W>
<W id="218" tag="NN" in="1:mod" out="">art</W>
<W id="219" tag="NN" in="-2:nobj" out="-1:mod">museum</W>
<W id="220" tag="VBD" in="-4:vobj" out="-3:subj|1:lobj">moved</W>
<W id="221" tag="IN" in="-1:lobj" out="1:nobj|4:mod">into</W>
<W id="222" tag="PRP$" in="-1:nobj" out="1:mod|2:possd">its</W>
<W id="223" tag="JJ" in="-1:mod" out="">own</W>
<W id="224" tag="NN" in="-2:possd" out="">building</W>
<W id="225" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="226" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="227" tag="NNP" in="-1:nobj" out="1:nobj">Caroline</W>
<W id="228" tag="NNP" in="-1:nobj" out="1:nobj">Amalie</W>
<W id="229" tag="NNP" in="-1:nobj" out="">Grove</W>
<W id="230" tag="." in="-29:pnct" out="">.</W>
</s>
