<s>
<W id="1" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W id="2" tag="PRP" in="1:subj|2:[subj]|7:[subj]|12:[subj]" out="">We</W>
<W id="3" tag="MD" in="41:qobj" out="-2:pnct|-1:subj|1:vobj|5:coord|39:pnct|40:pnct">can</W>
<W id="4" tag="VB" in="-1:vobj" out="-2:[subj]|1:pobj">live</W>
<W id="5" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="6" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="7" tag="NN" in="-1:nobj" out="">loss</W>
<W id="8" tag="CC" in="-5:coord" out="1:conj">but</W>
<W id="9" tag="MD" in="-1:conj" out="-7:[subj]|1:pnct|2:mod|5:vobj">must</W>
<W id="10" tag="," in="-1:pnct" out="">,</W>
<W id="11" tag="IN" in="-2:mod" out="1:nobj|2:pnct">like</W>
<W id="12" tag="NNS" in="-1:nobj" out="">others</W>
<W id="13" tag="," in="-2:pnct" out="">,</W>
<W id="14" tag="NN" in="-5:vobj" out="-12:[subj]|1:dobj">state</W>
<W id="15" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="16" tag="PRP" in="1:subj|3:[subj]|4:[subj]" out="">we</W>
<W id="17" tag="MD" in="-2:vobj" out="-1:subj|1:mod|2:vobj|7:pnct|8:mod">would</W>
<W id="18" tag="RB" in="-1:mod" out="">not</W>
<W id="19" tag="VB" in="-2:vobj" out="-3:[subj]|1:vobj">have</W>
<W id="20" tag="VBN" in="-1:vobj" out="-4:[subj]|1:dobj|2:mod">issued</W>
<W id="21" tag="NNS" in="-1:dobj" out="">shares</W>
<W id="22" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="23" tag="NNP" in="-1:nobj" out="">Hafnia</W>
<W id="24" tag="," in="-7:pnct" out="">,</W>
<W id="25" tag="IN" in="-8:mod" out="2:vobj">if</W>
<W id="26" tag="PRP" in="1:subj|2:[subj]|3:[subj]" out="">we</W>
<W id="27" tag="MD" in="-2:vobj" out="-1:subj|1:vobj">could</W>
<W id="28" tag="VB" in="-1:vobj" out="-2:[subj]|1:vobj">have</W>
<W id="29" tag="VBN" in="-1:vobj" out="-3:[subj]|1:dobj">foreseen</W>
<W id="30" tag="DT" in="-1:dobj" out="1:mod|3:nobj|4:mod">the</W>
<W id="31" tag="JJ" in="-1:mod" out="">large</W>
<W id="32" tag="NN" in="1:mod" out="">price</W>
<W id="33" tag="NN" in="-3:nobj" out="-1:mod">decline</W>
<W id="34" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="35" tag="NNP" in="-1:nobj" out="1:mod|2:possd|3:mod">Hafnia's</W>
<W id="36" tag="JJ" in="-1:mod" out="">strategic</W>
<W id="37" tag="NNS" in="-2:possd" out="">holdings</W>
<W id="38" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="39" tag="NNP" in="-1:nobj" out="1:coord">Baltica</W>
<W id="40" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="41" tag="NNP" in="-1:conj" out="">Skandia</W>
<W id="42" tag="," in="-39:pnct" out="">,</W>
<W id="43" tag="&amp;quot;" in="-40:pnct" out="">"</W>
<W id="44" tag="VBZ" in="" out="-41:qobj|2:subj|3:pnct">says</W>
<W id="45" tag="NNP" in="1:namef" out="">Bent</W>
<W id="46" tag="NNP" in="-2:subj" out="-1:namef">Knie-Andersen</W>
<W id="47" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W id="50" tag="IN" in="10:pred" out="1:nobj">Among</W>
<W id="51" tag="DT" in="-1:nobj" out="1:nobj|2:ref|3:rel">the</W>
<W id="52" tag="NNS" in="-1:nobj" out="">companies</W>
<W id="53" tag="WDT" in="-2:ref|1:subj" out="">that</W>
<W id="54" tag="VBP" in="-3:rel" out="-1:subj|1:pred">are</W>
<W id="55" tag="DT" in="-1:pred" out="2:mod|4:nobj">the</W>
<W id="56" tag="RBS" in="1:mod" out="">most</W>
<W id="57" tag="RB" in="-2:mod" out="-1:mod">obviously</W>
<W id="58" tag="VBZ" in="1:mod" out="">sales</W>
<W id="59" tag="NNS" in="-4:nobj" out="-1:mod">topics</W>
<W id="60" tag="VBP" in="" out="-10:pred|1:subj|28:pnct">are</W>
<W id="61" tag="NNP" in="-1:subj" out="1:nobj|2:pnct|3:conj|6:pnct|7:coord">Hafnia</W>
<W id="62" tag="NNP" in="-1:nobj" out="">Bank</W>
<W id="63" tag="," in="-2:pnct" out="">,</W>
<W id="64" tag="DT" in="-3:conj" out="1:mod|2:nobj">the</W>
<W id="65" tag="NNP" in="-1:mod" out="">English</W>
<W id="66" tag="NNP" in="-2:nobj" out="">Prolific</W>
<W id="67" tag="," in="-6:pnct" out="">,</W>
<W id="68" tag="CC" in="-7:coord" out="1:conj">and</W>
<W id="69" tag="DT" in="-1:conj" out="1:mod|3:nobj|4:pnct|5:mod">the</W>
<W id="70" tag="VBG" in="-1:mod" out="">underlying</W>
<W id="71" tag="NN" in="1:mod" out="">insurance</W>
<W id="72" tag="NNS" in="-3:nobj" out="-1:mod">companies</W>
<W id="73" tag="," in="-4:pnct" out="">,</W>
<W id="74" tag="JJ" in="-5:mod" out="1:pobj">such</W>
<W id="75" tag="IN" in="-1:pobj" out="1:nobj">as</W>
<W id="76" tag="NNP" in="-1:nobj" out="1:nobj|3:pnct|4:conj|7:coord">Hafnia</W>
<W id="77" tag="NNP" in="-1:nobj" out="1:nobj">Motor</W>
<W id="78" tag="NNP" in="-1:nobj" out="">Insurance</W>
<W id="79" tag="," in="-3:pnct" out="">,</W>
<W id="80" tag="NNP" in="-4:conj" out="2:nobj">Hafnia</W>
<W id="81" tag="NNP" in="1:mod" out="">Occupational</W>
<W id="82" tag="NNP" in="-2:nobj" out="-1:mod">Injury</W>
<W id="83" tag="CC" in="-7:coord" out="1:conj">and</W>
<W id="84" tag="NNP" in="-1:conj" out="1:nobj">Hafnia</W>
<W id="85" tag="NNP" in="-1:nobj" out="1:coord">Marine</W>
<W id="86" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="87" tag="NN" in="-1:conj" out="">Industry</W>
<W id="88" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W id="91" tag="DT" in="16:subj|21:[subj]" out="2:nobj|3:appr|4:pnct|5:ref|7:rel">The</W>
<W id="92" tag="NNS" in="1:mod" out="">savings</W>
<W id="93" tag="VBP" in="-2:nobj" out="-1:mod">bank</W>
<W id="94" tag="NNP" in="-3:appr" out="">Bikuben</W>
<W id="95" tag="," in="-4:pnct" out="">,</W>
<W id="96" tag="WDT" in="-5:ref|2:subj" out="">which</W>
<W id="97" tag="RB" in="1:mod" out="">previously</W>
<W id="98" tag="VBD" in="-7:rel" out="-2:subj|-1:mod|1:dobj|8:pnct">bought</W>
<W id="99" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="100" tag="JJ" in="-1:mod" out="">large</W>
<W id="101" tag="NN" in="-2:nobj" out="1:pobj">share</W>
<W id="102" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="103" tag="NNP" in="-1:nobj" out="2:nobj">Hafnia</W>
<W id="104" tag="NNP" in="1:mod" out="">Capital</W>
<W id="105" tag="NNP" in="-2:nobj" out="-1:mod">Bank</W>
<W id="106" tag="," in="-8:pnct" out="">,</W>
<W id="107" tag="VBZ" in="" out="-16:subj|1:mod|2:mod|5:vobj|11:pnct">is</W>
<W id="108" tag="RB" in="-1:mod" out="">not</W>
<W id="109" tag="IN" in="-2:mod" out="1:nobj">at</W>
<W id="110" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="111" tag="NN" in="-1:nobj" out="">moment</W>
<W id="112" tag="JJ" in="-5:vobj" out="-21:[subj]|1:pobj">interested</W>
<W id="113" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W id="114" tag="DT" in="-1:nobj" out="1:mod|3:nobj">a</W>
<W id="115" tag="JJ" in="-1:mod" out="">new</W>
<W id="116" tag="NN" in="1:mod" out="">bank</W>
<W id="117" tag="NN" in="-3:nobj" out="-1:mod">purchase</W>
<W id="118" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W id="121" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W id="122" tag="PRP" in="1:subj" out="">We</W>
<W id="123" tag="VBP" in="9:qobj" out="-2:pnct|-1:subj|1:dobj|7:pnct|8:pnct">have</W>
<W id="124" tag="DT" in="-1:dobj" out="1:mod|2:nobj">no</W>
<W id="125" tag="JJ" in="-1:mod" out="">strategic</W>
<W id="126" tag="NN" in="-2:nobj" out="1:pobj">interest</W>
<W id="127" tag="IN" in="-1:pobj" out="1:nobj">in</W>
<W id="128" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W id="129" tag="NNP" in="-1:nobj" out="">Bank</W>
<W id="130" tag="," in="-7:pnct" out="">,</W>
<W id="131" tag="&amp;quot;" in="-8:pnct" out="">"</W>
<W id="132" tag="VBZ" in="" out="-9:qobj|3:subj|6:pnct">says</W>
<W id="133" tag="NN" in="2:title" out="">director</W>
<W id="134" tag="NNP" in="1:namef" out="">Tommy</W>
<W id="135" tag="NNP" in="-3:subj" out="-2:title|-1:namef|1:pnct|2:mod">Petersen</W>
<W id="136" tag="," in="-1:pnct" out="">,</W>
<W id="137" tag="NNP" in="-2:mod" out="">Bikuben</W>
<W id="138" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W id="141" tag="NNP" in="1:subj|5:[subj]|7:[subj]" out="">Hafnia</W>
<W id="142" tag="MD" in="" out="-1:subj|1:mod|4:vobj|14:pnct|15:coord|40:pnct">will</W>
<W id="143" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="144" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="145" tag="JJ" in="-1:nobj" out="">future</W>
<W id="146" tag="NN" in="-4:vobj" out="-5:[subj]|1:dobj">have</W>
<W id="147" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="148" tag="VB" in="-1:vobj" out="-7:[subj]|1:mod|2:pobj">concentrate</W>
<W id="149" tag="RB" in="-1:mod" out="">only</W>
<W id="150" tag="IN" in="-2:pobj" out="1:nobj">on</W>
<W id="151" tag="PRP$" in="-1:nobj" out="1:mod|2:possd">its</W>
<W id="152" tag="JJ" in="-1:mod" out="">own</W>
<W id="153" tag="NNS" in="-2:possd" out="1:coord">companies</W>
<W id="154" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="155" tag="NNS" in="-1:conj" out="">assets</W>
<W id="156" tag="," in="-14:pnct" out="">,</W>
<W id="157" tag="CC" in="-15:coord" out="19:conj">but</W>
<W id="158" tag="RB" in="1:mod" out="">even</W>
<W id="159" tag="NNP" in="17:subj|19:[subj]|21:[subj]" out="-1:mod|3:possd|4:pnct|5:ref|7:rel">Hafnia's</W>
<W id="160" tag="NN" in="1:mod" out="">life</W>
<W id="161" tag="NN" in="1:mod" out="-1:mod">insurance</W>
<W id="162" tag="NNS" in="-3:possd" out="-1:mod">companies</W>
<W id="163" tag="," in="-4:pnct" out="">,</W>
<W id="164" tag="WDT" in="-5:ref|3:subj" out="">which</W>
<W id="165" tag="JJ" in="1:subj" out="">many</W>
<W id="166" tag="VBP" in="-7:rel" out="-1:subj|1:vobj|9:pnct">believe</W>
<W id="167" tag="VBP" in="-1:vobj" out="-3:subj|1:pred">are</W>
<W id="168" tag="IN" in="-1:pred" out="1:nobj">among</W>
<W id="169" tag="DT" in="-1:nobj" out="1:nobj|3:mod|5:possd">the</W>
<W id="170" tag="NNS" in="-1:nobj" out="">group's</W>
<W id="171" tag="RBS" in="1:mod" out="">most</W>
<W id="172" tag="JJ" in="-3:mod" out="-1:mod">important</W>
<W id="173" tag="NN" in="1:mod" out="">gold</W>
<W id="174" tag="NNS" in="-5:possd" out="-1:mod">eggs</W>
<W id="175" tag="," in="-9:pnct" out="">,</W>
<W id="176" tag="VBP" in="-19:conj" out="-17:subj|1:mod|2:vobj">are</W>
<W id="177" tag="RB" in="-1:mod" out="">now</W>
<W id="178" tag="VBN" in="-2:vobj" out="-19:[subj]|1:dobj">considered</W>
<W id="179" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="180" tag="VB" in="-1:vobj" out="-21:[subj]|1:pred">be</W>
<W id="181" tag="VBN" in="-1:pred" out="">overvalued</W>
<W id="182" tag="." in="-40:pnct" out="">.</W>
</s>
<s>
<W id="185" tag="JJ" in="1:mod" out="">Doubtful</W>
<W id="186" tag="NN" in="" out="-1:mod|1:pobj">value</W>
<W id="187" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="188" tag="NNP" in="-1:nobj" out="1:nobj">Hafnia</W>
<W id="189" tag="NNP" in="-1:nobj" out="">Life</W>
</s>
<s>
<W id="192" tag="NN" in="1:mod" out="">Finance</W>
<W id="193" tag="NNS" in="1:subj" out="-1:mod">sources</W>
<W id="194" tag="VBP" in="" out="-1:subj|1:dobj|15:pnct">say</W>
<W id="195" tag="IN" in="-1:dobj" out="5:vobj">that</W>
<W id="196" tag="DT" in="4:subj" out="3:nobj">the</W>
<W id="197" tag="NN" in="1:mod" out="">life</W>
<W id="198" tag="NN" in="1:mod" out="-1:mod">insurance</W>
<W id="199" tag="NN" in="-3:nobj" out="-1:mod">company</W>
<W id="200" tag="VBZ" in="-5:vobj" out="-4:subj|1:mod|2:pred">is</W>
<W id="201" tag="RB" in="-1:mod" out="">not</W>
<W id="202" tag="JJ" in="-2:pred" out="3:mod">worth</W>
<W id="203" tag="RB" in="1:mod" out="">nearly</W>
<W id="204" tag="RB" in="1:mod" out="-1:mod|2:pobj">so</W>
<W id="205" tag="JJ" in="-3:mod" out="-1:mod">much</W>
<W id="206" tag="IN" in="-2:pobj" out="2:vobj">as</W>
<W id="207" tag="RB" in="1:mod" out="">hitherto</W>
<W id="208" tag="VBN" in="-2:vobj" out="-1:mod">presumed</W>
<W id="209" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="212" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="213" tag="IN" in="" out="-1:pnct|1:vobj|7:pnct|8:coord">As</W>
<W id="214" tag="VBN" in="-1:vobj" out="1:pobj">opposed</W>
<W id="215" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="216" tag="VB" in="-1:nobj" out="1:nobj">many</W>
<W id="217" tag="JJ" in="-1:nobj" out="2:nobj">other</W>
<W id="218" tag="NN" in="1:mod" out="">insurance</W>
<W id="219" tag="NNS" in="-2:nobj" out="-1:mod">companies</W>
<W id="220" tag="&3a;" in="-7:pnct" out="">-</W>
<W id="221" tag="CC" in="-8:coord" out="2:conj|3:pnct">but</W>
<W id="222" tag="RB" in="1:mod" out="">completely</W>
<W id="223" tag="JJ" in="-2:conj" out="-1:mod">legal</W>
<W id="224" tag="&3a;" in="-3:pnct" out="">-</W>
</s>
