<s>
<W id="1" tag="CD" in="" out="2:nobj|3:pnct|4:ref|12:rel|15:pnct">Two</W>
<W id="2" tag="NN" in="1:mod" out="">crowd</W>
<W id="3" tag="NNS" in="-2:nobj" out="-1:mod">magnets</W>
<W id="4" tag="," in="-3:pnct" out="">,</W>
<W id="5" tag="WDT" in="-4:ref|8:subj" out="1:pnct">which</W>
<W id="6" tag="&3a;" in="-1:pnct" out="">-</W>
<W id="7" tag="DT" in="1:mod" out="">each</W>
<W id="8" tag="IN" in="5:mod" out="-1:mod|1:nobj|4:pnct">in</W>
<W id="9" tag="PRP$" in="-1:nobj" out="1:mod|2:possd">their</W>
<W id="10" tag="JJ" in="-1:mod" out="">own</W>
<W id="11" tag="NN" in="-2:possd" out="">way</W>
<W id="12" tag="&3a;" in="-4:pnct" out="">-</W>
<W id="13" tag="VB" in="-12:rel" out="-8:subj|-5:mod|2:dobj">portray</W>
<W id="14" tag="JJ" in="1:mod" out="">modern</W>
<W id="15" tag="NNP" in="-2:dobj" out="-1:mod">Paris</W>
<W id="16" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="19" tag="JJ" in="1:mod" out="">French</W>
<W id="20" tag="NN" in="" out="-1:mod">cocktail</W>
<W id="21" tag="NNP" in="2:subj" out="1:name">Place</W>
<W id="22" tag="NNP" in="-1:name" out="">Clichy</W>
<W id="23" tag="VBZ" in="" out="-2:subj|1:pred|6:pnct">is</W>
<W id="24" tag="DT" in="-1:pred" out="1:mod|4:nobj">a</W>
<W id="25" tag="JJ" in="-1:mod" out="1:coord">beautiful</W>
<W id="26" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="27" tag="JJ" in="-1:conj" out="">decorative</W>
<W id="28" tag="NN" in="-4:nobj" out="">square</W>
<W id="29" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W id="32" tag="PRP" in="1:subj|2:[subj]" out="">It</W>
<W id="33" tag="MD" in="" out="-1:subj|1:vobj|19:pnct">could</W>
<W id="34" tag="VB" in="-1:vobj" out="-2:[subj]|1:pred|4:pobj">be</W>
<W id="35" tag="DT" in="-1:pred" out="2:nobj">the</W>
<W id="36" tag="NN" in="1:mod" out="">background</W>
<W id="37" tag="NN" in="-2:nobj" out="-1:mod">scenery</W>
<W id="38" tag="IN" in="-4:pobj" out="1:nobj">for</W>
<W id="39" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:pnct|5:appa">any</W>
<W id="40" tag="JJ" in="-1:mod" out="">French</W>
<W id="41" tag="NN" in="-2:nobj" out="">film</W>
<W id="42" tag="&3a;" in="-3:pnct" out="">-</W>
<W id="43" tag="NN" in="1:mod" out="">detective</W>
<W id="44" tag="NN" in="-5:appa" out="-1:mod|1:pnct|3:conj|4:coord">movie</W>
<W id="45" tag="," in="-1:pnct" out="">,</W>
<W id="46" tag="JJ" in="1:mod" out="">psychological</W>
<W id="47" tag="NN" in="-3:conj" out="-1:mod">thriller</W>
<W id="48" tag="CC" in="-4:coord" out="3:conj">or</W>
<W id="49" tag="JJ" in="2:mod" out="">steamy</W>
<W id="50" tag="NN" in="1:mod" out="">love</W>
<W id="51" tag="NN" in="-3:conj" out="-1:mod|-2:mod">movie</W>
<W id="52" tag="." in="-19:pnct" out="">.</W>
</s>
<s>
<W id="55" tag="IN" in="6:mod" out="1:mod|3:pnct">Outside</W>
<W id="56" tag="IN" in="-1:mod" out="1:nobj">of</W>
<W id="57" tag="NNP" in="-1:nobj" out="">France</W>
<W id="58" tag="," in="-3:pnct" out="">,</W>
<W id="59" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W id="60" tag="NN" in="-1:nobj" out="">square</W>
<W id="61" tag="MD" in="" out="-2:subj|-6:mod|1:vobj|40:pnct">may</W>
<W id="62" tag="VB" in="-1:vobj" out="-3:[subj]|2:pred">be</W>
<W id="63" tag="RBS" in="1:mod" out="">best</W>
<W id="64" tag="VBN" in="-2:pred" out="-1:mod|1:pobj">known</W>
<W id="65" tag="IN" in="-1:pobj" out="2:nobj">from</W>
<W id="66" tag="NNP" in="1:namef" out="">Henry</W>
<W id="67" tag="NNP" in="-2:nobj" out="-1:namef|1:mod|2:possd|5:appr|9:pnct|10:ref|12:rel">Miller's</W>
<W id="68" tag="JJ" in="-1:mod" out="">juicy</W>
<W id="69" tag="NN" in="-2:possd" out="">novel</W>
<W id="70" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W id="71" tag="NNP" in="1:mod" out="">Quiet</W>
<W id="72" tag="NNP" in="-5:appr" out="-2:pnct|-1:mod|1:mod|3:pnct">Days</W>
<W id="73" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="74" tag="NNP" in="-1:nobj" out="">Clichy</W>
<W id="75" tag="&amp;quot;" in="-3:pnct" out="">"</W>
<W id="76" tag="," in="-9:pnct" out="">,</W>
<W id="77" tag="WRB" in="-10:ref|2:mod" out="">where</W>
<W id="78" tag="PRP" in="1:subj" out="">he</W>
<W id="79" tag="VBZ" in="-12:rel" out="-2:mod|-1:subj|1:pobj">tells</W>
<W id="80" tag="IN" in="-1:pobj" out="1:nobj">about</W>
<W id="81" tag="PRP$" in="-1:nobj" out="1:mod|2:possd|3:mod|14:mod">his</W>
<W id="82" tag="JJ" in="-1:mod" out="">bohemian</W>
<W id="83" tag="NN" in="-2:possd" out="">life</W>
<W id="84" tag="IN" in="-3:mod" out="1:nobj">among</W>
<W id="85" tag="NNS" in="-1:nobj" out="1:coord|3:pnct|4:coord">whores</W>
<W id="86" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="87" tag="NNS" in="-1:conj" out="">pimps</W>
<W id="88" tag="&3a;" in="-3:pnct" out="">-</W>
<W id="89" tag="CC" in="-4:coord" out="1:conj|5:pnct">and</W>
<W id="90" tag="NNS" in="-1:conj" out="1:mod">artists</W>
<W id="91" tag="IN" in="-1:mod" out="1:nobj">of</W>
<W id="92" tag="DT" in="-1:nobj" out="1:nobj">every</W>
<W id="93" tag="NN" in="-1:nobj" out="">sort</W>
<W id="94" tag="&3a;" in="-5:pnct" out="">-</W>
<W id="95" tag="IN" in="-14:mod" out="1:nobj">in</W>
<W id="96" tag="DT" in="-1:nobj" out="1:mod|4:nobj">the</W>
<W id="97" tag="JJ" in="-1:mod" out="1:coord">hectic</W>
<W id="98" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="99" tag="JJ" in="-1:conj" out="">chaotic</W>
<W id="100" tag="CD" in="-4:nobj" out="">1930s</W>
<W id="101" tag="." in="-40:pnct" out="">.</W>
</s>
<s>
<W id="104" tag="IN" in="8:mod" out="1:nobj|2:pnct">For</W>
<W id="105" tag="NNPS" in="-1:nobj" out="">Parisians</W>
<W id="106" tag="," in="-2:pnct" out="">,</W>
<W id="107" tag="NNP" in="5:subj" out="1:name|2:pnct">Place</W>
<W id="108" tag="NNP" in="-1:name" out="">Clichy</W>
<W id="109" tag="," in="-2:pnct" out="">,</W>
<W id="110" tag="RB" in="2:mod" out="1:pnct">however</W>
<W id="111" tag="," in="-1:pnct" out="">,</W>
<W id="112" tag="VBZ" in="" out="-8:mod|-5:subj|-2:mod|1:dobj|3:pnct">represents</W>
<W id="113" tag="NN" in="-1:dobj" out="1:mod">something</W>
<W id="114" tag="JJR" in="-1:mod" out="">more</W>
<W id="115" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W id="118" tag="NNP" in="22:subj" out="1:pnct|2:conj|3:pnct|4:conj|5:pnct|6:conj|7:pnct|9:conj|10:pnct|11:coord">Bars</W>
<W id="119" tag="," in="-1:pnct" out="">,</W>
<W id="120" tag="NNS" in="-2:conj" out="">restaurants</W>
<W id="121" tag="," in="-3:pnct" out="">,</W>
<W id="122" tag="NNS" in="-4:conj" out="">cinemas</W>
<W id="123" tag="," in="-5:pnct" out="">,</W>
<W id="124" tag="NNS" in="-6:conj" out="">theatres</W>
<W id="125" tag="," in="-7:pnct" out="">,</W>
<W id="126" tag="VBG" in="1:mod" out="">thriving</W>
<W id="127" tag="NN" in="-9:conj" out="-1:mod">business</W>
<W id="128" tag="&3a;" in="-10:pnct" out="">-</W>
<W id="129" tag="CC" in="-11:coord" out="1:mod|2:pnct|3:mod|6:conj|10:pnct">and</W>
<W id="130" tag="RB" in="-1:mod" out="">then</W>
<W id="131" tag="," in="-2:pnct" out="">,</W>
<W id="132" tag="IN" in="-3:mod" out="1:nobj|2:pnct">of</W>
<W id="133" tag="NN" in="-1:nobj" out="">course</W>
<W id="134" tag="," in="-2:pnct" out="">,</W>
<W id="135" tag="NNS" in="-6:conj" out="1:pobj">girls</W>
<W id="136" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="137" tag="JJ" in="1:mod" out="">easy</W>
<W id="138" tag="NN" in="-2:nobj" out="-1:mod">virtue</W>
<W id="139" tag="&3a;" in="-10:pnct" out="">-</W>
<W id="140" tag="VB" in="" out="-22:subj|1:dobj|18:pnct">create</W>
<W id="141" tag="DT" in="-1:dobj" out="1:nobj|2:ref|3:rel|8:ref">a</W>
<W id="142" tag="NN" in="-1:nobj" out="">cocktail</W>
<W id="143" tag="WDT" in="-2:ref|1:subj|2:[subj]" out="">that</W>
<W id="144" tag="VBP" in="-3:rel" out="-1:subj|1:vobj|4:coord">cannot</W>
<W id="145" tag="VB" in="-1:vobj" out="-2:[subj]|2:pred">be</W>
<W id="146" tag="RBR" in="1:mod" out="">more</W>
<W id="147" tag="JJ" in="-2:pred" out="-1:mod">French</W>
<W id="148" tag="CC" in="-4:coord" out="3:conj">and</W>
<W id="149" tag="WDT" in="-8:ref|4:dobj" out="">which</W>
<W id="150" tag="PRP" in="1:subj|3:[subj]" out="">one</W>
<W id="151" tag="MD" in="-3:conj" out="-1:subj|1:mod|2:vobj">can</W>
<W id="152" tag="RB" in="-1:mod" out="">hardly</W>
<W id="153" tag="VB" in="-2:vobj" out="-4:dobj|-3:[subj]|1:pred|2:mod">find</W>
<W id="154" tag="RBR" in="-1:pred" out="">better</W>
<W id="155" tag="RB" in="-2:mod" out="1:lobj">anywhere</W>
<W id="156" tag="IN" in="-1:lobj" out="1:nobj">in</W>
<W id="157" tag="NNP" in="-1:nobj" out="">Paris</W>
<W id="158" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W id="161" tag="DT" in="6:subj|10:[subj]|11:[subj]" out="1:mod|2:nobj|3:mod">An</W>
<W id="162" tag="JJ" in="-1:mod" out="">exciting</W>
<W id="163" tag="NN" in="-2:nobj" out="">evening</W>
<W id="164" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="165" tag="NNP" in="-1:nobj" out="1:possd">Paris'</W>
<W id="166" tag="NN" in="-1:possd" out="">nightlife</W>
<W id="167" tag="MD" in="" out="-6:subj|1:mod|4:vobj|17:pnct">can</W>
<W id="168" tag="TO" in="-1:mod" out="2:nobj">to</W>
<W id="169" tag="JJ" in="1:mod" out="">great</W>
<W id="170" tag="NN" in="-2:nobj" out="-1:mod">advantage</W>
<W id="171" tag="VB" in="-4:vobj" out="-10:[subj]|1:vobj">be</W>
<W id="172" tag="VBN" in="-1:vobj" out="-11:[subj]|1:pobj">introduced</W>
<W id="173" tag="IN" in="-1:pobj" out="1:nobj|3:pred">with</W>
<W id="174" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="175" tag="NN" in="-1:nobj" out="">dinner</W>
<W id="176" tag="IN" in="-3:pred" out="1:nobj">at</W>
<W id="177" tag="CD" in="-1:nobj" out="1:pobj">one</W>
<W id="178" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="179" tag="NNP" in="-1:nobj" out="1:name|2:possd">Place</W>
<W id="180" tag="NNP" in="-1:name" out="">Clichy's</W>
<W id="181" tag="JJ" in="-2:possd" out="1:mod|2:nobj">many</W>
<W id="182" tag="JJ" in="-1:mod" out="">excellent</W>
<W id="183" tag="NNS" in="-2:nobj" out="">restaurants</W>
<W id="184" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W id="187" tag="JJ" in="1:mod" out="">Spicy</W>
<W id="188" tag="NNS" in="" out="-1:mod|1:mod|4:pnct">dumplings</W>
<W id="189" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="190" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="191" tag="NN" in="-1:nobj" out="">soup</W>
<W id="192" tag="." in="-4:pnct" out="">?</W>
</s>
<s>
<W id="195" tag="PRP" in="1:subj" out="">You</W>
<W id="196" tag="VBP" in="" out="-1:subj|1:dobj|2:pnct|3:mod|34:pnct">get</W>
<W id="197" tag="PRP" in="-1:dobj" out="">them</W>
<W id="198" tag="," in="-2:pnct" out="">,</W>
<W id="199" tag="IN" in="-3:mod" out="2:vobj">if</W>
<W id="200" tag="PRP" in="1:subj" out="">you</W>
<W id="201" tag="VBP" in="-2:vobj" out="-1:subj|1:lobj">continue</W>
<W id="202" tag="RB" in="-1:lobj" out="1:nobj|4:mod">down</W>
<W id="203" tag="NNP" in="-1:nobj" out="1:name">Boulevard</W>
<W id="204" tag="NNP" in="-1:name" out="1:name">de</W>
<W id="205" tag="NNP" in="-1:name" out="">Clichy</W>
<W id="206" tag="IN" in="-4:mod" out="1:nobj">towards</W>
<W id="207" tag="NNP" in="-1:nobj" out="1:name|2:coord|5:pnct|6:ref|12:rel">Place</W>
<W id="208" tag="NNP" in="-1:name" out="">Pigalle</W>
<W id="209" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="210" tag="NNP" in="-1:conj" out="1:name">Place</W>
<W id="211" tag="NNP" in="-1:name" out="">Blanche</W>
<W id="212" tag="," in="-5:pnct" out="">,</W>
<W id="213" tag="WRB" in="-6:ref|6:mod" out="">where</W>
<W id="214" tag="JJ" in="1:mod" out="">no-nonsense</W>
<W id="215" tag="NNS" in="4:subj|10:[subj]" out="-1:mod|1:coord">nightclubs</W>
<W id="216" tag="CC" in="-1:coord" out="2:conj">and</W>
<W id="217" tag="NN" in="1:mod" out="">striptease</W>
<W id="218" tag="VBZ" in="-2:conj" out="-1:mod">shows</W>
<W id="219" tag="VBN" in="-12:rel" out="-6:mod|-4:subj|1:tobj|5:coord">run</W>
<W id="220" tag="JJ" in="-1:tobj" out="1:mod">non-stop</W>
<W id="221" tag="IN" in="-1:mod" out="1:nobj">through</W>
<W id="222" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="223" tag="NN" in="-1:nobj" out="">night</W>
<W id="224" tag="CC" in="-5:coord" out="1:conj">and</W>
<W id="225" tag="NN" in="-1:conj" out="-10:[subj]|1:dobj">offer</W>
<W id="226" tag="NN" in="-1:dobj" out="1:mod">something</W>
<W id="227" tag="IN" in="-1:mod" out="1:nobj">for</W>
<W id="228" tag="DT" in="-1:nobj" out="1:nobj">every</W>
<W id="229" tag="NN" in="-1:nobj" out="">taste</W>
<W id="230" tag="." in="-34:pnct" out="">.</W>
</s>
