<s>
<W id="1" tag="RB" in="15:mod" out="1:pnct">Thus</W>
<W id="2" tag="," in="-1:pnct" out="">,</W>
<W id="3" tag="NNS" in="13:subj" out="1:pobj">months</W>
<W id="4" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="5" tag="NN" in="-1:nobj" out="1:pobj">uncertainty</W>
<W id="6" tag="IN" in="-1:pobj" out="1:nobj">about</W>
<W id="7" tag="DT" in="-1:nobj" out="1:nobj|2:mod|6:mod">the</W>
<W id="8" tag="NN" in="-1:nobj" out="">status</W>
<W id="9" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="10" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="11" tag="CD" in="-1:nobj" out="1:nobj">two</W>
<W id="12" tag="NNS" in="-1:nobj" out="">republics</W>
<W id="13" tag="IN" in="-6:mod" out="2:nobj">in</W>
<W id="14" tag="JJ" in="1:mod" out="">international</W>
<W id="15" tag="NN" in="-2:nobj" out="-1:mod">law</W>
<W id="16" tag="VBD" in="" out="-15:mod|-13:subj|1:pnct|2:coord|25:pnct">ended</W>
<W id="17" tag="," in="-1:pnct" out="">,</W>
<W id="18" tag="CC" in="-2:coord" out="4:conj">and</W>
<W id="19" tag="DT" in="3:subj|5:[subj]" out="1:mod|2:nobj">the</W>
<W id="20" tag="JJ" in="-1:mod" out="">old</W>
<W id="21" tag="NNP" in="-2:nobj" out="">Yugoslavia</W>
<W id="22" tag="VBD" in="-4:conj" out="-3:subj|1:dobj|3:mod">ceased</W>
<W id="23" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="24" tag="VB" in="-1:vobj" out="-5:[subj]">exist</W>
<W id="25" tag="IN" in="-3:mod" out="1:nobj">for</W>
<W id="26" tag="NN" in="-1:nobj" out="1:nobj">everyone</W>
<W id="27" tag="JJ" in="-1:nobj" out="1:pobj">other</W>
<W id="28" tag="IN" in="-1:pobj" out="1:nobj">than</W>
<W id="29" tag="NNP" in="-1:nobj" out="1:pnct|2:ref|6:rel">Serbs</W>
<W id="30" tag="," in="-1:pnct" out="">,</W>
<W id="31" tag="WP" in="-2:ref|4:subj|5:[subj]" out="">who</W>
<W id="32" tag="JJ" in="2:mod" out="">late</W>
<W id="33" tag="JJ" in="1:mod" out="">last</W>
<W id="34" tag="NN" in="1:mod" out="-1:mod|-2:mod">summer</W>
<W id="35" tag="VBD" in="-6:rel" out="-4:subj|-1:mod|1:vobj">had</W>
<W id="36" tag="VBN" in="-1:vobj" out="-5:[subj]|1:dobj">conducted</W>
<W id="37" tag="NN" in="-1:dobj" out="1:pobj">war</W>
<W id="38" tag="IN" in="-1:pobj" out="1:nobj">against</W>
<W id="39" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="40" tag="NNPS" in="-1:nobj" out="">Croatians</W>
<W id="41" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W id="44" tag="DT" in="10:subj" out="1:nobj|5:pnct|6:modp">The</W>
<W id="45" tag="NNP" in="-1:nobj" out="1:possd">EC's</W>
<W id="46" tag="JJ" in="-1:possd" out="2:nobj">other</W>
<W id="47" tag="NN" in="1:mod" out="">member</W>
<W id="48" tag="NNS" in="-2:nobj" out="-1:mod">states</W>
<W id="49" tag="," in="-5:pnct" out="">,</W>
<W id="50" tag="VBG" in="-6:modp" out="1:dobj|2:pnct">including</W>
<W id="51" tag="NNP" in="-1:dobj" out="">Denmark</W>
<W id="52" tag="," in="-2:pnct" out="">,</W>
<W id="53" tag="RB" in="1:mod" out="">likewise</W>
<W id="54" tag="VBN" in="" out="-10:subj|-1:mod|1:dobj|4:mod|5:pnct">recognised</W>
<W id="55" tag="NNP" in="-1:dobj" out="1:coord">Croatia</W>
<W id="56" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="57" tag="NNP" in="-1:conj" out="">Slovenia</W>
<W id="58" tag="NN" in="-4:mod" out="">yesterday</W>
<W id="59" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W id="62" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="63" tag="CC" in="11:qobj" out="-1:pnct|2:conj|9:pnct|10:pnct">But</W>
<W id="64" tag="PRP" in="1:subj" out="">they</W>
<W id="65" tag="VBP" in="-2:conj" out="-1:subj|1:dobj|3:vobj">let</W>
<W id="66" tag="DT" in="-1:dobj|2:[subj]" out="1:nobj">the</W>
<W id="67" tag="NNPS" in="-1:nobj" out="">Germans</W>
<W id="68" tag="VBP" in="-3:vobj" out="-2:[subj]|1:dobj">do</W>
<W id="69" tag="DT" in="-1:dobj" out="1:mod|2:nobj">the</W>
<W id="70" tag="JJ" in="-1:mod" out="">dirty</W>
<W id="71" tag="NN" in="-2:nobj" out="">work</W>
<W id="72" tag="," in="-9:pnct" out="">,</W>
<W id="73" tag="&amp;quot;" in="-10:pnct" out="">"</W>
<W id="74" tag="VBD" in="" out="-11:qobj|1:subj|4:pnct|5:mod|28:pnct">commented</W>
<W id="75" tag="DT" in="-1:subj" out="1:mod|2:nobj">a</W>
<W id="76" tag="NNP" in="-1:mod" out="">Croatian</W>
<W id="77" tag="NN" in="-2:nobj" out="">official</W>
<W id="78" tag="," in="-4:pnct" out="">,</W>
<W id="79" tag="WRB" in="-5:mod" out="4:vobj">when</W>
<W id="80" tag="DT" in="3:subj" out="2:nobj">the</W>
<W id="81" tag="NN" in="1:mod" out="">champagne</W>
<W id="82" tag="NNS" in="-2:nobj" out="-1:mod">corks</W>
<W id="83" tag="VBD" in="-4:vobj" out="-3:subj|1:lobj|4:coord">flew</W>
<W id="84" tag="IN" in="-1:lobj" out="1:nobj">through</W>
<W id="85" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="86" tag="NN" in="-1:nobj" out="">air</W>
<W id="87" tag="CC" in="-4:coord" out="8:conj">and</W>
<W id="88" tag="NNP" in="7:subj" out="1:mod|2:possd|3:pnct|5:appa">Bonn's</W>
<W id="89" tag="JJ" in="-1:mod" out="">special</W>
<W id="90" tag="NN" in="-2:possd" out="">envoy</W>
<W id="91" tag="," in="-3:pnct" out="">,</W>
<W id="92" tag="NNP" in="1:namef" out="">Klaus-Peter</W>
<W id="93" tag="NNP" in="-5:appa" out="-1:namef|1:pnct">Klaiber</W>
<W id="94" tag="," in="-1:pnct" out="">,</W>
<W id="95" tag="VBN" in="-8:conj" out="-7:subj|1:dobj|2:pobj">exchanged</W>
<W id="96" tag="NNS" in="-1:dobj" out="">handshakes</W>
<W id="97" tag="IN" in="-2:pobj" out="1:nobj">with</W>
<W id="98" tag="NNP" in="-1:nobj" out="1:possd|3:appr">Croatia's</W>
<W id="99" tag="NNP" in="-1:possd" out="">President</W>
<W id="100" tag="NNP" in="1:namef" out="">Franjo</W>
<W id="101" tag="NNP" in="-3:appr" out="-1:namef">Tudjman</W>
<W id="102" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W id="105" tag="DT" in="2:subj" out="1:nobj">The</W>
<W id="106" tag="NN" in="-1:nobj" out="">official</W>
<W id="107" tag="VBD" in="" out="-2:subj|1:pobj|32:pnct">alluded</W>
<W id="108" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="109" tag="DT" in="-1:nobj|9:[dobj]" out="1:nobj|3:rel">the</W>
<W id="110" tag="NN" in="-1:nobj" out="">pressure</W>
<W id="111" tag="NNP" in="1:subj|7:[subj]" out="">Germany</W>
<W id="112" tag="VBD" in="-3:rel" out="-1:subj|1:mod|6:vobj">had</W>
<W id="113" tag="IN" in="-1:mod" out="1:nobj">for</W>
<W id="114" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="115" tag="JJ" in="-1:mod" out="">last</W>
<W id="116" tag="CD" in="-2:nobj" out="1:nobj">six</W>
<W id="117" tag="NNS" in="-1:nobj" out="">months</W>
<W id="118" tag="VBP" in="-6:vobj" out="-9:[dobj]|-7:[subj]|1:pobj|16:mod">put</W>
<W id="119" tag="IN" in="-1:pobj" out="4:nobj">on</W>
<W id="120" tag="RBR" in="1:mod" out="">more</W>
<W id="121" tag="JJ" in="2:mod" out="-1:mod">reluctant</W>
<W id="122" tag="NNP" in="1:mod" out="">EC</W>
<W id="123" tag="NNS" in="-4:nobj" out="-2:mod|-1:mod|1:pnct|2:mod">members</W>
<W id="124" tag="," in="-1:pnct" out="">,</W>
<W id="125" tag="JJ" in="-2:mod" out="1:mod|8:pnct">such</W>
<W id="126" tag="IN" in="-1:mod" out="2:nobj">as</W>
<W id="127" tag="NNP" in="1:mod" out="">Great</W>
<W id="128" tag="NNP" in="-2:nobj" out="-1:mod|1:pnct|2:conj|3:coord">Britain</W>
<W id="129" tag="," in="-1:pnct" out="">,</W>
<W id="130" tag="NNP" in="-2:conj" out="">France</W>
<W id="131" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="132" tag="NNP" in="-1:conj" out="">Greece</W>
<W id="133" tag="," in="-8:pnct" out="">,</W>
<W id="134" tag="TO" in="-16:mod" out="1:vobj">to</W>
<W id="135" tag="VB" in="-1:vobj" out="1:dobj">recognise</W>
<W id="136" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="137" tag="CD" in="-1:nobj" out="1:nobj">two</W>
<W id="138" tag="NNS" in="-1:nobj" out="">republics</W>
<W id="139" tag="." in="-32:pnct" out="">.</W>
</s>
<s>
<W id="142" tag="CC" in="" out="1:vobj">Nor</W>
<W id="143" tag="VBD" in="-1:vobj" out="1:subj|2:mod|6:pred|7:pnct|8:coord|42:pnct">was</W>
<W id="144" tag="NNP" in="-1:subj" out="">Denmark</W>
<W id="145" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="146" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="147" tag="VBG" in="-1:nobj" out="">beginning</W>
<W id="148" tag="RB" in="1:mod" out="">especially</W>
<W id="149" tag="JJ" in="-6:pred" out="-1:mod">enthusiastic</W>
<W id="150" tag="," in="-7:pnct" out="">,</W>
<W id="151" tag="CC" in="-8:coord" out="9:conj">and</W>
<W id="152" tag="NN" in="8:mod" out="">yesterday</W>
<W id="153" tag="DT" in="7:subj" out="1:nobj|5:mod">the</W>
<W id="154" tag="NNP" in="-1:nobj" out="1:pobj">Ministry</W>
<W id="155" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="156" tag="NNP" in="1:mod" out="">Foreign</W>
<W id="157" tag="NNP" in="-2:nobj" out="-1:mod">Affairs</W>
<W id="158" tag="IN" in="-5:mod" out="1:nobj">in</W>
<W id="159" tag="NNP" in="-1:nobj" out="">Copenhagen</W>
<W id="160" tag="VBD" in="-9:conj" out="-8:mod|-7:subj|1:dobj">avoided</W>
<W id="161" tag="VBG" in="-1:dobj" out="1:dobj|3:lobj|7:mod">sending</W>
<W id="162" tag="DT" in="-1:dobj" out="1:nobj">an</W>
<W id="163" tag="NN" in="-1:nobj" out="">ambassador</W>
<W id="164" tag="TO" in="-3:lobj" out="1:nobj">to</W>
<W id="165" tag="NNP" in="-1:nobj" out="1:coord">Croatia</W>
<W id="166" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="167" tag="NNP" in="-1:conj" out="">Slovenia</W>
<W id="168" tag="IN" in="-7:mod" out="1:nobj">with</W>
<W id="169" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:ref|4:rel">the</W>
<W id="170" tag="JJ" in="-1:mod" out="">same</W>
<W id="171" tag="NN" in="-2:nobj" out="">speed</W>
<W id="172" tag="IN" in="-3:ref|1:mod" out="">as</W>
<W id="173" tag="VBD" in="-4:rel" out="-1:mod|1:vobj">was</W>
<W id="174" tag="VBN" in="-1:vobj" out="1:mod|4:mod">done</W>
<W id="175" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="176" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="177" tag="NN" in="-1:nobj" out="">fall</W>
<W id="178" tag="IN" in="-4:mod" out="1:nobj">with</W>
<W id="179" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="180" tag="NN" in="-1:nobj" out="">recognition</W>
<W id="181" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="182" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="183" tag="JJ" in="-1:mod" out="">Baltic</W>
<W id="184" tag="NNS" in="-2:nobj" out="">countries</W>
<W id="185" tag="." in="-42:pnct" out="">.</W>
</s>
<s>
<W id="188" tag="DT" in="14:subj" out="1:nobj|6:mod|11:pnct">The</W>
<W id="189" tag="NN" in="-1:nobj" out="1:pnct|2:coord">satisfaction</W>
<W id="190" tag="&3a;" in="-1:pnct" out="">-</W>
<W id="191" tag="CC" in="-2:coord" out="1:conj|2:pnct">and</W>
<W id="192" tag="JJ" in="-1:conj" out="">self-satisfaction</W>
<W id="193" tag="&3a;" in="-2:pnct" out="">-</W>
<W id="194" tag="IN" in="-6:mod" out="1:nobj">of</W>
<W id="195" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="196" tag="NNPS" in="-1:nobj" out="1:coord">Croatians</W>
<W id="197" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="198" tag="NNPS" in="-1:conj" out="">Slovenians</W>
<W id="199" tag="," in="-11:pnct" out="">,</W>
<W id="200" tag="RB" in="2:mod" out="1:pnct">however</W>
<W id="201" tag="," in="-1:pnct" out="">,</W>
<W id="202" tag="VBD" in="" out="-2:mod|-14:subj|1:pred|2:pnct">was</W>
<W id="203" tag="JJ" in="-1:pred" out="">untarnished</W>
<W id="204" tag="." in="-2:pnct" out="">.</W>
</s>
<s>
<W id="207" tag="IN" in="12:mod" out="1:nobj|5:pnct">In</W>
<W id="208" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="209" tag="NN" in="-1:nobj" out="">ballroom</W>
<W id="210" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="211" tag="NNP" in="-1:nobj" out="">Zagreb</W>
<W id="212" tag="," in="-5:pnct" out="">,</W>
<W id="213" tag="NNP" in="1:title" out="">President</W>
<W id="214" tag="NNP" in="5:subj" out="-1:title|2:possd|4:appr">Tudjman's</W>
<W id="215" tag="NN" in="1:mod" out="">cabinet</W>
<W id="216" tag="NN" in="-2:possd" out="-1:mod">head</W>
<W id="217" tag="NNP" in="1:namef" out="">Hrvoje</W>
<W id="218" tag="NNP" in="-4:appr" out="-1:namef">Sarinc</W>
<W id="219" tag="VBD" in="" out="-12:mod|-5:subj|1:dobj|2:lobj|15:pnct#">threw</W>
<W id="220" tag="PRP" in="-1:dobj" out="">himself</W>
<W id="221" tag="IN" in="-2:lobj" out="1:nobj">into</W>
<W id="222" tag="DT" in="-1:nobj" out="1:mod|2:nobj">an</W>
<W id="223" tag="JJ" in="-1:mod" out="">extensive</W>
<W id="224" tag="NN" in="-2:nobj" out="1:pobj">praise</W>
<W id="225" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="226" tag="PRP$" in="-1:nobj" out="1:possd|2:coord">his</W>
<W id="227" tag="NN" in="-1:possd" out="">country</W>
<W id="228" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="229" tag="PRP$" in="-1:conj" out="1:pnct|2:mod|5:possd|6:pnct">its</W>
<W id="230" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W id="231" tag="JJ" in="-2:mod" out="1:coord">successful</W>
<W id="232" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="233" tag="JJ" in="-1:conj" out="">realistic</W>
<W id="234" tag="CD" in="-5:possd|-15:pnct#" out="">policies.</W>
<W id="235" tag="&amp;quot;" in="-6:pnct" out="">"</W>
</s>
