<s>
<W id="1" tag="NNP" in="" out="">Steffensen</W>
<W id="2" tag="NNP" in="3:title" out="">Director</W>
<W id="3" tag="NNP" in="2:namef" out="">Paul</W>
<W id="4" tag="NNP" in="1:namel" out="">Berg</W>
<W id="5" tag="NNP" in="6:subj|10:[subj]" out="-3:title|-2:namef|-1:namel|1:pnct|2:ref|4:rel">Steffensen</W>
<W id="6" tag="," in="-1:pnct" out="">,</W>
<W id="7" tag="WP" in="-2:ref|2:subj" out="">who</W>
<W id="8" tag="NN" in="1:mod" out="">today</W>
<W id="9" tag="VBZ" in="-4:rel" out="-2:subj|-1:mod|1:dobj|1:pnct#">turns</W>
<W id="10" tag="CD" in="-1:dobj|-1:pnct#" out="">60,</W>
<W id="11" tag="VBZ" in="" out="-6:subj|1:mod|4:vobj|15:pnct">has</W>
<W id="12" tag="IN" in="-1:mod" out="1:nobj">for</W>
<W id="13" tag="CD" in="-1:nobj" out="1:nobj">23</W>
<W id="14" tag="NNS" in="-1:nobj" out="">years</W>
<W id="15" tag="VBD" in="-4:vobj" out="-10:[subj]|1:pobj">looked</W>
<W id="16" tag="IN" in="-1:pobj" out="3:dobj">after</W>
<W id="17" tag="JJ" in="2:mod" out="">Danish</W>
<W id="18" tag="NN" in="1:mod" out="">business</W>
<W id="19" tag="NNS" in="-3:dobj" out="-1:mod|-2:mod|1:mod">interests</W>
<W id="20" tag="IN" in="-1:mod" out="2:nobj">in</W>
<W id="21" tag="NNP" in="1:mod" out="">South</W>
<W id="22" tag="NNP" in="-2:nobj" out="-1:mod|1:coord">America</W>
<W id="23" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="24" tag="DT" in="-1:conj" out="1:nobj">the</W>
<W id="25" tag="PRP" in="-1:nobj" out="">US</W>
<W id="26" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="29" tag="PRP" in="1:subj" out="">He</W>
<W id="30" tag="VBZ" in="" out="-1:subj|1:pred|8:coord|25:pnct">is</W>
<W id="31" tag="DT" in="-1:pred" out="1:nobj">the</W>
<W id="32" tag="NN" in="-1:nobj" out="1:pobj">son</W>
<W id="33" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="34" tag="DT" in="-1:nobj" out="1:nobj|2:mod">a</W>
<W id="35" tag="NN" in="-1:nobj" out="">merchant</W>
<W id="36" tag="IN" in="-2:mod" out="1:nobj">from</W>
<W id="37" tag="VBG" in="-1:nobj" out="">Hjørring</W>
<W id="38" tag="CC" in="-8:coord" out="1:pnct|10:conj">and</W>
<W id="39" tag="," in="-1:pnct" out="">,</W>
<W id="40" tag="VBG" in="7:mod" out="1:lobj|6:pnct">coming</W>
<W id="41" tag="IN" in="-1:lobj" out="1:pobj">out</W>
<W id="42" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="43" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="44" tag="NNP" in="-1:nobj" out="1:nobj">Sindal</W>
<W id="45" tag="NNP" in="-1:nobj" out="">Academy</W>
<W id="46" tag="," in="-6:pnct" out="">,</W>
<W id="47" tag="PRP" in="1:subj" out="-7:mod">he</W>
<W id="48" tag="VBD" in="-10:conj" out="-1:subj|1:lobj">went</W>
<W id="49" tag="TO" in="-1:lobj" out="1:nobj">to</W>
<W id="50" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="51" tag="NNP" in="-1:nobj" out="1:nobj">Niels</W>
<W id="52" tag="NNP" in="-1:nobj" out="2:nobj">Brock</W>
<W id="53" tag="NNP" in="1:mod" out="">Business</W>
<W id="54" tag="NNP" in="-2:nobj" out="-1:mod">College</W>
<W id="55" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W id="58" tag="CC" in="" out="6:conj|21:pnct">And</W>
<W id="59" tag="CD" in="2:tobj" out="1:nobj">two</W>
<W id="60" tag="NNS" in="-1:nobj" out="">years</W>
<W id="61" tag="RB" in="3:mod" out="-2:tobj|1:pnct">later</W>
<W id="62" tag="," in="-1:pnct" out="">,</W>
<W id="63" tag="PRP" in="1:subj" out="">he</W>
<W id="64" tag="VBD" in="-6:conj" out="-3:mod|-1:subj|1:lobj|3:mod">travelled</W>
<W id="65" tag="TO" in="-1:lobj" out="1:nobj">to</W>
<W id="66" tag="NNP" in="-1:nobj" out="">Colombia</W>
<W id="67" tag="TO" in="-3:mod" out="1:vobj">to</W>
<W id="68" tag="VB" in="-1:vobj" out="1:pred">be</W>
<W id="69" tag="DT" in="-1:pred" out="2:nobj|3:mod">a</W>
<W id="70" tag="NN" in="1:nobj" out="">branch</W>
<W id="71" tag="NN" in="-2:nobj" out="-1:nobj">manager</W>
<W id="72" tag="IN" in="-3:mod" out="1:nobj">for</W>
<W id="73" tag="DT" in="-1:nobj" out="2:mod|4:nobj">the</W>
<W id="74" tag="NNP" in="1:mod" out="">West</W>
<W id="75" tag="NNP" in="-2:mod" out="-1:mod">Indian</W>
<W id="76" tag="NNP" in="1:mod" out="">Trade</W>
<W id="77" tag="NNP" in="-4:nobj" out="-1:mod|1:name">Company</W>
<W id="78" tag="NNP" in="-1:name" out="">SA</W>
<W id="79" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W id="82" tag="IN" in="5:mod" out="2:nobj|3:pnct">In</W>
<W id="83" tag="NNP" in="1:mod" out="">South</W>
<W id="84" tag="NNP" in="-2:nobj" out="-1:mod">America</W>
<W id="85" tag="," in="-3:pnct" out="">,</W>
<W id="86" tag="PRP" in="1:subj" out="">he</W>
<W id="87" tag="VBD" in="" out="-5:mod|-1:subj|1:dobj|5:pnct">found</W>
<W id="88" tag="PRP$" in="-1:dobj" out="1:possd|2:pnct|3:appa">his</W>
<W id="89" tag="NN" in="-1:possd" out="">spouse</W>
<W id="90" tag="," in="-2:pnct" out="">,</W>
<W id="91" tag="NNP" in="-3:appa" out="">Niva</W>
<W id="92" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W id="95" tag="NNP" in="2:namef" out="">Paul</W>
<W id="96" tag="NNP" in="1:namel" out="">B.</W>
<W id="97" tag="NNP" in="1:subj|10:[subj]" out="-2:namef|-1:namel">Steffensen</W>
<W id="98" tag="VBD" in="" out="-1:subj|1:pred|4:mod|7:coord|21:pnct">was</W>
<W id="99" tag="DT" in="-1:pred" out="2:nobj">the</W>
<W id="100" tag="NN" in="1:mod" out="">branch</W>
<W id="101" tag="NN" in="-2:nobj" out="-1:mod">manager</W>
<W id="102" tag="IN" in="-4:mod" out="1:nobj">for</W>
<W id="103" tag="CD" in="-1:nobj" out="1:nobj">six</W>
<W id="104" tag="NNS" in="-1:nobj" out="">years</W>
<W id="105" tag="CC" in="-7:coord" out="2:conj">and</W>
<W id="106" tag="RB" in="1:mod" out="">then</W>
<W id="107" tag="VBD" in="-2:conj" out="-1:mod|-10:[subj]|1:dobj|7:mod">took</W>
<W id="108" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:mod">a</W>
<W id="109" tag="VBG" in="-1:mod" out="">continuing</W>
<W id="110" tag="NN" in="-2:nobj" out="">education</W>
<W id="111" tag="IN" in="-3:mod" out="2:nobj">in</W>
<W id="112" tag="NNP" in="1:mod" out="">Business</W>
<W id="113" tag="NNP" in="-2:nobj" out="-1:mod">Administration</W>
<W id="114" tag="IN" in="-7:mod" out="1:nobj">at</W>
<W id="115" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="116" tag="NNP" in="-1:nobj" out="1:pobj">University</W>
<W id="117" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="118" tag="NNP" in="-1:nobj" out="">Wisconsin</W>
<W id="119" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W id="122" tag="PRP" in="1:subj|3:[subj]|8:[subj]" out="">He</W>
<W id="123" tag="VBD" in="" out="-1:subj|1:dobj|6:coord|41:pnct">decided</W>
<W id="124" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="125" tag="VB" in="-1:vobj" out="-3:[subj]|1:lobj">remain</W>
<W id="126" tag="IN" in="-1:lobj" out="1:nobj">in</W>
<W id="127" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="128" tag="PRP" in="-1:nobj" out="">US</W>
<W id="129" tag="CC" in="-6:coord" out="1:conj">and</W>
<W id="130" tag="VBD" in="-1:conj" out="-8:[subj]|2:dobj">had</W>
<W id="131" tag="NN" in="1:mod" out="">executive</W>
<W id="132" tag="NNS" in="-2:dobj" out="-1:mod|2:mod">posts</W>
<W id="133" tag="JJ" in="2:mod" out="">first</W>
<W id="134" tag="IN" in="-2:mod" out="1:nobj">at</W>
<W id="135" tag="DT" in="-1:nobj" out="-2:mod|1:nobj|4:pnct|7:conj|9:pnct|12:conj">the</W>
<W id="136" tag="NNP" in="-1:nobj" out="1:name">Carlsberg</W>
<W id="137" tag="NNP" in="-1:name" out="1:name">Agency</W>
<W id="138" tag="NNP" in="-1:name" out="">Inc.</W>
<W id="139" tag="," in="-4:pnct" out="">,</W>
<W id="140" tag="RB" in="2:mod" out="">later</W>
<W id="141" tag="NNP" in="1:mod" out="">Royal</W>
<W id="142" tag="NNP" in="-7:conj" out="-2:mod|-1:mod|1:name">System</W>
<W id="143" tag="NNP" in="-1:name" out="">Inc.</W>
<W id="144" tag="," in="-9:pnct" out="">,</W>
<W id="145" tag="RBS" in="1:mod" out="">most</W>
<W id="146" tag="RB" in="1:mod" out="-1:mod">recently</W>
<W id="147" tag="NNP" in="-12:conj" out="-1:mod|1:coord|3:name|4:pnct|5:ref|8:rel|13:coord">Bing</W>
<W id="148" tag="CC" in="-1:coord" out="1:conj">&</W>
<W id="149" tag="NNP" in="-1:conj" out="">Grøndahl</W>
<W id="150" tag="NNP" in="-3:name" out="">Inc.</W>
<W id="151" tag="," in="-4:pnct" out="">,</W>
<W id="152" tag="WP$" in="-5:ref|3:dobj|5:[dobj]" out="1:possd">whose</W>
<W id="153" tag="NN" in="-1:possd" out="">subsidiary</W>
<W id="154" tag="PRP" in="1:subj|3:[subj]" out="">he</W>
<W id="155" tag="VBD" in="-8:rel" out="-3:dobj|-1:subj|1:coord|4:pnct">began</W>
<W id="156" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="157" tag="VBN" in="-1:conj" out="-3:[subj]|-5:[dobj]|1:part">built</W>
<W id="158" tag="RP" in="-1:part" out="">up</W>
<W id="159" tag="," in="-4:pnct" out="">,</W>
<W id="160" tag="CC" in="-13:coord" out="2:conj">and</W>
<W id="161" tag="NNP" in="1:mod" out="">Royal</W>
<W id="162" tag="NNP" in="-2:conj" out="-1:mod|1:name">Copenhagen</W>
<W id="163" tag="NNP" in="-1:name" out="">Inc.</W>
<W id="164" tag="." in="-41:pnct" out="">.</W>
</s>
<s>
<W id="167" tag="IN" in="5:avobj" out="1:pobj">Along</W>
<W id="168" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="169" tag="DT" in="-1:nobj" out="1:mod|2:nobj">these</W>
<W id="170" tag="VBG" in="-1:mod" out="">changing</W>
<W id="171" tag="NNS" in="-2:nobj" out="">positions</W>
<W id="172" tag="VBD" in="" out="-5:avobj|1:subj|36:pnct">came</W>
<W id="173" tag="NNS" in="-1:subj" out="1:pobj|3:mod">positions</W>
<W id="174" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="175" tag="NN" in="-1:nobj" out="">trust</W>
<W id="176" tag="IN" in="-3:mod" out="1:nobj">on</W>
<W id="177" tag="NNS" in="-1:nobj" out="1:coord">boards</W>
<W id="178" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="179" tag="NNS" in="-1:conj" out="1:mod">organizations</W>
<W id="180" tag="JJ" in="-1:mod" out="1:pobj">such</W>
<W id="181" tag="IN" in="-1:pobj" out="1:pnct|5:nobj">as</W>
<W id="182" tag="," in="-1:pnct" out="">,</W>
<W id="183" tag="IN" in="3:modp" out="1:nobj|2:pnct">for</W>
<W id="184" tag="NN" in="-1:nobj" out="">example</W>
<W id="185" tag="," in="-2:pnct" out="">,</W>
<W id="186" tag="DT" in="-5:nobj" out="-3:modp|1:mod|2:mod|3:nobj|6:pnct|7:conj|12:pnct|13:conj|17:coord">the</W>
<W id="187" tag="NNP" in="-1:mod" out="">Danish</W>
<W id="188" tag="NNP" in="-2:mod" out="">American</W>
<W id="189" tag="NNP" in="-3:nobj" out="1:pobj">Chamber</W>
<W id="190" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="191" tag="NNP" in="-1:nobj" out="">Commerce</W>
<W id="192" tag="," in="-6:pnct" out="">,</W>
<W id="193" tag="DT" in="-7:conj" out="1:nobj">the</W>
<W id="194" tag="NNP" in="-1:nobj" out="3:nobj">Rebild</W>
<W id="195" tag="NNP" in="1:mod" out="">National</W>
<W id="196" tag="NNP" in="1:mod" out="-1:mod">Park</W>
<W id="197" tag="NNP" in="-3:nobj" out="-1:mod">Committee</W>
<W id="198" tag="," in="-12:pnct" out="">,</W>
<W id="199" tag="DT" in="-13:conj" out="2:nobj">the</W>
<W id="200" tag="NNP" in="1:mod" out="">President</W>
<W id="201" tag="NNP" in="-2:nobj" out="-1:mod|1:name">Association</W>
<W id="202" tag="NNP" in="-1:name" out="">USA</W>
<W id="203" tag="CC" in="-17:coord" out="1:conj">and</W>
<W id="204" tag="DT" in="-1:conj" out="1:mod|2:mod|3:nobj">the</W>
<W id="205" tag="NNP" in="-1:mod" out="">Danish</W>
<W id="206" tag="NNP" in="-2:mod" out="">America</W>
<W id="207" tag="NNP" in="-3:nobj" out="">Society</W>
<W id="208" tag="." in="-36:pnct" out="">.</W>
</s>
<s>
<W id="211" tag="NNP" in="2:namef" out="">Paul</W>
<W id="212" tag="NNP" in="1:namel" out="">Berg</W>
<W id="213" tag="NNP" in="1:subj" out="-2:namef|-1:namel">Steffensen</W>
<W id="214" tag="VBZ" in="" out="-1:subj|1:pred|6:pnct">is</W>
<W id="215" tag="DT" in="-1:pred" out="1:nobj">a</W>
<W id="216" tag="NNP" in="-1:nobj" out="1:pobj">Knight</W>
<W id="217" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="218" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="219" tag="NNP" in="-1:nobj" out="">Dannebrog</W>
<W id="220" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W id="223" tag="PRP" in="1:subj" out="">He</W>
<W id="224" tag="VBZ" in="" out="-1:subj|1:dobj|3:pobj|5:pnct">has</W>
<W id="225" tag="PRP$" in="-1:dobj" out="1:possd">his</W>
<W id="226" tag="NN" in="-1:possd" out="">home</W>
<W id="227" tag="IN" in="-3:pobj" out="1:nobj">in</W>
<W id="228" tag="NNP" in="-1:nobj" out="">Bronxville</W>
<W id="229" tag="." in="-5:pnct" out="">.</W>
</s>
