<s>
<W id="1" tag="IN" in="6:mod" out="1:nobj|2:pnct">In</W>
<W id="2" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W id="3" tag="," in="-2:pnct" out="">,</W>
<W id="4" tag="DT" in="3:subj" out="2:nobj">the</W>
<W id="5" tag="NN" in="1:mod" out="">forest</W>
<W id="6" tag="NN" in="-2:nobj" out="-1:mod">fire</W>
<W id="7" tag="VBD" in="" out="-6:mod|-3:subj|2:pred|25:pnct">was</W>
<W id="8" tag="RB" in="1:mod" out="2:nobj">so</W>
<W id="9" tag="JJ" in="-2:pred" out="-1:mod">severe</W>
<W id="10" tag="IN" in="-2:nobj" out="1:pnct|12:vobj">that</W>
<W id="11" tag="," in="-1:pnct" out="">,</W>
<W id="12" tag="VBG" in="10:mod" out="1:pobj|7:pnct">according</W>
<W id="13" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="14" tag="DT" in="-1:nobj" out="1:mod|3:nobj|4:appr">the</W>
<W id="15" tag="JJ" in="-1:mod" out="">Finnish</W>
<W id="16" tag="NN" in="1:mod" out="">news</W>
<W id="17" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W id="18" tag="NNP" in="-4:appr" out="">FNB</W>
<W id="19" tag="," in="-7:pnct" out="">,</W>
<W id="20" tag="DT" in="2:subj|3:[subj]|4:[subj]" out="1:nobj">the</W>
<W id="21" tag="NN" in="-1:nobj" out="">smoke</W>
<W id="22" tag="MD" in="-12:vobj" out="-2:subj|-10:mod|1:vobj">could</W>
<W id="23" tag="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W id="24" tag="VBD" in="-1:vobj" out="-4:[subj]|4:lobj">smelled</W>
<W id="25" tag="PDT" in="3:mod" out="1:nobj">all</W>
<W id="26" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="27" tag="NN" in="-1:nobj" out="">way</W>
<W id="28" tag="RP" in="-4:lobj" out="-3:mod|1:mod">up</W>
<W id="29" tag="IN" in="-1:mod" out="2:nobj">in</W>
<W id="30" tag="JJ" in="1:mod" out="">southern</W>
<W id="31" tag="NNP" in="-2:nobj" out="-1:mod">Finland</W>
<W id="32" tag="." in="-25:pnct" out="">.</W>
</s>
<s>
<W id="35" tag="IN" in="14:mod" out="1:nobj|7:pnct">After</W>
<W id="36" tag="JJ" in="-1:nobj" out="1:nobj|2:possd">several</W>
<W id="37" tag="NN" in="-1:nobj" out="">days'</W>
<W id="38" tag="NN" in="-2:possd" out="1:pobj">struggle</W>
<W id="39" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="40" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="41" tag="NN" in="-1:nobj" out="">fire</W>
<W id="42" tag="," in="-7:pnct" out="">,</W>
<W id="43" tag="DT" in="6:subj" out="3:nobj|4:mod">the</W>
<W id="44" tag="JJ" in="1:mod" out="">civil</W>
<W id="45" tag="NN" in="1:mod" out="-1:mod">defense</W>
<W id="46" tag="NNS" in="-3:nobj" out="-1:mod">resources</W>
<W id="47" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="48" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W id="49" tag="VBD" in="" out="-14:mod|-6:subj|2:pred|3:mod|5:pnct">were</W>
<W id="50" tag="RB" in="1:mod" out="">completely</W>
<W id="51" tag="VBN" in="-2:pred" out="-1:mod">exhausted</W>
<W id="52" tag="NN" in="-3:mod" out="1:nobj">yesterday</W>
<W id="53" tag="NN" in="-1:nobj" out="">afternoon</W>
<W id="54" tag="." in="-5:pnct" out="">.</W>
</s>
<s>
<W id="57" tag="DT" in="9:subj" out="1:nobj|2:mod|4:mod">The</W>
<W id="58" tag="NN" in="-1:nobj" out="">official</W>
<W id="59" tag="IN" in="-2:mod" out="1:nobj">on</W>
<W id="60" tag="NN" in="-1:nobj" out="">duty</W>
<W id="61" tag="IN" in="-4:mod" out="1:nobj">at</W>
<W id="62" tag="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W id="63" tag="JJ" in="-1:mod" out="">local</W>
<W id="64" tag="NN" in="1:mod" out="">emergency</W>
<W id="65" tag="NN" in="-3:nobj" out="-1:mod">service</W>
<W id="66" tag="VBD" in="" out="-9:subj|1:pobj|6:dobj|17:pnct">said</W>
<W id="67" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="68" tag="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W id="69" tag="JJ" in="-1:mod" out="">Swedish</W>
<W id="70" tag="NN" in="1:mod" out="">news</W>
<W id="71" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W id="72" tag="IN" in="-6:dobj" out="3:vobj">that</W>
<W id="73" tag="JJ" in="1:mod" out="">extra</W>
<W id="74" tag="NN" in="1:subj|2:[subj]|3:[subj]" out="-1:mod">material</W>
<W id="75" tag="MD" in="-3:vobj" out="-1:subj|1:vobj">would</W>
<W id="76" tag="VB" in="-1:vobj" out="-2:[subj]|1:vobj">be</W>
<W id="77" tag="VBN" in="-1:vobj" out="-3:[subj]|1:pobj">transferred</W>
<W id="78" tag="TO" in="-1:pobj" out="1:nobj|3:pobj">to</W>
<W id="79" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="80" tag="NN" in="-1:nobj" out="">island</W>
<W id="81" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W id="82" tag="NNP" in="-1:nobj" out="">Stockholm</W>
<W id="83" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W id="86" tag="NN" in="4:mod" out="1:pnct">Yesterday</W>
<W id="87" tag="," in="-1:pnct" out="">,</W>
<W id="88" tag="CD" in="2:subj" out="1:nobj">seven</W>
<W id="89" tag="NNS" in="-1:nobj" out="">helicopters</W>
<W id="90" tag="VBD" in="" out="-4:mod|-2:subj|1:dobj|2:pobj|9:coord|21:pnct">took</W>
<W id="91" tag="NN" in="-1:dobj" out="">part</W>
<W id="92" tag="IN" in="-2:pobj" out="1:nobj">in</W>
<W id="93" tag="DT" in="-1:nobj" out="3:nobj|4:mod">the</W>
<W id="94" tag="NN" in="1:mod" out="">fire</W>
<W id="95" tag="VBG" in="1:mod" out="-1:mod">fighting</W>
<W id="96" tag="NNS" in="-3:nobj" out="-1:mod">operations</W>
<W id="97" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="98" tag="NNP" in="-1:nobj" out="">Gothland</W>
<W id="99" tag="CC" in="-9:coord" out="2:conj">and</W>
<W id="100" tag="EX" in="1:expl" out="">there</W>
<W id="101" tag="VBD" in="-2:conj" out="-1:expl|1:dobj|6:pred">was</W>
<W id="102" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="103" tag="JJ" in="-1:mod" out="">certain</W>
<W id="104" tag="NN" in="-2:nobj" out="1:pobj">amount</W>
<W id="105" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="106" tag="NN" in="-1:nobj" out="">optimism</W>
<W id="107" tag="IN" in="-6:pred" out="1:nobj">among</W>
<W id="108" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="109" tag="NN" in="1:mod" out="">fire</W>
<W id="110" tag="NNS" in="-2:nobj" out="-1:mod">fighters</W>
<W id="111" tag="." in="-21:pnct" out="">.</W>
</s>
<s>
<W id="114" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W id="115" tag="NN" in="-1:nobj" out="">wind</W>
<W id="116" tag="VBD" in="" out="-2:subj|1:vobj|3:coord|8:pnct">had</W>
<W id="117" tag="VBN" in="-1:vobj" out="-3:[subj]|1:mod">subsided</W>
<W id="118" tag="RB" in="-1:mod" out="">somewhat</W>
<W id="119" tag="CC" in="-3:coord" out="3:conj">and</W>
<W id="120" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W id="121" tag="NN" in="-1:nobj" out="">fire</W>
<W id="122" tag="VBD" in="-3:conj" out="-2:subj|1:vobj">had</W>
<W id="123" tag="VBN" in="-1:vobj" out="-3:[subj]">stabilized</W>
<W id="124" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W id="127" tag="NN" in="14:mod" out="1:pnct">Yesterday</W>
<W id="128" tag="," in="-1:pnct" out="">,</W>
<W id="129" tag="DT" in="12:subj|14:[subj]" out="1:nobj|2:ref|3:rel">some</W>
<W id="130" tag="NNS" in="-1:nobj" out="">people</W>
<W id="131" tag="WP" in="-2:ref|1:subj|2:[subj]" out="">who</W>
<W id="132" tag="VBD" in="-3:rel" out="-1:subj|1:vobj">were</W>
<W id="133" tag="VBN" in="-1:vobj" out="-2:[subj]|1:mod|3:pobj">evacuated</W>
<W id="134" tag="IN" in="-1:mod" out="1:nobj">on</W>
<W id="135" tag="NNP" in="-1:nobj" out="">Friday</W>
<W id="136" tag="IN" in="-3:pobj" out="1:nobj">from</W>
<W id="137" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="138" tag="NN" in="-1:nobj" out="">city</W>
<W id="139" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="140" tag="NNP" in="-1:nobj" out="">Kräklingsbo</W>
<W id="141" tag="VBD" in="" out="-12:subj|-14:mod|1:mod|2:vobj|8:pnct">were</W>
<W id="142" tag="RB" in="-1:mod" out="">still</W>
<W id="143" tag="VBN" in="-2:vobj" out="-14:[subj]|1:mod|2:pobj">quartered</W>
<W id="144" tag="RB" in="-1:mod" out="">haphazardly</W>
<W id="145" tag="IN" in="-2:pobj" out="1:nobj">with</W>
<W id="146" tag="NNS" in="-1:nobj" out="1:coord">friends</W>
<W id="147" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="148" tag="NNS" in="-1:conj" out="">acquaintances</W>
<W id="149" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W id="152" tag="CC" in="" out="4:conj|15:pnct">But</W>
<W id="153" tag="JJ" in="3:subj|4:[subj]" out="1:pobj">many</W>
<W id="154" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="155" tag="PRP" in="-1:nobj" out="">them</W>
<W id="156" tag="VBD" in="-4:conj" out="-3:subj|1:vobj">were</W>
<W id="157" tag="VBN" in="-1:vobj" out="-4:[subj]|1:dobj">given</W>
<W id="158" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:mod">a</W>
<W id="159" tag="JJ" in="-1:mod" out="">brief</W>
<W id="160" tag="NN" in="-2:nobj" out="">opportunity</W>
<W id="161" tag="TO" in="-3:mod" out="1:vobj">to</W>
<W id="162" tag="VB" in="-1:vobj" out="1:lobj|2:coord">return</W>
<W id="163" tag="NN" in="-1:lobj" out="">home</W>
<W id="164" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="165" tag="VB" in="-1:conj" out="1:dobj">get</W>
<W id="166" tag="NNS" in="-1:dobj" out="">belongings</W>
<W id="167" tag="." in="-15:pnct" out="">.</W>
</s>
<s>
<W id="170" tag="DT" in="8:mod" out="1:nobj|2:mod|4:pnct">The</W>
<W id="171" tag="NN" in="-1:nobj" out="">night</W>
<W id="172" tag="IN" in="-2:mod" out="1:aobj">before</W>
<W id="173" tag="JJ" in="-1:aobj" out="">last</W>
<W id="174" tag="," in="-4:pnct" out="">,</W>
<W id="175" tag="DT" in="3:subj" out="2:nobj">the</W>
<W id="176" tag="NN" in="1:mod" out="">fire</W>
<W id="177" tag="NN" in="-2:nobj" out="-1:mod">department</W>
<W id="178" tag="VBD" in="" out="-3:subj|-8:mod|1:mod|4:mod|8:pnct">shuttled</W>
<W id="179" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W id="180" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="181" tag="NN" in="-1:nobj" out="">sea</W>
<W id="182" tag="TO" in="-4:mod" out="1:vobj">to</W>
<W id="183" tag="VB" in="-1:vobj" out="2:dobj">get</W>
<W id="184" tag="JJ" in="1:mod" out="">extra</W>
<W id="185" tag="NN" in="-2:dobj" out="-1:mod">water</W>
<W id="186" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W id="189" tag="VBG" in="18:mod" out="1:pobj|9:pnct">According</W>
<W id="190" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="191" tag="NNS" in="-1:nobj" out="1:mod">reporters</W>
<W id="192" tag="VBN" in="-1:mod" out="1:pobj">dispatched</W>
<W id="193" tag="IN" in="-1:pobj" out="1:nobj">by</W>
<W id="194" tag="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W id="195" tag="JJ" in="-1:mod" out="">Swedish</W>
<W id="196" tag="NN" in="1:mod" out="">news</W>
<W id="197" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W id="198" tag="," in="-9:pnct" out="">,</W>
<W id="199" tag="DT" in="8:subj" out="1:nobj|2:coord">the</W>
<W id="200" tag="NN" in="-1:nobj" out="">fire</W>
<W id="201" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="202" tag="DT" in="-1:conj" out="1:nobj">the</W>
<W id="203" tag="RB" in="-1:nobj" out="1:mod|3:nobj">many</W>
<W id="204" tag="VBN" in="-1:mod" out="">plowed</W>
<W id="205" tag="NN" in="1:mod" out="">fire</W>
<W id="206" tag="NNS" in="-3:nobj" out="-1:mod">breaks</W>
<W id="207" tag="VBD" in="" out="-8:subj|-18:mod|2:dobj|3:mod|6:pnct|7:mod|16:pnct#">created</W>
<W id="208" tag="JJ" in="1:mod" out="">great</W>
<W id="209" tag="NNS" in="-2:dobj" out="-1:mod">gashes</W>
<W id="210" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="211" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="212" tag="NN" in="-1:nobj" out="">terrain</W>
<W id="213" tag="," in="-6:pnct" out="">,</W>
<W id="214" tag="RB" in="-7:mod" out="1:nobj">so</W>
<W id="215" tag="IN" in="-1:nobj" out="2:vobj">that</W>
<W id="216" tag="PRP" in="1:subj" out="">it</W>
<W id="217" tag="VBZ" in="-2:vobj" out="-1:subj|2:dobj">resembles</W>
<W id="218" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="219" tag="DT" in="-2:dobj" out="-1:pnct|1:mod|2:pnct|3:mod|4:nobj|5:pnct">a</W>
<W id="220" tag="NN" in="-1:mod" out="">ghost-like</W>
<W id="221" tag="," in="-2:pnct" out="">,</W>
<W id="222" tag="VBN" in="-3:mod" out="">ravaged</W>
<W id="223" tag="JJ" in="-4:nobj|-16:pnct#" out="">landscape.</W>
<W id="224" tag="&amp;quot;" in="-5:pnct" out="">"</W>
</s>
