<s>
<W id="1" tag="JJ" in="1:mod" out="">UN</W>
<W id="2" tag="NNS" in="1:subj" out="-1:mod">sources</W>
<W id="3" tag="VBP" in="" out="-1:subj|1:dobj|8:pnct">say</W>
<W id="4" tag="IN" in="-1:dobj" out="4:vobj">that</W>
<W id="5" tag="DT" in="3:subj|4:[subj]|5:[subj]" out="2:nobj">an</W>
<W id="6" tag="NN" in="1:mod" out="">airport</W>
<W id="7" tag="NN" in="-2:nobj" out="-1:mod">building</W>
<W id="8" tag="VBZ" in="-4:vobj" out="-3:subj|1:vobj">has</W>
<W id="9" tag="VBN" in="-1:vobj" out="-4:[subj]|1:vobj">been</W>
<W id="10" tag="VBN" in="-1:vobj" out="-5:[subj]">destroyed</W>
<W id="11" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W id="14" tag="DT" in="11:subj|13:[subj]|14:[subj]" out="1:nobj|2:mod">The</W>
<W id="15" tag="NN" in="-1:nobj" out="">area</W>
<W id="16" tag="IN" in="-2:mod" out="1:nobj">around</W>
<W id="17" tag="DT" in="-1:nobj" out="3:nobj|4:mod">the</W>
<W id="18" tag="NNP" in="2:mod" out="1:nobj">Holiday</W>
<W id="19" tag="NNP" in="-1:nobj" out="">Inn</W>
<W id="20" tag="NN" in="-3:nobj" out="-2:mod">hotel</W>
<W id="21" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="22" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="23" tag="JJ" in="-1:mod" out="">Bosnian</W>
<W id="24" tag="NN" in="-2:nobj" out="">capital</W>
<W id="25" tag="VBZ" in="" out="-11:subj|1:mod|2:vobj|37:pnct">has</W>
<W id="26" tag="RB" in="-1:mod" out="">also</W>
<W id="27" tag="VBN" in="-2:vobj" out="-13:[subj]|1:vobj">been</W>
<W id="28" tag="VBN" in="-1:vobj" out="-14:[subj]|1:pobj|3:pobj">bombarded</W>
<W id="29" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="30" tag="NNS" in="-1:nobj" out="">mortars</W>
<W id="31" tag="IN" in="-3:pobj" out="1:nobj">by</W>
<W id="32" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:pnct|4:ref|5:rel">the</W>
<W id="33" tag="VBG" in="-1:mod" out="">warring</W>
<W id="34" tag="NNS" in="-2:nobj" out="">parties</W>
<W id="35" tag="," in="-3:pnct" out="">,</W>
<W id="36" tag="WP" in="-4:ref|1:subj|2:[subj]" out="">who</W>
<W id="37" tag="VBP" in="-5:rel" out="-1:subj|1:vobj">have</W>
<W id="38" tag="VBN" in="-1:vobj" out="-2:[subj]|1:dobj|6:mod">increased</W>
<W id="39" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="40" tag="NN" in="-1:nobj" out="1:pobj">pressure</W>
<W id="41" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W id="42" tag="DT" in="-1:nobj" out="1:nobj">each</W>
<W id="43" tag="JJ" in="-1:nobj" out="">other</W>
<W id="44" tag="RP" in="-6:mod" out="1:mod">up</W>
<W id="45" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W id="46" tag="DT" in="-1:nobj" out="1:mod|3:nobj|6:pnct|7:ref|8:rel">the</W>
<W id="47" tag="JJ" in="-1:mod" out="">international</W>
<W id="48" tag="NN" in="1:mod" out="">peace</W>
<W id="49" tag="NN" in="-3:nobj" out="-1:mod|1:pobj">conference</W>
<W id="50" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W id="51" tag="NNP" in="-1:nobj" out="">Yugoslavia</W>
<W id="52" tag="," in="-6:pnct" out="">,</W>
<W id="53" tag="WDT" in="-7:ref|1:subj|3:[subj]" out="">which</W>
<W id="54" tag="VBZ" in="-8:rel" out="-1:subj|1:pred">is</W>
<W id="55" tag="TO" in="-1:pred" out="1:vobj">to</W>
<W id="56" tag="VB" in="-1:vobj" out="-3:[subj]|1:dobj|2:lobj|4:tobj">take</W>
<W id="57" tag="NN" in="-1:dobj" out="">place</W>
<W id="58" tag="IN" in="-2:lobj" out="1:nobj">in</W>
<W id="59" tag="NNP" in="-1:nobj" out="">London</W>
<W id="60" tag="IN" in="-4:tobj" out="1:nobj">on</W>
<W id="61" tag="NNP" in="-1:nobj" out="">Wednesday</W>
<W id="62" tag="." in="-37:pnct" out="">.</W>
</s>
<s>
<W id="65" tag="DT" in="5:subj|7:[subj]" out="1:mod|3:nobj|4:appr">The</W>
<W id="66" tag="JJ" in="-1:mod" out="">Serbian-dominated</W>
<W id="67" tag="NN" in="1:mod" out="">news</W>
<W id="68" tag="NN" in="-3:nobj" out="-1:mod">bureau</W>
<W id="69" tag="NNP" in="-4:appr" out="">Tanjug</W>
<W id="70" tag="VBZ" in="" out="-5:subj|1:mod|2:vobj|18:pnct">has</W>
<W id="71" tag="RBR" in="-1:mod" out="">earlier</W>
<W id="72" tag="VBN" in="-2:vobj" out="-7:[subj]|1:dobj">reported</W>
<W id="73" tag="IN" in="-1:dobj" out="5:vobj">that</W>
<W id="74" tag="IN" in="1:mod" out="">around</W>
<W id="75" tag="CD" in="3:subj|4:[subj]" out="-1:mod|2:nobj">1,700</W>
<W id="76" tag="NN" in="1:mod" out="">artillery</W>
<W id="77" tag="NNS" in="-2:nobj" out="-1:mod">shells</W>
<W id="78" tag="VBP" in="-5:vobj" out="-3:subj|1:vobj">have</W>
<W id="79" tag="VBN" in="-1:vobj" out="-4:[subj]|1:lobj|4:mod">landed</W>
<W id="80" tag="IN" in="-1:lobj" out="2:nobj">in</W>
<W id="81" tag="JJ" in="1:mod" out="">Serbian-dominated</W>
<W id="82" tag="NNS" in="-2:nobj" out="-1:mod">areas</W>
<W id="83" tag="IN" in="-4:mod" out="1:nobj">within</W>
<W id="84" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="85" tag="JJ" in="-1:mod" out="">last</W>
<W id="86" tag="JJ" in="-2:nobj" out="1:nobj">twenty-four</W>
<W id="87" tag="NNS" in="-1:nobj" out="">hours</W>
<W id="88" tag="." in="-18:pnct" out="">.</W>
</s>
<s>
<W id="91" tag="IN" in="1:mod" out="">Around</W>
<W id="92" tag="CD" in="4:subj|5:[subj]" out="-1:mod|1:nobj">20</W>
<W id="93" tag="NNS" in="-1:nobj" out="1:coord">soldiers</W>
<W id="94" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="95" tag="NNS" in="-1:conj" out="">civilians</W>
<W id="96" tag="VBD" in="6:qobj" out="-4:subj|1:vobj|5:pnct">were</W>
<W id="97" tag="VBN" in="-1:vobj" out="-5:[subj]|1:mod">killed</W>
<W id="98" tag="IN" in="-1:mod" out="1:nobj">during</W>
<W id="99" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="100" tag="NN" in="-1:nobj" out="">bombardment</W>
<W id="101" tag="," in="-5:pnct" out="">,</W>
<W id="102" tag="VBD" in="" out="-6:qobj|1:subj|2:pnct|3:coord|11:pnct">said</W>
<W id="103" tag="NNP" in="-1:subj" out="">Tanjug</W>
<W id="104" tag="," in="-2:pnct" out="">,</W>
<W id="105" tag="CC" in="-3:coord" out="3:conj">but</W>
<W id="106" tag="DT" in="2:subj|5:[subj]|6:[subj]" out="1:nobj">the</W>
<W id="107" tag="NNS" in="-1:nobj" out="">numbers</W>
<W id="108" tag="VBP" in="-3:conj" out="-2:subj|1:mod|2:mod|3:vobj">have</W>
<W id="109" tag="RB" in="-1:mod" out="">not</W>
<W id="110" tag="RB" in="-2:mod" out="">yet</W>
<W id="111" tag="VBN" in="-3:vobj" out="-5:[subj]|1:vobj">been</W>
<W id="112" tag="VBN" in="-1:vobj" out="-6:[subj]">confirmed</W>
<W id="113" tag="." in="-11:pnct" out="">.</W>
</s>
<s>
<W id="116" tag="JJ" in="1:mod" out="">UN</W>
<W id="117" tag="NN" in="" out="-1:mod">debate</W>
<W id="118" tag="NNP" in="1:subj" out="">Bosnia-Herzegovina</W>
<W id="119" tag="VBD" in="" out="-1:subj|1:mod|2:dobj|8:pobj|28:pnct">received</W>
<W id="120" tag="NN" in="-1:mod" out="">yesterday</W>
<W id="121" tag="DT" in="-2:dobj" out="1:nobj">a</W>
<W id="122" tag="NN" in="-1:nobj" out="1:pobj">stream</W>
<W id="123" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="124" tag="NN" in="-1:nobj" out="1:coord">support</W>
<W id="125" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="126" tag="NN" in="-1:conj" out="">sympathy</W>
<W id="127" tag="IN" in="-8:pobj" out="1:nobj">from</W>
<W id="128" tag="DT" in="-1:nobj" out="3:nobj|4:pnct|5:ref|8:rel">the</W>
<W id="129" tag="NNP" in="2:mod" out="">UN</W>
<W id="130" tag="NNP" in="1:mod" out="">General</W>
<W id="131" tag="NNP" in="-3:nobj" out="-1:mod|-2:mod">Assembly</W>
<W id="132" tag="," in="-4:pnct" out="">,</W>
<W id="133" tag="WRB" in="-5:ref|3:mod" out="">where</W>
<W id="134" tag="JJ" in="1:mod" out="">Islamic</W>
<W id="135" tag="NNS" in="1:subj" out="-1:mod">countries</W>
<W id="136" tag="VBD" in="-8:rel" out="-3:mod|-1:subj|1:dobj|6:mod">encouraged</W>
<W id="137" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="138" tag="NN" in="-1:nobj" out="1:pobj">use</W>
<W id="139" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="140" tag="JJ" in="1:mod" out="">military</W>
<W id="141" tag="NN" in="-2:nobj" out="-1:mod">power</W>
<W id="142" tag="TO" in="-6:mod" out="1:vobj">to</W>
<W id="143" tag="VB" in="-1:vobj" out="1:dobj">help</W>
<W id="144" tag="DT" in="-1:dobj" out="1:mod|2:nobj">the</W>
<W id="145" tag="JJ" in="-1:mod" out="">beleaguered</W>
<W id="146" tag="NN" in="-2:nobj" out="">republic</W>
<W id="147" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W id="150" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W id="151" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W id="152" tag="NN" in="-1:nobj" out="">debate</W>
<W id="153" tag="MD" in="41:qobj" out="-3:pnct|-2:subj|1:vobj|39:pnct|40:pnct">must</W>
<W id="154" tag="VBD" in="-1:vobj" out="-3:[subj]|1:dobj|4:lobj">sent</W>
<W id="155" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="156" tag="JJ" in="-1:mod" out="">clear</W>
<W id="157" tag="NN" in="-2:nobj" out="11:pobj">message</W>
<W id="158" tag="TO" in="-4:lobj" out="1:nobj">to</W>
<W id="159" tag="DT" in="-1:nobj" out="1:ref|2:rel">those</W>
<W id="160" tag="WP" in="-1:ref|1:subj" out="">who</W>
<W id="161" tag="VBP" in="-2:rel" out="-1:subj|1:pred">are</W>
<W id="162" tag="JJ" in="-1:pred" out="1:pobj">responsible</W>
<W id="163" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W id="164" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="165" tag="NN" in="-1:nobj" out="1:pobj">mutilation</W>
<W id="166" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="167" tag="NNP" in="-1:nobj" out="">Bosnia-Herzegovina</W>
<W id="168" tag="IN" in="-11:pobj" out="6:vobj|9:coord">that</W>
<W id="169" tag="DT" in="5:subj|6:[subj]" out="1:nobj|2:mod">the</W>
<W id="170" tag="NN" in="-1:nobj" out="">patience</W>
<W id="171" tag="IN" in="-2:mod" out="2:nobj">of</W>
<W id="172" tag="JJ" in="1:mod" out="">international</W>
<W id="173" tag="NN" in="-2:nobj" out="-1:mod">community</W>
<W id="174" tag="VBZ" in="-6:vobj" out="-5:subj|1:vobj">has</W>
<W id="175" tag="VBN" in="-1:vobj" out="-6:[subj]|1:part">run</W>
<W id="176" tag="RP" in="-1:part" out="">out</W>
<W id="177" tag="CC" in="-9:coord" out="1:conj">and</W>
<W id="178" tag="IN" in="-1:conj" out="10:vobj">that</W>
<W id="179" tag="JJ" in="1:mod" out="">further</W>
<W id="180" tag="NNS" in="8:subj|10:[subj]|11:[subj]" out="-1:mod|1:pobj|3:coord">acts</W>
<W id="181" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="182" tag="NN" in="-1:nobj" out="">violence</W>
<W id="183" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="184" tag="NNS" in="-1:conj" out="1:pobj">violations</W>
<W id="185" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="186" tag="JJ" in="1:mod" out="">international</W>
<W id="187" tag="NNS" in="-2:nobj" out="-1:mod">norms</W>
<W id="188" tag="MD" in="-10:vobj" out="-8:subj|1:mod|2:vobj">will</W>
<W id="189" tag="RB" in="-1:mod" out="">not</W>
<W id="190" tag="VB" in="-2:vobj" out="-10:[subj]|1:vobj">be</W>
<W id="191" tag="VBN" in="-1:vobj" out="-11:[subj]">permitted</W>
<W id="192" tag="," in="-39:pnct" out="">,</W>
<W id="193" tag="&amp;quot;" in="-40:pnct" out="">"</W>
<W id="194" tag="VBD" in="" out="-41:qobj|1:subj|7:pnct">said</W>
<W id="195" tag="NNP" in="-1:subj" out="2:possd|3:pnct|5:appa">Turkey's</W>
<W id="196" tag="NNP" in="1:mod" out="">UN</W>
<W id="197" tag="NN" in="-2:possd" out="-1:mod">ambassador</W>
<W id="198" tag="," in="-3:pnct" out="">,</W>
<W id="199" tag="NNP" in="1:namef" out="">Mustafa</W>
<W id="200" tag="NNP" in="-5:appa" out="-1:namef">Aksin</W>
<W id="201" tag="." in="-7:pnct" out="">.</W>
</s>
