<s>
<W id="1" tag="DT" in="5:subj" out="1:nobj">The</W>
<W id="2" tag="NN" in="-1:nobj" out="1:pobj">adoption</W>
<W id="3" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="4" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="5" tag="NN" in="-1:nobj" out="">resolution</W>
<W id="6" tag="VBZ" in="" out="-5:subj|1:pred|11:pnct|12:coord|36:pnct">is</W>
<W id="7" tag="DT" in="-1:pred" out="1:nobj|3:mod|4:possd|5:mod|7:mod">the</W>
<W id="8" tag="NNP" in="-1:nobj" out="">UN's</W>
<W id="9" tag="RBS" in="1:mod" out="">most</W>
<W id="10" tag="JJ" in="-3:mod" out="-1:mod">far-reaching</W>
<W id="11" tag="NN" in="-4:possd" out="">move</W>
<W id="12" tag="TO" in="-5:mod" out="1:nobj">to</W>
<W id="13" tag="VB" in="-1:nobj" out="">date</W>
<W id="14" tag="IN" in="-7:mod" out="1:nobj">in</W>
<W id="15" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="16" tag="NN" in="-1:nobj" out="">war</W>
<W id="17" tag="," in="-11:pnct" out="">,</W>
<W id="18" tag="CC" in="-12:coord" out="2:conj">and</W>
<W id="19" tag="PRP" in="1:subj" out="5:nobj">it</W>
<W id="20" tag="VBZ" in="-2:conj" out="-1:subj|1:pred">is</W>
<W id="21" tag="DT" in="-1:pred" out="1:mod|2:nobj">the</W>
<W id="22" tag="JJ" in="-1:mod" out="">first</W>
<W id="23" tag="NN" in="-2:nobj" out="">time</W>
<W id="24" tag="IN" in="-5:nobj" out="4:vobj">that</W>
<W id="25" tag="DT" in="3:subj|4:[subj]" out="2:nobj">the</W>
<W id="26" tag="NNP" in="1:mod" out="">Security</W>
<W id="27" tag="NNP" in="-2:nobj" out="-1:mod">Council</W>
<W id="28" tag="VBZ" in="-4:vobj" out="-3:subj|1:vobj">has</W>
<W id="29" tag="VBN" in="-1:vobj" out="-4:[subj]|1:dobj|7:mod">given</W>
<W id="30" tag="DT" in="-1:dobj" out="1:mod">the</W>
<W id="31" tag="JJ" in="-1:mod" out="1:nobj">green</W>
<W id="32" tag="NN" in="-1:nobj" out="1:pobj">light</W>
<W id="33" tag="TO" in="-1:pobj" out="2:nobj">to</W>
<W id="34" tag="JJ" in="1:mod" out="">military</W>
<W id="35" tag="NNS" in="-2:nobj" out="-1:mod">actions</W>
<W id="36" tag="IN" in="-7:mod" out="1:nobj">in</W>
<W id="37" tag="NN" in="-1:nobj" out="1:pobj">connection</W>
<W id="38" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="39" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="40" tag="JJ" in="-1:mod" out="">humanitarian</W>
<W id="41" tag="NN" in="-2:nobj" out="">task</W>
<W id="42" tag="." in="-36:pnct" out="">.</W>
</s>
<s>
<W id="45" tag="IN" in="12:mod" out="2:vobj">If</W>
<W id="46" tag="NNP" in="1:subj|3:[subj]" out="">Serbia</W>
<W id="47" tag="VBZ" in="-2:vobj" out="-1:subj|1:dobj|6:pnct">refuses</W>
<W id="48" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="49" tag="VB" in="-1:vobj" out="-3:[subj]|1:pobj">comply</W>
<W id="50" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="51" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="52" tag="NN" in="-1:nobj" out="">warning</W>
<W id="53" tag="," in="-6:pnct" out="">,</W>
<W id="54" tag="DT" in="3:subj" out="1:mod|2:nobj">the</W>
<W id="55" tag="JJ" in="-1:mod" out="">current</W>
<W id="56" tag="NNS" in="-2:nobj" out="">plans</W>
<W id="57" tag="VBP" in="" out="-3:subj|-12:mod|1:pred|19:pnct">are</W>
<W id="58" tag="TO" in="-1:pred" out="1:vobj">to</W>
<W id="59" tag="VB" in="-1:vobj" out="1:dobj">open</W>
<W id="60" tag="DT" in="-1:dobj" out="1:nobj|2:mod|4:mod">a</W>
<W id="61" tag="NN" in="-1:nobj" out="">corridor</W>
<W id="62" tag="IN" in="-2:mod" out="1:nobj">by</W>
<W id="63" tag="NN" in="-1:nobj" out="">land</W>
<W id="64" tag="TO" in="-4:mod" out="1:nobj">to</W>
<W id="65" tag="NNP" in="-1:nobj" out="1:coord">Sarajevo</W>
<W id="66" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="67" tag="JJ" in="-1:conj" out="1:nobj|2:ref|3:rel">other</W>
<W id="68" tag="NNS" in="-1:nobj" out="">areas</W>
<W id="69" tag="WDT" in="-2:ref|1:subj" out="">which</W>
<W id="70" tag="VBP" in="-3:rel" out="-1:subj|1:pred">are</W>
<W id="71" tag="IN" in="-1:pred" out="1:nobj">under</W>
<W id="72" tag="NN" in="-1:nobj" out="1:pobj">siege</W>
<W id="73" tag="IN" in="-1:pobj" out="2:nobj">by</W>
<W id="74" tag="NN" in="1:mod" out="">enemy</W>
<W id="75" tag="NNS" in="-2:nobj" out="-1:mod">forces</W>
<W id="76" tag="." in="-19:pnct" out="">.</W>
</s>
<s>
<W id="79" tag="IN" in="21:mod" out="1:nobj|4:pnct">In</W>
<W id="80" tag="NNP" in="-1:nobj" out="1:possd|2:appr">Croatia's</W>
<W id="81" tag="NN" in="-1:possd" out="">capital</W>
<W id="82" tag="NNP" in="-2:appr" out="">Zagreb</W>
<W id="83" tag="," in="-4:pnct" out="">,</W>
<W id="84" tag="DT" in="16:subj" out="1:mod|2:nobj|11:pnct|14:appa">the</W>
<W id="85" tag="JJ" in="-1:mod" out="">Danish</W>
<W id="86" tag="NN" in="-2:nobj" out="1:pobj">head</W>
<W id="87" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="88" tag="DT" in="-1:nobj" out="3:nobj|5:appa">the</W>
<W id="89" tag="NNP" in="2:mod" out="">UN</W>
<W id="90" tag="NN" in="1:mod" out="">refugee</W>
<W id="91" tag="NN" in="-3:nobj" out="-1:mod|-2:mod">organization</W>
<W id="92" tag="(" in="1:pnct" out="">(</W>
<W id="93" tag="NNP" in="-5:appa" out="-1:pnct|1:pnct">UNHCR</W>
<W id="94" tag=")" in="-1:pnct" out="">)</W>
<W id="95" tag="," in="-11:pnct" out="">,</W>
<W id="96" tag="NNP" in="2:namef" out="">Lars</W>
<W id="97" tag="NNP" in="1:namel" out="">Lynge</W>
<W id="98" tag="NNP" in="-14:appa" out="-2:namef|-1:namel|1:pnct">Nielsen</W>
<W id="99" tag="," in="-1:pnct" out="">,</W>
<W id="100" tag="VBD" in="" out="-21:mod|-16:subj|2:mod|3:pobj|6:dobj|28:pnct">said</W>
<W id="101" tag="NN" in="1:mod" out="">yesterday</W>
<W id="102" tag="NN" in="-2:mod" out="-1:mod">evening</W>
<W id="103" tag="TO" in="-3:pobj" out="1:nobj">to</W>
<W id="104" tag="NNP" in="-1:nobj" out="1:possd">Ritzau's</W>
<W id="105" tag="NNP" in="-1:possd" out="">Bureau</W>
<W id="106" tag="IN" in="-6:dobj" out="3:vobj">that</W>
<W id="107" tag="DT" in="2:subj" out="1:nobj">the</W>
<W id="108" tag="NNP" in="-1:nobj" out="">UNHCR</W>
<W id="109" tag="VBZ" in="-3:vobj" out="-2:subj|1:dobj">believes</W>
<W id="110" tag="IN" in="-1:dobj" out="10:vobj">that</W>
<W id="111" tag="DT" in="9:subj|10:[subj]" out="1:mod|2:mod|3:nobj">the</W>
<W id="112" tag="JJ" in="-1:mod" out="">great</W>
<W id="113" tag="JJ" in="-2:mod" out="">international</W>
<W id="114" tag="NN" in="-3:nobj" out="1:pobj">attention</W>
<W id="115" tag="IN" in="-1:pobj" out="2:nobj">on</W>
<W id="116" tag="JJ" in="1:mod" out="">ethnic</W>
<W id="117" tag="NN" in="-2:nobj" out="-1:mod|1:mod">cleansing</W>
<W id="118" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="119" tag="NNP" in="-1:nobj" out="">Bosnia-Herzegovina</W>
<W id="120" tag="VBZ" in="-10:vobj" out="-9:subj|1:vobj">has</W>
<W id="121" tag="VBN" in="-1:vobj" out="-10:[subj]|1:dobj">shaken</W>
<W id="122" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:mod">the</W>
<W id="123" tag="NNP" in="-1:mod" out="">Serbian</W>
<W id="124" tag="NNS" in="-2:nobj" out="">leaders</W>
<W id="125" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="126" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="127" tag="NN" in="-1:nobj" out="">republic</W>
<W id="128" tag="." in="-28:pnct" out="">.</W>
</s>
<s>
<W id="131" tag="&amp;quot;" in="2:pnct" out="">"</W>
<W id="132" tag="PRP" in="1:subj|3:[subj]" out="">We</W>
<W id="133" tag="VBP" in="" out="-2:pnct|-1:subj|1:mod|2:vobj|10:pnct">have</W>
<W id="134" tag="RB" in="-1:mod" out="">deliberately</W>
<W id="135" tag="VBN" in="-2:vobj" out="-3:[subj]|1:dobj|5:pobj">told</W>
<W id="136" tag="NN" in="-1:dobj|3:[dobj]" out="2:rel">everything</W>
<W id="137" tag="PRP" in="1:subj|2:[subj]" out="">we</W>
<W id="138" tag="VBP" in="-2:rel" out="-1:subj|1:vobj">have</W>
<W id="139" tag="VBN" in="-1:vobj" out="-3:[dobj]|-2:[subj]">seen</W>
<W id="140" tag="TO" in="-5:pobj" out="1:nobj">to</W>
<W id="141" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="142" tag="NN" in="-1:nobj" out="">press</W>
<W id="143" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W id="146" tag="CC" in="25:qobj" out="19:vobj|23:pnct|24:pnct">And</W>
<W id="147" tag="DT" in="18:subj|19:[subj]" out="1:mod|3:nobj">the</W>
<W id="148" tag="JJ" in="-1:mod" out="">great</W>
<W id="149" tag="NNS" in="1:mod" out="">media</W>
<W id="150" tag="NN" in="-3:nobj" out="-1:mod|1:pobj">coverage</W>
<W id="151" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="152" tag="RB" in="1:mod" out="">especially</W>
<W id="153" tag="DT" in="-2:nobj" out="-1:mod|1:mod|2:nobj">the</W>
<W id="154" tag="NNP" in="-1:mod" out="">Serbian</W>
<W id="155" tag="NNS" in="-2:nobj" out="1:dobj">attempts</W>
<W id="156" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="157" tag="VB" in="-1:vobj" out="1:dobj|4:lobj">throw</W>
<W id="158" tag="NNPS" in="-1:dobj" out="1:coord">Muslims</W>
<W id="159" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="160" tag="NNS" in="-1:conj" out="">Croats</W>
<W id="161" tag="IN" in="-4:lobj" out="1:mod">out</W>
<W id="162" tag="IN" in="-1:mod" out="2:nobj">of</W>
<W id="163" tag="JJ" in="1:mod" out="">Serbian-controlled</W>
<W id="164" tag="NNS" in="-2:nobj" out="-1:mod">regions</W>
<W id="165" tag="VBZ" in="-19:vobj" out="-18:subj|1:vobj">has</W>
<W id="166" tag="VBN" in="-1:vobj" out="-19:[subj]|1:dobj">shaken</W>
<W id="167" tag="DT" in="-1:dobj" out="1:nobj">the</W>
<W id="168" tag="NNP" in="-1:nobj" out="">Serbs</W>
<W id="169" tag="," in="-23:pnct" out="">,</W>
<W id="170" tag="&amp;quot;" in="-24:pnct" out="">"</W>
<W id="171" tag="VBD" in="" out="-25:qobj|2:subj|3:pnct">said</W>
<W id="172" tag="NNP" in="1:namel" out="">Lynge</W>
<W id="173" tag="NNP" in="-2:subj" out="-1:namel">Nielsen</W>
<W id="174" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W id="177" tag="PRP" in="1:subj|5:[subj]|11:[subj]" out="">He</W>
<W id="178" tag="VBZ" in="" out="-1:subj|1:mod|4:vobj|39:pnct">has</W>
<W id="179" tag="IN" in="-1:mod" out="2:nobj">in</W>
<W id="180" tag="JJ" in="1:mod" out="">recent</W>
<W id="181" tag="NNS" in="-2:nobj" out="-1:mod">days</W>
<W id="182" tag="VBN" in="-4:vobj" out="-5:[subj]|1:pobj|5:coord">negotiated</W>
<W id="183" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="184" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="185" tag="NNP" in="-1:mod" out="">Serbian</W>
<W id="186" tag="NNS" in="-2:nobj" out="">leaders</W>
<W id="187" tag="CC" in="-5:coord" out="1:conj">and</W>
<W id="188" tag="VBN" in="-1:conj" out="-11:[subj]|1:dobj|2:pred">made</W>
<W id="189" tag="PRP" in="-1:dobj" out="2:nobj">it</W>
<W id="190" tag="JJ" in="-2:pred" out="">clear</W>
<W id="191" tag="IN" in="-2:nobj" out="3:vobj">that</W>
<W id="192" tag="DT" in="2:subj|4:[subj]" out="1:nobj">the</W>
<W id="193" tag="NNP" in="-1:nobj" out="">UNHCR</W>
<W id="194" tag="MD" in="-3:vobj" out="-2:subj|1:mod|2:vobj">will</W>
<W id="195" tag="RB" in="-1:mod" out="">not</W>
<W id="196" tag="VB" in="-2:vobj" out="-4:[subj]|1:pred">be</W>
<W id="197" tag="NN" in="-1:pred" out="1:pobj">part</W>
<W id="198" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="199" tag="VBG" in="-1:nobj" out="3:dobj|5:lobj">moving</W>
<W id="200" tag="RB" in="2:mod" out="1:pobj">just</W>
<W id="201" tag="IN" in="-1:pobj" out="1:[nobj]">under</W>
<W id="202" tag="CD" in="-3:dobj|-1:[nobj]" out="-2:mod|1:nobj">30,000</W>
<W id="203" tag="NNPS" in="-1:nobj" out="">Muslims</W>
<W id="204" tag="IN" in="-5:lobj" out="1:mod|3:coord">out</W>
<W id="205" tag="IN" in="-1:mod" out="1:nobj">of</W>
<W id="206" tag="NNP" in="-1:nobj" out="">Bosnia-Herzegovina</W>
<W id="207" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="208" tag="IN" in="-1:conj" out="1:nobj">into</W>
<W id="209" tag="NNP" in="-1:nobj" out="1:coord">Croatia</W>
<W id="210" tag="CC" in="-1:coord" out="1:conj">or</W>
<W id="211" tag="DT" in="-1:conj" out="1:nobj|2:mod">the</W>
<W id="212" tag="NNS" in="-1:nobj" out="">areas</W>
<W id="213" tag="VBN" in="-2:mod" out="1:mod">protected</W>
<W id="214" tag="IN" in="-1:mod" out="1:nobj">by</W>
<W id="215" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="216" tag="NNP" in="-1:nobj" out="">UN</W>
<W id="217" tag="." in="-39:pnct" out="">.</W>
</s>
