<s>
<W id="1" tag="JJ" in="5:subj" out="1:possd">Danes'</W>
<W id="2" tag="NN" in="-1:possd" out="1:pobj">consumption</W>
<W id="3" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="4" tag="JJ" in="1:mod" out="">over-the-counter</W>
<W id="5" tag="NNS" in="-2:nobj" out="-1:mod">pain-relievers</W>
<W id="6" tag="VBZ" in="14:qobj" out="-5:subj|3:pred|13:pnct">is</W>
<W id="7" tag="RB" in="1:mod" out="3:nobj">so</W>
<W id="8" tag="RB" in="1:mod" out="-1:mod">alarmingly</W>
<W id="9" tag="JJ" in="-3:pred" out="-1:mod">great</W>
<W id="10" tag="IN" in="-3:nobj" out="1:pnct|6:vobj">that</W>
<W id="11" tag="," in="-1:pnct" out="">,</W>
<W id="12" tag="IN" in="4:mod" out="1:nobj|2:pnct">for</W>
<W id="13" tag="JJ" in="-1:nobj" out="">many</W>
<W id="14" tag="," in="-2:pnct" out="">,</W>
<W id="15" tag="PRP" in="1:subj" out="">it</W>
<W id="16" tag="VBZ" in="-6:vobj" out="-4:mod|-1:subj|2:pred">is</W>
<W id="17" tag="JJ" in="1:mod" out="">pure</W>
<W id="18" tag="NN" in="-2:pred" out="-1:mod">abuse</W>
<W id="19" tag="," in="-13:pnct" out="">,</W>
<W id="20" tag="VBZ" in="" out="-14:qobj|4:subj|7:pnct">believes</W>
<W id="21" tag="JJ" in="1:mod" out="">medical</W>
<W id="22" tag="NN" in="2:title" out="-1:mod">officer</W>
<W id="23" tag="NNP" in="1:namef" out="">Niels</W>
<W id="24" tag="NNP" in="-4:subj" out="-1:namef|-2:title|1:pnct|2:mod">Agdal</W>
<W id="25" tag="," in="-1:pnct" out="">,</W>
<W id="26" tag="NNS" in="-2:mod" out="">Randers</W>
<W id="27" tag="." in="-7:pnct" out="">.</W>
</s>
<s>
<W id="30" tag="DT" in="13:subj" out="1:nobj">The</W>
<W id="31" tag="NN" in="-1:nobj" out="1:pobj">consumption</W>
<W id="32" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="33" tag="NNS" in="-1:nobj" out="1:mod">pharmaceuticals</W>
<W id="34" tag="JJ" in="-1:mod" out="1:pobj">such</W>
<W id="35" tag="IN" in="-1:pobj" out="1:nobj">as</W>
<W id="36" tag="NNP" in="-1:nobj" out="1:pnct|2:conj|3:pnct|4:conj|5:coord">Kodimagnyl</W>
<W id="37" tag="," in="-1:pnct" out="">,</W>
<W id="38" tag="NNP" in="-2:conj" out="">Treo</W>
<W id="39" tag="," in="-3:pnct" out="">,</W>
<W id="40" tag="NNP" in="-4:conj" out="">Panodil</W>
<W id="41" tag="CC" in="-5:coord" out="1:conj">and</W>
<W id="42" tag="NNP" in="-1:conj" out="">Pamol</W>
<W id="43" tag="VBZ" in="" out="-13:subj|1:mod|3:pred|17:pnct">is</W>
<W id="44" tag="RB" in="-1:mod" out="">now</W>
<W id="45" tag="RB" in="1:mod" out="2:nobj">so</W>
<W id="46" tag="JJ" in="-3:pred" out="-1:mod">great</W>
<W id="47" tag="IN" in="-2:nobj" out="2:conj">that</W>
<W id="48" tag="PRP" in="1:subj" out="">it</W>
<W id="49" tag="VBZ" in="-2:conj" out="-1:subj|1:pobj">corresponds</W>
<W id="50" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="51" tag="DT" in="-1:nobj" out="1:nobj|2:mod">every</W>
<W id="52" tag="NNP" in="-1:nobj" out="">Dane</W>
<W id="53" tag="VBG" in="-2:mod" out="1:dobj|3:mod|4:mod">taking</W>
<W id="54" tag="CD" in="-1:dobj" out="1:nobj">160</W>
<W id="55" tag="NNS" in="-1:nobj" out="">pills</W>
<W id="56" tag="RB" in="-3:mod" out="">annually</W>
<W id="57" tag="IN" in="-4:mod" out="1:nobj">over</W>
<W id="58" tag="her" in="-1:nobj" out="1:possd">his</W>
<W id="59" tag="NN" in="-1:possd" out="">lifetime</W>
<W id="60" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W id="63" tag="&amp;quot;" in="5:pnct" out="">"</W>
<W id="64" tag="IN" in="4:mod" out="1:avobj|2:pnct">By</W>
<W id="65" tag="RB" in="-1:avobj" out="">now</W>
<W id="66" tag="," in="-2:pnct" out="">,</W>
<W id="67" tag="NNS" in="1:subj|2:[subj]" out="">people</W>
<W id="68" tag="VBP" in="" out="-5:pnct|-1:subj|-4:mod|1:vobj|12:pnct">are</W>
<W id="69" tag="VBG" in="-1:vobj" out="-2:[subj]|1:dobj|2:pobj">taking</W>
<W id="70" tag="NNS" in="-1:dobj" out="">pain-relievers</W>
<W id="71" tag="IN" in="-2:pobj" out="2:nobj">like</W>
<W id="72" tag="NN" in="1:mod" out="">lemon</W>
<W id="73" tag="VBZ" in="-2:nobj" out="-1:mod|1:coord">drops</W>
<W id="74" tag="CC" in="-1:coord" out="1:conj">or</W>
<W id="75" tag="DT" in="-1:conj" out="1:nobj">some</W>
<W id="76" tag="NN" in="-1:nobj" out="1:pobj">kind</W>
<W id="77" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="78" tag="NN" in="1:mod" out="">diet</W>
<W id="79" tag="NN" in="-2:nobj" out="-1:mod">supplement</W>
<W id="80" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W id="83" tag="DT" in="1:subj" out="">This</W>
<W id="84" tag="VBZ" in="11:qobj" out="-1:subj|1:pred|2:pnct|3:mod|9:pnct|10:pnct">is</W>
<W id="85" tag="VBG" in="-1:pred" out="">concerning</W>
<W id="86" tag="," in="-2:pnct" out="">,</W>
<W id="87" tag="IN" in="-3:mod" out="3:vobj">because</W>
<W id="88" tag="JJ" in="1:mod" out="">over-the-counter</W>
<W id="89" tag="NN" in="1:subj" out="-1:mod">medicine</W>
<W id="90" tag="VBZ" in="-3:vobj" out="-1:subj|1:mod|2:pred">is</W>
<W id="91" tag="RB" in="-1:mod" out="">not</W>
<W id="92" tag="JJ" in="-2:pred" out="">harmless</W>
<W id="93" tag="," in="-9:pnct" out="">,</W>
<W id="94" tag="&amp;quot;" in="-10:pnct" out="">"</W>
<W id="95" tag="VBZ" in="" out="-11:qobj|2:subj|3:pnct|4:mod|27:pnct">says</W>
<W id="96" tag="NNP" in="1:namef" out="">Niels</W>
<W id="97" tag="NNP" in="-2:subj" out="-1:namef">Agdal</W>
<W id="98" tag="," in="-3:pnct" out="">,</W>
<W id="99" tag="VBG" in="-4:mod" out="1:dobj">making</W>
<W id="100" tag="NN" in="-1:dobj" out="1:pobj">reference</W>
<W id="101" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="102" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="103" tag="NN" in="-1:nobj" out="1:nobj">fact</W>
<W id="104" tag="IN" in="-1:nobj" out="9:vobj">that</W>
<W id="105" tag="DT" in="8:subj" out="1:nobj">the</W>
<W id="106" tag="NN" in="-1:nobj" out="1:pobj">number</W>
<W id="107" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="108" tag="NNS" in="-1:nobj" out="1:mod">deaths</W>
<W id="109" tag="IN" in="-1:mod" out="3:nobj">from</W>
<W id="110" tag="JJ" in="1:mod" out="">salicylic</W>
<W id="111" tag="NN" in="1:mod" out="-1:mod">acid</W>
<W id="112" tag="NN" in="-3:nobj" out="-1:mod">poisoning</W>
<W id="113" tag="VBD" in="-9:vobj" out="-8:subj|1:pobj">rose</W>
<W id="114" tag="IN" in="-1:pobj" out="1:nobj|4:pobj">from</W>
<W id="115" tag="NN" in="-1:nobj" out="1:mod">5</W>
<W id="116" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="117" tag="CD" in="-1:nobj" out="">1980</W>
<W id="118" tag="TO" in="-4:pobj" out="1:nobj">to</W>
<W id="119" tag="CD" in="-1:nobj" out="1:mod">23</W>
<W id="120" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="121" tag="CD" in="-1:nobj" out="">1989</W>
<W id="122" tag="." in="-27:pnct" out="">.</W>
</s>
<s>
<W id="125" tag="IN" in="1:mod" out="">Around</W>
<W id="126" tag="NN" in="4:subj" out="-1:mod|1:pobj">half</W>
<W id="127" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="128" tag="DT" in="-1:nobj" out="1:nobj">these</W>
<W id="129" tag="NNS" in="-1:nobj" out="">cases</W>
<W id="130" tag="VBD" in="" out="-4:subj|1:pred|2:pnct">were</W>
<W id="131" tag="NN" in="-1:pred" out="">suicide</W>
<W id="132" tag="." in="-2:pnct" out="">.</W>
</s>
<s>
<W id="135" tag="NNPS" in="1:subj" out="">Danes</W>
<W id="136" tag="VBP" in="" out="-1:subj|1:mod|3:dobj|28:conj|31:pnct">consume</W>
<W id="137" tag="RB" in="-1:mod" out="">annually</W>
<W id="138" tag="RB" in="1:mod" out="">approximately</W>
<W id="139" tag="CD" in="-3:dobj" out="-1:mod|1:nobj|5:pnct|7:modp">400</W>
<W id="140" tag="NNS" in="-1:nobj" out="1:pobj">tons</W>
<W id="141" tag="IN" in="-1:pobj" out="2:nobj">of</W>
<W id="142" tag="JJ" in="1:mod" out="">active</W>
<W id="143" tag="NNS" in="-2:nobj" out="-1:mod">substances</W>
<W id="144" tag="&3a;" in="-5:pnct" out="">-</W>
<W id="145" tag="NNP" in="1:mod" out="">Acetylsalicylic</W>
<W id="146" tag="NN" in="-7:modp" out="-1:mod|1:coord|3:pnct">acid</W>
<W id="147" tag="CC" in="-1:coord" out="1:conj">or</W>
<W id="148" tag="NNP" in="-1:conj" out="">Paracetamol</W>
<W id="149" tag="&3a;" in="-3:pnct" out="">-</W>
<W id="150" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="151" tag="CC" in="13:qobj" out="-1:pnct|3:conj|12:pnct">and</W>
<W id="152" tag="DT" in="2:subj|3:[subj]|4:[subj]" out="1:nobj">this</W>
<W id="153" tag="NN" in="-1:nobj" out="">quantity</W>
<W id="154" tag="MD" in="-3:conj" out="-2:subj|1:vobj|8:pnct">must</W>
<W id="155" tag="VB" in="-1:vobj" out="-3:[subj]|1:vobj">be</W>
<W id="156" tag="VBN" in="-1:vobj" out="-4:[subj]|1:pobj">taken</W>
<W id="157" tag="IN" in="-1:pobj" out="1:nobj">as</W>
<W id="158" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="159" tag="NN" in="-1:nobj" out="1:pobj">sign</W>
<W id="160" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="161" tag="NN" in="-1:nobj" out="">abuse</W>
<W id="162" tag="," in="-8:pnct" out="">,</W>
<W id="163" tag="&amp;quot;" in="-12:pnct" out="">"</W>
<W id="164" tag="VBZ" in="-28:conj" out="-13:qobj|2:subj">says</W>
<W id="165" tag="NNP" in="1:namef" out="">Niels</W>
<W id="166" tag="NNP" in="-2:subj" out="-1:namef">Agdal</W>
<W id="167" tag="." in="-31:pnct" out="">.</W>
</s>
<s>
<W id="170" tag="IN" in="8:mod" out="1:nobj|6:pnct">On</W>
<W id="171" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">an</W>
<W id="172" tag="JJ" in="-1:mod" out="">ordinary</W>
<W id="173" tag="NNP" in="-2:nobj" out="">Friday</W>
<W id="174" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="175" tag="NNP" in="-1:nobj" out="">September</W>
<W id="176" tag="," in="-6:pnct" out="">,</W>
<W id="177" tag="PRP" in="1:subj" out="">he</W>
<W id="178" tag="VBD" in="" out="-1:subj|-8:mod|1:iobj|8:dobj|17:pnct">asked</W>
<W id="179" tag="CD" in="-1:iobj|8:[subj]" out="1:nobj|2:mod">five</W>
<W id="180" tag="NNS" in="-1:nobj" out="">pharmacies</W>
<W id="181" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="182" tag="NNS" in="-1:nobj" out="1:mod">Randers</W>
<W id="183" tag="IN" in="-1:mod" out="1:nobj">with</W>
<W id="184" tag="CD" in="-1:nobj" out="1:nobj">65,000</W>
<W id="185" tag="NNS" in="-1:nobj" out="">inhabitants</W>
<W id="186" tag="TO" in="-8:dobj" out="1:vobj">to</W>
<W id="187" tag="VB" in="-1:vobj" out="-8:[subj]|1:dobj">record</W>
<W id="188" tag="DT" in="-1:dobj" out="1:mod|2:nobj">the</W>
<W id="189" tag="JJ" in="-1:mod" out="">total</W>
<W id="190" tag="NN" in="-2:nobj" out="1:pobj">number</W>
<W id="191" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="192" tag="NNS" in="-1:nobj" out="1:pobj">sales</W>
<W id="193" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="194" tag="NNS" in="-1:nobj" out="">pain-relievers</W>
<W id="195" tag="." in="-17:pnct" out="">.</W>
</s>
<s>
<W id="198" tag="CD" in="2:subj|3:[subj]" out="1:nobj">31,632</W>
<W id="199" tag="NNS" in="-1:nobj" out="">tablets</W>
<W id="200" tag="VBD" in="" out="-2:subj|1:vobj|2:pnct|3:coord|21:pnct">were</W>
<W id="201" tag="VBN" in="-1:vobj" out="-3:[subj]">sold</W>
<W id="202" tag="&3a;" in="-2:pnct" out="">-</W>
<W id="203" tag="CC" in="-3:coord" out="3:conj">and</W>
<W id="204" tag="JJ" in="2:subj" out="1:nobj">several</W>
<W id="205" tag="NNS" in="-1:nobj" out="">pharmacies</W>
<W id="206" tag="VBD" in="-3:conj" out="-2:subj|1:dobj">declared</W>
<W id="207" tag="IN" in="-1:dobj" out="1:pnct|7:vobj">that</W>
<W id="208" tag="," in="-1:pnct" out="">,</W>
<W id="209" tag="IN" in="5:mod" out="1:nobj|3:pnct">on</W>
<W id="210" tag="DT" in="-1:nobj" out="1:nobj">that</W>
<W id="211" tag="NN" in="-1:nobj" out="">day</W>
<W id="212" tag="," in="-3:pnct" out="">,</W>
<W id="213" tag="PRP" in="1:subj" out="">they</W>
<W id="214" tag="VBD" in="-7:vobj" out="-1:subj|-5:mod|1:dobj">sold</W>
<W id="215" tag="DT" in="-1:dobj" out="2:mod|3:nobj">an</W>
<W id="216" tag="RB" in="1:mod" out="">usually</W>
<W id="217" tag="JJ" in="-2:mod" out="-1:mod">small</W>
<W id="218" tag="NN" in="-3:nobj" out="1:pobj">amount</W>
<W id="219" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="220" tag="NNS" in="-1:nobj" out="">painkillers</W>
<W id="221" tag="." in="-21:pnct" out="">.</W>
</s>
