<s>
<W id="1" tag="&amp;quot;" in="13:pnct" out="">"</W>
<W id="2" tag="WRB" in="12:mod" out="5:vobj">When</W>
<W id="3" tag="NNP" in="3:title" out="">Lady</W>
<W id="4" tag="NNP" in="2:namef" out="">Pamela</W>
<W id="5" tag="NNP" in="1:namel" out="">Colin</W>
<W id="6" tag="NNP" in="1:subj" out="-3:title|-2:namef|-1:namel">Campbell</W>
<W id="7" tag="VBD" in="-5:vobj" out="-1:subj|1:dobj|5:pnct">wrote</W>
<W id="8" tag="PRP$" in="-1:dobj" out="1:possd">her</W>
<W id="9" tag="NN" in="-1:possd" out="1:pobj">book</W>
<W id="10" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W id="11" tag="NNP" in="-1:nobj" out="">Diana</W>
<W id="12" tag="," in="-5:pnct" out="">,</W>
<W id="13" tag="NN" in="1:subj" out="">everyone</W>
<W id="14" tag="VBD" in="" out="-13:pnct|-12:mod|-1:subj|1:dobj|2:pobj|8:pnct">took</W>
<W id="15" tag="PRP" in="-1:dobj" out="">it</W>
<W id="16" tag="IN" in="-2:pobj" out="1:nobj">as</W>
<W id="17" tag="DT" in="-1:nobj" out="1:pnct|2:mod|3:nobj|4:pnct">a</W>
<W id="18" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W id="19" tag="JJ" in="-2:mod" out="">good</W>
<W id="20" tag="NN" in="-3:nobj" out="">cause</W>
<W id="21" tag="&amp;quot;" in="-4:pnct" out="">"</W>
<W id="22" tag="." in="-8:pnct" out="">.</W>
</s>
<s>
<W id="25" tag="NNP" in="1:subj|2:[subj]" out="">Diana</W>
<W id="26" tag="VBD" in="" out="-1:subj|1:vobj|26:coord|33:pnct">was</W>
<W id="27" tag="VBD" in="-1:vobj" out="-2:[subj]|1:pobj|4:mod|6:mod">raked</W>
<W id="28" tag="IN" in="-1:pobj" out="1:nobj">over</W>
<W id="29" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="30" tag="NNS" in="-1:nobj" out="">coals</W>
<W id="31" tag="DT" in="-4:mod" out="1:nobj">a</W>
<W id="32" tag="NN" in="-1:nobj" out="">bit</W>
<W id="33" tag="IN" in="-6:mod" out="1:nobj">as</W>
<W id="34" tag="DT" in="-1:nobj" out="2:mod|3:pnct|4:mod|5:nobj|6:pnct|7:ref|8:rel">a</W>
<W id="35" tag="RB" in="1:mod" out="">rather</W>
<W id="36" tag="JJ" in="-2:mod" out="-1:mod">harmless</W>
<W id="37" tag="," in="-3:pnct" out="">,</W>
<W id="38" tag="JJ" in="-4:mod" out="">funny</W>
<W id="39" tag="NN" in="-5:nobj" out="">girl</W>
<W id="40" tag="," in="-6:pnct" out="">,</W>
<W id="41" tag="WP" in="-7:ref|1:subj|3:[subj]" out="7:mod">who</W>
<W id="42" tag="VBD" in="-8:rel" out="-1:subj|1:mod|2:vobj|9:pnct">did</W>
<W id="43" tag="RB" in="-1:mod" out="">not</W>
<W id="44" tag="VB" in="-2:vobj" out="-3:[subj]|1:dobj">have</W>
<W id="45" tag="DT" in="-1:dobj" out="1:mod|2:nobj">an</W>
<W id="46" tag="JJ" in="-1:mod" out="">easy</W>
<W id="47" tag="NN" in="-2:nobj" out="">time</W>
<W id="48" tag="VBG" in="-7:mod" out="1:pobj">thinking</W>
<W id="49" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W id="50" tag="PRP" in="-1:nobj" out="">herself</W>
<W id="51" tag="," in="-9:pnct" out="">,</W>
<W id="52" tag="CC" in="-26:coord" out="2:conj">and</W>
<W id="53" tag="JJ" in="1:subj" out="">many</W>
<W id="54" tag="VBD" in="-2:conj" out="-1:subj|2:pred">were</W>
<W id="55" tag="RB" in="1:mod" out="">very</W>
<W id="56" tag="JJ" in="-2:pred" out="-1:mod|1:pobj">comfortable</W>
<W id="57" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="58" tag="DT" in="-1:nobj" out="">this</W>
<W id="59" tag="." in="-33:pnct" out="">.</W>
</s>
<s>
<W id="62" tag="WRB" in="22:mod" out="3:vobj">When</W>
<W id="63" tag="NNP" in="1:namef" out="">Andrew</W>
<W id="64" tag="NNP" in="1:subj" out="-1:namef">Morton</W>
<W id="65" tag="VB" in="-3:vobj" out="-1:subj|1:dobj|9:pred|14:mod|15:pnct">put</W>
<W id="66" tag="PRP$" in="-1:dobj" out="2:possd">his</W>
<W id="67" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="68" tag="NNP" in="-2:possd" out="-1:pnct|1:pnct|2:conj|5:pnct">Diana</W>
<W id="69" tag="&3a;" in="-1:pnct" out="">-</W>
<W id="70" tag="PRP$" in="-2:conj" out="1:mod|2:possd">Her</W>
<W id="71" tag="NNP" in="-1:mod" out="">True</W>
<W id="72" tag="NNP" in="-2:possd" out="">Story</W>
<W id="73" tag="&amp;quot;" in="-5:pnct" out="">"</W>
<W id="74" tag="IN" in="-9:pred" out="1:nobj">on</W>
<W id="75" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="76" tag="NN" in="-1:nobj" out="">street</W>
<W id="77" tag="CD" in="2:tobj" out="1:nobj">three</W>
<W id="78" tag="NNS" in="-1:nobj" out="">months</W>
<W id="79" tag="RB" in="-14:mod" out="-2:tobj">later</W>
<W id="80" tag="," in="-15:pnct" out="">,</W>
<W id="81" tag="DT" in="3:subj" out="1:nobj">the</W>
<W id="82" tag="NN" in="-1:nobj" out="">tone</W>
<W id="83" tag="RB" in="1:mod" out="">suddenly</W>
<W id="84" tag="VBD" in="" out="-22:mod|-3:subj|-1:mod|1:dobj|4:pnct">had</W>
<W id="85" tag="DT" in="-1:dobj" out="1:mod|2:nobj">a</W>
<W id="86" tag="JJ" in="-1:mod" out="">different</W>
<W id="87" tag="NN" in="-2:nobj" out="">ring</W>
<W id="88" tag="." in="-4:pnct" out="">.</W>
</s>
<s>
<W id="91" tag="IN" in="10:mod" out="1:nobj|3:pnct">In</W>
<W id="92" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="93" tag="NN" in="-1:nobj" out="">book</W>
<W id="94" tag="," in="-3:pnct" out="">,</W>
<W id="95" tag="VBD" in="5:mod" out="3:coord">named</W>
<W id="96" tag="RB" in="2:mod" out="1:aobj">as</W>
<W id="97" tag="RB" in="-1:aobj" out="">well</W>
<W id="98" tag="IN" in="-3:coord" out="-2:mod|1:conj">as</W>
<W id="99" tag="JJ" in="-1:conj" out="">anonymous</W>
<W id="100" tag="NNS" in="1:subj|6:[subj]" out="-5:mod">friends</W>
<W id="101" tag="VBD" in="34:qobj" out="-10:mod|-1:subj|1:dobj|4:coord|22:coord|32:pnct|33:pnct">made</W>
<W id="102" tag="NNS" in="-1:dobj" out="1:pobj">statements</W>
<W id="103" tag="IN" in="-1:pobj" out="1:nobj">about</W>
<W id="104" tag="NNP" in="-1:nobj" out="">Charles</W>
<W id="105" tag="CC" in="-4:coord" out="1:conj">and</W>
<W id="106" tag="VBN" in="-1:conj" out="-6:[subj]|1:dobj|2:vobj">made</W>
<W id="107" tag="PRP" in="-1:dobj|1:[subj]|3:[subj]" out="">him</W>
<W id="108" tag="VBP" in="-2:vobj" out="-1:[subj]|1:dobj">appear</W>
<W id="109" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="110" tag="VB" in="-1:vobj" out="-3:[subj]|1:pred">be</W>
<W id="111" tag="DT" in="-1:pred" out="1:mod|2:nobj|3:pnct|5:ref|7:rel">a</W>
<W id="112" tag="JJ" in="-1:mod" out="">tremendous</W>
<W id="113" tag="NN" in="-2:nobj" out="">fool</W>
<W id="114" tag="," in="-3:pnct" out="">,</W>
<W id="115" tag="IN" in="4:pobj|6:[pobj]" out="1:nobj">of</W>
<W id="116" tag="WP" in="-1:nobj|-5:ref" out="">whom</W>
<W id="117" tag="NNP" in="1:subj" out="">Diana</W>
<W id="118" tag="VBD" in="-7:rel" out="-1:subj|1:pred|4:pnct">was</W>
<W id="119" tag="JJ" in="-1:pred" out="-4:pobj|1:coord">sick</W>
<W id="120" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="121" tag="JJ" in="-1:conj" out="-6:[pobj]">tired</W>
<W id="122" tag="," in="-4:pnct" out="">,</W>
<W id="123" tag="CC" in="-22:coord" out="3:conj">and</W>
<W id="124" tag="IN" in="2:mod" out="">so</W>
<W id="125" tag="PRP" in="1:subj" out="5:vobj">it</W>
<W id="126" tag="VBD" in="-3:conj" out="-1:subj|-2:mod|1:pred">was</W>
<W id="127" tag="DT" in="-1:pred" out="1:nobj">the</W>
<W id="128" tag="NNP" in="-1:nobj" out="1:nobj">Buckingham</W>
<W id="129" tag="NNP" in="-1:nobj" out="">Mafia</W>
<W id="130" tag="VBD" in="-5:vobj" out="1:pobj">went</W>
<W id="131" tag="IN" in="-1:pobj" out="1:nobj">on</W>
<W id="132" tag="NN" in="-1:nobj" out="">counterattack</W>
<W id="133" tag="," in="-32:pnct" out="">,</W>
<W id="134" tag="&amp;quot;" in="-33:pnct" out="">"</W>
<W id="135" tag="VBZ" in="" out="-34:qobj|1:subj|10:pobj|12:pnct">says</W>
<W id="136" tag="DT" in="-1:subj" out="1:mod|2:nobj">a</W>
<W id="137" tag="NN" in="-1:mod" out="">close</W>
<W id="138" tag="NN" in="-2:nobj" out="1:pobj">friend</W>
<W id="139" tag="IN" in="-1:pobj" out="3:nobj">of</W>
<W id="140" tag="DT" in="3:mod" out="">both</W>
<W id="141" tag="NNP" in="1:title" out="">Prince</W>
<W id="142" tag="NNP" in="-3:nobj" out="-1:title|1:coord">Charles</W>
<W id="143" tag="CC" in="-1:coord" out="-3:mod|1:conj">and</W>
<W id="144" tag="NNP" in="-1:conj" out="">Diana</W>
<W id="145" tag="TO" in="-10:pobj" out="1:nobj">to</W>
<W id="146" tag="NNP" in="-1:nobj" out="">B.T</W>
<W id="147" tag="." in="-12:pnct" out="">.</W>
</s>
<s>
<W id="150" tag="NNP" in="1:mod" out="">PERSONAL</W>
<W id="151" tag="NNP" in="" out="-1:mod|1:list">LETTERS</W>
<W id="152" tag="NNP" in="-1:list" out="">STOLEN</W>
</s>
<s>
<W id="155" tag="NNP" in="2:mod" out="">New</W>
<W id="156" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="157" tag="NNS" in="17:subj" out="-2:mod|-1:pnct|1:pnct|2:mod">revelations</W>
<W id="158" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W id="159" tag="IN" in="-2:mod" out="1:nobj">around</W>
<W id="160" tag="NNP" in="-1:nobj" out="1:possd">Diana's</W>
<W id="161" tag="JJ" in="-1:possd" out="1:pobj">more-than-friendship</W>
<W id="162" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="163" tag="DT" in="-1:nobj" out="1:pobj|7:pnct|9:appa">another</W>
<W id="164" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="165" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="166" tag="NNS" in="-1:nobj" out="">friends</W>
<W id="167" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="168" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="169" tag="NN" in="-1:nobj" out="">house</W>
<W id="170" tag="," in="-7:pnct" out="">,</W>
<W id="171" tag="NNP" in="1:title" out="">Major</W>
<W id="172" tag="NNP" in="-9:appa" out="-1:title|1:pnct">Hewitt</W>
<W id="173" tag="," in="-1:pnct" out="">,</W>
<W id="174" tag="VBZ" in="" out="-17:subj|1:pred|6:pnct">is</W>
<W id="175" tag="DT" in="-1:pred" out="1:mod|3:nobj">the</W>
<W id="176" tag="JJS" in="-1:mod" out="">newest</W>
<W id="177" tag="&amp;quot;" in="1:pnct" out="">"</W>
<W id="178" tag="VBD" in="-3:nobj" out="-1:pnct|1:pnct">hit</W>
<W id="179" tag="&amp;quot;" in="-1:pnct" out="">"</W>
<W id="180" tag="." in="-6:pnct" out="">.</W>
</s>
<s>
<W id="183" tag="NNP" in="1:title" out="">Major</W>
<W id="184" tag="NNP" in="3:subj" out="-1:title|1:coord">Hewitt</W>
<W id="185" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="186" tag="NNP" in="-1:conj" out="">Diana</W>
<W id="187" tag="VB" in="" out="-3:subj|1:dobj|3:mod|4:pnct|5:mod|19:coord|41:pnct">know</W>
<W id="188" tag="DT" in="-1:dobj" out="1:nobj">each</W>
<W id="189" tag="JJ" in="-1:nobj" out="">other</W>
<W id="190" tag="RB" in="-3:mod" out="">well</W>
<W id="191" tag="," in="-4:pnct" out="">,</W>
<W id="192" tag="IN" in="-5:mod" out="1:pnct|7:vobj">because</W>
<W id="193" tag="," in="-1:pnct" out="">,</W>
<W id="194" tag="IN" in="5:mod" out="1:nobj|3:pnct">among</W>
<W id="195" tag="JJ" in="-1:nobj" out="1:nobj">other</W>
<W id="196" tag="NNS" in="-1:nobj" out="">things</W>
<W id="197" tag="," in="-3:pnct" out="">,</W>
<W id="198" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="199" tag="VBZ" in="-7:vobj" out="-1:subj|-5:mod|1:vobj">has</W>
<W id="200" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj">played</W>
<W id="201" tag="IN" in="-1:pobj" out="2:nobj">on</W>
<W id="202" tag="NNP" in="1:title" out="">Prince</W>
<W id="203" tag="NNP" in="-2:nobj" out="-1:title|2:possd">Charles'</W>
<W id="204" tag="NN" in="1:mod" out="">polo</W>
<W id="205" tag="NN" in="-2:possd" out="-1:mod">team</W>
<W id="206" tag="CC" in="-19:coord" out="1:pnct|17:conj">and</W>
<W id="207" tag="," in="-1:pnct" out="">,</W>
<W id="208" tag="WRB" in="15:mod" out="2:vobj">when</W>
<W id="209" tag="PRP" in="1:subj|2:[subj]" out="">he</W>
<W id="210" tag="VBD" in="-2:vobj" out="-1:subj|1:vobj|7:pnct">was</W>
<W id="211" tag="VBN" in="-1:vobj" out="-2:[subj]|1:lobj">sent</W>
<W id="212" tag="RB" in="-1:lobj" out="1:mod">down</W>
<W id="213" tag="TO" in="-1:mod" out="1:nobj">to</W>
<W id="214" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="215" tag="NNP" in="1:mod" out="">Gulf</W>
<W id="216" tag="NN" in="-2:nobj" out="-1:mod">war</W>
<W id="217" tag="," in="-7:pnct" out="">,</W>
<W id="218" tag="DT" in="3:mod" out="">both</W>
<W id="219" tag="NNP" in="1:title" out="">Prince</W>
<W id="220" tag="NNP" in="3:subj|5:[subj]" out="-1:title|1:coord">Charles</W>
<W id="221" tag="CC" in="-1:coord" out="-3:mod|1:conj">and</W>
<W id="222" tag="NNP" in="-1:conj" out="">Diana</W>
<W id="223" tag="VBD" in="-17:conj" out="-15:mod|-3:subj|1:dobj">promised</W>
<W id="224" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="225" tag="VB" in="-1:vobj" out="-5:[subj]|1:pobj">write</W>
<W id="226" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="227" tag="PRP" in="-1:nobj" out="">him</W>
<W id="228" tag="." in="-41:pnct" out="">.</W>
</s>
