<s>
<W id="1" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W id="2" tag="DT" in="2:subj|4:[subj]" out="1:nobj">The</W>
<W id="3" tag="NNS" in="-1:nobj" out="">personnel</W>
<W id="4" tag="VBD" in="" out="-3:pnct|-2:subj|1:dobj|8:coord|30:pnct#|31:pnct">had</W>
<W id="5" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="6" tag="VB" in="-1:vobj" out="-4:[subj]|1:dobj|2:mod">wake</W>
<W id="7" tag="PRP" in="-1:dobj" out="">him</W>
<W id="8" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="9" tag="DT" in="-1:nobj" out="2:nobj">the</W>
<W id="10" tag="NN" in="1:mod" out="">crew</W>
<W id="11" tag="NNS" in="-2:nobj" out="-1:mod">quarters</W>
<W id="12" tag="CC" in="-8:coord" out="13:conj">and</W>
<W id="13" tag="DT" in="12:subj" out="1:nobj|2:pnct|3:ref|5:rel">the</W>
<W id="14" tag="NN" in="-1:nobj" out="">train</W>
<W id="15" tag="," in="-2:pnct" out="">,</W>
<W id="16" tag="WDT" in="-3:ref|2:subj" out="">which</W>
<W id="17" tag="RB" in="1:mod" out="">later</W>
<W id="18" tag="VBD" in="-5:rel" out="-2:subj|-1:mod|1:pobj|4:mod|6:pnct">met</W>
<W id="19" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="20" tag="DT" in="-1:nobj" out="1:nobj">an</W>
<W id="21" tag="NN" in="-1:nobj" out="">accident</W>
<W id="22" tag="IN" in="-4:mod" out="1:nobj">in</W>
<W id="23" tag="JJ" in="-1:nobj" out="">Næstved</W>
<W id="24" tag="," in="-6:pnct" out="">,</W>
<W id="25" tag="VBD" in="-13:conj" out="-12:subj|1:lobj|5:mod">pulled</W>
<W id="26" tag="IN" in="-1:lobj" out="1:pobj">out</W>
<W id="27" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="28" tag="VBG" in="-1:nobj" out="1:name">Nykøbing</W>
<W id="29" tag="NNP" in="-1:name" out="">F.</W>
<W id="30" tag="IN" in="-5:mod" out="1:nobj">with</W>
<W id="31" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:possd">a</W>
<W id="32" tag="JJ" in="-1:mod" out="">few</W>
<W id="33" tag="NNS" in="-2:nobj" out="">minutes</W>
<W id="34" tag="JJ" in="-30:pnct#|-3:possd" out="">delay.</W>
<W id="35" tag="&amp;quot;" in="-31:pnct" out="">"</W>
</s>
<s>
<W id="38" tag="DT" in="5:subj" out="1:nobj">The</W>
<W id="39" tag="NN" in="-1:nobj" out="1:pobj">head</W>
<W id="40" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="41" tag="NN" in="-1:nobj" out="">traffic</W>
<W id="42" tag="RB" in="1:mod" out="">also</W>
<W id="43" tag="VBZ" in="" out="-1:mod|-5:subj|1:dobj|23:pnct">acknowledges</W>
<W id="44" tag="IN" in="-1:dobj" out="8:vobj">that</W>
<W id="45" tag="DT" in="7:subj" out="1:nobj|2:mod">the</W>
<W id="46" tag="NN" in="-1:nobj" out="">report</W>
<W id="47" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="48" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W id="49" tag="NN" in="1:mod" out="">accident</W>
<W id="50" tag="NN" in="1:mod" out="-1:mod">investigation</W>
<W id="51" tag="NN" in="-3:nobj" out="-1:mod">group</W>
<W id="52" tag="VBZ" in="-8:vobj" out="-7:subj|1:dobj">shows</W>
<W id="53" tag="IN" in="-1:dobj" out="9:vobj">that</W>
<W id="54" tag="DT" in="8:subj|9:[subj]" out="2:nobj|3:mod">the</W>
<W id="55" tag="NN" in="1:mod" out="">engine</W>
<W id="56" tag="NN" in="-2:nobj" out="-1:mod">driver</W>
<W id="57" tag="IN" in="-3:mod" out="1:nobj">on</W>
<W id="58" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W id="59" tag="JJ" in="1:mod" out="">toxic</W>
<W id="60" tag="NN" in="1:mod" out="-1:mod">waste</W>
<W id="61" tag="NN" in="-3:nobj" out="-1:mod">train</W>
<W id="62" tag="VBD" in="-9:vobj" out="-8:subj|1:vobj">was</W>
<W id="63" tag="VBG" in="-1:vobj" out="-9:[subj]|2:mod">moonlighting</W>
<W id="64" tag="JJ" in="1:mod" out="">big</W>
<W id="65" tag="NN" in="-2:mod" out="-1:mod">time</W>
<W id="66" tag="." in="-23:pnct" out="">.</W>
</s>
<s>
<W id="69" tag="&amp;quot;" in="3:pnct" out="">"</W>
<W id="70" tag="DT" in="2:subj" out="1:nobj">The</W>
<W id="71" tag="NN" in="-1:nobj" out="">moonlighting</W>
<W id="72" tag="VBD" in="43:qobj" out="-3:pnct|-2:subj|1:lobj|2:mod|12:pnct|13:coord|41:pnct|42:pnct">came</W>
<W id="73" tag="IN" in="-1:lobj" out="">out</W>
<W id="74" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="75" tag="NN" in="-1:nobj" out="1:pobj">connection</W>
<W id="76" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="77" tag="DT" in="-1:nobj" out="1:nobj|2:mod">the</W>
<W id="78" tag="NN" in="-1:nobj" out="">work</W>
<W id="79" tag="IN" in="-2:mod" out="1:nobj">of</W>
<W id="80" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W id="81" tag="NN" in="1:mod" out="">accident</W>
<W id="82" tag="NN" in="1:mod" out="-1:mod">investigation</W>
<W id="83" tag="NN" in="-3:nobj" out="-1:mod">group</W>
<W id="84" tag="," in="-12:pnct" out="">,</W>
<W id="85" tag="CC" in="-13:coord" out="2:conj">but</W>
<W id="86" tag="PRP" in="1:subj|3:[subj]" out="">I</W>
<W id="87" tag="VBP" in="-2:conj" out="-1:subj|1:dobj">want</W>
<W id="88" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="89" tag="VB" in="-1:vobj" out="-3:[subj]|1:dobj">emphasise</W>
<W id="90" tag="IN" in="-1:dobj" out="5:vobj">that</W>
<W id="91" tag="DT" in="4:subj|6:[subj]" out="3:nobj">the</W>
<W id="92" tag="NN" in="1:mod" out="">accident</W>
<W id="93" tag="NN" in="1:mod" out="-1:mod">investigation</W>
<W id="94" tag="NN" in="-3:nobj" out="-1:mod">group</W>
<W id="95" tag="VBZ" in="-5:vobj" out="-4:subj|1:mod|2:vobj">does</W>
<W id="96" tag="RB" in="-1:mod" out="">not</W>
<W id="97" tag="VB" in="-2:vobj" out="-6:[subj]|1:dobj">believe</W>
<W id="98" tag="IN" in="-1:dobj" out="5:vobj">that</W>
<W id="99" tag="DT" in="4:subj" out="2:nobj|3:possd">the</W>
<W id="100" tag="NN" in="1:mod" out="">engine</W>
<W id="101" tag="NNS" in="-2:nobj" out="-1:mod">driver's</W>
<W id="102" tag="NN" in="-3:possd" out="">moonlighting</W>
<W id="103" tag="VBD" in="-5:vobj" out="-4:subj|1:dobj">had</W>
<W id="104" tag="DT" in="-1:dobj" out="1:nobj|2:mod">any</W>
<W id="105" tag="NN" in="-1:nobj" out="2:pobj">affect</W>
<W id="106" tag="RB" in="-2:mod" out="">whatsoever</W>
<W id="107" tag="IN" in="-2:pobj" out="1:nobj">on</W>
<W id="108" tag="DT" in="-1:nobj" out="2:nobj|3:mod">the</W>
<W id="109" tag="NN" in="1:mod" out="">train</W>
<W id="110" tag="NN" in="-2:nobj" out="-1:mod">collision</W>
<W id="111" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="112" tag="JJ" in="-1:nobj" out="">Næstved</W>
<W id="113" tag="," in="-41:pnct" out="">,</W>
<W id="114" tag="&amp;quot;" in="-42:pnct" out="">"</W>
<W id="115" tag="VBZ" in="" out="-43:qobj|2:subj|3:pnct">says</W>
<W id="116" tag="NNP" in="1:namef" out="">Henrik</W>
<W id="117" tag="NNP" in="-2:subj" out="-1:namef">Nørgaard</W>
<W id="118" tag="." in="-3:pnct" out="">.</W>
</s>
<s>
<W id="121" tag="DT" in="" out="1:mod">THE</W>
<W id="122" tag="NNP" in="-1:mod" out="">GUILTY</W>
</s>
<s>
<W id="125" tag="NNP" in="19:subj" out="1:mod|2:possd|3:pnct|7:ref|16:rel">DSB's</W>
<W id="126" tag="JJ" in="-1:mod" out="">own</W>
<W id="127" tag="NNS" in="-2:possd" out="">investigations</W>
<W id="128" tag="," in="-3:pnct" out="">,</W>
<W id="129" tag="DT" in="12:dobj" out="1:nobj">the</W>
<W id="130" tag="NN" in="-1:nobj" out="1:pobj">result</W>
<W id="131" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="132" tag="WDT" in="-7:ref|-1:nobj" out="">which</W>
<W id="133" tag="NN" in="1:mod" out="">police</W>
<W id="134" tag="NN" in="3:title" out="-1:mod">commissioner</W>
<W id="135" tag="NNP" in="2:namef" out="1:namef">J.</W>
<W id="136" tag="NNP" in="-1:namef" out="">P.</W>
<W id="137" tag="NNP" in="4:subj" out="-3:title|-2:namef|1:pnct|2:list">Clausen</W>
<W id="138" tag="," in="-1:pnct" out="">,</W>
<W id="139" tag="JJ" in="-2:list" out="1:pnct">Næstved</W>
<W id="140" tag="," in="-1:pnct" out="">,</W>
<W id="141" tag="VBD" in="-16:rel" out="-4:subj|-12:dobj|1:mod|2:pnct">received</W>
<W id="142" tag="NN" in="-1:mod" out="">yesterday</W>
<W id="143" tag="," in="-2:pnct" out="">,</W>
<W id="144" tag="VBZ" in="" out="-19:subj|1:dobj|4:pobj|22:pnct">designates</W>
<W id="145" tag="DT" in="-1:dobj" out="2:nobj">the</W>
<W id="146" tag="NN" in="1:mod" out="">engine</W>
<W id="147" tag="NN" in="-2:nobj" out="-1:mod">driver</W>
<W id="148" tag="IN" in="-4:pobj" out="1:nobj">as</W>
<W id="149" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">the</W>
<W id="150" tag="JJ" in="-1:mod" out="">guilty</W>
<W id="151" tag="NN" in="-2:nobj" out="">party</W>
<W id="152" tag="IN" in="-3:mod" out="1:nobj">in</W>
<W id="153" tag="DT" in="-1:nobj" out="2:nobj|3:mod|6:mod">the</W>
<W id="154" tag="NN" in="1:mod" out="">train</W>
<W id="155" tag="NN" in="-2:nobj" out="-1:mod">collision</W>
<W id="156" tag="IN" in="-3:mod" out="1:nobj">at</W>
<W id="157" tag="NNP" in="-1:nobj" out="1:nobj">Næstved</W>
<W id="158" tag="NNP" in="-1:nobj" out="">Station</W>
<W id="159" tag="RB" in="-6:mod" out="1:mod">early</W>
<W id="160" tag="IN" in="-1:mod" out="1:nobj">on</W>
<W id="161" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="162" tag="NN" in="-1:nobj" out="1:pobj">morning</W>
<W id="163" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="164" tag="NNP" in="-1:nobj" out="1:mod">September</W>
<W id="165" tag="CD" in="-1:mod" out="">25</W>
<W id="166" tag="." in="-22:pnct" out="">.</W>
</s>
<s>
<W id="169" tag="DT" in="" out="1:nobj|2:pnct|3:ref|4:rel|22:pnct">A</W>
<W id="170" tag="NN" in="-1:nobj" out="">collision</W>
<W id="171" tag="," in="-2:pnct" out="">,</W>
<W id="172" tag="WDT" in="-3:ref|1:subj" out="">which</W>
<W id="173" tag="VBD" in="-4:rel" out="-1:subj|1:pred|6:pnct|7:mod">was</W>
<W id="174" tag="RB" in="-1:pred" out="1:pobj">close</W>
<W id="175" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="176" tag="VBG" in="-1:nobj" out="2:dobj">having</W>
<W id="177" tag="JJ" in="1:mod" out="">catastrophic</W>
<W id="178" tag="NNS" in="-2:dobj" out="-1:mod">consequences</W>
<W id="179" tag="," in="-6:pnct" out="">,</W>
<W id="180" tag="IN" in="-7:mod" out="8:vobj">because</W>
<W id="181" tag="DT" in="7:subj" out="1:nobj|2:mod">a</W>
<W id="182" tag="NN" in="-1:nobj" out="">tanker</W>
<W id="183" tag="IN" in="-2:mod" out="1:nobj">with</W>
<W id="184" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:appr">the</W>
<W id="185" tag="JJ" in="-1:mod" out="">toxic</W>
<W id="186" tag="NN" in="-2:nobj" out="">substance</W>
<W id="187" tag="NN" in="-3:appr" out="">acrylonitrile</W>
<W id="188" tag="VBD" in="-8:vobj" out="-7:subj|1:dobj">sprang</W>
<W id="189" tag="DT" in="-1:dobj" out="1:nobj">a</W>
<W id="190" tag="NN" in="-1:nobj" out="">leak</W>
<W id="191" tag="." in="-22:pnct" out="">.</W>
</s>
<s>
<W id="194" tag="DT" in="7:subj|9:[subj]|10:[subj]" out="2:nobj">All</W>
<W id="195" tag="NN" in="1:mod" out="">train</W>
<W id="196" tag="NN" in="-2:nobj" out="-1:mod|1:lobj">service</W>
<W id="197" tag="TO" in="-1:lobj" out="1:coord|3:nobj">to</W>
<W id="198" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="199" tag="IN" in="-1:conj" out="1:[nobj]">from</W>
<W id="200" tag="NN" in="-3:nobj|-1:[nobj]" out="">Næstved</W>
<W id="201" tag="VBD" in="" out="-7:subj|1:dobj|9:pnct|10:coord|20:pnct">had</W>
<W id="202" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="203" tag="VB" in="-1:vobj" out="-9:[subj]|1:vobj">be</W>
<W id="204" tag="VBN" in="-1:vobj" out="-10:[subj]|1:mod">discontinued</W>
<W id="205" tag="IN" in="-1:mod" out="1:nobj">in</W>
<W id="206" tag="DT" in="-1:nobj" out="1:mod|3:nobj">the</W>
<W id="207" tag="JJ" in="-1:mod" out="">early</W>
<W id="208" tag="NN" in="1:mod" out="">morning</W>
<W id="209" tag="NNS" in="-3:nobj" out="-1:mod">hours</W>
<W id="210" tag="," in="-9:pnct" out="">,</W>
<W id="211" tag="CC" in="-10:coord" out="6:conj">and</W>
<W id="212" tag="DT" in="5:subj" out="1:nobj">a</W>
<W id="213" tag="NN" in="-1:nobj" out="1:pobj">total</W>
<W id="214" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="215" tag="CD" in="-1:nobj" out="1:nobj">26</W>
<W id="216" tag="NNS" in="-1:nobj" out="">persons</W>
<W id="217" tag="VBD" in="-6:conj" out="-5:subj|1:lobj">went</W>
<W id="218" tag="TO" in="-1:lobj" out="1:nobj">to</W>
<W id="219" tag="DT" in="-1:nobj" out="1:nobj">the</W>
<W id="220" tag="NN" in="-1:nobj" out="">hospital</W>
<W id="221" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W id="224" tag="VBG" in="" out="1:nobj|31:pnct">Including</W>
<W id="225" tag="CD" in="-1:nobj" out="1:nobj|2:pnct|3:ref|4:rel">seven</W>
<W id="226" tag="NNS" in="-1:nobj" out="">policemen</W>
<W id="227" tag="," in="-2:pnct" out="">,</W>
<W id="228" tag="WP" in="-3:ref|1:subj" out="">who</W>
<W id="229" tag="VBD" in="-4:rel" out="-1:subj|1:pred|5:pnct|6:mod">were</W>
<W id="230" tag="IN" in="-1:pred" out="1:nobj">near</W>
<W id="231" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="232" tag="VBG" in="-1:mod" out="">leaking</W>
<W id="233" tag="NN" in="-2:nobj" out="">tanker</W>
<W id="234" tag="," in="-5:pnct" out="">,</W>
<W id="235" tag="IN" in="-6:mod" out="7:vobj">until</W>
<W id="236" tag="NN" in="1:mod" out="">fire</W>
<W id="237" tag="NN" in="3:title" out="-1:mod">commissioner</W>
<W id="238" tag="NNP" in="2:namef" out="1:namef">Svend</W>
<W id="239" tag="NNP" in="-1:namef" out="">Åge</W>
<W id="240" tag="NNP" in="2:subj" out="-3:title|-2:namef|1:pnct">Jensen</W>
<W id="241" tag="," in="-1:pnct" out="">,</W>
<W id="242" tag="VBN" in="-7:vobj" out="-2:subj|1:dobj">realised</W>
<W id="243" tag="IN" in="-1:dobj" out="2:vobj">that</W>
<W id="244" tag="PRP" in="1:subj" out="">it</W>
<W id="245" tag="VBD" in="-2:vobj" out="-1:subj|2:pred">was</W>
<W id="246" tag="JJ" in="1:mod" out="">hazardous</W>
<W id="247" tag="NN" in="-2:pred" out="-1:mod|1:mod">material</W>
<W id="248" tag="VBG" in="-1:mod" out="1:part|2:coord">seeping</W>
<W id="249" tag="IN" in="-1:part" out="">out</W>
<W id="250" tag="CC" in="-2:coord" out="1:conj">and</W>
<W id="251" tag="VBG" in="-1:conj" out="1:dobj">polluting</W>
<W id="252" tag="DT" in="-1:dobj" out="2:nobj">the</W>
<W id="253" tag="NN" in="1:mod" out="">railway</W>
<W id="254" tag="NN" in="-2:nobj" out="-1:mod">terrain</W>
<W id="255" tag="." in="-31:pnct" out="">.</W>
</s>
