<s>
<W id="1" tag="JJ" in="11:mod" out="1:pobj">Parallel</W>
<W id="2" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="3" tag="NNS" in="-1:nobj" out="1:pobj">preparations</W>
<W id="4" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W id="5" tag="JJ" in="1:mod" out="">next</W>
<W id="6" tag="NNP" in="-2:nobj" out="-1:mod|1:possd|4:pnct">year's</W>
<W id="7" tag="NNP" in="-1:possd" out="1:nobj">Le</W>
<W id="8" tag="NNPS" in="-1:nobj" out="1:nobj">Mans</W>
<W id="9" tag="NN" in="-1:nobj" out="">race</W>
<W id="10" tag="," in="-4:pnct" out="">,</W>
<W id="11" tag="NNP" in="1:subj|2:[subj]" out="">ACO</W>
<W id="12" tag="VBZ" in="" out="-11:mod|-1:subj|1:vobj|45:pnct">is</W>
<W id="13" tag="VBG" in="-1:vobj" out="-2:[subj]|1:dobj|6:mod">pursuing</W>
<W id="14" tag="DT" in="-1:dobj" out="2:nobj">a</W>
<W id="15" tag="NN" in="1:mod" out="">compensation</W>
<W id="16" tag="NN" in="-2:nobj" out="-1:mod|1:pobj">action</W>
<W id="17" tag="IN" in="-1:pobj" out="1:nobj">against</W>
<W id="18" tag="NNP" in="-1:nobj" out="">FIA</W>
<W id="19" tag="IN" in="-6:mod" out="1:nobj">for</W>
<W id="20" tag="DT" in="-1:nobj" out="1:nobj|2:ref|5:rel">the</W>
<W id="21" tag="NNS" in="-1:nobj" out="">losses</W>
<W id="22" tag="IN" in="-2:ref|4:dobj" out="">that</W>
<W id="23" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W id="24" tag="NN" in="-1:nobj" out="">club</W>
<W id="25" tag="VBZ" in="-5:rel" out="-2:subj|1:vobj">has</W>
<W id="26" tag="VBN" in="-1:vobj" out="-4:dobj|-3:[subj]|1:mod">suffered</W>
<W id="27" tag="IN" in="-1:mod" out="1:nobj">as</W>
<W id="28" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="29" tag="NN" in="-1:nobj" out="1:pobj">result</W>
<W id="30" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="31" tag="DT" in="-1:nobj" out="2:nobj|4:possd">the</W>
<W id="32" tag="NNS" in="1:mod" out="">sports</W>
<W id="33" tag="NN" in="-2:nobj" out="-1:mod|1:appr">commission</W>
<W id="34" tag="NNP" in="-1:appr" out="">FISA's</W>
<W id="35" tag="NN" in="-4:possd" out="1:dobj">failure</W>
<W id="36" tag="TO" in="-1:dobj" out="1:vobj">to</W>
<W id="37" tag="VB" in="-1:vobj" out="1:dobj">honour</W>
<W id="38" tag="VBZ" in="-1:dobj|3:[subj]" out="1:coord|3:mod">promises</W>
<W id="39" tag="CC" in="-1:coord" out="1:conj">and</W>
<W id="40" tag="NNS" in="-1:conj" out="">obligations</W>
<W id="41" tag="VBN" in="-3:mod" out="-3:[subj]|1:pobj|2:pobj">entered</W>
<W id="42" tag="IN" in="-1:pobj" out="">into</W>
<W id="43" tag="IN" in="-2:pobj" out="1:nobj">in</W>
<W id="44" tag="NN" in="-1:nobj" out="1:pobj">connection</W>
<W id="45" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="46" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:mod">a</W>
<W id="47" tag="JJ" in="-1:mod" out="">compulsory</W>
<W id="48" tag="NN" in="-2:nobj" out="">arrangement</W>
<W id="49" tag="IN" in="-3:mod" out="1:nobj">with</W>
<W id="50" tag="NN" in="-1:nobj" out="1:pobj">respect</W>
<W id="51" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="52" tag="DT" in="-1:nobj" out="1:mod|4:nobj">the</W>
<W id="53" tag="JJ" in="-1:mod" out="">classic</W>
<W id="54" tag="JJ" in="1:mod" out="">long</W>
<W id="55" tag="NN" in="1:mod" out="-1:mod">distance</W>
<W id="56" tag="NN" in="-4:nobj" out="-1:mod">race</W>
<W id="57" tag="." in="-45:pnct" out="">.</W>
</s>
<s>
<W id="60" tag="NNP" in="1:subj" out="">FISA</W>
<W id="61" tag="VBD" in="" out="-1:subj|1:dobj|2:pobj|7:mod|16:pnct">forced</W>
<W id="62" tag="NNP" in="-1:dobj" out="">ACO</W>
<W id="63" tag="IN" in="-2:pobj" out="1:nobj">into</W>
<W id="64" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="65" tag="NN" in="-1:nobj" out="1:pobj">number</W>
<W id="66" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="67" tag="NNS" in="-1:nobj" out="">changes</W>
<W id="68" tag="IN" in="-7:mod" out="1:nobj">against</W>
<W id="69" tag="VBG" in="-1:nobj" out="1:dobj">guaranteeing</W>
<W id="70" tag="DT" in="-1:dobj" out="1:mod|2:nobj|3:coord">a</W>
<W id="71" tag="JJ" in="-1:mod" out="">full</W>
<W id="72" tag="NN" in="-2:nobj" out="">field</W>
<W id="73" tag="CC" in="-3:coord" out="3:conj">and</W>
<W id="74" tag="JJ" in="2:mod" out="">massive</W>
<W id="75" tag="NNS" in="1:mod" out="">media</W>
<W id="76" tag="NN" in="-3:conj" out="-1:mod|-2:mod">coverage</W>
<W id="77" tag="." in="-16:pnct" out="">.</W>
</s>
<s>
<W id="80" tag="CC" in="" out="2:vobj|10:pnct">But</W>
<W id="81" tag="NN" in="1:subj|2:[subj]" out="">everything</W>
<W id="82" tag="VBZ" in="-2:vobj" out="-1:subj|1:vobj">has</W>
<W id="83" tag="VBN" in="-1:vobj" out="-2:[subj]|1:aobj|2:mod">gone</W>
<W id="84" tag="JJ" in="-1:aobj" out="">wrong</W>
<W id="85" tag="IN" in="-2:mod" out="1:nobj">in</W>
<W id="86" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="87" tag="JJ" in="-1:mod" out="">last</W>
<W id="88" tag="CD" in="-2:nobj" out="1:nobj">two</W>
<W id="89" tag="NNS" in="-1:nobj" out="">years</W>
<W id="90" tag="." in="-10:pnct" out="">.</W>
</s>
<s>
<W id="93" tag="DT" in="2:subj|3:[subj]" out="1:nobj">The</W>
<W id="94" tag="NN" in="-1:nobj" out="">field</W>
<W id="95" tag="VBZ" in="" out="-2:subj|1:vobj|5:pnct|9:conj|17:coord|74:pnct">has</W>
<W id="96" tag="VBN" in="-1:vobj" out="-3:[subj]|1:mod">shrunk</W>
<W id="97" tag="IN" in="-1:mod" out="1:nobj">by</W>
<W id="98" tag="CD" in="-1:nobj" out="1:nobj">50</W>
<W id="99" tag="NN" in="-1:nobj" out="">percent</W>
<W id="100" tag="," in="-5:pnct" out="">,</W>
<W id="101" tag="NNS" in="3:subj" out="1:pobj">thousands</W>
<W id="102" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="103" tag="NNS" in="-1:nobj" out="">spectators</W>
<W id="104" tag="VBD" in="-9:conj" out="-3:subj|1:pred|2:pnct|3:mod">stayed</W>
<W id="105" tag="RB" in="-1:pred" out="">away</W>
<W id="106" tag="," in="-2:pnct" out="">,</W>
<W id="107" tag="IN" in="-3:mod" out="3:vobj">because</W>
<W id="108" tag="DT" in="2:subj|3:[subj]" out="1:nobj">the</W>
<W id="109" tag="NN" in="-1:nobj" out="">excitement</W>
<W id="110" tag="VBD" in="-3:vobj" out="-2:subj|1:vobj">was</W>
<W id="111" tag="VBN" in="-1:vobj" out="-3:[subj]">gone</W>
<W id="112" tag="CC" in="-17:coord" out="1:pnct|16:conj">and</W>
<W id="113" tag="," in="-1:pnct" out="">,</W>
<W id="114" tag="IN" in="14:mod" out="1:nobj|4:pnct">for</W>
<W id="115" tag="DT" in="-1:nobj" out="1:mod|2:nobj">the</W>
<W id="116" tag="JJ" in="-1:mod" out="">same</W>
<W id="117" tag="NN" in="-2:nobj" out="">reason</W>
<W id="118" tag="," in="-4:pnct" out="">,</W>
<W id="119" tag="DT" in="9:subj" out="1:mod|2:nobj">a</W>
<W id="120" tag="JJ" in="-1:mod" out="">large</W>
<W id="121" tag="NN" in="-2:nobj" out="1:pobj">part</W>
<W id="122" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="123" tag="DT" in="-1:nobj" out="3:nobj">the</W>
<W id="124" tag="NNS" in="1:mod" out="">sports</W>
<W id="125" tag="VBP" in="1:mod" out="-1:mod">press</W>
<W id="126" tag="NN" in="-3:nobj" out="-1:mod">corps</W>
<W id="127" tag="RB" in="1:mod" out="">also</W>
<W id="128" tag="VBD" in="-16:conj" out="-14:mod|-9:subj|-1:mod|1:pred|2:pnct|3:mod">stayed</W>
<W id="129" tag="RB" in="-1:pred" out="">away</W>
<W id="130" tag="," in="-2:pnct" out="">,</W>
<W id="131" tag="RB" in="-3:mod" out="2:vobj">so</W>
<W id="132" tag="NNP" in="1:subj|2:[subj]" out="">ACO</W>
<W id="133" tag="VBD" in="-2:vobj" out="-1:subj|1:vobj">was</W>
<W id="134" tag="VBN" in="-1:vobj" out="-2:[subj]|1:pobj|11:mod">left</W>
<W id="135" tag="IN" in="-1:pobj" out="1:nobj">with</W>
<W id="136" tag="DT" in="-1:nobj" out="1:mod|2:nobj|3:coord|15:pnct|16:coord">a</W>
<W id="137" tag="JJ" in="-1:mod" out="">newly-renovated</W>
<W id="138" tag="NN" in="-2:nobj" out="">track</W>
<W id="139" tag="CC" in="-3:coord" out="1:conj">and</W>
<W id="140" tag="DT" in="-1:conj" out="2:mod|4:nobj">a</W>
<W id="141" tag="RB" in="1:mod" out="">completely</W>
<W id="142" tag="JJ" in="-2:mod" out="-1:mod">new</W>
<W id="143" tag="NN" in="1:mod" out="">pit</W>
<W id="144" tag="NN" in="-4:nobj" out="-1:mod">facility</W>
<W id="145" tag="IN" in="-11:mod" out="1:nobj">after</W>
<W id="146" tag="DT" in="-1:nobj" out="1:nobj">an</W>
<W id="147" tag="NN" in="-1:nobj" out="1:pobj">investment</W>
<W id="148" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="149" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="150" tag="CD" in="-1:nobj" out="">million</W>
<W id="151" tag="&3a;" in="-15:pnct" out="">-</W>
<W id="152" tag="CC" in="-16:coord" out="1:conj">and</W>
<W id="153" tag="DT" in="-1:conj" out="1:mod|2:nobj|4:mod">a</W>
<W id="154" tag="JJ" in="-1:mod" out="">financial</W>
<W id="155" tag="NN" in="-2:nobj" out="">debt</W>
<W id="156" tag="RB" in="1:mod" out="3:nobj">so</W>
<W id="157" tag="JJ" in="-4:mod" out="-1:mod|1:pnct">large</W>
<W id="158" tag="," in="-1:pnct" out="">,</W>
<W id="159" tag="IN" in="-3:nobj" out="2:vobj">that</W>
<W id="160" tag="PRP" in="1:subj" out="">they</W>
<W id="161" tag="VBD" in="-2:vobj" out="-1:subj|1:dobj|2:pobj|5:mod">schlepped</W>
<W id="162" tag="NNP" in="-1:dobj" out="">FIA</W>
<W id="163" tag="IN" in="-2:pobj" out="1:nobj">before</W>
<W id="164" tag="DT" in="-1:nobj" out="1:nobj">a</W>
<W id="165" tag="NN" in="-1:nobj" out="">court</W>
<W id="166" tag="TO" in="-5:mod" out="1:vobj">to</W>
<W id="167" tag="VB" in="-1:vobj" out="1:dobj">get</W>
<W id="168" tag="NN" in="-1:dobj" out="">compensation</W>
<W id="169" tag="." in="-74:pnct" out="">.</W>
</s>
<s>
<W id="172" tag="JJ" in="1:mod" out="">Next</W>
<W id="173" tag="NN" in="6:mod" out="-1:mod|1:pnct">year</W>
<W id="174" tag="," in="-1:pnct" out="">,</W>
<W id="175" tag="DT" in="4:subj|5:[subj]" out="1:nobj">the</W>
<W id="176" tag="NNP" in="-1:nobj" out="1:nobj">Le</W>
<W id="177" tag="NNPS" in="-1:nobj" out="1:nobj">Mans</W>
<W id="178" tag="NN" in="-1:nobj" out="">race</W>
<W id="179" tag="MD" in="" out="-6:mod|-4:subj|1:vobj|12:coord|20:pnct">will</W>
<W id="180" tag="VB" in="-1:vobj" out="-5:[subj]|1:pred">be</W>
<W id="181" tag="JJ" in="-1:pred" out="1:pobj">open</W>
<W id="182" tag="IN" in="-1:pobj" out="1:nobj">for</W>
<W id="183" tag="CD" in="-1:nobj" out="1:nobj|4:mod">four</W>
<W id="184" tag="NNS" in="-1:nobj" out="1:pobj">types</W>
<W id="185" tag="IN" in="-1:pobj" out="1:nobj">of</W>
<W id="186" tag="NNS" in="-1:nobj" out="">cars</W>
<W id="187" tag="IN" in="-4:mod" out="1:nobj">with</W>
<W id="188" tag="DT" in="-1:nobj" out="2:nobj">no</W>
<W id="189" tag="NN" in="1:mod" out="">gasoline</W>
<W id="190" tag="NNS" in="-2:nobj" out="-1:mod">restrictions</W>
<W id="191" tag="CC" in="-12:coord" out="2:conj">and</W>
<W id="192" tag="PRP" in="1:subj" out="">it</W>
<W id="193" tag="MD" in="-2:conj" out="-1:subj|1:vobj">will</W>
<W id="194" tag="VB" in="-1:vobj" out="2:pred|4:mod">be</W>
<W id="195" tag="JJ" in="1:mod" out="">full</W>
<W id="196" tag="NN" in="-2:pred" out="-1:mod|1:mod">speed</W>
<W id="197" tag="RB" in="-1:mod" out="">ahead</W>
<W id="198" tag="RB" in="-4:mod" out="">again</W>
<W id="199" tag="." in="-20:pnct" out="">.</W>
</s>
<s>
<W id="202" tag="IN" in="4:mod" out="1:nobj|2:pnct">On</W>
<W id="203" tag="NNP" in="-1:nobj" out="">Tuesday</W>
<W id="204" tag="," in="-2:pnct" out="">,</W>
<W id="205" tag="NNP" in="1:subj" out="">ACO</W>
<W id="206" tag="MD" in="" out="-4:mod|-1:subj|1:vobj|14:pnct">will</W>
<W id="207" tag="VB" in="-1:vobj" out="1:avobj">open</W>
<W id="208" tag="RP" in="-1:avobj" out="1:pobj">up</W>
<W id="209" tag="TO" in="-1:pobj" out="1:nobj">to</W>
<W id="210" tag="NNS" in="-1:nobj" out="1:pobj">entries</W>
<W id="211" tag="IN" in="-1:pobj" out="2:nobj">for</W>
<W id="212" tag="JJ" in="1:mod" out="">next</W>
<W id="213" tag="NNS" in="-2:nobj" out="-1:mod|1:possd|2:mod">year's</W>
<W id="214" tag="NN" in="-1:possd" out="">race</W>
<W id="215" tag="IN" in="-2:mod" out="1:nobj|2:pred">with</W>
<W id="216" tag="NNS" in="-1:nobj" out="">cars</W>
<W id="217" tag="IN" in="-2:pred" out="1:nobj">in</W>
<W id="218" tag="CD" in="-1:nobj" out="1:nobj">four</W>
<W id="219" tag="NNS" in="-1:nobj" out="">categories</W>
<W id="220" tag="&3a;" in="-14:pnct" out="">:</W>
</s>
