fixall:
	./remove_weird_xml_entities.pl #r1873
	./quote_xml_attributes_in_dag.pl # r1874
	./replace_unescaped_special_chars_by_entities.pl # 1877
	./add_root_element.pl # r1877
	./resolve_mismatchin_open_end_tags.pl # r1877
	./add_closing_tags.pl # r1878