#!/bin/bash

# Options
export lang=de
export bindir=~/svn/cdt/trunk/tools/
export tagger=/home/matthias/research/statmt/treetagger/cmd/tree-tagger-german
export EOSREGEXP="[^	]*	SENT	.*"

# Check arguments
export file=$1
if [ -z "$file" ] ; then
	echo "Usage: de2tag <file>"
	echo "The file must be utf8 encoded"
	exit 0
fi

# Source txt2tag command
bash $bindir/txt2tag

