#!/bin/bash

files="0235 0593 0596 0620 0647 0781 0783 0800 0866 0960 1014 1038 1043 1337 1420 1428"

lang=da
userspecs="iørn:da iørn:it morten:da morten:it lotte:da lotte:es"
for userspec in `echo $userspecs` ; do 
	user=`echo $userspec | awk -F: '{ print $1 }'`;
	lang=`echo $userspec | awk -F: '{ print $2 }'`;
	echo $user ":" $lang
	echo -e "\n# Added discourse tasks on `date`\n" >> todo/$user.auto;
	for id in `echo $files` ; do 
		src=`ls $lang/$id-$lang*$user*.tag 2>/dev/null | grep -v disc`
		if [ -z "$src" ] ; then
			src=`ls $lang/$id-$lang*.tag | grep -v auto | grep -v tagged | grep -v disc | head -1`
			if [ -z "$src" ] ; then
				src=`ls $lang/$id-$lang-auto.tag`
			fi
		fi
		dest=$lang/$id-$lang-disc-$user.tag
		if [ ! -f $dest ] ; then
			svn cp $src $dest
		fi
		echo "[ ] $dest" >> todo/$user.auto
	done
done

