#!/bin/bash

# Goto cdt directory
if [ -d ~/cdt ] ; then
	cd ~/cdt
fi
if [ -d ~/cdt-all ] ; then
	cd ~/cdt-all
fi

# Update svn archive
echo "Downloading files from CDT repository"
svn update --username `cat ~/.svnuser` --password `cat ~/.svnpasswd`

# Find user name
name=`cat ~/.cdtname`
if [ -z "$name" ] ; then
	echo "Cannot find your name. Please contact Matthias"
	exit 1
fi

# Add new tasks to user's task list
if ! cd ~/cdt/todo ; then
	echo "Cannot find cdt/todo directory. Please contact Matthias."
	exit 1
fi

if [ ! -f ~/cdt/todo/.$name ] ; then
	touch ~/cdt/todo/.$name
fi

if ! cmp .$name $name.auto ; then
	echo "You have received new tasks"
	diff .$name $name.auto | grep '^>' | sed -e 's/> //g' 
	diff .$name $name.auto | grep '^>' | sed -e 's/> //g' >> $name
	cp $name.auto .$name
fi

echo "You are using version 2008-08-01 of the update program"

