#!/bin/bash 

# Find name and exit if missing
echo > ~/.script
name=`cat ~/.cdtname` 
if [ -z "$name" ] ; then
	echo "Please provide your first name with the command 'setname your-name'"
	echo "using small letters only, then try the 'opentask' command again."
	exit 1
fi

# Check that todo file exists
todo=~/cdt/todo/$name
if [ ! -f $todo ] ; then
	echo "No todo-file for $name: please check your first name and set"
	echo "it again with 'setname' if wrong, otherwise contact Matthias."
	exit 1
fi

# Find first incomplete task
file=`grep '\[ \]' $todo | head -1 | sed -e 's/\[.\] //g'`
dir=`echo $file | sed -e 's/\/.*$//g'`
fname=`echo $file | sed -e 's/^.*\///g'`
if [ -z "$fname" ] ; then
	echo "No more tasks: please ask Matthias to give you more tasks"
	echo > ~/.script
	exit 1
fi

# Reset script file
mkdir -p /home/cdt/backup
echo "save /home/cdt/backup/backup-`date +%F-%H:%M:%S`" > ~/.script
echo "close -all" >> ~/.script
echo "cd /home/cdt/cdt/$dir" >> ~/.script

# Process alignment task 
if echo $fname | grep '.atag' ; then
	# Alignment task
	echo "Alignment task"

	# Try to create file if non-existent
	if [ ! -f /home/cdt/cdt/$dir/$fname ] ; then
		cd /home/cdt/cdt/$dir
		rfname=`echo $fname | sed -e 's/-[^-]*$//g'`
		if [ -f $rfname-auto.atag ] ; then
			echo "Copying $fname from $rfname-auto.atag"
			svn cp $rfname-auto.atag $fname
		fi
	fi

	# Load file if it exists
	if [ -f /home/cdt/cdt/$dir/$fname ] ; then
		echo "cd /home/cdt/cdt/$dir"
		echo "load $fname" >> ~/.script
		echo "autoalign -default *.atag" >> ~/.script
		echo "# Stop autoaligner with \"autoalign -off\"" >> ~/.script
	else
		echo "ERROR: cannot open/create file $file"
		echo "Please contact Matthias if you think this is an error"
	fi
fi

# Process dependency annotation task
if echo $fname | grep '\.tag' > /dev/null ; then
	# Dependency annotation task
	echo "Dependency annotation task: $fname"
	rfname=`echo $fname | sed -e 's/^\([^-]*-[^-]*\)-.*$/\1/g'`

	# Try to create file if non-existent
	if [ ! -f /home/cdt/cdt/$dir/$fname ] ; then
		# Create file from auto tag-file
		if [ -f /home/cdt/cdt/$dir/$rfname-auto.tag ] ; then
			echo "Copying $fname from $rfname-auto.tag" 
			svn cp /home/cdt/cdt/$dir/$rfname-auto.tag /home/cdt/cdt/$dir/$fname
			echo "tag source: $rfname-auto.tag"
		fi
	fi

	# Aparse the file if it contains no dependency edges
	if [ -f /home/cdt/cdt/$dir/$fname ] ; then
		if egrep 'in="[^"]' $fname | egrep 'out="[^"]' ; then
			echo "File contains dependency edges"
		else 
			# Identify id and language
			id=`echo $rfname | awk -F'-' '{ print $1 }'`
			lang=`echo $rfname | awk -F'-' '{ print $2 }'`

			# Find atag-file
			atagfiles=`ls /home/cdt/cdt/*-$lang/$id-*-$lang*.atag`

			# Prefer final atag file with ending $lang.atag
			atag=`echo $atagfiles | grep "$lang.atag" | head -1`
			method="final"

			# Otherwise prefer user's own atag file
			if [ -z "$atag" ] ; then
				atag=`echo $atagfiles | grep "$lang-$user.atag" | head -1`
				method="user's own"
			fi

			# Otherwise prefer the largest other atag file
			if [ -z "$atag" ] ; then
				atag=`du -s /home/cdt/cdt/*-$lang/$id-*-$lang*.atag \
					| sort -nr | head -1 | awk '{ print $2 }'`
				method="largest match"
			fi

			# Find atag-file and atag dir
			atagdir=`echo $atag | sed -e 's/\/[^\/]*$//g'`
			atagname=`echo $atag | sed -e 's/^.*\/\([^\]*\)$/\1/g'`
			echo "atag-file: $atag [$method]"
			echo "atag-dir : $atagdir"

			# Aparse file
			if [ -f /home/cdt/cdt/$lang/$id-$lang-auto.tag ] ; then
				echo "cd $atagdir" >> ~/.script
				echo "load ../$lang/$id-$lang-auto.tag" >> ~/.script
				echo "aparse $atagname" >> ~/.script
				echo "cd /home/cdt/cdt/$dir" >> ~/.script
				#echo "save $fname" >> ~/.script
				echo "close -all" >> ~/.script
			fi
		fi
	fi

	# Load file if it exists
	if [ -f /home/cdt/cdt/$dir/$fname ] ; then
		echo "cd /home/cdt/cdt/$dir"
		echo "load $fname" >> ~/.script
		echo "del -off" >> ~/.script
	else
		echo "ERROR: cannot find file $file"
	fi
fi
	
