#!/bin/bash

echo "DTAG commit version 2008-08-04"

cd "$HOME"

name=`cat .cdtname`
if [ -d cdt ] ; then
	cd cdt
fi
if [ -d cdt-all ] ; then
	cd cdt-all/trunk
fi

# Update repository
if [ -f tools/dtag-update ] ; then
	sh tools/dtag-update
fi

# Add all .tag or .atag files in figs directory
svn add figs/*.{tag,atag}

if [ ! -z "$name" ] ; then
	# Resolve all conflicts: we assume that the local copy of any file that
	# contains the user's name is the correct one
	files=`find . -name "*$name*" | grep -v '.svn' | egrep '(\.tag|\.atag)$'`
	if [ ! -z "$files" ] ; then
		svn resolve -R --accept working todo/$name $files
	fi

	# Add new .tag or .atag files to svn repository
	files=`svn status | grep "[-]$name" | awk '{ print $2 }' | grep -v .svn | egrep '(\.tag|\.atag)$'`
	if [ ! -z "$files" ] ; then
		echo -e "ADDING FILES\n$files"
		svn add $files
	fi
else
	echo "Please contact Matthias: Cannot find your name!"
fi

# Upload files
echo "Uploading files to CDT repository"
pwd
echo svn ci -m "Automatic update by $name" --username `cat "$HOME"/.svnuser` --password `cat "$HOME"/.svnpasswd`
svn ci -m "Automatic update by $name" --username `cat "$HOME"/.svnuser` --password `cat "$HOME"/.svnpasswd`



