#!/bin/bash

echo > ~/.script
name=`cat ~/.cdtname`
if [ -z "$name" ] ; then
    echo "Please provide your first name with the command 'setname your-name'"
    echo "using small letters only, then try the 'closetask' command again."
    exit 0
fi

# Find first task
todo=~/cdt/todo/$name
if [ -f $todo ] ; then
    file=`grep -v '[*]' $todo | head -1 | sed -e 's/^.*\/\([^/]*\)/\1/g'`
	if [ ! -z "$file" ] ; then
		sed -e "s/^\[ \]\(.*$file\)$/\[*\]\1/g" $todo > /tmp/x
		mv /tmp/x $todo
	fi
	if [ -z "$file" ] ; then
		echo "No more tasks: please ask Matthias to give you more tasks"
	else 
		echo "Closing task $file"
	fi
fi

