#!/bin/bash

# Options
export lang=it
export bindir=~/cdt/tools/
export tagger=$bindir/tree-tagger-italian
export EOSREGEXP="[^	]*	SENT	.*"

# Check arguments
export file=$1
if [ -z "$file" ] ; then
	echo "Usage: it2tag <file>"
	echo "The file must be utf8 encoded"
	exit 0
fi

# Source txt2tag command
bash $bindir/txt2tag

