#!/usr/bin/perl

binmode(STDIN, ":latin1");
binmode(STDOUT, ":latin1");

# Convert file
while (my $line = <>) {
	if ($line =~ /^<[^<]*>$/) {
		print $line;
	} else {
		$line =~ s/</\&lt;/g;
		$line =~ s/>/\&gt;/g;
		my ($input, $tag, $lemma) = split(/[\t\n]/, $line);
		$tag =~ s/\"/\&quot;/g;
		$lemma =~ s/\"/\&quot;/g;
		print "<W msd=\"$tag\" lemma=\"$lemma\">$input</W>\n";
	}
}

