	S	﻿
<W lemma="СОТР" msd="S" romanized="SOTR" sdeps="" in="" out="2:conj">СОТР</W>
<W lemma="=" msd="PUNCT" romanized="=" sdeps="coord" in="1:coord" out="">=</W>
<W lemma="АГГ" msd="S" romanized="АGG" sdeps="conj" in="-2:conj" out="-1:coord">АГГ</W>
<W lemma="ИСТОЧНИК" msd="S" romanized="ISTOCNIK" sdeps="conj" in="" out="2:conj">ИСТОЧНИК</W>
<W lemma="=" msd="PUNCT" romanized="=" sdeps="coord" in="1:coord" out="">=</W>
<W lemma="РИТСАУС" msd="S" romanized="RITSАUS" sdeps="conj" in="-2:conj" out="-1:coord">РИТСАУС</W>
<W lemma="ПЕРЕДАТЬ" msd="S" romanized="PEREDАT'" sdeps="" in="" out="2:conj">ПЕРЕДАТЬ</W>
<W lemma="=" msd="PUNCT" romanized="=" sdeps="coord" in="1:coord" out="">=</W>
<W lemma="@card@" msd="NUM" romanized="16.00" sdeps="conj" in="-2:conj" out="-1:coord">16.00</W>
<W lemma="ДИКТОР" msd="S" romanized="DIKTOR" sdeps="conj" in="" out="3:conj">ДИКТОР</W>
<W lemma="=" msd="PUNCT" romanized="=" sdeps="coord" in="2:coord" out="1:err">=</W>
<W lemma="=" msd="PUNCT" romanized="=" sdeps="err" in="-1:err" out="">=</W>
<W lemma="ер" msd="S" romanized="ER" sdeps="conj" in="-3:conj" out="-2:coord">ЕР</W>
<W lemma="два" msd="NUM" romanized="Dva" sdeps="nobj" in="18:subj" out="1:mod|2:attr|3:nobj|4:possr|7:pnct|12:appa|17:pnct">Два</W>
<W lemma="осужденный" msd="S" romanized="osuzdennyh" sdeps="mod" in="-1:mod" out="">осужденных</W>
<W lemma="главный" msd="A" romanized="glavnyh" sdeps="nobj" in="-2:attr" out="">главных</W>
<W lemma="руководитель" msd="S" romanized="rukovoditela" sdeps="nobj" in="-3:nobj" out="">руководителя</W>
<W lemma="банка" msd="S" romanized="BАNKА" sdeps="nobj" in="-4:possr" out="2:mod">БАНКА</W>
<W lemma="@card@" msd="NUM" romanized="6" sdeps="mod" in="1:mod" out="">6</W>
<W lemma="ИЮЛЯ" msd="S" romanized="IULA" sdeps="nobj" in="-2:mod" out="-1:mod">ИЮЛЯ</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-7:pnct" out="">,</W>
<W lemma="председатель" msd="S" romanized="predsedatel'" sdeps="title" in="4:title" out="1:nobj">председатель</W>
<W lemma="правление" msd="S" romanized="pravlenia" sdeps="title" in="-1:nobj" out="">правления</W>
<W lemma="Нильс" msd="S" romanized="Nil's" sdeps="namef" in="2:namef" out="1:namef">Нильс</W>
<W lemma="Йохан" msd="S" romanized="Johan" sdeps="namef" in="-1:namef" out="">Йохан</W>
<W lemma="Леер" msd="S" romanized="Leer" sdeps="appa" in="-12:appa" out="-2:namef|-4:title|4:conj">Леер</W>
<W lemma="и" msd="CONJ" romanized="i" sdeps="coord" in="3:coord" out="">и</W>
<W lemma="директор" msd="S" romanized="direktor" sdeps="title" in="2:title" out="">директор</W>
<W lemma="джон" msd="S" romanized="Dzon" sdeps="namef" in="1:namef" out="">Джон</W>
<W lemma="Ольсдорф" msd="S" romanized="Ol'sdorf" sdeps="conj" in="-4:conj" out="-2:title|-1:namef|-3:coord">Ольсдорф</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-17:pnct" out="">,</W>
<W lemma="подать" msd="V" romanized="podali" sdeps="" in="" out="-18:subj|1:mod|3:pobj|5:dobj|12:pnct">подали</W>
<W lemma="сразу" msd="ADV" romanized="srazu" sdeps="mod&7c;nobj" in="-1:mod" out="1:mod">сразу</W>
<W lemma="же" msd="PART" romanized="ze" sdeps="mod&7c;nobj" in="-1:mod" out="">же</W>
<W lemma="на" msd="PR" romanized="na" sdeps="" in="-3:pobj" out="1:nobj">на</W>
<W lemma="апелляция" msd="S" romanized="apellaciu" sdeps="" in="-1:nobj" out="5:mod">апелляцию</W>
<W lemma="решение" msd="S" romanized="resenie" sdeps="dobj" in="-5:dobj" out="3:possr">решение</W>
<W lemma="Копенгагенского" msd="A" romanized="Kopengagenskogo" sdeps="nobj" in="1:mod" out="">Копенгагенского</W>
<W lemma="городской" msd="A" romanized="gorodskogo" sdeps="possd" in="1:mod" out="-1:mod">городского</W>
<W lemma="судно" msd="S" romanized="suda" sdeps="possd" in="-3:possr" out="-1:mod">суда</W>
<W lemma="с" msd="PR" romanized="s" sdeps="mod" in="-5:mod" out="1:nobj">с</W>
<W lemma="требование" msd="S" romanized="trebovaniem" sdeps="nobj" in="-1:nobj" out="1:nobj">требованием</W>
<W lemma="оправдание" msd="S" romanized="opravdania" sdeps="nobj" in="-1:nobj" out="">оправдания</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-12:pnct" out="">.</W>
<W lemma="обвинение" msd="S" romanized="Obvinenie" sdeps="[subj]&7c;subj" in="2:subj" out="">Обвинение</W>
<W lemma="также" msd="PART" romanized="takze" sdeps="mod" in="1:mod" out="">также</W>
<W lemma="оставлять" msd="V" romanized="ostavlaet" sdeps="vobj" in="" out="-2:subj|-1:mod|1:mod|3:dobj|5:pnct">оставляет</W>
<W lemma="за" msd="PR" romanized="za" sdeps="vobj" in="-1:mod" out="1:nobj">за</W>
<W lemma="себя" msd="S-PRO" romanized="soboj" sdeps="vobj" in="-1:nobj" out="">собой</W>
<W lemma="возможность" msd="S" romanized="vozmoznost'" sdeps="nobj" in="-3:dobj" out="1:nobj">возможность</W>
<W lemma="обжалование" msd="S" romanized="obzalovania" sdeps="nobj" in="-1:nobj" out="">обжалования</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-5:pnct" out="">.</W>
<W lemma="председатель" msd="S" romanized="Predsedatel'" sdeps="subj" in="2:subj" out="1:possr">Председатель</W>
<W lemma="правление" msd="S" romanized="pravlenia" sdeps="subj" in="-1:possr" out="">правления</W>
<W lemma="получить" msd="V" romanized="polucil" sdeps="" in="" out="-2:subj|1:dobj|34:pnct">получил</W>
<W lemma="полтора" msd="NUM" romanized="poltora" sdeps="mod" in="-1:dobj" out="1:nobj|2:mod|4:conj">полтора</W>
<W lemma="год" msd="S" romanized="goda" sdeps="dobj" in="-1:nobj" out="">года</W>
<W lemma="тюрьма" msd="S" romanized="tur'my" sdeps="possd" in="-2:mod" out="7:pobj">тюрьмы</W>
<W lemma="и" msd="CONJ" romanized="i" sdeps="coord" in="1:coord" out="">и</W>
<W lemma="штраф" msd="S" romanized="straf" sdeps="nobj" in="-4:conj" out="-1:coord|1:pobj|5:[pobj]">штраф</W>
<W lemma="в" msd="PR" romanized="v" sdeps="pobj" in="-1:pobj" out="1:nobj">в</W>
<W lemma="размер" msd="S" romanized="razmere" sdeps="pobj" in="-1:nobj" out="1:nobj">размере</W>
<W lemma="миллион" msd="S" romanized="milliona" sdeps="nobj" in="-1:nobj" out="1:nobj">миллиона</W>
<W lemma="крона" msd="S" romanized="kron" sdeps="nobj" in="-1:nobj" out="">крон</W>
<W lemma="за" msd="PR" romanized="za" sdeps="mod" in="-7:pobj|-5:[pobj]" out="1:nobj">за</W>
<W lemma="злоупотребление" msd="S" romanized="zloupotreblenie" sdeps="nobj" in="-1:nobj" out="1:nobj|2:pnct|3:conj|9:pnct|10:conj|17:conj">злоупотребление</W>
<W lemma="доверие" msd="S" romanized="doveriem" sdeps="nobj" in="-1:nobj" out="">доверием</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-2:pnct" out="">,</W>
<W lemma="афёры" msd="S" romanized="af ry" sdeps="conj" in="-3:conj" out="1:pobj|5:mod">афёры</W>
<W lemma="с" msd="PR" romanized="s" sdeps="conj" in="-1:pobj" out="1:nobj">с</W>
<W lemma="налог" msd="S" romanized="nalogami" sdeps="conj" in="-1:nobj" out="">налогами</W>
<W lemma="особо" msd="ADV" romanized="osobo" sdeps="mod" in="1:mod" out="">особо</W>
<W lemma="грубый" msd="A" romanized="grubogo" sdeps="mod" in="1:mod" out="-1:mod">грубого</W>
<W lemma="характер" msd="S" romanized="haraktera" sdeps="nobj" in="-5:mod" out="-1:mod">характера</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="appa" in="-9:pnct" out="">,</W>
<W lemma="нарушение" msd="S" romanized="narusenie" sdeps="conj" in="-10:conj" out="1:nobj">нарушение</W>
<W lemma="закон" msd="S" romanized="zakona" sdeps="nobj" in="-1:nobj" out="2:nobj">закона</W>
<W lemma="акционерный" msd="A" romanized="akcionernogo" sdeps="nobj" in="1:mod" out="">акционерного</W>
<W lemma="общество" msd="S" romanized="obsestva" sdeps="nobj" in="-2:nobj" out="-1:mod">общества</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="" out="">,</W>
<W lemma="а" msd="CONJ" romanized="a" sdeps="coord" in="2:coord" out="1:mod">а</W>
<W lemma="также" msd="PART" romanized="takze" sdeps="coord" in="-1:mod" out="">также</W>
<W lemma="нарушение" msd="S" romanized="narusenie" sdeps="nobj" in="-17:conj" out="-2:coord|1:nobj">нарушение</W>
<W lemma="закон" msd="S" romanized="zakona" sdeps="conj&7c;coord" in="-1:nobj" out="1:pobj">закона</W>
<W lemma="о" msd="PR" romanized="o" sdeps="conj&7c;coord" in="-1:pobj" out="1:nobj">о</W>
<W lemma="банка" msd="S" romanized="bankah" sdeps="conj&7c;coord" in="-1:nobj" out="2:conj">банках</W>
<W lemma="и" msd="CONJ" romanized="i" sdeps="conj&7c;coord" in="1:coord" out="">и</W>
<W lemma="сберкассах" msd="S" romanized="sberkassah" sdeps="conj&7c;coord" in="-2:conj" out="-1:coord">сберкассах</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-34:pnct" out="">.</W>
<W lemma="директор" msd="S" romanized="Direktor" sdeps="possd" in="4:subj" out="1:possr|3:appr">Директор</W>
<W lemma="банка" msd="S" romanized="banka" sdeps="subj" in="-1:possr" out="">банка</W>
<W lemma="джон" msd="S" romanized="Dzon" sdeps="namef" in="1:namef" out="">Джон</W>
<W lemma="Ольсдорф" msd="S" romanized="Ol'sdorf" sdeps="appr" in="-3:appr" out="-1:namef">Ольсдорф</W>
<W lemma="получить" msd="V" romanized="polucil" sdeps="" in="" out="-4:subj|1:dobj|11:pnct">получил</W>
<W lemma="@card@" msd="NUM" romanized="6" sdeps="dobj" in="-1:dobj" out="1:nobj|2:mod|4:conj">6</W>
<W lemma="месяц" msd="S" romanized="mesacev" sdeps="nobj" in="-1:nobj" out="">месяцев</W>
<W lemma="тюрьма" msd="S" romanized="tur'my" sdeps="possd" in="-2:mod" out="">тюрьмы</W>
<W lemma="и" msd="CONJ" romanized="i" sdeps="coord" in="1:coord" out="">и</W>
<W lemma="штраф" msd="S" romanized="straf" sdeps="nobj" in="-4:conj" out="-1:coord|1:pobj">штраф</W>
<W lemma="в" msd="PR" romanized="v" sdeps="nobj&7c;pnct" in="-1:pobj" out="1:nobj">в</W>
<W lemma="размер" msd="S" romanized="razmere" sdeps="nobj&7c;pnct" in="-1:nobj" out="3:nobj">размере</W>
<W lemma="@card@" msd="NUM" romanized="90" sdeps="err" in="2:mod" out="1:+">90</W>
<W lemma="@card@" msd="NUM" romanized="000" sdeps="err" in="-1:+" out="">000</W>
<W lemma="крона" msd="S" romanized="kron" sdeps="nobj" in="-3:nobj" out="-2:mod">крон</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-11:pnct" out="">.</W>
<W lemma="оба" msd="NUM" romanized="Oba" sdeps="[subj]&7c;subj" in="1:subj" out="">Оба</W>
<W lemma="обвинять" msd="V" romanized="obvinautsa" sdeps="vobj" in="" out="-1:subj|1:pobj|17:pnct">обвиняются</W>
<W lemma="в" msd="PR" romanized="v" sdeps="pobj" in="-1:pobj" out="1:nobj">в</W>
<W lemma="нанесение" msd="S" romanized="nanesenii" sdeps="nobj&7c;vobj" in="-1:nobj" out="1:iobj|2:dobj|9:mod">нанесении</W>
<W lemma="банка" msd="S" romanized="banku" sdeps="iobj" in="-1:iobj" out="">банку</W>
<W lemma="ущерб" msd="S" romanized="userba" sdeps="nobj" in="-2:dobj" out="1:mod">ущерба</W>
<W lemma="в" msd="PR" romanized="v" sdeps="pobj" in="-1:mod" out="1:nobj">в</W>
<W lemma="размер" msd="S" romanized="razmere" sdeps="pobj" in="-1:nobj" out="3:nobj">размере</W>
<W lemma="приблизительно" msd="ADV" romanized="priblizitel'no" sdeps="mod" in="1:attr" out="">приблизительно</W>
<W lemma="@card@" msd="NUM" romanized="60" sdeps="numm" in="1:numm" out="-1:attr">60</W>
<W lemma="миллион" msd="NUM" romanized="millionov" sdeps="nobj" in="-3:nobj" out="-1:numm|1:mod">миллионов</W>
<W lemma="крона" msd="S" romanized="kron" sdeps="nobj" in="-1:mod" out="">крон</W>
<W lemma="из-за" msd="PR" romanized="iz-za" sdeps="mod" in="-9:mod" out="4:nobj">из-за</W>
<W lemma="безответственный" msd="A" romanized="bezotvetstvennogo" sdeps="mod" in="3:mod" out="2:conj">безответственного</W>
<W lemma="и" msd="CONJ" romanized="i" sdeps="coord" in="1:coord" out="">и</W>
<W lemma="противозаконный" msd="A" romanized="protivozakonnogo" sdeps="conj" in="-2:conj" out="-1:coord">противозаконного</W>
<W lemma="предоставление" msd="S" romanized="predostavlenia" sdeps="nobj" in="-4:nobj" out="-3:mod|1:mod">предоставления</W>
<W lemma="заем" msd="S" romanized="zajmov" sdeps="nobj" in="-1:mod" out="">займов</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-17:pnct" out="">.</W>
<W lemma="кроме" msd="PR" romanized="Krome" sdeps="mod" in="5:mod" out="1:nobj|2:pnct">Кроме</W>
<W lemma="то" msd="S-PRO" romanized="togo" sdeps="mod" in="-1:nobj" out="">того</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="coord" in="-2:pnct" out="">,</W>
<W lemma="они" msd="S-PRO" romanized="oni" sdeps="[subj]&7c;subj" in="2:subj" out="">они</W>
<W lemma="не" msd="PART" romanized="ne" sdeps="vobj" in="1:mod" out="">не</W>
<W lemma="доплатили" msd="V" romanized="doplatili" sdeps="vobj" in="" out="-5:mod|-2:subj|-1:mod|2:iobj|4:dobj|6:pnct">доплатили</W>
<W lemma="налоговый" msd="A" romanized="nalogovomu" sdeps="iobj" in="1:mod" out="">налоговому</W>
<W lemma="ведомство" msd="S" romanized="vedomstvu" sdeps="iobj" in="-2:iobj" out="-1:mod">ведомству</W>
<W lemma="@card@" msd="NUM" romanized="3,5" sdeps="numm" in="1:numm" out="">3,5</W>
<W lemma="миллион" msd="S" romanized="milliona" sdeps="dobj" in="-4:dobj" out="-1:numm|1:nobj">миллиона</W>
<W lemma="крона" msd="S" romanized="kron" sdeps="nobj" in="-1:nobj" out="">крон</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-6:pnct" out="">.</W>
<W lemma="два" msd="NUM" romanized="Dva" sdeps="[subj]&7c;subj" in="4:subj" out="1:mod|2:nobj">Два</W>
<W lemma="рядовой" msd="S" romanized="radovyh" sdeps="mod" in="-1:mod" out="">рядовых</W>
<W lemma="член" msd="S" romanized="clena" sdeps="nobj" in="-2:nobj" out="1:possr">члена</W>
<W lemma="правление" msd="S" romanized="pravlenia" sdeps="nobj" in="-1:possr" out="">правления</W>
<W lemma="быть" msd="V" romanized="byli" sdeps="" in="" out="-4:subj|2:pnct|1:preds">были</W>
<W lemma="оправдать" msd="V" romanized="opravdany" sdeps="vobj" in="-1:preds" out="">оправданы</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-2:pnct" out="">.</W>
<W lemma="однако" msd="ADV" romanized="Odnako" sdeps="mod" in="9:mod" out="1:pnct">Однако</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="possd" in="-1:pnct" out="">,</W>
<W lemma="судья" msd="S" romanized="sud'a" sdeps="title" in="7:subj|8:[subj]" out="2:possr|5:appr">судья</W>
<W lemma="городской" msd="A" romanized="gorodskogo" sdeps="title" in="1:mod" out="">городского</W>
<W lemma="судно" msd="S" romanized="suda" sdeps="title" in="-2:possr" out="-1:mod">суда</W>
<W lemma="Нильс" msd="S" romanized="Nil's" sdeps="namef" in="2:namef" out="1:namef">Нильс</W>
<W lemma="эрика" msd="S" romanized="Erik" sdeps="namef" in="-1:namef" out="">Эрик</W>
<W lemma="Енсен" msd="S" romanized="Ensen" sdeps="subj" in="-5:appr" out="-2:namef">Енсен</W>
<W lemma="не" msd="PART" romanized="ne" sdeps="dobj&7c;mod&7c;pobj" in="1:mod" out="">не</W>
<W lemma="стать" msd="V" romanized="stal" sdeps="dobj&7c;mod&7c;pobj" in="" out="-9:mod|-7:subj|-1:mod|1:vobj|14:pnct">стал</W>
<W lemma="скрывать" msd="V" romanized="skryvat'" sdeps="dobj&7c;mod&7c;pobj" in="-1:vobj" out="-8:[subj]|1:pnct|2:dobj">скрывать</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-1:pnct" out="">,</W>
<W lemma="что" msd="CONJ" romanized="cto" sdeps="nobj" in="-2:dobj" out="10:vobj">что</W>
<W lemma="с" msd="PR" romanized="s" sdeps="mod" in="3:mod" out="2:nobj">с</W>
<W lemma="чистый" msd="A" romanized="cistoj" sdeps="mod" in="1:mod" out="">чистой</W>
<W lemma="совесть" msd="S" romanized="sovest'u" sdeps="nobj" in="-2:nobj" out="-1:mod">совестью</W>
<W lemma="отправиться" msd="V" romanized="otpravit'sa" sdeps="vobj" in="6:vobj" out="-3:mod|1:lobj">отправиться</W>
<W lemma="домой" msd="ADV" romanized="domoj" sdeps="lobj" in="-1:lobj" out="">домой</W>
<W lemma="член" msd="S" romanized="cleny" sdeps="[subj]&7c;subj" in="4:subj" out="1:possr">члены</W>
<W lemma="правление" msd="S" romanized="pravlenia" sdeps="[subj]&7c;subj" in="-1:possr" out="">правления</W>
<W lemma="никак" msd="ADV-PRO" romanized="nikak" sdeps="mod" in="1:attr" out="">никак</W>
<W lemma="не" msd="PART" romanized="ne" sdeps="mod" in="1:mod" out="-1:attr">не</W>
<W lemma="смочь" msd="V" romanized="smogut" sdeps="vobj" in="-10:vobj" out="-6:vobj|-4:subj|-1:mod">смогут</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-14:pnct" out="">.</W>
<W lemma="оправдание" msd="S" romanized="Opravdanie" sdeps="subj" in="6:subj" out="">Оправдание</W>
<W lemma="ни" msd="PART" romanized="ni" sdeps="mod&7c;nobj" in="2:mod" out="">ни</W>
<W lemma="в" msd="PR" romanized="v" sdeps="mod&7c;nobj" in="4:mod" out="2:nobj">в</W>
<W lemma="кой" msd="A-PRO" romanized="koej" sdeps="mod&7c;nobj" in="1:mod" out="-2:mod">коей</W>
<W lemma="мера" msd="S" romanized="mere" sdeps="mod&7c;nobj" in="-2:nobj" out="-1:mod">мере</W>
<W lemma="не" msd="PART" romanized="ne" sdeps="mod" in="1:mod" out="">не</W>
<W lemma="являться" msd="V" romanized="avlaetsa" sdeps="qobj" in="19:qobj" out="-6:subj|-1:mod|-4:mod|13:conj|18:pnct|1:preds">является</W>
<W lemma="признание" msd="S" romanized="priznaniem" sdeps="nobj&7c;pobj" in="-1:preds" out="1:nobj">признанием</W>
<W lemma="тот" msd="A-PRO" romanized="togo" sdeps="nobj" in="-1:nobj" out="1:pnct|2:nobj">того</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-1:pnct" out="">,</W>
<W lemma="что" msd="CONJ" romanized="cto" sdeps="nobj" in="-2:nobj" out="2:vobj">что</W>
<W lemma="они" msd="S-PRO" romanized="oni" sdeps="[subj]&7c;subj" in="1:subj" out="">они</W>
<W lemma="выполнять" msd="V" romanized="vypolnali" sdeps="vobj" in="-2:vobj" out="-1:subj|2:dobj|5:mod|6:pnct">выполняли</W>
<W lemma="свой" msd="A-PRO" romanized="svou" sdeps="dobj" in="1:mod" out="">свою</W>
<W lemma="работа" msd="S" romanized="rabotu" sdeps="possd" in="-2:dobj" out="-1:mod|1:mod">работу</W>
<W lemma="в" msd="PR" romanized="v" sdeps="possd" in="-1:mod" out="1:nobj">в</W>
<W lemma="правление" msd="S" romanized="pravlenii" sdeps="possd" in="-1:nobj" out="">правлении</W>
<W lemma="образцовопоказательно" msd="A" romanized="obrazcovopokazatel'no" sdeps="mod&7c;nobj" in="-5:mod" out="">образцовопоказательно</W>
<W lemma="–" msd="PUNCT" romanized="–" sdeps="pnct" in="-6:pnct" out="">–</W>
<W lemma="это" msd="S-PRO" romanized="eto" sdeps="subj" in="-13:conj" out="3:&lt;pred&gt;|4:pnct">это</W>
<W lemma="отнюдь" msd="ADV" romanized="otnud'" sdeps="mod&7c;part&7c;pred" in="1:attr" out="">отнюдь</W>
<W lemma="не" msd="PART" romanized="ne" sdeps="mod&7c;part&7c;pred" in="1:mod" out="-1:attr">не</W>
<W lemma="так" msd="ADV-PRO" romanized="tak" sdeps="mod&7c;part&7c;pred" in="-3:&lt;pred&gt;" out="-1:mod">так</W>
<W lemma="," msd="PUNCT" romanized="," sdeps="pnct" in="-4:pnct" out="">,</W>
<W lemma="-" msd="PUNCT" romanized="-" sdeps="" in="-18:pnct" out="">-</W>
<W lemma="добавить" msd="V" romanized="dobavil" sdeps="" in="" out="-19:qobj|1:subj|2:mod|9:pnct">добавил</W>
<W lemma="судья" msd="S" romanized="sud'a" sdeps="subj" in="-1:subj" out="">судья</W>
<W lemma="к" msd="PR" romanized="k" sdeps="mod" in="-2:mod" out="2:nobj">к</W>
<W lemma="свой" msd="A-PRO" romanized="svoim" sdeps="nobj" in="1:mod" out="">своим</W>
<W lemma="замечание" msd="S" romanized="zamecaniam" sdeps="possd" in="-2:nobj" out="-1:mod|1:mod">замечаниям</W>
<W lemma="по" msd="PR" romanized="po" sdeps="pobj" in="-1:mod" out="1:nobj">по</W>
<W lemma="повод" msd="S" romanized="povodu" sdeps="pobj" in="-1:nobj" out="2:nobj">поводу</W>
<W lemma="судебный" msd="A" romanized="sudebnogo" sdeps="nobj" in="1:mod" out="">судебного</W>
<W lemma="заключение" msd="S" romanized="zaklucenia" sdeps="nobj" in="-2:nobj" out="-1:mod">заключения</W>
<W lemma="." msd="SENT" romanized="." sdeps="pnct" in="-9:pnct" out="">.</W>
